### ISSUE TITLE
Potential flaw with bonding process

### ISSUE THREAD

**Issue by kravenoff42** [bisq-network/bisq#1001]
Hello, 

Forgive me if I am over stepping, but I just heard about this technology on the Changelog Podcast, and am very interested in what is being doen here, I haven't started digging around much yet but one issue that occured to me listening to the desciption of the bonding scheme.
It sounds like more senior contributors that have proven there worth, get more influence within the system, and can affect change more easily.
I just wanted to mention the scenario where a contributor that been a valuable member who understands the mission having a change of heart or decides to abuse their position of influence.

Not sure what the fix would be, but I thought I would mention it in case it hadn't been considered.

thank you,
Jon

**Comment by ManfredKarrer** [comment]
Thanks for your input. Any bond can be confiscated if the role responsibility was violated or abused. The bond reflects the potential max. damage a role holder can cause. We try to avoid as far as possible that roles can create a lot of damage but there are some which cannot be decentralized like holding the domain or GitHub accounts. The contributor who has earned so much BSQ will be likely also be a major stakeholder and has several incentives to play good. Any damage will not only risk his bond but the value of his BSQ (investment). The history of his past contribution reflected in the BSQ he earned represents a kind of reputation which in general works sufficiently good, but I know reputation does not provide strong security. So the bonds should add more security. Also confiscated bonds get burned or depending if there are direct victims goes to the victims. That will help to "un-do" a part of the damage.

**Comment by cbeams** [comment]
Closing this out. Thanks for the input @kravenoff42, and glad you enjoyed the podcast! FYI, this sort of conversation is probably better for the bisq-network/dao repository, Bisq forum, or [bisq-contrib mailing list](https://lists.bisq.network/listinfo/bisq-contrib). Issues here in bisq-network/exchange are stuff specific to the Bisq exchange desktop client.
