### ISSUE TITLE
Once set, the "Use custom Bitcoin network peers" setting cannot be un-set

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1002]
This came up while testing our new Bitcoin full nodes. I'm using v0.5.3.

## Repro steps

1. Go to `Settings->Network info->Bitcoin network`. Notice that "Connected peers" lists a number of peers
2. Enter a valid Bitcoin full node address into the "Use custom Bitcoin network peers" field and hit enter. When prompted to restart, do so.
3. Once you've restarted, go back to `Settings->Network info` and notice that the only entry in "Connected peers" is the Bitcoin full node you entered in the last step. Everything is working as expected so far.
4. Now clear the "Use custom Bitcoin network peers" field and hit enter. Again, restart Bisq as instructed.
5. Once you've restarted, go back to the settings page, and notice that "Connected peers" still lists only the one Bitcoin node.

The expected behavior is that when the "Use custom Bitcoin network peers" field is cleared, that Bisq will re-discover / re-connect to an unspecified set of ~8-12 Bitcoin network peers. The actual behavior is that it never does this, and the user is "stuck" with having to specify their peers explicitly.

**Comment by ManfredKarrer** [comment]
At step 4 I did not get the restart popup (deleting the custom entry). That was a bug I fixed that. Not sure how you triggered the popup. 
Maybe you closed very fast so that the state change was not persisted. There is a delay of about 300 ms (to avoid too much disk I/O).
Just tested again and could not reproduce your case.

**Comment by cbeams** [comment]
No matter what I do, I am unable to get my client back into a state where it connects to a larger set of bitcoin nodes. I'm stuck with the following:

![image](https://user-images.githubusercontent.com/301810/32854141-f2019706-ca3d-11e7-9a45-135206746379.png)

Note also that if I check the "Use Tor for Bitcoin network" checkbox, a dialog appears asking me to shut down to apply the change:

![image](https://user-images.githubusercontent.com/301810/32854177-0efc4860-ca3e-11e7-8353-ae191cf0df5f.png)

At which point, I click "Apply and shut down". When I then re-open Bisq and go back to this settings screen, the box is still unchecked.

Is there a way (even manually) to reset network settings to their defaults?

**Comment by ManfredKarrer** [comment]
Ah that is because you have a localhost node running. Then it connects by default to that, which is the best option anyway. But should be communicated better in the UI. Will try to fix that.

**Comment by cbeams** [comment]
Closing as a non-issue. I've verified that if I shut down my local bitcoin node, Bisq does indeed reconnect to other peers.
