### ISSUE TITLE
Provide .torrent with each new release

### ISSUE THREAD

**Issue by meeDamian** [bisq-network/bisq#1013]
As discussed [here](https://twitter.com/bisq_network/status/930603160166690816?s=09), it would be great to have `.torrent` as an alternative way to download a new release.

![image](https://user-images.githubusercontent.com/301810/32851268-d4818afa-ca34-11e7-9a72-a2a60c8e2b2d.png)

**Comment by ManfredKarrer** [comment]
Not sure if I will have time to add that for this release. The preferred way is anyway to download via the in-app downloader, that way the sig check is done and the pub key is double checked (in app and on GH). A torrent might add a bit more risk if people would start to deploy alternative torrents and dont do sig checks (most don't do it).

**Comment by cbeams** [comment]
I updated the description with a screenshot of the Twitter thread that led to this issue, and I sent [this tweet](https://twitter.com/bisq_network/status/930825787611205633) asking for further feedback about this idea. It would be good to hear from other Bisq users whether this is something they would use, and to see how concerned we should be about "rogue seeds". Obviously the Bitcoin Core team isn't too worried about it, but would still be good to talk / think through the risks and benefits here.

**Comment by fresheneesz** [comment]
Its taking over 10 minutes for me to download this file, and the first time i tried the download shut down prematurely and I had to start over. A torrent would be very helpful.

**Comment by tarbib** [comment]
Hello +1 very much needed for me also. 5th time I tried to downlaod the last release today... Torrent are much more reliable. Thx
