### ISSUE TITLE
Better monitoring for support infrastructure

### ISSUE THREAD

**Issue by mrosseel** [bisq-network/bisq#1014]
Since bisq is becoming fully decentralized, it's important that nodes with an impact on Bisq functionality such as seednodes, pricenodes, bitcoin nodes, ... are monitored.
 
This ticket will track the implementation of a simple monitoring solution which aims to monitor the following:
* clearnet bitcoin nodes are working (does handshake)
* onion bitcoin nodes are working
* pricenodes are replying with fees and prices
* seednodes have an open port 8000

Possible extras:
* checking correct version and height of bitcoin nodes

Currently out of scope, but can be added:
 * The bisq.network website
 * The Discourse forum software at forum.bisq.io
 * The Mailman service running at lists.bisq.network
 * The Bisq markets webapp and API at market.bisq.io

Coding will be a mix of Java, Python (for bitcoin node handshakes) and shell scripts.
Alerts will be pushed to a Slack webhook.

**Comment by mrosseel** [comment]
work is ongoing in this repo: https://github.com/mrosseel/bisq-uptime
Test version is running in #monitoring in slack

**Comment by sqrrm** [comment]
I'm now running this myself, easy setup, nice work.

Being able to run the monitoring per user might help with the monitoring channel being a bit verbose. I would then use my private bisq-uptime to listen to my own services for issues and check on the global ones in the monitoring slack when I want to check the general status of services.
- Running it privately like this I'm only interested in my own nodes though and so it would be nice to be able to configure which nodes to check on.
- Having email as an option for notifications would be great when running it like a private monitoring tool, although slack works.
- The table is rather verbose on mobile, shorter strings would help with readability.

**Comment by mrosseel** [comment]
Additional features now planned:
- have separate slack URL's for price node, seed node, btc node
- make nodes configurable so we can share the nodeconfig between Bisq and Bisq-monitor
- replace the heartbeat message with a http call by a regular uptime service (the overview will dissapear)

**Comment by ripcurlx** [comment]
@mrosseel Should this issue be closed as it will be superseded by https://github.com/bisq-network/proposals/issues/62?

**Comment by mrosseel** [comment]
yes this can be closed, no further work is planned on this code.
