### ISSUE TITLE
Minor focus and re-calculation issue in "Set amount and price" block

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1017]
**Steps to reproduce:**
1. Create Offer to buy BTC
2. Set 0.25 BTC as amount, tap to "Distance in % from market price", don't set a value (will default to 0)

**Expected result:**
Amount in EUR to spend is calculated and pre-filled

**Actual result:**
Filed stays empty and is only updated if % distance is changed manually.

![Create Offer](https://user-images.githubusercontent.com/170962/32946538-35938424-cb98-11e7-83bd-81766e7c7a96.png)

**Comment by ManfredKarrer** [comment]
Actually the 0% should not be filled. I think it can be dangerous to pre-fill price and later users complain that they did not set the price themselves.

**Comment by ripcurlx** [comment]
Closing as complete within 0.9.0.
