### ISSUE TITLE
Wrong textfield alert highlighting in Trade Wallet balance.

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1018]
**Steps to reproduce:**
1. Create offer to buy BTC
2. Fund your offer from external wallet

**Expected result:**
Trade wallet balance is updated by funded amount and button for reviewing is enabled.

**Actual result:**
Trade wallet balance is updated, but textfield is highlighted with the red error indication border.

![Create Offer](https://user-images.githubusercontent.com/170962/32946918-c38e9434-cb99-11e7-9f50-392bfde1ca53.png)

**Comment by ManfredKarrer** [comment]
I could not reproduce it but I have seen it in the past some times. Not sure which edge case produce the issues. If u find a way to reproduce please let me know.

**Comment by ripcurlx** [comment]
I also tried to reproduce it a couple of times, but without success. I also looked into the code and the only way how I was able to cause the notFundedEffect was by transfering too little money to fund the offer. I have the feeling that this might be some render issue unrelated to the actual component state. Will look into it in more detail, when I'm able to reproduce it again.
