### ISSUE TITLE
New changing trading limit is not communicated properly within client and on website

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1019]
At the moment the only place, where the current limit with a new account (0.25 BTC) is shown is in the Account/National currency  accounts section.
![National Currency Accounts](https://user-images.githubusercontent.com/170962/32947293-793c0824-cb9b-11e7-9507-b912d52907d1.png)
When creating a new offer and you hit the limit, only the limit is shown without any information if this is a fixed limit or will change over time.
![Create Offer](https://user-images.githubusercontent.com/170962/32947327-a1211046-cb9b-11e7-922f-3326a05e81f8.png)
On the website we are talking at the moment of a limit of one BTC. We should update the website and add additional information within the client regarding this imposed limits.

**Comment by ManfredKarrer** [comment]
Upps, yes I forgot to update the FAQ... will do now...
Yes I agree in the app it is also not very well communicated. Maybe a different input method (slider) might help?

**Comment by ManfredKarrer** [comment]
FAQ updated.

**Comment by ripcurlx** [comment]
Just saw that the we don't write about the initial trade limit and after who many days it is lifted. Maybe we should extend the FAQs with this information and also add it to create offer dialog as well.

**Comment by ripcurlx** [comment]
This was fixed within information popups already. Closing as complete.
