### ISSUE TITLE
Remove libdohj dependency

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1021]
Now that dogecoin has been removed as a base currency in 0.6.0, I believe we should now be able to remove our dependency on libdohj as well. If this is correct, I'll create another issue to remove the libdohj fork from our GitHub org once the code / build system updates are complete.

**Comment by mrosseel** [comment]
Libdohj is also used for Litecoin support, so it can't be removed.

**Comment by cbeams** [comment]
Got it, thanks. Closing as invalid.
