### ISSUE TITLE
External notification service

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1022]
We would like to have a notification system so that users get informed about important event from their Bisq app in other channels like a mobile app, email or others.

This has to be implemented in a way which protects the users privacy.
An idea discussed with @cbeams  and @ripcurlx is to use a http server running as hidden service where users send the notification events from the Bisq app and that service is set up to use notification infrastructure (Google, Apple push notifications, email,... ) to push the notification to the user. The user has to set up their "account" with that service where they connect a UUID with a mobile number (and/or email). A private key for encryption will be needed as well (pairing of GPG private key between Desktop app and mobile app can be done with a QR code). The Bisq app sends then a message on defined events like "open offer got taken" to the service and the the service sends the notification to the mobile number/email matching the UUID. 
Those messages are encrypted.
We could allow optional plain text, but the main message has to be encrypted so the service cannot derive information out of it. To use plain text (headline like "offer taken") would has the benefit that the mobile device can display that in lock screen. The encrypted message can only be decrypted once the user opens up the mobile Bisq app. The plain text feature would be optional.

The UUID and GPG private key should be decoupled from any other app data (onion address, encryption or signing key) to allow that the user can re-assign any time their UUID and key with a new mobile number or email address.

The registration of the UUID/mobile nr./email should be done from the Bisq app to benefit from the privacy provided by the hidden service.

For email the service operates an email service to send out the message to the registered email address matching the UUID. The user need to have GPG if he uses encrypted messages, otherwise he would only receive the optional plain text message.

The operators of the service is a BSQ contributor and get paid for his service. The role is bonded with BSQ. The can and should be multiple services and the message passing should circulate so that one service never receives all messages of a user (with plaintext there is a privacy issue).

Maybe we can find a solution to also provide privacy with the optional plain text messages? Any idea how to achieve that would be very welcome!

Tasks:
- Define and fine-tune concept, specially in regards to privacy
- Research notification infrastructure and requirements for Apple and Google.
- Research alternative notification infrastructure
- Research email notification
- Research implementation technology (native app or write once run everywhere frameworks)
- Build service node
- Build basic prototype for Android and iOS. 
 
This app could be the seed for a more sophisticated mobile app which adds trading features over time. So it should be taken into account this future perspective when selecting solutions.

**Comment by citkane** [comment]
Hi,

With reference to this and:
https://github.com/mrosseel/bisq-proposals/blob/notification-proposal/bisq3.adoc

I would like to propose a high level architectural alternative based on some existing software here: http://twister.net.co/

Twister functions as a decentralised, p2p "Twitter" using a blockchain. I tried it a few years ago and, technically, it worked a treat.

This may provide some ideas as to how "in-app" notifications could work more persistently and "recover" if a user closes the app or their network connection corrupts.

I will offer my opinion on "out of app" notifications. Personally, I will be comfortable with notifications using email or https://www.signal.org/. This is based on my own, subjective feelings of trust and paranoia.

I cannot attest to the technical feasibility of connecting to "Signal", but for the matter of email I think that this could be done without a centralised approach. Given that it is possible (?) for the Bisq client app to connect to a smtp server outside of the onion network, the approach could be simply to make it easy for users to purchase any number of independent smtp services in-app using Btc. People who already have a smtp service could just enter their own details. The challenged would be to find email providers who will sell services for Btc and then to automate the purchase and in-app setup. (One click setup for users)

This way there is no centralised point of potential failure. Every user has an independent contract with any number of email providers. The problem will arise that only one contractual party has availed of external notification, is offline with their Bisq client, and expects notifications to arrive. There could be two approaches to this scenario:

1. Before agreeing to a trade, the app shows clearly that there is no two party facility for external notifications. This could serve as an incentive for users to enable a service as they will be less attractive trading partners.
2. Using the "Twister" typology, the connection details of smtp (or other) is encrypted into the communication blockchain. The trade contract includes the clause that a trading partner will be allowed to use your connection anonymously. 

I apologise in advance if these ideas are technically naive. I am an architect (academically of the bricks and concrete kind) who has strayed into the world of web development and UX/UI. I became interested in blockchain and bitcoin in 2011 and bittorrent, decentralised  systems and FOSS before then.

**Comment by dan-da** [comment]
imho, the bisq infrastructure/services should not have any user identifying information.  period.

in theory a simple notification framework can be done with:
a) a tor (or i2p) hidden service api that knows only about UUIDs from bisq network.  possibly notifications must be encrypted with pw, or maybe not necessary.  what privacy/security implications?

b) a client-side app (android, web, ios) that polls the hidden service regularly and displays to user.  client side app can use various local delivery/notification options depending on platform.

There is a real need for such services beyond bisq.   For example, clients have asked about notifications for incoming transactions to a bitcoin or monero wallet that they want to keep private/secure.   Perhaps the service could be free for bisq users, and fee-supported for other use cases...

**Comment by mrosseel** [comment]
@dan-da that is indeed one of the questions, do we keep it private-only with a dedicated mobile client which polls the hidden service (needs to run tor on mobile then), or are non-private methods also supported. Or both? 

@citkane thanks for the twister tip and your thoughts on setting smtp servers. Both need to be investigated how feasible they are of course, but I'll add them to the document!

**Comment by dan-da** [comment]
@mrosseel basically, I think we are talking pub/sub with encryption.  So the mobile client generates a priv/pub keypair.  Then to enable notifications, user would import pubkey into the bisq app and choose a channel identifier string (which could be eg user's Tor UUID).  The user's bisq app would push notifications to the channel encrypted with pubkey.   For a given channel, there could theoretically be multiple publishers or subscribers, but subscribers could only decrypt/display messages for which they have the private key.

cleartext notifications intended for public consumption with one or many subscribers could also be supported.

again, the above is general purpose architecture that could be used for notifications beyond bisq use-case.

maybe something like it already exists we can leverage....?

**Comment by citkane** [comment]
@dan-da, from a UX point of view, relying on your own instance of your client to be online for external messages to be received is shaky. eg. (Oh s**t! The kids turned off my pc two days ago!!!!!!). External notifications serve the purpose of reminding you that you have an open trade and action is required.

In a contractual triage, if external notifications can rely on 1 party to be online (and arbitrators should have pretty good uptime) the system would be more reliable. 

Architecturally, there are much broader points to consider, eg. I go on holiday and forget to pack my laptop with open trades - or - I am travelling with open trades and my battery dies. At the moment it appears that any of these situations could cause trade disputes and even lost communications. This is why the issue of persistence of communication needs consideration.

**Comment by dan-da** [comment]
@citkane fair point regarding not wishing to rely on your own node to be online.  

The pub/sub plus priv/pub keypair architecture I outlined doesn't really care who is the publisher of the notification.  So it could be any node(s) on the network.   That said, we probably need to think about exactly what sorts of notifications would be used, and if some or all require any data that only the user's own node would have.

A few examples of desirable notifications I can think of are:
* offer accepted
* trade(s) executed over/under limit price
* trade partner made payment

It seems that a 3rd party node ( operated by bisq or another peer ) *could* provide these notifications if provided with an offerid or market+limit.  However, there is some potential privacy loss.   There also exist a class of notifications that a 3rd party could not provide, such as changes to a user's Bisq wallet balance, eg deposits.

I would suggest that for best privacy, one could run own bisq node for publish notifications, but for those that can't or won't, they can delegate many notifications to 3rd party, possibly by paying some sort of BSQ fee to incentivize 3rd party notification publishers, and keep things as decentralized as possible.

**Comment by dan-da** [comment]
One additional thought:   it should be possible to leverage an encrypted email service such as protonmail for notifications.  Consider that protonmail allows user to export pgp public key and accept pgp email, plus they have an android client that displays android notification when new email is received.  I believe they support iOS as well.

Using protonmail, one's own Bisq node could send encrypted email directly to the user's protonmail account, without passing user's email address to any other bisq nodes.

though of course that doesn't solve the "my node is not always online" problem.

**Comment by ripcurlx** [comment]
@ManfredKarrer Isn't that already completed because of our new relay server?

**Comment by ManfredKarrer** [comment]
Yes with mobile notification it is implemented. I will close.
