### ISSUE TITLE
A timeout occurred at publishing the offer.

### ISSUE THREAD

**Issue by mboehler** [bisq-network/bisq#1027]
I was attempting to place an offer to sell bitcoins and it gave me this error.  I had just clicked "Confirm: Place offer to sell bitcoin", then it said "Offer publishing is in progress..." for a few moments and then and this came up.
[bisq.log](https://github.com/bisq-network/exchange/files/1503457/bisq.log)

**Comment by mboehler** [comment]
I tried again and it worked fine this time.  I think the error may have been caused because I created and cancelled order a couple of times before Confirming.  I was trying to use all of the bitcoin I had in my bisq wallet and it took a few tries to get the numbers to work out.

When I exited and software and reloaded it this time, I simply created an offer for 0.1 BTC and it worked the first time.

**Comment by lightsout21** [comment]
Had a timeout as well when trying to publish an offer. Log file looks different from mboehler's.

Everything works a s expected after restart.

Linux Mint
Bisq 0.6.1
AirVPN

[bisq.log](https://github.com/bisq-network/exchange/files/1520953/bisq.log)

**Comment by ManfredKarrer** [comment]
You have v 0.5.1. Please update to 0.6.1, there have been many bug fixes.

**Comment by cbeams** [comment]
Closing as complete (or otherwise addressed).
