### ISSUE TITLE
Pop-up window announcing new update

### ISSUE THREAD

**Issue by amuuza** [bisq-network/bisq#1030]
Once you close the pop-up window announcing a software update, it won't show up again.
It would be nice if the user had more options with that pop-up window: proceed with the update, postpone the reminder or discard it.

**Comment by ManfredKarrer** [comment]
Agree. Would be a good feature. Will put it on the todo list...

**Comment by mrosseel** [comment]
maybe an easier way to do it and better for the network: if a user dismisses the upgrade, put a little blue link to the right of the version number (status bar at the bottom of the app) saying 'upgrade now' or 'upgrade available'. 
This way the user is reminded to upgrade each time the app is used, improving upgrade rates.
Plus he doesn't have to look in menus or wait till he's reminded again.

**Comment by ManfredKarrer** [comment]
Yeah. Easiest would be to just add a "dont show again" check box and if not selected the update screen comes at each startup. resetting the dont show again flag will retrigger update as well.

**Comment by mrosseel** [comment]
having an indication besides the version number that you're running an outdated version would remind users 'every second' which is in my opinion better, and also less annoying than popup screens. Clicking the warning could open the download window. This way there's no need to store a check box state etc.

**Comment by ManfredKarrer** [comment]
Yes, it is just more UI work. The dont show again flags are handled generically so very easy to add.

**Comment by mrosseel** [comment]
true. Maybe something for @ripcurlx

**Comment by amuuza** [comment]
I think that was fixed.
