### ISSUE TITLE
Unconfirmed trade funds

### ISSUE THREAD

**Issue by kilianju** [bisq-network/bisq#1032]
Hi all,

a few minutes ago I tried to fund a trade of mine. The amount of BTC left my wallet, and minutes after I pressed "Confirm", the client stated, that there was an error. Apparently the funds were already paid or something.. and that in the worst case, my funds were lost. If an admin or dev wants the error log, please write me a message so I can send it to you.
Thanks in advance!

Kilian

**Comment by ManfredKarrer** [comment]
Can you send me the logs please (manfred at bitsquare dot io). 
You can check in the funds/tx screen if funds have left (trade fee). I assume not. You should see it also at portfolio/failed trades if that is the case.
Which version do u use? If not 0.6.* please update, there have been many bugfixes.

**Comment by ripcurlx** [comment]
I'll close this issue because of lack of information. Problem might be resolved with one of the latests releases already. Please reopen if the error still occurs.
