### ISSUE TITLE
Error when creating offers

### ISSUE THREAD

**Issue by technoshaman7777** [bisq-network/bisq#1033]
After the update yesterday I was able to create a few offers. Now it just gives me an error message and says to report it here. Is this just a side effect of high BTC mining fees right now on the network? I have a trade transaction that the blockchain hasn't confirmed for 13 hours now. 
 Bisq error log is below:

"An error occurred when placing the offer:

A timeout occurred at publishing the offer.

No funds have left your wallet yet.
Please restart your application and check your network connection."

[Bisq Log.txt](https://github.com/bisq-network/exchange/files/1516484/Bisq.Log.txt)

**Comment by ManfredKarrer** [comment]
There are a lot of connection errors. Do you have stable internet?

**Comment by technoshaman7777** [comment]
Yes, and I have tried rebooting, several times but nothing seems to help. I just wondered if it was my computer or the blockchain?

**Comment by ManfredKarrer** [comment]
How is your internet connection? Do you have issues with Tor getting blocked?

**Comment by technoshaman7777** [comment]
No issues there. I've been using Bisq for about a year with hour any problems until now. Maybe I need to move my BTC and do a restore?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ManfredKarrer** [comment]
Hm... to start with a new app directory and wallet is not a bad idea. Wallets get heavy over time with a lot of transactions and if there is some issue between the internal wallet database and the wallet it might be a cause for problems. Also add some privacy to restart from time to time.  
Note that there is still no support for taking over your local "reputation" (the nr. of trades u did with other users). If you want to keep that you would need to keep your onion address. It is not difficult to do that but a manual process atm. Let me know if you want that then I explain. But it has the drawback to not give more privacy (all past trades are linked by the onion address).

**Comment by ripcurlx** [comment]
Closing because of lack of feedback. Feel free to re-open if the issue wasn't solved by @ManfredKarrer suggestion.
