### ISSUE TITLE
withdraw: java.lang.IllegalArgumentException: Negative values not allowed

### ISSUE THREAD

**Issue by mtausk** [bisq-network/bisq#1034]
v 0.6.1

Send funds > select > Withdraw to (correct) address > Withdraw selected

Throws java.lang.IllegalArgumentException: Negative values not allowed

log sent to manfred...

**Comment by mtausk** [comment]
I hope there's nothing that other people should not see in the logs I pasted...

**Comment by mrosseel** [comment]
you can always delete it and send directly to manfred

**Comment by mtausk** [comment]
Where/how?

**Comment by mrosseel** [comment]
manfred at bitsquare dot io

**Comment by ripcurlx** [comment]
This should be fixed already a long time ago. Closing as complete.
