### ISSUE TITLE
Feature request (minor): Auto-remove offers when price hits a certain threshold

### ISSUE THREAD

**Issue by lightsout21** [bisq-network/bisq#1035]
I want to sell X, but only when fiat (or btc) value is minY.

Solution: Auto remove %based offers when threshold is hit.

This can save users from being hit negatively by big price swings.

**Comment by lightsout21** [comment]
Relevant: Issue #853

**Comment by ManfredKarrer** [comment]
Agree, would be a nice feature. Should not be too hard to implement.
The offer can be kept locally but removed from the offerbook. Once the price is outside the  "danger zone" it can be re-published. Mostly UI work and in OpenOfferManager. OfferPayload must not be changed for that, local persistence should be used to store the extra data.
