### ISSUE TITLE
Transaction failed - lost 0.1BTC Please help! alt-o option does not work!!

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#1037]
I have a failed transaction because of a network error, its now in the failed Tab, yet the amount has been debited. Please help?
i cannot press alt + o to open support ticket.

**Comment by ghost** [comment]
I closed the client and started it up again, and wallet showed the correct total now. I almost died!
Anyway, it seems as if a transaction fails, that the wallet amount does not get updated in real time. So a restart of the client is needed.   maybe a bug?

**Comment by ManfredKarrer** [comment]
Hm, yes might be a bug. Never saw such a case so far....

**Comment by ripcurlx** [comment]
Closing for now. Feel free to reopen if the error occurs again.
