### ISSUE TITLE
add appimage

### ISSUE THREAD

**Issue by waozixyz** [bisq-network/bisq#1038]
compiling to source is a pain, could you please provide an appimage for bisq? that would be great!
https://appimage.org/

**Comment by ripcurlx** [comment]
Since the issue was created the build process from source was simplified a lot and we also support now prepared .deb binaries and a prepared repo for Arch Linux.

**Comment by henriiquecampos** [comment]
Hey, I'm trying to run it for Solus 4.0, and none of the available releases work, an appimage would be much appreciated.

**Comment by ghost** [comment]
I agree. An AppImage should be considered the standard for distributing standalone packages for Linux. It simplifies the experience for both the developer and the user. The need to maintain all the different builds like DEB and RPM would become unnecessary.
