### ISSUE TITLE
transaction failed 2*taker fee ~0.006btc lost!

### ISSUE THREAD

**Issue by sejktmcsdlmfhsc** [bisq-network/bisq#1039]
I just tried to take a buy bitcoin offer 19:43 but then got a timeout message:
"
A timeout occured.
The takler fee has already been paid. In the worst case you have lost that fee. We are sorry about that but keep in mind it is a very small amount.
...
"
I beg a pardon? 0.03 is about 300 bucks not a very small amount!
To me the network seemed stable, other apps still worked fine.
The message also advised to restart the node, which I did.
The transaction was listed as failed but the available balance was 0.03 btc lower.
Please help.

@ManfredKarrer :
Is there a way to push this taker fee to my next transaction?
Or is there a refund protocol?
Or does this go to dispute?

Thank you in advance.

**Comment by ManfredKarrer** [comment]
The lost fee is the trade fee + mining fee but that should not be 0.03 BTC. Can you send me a screenshot of the funds/transactions screens and the trade details (click on the trade id)? My email is manfred at bitsquare dot io.

**Comment by sejktmcsdlmfhsc** [comment]
will do. thank you for the quick response!

**Comment by ManfredKarrer** [comment]
The lost fee is the trade fee + mining fee but that should not be 0.03 BTC. Can you send me a screenshot of the funds/transactions screens and the trade details (click on the trade id)? My email is manfred at bitsquare dot io.

**Comment by ManfredKarrer** [comment]
Thanks for your email. The deposit has been creates so that is why your security deposit is locked. 
The case will end up in arbitration and there you will get refunded your deposit. I will tell the arbitrators so they are prepared about it. Usually that should not happen that such a case lead to a failed trade (as soon the deposit is created it should always be in pending trades), but there is a bug in an edge case...

**Comment by sejktmcsdlmfhsc** [comment]
Thank you so much for the feedback! 
I will wait for the dispute then.

**Comment by sejktmcsdlmfhsc** [comment]
@ManfredKarrer the arbitration went fine! 
Good to see that bisq works well even if not everything goes according to plan!

Unfortunately the timeout issue just happend again. 
There were two working trades in between, but today ~17:45 it did timout again, 
taker fee gone (0.00324BTC:  ~58$) this is starting to add up..  )-: 
This time the deposit came back after a bisq restart..

**Comment by ManfredKarrer** [comment]
@sejktmcsdlmfhsc I am sorry to hear that. I am working on a new release to fix those issues. Will be out very soon. Get in touch with @cbeams regarding the lost trade fees.  Be sure to have Tor activated for BitcoinJ in the settings/network as for clearnet we have limited proviced btc nodes and that causes issues.

**Comment by sejktmcsdlmfhsc** [comment]
@ManfredKarrer thank you for the quick reply!
I will contact @cbeams then. Looking forward to the new release with the bugfixes!! 
Tor was active as far as I could tell from bisq start screen when connecting to the tor nodes.
No other applications other than terminal and Bisq were running.

I tried an upgrade in a vm to the current 0.6.1 which seemed way more responsive! 
Unfortunately it told me that my bank account details were new(?) [I just copied over .local/share/Bisq] - (I have been using them on bisq at least since since October) so it did set my limits way lower than it used to be. 
 (currently I run 0.5.3 as you probably saw in the last log. Mainly because I do not want to loose the fee of a 0.5BTC sell that I once set up and nobody took so far. [is there maybe an expiration possible?])

**Comment by ManfredKarrer** [comment]
if u update all is taken over. only 0.5 was a non backward compatible update. the trade limit depends when u have set up your fiat payment account. we faded in that new security feature with 15.12. so the decreased limit is a result of that. if u have installed 0.6 when it was released and set up the payment account u should still have the 0.25 btc limit.

**Comment by cbeams** [comment]
@sejktmcsdlmfhsc, I'm not sure whether you've tried to contact me directly yet. Please send me an email at chris@beams.io and reference this GitHub issue when you do. I'm closing this issue in the meantime. Thanks.

/cc #1044
