### ISSUE TITLE
Wrong shortcut icon on Windows

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#1040]
Default java icon instead of bisq:

![image](https://user-images.githubusercontent.com/39793/33529672-5571518e-d874-11e7-86ae-d47894498f99.png)

**Comment by ghost** [comment]
I will try to fix it, usually the problem with install `bmp` icon, not with an icon from application - installation setup file also has not bisq icon, but a default `duke`.

**Comment by ManfredKarrer** [comment]
It should be fixed with https://github.com/bisq-network/exchange/commit/02a5b1386ddc5422652d7b9bfa85b94cf1d1d3eb but I have not tested it yet.

**Comment by ghost** [comment]
I was build setup from master and it works.

![image](https://user-images.githubusercontent.com/39793/33530844-905e33d2-d885-11e7-87dc-afad34b94619.png)

Some remarks:

1. I find default setup file icon better as a custom one, looks like (and maybe it's a typo in the line ``SetupIconFile=C:\Users\asd\Desktop\exchange\package\win\64bit\Bisq.ico``):

![image](https://user-images.githubusercontent.com/39793/33530888-fc7a0852-d885-11e7-811f-c311eb9e409c.png)

2. `javapackager.exe` starts to find `Bisq.iss` file only after I moved it from `package\win\64bit` to `package\windows`, instead it build it by default and ignore all customization, may be your env is differ.

**Comment by ManfredKarrer** [comment]
Thanks for testing it!!!

Hm... "package\windows" is nowhere used. No idea. I have not made a win build since those changes but will check at next release. Maybe I made a path mistake in the latest changes?

Btw: Please add a compensation request for your contributions!
See: https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc
https://github.com/bisq-network/compensation/issues

Deadline for November is already close but you can add it for next month as well...

**Comment by ghost** [comment]
Thank you, I will check it again when a new version was released or if you will face with additional problems to build it on Windows - just tell me. Usually the default directory for custom icons and InnoSetup project should be `package\windows` [1], [2].

[1] https://stackoverflow.com/questions/34252947/adding-icon-to-bundle-using-javapackager
[2] http://code.makery.ch/library/javafx-8-tutorial/part7/

> Packaging tools look for customized resources on the classpath before reverting to built-in resource. The Javafx Packager has "." (the current working directory) added to the classpath by default. Hence, to replace the application icon, simply copy your custom icon to ./package/macosx/DemoApp.icns in the directory where javafxpackager is run (typically, the root project directory).

from https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html

**Comment by ManfredKarrer** [comment]
Ah ok. Good to know. So that is default set by the Java packager or InnoSetup?

**Comment by ghost** [comment]
Java Packager, but may be in your environment it works, who knows ;)
