### ISSUE TITLE
wrong y axis label

### ISSUE THREAD

**Issue by bisqfan** [bisq-network/bisq#1041]
The label on the y-axis is currently "Price in EUR for 1 BTC".
Expected label: "Volume in EUR"

<img width="239" alt="screen shot 2017-12-03 at 23 10 55" src="https://user-images.githubusercontent.com/34220505/33530408-4f8e1bb6-d87f-11e7-8d64-8cf0172f701a.png">

**Comment by ManfredKarrer** [comment]
No that is the price. the volume i s below.

**Comment by bisqfan** [comment]
oops, my bad, you are right. I close the issue.
