### ISSUE TITLE
Blurred GUI after pop-up interrupted

### ISSUE THREAD

**Issue by r8d8** [bisq-network/bisq#1042]
Steps to reproduce:
* Open Bisq and make any action to spawn pop-up window
* Close windows with window control (black arrow) insted of `Close` button
![bisq_popup](https://user-images.githubusercontent.com/8018746/33549379-eb53f430-d8f2-11e7-9b05-def185ff1f7f.png)

Received behaviour:
* Pop-up window closed but blured layer resist, app doesn't responds to mouse actions
![bisq_blured](https://user-images.githubusercontent.com/8018746/33549382-ee80d394-d8f2-11e7-9418-e6375e8943b3.png)

Required behaviour: 
* Closed pop-up window and blured layer should dissapear

Enviroment:
ArchLInux (kernel 4.13) + Awesome window manager
Bisq v0.6.1

**Comment by ManfredKarrer** [comment]
The outer frame of the popup should not be visible. Seems that some JavaFX features are not supported on that window manager.

**Comment by r8d8** [comment]
@ManfredKarrer, may I try to fix it?

**Comment by ManfredKarrer** [comment]
Sure would be great!

**Comment by ghost** [comment]
ArchLinux, @r8d8 please check in your settings `wmname LG3D` (`.xinitrc`) [1].

[1] https://wiki.archlinux.org/index.php/java#Impersonate_another_window_manager

**Comment by r8d8** [comment]
@dulanov, `wname` doesn't helped

**Comment by r8d8** [comment]
Same error on Ubuntu + AwesomeWM. Will try to tune OpenJDK.

**Comment by ghost** [comment]
on vanilla GNOME is it work?

**Comment by r8d8** [comment]
It works on XFCE (I haven't gnome), so looks like  trouble in awesomeWM.

**Comment by ghost** [comment]
It's all interesting, because I couldn't find any issues either in original JDK and in awesome window manager issue trackers, only very old one issue:

> Issue RT-4797: <code>StageStyle.TRANSPARENT</code> is not supported on the OpenSolaris and Linux platforms.
Description: On the OpenSolaris and Linux platforms, a stage style of <code>TRANSPARENT</code> is treated as <code>UNDECORATED</code>. 
Workaround: None.

In code it simply:

```java
                stage = new Stage();
                stage.setScene(scene);
                Window window = rootScene.getWindow();
                setModality();
>>>                stage.initStyle(StageStyle.TRANSPARENT);
                stage.show();
```

Please also try `java.lang.System.setProperty("javafx.allowTransparentStage", "true");`.

**Comment by r8d8** [comment]
IntelijIdea having the same error:
![framming_error](https://user-images.githubusercontent.com/8018746/33669929-6aae9356-daac-11e7-9d4f-4e6960bd81a9.png)
Will delegate issue them, maybe they already have some solution)

**Comment by ghost** [comment]
So it's not JavaFX specific bug any more, Intellij IDEA is written on Swing.

**Comment by ManfredKarrer** [comment]
Ah if even the masters have the issue we are in company ;-)

**Comment by ghost** [comment]
But anyway, @ManfredKarrer we can try to add a stage close handler for every overlay windows (?) and handle it independently of the border existence, because initial error was not a border appearance, but blurred window after close.

**Comment by ManfredKarrer** [comment]
Yes the stage should the event. u can test it when changing the window style so the default frame is displayed and then see which event arrive at the stage or scene...
