### ISSUE TITLE
Concept for editing existing offers

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1043]
If we allow that users can edit an existing offer they do technically remove the offer and create a new one because the offer is stored by the hash and any change would break that.
The maker fee is important as spam protection. If we allow to create a new offer without fee we would disable that protection. So we need to find a way how to link to the original offer where the fee was paid or to verify that the fee tx is only used in one offer.
If a solid concept is found it requires some UI work.

**Comment by Quenos** [comment]
What I do not get is why are you concerned with spam? What is your definition of spam?
An offer is an offer and can be taken by anyone.
The only concern I see is unnecessary network congestion if orders are entered and almost immediately removed again. This can be countered by a timing mechanism. Only orders that are older than x can be removed for free.

**Comment by cyphersphinx86** [comment]
Maybe we could limit the editing ability to one time per minute.
So if an order is cancelled it can be replaced by a new one for free, but only one time per minute.
This should allow simple user mistakes to be corrected, as well as giving our trade bot ability to calibrate most of the time.

**Comment by ManfredKarrer** [comment]
@Quenos All offer produce load for the P2P network (each client). The nr. of offers does not scale endlessly so we need a mechanism to protect and incentivice the behavior of offer creation.

@cypherspace86 Yes some time checking might work. Consider that each client need to be able to validate if an offer is valid or not. But I think that is do-able.

**Comment by ManfredKarrer** [comment]
Close because editing offer is already implemented.
