### ISSUE TITLE
Investigate why there are timeouts leading to failed trades

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1044]
We get frequent timeouts which lead sometimes to lost trade fees. Find out the reason for timeouts (Tor network issues, too low timeouts currently used, bug/errors on the peers side so he stops responding, network disconnections to peer,...).

**Comment by cbeams** [comment]
I've removed the bounty label from this issue, and assigned it to you, @ManfredKarrer, to reflect the actual situation.

**Comment by cbeams** [comment]
These are the artifacts from our F2F meeting with @ManfredKarrer, @ripcurlx and @cbeams in Vienna on this topic:

![image_uploaded_from_ios](https://user-images.githubusercontent.com/301810/34715925-99599452-f52e-11e7-98e2-75ade4c9acc4.jpg)

We also recorded audio of the conversation that led to this whiteboard, but the file is too large to upload here. It can be found in Slack at https://bisq.slack.com/archives/C8LTGBCE5/p1515246556000052.

**Comment by cbeams** [comment]
Closing as complete. See epic #1167 for further details.
