### ISSUE TITLE
Add payment method: Uphold

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1048]
Investigate and if it fulfills our requirements integrate Uphold as new payment method.

**Comment by ManfredKarrer** [comment]
Requested at: https://bisq.community/t/integrating-uphold-to-bisq-and-a-few-questions-suggestions/3482/8

@flix1 @cbeams  Are you familiar with Uphold?

**Comment by ManfredKarrer** [comment]
I just set up a Uphold account. Seems to be a cool payment option. Good experience so far but waiting for verification....

**Comment by ManfredKarrer** [comment]
Verification was fast. Just upload ID card + photo.

Supported counties for banks:
In which countries does Uphold offer bank account funding and withdrawals?

Direct bank account funding and withdrawals are currently offered to Uphold members in the following countries:

Austria, Belgium, Bulgaria, Croatia, Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Ireland, Italy, Latvia, Liechtenstein, Lithuania, Luxembourg, Malta, Monaco, Netherlands, Norway, Poland, Portugal, Romania, San Marino, Slovakia, Slovenia, Spain, Sweden, Switzerland, the United States and the United Kingdom.

**Comment by ManfredKarrer** [comment]
<img width="531" alt="screen shot 2018-02-12 at 20 24 27" src="https://user-images.githubusercontent.com/1449498/36128933-cbead614-1032-11e8-814c-326f3c795569.png">

**Comment by ManfredKarrer** [comment]
<img width="523" alt="screen shot 2018-02-12 at 20 24 20" src="https://user-images.githubusercontent.com/1449498/36128950-daf66196-1032-11e8-86c8-5f9de2622d07.png">

**Comment by ManfredKarrer** [comment]
Uphold is committed to making financial services affordable for everyone and we strive to keep all fees as low as possible. Certain fees may apply to institutional and high-frequency members, but any such fees will be agreed upon in advance.

* China Union Pay card funding is available at a 1.8% fee. 

Minimums

The minimum withdrawal amount is 0.00001 BTC or the equivalent in any other currency.

EU: the minimums are €75/transaction or £100/transaction. 

To increase your limits, please see our Account Limit Increase Application.

Cryptocurrencies

There is a 500 bitcoin limit for any single bitcoin transaction. For members who want to transact more than 500 bitcoin or Litecoin, you may execute multiple transactions. 

How does Uphold set its conversion rates?

Uphold uses the mid-market price when quoting the value of holdings on our system and for our currency conversions. The mid-market price is the midpoint between the bid and ask price quoted in the financial markets. For example, if the bid price is $305 and the ask is $295, then the price used for buying and selling that asset is $300. For our precious metals, we use the midpoint between Gold Bullion International’s (GBI) buy /sell prices.

As part of our commitment to fairness and transparency, we are proud to use the mid-market price to eliminate any spread and ensure no hidden fees, so that our members receive the market’s most transparent and fair pricing.

In the case of bitcoin, we're constantly monitoring rates and liquidity from multiple exchange partners and, in our efforts to reduce volatility, we pick our rates based on which exchanges have the highest liquidity. We do not endorse any particular mid-market price and we cannot verify if the mid-market price reflects exact fair market value at any time.

 $1,000 Transaction Allowance for non-verified members

Uphold requires all members to become verified members when the cumulative value of their lifetime transactions (excluding the addition of funds to their accounts) exceeds $1,000 U.S. dollars.

This is for your safety and the security of the Uphold network at large. When this allowance is exceeded, accounts will be restricted from conducting transactions of any kind until the account has been fully verified. Our team reviews all transactions for compliance with our membership agreement.

Inactive accounts 

To keep your Uphold account active you simply need to initiate a transaction within your Uphold wallet every 90 days. A transaction is considered any action which value is moved and is initiated by a member within their Uphold wallet. Including a bank transfer (deposit or withdrawal), moving value between cards, sending value to another member, email address, or crypto address.

The following is a summary of cumulative fees that will be automatically collected from inactive accounts:

    90 - 180 days: 1 USD per month
    180 - 365 days: 5 USD per month
    365+ days: 10 USD per month

**Comment by ManfredKarrer** [comment]
Uploading money works from credit card, SEPA, GPB bank or crypto currencies.
At credit card funding they show that popup:
<img width="461" alt="screen shot 2018-02-12 at 20 36 56" src="https://user-images.githubusercontent.com/1449498/36129340-b76a1388-1034-11e8-97bc-89e64564440c.png">

Not sure if that would really help, but interesting to see.

**Comment by ManfredKarrer** [comment]
And they suffered the same boycott by credit card providers like XAPO and others:
<img width="549" alt="screen shot 2018-02-12 at 20 39 43" src="https://user-images.githubusercontent.com/1449498/36129387-ef9708c4-1034-11e8-9554-3cf76316c2d8.png">

**Comment by ManfredKarrer** [comment]
Seem to be a very good Fintech company. Pretty impressed by UI and features. 
Required fields for sending any currency to another Uphold user is only:
Username or email or tel nr. - so that gives quite good privacy.

Regarding chargeback risk I have not found anything yet.
Does anyone has any info? 

Also interesting:
https://uphold.com/en/transparency
If that content is real of PR I cannot say but at least well done from UI!
Bitfinex could learn a bit from them ;-)

**Comment by ManfredKarrer** [comment]
https://uphold.com/en/legal/membership-agreement/world

" 5.11 You expressly agree that you will not reverse or attempt to reverse any add-funds or add-Value transaction(s) you complete. You also agree that we may deduct any Value associated with your Account if an add funds or add-Value transaction using a bank account or credit card is subsequently reversed via a chargeback, reversal, claim or is otherwise invalidated. We may also deduct any Value held by you in a wallet to satisfy any outstanding amount owed by you to us under this Agreement or otherwise. We reserve the right to report, suspend and/or terminate Accounts for chargeback abuse. "

**Comment by ManfredKarrer** [comment]
11. ASSUMED RISK WITH TRANSACTIONS.

Your use of the Service, or any part thereof, is at your sole risk and we assume no responsibility for the underlying transaction of funds, or the actions or identity of any transfer recipient or sender. If any third party files a claim for a chargeback or we are otherwise informed of a dispute between you and another party, we are not responsible for determining the veracity of claims or resolving the dispute, including disposition of any associated Value.

**Comment by ManfredKarrer** [comment]
They even have an API:
https://uphold.com/en/developer/api/documentation/#introduction

**Comment by ManfredKarrer** [comment]
From my investigations I think we should add it. 
The FX feature cannot be really used as that would require more effort in Bisq side, so currency need for sender and receiver need to be the same.
Only open question is chargeback risk, but in doubt I would give it a try.

**Comment by ManfredKarrer** [comment]
Added Uphold: https://github.com/bisq-network/exchange/commit/ead30822e5ef03905119f2f298c0511d0246fdf5

**Comment by ManfredKarrer** [comment]
More questions:
- How long takes a normal transfer?
- Do they transfer 24/7 or only at office hours?

**Comment by ManfredKarrer** [comment]
<img width="928" alt="screen shot 2018-02-13 at 20 03 46" src="https://user-images.githubusercontent.com/1449498/36182726-09a51890-10f9-11e8-84fe-5c3f0b2a2ccb.png">

**Comment by flix1** [comment]
I have an Uphold account. It works quite well... but the number of users is low (not millions) and Uphold users already have the option to buy/sell BTC on the Uphold platform itself... so the number of people who will use Uphold in combination with Bisq is probably tiny. @ManfredKarrer I would not make this a priority. But sure, it's nice to test it.

**Comment by ManfredKarrer** [comment]
An interesting option might be the cross currency support. Reminds on OKPay, but might be not much used at the end...

**Comment by tuqueque** [comment]
Fantastic!... I also have an Uphold account (I was the one asking for Uphold support in Bisq), the cryptocurrencies supported in Uphold is rather small, so Bisq still is a great option for the few among us that want to trade less common assets. Thanks for your work on the implementation!

**Comment by ManfredKarrer** [comment]
Uphold transfer seem to be instant: 
https://support.uphold.com/hc/en-us/articles/206116473-What-is-Uphold-

**Comment by ManfredKarrer** [comment]
Here is the screen for sending money:
<img width="1113" alt="screen shot 2018-02-23 at 10 42 21" src="https://user-images.githubusercontent.com/1449498/36602545-4c84f308-1886-11e8-8343-1e22b3a7ac3e.png">

**Comment by tuqueque** [comment]
Yes, Uphold transfers between members ( when using FIAT money) are instant and zero fees. If you transfer cryptocurrencies, fees and time for the transfer to take effect depend on each asset/blockchain, as usual.
