### ISSUE TITLE
Add payment method: Square Cash App

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1049]
Investigate and if it fulfills our requirements integrate Square as new payment method.

**Comment by cbeams** [comment]
_This is a write up I did on adding square cash / cash app as a payment method back in November. Unfortunately I did it in a GitHub team discussion before I realized that those are essentially private communications (you have to be a member of the team to be able see it). Anyway, here it is, reposted where everyone can see and comment:_

[Zelle](https://www.zellepay.com/) is by far the most commonly-used payment method for Bisq users in the US right now, but it can be problematic for a number of reasons. [Square Cash](https://cash.me) is becoming popular, and it would be interesting to see if it could be a suitable payment method in Bisq as well.

Note that this investigation has nothing in particular to do with the recent news that it's now possible to buy and sell bitcoin directly via Square Cash. Rather, this discussion is all about whether we should support Square Cash as a payment method like any other. Doing so would allow people who use Square Cash to still take advantage of all of Bisq's privacy and security features.

The main question to investigate is what kind of chargeback risk is involved with Square Cash transactions. Like all other payment methods supported by Bisq, it must be extremely difficult or impossible for fraudsters to issue chargebacks. See the [payment method hardness scale](https://en.bitcoin.it/wiki/Payment_methods) on the Bitcoin Wiki for more details.

Another question to investigate is what kind of transaction limits are imposed by Square Cash. These limits may be imposed on a daily or monthly basis, and/or they may be imposed based on the age of a Square Cash account. All of this information would be important for us to know if we're going to support it effectively within Bisq.

You can find out more about Square Cash at https://cash.me/ and https://squareup.com/help/us/en/topic/272.

In any case, please comment on or add a 👍  reaction to this discussion if you're a Bisq user (current or potential) who would like to use Square Cash as a payment method.

For those interested in doing the research on chargebacks and other potential risks, this work—like all other contributions—is [eligible for compensation in BSQ](https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc#how-bsq-is-used) under the Bisq DAO. And in addition to answering the questions above, we'd also suggest that you update the payment methods page on the Bitcoin Wiki (see link above), as it does not yet have an entry for Square Cash.

Thanks, and we look forward to hearing from everyone!

**Comment by ManfredKarrer** [comment]
@flix1 Could you check the requirements to add it?

**Comment by ManfredKarrer** [comment]
@cbeams @flix1 
Can anyone provide me the required data fields?

**Comment by ManfredKarrer** [comment]
Seems to support US credit cards only.

**Comment by 1GWilly8** [comment]
This post seems to indicate that payments are non-reversible once the receiver has accepted them.
https://squareup.com/help/us/en/article/5691-how-to-cancel-a-cash-app-payment

**Comment by ManfredKarrer** [comment]
@gayw18 Thanks!
Do you know the mandatory fields when sending funds to another user? Email or tel nr or username or account nr?

**Comment by 1GWilly8** [comment]
It seems very flexible, you can even pay users who don't have the cash app via email (they just enter debit card info into Cash's website to claim funds).

In app:
- CashTag (In app username that looks like $SampleUser)
- Email 
- Stored contacts
- Phone number

Out of app:
- Email w/ Cash@Square.com cc'd and amount to transfer in the subject line
- https://cash.me/$SampleUser

Demo starts at 1:06:
https://www.youtube.com/watch?v=rRlwRvxmziY

**Comment by ManfredKarrer** [comment]
So its only one field:
Cashtag or email or phone nr.
Right?
It is US and USD only, right?

**Comment by 1GWilly8** [comment]
Yes, just one field and it is US only, so I would assume USD only as well.

**Comment by mrosseel** [comment]
similar to the discussion around venmo, it might be a good idea to start with Cashtag only; we're sure the user is already in the system and won't experience some signup obstacle which would invalidate the trade.

**Comment by ManfredKarrer** [comment]
@mrosseel Good point. The cashtag is set after sign up i assume. not sure if that means that the user is verified.

**Comment by ManfredKarrer** [comment]
More questions:
- How long takes a normal transfer?
- Do they transfer 24/7 or only at office hours?

**Comment by ManfredKarrer** [comment]
<img width="933" alt="screen shot 2018-02-18 at 19 51 13" src="https://user-images.githubusercontent.com/1449498/36359141-de6a58de-14e5-11e8-85d5-5d02cb689697.png">

**Comment by cbeams** [comment]
Heads up: Cash App has a $2500 weekly spending limit. From https://squareup.com/help/us/en/article/5505-send-and-request-money-with-cash-app:

![image](https://user-images.githubusercontent.com/301810/36382366-ee95c8e4-1588-11e8-94fb-bfacaa22cc8b.png)

Also, once your account is verified, there is no limit on how much you can receive:

![image](https://user-images.githubusercontent.com/301810/36382428-25a285e8-1589-11e8-8b9a-2e99933bf963.png)

**Comment by cbeams** [comment]
Regarding chargeback risk with Cash App, it looks like it is possible for the buyer to initiate a a chargeback, but it requires interaction with Square support staff. From: https://squareup.com/help/us/en/article/6134-get-started-with-your-cash-app-card

![image](https://user-images.githubusercontent.com/301810/36384517-d8214802-158f-11e8-9ab4-5c3ea0ec53d2.png)

Here's an example of somebody getting scammed on LocalBitcoins with a Cash App trade: https://localbitcoins.com/forums/#!/localbitcoins/fraud:square-cash-reversal-got-sc

**Comment by ManfredKarrer** [comment]
"For square cash, they initiate the deposit right away, but it takes several days for the ACH to clear into your bank, and during this time it can get canceled any time." 
https://localbitcoins.com/forums/#!/localbitcoins/fraud:square-cash-reversal-got-sc

Maybe we should add some delay at the payout?

**Comment by ManfredKarrer** [comment]
We decided to not a delay as it would confuse users and remove the advantage of instant payments. We show a popup with pointing out the chargeback risk and use lower trade limits.
