### ISSUE TITLE
Add payment method: International transfer

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1051]
Investigate and if it fulfills our requirements integrate it as new payment method.

**Comment by Quenos** [comment]
What is the difference with #1049?

**Comment by ManfredKarrer** [comment]
Deferred as there are too many issues:
- unknown bank fees
- unknown duration (can be 2 weeks)
- unknown exchange rate
- little demand for it so far
- how do we list it: with senders currency or receivers currency?
