### ISSUE TITLE
Check if US ACH is really chargeback risky

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1052]
Gather clear information about the chargeback risks of ACH payment in the US. We have it deactivated because we considered the chargeback risk too high.

**Comment by pranay01** [comment]
Would like to explore this. Do I need to get it assigned to me before working on it? Also, what is the nature of output expected - just a report based on research?

**Comment by mrosseel** [comment]
assigning is not needed, just indicate on this ticket you will be working on it and when you think you can finish it. A report based on research is indeed the expected output. 

If you're unsure feel free to ask further questions on this ticket or in slack!

**Comment by cbeams** [comment]
> Would like to explore this.

Great!

> Do I need to get it assigned to me before working on it?

No, but I've just invited you to join the @bisq-network org and can assign it to you if and when you accept.

> Also, what is the nature of output expected - just a report based on research?

Yes, a write up on your findings is good for a start, and you can submit that as a comment here, or write it up in a Gist or other doc that you link to from here.

Of particular interest in that report would be research into LocalBitcoins' support for ACH/WIRE and what kind of issues users there have run into.

/cc @flix1

**Comment by pranay01** [comment]
Ok. @cbeams Have joined @bisq-network 
I will be working on it and plan to finish it within a week.

**Comment by cbeams** [comment]
Great, @pranay01. I've assigned you to this issue. Looking forward to your findings!

**Comment by ManfredKarrer** [comment]
@pranay01 Did you find out something?

@flix1 Do you know about the risk of ACH or if there is a way to avoid that ACH can be used for a local bank transfer in the US, thus forcing a WIRE transfer which seems to have less chargeback risk.

**Comment by pranay01** [comment]
@manfredkarrer Added my research on ACH chargeback risk
https://docs.google.com/document/d/1vf7vhZbIOTgFHkJk0zRlv0_55nbOWTufNTIRnoaN-cI/edit?usp=sharing

**Comment by ManfredKarrer** [comment]
Great thanks! Can you compare it to Zelle or Quickpay regarding chargeback risk?

**Comment by ManfredKarrer** [comment]
@cbeams @flix1 
Could you have a look to that screen if the data fields are correct?
We have the requirement that the routing nr has 9 numbers and the account number 4-17 numbers.
Account types are checking and savings.

<img width="1078" alt="screen shot 2018-02-22 at 20 00 18" src="https://user-images.githubusercontent.com/1449498/36572650-06f8e86a-180b-11e8-9dd9-95feff96ce03.png">
