### ISSUE TITLE
Confirm which banks fully support Zelle payments

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1053]
We only support the member banks of Zelle. It seems that the group of banks working reliable with Zelle got extended. Collect clear information for those banks which work reliable with all the other banks in that group.

**Comment by ManfredKarrer** [comment]
@flix Can you try to get more information if we can lift our restrictions? If we don't get clear information we could give it a try to remove the bank restrictions and see how it plays out in real life. Worst case: more arbitration cases.

**Comment by flix1** [comment]
Not fully verified, but indicative:
https://localbitcoins.com/buy-bitcoins-online/usd/

There are LBC offers for Zelle with the following banks:
1. Wells Fargo
2. Bank of America
3. Chase
4. Citibank
5. TD

**Comment by ManfredKarrer** [comment]
We have those listed as member banks:
<img width="568" alt="screen shot 2018-02-14 at 11 11 17" src="https://user-images.githubusercontent.com/1449498/36214577-d196d4a0-1177-11e8-84fe-33c19ab7654d.png">

**Comment by ManfredKarrer** [comment]
So Citibank is missing. What is TD?

**Comment by flix1** [comment]
TD is Toronto Dominion, a Canadian bank also present in US.

**Comment by cadayton** [comment]
With Bisq I've used Zella with Chase multiple times with no issues other than remembering there is a $2000 per day limit.   I do have an account with BofA too and do know they market using Zella, but I have not used Zella with my BofA account.

**Comment by ManfredKarrer** [comment]
I added TD Bank. For extending it further it will require more investigation. I keep that issue open but kick it out from release/milestone 0.6.6.

**Comment by MattNguyen** [comment]
What else do you need investigated? I noticed that Zelle lists their partner banks [here](https://www.zellepay.com/get-started). Do you want to add _all_ of the partner banks in [common/src/main/resources/i18n/displayStrings.properties](https://github.com/bisq-network/exchange/blob/f86bb433ed8018bc7edbae48a7d1ab7fd7cc7df5/common/src/main/resources/i18n/displayStrings.properties)?

**Comment by ManfredKarrer** [comment]
I doubt that all those banks really work in any combination with each other, at least 1 year ago we got a lot of problems and it turned out that only the member banks works really reliable. Not sure if they really improved their service, but at least I would not trust what the state on their webpage.

**Comment by alfsbs** [comment]
Issue moved to [bisq-network/payment-methods #10](https://github.com/bisq-network/payment-methods/issues/10) via [**ZenHub**](https://www.zenhub.com/)
