### ISSUE TITLE
Export/import feature for onion address

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1055]
To keep one's local reputation if changing the data directory an export/import feature for the onion address would be nice to have. It simply requires hostname and private_key files from the hidden service directory.

**Comment by blabno** [comment]
Where in UI do we want to have this functionality (Settings->Network info)?

**Comment by cbeams** [comment]
In the Tor settings dialog at `Settings->Network info->Open Tor settings`.

**Comment by fotispap** [comment]
Would it make sense to merge this with issue #1056 ?
This is what I have in mind:
![torNetworkSettings](https://user-images.githubusercontent.com/1302765/47317215-4dbd2c00-d649-11e8-8841-d3d9e2234800.png)

**Comment by ManfredKarrer** [comment]
@fotispap Thanks!
I would use the term private key  for what is exported/imported instead of onion address. Renew onion address is ok, but import/export priv key...

I would also not add it to the Tor settings as that is shown automatically at connection problems. Better to add a button in the network settings for renewing the onion address. Then show the details in a new popup.

It is important to explain the user that he can do that only if he has no offers/trades/disputes open and the he will lose his local reputation (those he has traded with will not see him as the same node and therefore the number of trades displayed in the avatar will be not valid anymore). 

I also is important to check for open offers/trades/disputes and only allow then the renewal.

Such checks are already partially in place for emptying the wallet for instance...

**Comment by fotispap** [comment]
Sorry for disappearing! I am not sure if assigning @freimair means he plans to work on this? I am working on a version incorporating @ManfredKarrer suggestions. I decided to implement the functionality first and worry about the GUI part later. I am hoping to have a pull request ready next week.

**Comment by ManfredKarrer** [comment]
@fotispap Ah cool. If you work alreay on it then please go on. @freimair was just jumping in here as it was not clear that someone else works on it.

**Comment by freimair** [comment]
alright, I leave it to you then

**Comment by freimair** [comment]
i guess you are onto #1056 as well?

**Comment by fotispap** [comment]
Thanks freimair! Yes, I thought it made sense implementing the as one, since they are very similar functionalities. I will try to get a pull request soon, and looking forward to your feedback.

**Comment by freimair** [comment]
@fotispap Do you plan on getting this done still? if not, I would take over and get it done.

**Comment by freimair** [comment]
how about:
![Screenshot from 2019-07-11 11-33-14](https://user-images.githubusercontent.com/1070734/61040132-52409500-a3d0-11e9-9db3-f0183526c6bd.png)

Exact labels and titles are to be discussed of course...

**Comment by ManfredKarrer** [comment]
I would use "key" instead if "ID" or "address".
It requires some checks if open offer, trades or disputes are there and if so tell the user that he has to wait until those are closed (or close offers).

**Comment by freimair** [comment]
hm, I was thinking whether we should change "My onion address" to "My ID" because what else is that highly cryptic string of characters to a user. Having an ID is quite common in today's interwebs, why burden the user with this "onion address" thing, whatever that might be.

ad checks: of course.
- am I correct that 'TradeManager::getTradableList' gives me all trades in progress including trades in dispute?
- I plan on republishing the offers with the new address, more investigation due...

ad feature: I plan on forcing a restart of the app after a renewal or import. Because
- that makes it a lot less complex to implement (and therefore less error-prone)
- I expect that the feature will not be used on a regular basis, will it?
