### ISSUE TITLE
Feature for renewing the onion address

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1056]
For gaining more privacy a feature for renewing the onion address would be nice to have.
It would simply delete (backup first) the filed in the hidden service directory. It would require some checks that the user has no open offer, trades or disputes and that he understands that he loses his local reputation by changing the onion address.

**Comment by ghost** [comment]
Did anyone work on this issue? Renewing onion address on each restart should not be difficult IMO

> he loses his local reputation by changing the onion address

Why is reputation associated with onion address?

**Comment by xanoni** [comment]
> Why is reputation associated with onion address?

Can someone clarify?

**Comment by ripcurlx** [comment]
> > Why is reputation associated with onion address?
> 
> Can someone clarify?

It is not a real reputation feature more a possibility to tag onion addresses on your own node and to see how often you've interacted already with a certain address. This is planed differently for Bisq 2.0 (see https://github.com/bisq-network/proposals/issues/330)
