### ISSUE TITLE
Check if Java9 is already ready for use

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1057]
A while ago maven was still not supporting Java 9. Once all our infrastructure supports Java 9 test if all works as expected, so we can move to Java 9.

**Comment by porcupinenick** [comment]
Why are we checking for Java9 compatibility if JDK10 is needed to install Bisq? Am I missing something here?

**Comment by ManfredKarrer** [comment]
Was outdated issue. I close.

**Comment by ripcurlx** [comment]
@sirnickyc We just merged the Java 10 support yesterday. This issue indeed is closed now because of https://github.com/bisq-network/bisq/pull/1660. @ManfredKarrer was faster to close it 😉
