### ISSUE TITLE
Make arbitration chat messages selectable

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1058]
Currently, the text in Bisq's arbitration chat messages is not selectable, i.e. it is not possible to click and drag over the text in order to copy a portion to the clipboard.

![image](https://user-images.githubusercontent.com/301810/34817808-4c8ad17c-f6b9-11e7-906b-4ea30737a6da.png)

Notice in the screenshot above the double-document icon in the upper right of each message. This copies the entire contents of the chat message to the clipboard, but this is cumbersome when all one wants is to copy a particular passage of text, e.g. a URL.

With regard to the related topic of URLs actually being clickable in these messages, see #1059.

**Comment by blabno** [comment]
I'm taking this one.

**Comment by blabno** [comment]
It seems that labels are not selectable. This feature has been requested in 2015 and nobody even commented on it https://bugs.openjdk.java.net/browse/JDK-8091644.
So I would suggest showing on double click modal with textarea containing the message.

**Comment by blabno** [comment]
Do we want the modal to have modality Application or None? 
Application modality means that you cannot focus any other app window unless you close the modal.
