### ISSUE TITLE
Add 'Press' page to wiki

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#106]
To capture media mentions, reviews, podcasts about Bitsquare.

October 2nd 2014 Bitsquare Presentation at Barcelona Bitcoin Meetup:
http://www.meetup.com/bitcoin-barcelona/events/208734292/
![untitled-3](https://cloud.githubusercontent.com/assets/8958455/4504554/99165bbe-4ae7-11e4-829f-251234d55973.png)

September 9th 2014 Informal Bitsquare Explanation at Barcelona Bitcoin Meetup:
http://www.meetup.com/bitcoin-barcelona/events/203215982/
![600_408083032](https://cloud.githubusercontent.com/assets/8958455/4504564/b8c4de36-4ae7-11e4-87f5-3b49b946683a.jpeg)

**Comment by cbeams** [comment]
Hey @btcll, @ManfredKarrer—I've added https://github.com/bitsquare/bitsquare/wiki/Press-and-Events. Could you guys just add entries for everything you can think of? Lloyd, not sure if we want to do inline photos there, as it might create a lot of scrolling and obscure the information. We could add a "Photos" wiki page, perhaps. Feel free to do that if you like.

Note that adding images to GitHub Wiki pages isn't super straightforward. You can click the image button, but you really only have the option of a URL—i.e. you can't upload an image through the UI. There are ways of getting images into the Wiki's git repository, but the easier thing to do is just upload whatever image you want to http://imgur.com and link to it.

In the meantime, I'm going to close this issue. Just add whatever you can think of to that page and we can tidy it up as we go. Don't worry about making it pretty now.

**Comment by ManfredKarrer** [comment]
I added all events/media coverage: https://github.com/bitsquare/bitsquare/wiki/Press-and-Events
I added also an essays category with the links to the articles of Chris and Richard. 
@cbeams: I added also your SpringOne talk (decide you if that fits... was more general about bitcoin i assume...)

**Comment by cbeams** [comment]
Looks great!
