### ISSUE TITLE
Hide coin selection table in withdrawal screen

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1061]
Option to hide coin selection table in withdrawal screen (by default all possible inputs are selected and table is hidden). In the development branch there is already added another feature to send exact amount for receiver. Please build on top of that branch.
Check with @ripcurlx for usability and design.

UPDATE: The mentioned feature is already in master and released.

**Comment by ripcurlx** [comment]
@ManfredKarrer Do you mean to hide the selection table when `Use all available inputs` is selected and show it for `Use custom inputs`?
<img width="1312" alt="bildschirmfoto 2019-02-12 um 10 47 34" src="https://user-images.githubusercontent.com/170962/52626609-d4756d80-2eb3-11e9-9110-138eb68adfc5.png">

**Comment by ManfredKarrer** [comment]
I think with the improvements in the meantime that issues can be closed.
