### ISSUE TITLE
Always show tooltip with full text if text is truncated 

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1066]
To improve usability for languages which don't have a compact way of expression (e.g. French) truncated text should automatically cause an Tooltip to be shown on Rollover with the full text.

**Comment by ghost** [comment]
OMG, I tried exactly to fix this problem on the last week on my own project and didn't find any simple straightforward solution similar to this one with textedit promptext, also was introduced by me some time ago ;)

**Comment by ManfredKarrer** [comment]
Maybe with overriding the handling of the ellipsisString it could work? E.g. we use our extended version of Label/TextField and when usually the ellipsisString is shown we adjust the behavior to show a tooltip. Have not looked into it if it is feasible...

**Comment by ghost** [comment]
I am always tried to solve such problems without need to extend JavaFX standard components, with this step it became possible - there are some receipts on StackOverflow, but more fragile and more difficult to support.

**Comment by ripcurlx** [comment]
Yes, I also think it won't be a nice solution, but I could also live with a hack, if everyone can read what we have to say in any language ;-)

**Comment by ripcurlx** [comment]
Actually, if find it kind of strange that this is not supported out-of-the-box by javafx.

**Comment by ManfredKarrer** [comment]
Yes thats a weak part of JavaFX. Flash/Flex had that even >10 years ago...

**Comment by ripcurlx** [comment]
Will be released as soon as [UI-improvement branch](https://github.com/bisq-network/exchange/tree/UI-improvements) goes live

**Comment by cbeams** [comment]
Hey @ripcurlx, please don't close issues like this until code is actually on `master`. We never know what's going to happen, the `UI-improvements` branch might not get merged, there might be a delay, etc. Like I just mentioned in https://github.com/bisq-network/exchange/issues/1092#issuecomment-357919773, it's better to have a tracking issue like this that keeps us aware that work is not finished until code is on `master` and ready to ship in the next release.

**Comment by cbeams** [comment]
This sort of thing, by the way, is part of the reason for the plan to do away with *all* feature/topic branches in the bisq-network/exchange repository (#1190) . Can discuss more fully elsewhere.

**Comment by ripcurlx** [comment]
ok - will keep it that way with all other issues.

**Comment by ripcurlx** [comment]
Closing as complete.
