### ISSUE TITLE
Streamline wording of support/dispute

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1081]
At the moment we have a support section, which actually is a section where all arbitration tickets/disputes are handled. Wouldn't it be better if we rename "Support" to "Disputes" and "Support tickets" to "Arbitration tickets", as we are not planning to have general support communication in this section?

**Comment by ripcurlx** [comment]
@ManfredKarrer @cbeams Do you have an opinion on that?

**Comment by ManfredKarrer** [comment]
I used support for technical problems (user opens with cmd+o before trade period is open) and dispute for trade issues (payment not received,...). It is also in the disputes slightly diff. used. Not strong opinion about it but I think "dispute" in case of a technical problem sounds a bit hard.

**Comment by ripcurlx** [comment]
True - forgot that you can open tickets manually as well. I guess I have to look at all the use cases again and will come with a suggestion afterwards.

**Comment by ripcurlx** [comment]
I'm closing this for now, as I don't see it as a pressing issue anymore.
