### ISSUE TITLE
Currency display settings do not affect available offers list

### ISSUE THREAD

**Issue by gdvine** [bisq-network/bisq#1084]
Steps to reproduce:

1. Remove some currencies on Preferences tab from "Currencies in market price feed list"
2. Go to Buy or Sell tab
3. See that offers including removed currencies are still visible

Expected result:
- Offers list respects currency filter settings and only shows those offers in which the user is interested.

**Comment by dhingra** [comment]
Hello,

Looking forward to contribute ,can I start with this issue? 
Thanks
R

**Comment by mrosseel** [comment]
@dhingra sure! If you haven't done so already, please follow the dev setup guide: https://github.com/bisq-network/exchange/blob/master/doc/build.md

**Comment by gdvine** [comment]
Thanks Rohit! The magic of open source, woohoo!

**Comment by dhingra** [comment]
@gdvine Checked-in code and created PR.

**Comment by gdvine** [comment]
Looks good, thanks again!

**Comment by ripcurlx** [comment]
Closing as complete.
