### ISSUE TITLE
[feature] Keybase integration?

### ISSUE THREAD

**Issue by tr37ion** [bisq-network/bisq#1085]
How about integrating [Keybase](https://keybase.io/)? They have a PGP trusted [Messenger](https://keybase.io/download) which could be used to build a Web of Trust around transactions. They have an [API](https://keybase.io/docs/api/1.0), too.

This could be an optional feature as Bisq is designed around anonymous transactions. Possibly, this could help people staying in contact with each other. 

Adding small URL link button to [Keybase.io](https://keybase.io/) would link Bisq to Keybase, if wanted by the user. Similar to [Keybase's browser addon](https://keybase.io/docs/extension) which optionally links social network users to Keybase accounts.

Only people who like to be contacted link their Keybase account and only people who want to use it press the link button.

**Comment by jonathancross** [comment]
FYI: Keybase also has a Tor hidden service: `fncuwbiisyh6ak3i.onion` and a simple API get seems to work from that domain too: http://fncuwbiisyh6ak3i.onion/_/api/1.0/user/lookup.json?usernames=jcross

**Comment by tr37ion** [comment]
And as I am thinking of it. It can be the other way around, too. Bisq users register their Bisq accounts with Keybase.

I somehow like the idea of having the Bisq users provide Keybase accounts with their trades. 

Bisq developers could even start a Keybase Team and use the encrypted file system for signed release downloads and/or they use the encrypted git for teams. 

Nevermind, I'm possibly too excited now. Nonetheless, devs may have a look into what [Keybase's Github repo](https://github.com/keybase) has to offer.

**Comment by jonathancross** [comment]
I'm an enthusiastic user of Kebase, but I don't think Bisq should be integrated with a centralized system. PGP keys can be of use in executing trades, and keybase can help to identify the correct pubkey, but I don't think we want to create any dependecies on them.

**Comment by ManfredKarrer** [comment]
@jonathancross I have not followed the thread yet as too busy with next release but my first guts reaction was the same. We prevent adding external dependencies as far as possible.

**Comment by tr37ion** [comment]
Actually you won't be depend on anything. It is just that there is a (optional) button which opens Keybase Messenger if the person allows so. 

@jonathancross Sure, I just thought there is something valuable if people want to offer verifying therePGP keys and trades without making Bisq depend on Keybase. 

@ManfredKarrer I might be an idea if you try [Keybase](https://keybase.io/docs/the_app/install_linux) first to get an idea what it is capable of. You might use it for development or key sharing, too.

Well, just what I was thinking of these days.

**Comment by ripcurlx** [comment]
As no one picked up this feature request for some time and there is already a setup process ongoing for rocket.chat (https://github.com/bisq-network/roles/issues/79), which covers the messenger part, I'll close this issue for now. Feel free to reopen if the other parts become more relevant again.
