### ISSUE TITLE
One pricenode does not receive all prices

### ISSUE THREAD

**Issue by mrosseel** [bisq-network/bisq#1088]
One of the price nodes is only returning 50 results for the /getAllMarketPrices instead of the normal 190+.
After a restart, this was fixed.

Suggested actions:
* enrich returned json with more info so this can be monitored better.
   * add a provider string to each price
   * add for each provider a field which indicates how many prices it returned

[normal_pricenode.txt](https://github.com/bisq-network/exchange/files/1552220/normal_pricenode.txt)
[small_pricenode.txt](https://github.com/bisq-network/exchange/files/1552221/small_pricenode.txt)

**Comment by ripcurlx** [comment]
Closing as complete.
