### ISSUE TITLE
Remove Floating Icon

### ISSUE THREAD

**Issue by Francewhoa** [bisq-network/bisq#1090]
Hi there Bisq enthusiasts :)

How do we remove Bisq floating icon? Which is display on all workspaces/screens?

Steps to reproduce this challenge

1. Using Debian 8 Jessie, using GNOME 3.14.1, download and install a fresh [Bisq 0.6.1 for Debian 64 Bit](https://github.com/bisq-network/exchange/releases/download/v0.6.1/Bisq-64bit-0.6.1.deb)
1. Open Bisq
1. Notice that a floating icon is display on top of everything, on all workspaces. For those not familiar with Debian, the “workspace” are screen(s). The user can have an unlimited amount of workspaces.
1. The first challenge is that the user is not able to remove, hide, or move this floating icon. The screenshot below shows the location of the challenge. **How do we remove that floating icon?** It’s a challenge because that floating icon is blocking the user from doing some frequent operations. Simply because they are located under the Bisq floating icon. A temporary fix is to close Bisq. Which remove that floating icon. But that’s unfortunate because in some cases it’s useful to keep Bisq open.
1. The second challenge is that it is not clear what that floating icon is for. It seems to do nothing. If the user click on it nothing happens. Same result with left or right clicks. **What is the floating-ufo-icon for?** LOL ;)

![challenge-floating-icon---2017-12-14---14 01 04---selection_001---francewhoa](https://user-images.githubusercontent.com/119942/34016715-c622663c-e0d7-11e7-86b0-afaf5d4e980f.jpg)

I searched the Bisq application configuration page, this [forum](https://bisq.community/search?q=floating%20icon) and this [documentation](https://github.com/bisq-network/exchange/wiki) but found no answer

I would be happy to contribute testing and documentation if needed

Cheers,

Francois

**Comment by Francewhoa** [comment]
It seems this icon is related to a **JaveEmbeddedFrame**. Which seems to be container for a permanent fixed tray notification floating over all other windows?

There is a related challenge in this ticket at https://askubuntu.com/questions/100409/extra-javaembeddedframe-window-when-using-jdownloader

The above is just information that might help to narrow down the source of the challenge. Any suggestion to resolve this challenge?

**Comment by ripcurlx** [comment]
@Francewhoa Is this still occurring with our latest version 0.9.1 (different SDK)? If not please reopen this issue.

**Comment by xuhcc** [comment]
I'm seeing this floating icon too. On 0.9.1 it is still present.
System: ArchLinux, Gnome 3.30, with TopIcons Plus extension.
