### ISSUE TITLE
Show tor initialization steps on startup

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1092]
If startup time takes longer than normal, it would be great to have any kind of indication where in the initialization process you actually are.

e.g. writing it like:
- (1/4) Connecting to Tor Network...
- (2/4) Tor node created
- (3/4) Hidden service published
- (4/4) Initial data received 
> you hardly see the last message as it is shown only a brief amount of time

![step 1](https://user-images.githubusercontent.com/170962/34040327-76eb1a8e-e193-11e7-977f-55cc00d6363a.png)
![step 2](https://user-images.githubusercontent.com/170962/34040326-76d234c4-e193-11e7-9196-8bdb163c7d54.png)
![step 3](https://user-images.githubusercontent.com/170962/34040325-76b70a64-e193-11e7-9700-96581e85a24d.png)
![step 4](https://user-images.githubusercontent.com/170962/34040324-769db44c-e193-11e7-8c2e-9e2f0f225f01.png)

**Comment by ripcurlx** [comment]
Will be released as soon as UI-improvement branch is merged

**Comment by cbeams** [comment]
Hey @ripcurlx, please don't close issues like this until code is actually on `master`. We never know what's going to happen, the `UI-improvements` branch might not get merged, there might be a delay, etc. And even if when it does get merged, it's going to get merged into `Development`, which is still not `master`. It's better to have a tracking issue like this that keeps us aware that work is not finished until code is on master and ready to ship in the next release.

**Comment by ripcurlx** [comment]
Closing as complete. Was merged to master by @ManfredKarrer already.
