### ISSUE TITLE
Documentation Bisq Logo

### ISSUE THREAD

**Issue by Francewhoa** [bisq-network/bisq#1094]
This ticket can be close. I needed to create it to upload the Bisq logo to Github. Which in turn created a permanent link to this logo. Which in turn is linked to this [documentation page](https://github.com/bisq-network/exchange/wiki).
![bisq-logo](https://user-images.githubusercontent.com/119942/34069130-e5f48f62-e1fe-11e7-8a00-753e25a897f4.png)

**Comment by cbeams** [comment]
Thanks, @Francewhoa. It would be good to chat a bit about directions to take with documentation before diving too deep. The bisq-network/exchange wiki has been around for a while, but we've been focusing on bisq-network/docs more recently, for reasons I can go into on Slack if you'd like to discuss there. In any case, contributions to documentation are super welcome and badly needed. Let's sync up, yeah?

**Comment by Francewhoa** [comment]
Hi @cbeams :) Collaboration sounds great. As you know I'm new to both Bisq and the bisq-network/exchange wiki and I didn't know about the bisq-network/docs. I'm signing-off for today. I'm happy to discuss on Slack as soon as I'm free. How about at Slack #docs? Feel free to suggest another convenient location.

I have an extensive experience writing documentation. I’m interested to contribute writing additional documentation for Bisq. Starting with a focus on documentation for newcomers end-users to both crypto coins and Bisq. Two days ago I posted a related message in the Bisq forum at https://bisq.community/t/contribute-documentation/3823
