### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Zahnentferner** [bisq-network/bisq#1096]
In the "open trades" screen, the sentence "You needs to wait for at least..." has  typo. The word "needs" should be replaced by "need".

**Comment by cbeams** [comment]
Thanks, @ceilican. /cc @csacher.

**Comment by montvid** [comment]
Yes saw this too.

**Comment by thijstriemstra** [comment]
Can't find this sentence in the code though.

**Comment by cbeams** [comment]
```
~/Work/bisq-network/exchange[master]
$ git grep -l 'needs to wait'
common/src/main/resources/i18n/displayStrings.properties
common/src/main/resources/i18n/displayStrings_el.properties
common/src/main/resources/i18n/displayStrings_es.properties
common/src/main/resources/i18n/displayStrings_hu.properties
common/src/main/resources/i18n/displayStrings_pt.properties
common/src/main/resources/i18n/displayStrings_ro.properties
common/src/main/resources/i18n/displayStrings_ru.properties
common/src/main/resources/i18n/displayStrings_sr.properties
```

**Comment by thijstriemstra** [comment]
Yea a github search can do that as well: https://github.com/bisq-network/exchange/search?utf8=%E2%9C%93&q=You+needs+to+wait+for+at+least&type=

But it uses `{0} needs to wait for at least` so I guess {0} gets replaced with 'you'?

**Comment by cbeams** [comment]
Correct.
