### ISSUE TITLE
Money were taken out of my wallet 3 times in a row while my offer were timed-out error :(

### ISSUE THREAD

**Issue by Yonnis01** [bisq-network/bisq#1099]
NO, please don't close this issue/file because my problems are not resolved!!!

And YES tr37ion, I did sent 2 different posts (one several days ago and one earlier today) because I do have 2 different problems:

1st. The 1st post was about the ERROR on the system and being charged a total of 0.010165 for 5 different offers I made and each one of them, before it went through, it came back as ERROR but each time money were take out from my account. All the details about that were sent to you in my 1st post which I sent a couple of days ago and, because I didn't get any answers, I sent it again earlier today.

2nd. The 2nd post was the 2 offer I made that finally went through, but after 5 days and a half, neither one received any confirmation and I wasn't able (it didn't allow me) to start the payment. 
Please see the 2 attached PDFs with screen shots of the BISQ system pages where, as of earlier today, with just 36 hours left, I has still waiting for the confirmations of the transaction to go through in order to start my payment... 

I looks like after all, my deposit of 0.06 BTC was locked and held for this two offers, but the confirmation for Sellers BTC it never came, or at least it didn't came as of noon today which is to late to finalize this transaction. I had no idea that your system has so many problems and is so faulty... We need to post this somewhere and to make everyone aware of all this issues I've been having I've been having with Bisq within the last week... 

I did used your system 3 other times last week and everything went through smoothly, so I know that is nothing wrong that I did on my side to slow down the process, but your Bisq system it has (or had) several issues with withdrawing funds with Error messages without the offer going through as mentioned on my 1st post from several days ago.

Now I need your help and with my last 2 offers which I made over 5 and 1/2 days ago and for which I still didn't receive confirmations as of noon today and which made it impossible on my end to send the payment...

Can you please help with all this mess?

I do need/expect answers and resolutions for both of my posted problems, but especially for my 2nd post with the 2 Offers transactions ID# 4159602 and ID# GJ3fBVD which are still waiting for confirmation for starting my payment but less than 34 hours to be processed and to be finalised while tomorrow is Sunday and Monday is Christmas and all the banks are closed... 

Please advice ASAP...   Thank you!

Respectfully,
Yonni S

Attached files:

![bisq tradeid 4159602](https://user-images.githubusercontent.com/34652876/34324498-94cf7d24-e832-11e7-89a5-ad4f903e89d0.png)

![bisq tradeid gj3fbvd](https://user-images.githubusercontent.com/34652876/34324500-9b5da7ce-e832-11e7-85f9-0f5ef8f75070.png)

**Comment by montvid** [comment]
See #1087 I am waiting for a refund too!

**Comment by cbeams** [comment]
@Yonnis01 and @montvid, I am closing this issue. If you have not done so already, please contact me directly at chris@beams.io, and we'll get this worked out together. Thanks.

/cc #1044
