### ISSUE TITLE
BISQ - Lost Transaction Fee

### ISSUE THREAD

**Issue by Previncoin** [bisq-network/bisq#1107]
I  thought the system would take the transaction fee automatically, by the time I realized that it had to be submitted manually hours had passed & the transaction timed out. When I clicked cancel a pop-up box said the fee would be returned to my account but it never arrived, I lost over £200 can it be retrieved?

**Comment by cbeams** [comment]
@Previncoin, please send me an email at chris@beams.io with the transaction id of the transaction that timed out. Note that under no circumstances should you have lost £200. You would only have lost your Bisq trading fee and Bitcoin mining fee, and both of these can be reimbursed.

When you email me this information, I will respond to you with a new issue ID you can use to track the progress of your reimbursement. Thanks.
