### ISSUE TITLE
Add "Cash in person" as a payment option

### ISSUE THREAD

**Issue by mutagenfork** [bisq-network/bisq#1110]
See #1101 for the rationale for this feature request. 

Per @dan-da 's request, here's a proposed protocol for doing "Cash in person" with the bisq network.  

Find a meeting place:

Meet in a public place.   Scammers and muggers are a lot less likely to try anything with witnesses around.   An ideal location will meet the following criteria: 

* Public Location - Are there plenty of people around?
* WiFi Access - Is there free or cheap public WiFi access in the area?
* Security - Are there security cameras or security guards in the area?

Some examples of places that meet these criteria:

* restaurants
* coffee shops
* bookstores
* hotel lobbies
* bank lobbies 
* libraries
* mall
* casino or poker club

A location with security cameras adds an extra layer of security to a trade. If the other party does try to rob you, you'll have physical evidence in a recording that can help the authorities track the offender.  

Muggers are also a lot less likely to rob you if there's a guard with a gun a few yards away.  Consider bringing along a second person as an additional source of additional security and protection.  

Arrange the transaction:

* Agree to the price and procedures in advance.  Send them a copy of these instructions so that they know what to expect, and ask them to confirm that they will follow these procedures.  
* Explain to them that if they talk about any criminal activity, you will end the transaction immediately and walk away. 
* Explain that if they deviate from the procedure you will walk away.  
* Try to schedule the transaction during day-light hours (6 am - 6 pm).  Crimes are more frequent after dark.    
* Tell them how long you will wait for them if they are late, and ask them how long they will wait for you. 
* If you will be bringing a second person, let the buyer know, so that they don't freak out when they see two people there.
* Explain to them how long network confirmation time will likely take, so that they don't get nervous if the funds don't immediately show up in their wallet. 
* Once you've agreed upon a time and location, put the meeting on your calendar.  
  
Items to bring: 

* Laptop with a copy of the bisq software running on it.  Consider using an inexpensive "burner" laptop that doesn't have anything else of value on it.  
* [Dri-Mark Smart Money Counterfeit Dual Detector (Pen and UV Light)](https://www.amazon.com/Smart-Money-Counterfeit-Detector-Light/dp/B004JOHZ0Q/)  
  
Before going to the meeting place:

* Confirm with the buyer the time and location the both 24 hours before and one hour before you head to the meeting place.  
* Exchange phone numbers, so that you can update each other if there are any delays.  
* Make sure that they know that they should have the exact amount of cash in hand in an envelope--you don't want to have to wait for them to get cash from an ATM.  
* Describe the clothes you will be wearing, and where you will be seated so that they can easily find you.   
* Offer to buy them a drink or food, so you can order before they arrive.  Given congestion on the Bitcoin network, it can take a long time for transactions to confirm. 

At the meeting place:

* Set up your laptop with a copy of the bisq software.  
* Arrive early, and try to find a location that is visually isolated from other patrons (a booth, for example), but close enough to other people that you can call for aid if necessary.  (You don't want to be counting and authenticating large amounts of cash in front of strangers.)  
* Make that you can connect to the Wifi network with your laptop.  
* Order drinks/food.  (You don't want the waitstaff to be bothering you while you're in the midst of doing the exchange.) 

When the buyer arrives:

* Greet them, shake their hand, and invite them to take a seat. 
* Give them time to set up their laptop and connect to the Wifi.  
* Confirm that they've read your instructions regarding what to expect.  If they haven't read them yet, ask them to review them now. 
* Consider doing a small transfer at first to make sure that everything is working, and that you have their wallet address correct.  
* If selling large amounts, consider breaking up the trade into smaller increments.  This will reduce the risk to them that you will try to grab the cash and run. 
* Once you're satisfied that everything is working properly, and they know what to expect,  ask them to count the bills to confirm that they have the proper total amount.  
* Assuming they have the proper amount, ask them to place the first increment of cash on the table.  
* Count the bills and test them for authenticity.  Before reaching for the bills, remind them that you will be testing them for authenticity.    Using the Dri-mark men, make a small mark on paper currency: dark mark means counterfeit, light mark passes test.  (Note, however, that some counterfeit papers can pass this test.)    Look for other [anti-counterfeit features](https://www.youtube.com/watch?v=Ybt04VtOmzE) on the bills.  
* As you confirm the bills, place them under a notebook or book on the table. 
* Once you've confirmed that the bills are authentic, transfer the cryptocurrency to them with the bisq app.  
* Once the transaction has been confirmed, remove the bills and place them in your wallet.
* Repeat this process until the entire transaction has been completed.

**Comment by dan-da** [comment]
@mutagenfork Thanks for in-person writeup.

Is it accurate to say that you envision no arbitration role or responsibility for bisq?   But rather only to play match-maker for the exchange...

whereas the cash-by-mail writeup does suggest arbitration via review of video evidence....

**Comment by mutagenfork** [comment]
In general, I think the arbiter would find it difficult to decide who was right in a dispute about an in-person cash trade, unless the entire transaction were filmed.  

For example, if the seller simply grabbed the buyer's cash and ran, the buyer could complain to the arbiter.  If there were video footage of the theft, the arbiter could review the tape, and decide for the buyer.

**Comment by mutagenfork** [comment]
I do think using bisq to record the outcome of the transaction is useful though.  A record of completed transactions would help foster trust.

**Comment by dscotese** [comment]
The participants to a trade who end up in a dispute ought to be responsible to provide the arbiter with evidence supporting their claim.  Arbiters ought to be able to specify deadlines and such.  The victim of any disputed in-person trade can collect statements from individuals present (strangers even) and (if such witnesses are willing) collect info about who they are and why they were there so that a comprehensive picture of what happened can be pieced together.  If a scammer ever successfully navigates this to the point where the arbiter makes the wrong decision, the victim will have a fantastic story to tell, depending on the amount of evidence collected.  Further, it makes sense that even after an arbiter has decided, the case can stay open so that either party can provide more evidence (digging themselves deeper or redeeming themselves as the case may be).  I like to think (and really believe that technology makes this so) that the truth eventually comes out as long as people keep looking.

**Comment by blabno** [comment]
Parties could exchange printed signatures confirming that they have received stuff from the other side.
Signatures could be done using Bisq wallet or gpg (public key would have to be included in the trade).
Probably we could even have some mobile app to display, scan and verify those signatures.

**Comment by ripcurlx** [comment]
Closing as complete as F2F is now already available on Bisq.
