### ISSUE TITLE
Seednode no longer working for regtest

### ISSUE THREAD

**Issue by citkane** [bisq-network/bisq#1114]
Up until about 2 days ago, master branch was working perfectly when starting a seednode for regtest:
```
java -jar seednode/target/SeedNode.jar --baseCurrencyNetwork=BTC_REGTEST --useLocalhost=true --myAddress=localhost:2002 --nodePort=2002 --appName=bisq_seed_node_localhost_2002
```

Today, after compiling the latest master, starting a seednode fails with error:
`[checkCryptoThread] ERROR i.b.c.c.Encryption: JCE cannot authenticate the provider BC`

log attached: [seednode.log](https://github.com/bisq-network/exchange/files/1579920/seednode.log)

I have tried: 

- clearing out the maven repo first (by deleting ~/.m2) and compiling again. 
- With and without edits to 'DevEnv.java'.
- First deleting  ~/.local/share/bisq_seed_node_localhost_2002

The error however persists.

**Comment by ManfredKarrer** [comment]
That error is related to the bouncycastle jar. I got it reported as well from @ripcurlx but I did not had time to look into the issue. Are you running from jar or from the IDE (IntelliJ)? From intellij it seems it works. Do you have 2 different JDKs? You can try to look at the commit history of the pom file of the seednode module. I changed there a bit, try the old version to see it it was the reason...

**Comment by citkane** [comment]
I am running from jar: `java -jar seednode/target/SeedNode.jar --baseCurrencyNetwork=BTC_REGTEST --useLocalhost=true --myAddress=localhost:2002 --nodePort=2002 --appName=bisq_seed_node_localhost_2002`

**version:**
javac 1.8.0_151
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

Two days ago this was working perfectly and I have changed nothing in my environment, so I am sure that my JDK PATH/s are configured correctly.

**Comment by ManfredKarrer** [comment]
Can you try to revert the pom file to the previous version. The changes there probably caused the  issue.

**Comment by citkane** [comment]
Confirmed @ManfredKarrer 

**Proof:**

I compiled with the seednode's .pom from Dec 19 and running the seednode .jar resulted in the same error and log as described above.

Using the seednode's .pom from Nov 24 I updated the version to `<version>0.6.2</version>` and the compile succeeded. Seednode .jar ran successfully and clients were able to connect. The .pom later than Nov 24 would appear to have a regression.

**Comment by mrosseel** [comment]
This is the change which gives an error, before the bouncycastle classes where not packed into the shade jar, now they are. On my system with java 1.8.0-112 everything works, so it's probably both the java version and the pom change. Of course it should work on the latest java so maybe the change should be reverted.

![screen shot 2017-12-22 at 14 40 03](https://user-images.githubusercontent.com/1465310/34299954-1f15f926-e726-11e7-97bc-53f0a7deba18.png)

**Comment by citkane** [comment]
I compiled master for v0.6.3 today and the issue as I described at https://github.com/bisq-network/exchange/issues/1114#issue-283945763 is gone. Thanks.
