### ISSUE TITLE
Verification fail

### ISSUE THREAD

**Issue by HanZeno** [bisq-network/bisq#1116]
had gpg verification fail of Bisq-0.6.2.dmg.asc (F379A1C6.asc) today. Im noob at GPG so probably it's just me, but please have a look. Also maybe the verification guide could be written better.

**Comment by DarkSatyr** [comment]
The same for me
Maybe I'm wrong somewhere, but I've tried to do next:
`gpg --keyserver pgp.mit.edu --recv-keys 1DC3 C8C4 316A 698A C494 039C F5B8 4436 F379 A1C6
gpg --digest-algo SHA256 --verify /Users/user_1/Downloads/F379A1C6.asc`

Also tried to import key, but had no success:
`gpg --import /Users/iastremskyi/Downloads/F379A1C6.asc`

At the end got - "gpg: verify signatures failed: Unexpected error"
Please help

**Comment by DarkSatyr** [comment]
ok, looks like this is my mistake, I've tried to use Public Key instead of signature from here https://github.com/bisq-network/exchange/releases/tag/v0.6.2

**Comment by HanZeno** [comment]
ManfredKarrer : "Bisq-0.6.2.dmg.asc" doesn't provide any signatures upon GPG keychain sign verification on mac os x 
[https://imgur.com/a/UlTe6](url)

Please just confirm that it's signed instead of closing the topic.

**Comment by ManfredKarrer** [comment]
Just checked again and is valid for me:

gpg --digest-algo SHA256 --verify Bisq-0.6.2.dmg{.asc*,}
gpg: Signature made Wed Dec 20 21:22:51 2017 CET
gpg:                using RSA key 1DC3C8C4316A698AC494039CF5B84436F379A1C6
gpg:                issuer "manfred@bitsquare.io"
gpg: Good signature from "Manfred Karrer <manfred@bitsquare.io>" [ultimate]

**Comment by HanZeno** [comment]
I get this hash 433d2636b73a0857433ce5c045ef8097a79e7cb4e899c3c5e8543288740d4e0a
for the .dmg file
running it manually through terminal.

But verifying the sign through GPG keychain, there's no signature showing. Im a novice so can't say why. Just get somebody else to verify it and then fine.
Again it's probably me, just nice to double check again.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by ManfredKarrer** [comment]
That is a different hash I get. How are you creating it?
$ shasum -a 256 Bisq-0.6.2.dmg 
4b774299d0fe8f2da5e3bd09b90bc1d72d21f203dadc80fdc3c5475e1f8cb3eb

**Comment by HanZeno** [comment]
Yes exactly:

Bisq-0.6.1.dmg
$ shasum -a 256 /Users/naturalenergy/Downloads/Bisq-0.6.1.dmg
433d2636b73a0857433ce5c045ef8097a79e7cb4e899c3c5e8543288740d4e0a

Bisq-0.6.2.dmg (just redownloaded)
$ shasum -a 256 /Users/naturalenergy/Downloads/Bisq-0.6.2.dmg
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by ManfredKarrer** [comment]
You downloaded from https://github.com/bisq-network/exchange/releases/tag/v0.6.2?
I downloaded again from https://bisq.network/downloads/ and got the same hash as above.
Do you have a proxy or anything or VPS? Can you try from another internet connection or computer? Please let me know once you found out what caused the issue.

**Comment by ManfredKarrer** [comment]
Ps: Don't run the file if the hash does not match 4b774299d0fe8f2da5e3bd09b90bc1d72d21f203dadc80fdc3c5475e1f8cb3eb

**Comment by HanZeno** [comment]
> You downloaded from https://github.com/bisq-network/exchange/releases/tag/v0.6.2?

YES

**Comment by ManfredKarrer** [comment]
I just downloaded again from https://github.com/bisq-network/exchange/releases/tag/v0.6.2 as well as from the bisq.network download page (links to the same URL). Both result in hash: 4b774299d0fe8f2da5e3bd09b90bc1d72d21f203dadc80fdc3c5475e1f8cb3eb

**Comment by ManfredKarrer** [comment]
@cbeams, @mrosseel: Could you make a test download with a sig check and post the hash to double check?

**Comment by HanZeno** [comment]
Manfred,
4b774299d0fe8f2da5e3bd09b90bc1d72d21f203dadc80fdc3c5475e1f8cb3eb
got the correct hash now. New download, new connection, from github.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by ManfredKarrer** [comment]
Did you find out what has changed? Check your internet connection to not be MITM attacked...

**Comment by HanZeno** [comment]
1) am not too tech savy, so I calculated the hash wrong by not being in the right directory I think.
$ shasum a- 256 from standard directory, not "Downloads", it gives a different hash..

2) just now with GPG I just got verification of the Bisq-0.6.2.dmg.asc file for the first time. Not sure what changed. Maybe restarting both GPG/computer

So everything seems to be ok, sorry for bothering you.

Anyway it's still too complicated for ordinary people to verify and get going .. and super important for anyone going on a peer to peer exchange not to have a sniffing crack on the installed version. Would be great if this verification process could be simpler. Decentralised exchanges will have a great future. I believe the centralised are going to have a MtGox repeat either by printing endless tethers, being shut down or simply exit scams (etc).

Looking forward anyway to get going with Bisq and spread the word! Keep up the great work

Greets!

[Skærmbillede 2018-01-04 kl. 21.32.45.png]

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by ManfredKarrer** [comment]
Ah good it was nothing serious!
I understand that for not tech-savvy people such things are hard, because of that we have added the in-app-downloader which does all that download and sig checks in the app. Then only the first time download need to be done manually.

**Comment by HanZeno** [comment]
Hi Manfred,
I had a idea today, qua protecting the market/adoption in BTC throughout the next run up from single point of exchange failures (Bitmex..)

What would it cost for "the team" to develop a derivative platform on top of Bisq code already in place?
Meaning you have an interface like Bitmex but the core technology/software model is based upon Bisq. We'd have to brainstorm about if it could be done, like democratisation of an insurance fund, multi sigged etc

Protecting people from system due liquidations will be important in the sense they're playing a major part in the inflationary impact of shorting leverage (Bitmex printing x100 leverage synthetic XBT .. and vice versa doing their system overload and barting to shakeout any pressure of people longing).

We obviously would need to exchange more ideas and if it could at all be technically done etc

Loving Bisq so far..

Han

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
