### ISSUE TITLE
GBYTE has 9 decimal places, not 8

### ISSUE THREAD

**Issue by TheButterZone** [bisq-network/bisq#1118]
When I type .xxxxxxxxx in a create buy bitcoin offer, the 9th number keeps getting truncated out.

And BTC has 8, not 4, anything past 4 keeps getting truncated out of the BTC to buy, minimum amount of BTC, security deposit fields.

**Comment by ripcurlx** [comment]
@TheButterZone Is there a reason why you need this precision? Atm for buying BTC with any altcoin we show 8 decimals as you stated above.

**Comment by ripcurlx** [comment]
I'm closing this issue for now. Feel free to reopen if this is a pressing issue.
