### ISSUE TITLE
sending message for support tickets 

### ISSUE THREAD

**Issue by b3dk7** [bisq-network/bisq#1120]
When sending messages to the arbitrator via the support window, messages seem to be forever in the pending "sending message..." stage. This stops the user from sending a new message. Only restarting the program seems to fix the issue. 

![support](https://user-images.githubusercontent.com/8342083/34356643-3a840ac0-ea48-11e7-8de8-e05361d0cd9b.png)

**Comment by cbeams** [comment]
We've had some network reliability issues lately that might explain this behavior. Have you been able to communicate with your arbitrator in the meantime?

**Comment by b3dk7** [comment]
yes i have, thanks :)

**Comment by khowell30** [comment]
Same issue as recently as yesterday.  It appears messages are posted, but sometimes x2.  Arbitrator is able to respond to some of them, so I KNOW some of them are going through.  Just updated to 0.6.3 if fix is included.

**Comment by cbeams** [comment]
Closing as superseded by #1173
