### ISSUE TITLE
Preferred currency dropdown renders duplicate currency. 

### ISSUE THREAD

**Issue by dhingra** [bisq-network/bisq#1123]
Steps to reproduce:

1. Remove all selected(selected -1) currencies from "Display national Currencies".
2. Restart GUI

![1084-preferredcurrency](https://user-images.githubusercontent.com/7157372/34369978-7869ccee-ea8e-11e7-84d0-ebc2a6cebc99.png)

![1084-preferredcurrency-1](https://user-images.githubusercontent.com/7157372/34369977-785ecb3c-ea8e-11e7-8dcd-1065bde837a5.png)

**Comment by cbeams** [comment]
Closed as superseded by PR at #1124.
