### ISSUE TITLE
error occurred when reading SPV chain file. 

### ISSUE THREAD

**Issue by wellfedjockey** [bisq-network/bisq#1127]
error occured when reading SPV chain file.
it may be may be that the SPV chain file is corrupted.

Error Message: org.bitcoinj.store.BlockStoreException: corrupted block Store: could not find chain head
00000000000000000...
File Path: ...
Do you want to delete it and start a resync?

I tried that but the same message keeps popping up

**Comment by ManfredKarrer** [comment]
Did you do the delete and resync with 2 restarts? If so and it failed again try to delete it manually. The bisq.spvchain file is in the application folder (Account/Backup -> button to open it) inside the btc_mainnet/wallet/ folder. Just delete it and restart. Wait until all is synced again (can take a while) and then restart again.

**Comment by wellfedjockey** [comment]
That worked great.  Thank you
