### ISSUE TITLE
Urgent: Arbitrator cannot read my responses

### ISSUE THREAD

**Issue by mtausk** [bisq-network/bisq#1134]
Arbitrator wants to close the deal because he hasn't read my responses. It looks like he does not get them. My money is in danger!

Trade ID: IEK7SI-898492e1-84ab-4a05-ab9e-07ee7419d091-061

Thanks.

**Comment by cbeams** [comment]
Thanks, @mtausk for opening this. I see the new dispute ticket you opened, and will continue this conversation in-app.
