### ISSUE TITLE
Wrong date on export folder path.

### ISSUE THREAD

**Issue by BranndonWork** [bisq-network/bisq#1137]
I'm new to Bisq. After installing, setting up, then backing up my account, the folder created has a date of `bisq_backup_2018-12-31-xxxxxx` which is a year ahead. I assume it's a new years related bug. I searched the codebase and couldn't track down the portion responsible for creating this date.

**Comment by cbeams** [comment]
Thanks, @BranndonWork. The relevant code is here: https://github.com/bisq-network/exchange/blob/11c5c92879d2dce163920d5051622497a8f9ba22/gui/src/main/java/io/bisq/gui/main/account/content/backup/BackupView.java#L149-L150

Nothing obvious to me at a glance. Would be interesting to see if anyone else can repro this today.

**Comment by cbeams** [comment]
Just repro'd it myself:

![image](https://user-images.githubusercontent.com/301810/34461413-8dd91b40-ee29-11e7-9b07-d52e7a30ae74.png)

The code is so simple it makes me wonder if this is a JDK bug. Checking it out now.

**Comment by cbeams** [comment]
Indeed, it looks like this issue has nothing to do with Bisq:

```
$ cat Main.java
import java.text.SimpleDateFormat;
import java.util.Date;

public class Main {
    public static void main(String... args) {
        String dateString =
            new SimpleDateFormat("YYYY-MM-dd-HHmmss").format(new Date());

        System.out.println(dateString);
    }
}

$ javac Main.java
$ java Main
2018-12-31-125536
```

**Comment by robinhowlett** [comment]
`YYYY` is week-year, not calendar year. Use `yyyy` instead.

See https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html

**Comment by cbeams** [comment]
Thanks, @robinhowlett! (and @jkuipers, who reported the same fix via Twitter)

I've just fixed this in 604a9b1.

**Comment by BranndonWork** [comment]
Awesome! So glad that I helped a tiny bit. Would have been great to have submitted the fix myself. I'm keeping an eye on this project and would love to assist if I find the right task.

**Comment by cbeams** [comment]
Look at issues labeled `good first issue` and/or `$BSQ bounty`.
