### ISSUE TITLE
OutOfMemoryError in Bisq 0.6.2

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1138]
I just received the following report from a user:

> I think version 0.6.2 of Bisq has a java memory
> leak, I have several occurrences of the platform hanging if you leave it
> running for 24 hours or more, I had a couple of instances of a java out
> of memory error:
> 
> ```
> Dec-28 15:44:41.475 [Save-file-task-8323] ERROR i.b.c.s.FileManager:
> Error in saveToFile toProtoMessage: PersistableNetworkPayloadCollection,
> /home/user/.local/share/Bisq/btc_mainnet/db/PersistableNetworkPayloadMap
> Dec-28 15:44:41.483 [Save-file-task-8323] ERROR i.b.c.s.FileManager:
> Error at saveToFile,
> storageFile=/home/user/.local/share/Bisq/btc_mainnet/db/PersistableNetworkPayloadMap
> java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
>        at
> io.bisq.common.storage.FileManager.saveToFile(FileManager.java:196)
>        at
> io.bisq.common.storage.FileManager.saveNowInternal(FileManager.java:177)
>        at
> io.bisq.common.storage.FileManager.lambda$new$0(FileManager.java:72)
>        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>        at
> java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
>        at
> java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
>        at
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>        at
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>        at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.OutOfMemoryError: Java heap space
>        at
> com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:68)
>        at
> io.bisq.common.storage.FileManager.saveToFile(FileManager.java:191)
>        at
> io.bisq.common.storage.FileManager.saveNowInternal(FileManager.java:177)
>        at
> io.bisq.common.storage.FileManager.lambda$new$0(FileManager.java:72)
>        at
> io.bisq.common.storage.FileManager$$Lambda$104/1832661523.call(Unknown
> Source)
>        ... 6 common frames omitted
> ```

**Comment by llhoppy** [comment]
I just had another instance of this error, screenshot attached
![java heap space screenshot_2018-01-02_08-52-22](https://user-images.githubusercontent.com/2623245/34479435-c6388ba8-ef9e-11e7-80bc-6ec12374291c.png)

**Comment by ManfredKarrer** [comment]
Which OS are you using? Do you remember how long it was running? We never saw outOfMemory issues on OSX or Windows but on Linux. Might be some OS specific issue.

**Comment by llhoppy** [comment]
Hi , I am running it on Qubes ,
Linux trade 4.9.56-21.pvops.qubes.x86_64 #1 SMP Tue Oct 17 23:58:50 UTC 2017 x86_64 GNU/Linux

the Qube runs :
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.10 (jessie)
Release:	8.10
Codename:	jessie

**Comment by ManfredKarrer** [comment]
How much RAM have you assigned? I think 2-4 GB should be ok, below might be problematic...

**Comment by llhoppy** [comment]
I have 2gig assigned

**Comment by llhoppy** [comment]
I increased my qube to 4gig memory just in case and left Bisq running , had another java heap space error this morning

**Comment by ripcurlx** [comment]
@llhoppy Do you still have this issue with the current (0.9.1) version? Feel free to reopen if it is still an issue.
