### ISSUE TITLE
Improve user experience for users with no BTC - "must have BTC to buy BTC" is a vicious circle

### ISSUE THREAD

**Issue by stefek99** [bisq-network/bisq#1140]
See my tweet: https://twitter.com/stefek99/status/947196764783771649

I suggest there should be an option along the lines:

- Alice no BTC prior to the trade
- Bob pays the transaction fee for both of them
- the exchange rate is adjusted to compensate for that

The core intention is to have more people on the platform, `must have BTC to buy BTC` is seriously no go...

See: https://www.cryptocompare.com/exchanges/bisq/overview
![image](https://user-images.githubusercontent.com/249703/34470529-6e9ad448-ef33-11e7-8c00-d6893388e2ac.png)

**Comment by stefek99** [comment]
Reading the docs: https://github.com/bisq-network/docs/blob/master/exchange/whitepaper.adoc#arbitration

> You must already have a small amount of Bitcoin to execute a trade (for paying the security deposit, trade fee and Bitcoin mining fee)

> Arbitrators need to lock away 2 Bitcoins, which are only returned when they step back from their service.

---

I'm thinking about incentives and motivations.

It is possible that someone want to genuinely grow the ecosystem and does the arbitration as a community service.

Chances are other arbitrators are doing this for profit.

There will be more profit if there are more trades.

There will be more trades if no prior BTC deposit required - and to remain fair with fees "no deposit" option will be reflected with exchange rate and / or some BTC claimed after the transaction.

![image](https://user-images.githubusercontent.com/249703/34471445-4b8a7ca8-ef4a-11e7-99bf-1feb59fc5f0a.png)

# I really want to see it grow!

**EDIT / UPDATE:** https://github.com/bisq-network/growth

Kind of egg / chicken problem... I really want to see the ecosystem grow. I'd love to trade on the platform and allow more people into space without centralised services such as Coinbase. Unfortunately, it is so easy to be centralised, so difficult to it fully peer-2-peer.

**Comment by alexej996** [comment]
Problem with the option you outlined above is that Alice can take all such offers at once and make every maker of such offer (Bob) to wait until the max trade period is over so he can open a dispute. Bisq is P2P network that uses Tor, there will be no way that I know of to stop someone from spaming the network in this way. And if there is at least one person that does this, it is enough to completely sabotage every such trade instantly.

**Comment by stefek99** [comment]
I hear you.

It makes sense - someone could spawn multiple instances - take all the open offers, system will be unusable.

We could add another element:
> so you don't have BTC to pay the fee, but we have a good news - selfie with the passport - because BISQ is P2P network we need to avoid spam attacks

I know that `selfie with the passport` is not anonymous, but the advantage of buying BTC without having BTC in the first place far outweighs the downside.

Not everyone is based in London, many people cannot simple go to Bitcoin ATM.

**Comment by alexej996** [comment]
We already have something like that (Starter pack on Bisq forum), but it is not part of the app as it seems like it would require some kind of centralization or another layer to the network with people who would take legal actions if users don't follow the protocol. Also, in my opinion, any system that requires government involvement is not optimal.

Starter pack is a subcategory on Bisq forum where users post offers to lend other users a small amount of BTC for the security deposit of the first trade. These users often require such documentation to insure their return.

Keep in mind that Bisq is not a company, it is a transparent open source organization (with the DAO coming up it will be even more decentralized as well).

Btw, there are ATMs (for example) in many countries and many cities. I found this website with a lot of them listed https://coinatmradar.com/

**Comment by stefek99** [comment]
You know my stance.

I'll be pushing towards wider adoption, even at a cost of partial centralisation / governance.

### What is our endgoal?

We can sit and watch LocalBitcoins / Coinbase being the first point of touch for crypto, or we can implement some clever arbitration mechanisms...

Game theory incentives:
* use your own BTC to pay fee have better rates
* upload your passport / ID to have better rates

People are rational, they'll understand why is this required.

Client-side PGP encryption with the public key of the certified arbitrator - looks safe enough to me - we are not holding any sensitive data in that way.

---

Again - you know my stance, I've made my point. I really want P2P distributes decentralised services to grow... Too bad usability is often poor, to gain adoption we need to level up.

_(companies like Coinbase and LocalBitcoins are charging fees and they have incentives to keep the volume high - here `0.5%` platform development fee might be justified - funds managed by DAO etc...)_

**Comment by alexej996** [comment]
Well, thank you for your opinion on this. It is always helpful to hear what other people think.
You can join our Slack for more discussions, just go to Bisq website and click on community tab to find an invite for Slack.

**Comment by stefek99** [comment]
Reddit: https://www.reddit.com/r/bisq/comments/7ni4yu/ive_encountered_bisq_at_34c3_tried_to_make_a/

Slack: https://bisq.slack.com/archives/C0336TYTG/p1515240848000034

_(people recognise my blue face avatar and I'm likely to stick with it for the foreseeable future)_

**Comment by ripcurlx** [comment]
@stefek99 @alexej996 Thanks for the thoughts and input, but I'm closing this issue for now as a lending market within the client is out of scope for the foreseeable future. We do need to soften the no-BTC  hurdle as good as possible, but I think it might be just pointers to other options (e.g. BTC atms,..) how to acquire your first BTCs in a safe way.
