### ISSUE TITLE
Not many offers on the platform - change the default view settings - reduce number of options (at least temporarily)

### ISSUE THREAD

**Issue by stefek99** [bisq-network/bisq#1141]
There are not many offers now.

At first I went to default `BTC / USD` and I was disappointed.

Maybe - until the volume picks up - there should be all available offer displays by default?

*(otherwise it looks empty and people are less likely to remain)*

<img width="1371" alt="pasted_image_01_01_2018__20_44" src="https://user-images.githubusercontent.com/249703/34470568-ac98295c-ef34-11e7-990f-f6c096753532.png">

**Comment by ManfredKarrer** [comment]
I think the user's default currency makes more sense as it is now. Offers are usually between 50-100. You might have hit xmas holiday time...

**Comment by cbeams** [comment]
Closed as unneeded
