### ISSUE TITLE
Support a 'CMD+Enter' keyboard shortcut for sending arbitration chat messages

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1144]
Currently, when using Bisq's arbitration chat interface, it is necessary to use the mouse to click the `Send` button. This is because focus gets "trapped" within the chat textarea once it has been established.

A `CMD+Enter` keyboard shortcut would solve this usability problem nicely.

![image](https://user-images.githubusercontent.com/301810/34498093-508648f2-f000-11e7-9492-0c4659e7ade6.png)

**Comment by Vrakfall** [comment]
Should also be `Ctrl+Enter` on Linux/BSD & Windows, shouldn't it?

**Comment by cbeams** [comment]
Yes 👍

**Comment by maskoficarus** [comment]
Fixed: https://github.com/bisq-network/exchange/pull/1160

**Comment by cbeams** [comment]
Closing as complete per https://github.com/bisq-network/exchange/pull/1160#issuecomment-355940678. Thanks @maskoficarus!
