### ISSUE TITLE
Can't restore wallet from seed Windows: Log attached

### ISSUE THREAD

**Issue by andromedona** [bisq-network/bisq#1145]
FWIW
[bisq.log](https://github.com/bisq-network/exchange/files/1598751/bisq.log)

**Comment by ManfredKarrer** [comment]
There was a NullPointerException at that line:
long date = restoreDatePicker.getValue().atStartOfDay().toEpochSecond(ZoneOffset.UTC);

Can you describe where and how did you restore? At account/seed words or at startup? Did you set the date?

**Comment by andromedona** [comment]
I didn't know the date so all I had were the seed words. It's not a huge deal as I can just set up a new one and transfer the assets from the old, but if there is an easy fix without knowing the date, that would be great. Thanks.

**Comment by ManfredKarrer** [comment]
You can use a date which is for sure older then when you started the wallet. I fixed the issues for the next release so if no date is set it will use 0.

**Comment by ripcurlx** [comment]
Closing as complete. If it should still occur in the current version feel free to reopen.
