### ISSUE TITLE
An error occurred when taking the offer.

### ISSUE THREAD

**Issue by hermanschutte** [bisq-network/bisq#1147]
An error occurred when taking the offer.

An error occurred at task: CreateTakerFeeTx
Exception: org.bitcoinj.core.ECKey$KeyIsEncryptedException

No funds have left your wallet yet.
Please try to restart your application and check your network connection to see if you can resolve the issue.Please try to restart your application and check your network connection to see if you can resolve the issue.

**Comment by ManfredKarrer** [comment]
Do you run from source or the binary? If from source be sure to follow exactly the steps at the build.md doc.

**Comment by hermanschutte** [comment]
It's run from the binary.

**Comment by ManfredKarrer** [comment]
Which OS do you use? 
Try to un-install and re-install Bisq. Make a backup first as on windows with uninstall your data directory might get deleted as well.

**Comment by hermanschutte** [comment]
It's macOS, Sierra 10.12.6. The offer is no longer available, so not able to see if re-installing fixed it though.
