### ISSUE TITLE
Cannot download[Windows 64bit]

### ISSUE THREAD

**Issue by scratlzj** [bisq-network/bisq#1149]
Cannot download via Chrome or Firefox web browser. No speed. Why? Any suggestion?

**Comment by alexej996** [comment]
You can't download Bisq binary from the website?
Here is the direct link to it https://github.com/bisq-network/exchange/releases/download/v0.6.2/Bisq-64bit-0.6.2.exe , so you can double check that is the actual problem.

It is pretty weird if that is the case, it is just like any other file that you download from the browser.
Try restarting your computer, that is always first thing you should try.
Other then that, what antivirus software are you using? Maybe it is giving a false positive.

PS: Always remember that you can compile Bisq from source, if you are up for little challenge.

**Comment by scratlzj** [comment]
Download successfully. But now I can't even connect to network through Bisq. btw: I live in China, probably that's why, and I already used a VPN.

**Comment by alexej996** [comment]
You should be able to connect by selecting bridges for Tor in Bisq, but I understand that this is not perfect. VPN should be unnecessary.
Besides, as far as I know, China's government blocks all VPN's that they don't have an insight into, so I doubt they are safe.

**Comment by ManfredKarrer** [comment]
@scratlzj Pluggable transports (Obfusc4 or meek) should work in china. It might take a while though to get connected.
