### ISSUE TITLE
MadCoin adresse verification failed

### ISSUE THREAD

**Issue by feydreva** [bisq-network/bisq#1151]
Hello, 

When I enter my MDC address in the Altcoin account , i get the error Adress validation failed because it does not match the structure of a MDC address : 
my address is : mPQVWKBYeaP2An2CRMng1LbAj7kTsH7mNk

http://block.madcoin.life:3001/address/mPQVWKBYeaP2An2CRMng1LbAj7kTsH7mNk

**Comment by ManfredKarrer** [comment]
Please get in touch with MADCOIN devs to fix their address validation.

**Comment by ManfredKarrer** [comment]
Merged to dev branch

**Comment by cbeams** [comment]
> Merged to dev branch

What got merged to the dev branch?
