### ISSUE TITLE
Add payment method Payeer

### ISSUE THREAD

**Issue by neomeo** [bisq-network/bisq#1152]
Payeer is a 3rd party payment processor, they generally process credit and debitcard payment. some bitcoin exchange like livecoin and yobit already using them for bitcoin trading.

**Comment by alfsbs** [comment]
Issue moved to [bisq-network/payment-methods #9](https://github.com/bisq-network/payment-methods/issues/9) via [**ZenHub**](https://www.zenhub.com/)
