### ISSUE TITLE
Bisq doesn´t open! Attached screenshoot!

### ISSUE THREAD

**Issue by munozfrancisco** [bisq-network/bisq#1157]
After installation, I was trying to restore a bisq wallet by seed. I think after that, the program doesn´t open. Happy because my wallet has been empty before this issue.

![screenshoot bisq](https://user-images.githubusercontent.com/19628554/34646232-59baf8a8-f395-11e7-9038-0068df25a715.jpg)

**Comment by munozfrancisco** [comment]
attached log file
[bisq.log](https://github.com/bisq-network/exchange/files/1609463/bisq.log)

**Comment by mrosseel** [comment]
Which version was your old wallet? If it comes from a too old bisq version,
wallet seeds are not compatible.

**Comment by munozfrancisco** [comment]
I don´t remenber, but was in december. Anyway i will be happy only if the program would open to trade!

**Comment by cbeams** [comment]
Issue moved to [bisq-network/support #2](https://github.com/bisq-network/support/issues/2) via [**ZenHub**](https://www.zenhub.com/)
