### ISSUE TITLE
Fiat currency pairs display reversed

### ISSUE THREAD

**Issue by gdvine** [bisq-network/bisq#1158]
In the main currency pair dropdown at top, fiat/BTC pairs are displayed backwards – they say BTC/USD for example, but are displaying how many USD are needed to buy one BTC. Should say USD/BTC etc.

**Comment by gdvine** [comment]
By the way, how do I apply labels to issues in the Bisq Exchange repo? It doesn't give me the option. For example, this one is a trivial bug.

**Comment by mrosseel** [comment]
Isn't this the way it's displayed in other exchanges such as poloniex? It's
counterintuitive but 'standard'

**Comment by gdvine** [comment]
My friend was in a coma since 2010 and thought it was still the same price as back then

Seriously though, we're leaders here in Bisq, not followers like those centralized dinosaurs. We lead by being right and doing the right thing, even for trivial issues.

**Comment by ManfredKarrer** [comment]
In the early Bitsquare versions we used the logical notation (e.g. 15 000 EUR/ BTC and 15 ETH/BTC). I read it like in math division. But users and pro traders complained a lot and the difficulty to compare prices was another main reason to go with the weird standard. Would have added too much friction and confusion to keep that.... But I understand your points, would have loved if users and traders would have accepted that and Bisq would have set a new standard ;-)

**Comment by gdvine** [comment]
Wow that is crazy! They are dumb.

**Comment by GuiSim** [comment]
I suggested here https://github.com/bisq-network/exchange/issues/1191 that we use

`1 BTC => Y USD`

I think this is clear and does not introduce any confusion. 1 BTC is worth X USD.
