### ISSUE TITLE
ZCoin

### ISSUE THREAD

**Issue by meapistol** [bisq-network/bisq#1159]
It seems the instructions on Bisq for ZCoin are wrong or I miss something.
According to this link, https://zcoin.io/how-to-use-zerocoin-in-zcoin-xzc/, Zcoin is like Bitcoin and transactions can be traced and thus arbitrated. ZCoin can be made anonymous by using Zerocoin if one wants. The instructions on Bisq say that one should use t-addresses instead of a-addresses which I think is taken from ZCash. Nevertheless Bisq allows an address starting with a to be used when making an account.

**Comment by ManfredKarrer** [comment]
I did not find anything about a-addresses. Do you know what is the equivalent to t-addresses (traceable) and z-addresses (not traceable) from ZCash?

**Comment by meapistol** [comment]
As far as I understand the addresses start with a and there are no t-addresses.
To get anonymous ZCoin one changes them to ZeroCoin and then mint new ZCoin (destroying the ZeroCoin). This seems to be done in the wallet.
The newly minted ZCoins can be traced like a normal Bitcoin but their origin is unknown and new.
I tried this anonymisation now but it needs to be confirmed in the ZCoin-blockchain before I can spend my newly minted 10 ZCoin. If you have a wallet I can send them to you in an hour or so.
I suggest to not use the info-screen for ZCoin in the next release since it is imminent.
I did a trade in ZCoin which went well. There are four offers now on Bisq, one of which is mine.

-mep

**Comment by meapistol** [comment]
I checked the transaction ID on the ZCoin blockexplorer and I can see the receiving address, the sending address and the transaction amount:
https://explorer.zcoin.io/tx/ef12239407e3d7b0d7cfea71722a3fcd60f1a4e0e001b8e893e87a4da74a65dd

**Comment by jonathancross** [comment]
[Zcoin and ZCash used to have separate messages](https://github.com/bisq-network/exchange/blob/d7ed22c2b8890ad567be2ce930728f31e226242c/gui/src/main/java/io/bitsquare/gui/main/account/content/altcoinaccounts/AltCoinAccountsView.java#L173), but they were [replaced with a single message](https://github.com/bisq-network/exchange/commit/f268abe2e10ced3339eb85132eb82647a1f7f960#diff-3940b540944ab35304fd8dd85f85a969R138) ([`account.altcoin.popup.transparentTx.msg`](https://github.com/bisq-network/exchange/blob/master/common/src/main/resources/i18n/displayStrings.properties#L917)) which only makes sense for Zcash.

UPDATE: Ah, looks like I took too long to submit my comment and there has been a lot of activity already on this.  Hope this info is of use anyway. ;-)
