### ISSUE TITLE
Bisq doesn´t open

### ISSUE THREAD

**Issue by eamm2** [bisq-network/bisq#1161]
Impossible Download Bisq many time try to run it but it's impossible to open it, not idea what it is the bug or problem. 

Help please!

![image](https://user-images.githubusercontent.com/35218174/34664599-f70c5e9a-f45c-11e7-95e2-43c4044f063d.png)

**Comment by ManfredKarrer** [comment]
Which OS are you using?
Try to deinstall or delete the installation directory and then re install again. Be sure to make backup before to not lose the data directory at de-installation. 
On windows we saw some issues with old installations...

**Comment by eamm2** [comment]
Using Windows, have deinstallation everything start from 0, still shows same error.

**Comment by mrosseel** [comment]
There's not only the installation directory but also the data directory. 
Do you know the location of the data directory and have you tried moving/delete+backup this directory?

**Comment by ManfredKarrer** [comment]
Do you have AV software? There have been reports that some AV software deletes files.

**Comment by eamm2** [comment]
yep have AV-kaspersky but have not restrictions to run Bisq

![image](https://user-images.githubusercontent.com/35218174/34669898-4601f58e-f474-11e7-9478-7b370d04dcfe.png)

Have not problem with Internet provider but try to open sing bridges, still not working

![image](https://user-images.githubusercontent.com/35218174/34669920-55e12f92-f474-11e7-8863-baf3e0ad64ea.png)

**Comment by eamm2** [comment]
Please any help still not running same error from beginning.

![image](https://user-images.githubusercontent.com/35218174/34677166-882f1aa2-f48f-11e7-99c3-57b8c83ac778.png)

  
[bisq.log](https://github.com/bisq-network/exchange/files/1612016/bisq.log)

Any help

**Comment by ManfredKarrer** [comment]
Maybe some tor files are locked?
try to delete all tor files in \Bisq\btc_mainnet\tor\ except the hiddenservice folder. There is your onion key, so that must not be deleted! Make a backup before.

**Comment by eamm2** [comment]
ManfredKarrer Impossible, still falling after falling, Impossible open it

![image](https://user-images.githubusercontent.com/35218174/34723084-91ae95fc-f549-11e7-8f1f-8cc8c69d259f.png)
[bisq.log](https://github.com/bisq-network/exchange/files/1615214/bisq.log)

after rempve the files...
![image](https://user-images.githubusercontent.com/35218174/34723189-ebca0d64-f549-11e7-8b75-5b7cdafdc66c.png)

**Comment by eamm2** [comment]
Please help!! stil cant use Bisq

**Comment by ManfredKarrer** [comment]
Did you restore the wallet or did anything else? Seems that the wallet does not match the wallet DB file. Do you have funds in the wallet? Or open offers, trades, disputes? If not then you can remove the data directory and start over new with a new wallet. Backup the old just in case.

**Comment by swhh60** [comment]
Having exactly the same problem after recent update on Mac, even after completely uninstalling all Bisq related files and reinstalling app.  Had no assets just at stage of funding security deposit but impossible so far. Former version gave me a wallet address for funding but no chance now.

**Comment by ManfredKarrer** [comment]
@swhh60 What do u mean with uninstalling on OSX? Did you delete the data directory? If you have no funds, offers, trade, disputes you can delete it at /Users/{USER}/Library/Application Support/Bisq

**Comment by swhh60** [comment]
Said no funds etc. Dumped everything to do with Bisq and reinstallation doesn’t help, must be location specific.

**Comment by ManfredKarrer** [comment]
Are u sure u deleted the data directory at /Users/{USER}/Library/Application Support/Bisq ? The Application Support is usually hidden....

**Comment by eamm2** [comment]
Dear Manfred Karrer,
Problem show up again can't log in again, I nkopw yes I have funds and yes have delet all tor files, please what else I could do to crecover or make it work Bisq

**Comment by ManfredKarrer** [comment]
@eamm2 Do you have AV software? Some make issues with Bisq and/or Tor.

**Comment by ManfredKarrer** [comment]
Is that issue resolved? I assume AV software of a stale installation is the reason.
