### ISSUE TITLE
API connection timeout

### ISSUE THREAD

**Issue by cryptoqween** [bisq-network/bisq#1162]
Hi guys, 

we have integrated with you on cryptocompare.com and getting connection timeout from our server, when calling  https://markets.bisq.network/api/trades/?market=btc_eur
Is it possible that our IP is blocked? Can you please let me know who I can contact about this?

Thanks guys
Quynh

**Comment by ManfredKarrer** [comment]
@dan-da Could you have a look?

**Comment by dan-da** [comment]
hi @cryptoqween.  At present, if your site/bot is issuing more than 180 http requests per minute then the IP will be blocked for 1200 seconds (20 minutes).   If this happens repeatedly, then it will be blocked for longer and longer time periods.   If you would like to send me your IP, I can check if this happened.  Anyway, please try to limit your request frequency as much as possible... eg only a few requests per minute. The server is not so beefy and the API backend is not fully optimized.

Another possibility for timeouts could be that the server is overloaded at certain times by too many requests.  @ManfredKarrer   An improvement we could make is to install cacti or similar load monitoring tool to easily check server load graphs over time.   With increasing API and website load, we are bound to run into hardware limits sooner or later, and best to keep an eye on it.  Other ways to scale include moving api to another domain/server eg api.markets.bisq.network and optimizing software further.  Lowest hanging fruit there should be to re-enable/fix the inter-request caching that for some reason didn't work on that server when deployed.

**Comment by cryptoqween** [comment]
Hi @dan-da thanks for the quick response, we'll descrease calls on our side and see what happens

**Comment by cryptoqween** [comment]
Is there a way to send you a private message please? @dan-da 
Thanks!

**Comment by dan-da** [comment]
@cryptoqween github doesn't seem to support PMs.  If you'd like to post an email addr I will contact you there.

**Comment by cryptoqween** [comment]
Can you email me at q at cryptocompare dot come
Thanks @dan-da

**Comment by cbeams** [comment]
Issue moved to [bisq-network/markets #1](https://github.com/bisq-network/markets/issues/1) via [**ZenHub**](https://www.zenhub.com/)
