### ISSUE TITLE
2nd Time Issue Placing BTC Offer

### ISSUE THREAD

**Issue by kamranpirwani** [bisq-network/bisq#1163]
## Purpose
I'm having issues creating an offer to buy BTC on Bisq. I tried previously before, and this is the second time in a row I'm seeing the following error message:

```
An error occurred when placing the offer:

A timeout occurred at publishing the offer.

No funds have left your wallet yet.
Please restart your application and check your network connection.
```

<img width="1275" alt="screen shot 2018-01-08 at 12 37 33 pm" src="https://user-images.githubusercontent.com/1796568/34683693-cf398af0-f470-11e7-8ca7-6005a181db2e.png">

If you look at the history, there are funds that left my account that actually did NOT get credited back -- referring to 10e54ec441729c2d954983e9fc453a46702dd400b1ae0563e5274ded61205dff
and 7c2d0a90c95a6d7afab2f9ea5fdd35803512eb3c2f736dd01bfd66657914317a
## Troubleshooting
I've looked through the bisq logs and didn't see anything concerning. Please advise on what I should be doing.

[bisq.log](https://github.com/bisq-network/exchange/files/1612448/bisq.log)

It appears I am indeed connected to TOR and have 9 network peers. Is there something I am overlooking here?

**Comment by khowell30** [comment]
You're not alone.  A lot of us are having this problem.  

There are a lot of new posts this am describing the issue and proposed solutions.  I'm awaiting return of my deposit and fees from a trade 4 days ago that timed out at the first step - waiting for blockchain (but Im' cautiously optimistic).

I expect you'll get a request soon from @ManfredKarrer for your log file, to get things straightened out ;)

I really want BISq to succeed!

**Comment by kamranpirwani** [comment]
@khowell30 Thanks for the response! This is my first time using Bisq and I think there is a TON of potential if it works smoothly. Hopefully we can get the issue squared away and yours as well. Cheers!

**Comment by khowell30** [comment]
Is there an update on what to do to get these orphaned trading fees returned?

Same issue for me:
<img width="1193" alt="screen shot 2018-01-11 at 8 36 44 pm" src="https://user-images.githubusercontent.com/35157196/34855727-3b1eeb70-f70f-11e7-8420-1116ab092941.png">

6650ec7fcec990dab2121af76688021c41730b11d4962d728525315396a36d24
ea2ca92e133b5575fad0bcf837d7fadd393b311b0fda8f6a574b41e0dc2030ea

**Comment by cbeams** [comment]
> If you look at the history, there are funds that left my account that actually did NOT get credited back -- referring to `10e54ec441729c2d954983e9fc453a46702dd400b1ae0563e5274ded61205dff`
> and `7c2d0a90c95a6d7afab2f9ea5fdd35803512eb3c2f736dd01bfd66657914317a`

@kamranpirwani, please see https://github.com/bisq-network/support/issues/20#issuecomment-358310226, where I've staged `10e54ec441729c2d954983e9fc453a46702dd400b1ae0563e5274ded61205dff` for reimbursement. Please subscribe to that issue to be notified when the reimbursement is paid out via batch transaction.

As for the second transaction, `7c2d0a90c95a6d7afab2f9ea5fdd35803512eb3c2f736dd01bfd66657914317a`, this does not appear to have been a Bisq protocol transaction, but rather a manual attempt to send these funds from an address managed by your Bisq wallet to some other address. There was a 14 sat/byte fee on that tx, which is why it has still not confirmed. Try running it through https://pool.viabtc.com/tools/txaccelerator/.

**Comment by cbeams** [comment]
@khowell30, I've responded to you via email regarding your reimbursement.

**Comment by cbeams** [comment]
Closing as superseded by the individual reimbursement issues under bisq-network/support#1.

**Comment by cbeams** [comment]
This reimbursement (@kamranpirwani's) is complete, please see https://github.com/bisq-network/support/issues/20#issuecomment-358533111.
