### ISSUE TITLE
Downloadables/Binaries should be hosted on IPFS instead of AWS

### ISSUE THREAD

**Issue by Eyesonly88** [bisq-network/bisq#1164]
Hi there, I'm a fan of your project 😍 

I just want to suggest to host the downloadables/binaries on IPFS instead of AWS to make distribution truly decentralized.
https://ipfs.io/

Thanks.

**Comment by tr37ion** [comment]
Interesting idea. One could add a blog for Bisq on https://www.zeronet.io/ and then just use their IPFS interface.

**Comment by ManfredKarrer** [comment]
Nice feature request but due lack of dev resources not realistic to add soon. I close it or now to keep our GH issues maintainable.

**Comment by 0zAND1z** [comment]
@Eyesonly88 , I have added your Wishlist to #2845 .

It would be great if you want to make your case again there. I am willing to contribute on some of the proposed features and see it to the end.
