### ISSUE TITLE
LTC buy offer posted 4 times due to connection timeout error

### ISSUE THREAD

**Issue by emma19900907** [bisq-network/bisq#1165]
Posted an offer and kept getting a timeout error as others have posted, but no funds were withdrawn from my wallet. Was preparing to post here when suddenly got the notice that the offers had been posted successfully. All 4 that I attempted. Cancelling them incurs a fee. None had gone through, then they all succeeded at once. Wonder how this can be resolved. Attached a picture for reference, thanks.

![cap1](https://user-images.githubusercontent.com/35244464/34701262-203689b0-f522-11e7-919a-c6710ae570a9.png)

**Comment by cbeams** [comment]
Issue moved to [bisq-network/support #32](https://github.com/bisq-network/support/issues/32) via [**ZenHub**](https://www.zenhub.com/)
