### ISSUE TITLE
FIX TIMEOUTS

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1167]
Over the last month we have seen a number of trades (~30–50) fail on timeouts due to Bitcoinj never receiving notification that a given transaction was successfully broadcasted to the Bitcoin network.

This problem leads to traders' maker / taker fees and mining fees being "lost" in the sense that the funds leave the traders' wallets while at the same time the trade fails and cannot be completed. The maker / taker fees are never really, lost, though. They are simply transferred to the arbitrator selected for that trade, and can therefore be reimbursed to the trader by that arbitrator. Mining fees, on the other hand, are genuinely lost, and must be reimbursed "out of pocket" by the arbitrator. Altogether, this is a costly problem, not only in terms of bitcoin, but also in terms of time and effort expended by all parties involved. As such, fixing it is our highest priority.

See the issues within this epic for complete details.

**UPDATE:** with v0.6.3 out, we're no longer seeing timeout errors, but we are now seeing trades show up in arbitration with missing, i.e. never-broadcasted maker / deposit transactions. We'll continue working on this in the context of this epic, as the underlying issue is the same—the problem is just manifesting in a different way now.

**Comment by cbeams** [comment]
UPDATE: we shipped v0.6.3 yesterday, which contains fixes for this timeout problem. I'm going to leave this epic open, along with an issue to track any further timeouts or similar problems (#1178) and we'll see how things go over the next few weeks. I'll also be working on getting everyone who experienced the timeouts reimbursed in bisq-network/support#1.

**Comment by sneurlax** [comment]
Is this related to #1193?

**Comment by cbeams** [comment]
> Is this related to #1193?

It is. See https://github.com/bisq-network/exchange/issues/1193#issuecomment-357521694

**Comment by cbeams** [comment]
Closing as complete. v0.6.3 and v0.6.4 dealt with the timeout issue and the subsequent tx broadcast failure issue, and it seems there's no longer a need to keep this epic open. That was a big push to get through all of that, whew! Thanks everyone.
