### ISSUE TITLE
Tolerate transaction broadcast timeouts

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1168]
From our [planning GDoc](https://docs.google.com/document/d/1jJjJ2yFgi3HT_N2nNSUioJ77EcDjd8j3sUvv7N7aCgY/edit):

> Add timeout handler to complete if bitcoinj not completing and retry, complete broadcast handler optimistically with logging a warning

The idea here is that it is better to tolerate the first timeout and then retry broadcasting in the background several times, than it is to fail on the first timeout, which leads to the lost fee problem.

When we tolerate timeouts in this fashion, the worst case scenario is that the trade goes to arbitration because a fee transaction never gets published. While still not ideal, this is a far better outcome than the trader losing their mining fee (and needing to be manually reimbursed).

**Comment by ManfredKarrer** [comment]
I did not implement the retry because I think that when we broadcast to all nodes the likelihood is very small that the tx did not get broadcasted and retry handling might introduce bugs and cannot easily be tested.

**Comment by cbeams** [comment]
Closing as complete. @ManfredKarrer, see the commit I just referenced above. I believe this is the only commit involved in implementing this fix. Please specify the others if I missed them.

**Comment by cbeams** [comment]
I've updated the title of this issue to reflect that, per https://github.com/bisq-network/exchange/issues/1168#issuecomment-356419232, we did not actually implement retrying tx broadcasts after initial timeout, and that we need to consider doing that in #1195.
