### ISSUE TITLE
Decrease likelihood of tx broadcast timeouts

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1169]
In v0.6.1 we introduced Bisq's own federation of Bitcoin Core full nodes, for two reasons:

1. To prevent BitcoinJ from blindly following the SegWit2X chain if it became the longest chain with most cumulative work. This became a non-issue shortly after we stood up the federation, given that the SegWit2X fork was cancelled
2. To significantly improve user privacy by ensuring that the only Bitcoin nodes that can see Bisq client bloom filters are our own. This is important because bloom filters leak information about which addresses exist in each client's wallet, which chain analysis companies and other adversaries can harvest. So long as the Bitcoin nodes in our federation are honest and uncompromised, Bisq user privacy is protected from this risk.

We went with bitcoinj's default values for transaction broadcasting in v0.6.1, specifically

 - We had 12 (Tor) nodes available in the federation
 - Bitcoinj needed to connect to a minimum of 10 nodes in order to start broadcasting
 - Bitcoinj would then actually broadcast to 5 of those nodes (50% of 10)
 - Bitcoinj would wait to hear back from 50% of those 5 nodes, i.e. 2 or 3 in order to consider a transaction fully broadcasted

In v0.6.2, we changed these settings as follows:

 - We still had 12 Tor nodes available in the federation
 - Bitcoinj needed to connect to 7 of those nodes in order to start broadcasting
 - Bitcoin would actually broadcast to 4 or 5 of those 7 nodes (50% of 9)
 - Bitcoinj would wait to hear back from 50% of those 4 or 5, i.e. 2 or 3 nodes in order to consider a transaction fully broadcasted

After v0.6.2 was released, users started started experiencing a much higher rate of timeouts while waiting to hear back from nodes, leading to lost fees as described elsewhere (see the "FIX TIMEOUTS" epic). There are multiple potential reasons for these timeouts, and several ways we are looking to mitigate this problem, but one such way is to tweak the settings mentioned above to decrease the likelihood of these timeouts, or rather to _increase_ the likelihood of hearing back from nodes that we broadcast to, in order to "convince" Bitcoinj that a given tx has indeed been successfully broadcast.

In v0.6.3, we plan to:

- [x] Continue having 12 Tor-based Bitcoin Core full nodes available
- [x] Target being connected to 9 nodes at all times
- [x] Require being connected to 4 nodes in order to start broadcasting
- [x] Broadcast to 100% of connected nodes, i.e. between 4 and 9 nodes
- [x] Wait to hear back from 2 of those nodes in order to consider a transaction successfully broadcasted

See [original GDoc](https://docs.google.com/document/d/1jJjJ2yFgi3HT_N2nNSUioJ77EcDjd8j3sUvv7N7aCgY/edit) where @ManfredKarrer and @cbeams sketched out this plan.

**Comment by ManfredKarrer** [comment]
All implemented in Development branch.
BitcoinJ changes:
https://github.com/bisq-network/bitcoinj/commit/63c9a91714886d171efacd56518dc576cd3e231e

Use LibdohJ with latest BitcoinJ changes and pass params:
https://github.com/bisq-network/exchange/commit/9fb59c89d508e4f819a9f1b301d297e059ba3d47

**Comment by cbeams** [comment]
Closing as complete.
