### ISSUE TITLE
Start trading window timer after deposit transaction confirmation

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1170]
Currently, Bisq's trading window timer starts when an offer is taken. Usually this works out fine, but during blockchain congestion, Bisq's maker, taker and deposit transactions can take many hours or even days to confirm, causing the trading window to be exceeded and often resulting in drawn out arbitration cases and canceled trades.

A simple solution is to start the trading window timer only after the deposit transaction has confirmed. Indeed, this should have been the implementation all along—it just hadn't become important until recently.

See description in #1171 for details.

**Comment by cbeams** [comment]
@ManfredKarrer, I've assigned you to this issue and slated it for v0.6.3, as I believe we agreed that this change should get into the next release.

**Comment by ManfredKarrer** [comment]
Seems to be a bit more tricky as I thought.
https://groups.google.com/forum/#!forum/bitcoinj
Also will require a bit of testing as the trade period is checked and used in various places.

I prefer to not include that in the 0.6.3 release.
Added my current WIP code here: https://github.com/bisq-network/exchange/tree/TradePeriodStartsAfterConfirmation

**Comment by cbeams** [comment]
I assume you meant this post on the bitcoinj forum: https://groups.google.com/forum/#!topic/bitcoinj/05TJbxAwKXs

I've removed this from v0.6.3 and will add to v0.6.4 to make sure this important issue stays on our radar.

**Comment by cbeams** [comment]
@ManfredKarrer, I've removed this from v0.6.4 (as it's already shipped), and tentatively added it to v0.6.5. Do you think you can get to this? It is quite an important measure for avoiding future messes when blockchain congestion rears its head again.

**Comment by ManfredKarrer** [comment]
@cbeams Will try.... Though wanted to focus back on DAO stuff.

**Comment by ManfredKarrer** [comment]
Required a fix in BitcoinJ to get the block time (https://github.com/bisq-network/bitcoinj/issues/11).

Behavior is following:
- If deposit tx is unconfirmed the trade duration is set to max trade duration of payment method
- If deposit tx is confirmed we use block time where tx got included. That time can differ +/- 2 hours. 
To handle that possible time offsets we use following rules:
If block date is in future (Date in Bitcoin blocks can be off by max. 2 hours) we use our current date.
If block date is before our trade date we use our trade date.

**Comment by ManfredKarrer** [comment]
Implemented via PR https://github.com/bisq-network/exchange/pull/1287

**Comment by cbeams** [comment]
> Implemented via PR #1287

@ManfredKarrer, it's better to do this sort of thing on the PR side. Include the text `Fixes #1287` in the description of the PR and the referenced issue will be closed automatically if and when the PR is merged.

**Comment by cbeams** [comment]
Closing as complete now that #1287 has been merged.
