### ISSUE TITLE
MITIGATE CONGESTION

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1171]
Recent spikes in the Bitcoin mempool have led to congestion on the Bitcoin blockchain, which in turn leads to inaccurate fee estimations, which in turn leads to Bisq trading windows being exceeded due to "stuck" maker/taker/deposit transactions taking longer than the trading window itself to confirm, which in turn leads to an increased number of arbitration tickets. While most traders simply "wait it out", these situations sometimes lead one trader to cancel the trade on the technicality of the trading window being exceeded, when in fact it is simply in their favor to cancel because the price has moved against their interests.

We cannot prevent or avoid the root cause of the congestion itself, so we must find ways to mitigate its negative effects on Bisq users and arbitrators. We must:

1. Improve fee estimations, such that transactions don't get stuck in the first place (#1077)
2. Start Bisq's trading window timer only _after_ the trade's deposit transaction has been confirmed (#1170)

(1), while a challenging problem to actually solve, would avoid the problem of stuck transactions altogether, while (2) avoids the problem of the trading window being exceeded in cases where trades do still get held up on stuck transactions.

We should also publish some kind of document that lets traders know what to expect in the case of blockchain congestion causing trade transactions to take a long time to confirm.

**Comment by wiz** [comment]
https://github.com/bisq-network/projects/issues/27

**Comment by wiz** [comment]
Fixed by https://github.com/bisq-network/projects/issues/27
