### ISSUE TITLE
Track dropped arbitration messages

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1173]
Per details in the description of #1172, this issue exists for tracking arbitration cases where messages have been dropped, or we believe they have been dropped.

To make note of an incident, add a comment to this issue as soon as possible, mention the Trade ID, who the arbitrator is, and explain what happened as best as you can. **Do not** include identifying details about the trade or traders involved.

Note: this issue and the instructions are primarily intended for @bisq-network/arbitrators, but individual traders are also welcome to follow these instructions if they believe they're experiencing a dropped message problem during arbitration.

In any case, by keeping close track of how often this problem is happening, we'll be able to know when we've solved it.

This issue is closely related to, but distinct from #1174. Please do not confuse the two.

**Comment by cbeams** [comment]
For the record, my last known incident with dropped arbitration messages happened on **January 6th,** as documented in the forum at https://bisq.community/t/cannot-see-answers-of-closed-dispute-ticket/4262. I followed up with the user in a private chat there and all is well.

**Comment by keo-bisq** [comment]
I have several disputes where one trader is not responding, possibly due to dropped messages:
0423401, QITYNPXN, 4159602. These disputes have been hanging for weeks now with no messages on the forum.

**Comment by ManfredKarrer** [comment]
@keo-bisq Can you post that on the Forum as well?

**Comment by cbeams** [comment]
Trade `96205518` definitely just had a dropped arbitration message. Namely, the seller sent me a message that I never received. I confirmed this with the seller via email, and saw a screenshot of his client confirming it. We had successfully exchanged chat messages on this ticket before, and now after the dropped message, but the dropped message never made it through.

**Comment by cbeams** [comment]
Trade `vNYbeG` appears to have dropped its 'payment started' message; I got screenshot proof that the buyer clicked the button, but the seller said they were unable to click 'payment received'.

**Comment by cbeams** [comment]
> Trade vNYbeG appears to have dropped its 'payment started' message; [...]

Note: adding the above message on this issue was a mistake on my part. I meant to add it to #1174, and I've done that now at https://github.com/bisq-network/exchange/issues/1174#issuecomment-364962145

**Comment by cbeams** [comment]
Trade ID `ZKdpG` experienced at least one dropped arbitration message on the buyer's side.

**Comment by cbeams** [comment]
It appears that the seller in trade `KEHENQM` never received my initial arbitration chat message, leading to significant delays in the arbitration process.

**Comment by cbeams** [comment]
One of my arbitration messages to the buyer in trade `999999` was dropped, and this was verified by the buyer in a series of screenshots of our chat thread.

This dropped message caused at least one full day of unnecessary delay in the arbitration process.

**Comment by cbeams** [comment]
Issue moved to [bisq-network/support #85](https://github.com/bisq-network/support/issues/85) via [**ZenHub**](https://www.zenhub.com/)
