### ISSUE TITLE
Reduce tx fee in case of many inputs at taker fee tx

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1175]
The taker pays the tx fees for the deposit and payout tx additional to the trade fee tx because the fee need to be included in the deposit tx and the maker does not know which fee will be required at take offer time. There is still a risk that at payout time the tx fee is not sufficient but we accept that risk as not too critical for now and there is not an easy solution as RBF (replace by fee) is not supported in BitcoinJ.
 
If the taker has many inputs at his trade fee tx the current model uses that fee for the deposit and the payout tx as well. That can lead to very high fees for those 2 follow-up txs. We want to optimize that.

The deposit tx can only have 2 or 3 outputs and thus the size is rather deterministic.
The size of the payout tx is always the same (roughly as signature sizes are slightly different) but there might be a dispute and that is a bit larger as well.
All those variations are in a small range, only the trade fee tx can have 1 input or many and thus change the required fee very strongly.

Average tx size by tx type:
- trade fee tx: 260 bytes (1 input)
- deposit tx: 336 bytes (1 MS output+ OP_RETURN) - 414 bytes (1 MS output + OP_RETURN + change to maker in case taker does not take max trade amount)
- payout tx: 371 bytes
- disputed payout tx: 408 bytes

We want to change the current fee calculation by using an average of the trade fee size and the deposit tx size. The miners take the sum of the fees of dependent txs to decide to include a tx, thus a trade fee tx with a smaller fee might get included if he deposit tx has a higher fee.

**Comment by cbeams** [comment]
In what commit(s) did you implement this?

**Comment by ManfredKarrer** [comment]
Just pushed it here: https://github.com/bisq-network/exchange/tree/FixWrongFeeCalculationForTaker

Will remove those feature branches after merged.

**Comment by cbeams** [comment]
Closing as complete. See referenced commits above.
