### ISSUE TITLE
Allow setting of fees when withdrawing

### ISSUE THREAD

**Issue by Quenos** [bisq-network/bisq#1177]
At the moment it seems to be impossible to set fee when withdrawing.
I had to pay 500 sat/kB where blocks were mined with transactions in it that only paid 200sat/kB

By being able to set an appropriate fee yourself you would also be able to define the urgency you need.

This could be made an advanced feature to prevent newbies from making mistakes and complaining why their transactions are stuck.

**Comment by cbeams** [comment]
Closing as already implemented.

@Quenos, see `Settings->Preferences->Withdrawal transaction fee` as shown below.

![image](https://user-images.githubusercontent.com/301810/34865525-50e02a2c-f779-11e7-9581-4827c1c8da4b.png)
