### ISSUE TITLE
Bisq hangs at startup when trying to connect to Tor network

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1179]
We've had a couple reports of this happening recently ([example](https://twitter.com/TenaciousBTC/status/951444679832240128)). Could be issues with the Tor network itself, or related to recent changes we've made. In any case, we need to see how frequently this is happening, and examine logs from those who are experiencing it.

If you're experiencing this issue, please react to this issue description with a 👍, and consider attaching your `bisq.log` file (`Account->Backup->Open log file`).

**Comment by ManfredKarrer** [comment]
I assume that was from the time when Tor had many issues with ddos.
