### ISSUE TITLE
Login password dialog doesn't provide 'exit' button

### ISSUE THREAD

**Issue by tr37ion** [bisq-network/bisq#1181]
Please add an option to exit Bisq from the login password dialog.

**Comment by ripcurlx** [comment]
If you mean the wallet password prompt on app startup, you could just close the application window or quit the app over the app menu. At least it's working like that on mac os. What OS do you have issues with?

**Comment by tr37ion** [comment]
Yes, I mentioned the login dialog. I'm with Arch Linux. As using tiled window managers have no window borders at all it might lead to a bad habit shutting down the app with keyboard shortcuts. 

It just makes it feel more natural just hitting the ESC key or  press an **[EXIT]** button to leave the app properly. Not that users kill the app later on, too.
