### ISSUE TITLE
Adding double click for Market/Spread currencies

### ISSUE THREAD

**Issue by tr37ion** [bisq-network/bisq#1183]
It would be nice if double clicking the currencies in **Market/spread** opens either a list of all open Buy/Sell orders or switches to the last entered **Buy/Sell BTC** tab applying the currency filter.

**Comment by ripcurlx** [comment]
In general not a bad idea, but switching to the `Buy/Sell BTC` depending on your previous behaviour might not be very intuitive. As there is no overview screen of buy and sell offers atm we could switch to the offer book instead having the specific currency selected. But this would only work properly if we display in the `Spread` tab only the currencies based on the user filter, like you've mentioned in https://github.com/bisq-network/exchange/issues/1233.

**Comment by tr37ion** [comment]
I thought of clicking the offer values instead. 

Clicking a `Buy BTC` value of any currency offer opens the respective `Buy BTC` offer filtered by the selected currency:

![image](https://user-images.githubusercontent.com/1538617/35161114-8460554a-fd3f-11e7-8a8d-6bf4ec49f0d3.png)

**Comment by ripcurlx** [comment]
As it is not common that you have different actions when clicking on different cells within a row, we need to have some kind of indication that there is a secondary action possible when clicking on this cell. Maybe giving it a hyperlink style (blue, bold and underline on rollover) could be sufficient.

**Comment by tr37ion** [comment]
Yes, a hyperlink-like solution was what I was looking for, as nowadays this is the most common usecase (webdesign).
