### ISSUE TITLE
Add number of open offers to currency filter popups

### ISSUE THREAD

**Issue by tr37ion** [bisq-network/bisq#1184]
The **Market** sections currency popup lists the number of currently open offers with a dash eg `Bitcoin (BTC) - 3 offers`. 

Can you please add this to **BTC Buy/Sell /Filter by Curency:** popup menu, too?

**Comment by ripcurlx** [comment]
So you mean having in the currency selection for sell offers only the number of sell offers next to the currency and for buy offers open buy offers, right? Good idea!

**Comment by tr37ion** [comment]
Yes. In the end it looks like this:

![image](https://user-images.githubusercontent.com/1538617/35160750-5f745e58-fd3e-11e7-9c5a-a9b1d7f674e5.png)

**Comment by ghubstan** [comment]
I have an optional fix for this issue @   
https://github.com/ghubstan/exchange/commit/cedefba24d75322afb2491593be23a84cbfd849e

It's my first attempt at contributing to this project, and the first time I've tried to do a git pull request.  Please let me know what further steps or changes I need to make if you want to merge this commit into your repo.

**Comment by ghubstan** [comment]
RE: "...could you please create a new PR including the changes requested in my comments above?"

I would be happy to, but I can't find Manfred's comments asking for further changes and a new PR.
I got an email and the comment, "Thanks for your PR Stan! Please see my comments", but never found the comments I was asked to look at. Can you provide a link?

Thanks.

**Comment by ripcurlx** [comment]
Closing as complete
