### ISSUE TITLE
Sort Market currency popup entries

### ISSUE THREAD

**Issue by tr37ion** [bisq-network/bisq#1185]
Please auto sort the order in **Market / Currency** popup if coins were added/removed.

![image](https://user-images.githubusercontent.com/1538617/35160571-d46e657e-fd3d-11e7-93dd-ec73d6d13756.png)

**Comment by ripcurlx** [comment]
You mean to display new coins in the list although you haven't selected them in your preferences? Maybe it would be better to have a kind of "What's new" popup in every release highlighting the most important updates and new coins added, so everyone can add them to their list if they like to. I just don't want to spam the list for everyone with lots of irrelevant coins over time.

**Comment by ripcurlx** [comment]
Or do you mean, that the Monero entry with 7 offers is below the one offer for NZD? Atm the list is sorted by offers and fiat/crypto. First is fiat (sorted by offers) and then crypto (sorted by offers)

**Comment by tr37ion** [comment]
If it is written `Currency:` the user expects a sorted list of currencies by name. To find currencies with the most offers `Market/Spread` is a better place to go. 

My current workflow is going to `Market/Spread` and find the trade I'm interested in and then come here to select the currency I found before. All sorting, filtering eg. already happened before. 

Another approach would be changing from `Currency:` to `Current Offers per Currencies` eg. Which is true, while confusing. 

Users expect such lists sorted by name. If it should be ordered by offers, the currencies with the same offer number need to be sorted within. In the future With more and more offers listed in the future, this sorting will lead to chaos ;) - Just take the simple approach IMHO.

**Comment by ripcurlx** [comment]
Still relevant.

**Comment by ripcurlx** [comment]
Still relevant.

**Comment by ripcurlx** [comment]
Still relevant.
