### ISSUE TITLE
Give currency symbol its own collumn in Market/Spread

### ISSUE THREAD

**Issue by tr37ion** [bisq-network/bisq#1187]
Sometimes currency name differs from its symbol eg. `Monero (XMR)`. Listing currency name `Monero` and symbol `XMR` in different columns enables Users to sort the list likewise.

![bisq-1](https://user-images.githubusercontent.com/1538617/34899763-2dfe0f2e-f7fb-11e7-97dd-2ab835aa5c15.jpg)

**Comment by ripcurlx** [comment]
If we add the filtering as mentioned in https://github.com/bisq-network/exchange/issues/1233, I don't think it would be necessary, as for 99% of users this list will be quite short.

**Comment by tr37ion** [comment]
Keep in mind that #1233 is only related to fiat currencies. Sure, if you take the altcoin filter into account too, then this list ***can be short***. Although, I myself enable all altcoins by default to find those with new trade offers, too.

With moving the currency symbols into anew  column I am able to find them by symbol name easily. It seems more and more altcoins use weird symbol names, though.
