### ISSUE TITLE
Adding currently running transaction status to status bar

### ISSUE THREAD

**Issue by tr37ion** [bisq-network/bisq#1188]
How about adding the currently running transfer's status icons to the lower right status bar? Clicking them opens a details panel.

![trans-status](https://user-images.githubusercontent.com/1538617/34854154-2dc5d3e8-f738-11e7-8f5f-7f3b8c4e98a9.jpg)

**Comment by ripcurlx** [comment]
You mean no matter which kind of transaction (offer (send&receive transactions), send & receive funds) to display the least confirmed one or having three icons for send, receive and offers. Not sure if this might be a little bit confusing. Have to think about it in more detail.

**Comment by tr37ion** [comment]
Currently the status of open transactions shows certain icons

![image](https://user-images.githubusercontent.com/1538617/35160032-500a87dc-fd3c-11e7-9110-69365679b3ea.png)

The statusbar then lists only those transactions which are in progress or need user action. If confirmations are running the right Confirmations icon is shown. It might be needed to add new icons for certain prodess steps. If yes, then we should list all possible states somewhere and create those icons.
