### ISSUE TITLE
Remove feature branches from this repository

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1190]
Per the [C4 process](https://rfc.unprotocols.org/spec:1/C4/), development should be done in individual contributors' forks, not in topic/feature branches of the main repository. To this end, I've just posted the following in Slack at https://bisq.slack.com/archives/C1267HFD1/p1515766342000298:

![image.png](https://images.zenhubusercontent.com/56f1d5436caf56c9d38e1e86/64c01817-9e2d-4723-95b8-5601052276e1) 

I'll wait for the requested feedback and then take action on removing these branches as appropriate. Thanks all.

**Comment by cbeams** [comment]
I have just created a mirror of the existing bisq-network/exchange repository at https://github.com/cbeams/bisq-exchange-1190, complete with all of the topic / feature branches that exist as of the time of this writing:

```
~/Work/bisq-network/exchange[master]
$ git remote show origin
* remote origin
  Fetch URL: git@github.com:bisq-network/exchange.git
  Push  URL: git@github.com:bisq-network/exchange.git
  HEAD branch: master
  Remote branches:
    Development                                             tracked
    MinimizeJar                                             tracked
    SocialMedia2FA                                          tracked
    TradePeriodStartsAfterConfirmation                      tracked
    TravisAndSubModules                                     tracked
    UI_scaling_issue_686                                    tracked
    cedric_maven_exec                                       tracked
    cedricwalter-Bitsquare_Icon_Missing_on_compiled_release tracked
    dao                                                     tracked
    master                                                  tracked
    policyfile                                              tracked
    policyfile-dev                                          tracked
```

I will now delete all branches except for `master`, `dao` and `Development`.

@ManfredKarrer, regarding the `TradePeriodStartsAfterConfirmation` branch, which is associated with #1170, you will still have this branch locally after I delete it on the remote. Please do the following to set it back up in your own fork (the following assumes you have your own fork of the exchange repository set up as a remote named `ManfredKarrer` in your local clone):

```
git checkout TradePeriodStartsAfterConfirmation
git branch -m start-trade-period-after-conf
git push -u ManfredKarrer start-trade-period-after-conf
```

From there, you can issue a pull request to `bisq-network/exchange:master` when the changes are ready.

**Comment by cbeams** [comment]
The above is now complete:

```
~/Work/bisq-network/exchange[master]
$ git remote show origin | grep tracked | cut -d' ' -f5 | egrep -v '(master|dao|Development)' | xargs -Ibranch git push origin :branch
To github.com:bisq-network/exchange.git
 - [deleted]             MinimizeJar
To github.com:bisq-network/exchange.git
 - [deleted]             SocialMedia2FA
To github.com:bisq-network/exchange.git
 - [deleted]             TradePeriodStartsAfterConfirmation
To github.com:bisq-network/exchange.git
 - [deleted]             TravisAndSubModules
To github.com:bisq-network/exchange.git
 - [deleted]             UI_scaling_issue_686
To github.com:bisq-network/exchange.git
 - [deleted]             cedric_maven_exec
To github.com:bisq-network/exchange.git
 - [deleted]             cedricwalter-Bitsquare_Icon_Missing_on_compiled_release
To github.com:bisq-network/exchange.git
 - [deleted]             policyfile
To github.com:bisq-network/exchange.git
 - [deleted]             policyfile-dev
```

What remains is for @ManfredKarrer to merge the `dao` and `Development` branches into `master` per our discussion in Slack yesterday (starting with the message at https://bisq.slack.com/archives/C8MU98VSL/p1516890190000502).

Once `dao` and `Development` have been merged and deleted, I'll close this issue.

**Comment by ManfredKarrer** [comment]
Lets postpone the merge of dev to master after the release 0.6.5.

**Comment by cbeams** [comment]
No problem. I've slated this for v0.6.6.

**Comment by ManfredKarrer** [comment]
Dev is merged to master now.

**Comment by cbeams** [comment]
Closing as complete. I've removed `dao` and `Development` branches from bisq-network/exchange:

```
~/Work/bisq-network/exchange[master]
$ git push -u origin :dao
To github.com:bisq-network/exchange.git
 - [deleted]             dao

~/Work/bisq-network/exchange[master]
$ git push -u origin :Development
To github.com:bisq-network/exchange.git
 - [deleted]             Development
```

And removed those branches locally:
```
~/Work/bisq-network/exchange[master]
$ git branch -d dao
Deleted branch dao (was 6895ac910).
~/Work/bisq-network/exchange[master]
$ git branch -d Development
Deleted branch Development (was ef5bc8078).
```

Leaving the following (beautiful!) situation:

```
~/Work/bisq-network/exchange[master]
$ git remote show origin
* remote origin
  Fetch URL: git@github.com:bisq-network/exchange.git
  Push  URL: git@github.com:bisq-network/exchange.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```
