### ISSUE TITLE
Increase clarity in buy vs sell bitcoin page

### ISSUE THREAD

**Issue by GuiSim** [bisq-network/bisq#1191]
I started using Bisq recently and encountered a lot of usability issues, especially around prices when exchanging from one currency to another. Here are my thoughts on this.

Right now, all prices are displayed in BTC.

The buy bitcoin section
![image](https://user-images.githubusercontent.com/2000390/34885194-2df88da6-f78d-11e7-8619-ee3f8cce7c7a.png)

The sell bitcoin section
![image](https://user-images.githubusercontent.com/2000390/34885212-38d9282a-f78d-11e7-8b40-d9dc0587385e.png)

To me, this is super confusing for a few reasons:

First, the price is always displayed in "Price in BTC for 1 XMR" (in this example). This is confusing as in one scenario we're going from BTC to XMR but in the other we're going from XMR to BTC. 

Second, the Market Spread is not very intuitive. 
* When buying BTC, a higher market spread is good for the seller, bad for the buyer.
* When selling BTC, a higher market spread is bad for the seller, good for the buyer.
(and I wouldn't even be surprised if I got this wrong!)

Suggestions to increase clarity:

* Display market spreads in Green or Red, depending on their impact on your trade. A "good" trade (always from the perspective of the user) should have a green market spread. A "bad" trade (from the perspective of the user) could have a red market spread. We could even use a scale, the better trade could be in green and the worst trade in red.
* Introduce two columns: One that contains the BTC to XMR rate and one that contains the XMR to BTC rate. e.g.: `1 BTC = 33 XMR` and `1 XMR = 0.027 BTC`. Display these two columns on both the buying and selling pages.

Let me know what you think.

**Comment by mrosseel** [comment]
thx for the input, @ripcurlx is working on the UI so I'm sure he appreciates extra input for that

**Comment by tr37ion** [comment]
I had a similar thought. Is it possible to do something like this with Java?
![price-1](https://user-images.githubusercontent.com/1538617/34899745-06a6ab20-f7fb-11e7-81c4-e2b2ad0e337f.jpg)

**Comment by ripcurlx** [comment]
@trading pairs: Yes, it is a little bit confusing indeed, as we see BTC as our base currency and everything is about buying and selling BTC. This works okay with Fiat money as in most cases people either want to buy BTC or sell BTC. In the case of altcoins the perspective is a little bit different, as it's not 100% clear how all user would see it.
Having both exchange rates could be a way to go - I like the idea. Still we have to see if we have enough space to fit everything within the default width of the window. 

@spread: This is definitely something to be improved (see https://github.com/bisq-network/exchange/issues/1214). We could add color coding for sure, but I guess it will be a sea of red most of the time. But some kind of indication if the spread is good or bad for the user without the need to open an information popup would be great.

**Comment by tr37ion** [comment]
@ripcurlx An interim solution could be adding a red/green arrow icon column which shows if the spread is above or below market value. Or move the percentage into a new column and make it sortable.

![image](https://user-images.githubusercontent.com/1538617/35159629-20f2ebe8-fd3b-11e7-82d9-005a0dbecbd2.png)


I didn't think it through for now, but maybe this can help in the mean time.

**Comment by ripcurlx** [comment]
Have to think it through from a UX perspective so that it is no confused for price changes or something like that.

**Comment by ripcurlx** [comment]
This issues was superseded by bisq-network/exchange#1203.
