### ISSUE TITLE
Resend Transaction?

### ISSUE THREAD

**Issue by brett-doffing** [bisq-network/bisq#1194]
I believe my unconfirmed transaction has disappeared from the mempool as later transactions with smaller sat/byte fees are now being confirmed. My transaction is from Bisq to an exchange. What are my options here? Am I able to get the private key? I know Bisq uses HD wallets, but not exactly sure what standard, for which I could probably extract them and create a new transaction. Bisq says I have 0 funds, so I can't even fill in the "Withdraw from address" field. I'm coming up on two weeks waiting for this transaction, so I'd like to figure out a way to get it confirmed. Suggestions?

**Comment by cbeams** [comment]
Issue moved to [bisq-network/support #31](https://github.com/bisq-network/support/issues/31) via [**ZenHub**](https://www.zenhub.com/)
