### ISSUE TITLE
Change position of call to action buttons in offer book

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1198]
This was mind-bending for me when I saw the offer book for the first time. Although it make sense to put the `buy offers` above the `create sell offer` button, but still I was absolutely confused in the beginning. I think just switching this buttons and leave everything else afterwards as it is atm, would make this screen easier to digest for the first time.

*Before*
![offer book before](https://user-images.githubusercontent.com/170962/34991352-9be048b0-fac9-11e7-85c0-7ba83e9fce3d.png)
*After*
![offer book after](https://user-images.githubusercontent.com/170962/34991351-9bb92d7a-fac9-11e7-9981-87f2c4be0061.png)

**Comment by ManfredKarrer** [comment]
This would be even more confusing to me. 
Maybe the text above the tables is the main problem.
If you want to buy BTC you will look on the right side and then the button for buying BTC should be there IMO. The text "offers to sell" might be changed to something without buy/sell to reduce confusion.

**Comment by ripcurlx** [comment]
Maybe it could be titled something like this:`Available offers for buying BTC` or we just switch the titles around and see it always from the trader perspective. So `Offers to buy BTC with EUR` combined with the CTA-button `I want to buy BTC with EUR`. I think the mind-bending thing on this screen is that you need  to know as a first-time-user how Bisq works to be able to understand the two phrases.

**Comment by ManfredKarrer** [comment]
Maybe we can skip the headline completely?
I think the mind-bending thing is the mix between the offers perspective and your perspective (mirrored).

**Comment by ripcurlx** [comment]
Yes - that would also be better from my point of view as it is now. So there is less stuff on the first screen people have to think about.

**Comment by ManfredKarrer** [comment]
If you like we can push that in to today's release. Should be a quick one... So if you have time for a PR in the next hour....

**Comment by ripcurlx** [comment]
I tried to finish the PR in time, but I ended up having a scrollbar issue after resizing the tables for the gained space. Unfortunately I'll have to rush to a meeting now. So it's for the next release and I'll finish it off tomorrow morning. Sorry about that 😞

**Comment by ManfredKarrer** [comment]
No worry...

**Comment by ripcurlx** [comment]
While doing it I'll add the height autoscaling from https://github.com/bisq-network/exchange/issues/1186 as well.

**Comment by ripcurlx** [comment]
After letting it rest for a while I don't think it is a good idea to get rid of the titles and leave it as it is. I would suggest following:
**Before**
![offer-book-before](https://user-images.githubusercontent.com/170962/35739842-39e8b0f8-0833-11e8-91f4-c6c49b8dbc98.png)
**After**
![offer-book-after](https://user-images.githubusercontent.com/170962/35739853-45d9517e-0833-11e8-8f11-6eef618e21e0.png)
I don't think it helps to connect the sell offers with the buy button and vice versa, although there is a reasoning behind it. For me personally it would be more logical if I have the buy offers above the buy  button and I don't think it makes it easier to understand if you add an extensive title. I think 90% of the users are just clicking on the buy or sell bitcoin button and are ignoring the offers anyway.  And for those who understand what a buy and a sell offer is, we don't have to explain it in such detail. What do you think?

**Comment by ManfredKarrer** [comment]
I am not sure. We use the direction (BUY/SELL) of the offer at some places like the market/trades table. In your suggestion you make the headline Buy offer for technically sell offers (and they will be shown as that at some places).
Maybe we should request input from someone not involved in the discussion yet to get some fresh ideas? Seems to me we are stuck with not satisfying solutions.

**Comment by ripcurlx** [comment]
I meant switching the tables so it still matches the existing point of view (sell/buy) as it is. But as this discussion continues already quite some time back and forth, it is a good indicator, that we might need to do a bigger change on this screen to make it work 😁

**Comment by ripcurlx** [comment]
Based on a discussion on the same topic in our [forum](https://bisq.community/t/buy-offers-going-into-sell-category/4734) I created following variation of the `offer book` and the `Buy/Sell BTC` screens. Thanks to @cosmasta on the input! The idea is about thinking more in Buyers/Sellers than offers. So we could use following wording:
![offer book new](https://user-images.githubusercontent.com/170962/36093274-726afac6-0fea-11e8-8302-1c2cb44a8f43.png)
On the left column I've additionally added the `Buyer` column to emphasize that you're actually buying/selling from/to someone. For me this would help in understanding Bisq already on this screen. Of course this also should be changed in the Buy/Sell BTC screen as well:
![seller persona](https://user-images.githubusercontent.com/170962/36093282-79819c70-0fea-11e8-87db-68184b6b816e.png)

@ManfredKarrer What do you think?

**Comment by ManfredKarrer** [comment]
@ripcurlx I agree to the market screen. With the "Buyer" column I am not so sure if it adds additional confusion to see the word "buy" in the sell screen. I think we have to assume that most people have not the mental model realized that your sell activity is the buy activity from another trader. So might be better to ignore that as long it is not required. Specially that would be more problematic in the Altcoin case as there it is more intuitive to see it the other way round (e.g. the BTC buyer would be the altcoin seller).

**Comment by ripcurlx** [comment]
Or we replace the `Buyer/Seller` header label with a general `Trader`label. What do you think? I think it helps if people understand that they are trading with real people.
![offer book new](https://user-images.githubusercontent.com/170962/36110492-0c935124-1023-11e8-8e2c-cdb0d4d257d8.png)
![seller persona](https://user-images.githubusercontent.com/170962/36110496-1302ff50-1023-11e8-869c-caad974fe459.png)

**Comment by ManfredKarrer** [comment]
No sure if at the market screen the trader icon is required?
