### ISSUE TITLE
Use same order for offer tables

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1200]
Having the price columns next to each other making it easier to compare the prices of sell and buy offers, makes it in my opinion more complicated. I would use the same order in both offer tables.

![offer book](https://user-images.githubusercontent.com/170962/34991600-816bb8f6-faca-11e7-8a24-ebde3e2b5268.png)

**Comment by ripcurlx** [comment]
@ManfredKarrer Do you have an opinion on this change? 😉

**Comment by ManfredKarrer** [comment]
No strong opinion. I saw it at some exchanges and found it practical to compare the prices as they are next to each other. But leave it to you....

**Comment by ripcurlx** [comment]
I found it a little confusing especially in the beginning when I wanted to quickly scan the tables and wasn't sure which columns have the same meaning. Obviously the ones with the same header label 😉 . But still I don't see so much benefit having the price values next to each other.
