### ISSUE TITLE
Use consistent naming of markets everywhere in the app

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1201]
Besides using the market where applicable, we could reduce the use of the currencies, when we add a currency selection as an additional screen on startup for new users.

**Especially on the offer screen we have:**
- Offer book for Euro (BTC/EUR)
- Currency: Euro (EUR) - 11 offers
- Offers to buy BTC with EUR
- Offers to sell BTC for EUR
- I want to sell BTC for EUR
- I want to buy BTC with EUR
- BTC/EUR: 12300.45
- Amount in BTC
- Price in EUR for 1 BTC

**We could use instead:**
- Offer book for Euro (BTC/EUR)
- Currency: Euro (BTC/EUR)
- Offers to buy BTC
- Offers to sell BTC
- Buy BTC
- Sell BTC
- BTC/EUR: 12300.45
- Price in EUR

**Comment by ManfredKarrer** [comment]
Consider difference with Altcoins. If they want to buy ETH it would be to sell BTC but that is no intuitive and confused users in early versions where we just used BTC. Because of that I changed for Altocoins to "Buy ETH (sell BTC)".

**Comment by ripcurlx** [comment]
Yes, to make the altcoin or different base currency use cases easier to understand we need something like discussed on https://github.com/bisq-network/exchange/issues/1207

**Comment by ripcurlx** [comment]
This would look like for USD:
**Before**
<img width="1312" alt="bildschirmfoto 2018-02-13 um 14 06 58" src="https://user-images.githubusercontent.com/170962/36151409-66bee5c4-10c7-11e8-9cb6-48d1710625e4.png">
**After**
![bildschirmfoto 2018-02-13 um 14 24 47](https://user-images.githubusercontent.com/170962/36152080-f3e52f60-10c9-11e8-8660-be8057849aa3.png)

**Comment by ghost** [comment]
The offers to buy / offers to sell is quite confusing in the current version. The table mentions buy, the call to action says sell, then the colours seem to be inverted since the the norm is buy (green-blue) and sell (yellow-red’ish). 

I understand the logic of "Here is the list of people buying, why not sell to them" or "Here is the list of people selling, why not buy from them".. But its quite confusing this cross referencing in the UI. 

Why not keep it simple and do something like "Buy Offers List, why not buy some too?" or "Sell Offers List, why not sell some too?" and you can cross reference on your own accord. 
![market](https://user-images.githubusercontent.com/5376199/39603533-b7648b0e-4f20-11e8-941a-39af97ee766b.png)

UI/Visuals still to be defined, was just experimenting with possible layouts.

**Comment by ripcurlx** [comment]
@diogorsergio Yes, in the new design we tried to get rid of the different labels Buy/Sell labels. As you mention it, I'm also not sure if the color should be the other way round as it is in the screenshot bellow. The other thing we have to think about is what to do in the chart above. There actually the color is correct as they are Buy offers on the left and Sell offers on the right. Not sure if it would get again more confusing if we have a color mix on each side. What do you think @ManfredKarrer ?
<img width="1312" alt="bildschirmfoto 2018-05-04 um 13 53 37" src="https://user-images.githubusercontent.com/170962/39626524-90df847a-4fa2-11e8-9186-11b676df6650.png">

**Comment by ghost** [comment]
@ripcurlx If you check the mockup, I tried to solve that issue. The left is for buys in both the chart and the offers table and the right is sell in both as well. This way everything is connect and there's no cross-referencing implied in the UI, but you can still do it in your head. 

**Current:**

| Offers to Buy  | Offers to Sell |
| ------------- | ------------- |
| [Sell BTC]  | Buy BTC  |

I understand the logic of "Here is the list of people buying, why not sell to them" or "Here is the list of people selling, why not buy from them".. But its quite confusing this cross referencing in the UI.

--------

**Proposed:**

| Offers to Buy  | Offers to Sell |
| ------------- | ------------- |
| [Buy BTC]  | Sell BTC  |

Why not keep it simple and do something like "Buy Offers List, why not buy some too?" or "Sell Offers List, why not sell some too?" and you can cross reference on your own accord.


![market](https://user-images.githubusercontent.com/5376199/39631436-09e06d06-4faa-11e8-9e7a-03c04119efa9.png)

The labels I used in the mockup can be worded differently to better convey this idea.
What do you think?
