### ISSUE TITLE
Make sell/buy BTC screen more self-explanatory

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1203]
Add information inline for price distance and volume range and add hint line before the create offer call-to-action button. Here's a rough sketch how it could look like:
![sell bitcoin](https://user-images.githubusercontent.com/170962/34993334-4cddd640-fad0-11e7-9ffc-177aa4286e95.png)

**Comment by tr37ion** [comment]
Please don't forget to dot-align the figures #1028

**Comment by ripcurlx** [comment]
Good point! I'll have a look how to do this in a consistent way. Sometimes it is a little bit tricky when we also have to display ranges.

**Comment by tr37ion** [comment]
For now you could just switch to `Fira Mono` font, which looks like a sans-serif font  and then just fill up the values with zeros to the right, so that values align nicely to the right. It is important to have a mono-space font, because then values are vertically comparable.

Sure a dot-aligned solution would be the best solution in the end.

**Comment by ripcurlx** [comment]
@fira mono: I'll have a look how it looks like mixing these two fonts within the app and the size of the font, as we have to bundle it within the app.

**Comment by tr37ion** [comment]
Fira Mono is one of the few fonts which scales very well. It is perfectly readable even with very small sizes. 

![image](https://user-images.githubusercontent.com/1538617/35221974-878d0a8a-ff7c-11e7-816b-7122e3236895.png)

**Comment by ripcurlx** [comment]
An updated version of the buy/sell screen up for discussion. @ManfredKarrer & @tr37ion let the discussion begin 😉 
![sell screen](https://user-images.githubusercontent.com/170962/35856944-d214a934-0b37-11e8-8e34-9c4f03bebeef.png)

**Comment by ripcurlx** [comment]
Or the same with the call-to-action button below.
![sell screen](https://user-images.githubusercontent.com/170962/35859847-f6678d56-0b41-11e8-9ba7-a23529ca81cc.png)

**Comment by tr37ion** [comment]
I got this layout. Positioning the filters and the `Create` button is not easy.

![image](https://user-images.githubusercontent.com/1538617/35861388-6b1d0494-0b3f-11e8-91f5-29485386e4de.png)

**Comment by ripcurlx** [comment]
If we would align it like this, I would start from the left, as this is the order how to approach this screen. Adapt the filter if necessary -> Take offer or move down to Create new offer. If we add the missing decimal places I think it would be maybe better to add them with a different color, not to overwhelm the user with zeros that don't add additional value. Regarding the flags I'm not such a great fan, as I think that users recognize/know the country codes more than the actual flags.
![sell screen no flags](https://user-images.githubusercontent.com/170962/36096305-14fb3390-0ff6-11e8-8dbd-b93e04a6a486.png)

**Comment by tr37ion** [comment]
Looks fine. The different colour for the zeros is a good idea. Maybe move the percentages to a new column.

What about making the button like in my mockup and moving the `NO. of offers ..` to the status bar?

**Comment by ripcurlx** [comment]
Moving the percentage into a new column might solve the need of an additional `+` for the positive price distance, so prices are still aligned properly. To be able to squeeze it into the view I also had to rename the price column and added an additional question icon for explaining `Distance`. I've also added the idea of the issue https://github.com/bisq-network/exchange/issues/1214 showing which distance is good or bad for the user. Having the No. of offers in the footer, is too far off and will be overlooked for sure. What do you think about following mockup?
![sell screen no flags](https://user-images.githubusercontent.com/170962/36143650-f7f10f48-10ab-11e8-8293-3bfb6a39b0ae.png)

**Comment by ripcurlx** [comment]
I've also renamed the column title `Buyer` to `Trader` to reduce the usage of Buy within the Sell bitcoin screen.

**Comment by ripcurlx** [comment]
Or we make it super verbose and explain everything 😉 
![sell screen no flags](https://user-images.githubusercontent.com/170962/36144447-5597cc52-10ae-11e8-8e3c-010dd463ce9a.png)

**Comment by ripcurlx** [comment]
@ManfredKarrer What do you think about going in this direction within the Sell/Buy bitcoin screen?

**Comment by tr37ion** [comment]
Some ideas:

 * Add filter for only showing offers one can take (registered accounts)
 * Move current vie to `Expert view` and show only Price, Distance, Payment Method and Trader
 * Add filter for showing only offers the user can take (> min limits)

**Comment by ripcurlx** [comment]
I think the amount of BTC to sell should also be visible for each offer, even in the non-expert view, as it is also important for your decision to sell (or buy).

**Comment by ripcurlx** [comment]
Maybe we can have a condensed view for new users and within filters the option to have an enhanced table where all values get their own column.
![sell screen](https://user-images.githubusercontent.com/170962/36153595-142b02e0-10cf-11e8-823d-995a72b24aaa.png)

**Comment by ripcurlx** [comment]
That way, we can still implement sorting that takes the min & max values into account (as it is now) and reduce the number of columns a user has to overview from the beginning. For power users we have the filter and an option to split up the BTC and EUR range into a separate column.

**Comment by ripcurlx** [comment]
Or we name it instead of "show filters" --> "advanced settings"

**Comment by ManfredKarrer** [comment]
Problem with "Add filter for only showing offers one can take (registered accounts)" is that new users would not see anything before they have registered an account.

**Comment by ManfredKarrer** [comment]
Re "Move current vie to Expert view and show only Price, Distance, Payment Method and Trader" - that is more or less the view at the market overview screen.

**Comment by tr37ion** [comment]
Or list the `max|min` available values for `buy|sell` orders. So that with buy orders only the max available value is shown. If you don't have the min asked amount, the offer will not be listed eg.

**Comment by ManfredKarrer** [comment]
The idea with the bar in the background of the price distance is nice but has the problem that negative (green) are an exception. So all will be red (rosa) which gives negative feeling.
The info icons at the tables are too much for me. Then nearly every item gets an info. Instead we could maybe use tooltips as kind of lightweight info? Or maybe have an introduction / guided tour mode where all items are explained. But better to get to wording which does not require explanations (hard :-)).

**Comment by sqrrm** [comment]
The background color bar could use the average distance as the base for colorization, such that 1% is still green if that's better than the average distance in the market.

**Comment by tr37ion** [comment]
@ManfredKarrer  Well, isn't it the purpose of those colours to guide the user a bit? I think we should not think too much of what the user might 'feel' of red/green colouring. If it is mostly red then it be so. It is just a quick way to find the most attractive offer. Plus get a feeling for `How much the offer is off the current market price.`

@sqrrm has a nice idea, while I'm not sure if all rainbow colours have enough contrast to be shown.

A compromise might me using a grey color.

**Comment by ripcurlx** [comment]
I'll let the idea of indicating the price distance visually rest for a while in the case that we might come up with an even better idea soon. Still I will start implementing following version of the Buy/Sell screen first. I've tried out a new wording for "price distance" as well --> price offset. Do you think this is easier to understand than the term we used before? ![sell screen no flags](https://user-images.githubusercontent.com/170962/36200927-8507739a-117e-11e8-9548-326aaa29303a.png)

**Comment by ManfredKarrer** [comment]
Re colored bars:
I think too much information kills the important things. Emphasizing too much takes attention from other emphasized areas. The offers are sorted by best price already. IMO that is enough. We dont want to distract users and introduce new mental models how the colors are applied (some will ask why the colors or bar are that way, specially for their own offers). 

Re price offset:
Not sure about offset. 

LBTC use "Marging":

<img width="916" alt="screen shot 2018-02-14 at 11 32 01" src="https://user-images.githubusercontent.com/1449498/36215978-90bf6466-117b-11e8-8383-5f3bcf453967.png">

HodlHodl does not show it in the offerbook but only at the maker screen:

<img width="675" alt="screen shot 2018-02-14 at 11 35 03" src="https://user-images.githubusercontent.com/1449498/36215983-942f974c-117b-11e8-999d-e59f9eaf1410.png">

**Comment by ManfredKarrer** [comment]
Maybe "Distance from market price" would explain it clearly but thats too long...

**Comment by ManfredKarrer** [comment]
Or maybe "Above market" in case of buy screen (positive means 1% above market so its better then 3% but worse then -1%).
For sell would be "Below market". So 1 % is better then 3% for the seller and worse then -1%.
That would explicitly explain the positive/negative meanings of the % value.

**Comment by ripcurlx** [comment]
The more I think about it, the less I think we should display price distance in the default view at all. It was also something that confused me, when I was seeing this interface for the first time. Maybe we should move this column also in the advanced settings and stick with a simpler view only highlighting with color the favorable case for the user.
![sell screen no flags](https://user-images.githubusercontent.com/170962/36254736-6ad291d4-124c-11e8-8da7-e35f88b1eac4.png)

**Comment by ripcurlx** [comment]
Maybe with a simple|advanced switch like this:
![sell screen no flags](https://user-images.githubusercontent.com/170962/36255149-1f0c41da-124e-11e8-9b7d-27c2a0fe4c4a.png)

**Comment by tr37ion** [comment]
Now the green bar is making no logical sense, I guess. Is it possible to center the bars?
![image](https://user-images.githubusercontent.com/1538617/36302765-99cba18c-1301-11e8-8672-5a266060224b.png)

**Comment by ripcurlx** [comment]
Yes, I think this should be doable. Still we could use grey for the not favorable distance and green to the right in the case of sell (higher is better) or to the left in the case of buy (lower is better).
![sell screen no flags](https://user-images.githubusercontent.com/170962/36305366-8aa17cc4-1313-11e8-992f-fedf394cdad2.png)

**Comment by mrosseel** [comment]
another idea for your consideration: insert a dividing line in the table, indicating which offers are above price/below price. This division line could also include the words 'offers above this line are cheaper than average'.

**Comment by tr37ion** [comment]
Not sure, but I still think red/green is more intuitive. Maybe give red a bit more transparency if you think it is too shiny.

**Comment by ManfredKarrer** [comment]
Is there any exchange which uses such bars in the background to indicate best prices? I have never seen that and I fear that this confuses users or at least attract their attention to something what is not the most important part in the screen. The parts where the user should get guided to are the "Take offer" and "Create offer" buttons IMO.

**Comment by tr37ion** [comment]
@ Yes, those bars are quite common. Have a look at #1228 eg.

**Comment by ManfredKarrer** [comment]
@tr37ion: Re #1228: Isn't that the accumulated order amounts?

**Comment by ripcurlx** [comment]
Maybe we could, as a first step, just add an indicator to the price if it is a dynamic pricing or not. So as soon as I know the meaning of it, I know that the price of these offers will change with the current market price. On roll over we can give the exact price distance (in % and moneywise) and in the advanced mode we'll have the separate column anyways.

**Comment by tr37ion** [comment]
@ManfredKarrer Sure, just an example, that such UI elements are quite common to display certain information. I guess, in the end Bisq will implement such an order view one day. Yet, this is a discussion for some time in the future.

@ripcurlx Good intermediate idea. Just check that this still feels good with many hover rows. Possibly add a small delay of 1s before the hover effect takes place.

**Comment by ManfredKarrer** [comment]
@tr37ion: Yes I know that this UI element is used sometimes but people have learned the meaning behind it and will be confused when it has another meaning in Bisq.
As said before if we put too much information in, the user get challenged more to understand all and it will take away focus from the most important elements.

**Comment by ripcurlx** [comment]
I'm back on this issue again ;-). Starting with a quick indicator icon for a dynamic price in the available offer list. I think doing it that way it is more clear for the user, that the price of the offer is changing.
![sell screen no flags](https://user-images.githubusercontent.com/170962/36731345-c26fc7d6-1bca-11e8-9caa-c24efc7e7463.png)
On roll-over it could show something like this:
![sell screen no flags](https://user-images.githubusercontent.com/170962/36731750-f258b038-1bcb-11e8-8530-fd8f3cec152f.png)

**Comment by ripcurlx** [comment]
@cbeams and @ManfredKarrer: Do you have strong opinion on this and/or https://github.com/bisq-network/exchange/issues/1214? Otherwise they would be my next issues ready for development.

**Comment by tr37ion** [comment]
The popup solution works good if filter options take place before.  might be a bit teadious if there are still a lot offers listed. Just to keep in mind.

Btw. how does the `Advanced` mode look now?

**Comment by ManfredKarrer** [comment]
@ripcurlx I find the refresh icon not very intuitive and would prefer to see the % directly without rollover. With the rollover you never see all offer prices. I would prefer the % in the brackets, maybe with an additional icon if we find one which is clear (maybe the BitcoinAvergae or Poloniex icons so it becomes more clear that we use those a reference market price? - But not sure if that adds more confusion than it solves...). The rollover would be good to have additionally.

**Comment by ripcurlx** [comment]
If we add the price distance percentage again and want to keep the alignment, I could try to add the spaces in a way that doesn't break the alignment. I personally think that the sync icon is quite intuitive, but that might be just my personal opinion. I'll create a new mockup so we can see how it could look like. 😀

**Comment by ripcurlx** [comment]
Based on a discussion with @ManfredKarrer on #1214  we talked about the idea of not only adding the state (market based margin, fixed) to each offer, but maybe also adding the current percentage distance from the marketprice also for fixed offers, to make it easier to put it into perspective compared to market based margin offers. The disadvantage of this version is that we'll have lots of icons and existing users who were used to differentiate the fixed from the dynamic offers by the percentage value, might be confused in the beginning by this change.
![sell screen](https://user-images.githubusercontent.com/170962/37083271-5235cefe-21ef-11e8-8930-7759309be15a.png)
Having it in a more realistic offer book shows that this approach might be a problem as deactivated rows will blend with the grayed out percentage values of fixed prices.
![sell btc](https://user-images.githubusercontent.com/170962/37083934-5dc74bd8-21f1-11e8-9fb2-09495603e1d4.png)
Maybe we could be fine just having the icons for differentiation?
![sell btc](https://user-images.githubusercontent.com/170962/37084005-92e52da8-21f1-11e8-93b0-f64d8e43068f.png)
What do you think?

**Comment by ManfredKarrer** [comment]
Yes, maybe the extra greyed out fixed price % is too confusing in context of deactivated rows... last screen looks good to me.

**Comment by ripcurlx** [comment]
I've updated the screen having the percentage with the same color both for fixed and market-price-margin trades. I've also removed as a first step the simple|advanced switch to break down this issue into two separate ones, where the first iteration will be just an improvement of the current state. As this is also a bigger change maybe @cbeams also want to give his view on this, before it goes into development.
![sell screen no flags](https://user-images.githubusercontent.com/170962/37203540-46279b9c-238e-11e8-9504-209561d6c9ab.png)

**Comment by ripcurlx** [comment]
The help tooltips for the amount range could say something like this: 
![USD amount](https://user-images.githubusercontent.com/170962/37409357-767047c2-279e-11e8-8f14-9dee2a71b51e.png)
![BTC amount](https://user-images.githubusercontent.com/170962/37409359-76b9129a-279e-11e8-80dc-04b1bfada4d0.png)

**Comment by ripcurlx** [comment]
As I'm about to submit the next pull request I'd love some feedback from a native speaker (@cbeams ?) on the tooltips used. Thanks!
**Positive percentage**
![bildschirmfoto 2018-03-28 um 14 55 04](https://user-images.githubusercontent.com/170962/38030229-4dbf5e44-3298-11e8-8dfc-015fadc040d3.png)
**0 percent**
![bildschirmfoto 2018-03-28 um 14 55 01](https://user-images.githubusercontent.com/170962/38030230-4de927d8-3298-11e8-8bef-4b1414b85a1b.png)
**Negative percentage**
![bildschirmfoto 2018-03-28 um 14 54 57](https://user-images.githubusercontent.com/170962/38030232-4e0dd01a-3298-11e8-940b-a90680c4f507.png)
**Fixed price**
![bildschirmfoto 2018-03-28 um 14 54 55](https://user-images.githubusercontent.com/170962/38030233-4e2bc2fa-3298-11e8-9843-df0416e44f4c.png)

**Comment by ripcurlx** [comment]
Still relevant.

**Comment by ripcurlx** [comment]
Still relevant.

**Comment by ripcurlx** [comment]
Still relevant.
