### ISSUE TITLE
Use environment locale to select right locale and currency 

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1204]
At the moment the default environment locale is not used/set properly which causes every user to be defaulted to `en_US`. Every new user will experience the app in English with USD selected.

**Steps to reproduce:**
- Have system settings set to e.g. `de_AT`
- Start a clean Bisq installation

**Expected Behavior:**
On first startup of Bisq I expect the app to be in German and EUR selected as currency.

**Actual Behavior:**
The app starts in English and USD is selected.

**Comment by blabno** [comment]
I'm taking this one.

**Comment by ManfredKarrer** [comment]
I don't remember what the problems was but there have been issues when using the OS default locale. Thats why the following code is executed at the very start.

public class BisqAppMain extends BisqExecutable {
    static {
        // Need to set default locale initially otherwise we get problems at non-english OS
        Locale.setDefault(new Locale("en", Locale.getDefault().getCountry()));

Should be fixed and investigated what was the issues if that code is not in place (just try it out).
