### ISSUE TITLE
Bisq-0.6.3.dmg cannot be verified

### ISSUE THREAD

**Issue by unixb0y** [bisq-network/bisq#1206]
Hello,
I just downloaded the latest version (Bisq-0.6.3.dmg) and Bisq-0.6.3.dmg.asc but GPG throws errors.

Here's the issue, apparently:
gpgkeys: HTTP fetch error 60: SSL certificate problem: Invalid certificate chain
gpg: no valid OpenPGP data found.

Also, the keyserver says it has no keys for "F379A1C6".
Please fix this. Verifying the signature is crucial for such an application!

**Comment by mrosseel** [comment]
when downloading in-app the signatures are checked, so since there have been no reports there the dmg + signature is probably correct. 

Please follow the explanation on this page completely: https://github.com/bisq-network/exchange/releases/tag/v0.6.3

If it still fails let us know!

**Comment by unixb0y** [comment]
@mrosseel Again, try it by yourself:
Download "Bisq-0.6.3.dmg.asc" and "Bisq-0.6.3.dmg" from the link you just posted, execute
"gpg --verify Bisq-0.6.3.dmg.asc Bisq-0.6.3.dmg"
And you'll get these errors:

> gpg: Signature made Thu Jan 11 00:57:00 2018 CET using RSA key ID F379A1C6
gpg: requesting key F379A1C6 from hkps server hkps.pool.sks-keyservers.net
gpgkeys: HTTP fetch error 60: SSL certificate problem: Invalid certificate chain
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper internal error
gpg: keyserver communications error: general error
gpg: Can't check signature: public key not found

**EDIT:**
The keyserver doesn't find any results for the key **F379A1C6**, which is supposed to have been used for the signing.
http://hkps.pool.sks-keyservers.net/pks/lookup?op=vindex&search=F379A1C6

**Comment by mrosseel** [comment]
just downloaded both files and this is the result:

```
me@me:Downloads gpg --digest-algo SHA256 --verify Bisq-0.6.3.dmg.asc Bisq-0.6.3.dmg
gpg: Signature made Thu Jan 11 00:57:00 2018 CET
gpg:                using RSA key 1DC3C8C4316A698AC494039CF5B84436F379A1C6
gpg:                issuer "manfred@bitsquare.io"
gpg: Good signature from "Manfred Karrer <manfred@bitsquare.io>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 1DC3 C8C4 316A 698A C494  039C F5B8 4436 F379 A1C6
```

**Comment by unixb0y** [comment]
That's weird....
```
me@me~/Downloads> gpg --digest-algo SHA256 --verify Bisq-0.6.3.dmg.asc Bisq-0.6.3.dmg
gpg: Signature made Thu Jan 11 00:57:00 2018 CET using RSA key ID F379A1C6
gpg: requesting key F379A1C6 from hkps server hkps.pool.sks-keyservers.net
gpgkeys: HTTP fetch error 60: SSL certificate problem: Invalid certificate chain
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper internal error
gpg: keyserver communications error: general error
gpg: Can't check signature: public key not found
```

**Comment by mrosseel** [comment]
one thing which might be different, I have Manfred's gpg key in my gpg keychain so it doesn't have to be looked up online. Can you try adding the key and retesting?

**Comment by unixb0y** [comment]
Yeah, ok - now it worked:

```
gpg: Signature made Thu Jan 11 00:57:00 2018 CET using RSA key ID F379A1C6
gpg: Good signature from "Manfred Karrer <manfred@bitsquare.io>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 1DC3 C8C4 316A 698A C494  039C F5B8 4436 F379 A1C6
```

Might want to tell this other users as they might be discouraged when they see gpg throws errors and Manfred's Key is not listed online...

**Comment by jonathancross** [comment]
@unixb0y In your situation, you can see there was just an http error on your end:

> gpgkeys: HTTP fetch error 60: SSL certificate problem: Invalid certificate chain

Therefore the pubkey was not downloaded.
This issue is entirely unrelated to bisq :-)

> Manfred's Key is not listed online...

The key is fine, but keyservers are flakey.  Here is the key:
https://sks-keyservers.net/pks/lookup?op=vindex&search=0xF5B84436F379A1C6

F379A1C6.asc is also included in the release:
https://github.com/bisq-network/exchange/releases/tag/v0.6.3

**Comment by ManfredKarrer** [comment]
@jonathancross Thanks a lot for your response!

**Comment by unixb0y** [comment]
@jonathancross @ManfredKarrer Thank you guys!
Why is it "F379A1C6" but on the link you provided it's "F5B84436F379A1C6"?

**Comment by ManfredKarrer** [comment]
F5B84436F379A1C6 is the long version. F379A1C6 are last digits

**Comment by unixb0y** [comment]
I see, thanks @ManfredKarrer !
The last version that I had downloaded worked perfectly without adding your key manually.
I like Bisq and I don't want people to be irritated by what seemed like a wrong signature, so I'd suggest you "fix" that so it works like it did in the last version.... 😉
Also, keep up the good work!

**Comment by jonathancross** [comment]
> I'd suggest you "fix" that so it works like it did in the last version....

Hi @unixb0y There is absolutely nothing that Manfred could do to "fix" this and frankly it is a bit rude to keep suggesting this.

The error could be caused by millions of things -- all of which are unrelated to Bisq.  It was an error in `gpg` and possibly certificates on your computer.

Please close this issue as we've politely taken time to explain the error to you, but it seems you have not taken the time to understand it yourself.

Thanks.

**Comment by unixb0y** [comment]
@jonathancross sorry, I didn’t mean to be rude. 
It’s alright I got it now...

**Comment by mrosseel** [comment]
@unixb0y don't worry, thanks for the report - if there are similar reports in the future we'll have a closer look

**Comment by unixb0y** [comment]
Sure, alright :) @mrosseel
