### ISSUE TITLE
Can not connect to tor with bisq in linux

### ISSUE THREAD

**Issue by brycehenley** [bisq-network/bisq#1210]
Can not connect to tor with default or custom bridges with bisq on Arch linux. I have tried numerous networks that I was able to connect on before. I also wiped my data directory and reinstalled with no luck. Tor is not blocked so I should not even need a bridge.

here is the error:
```
Jan-17 10:44:20.950 [NetworkNode-9999] ERROR i.b.n.p.n.TorNetworkNode: Tor node creation failed: java.io.IOException: User limit of inotify watches reached 
Jan-17 10:44:20.951 [NetworkNode-9999] INFO  i.b.n.p.n.TorNetworkNode: Restarting Tor 
Jan-17 10:44:20.951 [NetworkNode-9999] WARN  i.b.n.p.n.TorNetworkNode: We stop tor as starting tor with the default bridges failed. We request user to add custom bridges. 
Jan-17 10:48:17.417 [JavaFX Application Thread] WARN  i.b.g.m.MainViewModel: startupTimeout called 
```

**Comment by tr37ion** [comment]
Do you use package `bisq-bin`?

**Comment by brycehenley** [comment]
No, I tried bisq and bisq-git with the same result. I will try bisq-bin soon.

**Comment by freimair** [comment]
@brycehenley is the issue still there?

**Comment by freimair** [comment]
closed due to inactivity.
