### ISSUE TITLE
Trade period is not divided between Maker action and Taker action according to particular instrument(fiat, crypto) average transfer time

### ISSUE THREAD

**Issue by nuschpl** [bisq-network/bisq#1212]
BTC<->SEPA transfer time is about 6 days. And it's mainly because of SEPA transfer time, but is not divided between Maker and Taker. BTC seller may in that case wait 5 days, while BTC market price is dropping. Shouldn't the time be divided between maker action and taker action? We shouldn't rely here on arbitrator IMHO, but set strict rules.

**Comment by tr37ion** [comment]
I see it more like an Ebay order. You once agreed to a price you want to buy/sell something. The actual payment is another track. At the time of accepting maker and taker agreed on that deal. It can have pros and cons for both peers.
