### ISSUE TITLE
Don't show amount range if there is no amount range

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1215]
In some screens (e.g. take offer, my open offers,...) we display the amount range, even if there is no amount range. In the cases like my open offers it should be displayed e.g 0.10 instead of 0.10-0.10 or in cases like the take offer screen hide this field at all.

*Take Offer*
![Taker Offer](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/da18808c-8c0c-4637-a1a4-7f5e8a3d47ef)
*My Open Offers*
![My Open Offers](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/adae18cc-d399-454a-b70b-20721c3ebf33)

**Comment by tr37ion** [comment]
Splitting those two values in two columns make them better readable and sortable in the list.
