### ISSUE TITLE
Improve amount range selection when creating an offer

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1217]
Maybe we should add some toggle element similar to `Fixed|Percentage` for the amount as well.
E.g. `Fixed|Range`. Starting with only a fixed value we could prompt the user on her first offer that selecting a range of bitcoins to buy or sell increases the speed of the offer to be taken. When selecting the range option we could present the user with a slider where she can select the minimum and maximum values.

*Create offer to sell*
![Create offer to sell - step 2](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/fa4f5411-34bd-4008-99ba-f1c20eccf4b0)

**Comment by tr37ion** [comment]
I must say, this dialogue was very confusing to me at first. Maybe it is possible to write it as fill-in-the-blank text or automatically generate a sentence representing the values entered. That way it is clear what this is all about.

```
You want to<buy|sell> xx.xx BTC with a <fixed|percentage> distance <above|below> the current 
market price. If the market price changes your offer will <stay at xx.xx| be adjusted accordingly>. 
You ask the <buyer|seller> to require paying xx.xx BTC as refundable security deposit.
```
Something like that.

**Comment by ghost** [comment]
I agree with @tr37ion dialogue is not straight forward, it took me a while to get it for the first time. I'll explore some ideas and try to come up with a more intuitive solution.

**Comment by ripcurlx** [comment]
@diogorsergio Although nothing changed in the amount selection in the create offer screen, I wanted to give you an updated screenshot of the upcoming v0.7.0 release.
![Create offer](https://user-images.githubusercontent.com/170962/39514751-6c9edf6c-4df8-11e8-87eb-6423a030e546.png)

**Comment by tr37ion** [comment]
I still recommend adding an a sentence like summery, too. This helps understanding the result of the selection.
