### ISSUE TITLE
Guide user to "Portfolio/History" instead of "Funds/Transactions" after a successful trade

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1221]
As the transactions screen is quite overwhelming for a first time user I think it would be better to re-direct the user to the History tab instead.

![Portfolio - Open Trades - Step 6](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/feca6e4f-2444-4204-81cb-5f36d558c84a)

**Comment by tr37ion** [comment]
Is it possible to not offer anything, just showing the message until it was clicked? If the user wants to see the History or Fund section he/she can use the UI later on.

**Comment by ripcurlx** [comment]
Of course we we also could just show the popup and close it showing an empty Open Trades table. The idea behind this was to show the user the place where she can still check out her completed trades.
