### ISSUE TITLE
Only display if user is Seller or Buyer in "Open Trades"

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1222]
Although it does matter on the implementation and fee side if a user is a `taker` or `maker` when being `seller` or `buyer` it introduces a complexity in the "Open Trades" tab that is not necessary.
An easy solution would be to write in the `My role` column only `BTC seller` or `BTC buyer`.![Portfolio - Open Trades - Step 1](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/7ec7241c-0fd9-4ebf-ad91-035081a5ae55)

**Comment by tr37ion** [comment]
You could make it even simpler by using icons for `Seller` and `Buyer` colorized in red or green as first column. Then The Role is no more needed. Hovering the icon shows a tooltip like `You did buy/sell xxx.xx BTC`.

**Comment by ripcurlx** [comment]
True - we could also just stick with icons. Maybe we could even re-use the [->, ->] from the transactions table.
