### ISSUE TITLE
Make popups easier to distinguish

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1223]
At the moment we have different popup types (error, warning, info, feeback, background info, instruction, confirmation and attention.), but it is not clear to the user which CAN, SHOULD or HAVE TO be read. A solution would be to colorize/style the popups so users are aware when to double check the content that is presented or which popups are just click-through ones (maybe we should get rid of these anyways ;-)).

**Comment by tr37ion** [comment]
You could slide in important messages from the bottom or top (colorized orange/red) as one liner like eg. Youtube does.

![image](https://user-images.githubusercontent.com/1538617/35100521-71e989ce-fc5c-11e7-8a2c-0523f8dc3e0c.png)

**Comment by ripcurlx** [comment]
Closing as complete with 0.9+.
