### ISSUE TITLE
Improve offer confirmation dialogue

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1225]
Maybe we could structure it more like:
You are selling
1.00 BTC
@ 7,487.61 AUD per BTC
(auto adapts to 1% distance from market price)
Payment method: OKPay ("OKPay dummy")
Total: 7,487.61 AUD

(I'm confused again what Price and Amount to spend means again for the user)

Similar to the the Take Offer screen, this is one of our most important screens and should be super clear and easy to digest and confirm.
I also think we should add the fees (Bisq trading and mining fees) to this popup to be as transparent as possible what the user will have to pay for doing a transaction on Bisq.

![Create offer to sell - step 8.png](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/f69b5cba-94a1-4fd0-96e0-8d48d483b183)

**Comment by tr37ion** [comment]
Make descriptions more personal like 'Your offer ID:' instead of 'Offer ID'. Changes like this make entries more prominent and easier to understand.

**Comment by ripcurlx** [comment]
Also using Your onion address or if I'm not the "maker" Seller's/Buyer's onion address would be more easy to grasp.

**Comment by tr37ion** [comment]
I kind of feel technical terms like `maker/taker` might be good for a professional trading platform and pro traders know those terms, but with Bisq trading should be a bit more relaxed and using **simple language** flattens the learning curve a lot.

**Comment by ripcurlx** [comment]
Still relevant
