### ISSUE TITLE
Improve trade information during trade process

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1227]
Based on the discussions by @mrosseel, @ManfredKarrer and myself we could think about following changes to the Trade information block.

We could have following structure:
Deposit transaction ID -> keep it as it is
Max. allowed trade period: 6 days (i) --> remove last trade date and add information icon with popup that explains the reason behind this and the difference between different payment methods
Remaining time: 23 hours, 56 minutes (until Oct 31 2017 9:59:46 AM)

![Portfolio - Open Trades - Step 3](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/55da2760-90db-4597-82f5-996b9a40c449)

**Comment by tr37ion** [comment]
Is it possible to use the wording `Bisq Escrow` like 

`You pay xx.xx BTC to Bisq Escrow awaiting xx.xx USD in your Bank Account ABC`

or something like this. Then the text explains what is actually happening in each step.

**Comment by ManfredKarrer** [comment]
The word "escrow" is overloaded IMO. Many people think of a 3rd party receiving the funds (like a notary) which is of course not the case in Bisq. The MultiSig feature as utility to replace the classic escrow function is something which is inherently new and I think it should not be confused by using a term from old concepts.

**Comment by tr37ion** [comment]
@ManfredKarrer Technically this is true, while ordinary users will not grasp what is actually happening. Using a more common wording makes Bisq less scary and way easier to understand. The MultiSig feature is in itself an escrow-like automated process.

Therefore, the wording helps users to trust Bisq easily without the need to learn all technical details first. The UI should not make users insecure in steps they are doing, it helps making a trade first IMHO.

**Comment by ManfredKarrer** [comment]
@tr37ion I agree that we should not confuse users but IMO escrow would confuse users as it would suggest (at least for me) that a 3rd party escrow is holding the funds. Some users even think that without that we use the word escrow.

**Comment by ripcurlx** [comment]
> Max. allowed trade period: 6 days (i) --> remove last trade date and add information icon with popup that explains the reason behind this and the difference between different payment methods
> Remaining time: 23 hours, 56 minutes (until Oct 31 2017 9:59:46 AM)

@ManfredKarrer what about the changes mentioned in the beginning? If you're fine with it, I would create a PR for it.

**Comment by ManfredKarrer** [comment]
@ripcurlx Yes, agree to those proposals!

**Comment by ripcurlx** [comment]
I changed it like that atm for ongoing trades:
<img width="Trade ongoing" src="https://user-images.githubusercontent.com/170962/35738230-80bb3f5a-082e-11e8-866a-c192508445df.png">
and for trades that exceeded the trade limit:
<img width="814" alt="trade exceeded limit" src="https://user-images.githubusercontent.com/170962/35738278-a61b6b1c-082e-11e8-92b6-0e62afc05afe.png">
In the max allowed trade period I'll add an additional info icon that will show on roll over in the popover details why there is a trade limit for the payment method and that there are different limits for different payment methods and when the timer is started (after first blockchain confirmation).
![tradelimit](https://user-images.githubusercontent.com/170962/35738572-869382c4-082f-11e8-8741-d5a6d14bbae1.png)

**Comment by ripcurlx** [comment]
In the info pop over we could do something like this: 
![warning info](https://user-images.githubusercontent.com/170962/35823613-737bcef2-0ab0-11e8-8d6c-f4ec8cb132df.png)

**Comment by cbeams** [comment]
“… the trade will go to arbitration automatically” would be better. “Automatic arbitration” sounds like an automatic human-less arbitration process.

Otherwise: ACK!

**Comment by ManfredKarrer** [comment]
Yes it also does not open a dispute itself, the user have to do it and its not mandatory if they want to wait longer. Thats btw another area where more info would be good ;-) (dispute info texts in UI)

**Comment by ripcurlx** [comment]
I've updated the text. Regarding the dispute info, I've just created another issue to track this. Besides that, is following layout fine for you guys?
![trading process](https://user-images.githubusercontent.com/170962/36141406-e18c387e-10a4-11e8-96ab-13b6e78f7d7e.png)
If yes, following PR (https://github.com/bisq-network/exchange/pull/1328) would be ready for merging.
