### ISSUE TITLE
Change Order Book View

### ISSUE THREAD

**Issue by tr37ion** [bisq-network/bisq#1228]
The main Order Book chart and buy/sell buttons are not easy to grasp. Please change it to a vertical order list and show Sell/Buy offers if someone clicks a listed entry. Then to the right you could show a column with details and buy/sell button:

![image](https://user-images.githubusercontent.com/1538617/35100225-4e158418-fc5b-11e7-84bc-4df9677d2d30.png)

An quick hack for an nice order book could be something like:

![image](https://user-images.githubusercontent.com/1538617/35113743-d7297d5a-fc82-11e7-9cf2-f851040a439a.png)

Possibly just change font colour instead of background

**Comment by tr37ion** [comment]
You could also add a watchlist to the right of the orderbook:

![image](https://user-images.githubusercontent.com/1538617/35099513-8b68b1d0-fc58-11e7-8fb4-0a4243a46b01.png)

**Comment by ripcurlx** [comment]
The big question is how we could restructure the market/order book view to cater both noobs and pro traders. I think we'll end up with different approaches for each of them anyways. Please also see https://github.com/bisq-network/exchange/issues/1207.

**Comment by tr37ion** [comment]
In my example the market/order book view shows the order book above. Clicking the order book opens the buy/sell details as shown with the dialog to the right of the order book. 

The current chart can move to another tab for general market info.

**Comment by justpaulgmx** [comment]
I'm not available to assist in this area but wanted to say that I consider it a thoughtful and smart suggestion. I particularly like the black background mockup, a very familiar look. 

I feel ripcurlx has a point, but it could simply be handled with an advanced tab with more options.

Anyway, this issue has been open for a year now. If people need funding to make it happen, I'd like the to vote for it. If it's considered a distraction let's table UI for another time, but I think it would be a mistake. As someone evangelizing for Bisq and decentralized markets importance,  useability is as important as ever.

Thanks for the work done, regardless of outcome. 

Paul.
