### ISSUE TITLE
Limit input values to currency limits

### ISSUE THREAD

**Issue by tr37ion** [bisq-network/bisq#1229]
Please, limit the possible input value to each currency's max/min values.

![image](https://user-images.githubusercontent.com/1538617/35111251-1c624206-fc7b-11e7-89ed-e4972bbdf622.png)

**Comment by ripcurlx** [comment]
This screen is a little bit tricky because of all it's validations, field dependencies and formatting, but it's also on my list to clean up stuff like this. Thanks for the input!

**Comment by ripcurlx** [comment]
Still relevant
