### ISSUE TITLE
Move 'Create New Offer' button to the top

### ISSUE THREAD

**Issue by tr37ion** [bisq-network/bisq#1230]
To make it more obvious that Bisq is not just looking for sell orders. Move the ***Create New Offer*** button  to a more prominent place. 

Possibly change the text ***'Currently here are no offers available'***  could change to ***'Currently here are no offers available. But you can create your search request by adding your <buy|sell> offer above.'***

![image](https://user-images.githubusercontent.com/1538617/35111733-3a5c04a8-fc7c-11e7-8e89-9dd0a6515d58.png)

**Comment by ripcurlx** [comment]
There is already a new issue covering this screen https://github.com/bisq-network/exchange/issues/1203. Yes, the empty state could be improved as well. Maybe we could even put the call-to-action button within the empty list.

**Comment by tr37ion** [comment]
The bottom new space could be used to show offer details with quick action buttons to <buy/sell> eg.
