### ISSUE TITLE
Transaction Failed and Deposit is Stuck

### ISSUE THREAD

**Issue by ded5955b** [bisq-network/bisq#1232]
My transaction failed upon accepting an offer and now 0.00322665 BTC are tied up in the trade but I cannot do anything.  How can I get my deposit back!??

> An error occurred at task: VerifyPeersAccountAgeWitness
> The peers trade limit is less than the traded amount.
> tradeAmount=0.18 BTC
> Peers trade limit=0.125 BTC

Trade ID: pu1QuRC-b49fe963-d20c-431a-969e-8a2e236f9956-063
Deposit transaction: c50788d5d7d36cd773b18807b8f6b9b794d55ae2cd6952780126c817f942ee6d

**Comment by cbeams** [comment]
Issue moved to [bisq-network/support #64](https://github.com/bisq-network/support/issues/64) via [**ZenHub**](https://www.zenhub.com/)

**Comment by cbeams** [comment]
In case you missed it, @ded5955b, this issue has been moved to bisq-network/support#64, where it is now staged for reimbursement.

**Comment by Annuit-Coeptis** [comment]
I am seriously fed up at taking offers and then being presented with an excuse why it won't happen. And then being charged a trade fee FFS! Now today on 2 different offers because "The peers trade limit is less than the traded amount." Once more and I'll finish with bisq. I hope to discuss this if there is a Malmö Meetup on bisq.

**Comment by ManfredKarrer** [comment]
@Annuit-Coeptis Come down.... this is an open source project not a company...

If you have lost trade fee you can ask for reimbursement at:
https://github.com/bisq-network/support/issues

We publish that week a new release with a fix to avoid those lost trade fees completely.

**Comment by devinbileck** [comment]
@Annuit-Coeptis What version are you running? There was a recent increase in trading limits (in 0.9.4) and perhaps there is an issue where you or your trading peer have mismatched versions. Were you the taker in each attempted trade?

**Comment by Annuit-Coeptis** [comment]
Hi. Thanks for your suggestion. I have 0.9.3. I will update. I was the taker in each of the cases I have had a problem. 
I heard about bisq in a Meetup and was very pleased with the concept and satisfied with a few trades I did, apart from the trade limits, which have been somewhat improved. The trade fee is a modest amount, but I can't understand why it should be paid on an unfulfilled trade, even if it is an open source project. Spreads on the platform are quite large especially on smaller currencies like sek, so when an offer approaches reality, it is worth attention. When several of these fail, however, one definitely gets the impression that some players are somehow able to run from their offers.

**Comment by ManfredKarrer** [comment]
The lost trade fees due failed trade issue will be history with (tomorrows?) new release.

**Comment by ghost** [comment]
@Annuit-Coeptis 
I think that the only thing you pay are the bitcoin **mining** fees, which are to be paid each time bitcoins are moved. That's independent of the application.
