### ISSUE TITLE
'Display National Currencies' setting not respected by Market/Spread list.

### ISSUE THREAD

**Issue by tr37ion** [bisq-network/bisq#1233]
Limiting ***National Currencies*** setting to

![image](https://user-images.githubusercontent.com/1538617/35113319-472cf3a4-fc81-11e7-893e-1738dab9af9f.png)

still shows other currencies in

![image](https://user-images.githubusercontent.com/1538617/35113345-67284528-fc81-11e7-9863-6905d4cdeeec.png)

Is this intentionally?

**Comment by ripcurlx** [comment]
Good point. Would make sense from my point of view :-)
