### ISSUE TITLE
could not delete spv chain

### ISSUE THREAD

**Issue by sgrang** [bisq-network/bisq#1235]
[bisq log file.txt](https://github.com/bisq-network/exchange/files/1644933/bisq.log.file.txt)

**Comment by ManfredKarrer** [comment]
Can you post a bit more details? Which error message do you receive?
Do you delete it at settings/network?

**Comment by sgrang** [comment]
Thank you for the reply.  I just figured it out.  Yes needed to manually
delete spv file. Not too tech savvy but made it work!

Scott W. Granger
Madison Street Partners
949-310-4221 (c)
