### ISSUE TITLE
Investigate possible inability for Bisq v0.6.3 to broadcast transactions against a local full node

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1236]
I'm adding this issue very quickly here so that we don't lose track of it.

From the conversation at https://bisq.community/t/btc-withdrawal-transaction-not-sent/:

![image.png](https://images.zenhubusercontent.com/56f1d5436caf56c9d38e1e86/23e9b3a7-ceba-4be0-97f6-2f69756650ca)

**Comment by ManfredKarrer** [comment]
That should be fixed with v 0.6.4. Lets see if the next weeks will deliver still issues in that area or now.

**Comment by cbeams** [comment]
Closing as (believed to be) resolved in 0.6.4. We can re-open if this crops back up.

**Comment by cbeams** [comment]
Removed from `v0.6.4`, as this issue was just an investigation, not actually a bug report that led to a specific fix (that happened elsewhere). The only issues that should get included in milestones are issues that actually changed code in the release tagged with that milestone version.
