### ISSUE TITLE
IMPROVE FIRST TIME USER EXPERIENCE

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1237]
As a first step to improve the usability of the app we should focus on the first time user experience.  This could be a adaptive UI that will only be visible if you use Bisq for the first time. An easy way to reduce complexity could be to ask the user to confirm/select a couple of presets that would reduce the complexity within the app afterwards a lot.

**Select locale**
Atm Bisq is always launched in English as it contains the highest quality of locale. For users who are not very fluent in English we could already offer them to switch the language which would help them a lot in their first time user experience.

**Select market**
We could do this already in an exchange style as on other platforms offering the user two dropdowns:
(Select currency) <> (Select currency)
We'll pre-fill the currencies based on the user locale. e.g. de_AT --> EUR <> BTC
Of course we can use nice graphical assets and use this already to communicate what exchange options are available on Bisq.

**Show how easy it is to trade on Bisq**
Based on the selected currencies we will display a quick overview what is necessary to do your first trade. Maybe this could be a kind of progress bar on top with a guided tour that opens the necessary sections to progress.

Questions we could ask the user upfront that would make it easier on the long run:
- Do you want to use the Bisq wallet for trading or your external wallet?
- Do you want us to set appropriate security deposit values? --> we could hide the deposit input fields if the user agrees and explain the idea behind it at this point

This epic story is a starting point to spark the discussion for our first time user experience and will branch out in lots of separate issues over time. We should always keep in mind to make it easy to do the right thing. Even if people are very new to the crypto space it should be easy for them on Bisq to exchange currencies in a secure and privacy-aware way.

I'll try to make a first rough mockup next week, how this user onboarding could look like. As always feedback and ideas are highly appreciated!

**Comment by ghost** [comment]
@ripcurlx  I really like the idea of onboarding first time users, so when they open the app we bring them a pop-up to hand held them in the process of setting up bisq. 

But we need to think on what we should focus. 

* Introduce bisq and ask for basic settings like you mentioned above
  * Locale
  * Market
  * Account

or

* Introduce bisq and help the user securing his account
  * Write down seed
  * Confirm seed?
  * Setup password

Either option we can then have a section on the landing screen titled "Get started/Start trading" and remind them to do the remaining setup depending on what they did upfront.

**Comment by ripcurlx** [comment]
The problem with just to start trading without having the proper password/seed words setup first will force you/remind you on the way to do it anyways. If we think it is best practice to set a password and store the seedwords I think it is not a lot of work to this on first start up and offer afterwards the "first trade" onboarding. The original idea to do it like it is now, was to let the user explore as much as possible and only try to "convert" her later in the process. On the other hand for me it felt like a little bit complicated to do all this little steps randomly during the process. What do you think?

**Comment by ghost** [comment]
What I fear is that people might never do it with the thinking (I'll do it later), then something bad happens and it becomes the problem of (Why didn't I do it). 

But there are a lot of approaches we can take if we want the user to explore first. 

If we ask them to secure first we can make it optional with a secondary CTA along the lines of "Let me explore", and if they click it we can trigger a notification to the Alerts badge to remind them to secure the account, or even from time to time bring the "Secure your account" when they open the app.

We can also do it contextual to when they fund their account, or initiate a trade since it now becomes a higher risk profile we can trigger the flow "To keep your funds safe, please secure your account", and this way we can offer a "Start trading" flow first and then follow up to "Secure your account" after funding/trading initiated. At that point they have committed to the app, so its in their best interest to do it.

**Comment by ripcurlx** [comment]
Yes, we can try something like this. I guess it is maybe quite similar to a registration screen when you install a mobile app. You either let the user browse the content without registration and try to push for registration later or you force the user for a registration before using the app. Unfortunately there is no right answer for this use cases as it defers a lot between applications what works best (strongly depends on the audience and motivation why to use the app). But maybe having a skip option in place and the ability to somehow track it in a privacy-aware way (https://github.com/bisq-network/analytics/issues/3) would be great.

**Comment by ghost** [comment]
I'll put some on-boarding flows together so we can start a discussion on what approach we should take.
