### ISSUE TITLE
Null value key pairs

### ISSUE THREAD

**Issue by mrsclaessens** [bisq-network/bisq#1239]
In the midst of restoring my wallet I got an error about having Null value key pairs. After which I lost the ability to see the GUI although it still seems to connect to the network. Also prior to the null value error i could see a balance in my funds area. Now this has disappeared and doesn't appear in the emergency wallet either. I have attached the log file that is linked to the error message. Any way I can prevent the error? Cheers Jo 
[system.log](https://github.com/bisq-network/exchange/files/1646905/system.log)

**Comment by mrsclaessens** [comment]
Okay i can recreate this. when I installed the app again on a fresh machine and I copies the account director file over from my other first computer I get the message that tells me I can't have a null value for my key pairs
[system.log](https://github.com/bisq-network/exchange/files/1647521/system.log). Have I corrupted my original account directory?

**Comment by ManfredKarrer** [comment]
Can you send me the Bisq log file (Application Support/Bisq/bisq.log)?
You did a restore of the wallet by the seed words, right?

**Comment by ManfredKarrer** [comment]
I fixed a nullpointer in that area in 0.6.4. If you still get the issue please re-open.

**Comment by cbeams** [comment]
Looks like the commit in question was dbdb8b3cea23e74d22cc479b8adef206b615c667. I've retroactively included this issue in the v0.6.4 milestone to reflect.

**Comment by cbeams** [comment]
Actually, that commit was shipped in v0.6.3. Maybe I'm missing some other commit here, or maybe @ManfredKarrer, you meant 0.6.3 when you wrote 0.6.4 above?
