### ISSUE TITLE
NGN shown in Market/Spread but not in Buy/Sell BTC?!

### ISSUE THREAD

**Issue by tr37ion** [bisq-network/bisq#1240]
I just saw that the new coin NGN is shown with one trade in `Market/Spread` while I can't find it in `Buy/Sell BTC` list. Am I missing something? - I added all ALT coins.

![image](https://user-images.githubusercontent.com/1538617/35164821-3803995c-fd4c-11e7-8dfe-75ba0adcb8fc.png)

**Comment by ripcurlx** [comment]
Need to do some investigation on how these two lists are synced atm. Did it solve itself after time?

**Comment by tr37ion** [comment]
Still missing with 0.6.4

**Comment by ripcurlx** [comment]
I do see it in my list.
<img width="1312" alt="bildschirmfoto 2018-01-25 um 17 27 25" src="https://user-images.githubusercontent.com/170962/35399656-0cf337b0-01f5-11e8-9383-90cff8838d31.png">
Unfortunately I wasn't able to re-produce it atm. Will have a look if I'm able to add some safeguard functionality to force the synchronisation of these two lists. I'll keep you posted.

**Comment by tr37ion** [comment]
Yes, it is in `Market/Spread` popups. While it is missing in the other `Buy BTC/Sell BTC` popups.

**Comment by ripcurlx** [comment]
@tr37ion: Finally I had time to look at the difference of the currency selector in the `Offer book`, in the `Buy/Sell BTC` tab and what is displayed in the `Spread` section. The big difference is that in the `Buy/Sell BTC tab` only currencies are displayed that are configured in the `Settings` section (fiat & crypto) and in the `Offer book` & `Spread` you only see currencies that have offers, no matter if you have selected them in your settings. This is quite confusing at the moment.

Maybe we should select all fiat & crypto currencies by default in the `Settings` and apply the filter everywhere? In the `Offer book` and `Spread` all currencies without offers are filtered out anyways and in the `Buy/Sell BTC tab` every currency would be shown in this scenario. This is a little bit overwhelming if you look at it within the list, but the default currency is selected by default anyways. Maybe adding the number of buy/sell offers per currency in this drop down would also help finding out the interesting ones. Still sorting it by available offers might be really hard if you want to create the first offer in your currency and have to scan through a really long list.

The other option could be that we apply the filter and keep the current list of most popular currencies from `Settings`. In this case you might miss out offers in currencies you haven't selected so far. Not sure if, besides curiosity, this is a real use-case. We could add the default currency selection in the user on-boarding so she'll see her required currency for sure and can add any other currency in the `Settings` or by clicking on the `Edit currency list` in the currency dropdowns. What do you think? Maybe @ManfredKarrer could give us his thoughts on this as well?

**Comment by ripcurlx** [comment]
@tr37ion: So for your bug, do you have NGN selected in your currency list in `Settings`?

**Comment by ripcurlx** [comment]
Maybe we should rename the `Currency:` label in front of the currency selector to `Currency with offers:` or something like that, so people are not confused if their currency is not available in this screen, as it is the first screen you'll see when starting up Bisq. If we have a different **Setup Guide**  and exchange currency screen as mentioned in https://github.com/bisq-network/exchange/issues/1207 would solve this problem anyways.

**Comment by tr37ion** [comment]
@ripcurlx  Yes, I added all currencies in `Settings`. Maybe use `Offers for [currency]`.

**Comment by ripcurlx** [comment]
I like the `Offers for [currency]` idea!

**Comment by ripcurlx** [comment]
Btw. I was wrong with the offer book combo box (currency selector). Here all currencies that are configured in the `Settings` are shown no matter if an offer is available or not.
