### ISSUE TITLE
Add market price countdown bar for refresh tick

### ISSUE THREAD

**Issue by tr37ion** [bisq-network/bisq#1242]
Please add a visual indicator which shows how much relative time is left until the next market price tick is refreshed. It can be something like progress bar 

![image](https://user-images.githubusercontent.com/1538617/35170507-d779fa62-fd60-11e7-809d-401b147c0fc1.png)

or a small timer icon next to the status bar Tor icon.

![image](https://user-images.githubusercontent.com/1538617/35170478-b844cdfc-fd60-11e7-91f4-172ec94fd7cb.png)

**Comment by ripcurlx** [comment]
Like the idea. Atm I think it's a 60 sec delay with a random number of secs (max. 5) added for each repeated request.
