### ISSUE TITLE
In Market/Spread list the 'Spread' sorting is broken

### ISSUE THREAD

**Issue by tr37ion** [bisq-network/bisq#1243]
Sorting the Market Spread of coins is broken:

![image](https://user-images.githubusercontent.com/1538617/35171238-5a2ab58a-fd63-11e7-86b4-016a58321380.png)

or another information is missing.

**Comment by ripcurlx** [comment]
Thanks for pointing this out @tr37ion! There is obviously something going wrong when sorting by `Spread`
