### ISSUE TITLE
Prepare release 0.6.4: Fix issues with local Bitcoin node

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1244]
@ManfredKarrer commented on [Sat Jan 20 2018](https://github.com/bisq-network/dao/issues/38)

See: https://github.com/bisq-network/exchange/issues/1193#issuecomment-359128103 
https://github.com/bisq-network/exchange/issues/1154

---

@ManfredKarrer commented on [Sat Jan 20 2018](https://github.com/bisq-network/dao/issues/38#issuecomment-359169548)

We previously only checked if the P2P network is ready but we now add a check if the node has sufficient BTC peers and it the block download has been completed. The block download completion should cover the case where a localhost btc node is not fully synced (has to be tested if it behaves like that).

We add a check for that case in all tx broadcast use-case like:
- Create offer
- Take offer (taker publishes deposit tx, so we do not need to check on makers side)
- Create payout tx
- Create disputed payout tx 
- Withdraw (end of trade + normal withdrawal)
- Emergency wallet tool
- Manual payout tool for arbitrator
- DAO voting, comp. request and withdrawal

In the UI cases we show popups indicating the reason why the users has to wait.
In the dispute message handling we use a local cache for the messages and event listeners on the relevant data to trigger the check and apply the cached messages. We apply here the btc related checks as well even the message is not requiring that. Only the DisputeResultMessage would require the btc related check. We prefer less code complexity instead of slight optimization here, but it could be optimized in future.

Similar the check for the P2P network is not required at withdrawal use cases. We still keep it as usually we are anyway connected. Might be optimized in future.

**Comment by cbeams** [comment]
@ManfredKarrer, not sure if you planned on doing this already, but per the process we're trying to put in place now, please submit this fix as a pull request to master from the `fix-local-btc-node-handling` branch, as opposed to merging it there directly yourself. When you create the PR, please assign me as a reviewer, and I'll look into it ASAP. Thanks.

**Comment by ManfredKarrer** [comment]
@cbeams Sorry I read your posting too late. I merged it already to master.

**Comment by cbeams** [comment]
Closing as fixed by commits https://github.com/bisq-network/exchange/compare/410959d389960a76d95d7199e2c3663df161970a...328d89da6c0e6ef92cad52811730a77a3d29600e.

(These commits were developed in the `fix-local-btc-node-handling` branch, and then fast-forward merged to `master`, i.e. merged in such a fashion that no merge commit was created.)
