### ISSUE TITLE
Spreads view shows incorrect nr. of offers

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1246]
There is a bug in the spreads view to show incorrect nr. of offers. After switching screens that correct number (about the half of the nr. shown before) is displayed.

**Comment by ManfredKarrer** [comment]
Issue could not get reproduced. Most likely it is caused if offers change the state or errorMessage and then the add or remove might have not worked correctly.
Hope the commit https://github.com/bisq-network/exchange/commit/c4c4c0662bb9517ec10737f272e423fd2d92bbc0 has resolved that.

**Comment by cbeams** [comment]
Re-opened, as I just saw this bug exhibit itself again on v0.6.4.

**Comment by cbeams** [comment]
Actually, I am re-closing this and re-opening #1202 as it is the better-crafted issue, with screenshots, etc.
