### ISSUE TITLE
Wrong balance shown after update to version 0.6.2 or 0.6.3

### ISSUE THREAD

**Issue by JoKeyser** [bisq-network/bisq#1247]
First, thanks for your great work. I've been dabbling with the system last month and it works really well.

I've started using version 0.6.1, but after an update to 0.6.2 or 0.6.3 (I'm not sure which one), my transaction balance is shown as 0 for some reason, which isn't right. As "proof" I attach a screenshot of Electrum, imported through the seed words - it shows the funds I know are correct, and have been shown in Bisq until the upgrade. I've tried downgrading to 0.6.2 and 0.6.1, but that doesn't change anything (maybe files got upgraded?).

Here the (somewhat anonymized) screenshots:

![bisq_problem](https://user-images.githubusercontent.com/8722846/35195035-402183b4-feb5-11e7-9f98-f02fa916632a.png)

Here the 'correct' view of the balance in Electrum:
![electrum](https://user-images.githubusercontent.com/8722846/35195053-6d55b4f4-feb5-11e7-867a-7c421bec01d7.png)

I'm happy to provide any more information that may help you, including my files etc (over encrypted email), if that helps. I'm using the Bisq version from Arch Linux's AUR.

**Comment by JoKeyser** [comment]
I should say that I'm not sure whether I made the last transaction within Bisq or with Electrum... if the latter, maybe it's natural not to work in Bisq anymore?
(And maybe I've mis-interpreted that the upgrade has anything to do with it, and all that happened was that Bisq caught up with the history that may have been "tainted" with Electrum's transaction...)

**Comment by cbeams** [comment]
Issue moved to [bisq-network/support #58](https://github.com/bisq-network/support/issues/58) via [**ZenHub**](https://www.zenhub.com/)
