### ISSUE TITLE
menu bar icon is unreadable on macOS

### ISSUE THREAD

**Issue by charlesrocket** [bisq-network/bisq#1248]
![bisq menu bar icon](http://funkyimg.com/i/2BumV.jpeg)

finally managed to built on osx 10.13 and noticed that the icon is unreadable with dark menu bar

**Comment by ripcurlx** [comment]
Thanks for the hint @charlesrocket! Will have a look if there is the possibility with java apps to provide different icons for different themes on mac osx.

**Comment by charlesrocket** [comment]
@ripcurlx no probs! https://stackoverflow.com/questions/33477294/menubar-icon-for-dark-mode-on-os-x-in-java

**Comment by ripcurlx** [comment]
Sounds like a great issue for a `$BSQ bounty` - are you up for it? 🙂

**Comment by cbeams** [comment]
I have been meaning to add this very issue as a bounty for a while now.

**Comment by charlesrocket** [comment]
@ripcurlx ill try to find some time, but you can post it in case somebody wants to claim it

**Comment by charlesrocket** [comment]
dark menu bar icon set suggestion https://github.com/bisq-network/exchange/pull/1258

**Comment by ripcurlx** [comment]
@charlesrocket If you want to take this bounty, please comment in the newly created bounty issue https://github.com/bisq-network/exchange/issues/1263
