### ISSUE TITLE
Create concept how we can support TransferWise as payment method

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1250]
TransferWise seems to be used by some Bisq users but often leads to arbitration because the sending bank account of TransferWise is not as defined by the user (he cannot know it in advance).
It would require a concept how we can support TransferWise without breaking our security mechanism and without adding too much dev efffort.
Anyone how is capable and willing to work on that can earn BSQ in context of our DAO compensation requests. 

See also: https://bisq.community/t/transferwise-borderless-account-and-outgoing-transfers-from-different-account/2224/9

**Comment by alfsbs** [comment]
Issue moved to [bisq-network/payment-methods #2](https://github.com/bisq-network/payment-methods/issues/2) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sylph1o** [comment]
> Issue moved to [bisq-network/payment-methods #2](https://github.com/bisq-network/payment-methods/issues/2) via [**ZenHub**](https://www.zenhub.com/)

This link is dead. Is an issue still open somewhere on that topic? If so, a link there would be very useful.

**Comment by d668** [comment]
Any update? TransferWise can be sent via email actually and the sender ID will be his name
