### ISSUE TITLE
Tooltip missing in dev branch with recent merge

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1253]
There are some glitches with the recent merge:
- Toolips missing in icons at detail popups (offer, trade details, dispute windows)
- Address is centered instead of left aligned in funds/send as well columns in funds/locked and funds/receive. 
- Tx confirmation component in funds/receive missing
- Tx confirmation component is larger as it was and thus the row height is larger 
<img width="1258" alt="screen shot 2018-01-22 at 20 02 44" src="https://user-images.githubusercontent.com/1449498/35252634-58e4fc14-ffaf-11e7-9472-da68d1c84043.png">
. Leave it to you what you prefer.
- Copy and open link icons in trade process views does not have tooltip. 
- Open link and amount copy icon in create offer and taker view does not have tooltip. 
- Settings/About: tootips missing

**Comment by ManfredKarrer** [comment]
Just tested with German to see truncations and tooltips. Reduced window width to min. so get more truncations.

- Portfolio/Verlauf/Status spalte: kein tooltip obwohl truncated (ticket geschlossen)
- Portfolio/Offen/Mein Rolle: kein tooltip obwohl truncated
- Settings/Network: SPV label truncated but no tooltip
- Settings/General: Custom fee label truncated but no tooltip -> no need to limit space here, if easy the label can span over to next column...

**Comment by ripcurlx** [comment]
I've changed already all icons back to the regular label as it has the issue that it overwrites a tooltip when it's set manually. And as there is no text displayed we don't have truncation issues anyways.

**Comment by ripcurlx** [comment]
> Tx confirmation component in funds/receive missing

Works for me. Probably you just see unused addresses in your view. Maybe scroll down to find used ones ;-)

**Comment by ripcurlx** [comment]
> Address is centered instead of left aligned in funds/send as well columns in funds/locked and funds/receive.

All columns with id "addressColumn" will be now left aligned.

**Comment by ripcurlx** [comment]
> Tx confirmation component is larger as it was and thus the row height is larger

Didn't do it by intend. I think it has something to do with the changed cell factory content. Will have a more detailed look into it.

**Comment by ripcurlx** [comment]
> Portfolio/Verlauf/Status spalte: kein tooltip obwohl truncated (ticket geschlossen)
> Portfolio/Offen/Mein Rolle: kein tooltip obwohl truncated
> Settings/Network: SPV label truncated but no tooltip
> Settings/General: Custom fee label truncated but no tooltip -> no need to limit space here, if easy the label can span over to next column...

I've checked now all tables where still the default text cell factory is used and replaced it with a AutoTooltipLabel. Also in FXML views AutoTooltipLabels are used now. Still I've to implement auto tooltip versions for checkboxes & radiobuttons next.

**Comment by ManfredKarrer** [comment]
@ripcurlx Can that issue be closed?

**Comment by ripcurlx** [comment]
This is fixed by a pull request that was merged to Development already.
