### ISSUE TITLE
Add Monero and Zcash as base currencies

### ISSUE THREAD

**Issue by rex4539** [bisq-network/bisq#1255]
This way it will be possible to buy them directly with fiat.

Now you need to have BTC, LTC or DASH to exchange them.

**Comment by mrosseel** [comment]
That's on the wish list, but there's no developer bandwidth for it at the moment. If you know someone interested and capable of tackling this, be sure to send them to bisq.

**Comment by cbeams** [comment]
Closing as deferred until such time that a credible contributor shows up that is willing to take on these responsibilities, and who has earned sufficient $BSQ to bond into the high-trust role of arbitrator. And in any case, we wouldn't add both of these as base currencies within the scope of one issue. They would be managed independently. Thanks, though, @rex4539 for the suggestion. This issue will be here now to be discovered by others who are interested in the same thing.
