### ISSUE TITLE
traderSignAndFinalizeDisputedPayoutTx

### ISSUE THREAD

**Issue by grisq** [bisq-network/bisq#1261]
Error at traderSignAndFinalizeDisputedPaoutTx 
io.bisq.core.btc.exceptions.TransactionVerificationException:
org.bitcoinj.core.ScriptException: Script resulted in a non-true stack
[bisq.log](https://github.com/bisq-network/exchange/files/1659030/bisq.log)

**Comment by pimato** [comment]
having the same problems here:

<img width="594" alt="bildschirmfoto 2018-01-24 um 09 34 40" src="https://user-images.githubusercontent.com/5337809/35322252-e901ff28-00e9-11e8-990e-9be39a7f9add.png">

**Comment by ManfredKarrer** [comment]
@grisq 

There was no valid deposit tx:

https://blockchain.info/tx/ef428b66c276940bbcf6a6c5171ca0e78a69f452254ae023400e7a324bc3c44e
is the input for the payout tx but that is not a Bisq deposit tx but a normal MS tx.

I have no clue why that happened. Maybe u can tell me more context to the case.

**Comment by ManfredKarrer** [comment]
@pimato  Can you send me the log file and give some more info?
