### ISSUE TITLE
Implement voting

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1266]

**Comment by sqrrm** [comment]
@ManfredKarrer I remember you mentioned how you wanted to implement the voting using a commitment during voting phase and then reveal during resolution, as opposed to the original idea of early votes having heavier weights. Is there anything written on the details of the hidden commitments and resolution?

**Comment by ManfredKarrer** [comment]
I have started to write it up but need to check where it was...was not complete as well

**Comment by ripcurlx** [comment]
@ManfredKarrer I think this can be closed as complete, correct?
