### ISSUE TITLE
Add missing countries

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#127]
In our country locales list there are some countries missing (North Korea, Guernsey, Jersey, Isle of Man...). Research if we find a better country/region list.

**Comment by ManfredKarrer** [comment]
Moldavia is missing as well. We need to render a static list of counties rather use the list drieved from the OS locales.

**Comment by takinbo** [comment]
@ManfredKarrer I agree with you - a number of important countries are missing from that list. Using the ISO 3166 countries list (available via the `getISOCountries()` method of the `Locales` class) would be a better choice for the selection of available countries.

**Comment by ManfredKarrer** [comment]
Yes will be fixed in the next version.

**Comment by haiqu** [comment]
North Korea is on the banned list for most countries. The channel islands, while they have their own currencies, are all tied to the GBP and supporting them would be pretty pointless.

I think a lot depends on which countries you can get a price feed for, doesn't it?

**Comment by haiqu** [comment]
I've been using these references:

https://en.wikipedia.org/wiki/ISO_3166-1 Countries
https://en.wikipedia.org/wiki/ISO_4217     Currency

**Comment by takinbo** [comment]
It would be good to have a number of African countries (including Nigeria) added to the list of countries and currencies. These countries already have a healthy OTC/Peer-to-peer market and could really benefit from a platform that allows them to carry out their trades with escrow abilities.

**Comment by ManfredKarrer** [comment]
Ok, I will add them to the next release.

**Comment by takinbo** [comment]
How can I help?

**Comment by ManfredKarrer** [comment]
Which countries do u recommend to get added?

**Comment by takinbo** [comment]
If I were to suggest, I would recommend adding countries on https://coin.dance/volume/localbitcoins that are not already on the list and they are: Nigeria and Tanzania. I would also recommend adding Angola, Ghana, Uganda and Zimbabwe with more to come later. Any reason why we can't have all of them?

**Comment by ManfredKarrer** [comment]
Here is the doc how to add a new country:
https://github.com/bisq-network/docs/blob/master/exchange/howto/add-new-country.adoc
