### ISSUE TITLE
Add popmoney as a payment type

### ISSUE THREAD

**Issue by seljuck** [bisq-network/bisq#1273]
Currently bisq-network accepts Zelle as a payment type. Not all US banks offer that service. Some offer a competing service called popmoney. https://www.popmoney.com/

popmoney does not appear compatible to Zelle, so it would have to be a new payment type.

Feedback on what information bisq-network requires to add popmoney is the next step.

**Comment by cbeams** [comment]
Thanks, @seljuck. Here are the main things we need to know:

 1. What information is required to complete a payment via Popmoney, e.g. First / Last name, email address, etc. When someone pays someone else via Popmoney, what info must they provide?
 2. What kind of limits are involved? Are there daily / weekly / monthly limits? Are there limits based on the age of your account, or the amount of activity you've engaged in before?
 3. Chargeback risk. This is the most important item. How "hard" are Popmoney transfers on the hardness scale discussed at https://en.bitcoinwiki.org/wiki/Payment_methods? According to that same wiki page, Popmoney transfers ultimately happen via ACH and get only a 5/10 on the hardness scale. @pranay01 has been looking into ACH chargeback risk in #1052. Perhaps the two of you could collaborate here.

@ManfredKarrer, if there is anything else you can think of that @seljuck (or anyone else) would need to provide us to get Popmoney supported, please chime in.

@seljuck, let us know if you do in fact plan to research this. I'll assign the issue to you and invite you to join the @bisq-network GitHub org if so.

**Comment by ManfredKarrer** [comment]
We had those documents in the past:
https://docs.google.com/document/d/1iQHhtAOieu5i6_2rvkvtcLS70A991aZlxkJgzv97XuU/edit#heading=h.kfdzjkg0kjh
https://docs.google.com/spreadsheets/d/1xiOqcBSInIF7ozWdN3DvM5O-nyZ-397G9MR8LOXs6iA/edit#gid=0

They are not maintained anymore but should give a good start.

**Comment by ManfredKarrer** [comment]
@seljuck Did you find out the required information?

@flix1 : Do you know anything about that?

**Comment by ManfredKarrer** [comment]
It is US only, just tried to setup an account but cannot.

**Comment by ManfredKarrer** [comment]
More questions:
- How long takes a normal transfer?
- Do they transfer 24/7 or only at office hours?

**Comment by ManfredKarrer** [comment]
Seems that popmoney require both full name + phone nr. or email address.

**Comment by ManfredKarrer** [comment]
<img width="934" alt="screen shot 2018-02-18 at 19 56 15" src="https://user-images.githubusercontent.com/1449498/36359146-e0ccf92e-14e5-11e8-9f37-db0f74d74b65.png">

**Comment by cbeams** [comment]
A quick note to say that I've signed up for a Popmoney account and am going through their verification process now. Can provide more details later.

**Comment by ManfredKarrer** [comment]
@flix1 @cbeams Do you know how long a transfer takes? Is it instant?

**Comment by ManfredKarrer** [comment]
Seems to be instant:
https://www.popmoney.com/realtime-payment.html
