### ISSUE TITLE
Track FasterPayments-based trades that go to arbitration due to first and last name requirements

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1274]
I just had an trade show up in my arbitration queue with the following message from the buyer:

> The Seller didnt provide any Name at all (!). UK Banks require full name for transferring money.... pls insist that all seller include this asd this is second time in 2 weeks it has happened. 

This is at least the 3rd or 4th time I've handled such a trade personally. My understanding has been that _some_ UK banks require first and last name, while others do not, but it seems we have no way of knowing the difference.

At this point, the safest bet is to simply require first and last name for all FasterPayments-based trades.

**Comment by cbeams** [comment]
@ManfredKarrer, I'd also like to slate this for `v0.6.5`, since this is something that negatively impacts users and causes increased arbitration workload.

@ripcurlx, do you think this issue is something you could own, bringing @ManfredKarrer in only as necessary for guidance?

**Comment by cbeams** [comment]
I ask you, @ripcurlx because this is, I believe, mainly about supporting these fields in the UI for FasterPayments-based trades, and in whatever underlying data structures there are. Shouldn't be too far afield from what you've already been doing, but @ManfredKarrer would need to confirm that.

**Comment by cbeams** [comment]
Note: the seller involved in the trade mentioned above just got back to me in arbitration, and made it clear that he wants to cancel this trade, rather than provide first name and last name information. This is (a) because of privacy reasons and (b) because the seller has completed many other FasterPayments-based trades (in the neighborhood of 10–15) using Bisq in the last few months, **and has not needed to provide first and last name** for those trades.

So, if we force users to enter first and last name, then we're requiring people to sacrifice privacy quite possibly unnecessarily.

If we don't force users to enter first and last name, then some percentage of these trades will end up in arbitration like this one did.

It seems the only option that would satisfy both of these problems would be to identify all the UK banks that require first and last name data and match users according to which banks they can work with and whether they're willing to provide first name and last name information. This would be a nightmare to implement and keep up to date, so it doesn't seem like a feasible option.

Other suggestions?

I'm still leaning toward forcing first and last name in the trade details. It's a shame to have to give up this information, but it is only with one's counterparty after all, and this is the way that all SEPA transactions work across the rest of Europe anyway.

**Comment by cbeams** [comment]
I've just resolved the trade mentioned above by cancelling it. The seller did not wish to reveal first and last name, and the buyer could not progress without it.

The buyer shared the following link to FasterPayments' own site and documentation in which they indicate that "account name" is always required. From http://www.fasterpayments.org.uk/about-us/how-faster-payments-works (emphasis mine):

> 3. In addition to Simon stating the amount he wants to pay, he also provides Mike’s sort code and account number – this is the information used to address the payment. **Simon also enters the name of the account he wants to send the payment to,** which will appear on his statement along with any reference details  so that Mike knows what the payment is for.

The buyer's bank was Natwest, which according to the seller is "owned by the government" and so "isn't surprising that they require this additional information".

I'm going to leave this issue open, but am going to change it to a "tracking" issue that @keo-bisq and I can use to keep track of these kind of FasterPayments-related issues, and see what we want to do with them over time.

For the moment, it seems that we should leave the status-quo as it is, and **not** require users to enter first and last name. My rationale for this is that, in January alone, I can see on the order of 30 FasterPayments-based trades, and this is the only one I've personally arbitrated that had this problem (I have had similar cases in the past, but just a couple). At this rate, it is probably better to do the following:

1. continue preserving privacy for the majority by not requiring first and last name for FP trades
2. cancel the few trades that do end up going to arbitration because of this issue
3. log those trades (by ID) here in this issue so we have a sense of the prevalence of the problem over time.

**Comment by ManfredKarrer** [comment]
I would also prefer to keep it and only change if we get more issues. I would do the implementation as it requires also data model related changes.

**Comment by tomatopeel** [comment]
I am experiencing this issue using LLOYDS BANK PLC

**Comment by tomatopeel** [comment]
Putting "N/A" in the name field seems to have worked as a workaround so far. Will update here if there are any problems, marked payment as started.

**Comment by tomatopeel** [comment]
It worked, trade completed and closed, so I'd suggest trying that for anybody also experiencing this issue.

**Comment by cbeams** [comment]
Thanks for that, @tomatopeel!

**Comment by cbeams** [comment]
Trade `wkamn` is suffering from this problem. I've advised the buyer to try the "N/A" approach described above; we'll see if that works.

**Comment by cbeams** [comment]
Issue moved to [bisq-network/support #87](https://github.com/bisq-network/support/issues/87) via [**ZenHub**](https://www.zenhub.com/)
