### ISSUE TITLE
Where is FairCoin?

### ISSUE THREAD

**Issue by juanjgit** [bisq-network/bisq#1277]
It was there last time I installed Bisq and now it is not. I can not see any note about de-listing in forum or release notes. Where did it go?

**Comment by ManfredKarrer** [comment]
It was never traded. We removed all never traded coins in v 0.6.0. You can add it again by fulfilling the requirements at https://github.com/ManfredKarrer/docs/blob/list-token/exchange/howto/list-token.adoc
