### ISSUE TITLE
Bisq reports exchange rate as N/A

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1281]
A number of reports have come in recently about Bisq reporting `N/A` for the exchange rate price:

From https://twitter.com/mischa_demidov/status/956523069518082049:

![image.png](https://images.zenhubusercontent.com/56f1d5436caf56c9d38e1e86/8c90af30-6fc5-4410-b3cc-66e7e6c22f43)

From https://bisq.slack.com/archives/C0336TYTG/p1516815267000568

![image.png](https://images.zenhubusercontent.com/56f1d5436caf56c9d38e1e86/b6d7277c-ba66-4b34-8f71-c8c3f268180a)

**Comment by cbeams** [comment]
@ManfredKarrer started working on this yesterday. From https://bisq.slack.com/archives/C1267HFD1/p1516922120000303:

> There are repeated issues with price nodes not delivering data. I will prepare a new release with a fix for that.

And it appears that @ManfredKarrer's commits d565c9fe0...9027db5c2 have been about doing just that.

**Comment by ManfredKarrer** [comment]
It is implemented in master. Will get released soon.
