### ISSUE TITLE
Seller Trade Acceptance

### ISSUE THREAD

**Issue by llhoppy** [bisq-network/bisq#1282]
I would like to suggest the following change to how Bisq deals with new trades from a sellers perspective. 

Currently a buyer is able to browse available offers from sellers and review each individual buyer before choosing who to trade with. As a seller I would like to be prompted when a buyer accepts my trade offer and given a chance to review the buyer before accepting the trade.For example, this helps with a trade where the buyer failed to make payment and the trade gets stuck in arbitration for weeks.

thanks for your time and consideration

**Comment by ripcurlx** [comment]
@llhoppy: Did you run into this problem already once? Maybe we could offer the option to exclude certain onion addresses of certain offers, if you had issues with this user on previous trades. Letting the seller confirm the buyer by default might slow down the trading process additionally for everyone.

**Comment by llhoppy** [comment]
Agreed, having a way to exclude certain onion addresses from a users sell offers would provide a good solution for this problem

**Comment by ManfredKarrer** [comment]
@llhoppy The take-offer process is not interactive. That would destroy usability as it would require that the maker is online or that the take offer process is delayed until both are online (there is a handshake protocol at take offer and if both would be offline it can take very long).
If you know a user with whom you don't want to trade you can block his onion address at the settings.

**Comment by ripcurlx** [comment]
Closing as complete based on information in https://github.com/bisq-network/bisq/issues/1282#issuecomment-361452015
