### ISSUE TITLE
Refactor method for checking payment methods matching and add unit tests 

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1285]
Refactor method io.bisq.core.payment.PaymentAccountUtilisPaymentAccountValidForOffer and add unit tests.

**Comment by tau3** [comment]
Hello! I'm currently working on the issue.

**Comment by ManfredKarrer** [comment]
@tau3 Thanks a lot!

**Comment by tau3** [comment]
@ManfredKarrer it is here: https://github.com/bisq-network/exchange/pull/1295/

**Comment by ManfredKarrer** [comment]
Great thanks! I plan to release tomorrow a new version and prefer to merge your PRs after the release to not add extra risks and testing effort. 

Also don't forget to make a compensation request:
https://github.com/bisq-network/compensation/issues

Here an overview about the DAO:
https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc
