### ISSUE TITLE
Support quick access to top nav items with ⌘1–⌘9 keyboard shortcuts

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1286]
This feature is about increasing speed and productivity for Bisq power users (especially @bisq-network/arbitrators!) by reducing the need to use the mouse for navigation.

This, like another recent bounty we did in #1144, is just one of many such keyboard shortcut implementations that can add up to better productivity and enjoyment when using Bisq. Another would be supporting alt+letter key combinations for navigating to submenu items (but that would be managed as a separate issue; I'm just mentioning it here for context).

![image](https://user-images.githubusercontent.com/301810/35455589-d241008c-02d2-11e8-9bc5-8b998178a846.png)

Of course, it wouldn't be ⌘ keys on Windows and Linux, it would be whatever is idiomatic there for this kind of navigation.

Note that while there are usually only 8 top nav items, the DAO tab can be enabled with ⌘D, making a 9th.

**Comment by blabno** [comment]
I'm taking this bounty.

**Comment by cbeams** [comment]
Great!

**Comment by cbeams** [comment]
From https://bisq.slack.com/archives/C1267HFD1/p1517382960000170:

![image](https://user-images.githubusercontent.com/301810/35610466-a62fd9f4-0661-11e8-931c-ad2b4cb928a7.png)
