### ISSUE TITLE
Check if payment label is visible in blockchain

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#129]
Check if payment label used to open/pre fill external wallet got added to tx and is publicly visible in blockchain? I assume it is not, but need to check that, if so we should not use the label. Using a label should be optional (preferences)

**Comment by cbeams** [comment]
@ManfredKarrer, closing this issue as I believe you said you completed it.

**Comment by ManfredKarrer** [comment]
Checked with https://www.biteasy.com/testnet/addresses/mhEmPKCcoHhrwFnhj5evWsR49ZZHD9kozr 
Labels are only used locally inside a wallet app
