### ISSUE TITLE
Add payment method Revolut

### ISSUE THREAD

**Issue by flix1** [bisq-network/bisq#1312]
**Revolut** is an instant-payment app which can be easily funded from bank accounts or debit cards. 

It works for 26 currencies and in all of Europe + North America.

Payments are instant and not refundable.

https://www.revolut.com

Native currencies supported on the app (for instant in-app payments)
USD, GBP, EUR, PLN, CHF, DKK, NOK, SEK, RON, SGD, HKD, AUD, NZD, TRY, ILS, AED, CAD, HUF, INR, JPY, MAD, QAR, THB, ZAR.

Currencies supported for spending (with Revolut debit card): 120+
https://www.revolut.com/es/faq?lang=en#what-currencies-are-supported-for-spending

**Comment by flix1** [comment]
**Not** working in the US yet.

**Comment by montvid** [comment]
I would like that to be added because of instant payments between revolut users.

**Comment by montvid** [comment]
the problem is that you have to share your telephone number with another user to send funds. Good for friends but not so good for strangers calling you - or tracking. :D

**Comment by nuschpl** [comment]
@montvid so we not add a warning in GUI, people will choose between anonymity and ease of use

**Comment by ManfredKarrer** [comment]
@flix1 Should we add Revolut to 0.6.6?
If so can you provide me the required data fields (name, account nr,...)?
Can it be used with same currencies or is it like Transferwise for FX?

**Comment by montvid** [comment]
Revolut needs just a telephone number to send funds to another Revolut user. I am new to Revolut but my tx got confirmed by my friend in a few minutes if not seconds. If both users need to have each other telephone numbers I don't know.

**Comment by flix1** [comment]
@ManfredKarrer I think that it's worth trying out. It is very widespread in Europe and might work well for small amounts.

Privacy is a concern, but not more so than with SEPA payments.

As @montvid mentions the only data field needed is a telephone number (it does allow other options like e-mail, but the standard and most efficient way to id users is phone nº).

I suggest we try it but limit amounts initially (to 0.05 BTC max)

**Comment by flix1** [comment]
> Can it be used with same currencies or is it like Transferwise for FX?

Payments are made with the same currency always. So EUR wallet to EUR wallet. If you send GBP, the other user will receive GBP.

Then users can easily change currencies within the app.

**Comment by ManfredKarrer** [comment]
Ah cool. Will add it.
So account id is either email or tel nr. Email will give users a bit better privacy.

**Comment by stevenkain** [comment]
Awesome! BTW, they recently also became available in the US: 
https://community.revolut.com/t/revolut-has-landed-in-the-usa/12406

**Comment by ManfredKarrer** [comment]
@flix1 @montvid @stevenkain Is the account ID really only the phone number or are there alternatives like email?

**Comment by flix1** [comment]
You can use e-mail.. but not every user has a validated e-mail associated to their Revolut account, whereas every user must have a valid phone number.

**Comment by stevenkain** [comment]
The idea is that you can send someone money knowing only their telephone
number.

Pe 22 feb. 2018 19:20, "flix1" <notifications@github.com> a scris:

**Comment by ManfredKarrer** [comment]
<img width="926" alt="screen shot 2018-02-22 at 19 55 37" src="https://user-images.githubusercontent.com/1449498/36572535-62961464-180a-11e8-903f-56955903f162.png">

**Comment by stevenkain** [comment]
Sweet!

Pe 23 feb. 2018 02:56, "Manfred Karrer" <notifications@github.com> a scris:

**Comment by ripcurlx** [comment]
There is also a name field when adding a contact. Did anyone try to add an account with a correct phone/email, but a custom name and test a payment with that person? If not I could do a test payment to someone with a Revolut account. Just DM me within Slack.

**Comment by ripcurlx** [comment]
I wanted to create a sell offer with GBP and Revolut, but it always defaults to EUR and I didn't find a way to change it (Top market exchange rate selection and default currency in settings didn't have an effect). Is this not possible and why is it using Euro by default?
![Account](https://user-images.githubusercontent.com/170962/36585284-89a655f0-187d-11e8-841c-fe3d312ad4b2.png)
![Sell BTC](https://user-images.githubusercontent.com/170962/36585285-89c6bae8-187d-11e8-875b-8a34594d5f87.png)

**Comment by ripcurlx** [comment]
Ups, my bad. I selected the wrong payment method. Too much switching of payment methods ;-)

**Comment by ManfredKarrer** [comment]
Seems Revolut requires name as well and moile nr. instead of email:

"Add their name and mobile number as registered on their Revolut profile to your contacts."
https://www.revolut.com/pa/faq#how-can-i-send-money-to-another-revolut-user

**Comment by flix1** [comment]
@ManfredKarrer you don't need a name to make a payment, this is only to find them in your contacts... since Revolut app looks for people in your mobile contacts. But if payee is not there you can just name them anything you want.

To actually send a payment e-mail or phone number is enough. Revolut will add the other details...

**Comment by ManfredKarrer** [comment]
@flix1 Ok. Then i leave it as it is with email or phone nr.

**Comment by cbeams** [comment]
See https://github.com/bisq-network/bisq/issues/1806, regarding common issues around Revolut payment links.

**Comment by montvid** [comment]
I just tested the revolut payment system. For bisq purposes only Name and Surname and payment link is needed. The buyer can provide a photo of his Revolut history with the sellers name and surname to confirm he has paid/sent the link to the seller. email is not needed if there is a way to send the link via bisq

**Comment by stevenkain** [comment]
For businesses accounts you already have a API acces to their bank account
info (given by consent of the owner). I would be surprised if this won't
become available also for personal Revolut accounts, if there isn't already
implemented.

**Comment by montvid** [comment]
@cbeams i have read #1806 my opinion is the revolut links should be shared in bisq if not possible sent manualy via email ie option 2. Good luck. 🙂

**Comment by stevenkain** [comment]
Is there no way to automate these with the API from Revolut?

**Comment by ManfredKarrer** [comment]
Close that issue as Revolut is implemented. Regarding the discussion which contact data is best to provide please continue at #1806
