### ISSUE TITLE
An error occurred when taking the offer.  A timeout occurred.  The taker fee is already paid. In the worst case you have lost that fee.

### ISSUE THREAD

**Issue by cybairfly** [bisq-network/bisq#1319]
![error](https://user-images.githubusercontent.com/18344357/35737299-56d099ae-082b-11e8-8ea6-ce6f57aa5b5f.png)
An error occurred when taking the offer.

A timeout occurred.

The taker fee is already paid. In the worst case you have lost that fee.
Please try to restart your application and check your network connection to see if you can resolve the issue.Please try to restart your application and check your network connection to see if you can resolve the issue.

[bisq.log](https://github.com/bisq-network/exchange/files/1689600/bisq.log)

**Comment by cbeams** [comment]
Issue moved to [bisq-network/support #67](https://github.com/bisq-network/support/issues/67) via [**ZenHub**](https://www.zenhub.com/)
