### ISSUE TITLE
Fractured Bisq Community?!

### ISSUE THREAD

**Issue by tr37ion** [bisq-network/bisq#1320]
There is one thing I'm thinking of for quite some time. If  I go to [Community Page](https://bisq.network/community/) I get a really long list of pages the Bisq Community is able to communicate, like:

   * @bisq-network on GitHub
   * @bisq_network on Twitter
   * Bisq YouTube channel
   * Bisq Slack workspace
   * Bisq Forum
   * Bisq Contributor mailing list
   * #bisq on Freenode IRC
   * r/Bisq Subreddit
   * ‘bisq’ Keybase team

Categorizing those community sites:

   * @bisq-network on GitHub - async communication
   * @bisq_network on Twitter - semi-live
   * Bisq YouTube channel - videos?!
   * Bisq Slack workspace - live chat
   * Bisq Forum - async communication
   * Bisq Contributor mailing list - async communication
   * #bisq on Freenode IRC - live chat
   * r/Bisq Subreddit - async communication
   * ‘bisq’ Keybase team - live chat
   * Developer Kanban - project management

Sometimes I think, how can you manage all of those community platforms? Wouldn't it be better to drastically reduce them to some core ones? Like:

   * @bisq-network on GitHub --> kept --> Github
   * @bisq_network on Twitter --> kept --> Github Release Tab
   * Bisq YouTube channel --> discontinue until someone does regular stuff
   * Bisq Slack workspace --> Discontinue --> IRC
   * Bisq Forum - async communication --> Github Issues
   * Bisq Contributor mailing list - async communication --> dicsontinue --> IRC or Github Issues
   * #bisq on Freenode IRC --> discontinue --> IRC
   * r/Bisq Subreddit - async communication --> kept, but community managed --> Github Issues
   * ‘bisq’ Keybase team - live chat --> IRC
   * Developer Kanban - project management --> discontinue --> Export to Github Projects

This will reduce the Platforms to:

   * ***Github Issues*** - for async community
   * ***IRC*** - for live communication
   * ***Github Projects*** - for fully integrated dev kanban

Everything else is a nice plus, but not actively maintained by the core team. If the community wants to use other platforms let them grow it naturally and hop on if it is successful and manageable. 

I feel trying to be everywhere but not really hurts in the end, as it doesn't guide new people, where to get answers eg. 

At first this might feel a bit awkward only using Github and IRC, but both platforms cover almost everything you need. And Github Issues are directly linked to Github Projects (Kanban) and makes the issues easily manageable. For live support everyone can just enter the IRC.

Try it for some weeks, and find out if it works for you and the community. I'm pretty sure this will reduce project management time for you. Also if the community needs another Platform, they will open one, sure. Then if that platform comes in nicely, then you can hop on, but not the other way around IMHO.

EDIT: It might be also possible to use Keybase instead of IRC as it provides live chat, community management, mobile apps and git repo, too. Just a thought.

**Comment by ManfredKarrer** [comment]
We removed Keybase and mailing list. Kanban is not used anymore.
Basically agree but there are no plans to remove any of our channels.
Main channels are:
- Github
- Slack
- Forum
- Twitter

The others are additional for those who prefer certain style (IRC, Reddit). Youtube is needed for video/hangouts but not seen as communication channel.

I will close here, if you want to discuss further please use the Forum. We want to keep GH issues for technical issues mostly.
