### ISSUE TITLE
Java null pointer error

### ISSUE THREAD

**Issue by unixb0y** [bisq-network/bisq#1322]
Hello, as I opened Bisq, I got a pop-up with a Java null pointer exception and something that said to post the logfile here.
Am I safe to post it (no personal info included)?
If yes, I'll post it!
Cheers.

**EDIT**: Never mind, I lost the log file. Still I'll leave this open so you know about this little error that came up.

**Comment by ManfredKarrer** [comment]
There is no personal info in the logs but you can also send me the post by email (manfred at bitsquare dot io).

**Comment by unixb0y** [comment]
Hi @ManfredKarrer does Bisq save the logs anywhere? I hit "copy" but it seems it didn't do that and by then I had already closed the Pop-Up.

**Comment by ManfredKarrer** [comment]
@unixb0y  Yes you can open the log at account/backup.

**Comment by unixb0y** [comment]
Great 👍 @ManfredKarrer 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ManfredKarrer** [comment]
Close as no info available
