### ISSUE TITLE
Serious Spike in upload speed when opening bisq (causing lag for users)

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#1324]
Not sure what you have changed since update 0.6.4, because 0.6.5 has started causing 'lagging/throttling' issues.
By lagging, i mean that the upload speed of my internet connection spikes up as soon as bisq is connected to the TOR network. Which in turn causes my internet connection to lag/throttle.
Some users around the world still have an upload speed of 500kbps or 1mbps. Not sufficient enough.  Of course this problem did not occur before bisq 0.6.5 update.

my TOR connection runs as a daemon regardless if bisq runs or not. as soon as bisq is run and connects to all tor nodes as well as the hidden service.. i monitor my upload speed using nethogs and i see a much bigger spike than before.  I see a spike of 25 - 30kbps on btc_mainnet

Has anything been changed in this? if yes.. please could you lower this in any way possible?
Its actually unbearable and impossible to have bisq open in the background.

**Comment by ghost** [comment]
I was wondering, if you have indeed changed something and that a higher upload speed is needed or because there is an increase in users on the bisq network then maybe you can include a variable in the code to control the upload speed of the tor hidden service, and in turn include it in the network options to allow users like me with a lower internet speed to be able to change the upload speed to something lower and convenient.

**Comment by ManfredKarrer** [comment]
The only idea I have to that is that the Tor Dos protection they recently added to relay nodes hits your connection. If you have Tor open for many other connections/apps you might get into their red zone.
See the Tor relay mailing regarding the changes: https://lists.torproject.org/pipermail/tor-relays/2018-January/014357.html

**Comment by freimair** [comment]
@ghost is the issue still there?

And how did you manage to get your Bisq to use your tor deamon? or did I miss your point there?

**Comment by freimair** [comment]
hm. @ManfredKarrer, there is no more @ghost on github, so there is no chance to reach out to him. I suggest, as we do not have a similar request (do we?), we close the issue?

or shall I look into implementing a userdefined upload limit?

**Comment by ManfredKarrer** [comment]
Yes lets close it then...

**Comment by cbeams** [comment]
FYI, @ghost is the placeholder account that GitHub uses when the original poster has deleted their account.

**Comment by ManfredKarrer** [comment]
ah good to know ;-)
