### ISSUE TITLE
Java null pointer exception in v0.6.4

### ISSUE THREAD

**Issue by JoKeyser** [bisq-network/bisq#1327]
The error occurred while opening, and then it proceeded to work fine.
Nevertheless, here the log, in case it points to an actual problem.

[bisq.log](https://github.com/bisq-network/exchange/files/1696187/bisq.log)

**Comment by JoKeyser** [comment]
Just upgraded to v0.6.5-1 (Arch Linux) and it didn't happen again. So maybe this issue is irrelevant.

**Comment by ManfredKarrer** [comment]
Yes that nullpointer is fixed in 0.6.5. Thanks for reporting!
