### ISSUE TITLE
Failed trade - twice

### ISSUE THREAD

**Issue by amuuza** [bisq-network/bisq#1338]
Hi,

I have tried the same trade twice, but twice I have had a "trade failed".

Trade ID: SeiOKTX-0bff3f98-57a1-48e7-ad68-984581a48f2e-065
Selected arbitrator: 3b7cft5k4ae6a236.onion:9999
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

I guess you will need the logs in order to troubleshoot, but isn't that a too private info to be attached here? 
I do not know what the contents of the logs are.

Thank you!

**Comment by ManfredKarrer** [comment]
Yes the logs would be good. You can open it at account/backup. U can send it to me by email: manfred at bitsquare dot io

**Comment by ManfredKarrer** [comment]
From the logs I cannot see why it failed, just that you did not get the expected messages back from the peer. Is probably an issue on the peers side or bad network connectivity (yours or peer).
You can request from @cbeams a refund for the lost trade fee.

**Comment by amuuza** [comment]
Thank you Manfred
