### ISSUE TITLE
Larger bid/offer thresholds outside the market price

### ISSUE THREAD

**Issue by xirua** [bisq-network/bisq#1339]
Hi guys, further to our conversation today on your growth call, I personally find the 20% threshold for fixed limit orders outside the market price are too small.

Bitcoin is very volatile and can move 20% in a single day. For a savvy investor (not just traders), you may have no interest in transacting within that limited threshold. As such, you are unable to rest orders. You have to wait for the index price to move close enough to your target before placing the order. What if this occurs overnight while you're sleeping? What if you want to advertise that liquidity for as long as possible for the best chance of a fill in a low volume environment? 

While I understand there is an undesired network load this could introduce, I have never seen this type of threshold before on an exchange. It may prevent liquidity from stacking in the book. It may also prevent participants from 'lining up' at a price and having the right to execute in the sequence their order was received.

These thresholds should be reviewed and increased, if not removed.

**Comment by ManfredKarrer** [comment]
I just changed that for the next release to 30% default and can be set to max 50% in the settings.

**Comment by xirua** [comment]
Outstanding! Thanks, Manfred.
