### ISSUE TITLE
Trade failed twice after funding trade

### ISSUE THREAD

**Issue by fran-rial** [bisq-network/bisq#1340]
An error occurred when taking the offer.

A timeout occurred.

The taker fee is already paid. In the worst case you have lost that fee.
Please try to restart your application and check your network connection to see if you can resolve the issue.Please try to restart your application and check your network connection to see if you can resolve the issue.

[bisq_timeout_after_deposit.txt](https://github.com/bisq-network/exchange/files/1710062/bisq_timeout_after_deposit.txt)

Is there a way to get that fees back?

**Comment by cbeams** [comment]
Issue moved to [bisq-network/support #73](https://github.com/bisq-network/support/issues/73) via [**ZenHub**](https://www.zenhub.com/)
