### ISSUE TITLE
Add payment method: Halcash

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1348]
Investigate what is needed to add Halcash as payment method.
@flix1 Are you familiar with Halcash?

**Comment by flix1** [comment]
I'm familiar with Halcash and have used it in the past. It's an SMS-based payment system widely used for remittances and connected to several ATM networks in Europe. There are several companies which are using it to allow users to sell Bitcoin.

It has low limits and high fees, but is reliable and fast.

I have my doubts that it is a good fit for Bisq.

**Comment by flix1** [comment]
Use Halcash to sell Bitcoin

Bitnovo   https://www.bitnovo.com/
Bit2me   https://bit2me.com/

The best feature of Halcash is being able to withdraw cash directly at 10k+ ATMs in Europe.

Also somewhat used in LBC:
https://localbitcoins.com/sell-bitcoins-online/hal-cash/

**Comment by ManfredKarrer** [comment]
We have often requests from people who don't want to use Banks and want more privacy. Halcash might be an option to serve those. Also not perfect privacy as phone number is the ID but might be a bit better than Banks.

**Comment by ManfredKarrer** [comment]
What would be the required data you need to know to send someone money?
How can the arbitrator proof the transfer?
Is there anything special required (like with cash deposit sending the photo of the receipt to the seller)?
I assume there is no chargeback risk at all.
What are max. amounts?

**Comment by alfsbs** [comment]
Issue moved to [bisq-network/payment-methods #3](https://github.com/bisq-network/payment-methods/issues/3) via [**ZenHub**](https://www.zenhub.com/)
