### ISSUE TITLE
Trade process (BTC buyer wait for confirmation screen): Show explicit Nr. of confirmations

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#135]
Nr. of confirmation should be displayed explicit with text, spinner/confirmation component is not enough

**Comment by haiqu** [comment]
This information is available by opening the Deposit Transaction (click the blue link) and looking at `Details -> Block`. Confirms is shown next to that.

**Comment by ManfredKarrer** [comment]
Yes, was a comment form an early usability tester, but nearly nobody else complained about that. Will close...
