### ISSUE TITLE
Not possible to select `English` anymore, if system locale is non-English

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1357]
Since the PR (https://github.com/bisq-network/exchange/pull/1313) was merged into master, I'm not able to select `English` anymore in the `Settings` screen. It always defaults to my system locale (`de_AT` in my case). I'm able to select any other locale (e.g. `Spanish`), which works after re-start. But whenever I select `English` it displays the `To apply the language change to all screens requires a restart.` in my systems language (`de`) and not in English. When restarted `English` is selected in the `Settings`, but everything is in German.

**Comment by ripcurlx** [comment]
It has something to do with the default locale setting. I just made a quick test and added a new property file displayStrings_en.properties with the English translations in it and it works. 
When 
`resourceBundle = ResourceBundle.getBundle("i18n.displayStrings", newValue, new UTF8Control());`
is called it will always return the german resource bundle no matter if "de_AT" or "en_AT" is used.

**Comment by ManfredKarrer** [comment]
Yes seems the setting of the default local will overwrite your settings. 
@blabno Can you have a look to fix that?

**Comment by blabno** [comment]
Yes, I'll do that on Monday when I'm back from holiday.

14 lut 2018 18:32 "Manfred Karrer" <notifications@github.com> napisał(a):

**Comment by blabno** [comment]
After looking at the way the ResourceBundle work we should duplicate default `displayStrings.properties` and name it `displayStrings_en.properties`.

Here's how it works.

Assuming you have selected `en` language.
First ResourceBundle tries to find file `displayStrings_en.properties`. If the file cannot be found then
RB checks what is default locale (looks at env variables). In case your env locale is `de` and there is a file
`displayStrings_de.properties` then that file is going to be loaded. 
`displayStrings.properties` is used only if you do not have a file with suffix matching requested or env locale.

What do you think @ManfredKarrer ? Should we duplicate?

**Comment by blabno** [comment]
Alternatively we could add
```
if ("en".equalsIgnoreCase(newValue.getLanguage()))
  newValue = Locale.ROOT;
```
before
```
resourceBundle = ResourceBundle.getBundle("i18n.displayStrings", newValue, new UTF8Control());
```

**Comment by ManfredKarrer** [comment]
Prefer the second approach with Locale.ROOT.
