### ISSUE TITLE
Regression: No longer possible to register arbitrator in REGTEST.

### ISSUE THREAD

**Issue by citkane** [bisq-network/bisq#1359]
At:
https://github.com/bisq-network/exchange/blob/ff629542e7e83c70202078c20edec6a37f5f5878/common/src/main/java/io/bisq/common/app/DevEnv.java#L13

`USE_DEV_PRIVILEGE_KEYS` is  `final` and has been changed to `false`, thus preventing arbitrator registration in REGTEST.

If we change it to:
```java
public static boolean USE_DEV_PRIVILEGE_KEYS = false;
```
and then, immediately inside the main method at:
https://github.com/bisq-network/exchange/blob/ff629542e7e83c70202078c20edec6a37f5f5878/gui/src/main/java/io/bisq/gui/app/BisqAppMain.java#L37
insert:
```java
for (String arg: args){
    if(arg.contains("REGTEST")) DevEnv.USE_DEV_PRIVILEGE_KEYS = true;
}
```
the behaviour returns to expected and possible production issues which may have caused the change are avoided.

**Comment by ManfredKarrer** [comment]
I wanted to keep both REGTEST and USE_DEV_PRIVILEGE_KEYS separated as you might to want to test with USE_DEV_PRIVILEGE_KEYS = false as well. Best would be to use a new prog. argument. Easiest is to just change false to true in the code.

**Comment by citkane** [comment]
Fair enough, but it would be even easier if we could change `false` to `true` from anywhere in the codebase without having to update code in DevEnv.java. This would need removing of `final` from the `USE_DEV_PRIVILEGE_KEYS` initial declaration.

As it is, module 'common' needs to be recompiled to affect the change, which means that, to work on a single module, I have to bring in the whole 'exchange' stack of modules and compile them all with the changed 'common'.

I am working on a stand-alone, drop-in module and I do not want to have to change any code outside of my module. It is better for me to depend on bisq modules from jitpack in the module POM. This is not however possible if DevEnv.java declarations remain `final`.

Is there any reason that they need to be `final`?

**Comment by ManfredKarrer** [comment]
Ah ok. No problem to make it non-final. Best would be then to use Lombok @Getter/@Setter.

**Comment by blabno** [comment]
@citkane are you working on this change, or can I take it?

**Comment by citkane** [comment]
@blabno I am not integrated into the dev cycle yet, I would appreciate if you could take it, thanks to you and @ManfredKarrer .

**Comment by blabno** [comment]
@ManfredKarrer since `USE_DEV_PRIVILEGE_KEYS` is supposed to be configurable then probably it should be part of `BisqEnvironment`?

**Comment by ManfredKarrer** [comment]
@blabno : Yes.
