### ISSUE TITLE
Add feature for deactivating an offer

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1368]
We add a button to the open offer for deactivating an open offer. That will remove it from the public offer book but keeps the offer in the Bisq app. It has the same functionality like when the Bisq app gets shut down. The user can then activate the offer again any time and it gets re-published to the offer book. 

<img width="1199" alt="screen shot 2018-02-18 at 14 40 39" src="https://user-images.githubusercontent.com/1449498/36355997-bef7ac8a-14b9-11e8-987a-72b0ddf393b2.png">

**Comment by ManfredKarrer** [comment]
@ripcurlx Can you have a quick look to the graphical solution? Would have preferred  a nice animated sliding toggle button (like here https://www.youtube.com/watch?v=maX5ymmQixM) but have not found a ready made component and not enough time to build it myself.

**Comment by ManfredKarrer** [comment]
@ripcurlx  Could you review commit https://github.com/bisq-network/exchange/commit/beaaf59b703929b97a7010e51a12f236f60bfcbd in release-candidate-0.6.6 branch?

**Comment by ManfredKarrer** [comment]
@cbeams @ripcurlx Could you check that as well when testing the RC?

**Comment by ripcurlx** [comment]
I missed your comments on the design issue, but I‘ve already tested it in the morning (see test document)

**Comment by ManfredKarrer** [comment]
Cool. I will close it now.
