### ISSUE TITLE
Add memo field for withdraw BTC funds

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1387]
At the "send funds" screen we should add a new input field for a user message/memo so part transfers can be easier assigned.
In the "transactions" screen we should add the truncated memo text to the "Withdrawn from wallet" text. The tooltip should display the full text. Maybe "Withdrawn from wallet" can be replaced by a shorter text...

**Comment by ManfredKarrer** [comment]
Still relevant

**Comment by niyid** [comment]
Anybody taken this yet?

**Comment by cd2357** [comment]
Solved by @petrhejna in #4229
