### ISSUE TITLE
package io.bisq.generated.protobuffer does not exist

### ISSUE THREAD

**Issue by galaxycash** [bisq-network/bisq#1389]
I get errors when compiling
Error:(25, 37) java: package io.bisq.generated.protobuffer does not exist
Error:(80, 14) java: package PB does not exist

Intellij IDEA & Windows

**Comment by citkane** [comment]
For IntelliJ you need to add modules:

- Lombok plugin
- Protobuf Support

You will need to flush cache, restart and Maven re-import after modules installed.

PB is still flagged as not found in real time editor (can't figure out why), but Maven compiles and runs without errors.

**Comment by rpgoldberg** [comment]
I am getting this issue as well, but against the gradle import. I have added the Lombok plugin and Protobuf Support, flushed cache, restarted, and reimported to no avail. Latest IDEA against openJDK 10 on Windows 10.

**Comment by cbeams** [comment]
From https://github.com/bisq-network/bisq/blob/master/README.md#importing-bisq-into-intellij-idea:

> TIP: If you encounter compilation errors related to the `io.bisq.generated.protobuffer.PB` class, it is probably because you didn't run the full Gradle build above. You need to run the `generateProto` task in the `common` project. You can do this via the Gradle tool window in IDEA, or you can do it the command line with `cd common; ./gradlew generateProto`. Once you've done that, run `Build->Build Project` again and you should have no errors.

Closing as this should solve your problem. Please reopen if it doesn't.
