### ISSUE TITLE
Taking Offer Failed, Taker Fee lost x4

### ISSUE THREAD

**Issue by tomatopeel** [bisq-network/bisq#1393]
```
An error occurred when taking the offer.

A timeout occurred.

The taker fee is already paid. In the worst case you have lost that fee.
Please try to restart your application and check your network connection to see if you can resolve the issue.Please try to restart your application and check your network connection to see if you can resolve the issue.
```

Just got this trying to take an offer 4 times in a row, I didn't realize I was repeatedly paying taker fees!!!

I'm going to send my logs for this to Manfred's e-mail that I was given before, would be good to know the extent to which it's safe to post logs to github issues though

**Comment by tomatopeel** [comment]
FWIW this is occurring when I've not got a great internet connection, just tethering to my mobile.

**Comment by tomatopeel** [comment]
I'm up to 6 failures to take the offer now. It's still there and I thought I'd try again with a fast connection and then with the new 0.6.6 release, still the same result, so it seems likely to be connected with the screw-up in https://github.com/bisq-network/support/issues/72

**Comment by cbeams** [comment]
Issue moved to [bisq-network/support #75](https://github.com/bisq-network/support/issues/75) via [**ZenHub**](https://www.zenhub.com/)
