### ISSUE TITLE
an error occurred when placing the offer: v0.6.6

### ISSUE THREAD

**Issue by Alexander-The-Decent** [bisq-network/bisq#1395]
This has happened multiple times and has only happened since I updated to v0.0.6

An error occurred when placing the offer:

A timeout occurred at publishing the offer.

No funds have left your wallet yet.
Please restart your application and check your network connection.
[bisq.log](https://github.com/bisq-network/exchange/files/1756212/bisq.log)

**Comment by ripcurlx** [comment]
Hi @Alexander-The-Decent! As the Bitcoin transaction memory pool was packed during the time you've experienced your timeouts, I wanted to check back if you still have this issue now?

**Comment by ManfredKarrer** [comment]
@Alexander-The-Decent @ripcurlx I think the reported timeout is not a trade timeout but at take-offer or make-offer. That can be either due a bug on the peers side or bad network connectivity.
