### ISSUE TITLE
The day my Bisq died :'(

### ISSUE THREAD

**Issue by QbiX90** [bisq-network/bisq#1396]
Yes, a new Update! :)
The Download took a while but then, Key check... finished. Green letters: Please shutdown 0.6.5 and install 0.6.6.

RIP.

Oh, The Complete Debug flog is inside this .rar.txt - I dont want anyone grant access to it because I dont rly know, what information could be abused. (Trust me, ppl are bad.)
So if there is a need from the dev. Team - someone of them should write me.

Its the 3rd time I lost everything. 💥 💥 💥 
I dont know whats wrong. 

Love from Germany, ❤️ 
Marvin Beer

[DeadOnRestart(Update).rar.txt](https://github.com/bisq-network/exchange/files/1756544/DeadOnRestart.Update.rar.txt)

**Comment by ManfredKarrer** [comment]
Can be explain more specific what happened? You can send me screenshots and log to manfred at bitsquare dot io.

**Comment by QbiX90** [comment]
I hope my logfile has helped you.

I just reinstalles everything and it started as it should.
But I am afraid I'm way to late. So Bitcoin doesnt really make sence with this application if you have none. 😢 

![image](https://user-images.githubusercontent.com/36821536/36656058-b5c9ffce-1ac6-11e8-87b6-511170523720.png)

**Comment by ManfredKarrer** [comment]
You are never too lat with Bitcoin ;-). 1 Satoshi is still super cheap ;-)
