### ISSUE TITLE
Market price margin set to zero when tabbing through

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1411]
When tabbing through the create offer interface. Distance is set to zero when field loses focus, but amount to receive and price is not updated.
![Margin set to zero](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/314bf96d-e0ae-4664-b77d-91cb9905eb41)
![Focus leaves margin field](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/6f3ae155-36d8-4eb4-afee-180022e928b2)
Either we don't default it to zero when tabbing through or we update the corresponding fields.

I personally would keep the zero default and just update the corresponding values correctly, as it would help the user to finalize the offer without the need to think too much.

What do you think @ManfredKarrer?

**Comment by ManfredKarrer** [comment]
Yes agree.
