### ISSUE TITLE
Add payment method: ATH Móvil (Puerto Rico)

### ISSUE THREAD

**Issue by josedcrespo** [bisq-network/bisq#1414]
In Puerto Rico, Evertec, Inc. provides person to person interbank transfers using an app called ATH Móvil. Recently they achieved the one million users milestone. (That's ~1/3 of the population) Due to recent spike in global and particularly local interest in cryptocurrencies it provides a great method for buying bitcoin using Bisq. The only downside is that is limited to a $500 maximum daily transfer. The requirement to do a transfer is the person's mobile phone number.

**Comment by abigail830** [comment]
@ripcurlx here should be also in:payment-methods :-P

Given I having a fresh memory for implement new payment method, if you see any issue on this topic is ready to implement, feel free to assign to me. If no, then I would go on explore other items.

**Comment by josedcrespo** [comment]
If no other additional information is needed, this is ready to implement. Thanks!

**Comment by alfsbs** [comment]
Issue moved to [bisq-network/payment-methods #4](https://github.com/bisq-network/payment-methods/issues/4) via [**ZenHub**](https://www.zenhub.com/)
