### ISSUE TITLE
Add estimated settlement times for different payment methods

### ISSUE THREAD

**Issue by dolebas** [bisq-network/bisq#1415]
Low fees combined with settlement speed is a sweet competitive advantage compared to many current fiat-crypto exchanges.

Displaying estimated settlement times could help new users choose the best payment methods available.

**Comment by ripcurlx** [comment]
I like the idea @dolebas. This might nudge people to use more and more payment methods with faster settlement times as they are presented in a more favorable way.

**Comment by dolebas** [comment]
Glad to hear that @ripcurlx. Hopefully, helping people discover and choose optimal payment methods might potentially create a positive spiral with regard to liquidity =)

**Comment by ripcurlx** [comment]
Still relevant and might be solved in combination with our new instant trade feature.
