### ISSUE TITLE
Cleanup package scripts

### ISSUE THREAD

**Issue by mihaifm** [bisq-network/bisq#1417]
Hi, and thanks for this great tool!

I just compiled bisq from source and it worked smoothly. 
Then I tried to use the package script (`package/linux/64bitBuild.sh`), and encountered several problems:

- The file seems to contain a BOM which I had to clear with `:set -nobomb` in vim. This should be removed. 
- There are some private paths hardcoded inside. I tried setting `dir=.`
- I got the following output after running the script:
```
    Using base JDK at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre
    Using base JDK at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre
    Bundler DEB Installer skipped because of a configuration problem: Main application jar is missing.  
    Advice to fix: Make sure to use fx:jar task to create main application jar.
```

I eventually gave up in trying to build the package. I think we either need to make this file work without those private paths, or at least add clear instructions on what needs to be changed in this file in order to make it run.

thanks

**Comment by ManfredKarrer** [comment]
Close as new build system is in place
