### ISSUE TITLE
Font/UI sizing issue on HiDPI display

### ISSUE THREAD

**Issue by peterzen** [bisq-network/bisq#1425]
When running the application on a HiDPI screen in high resolution, the font size can be too small to the point of being unreadable as the application does not honor the display scaling setting. 

![image](https://user-images.githubusercontent.com/5878500/37014871-ca862efe-2103-11e8-9e09-b5b6cc12f19c.png)

 Is there a way to specify a scale factor via a Java/JavaFX environment variable, similarly to how Qt apps honor $QT_SCALE_FACTOR?

Platform: Dell XPS 13" display, Ubuntu 17.10, default display settings, resolution 3200x1800, scale: 200%

**Comment by sqrrm** [comment]
Bisq doesn't scale the UI on HiDPI monitors with linux since JavaFX doesn't handle the scaling in Java 8. Once upgraded to Java 9 it will work but there are some issues with switching to Java 9, see #1262

**Comment by peterzen** [comment]
Thanks @sqrrm, I suspected this was the case but couldn't find this issue - I'll keep an eye on it.

**Comment by ManfredKarrer** [comment]
We plan to use Java 9 soon. Hope that will fix it.

**Comment by 2m** [comment]
Java 9 added support for HiDPI in Linux and Windows: http://openjdk.java.net/jeps/263

That is, when using Java 9 the `GDK_SCALE` environment variable is considered and windows are scaled accrodingly.

Eagerly waiting for the upgrade of bisq to Java 9.

**Comment by ripcurlx** [comment]
@2m @peterzen Could you please verify if this issue is solved with our latest release 0.9+ (Java 10)?

**Comment by ysangkok** [comment]
Not fixed in 0.9.1.

![screenshot from 2018-12-18 10-54-22](https://user-images.githubusercontent.com/284023/50146116-5467c880-02b3-11e9-9c32-613ac3a3335a.png)

**Comment by ripcurlx** [comment]
@ysangkok Thanks - I'll have a look if there is an easy way to resize everything based on the OS scale factor.

**Comment by ysangkok** [comment]
But if I launch with `GDK_SCALE=2 ./Bisq`, it does scale. Some hacky launcher that can read the Ubuntu scale from Gconf would work, I guess... Really the Java runtime should detect this, so I guess this can still be considered a Java bug, even if you do ship Java.

**Comment by ripcurlx** [comment]
Thanks for the input! Maybe we can modify our javapackager setup to do so until it is fixed properly within Java.

**Comment by peterzen** [comment]
On Ubuntu 18.04 with OpenJDK 10.0.2 it honors both `GDK_SCALE` and the `org.gnome.desktop.interface scaling-factor` setting, all good.

**Comment by blackbookpro** [comment]
Bisq is displayed way too small on Ubuntu 20.04 on a Macbook Pro 15" Display (2880 x 1800). Is there a way to scale the view? Would appreciate any help!
![image](https://user-images.githubusercontent.com/10968562/101714031-131ce480-3a99-11eb-939e-5036f0c52151.png)

**Comment by ripcurlx** [comment]
@blackbookpro Did you have already a look at this short guide: https://github.com/bisq-network/bisq/issues/4541#issuecomment-695758900

**Comment by mateMathieu** [comment]
Hi, I did the trick that is documented in the FAQ to adjust the scaling for HiDPI screens, but at the following update the whole thing is wiped out.
Can't we find a better way that would avoid this?

It would also be nice to work with both GTK and QT.

Please!  :)
