### ISSUE TITLE
Stop support for Dash as basecurrency due lack of activity

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1430]
The last trade on Dash as base currency was back in September.

In the current release with the removal of DOGE we introduced a bug with the dash port number which does not match anymore the network ID which is derived from the nodes enum (was 9 before now its 6 as doge got removed from the enum).

As that shows supporting multiple base currencies comes with extra effort and is only justified if at least some activity is happening there. 
Beside that I need to run the arbitrator node and 2 seed nodes (which would require now also a hotfix for that bug). But instead of wasting time on something what nobody uses anyway I will stop supporting Dash as base currency. So I will stop my dash seed nodes which are not accessible anyway since the last release - which shows also that there are no user as there was no complaints.

If anyone wants to take over support for that which includes running an arbitrator and 2 seed nodes as well as testing when a new release is done and general maintenance and support please get in touch. 
Please understand that I cannot hand over arbitration rights to unknown persons due risks. So you need to have some solid reputation (which does not require a lot of effort for me to cross check).
It needs to be also a developer who is able to fix things and understands Bisq to a good degree.

**Comment by lordbah** [comment]
I'm sorry to see that but I understand your reasoning. I've had a sell offer up for a couple of months with no interest. Hopefully some time in the future ...
