### ISSUE TITLE
Improve design of BsqBlockChain

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1436]
@tau3 May I ask you for input about the DAO architecture?

There is specially one area with what I am not satisified.
It's: io.bisq.core.dao.blockchain.BsqBlockChain

This class is holding the mutable state of the blockchain containing only BSQ transactions.
There is a parser class (FullNodeParser or LiteNodeParser) which iterates the blocks, checks via the BsqVerification class if a tx is a relevant BSQ tx and if so it sets some state in the BsqBlockChain.
The parser is running in a separate thread. The data in the BsqBlockChain is accessed from several different classes on different threads (UI thread only reads, parser writes and reads).
We use read/write locks atm for handling the threading but I am not convinced that this is the best way.  

Would be great if you could have a look to that and give me your feedback and / or suggestion? We can have also a voice chat so I can explain better some details if needed.

**Comment by ManfredKarrer** [comment]
Btw: I did quite a few refactorings/improvements in the DAO code, so please update from upstream master if you have forked. Though the BsqBlockChain has not change much and is still an open problem...

**Comment by ManfredKarrer** [comment]
After further thoughts I think I will keep the ReadWriteReentrantLocks and use a WriteModel and ReadModel to encapsulate the access to the shared data in BsqBlockChain, making all methods package private so only the WriteModel and ReadModel can access. 
There is no concurrent write as far I see and with the ReadWriteReentrantLocks the reads are well controlled. The WriteModel and ReadModels should give better overview which clients are accessing the data in which fashion.

Pushed my WIP code here:
https://github.com/bisq-network/exchange/tree/refactor-dao-data-model

@sqrrm Any thoughts on that?

**Comment by sqrrm** [comment]
I think this makes sense and I agree that this gives a much better overview of how the BsqBlockChain is accessed. Looking at your WIP changes it's already easier to understand the scope of each class. It might also encourage some caution in future when WriteModel is used but shouldn't be needed.

**Comment by ManfredKarrer** [comment]
Changed the read/write model idea to just use interfaces to limit to read or write access.
I am still not convinced that the ReadWriteReentranceLock is really needed and if simple synchronized is not sufficient, but I leave that for now.
Close  the issue as design is now more satisfying.

**Comment by tau3** [comment]
@ManfredKarrer sorry for late answer. Seems that the class under discussion is now at https://github.com/bisq-network/bisq-core/blob/master/src/main/java/bisq/core/dao/blockchain/BsqBlockChain.java, is it correct? I still see some concurrency problems here, like `addBlock` method - i think it may raise `ConcurrentModificationException`, because `listeners` collection is not thread-safe (i.e. someone can remove a listener during that call). I'd suggest splitting `BsqBlockChain` into smaller classes (at least moving `listeners` collection into separate class that manages its concurrent consistency by itself)

**Comment by ManfredKarrer** [comment]
@tau3 Yes there have been some refactorings....

Would be great if you could help to get that class more solid. There is only one thread writing at one time.

**Comment by ManfredKarrer** [comment]
Close as sufficiently discussed and in a solid state now.
