### ISSUE TITLE
Layout of transaction list items is not vertically centered

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1441]
Layout of transaction list items is not vertically centered in row ("Sent to:, Received with:"). 

<img width="1200" alt="screen shot 2018-03-08 at 20 19 40" src="https://user-images.githubusercontent.com/1449498/37185390-1807c708-230e-11e8-8ad1-33119cb2a057.png">

**Comment by ripcurlx** [comment]
I missed that when I removed the padding for the hyperlinks. Thanks for the hint!
