### ISSUE TITLE
Make account age based limits better visible

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1444]
One problem with the different trade limits based on the account age of the user is that offer makers who are not aware of that and who have already reached the max. limit might make offers without min. amount and their max. limit (e.g. 0.25 btc) and thus limiting the group of potential takers as many of the users will be in the first or second month of the account age with lower limits.
We should find some way to communicate that context in the create offer screen so that makers can make a conscious decision if they really want to exclude a large group of potential takers if they don't allow lower amounts as well by setting the min. amount. 
Maybe the min. amount should by default be set to the lower limit of a first month account (0.0625 BTC)?

**Comment by bitxat** [comment]
Please see my related issue for account age limits here: https://github.com/bisq-network/bisq-desktop/issues/1476

**Comment by ManfredKarrer** [comment]
Still relevant
