### ISSUE TITLE
Users can use Bitsquare in their native language

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#145]
## Motivation

Non-English speaking users should be able to use Bitsquare in their native language. This work consists of two major pieces of work: (1) externalizing existing english strings into property files, and (2) developing non-english translations. See other issues labeled `re: i18n` for specific language translation suggestions.
## Implementation notes

Use the % prefix in FXML and BSResource in code to get all display strings from the locale property files.
In Create offer screen the internationalization is already implemented.

**Comment by cbeams** [comment]
See also the [wiki page on internationalization](https://github.com/bitsquare/bitsquare/wiki/Internationalization) (which may be a bit redundant now that these issues are here, but still perhaps a good place to capture names of volunteers, etc).

**Comment by notmandatory** [comment]
We should consider using [Transifex](https://www.transifex.com/projects/p/bitcoin-wallet/) to help with translations, I found the android bitcoin wallet project is using it too.  Opensource projects are free.

**Comment by llildur** [comment]
Im from Mexico, i like contribute with spanish translation.

**Comment by ManfredKarrer** [comment]
Added input from the wiki page (removed the wiki page):

| Language | Volunteer | Email or GitHub ID | Issue |
| --- | --- | --- | --- |
| Australian | Lloyd | btcll | [#167](https://github.com/bitsquare/bitsquare/issues/167) |
| French | Jonas | nayow@hotmail.fr | [#151](https://github.com/bitsquare/bitsquare/issues/151) |
| Spanish | Aleix | aleix.ripol@gmail.com | [#146](https://github.com/bitsquare/bitsquare/issues/146) |
| Swedish | Richard | remyers | [#150](https://github.com/bitsquare/bitsquare/issues/150) |
| Italian | Steve | stevemyers | [#166](https://github.com/bitsquare/bitsquare/issues/166) |
| German | Marc | dropthekidz@hotmail.com | [#147](https://github.com/bitsquare/bitsquare/issues/147) |
| Bulgarian | Stan | @aramaic |  |
| Brazilian Portuguese | adelorenzo, Felipe | @adelorenzo, @AnonLoki01 |  |

**Comment by adelorenzo** [comment]
Hello, I can contribute with the Brazilian Portuguese translation

**Comment by ghost** [comment]
Hi Manfred,

I think I can handle the Bulgarian version.

regards,

Stan Stavrev

**Comment by FelipecoinBrazil** [comment]
Hi,

My name is Felipe and I would like to help on translations to Brazilian Portuguese.

**Comment by ghost** [comment]
Hey,

I'd love to contribute to the Turkish localization.

**Comment by jonathascarrijo** [comment]
I'd be glad to help with the brazilian portuguese translation as well.

BTW, it's a pity bitsquare payment methods aren't the ones brazilian people use to buy and sell bitcoin. I'd be thrilled to see bank transfer as a payment method option.

**Comment by ManfredKarrer** [comment]
@jonathascarrijo: Thanks!

Can you provide detailed information regarding brazilian payment methods?

We have here 2 docs for collecting information and there are general requirements for a payment method to be considered for Bitsquare:
https://docs.google.com/spreadsheets/d/1xiOqcBSInIF7ozWdN3DvM5O-nyZ-397G9MR8LOXs6iA/
https://docs.google.com/document/d/1iQHhtAOieu5i6_2rvkvtcLS70A991aZlxkJgzv97XuU/

Feel free to add comments/suggestions. Bitsquare aims to support a wide range of methods, but they need to be chargeback safe and verifiable for an arbitrator. 
We don't have resources to investigate worldwise all payment methods, so we rely on the help from people who want to contribute.

**Comment by lattice0** [comment]
I'm from Brasil and I'd like to contribute with Brazilian Portuguese translation of the app and the website!

**Comment by Chuox** [comment]
Hello, Want to help whit Spanish translation, also, the exchangue rate for VEF (Venezuela local currency) is in certain way wrong. This is an app whit prices of localbitcoin and surbitcoin the main Venezuelan exchange. http://blasttrader.herokuapp.com/
Cheers!

**Comment by ManfredKarrer** [comment]
I use Bitcoin average for fiat rates.
https://api.bitcoinaverage.com/ticker/global/VEF/
seems they have wrong prices for VEF if those on http://blasttrader.herokuapp.com/ are correct. I have a bit of contact to them and will tell them.

Thanks for offering help with translations! I will not have soon time to add multi language support to the app but I will keep you informed once we start working on that!

**Comment by Chuox** [comment]
I see... I check and the problem is how the Index formula is calculated on bitcoinaverage.com, they use  oficial fiat exchange rates, which in mst countries that woulnd be a problem, but our goverment lies about the USD/VEF exchangue rate (among others thing). The are using a 10VEF/USD rate, which I whis it was the true vale of the coin.
Anyway, I really like this project, I'm learning java and running "a node" to see how much can I help.

**Comment by ManfredKarrer** [comment]
Yes I just got an anwer form bitcoin avaerage and they use the official dollar/VEF rate which is the reason for the difference...

**Comment by shaun-ba** [comment]
Just chiming in to say that we don't have a great deal of options here, we have to use global exchange rates to provide our data and can't get wrapped up in local political or other debates.

Of course if anyone wants to use their own rate you can do so against our global USD data :)

**Comment by ManfredKarrer** [comment]
@bitnumus : Thanks for your input! 
I might add later in the setting an option to customize the rate for such countries where the official rate is just a wanna be :-)

**Comment by shaun-ba** [comment]
@ManfredKarrer To be honest we could also do that for the global price, i'll add it to our list. 

/indices/global/ticker/BTCVEF?exchangerate=<blah>

**Comment by shaun-ba** [comment]
@ManfredKarrer Ah, also i forgot to mention we have a new API incoming :). I have added you to our closed beta mailing list

**Comment by ManfredKarrer** [comment]
@bitnumus : Cool thanks!

**Comment by hpopolis** [comment]
Hi, I'd like to contribute as a Korean translator.

**Comment by franckuestein** [comment]
Hi!
@ManfredKarrer I'd like to help with catalan translation 😀

**Comment by WillemKvanderMerwe** [comment]
Hi, I can help translate to Afrikaans (South African). Love this project!

**Comment by pl48415** [comment]
Hi, I can translate to Croatian.

**Comment by ojedson** [comment]
I can help translate to Swahili,the most widely spoken language in Africa. Respect for this project

**Comment by KanoczTomas** [comment]
Hello, I can help with Slovak and Hungarian translation as well. Not sure thought where to start ;)

**Comment by ManfredKarrer** [comment]
We still dont have the code ready for supporting translations, but thanks for your offer! We let you know once we get ready for it.

**Comment by kompowiec** [comment]
Hello, i'm from Poland and i can help add polish translation.

**Comment by MarcSte** [comment]
Hey, thanks for the offer. There's still no code ready and it will take a while to develop. You'll be notified through our regular channels.

**Comment by jasomweb** [comment]
I can help with Slovak translation as well. Waiting for the code :-)

**Comment by haiqu** [comment]
I will be dealing with this task since it is long overdue. Please see:

https://forum.bitsquare.io/t/any-cunning-linguists-among-us/721/6

This is not the final version of the files but I'd like us to get a start on it anyhow.

**Comment by cj4c0b1** [comment]
I can help with Brazilian Portuguese translations if it not already done.
And if it is done and can revise to be the most correct as possible.

**Comment by githubaccq** [comment]
Russian

**Comment by ManfredKarrer** [comment]
We have now all display strings supported for translation. 
Please help us to get the missing translation strings filled up! 
Join out Transifex page or check at our forum if you have any questions.
https://www.transifex.com/bitsquare/bitsquare/
https://forum.bitsquare.io/t/any-cunning-linguists-among-us/

**Comment by JesusThisUsernameIsAlreadyTaken** [comment]
Hi there, I would like to make a Russian translation. I also have some experience in this field and find this project very useful for society.

**Comment by ManfredKarrer** [comment]
Please join our transifex team: https://www.transifex.com/bitsquare/bitsquare/dashboard/

**Comment by JesusThisUsernameIsAlreadyTaken** [comment]
I already tried to choose the Russian language from the list but it is
excepted already, so I can't even join the team as long as Russian is not
accepted officially for the project.

2017-04-04 2:45 GMT+02:00 Manfred Karrer <notifications@github.com>:

**Comment by ghost** [comment]
I requested Bulgarian to be added to the language list. I see some
languages from countries which were far behind the Bulgarian Bitcoin
community and Mining operations. During BTC Guild golden time - team
Bulgaria score 6th place globally and we are really proud of that for such
a small country. Hope the Bulgarian language was missed by mistake and this
is not made on purpose?

Thanks

Stan

**Comment by ManfredKarrer** [comment]
Added both Bulgarian and Russian.
Feel free to join the Transifex team and help translating.

**Comment by Fraccaman** [comment]
I can help with Italian translation if not already implemented.

**Comment by ManfredKarrer** [comment]
Thanks. Feel free to join at: https://www.transifex.com/bitsquare/bitsquare/languages/

**Comment by ripcurlx** [comment]
Shall we keep this issue open or add a new issue if we want to offer Bisq in other languages?

**Comment by cbeams** [comment]
Closing as (essentially) complete. Many translations have been added. New ones can be managed as individual issues. There's no particular need for an epic-style issue like this at this point.
