### ISSUE TITLE
Limit orders?

### ISSUE THREAD

**Issue by dreboli** [bisq-network/bisq#1452]
I'd like to hide my sell offer every time the market price goes below 7000 EUR, and only enable it once the price is above 7000EUR.
Is this currently possible, or a planned feature?

**Comment by ManfredKarrer** [comment]
With the latest version you can deactivate manually an offer under portfolio/open offer. Automatic changes are not implemented but would be a nice feature.

**Comment by abigail830** [comment]
@ManfredKarrer existng bisq is mainly supporting market order, while I think limit order and stop_loss is important as of trading platform. May I know the plan for this?

Is there any place I could check the Jira/Task list target to implement for coming version ? Or any milestone planning..etc

**Comment by ManfredKarrer** [comment]
No there is no concrete issue of proposal for that. In fact it would make sense to create a proposal for that to cover all the aspects before implementing it. There are conceptually differences to centralized exchanges we have to keep in mind.
