### ISSUE TITLE
Simplify token listing process

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1456]
## Problem

After splitting the bisq-network/exchange repository into bisq-common, bisq-p2p, bisq-core and bisq-desktop, the process of listing a token is now overly difficult, requiring changes to be made across three repositories (common, core and desktop).

## Solution

Move and refactor types as necessary such that changes necessary for listing a token need be made only within a single repository, either bisq-common or bisq-core.

**Comment by ManfredKarrer** [comment]
IMO the AltCoinAddressValidator should move to core, might be needed in future for API/web/mobile as well.

CurrencyUtil is in common but I don't see yet a reason why it cannot move to core. It will require dependent classes like Price and Altcoin as well to move. Might be more and maybe there is then a dependency to p2p which would break moving. Probably some interfaces are required at some point.

The printAllCurrencyStats in TradeStatisticsManager can be moved to a util class/tool.

**Comment by cbeams** [comment]
Agreed. I’m in the middle of doing all that now.

**Comment by cbeams** [comment]
@ManfredKarrer, could you review each of the PRs above, and merge them in the following order?

 1. bisq-common
 1. bisq-core
 1. bisq-desktop
 1. docs
