### ISSUE TITLE
Major Vulnerability 

### ISSUE THREAD

**Issue by 0xConsole** [bisq-network/bisq#1457]
I've discovered a major vulnerability in the bisq desktop application. Please contact me or leave me your email here. I will do a responsible disclosure.

**Comment by cbeams** [comment]
You can contact me at chris@beams.io, thanks.

**Comment by cbeams** [comment]
Closing as not credible. I had the following email exchange with the original poster and have not heard further from them.

![image](https://user-images.githubusercontent.com/301810/37503996-fc5e8388-28db-11e8-8b23-0d620a198240.png)
