### ISSUE TITLE
Create a bug bounty program with clear terms

### ISSUE THREAD

**Issue by HysMagus** [bisq-network/bisq#1462]
Subject: Creating A Specific Bug Bounty Program With Clear Terms to assist in a clear and easy process for the payment of bounties

Summary: Having a bug bounty program with clear guidelines, easy to report process, and set limits of rewards.

Reasoning: Bisq is an amazing exchange network, and building a clear responsible disclosure system with set budgets for the report of specific types of vulnerabilities will make situations such as #1457 less likely to occur as there is not only a clear budget which the disclosure will be limited under but the system can require that the bug be disclosed prior to rating to ensure that you aren't paying 10 BTC for a minor situation. 

Options:
For my own businesses, I use sites such as [Hacker One](https://hackerone.com) and inbuilt custom forms using sites such as Form.IO ([they are on github](https://github.com/formio/formio)).

It is my understanding that since Bisq is a P2P exchange network, there might be a preference to have this system a little more decentralized. So a possible solution is to create a pseudo ticket system, similar to the current arbitrator UI that exists currently) on the platform with clear reward ranges. In this scenario the people notified would be the people who are notified in any situation. 

What differentiates this from just having an email address, is existing price ranges depending on the severity of the bug and clear methods with specified locations to submit this information. 
 
What do you guys think? 

Note: This is my first time making a issue on Bisq and I would just like to say that everyone in this community is Awesome!

**Comment by cbeams** [comment]
Issue moved to [bisq-network/proposals #10](https://github.com/bisq-network/proposals/issues/10) via [**ZenHub**](https://www.zenhub.com/)
