### ISSUE TITLE
Add a new field called "extra requeriments" in SEPA and Bank Transfers

### ISSUE THREAD

**Issue by sfkls** [bisq-network/bisq#1466]
Some bank accounts require adding some type of code such as comments or observations so that the money goes to a particular user. There are shared accounts under a single IBAN and a user identifier must be placed in the "Concept" field of the transfer.

Example:

Observations: please add this code as "concept" of the transfer: 234X9

In the "Cash deposits" option there is a field called "extra requeriments". It is simply add one similar to SEPA and bank transfers.

**Comment by ManfredKarrer** [comment]
I have never seen or heard about that at SEPA banks. can you post a screenshot and name the bank? We can add it but I fear it might confuse users.

**Comment by sfkls** [comment]
Than you for your response, Manfred. This is used in accounts that belong to cooperatives, where members can have their money when the transfer is made by putting their code as a reference. **In fact, it would be enough to add the "reference" field (not mandatory) as it is now available to any online bank where you want to make a transfer**. This is essential for those of us who want to use Bisq and we use shared bank accounts of this type.

**Comment by ManfredKarrer** [comment]
So in your Bisq SEPA account you need to add an extra requirement that the buyer will add the term Concept plus some ID to the reference text, right? I think some banks have rather low limits if allowed characters there, so adding it with the trade ID might cause issues. But the standard ccan be looked up somewhere what the max. length of the field is. I just saw in some of my bank accounts that often the text gets shortened or truncated to be basically unreadible... Banks are so crappy its unbelievable...

**Comment by sfkls** [comment]
Banks are insatiable creatures. But it is normal that they allow to put something short in the "reference" field. For example, when you pay for an online purchase by bank transfer you always have to put the reference of the purchase. In my case, to receive money, it is a code similar to "deposit XXXXX"

I think that for us to use Bisq, it would be enough to include two fields (reference & observations) in the bank account data.
Account owner full name:___________________________________
IBAN:____________________________________
BIC:__________________________
Reference: ___________________________________
Observations:_______________________________

"Observations" serves to remember that it is important to put the reference when making the bank transfer. To be able to write, for example:

_Please, it is very important that you include the indicated reference when making the transfer. Thank you._

**Comment by flix1** [comment]
I've see this, but it's not for banks that are directly connected via SEPA. 

This is used by companies that are effectively selling sub-accounts because they don't have the necessary license to offer all their customers an individual IBAN/account number.

It is also used by Caribbean banks that don't have real USD or EUR banking connectivity and are holding client funds pooled in their account at corresponding banks in US, Europe.

...because they need to internally attribute funds which are pooled, they normally use some additional field to identify them.

Some Forex brokers and Bitcoin exchanges also do this if they only have one account for all their clients to wire to.

I do not recommend using this type of account to trade with Bisq. Since control of the funds is indirect they are normally slower and since they depend on corresponding banks they can very easily run into trouble with "high risk" transfers such as Bitcoin related payments.

**Comment by flix1** [comment]
Many banks will close accounts that engage in Bitcoin-related activity, so it is highly recommended to avoid any additional info that will be flagged by compliance. The words "Bisq", "Bitcoin", "crypto", "cryptocurrency" should be avoided.

Other banks will flag for inspection any commercial activity in a non-business account and it could lead to account closing. So words like "trading" should also be avoided.

**Comment by sfkls** [comment]
The IBAN that I use is a shared IBAN. The IBAN belongs to a totally legal bank (ethical banking, specifically). The cooperative to which I belong simply manages that account that it is shared by several hundred members. This system is used by many other cooperatives with members, in many cases, very interested in cryptocurrencies. That is why I suggest the inclusion of these additional fields.

**Comment by ManfredKarrer** [comment]
We just need to find a way for the wording that does not confuse other users.
"Observations" is very confusing term to me. 

I would recommend that we add a field for extra requirements and there the user has to explain well what and how to add that extra data. I fear that still buyers will miss it and it will then probably cause problems as the bank does not know to whom belongs the funds.

Wouldn't it be easier to just set up a easy online SEPA bank like https://mistertango.com ?

It is the first time that such a feature is requested and I want to avoid that the UI gets overloaded.

**Comment by sfkls** [comment]
A field for extra requirements is fine. That is really enough. Thank you.

MisterTango seems interesting and, of course, there are many options in Bisq which makes me happy. The issue is that simply with this additional field we can participate in Bisq who, for various reasons, we avoid working with banks and we want to promote the financial freedom that the cryptocurrencies have brought to us. Some of us live in countries that begin to have serious controls over transactions related to cryptocurrencies and we use different methods not to be under that control. Some of us are activists related to different fields of freedom which I think is also the essence of a decentralized market running on the Tor network such as Bisq. That additional field in SEPA transfers is really useful for some of us. Thank you again for considering this suggestion.
