### ISSUE TITLE
PromptPay for Thailand

### ISSUE THREAD

**Issue by CryptoRevolutio0** [bisq-network/bisq#1467]
I saw there any possibility to ad PromptPay payment to Bisq? It's the fastest way to transfer money in Thailand. 
I don't have the skill set needed for this.

**Comment by ripcurlx** [comment]
Hi @CryptoRevolutio0! Although you might not have the skills for implementing the payment method integration yourself the first important step would be the investigation on this payment method and adding this information to this issue.

Important stuff to find out upfront:
- How big is the chargeback risk? (How easy can someone revert a payment?)
- How long does it take until the payment is settled?
- What information/fields are required to make a payment?
- How can an arbitrator confirm in case of a dispute that a payment was made? (Is there a web interface/website for PromptPay?)

You can a look at payment methods that are discussed right now for getting an idea how the discussion could look like (e.g. WeChat: https://github.com/bisq-network/bisq-desktop/issues/1354)

As soon as all these informations are clear and it looks like that PromptPay is a good fit with Bisq, maybe someone will take care of the implementation part.

**Comment by alfsbs** [comment]
Issue moved to [bisq-network/payment-methods #6](https://github.com/bisq-network/payment-methods/issues/6) via [**ZenHub**](https://www.zenhub.com/)
