### ISSUE TITLE
Can't close contract JSON format

### ISSUE THREAD

**Issue by Bedotech** [bisq-network/bisq#1472]
Hi all,

On `Locked funds` tabs select the column `Details` if i open the details popup and click on `View contract in JSON format` i cannot close the windows with the JSON formatting.

I work on: `Linux 4.14.27-1-MANJARO x86_64 GNU/Linux`

**Comment by ripcurlx** [comment]
I guess you don't have a close window control like in my screenshot? Could you please post a screenshot how it looks like in your case - thanks!
<img width="1312" alt="bildschirmfoto 2018-03-22 um 15 58 43" src="https://user-images.githubusercontent.com/170962/37778382-1efd1090-2dea-11e8-8467-70b31b872734.png">

**Comment by ManfredKarrer** [comment]
Seems a Linux desktop manager issue to not show the window frame.

@ripcurlx A close handler with esc would be nice here. We use that at all other popups.

**Comment by ripcurlx** [comment]
Still relevant.

**Comment by ripcurlx** [comment]
Still relevant.
