### ISSUE TITLE
Improve Offer Book

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1484]
After a recent discussion with @cbeams it became clear to me that we still have something to improve in the new offer book screen. It's still not 100% clear that you're buying from real people and now with the changed title the chart on top is lacking a legend.

**Current state on master**
![Current state on master](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/2e7e9a04-fd06-4762-938c-ec529eb14b02)

**Suggested first changes**
![Improved Offer Book](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/97c2d561-274d-43e6-975c-589fb25ba715)

I'll have a look if I can add a legend to the chart above in an easy way and will update this issue asap.

**Comment by ripcurlx** [comment]
A quick solution could be to add a legend. I'll have a look if I can change the position easily.
![improved offer book](https://user-images.githubusercontent.com/170962/38088039-bb49f4a2-335a-11e8-8a2e-fac718fead0a.png)

**Comment by ripcurlx** [comment]
I think putting it on the right is the better way to go. What do you (@cbeams) think?
![improved offer book](https://user-images.githubusercontent.com/170962/38088680-ecd2487e-335c-11e8-800c-9a2b8a7065c2.png)

**Comment by ManfredKarrer** [comment]
Hm, having it right breaks the symmetry somehow for me. I would prefer the version where its below.

**Comment by dorkmo** [comment]
"an offer to buy" "an offer to sell" might be easier for noobs.

**Comment by ManfredKarrer** [comment]
@dorkmo Thats exaclty the problematic part here. Its the opposit, its an offer of a user who wants to buy, thus an offer for you if u want to sell. That mirrored perspective is a bit tricky to get right in the UI to not confuse users. We always act from the users perspective. So the "Buy offers" as in the screen violates that and adds confusion again. 
I think easiest is to avoid that and not give them labels. The colors and placements with the table should guide a bit and at the end it is not relevant for the user. He simple wants to know where to click if he wants to buy or sell and that is achieved as it is.

**Comment by ripcurlx** [comment]
After letting it rest for some while I also think that adding a legend just makes it more confusing again for new users. I'll prepare a PR with the Trader icons only.
