### ISSUE TITLE
Required data fields for sending money in Argentina

### ISSUE THREAD

**Issue by fedegrc** [bisq-network/bisq#1489]
I tried to 'Create new account' with the payment methods 'National bank transfer', 'Transfer with same bank' and 'Transfers with specific banks' without success. The issue is that in Argentina we identify bank accounts with a CBU number instead of IBAN, BIC or SWIFT.

I'll provide the required data fields for sending money (English and Spanish version), but first I would like to talk about how the CBU number is created because it may be used to fill some fields automatically and detect if the CBU is invalid.

CBU is a 22 numerical digits that looks like 2850590940090418135201 (example used in [1]).

Field explanation:

If the CBU is aaabbbbcddddddddddddde, then:
aaa = Bank code. Using the table in [1] then you know the Bank name (Nombre del banco)
bbbb = Branch no. (Número de sucursal)
c = checksum of aaa and bbbb
ddddddddddddd = Account no. (Número de cuenta)
e = checksum of ddddddddddddd

The checksum is explain in [1]. I can translate it for you if you would like to implemented it.

Now, the required data fields for sending money using 'National bank transfer', 'Transfer with same bank' and 'Transfers with specific banks':

- **Account owner full name** (**Nombre del propietario de la cuenta**)
- **Account owner CUIL/CUIT** (**CUIL/CUIT del propietario de la cuenta**): 11 numerical digits usually written in this way: xx-xxxxxxxx-x (you can see more details in [2]).
- **CBU no.** (**Número de CBU**): 22 numerical digits
- **Bank name** (**Nombre del banco**) (*)
- **Branch no.** (**Número de sucursal**) (*)
- **Account no.** (**Número de cuenta**) (*)

(*) Could be automatically filled using the previous explanation. Manually filled is ok.

[1] https://es.wikipedia.org/wiki/Clave_Bancaria_Uniforme#Estructura_de_la_CBU
[2] https://es.wikipedia.org/wiki/Clave_Única_de_Identificación_Tributaria

@flix1 fyi

**Comment by ManfredKarrer** [comment]
@ripcurlx  Would be good if we get that into 0.7.0...

**Comment by flix1** [comment]
Well done @fedegrc !

This kind of detailed local info is what we will need for every country to localize Bisq. Please, please keep telling us of anything else that we will need to make Bisq work well in Argentina!

If we can get all the changes into the next version we might be able to do something to kick-start the ARS/BTC market shortly afterwards... like a Liquidity Week or similar.

**Comment by flix1** [comment]
@ripcurlx can you put the "payment methods" label on this issue?

**Comment by flix1** [comment]
**CBU**
![image](https://user-images.githubusercontent.com/4233784/38172620-eb46313c-35af-11e8-94c4-808a5af17bb3.png)
Very similar to IBAN for SEPA... modification needed should be minimal.

**CUIT**
![image](https://user-images.githubusercontent.com/4233784/38172644-585d6b1e-35b0-11e8-92e4-159b8327a551.png)

This will require a new field... but it's just like a National ID nº in many European countries. It should be simple enough.

**Comment by flix1** [comment]
These are all the fields that you need to receive a wire transfer in Argentina:

![image](https://user-images.githubusercontent.com/4233784/38172661-d7b47862-35b0-11e8-8438-cea521a1ac2c.png)


1. Bank Name
2. Account Number
3. Account type/currency
4. CBU
5. Beneficiary Name
6. Beneficiary CUIT/CUIL

**Comment by fedegrc** [comment]
Additional information:

- The CBU number is enough to send money so that field should be mandatory, but it's a good practice to provide the account owner full name, bank name, etc. because the sender can use them to verify that he/she is sending money to the correct bank account.
- In some bank websites, when we start a transfer process, first we have to select "Transfer with same bank" or "Transfer with another bank". If we select "Transfer with same bank" then it not necessary to provide the CBU, just the owner account number is enough to do the transfer. However, we normally use the CBU because there is no any difference between "Transfer with same bank" and "Transfer with another bank". National transfers are free in both cases.
- Bank accounts in Argentina usually have two currencies: ARS and USD. So, we're able to transfer ARS and USD too. From my point of view, Bisq should allow only ARS because USD transfers are used to buy expensive things, like a car or a house.
- It is not a good idea to received an international transfer because the beneficiary must do some paper works in a government entity to justify that money.
- Wire transfers up to ARS50000 (~USD2500) are free.
- I'm not really sure but I think that wire transfers are immediate or take one business day, it depends of the bank.

**Comment by ripcurlx** [comment]
@fedegrc Could you please have a look at the screenshots from my local branch below if it would have everything on it for doing a national bank transfer in AR? Atm I just implemented it without validation and field completion. I'll try to add validation and autocompletion as well.

**Add new payment method in Spanish**
<img width="1312" alt="payment-account-add" src="https://user-images.githubusercontent.com/170962/38257717-09c99056-3761-11e8-9892-bf4e721a359c.png">
**Add new payment method in Espenglish**
(we do this also with other payment methods with country specific fields)
<img width="1312" alt="payment-account-espenglish" src="https://user-images.githubusercontent.com/170962/38257718-09e77cb0-3761-11e8-9c04-26f460bf76bf.png">
**Display payment method in Spanish**
<img width="1312" alt="payment-account-display" src="https://user-images.githubusercontent.com/170962/38257715-09a3e5cc-3761-11e8-99d9-aa313b076049.png">
**Display payment method in payment dialog for buyer (English user interface)**
<img width="1312" alt="payment-info" src="https://user-images.githubusercontent.com/170962/38257714-097cb0ce-3761-11e8-9a6c-7914d6eb25cf.png">

**Comment by fedegrc** [comment]
@ripcurlx , looks great!
Just two details:
- I think that Espenglish make sense if the field is Clave Bancaria Uniforme (CBU), but from my point of view if the field is just CBU, then it can be written in English as CBU number or CBU no.
- "peso argentino (ARS)" should be "Peso argentino (ARS)"

**Comment by ManfredKarrer** [comment]
The translation of the currency is taken from java locales, so i think that cannot be changed easily.

**Comment by ripcurlx** [comment]
@fedegrc Thanks for the proof reading! As Manfred already mentioned on the Pesos it will be difficult to change it properly. I've changed the CBU number to have it localized as you've suggested. So we only have to figure out some kinks in the `Transfer with specific bank`/`Transfer with same bank` in general, but these changes will be in the next release. 👍

**Comment by fedegrc** [comment]
@ripcurlx , Investigating how to deposit cash I realize say that we only need the CBU. So, I think the changes you are working on can be applied to:
- Cash Deposit
- National bank transfer
- Transfer with same bank
- Transfers with specific banks

**Comment by ripcurlx** [comment]
@fedegrc National bank transfer, Transfer with same bank and Transfers with specific banks are already supported in my PR. I'll quickly have a look at the Cash Deposit if that's an easy fix as well.

**Comment by ripcurlx** [comment]
Ok - cash deposit support is now ready as well. Just have to wait for @ManfredKarrer to merge my PR in core and common, before I can merge the desktop PR with all the changes.

**Comment by ripcurlx** [comment]
@fedegrc Hi Federico! Do you think you could join us today in our [growth call](https://github.com/bisq-network/growth/issues/50) to talk about the situation in Argentina?
