### ISSUE TITLE
Open Offers Text Alternating Colour Between Black and Grey

### ISSUE THREAD

**Issue by tomatopeel** [bisq-network/bisq#1491]
![image](https://user-images.githubusercontent.com/13825174/38171846-f04c2b44-35c0-11e8-8844-4cfd4f295cdf.png)
![image](https://user-images.githubusercontent.com/13825174/38171851-00d2c19e-35c1-11e8-86a6-bacbfd72242b.png)
![image](https://user-images.githubusercontent.com/13825174/38171855-1daac88e-35c1-11e8-97b9-fda80edbf671.png)
The colours seemed to alternate randomly, at quite a slow pace (maybe every 10-60 seconds, not sure).

**Comment by ripcurlx** [comment]
Thank for pointing this out, I think I have an idea what could cause this random issues.
