### ISSUE TITLE
an error occurred when taking the offer: "too-long-mempool-chain' (64)

### ISSUE THREAD

**Issue by MrZeke** [bisq-network/bisq#1493]
Please see screen shot for info on this.  thanks

![screen shot 2018-04-03 at 3 30 09 pm](https://user-images.githubusercontent.com/10793013/38271257-f312ded8-3753-11e8-8f97-577c031f3728.jpg)

**Comment by ManfredKarrer** [comment]
Ah that can happen in rare cases when your tx has a very long chain of unconfirmed transactions as input. Not sure how well the wallet will handle that case. Just check out the funds/tx list to see if you have many unconfirmed txs. Wait until all are confirmed and then check the wallet balances with cmd+e to see the total balance and if it matches the available + reserved balance in the UI. If not do a resync of the spv file at settings/network.

**Comment by MrZeke** [comment]
Thanks ManfredKarrer I will try this.

**Comment by MrZeke** [comment]
Also one more question. @ManfredKarrer is there fees for canceling a trade ?  A trade i have put on the but side. (MAKER)

based off a 1 btc trade thanks.

**Comment by ManfredKarrer** [comment]
If you remove a offer your maker fee is lost as it was paid when creating the offer. We plan to make offers editable in the next release. You can also deactivate an offer if you want to take it temporarily out without losing the fee. Please use the Forum for questions and discussions so we keep Github more for the technical issues.

**Comment by MrZeke** [comment]
@ManfredKarrer is there any way I can PM you ? Telegram maybe ?

**Comment by ManfredKarrer** [comment]
On the Forum you can PM me...
