### ISSUE TITLE
Wrong behavior for trades with Specific and Same Bank Transfers

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1495]
During my fixes for Argentina I recognized Problems as offers can be taken until the final step between different account types (`Transfer with specific banks` and `Transfer with same bank`)

Steps to reproduce:
- Alice creates account with Transfer with specific banks and accepts Bank "Bank Alice" and "Bank Bob"
- Alice creates offer to buy BTC
- Bob creates account with Transfer with same Bank ("Bank Bob")

Expected Behavior:
- Bob is not allowed to take offer as the transfer would be from "Bank Bob" to "Bank Alice"

Actual Behavior:
- Bob is able to take the offer, but it fails in the final confirmation showing Alice following error:
![bildschirmfoto 2018-04-04 um 11 23 27](https://user-images.githubusercontent.com/170962/38299829-858b62a6-37fb-11e8-852b-43f843974134.png)
- The screen on Bobs size freezes until a timeout occurs.

The same happens if Alice is having an `Transfer with specific banks` account with Bank Bob. In that case actually it should be possible for Bob to take the offer as the transfer would be from Bank Bob to Bank Bob, but it fails with the same error.

**Comment by ripcurlx** [comment]
@ManfredKarrer How should we handle this issue? Don't allow trades between different payment methods or allow it if the conditions on both sides (same bank) are fulfilled?

**Comment by ManfredKarrer** [comment]
Seems that the checks are not correct:
The code handling that is at:
PaymentAccounts/PaymentAccountUtil/ReceiptPredicates/ReceiptValidator
It is used in he offerbook to deactivate offers which u cannot take.
The checks in the trade protocol should us the same logic, not sure how it is atm, seems it uses dif. checks and probl. also wrong (comparing payment methods only).

**Comment by mrosseel** [comment]
If there is checking logic in GUI and Core, this might be a good opportunity to refactor it into Core.

**Comment by ripcurlx** [comment]
I got following test https://github.com/bisq-network/bisq-desktop/blob/86ad6ef41a8c72ffc36e94ba6feff888081e236c/src/test/java/bisq/desktop/main/offer/offerbook/OfferBookViewModelTest.java#L96 running again and now two cases fail atm:
https://github.com/bisq-network/bisq-desktop/blob/86ad6ef41a8c72ffc36e94ba6feff888081e236c/src/test/java/bisq/desktop/main/offer/offerbook/OfferBookViewModelTest.java#L179-L182
and
https://github.com/bisq-network/bisq-desktop/blob/86ad6ef41a8c72ffc36e94ba6feff888081e236c/src/test/java/bisq/desktop/main/offer/offerbook/OfferBookViewModelTest.java#L199-L203
I'll have a look why this behavior changed.
@mrosseel I think the relevant methods are in the core package already.

**Comment by ripcurlx** [comment]
Closing as complete.
