### ISSUE TITLE
Unable to build and compile

### ISSUE THREAD

**Issue by jared201** [bisq-network/bisq#1498]
After syncing and building the bisq-core successfully, i tried to build the desktop again and I'm getting this error now:

:compileJava FAILED
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:112: error: illegal start of expression
    public static List<CryptoCurrency> createAllSortedCryptoCurrenciesList() {
    ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:112: error: illegal start of expression
    public static List<CryptoCurrency> createAllSortedCryptoCurrenciesList() {
           ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:112: error: ';' expected
    public static List<CryptoCurrency> createAllSortedCryptoCurrenciesList() {
                      ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:112: error: illegal start of expression
    public static List<CryptoCurrency> createAllSortedCryptoCurrenciesList() {
                                       ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:112: error: -> expected
    public static List<CryptoCurrency> createAllSortedCryptoCurrenciesList() {
                                                                            ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:112: error: not a statement
    public static List<CryptoCurrency> createAllSortedCryptoCurrenciesList() {
                                                                          ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:226: error: ';' expected
    }
     ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:228: error: illegal start of expression
    public static List<CryptoCurrency> getMainCryptoCurrencies() {
    ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:228: error: ';' expected
    public static List<CryptoCurrency> getMainCryptoCurrencies() {
          ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:228: error: ';' expected
    public static List<CryptoCurrency> getMainCryptoCurrencies() {
                                                              ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:255: error: illegal start of expression
    public static List<TradeCurrency> getAllOKPayCurrencies() {
    ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:255: error: illegal start of expression
    public static List<TradeCurrency> getAllOKPayCurrencies() {
           ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:255: error: ';' expected
    public static List<TradeCurrency> getAllOKPayCurrencies() {
                      ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:255: error: illegal start of expression
    public static List<TradeCurrency> getAllOKPayCurrencies() {
                                      ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:255: error: -> expected
    public static List<TradeCurrency> getAllOKPayCurrencies() {
                                                             ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:255: error: not a statement
    public static List<TradeCurrency> getAllOKPayCurrencies() {
                                                           ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:281: error: ';' expected
    }
     ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:284: error: illegal start of expression
    public static List<TradeCurrency> getAllUpholdCurrencies() {
    ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:284: error: ';' expected
    public static List<TradeCurrency> getAllUpholdCurrencies() {
          ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:284: error: ';' expected
    public static List<TradeCurrency> getAllUpholdCurrencies() {
                                                            ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:316: error: illegal start of expression
    public static List<TradeCurrency> getAllRevolutCurrencies() {
    ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:316: error: illegal start of expression
    public static List<TradeCurrency> getAllRevolutCurrencies() {
           ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:316: error: ';' expected
    public static List<TradeCurrency> getAllRevolutCurrencies() {
                      ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:316: error: illegal start of expression
    public static List<TradeCurrency> getAllRevolutCurrencies() {
                                      ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:316: error: -> expected
    public static List<TradeCurrency> getAllRevolutCurrencies() {
                                                               ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:316: error: not a statement
    public static List<TradeCurrency> getAllRevolutCurrencies() {
                                                             ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:346: error: ';' expected
    }
     ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:348: error: illegal start of expression
    public static boolean isFiatCurrency(String currencyCode) {
    ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:348: error: ';' expected
    public static boolean isFiatCurrency(String currencyCode) {
          ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:348: error: ';' expected
    public static boolean isFiatCurrency(String currencyCode) {
                                        ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:348: error: ';' expected
    public static boolean isFiatCurrency(String currencyCode) {
                                                            ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:359: error: illegal start of expression
    public static Optional<FiatCurrency> getFiatCurrency(String currencyCode) {
    ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:359: error: illegal start of expression
    public static Optional<FiatCurrency> getFiatCurrency(String currencyCode) {
           ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:359: error: ';' expected
    public static Optional<FiatCurrency> getFiatCurrency(String currencyCode) {
                          ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:359: error: illegal start of expression
    public static Optional<FiatCurrency> getFiatCurrency(String currencyCode) {
                                         ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:359: error: -> expected
    public static Optional<FiatCurrency> getFiatCurrency(String currencyCode) {
                                                                             ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:363: error: illegal start of expression
    @SuppressWarnings("WeakerAccess")
    ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:363: error: ';' expected
    @SuppressWarnings("WeakerAccess")
                                     ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:364: error: illegal start of expression
    public static boolean isCryptoCurrency(String currencyCode) {
           ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:364: error: ';' expected
    public static boolean isCryptoCurrency(String currencyCode) {
                 ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:364: error: ')' expected
    public static boolean isCryptoCurrency(String currencyCode) {
                                                 ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:364: error: illegal start of expression
    public static boolean isCryptoCurrency(String currencyCode) {
                                                              ^
/Users/jared/bisq-core/src/main/java/bisq/core/locale/CurrencyUtil.java:364: error: ';' expected
    public static boolean isCryptoCurrency(String currencyCode) {
                                                               ^
/Users/jared/bisq-core/src/main/java/bisq/core/payment/validation/AltCoinAddressValidator.java:75: error: illegal start of expression
=======
^
/Users/jared/bisq-core/src/main/java/bisq/core/payment/validation/AltCoinAddressValidator.java:75: error: illegal start of expression
=======
  ^
/Users/jared/bisq-core/src/main/java/bisq/core/payment/validation/AltCoinAddressValidator.java:75: error: illegal start of expression
=======
    ^
/Users/jared/bisq-core/src/main/java/bisq/core/payment/validation/AltCoinAddressValidator.java:75: error: illegal start of expression
=======
      ^
/Users/jared/bisq-core/src/main/java/bisq/core/payment/validation/AltCoinAddressValidator.java:78: error: illegal start of expression
                default:
                ^
/Users/jared/bisq-core/src/main/java/bisq/core/payment/validation/AltCoinAddressValidator.java:78: error: illegal start of expression
                default:
                       ^
/Users/jared/bisq-core/src/main/java/bisq/core/payment/validation/AltCoinAddressValidator.java:79: error: ';' expected
                    log.debug("Validation for AltCoinAddress not implemented yet. currencyCode: " + currencyCode);
                       ^
/Users/jared/bisq-core/src/main/java/bisq/core/payment/validation/AltCoinAddressValidator.java:84: error: class, interface, or enum expected
    }
    ^
/Users/jared/bisq-core/src/main/java/bisq/core/payment/validation/AltCoinAddressValidator.java:89: error: class, interface, or enum expected
        return !(asset instanceof Coin)
        ^
/Users/jared/bisq-core/src/main/java/bisq/core/payment/validation/AltCoinAddressValidator.java:92: error: class, interface, or enum expected
    }
    ^
53 errors
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 3s
1 actionable task: 1 executed

**Comment by jared201** [comment]
sorry disregard that log, this is the new one:

:compileJava FAILED
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/app/BisqApp.java:50: error: cannot find symbol
import bisq.core.dao.DaoSetup;
                    ^
  symbol:   class DaoSetup
  location: package bisq.core.dao
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/app/BisqApp.java:52: error: package bisq.core.dao.vote.myvote does not exist
import bisq.core.dao.vote.myvote.MyVoteService;
                                ^
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/MainViewModel.java:48: error: cannot find symbol
import bisq.core.dao.DaoSetup;
                    ^
  symbol:   class DaoSetup
  location: package bisq.core.dao
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/MainViewModel.java:169: error: cannot find symbol
    private final DaoSetup daoSetup;
                  ^
  symbol:   class DaoSetup
  location: class MainViewModel
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/MainViewModel.java:248: error: cannot find symbol
                         DaoSetup daoSetup, EncryptionService encryptionService,
                         ^
  symbol:   class DaoSetup
  location: class MainViewModel
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/components/SeparatedPhaseBars.java:20: error: cannot find symbol
import bisq.core.dao.vote.PeriodService;
                         ^
  symbol:   class PeriodService
  location: package bisq.core.dao.vote
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/components/SeparatedPhaseBars.java:142: error: package PeriodService does not exist
        private final PeriodService.Phase phase;
                                          ^
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/components/SeparatedPhaseBars.java:153: error: package PeriodService does not exist
        public SeparatedPhaseBarsItem(PeriodService.Phase phase, boolean showBlocks) {
                                                   ^
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/active/ActiveProposalsView.java:35: error: cannot find symbol
import bisq.core.dao.vote.PeriodService;
                         ^
  symbol:   class PeriodService
  location: package bisq.core.dao.vote
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/active/ActiveProposalsView.java:39: error: package bisq.core.dao.vote.result does not exist
import bisq.core.dao.vote.result.BooleanVoteResult;
                                ^
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/BaseProposalView.java:32: error: cannot find symbol
import bisq.core.dao.vote.PeriodService;
                         ^
  symbol:   class PeriodService
  location: package bisq.core.dao.vote
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/active/ActiveProposalsView.java:98: error: cannot find symbol
                                PeriodService periodService,
                                ^
  symbol:   class PeriodService
  location: class ActiveProposalsView
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/ProposalListItem.java:30: error: cannot find symbol
import bisq.core.dao.vote.PeriodService;
                         ^
  symbol:   class PeriodService
  location: package bisq.core.dao.vote
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/ProposalListItem.java:33: error: package bisq.core.dao.vote.result does not exist
import bisq.core.dao.vote.result.BooleanVoteResult;
                                ^
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/ProposalListItem.java:34: error: package bisq.core.dao.vote.result does not exist
import bisq.core.dao.vote.result.VoteResult;
                                ^
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/active/ActiveProposalsView.java:254: error: package PeriodService does not exist
    protected void onPhaseChanged(PeriodService.Phase phase) {
                                               ^
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/BaseProposalView.java:89: error: package PeriodService does not exist
    protected ChangeListener<PeriodService.Phase> phaseChangeListener;
                                          ^
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/BaseProposalView.java:90: error: cannot find symbol
    protected final PeriodService periodService;
                    ^
  symbol:   class PeriodService
  location: class BaseProposalView
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/BaseProposalView.java:91: error: package PeriodService does not exist
    protected PeriodService.Phase currentPhase;
                           ^
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/BaseProposalView.java:104: error: cannot find symbol
                               PeriodService periodService,
                               ^
  symbol:   class PeriodService
  location: class BaseProposalView
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/BaseProposalView.java:239: error: package PeriodService does not exist
    protected void onPhaseChanged(PeriodService.Phase phase) {
                                               ^
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/ProposalListItem.java:61: error: cannot find symbol
    private final PeriodService periodService;
                  ^
  symbol:   class PeriodService
  location: class ProposalListItem
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/ProposalListItem.java:66: error: cannot find symbol
    private final ChangeListener<VoteResult> voteResultChangeListener;
                                 ^
  symbol:   class VoteResult
  location: class ProposalListItem
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/ProposalListItem.java:75: error: package PeriodService does not exist
    private ChangeListener<PeriodService.Phase> phaseChangeListener;
                                        ^
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/ProposalListItem.java:84: error: cannot find symbol
                     PeriodService periodService,
                     ^
  symbol:   class PeriodService
  location: class ProposalListItem
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/ProposalListItem.java:125: error: package PeriodService does not exist
    public void applyState(PeriodService.Phase newValue, VoteResult voteResult) {
                                        ^
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/ProposalListItem.java:125: error: cannot find symbol
    public void applyState(PeriodService.Phase newValue, VoteResult voteResult) {
                                                         ^
  symbol:   class VoteResult
  location: class ProposalListItem
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/closed/ClosedProposalsView.java:26: error: cannot find symbol
import bisq.core.dao.vote.PeriodService;
                         ^
  symbol:   class PeriodService
  location: package bisq.core.dao.vote
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/closed/ClosedProposalsView.java:40: error: cannot find symbol
                                PeriodService periodService,
                                ^
  symbol:   class PeriodService
  location: class ClosedProposalsView
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/dashboard/ProposalDashboardView.java:26: error: cannot find symbol
import bisq.core.dao.vote.PeriodService;
                         ^
  symbol:   class PeriodService
  location: package bisq.core.dao.vote
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/dashboard/ProposalDashboardView.java:51: error: cannot find symbol
    private final PeriodService periodService;
                  ^
  symbol:   class PeriodService
  location: class ProposalDashboardView
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/dashboard/ProposalDashboardView.java:52: error: package PeriodService does not exist
    private PeriodService.Phase currentPhase;
                         ^
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/dashboard/ProposalDashboardView.java:64: error: cannot find symbol
    private ProposalDashboardView(PeriodService periodService,
                                  ^
  symbol:   class PeriodService
  location: class ProposalDashboardView
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/myvotes/MyVotesView.java:33: error: cannot find symbol
import bisq.core.dao.vote.PeriodService;
                         ^
  symbol:   class PeriodService
  location: package bisq.core.dao.vote
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/myvotes/MyVotesView.java:34: error: package bisq.core.dao.vote.myvote does not exist
import bisq.core.dao.vote.myvote.MyVoteService;
                                ^
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/myvotes/MyVotesView.java:37: error: package bisq.core.dao.vote.result does not exist
import bisq.core.dao.vote.result.BooleanVoteResult;
                                ^
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/myvotes/MyVotesView.java:38: error: package bisq.core.dao.vote.result does not exist
import bisq.core.dao.vote.result.VoteResult;
                                ^
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/myvotes/MyVotesView.java:74: error: cannot find symbol
    private final MyVoteService myVoteService;
                  ^
  symbol:   class MyVoteService
  location: class MyVotesView
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/myvotes/VoteListItem.java:30: error: package bisq.core.dao.vote.myvote does not exist
import bisq.core.dao.vote.myvote.MyVote;
                                ^
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/myvotes/MyVotesView.java:91: error: cannot find symbol
                        PeriodService periodService,
                        ^
  symbol:   class PeriodService
  location: class MyVotesView
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/myvotes/MyVotesView.java:92: error: cannot find symbol
                        MyVoteService myVoteService,
                        ^
  symbol:   class MyVoteService
  location: class MyVotesView
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/myvotes/VoteListItem.java:55: error: cannot find symbol
    @Getter
    ^
  symbol:   class MyVote
  location: class VoteListItem
/Users/jared/bisq-asx-desktop/src/main/java/bisq/desktop/main/dao/proposal/myvotes/VoteListItem.java:76: error: cannot find symbol
    VoteListItem(MyVote myVote,
                 ^
  symbol:   class MyVote
  location: class VoteListItem
43 errors
FAILURE: Build failed with an exception.

**Comment by cbeams** [comment]
@jared201, please use ``` fenced code blocks in the future. It makes reports like this much more readable.

Also, please share a more complete description of exactly what you did when trying to build this. For example, the following should work perfectly:

```
git clone https://github.com/bisq-network/bisq-desktop
cd bisq-desktop
./gradlew build
./build/app/bin/bisq-desktop --appName="Bisq Dev" # Bisq should launch successfully
```

I have just run the commands above against `master` @ acd00dded, and all worked as expected. What are you doing differently?

**Comment by jared201** [comment]
@cbeams that's exactly what I did, actually it was successfully compiling 24 hours ago before I sync with the latest codes. Then I deleted /bisq-desktop entirely and git clone'd from scratch still the same thing, I'm running on MacOS High Sierra using JDK 1.8.161

**Comment by ripcurlx** [comment]
It seems to be the core and desktop repository are broken atm.

**Comment by ripcurlx** [comment]
I looks like Protocol Buffers config is not in sync with some classes (e.g. TxInput, ProposalPayload,...) Maybe @ManfredKarrer knows what needs to be changed or just needs to push local changes.

**Comment by jared201** [comment]
tried one more time after @cbeams reversion of the travis file, it's working now, thanks!
