### ISSUE TITLE
Failed trade missing funds

### ISSUE THREAD

**Issue by jaiden5** [bisq-network/bisq#1503]
Hello. I am big fan of Bisq and have been using it a lot to try and test it and hopefully I can report some bugs here that help everyone.

# System Specification:
Mac OSX 10.13.3
Bisq 0.6.7

# Brief Description of Bug:
I was an XMR Seller tagged here as "BTC_Buyer"  

Bisq application notified the BTC_Buyer of a new trade in **Portfolio>Open Trades** tab but failed to initiate stage 1 **Waiting for blockchain confirmation**. Instead the user was presented with grayed out progress bars down the left hand side see [Screen Shot_2018-04-06_at_16.20.51] below:  

<img width="382" alt="screen_shot_2018-04-06_at_16 20 51" src="https://user-images.githubusercontent.com/38193322/38473702-af82ae60-3b94-11e8-855e-7dd5ce069fb2.png">   
Note the BTC_Buyer also had one other open trade with the same user on XMR/BTC, in both cases the user was the BTC buyer on XMR trading pair.  

BTC_Buyer opted to open up a support ticket using alt+o command so that the trade could be processed manually. User sent XMR to BTC Seller but the transaction was delayed due to XMR fork. Transaction eventually came through and arbitrator closed the trade with the following report:  

```
Ticket closed on Apr 8, 2018 1:10:08 PM


Summary:
BTC buyer/Maker delivered tamper proof evidence: No
BTC buyer/Maker did ID verification: No
BTC buyer/Maker did screencast or video: No
Payout amount for BTC buyer: 0.3420 BTC
Payout amount for BTC seller: 0.0030 BTC

Summary notes:
Late payment, probably due to Monero fork.
```  

However BTC_Buyer was met with the following error message [Screen_Shot_2018-04-08_at_15.47.02]:  
<img width="492" alt="screen_shot_2018-04-08_at_15 47 02" src="https://user-images.githubusercontent.com/38193322/38473738-0de54d96-3b95-11e8-89cd-63c414d1a65e.png">  

The 0.3420 BTC was not sent to the BTC_Buyer. 

# Next steps
I have a copy of the logs but I would prefer to give these to developers privately. Is this an option? I am not sure where my BTC is at this point, I have looked through all the transactions in my history and searched through the blockchain and would like to know if it is recoverable. Maybe it got mixed up with the other trade I was in.

If I can improve the way I report issues like these please let me know. Thank you.

**Comment by ManfredKarrer** [comment]
Thanks for the detailed bug report!!!
You can send me the log file (manfred at bitsquare dot io) together with trade ID and txIds.
 It looks that the dispute payout tx was not successful and need to be redone manually. No worry no fund ever lost.
I would recommend after we have resolved that to start over with a new app and new data directory, seems there are some database files screwed up. You can export your payment accounts and re-import them. See https://bisq.community/t/switching-to-a-new-data-directory/1697

**Comment by ManfredKarrer** [comment]
@keo-bisq @cbeams Please be aware that that dispute probably was not successfully paid out and will likely require a manual payout.

**Comment by ManfredKarrer** [comment]
@keo-bisq  Update after getting more info:
The dispute was Keo's case. The deposit tx was never created so the payout failed and cannot be re-done. Unfortunately the buyer sent the XMR to the peer. We will try to contact the peer to refund the XMR.

**Comment by keo-bisq** [comment]
I have reopened the case and messaged the traders. However there is no reply.
I wonder what the status is on this dispute.

**Comment by ManfredKarrer** [comment]
@keo-bisq  I am in email contact with the buyer. I fear the seller has the dispute closed and will not watch new messages. I will try to find a way to send him a direct message.

**Comment by ManfredKarrer** [comment]
Should be fixed with changes in latest releases. Otherwise please re-open.
