### ISSUE TITLE
What IDE the devs are using?

### ISSUE THREAD

**Issue by jared201** [bisq-network/bisq#1507]
hi, just want to check what IDE the devs are using? i'm looking at reviewing the entire source code and will write down my Wiki in my own fork going forward. Thanks!

**Comment by cbeams** [comment]
We all use IDEA. Make sure you're using a recent version 2017.01 or better. See https://github.com/bisq-network/bisq#readme for further details.

**Comment by sqrrm** [comment]
Manfred had troubles with the latest one, 17.03 seems to work well.
