### ISSUE TITLE
Erro at TradeSignAndfinalizeDisputedPayoutTx

### ISSUE THREAD

**Issue by phrost33** [bisq-network/bisq#1508]
![screen shot 2018-04-10 at 10 24 04 am](https://user-images.githubusercontent.com/38252186/38564826-4bd7a910-3cb6-11e8-936f-99c32752cf90.png)

**Comment by phrost33** [comment]
I can't trade anymore. Every time that I try to take a offer it doesn't work.

![screen shot 2018-04-10 at 11 58 58 am](https://user-images.githubusercontent.com/38252186/38565026-a993cbce-3cb6-11e8-8f1f-8b6b0c7f16ec.png)

**Comment by ManfredKarrer** [comment]
Can you send me the logs? manfred at bitsquare dot io. Did anything special happen (crashes,...)?

**Comment by phrost33** [comment]
I will try. I’m not sure. It seems that my offers "to buy" that got expired. 

I lost some satoshis too.

How can I get the log again?

**Comment by ManfredKarrer** [comment]
At account/backup there is a button to open the log file

**Comment by phrost33** [comment]
Same error again. Every time that I open Bisq it shows up. Attached the error screenshot and log.

![screen shot 2018-04-11 at 9 31 43 am](https://user-images.githubusercontent.com/38252186/38616667-3210a972-3d6b-11e8-85f0-8fbc7392851b.png)

**Comment by phrost33** [comment]
[bisq.log](https://github.com/bisq-network/bisq-desktop/files/1898768/bisq.log)

**Comment by ManfredKarrer** [comment]
Seems that there is a dispute payout with a tx output which has already been spent. I would recommend that you do following:
1. Make a backup from the data directory (account/backup)
2. Check if the wallet balance is as expected. Open the wallet tool with cmd+e and see if the balance is the same as the sum of available + reserved in the UI. If not got to settings/network and click the "delete spv chain file" button.
3. If balance is ok and if u dont have open offers, trades, disputes I would recommend to start over with a new data directory to avoid the risk that there are future issues. You can export your payment accounts and re-import them afterwards. See: https://bisq.community/t/switching-to-a-new-data-directory/1697
If you dont want to do that and if you dont have open disputes you can delete the DisputeList file inside the data directory (/Bisq/btc_mainnet/db/DisputeList). I assume the error should be gone then.

**Comment by ManfredKarrer** [comment]
I will remove the log file for protecting better your privacy.

**Comment by phrost33** [comment]
Thanks
    
    
    On 12/4/18 1:55 AM, Manfred Karrer
      wrote:
    
    
      I will remove the log file for protecting better your privacy.

**Comment by ManfredKarrer** [comment]
Should be fixed with changes in latest releases. Otherwise please re-open.
