### ISSUE TITLE
Option to have fiat values rounded to full euros, 0 cents

### ISSUE THREAD

**Issue by marco4444** [bisq-network/bisq#1511]
Proposal to change the precision of the price in the trade statistics
 
Setup of the fiat trade values. In order to increase the privacy of fiat2BTC trades all fiat amounts 
should be optional rounded to a full amount $xx.00, €xx.00. Background is that a decimal place .00 occurs 39 
times more often in all fiat transfers than the average .xy and even 390 times more often than bad 
choices like .93 or .74. If rounded by value = Math.round(value) it would be much more difficult to 
reveal the identity of a bisq trader on the fiat side by time/amount attacks while beeing no big loss 
for the traders. Because the history of all trade amounts+times are public and all unhacked bank data have a high 
chance to be hacked and sold in future it's wise to use only Euro amounts which have many clones in the total currency area 
at the trading time + 24h.

P.S: Important is that the fiat value transferred via bank account has 0 cents, not only the visible history in the bisq client.

EDIT: Clean up formatting and made title more clear

**Comment by ManfredKarrer** [comment]
@ripcurlx 

I just looked into it. We would need to do it on the UI level for displaying the fiat amounts with zero precision, so that users always transfer the plain amount (443.00 instead of 443.23). 
Not sure if that is too much effort for the upcoming release. But lets keep it in mind....

**Comment by ManfredKarrer** [comment]
I checked the currencies which have a larger value than USD:
http://sassyfeeds.com/top-10-expensive-currency-world-today/
If we simply remove the decimal value from the fiat amount it would still not hurt too much even with the most expensive currency (Kuwait Dinar).

As the lowest BTC value the user can enter is 0.0001 BTC and that is below 1 USD we need to ensure that the fiat value is at least 1. Usual rounding can be used, just in case it results in 0 we need to change to 1.

The open question is how we communicate that rounding to the user to avoid confusion?
Specially if he changes the price and does not see any effect in the volume he might get confused.

@ripcurlx Any idea? An info icon might do it...

The PRs at https://github.com/bisq-network/bisq-core/pull/116 and https://github.com/bisq-network/bisq-desktop/pull/1558
are not ready for merge and not much tested. Percentage based price changes are not tested as well.

**Comment by ManfredKarrer** [comment]
Another question is how we deal with the update. Users who have not updated yet will see the exact price and will transfer or expect a different Fiat amount than users who have the update.
One possibility would be that we enable the feature after a few weeks so we give user more time.
Or we simply ignore it and risk that a few dispute cases get opened from it.
Another would be that we add another popup to tell the user about the new feature and that the fiat might not match exactly what he sees in the app.

**Comment by ghost** [comment]
> Another would be that we add another popup to tell the user about the new feature and that the fiat might not match exactly what he sees in the app.

Would it not be enough to mention at the first use(s) to read carefully the documentation, and to have this rounding affair properly mentionned in the doc ?
(Could also be done together with a popup).

**Comment by ripcurlx** [comment]
I think that it is crucial that we make sure not to increase arbitration cases. I would go for both ways you have suggested to communicate this feature. We add this feature in the next release and deactivate it in a way, that we can enable it in the future if we think the update rate is ok. At that point we show a popup for old and new clients that both rounded and exact decimal values are accepted as correct fulfillment of the trade protocol.
Regarding UI change we could do something like that:

![round-volume-icon](https://user-images.githubusercontent.com/170962/40613054-37701a10-627d-11e8-9975-f0e2fe4a1dda.png)
![round-volume-pop-over](https://user-images.githubusercontent.com/170962/40613053-37538ed6-627d-11e8-960d-9571e65d243d.png)
![round-volume-take-offer-icon](https://user-images.githubusercontent.com/170962/40613052-37375702-627d-11e8-97d8-762f98beed7e.png)
![round-volume-take-offer-pop-over](https://user-images.githubusercontent.com/170962/40613051-371a6f84-627d-11e8-9bbd-73cbfa1c82ef.png)

**Comment by ripcurlx** [comment]
After having a discussion with @ManfredKarrer on this topic we might change the create and take offer scenario by moving the rounding to the next step putting an intermediary pop-up in between. Yes, the popup will be smaller in the final version and any text suggestions are more than welcome 😉

**Example screens for create offer**
![round-volume-warning](https://user-images.githubusercontent.com/170962/40660399-324610ba-6351-11e8-9742-456158c9c897.png)
![round-volume-confirmation-info-icon](https://user-images.githubusercontent.com/170962/40660424-4202d150-6351-11e8-92d3-a136f6283a5f.png)
![round-volume-confirmation-pop-over](https://user-images.githubusercontent.com/170962/40660501-722b0974-6351-11e8-99fb-4fc8bd81f1c3.png)

Besides the popup and the info icon in the amount input field we would need a popup for older clients to tell them, that they might receive rounded values in their trades. It is planed to integrate this feature hidden in the next release and hide this feature until version 0.8+ is live. So we have some time for the users to update and reduce arbitration cases, if users with old clients (0.7.0-) don't read the info popup. Is this ok for @cbeams and @keo-bisq?

**Comment by marco4444** [comment]
Great. I like the proposed text, because it explains what is done and why.
Wonder if it's possible to add a link (e.g. to this thread or another website) explaining why this increases the privacy. Most people thinking first time about this topic have the gut feeling that a rounded amount is suspicious and an amount like 713.97 is perfectly inconspicuously. A little explanation for interested users might avoid questions, irritations ... .

**Comment by ripcurlx** [comment]
Yes, we could link a GitHub issue in the popup, but I was thinking if it might make sense to have documentation of certain features also in the https://docs.bisq.network/?

**Comment by cbeams** [comment]
Yes! I'd like to consider moving away from text-heavy popups in the app and toward very brief popups that then offer the user a link to whatever document is most appropriate to read on that topic. And documents specific to given features are certainly something we can do, e.g. an "Editing Offers" doc that explains the options for editing, suspending and removing existing offers. See the PR at https://github.com/bisq-network/bisq-docs/pull/60 for more context.
