### ISSUE TITLE
Incorrect button behaviour when withdrawing bitcoin

### ISSUE THREAD

**Issue by mrosseel** [bisq-network/bisq#1512]
After a completed trade, I pushed 'Withdraw to external wallet'. 
This operation succeeded (tx on the blockchain) but after that both buttons were grayed out, my trade was still in view and I stayed in the 'Open trades' screen.
When switching to another tab and returning, both buttons were enabled again, and I could again move the funds to somewhere. 
No errors were seen in the log.

Expected: after withdrawing, the trade is no longer open and the view changes to somewhere else.

**Comment by ripcurlx** [comment]
Did you test this on our current master branch in production or with our latest release?

**Comment by mrosseel** [comment]
* downloaded version of v0.6.7
* update: after 5 minutes the view did switch as expected. Log is available via email
