### ISSUE TITLE
Adding Serve Payment Method - USA

### ISSUE THREAD

**Issue by slav2020** [bisq-network/bisq#1517]
**Purpose:** 
Description of Serve Send Money payment method and review of the features necessary to accommodate it in Bisq. This document will describe the Serve payment/acceptance process as well as the suggested UI functions on Bisq.

**Prerequisites for using Serve:** 
1)	Amex Serve Account with telephone or email registered on the account and user enrolled in Send Money service
2)	Access to Serve mobile application or online portal.
3)	Account should be below monthly limit for sending funds - believe USD 2,500 currently monthly per account. (The limit for receiving is based on total monthly transaction value per account -  I believe this to be 10K normally.)

**Serve Process overview (Online or mobile):**
Sending
1)	Access “Send & Request Money” function in Serve menu of options
2)	Select “Send Money” and “Add a new contact”. Enter the email or telephone provided by the BTC seller. 
3)	Enter amount. Press “continue”.
4)	Add message which would be the Bisq trade unique identifier. Press “Review”.
5)	User will get a review screen showing destination email/phone, amount, remaining balance and memo on their account.
6)	Review and press “Submit”
7)	The funds sent should appear in your transaction history. (Note that the transaction can be cancelled by the Sender if it has not yet been accepted by Receiver. However, once accepted and confirmed by receiver it requires American Express to reverse the transaction based on fraud/error claims which is a much more involved process.)

Receiving
1)	Using Mobile application, access the transaction history section. In the Serve online site, access the send section of the site if you don’t see it on the login screen.
2)	Review the incoming transaction for amount, sender ID (email address), comment and click accept, follow the review and confirm screens to fully accept.
3)	The accepted transaction should appear in the transaction history log (if declined it will be marked as declined and funds would have been returned to the sender immediately)
Please note that the above process is real-time so sending and receiving will be almost instantaneous barring any network issues. Additionally, cancelling a payment or declining an erroneous payment is also in real-time allowing users to resolve minor issues that may arise such as miss-typed addresses/amounts, forgetting to add the unique transaction ID, breaching Serve transaction limits, etc.

**Suggested Bisq functionality for accommodating Serve transactions:**
1)	Setting up National Currency Account
a.	Payment Method  = “Serve”
b.	Account Owner Full Name = <Name> (should be made optional)
c.	Serve email or phone number = <email> or <phone>
d.	Currency = <USD>
e.	Limitations = “Max. trade duration: 1 day / Max trade limit: <LMT> / Account age: 0 days
f.	Salt for account age verification = <Salt>
g.	Account Name = <account name>
h.	“Information” screen can stay the same. No changes necessary.

2)	Create offer to buy BTC
a.	Enable use of Serve Payment method.
b.	No other changes necessary.

3)	Create offer to sell BTC
a.	Enable use of Serve Payment method.
b.	No other changes necessary.

4)	Buying/Selling BTC
a.	The buyer of BTC (ie Serve sender) only needs to know the email or phone designated by the receiver (Full name is not necessary). All other instructions should be the same as Zelle/ Cash app – ie. Not entering any comments besides unique trade ID, etc.
b.	BTC Seller (ie Serve receiver) only needs to know the sender’s email address, amount and unique trade ID. No other information is required to confirm the incoming funds and accept or decline the transfer.
c.	There should also be a note added to one of the screens that BTC Seller (ie. Serve receiver) needs to accept payment in the Serve site before releasing BTC since the transaction can be unilaterally cancelled by the BTC buyer until confirmed.

**Comment by slav2020** [comment]
Web: https://www.serve.com
Mobile app: Available on OIS and Android
Chargeback risk: Low
Privacy protection to other peer: High
Mandatory data for a transaction: Registered email or phone number, trade reference number
Duration: 5 minutes
Region: USA
Fees: Low
Verifiable: Need copies of Sender and Receiver screens confirming sending/receiving
Fraud risk: Low

**Comment by alfsbs** [comment]
Issue moved to [bisq-network/payment-methods #7](https://github.com/bisq-network/payment-methods/issues/7) via [**ZenHub**](https://www.zenhub.com/)
