### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by Yummis** [bisq-network/bisq#1518]
@bisq-network @cbeams 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/34694228/39152649-e8e8e82e-4740-11e8-9c90-a6f56a3f01f2.png">

**Comment by Yummis** [comment]
Paid already the deposit, it happened to me before, now the deposit is lost :-(

**Comment by Yummis** [comment]
I tried again but it happened again, more money lost 😩😩, 
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/34694228/39154876-c5e79864-4747-11e8-9841-b22603d89792.png">

[bisq.log](https://github.com/bisq-network/bisq-desktop/files/1940143/bisq.log)

**Comment by Yummis** [comment]
Is there any way I can get the deposit back?

**Comment by ManfredKarrer** [comment]
The deposit is not lost but maybe the taker fee. Check the transactions in funds/txs to see that the deposit tx was not created. You can double check with cmd+e the internal wallet balance with that what you see in the UI (need to match sum of available + reserved).

**Comment by ManfredKarrer** [comment]
Should be fixed with changes in latest releases. Otherwise please re-open.
