### ISSUE TITLE
Implement civic.com to verify bisq users

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#1524]
Implement www.civic.com to verify bisq users. 
See discussion: https://bisq.community/t/new-requirement-for-payment-accounts-with-charge-back-risk/2376/82?u=leo

**Comment by ManfredKarrer** [comment]
When I tried civic out a few months ago it was a joke... Primitive email verification and rest "will come soon"....
Also ID verification is a problematic path. As long it is not needed let's keep it out.

**Comment by bitcoinuser** [comment]
I wrote this to Civic:

![captura de tela de 2018-05-01 16-21-19](https://user-images.githubusercontent.com/1178856/39489648-a8d34758-4d5c-11e8-9cdd-e1c3dfa62ec6.png)

**Comment by ManfredKarrer** [comment]
Closing as no plans to go in that direction.
