### ISSUE TITLE
The "Offer book" graph is showing inconsistent information

### ISSUE THREAD

**Issue by fedegrc** [bisq-network/bisq#1525]
Hi, I'm creating this issue in order to propose a change to the graph located in the section  "Market -> Offer book". First, I'll describe the issue I'm seeing using this graph:

![issue](https://user-images.githubusercontent.com/14953828/39454502-0a5025ba-4cb2-11e8-956f-ea47b5762d06.png)

Following the table related to the Buy side of the previous graph:

![issue2](https://user-images.githubusercontent.com/14953828/39454526-41979184-4cb2-11e8-95ec-cb36350281a2.png)

The summation of all BTCs is 1.28 BTC. If we want to buy all BTCs, we should spend USD 12047.77, so the Price is 12047.77 / 1.28 =  9412.32. If we see the graph, it shows a Price of ~9760 instead of 9412.32

I have been working on a R function that could solve this issue and provide useful information. The result is this graph:

![grafico-3](https://user-images.githubusercontent.com/14953828/39454310-ebe28646-4cb0-11e8-9435-1009c5a40274.png)

**Comment by ripcurlx** [comment]
@fedegrc Thanks for pointing this out. I'll have to see how this is calculcated atm and will come back to this issue soon.

**Comment by fedegrc** [comment]
@ripcurlx , an easy way to see that the graph is wrong is recognizing that sometimes there is a vertical lines showing the same Price for two or more Amount in BTC, which is mathematically impossible (except if the vertical line is in the "first/best" value).

![screenshot_20180514_160149](https://user-images.githubusercontent.com/14953828/40017573-268b76ce-5790-11e8-96ff-7468cab87d8e.png)


The Price col of the following table shows the correct values:

```
  USD    BTC  cumsum(USD) cumsum(BTC)   Price
 353.12 0.040    353.12     0.0400    8828.0000
1070.73 0.125   1070.73     0.1650    8629.3939
1056.80 0.125   1056.80     0.2900    8553.9655
2119.60 0.250   2119.60     0.5400    8518.9815
1059.80 0.125   1059.80     0.6650    8511.3534
```
