### ISSUE TITLE
Bisq shouldn't accept orders of (Transfer with same bank) on Brazil.

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#1531]
Hi, recently I had a bad experience on localbitcoins involving bank transfer with the same bank on Brazil

1- I sold bitcoins to an user, the user sent me his identity and the name was identical of bank account owner.
2- He sent me the money and I released the bitcoins.
3- After a day I see that the money that I received was blocked by my bank. (The bank is the same of the buyer)
4- The bank told me that the owner of the account that sent me the money contacted the bank and the police and said that it was not him that released the money. But remember that I had proves that it was him. The bank told me to prove that I sold a product to the buyer. (Localbitcoin and photo of the buyer identity was not accepted). 
5- The money blocked from my account was released to the buyer. 

What I want to say is that bank transfer of same banks on Brazil is not secure. Anyone can say that it was not him that released the money, the bank will block the money. If you do not prove (localbitcoins is not accepted as a prove), the money goes back to the buyer. 

So I propose for bisq to remove the payment method (Same bank account) for Brazil. And for (National Bank Account) I propose do not accept orders of people that has the same bank account of who is selling.

**Comment by bitcoinuser** [comment]
Bank transfers from different banks cannot be blocked. Just the justice has this power. But transfers with the same bank, the bank can block it and give back the money to the buyer.

**Comment by ManfredKarrer** [comment]
What was the amount?
Unfortunately any bank transfer is vulnerable to such and other payment methods even worse. The banks should detect a scammer who repeatedly get into such cases and the victim should go to court to get justice (I know that is often a burden) to make it for scammer and bank more troublesome to repeat such.  But shocked (but not surprised) about the low customer support qualities of banks. Hope some day we don't need banks anymore....

**Comment by bitcoinuser** [comment]
The amount was low, kind of 200 dollars. I talked with bank manager and he knew that I was the one that was telling the truth. But the bank politic looks like always tell bank managers, in this kind of case, to decide in favor of the buyer. I can tell that in Brazil all is bureaucratic and in most times doesnt pay to go to court. In the end the bank even closed my bank account.
In Brazil even in court, with contracts, judges can decide against you. it's crazy.

But if bisq implement an option for sellers do not accept orders of people with same bank account, for sure it helps in this specific case. What do you think?

**Comment by bitcoinuser** [comment]
One way to implement my suggestion is: when creating a new account on payment method national bank transfer, you could add a new field like (Doesn't accept orders from these banks). So I could write the banks I don't accept orders. I prefer to have options to write the bank name, because here in Brazil some banks changed the name. I have an example of a bank that the name was (Intermedium) and changed to (Inter). So in the field I could write Inter;Intermedium. So will block orders from these two names.

**Comment by ManfredKarrer** [comment]
We are short on dev resources and it makes usability not easier to add even more complex and hard to explain payment options. I think the same bank account and specific bank account methods also have been hardly used. 
We also cannot react on each individual case with software changes and I am not sure if the risk for other banks is so much lower? If banks acting willingly unjust and legal system does not help the victim things get difficult....

But if any dev pick it up and works on it, also explain why that option makes sense in some cases (opposed to the same bank account method which was introduced bc of lower or no fees) I am fine...
Just fear that it add quite a lot of confusion and gives wrong signals (like that people got scammed at Bisq).

**Comment by bitcoinuser** [comment]
> We also cannot react on each individual case with software changes and I am not sure if the risk for other banks is so much lower? If banks acting willingly unjust and legal system does not help the victim things get difficult.... 

Believe me, bank transfers from different banks is a lot harder to reverse (only legal system is able to do this). Only justice. So a scammer will never go to justice, because he is the scammer.

> But if any dev pick it up and works on it, also explain why that option makes sense in some cases (opposed to the same bank account method which was introduced bc of lower or no fees) I am fine...

At least in Brazil we have some digital banks that transfer to other banks without any fee.

> We are short on dev resources and it makes usability not easier to add even more complex and hard to explain payment options. I think the same bank account and specific bank account methods also have been hardly used.

I agree that same bank account and specific account is strange. I think this fields should be added in some way on (National bank transfer) window.
 
I'm not a developer, but hope someone pick it up. Thanks for listening me.

**Comment by blabno** [comment]
I could help but I don't understand the proposed solution. You're saying that the problem is with same bank transfer, but want to modify national transfer method?

**Comment by ManfredKarrer** [comment]
As i understood he want that same bank account transfer for Brazil gets deactivated. It would require to add a list of banks you want to block. I am concerned that adds a lot of complexity and confusion from user experience and I am not 100% convinced that this will change the security situation a lot.
If we support that I would rather consider to unify the same bank account and specific bank account with that new request (excluded banks) and have one alternative nation bank transfer payment method which comes with custom restrictions. The user then can define those 3 special cases. 
But I want to emphasize that the added costs in UX might be not worth it. If we win 5 new users by adding that feature and lose 20 others because they get too much confused its not a good idea to do that. So far those special payment methods have not been used much.

**Comment by bitcoinuser** [comment]
Hi, 

Yesterday I did a National Bank Transfer of 0.25 bitcoins on Bisq. Good that me and the seller used different banks.

To solve my problem now, I don't care if you keep the option to create account with (Transfer with same Bank). People that sell with this option should know the risks. 
If I sell bitcoin on Bisq I just would like that when adding a new account, on payment National Bank Transfer, should have a field like: 
(Doesn't accept orders from these banks). So I could write the banks I don't accept orders. I prefer to have options to write the bank name, because here in Brazil some banks changed the name. I have an example of a bank that the name was (Intermedium) and changed to (Inter). So in the field I could write Inter;Intermedium. So will block orders from these two names.

**Comment by bitcoinuser** [comment]
So my sell offfer that I created with National Bank Transfer account, will not be showed to all other users that have National Bank Transfer account. Will show just to users that have different bank account than mine.

**Comment by bitcoinuser** [comment]
Sorry for my english. Just read what I wrote and what I mean here is confusing:

> If I sell bitcoin on Bisq I just would like that when adding a new account, on payment National Bank Transfer, should have a field like:
(Doesn't accept orders from these banks). So I could write the banks I don't accept orders. I prefer to have options to write the bank name, because here in Brazil some banks changed the name. I have an example of a bank that the name was (Intermedium) and changed to (Inter). So in the field I could write Inter;Intermedium. So will block orders from these two names.

The "doesn't accept orders from these banks" is Doesn't accept orders from the same bank of the account I created. I gave options to write tags, like inter and intermedium, because the problem with banks changing names. Because bisq doesn't have a dropdown to choose banks from a list.

**Comment by bitcoinuser** [comment]
> The "doesn't accept orders from these banks" is Doesn't accept orders from the same bank of the account I created. I gave options to write tags, like inter and intermedium, because the problem with banks changing names. Because bisq doesn't have a dropdown to choose banks from a list.

In the end I just want that (National Bank Transfer),have an option to not accept orders from the same bank of mine. As a solution I suggested a new field, because bank names change. I suggested to write tags (bank name) that should be blocked to accept my sell offers.

**Comment by bitcoinuser** [comment]
Hi,

1- See my suggestion on print.
2- But I think is important to allow to add more tags because banks sometimes change name. So my trading account has bank field ex. (Banco Inter), but some users can have accounts with bank field (Banco Intermedium), that was the old name of the bank. So if I restrict to only Banco Inter, other users with bank field Banco Intermedium could accept the offer, but it shouldn't.
3- Other thing is that should only restrict one word, because if I restrict the word (Banco) "Bank in english", all offers that have in bank field the word bank, will not be accepted.

Of course, instead of restrict users from accepting the offer, when user click on it, it could show a warning message to the buyer that the seller doesn't accept transaction from the same bank. So if the user insist, he could loose fees, because the arbitrator will see that the sell offer didn't accept the transfer from that bank. 

![captura de tela de 2018-05-04 20-29-12](https://user-images.githubusercontent.com/1178856/39657329-3dff0cb8-4fdd-11e8-9931-1a5954c11ce3.png)

**Comment by bitcoinuser** [comment]
> Of course, instead of restrict users from accepting the offer, when user click on it, it could show a warning message to the buyer that the seller doesn't accept transaction from the same bank. So if the user insist, he could loose fees, because the arbitrator will see that the sell offer didn't accept the transfer from that bank.

I like this idea. The option could be even showed when creating a new sell offer, instead of add this on trading account as seen on the print above.

**Comment by bitcoinuser** [comment]
Hi @blabno, did you understand the problem? I really would like to see a solution to this problem to be able to create a sell offer. 
Thanks.

**Comment by blabno** [comment]
@bitcoinuser I get the idea, but it seems that Manfred is not happy with it. I share his doubts.
