### ISSUE TITLE
Time out happened TWICE within 5 mins. LOST fees. Can you recover fees?

### ISSUE THREAD

**Issue by Chronos23432** [bisq-network/bisq#1534]
Hi,

I initiated a BUY transaction. I needed a total of 30 seconds to click "Buy BTC", set amount of Btc and then, click Next Steps, then confirm transaction....Bisq started processing the trade, and I noticed it took ~1 minute - then error message appearedd saying "Transaction has TIMED OUT". Then I was told I would "worst case" loose my deposit.

I restarted Bisq and noticed that most BtC was refunded but Taker and Tx FEE were NOT refunded.

Then I tried to initiate the trade again - I went through the same set of steps to arrive to the same error message ".....TIMED OUT". Ahain, I lost Taker and Tx fee.

I have never seen this issue before.

My network is not down. My internet is working.
I have Tx IDs for both transactions but didn't want to publicly show them.

Why is this happening?
Should I keep trying, wait or do something else?
Will Taker and Tx fee be returned?

Any input and help?

**Comment by ManfredKarrer** [comment]
Should be fixed with changes in latest releases. Otherwise please re-open.
