### ISSUE TITLE
Trades ended in an error message. 

### ISSUE THREAD

**Issue by Jerrykro** [bisq-network/bisq#1538]
I made two trades that ended in an error message and lost "Taker and Txfer" fees.  Am hesitant to try another trade. Error message attached.

![20180512_083548](https://user-images.githubusercontent.com/39220569/39959185-187fb2a8-55c3-11e8-8bf9-a21984a40a14.jpg)

**Comment by ManfredKarrer** [comment]
Was it the same offer or offer-maker?
Did you had anything strange with your app or network problems?

**Comment by Jerrykro** [comment]
I just lost 0.72+ BTC (all) off of the Bisq Exchange. I was transferring some BTC out of the Exchange. The password entry locked. After I restarted the program, my coins where all gone.

**Comment by cbeams** [comment]
You haven’t lost the funds. Your wallet us just in an inconsistent state after the failure.

Go to `Settings->Network info->Resync SPV file` to fix it.

**Comment by Jerrykro** [comment]
The program only sync from 69% to 77% after 6 tries and then shots down.

**Comment by ManfredKarrer** [comment]
Do you have a local Bitcoin Core node running (in pruned mode)? If so stop that and start Bisq again.
Otherwise got to settings/network and delete the spv chain file.

**Comment by ManfredKarrer** [comment]
Should be fixed with changes in latest releases. Otherwise please re-open.
