### ISSUE TITLE
Make all UI screens safe for min. window size

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#154]
1. Find which min. window size we want to support 760x560)?
2. Check all screens if there are problems, add scroll panes if needed

**Comment by haiqu** [comment]
Top bar was the limiting factor here with 1024x768 on a Lenovo T60 laptop. I have now modified the spacings to make it work and will do a PR once I've finished adding a price feed from CMC for smaller altcoins.

At 760x560 it will be far too small to be usable, and most modern phones & tablets have a larger number of pixels than my laptop, so I'd suggest 1024x768 be set as the limit.

**Comment by ManfredKarrer** [comment]
Yes agree 1024x768 should be ok. Tablets are not supported as they don't run on any or our target OS (as far I am aware).

**Comment by haiqu** [comment]
Windows 10 mobile? Android also has a Java implementation so it could be ported there. I just bought a Nexus 7 so I might give that a try.

**Comment by haiqu** [comment]
I think we can close this one.

**Comment by ManfredKarrer** [comment]
Have you testes all screens with 1024x768? I think there are still some minor issues open, but not tested yet.

**Comment by haiqu** [comment]
A few text fields in non-critical places are truncated but mainly it's fine.
