### ISSUE TITLE
First wallet address gets reused

### ISSUE THREAD

**Issue by nothingmuch** [bisq-network/bisq#1540]
the first address generated by the HD wallet gets reused repeatedly, other addresses were used, only once per address, but these are clustered around the first address (e.g. with oxt.me) , allowing transactions to be linked. this also discloses disclosing balances etc to counterparties who may have personally identifying information due to the nature of the transfers

as far as i can tell this is because `getOrCreateUnusedAddressEntry` is only used in `completePreparedGenericProposalTx`, whereas [change address generation](https://github.com/bisq-network/bisq-core/blob/0d830b74478b1b70365a7d02daa76ac11380e3b0/src/main/java/bisq/core/btc/wallet/BtcWalletService.java#L450) uses `getOrCreateAddressEntry`. i've not attempted to verify this claim, i only spent a few minutes browsing through the code.

**Comment by nothingmuch** [comment]
oops, i started this bug report here, but after reading a bit I meant to post it on `bisq-core` as that's where the code is... sorry!

**Comment by ManfredKarrer** [comment]
@nothingmuch Thanks for reporting. 

I will check it (Edited: - was initially thinking you refer to the DAO code only).

**Comment by ManfredKarrer** [comment]
Yes, damn there is an issue. Will need a bit more time to analyze. Thanks for the finding! Feel free to make a DAO compensation request (see https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc) . That was a very valuable input!!!
