### ISSUE TITLE
Help avoid leaking identifying information about counterparties for bank transfers requiring contact name

### ISSUE THREAD

**Issue by nothingmuch** [bisq-network/bisq#1544]
In the UK faster payments only technically require a sort code and account number, but at least my bank also takes a name for the recipient, and saves this name as a contact.

In lieu of a name, one could paste the peer ID into the name field, but this allows the bank to correlate transfers with specific bisq users, by simply observing bisq nodes, so I think this should be discouraged, by providing an easier alternative.

To help users avoid inadvertantly divulging this information, an HMAC of the peer ID could be provided using the wallet key, resulting in a deterministic identifier that that is is unique for each sender and does not correlate with publicly available data on the bisq network itself.

**Comment by cbeams** [comment]
Closing as moved to bisq-network/payment-methods#12.
