### ISSUE TITLE
UI and arbitration

### ISSUE THREAD

**Issue by keo-bisq** [bisq-network/bisq#1545]
The new UI is apparently confusing with regards to who is buying and who is selling. I got my first arbitration now where a trader became a buyer when he wanted to sell. He got confused by the colour-coding.

Keo

**Comment by ripcurlx** [comment]
Actually the color coding didn't change at all with the update. Do you know more details on the path the user took within the client until she took the sell offer by mistake? So I know which wording in certain screens is not explicit enough.

**Comment by ManfredKarrer** [comment]
Close it as no further discussion appeared. Also the redesign makes it probably irrelevant as it changes a lot the user experience.
