### ISSUE TITLE
Bisq bitcoin trade not going through

### ISSUE THREAD

**Issue by ff1d1l** [bisq-network/bisq#1546]
[bisq.log](https://github.com/bisq-network/bisq-desktop/files/2020276/bisq.log)
An error occurred when taking the offer.

A timeout occurred.

The taker fee is already paid. In the worst case you have lost that fee.
Please try to restart your application and check your network connection to see if you can resolve the issue.Please try to restart your application and check your network connection to see if you can resolve the issue.
[Uploading bisq.log…]()

**Comment by ManfredKarrer** [comment]
Did you had bad network connectivity? There are many connection errors in the logs.

**Comment by chirhonul** [comment]
Ping @ff1d1l.

Is this issue still current, or can we close it at this time?

**Comment by ff1d1l** [comment]
Thank you, it was resolved satisfactorily.

 

Kind regards

 

ff1d1l

 

Sent: Monday, July 23, 2018 at 3:11 PM
