### ISSUE TITLE
smartphone notification service

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#1547]
I think it would be useful to have a notification service available for important events occuring in desktop application (offer taken, payment sent, etc) when the user is away.
For example, [Pushover](https://pushover.net) is a great service, allowing the user to receive notifications on your devices (phones, tablets, etc) from any application using an API which is basically an URL post to their servers.

**Comment by ManfredKarrer** [comment]
Pushover sounds good but it is not clear to me how the complete process would work exactly.
We don't want that users need to register at their service (usability and privacy issue) or that the Bisq app connects directly to their service (privacy issue, all runs over Tor by default in Bisq - those services often don't support API calls over Tor).
 
Can you define more detailed the model in a proposal?
There are some rough ideas how it can work also without any 3rd party service...

**Comment by ghost** [comment]
Right, I missed the strong privacy requirements... In that context, my proposal does not work obviously:
- it requires an account on their website
- app must perform an API call to their website (no idea if it would work with Tor)

I'll check about no-3rd-party solutions...

**Comment by blabno** [comment]
https://github.com/mrosseel/bisq-api/issues/67

The problem with notifications, be it FCM, GCM, or any other is that it requires registering an account with Google or other provider and set those credentials up with the backend (desktop or bisq-api).
Obviously, we cannot have the same credentials stored in the source code as it would be abused.

**Comment by ManfredKarrer** [comment]
Close that issue as a notification app is in development:
See: https://github.com/bisq-network/proposals/issues/25
