### ISSUE TITLE
Add support for Monero 2-of-3 Multisig

### ISSUE THREAD

**Issue by needmoney90** [bisq-network/bisq#1548]
I'm currently building a market making bot, [Merkato](https://github.com/livinginformation/merkato), which is nearing beta. I would like to allow users to market make with Merkato on Bisq in an automated fashion, but to do so will require either atomic swaps (in development), or 2-of-3 multisig with a trusted party that can release funds in the case of a dispute.

Out of all the cryptocurrency communities in the ecosystem, Monero's goals are best achieved if a significant amount of its liquidity remains off of censorable centralized exchanges - and the clear choice for that at the moment is Bisq. If you guys are interested in speaking further about getting Merkato working on Bisq with multisig infrastructure, I would be very interested in setting up a meeting. I think it has the potential to turn Bisq into the go-to place to buy and sell Monero for everyday users.

- Livinginformation (Needmoney90)

**Comment by ManfredKarrer** [comment]
Thanks for reaching out! Sounds very interesting! If you have time end of the week we can have a voice chat. Can you get in touch with me on Slack or by email (manfred at bitsquare dot io)?

**Comment by ManfredKarrer** [comment]
I will close the issue as it has not actionable results yet. Looking forward for further cooperation with Merkato!
