### ISSUE TITLE
Settings | Network Info | Bitcoin network

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#1550]
On a Bisq-0.7.0 debian 64 bits,
In the Settings | Network Info | Bitcoin network tab,
Connected peers:
The mentionned onion addresses are repeated.
1st address, repeated 3 times
2nd address, repeated 3 times
3rd and last address mentionned, repeated 2 times.

Not sure if this is really wanted ?

**Comment by ManfredKarrer** [comment]
Which mentionned onion addresses? Can you post a screenshot?

**Comment by ghost** [comment]
```
[c6ac4jdfyeiakex2.onion]:8333
[c6ac4jdfyeiakex2.onion]:8333
[c6ac4jdfyeiakex2.onion]:8333
[vlf5i3grro3wux24.onion]:8333
[vlf5i3grro3wux24.onion]:8333
[vlf5i3grro3wux24.onion]:8333
[vlf5i3grro3wux24.onion]:8333
[sjyzmwwu6diiit3r.onion]:8333
[sjyzmwwu6diiit3r.onion]:8333
```

**Comment by ghost** [comment]
![bisq-22052018a](https://user-images.githubusercontent.com/34919942/40374818-6b7e1602-5dd9-11e8-9a5e-f8f9e8f6185c.png)

**Comment by ManfredKarrer** [comment]
So at the BTC nodes you get the same nodes multiple times. That's weird. How long have you running Bisq without restart? Did you had network issues? After a restart you should have no duplicate BTC nodes there.

**Comment by ghost** [comment]
> How long have you running Bisq without restart? 

Bisq was launched at 11:30 the same day, so just a few hours

> Did you had network issues? 

The PC running Bisq gets internet thru wifi(box) + wifi (local), so network issues are possible.
But, on the same time, the P2P network, as showed in Settings|Network Info has no duplicates

fwiw, in the log there is this kind of message
mai-23 00:58:56.254 [BlockingClient network thread for c6ac4jdfyeiakex2.onion:8333] INFO  o.b.core.Peer: Received alert from peer [c6ac4jdfyeiakex2.onion]:8333: URGENT: Alert key compromised, upgrade required 

I'll try to have a better look at the log file, but it's a huge (2.5MB) file.
Should I search for some specific things ?

> After a restart you should have no duplicate BTC nodes there.

I'll restart Bisq and see

**Comment by ghost** [comment]
I have moved the PC on a better place for wifi reception.
I have restarted Bisq
... and there are now 9 nice BTC peers, all different.
So, things seem ok.

**Comment by ManfredKarrer** [comment]
That "Alert key compromised, upgrade required" message is a misleading warning. It is just that in Bitcoin they removed the Alert feature a while ago... so you can ignore that.

You can observe it a bit if it appears again that you get duplicated BTC nodes. It is not terrible bad just meaning you have less different nodes connected to, so less redundancy but should not be the case. Probably at connection loss and re-connects there are some issues in the code that it does not ignore already connected peers for new connection attempts. Though that is inside BitcoinJ and we don't have a dedicated dev for that area atm.

**Comment by ghost** [comment]
Thanks for your explanations and your time Manfred.

**Comment by ManfredKarrer** [comment]
Closed as not reproduceable

**Comment by ghost** [comment]
I continue to have this issue on a regular basis.
But, as said, my connection is wifi + wifi, so I believe this may well be the real reason.

**Comment by ManfredKarrer** [comment]
Ok, I reopened it for further investigation. Seems that at connection loss you reconnect to the same peers.

**Comment by ManfredKarrer** [comment]
Fixed
