### ISSUE TITLE
Stuck at "Waiting funds" after 6 confirmations (Loss of funds)

### ISSUE THREAD

**Issue by nolim1t** [bisq-network/bisq#1551]
I've created a test trade just to see how it works, however theres no UI indication at all. How many confirmations does it usually take for the trade to start?

Offer
![offer](https://user-images.githubusercontent.com/83470/40417657-72f91b9e-5eaa-11e8-8fda-d4336c52309d.png)

[Blockchain Info](https://blockchain.info/address/1FJrEwh1ZeBvB7Bv7XX1uVNgNi67Ccfvy3)
![blockchain](https://user-images.githubusercontent.com/83470/40417626-5fe359a2-5eaa-11e8-80b3-a2373a2e9015.png)

**Comment by nolim1t** [comment]
Used an external wallet to fund the transaction

**Comment by ManfredKarrer** [comment]
Hm, that is strange. Usually Bisq recognize the tx as soon it is seen in the network. No need to wait for any confirmation.
Did you have Bitcoin Core running and was is not fully synced? That might be a reason for the issues. After restarting Bisq you should see the received tx in funds/tx.
[EDITED]

**Comment by nolim1t** [comment]
The screen is above is "Create offer" screen when opted to fund using an external wallet.

The transaction is on the blockchain

**Comment by nolim1t** [comment]
version 0.7.0

**Comment by ManfredKarrer** [comment]
Which external wallet did you use? If it was Bitcoin Core was it still syncing blocks?

**Comment by ManfredKarrer** [comment]
Which external wallet did you use? If it was Bitcoin Core was it still syncing blocks?

**Comment by nolim1t** [comment]
Using a mobile wallet.

It's confirmed on the blockchain (130+ now) but now because I closed the app the funds seem to have disaappeared or no longer in my control

**Comment by ManfredKarrer** [comment]
Do you see the funds in Bisq? If not check with cmd+e the internal wallet balance. That has to be the same as the balance u see in the UI (available + reserved). If not got to settings/network and resync the spv chain file.

**Comment by nolim1t** [comment]
the funds are not in the internal wallet balance.

The create offer address (the address thats shown when you try to create an offer) is somehow not linked to this so the funds is currently 'lost'

**Comment by ManfredKarrer** [comment]
Try to resync the wallet in settings/network (resync spv chain). if the tx to your address is confirmed the funds are not lost, no worry.

**Comment by nolim1t** [comment]
when I resync the spv chain another issue occurs. Keep getting the tor error message. Is there any other way of recovering the funds?

**Comment by ManfredKarrer** [comment]
Which tor error message?

**Comment by nolim1t** [comment]
This error message
![tor error](https://user-images.githubusercontent.com/83470/41019391-9537005c-6988-11e8-87b9-9b6d9068b2c6.png)

Then I delete the tor files and restart (done this many times, and different internet connections)

Proof of syncing
![after deleting](https://user-images.githubusercontent.com/83470/41019401-a9abc6a8-6988-11e8-89b5-c22b34f69762.png)
![7 peers after deleting](https://user-images.githubusercontent.com/83470/41019402-a9e90338-6988-11e8-9122-e3e365ddf061.png)
![9 peers after delete](https://user-images.githubusercontent.com/83470/41019403-aa22c078-6988-11e8-9fa9-fb1c50ba6bea.png)

Then  after it returns to the same thing.

**Comment by nolim1t** [comment]
So basically now stuck with unrecoverable funds after "resyncing the chain"

**Comment by ManfredKarrer** [comment]
Hm, thats weird. Do you have any network restrictions, unstability or VPN?
Do you have the seed words backed up? With that you always can recover your funds. Beside that there is a wallet tool where you can display all private keys. You can open that with cmd+j.
Maybe try to user Bisq from another network environment, then all should work normal. Seems to be some local issue at your network.

**Comment by nolim1t** [comment]
I tried from many different networks in different places including VPN same thing.

Anyway the cmd+j thing worked which dumped all the private keys and was able to sweep the funds into another wallet.

I'll close this issue for now any maybe do a reinstall and try again
