### ISSUE TITLE
TIMEOUT ERROR happened TWICE within minutes from each other ....can you refund the two "Taker fees"?

### ISSUE THREAD

**Issue by Chronos23432** [bisq-network/bisq#1554]
Hello,

I received an error when I placed my order. I placed order TWICE, minutes from one another.
"An error occurred with taking offer
A timeout occurredThe taker fee is already paid. In the worst case you have lost that fee. Please try to restart....
To help us improve the software please report the bug at our issue tracker....."

(1) First buying error.
Maker Fee transaction ID (not recorded on a chain): aa63289d9f461761c24adfe8f4c429944de05b059a284f6201dd36160b19e41b
taker fee transaction ID *(recorded and unconfirmed on the chain): 87ea322f06ea373ed7f8ebdeee24c6c87b3feccc0e01c673f00be119a24da866

taker fee was: 0.00003200 BTC 

(2) Second buying error.
Maker Fee transaction ID (not recorded on a chain): aa63289d9f461761c24adfe8f4c429944de05b059a284f6201dd36160b19e41b
taker fee transaction ID *(recorded and unconfirmed on the chain): 
8480e4b25bc590616e07f12ec301aefd083e1c4d892e63accda9ccd396a60554

taker fee was: 0.00003640 BTC

Interestingly both buying trades had identical(!) Maker fee. (Myabe that's normal. I was trying to buy from the same seller twice within minutes).

Can I have that refunded?

How can I avoid this problem? (this is second time this occurred. last time was 3 weeks ago, I believe also around midnight (US central).

Are there times I should NOT be using Bisq?

**Comment by ManfredKarrer** [comment]
Did you had any bugs or network issues? Instable network can cause that. 
Send me an email (manfred at bitsquare dot io) with a btc address and the lost trade fee so I can reimburse you. Please send me also the log file (account/backup -> button to open it).

**Comment by ManfredKarrer** [comment]
Refunded the lost fee and have not seen any suspicious in the logs. It might be an issue on the makers side (3 times same offer). I will close now but if you get another issue please re-open.

**Comment by cbeams** [comment]
Thanks for refunding the fees, @ManfredKarrer. In the future, please create an issue at https://github.com/bisq-network/support/issues. This makes it possible to quickly handle failed trades as they happen, to batch up fee reimbursements and save on transaction fees, to track how many of these we're doing over time, and to create clear accounting about the reimbursements (in case someone says they didn't receive theirs, etc).

These issues are really simple. The main thing is to just paste in a screenshot of the transaction IDs as well as their plain text values. For example, here's a reimbursement issue I created yesterday: https://github.com/bisq-network/support/issues/110.

**Comment by ManfredKarrer** [comment]
Ok. Will do next time. Thanks!
