### ISSUE TITLE
Check Monero tx message when buying XMR

### ISSUE THREAD

**Issue by kopite77** [bisq-network/bisq#1555]
When you buy XMR in bisq, you wait for the seller to start the tx to send you XMR before you pay with your BTC. Once this step is started, you are notified and the dialog (sorry I did get to screenshot) tells you to check with your favorite Monero block explorer that the transaction sent to your address has a confirmation. But this is wrong as this action is not possible through a block explorer in Monero. You have to confirm this in your wallet if your node is fully synched.

**Comment by ManfredKarrer** [comment]
Yes, true. The popup should be modified for Monero.

**Comment by ManfredKarrer** [comment]
@ripcurlx Lets try to get that fixed for next release...

**Comment by ManfredKarrer** [comment]
Fixed in https://github.com/bisq-network/bisq/pull/1720

<img width="920" alt="screen shot 2018-09-24 at 12 50 04" src="https://user-images.githubusercontent.com/1449498/45969125-6c071c00-bff8-11e8-9843-a5958d6cbf19.png">

**Comment by kopite77** [comment]
@ManfredKarrer @ripcurlx I encountered this issue again in v0.8.0. Please see attachment. 
![screenshot](https://user-images.githubusercontent.com/34752465/48305488-1de2a500-e4e0-11e8-88c0-33dc7ad34196.png)

**Comment by kopite77** [comment]
@ManfredKarrer @ripcurlx I've just encountered this again with v0.8.1

**Comment by ManfredKarrer** [comment]
@kopite77 0.8.1 did not had any of the new features, it was just to avoid a performance issue at startup with a DB file. in 0.9 the feature will be shipped.
