### ISSUE TITLE
Fix issue where traders are able to send arbitration messages after a ticket has been closed

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1561]
From my arbitrator report this month at https://github.com/bisq-network/roles/issues/13#issuecomment-393193780:

> Another issue I haven't brought up before is the problem of traders sending arbitration messages after I've closed their ticket. When this happens, I never see the additional messages, because the ticket is hidden away from me, and because no sort of notification occurs when closed tickets get new messages.
> 
> Trade `NX5C4W5F` was such a case, and it left the buyer very worried for nearly a month. The buyer's bitcoin had never been released to them, even though I closed the arbitration ticket in their favor. The payout transaction never occurred, and I believe this is because my close ticket message / payout transaction signing message never made it to the buyer's client in the first place. I believe it's for this reason as well that the buyer was able to continue messaging me: their client never got the signal from mine that the conversation was over. Note that also have reason to believe, from the content of his comments, that he never received _any_ of my arbitration messages.
> 
> So this specific problem can probably be generalized to the known problem of dropped arbitration messages. We may be able to mitigate the effects effects of this specific problem, though, without necessarily having to fix the general problem. Getting any kind of notification that a closed message is still active would be helpful, but that's probably a lot of code we wouldn't otherwise want.
> 
> @ManfredKarrer has been thinking about doing "read receipt"-style messages as a way of solving the dropped message problem, i.e. getting an explicit confirmation message from your peer that they definitely got your message, with, say, a hash of its contents to prove it. We could build on this approach to ensure that my arbitration ticket doesn't actually close until we've gotten confirmation from the peer's side that their side is closed as well.
> 
> In any case, this problem creates a nasty experience for users, so would be good to remedy / mitigate in some fashion asap.

/cc @ripcurlx, as I believe you intend to work on arbitration-related issues like this and https://github.com/bisq-network/support/issues/85.

**Comment by ripcurlx** [comment]
I had already a discussion with @ManfredKarrer on dropped messages recently and one of my next tasks will be a confirm message for trade and arbitration messages. We could display it in the UI by showing WhatsApp like icons in messages or trade steps if a message was seen by the recipient or if is still a mailbox message. So it should help on this kind of communication issues. I’ll create an issue for this soon.

**Comment by cbeams** [comment]
@ManfredKarrer wrote at https://github.com/bisq-network/roles/issues/13#issuecomment-393857071:

> @cbeams Regarding the messages after closed: We could add a feature to auto-re-open a ticket if you receive a message later, including the red icon so you see that there is something open. A different close feature would be the required as well (as current close makes the payout tx).
> 
> To not close a ticket as long you have not received from both traders the confirm msg would be another good feature.
