### ISSUE TITLE
 Export/import sig.key

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1564]
To carry over a account age witness from a fiat account the sig.key need to be copied over as well.
See: 
https://bisq.community/t/carry-over-account-age-witness-to-new-data-directory/5605 for the description.

We should add an export sig.key and import sig.key feature to make that more convenient.
Though it need to be made clear to the user that there must not be open offer, trades or disputes where the signature might be used!

If anyone has a better idea, please share. Not sure if exporting/importing is here really the best idea...

**Comment by ghost** [comment]
is it: account age witness from a **fiat** account ?
or : account age witness from a (bisq appli) account ?
To help the understanding, maybe at first a more long and more explicit name could be use than sig.key ? : sig-pub.key ?

Actually, there is already a "backup wallet" function implemented in the Account menu (which is practically also a kind of export).
Is is better to have this already existing function, plus a new (separate) export/import sig.key function ?
Or is is imaginable to have those 2 functions packed in only one apparent for the user: "backup wallet + account infos" ?
My understanding is that actually the wallet is already practically completely linked to the bisq account, so maybe it makes sense to backup/export all this info pack in a same operation ?
(and btw, this makes me also think that the onion assigned adress may also be part of the pack).

My understanding of bisq is far from complete, so apologies for any misunderstanding.

**Comment by ManfredKarrer** [comment]
Fiat account:
See https://docs.bisq.network/payment-account-age-witness.html

The sig.key is the private key stored locally.

Yes Backup could be used but the moving to an new data directory is mostly because there are some database issues or the wallet is very old and  therefore takes long for syncing.
To have some configurable backup/export feature where u define which data you carry over might be an option. 
There are several types and aspects of the data:
- BTC wallet data
- db: there is a wallet database file (AddressEntries) which need to be in sync with the wallet
- db: most of the other db files can be usually deleted when moving to new data directory 
- keys: sig and encryption keys
- tor: hiddenservice onion key is only relevant data here. other data gets created from the app.

Its a bit complex to understand all aspects of all different data, I fear I need to dedicate some time on that once day, but will not be able to do that soon....
