### ISSUE TITLE
Bug with fixed currency at edit offer

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1565]
After  a user has clicked edit offer the currency will stick in create offer views as well as in the edit offer view.
To reproduce create 2 offers with fiat and an altcoin. Then go to edit offer at both and back to create offer. Switch payment method at create offer. The currency does not change anymore. At the edit offer it shows the same currency for both offers. 

See also: https://bisq.community/t/create-buy-offer-wrong-currency/5573/11

**Comment by initCCG** [comment]
This bug still in effect in 0.7.1.

**Comment by ripcurlx** [comment]
If you had the issue before it could be as it is persisted in the proto buffer objects. A one-time workaround would be as Manfred mentioned here: https://github.com/bisq-network/bisq-desktop/issues/1597#issuecomment-401545985.
After you have "fixed" your payment account objects like that  it shouldn't show up again in 0.7.1
