### ISSUE TITLE
Show popup if local Bitcoin core is running

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1566]
If a local Bitcoin Core is running we need to inform the user that he must not run that in pruned mode as otherwise the wallet might not sync. Furthermore are issues if the Bitcoin Core node is still syncing. Bisq should be started after Bitcoin Core is fully synced.

**Comment by ghost** [comment]
I did not count, but by browsing the discourse forum, I have seen and remarked this pattern arising indeed a number of time.

I was even wondering if this may also concern other crypto nodes: 
- where the crypto is in fact implemented over bitcoin
- where the crypto node is in fact just a bitcoin node rebranded
(There was a case yesterday june 5th (in the slack) with somebody having worries + a core node + a decred node.)

**Comment by ManfredKarrer** [comment]
Should not be affected by other nodes as long they don't use the same port.
