### ISSUE TITLE
ambiguity ? alt+0 = Open Dispute and Open Support Ticket

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#1568]
The support button in the application mentions: alt+o = open **support ticket**
while on the other hand, we mention often: alt+o as opening a **dispute**.

It seems imo that the sense is not the same, and we have already seen people reluctant to use this feature because they understood it as "open a dispute" (in the litigation sense) while they just wanted to signal a maybe purely technical problem (not involving the counterparty).
(My Robert & Collins says : dispute = discussion, but also dispute = litigation).

Maybe we could:
- either homogenize that, ie alt+o = open support ticket, which then leads either to technical help, or arbitration
- either have a alt+o reserved for technical support ticket, and another alt combination alt+d (or alt+a) reserved for arbitration/litigation ?

**Comment by ripcurlx** [comment]
We already started the discussion on this issue once (https://github.com/bisq-network/bisq-desktop/issues/1081), but didn't finalized it. IMO we shouldn't handle general support through this feature as it would cause more load on the arbitrators. Maybe we could open a popup when clicking cmd+o pointing the user for support to the [support repository](https://github.com/bisq-network/support/issues) and/or slack support channel and provide the option to open a dispute when triggered from within an active trade.
