### ISSUE TITLE
Use OS native notifications

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#157]
We use simulated notifiactions as JavaFX does not support native OS notifiactions. Find solutions to use native notifacitions.
See: http://mail.openjdk.java.net/pipermail/openjfx-dev/2014-September/015827.html

**Comment by qxotk** [comment]
@ripcurlx Might I ask if was:dropped label is removed, does that mean this is still a desirable enhancement?  I am looking through the "good first issues" to find something to contribute.

**Comment by ripcurlx** [comment]
Yes, having cross platform desktop notifications that are not just emulated would be great. But the last time I looked into it, it wasn't so straight forward.
