### ISSUE TITLE
Sorting of currencies in market/trades incorrect

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1570]
The currencies at market/trades should be sorted by number of trades but not all are:
<img width="373" alt="screen shot 2018-06-07 at 21 38 00" src="https://user-images.githubusercontent.com/1449498/41122250-3f03ab22-6a9b-11e8-80e3-ff35e817a01c.png">
<img width="352" alt="screen shot 2018-06-07 at 21 37 51" src="https://user-images.githubusercontent.com/1449498/41122251-3f20b71c-6a9b-11e8-811c-a4814af49f99.png">

**Comment by ripcurlx** [comment]
Still relevant
