### ISSUE TITLE
Error while taking an offer

### ISSUE THREAD

**Issue by coyg** [bisq-network/bisq#1571]
Hi,

I get the following error when trying to make a DCR-BTC trade:

An error occurred when taking the offer.  A timeout occurred.  The taker fee is already paid. In the worst case you have lost that fee. Please try to restart your application and check your network connection to see if you can resolve the issue.Please try to restart your application and check your network connection to see if you can resolve the issue.

[bisq.log](https://github.com/bisq-network/bisq-desktop/files/2086086/bisq.log)

Thanks,
Coyg

**Comment by SwallowGarage** [comment]
Exact same problem here

**Comment by richuurd** [comment]
Same here...my network connection is strong as well.

**Comment by ManfredKarrer** [comment]
We are working on improvements. Prob. next week we release a new version...

**Comment by ghost** [comment]
If richuurd speaks about his 6:30 EST Jun 22, trade (issue 1579)
this may well be due to bitcoin mempool congestion: 
6:30 EST Jun 22 = 11:30 GMT Jun 22, and a congestion was unfortunately just beginning at this moment : https://jochen-hoenicke.de/queue/#1,2d

**Comment by ManfredKarrer** [comment]
I doubt it is related to mempool congestion. That would only delay the confirmation time. In the worst case the tx would get removed from the mempool after a while (1-2 weeks). But as it was a short term congestion I don't think that this was the case.

**Comment by BigslimVdub** [comment]
Identical issue 9.3 on windows 10. Can not make trades when clicking “place offer to sell bitcoin” as it times out. 

After trying 4 times in a row to confirm transaction it did finally go through.

**Comment by ghost** [comment]
@BigslimVdub 
Do you have a good quality internet connection ? which kind ? wifi ?

**Comment by BigslimVdub** [comment]
Hard line and no WiFi. Service is cable internet. I have very good stable internet. Nothing else on the network is running tor and I do not use vpn. I also had an issue with deposit where bisq kept saying “waiting for transaction” for 45 minutes so I had to close and reopen for it to show funds deposited. I don’t seem to have issues on OS X. Possibly it is due to windows defender or something and I need to add exception to appdata bisq folder?

**Comment by ghost** [comment]
> Possibly it is due to windows defender or something and I need to add exception to appdata bisq folder?
Yes. There are regular issues with AVs on windows.
Bisq does its best about that, but it's not an easy issue.
If by any way you can specify your AV to let Bisq quiet, that may help.

**Comment by BigslimVdub** [comment]
I don’t have any AV on that machine just windows defender. Is there a list of folders to add exceptions to? I already did the folder I installed bisq to. Windows does not like tor services at all. Thanks for the help. I am unsure this is the issue for the original post or not. If I continue to have issues I will open a separate bug.

**Comment by ghost** [comment]
Bisq data folders on windows are:
Windows 7,8,10: C:\Documents and Settings\username\AppData\Roaming\Bisq 
Windows XP: C:\Documents and Settings\username\Application Data\Bisq 

It's generally with these folders that AV show problems.
