### ISSUE TITLE
Resend trade message bug 

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1577]
It seems that in some cases the resend message functionality does not detect once a message is really sent/arrived - or for some unknown reason the mailbox message never get stored and therefore the resend functionality always goes back to the "send again" state.

Here is the report of the user in slack:
"I have done that - but, after 3 hours it would appear it is stuck - i.e. at the point where it says "Wait until payment arrived" - this is exactly what happened to me last time.  To put this into context - an earlier trade, using National Bank Transfer, went through in minutes - this, problematic, trade, I have used "Faster Payments" - and it was using this method (Faster Payments) that I had problems before.  I know you will say, it is only 3 hours, wait - however, this is exactly what happened last time.  There is something wrong with the system when "Faster Payments" is used - and it should be corrected.  

Is there any way I can communicate directly with the other party (of this trade)?"

**Comment by ripcurlx** [comment]
Since this ticket was created lots of stuff changed with the transaction/message handling. I'll close this  ticket for now.
