### ISSUE TITLE
bisq: take offer in progress: then fail. 

### ISSUE THREAD

**Issue by proskilzz** [bisq-network/bisq#1579]
Dont know what to do just got stuck at taking offer. then error.

**Comment by proskilzz** [comment]
I should mention I have a vpn running.

**Comment by proskilzz** [comment]
tried a third time, bugged, (this time without a VPN) still hangs. kcPOB-cfde1564-364f-4032-9f07-16267ef37dda-070 trade id

**Comment by ghost** [comment]
Do you run a bitcoin node ?
Did you get an error message ? if yes, which one ?
At which precise time did you trigger your offer taking ?

**Comment by ManfredKarrer** [comment]
Was it the same offer? If so don't repeat, seems there is a bug on the peers side. Which payment method was used? Did you edited the offer? (there is a known bug in the edit offer feature)

**Comment by richuurd** [comment]
I got a the same timeout error @ 6:30 EST Jun 22, 2018.

"An error occurred when taking the offer. A timeout occurred. The taker fee is already paid. In the worst case you have lost that fee. Please try to restart your application and check your network connection to see if you can resolve the issue.Please try to restart your application and check your network connection to see if you can resolve the issue."

Running a full node. This is right after I had issues with broadcasting transactions and started over with new data directory.

**Comment by ghost** [comment]
There are issues if the Bitcoin Core node is still syncing. Bisq should be started after Bitcoin Core is fully synced.
https://bisq.community/t/bitcoin-core-pruned-mode/5659

There are also issues with pruned mode, but I assume this is not your case (?)

But your worry may also be due to bitcoin mempool congestion: 
https://jochen-hoenicke.de/queue/#1,2d
6:30 EST Jun 22 = 11:30 GMT Jun 22, and a congestion was unfortunately just beginning at this moment.
Did you notice your tx fees when you take the offer ?

**Comment by proskilzz** [comment]
I used interact e transfer, I did not edit the offer. Also the mempool was really congested that day.

**Comment by proskilzz** [comment]
I just tried again with a less congested mempool. an error again, I  feel the guys version is old.

**Comment by ManfredKarrer** [comment]
@proskilzz We will release soon a new version which will gives us more information about such cases and hopefully resolved that. It might be that there was an error on the peers side which caused the failure.

**Comment by ripcurlx** [comment]
We introduced changes effecting message broadcasting in https://github.com/bisq-network/bisq/releases/tag/v0.8.0 that should fix this issue. Please create a new or re-open this issue if it occurs again.

Closing as complete.
