### ISSUE TITLE
'Bitcoin Core nodes to connect to' unchangeable

### ISSUE THREAD

**Issue by marco4444** [bisq-network/bisq#1580]
Using latest version 0.7.0 
If I go to 
settings --> Network info --> Bitcoin core nodes to connect to
I cannot change this. When I try to select another radio button I'm forced to restart. After restart the setting is the old (Use provided Bitcoin Core nodes).

Can someone repeat this issue? 
Want to connect to my own core node, but it's not local, it's remote.
Thanks.

**Comment by ghost** [comment]
I repeated (at least I tried) this issue.
Trying to use http://bitcoin4-fullnode.csg.uzh.ch/ as BTC node.
... and now I'm unable to restart Bisq properly (I tried 3 times, even shutting the PC off)
Bitcoin network peers : 0 / connection failed bitcoin mainnet (using Tor)

In the log file:
``################################################################
Tor started after 7263 ms. Start publishing hidden service.
################################################################ 
juin-22 08:36:23.214 [JavaFX Application Thread] INFO  b.d.m.MainViewModel: initWalletService 
juin-22 08:36:23.235 [JavaFX Application Thread] INFO  b.c.b.w.WalletsSetup: Socks5Proxy for bitcoinj: socks5Proxy=localhost:42899	Version 5 
juin-22 08:36:23.250 [JavaFX Application Thread] INFO  o.b.c.Context: Creating bitcoinj 0.14.4 context. 
juin-22 08:36:23.254 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
juin-22 08:36:23.255 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= For input string: "//bitcoin4-fullnode.csg.uzh.ch/" 
juin-22 08:36:23.255 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.NumberFormatException 
juin-22 08:36:23.256 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.NumberFormatException: For input string: "//bitcoin4-fullnode.csg.uzh.ch/"

I can send the log file (the last 500 lines) if needed.

I'll probably need to restart with a fresh Bisq directory.

**Comment by ManfredKarrer** [comment]
Try it without http:// or the ip address 192.41.136.217 (http://seedmonitor.0-2-1.net/) or onion address.
If you have tor enabled only onion addresses are accepted. the ui there is not very sophisticated as it is a not much used feature anyway, but should be improved to detect those cases and accept http:// prefix...

**Comment by ManfredKarrer** [comment]
@marco4444 Which format did you use? try the domain name, ip or onion address only

**Comment by marco4444** [comment]
I wanted to enter just an ip-4 address, but could not enter anything. The field was deactivated. When I klicked the second (of three) radio button the field was for a millisecond activated, but the pop up window forcing restart was faster. After restart the left hand radio button was activated again and the field for the iP address deactivated.

Installed bisq on latest Fedora release on a Lenovo laptop with i5 Intel processor and 4GB RAM

**Comment by ManfredKarrer** [comment]
Ah ok, thanks for reporting. Will look into it...

**Comment by ManfredKarrer** [comment]
It is a UI glitch but you can close the popup then you can edit the field. The popup gets activated by any state change (radio button selection or leaving the text field). 
I will close that as the not-optimal UI behavior has not sufficient priority to get fixed.

**Comment by marco4444** [comment]
Couldn't close the popup at the time when I initiated this issue, however, after a new start of the OS (not only bisq) the behaviour changed and I could close as described above. So it's running successfully now, thanks for support!
