### ISSUE TITLE
Add popup for feedback after trade competion

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1584]
When a trade gets completed we should display a popup with asking the user for feedback about his experience. We can point to the forum as the preferred place to give user feedback.
Here is a draft for a text:

Congratulations for completing your first Bisq trade.
We would love to hear back from you to tell us what you think about the user experience. It will help us to improve the software and to smooth out edges.
The best place to get in touch with the Bisq community is the Bisq Forum at https://bisq.community.
Thanks for using Bisq!

Any suggestion for a better text is highly welcome!

**Comment by ghost** [comment]
Maybe : "We would love to hear back from you about your experience" 
would be a bit less redundant

**Comment by ManfredKarrer** [comment]
We could add that survey link as well: 
http://survey.io/survey/87c4f

**Comment by ManfredKarrer** [comment]
After discussion with @ripcurlx  we decided to show the popup after each completed trade but use the "don't show again" checkbox so users can remove it. We added the link to the http://survey.io/survey/87c4f (EDIT: we use https://bisq.network/survey in the code which redirects to http://survey.io/survey/87c4f 302).

It might be a good idea to use a bisq link so we are flexible to adjust the survey link.
@cbeams Could you add such a link? e.g. https://bisq.network/survey

EDIT: I made a [PR](https://github.com/bisq-network/bisq-website/pull/61) for a redirect. 
```/survey http://survey.io/survey/87c4f 302```

The popup is displayed after the user moves his funds. Otherwise if we show it directly at the completed screen it would cover the important result information.

<img width="1191" alt="screen shot 2018-06-26 at 13 19 01" src="https://user-images.githubusercontent.com/1449498/41908544-9b24d0b8-7944-11e8-9b6a-5812b44bec07.png">

The text can be improved as well the overall appearance (maybe some nice graphics?) But we can update that at any release to make that better. For now its better to have any way to provide a link for feedback, rather than none...

**Comment by ghost** [comment]
The survey is nice ... but I wonder if it is really useful to collect emails ?
Bisq is a great respectful of privacy tool, but imo this could/should also apply to the ecosystem around.

**Comment by ManfredKarrer** [comment]
Yes agree. I was wondering as well about the email field.... 
@ripcurlx Is it possible to still edit the survey page? If not we have anyway a redirect so we are flexible.

**Comment by ripcurlx** [comment]
Unfortunately it is not possible to edit the form itself. Of course we could use a service that allows better editing e.g. surveymonkey or Google forms, but these carry other privacy risks. Having the email would allow us to get in contact and get more detailed feedback if required. But I guess no one will provide it anyways ;-)

**Comment by cbeams** [comment]
I'll get back with updates to the text as soon as I can. Should just be an hour or so.

**Comment by cbeams** [comment]
## Original

> Congratulations for completing your Bisq trade
> 
> We would love to hear back from you about your experience. It will help us to improve the software and to smooth out edges.
> If you want to give us feedback please visit our survey page (no registration required).
> Bisq survey ->
> 
> If you have any questions or experienced problems please get in touch with the Bisq community at the Bisq Forum
> Bisq Forum ->
> 
> Thanks for using Bisq!

## Revised

> Congratulations on completing your trade
> 
> We'd love to hear back from you about your experience. It'll help us to improve the software and to smooth out any rough edges. If you'd like to provide feedback, please fill out this one-minute survey (no registration required) at https://bisq.network/survey.
> 
> If you have any questions, or experienced any problems, please get in touch with other users and contributors via the Bisq forum at https://bisq.community.
> 
> Thanks for using Bisq!

## Notes

I think it's better to spell out the URLs here, given that Bisq's status bar doesn't work like browser status bars. When I see a hyperlink, I almost always look at the status bar to see where I'm going before I click; there's no way to do that here. And in any case, it's good for the user to see the URL of the forum, so they can at least potentially remember it in the future, assuming they don't click now.

Manfred, notice how I've taken your first two sentences and collapsed them into a single paragraph. Previously they were separated by a newline. In written English prose, we have no such construct as separating sentences with a newline. It's paragraph->single blank line->paragraph, one after the other. This may seem like a small point, but it's actually big. I have a surprisingly hard time reading texts that you write with this kind of newline-separated sentence structuring. I've seen other German native writers do this too, so I believe it may be idiomatic in German, but it isn't at all in English, and it makes the reader's eye jump around, frantically wondering whether what they're reading is supposed to be one paragraph, a new paragraph, or something weirdly in-between. Generally, having read a lot of your writing, I think it's safe to say that where you're inclined to do a newline-separated sentence, just keep going on the same line and keep it in the same paragraph.

**Comment by ManfredKarrer** [comment]
Thanks @cbeams ! 
Yes I am aware of that bad behavior (bad habits are hard to get rid of ;-)). In fact in German - at least from my limited language expertise - it is usual to make line breaks to have something in between a full paragraph and the normal flow of sentences. For me it helps to orientate the eye in the longer flow of text...
