### ISSUE TITLE
keyPair

### ISSUE THREAD

**Issue by Jerrykro** [bisq-network/bisq#1596]
keyPair must not be null. If we got the addressEntry created from PB we need to have setDeterministicKey got called before any access with getKeyPair().

ajkroot@comast.net

**Comment by ManfredKarrer** [comment]
Did you restore from seed words? If not did you do anything special? That error usually comes when you restore from seed words. The internal wallet database will then not match. Restore is only for emergency cases but will not give you a working Bisq. You need to use a backup to restore the full state.

**Comment by Jerrykro** [comment]
I did not restore from seed. (I do have the seed.)

I was sending some of my BTC out. The program locked and I had to restore the program. When I restored the coins were gone. The backups that I have are not current.

**Comment by ManfredKarrer** [comment]
What do you mean with "restore the program"? Can you try to delete the SPV chain file at settings/network? Do you have an open offer/trade/dispute? If not you can try to use a backup and run from that. Backup your current data directory first...

**Comment by ripcurlx** [comment]
Closing because of lack of information. Feel free to re-open the issue if it is still ongoing.
