### ISSUE TITLE
Public Keys for signing bisq

### ISSUE THREAD

**Issue by isii092** [bisq-network/bisq#1598]
@ManfredKarrer 
Up till now you have been the one signing the new releases.
Can you confirm the other 2 public keys in the releases page?
Should we expect releases to be signed by these:
29CDFD3B.asc
5BC5ED73.asc

**Comment by ManfredKarrer** [comment]
Yes there are currently 3 possible signers (me, @cbeams  and @ripcurlx). The used signers is in https://github.com/bisq-network/bisq-desktop/releases/download/v0.7.1/signingkey.asc (@ripcurlx).

**Comment by ripcurlx** [comment]
Closing as complete.
