### ISSUE TITLE
0.7.1, osx: no bitcoin peers after computer suspend

### ISSUE THREAD

**Issue by osnwt** [bisq-network/bisq#1600]
Macbook Pro, 0.7.1. After computer resumes after suspended state, Bisq desktop does not reconnect to bitcoin peers (but reconnects to Tor peers):

<img width="1207" alt="resumed" src="https://user-images.githubusercontent.com/1081613/42417383-4551a21e-8291-11e8-9a4b-fd980322ab63.png">

Only app restart resolves it.

**Comment by ripcurlx** [comment]
Do you see this behavior every time you resume your computer?

**Comment by osnwt** [comment]
I think yes, at least, few times.
I will start it again and see if I have at least one time when it reconnects properly.

**Comment by osnwt** [comment]
Tried few times, sometimes it went out of sleep with few (3-1) BTC peers, and the number did not increase later. Finally it ends with 0 peers and never recovers. It is on Mac.

**Comment by ManfredKarrer** [comment]
I just tested with removing my network connection, lost all connections as expected, then reconnect and get all p2p and btc nodes back. No idea what causes the issue on your side.

**Comment by ManfredKarrer** [comment]
can u post a screenshot of the energy savings setting u use?

**Comment by ripcurlx** [comment]
Closing because of lacking follow-up information.
