### ISSUE TITLE
Tried to make a buy, somehow failed. Security deposit gone?

### ISSUE THREAD

**Issue by nilskp** [bisq-network/bisq#1602]
First time using Bisq. Tried to make a buy, which failed. What happened with security deposit?

**Comment by nilskp** [comment]
Looking at the Transactions tab, there are two transactions listed, one of them with Details: Error message: "A timeout occurred", and Trade state: TAKER_FEE_PUBLISHED.

**Comment by nilskp** [comment]
The amount is 0.03 BTC, so it's not exactly small change.

**Comment by nilskp** [comment]
Ok, I now see the security deposit in my wallet. This problem may have been related to upgrading to 0.7.1. I had to delete SPV file and resync.

**Comment by cbeams** [comment]
Thanks for following up Nils. Failed trades are relatively rare, sorry you had one as a first experience. If you’d like to be refunded for your lost trading fees, please open an issue in bisq-network/support with the trade ID, the maker, taker and deposit tx IDs from the `Details` tab as well as a screenshot of those three fields. Look at other open issues there for examples.
