### ISSUE TITLE
Add Hal Cash as payment method 

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1608]
Hal Cash seems to be a privacy protecting and fast payment method. It is popular in Spain and available in some other countries.
I think we should add it.
It requires 2 codes to withdraw the money form the ATM. 1 code is sent by the buyer and 1 code comes from Hal Cash.
The code can be sent as mobile message to the sellers phone.
The phone nr. is the only required data.

Here is video in Spanish explaining it:
https://www.youtube.com/watch?v=-X088uJN4pM

**Comment by alfsbs** [comment]
# Introduction
 
Hal Cash is an ATM cash withdrawal payment method popular in Spain and Poland
 
# Requirements verification
 
**Web**: Chargeback risk
**Chargeback risk**: None
**Privacy protection to other peer**: High
**Mandatory data for a transaction**: Mobile Nr.
**Duration**: Instant
**Region**: Spain / Poland
**Fees**: Depends on bank
**Verifiable**: TLSNotary
**Fraud risk**: Low
**Conclusion**: Include
 
# Implementation information
 
## Setting up National Currency Account
 
**Payment Method**: Hal Cash
**Mobile phone no.**: **
**Supported currencies**: EUR
**Limitations**: **
**Salt for account age verification**: **
**Account name**: **
 
## Create offer to buy BTC
 
**Enable use of Hal Cash
No other changes necessary.
 
## Create offer to sell BTC
 
**Enable use of Hal Cash
No other changes necessary.
 
## Buying/Selling BTC
 
The buyer of BTC only needs to know the mobile phone no. of the seller and he must send to the seller the code received from Hal Cash

**Comment by ManfredKarrer** [comment]
Here is a overview of Polish ATMs:
https://coinatmradar.com/manufacturer/45/poland-halcash-bitcoin-atm-producer/

Seems they will start soon in the US as well under a different brand (Pin4).

**Comment by ManfredKarrer** [comment]
Does anyone know what is the limit for a transfer and how the policy is (limit per day, limit per reciver,...) and if it is same in spain and poland?

**Comment by ManfredKarrer** [comment]
Implemented with:

https://github.com/bisq-network/bisq-common/pull/32
https://github.com/bisq-network/bisq-core/pull/144
https://github.com/bisq-network/bisq-desktop/pull/1619

**Comment by ManfredKarrer** [comment]
Here are the screens:
Can anyone cross check if all is correct?

<img width="1200" alt="screen shot 2018-08-10 at 22 10 16" src="https://user-images.githubusercontent.com/1449498/43979759-108b8354-9cec-11e8-92de-882e67a7c6d5.png">
<img width="1200" alt="screen shot 2018-08-10 at 22 10 32" src="https://user-images.githubusercontent.com/1449498/43979760-10a7693e-9cec-11e8-9c06-a0e71605ab97.png">
<img width="1193" alt="screen shot 2018-08-10 at 22 14 57" src="https://user-images.githubusercontent.com/1449498/43979761-10c2cf8a-9cec-11e8-9ce0-5f6475f2bfb2.png">
<img width="1197" alt="screen shot 2018-08-10 at 22 15 03" src="https://user-images.githubusercontent.com/1449498/43979762-10dc0a7c-9cec-11e8-8382-0140d8caca6e.png">
<img width="1198" alt="screen shot 2018-08-10 at 22 15 17" src="https://user-images.githubusercontent.com/1449498/43979763-10f4fc26-9cec-11e8-96b2-09e5cd8d4665.png">
<img width="1200" alt="screen shot 2018-08-10 at 22 15 43" src="https://user-images.githubusercontent.com/1449498/43979764-110c296e-9cec-11e8-9f14-b1efe248a3f7.png">

**Comment by alfsbs** [comment]
**Trade limits**: min 10 EUR, max 600 EUR. (per withdrawal), and 3000 EUR / receiver / day, and 6000 EUR / receiver / month.

**Trade amount**: There is an issue with regards to amount, min unit is 10 EUR (or multiples). We can limit this PM for fixed offers or if it's possible we can make offers to round up to the closest 10 EUR multiple.

**Time limit** With regards to time limit, there is a maximum time of 10 days for the operation, so we could leave some more time for the trade, so that there is less risk of disputes.

**Comment by ManfredKarrer** [comment]
Thanks @alfsbs !
Good finding with the issue of a multiple of 10 EUR! Not having a good solution for that beside what you recommend. I will add a text in the info popup to tell users.

**Comment by ManfredKarrer** [comment]
I will add a check in the make offer screen as well to avoid that users can create an offer which is using % based price and an amount which is not a multiple of 10 (rounded).

**Comment by ManfredKarrer** [comment]
I will disable market based price and auto adjust the EUR amount of multiple of 10 EUR.
  
Here is the popup info text when creating an account:

When using HalCash the BTC buyer need to send the BTC seller the HalCash code via a text message from the mobile phone.\n\n\
  Please make sure to not exceed the maximum amount your bank allows you to send with HalCash. \
  The min. amount per withdrawal is 10 EUR and the max. amount is 600 EUR. For repeated withdrawals it is \
  3000 EUR per receiver per day and 6000 EUR per receiver per month. Please cross check those limits with your \
  bank to be sure they use the same limits as stated here.\n\n\
  The withdrawal amount must be a multiple of 10 EUR as you cannot withdraw other amounts from an ATM. The\
  UI in the create offer view will adjust the BTC amount so that the EUR amount is correct. You cannot use market \
  based price as the EUR amount would be changing with changing prices.\n\n\
  In case of a dispute the BTC seller need to provide the proof that he sent the EUR.

**Comment by ManfredKarrer** [comment]
I updated the PRs...

**Comment by ManfredKarrer** [comment]
@ripcurlx We can use the same logic as implemented here for applying non-decimal fiat amounts.
It would just change that it is not divided by 100000 then rounded and then multiplied by 10, but divided by 10000 and then rounded.
We can make the methods then more generic to use it for both HalCash and normal Fiat.

**Comment by jbarcelo** [comment]
Isn't it possible for the creator of an offer to set a range of the amount of BTC to be traded? Like 0.01-0.02 BTC. If this is possible, it could be the taker of the offer the one that (at the time of taking the offer) makes sure that the amount traded (in euro) is a multiple of 10 EUR. In this case it would be possible to create offers as based on a % of the market price.

**Comment by ripcurlx** [comment]
@jbarcelo The only problem is that if we can't enforce this, we'll might have unnecessary arbitration cases. Having a different kind of volume selection for the taker based on the trade amount in Euro could be a way to go, but this will need more UI changes in the interface.

**Comment by jbarcelo** [comment]
@ripcurlx Right. I understand.

**Comment by ManfredKarrer** [comment]
@jbarcelo Yes the app in the taker screen makes sure to get the EUR amount round to 10 EUR in case there is a range. You are right it might be able to support still % based offers if there is a sufficiently large range, though it makes it a bit more complicate. I would prefer to keep it simple now and see first how much it will be used. We would need to require a min range to be able to find a volume with resolves to a 10 EUR amount, with diff. prices that range would change so its not trivial to implement that correctly... but if we get good volume with Halcash trades we can add that in the next release.

**Comment by jbarcelo** [comment]
@ManfredKarrer I agree. I would recommend a minimum range of 10 mBTC which currently is around 50 EUR. As long as BTC stays above 1000 EUR, a range of 10 mBTC ensures that there is at least one possibility to take the offer for an amount that is a multiple of 10 EUR.

In the unlikely case that BTC dropped below 1000 EUR, it would no longer be possible to take some of the Hal Cash offers ... but that would not be the end of the world. Wise users would simply set a wider range.

**Comment by ManfredKarrer** [comment]
Yes its definitely possible, just not trivial to implement. I prefer to keep the effort lower atm, the 10 EUR requirement had already taken more time as I wanted to spend on it. Often new payment methods are not used at all (WU, Moneygram,....). So lets see first if there is demand for it. I don't think that not having a % based option is a show stopper for not using HalCash. Or do you think that is the case? 
Btw. Anyone is welcome to implement that, thought the code base for that is not trivial, so its not a low hanging fruit task...

**Comment by jbarcelo** [comment]
I totally agree with you @ManfredKarrer . Right now developer hours are the bottleneck and they should be used wisely for the most critical tasks. I wish I could learn and help, it's just that I don't know where to start XD. Even the "low hanging fruits" such as adding halcash support seem like impossible for me XD.

**Comment by jbarcelo** [comment]
@ManfredKarrer, a somewhat unrelated comment. I was looking at the screenshots and the pop-up says "In case of a dispute the BTC seller need to provide the proof that he sent the EUR" ... Am I wrong or it is the BTC buyer the one that has to send the EUR?

Should it read "In case of a dispute the BTC *buyer* need*s* to provide the proof that he sent the EUR"?

**Comment by ManfredKarrer** [comment]
Ah thanks. Yes you are right, the buyer is the sender of EUR.

**Comment by ManfredKarrer** [comment]
Fixed.

**Comment by ripcurlx** [comment]
Already live in https://github.com/bisq-network/bisq/releases/tag/v0.8.0.

Closing as complete.
