### ISSUE TITLE
Add popup if user has non-english language

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1612]
If the user has a non-english language selected (or default selected because the OS is in another language) we should display a popup to tell the user that the arbitrators are english-only atm.

That popup can be displayed in 3 situations:
- When selecting another language in settings
- When making an offer (only if no language match)
- When taking an offer (only if no language match)

The arbitrator selection is language based, so if we have one day other languages supported by arbitrators we can detect that by checking the supported arbitrator field in the offer and only display the popup if there is no match of arbitrator's language and user's language.

We should add that to the next release and translate the popup text to all yet supported languages!
We need to push the translators to translate that with high priority to get it into the release.

Suggested text in context of offers:
Please be aware that in case of a dispute the arbitrator(s) selected for that offer are not capable of {0}. The language(s) used in case of a dispute is: {1}

Suggested text when switching language in settings:
Please be aware that in case of a dispute the available arbitrator(s) are not capable of {0}. The language(s) used in case of a dispute would be: {1}

{0} -> users language. E.g. "French"
{1} -> arbitrators language(s). E.g. "English, German"

@m52go @ripcurlx 
Please feel free to improve the suggested text...

**Comment by m52go** [comment]
Simplified a bit, hopefully not too much!

Suggested text in context of offers:
In case of a dispute, please note that arbitration for this offer will be handled in {1}. Language is currently set to {0}.

Suggested text when switching language in settings:
In case of a dispute, please note that arbitration is handled in {1}.

**Comment by ManfredKarrer** [comment]
@m52go Thanks!

**Comment by ripcurlx** [comment]
@ManfredKarrer For the language selection I would show the warning popup everytime (no "don't show again") and for the take and make offer warning I'll add the "don't show again" option as it would be super annoying if you trade a lot.

**Comment by ManfredKarrer** [comment]
Good point. will change that.

**Comment by ripcurlx** [comment]
I just wanted to implement the warning for take and make offer as well, but it is not 100% clear at what point of the journey we want to inform the user.
![bildschirmfoto 2018-08-14 um 11 35 09](https://user-images.githubusercontent.com/170962/44084192-62130eaa-9fb6-11e8-87bc-a821911f7e4e.png)
The early warning would be when the user clicks on `Take offer` or `Create new offer to ...` the late one in the confirmation screen.
![bildschirmfoto 2018-08-14 um 11 35 31](https://user-images.githubusercontent.com/170962/44084273-8c91d31e-9fb6-11e8-84ff-3d19f669a670.png)
I personally would go for the early warning as the user already has transfered/locked some BTC when clicking on Confirm. @ManfredKarrer @m52go Any preferences?

**Comment by ManfredKarrer** [comment]
@ripcurlx Yes agree, the earlier the better.
