### ISSUE TITLE
java.lang.NullPointerException v8.0

### ISSUE THREAD

**Issue by cadayton** [bisq-network/bisq#1618]
On Linux Mint 19 system without a webcam a null pointer error was return after clicking on the QRcode button in the Notification dialog.
[bisq.log](https://github.com/bisq-network/bisq-desktop/files/2272459/bisq.log)

**Comment by ManfredKarrer** [comment]
Note for myself:
Aug-08 17:37:00.415 [Thread-27] INFO  c.g.s.w.Webcam: WebcamDefaultDriver capture driver will be used 
Aug-08 17:37:00.785 [Thread-27] WARN  c.g.s.w.Webcam: No webcam has been detected! 
Aug-08 17:37:00.786 [Thread-27] ERROR b.c.s.CommonSetup: Uncaught Exception from thread Thread-27 
Aug-08 17:37:00.786 [Thread-27] ERROR b.c.s.CommonSetup: throwableMessage= null 
Aug-08 17:37:00.786 [Thread-27] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.NullPointerException 
Aug-08 17:37:00.788 [Thread-27] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.NullPointerException
	at bisq.desktop.main.account.content.notifications.WebCamLauncher.run(WebCamLauncher.java:48)

**Comment by ManfredKarrer** [comment]
Fixed: https://github.com/ManfredKarrer/bisq-core/commit/2a4bde8c427106f06879af37c41fcd3d592a32c0
