### ISSUE TITLE
Not generating key

### ISSUE THREAD

**Issue by boyofbow** [bisq-network/bisq#1643]
Since update to v 0.08.0 Not generating key box when trying to open  bisq. So takes me straight to new account

**Comment by boyofbow** [comment]
Can login now but bitcoin and dispute gone

**Comment by ManfredKarrer** [comment]
Can you send me the logs (manfred at bitsquare dot io). can u check the data directory and see if there is a "corrupted files" folder inside the db folder? here is a screenshot with all sub dirs inside the data directory folder opened so i can see how it should look like.
<img width="260" alt="screen shot 2018-08-26 at 10 41 15" src="https://user-images.githubusercontent.com/1449498/44626441-a65b9b80-a91c-11e8-9dea-cdad3cb23f01.png">

**Comment by ripcurlx** [comment]
It looks like @ManfredKarrer and @boyofbow handled that over a different channel so I'm closing this issue as complete. Please re-open it if it's not the case.
