### ISSUE TITLE
Payment method information popup display time is rather short (~5 seconds)

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#1644]
I'm not sure this should be considered as an issue,
but, in the buy BTC tab or sell BTC tab, the Payment method information popup (i) display time is rather short (~5 seconds).
When the displayed informations are numerous, eg sometimes for F2F, 5 seconds is not enough to read the whole text.

**Comment by ManfredKarrer** [comment]
What do u mean with display time? The popups should not close automatically. If so there is a bug.

**Comment by ghost** [comment]
It's on a Debian 9.5 updated. Bisq v0.8.0.
When the pointer is on the (i), the popup displays nicely its message, but closes after 5 seconds
I verified on 2 different machines, all Debian 9.5, and this happens on both.

I also verified on a Debian 9.5 with Bisq v0.7.1, and this happens also.
The popup displays its message, 5 seconds, and bye.
(good training to read fast !)

btw, the display time is the same for the popup which displays when the pointer is on the little icons representing the trader/maker. "Maker's onion address, blah blah ... " 5 seconds, and hop it's gone.

**Comment by ManfredKarrer** [comment]
Ah you mean the rollover popup. I though of the normal popups. Yes there is a timeout. I am not sure if it is based on the ToolTip and if that is easy to change. @ripcurlx might know....

**Comment by ghost** [comment]
As said, it's certainly not a great issue, if it is one at all.
It's just that 5 seconds may seem quite short ... at least for some (slow) people (like me).

**Comment by ghost** [comment]
btw, in the same "buy BTC" tab, the price column has also rollover popups ("you'll pay 5.00% more ...") and those popups with just 2 similar lines of text don't close.
While the rollover popups in the payment methods column may have 7 lines of varying text, but close after 5 seconds.

**Comment by ManfredKarrer** [comment]
We just increased the display from 4 to 6 sec.
