### ISSUE TITLE
You must have bootstrapped before adding data to the P2P network.

### ISSUE THREAD

**Issue by spottedmarley** [bisq-network/bisq#1645]
I have been receiving this error message any time I startup Bisq lately. I have no idea what it means but it asked me to report it here. Here is the message that was copied to my clipboard...

You must have bootstrapped before adding data to the P2P network.

I haven't done anything new.. although I recently opened a support ticket for the first time.. it went fine, no issues, but now whenever I launch the Bisq client I get this error message. Should I worry about the status of my accounts or trades or anything like that?

I've attached the log file as instructed in the error dialog.
[bisq.log](https://github.com/bisq-network/bisq-desktop/files/2321984/bisq.log)

Thanks
SM

**Comment by ghost** [comment]
The number of bitcoin peers and Bisq peers are displayed left and right in the Bisq appli bottom bar.
What are those numbers for you ?

**Comment by ManfredKarrer** [comment]
Should be fixed with https://github.com/bisq-network/bisq-p2p/pull/20

@spottedmarley Just click OK for now. with next release that should be fixed. Hope the error popup goes away by itself once your app boots up faster.

**Comment by ManfredKarrer** [comment]
If you still have issues please let us know. I will close for now as I expect its resolved.

**Comment by huey735** [comment]
@ripcurlx I have come across a new instance of this issue. The user reported

>when i started aplication - after entering the password that is received, an error pops up - "you must have bootstrapped before adding data to the p2p network

![bisq warning](https://user-images.githubusercontent.com/44140017/107277081-dabf6580-6a4b-11eb-98d0-4a767c9b7958.png)

**Comment by chimp1984** [comment]
Can you request log files?

**Comment by huey735** [comment]
I have and I'll sent them to you @chimp1984
