### ISSUE TITLE
Suggestion for in app receipt upload for cash deposits.

### ISSUE THREAD

**Issue by gibechoes** [bisq-network/bisq#1648]
Is it possible to enable image to be uploaded in app and sent to peer direct to proof of deposit?
Email is not guaranteed secure,  pgp is not mainstream and cant rely on all users to know to use.
Also more convenient if in app. What would load on bisq p2p network be, could limit size of images to under 100k?

**Comment by ManfredKarrer** [comment]
Yes would be a nice feature, but current dev resources are all occupied with other higher prio stuff. But any dev is welcome to add that.
