### ISSUE TITLE
Signature of 0.8.0 release = christoph.atteneder@gmail.com, not from a bisq.network address?

### ISSUE THREAD

**Issue by Emily7777** [bisq-network/bisq#1664]
Is this an authorized signator of this project?

**Comment by ghost** [comment]
Yes he is.
Christoph Atteneder managed the last release (v0.8.0).

Here’s the result in CLI:
$ gpg --fingerprint 29CDFD3B
pub rsa4096 2017-07-27 [SC] [expires: 2021-07-27]
CB36 D7D2 EBB2 E35D 9B75 500B CD5D C1C5 29CD FD3B
uid [ unknown] Christoph Atteneder christoph.atteneder@gmail.com
sub rsa4096 2017-07-27 [E] [expires: 2021-07-27]

**Comment by ManfredKarrer** [comment]
We don't use bisq.network for email addresses.
