### ISSUE TITLE
Hide paring token (contains encryption key)

### ISSUE THREAD

**Issue by joachimneumann** [bisq-network/bisq#1666]
The pairing token that is used to pair a mobile phone with the Bisq desktop app contains (amongst other things) the encryption key in clear text. This key is visible in the GUI and stays visible when the user re-opens the notification tab.

I propose to hide the pairing key and only display it when the user presses a "show" button.

I am not sure how the screen should look like before pairing, may be instead of the "show" button a text "not paired". Here a first proposal to hide the pairing token:

<img width="1680" alt="screen shot 2018-09-08 at 21 43 33" src="https://user-images.githubusercontent.com/5642225/45258039-ead14780-b3b0-11e8-8dee-3dc400decd58.png">

**Comment by ManfredKarrer** [comment]
@joachimneumann Is the encryption key the third or the forth token in the string? If the forth it is cut off anyway so I would not consider that critical. But of course to add a "password"-like hiding function might be an option as well. Just not sure if it adds more confusion as it actually benefits.

**Comment by joachimneumann** [comment]
The encryption key is the third item in the string and therefore visible.
However, I agree that this is not super urgent and we might have to think a bit more about 
how to present the token without creating confusion.
Should we postpone this issue to a later point of time?

**Comment by ManfredKarrer** [comment]
Yes, I would prefer to postpone it. We can leave it open and i put label was:deferred on it.
