### ISSUE TITLE
Add Skrill, Neteller & PayPal support

### ISSUE THREAD

**Issue by fraktar** [bisq-network/bisq#1672]
Hodlhodl has more options currently. It would be nice to offer those as well.

**Comment by ManfredKarrer** [comment]
PayPal has super high chargeback risks, so that is no-go.

**Comment by fraktar** [comment]
> PayPal has super high chargeback risks, so that is no-go.

I know, I grossly dislike PP too but I thought that would attract more users. 

If not, at least Skrill/Neteller would be worth a shot imho.

**Comment by ManfredKarrer** [comment]
I think @alfsbs had some good reasons why both are not on the list of payment methods we are considering to get added. I think as far I remember both had quite a high scam-rate from some basic investigations.

**Comment by alfsbs** [comment]
@fraktar Skrill has a too lose chargeback policy, over our risk bar: https://www.skrill.com/en/footer/terms-conditions/skrillaccounttermsofuse/
With regards to Neteller, it has a reputation for blocking accounts, high fees and low volume of users, so we are not considering it yet. 
As we are a DEX we have to support only payment methods that ensure trust for the BTC sellers, until we are able to provide guarantee by other means.
Hopefully we can carry on your next request. Thanks for collaborating!

**Comment by ManfredKarrer** [comment]
Thanks @alfsbs for the comment. I will close the issue.
