### ISSUE TITLE
Using clean with gradle build breaks project build form IntelliJ

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#168]
I got problems with repeated builds from gradle. Using "./gradlew clean build" would solve that problem but then the build inside IntelliJ is broken. 
I get a nullpointer as images cannot be loaded, but the images are in place.
A project rebuild inside IntelliJ fixes it again.

Is there a task which only builds the jar file without the binaries (which takes more time)?
The "check" task should be enough for testing if the project has no build errors, right?

**Comment by cbeams** [comment]
looking into this now.

**Comment by cbeams** [comment]
Manfred, I'm working against current master (655c9fb), and trying the following steps to reproduce your problem:
1. `./gradlew clean build`
2. In IDEA, Open the `BitSquare` class and run its `main` method. Note I do not have any special settings in the Run Configuration for this class.

When I run the main method, Bitsquare comes up cleanly, with all its images and I do not see any exceptions.

Note that I also blew away my data directory with `rm -rf ~/Library/Application\ Settings/Bitsquare*` before trying this as well, just to be safe, make sure there weren't serialization issues, etc.

Can you provide more specific reproduction steps?

In the meantime, yes, there are other gradle tasks you can run, depending on what you want to do.
- `./gradlew jar` will compile everything and build the bitsquare jar file (though I'm not sure what good that would do)
- `./gradlew test` will compile everything and run all tests

There's more. You can take a look at the output of `./gradlew tasks`, take a look at the [Tasks section of the Gradle plugin documentation](http://www.gradle.org/docs/current/userguide/java_plugin.html#N11F86), and more generally you might be interested to get familiar with the [Gradle build lifecycle](http://www.gradle.org/docs/current/userguide/build_lifecycle.html) (though not at all critical to understand for your current question).

I'll assign this issue back to you for further feedback on reproduction steps.

**Comment by ManfredKarrer** [comment]
@cbeams: Thanks for looking into it and for the comments!
So "./gradlew test" should be fine as check before pushing to github.

As soon as I run again into the issue I will try to find how to reproduce it. I use the latest Intellij version (updated recently) but don't think its related...

**Comment by cbeams** [comment]
Closing, sounds like this is worked out. Please re-open if not.
