### ISSUE TITLE
TTMD

### ISSUE THREAD

**Issue by JECollier** [bisq-network/bisq#1681]

**Comment by ManfredKarrer** [comment]
What is the content of that issue?

**Comment by JECollier** [comment]
I am sorry as I am new to the crypto market.  I am participating in a new token "TTMD" and was told that we are in the next round of tokens to be taken live on BISQ and was trying to find something to support that position. I would appreciate any assistance.

**Comment by ManfredKarrer** [comment]
Adding altcoins is on halt atm.

**Comment by ManfredKarrer** [comment]
Adding altcoins is on halt atm. 
See: https://docs.bisq.network/exchange/howto/list-asset.html
