### ISSUE TITLE
Fix performance issues with Java 10 version of ProgressIndicator 

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1692]
Continuing the discussion from https://github.com/bisq-network/bisq/pull/1660#issuecomment-422477534

@ripcurlx :
> I have a question regarding the Status Indicator. Actually besides extending a different base class the only thing I need to change was in the constructor to replace

It was more, but don't remember the details. Reduced framerate of animation, etc. the Indicator is pretty crappy, how can it be that a small spinner takes 5% cpu? If you have a small demo app with 20 spinners in animation you will see. Earlier we had the Indicator in animation mode for showing 0 confirmation transactions but that started to kill CPU once you have several transactions with 0 confirmation listed.

To see the differences one need to compare the original java fx files which got replaced by the 2 which have been deleted in the Java 10 change.

**Comment by ManfredKarrer** [comment]
Here is a testapp:
```
public class ProgressIndicatorTestApp extends Application {
    @Override
    public void start(Stage stage) {
        FlowPane root = new FlowPane();
        FlowPane pane = new FlowPane();

        Button add = new Button("add");
        add.setOnAction(actionEvent -> {
            pane.getChildren().add(new ProgressIndicator());
        });

        Button remove = new Button("remove");
        remove.setOnAction(actionEvent -> {
            pane.getChildren().clear();
        });

        root.getChildren().add(add);
        root.getChildren().add(remove);
        root.getChildren().add(pane);

        Scene scene = new Scene(root, 300, 200);

        stage.setScene(scene);
        stage.show();
    }
}
```

**Comment by ManfredKarrer** [comment]
One indicator consumes about 7-11% on my imac. Adding more adds  about 2% but has heavy spikes.

**Comment by ManfredKarrer** [comment]
@devinbileck If you have an idea about how to either fix that or to find a nice alternative, that would be rather high-prio to get into the upcoming release with the redesign.
We could either use the same approach with the old version before we upgraded to Java 10 (overwriting and changing the base classes to mitigate most of the performance issues) or replace the indicator with a new component. Unfortunately JavaFX seems to be not well designed for animations, such a small re-rendering should never cost so much CPU...

**Comment by devinbileck** [comment]
Sure I will take a look, but cant guarantee much at this point ;)

**Comment by ripcurlx** [comment]
Still relevant
