### ISSUE TITLE
Add info for Faster Payment that the receivers name is not required

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1693]
As discussed here we add info for Faster Payment that the receivers name is not required.

"Some banks might require the receivers name. The UK sort code and account number is sufficient for a Faster Payment transfer and the receivers name is not verified by any of the banks."

<img width="1196" alt="screen shot 2018-09-18 at 17 30 51" src="https://user-images.githubusercontent.com/1449498/45720171-d8050280-bb68-11e8-9e98-02ce4e5928ec.png">

**Comment by ripcurlx** [comment]
Closing as complete.
