### ISSUE TITLE
If app is not well connected trade state can become invalid

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1699]
Here is the message from Slack:

Hello, there was a technical issue in the F2F trade in Zurich today. Both parties opened a support ticket but I thought I should mention it here as well. When the buyer pressed "make a payment" button, an error message showed up saying that he did not seem to be connected over Tor even though he was connected to one peer. He was not able to go back to press the "make a payment" button again.  On my end, it said "Waiting until the payment is confirmed". He shut down outdated Tor files (which took some time) but that did not help. In the end, the trade has not occurred. He sent some attachments with the ticket, but I can also ask him to send the original error message if needed. I hope this makes sense.

**Comment by ManfredKarrer** [comment]
Investigated that case but could not reproduce it.

**Comment by ripcurlx** [comment]
@ManfredKarrer Shall we close this ticket until this problem is re-produceable or happening again?

**Comment by ManfredKarrer** [comment]
I leave it to you...

**Comment by ripcurlx** [comment]
Closing ticket as not reproducable.
