### ISSUE TITLE
Integrate User Guide as in-app help system

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#170]
As mentioned at https://github.com/bitsquare/bitsquare/issues/63#issuecomment-58250757, the plan is to rework the Bitsquare UI to link to _How-To_ sections specific to the screen or activity that the user needs help with.

The docs shall published on a version-by-version basis, so regardless the version of Bitsquare the user is using, they'll always be referred to the correct documentation. See #169 for details (which this issue depends on in order for work to begin).

**Comment by ManfredKarrer** [comment]
To use a simple web link and let it open in the browser seems the better solution instead of a an in-app help. We wull use http://docs.bitsquare.io/ and need to customize the anchors to the sub sections.
