### ISSUE TITLE
OSX App Nap mode causes Bisq to lose network connections

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1701]
It seems that Apple changed the behavior of standby mode so that network connections get lost while in standby mode (even if only display is set to sleep).

This is pretty bad as if you have offers open those offers will get removed when your Bisq app is running but has no network access. I am not 100% sure how it is handled as it seems that only the P2P nodes get disconnected but not the Bitcoin nodes. So it might be some special handling for limiting the resources and not completely preventing network activity.

What is really annoying that there is zero information about those hidden behaviors (experienced similar issues with the iOS notification app). It is really a shame how Apple developed over the last years. Time to move to Linux....

Here is one of the few discussion about that issue: 
https://forums.macrumors.com/threads/mac-looses-connection-when-sleeping.1414285/

Here are the settings I use.
<img width="665" alt="screen shot 2018-09-19 at 14 39 59" src="https://user-images.githubusercontent.com/1449498/45776897-eb23db00-bc19-11e8-93a6-58d8d6f9686b.png">

Does anyone has an idea how to solve that?

Seems that app "Caffeinate" is build so solve that issue, testing it out now (costs 2 USD).

Maybe putting the display into lock screen by ctrl-shift-eject and leave the standby setting to never helps as well as one user posted in the link above:
"You can put just the display to sleep (ctrl-shift-eject does this). This will turn off the display and conserve power whilst still keeping the Mac turned on and thus the network connection(s)."

**Comment by ManfredKarrer** [comment]
Seems both approaches (Caffeinate, ctrl-shift-eject) did not help. Also I observed that when I have Bisq open but not as active window network connections drop, at least when I bring it in foreground more offers get quickly displayed in the spread screen.

**Comment by ManfredKarrer** [comment]
App Nap causes the issues:
https://www.lifewire.com/control-how-mac-applications-use-app-nap-2260788
https://apple.stackexchange.com/questions/121386/missing-prevent-app-nap-button-on-app

Run that command in the terminal and restart Bisq. It should never end up in App Nap mode with that and therefore not lose network connectivity when not visible (hidden by other windows).
```
defaults write io.bisq.CAT NSAppSleepDisabled -bool YES
```

It would be good if we find a way that App Nap is disabled by default for Bisq. Will search more for the java packager options.

**Comment by ManfredKarrer** [comment]
With further research it should be able to deactivate AppNap with `<key>LSAppNapIsDisabled</key><string>True</string>` in the Info.plist file. That is also as it is done in Bitcoin Core.

**Comment by ManfredKarrer** [comment]
I tried with binaries with both those keys added to Info.plist but unfortunately it does not help once monitor is in standby mode. 
 ```
<key>NSAppSleepDisabled</key><true/>
 <key>LSAppNapIsDisabled</key><true/>
```

The only working solution so far is using `defaults write io.bisq.CAT NSAppSleepDisabled -bool YES`.
The actual value can be read with `defaults read io.bisq.CAT NSAppSleepDisabled`.

**Comment by ghost** [comment]
This comment is not about OSX etc. Apologies.
I however jump in to signal that the number of offers significantly varying is something I observed at least 2 months back. 
1/ Same machine, same OS, behind same IP. PC A displays 110 orders, and PC B displays 130 orders.
2/ Or, on the same machine, you run Bisq and it displays 110 offers. You shut down, relaunch, and hop there are now 130 orders.
As if the appli may get stucked with a bunch of peers where the offers don't circulate well.

**Comment by ManfredKarrer** [comment]
From Apple developer docs:
An app is considered to be a candidate for sleep if:
- It is not visible—if all of an app’s windows are either hidden by other windows or minimized in a hidden dock, and the app is not in the foreground
- It is not audible
- It has not explicitly disabled automatic termination
- It has not taken any power management assertions

When all of these conditions are met [...] the app is placed on a scheduling queue that rarely gets actual time on the CPU. The app wakes up automatically when the user brings the app to the foreground or when the app receives a Mach message or Apple event.

Tried NSDisableAutomaticTermination both as Info.plist as well as written to default but did not help.

Maybe the easiest hack it to play an inaudible sound file?

**Comment by ghost** [comment]
If I remind properly, there's on average a new offer every 30'.
Could play a little sound each time it happens ? and for other small events (losing peer, gaining peer) ?
Could be deactivated by the user, but deactivating meaning only volume=0, but still the sound being played.
This would allow the thing to be also a bit useful.

**Comment by ManfredKarrer** [comment]
Did a test with a sound file endless loop with volume set to 0 and that helps to prevent standby mode. 
We could add a checkbox to disable that in the settings if a user wants to get Bisq in standby mode.
@ripcurlx @cbeams What do you think? Its a bit of an ugly hack but seems Apple does not support it without adding Objective C code or setting it by the user.

**Comment by cbeams** [comment]
I guess this is only happening on newer versions of macOS? I'm still on Sierra (10.12.5) and I'm not having any problems.

You mentioned earlier that Bitcoin Core uses the `LSAppNapIsDisabled` plist setting to solve this. Is it also not working for them? Might be worth asking around there. I'd be surprised if they resorted to playing a silent sound file to solve the problem.

**Comment by ripcurlx** [comment]
I guess lots of things changed on macOS since `LSAppNapIsDisabled` was introduced to Bitcoin Core  (Commit on Oct 4, 2014) https://github.com/bitcoin/bitcoin/commit/1f9be984db13e9bed98d2aadb8f0577a2057f7cc#diff-5fdfe8cc3c56a1deb4896e4532024326

I'll have a look if I find something else or if we have to go with the play sound solution.

**Comment by ManfredKarrer** [comment]
@cbeams The introduced AppNap in earlier versions already but might have been changed in the under the hood behavior. I have Sierra but observed that issues since a while (prob. when I updated). 
I tested yesterday and could reproduce it when having Bisq with offers online on my iMac, then let it go in standby (monitor only), then try to take that offer from my laptop. The first few minutes it worked, afterwards it could not connect to the user anymore. The offer stayed online longer. Might be that offer republishing still works more or less. I think its not very deterministic behavior but rather limiting resources. Could also be related to other system environment (e.g. you have many apps open, etc.). With the sound keeping playing silently all worked (left it over night and the laptop could connect to the iMac Bisq apps offers).

It seems that `LSAppNapIsDisabled` and `NSAppSleepDisabled` are not supported anymore. At least it did not pass my test scenarios.
Only alternative way what worked was to use `defaults write io.bisq.CAT NSAppSleepDisabled -bool YES` but I don't know a easy way how we can trigger that from the app. It need to be done before the app starts, so it is probably impossible to do that from the java app. So only way would be to tell users to run that command, but I prefer to handle it automatically without annoying the user with any extra steps. 

I have seen some issue at Bitcoin Core where they discussed to fall back to an alternative solution (but did not find the link anymore, will search again). I think they have the option to call a OSX system call directly. We could do that probably as well but that would introduce native code, which I prefer to avoid.

Playing the sound might be also useful for other OS standby behaviors, I assume at least Windows will have or will add in future similar stuff (as for laptops on battery App Nap is a useful feature). For Bisq users we should note that they should not leave Bisq running on a laptop on low battery, but I think most will not do that anyway...

Btw. the play sound code is pretty simple:
```
            URL resource = getClass().getResource("/test.aiff");
            MediaPlayer mediaPlayer =new MediaPlayer(new Media(resource.toString()));
            mediaPlayer.setOnEndOfMedia(() -> mediaPlayer.seek(Duration.ZERO));
            mediaPlayer.setVolume(0);
            mediaPlayer.play();
```

**Comment by ManfredKarrer** [comment]
https://github.com/bitcoin/bitcoin/issues/11896#issuecomment-352148399

https://developer.apple.com/library/archive/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/AppNap.html

"If an app isn’t performing user-initiated work such as updating content on screen, playing music, or downloading a file, the system may put the app in App Nap."

"For any app that's not performing important user work, App Nap triggers a number of measures, including: Priority reduction, which reduces the process priority of the app so it receives a smaller share of available processor time Timer throttling, which reduces the frequency with which the app’s timers are fired I/O throttling, which reduces the rate at which the app can read or write data from a device while foreground apps need the device"

Seems the way to do it correctly is as here:
https://developer.apple.com/library/archive/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/PrioritizeWorkAtTheAppLevel.html#//apple_ref/doc/uid/TP40013929-CH36-SW3 but that will require that we add OSX native code.

**Comment by ManfredKarrer** [comment]
App Nap issues on Bitcoin Core:
https://github.com/bitcoin/bitcoin/issues?utf8=%E2%9C%93&q=App+Nap

Here is the code they plan for v0.18
https://github.com/bitcoin/bitcoin/commit/192b9e720fc1c017fb9a50aaa0e01c853283b73d#diff-fb062075fca1fb9af26602d3bbaa7c96
https://github.com/bitcoin/bitcoin/commit/192b9e720fc1c017fb9a50aaa0e01c853283b73d

**Comment by ManfredKarrer** [comment]
My previous overnight test with running sound -> AppNap might have been incorrect as I run it from the IDE. Need to re-test with with a binary as it seems it behaves different. ;-(

**Comment by ManfredKarrer** [comment]
The JavaFX media player consumes a lot of CPU (100%) even if idle. I used old swing style code which consumes no visible extra cpu (Bisq in idle is about 2%) with that. 
The sound file we use is filled with white noise at a very low volume which is not audible at even pretty high speaker volume. Using complete silence does not work as the OS detects that there is no audio.

I am aware that this is a hack, but there are quite a few arguments to go that path and not use the official way (https://developer.apple.com/library/archive/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/PrioritizeWorkAtTheAppLevel.html#//apple_ref/doc/uid/TP40013929-CH36-SW3 ).

- It would introduce native OSX code which complicates build process
- We don't have any expert in that area (OSX native). 
- The official way will only work for AppNap not preventing sleep mode. 
- It might be also that Apple changes the behavior or API as they did in the past. 
- Other OS might have already or might add in future similar features like App Nap and playing a sound is likely helping there as well to prevent that Bisq gets set to sleep mode or App Nap (low resources) mode.

I added a checkbox in the settings to deactivate that playing of the silent sound and allow standby mode, so for users who want explicitly allow standby mode it can be set. 

<img width="1198" alt="screen shot 2018-09-21 at 14 38 23" src="https://user-images.githubusercontent.com/1449498/45903467-6e2a6a00-bdaf-11e8-9cc6-ff6a9d77c431.png">

**Comment by ManfredKarrer** [comment]
Here some test in activity monitor with the option disabled and enabled:

<img width="1366" alt="screen shot 2018-09-21 at 15 03 32" src="https://user-images.githubusercontent.com/1449498/45903505-9023ec80-bdaf-11e8-88f1-0602224de8d6.png">

<img width="1381" alt="screen shot 2018-09-21 at 15 03 49" src="https://user-images.githubusercontent.com/1449498/45903507-9023ec80-bdaf-11e8-860c-a627aa7104f1.png">

I tested it also with running it over night and all worked as expected.

**Comment by ripcurlx** [comment]
Closing as complete.
