### ISSUE TITLE
Window "Trading wallet is sufficiently funded" appears for too short a time

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/bisq#1704]
When transferring funds from a Bisq wallet during a trade setup, the window which states that "Trading wallet is sufficiently funded" appears for a few seconds and closes on its own. It is hard for a first time user to see this small window on the upper right corner and to react to it. 

Suggestion: either keep it for a longer period of time or allow the user to close it him/herself since there is already a "Close" button available in the window itself.

**Comment by ManfredKarrer** [comment]
Those popups in the right top corner are simulation notifications (real OS based notifications are unfortunately not easy in Java as its cross platform and each OS has their diff. API/systems). So most are not meant to be sticky and should rather display extra info without disturbing too much.
In the UI the button gets active and the funds text gets green, which should signal that the user can go on. At least that is the intention ;-). 

I would delegate it to the UI dev @ripcurlx and the dsigner @pedromvpg for suggestions to improve that. Atm they are busy with redesign but maybe they have some idea and we can collect it here...

**Comment by arunasurya** [comment]
I think it is easiest to just keep the window for a few seconds longer.

**Comment by ManfredKarrer** [comment]
I will increase from 4 sec to 6 sec.

**Comment by ManfredKarrer** [comment]
Implemented in commit https://github.com/bisq-network/bisq/pull/1711/commits/6e9b71f7778568db0572a3e7a5179a060ee171c4 at PR https://github.com/bisq-network/bisq/pull/1711
