### ISSUE TITLE
A possible option to disconnect from a local bitcode node if it is not up-to-date

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/bisq#1705]
I learned today that the Bisq app detects and automatically connects to a local bitcoin node, which is a great feature. My node was not up-to-date, however, and I had to shut down the app and restart a trade setup. 

Suggestion: It would be great to have an option to connect to and/or disconnect from a local node (if it is not up-to-date). Perhaps a window can appear asking "A local node was detected. Do you want to connect to it? Y/N".

**Comment by ManfredKarrer** [comment]
Yes good suggestion.
One work around is that you shut down the local btc node and then start Bisq, and then restart the btc node. The check for the localhost btc node is only done at startup of Bisq.

**Comment by arunasurya** [comment]
That sounds reasonable, although the user may forget that he/she is running the local node before starting the app. Perhaps it is easiest to leave it as it is but the app can stop trying to connect to localhost if it failed to do so after some time?

**Comment by ManfredKarrer** [comment]
Unfortunately the Bisq app does not know if the local btc node is already synced or still syncing, at least I am not aware of an easy way to find out about that. We only do a simple localhost connection, no btc protocol calls to the node.

I am not 100% sure if a popup telling/asking the user is good here as we have already so many popups and we want to not annoy the user too much with not absolutely required information. But of course its a difficult choice where the right line here is....

I leave that issue pending, maybe we find a convincing solution in the meantime.
