### ISSUE TITLE
Bisq application stuck after clicking scan QR-code win 10

### ISSUE THREAD

**Issue by princeofeth** [bisq-network/bisq#1708]
Hi this is my first time posting an issue so if there is anything I missed or didn't include please let me know.

The problem: When trying to pair my phone to the bisq app in win10 using the scan QR code it just says "waiting for webcam..." and the app just gets stuck their and the only way to use the bisq app again is to close it from task manager and restart it.
I also just found out why this happens, in win10 in the privacy settings/app permissions/camera I have the "Allow apps to access your camera" switched off and when switched on everything works fine.

Steps to Re-produce:
1. Win 10 operating system
2. In windows settings, privacy, camera:    turn off: allow apps to access your camera
3. Open bisq application.
4. Go to account then notifications and click Scan QR code.
5. Get stuck there looking at "waiting for webcam..."

Suggested solution
Have a cancel button after clicking Scan QR code
Also a message saying "have you checked your win10 privacy settings to allow bisq to use the camera."

**Comment by ghost** [comment]
Thanks @princeofeth for reporting.
