### ISSUE TITLE
Not all offers were visible in the offer book

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/bisq#1709]
I could only see one offer in the offer book despite the fact that there were several offers (to buy and sell BTC) at that time, as verified by a separate account holder. 

I needed to restart the app to see the complete offer book.

![incomplete offer book](https://user-images.githubusercontent.com/43150241/45881613-30234b00-bd9b-11e8-849f-e44586ca2c35.png)

**Comment by ghost** [comment]
How many BTC connected peers at the time ?
How many P2P connected peers at the time ?
(Bottom bar left and right).
What kind of connection ?
What says Settings/Network informations ?

**Comment by arunasurya** [comment]
There were 9 bitcoin network peers and 8 P2P network peers (as you can see in the screenshot). 
It was a wifi connection that seems to otherwise be stable. 
I closed Bisq, so unfortunately I can't show it.

**Comment by ghost** [comment]
I have also a wifi connection. wifi/wifi to be exact.
Which seems also quite stable ... but I suspect some microcuts from time to time. Could be very very short, but still enough to cause issues.
I wonder what kind (and length) microcuts can be tolerated by the appli ?
(sorry for not seing the bottom bar in your screenshot. (sometimes also the picture isn't downloaded fully)).

**Comment by ManfredKarrer** [comment]
@arunasurya It can be that the offer maker lost connection and the offers remain in peers until they get cleared by a timeout (7 minutes). Beside that there are issues with OSX as described here: https://github.com/bisq-network/bisq/issues/1701. I just made a PR to fix that.
A certain level of "uncertainty" is normal in a P2P system as data are broadcasted and there is no guarantee that all peers receive all data. Though it has usually a pretty high reliability.

**Comment by ManfredKarrer** [comment]
I will close that for now as I don't see any action to be taken. The PR fixing the OSX standby mode issue is merged, that could have been part of the observed behavior. Beside that it is expected P2P network behavior that number of offers is not exactly the same on different nodes. 
Feel free to re-open in case you see need for more discussion.

**Comment by arunasurya** [comment]
@ManfredKarrer , thank you. I took a look at #1701 and tried disabling the "AppNap" setting for Bisq to rule out that this was the cause of the missing orders:
```
defaults write io.bisq.CAT NSAppSleepDisabled -bool YES
```

I will let you know here if the issue persists.

**Comment by ManfredKarrer** [comment]
@arunasurya 
If a OSX maker gets set into AppNap mode or standby his app will not republish his offer and then on your side his offer gets removed after a timeout of 7 minutes.  The bad thing with AppNap is that people  (including myself) are not aware of that and that a user might switch back online once his app is visible again on his screen. So his offer availability can toggle between online/offline.
So you cannot do so much here, it is more the sum of makers who might go online/offline frequently. 

After then next release, once most users have updated the number of offers should be more consistent if that was the main reason for it.
