### ISSUE TITLE
Blacklist settings on docs.bitsquare.io causing issues

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#172]
docs.bitsquare.io / 179.43.134.87 has become unresponsive.

**Comment by ManfredKarrer** [comment]
@cbeams I just tested: http://docs.bitsquare.io/en/0.1.0-SNAPSHOT/userguide/ there is content...

**Comment by cbeams** [comment]
Oh wow. I got blacklisted. I just tried connecting via a different network and I can see it again. This must be because I tried several times to ssh into the box via port 22 (which is not actually the port that SSH runs on on that box). Pretty touchy :)

Anyway, thanks Manfred for double-checking that. And Lloyd, sorry for the false alarm.

**Comment by cbeams** [comment]
@btcll, reopening this issue. I got into cPanel to try to find out how to de-blacklist myself. Looked at Security->IP deny manager, but found nothing.

And now it seems that I've been blacklisted from my phone's connection too! Not sure what I'm doing wrong here, but in any case, I'm blocked completely now.

**Comment by btcll** [comment]
No worries about the false alarm! Had me a little worried though! Just checked, it didn't go down, phew
 [~]# uptime
 23:57:56 up 4 days,  2:42,  1 user,  load average: 0.07, 0.11, 0.09

Blacklist is likely the issue! Send me an encrypted email with your normal IPs and I can whitelist them for you if you like in the firewall :) I'll get onto IRC.

**Comment by btcll** [comment]
Added @cbeams IPs to the allow log. Let me know if it happens again but going to consider this closed now :+1:
