### ISSUE TITLE
starting SEPA offer ends up in an error, when N26.Beam offer is pending

### ISSUE THREAD

**Issue by Sylo44** [bisq-network/bisq#1725]
So I have started an N26 Beam offer. and everything worked fine, offer is still running.
Because I needed more BTC I decided to take another SEPA offer as well, ebcause I need more BTC.

When I  want to confirm the offer it loads for a very long time and ends up here every single time:
(see attached .png)
![screenshot_2](https://user-images.githubusercontent.com/43583744/46032209-43b41600-c0fb-11e8-9a93-082aabf46174.png)

Also uploaded the log file, hopefully this helps and can be fixxed

[bisq.log](https://github.com/bisq-network/bisq/files/2416387/bisq.log)

**Comment by Sylo44** [comment]
when I click here:
http://prntscr.com/kymq7n

I wait on this screen, until error:
http://prntscr.com/kymqgd

**Comment by Sylo44** [comment]
after the N26.beam trade was marked as paid though, it worked like a charm

**Comment by ManfredKarrer** [comment]
Sorry to hear that issue. If you have lost the trade fee feel free to request a refund at https://github.com/bisq-network/support/issues
