### ISSUE TITLE
Source code on website (JDK 8 (1.8)) does not match source code on github master (Java SE 10)

### ISSUE THREAD

**Issue by bedri** [bisq-network/bisq#1729]
Problem:
The source code given for download on website (https://bisq.network/downloads/ - https://github.com/bisq-network/exchange/archive/v0.8.0.tar.gz) can be compiled with JDK 8 (1.8) however the source code on github master branch requires Java SE 10. This brings an inconsistancy.

Solution:
(Bad) Source code on website can be replaced by sourcecode on github.
(Good) Both source codes linked on website.
(Best) Both source codes linked on website as well as the github repository link is given.

**Comment by ManfredKarrer** [comment]
We just changed after the 0.8 release to Java 10. If you want to run the release code use the src code from there or checkout the release tag. If you want to run from current master which contains ongoing development code u need to update to Java 10.
It was an exceptional case and i think its not worth to do some special handling for it.
I will close as no actions are planned here, if you want to discuss further feel free to re-open.

**Comment by bedri** [comment]
Thanks for the quick response. For to create a pull request to add a new coin, which source code shall I use then?

**Comment by ManfredKarrer** [comment]
Master
