### ISSUE TITLE
Application Testing

### ISSUE THREAD

**Issue by btcll** [bisq-network/bisq#173]
If you are prepared to help with the testing of Bitsquare and provide meaningful feedback please add your name and email to this Issue. Familiarity with Java and Github Issues is a plus but not essential.

**Comment by kimmel-** [comment]
sergi @sergi.compte@gmail.com

**Comment by ManfredKarrer** [comment]
Would you like to help us testing a Bitsquare pre-alpha version? https://groups.google.com/d/msg/bitsquare/ok6_kufx2gk/Z6Pbq9maklMJ

**Comment by Bombibit** [comment]
marc.lundwall@gmail.com

**Comment by ghost** [comment]
I can help test it.  ivank2139@tessaract.net

**Comment by vorpalmusic** [comment]
Andrew Kozloski is vorpalmusic  at gmail dot com

**Comment by rohythakur** [comment]
I can do it , rohyt , rohythakur@gmail.com
re: testing

**Comment by ManfredKarrer** [comment]
Thanks @rohythakur. I will announce it as soon a bigger testing session starts.

**Comment by hjrnz1** [comment]
hamishr@protonmail.com -- Hamish

**Comment by Bloodominick** [comment]
landofmidgar@gmail.com Domenico

**Comment by ManfredKarrer** [comment]
Bitsquare is now already running live on mainnet and there are a bunch of offers out. More than 100 real trades have already been executed.
We need now more people helping test the system and start using it.

Here is the link to the latest version:
https://github.com/bitsquare/bitsquare/releases

Would be great if you can join!

**Comment by marcpopp** [comment]
mapo2364@gmail.com - Marc

**Comment by JerJohn15** [comment]
I've just got introduced to testing not too long ago. I would love to contribute to this project!

jthjohnson15@gmail.com - Jeremiah

**Comment by riclas** [comment]
ricardo - ricardo_barbano@hotmail.com

**Comment by Paul117** [comment]
Add me to your testers' list. I'd love to help.

**Comment by b3dk7** [comment]
benedikt benedikt at riseup dot net

**Comment by daniel-t01** [comment]
I'd like to help testing: daniel_t01@hotmail.com

**Comment by ecslew** [comment]
I'd love to help out testing: ecslew@yahoo.com

**Comment by BluBeast** [comment]
I'd like to help:   moonseal@gmail.com - Anne

**Comment by ManfredKarrer** [comment]
We would need testers from (mainland) China for testing Bitsquare's Tor bridge support. The sooner the better, as we want to release in a few days. Anyone who can help of has contacts in China please ping me. Thanks!

**Comment by BBoBBG** [comment]
Hope i could help ...  awz@empirictechs.com - Al

**Comment by angshumanpal** [comment]
Angshu at pal dot angshuman at the rate gmail dot com for initialization and etc. I can test as well, have 16 years experience in technology

**Comment by cj4c0b1** [comment]
Please count with me Manfred.

The idea to put your email here at plain text is not good.

Everyone that do this will certainly receive a bunch of SPAM!!! and probably hack attacks.

So please just put you comment that you want to join and help in testing.

And those that do not have enabled to show the email, or do not have it in your bio just sent an email do the admin/moderator.

That is the SECURE WAY!

**Comment by snakes-r-us** [comment]
Count me in for application testing.

snakes

**Comment by angshumanpal** [comment]
I can UAT and also support with proper documentation(s).

Regards,
Angshuman

**Comment by oversian** [comment]
hello

also available for UAT ;  sovoox   (at) gmail (dot) com

**Comment by misuta** [comment]
I would like to test it if you still in that phase  misuta@hotmail.com - Gio

**Comment by smilesvua** [comment]
I would like to help smilesvua@gmail.com

**Comment by Cisko-Rijken** [comment]
I noticed a dead link! Namely, this one:

https://bitsquare.io/team/

**Comment by cbeams** [comment]
Thanks @Cisko-Rijken, we're in the middle of relaunching the site now. This and other dead links should be eliminated in the process (though it'll be a few days before you see the changes). In any case, thanks for pointing this out, and future such issues can be reported against the repository at https://github.com/bitsquare/site.

**Comment by stevenkain** [comment]
I would like to help as a tester and provide server node support: stevieosaurus@gmx.com
