### ISSUE TITLE
BTC value shouldn't be changed automatically

### ISSUE THREAD

**Issue by fedegrc** [bisq-network/bisq#1731]
Since the implementation of the privacy feature "Rounded fiat values", BTC values are changed automatically to match the rounded fiat amount as close as possible.
This change depends on the market price, so the BTC values match the rounded fiat amount only at the time that the offer is created. On the other hand, market price change avery minute so it is almost impossible that an offer been taken before that the market price changes to a another value.
So, I think that it is not usefull to change the BTC values automatically.

**Comment by ManfredKarrer** [comment]
Oh, thanks for reporting. Will look into it.

**Comment by ManfredKarrer** [comment]
I just saw that the trade statistics do not apply the rounding. I will fix that issue in the trade statistics so it is not confusing to see exact values there.

Regarding the BTC amount changing: I tested and it behaves as expected (change fiat volume but not btc amount). Maybe there are some edge cases where that happens. Can you post a screenshot or give me some hints how I could reproduce the issue?

**Comment by gibechoes** [comment]
I thought it was a feature to have the stats differ to obfuscate the true fiat amount sent?
Volume on bisq is low, so we need more privacy not less when dealing with fiat. :)
There must be a better way to show volume on bisq in a privacy enhancing way?

(I also do not fully understand the OPs issue either)

**Comment by ManfredKarrer** [comment]
The volume is calculated on the fly from the price and the btc amount. So the visual display is only for convenience, if any analysis company would like to spy on it, it would not matter if it is rounded in the statistics or not.

**Comment by fedegrc** [comment]
Sometimes BTC amount is changed and sometimes it is no changed. I think it depends on the exchange rate. I did two tests with the same value on the field "Amount of BTC to sell".

1st test
I pressed "Create a new offer to sell BTC for USD".
I set the field "Amount of BTC to sell" to 0.15 and then I pressed the tab key.
Following, the screenshot:

![1](https://user-images.githubusercontent.com/14953828/46263909-0cd46a80-c516-11e8-952a-fd82e96ae219.png)

2nd test
I waited one minute until the exchange rate changed from BTC/USD 6538.42 to another value
I pressed "Create a new offer to sell BTC for USD".
I set the field "Amount of BTC to sell" to 0.15 and then I pressed the tab key. When I pressed the tab key, the value was automatically changed from 0.15 to 0.1499
Finally, the screenshot:

![2](https://user-images.githubusercontent.com/14953828/46263912-1e1d7700-c516-11e8-946e-a12736841724.png)

The "available offers" section shows that there are more users experiencing this behavior:

![screenshot_20180928_082723](https://user-images.githubusercontent.com/14953828/46263779-f0cfc980-c513-11e8-9505-74e3a6db60e2.png)

![screenshot_20181001_005131](https://user-images.githubusercontent.com/14953828/46263796-2d032a00-c514-11e8-90a7-a99522ff9752.png)

This message confirms that the BTC amount could be changed:

![screenshot_20180929_105251](https://user-images.githubusercontent.com/14953828/46243654-12776680-c3d7-11e8-9eb4-21572858f3db.png)

I think that BTC amount shoun't be changed.

**Comment by ManfredKarrer** [comment]
Ah so it changes at setting the offer but not afterwards. Yes there are known issues with the adjustments. Its a bit tricky as it involves several things to consider (no sub satoshi values, no change output below dust,...). Can be fixed for sure, but would delay that for a general over-haul of the create offer screen which is planned after the redesign...
