### ISSUE TITLE
Make more prominent which payment account should be used to complete a given trade

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1733]
A common source of disputes goes as follows:

1. Buyer has multiple payment accounts of the same type set up in Bisq->Accounts, e.g. two SEPA accounts, their own and their wife's (on which they are a co-signer).

2. Buyer creates an offer, specifies their wife's SEPA account in the trade details.

3. Buyer goes to make payment and uses their own SEPA account instead of their wife's

4. Seller opens dispute, citing the discrepancy between expected SEPA account in the Bisq trade details and actual SEPA account in the payment details. Seller wants proof that the named party has actually authorized the account, requests photo ID, etc.

As mentioned, these disputes are fairly common, and they tend to take a long time to resolve because of the photo ID requirement. For this reason, **it would be good to prioritize some kind of UX improvement that makes it extra clear to the buyer which of their multiple SEPA accounts they should use to make payment for a given trade.**

Perhaps this is something that fits in well with the ongoing redesign effort.

/cc @pedromvpg, @ripcurlx, @ManfredKarrer, @keo-bisq

**Comment by ManfredKarrer** [comment]
@ripcurlx I added a commit to the current PR for the TakeOfferView class 

If we have multiple payment accounts we should show some info/warning to
make sure the user has selected the account he wants to use.
To use a popup is not recommended as we have already 3 popups at the 
first time (if user has not clicked
don't show again).
@ripcurlx Maybe a similar warn triangle as used in create offer 
might work?

That is only one part, I will look into the trade screens as well...

**Comment by ManfredKarrer** [comment]
One other improvement would be to persist the last selected account in case there are multiple. We do that in create offer. But for take offer it is a bit more complex as we need to first check which payment account is valid for the selected offer. So it would not be enough to store one account as there might be the case that for 2 payment methods there are multiple accounts and then when the user takes once an offer from one payment method and then later from another the persisted value would become useless. So we would need to store it by payment method or currency, but that is also not perfect as the selection for the possible payment accounts carry more complexity depending on the payment method (country based, currency,... see ReceiptValidator). 
So I think that feature is not worth the effort atm.

**Comment by ManfredKarrer** [comment]
Implemented with https://github.com/bisq-network/bisq/pull/1735/commits/2b5731ce7f169c2b501effab938451b100ec50f0

<img width="1201" alt="screen shot 2018-09-28 at 11 58 46" src="https://user-images.githubusercontent.com/1449498/46222647-a33a3d80-c316-11e8-8c03-ba42830197b7.png">
