### ISSUE TITLE
Interac PM bug

### ISSUE THREAD

**Issue by alfsbs** [bisq-network/bisq#1734]
As commented by Freesov in community 
https://bisq.community/t/bug-report-re-interac-e-transfer-options-in-bisq/6304/1 :

> Hello,
>
>I was just instructed by an arbitrator to report a “UI bug” in the Bisq Software.
>
>This pertains to the option that is offered in the software for the Interac e-Transfer funds recipient to provide either an email address or a “mobile phone number”.
>
>The problem with this is that not all Canadian banks support the use of a mobile phone number for Interac e-Transfer payments - I deal with Scotiabank and they only support the use of an email address.
>
>So right now my transaction is held up in arbitration because the BTC seller who accepted my offer provided a mobile phone number (no email address). The arbitrator is trying to contact the BTC Seller to see if they are willing to provide an email address.
>
>Can the Bisq software be altered to remove the mobile phone number option and prompt users for email address only? I have used Interac e-Transfer for years and email address is all I have ever used (or seen used by others).
>
>Thanks!!

**Comment by ManfredKarrer** [comment]
@alfsbs @flix1 
Do you recommend that we remove the phone nr? Is it sure that all support email addresses?

Have I already said that banks are terrible? ;-) They never arrived in the 21st century...

**Comment by alfsbs** [comment]
@ManfredKarrer What do you think about making the email a required field?

**Comment by ManfredKarrer** [comment]
@alfsbs I leave it to you. I don't know enough about Interac. If it is guaranteed that it works for all we can change that for new accounts. But old account will still have tel nr.
