### ISSUE TITLE
Account age displayed in altcoin accounts

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1743]
The account age  should not be displayed in the altcoin accounts as account age witness is irrelevant there.

<img width="669" alt="screen shot 2018-10-01 at 21 54 13" src="https://user-images.githubusercontent.com/1449498/46327093-87a88e80-c5c5-11e8-81fe-06e837a09316.png">

**Comment by ManfredKarrer** [comment]
I think that would be a low hanging fruit for any developer who wants to start contributing to Bisq. 
I would suggest a BSQ bounty of 30 BSQ for any dev who fixes that.

**Comment by JakubRuzicka** [comment]
Hi, can i work on it?

**Comment by ManfredKarrer** [comment]
@JakubRuzicka Yes please!

**Comment by fotispap** [comment]
Hey there! Not sure what is the etiquette now that Jakub asked to work on the issue, but I have made a fix on this issue as well. Does it make sense to open a pull request?

**Comment by ManfredKarrer** [comment]
@fotispap We don't have clear defined rules for that... but as it is prob. a small fix feel free to make the PR.

@JakubRuzicka Please check if the work might have been completed already by @fotispap. But there are many other low hanging fruit issues open. Just search the repo for  `good first issue` and `$BSQ bounty` labels.

**Comment by ManfredKarrer** [comment]
@fotispap Thanks for the PR! Please file a compensation at https://github.com/bisq-network/compensation/issues

See also https://docs.bisq.network/contributor-checklist.html
