### ISSUE TITLE
Default Currency and Trading account error

### ISSUE THREAD

**Issue by fedegrc** [bisq-network/bisq#1753]
Issued reproduced with two o more accounts with different currencies.

Steps to reproduce:
1. "Buy bitcoin" tab
2. "Create new offer to buy BTC with USD"
3. Select a Trading account that is not USD
4. Cancel the offer by clicking the x or "Cancel"
5. "Create new offer to buy BTC with USD"
At this point, the "Trading account" and "Currency" shoud be USD in the "Create offer" tab, but is not. This could produce a mistake we create a new offer.

Same issue in "Sell bitcoint" tab.

**Comment by ripcurlx** [comment]
@fedegrc Can you reproduce this with 0.9.0? I just tried it and it works as you are expecting.

**Comment by fedegrc** [comment]
I just tried it with version 0.9.1 and it works as expected if both Trading accounts allow only one Currency. If you have two accounts and one of them allow two or more currencies, you will be able to reproduce the issue.

Steps to reproduce:

We have the following two accounts:

Account 1:
- Trading account: Zelle
- Currency: US Dollar (USD)

Account 2:
- Trading account: Revolut
- Currency: Euro (EUR) & US Dollar (USD)

Then, we proceed with these steps:

1. Go to "BUY BTC" section
2. Filter by currency: "USD - US Dollar"
3. Filter by payment method: "Zelle (ClearXchange)"
4. Click "CREATE NEW OFFER TO BUY BTC WITH USD"
5. Trading account: "Revolut"
6. Currency: "Euro (EUR)"
7. Cancel the offer by clicking the x or "Cancel"
8. "CREATE NEW OFFER TO BUY BTC WITH USD"

At this point, you will see that the "Trading account" is Revolut (which is ok) and the "Currency" is "Euro EUR" (shoud be USD).

**Comment by ripcurlx** [comment]
@fedegrc I was able to re-produce it based on your steps in 0.9.3 as well. I'm working on a fix right now.
