### ISSUE TITLE
Option to blacklist a user from future trades/option to decline trades

### ISSUE THREAD

**Issue by j3ko** [bisq-network/bisq#1759]
There is a user that insists on having the word "bitcoin" in their transaction email that is accepting my open offers.  I have asked them to change the email but they are unwilling to do so.  The transaction email shows up in my bank transaction history as "bitcoin...".

It has gotten to a point where I will not put up any offers anymore for fear of this particular user accepting it.

Is there any issue with adding an option to blacklist users from future trades?  Or maybe a way to decline incoming trades outright?

maybe, when declining a trade to allow the user to enter a reason for declining as well.

**Comment by cbeams** [comment]
See `Settings->Network info->General preferences->Ignore peers with onion address`.

**Comment by ghost** [comment]
@j3ko , thanks for signaling this kind of behaviour.

**Comment by j3ko** [comment]
@cbeams thanks, I might be blind. I'm running 0.8 and I don't see a "general preferences" option in the "Network info" tab.  It would be nice if the UI would just allow me to click on a user image and block them in the popup.

@HarryMacfinned no problem, I really like the platform and I want to see it grow.

Is there any issue with allowing the market maker to decline a trade?  I wouldn't mind being penalized for transaction fees if that is the issue with giving the market maker an option to back out.

For future reference should I have left something like this to be arbitrated?

**Comment by ManfredKarrer** [comment]
@j3ko Please open a dispute in such cases. It is clearly stated that this is not permitted. If the user repeatedly is doing that the arbitrator should take 100% of his security deposit. If that even does not change his behavior we can block his onion address. 
Beside that as @cbeams mentioned you can filter peers by the onion address so he cannot trade anymore with you.

Can you post his onion address here so the arbitrators are aware?

**Comment by ManfredKarrer** [comment]
@j3ko It is in settings/preferences/General preferences/ Ignore peers....

**Comment by ManfredKarrer** [comment]
I close that as it is an implemented feature
