### ISSUE TITLE
Open up a paid account on GitHub

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#176]
https://github.com/pricing
Costs 25.- per month as we are an organisation.
I think we need to rethink that if it really makes sense.

**Comment by btcll** [comment]
I think right now this would qualify as your project @ManfredKarrer with us others helping you. I would opt for the Micro plan and we can upgrade when more funds are available :)

**Comment by ManfredKarrer** [comment]
We turned it to an organisation. But anyway its open if we really go that road with private repos...

**Comment by cbeams** [comment]
Manfred and I determined this wouldn't be necessary—for now. Closing.
