### ISSUE TITLE
Use system Tor if possible

### ISSUE THREAD

**Issue by qubenix** [bisq-network/bisq#1761]
Currently the software uses its bundled Tor regardless if Tor is already installed on the users system. This results in a [Tor over Tor](https://tor.stackexchange.com/questions/427/is-running-tor-over-tor-dangerous) situation on systems like Whonix which transparently proxy all traffic.

Please see:

+ Tor friendly applications best practices: https://trac.torproject.org/projects/tor/wiki/doc/Tor_friendly_applications_best_practices.

+ Whonix friendly application best practices: https://www.whonix.org/wiki/Dev/Whonix_friendly_applications_best_practices

---

Thank you for all your hard work on this project.

**Comment by ManfredKarrer** [comment]
There is an open issue out for that but dev resources found so far who work on that. If you are a dev you are welcome.

**Comment by qubenix** [comment]
I made a post on the Whonix forum's Bisq thread about needing Java coders: https://forums.whonix.org/t/bisq-the-p2p-exchange-network/4953/17?u=qubenix.

Feel free to close this issue if you feel it is a duplicate. I apologize, I did try to search for this exact issue and didn't see it (although it was mentioned in other issues).

**Comment by ManfredKarrer** [comment]
Thanks. I think it is posted at the netlayer library GH issues. I leave it open here to keep attention to it.

**Comment by ManfredKarrer** [comment]
See https://github.com/JesusMcCloud/netlayer/issues/7

**Comment by ManfredKarrer** [comment]
In anyone is interested to work on that please check with @freimair if he has not started to work on that already....

**Comment by freimair** [comment]
Manfred, you can assign the issue to me, so there is no doubt.
