### ISSUE TITLE
Show BTC balance value

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#1770]
It would be nice to show the value of your BTC balance based on your preferred currency. Not sure an additional field is required, perhaps just a tooltip when hovering over the balance.

**Comment by ManfredKarrer** [comment]
Yes, agree! And probably best with hovering similar like at blockchain.info.

**Comment by devinbileck** [comment]
@ManfredKarrer @ripcurlx feel free to assign this to me. I can take a look at implementing it.

**Comment by ManfredKarrer** [comment]
Great!
