### ISSUE TITLE
Require password when restoring application window

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#1772]
When leaving the application running with open offers, I like to hide the application window to keep it out of the way (by clicking the icon in the Windows system tray and selecting the hide option). It may be beneficial to require the password when restoring the window in case someone else uses the computer. Normally I log out or lock my computer when afk, but if I allow someone to access it while I am logged in, requiring the password would prevent them from accessing the application if I am not watching.

**Comment by ManfredKarrer** [comment]
Good idea! Feel free to implement that!
Great to see devs like you who come up with own suggestions for improvements AND be able to implement it!!!!
