### ISSUE TITLE
Find good UI solution for trade fee payment info in BSQ or BTC

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1782]
Atm we use a popup for asking the user if he wants to pay the rade fee in BTC or BSQ.
<img width="1190" alt="screen shot 2018-10-17 at 10 54 31" src="https://user-images.githubusercontent.com/1449498/47100161-7d5cd600-d1fc-11e8-8ee8-bc3c135184f5.png">

As we have already lots of popups specially at the create and take offer screens we should find another solution.
I think it is required to show at least once the user the option in the screens directly (not only to make that selection in the settings), but it should be in the settings as well (not impl. yet), so if the user has clicked for instance a "don't show again" checkbox he will not be bothered anymore in the trade screens.

If the user does not have BSQ in his BSQ wallet he gets another popup.
<img width="758" alt="screen shot 2018-10-17 at 11 03 41" src="https://user-images.githubusercontent.com/1449498/47100154-76ce5e80-d1fc-11e8-859c-3eecc9a91246.png">

Maybe we can show the fee option similar like the security deposit option but make the security deposit option by default invisible and only enable it if selected in the settings to show it (advanced option). Once the user has selected first time the fee (BSQ or BTC) he can get an info that it will be hidden from now on but can be turned on in the settings again. In the popup we should also promote the discount when using BSQ and maybe give a bit of hints for more info regarding BSQ/DAO.

See also https://github.com/bisq-network/bisq/issues/1783

**Comment by cyphersphinx86** [comment]
Just to bring in a new angle or maybe bring back an old one, if you already have discussed this.
I always wonder: Why not have trade fees always be paid in bisq tokens. If a user has a dedicated bisq wallet for this, that wallet would be used. If not, behind the scenes bisq token would be bought with btc, without the user knowing about this detail and hence no popup needed, just a more expensive trade for the not so experienced user due to the on demand invisible token trade. The more experienced user who has a bisq wallet would then get rewarded for holding bisq token as his trades would be cheaper after his one time setup.

**Comment by cyphersphinx86** [comment]
And I was ranting conceptually there, not giving too much thought to the actual implementation.
Maybe keep the trade fees in either btc or bisq but have all trade fees defaulted to be payed in btc (no popup) Then the dedicated bisq wallet is a bounty that advanced users can use to save trade fees on (by attaching a bisq wallet).

**Comment by ManfredKarrer** [comment]
Automated conversion is not easy in a decentralized way. You as BSQ buyer need to find a BSQ seller and both need to be online to make the tx. It would be a bit easier if the BTC/BSQ trade would be a atomic tx instead of using the normal trade protocol as atm. But that atomic exchange is not implemented yet (though planned in the future). 
There could be some market makers (being online all the time or running via APIs) which could server in future for a quick swap. And we could add a shortcut option to make the trade as easy and fast as possible (e.g. - swap BSQ for best market price) but as said that will require a bit of extra work.
Then is the question if the swap costs also trade fees, and if so it must be paid in BTC as the user does not have BSQ... But I assume the atomic swap could either work without fee or deduct the fee from the exchange rate.

Beside that we do not want to force users into using BSQ.

**Comment by ManfredKarrer** [comment]
@cypherspace86 I just added a proposal (insprired from your input): https://github.com/bisq-network/proposals/issues/50

**Comment by ManfredKarrer** [comment]
I am workin on that now myself...

**Comment by ManfredKarrer** [comment]
@ripcurlx will continue to improve that. A basic version is implemented which avoids having a popup.

**Comment by ManfredKarrer** [comment]
Close as it is implemented.

**Comment by cbeams** [comment]
@manfredkarrer,  I was running against master earlier today and noticed at this new pop up appears by default. BSQ won’t be available anywhere other than testnet in v0.9.0, so shouldn’t this pop up be conditional on `—daoActivated` or similar?

**Comment by ManfredKarrer** [comment]
Did you run regtest or mainnet. in mainnet it should not be there (assuming u dont have doa activated), otherwise there is a bug.

**Comment by ManfredKarrer** [comment]
On testnet and regtest dao is activated by default

**Comment by cbeams** [comment]
Yes, I was running against regtest. Not sure it makes sense to keep that activated by default there until the rest of the DAO code is enabled by default.

**Comment by ManfredKarrer** [comment]
On testnet it will be with upcoming release. On Regtest - yes it could be deactivated, but I think its also good if all devs run it to spot potential bugs earlier.

**Comment by ripcurlx** [comment]
Closing as complete. Was released for Testnet with v0.9.0.
