### ISSUE TITLE
Hide security deposit option in create offer screen by default

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1783]
The setting of the buyers security deposit is difficult to understand for most users without a lot of background info. We should hide that to avoid confusion and only show it if an "show advanced features" option is selected in the settings. A text with more background info why it the reasoning to set the buyers deposit would be good as well.

<img width="1192" alt="screen shot 2018-10-17 at 11 07 24" src="https://user-images.githubusercontent.com/1449498/47100535-56eb6a80-d1fd-11e8-90ab-41bedc6cf3a9.png">

**Comment by KanoczTomas** [comment]
The security deposit is paid by the seller and the byer as well. It is paid on top of the traded amount. When the trade completes successfully it is returned. In case of an arbitration the party which looses the arbitration process will loose the security deposit as well. It will be taken by the arbitrator as a compensation for the services provided. The default value is 0.01 BTC. Higher amounts tend to motivate both parties to complete the trading protocol in time and do not let the trade to be disputed after the trade timouts automatically. Each trade type has an expiration time after which it will automatically go to the arbitrator. E.g. sepa payments have a timeout of 6 days. Lower security deposit allows people with less BTC on their balance to be able to start trading on Bisq.

**Comment by ManfredKarrer** [comment]
Thanks for your suggestion!
There are a few thing which are not correct:

> It will be taken by the arbitrator as a compensation for the services provided.

No that was in earlier versions but we removed that. The arbitrator can never receive any funds from the trade, only the other trader.

> Each trade type has an expiration time after which it will automatically go to the arbitrator.

No it does not open a dispute automatically but one of the traders need to open the dispute. They can also choose to wait longer and continue the trade (e.g. in case of a long bank holiday weekend).

I think we should explain more clearly what are the benefits and drawbacks of changing the buyer deposit and why it is only adjustable for buyer and not seller (buyer can choose to not pay in case of volatility and better price, so is cheaper for him to "cancel" - higher deposit creates higher costs).

**Comment by KanoczTomas** [comment]
Ok, I am not sure of the correct answer, lets try trial and error iteration :) Perhaps we can find the best formulation if we try to discuss the questions that arise from the above comments. Tried googling a documentation on it, no success.

So the arbitrator receives only the trading fees? What is his motivation to resolve the issue then and even more importantly, what is the penalty of being wrong?

From your answer I figure the security deposit in case of a dispute goes to the other trading side?

Yeah, forgot the icon to open a dispute gets clickable and the trade does not go to an arbitertrator automatically.

**Comment by cbeams** [comment]
> So the arbitrator receives only the trading fees?

Correct.

> What is his motivation to resolve the issue then

Avoiding reputational damage both for himself and for Bisq as a project.

> and even more importantly, what is the penalty of being wrong?

Again, reputational damage is the answer. When arbitrators make mistakes, traders are quick to report it, usually via the forum, and arbitrators tend to be very quick to make amends. If Bisq were to get even the slightest reputation of having corrupt, lazy or incompetent arbitrators, it would mean possibly irreparable damage for the project. This is one of the reasons why arbitration is such a high-trust (and therefore will be such a high-bond) role.

Remember that users have the ability to blacklist arbitrators that they believe have acted unjustly. This is actually going away in 0.9.0 for security-related reasons, and I don't know how important that mechanism has been to date, but it's one I always liked, as it puts power in the users' hands to choose who they're willing to do business with.

**Comment by niyid** [comment]
Hello. What's the status on this?
