### ISSUE TITLE
Add Advcash as payment method

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1785]
Seems an interesting payment provider similar to PerfectMoney.

https://advcash.com/

@alfsbs What do you think?

**Comment by userzer0x** [comment]
@ManfredKarrer Yes. I second this.
AdvCash is quite the name out there. Its actually better than PerfectMoney

**Comment by ManfredKarrer** [comment]
Since 2 days I get that URL http://m.yareel.com/ when requesting https://advcash.com/ . Seems their dns got hijacked... 
@userzer0x Does the URL work for you?

**Comment by userzer0x** [comment]
Yes my side is working ok. Thats weird, maybe something else wrong in your browser or your dns?

**Comment by userzer0x** [comment]
@ManfredKarrer try the URL on your phone via your cell network or try it via a different IP. It should be working fine.

**Comment by ManfredKarrer** [comment]
Yes, true on my mobile its ok. Strange need to check with my ISP...

**Comment by gibechoes** [comment]
Anyone use this? Site says no KYC for low amounts? seems interesting option.

**Comment by userzer0x** [comment]
@gibechoes yes i use it. its very convenient. KYC is used for few deposit methods.
