### ISSUE TITLE
Java 10 is EOL, move to Java 11

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#1787]
As noticed by the CI builds failing lately, Oracle broke or removed their JDK10 downloads. JDK10 is End of Life anyways (https://www.oracle.com/technetwork/java/javase/eol-135779.html), so need to switch to JDK11 which will be their LTS version anyways.

**Comment by ghost** [comment]
but does Bisq actually compile properly with JDK11 ?

**Comment by devinbileck** [comment]
Not yet, but working on it :)

**Comment by cbeams** [comment]
See https://github.com/bisq-network/bisq/pull/1792, in which I quickly (and unsuccessfully) attempted to switch Travis CI builds to OpenJDK10.

**Comment by ManfredKarrer** [comment]
PR for OpenJDK 10 with javafx 11 is merged. 
I leave the issue open as we still want to migrate to java 11 after gradle support is available.

**Comment by ripcurlx** [comment]
Un-stale this issue as we still want to keep this on our roadmap.

**Comment by devinbileck** [comment]
Just an update on this. The primary item blocking us is there is no javapackager in JDK11. However, progress is being made on its replacement https://jdk.java.net/jpackage/ which is based on JDK 13. The next LTS release (JDK 17?) is still a few years away and no idea if this will be ported to the current LTS, JDK11. So unless we find an alternative solution, we may be stuck on JDK10 for a while.

**Comment by leshik** [comment]
@devinbileck Could we use [this port](https://mail.openjdk.java.net/pipermail/openjfx-dev/2018-September/022500.html) while waiting for the full fledged solution?

**Comment by devinbileck** [comment]
Thanks for the link. Potentially, yes. But I would be hesitant without further review and would especially be concerned using an unofficial/unsupported port. With the time required to ensure our code base is updated for Java 11 (and potentially BitcoinJ), and since we just recently went through all the hassle updating Java from 8 to 10, unless there is an urgent need I would think at least for now our time would be better suited focused on other high priority areas.

**Comment by devinbileck** [comment]
Still relevant.

**Comment by battleofwizards** [comment]
Minor update: a few days ago the first build of JEP 343 `jpackage` was published: https://jdk.java.net/jpackage/ This is early access build.

**Comment by devinbileck** [comment]
Relevant

**Comment by cd2357** [comment]
> The primary item blocking us is there is no javapackager in JDK11. (...) So unless we find an alternative solution, we may be stuck on JDK10 for a while.

If I understand [this](https://openjdk.java.net/jeps/343) correctly, `jpackager` is available in Java 14, and [Java 14 is already GA](https://jdk.java.net/14/).

From what I see, getting the latest `jpackager` could directly solve a bunch of issues, like #3373 #3402 and #4196. Also, an upgrade of Java would make #4242 possible, which seems to address (or at least improve) a lot of JavaFX-related memory and performance issues.

Would it then make sense to upgrade to Java 14?

Or are there other blockers preventing this / other reasons not to?
