### ISSUE TITLE
Customize user guide CSS

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#179]
In, https://github.com/bitsquare/bitsquare/issues/169#issuecomment-58401584, @ManfredKarrer wrote:

> @btcll: Looks good already, the only tiny wish I have is to change the red color of the headlines to something less alerting (Bitsquare blue or the like)...

In https://github.com/bitsquare/bitsquare/issues/169#issuecomment-58402743, @btcll wrote:

> @ManfredKarrer I'm not sure what the CSS options are, but if @cbeams can give me some guidance I am happy to do a Bitsquare CSS document up for the docs. It looks like it is all inline CSS at the moment.

**Comment by cbeams** [comment]
Assigned to myself to take the next step:
- [ ] Research how to provide custom CSS to Asciidoctor (via the gradle-asciidoctor-plugin DSL).

I'll come back to this (not the highest priority at the moment), but here are a couple leads when I do:
- https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/9
- http://asciidoctor.org/docs/produce-custom-themes-using-asciidoctor-stylesheet-factory/

Looks like it might be as simple as providing a `stylesheet=path/to/some.css` entry in the `asciidoctor.options.attributes` map in build.gradle. See https://github.com/asciidoctor/asciidoctor-gradle-plugin#configuration.

**Comment by btcll** [comment]
Hey @cbeams - please try it with the stylesheet= and link it to styles.css and we can give it a go. The default styles can be extracted from the current HTML. Let me know if it works and I'll have a play with the styles.css to get some Bitsquare blue happening :)

**Comment by cbeams** [comment]
closing as it's not clear we'll do this at all. user guide is currently on the wiki. css does not apply.

**Comment by cbeams** [comment]
> closing as it's not clear we'll do this at all. user guide is currently on the wiki. css does not apply.

Actually closing this time.
