### ISSUE TITLE
I have not received BTC

### ISSUE THREAD

**Issue by rascoes** [bisq-network/bisq#1790]
Hi. After six hours. Support ticket closed positively. But I can not complete the exchange because it is not in Portfolio to receive BTC.
Thank you

Ticket closed on Oct 19, 2018 12:04:30 PM
Summary:
BTC buyer/Taker delivered tamper proof evidence: No
BTC buyer/Taker did ID verification: No
BTC buyer/Taker did screencast or video: No
Payout amount for BTC buyer: 0.0824 BTC
Payout amount for BTC seller: 0.0030 BTC

Summary notes:
Buyer opened dispute because they had accidentally clicked the 'Payment Sent' before their payment actually went through. The buyer successfully sent their payment immediately afterward, and the seller has since acknowledged receipt. I'm closing this trade out normally now. Thanks and best regards to both parties.

**Comment by cbeams** [comment]
I re-opened and re-closed the dispute just now, and your payout transaction has now been published. I'm not sure why it didn't take in the first place—one of us may not have been well-connected. In any case, please include the trade ID in any future such support requests. Thanks.

**Comment by rascoes** [comment]
Finally exchange completed. I have received the BTC. Thank you very much for your help.
