### ISSUE TITLE
Add following Payment Methods for Indian buyers and sellers

### ISSUE THREAD

**Issue by hokkaidosuneku** [bisq-network/bisq#1799]
HI,

Most trades in India are performed using either NEFT, IMPS or UPI and various mobile/online wallet applications such as:

- PayTM
- Google Pay (Previous known as Tez)
- PhonePe
- BHIM.

It would be nice to have these options added either individually under Payment Method's dropdown options or would also be nice to consolidate it under a single dropdown option probably called 'Web Wallets' something similar to the 'Other Online Wallets' dropdown option provided by [LocalBitcoins](https://localbitcoins.com/instant-bitcoins/?action=buy&country_code=IN&amount=&currency=INR&place_country=IN&online_provider=OTHER_ONLINE_WALLET&find-offers=Search)

Also in addition to this I'm currently aware that I can configure under National currency accounts for 'National bank transfer' my bank details, but I was confused as to where would I be able to specify if I would only be accepting IMPS over NEFT or vice versa. NEFT usually takes about the next working day to process payments and IMPS transfers funds instantly. Should I be using a custom Account name to indicate either NEFT or IMPS?

**Comment by ManfredKarrer** [comment]
Could you provide information about chargeback risk of those methods? 

@alfsbs Any info on those?

**Comment by ripcurlx** [comment]
As we are planning more activity in India. @alfs @m52go Maybe some of the payment methods mentioned by @brijananand would be worth investigating?
