### ISSUE TITLE
Open offer not visible in market

### ISSUE THREAD

**Issue by iljah** [bisq-network/bisq#1804]
Not sure if related to https://github.com/bisq-network/support/issues/150 but another offer I made isn't visible anywhere except my open offers tab in protfolio but it should be (id NAdjQkUo-37b11094-4544-4f8e-a6f0-1dceda7054fb-080). Maker fee has been confirmed by btc network.

**Comment by ManfredKarrer** [comment]
Do you have edited the offer and maybe deactivated it? Which currency, buy/sell, price, payment method is it, so I can see if I can see the offer.

**Comment by iljah** [comment]
Haven't done anything to it after submitting. BTC/XMR at 0.01639. I assume it should be visible at markets.bisq.network if everything was fine.

**Comment by iljah** [comment]
Found this in logfile: `INFO  b.c.n.a.MyOfferTakenEvents: We got a offer removed. id=NAdjQkUo-37b11094-4544-4f8e-a6f0-1dceda7054fb-080, state=AVAILABLE`

**Comment by iljah** [comment]
Which was after `INFO  b.c.b.w.BtcWalletService: swap addressEntry with address ... and offerId NAdjQkUo-37b11094-4544-4f8e-a6f0-1dceda7054fb-080 from context OFFER_FUNDING to available`

**Comment by ManfredKarrer** [comment]
Did you had any error? Seems like one took your offer but maybe it faied then, so your offer got locally removed. Maybe best is to remove the offer manually and created it again. You can ask for trade fee reimbursement under the support repo.

**Comment by iljah** [comment]
I didn't see any errors related to this when submitting or afterwards. Just tried to remove the offer and got a warning window with this text and close button:
```
Remove offer failed:
Remove offer failed
```

**Comment by iljah** [comment]
Tried to edit it, got this warning window:
```
Editing of offer failed:
Remove offer failed
```
After closing above I got warning window:
```
Editing of offer failed:
Editing of offer can't be canceled as it is not edited.
```

**Comment by iljah** [comment]
So looks like the btc I deposited to that offer is stuck in gui. Will I have access to it if I create a new bisq data directory and copy over old btc_mainnet directory?

**Comment by iljah** [comment]
Or should I figure out how to import that into btc node in wif format?

**Comment by ManfredKarrer** [comment]
@iljah Best its to create a fresh new data directory and move over your funds. 

Do not copy over any files! Send the BTC with a noramal tx to an external wallet and then fund the new wallet. tx fees are low atm and u can set it even lower in the settings if u like.

See
https://bisq.community/t/switching-to-a-new-data-directory/1697
and 
https://bisq.community/t/carry-over-account-age-witness-to-new-data-directory/5605

**Comment by iljah** [comment]
From first link:
> If you have open offers, remove them (you will lose the “create offer” fee.

I cannot remove the offer, as I wrote above. Are you sure I should still switch to new data directory before getting funds back from this one?

**Comment by iljah** [comment]
First link mentioned emergency wallet tool, I was able to move stuck funds with that. Portfolio is still showing open offer in OP even though bisq warned me that open offers would be removed if I moved their funds with emergency wallet...

**Comment by iljah** [comment]
> u can set it even lower in the settings if u like.

Emergency wallet tool seems to have ignored this setting.

**Comment by ManfredKarrer** [comment]
With the emergency wallet tool u see the internal balance if that is 0 after withdrawing all all is fine. You can run a spv file resync (settings/network) to be sure that the wallet really had all txs. After the resync check again with the wallet tool if balance is 0. 
Sorry for the troubles....

**Comment by stachrom** [comment]
i have the same behavior - Since editing the offer. 

If i disable and enable the offer - its getting re-propagated - than its stays for about 10 min in the public orderbook just to vanish again.

**Comment by ManfredKarrer** [comment]
@ripcurlx Lets focus on that test case as well. E.g. check if an offer is still available at other clients after longer period (> 10 min).

**Comment by stachrom** [comment]
@ManfredKarrer I think i found the issue. 

If the hosttime is not in sync with the current global time (in my case 5 min diff) - the offer seams to disapear in the global order book after some time  ( 5 -20 min)

**Comment by iljah** [comment]
In my case offer was never visible globally and time should've been in sync since fedora updates it automatically.

**Comment by justpaulgmx** [comment]
I know in earlier versions, the client was programmed to not show makers their own trades when browsing taker opportunities of the same currency pair. I assume this was to stop people accidentally buying from themselves :-) I'm assuming it was changed but could have become an option in settings. Just my 0.02 sats worth.

**Comment by ManfredKarrer** [comment]
Its in the settings and your offer would have the "remove" label so you cannot take it.

**Comment by justpaulgmx** [comment]
So issue resolved? Was the simplest answer the correct one? :-)

**Comment by iljah** [comment]
I haven't seen this second time but haven't tried to reproduce it either. Current guess would be that I made my offer too soon after starting up bisq so it hadn't connected to enough nodes (bisq) yet. And/or it did send out my offer to couple of other nodes, but for some reason my offer was lost and my node didn't rebroadcast it, so my offer was visible to me but not to anyone else.

**Comment by justpaulgmx** [comment]
Thanks for the clarification, I guess we leave the issue open.

**Comment by iljah** [comment]
You thought problem was me not seeing my offer? First thing I wrote when creating issue was `offer I made isn't visible anywhere except my open offers tab in protfolio`, not sure how I could've been more clear...

**Comment by ManfredKarrer** [comment]
@iljah The offers get re-broadcasted ever few minutes. As long you are healthy connected to the network your offers should be visible to all. Do you use latest version? If not please update, there have been many bug fixes.

**Comment by iljah** [comment]
I haven't seen this problem since october, and now I wait until bisq gets about 10 tor connections before I do anything, so this can probably be closed...

**Comment by justpaulgmx** [comment]
Yes, I agree it should be closed now unless you found this error on a second computer running another Bisq client and account. To  clarify, the default settings in Bisq will show your sell BTC offers in the portfolio area of the app, but not list it on the buy Bitcoin page because it hides your own offers so you don't buy from yourself.

Thanks so much for your feedback and responses.

**Comment by justpaulgmx** [comment]
Sorry, just saw this was closed. 

Thanks so much for your feedback and responses.
