### ISSUE TITLE
Nightly releases

### ISSUE THREAD

**Issue by project-qmc** [bisq-network/bisq#1812]
Maybe there should be nightly releases so altcoins don't try to get listed 1-2 months ago and lose interest by the time a new release comes out (leaving a flood of never traded altcoins on bisq)

HyperDEX / BarterDEX seem to do this quite well - isn't that possible with bisq?

**Comment by aejontargaryen** [comment]
You can build master branch at anytime. Day or night ;-)

**Comment by project-qmc** [comment]
But people wouldn't be so keen to trust binaries from 3rd parties :)

**Comment by aejontargaryen** [comment]
Altcoins arent as main of a focus for Bisq compared to the other DEXs you listed who's actual entire focus is altcoins, iirc.
you could replace binaries with build instructions?

**Comment by cbeams** [comment]
Nightly builds are a future possibility, but we're not well set up for it now.

> you could replace binaries with build instructions?

Build instructions are at https://github.com/bisq-network/bisq#building-bisq.
