### ISSUE TITLE
Importing Bisq into Intellij IDEA Question

### ISSUE THREAD

**Issue by xerxes805** [bisq-network/bisq#1816]
![image](https://user-images.githubusercontent.com/32861660/47471924-36e02a80-d83f-11e8-9a8a-a485edc26526.png)
I tried Importing Bisq into Intellij IDEA，But there are many errors, such as（How to deal with it?please）：
Error: (40, 28) java: The package javafx.scene.control does not exist
Error:(43, 27) java: The package javafx.scene.layout does not exist
Error: (61, 21) java: symbol not found
   Symbol: Class GridPane
   Location: class bisq.desktop.components.paymentmethods.PaymentMethodForm
Error: (64, 21) java: symbol not found
   Symbol: class BooleanProperty
   Location: class bisq.desktop.components.paymentmethods.PaymentMethodForm
Error: (68, 15) java: symbol not found
   Symbol: Class CheckBox
   Location: class bisq.desktop.components.paymentmethods.PaymentMethodForm

**Comment by devinbileck** [comment]
If you are specifically trying to import v0.8.0 source, do you have Oracle JDK8 installed? Did you select JDK8 in IntelliJ project settings?

**Comment by xerxes805** [comment]
Yes, both jdk8 and jdk10 have tried。

**Comment by devinbileck** [comment]
Are you using OpenJDK or Oracle JDK?
Provide the output of this command: `java -version`

Did you run `gradlew build`?

**Comment by xerxes805** [comment]
![image](https://user-images.githubusercontent.com/32861660/47550407-b0584580-d931-11e8-8d80-b8a59829dbf6.png)
run build project

**Comment by devinbileck** [comment]
You will need to run `gradlew build`.

**Comment by ripcurlx** [comment]
Closing as complete.
