### ISSUE TITLE
Error at traderSignAndFinalizedDisputedPayoutTx

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#1828]
I got this message when I opened Bisq and I have no idea what it means.

![20181018_bisq_error](https://user-images.githubusercontent.com/44140017/47613604-66cf3e00-da8a-11e8-8621-1b98e64eb588.PNG)

debug.log file

[20181028_bisq_error.log](https://github.com/bisq-network/bisq/files/2522589/20181028_bisq_error.log)

**Comment by ManfredKarrer** [comment]
You might need to open a dispute with cmd+o in case your trade payout did not work.

**Comment by huey735** [comment]
> 
> 
> You might need to open a dispute with cmd+o in case your trade payout did not work.

I have no unresolved trade.

**Comment by huey735** [comment]
@ManfredKarrer I've solved it by creating a new "account". I've created a Bisq2.bat file the following inside, following one of your old posts.

Bisq.exe --appName=Bisq_2

Now I when run it I have a new Bisq directory and I no longer get that error. It'd be nice however to know what went wrong.
