### ISSUE TITLE
Interac E-transfer validation

### ISSUE THREAD

**Issue by j3ko** [bisq-network/bisq#1830]
A couple interac e-transfer fields need some extra validation because of rules enforced by banks:

1. For the security question:  "Please enter a question that is 1 to 40 characters long and contains only letters, numbers, and/or the symbols ' _ , . ? -"
2. For the security answer: "Please enter a one-word answer that is 3 to 25 characters long and contains only letters, numbers , and/or the symbol -"

The workaround is contacting the other party via email/mobile and telling them what you changed in order to pass validation with your e-transfer.

**Comment by ManfredKarrer** [comment]
@j3ko Are you a developer? If so could you implement that?

**Comment by j3ko** [comment]
@ManfredKarrer I am, I would love to take a crack at it.

**Comment by ManfredKarrer** [comment]
Great!!!
