### ISSUE TITLE
Received fiat but trade still “waiting until payment has started”

### ISSUE THREAD

**Issue by trybtc-2** [bisq-network/bisq#1848]
I have an open trade where I received the fiat payment but the “trade process” status is still “Wait until payment has started”. Obviously I didn’t get the full buyer information so I can’t confirm that those matched the transfer, but the Trade ID and the amount of the transfer matched. The trade deadline has now expired and a dispute has been opened. I’ve explained the situation in the chat and I’m sure the arbitrator will handle it.

Perhaps it would be better in such situations for sellers to be able to officially indicate that they received the money in the interface, and complete the trade (from their end).

Discussed here: https://bisq.community/t/received-fiat-but-trade-still-waiting-until-payment-has-started/6519

**Comment by ripcurlx** [comment]
@trybtc-2 I think this can't be done easily to skip a step in the trade process. @ManfredKarrer or is there a workaround to skip certain steps by the other trade party?

**Comment by ManfredKarrer** [comment]
No. With the new trade protocol we will impl. that more flexible.
