### ISSUE TITLE
Design hero images

### ISSUE THREAD

**Issue by btcll** [bisq-network/bisq#186]
In the current design each page has an image at the top of the page that is 1400x450px

The graphic gives some colour to the page, and helps orientate the user to the contents of the page.

I've had a go at making some images, but I think a designer could do far better. You can see an example here:
http://dev.bitsquare.io/donate/
and here:
http://dev.bitsquare.io/philosophy/

The height doesn't have to be 450px - if making the height smaller or larger would look better in the design then that's something we can change.

The pages that require a top banner image are:
- Philosophy
- Community
- Donate
- Contact
- Press

:+1:

**Comment by cbeams** [comment]
Moved this issue to bitsquare/site#3.
