### ISSUE TITLE
Create concept how we can support TransferWise as payment method

### ISSUE THREAD

**Issue by alfsbs** [bisq-network/bisq#1867]
@ManfredKarrer commented on [Mon Jan 22 2018](https://github.com/bisq-network/bisq-desktop/issues/1250)

TransferWise seems to be used by some Bisq users but often leads to arbitration because the sending bank account of TransferWise is not as defined by the user (he cannot know it in advance).
It would require a concept how we can support TransferWise without breaking our security mechanism and without adding too much dev efffort.
Anyone how is capable and willing to work on that can earn BSQ in context of our DAO compensation requests. 

See also: https://bisq.community/t/transferwise-borderless-account-and-outgoing-transfers-from-different-account/2224/9

**Comment by ripcurlx** [comment]
Might be still useful to add in the future.
