### ISSUE TITLE
Add payment method: ATH Móvil (Puerto Rico)

### ISSUE THREAD

**Issue by alfsbs** [bisq-network/bisq#1868]
@josedcrespo commented on [Wed Feb 28 2018](https://github.com/bisq-network/bisq-desktop/issues/1414)

In Puerto Rico, Evertec, Inc. provides person to person interbank transfers using an app called ATH Móvil. Recently they achieved the one million users milestone. (That's ~1/3 of the population) Due to recent spike in global and particularly local interest in cryptocurrencies it provides a great method for buying bitcoin using Bisq. The only downside is that is limited to a $500 maximum daily transfer. The requirement to do a transfer is the person's mobile phone number.

---

@abigail830 commented on [Wed Apr 11 2018](https://github.com/bisq-network/bisq-desktop/issues/1414#issuecomment-380315976)

@ripcurlx here should be also in:payment-methods :-P

Given I having a fresh memory for implement new payment method, if you see any issue on this topic is ready to implement, feel free to assign to me. If no, then I would go on explore other items.

---

@josedcrespo commented on [Wed Apr 11 2018](https://github.com/bisq-network/bisq-desktop/issues/1414#issuecomment-380457461)

If no other additional information is needed, this is ready to implement. Thanks!

**Comment by ripcurlx** [comment]
Might be still useful to add in the future.

**Comment by btcpuertorico** [comment]
Interest on this payment method is increasing in Puerto Rico. ATH Movil is almost ubiquitous among local population. It would definitely help increase adoption.

**Comment by pazza83** [comment]
Hi thanks for the message. I will take a look at it.

**Comment by pazza83** [comment]
Hi @btcpuertorico / @alfsbs I have just taken a look at ATH Móvil and the website does not say much about this payment service.

It would be great if you are able to let me know a little more about this payment method. Do you know answers to any of the following questions:

1. How easy is it to cancel / reverse / chargeback a payment once it's made? 
2. What information must a user provide to make a payment?
3. How long do payments take? 
4. Does it cost anything to make a transfer using this payment method? 
5. Is the payment method only for people with a bank account in Puerto Rico?
6. How easy or difficult is fraud with this payment method?
7. What is the minimum or maximum amount you can send with this payment method?
8. When you receive a payment what information about the other party do you see? name, email, phone number etc?

Many thanks :)

**Comment by btcpuertorico** [comment]
Hi @pazza83 :

    How easy is it to cancel / reverse / chargeback a payment once it's made?
Its extremely difficult and I would say non existent . Haven't heard of any case. 

    What information must a user provide to make a payment?
You only need the phone number of the other person.  

    How long do payments take?
Instant.

    Does it cost anything to make a transfer using this payment method?
Free for individuals.

    Is the payment method only for people with a bank account in Puerto Rico?
Yes. Banks and Credit Unions.

    How easy or difficult is fraud with this payment method?
Very difficult. Unless inside job or security breach by Evertec.

    What is the minimum or maximum amount you can send with this payment method?
$1-$500 per day.

    When you receive a payment what information about the other party do you see? name, email, phone number etc?
You receive email confirmation with name, phone number and amount transferred.

Thank you!

**Comment by pazza83** [comment]
Thanks @btcpuertorico for all the info. very useful. I have opened a new issue opened here for discussion: [Add ATH Móvil as a new payment method (Popular payment service in Puerto Rico) #238](https://github.com/bisq-network/growth/issues/238)
