### ISSUE TITLE
Add Payeer Payment Method

### ISSUE THREAD

**Issue by alfsbs** [bisq-network/bisq#1874]
@alfsbs commented on [Fri Apr 27 2018](https://github.com/bisq-network/bisq-desktop/issues/1523)

Requirements verification:

Web: payeer.com
Chargeback risk: Very low
Privacy protection to other peer: High
Mandatory data for a transaction: Amount and Payeer accout, email or phone no.
Duration: Instant
Region: CIS countries
Fees: High
Verifiable: https / TLS Notary
Fraud risk: Low
Conclusion: Include

@ManfredKarrer should we go on with its implementation?

**Comment by alfsbs** [comment]
# Introduction
 
Payeer is the 7th most used payment method in the top 6 countries with offers in LBTC. https://github.com/bisq-network/roles/issues/38#issuecomment-402697563
 
# Requirements verification
 
**Web**: Chargeback risk
**Chargeback risk**: Very low
**Privacy protection to other peer**: payeer.com
**Mandatory data for a transaction**: Account, email or mobile nr
**Duration**: 1-4 days
**Region**: CIS countries
**Fees**: High
**Verifiable**: TLSNotary
**Fraud risk**: Low
**Conclusion**: Include
 
# Implementation information
 
**Similar payment method**: Revolut
 
## Setting up National Currency Account
 
**Payment Method**: Payeer
**Account, email or mobile nr**: **
**Supported currencies**: RUB, USD, EUR
**Limitations**: **
**Salt for account age verification**: **
**Account name**: **
 
## Create offer to buy BTC
 
**Enable use of Payeer
No other changes necessary.
 
## Create offer to sell BTC
 
**Enable use of Payeer
No other changes necessary.
 
## Buying/Selling BTC
 
The buyer of BTC only needs to know the email, account or mobile phone number of the seller. All other instructions should be the same as Revolut.
BTC Seller only needs to know the buyer’s email, account or mobile phone number and trade ID

**Comment by ripcurlx** [comment]
Might be still useful to add, so I removed the stale label.
