### ISSUE TITLE
Add Qiwi payment method

### ISSUE THREAD

**Issue by alfsbs** [bisq-network/bisq#1875]
# Introduction
 
Qiwi is the most used payment method in Russia LBTC
 
# Requirements verification
 
**Web**: Qiwi.com
**Chargeback risk**: Very low
**Privacy protection to other peer**: High
**Mandatory data for a transaction**: Mobile Nr.
**Duration**: Instant
**Region**: CIS countries
**Fees**: Low
**Verifiable**: TLSNotary
**Fraud risk**: Low
**Conclusion**: Include
 
# Implementation information
 
**Similar payment method**: Revolut
 
## Setting up National Currency Account
 
**Payment Method**: Qiwi
**Mobile phone no.**: **
**Supported currencies**: RUB, USD
**Limitations**: **
**Salt for account age verification**: **
**Account name**: **
 
## Create offer to buy BTC
 
**Enable use of Qiwi
No other changes necessary.
 
## Create offer to sell BTC
 
**Enable use of Qiwi
No other changes necessary.
 
## Buying/Selling BTC
 
The buyer of BTC only needs to know the mobile phone number of the seller. All other instructions should be the same as Revolut.
BTC Seller only needs to know the buyer’s mobile phone number and trade ID

**Comment by ripcurlx** [comment]
Might be still useful to add, so I removed the stale label.
