### ISSUE TITLE
Dev of payment methods: Serve, Payeer, Qiwi and Advcash

### ISSUE THREAD

**Issue by alfsbs** [bisq-network/bisq#1877]
Qiwi https://github.com/bisq-network/payment-methods/issues/15
Payeer https://github.com/bisq-network/payment-methods/issues/14
Serve https://github.com/bisq-network/payment-methods/issues/7
Advanced Cash https://github.com/bisq-network/payment-methods/issues/17

**Comment by ManfredKarrer** [comment]
Removed Halcash from list as it is already implemented.
