### ISSUE TITLE
Adding cash deposit bank information alert

### ISSUE THREAD

**Issue by alfsbs** [bisq-network/bisq#1878]
For cash deposits in the US, you need to know the bank name before(!) you initiate the the trade. If the buyer has to proceed with trade, has her BtC funds locked, only to find out that the bank to deposit cash to is not in her area, then that situation creates a problem -> trade needs to be cancelled etc…

The only way to see the info (if provided) is to go t “Buy BTC” screen, under “Payment Method” hover over (but do not click) the “i” (info) button

@ManfredKarrer do you think it would be convenient and practical to implement an alert in cash deposits when taking an offer such as the following?

> Please confirm that <bank name> operates in your area

**Comment by ManfredKarrer** [comment]
Good catch.
I will add the bank ID to the offer details and show a popup when a user takes a SELL offer for cash deposit and show the bank ID in the offer as well let the user confirm that he can access the bank branch in his area. 
For taking a BUY offer it is not possible to cover that as the maker (the BTC buyer) does not know who will take the offer and where he needs to deposit the funds. Maybe we need to disable to create buy offers for cash deposit?

**Comment by ManfredKarrer** [comment]
<img width="1196" alt="screen shot 2018-05-10 at 13 27 13" src="https://user-images.githubusercontent.com/1449498/39867595-e272ec70-5455-11e8-93bb-edf0d8c5e9b5.png">

**Comment by ManfredKarrer** [comment]
The Bank ID is usually the BIC code. The bank name is not part of the offer so that cannot be displayed. That would require changes in the offer payload data. But I hope the BIC is enough...

**Comment by ManfredKarrer** [comment]
Yes I don't disable it and the handling need to be improved. Though will not make it to the upcoming release (prob. tomorrow). But can be added to next release....
