### ISSUE TITLE
Update instructions for Monero transaction proof

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1885]
Seems that Monero has changed the way how a sender can proof his payment. In the latest GUI wallet there is the tool to do that. We need to update our popup text where we explain what is needed.

**Comment by ManfredKarrer** [comment]
It is a small task but would be nice if one experienced with Monero can do that.
I suggest a bounty of 30 BSQ for it.

**Comment by ManfredKarrer** [comment]
<img width="816" alt="screen shot 2018-11-05 at 09 05 25" src="https://user-images.githubusercontent.com/1449498/48002594-fc497e00-e0d9-11e8-82cd-fea221dc88d5.png">

**Comment by KanoczTomas** [comment]
It is fairly easy with the gui, one has to go to history and click on `P`, it will show the payment proof for the tx. Double click on the generated proof and it gets to the clipboard.

**Comment by KanoczTomas** [comment]
@ManfredKarrer if some screenshots would help I am setting up a testnet node for monero just now and can do some screenshots with some steps. Either the text will have a link to a github howto file with steps (which could be updated separately) or the release will have the images in it. The steps are super easy though, not sure if it is really needed. Let me know.

**Comment by ManfredKarrer** [comment]
We need written (simple formatted) text as otherwise its more effort to add it the popup in the app...

**Comment by KanoczTomas** [comment]
"Go to `History` tab, click on the sent transaction. Make sure details are shown for it (press `down arrow` on the right, if details are not shown). Click on the `P` button above the `?` button to generate the proof. Double click on the generated proof to get it to clipboard. Note that the proof as well as the txid is needed for correct verification."

**Comment by ManfredKarrer** [comment]
Implemented with #1902

**Comment by KanoczTomas** [comment]
@ManfredKarrer what does this mean from the bounty standpoint?
