### ISSUE TITLE
tor blocked in china,  i can use tor browser with proxy in china, but bisq does not has such configuration

### ISSUE THREAD

**Issue by longlu** [bisq-network/bisq#1887]
tor blocked in china,  i can use tor browser with proxy in china, but bisq does not has such configuration

**Comment by longlu** [comment]
i use tor browser without problems because tor browser allow me to add proxy before i use it.

but bisq does not have such option.  it won't with just bridges in china, i'll need also add proxy there.

Bisq need to add that configuation like tor browser

**Comment by longlu** [comment]
i use tor browser without problems because tor browser allow me to add proxy before i use it.

but bisq does not have such option. it won't  work with just bridges in china, i'll need also add proxy there.

Bisq need to add that configuation like tor browser

**Comment by longlu** [comment]
Tor browser works in china because it has configuration for me to add proxy , I use shadowsocks, so i add 127.0.0.1 socks5. before I user tor browser.

Bisq does not has such option. so it won't be able to connect in china.

**Comment by ManfredKarrer** [comment]
You can use plugable transports. Open settings/network and there is the tor settings. As well at startup after 4 min not able to connect it opens the tor settings. obfusc4 should work best.
