### ISSUE TITLE
Update legacy assets with proper AddressValidator

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#1896]
I have split this into a separate issue from https://github.com/bisq-network/bisq/issues/1815#issuecomment-433112999.

A lot of legacy assets are using the deprecated DefaultAddressValidator which provides very basic and insufficient validation (non-null and non-empty). Any new asset implementations are required to provide their own AddressValidator implementation. To bring these legacy assets up to date and in order provide proper validation, they should be updated with an appropriate AddressValidator.

However, as part of https://github.com/bisq-network/bisq/pull/1861, a majority of these legacy assets will be delisted. So will need to review this once all untraded assets have been delisted.

**Comment by ripcurlx** [comment]
@devinbileck Feel free to take this bounty 😄

**Comment by devinbileck** [comment]
@ripcurlx There is a bounty for this? But feel free to assign it to me, I can take a look when I get a chance.

**Comment by ripcurlx** [comment]
@devinbileck You've just added a bounty label on it 😄

**Comment by ManfredKarrer** [comment]
@devinbileck Bounties are more for attracting new devs. Its always hard to estimate in advance value of those, so as you are already a experienced Bisq contributor I think its easier if you just work on it and request based on your efforts.

**Comment by niyid** [comment]
Hello @devinbileck 

Is this being worked on? I can "help". :-D

**Comment by devinbileck** [comment]
@niyid No I have not looked into this. Feel free to take over :)

**Comment by niyid** [comment]
For clarification; I believe the requirement is to do a check for references to the deprecated `DefaultAddressValidator` and replace those instances with more functional address validators. Correct?

I do not have to wait for the asset delisting do I?

**Comment by devinbileck** [comment]
> For clarification; I believe the requirement is to do a check for references to the deprecated DefaultAddressValidator and replace those instances with more functional address validators. Correct?

Correct.

> I do not have to wait for the asset delisting do I?

No.

**Comment by niyid** [comment]
Thanks Devin. I will get right on it.

**Comment by niyid** [comment]
Thanks Devin. You may reassign to me, please.

Regards.

**Comment by devinbileck** [comment]
I am unable to assign you. Would need @ripcurlx or @sqrrm to do that. But I have unassigned myself.

**Comment by niyid** [comment]
Great. Thanks for letting me know.

**Comment by niyid** [comment]
Hi @ripcurlx 

Can you please assign this task to me?

Regards.

**Comment by sqrrm** [comment]
@niyid assigned
