### ISSUE TITLE
Resolve deprecated method in gradle-witness prior to moving to Gradle 5

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#1897]
Before moving to Gradle 5, we will need to resolve the following deprecated method in gradle-witness:
```
> Configure project :desktop
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_50pvy62xio1vz17f8pklhdf32.run(C:\Users\Devin\Documents\GitHub\devinbileck\bisq\desktop\build.gradle:18)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
```

It is a [known issue](https://github.com/signalapp/gradle-witness/issues/22) that is still outstanding.

We may want to consider alternatives to gradle-witness since its last activity was Nov 2014. I found https://github.com/matthewtamlin/retrial as a potential candidate, which states:

> Retrial was created to address the unresolved issues in Open Whisper Systems' gradle-witness plugin, and to provide a more convenient means of storing dependency checksums.

However, @cbeams mentioned the following in https://github.com/bisq-network/bisq/issues/1815#issuecomment-435598615:

> This is a really easy problem to solve, and we're already working from my fork of gradle-witness, so we might want to just patch this one as well instead of moving to something entirely different.
> 
> Per the commit comment at 27cc933, the gradle-witness.jar we're using today is built from the PR at signalapp/gradle-witness#26 (which comes from my fork). So we can just further patch the code there, issue another pull request to the canonical repository (to be good citizens), and rebuild and check in the new jar.

**Comment by devinbileck** [comment]
@cbeams I have resolved the issue and opened a PR in the canonical repo (https://github.com/signalapp/gradle-witness/pull/28). How would you like to proceed with integrating the fix from both of our PR's?

**Comment by cbeams** [comment]
Thus far, my fork of witness has been the bisq-network's de-facto fork, but I guess now we should actually create a fork in the bisq-network org and then merge those two PRs into it. The canonical witness repo is, I believe, now totally unmaintained. I submitted my PR there just for good measure, so others could see it, etc. At this point, I expect neither of ours will ever be merged. So we can just create our own, more official fork for Bisq.

... I've just set this up at https://github.com/bisq-network/gradle-witness, and the master branch there now has merge commits from both our forks, i.e. now contains both our patches. So you can build from there and put together a PR that adds the updated resulting `gradle-witness.jar` etc. Please include the commit hash that you built witness from in your commit comment that updates the jar. Do a `git log --follow` on gradle-witness.jar to see how I documented this when adding it originally.
