### ISSUE TITLE
BTC/USD and BTC/EUR trades showing up as BTC/BTC

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#1909]
I'm running my arbitration client against current `HEAD` of the `master` branch (fa911e96ed18bfb0214a441be8c00434fd3cd68f) and seeing what are actually BTC/EUR or BTC/USD trades showing up as BTC/BTC trades.

When I build and run the client against the `v0.8.0` tag, these trades show up correctly, and I know they showed up correctly even a few days ago as well (I've been rebuilding and running against master for the last week or so).

![image](https://user-images.githubusercontent.com/301810/48309977-86379200-e585-11e8-9a08-d47370957108.png)

![image](https://user-images.githubusercontent.com/301810/48309979-8f286380-e585-11e8-991f-5dac21360a7f.png)

Perhaps this has something to do with the recent changes around asset listing?

**Comment by cbeams** [comment]
This behavior is also showing up in the Market->Trades UI:

![image](https://user-images.githubusercontent.com/301810/48310704-85a5f800-e593-11e8-9254-fcc1b3ce6333.png)

**Comment by ManfredKarrer** [comment]
It is probably related to the change in chang ein isCuryptoCurrency. I will have a look.
