### ISSUE TITLE
trouble taking and offer

### ISSUE THREAD

**Issue by gusgg** [bisq-network/bisq#1916]
I'm getting an error when trying to take and offer in CAD. It seams that the open offers get continually disconnected, but it's strange since there are at least 4 of them.

![captura de pantalla 2018-11-13 a las 12 01 55 p m](https://user-images.githubusercontent.com/29762203/48434068-5f708b80-e73e-11e8-8df8-38ae9fcd2c39.png)

**Comment by ripcurlx** [comment]
@gusgg Do you experience the same problem in version v0.9+?
