### ISSUE TITLE
Sellers can place offers

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#193]
This feature is currently implemented but has been disabled in anticipation of buyers being able to take offers that sellers have placed (#192).

**Comment by cbeams** [comment]
Per today's call with @ManfredKarrer, let's re-enable this functionality for v0.1, such that buyers have something to browse (#188). Otherwise, they would sit in front of a perpetually empty list in the "Buy" panel.

**Comment by ManfredKarrer** [comment]
I disabled the take offer in the Buy BTC screen, as the trade process is not implemented for that. We show a info warning.
