### ISSUE TITLE
Potential path seperator issue

### ISSUE THREAD

**Issue by freimair** [bisq-network/bisq#1932]
I just stumbled over a piece of code hidden in the netlayer dependency:
```
return File(workingDirectory, "/$DIR_HS_ROOT/$hsDir")
```
Seems to me as if that might only do as intended in non-Windows environments. However, if I fix that, Windows users might loose their Bisq ID and reputation.

Do we have any Windows users which can tell us the directory structure of the Bisq working directory?

**Comment by ghost** [comment]
Not sure if this helps:
Windows 7,8,10: Windows 7,8,10: C:\Documents and Settings\username\AppData\Roaming\Bisq 
Windows XP: C:\Documents and Settings\username\Application Data\Bisq 

I guess the structure should be the same as Mac/Linux inside the directory ? But maybe I'm wrong.

(I'm not a windows user)

**Comment by freimair** [comment]
Thanks for your reply, however, the interesting part would be the structure inside the directory. That is where "/" (unix-based) vs "\\" (Windows) comes into play.

The structure within should look something like
```
...
- Bisq
  - btc_mainnet
    - ...
    - tor
      - ...
      - hiddenservice
```
and NOT something like
```
...
- Bisq
  - btc_mainnet
    - ...
    - tor
      - ...
    - tor/hiddenservice/
```

If the latter is true, we cannot only fix the issue because we would break stuff for Windows users...

**Comment by ManfredKarrer** [comment]
Oh if that is true we cannot change that easily. It would break not only local reputation but the user could not be reached with existing offers/trades/disputes anymore. 
A fix could be that on windows we copy over the to the correct path the data and in a few versions when we can assume that all active users have updated we remove the old code.

**Comment by devinbileck** [comment]
Thankfully, Windows recognizes the forward slash as a path separator so this is not an issue.
And just for confirmation, the structure on Windows is:
```
- Bisq
  - btc_mainnet
    - tor
      - hiddenservice
```

**Comment by freimair** [comment]
Nice, well then, I am off to fixing the "bug" in Netlayer...
