### ISSUE TITLE
Add community page on site

### ISSUE THREAD

**Issue by btcll** [bisq-network/bisq#194]
I've been working on content for the Community Page on the website. Would appreciate if you could let me know if anything is missing or needs modification:
http://dev.bitsquare.io/community/

I intend to use the GitHub API to show the team members direct from GitHub on this page, but that's new for me so decided to hold off until after the rest of the website is done. If anyone has done it before then let me know and I'll add it, but I think that's low priority for now.

**Comment by cbeams** [comment]
Hey @btcll, I'm migrating some issues across repositories. See bitsquare/site#1, where this lives now.
