### ISSUE TITLE
Show info about single altcoin account when taking offer

### ISSUE THREAD

**Issue by joachimneumann** [bisq-network/bisq#1949]
When I create a new offer to but altcoins, e.g., MXR (sell BTC), Bisq shows the first 6 characters of the Monero address to which the funds will be transferred:
<img width="554" alt="screenshot 2018-11-22 at 11 49 33" src="https://user-images.githubusercontent.com/5642225/48882460-034bec80-ee4d-11e8-81d8-8c066b864a80.png">

If a user takes an offer and has more than one altcoin trading account, he will be presented with a dropdown list to select the altcoin account:
<img width="593" alt="screenshot 2018-11-22 at 11 58 48" src="https://user-images.githubusercontent.com/5642225/48882682-1ca16880-ee4e-11e8-920d-3781ad031459.png">

However, when a user takes an existing offer and has only set up a single altcoin account, Bisq shows only general Payment info without specifying the e.g., Monero address to which the funds will be transferred:
<img width="586" alt="screenshot 2018-11-22 at 11 49 19" src="https://user-images.githubusercontent.com/5642225/48882473-1d85ca80-ee4d-11e8-93cd-f2d72c05f7ce.png">

This can be confusing if the user wrongly assumes that he will be able to specify the Monero address at a later point of time. Especially if the user has created a Monero altcoin account just for testing without having saved the seed words. 
Showing the first 6 characters of the Monero address also in this case (single account, taking offer) would prevent users from making wrong assumptions about the point of time at which the altcoin address is selected.

**Comment by ripcurlx** [comment]
@joachimneumann Thanks for pointing this out.
What you see above is the default payment account name for any payment account. We truncate the string (mostly account number) after 10 characters, but it can also be customized by the user. Still it is true that it would be good to show the payment account name in the Payment method field. I'll have a look at it today.

**Comment by ripcurlx** [comment]
I'm now showing for Altcoins the account name in the payment method field if there is just one 
![bildschirmfoto 2018-11-22 um 11 20 42](https://user-images.githubusercontent.com/170962/48896798-cb42aa80-ee48-11e8-9302-49c20a7fcaa0.png)
and for Fiat accounts I left it with the payment method name, as I don't think we have the same issue there as well.
![bildschirmfoto 2018-11-22 um 11 20 55](https://user-images.githubusercontent.com/170962/48896796-cb42aa80-ee48-11e8-904a-8dc7592d89d8.png)
@ManfredKarrer what do you think?

**Comment by ManfredKarrer** [comment]
Great @ripcurlx that you fixed that so quickly. I would do the same for Fiat. The account name should give more information than the payment method only.

**Comment by ripcurlx** [comment]
![bildschirmfoto 2018-11-22 um 12 25 48](https://user-images.githubusercontent.com/170962/48900117-cafadd00-ee51-11e8-8aca-93ffb9343216.png)
Ok, I'll do it the same for both payment method types.

**Comment by aejontargaryen** [comment]
looking great @ripcurlx
