### ISSUE TITLE
Bisq crasheswhile processing TKE order

### ISSUE THREAD

**Issue by Tharrso** [bisq-network/bisq#1968]
I clicked the TAKE OFFER button. I paid the fees. Then I got this error message:
>>An error occurred when taking the offer.
A timeout occurred.
The taker fee is already paid. In the worst case you have lost that fee.
Please try to restart your application and check your network connection to see if you can resolve the issue.Please try to restart your application and check your network connection to see if you can resolve the issue.<<

I can certainly restart Bisq and check my network connection, but how does that resolve the issue?

**Comment by ghost** [comment]
If it is possible, you can bring your failed trade to arbitration with CMD+O .

**Comment by ManfredKarrer** [comment]
@Tharrso You can ask for reimbursement of the lost fee at https://github.com/bisq-network/support/issues/

**Comment by ManfredKarrer** [comment]
The reason for the issue is probably that the peers computer was in app nap mode (on OSX at least we know there are issues). We fixed that with the upcoming release.

**Comment by Tharrso** [comment]
I get a message from Bisq this morning that "You have locked up funds from a failed trade.
Locked up balance 0.005BTC. ..."
And it gives the deposit address and the trade ID. And it asks me to open a support ticket.
Yet when I look at the trade in my OPEN TRADES tab it seems to be progressing normally. I.e. it sees that payment has been started and it is waiting for payment to be received by the seller.
Do I 
![warning2](https://user-images.githubusercontent.com/44954997/49031228-3b5d7300-f15e-11e8-814b-de2c9d85caa5.png)
need to do anything?

**Comment by ManfredKarrer** [comment]
Seems like a false alarm...
