### ISSUE TITLE
BUY order not progressing

### ISSUE THREAD

**Issue by Tharrso** [bisq-network/bisq#1977]
A week or so ago I posted an offer to buy BTC. It looks like that offer was taken yesterday, but it has not progressed. 
![imuviopentrade](https://user-images.githubusercontent.com/44954997/49049839-8cd52480-f195-11e8-96f7-da172b3c67f2.png)
I have not been asked to make a payment or notified of blockchain confirmation. Please see the two attached screenshots.

What to do?

**Comment by ghost** [comment]
... I think it's not a very good idea to post screen copies with private details, furthermore details of the trading partner.
Usage is to erase private informations.

**Comment by Tharrso** [comment]
OK.
But what about this trade?

**Comment by ghost** [comment]
There is a time limit for all trades.
If the trade is still in the limit, and not failed or stucked yet, you have to wait till the time limit is reached.
If there is no technical issue (timeout etc), I expect the trading partner to conclude.

**Comment by Tharrso** [comment]
I this case how will I know that the time limit is reached? There is no countdown like there is when I take a SELL offer. It has been three days and nothing has changed on the OPEN TRADES tab.

**Comment by ManfredKarrer** [comment]
Hi @Tharrso 
The take offer attempt has failed and there was not created a deposit transaction. If you open the 2 trade fee transactions you see that the second output which would be used as input for the multisig deposit tx are unspent. 
There is a UI glitch that such failed take offer attempts are not removed automatically. You can try to open a dispute and tell the arbitrator that there was no deposit tx created, so his payout tx is irrelevant but it will trigger that your trade gets closed. 
You can check also if the wallet balance is correct by opening the emergency wallet tool with cmd+e and see if the balance displayed there matches the sum of availabel + reserved balance in your UI.
If you have furher questions you can contact me at manfred at bitsquare dot io.

**Comment by ripcurlx** [comment]
Closing as complete. @Tharrso Feel free to reopen if you still experience this issue.
