### ISSUE TITLE
Failed transaction costs

### ISSUE THREAD

**Issue by Tharrso** [bisq-network/bisq#1986]
This evening I took an offer and paid the deposit etc. However, the next step failed because the seller's computer was offline or they were away from it for too long.
In my TRANSACTIONS tab I don't see any mention of a "Taker and Tx fee" for this transaction.
Was any BTC actually taken for this failed transaction? If so, how do I get it back?

**Comment by ManfredKarrer** [comment]
@Tharrso Can you send me by email (manfred at bitsquare dot io) more concrete information? Was that the trade you posted in another GH issue?
