### ISSUE TITLE
0.9.0: When naviagting to Account seedword popup is shown

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1994]
The navigating to the account menu the fiat account screen is shown by default. But the other sceens from the tabs like seedword get called the activate method and there the popup is triggered to ask if the user want to sho the seed word.
Yoou might need to reset the "dont show again" flags to reproduce it. Each time you navigat there it shows the popup. Not sure if that is also in the master version but might be.

**Comment by ripcurlx** [comment]
It looks like all views that where loaded already get the activate call when switching to the Parent View section. I'll have to dig deeper in the code to see how this activation calls are structured.

**Comment by ripcurlx** [comment]
Found the issue. We need to remove the content from the previous tab, when a new one is selected. Otherwise they will be activated when switching between parent views.
