### ISSUE TITLE
External Tor features does not announce its hidden service

### ISSUE THREAD

**Issue by freimair** [bisq-network/bisq#2010]
When testing my external Tor implementation yesterday (during the testing of the 0.9 release candidate) I found, that in its current implementation, jtorctl does not announce a freshly generated ephemeral serivce to the Tor network.

Has been fixed in #2009, however, as jitpack is behaving kind of funny (jitpack/jitpack.io#3572), that fix is not ready to be included into Bisq as of now.

I recommend taking the
```- [Enable use of external Tor services](https://github.com/bisq-network/bisq/pull/1935)```
off the list of new features, until this issue gets closed by myself.

**Comment by ManfredKarrer** [comment]
Sometimes jitpack does not pick up a new version. Adding another dummy commit most time resolves that.
