### ISSUE TITLE
Reason field missing from 'Close Ticket' arbitration screen

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#2029]
In the redesigned UI just merged to master, there is no longer a reason field in the 'Close Ticket' arbitration screen, i.e. the radio button that indicates whether the dispute was due to a bug, a protocol violation, a bank issue, etc.

Was it intentional to leave this out? We hadn't been using it for anything so far, but it was a useful exercise for me to categorize disputes with it anyway. It helped me think about the right course of action. And the data could at least potentially be put to good use in the future.

I don't feel strongly about bringing it back; I just want to know if omitting it was intentional or not.

**Comment by ManfredKarrer** [comment]
I just added it a bit before. Can u pull and check again?

**Comment by ManfredKarrer** [comment]
Was not intentional....small bug caused it...

**Comment by cbeams** [comment]
Closing as fixed, thanks.
