### ISSUE TITLE
Update from 0.8.0 to 0.9.0 new bisq doesn't start at all

### ISSUE THREAD

**Issue by Onefox** [bisq-network/bisq#2037]
Well, after I downloaded and updated to v0.9.0 the program doesn't even start any more...
Mouse cursor starts spinning and nothing happens, no process is running.
I have Windows 8.1 Pro and v0.8.0 was working fine...
No AV running.
Are there any log files anywhere that I can check?

I uninstalled and reinstalled it and rebooted windows.

**Comment by ManfredKarrer** [comment]
There are some know issues with windows.

Can you try to backup your data directory and then delete  the app data directory or uninstall the Bisq app. Then re-install again. If you uninstall the data directory gets deleted as well, so if you used Bisq before you need to move over your backup directoy.

Another reason can be AV software. Some are deleting files from the installation or data directory.

Another is that at installation time the AV software stops Tor and then there is a pending locked file which cannot be deleted by another process. An OS restart resolves that.

All those issues are known since a while but happen not often. If you are a developer and experienced with Windows, maybe you can help to get those fixed.

**Comment by ManfredKarrer** [comment]
Yes log file is in data directory.

**Comment by Onefox** [comment]
I had no AV running.

The log file only shows the download process and than a normal looking shutdown. (the bisq.log file in the roaming bisq folder).

After I cleared the roaming folder and started bisq It worked again. Than I stopped it and removed the new generated btc_mainnet folder and copied my backup into place and got all data back. So its running again now.

Now its working again...
Is there anything that could help analyse the behavior?

ps.: sadly I don't have experience with developing for windows :/

**Comment by ManfredKarrer** [comment]
Ah good! We did not had time to dive deeper to investigate.... Most Bisq devs don't use Windows...

**Comment by sethforprivacy** [comment]
I'm also having this issue -- cannot open 0.9.0 at all after updating. Here is the output of the log file after downloading the new version and attempting to install it:

https://paste.fedoraproject.org/paste/vTCwMuRlyZVy2kLjRfi~ig

**Comment by ManfredKarrer** [comment]
@GoodEn0ugh Whcih OS? Can u post full logs?

**Comment by sethforprivacy** [comment]
W10 -- I backed up C:\Users\<username>\AppData\Roaming\Bisq, uninstalled Bisq, and reinstalled, and it started right up.

**Comment by sethforprivacy** [comment]
[bisq.log](https://github.com/bisq-network/bisq/files/2641766/bisq.log)

**Comment by izzytdi** [comment]
Same problem here Windows 10.  Can not longer build from source either. gradle gives error:

bisq.core.app.BisqHelpFormatterTest > testHelpFormatter FAILED
    java.lang.AssertionError at BisqHelpFormatterTest.java:132

Commenting out this line allows build and program to run, maybe this is involved?

**Comment by ManfredKarrer** [comment]
Just added to the release notes description and solution for Windows installation problems.
https://github.com/bisq-network/bisq/releases/tag/v0.9.0

## Installation instructions
### Windows:

There are some known issues (not introduced in that release) with installing Bisq on Windows.
The Windows installer does not cleanup or overwrite always correctly the old installation files. If you cannot start Bisq after installation please delete the application directory [1] (not the data directory! [2]). You could also try to uninstall Bisq from the operating system but then the data directory (including your wallet and account data) will be deleted as well. If you want to use the uninstall option be sure to have made a backup first and move the backup afterwards to the data directory location.

Another issue can be Anti Virus software. We got several reports from users running into different problems. Either the AV software blocks Bisq or Tor, delete files in the data directory or app directory) or cause such a long delay at startup that Tor gets terminated and a file remains locked which can cause that Bisq cannot be started afterwards. To resolve that you need to restart Windows then the lock get released. We are working on solutions to fix those issues.

If you use Crypto currencies on your Windows system be aware that Windows is much more vulnerable to malware than Linux or OSX. Consider to use a dedicated non-Windows system when dealing with cryptocurrencies.

[1] Application directory (contains application installation files):
C:\Users\AppData\Local\Bisq

[2] Data directory (contains all Bisq data including wallet):
C:\Users\AppData\Roaming\Bisq

**Comment by Previncoin** [comment]
"After I cleared the roaming folder" what do you mean? please be more specific, the "roaming folder" contains many applications.

**Comment by ManfredKarrer** [comment]
The Bisq folder inside the roaming...

**Comment by Quenos** [comment]
Hi Manfred,
Your post with the work around is not precise enough.
If you have the bug on Windows, you need to delete, or even better rename, the following directory:

C:\Users\\\<username>\AppData\Local\Bisq

Then install Bisq with the installer file, and for me this did the trick.

**Comment by Previncoin** [comment]
I removed C:\Users<username>\AppData\Local\Bisq, disabled Windows Defender, shut down Malwarebytes  Free, re-installed BISQ 0.9.0 & it worked. Transaction history looks OK wallet balance seems about right (will have to check), interface is better, text is more readable. (Win 8.1)

Thanks for support.

**Comment by ManfredKarrer** [comment]
@Previncoin I think the app directoy is the main issue. AV software should mostly work with Bisq but we got some reports from time to time that they flag is as false positive.

**Comment by ripcurlx** [comment]
Related to #2066.

**Comment by ripcurlx** [comment]
@ManfredKarrer 
I guess you mean with 

> [1] Application directory (contains application installation files):

**C:\Users\AppData\Local\Bisq**

and not

**C:\Users\AppData\Roaming\Bisq**

You used the same directory path twice.

**Comment by ManfredKarrer** [comment]
Ups, yes was wrong. I updated it.

**Comment by ripcurlx** [comment]
Closing as complete in 0.9.1.
