### ISSUE TITLE
'Extra Requirments' field in Cash Deposit Account not visible prior to accepting.

### ISSUE THREAD

**Issue by headblock** [bisq-network/bisq#2038]
Have upgraded to .9 and have a cash deposit offer created from previous version. The 'Extra Requirements' text is no longer visible to a user prior to accepting the offer.  Have not done any further testing, can provide more detail if needed.

**Comment by ghost** [comment]
Thanks for reporting.

**Comment by ripcurlx** [comment]
@headblock Just to confirm: Where exactly was this displayed before? I just looked at the info popup on the offer and there it wasn't shown before.

![bildschirmfoto 2018-12-04 um 16 10 26](https://user-images.githubusercontent.com/170962/49451298-3001eb80-f7df-11e8-89d0-84a1cd5c6091.png)
![bildschirmfoto 2018-12-04 um 16 09 42](https://user-images.githubusercontent.com/170962/49451299-309a8200-f7df-11e8-9436-24697b6651e4.png)

**Comment by ripcurlx** [comment]
I just found the extra requirements on both client versions during the purchase process. Is there another place where it was shown before? 
![bildschirmfoto 2018-12-04 um 16 17 29](https://user-images.githubusercontent.com/170962/49451772-2f1d8980-f7e0-11e8-834c-3a4ac522518f.png)
![bildschirmfoto 2018-12-04 um 16 17 20](https://user-images.githubusercontent.com/170962/49451774-2fb62000-f7e0-11e8-9e62-77ace4a26e88.png)
![bildschirmfoto 2018-12-04 um 16 14 40](https://user-images.githubusercontent.com/170962/49451775-2fb62000-f7e0-11e8-9e4a-19612d46ddbd.png)
![bildschirmfoto 2018-12-04 um 16 14 34](https://user-images.githubusercontent.com/170962/49451776-2fb62000-f7e0-11e8-9eff-42730f4b567c.png)

**Comment by ripcurlx** [comment]
There was an unnecessary scrolling when using CashDeposit with a requirement field, which I just fixed, but I think you mean something different.
![bildschirmfoto 2018-12-04 um 16 40 48](https://user-images.githubusercontent.com/170962/49453437-6477a680-f7e3-11e8-9492-2dbe9a8675e4.png)

**Comment by headblock** [comment]
Thanks for checking. I think i made a mistake, sorry! I created a test offer on older version i have and the extra requirements text is not their either.
I must have remembered incorrectly how its displayed, i thought you can see the extra requirements text before taking the offer, but this doesn't seem to be the case. Sorry about that.
