### ISSUE TITLE
"Enabled" header doesn't change with language setting

### ISSUE THREAD

**Issue by initCCG** [bisq-network/bisq#2040]
Under Portfolio>My Open offers, the "Enabled" column header doesn't change to a different language when it's set.
It  doesn't exist in the translation strings set. 

Other headers, such as "Type of offer" next to it change.

Is "Enabled" hard coded for some reason?

**Comment by ManfredKarrer** [comment]
Not all strings are translated yet....

**Comment by initCCG** [comment]
All except 2 long shitcoin strings are translated in Russian.
There is no "Enabled" string in the translation file.
