### ISSUE TITLE
Elements within open trades view partially obstructed

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2041]
Potentially another display scaling issue (related https://github.com/bisq-network/bisq/pull/1945), but column headers along the top and buttons along the bottom are partially being obstructed in the open trades view.
![image](https://user-images.githubusercontent.com/603793/49423848-9dfdd280-f74d-11e8-803c-7f4b3039e66b.png)

This is on a Windows 10 laptop with a 13-inch 1920x1080 display and using 150% display scaling. As a result, it has a usable resolution (maximum screen bounds) of 1280x660 (accounting for the height of the Windows task bar).

There is a vertical scroll bar, but does not allow the buttons to be scrolled fully into view.

**Comment by ManfredKarrer** [comment]
Maybe we can move mining fee to trade fee:
Something like: 
Fees: 0.00005 BTC (trade fee) /  0.0008840 BTC (mining fee)

**Comment by ripcurlx** [comment]
@ManfredKarrer Good point! I'll do that to save some space for scaling setups.

**Comment by devinbileck** [comment]
Should still look into this.
