### ISSUE TITLE
Issue with input validation in create offer view

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2044]
When creating an offer, after entering amount of BTC to buy I put the cursor in the minimum amount of BTC box and the USD amount box showed error text but not below % box. If I then click in the below % box the values get filled in and the error text remains.
![image](https://user-images.githubusercontent.com/603793/49424464-87587b00-f74f-11e8-8648-8ea02bb534f8.png)

**Comment by ripcurlx** [comment]
@devinbileck I'll give it a try. Unfortunately the validation dependencies and logic is quite complex on this screen. Maybe now it is a good time to untangle this parts a little bit.

**Comment by cbeams** [comment]
This relates to #3715.
