### ISSUE TITLE
Differing status of transactions being confirmed between maker, taker, and arbitrator

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2045]
After mentioning this to @ManfredKarrer, he clarified the confirmation is only available for the transactions of your own wallet. The peers transaction is unknown to you and BitcoinJ does not know the confirmation state.

However, as it is shown, this is confusing and I have wondered in the past why my trading peers transaction has not been confirmed. It would be ideal to have a UI solution. Even if that involves showing an icon indicating it is unknown.

Maker:
![image](https://user-images.githubusercontent.com/603793/49424764-6e9c9500-f750-11e8-91d9-2bcb97ce9c0a.png)

Taker:
![image](https://user-images.githubusercontent.com/603793/49424773-752b0c80-f750-11e8-98b8-cd671a9d9d2f.png)

Arbitrator:
![image](https://user-images.githubusercontent.com/603793/49424786-7e1bde00-f750-11e8-8f06-2b692bd5f590.png)

**Comment by ManfredKarrer** [comment]
We should find an icon representing the information that the confirmation state for the peers transaction is unknown (as expected).

**Comment by ripcurlx** [comment]
@pedromvpg Could you come up with an icon for this use case?

**Comment by ManfredKarrer** [comment]
I think that should still be kept open.
