### ISSUE TITLE
Trade contract JSON data does not correspond to the values shown in the trade details

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2046]
Could be my lack of experience and knowledge, but I am having trouble understanding the numbers shown in the trade details. In the contract JSON it shows a txFee and makerFee but I don't see how that corresponds in the trade details view. The maker fee appears to be the txFee?
![image](https://user-images.githubusercontent.com/603793/49425697-45c9cf00-f753-11e8-9202-62e8919b8392.png)

**Comment by devinbileck** [comment]
Should still investigate this.

**Comment by huey735** [comment]
@devinbileck I've been investigating the JSON too and I've deduced that "makerFee" corresponds to the the offer maker trading fee and that "txFee" corresponds to the offer maker on-chain fee for the "Make offer" transaction. Of these two only "txFee" shows in "Trade details" under "Mining fee". The taker's mining fee is = maker txFee x 3.

**Comment by devinbileck** [comment]
Thanks @huey735! That makes sense.
