### ISSUE TITLE
Not fetching prices from coinmarketcap

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2047]
For example, TRTL is on coinmarketcap but it doesn't seem to be getting its price.
![image](https://user-images.githubusercontent.com/603793/49426029-1ebfcd00-f754-11e8-86a1-91d31619fc41.png)

**Comment by ManfredKarrer** [comment]
Maybe ticker symbol is different?

**Comment by ghost** [comment]
apparently, it's the same (TRTL):
https://coinmarketcap.com/currencies/turtlecoin/

**Comment by devinbileck** [comment]
```
Dec-04 23:28:08.592 [JavaFX Application Thread] INFO  b.c.p.price.PriceFeedService: We don't have a price for currency TRTL. priceProvider=http://174.138.104.137:8080/. That is expected for currencies not listed at providers. 
Dec-04 23:28:08.594 [JavaFX Application Thread] INFO  b.c.p.price.PriceFeedService: Received new data from provider http://174.138.104.137:8080/ after 0.465 sec. Requested market price for currency TRTL was not provided. That is expected if currency is not listed at provider. 
```

**Comment by ghost** [comment]
The json result of http://5bmpx76qllutpcyp.onion/getAllMarketPrices
just doesn't mention TRTL.

**Comment by bobbyong** [comment]
Hi guys have you tried CoinGecko's free API?
Here is an endpoint for TRTL/USD - https://api.coingecko.com/api/v3/simple/price?ids=turtlecoin&vs_currencies=usd

**Comment by ManfredKarrer** [comment]
Ah I think the price nodes need to be updated...

**Comment by ghost** [comment]
@bobbyong ,
Thanks for the link.

**Comment by ghost** [comment]
@ManfredKarrer wrote:
> Ah I think the price nodes need to be updated...

Does this mean that the currency codes are hardcoded in the pricenode code ?

**Comment by ripcurlx** [comment]
> Hi guys have you tried CoinGecko's free API?
> Here is an endpoint for TRTL/USD - https://api.coingecko.com/api/v3/simple/price?ids=turtlecoin&vs_currencies=usd

Hi @bobbyong! I just wanted to give your Google Spreadsheets add-on a try, but I didn't find a way to access historical market data (e.g. exchange rate at a certain day). Does the add-on support this somehow?

**Comment by ripcurlx** [comment]
Closing as complete. Fixed by updating the price nodes.
