### ISSUE TITLE
Use mono space font in tables or sans

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#2054]
Besides bug fixes I'm trying to finish off the last couple of design changes that didn't make it into 0.9.0 for 0.9.1.

As I wasn't 100% sure in Slack how the final decision was, I wanted to quickly raise it here again.
We are using mono to improve the spacing and have the numbers in some tables properly aligned under each other. This has the effect, that we have some tables with Mono and some with Sans content. As these two fonts look quite different it sparked the discussion a couple of times within the existing contributors.

IBM Sans
![IBM-Sans.png](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/96e7893c-2cc8-44c0-95cc-1f9b3bb73374)
IBM Mono
![IBM-Mono.png](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/a9265251-1685-4b2c-89c7-a142c13c2935)

I was previously for using a Mono font because of the spacing issue. But as I now think the perfect alignment improves less the usability than the distraction caused due the different fonts, I'm also fine just use the regular IBM Sans in all tables.

@pedromvpg What do you think?

**Comment by ManfredKarrer** [comment]
I find IBM Sans fits much better to the other fonts.
