### ISSUE TITLE
Win32/Cloxer.D!cl trojan found in 0.9.0 installer.

### ISSUE THREAD

**Issue by xianglo** [bisq-network/bisq#2057]
Please close this issue if this is a typical randomizer that Windows defender may find disagreeable. My download was hash checked.

**Comment by devinbileck** [comment]
Hmm. I am not encountering that. Are your definitions up to date?
I also ran it through VirusTotal and it came up clean: https://www.virustotal.com/#/file/6f3753d269f4906da664a1948cb9593b72a0bf5a033e20bd4ce9265f6e892f2b/detection

**Comment by ripcurlx** [comment]
AVG Anti Virus also didn't complain when I checked all files included in the release.

**Comment by ManfredKarrer** [comment]
Would be nice to have that check at https://www.virustotal.com be integrated in the build process (beside doing the manual check with avg).

**Comment by devinbileck** [comment]
They provide a free public API that can be used: https://www.virustotal.com/en/documentation/public-api/
Should be as simple as:
```
curl -v -F 'file=@/path/to/file' -F \
  apikey=${VT_API_KEY} https://www.virustotal.com/vtapi/v2/file/scan
```

**Comment by ManfredKarrer** [comment]
@ripcurlx Can you try it out in the 0.9.1 release?

**Comment by xianglo** [comment]
I had defender delete it and havent had ny problems using 0.9.0. Im only booted into Windows temporarily. Ill keep an eye.
![screenshot 2](https://user-images.githubusercontent.com/224958/49567338-62a10680-f8fb-11e8-8e32-5a1ebee0cf38.png)

**Comment by ManfredKarrer** [comment]
The probably detect tor and flag is by default as malware....

**Comment by ManfredKarrer** [comment]
Close it as it is a false positive
