### ISSUE TITLE
Apply styling to Windows system tray application menu

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2058]
In Windows when I right click the application icon in the system tray, it appears to be using a boring generic Java style menu. Would be nice if we could apply styling with the new colour scheme.
![image](https://user-images.githubusercontent.com/603793/49496602-3a41db00-f81b-11e8-9a1c-3cda331166ad.png)

**Comment by ripcurlx** [comment]
@devinbileck If you want to tackle this one as well yourself, let me know and I'll assign you.

**Comment by devinbileck** [comment]
@ripcurlx Sure I can give it a shot. Not exactly sure how to implement it, will have to do some research.

**Comment by ManfredKarrer** [comment]
On OSX most apps use the OS default as we do. Don't know how its on Windows but would not see that as high priority... Maybe you can time box it...

**Comment by devinbileck** [comment]
Still planning on looking into this.
