### ISSUE TITLE
DAO cycle display after reorg

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/bisq#2064]
After generating 10 blocks and then causing a reorg from the 4th of those blocks the cycle display got messed up.

![image](https://user-images.githubusercontent.com/23560607/49522614-5b9cd880-f8a8-11e8-9b51-8d8f5f2b8071.png)

**Comment by sqrrm** [comment]
This is probably due to the reorg handling which is exactly what I'm reviewing, shouldn't have created an issue about it, just wanted to have a log to what happened to the phase handling when it got messed up.

**Comment by ManfredKarrer** [comment]
Was it correct after a restart? 

To avoid that we need to handle all possible cases we could do following:
If reorg depth < break then it cannot / must not break the consensus/vote result and with that also param changes. So we can ignore that there are changes and we need to adjust all to reflect that. 
If reorg depth >= break then we reset from genesis, with that all params and all get reset as well (new empty DaoState object).

**Comment by sqrrm** [comment]
It looks better but I think it's still not correct. Running two instances and they have a different view of the cycle after reorg+restart.

**Comment by ManfredKarrer** [comment]
I could not reproduce an issue with reorgs. If you manage to reproduce please re-open.
