### ISSUE TITLE
Unexpected content in summary message when a support ticket gets closed

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2065]
When a support ticket gets closed, there are a few items in the summary message that the arbitrator did not have a chance to specify:
![image](https://user-images.githubusercontent.com/603793/49529622-49507980-f86b-11e8-831d-c73868662501.png)

Apparently there used to be a checkbox for them in the Close Ticket screen, but they are no longer shown:
![image](https://user-images.githubusercontent.com/603793/49529632-50778780-f86b-11e8-9039-46dad5142c92.png)

No idea if the checkbox should be added again or the summary message updated to remove those items.

**Comment by ManfredKarrer** [comment]
Ah yes that is missing. @ripcurlx Maybe similar issue as with reason radio buttong (was missing increment in rowIndex).

**Comment by devinbileck** [comment]
Should still look into this.
