### ISSUE TITLE
Add EOS coin

### ISSUE THREAD

**Issue by wenk2018** [bisq-network/bisq#2069]
Really need this to do anonymous smart contracts.

**Comment by ripcurlx** [comment]
@wenk2018 If you are a developer you could follow following process to get EOS listed: https://docs.bisq.network/exchange/howto/list-asset.html

If not, you could still check if all pre-conditions are fulfilled and gather the required information here, so someone could pick it up to implement.

**Comment by ripcurlx** [comment]
Also as it was just pointed out on Slack by @meapistol, you need to check if EOS would qualify as a security, as there is a current listing stop for all securities on Bisq.

> Please note: Bisq will not list your token if it has taken part in an initial coin offering (ICO). Given the uncertain regulatory treatment of such tokens, [Bisq stakeholders determined](https://github.com/bisq-network/proposals/issues/58) they are currently too much of a legal risk for the project.

**Comment by ackza** [comment]
EOS is not a security, SEC even made that clear with letter of no action so we are good :) Dont make us create a new better bisq!
