### ISSUE TITLE
UI: suggestions for 'DAO -> Governance -> Browse open proposals' page

### ISSUE THREAD

**Issue by BravoIndia** [bisq-network/bisq#2071]
In version 0.9.0 under DAO -> Governance -> Browse open proposals

#1: The following red rectangle area is quite confusing and unintuitive upon first use:

![image](https://user-images.githubusercontent.com/33473721/49564311-a6c0f500-f955-11e8-9929-0da9c9f674f4.png)

I suggest putting the title "My vote" in the area highlighted below:

![image](https://user-images.githubusercontent.com/33473721/49564348-c8ba7780-f955-11e8-8382-290dd2ccf3b0.png)

#2: There should be a confirmation button upon choosing a vote, and perhaps a pop up message box (e.g. "You're about to change your vote to: Accepted. Are you sure?")

#3: If in the 'Link' column, the entered text is not a URL, the following pop-up should not appear: 

![image](https://user-images.githubusercontent.com/33473721/49564774-564a9700-f957-11e8-8ea8-3c14fb626032.png)

#4: It also may be good to change "Open the web page and don't ask again" to "Open the web page" and include a "Don't ask again" checkbox (which will apply to either selection if checked, so those wanting to simply copy don't need to click repeatedly either).
For example:

![image](https://user-images.githubusercontent.com/33473721/49564834-927df780-f957-11e8-8d9f-af8265b63762.png)

**Comment by devinbileck** [comment]
Good suggestions!
2. I wonder if another popup is really necessary? It is simple enough to undo or change your vote afterwards.
3. May actually want to add input validation and only accept URL links, rather than random text. I recall seeing some errors in the debug log when a proposal was not a URL.

**Comment by BravoIndia** [comment]
Thank you,
2. I agree, it doesn't have to be a popup. But if not, there should at least be a confirmation button, no? 
I was thinking that changing a vote on a proposal should take more than one click, to prevent accidentally changing a vote on a certain proposal without noticing (while looking at others, for example).
3. Makes sense. @ManfredKarrer mentioned in his [post](https://bisq.community/t/how-to-explore-the-dao-on-testnet/6692) that "we don’t want to spam Github with entrties for testing purposes". If non-URL are done away with, maybe we can use other sites during testing?

**Comment by devinbileck** [comment]
2. Thats true, confirmation may be useful.
3. Yeah I think just using random links should be good enough for testing, whether that be to existing GitHub proposals or whatever link you want to put in there.

**Comment by ManfredKarrer** [comment]
@BravoIndia Thanks for the suggestions! Basically agree to all beside the confirmation popup for vote change, but no strong opinion on that (if at least with a dont show again) - but generally we want to avoid popups if not absolutely needed as there are already way too many.

I think a final confirmation with overview screen would be good like at create offer the final confirm window with all data. Then the user should see if his votes have been as intended. 

Do you have a suggestion for Re 1?

Yes links are not validated yet but we could handle the exception to not log. I think its the only place in Bisq where user can edit the URL so on other places its exceptional that a URL does not work.

Re 3: Yes agree would be good to use more realistic situation. Maybe we also can create a dao-testing repo which gets deleted later? Or any other idea for a place where its easy without extra registration to post links? Maybe pastebin?

**Comment by ManfredKarrer** [comment]
@BravoIndia  Great thanks by the way for the videos! Helps a lot for psotting the issue!

**Comment by sqrrm** [comment]
1. Agree
2. I don't like popup, but perhaps some kind of indication that a vote was changed could be good
3. We could create one issue for proposal testing and just add a comment in the issue and link to that one

**Comment by sqrrm** [comment]
I have fixes for the header and jumping vote icons on scrolling.

Still not sure what's the better way to show a changed vote, I'm thinking something like changing the background color of the vote for 10s after clicking to change the vote. Then it's obvious that the vote was recently changed but not too annoying.

**Comment by ManfredKarrer** [comment]
@sqrrm Great that u fixed the scroll issue! The animations use in checkboxes of the redisigned version might be useful. Bit not sure if its easy to implement. Would focus on higher prio stuff atm...

**Comment by BravoIndia** [comment]
All good ideas, thank you everyone. @sqrrm Great thought to change the background color for 10s after a vote change, and thank you for implementing the header and jumping vote icon fixes!
