### ISSUE TITLE
DAO: Critical UI bug; changing vote on one proposal changes other proposal

### ISSUE THREAD

**Issue by BravoIndia** [bisq-network/bisq#2072]
See in the screen capture below, it stats half way through the video.
As I change my vote in one proposal, others change:

https://streamable.com/6ihnt

I've been unable to determine under what conditions I'm able to replicate this bug, but it has happened a few times, usually changing the vote on the proposal directly below the one I'm clicking on.

I've seen it change at least from:
-  Accepted -> ignored
- Accepted -> Rejected (when changing the one above from accepted to rejected)
- Rejected -> accepted (when changing the one above from accepted to rejected)
- Rejected -> Ignore (when changing the one above from accepted to rejected)
- Ignored -> Rejected (when changing the one above from rejected to ignored)
- Ignored -> Rejected (when changing the one above from ignored to accepted)

**Comment by BravoIndia** [comment]
Some replication:

https://streamable.com/9xzrv

Perhaps this can provide some hints.

**Comment by devinbileck** [comment]
I saw this occur as well just from scrolling in the proposal window where my vote would randomly change on proposals.

**Comment by ManfredKarrer** [comment]
Thanks for reporting! I will look into it. I assume the table rows are not updated correctly at scrolling and so the vote change triggers the wrong data.

**Comment by ManfredKarrer** [comment]
@BravoIndia That bug finding is subject to the bounty program! So dont forget to ask for BSQ end of the month!

**Comment by ManfredKarrer** [comment]
Just had a quick look to the video and I am pretty sure its a scrolling/update issue. Will look into fixing it the next days.

**Comment by ManfredKarrer** [comment]
@BravoIndia  Great thanks by the way for the videos! Helps a lot for psotting the issue!

**Comment by BravoIndia** [comment]
@ManfredKarrer Glad to be of help!

**Comment by ManfredKarrer** [comment]
@sq fixed that with https://github.com/bisq-network/bisq/pull/2094
