### ISSUE TITLE
Clicking cancel at seedword screen password popup casue blank popup 

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2083]
If a password is set and you got to seedwords view and click cancel you get a blank popup. Not 100% sure how to reproduce.... maybe you need to switch first to another main screen and then go back to account with seedwords as selected tab...
<img width="1116" alt="screen shot 2018-12-07 at 00 17 15" src="https://user-images.githubusercontent.com/1449498/49617586-7c9f1f80-f9b5-11e8-885d-101b8f01e64b.png">

**Comment by ManfredKarrer** [comment]
The activate method is called twice. I think the problem lies in the parent class (Account). We prob. use still the codebase from the submenu version pre 0.9 and it might require some changes there to treat tabs differently.

**Comment by ripcurlx** [comment]
I've problems reproducing this bug on current master. Are you still able to reproduce it?
