### ISSUE TITLE
DAO: Typo in prompt when attempting to pay asset listing fee and trial period is less than 30 days

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2086]
There is a typo ("perios" -> "period") in the prompt that appears when you attempt to pay an asset listing fee and trial period is less than 30 days:
![image](https://user-images.githubusercontent.com/603793/49619343-11cbf500-f971-11e8-97d6-d986650afa98.png)

**Comment by ripcurlx** [comment]
Closing as complete.
