### ISSUE TITLE
DAO: Inform user that proposals cannot be submitted while not in the proposal phase

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2087]
When not in the proposal phase, you are unable to make a proposal (the proposal type dropdown is disabled).
![image](https://user-images.githubusercontent.com/603793/49614810-45eaea00-f960-11e8-99e5-97a331d4f98e.png)

As a usability improvement, it would be nice to show a message informing the user that they have to wait for the next proposal phase to submit a new proposal.

**Comment by BravoIndia** [comment]
Totally agree, confused me too at first.

**Comment by ManfredKarrer** [comment]
Yes good point.
Any UI deve helping out here? I need to focus on the stability/security area atm.
