### ISSUE TITLE
Error java.io.IO ?

### ISSUE THREAD

**Issue by MrDyh** [bisq-network/bisq#2088]
I wanted to update version 0.8.0 to version 0.9.0 of the software but it was a failure. So I thought I would uninstall my current version of Bisq for the new one and that's what I did. However I have a problem to import my seed from my previous wallet (created in version 0.8.0).

<a href='https://www.casimages.com/i/181207090906496299.png.html' title='Mon image'>Lien vers mon image</a> 

I'm told it's just a rename error so I tried to rename manually, but without success also.

Someone have a issue ?

https://www.reddit.com/r/bisq/comments/a3nwxw/error_javaioio/

**Comment by ManfredKarrer** [comment]
Which OS do you use? Windows? The code probably miss the special handling for windows...
I assume beside the error popup it does not has any effect but would need more time to investiage/test...

**Comment by MrDyh** [comment]
> 
> 
> Which OS do you use? Windows? The code probably miss the special handling for windows...
> I assume beside the error popup it does not has any effect but would need more time to investiage/test...

Hi ManfredKarrer ! Yes I'm windows user..
In the meantime is there any other software on which I can get my BTC ? because it's a private key with multiple public addresses that's it? I don't know how it works^^

**Comment by ManfredKarrer** [comment]
You don't need to import the seed words. The problem you have is related to the issue that the windows installer does not delete the old files in the application directory. See https://bisq.community/t/bisq-v0-9-0-released/6694/15?u=manfredkarrer for more details.
After you have done that just use the latest Bisq data directory to run with 0.9.0. Make a backup (just copy the data directory) before changing anything.

**Comment by MrDyh** [comment]
I know what you mean, but I don't think it's going to work with me. 
I specified in my first message that I had uninstalled Bisq 0.8.0, uninstalled at 100% (included data directory)...
I have no choice but to import the seed, you confirm ?

**Comment by ManfredKarrer** [comment]
Did you made a backup once? If you have no backup then you need to restore from seedwords. I just checked the code and it uses specail handling for Windows. But anyway that error message is not critical and the restore was applied despite the error popup. 
Can you check if you can open Bisq after the restore? If so is the balance as expected? If not please check with cmd+e at the emergency wallet window if the balance there is as expected.

**Comment by ripcurlx** [comment]
@MrDyh Where you able to restore your wallet from seedwords? If you don't, feel free to re-open this issue.

**Comment by camenlx** [comment]
how to restore "ALL" from a backup? (wallets, portfolio offers, options, and so on...)
I also cannot restore 'all' wallet from seeds in a new pc windows ...
why have a backup dir saved if one cannot restore from such a dir?!
