### ISSUE TITLE
DAO: Confusing warning when adding more days to asset trial period

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2092]
When trying to add 7 more days to the trial period to CHA which I previously added 99 days
![image](https://user-images.githubusercontent.com/603793/49680712-92abef00-fa4c-11e8-9eae-a900c3614a24.png)

I encounter this error
![image](https://user-images.githubusercontent.com/603793/49680717-a22b3800-fa4c-11e8-9dd2-20463bea185c.png)

I am a little confused with this. Either it is not checking that it already has 99 days currently or the Pay Fee button should be disabled if you can only pay minimum 30 days at a time (currently is disabled if less than dust amount 5.46).

**Comment by ManfredKarrer** [comment]
Yes the handling of the fee payments is not really completed. I wanted only add min. effort to that area but I am aware that is requires a bit more fine tuning. Any dev want to pick up that? It is not on my prio list.

**Comment by ManfredKarrer** [comment]
@ben-kaufman This task as low prio IMO....
