### ISSUE TITLE
Other parties cannot see offer - bisq 0.9.0

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#2093]
I have entered an offer in Bisq 0.9.0:
Maker as ODN buyer / Taker as ODN seller
BTC amount 0.07 BTC
ODN amount 137254
...
Offer ID 35834409-a32706ce-250d-4f4d-94ee-f9a397484e11-090
...
Everything looks good, however, other parties cannot see this offer and perform the trade.
Any ideas? What could be wrong here?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/29592708/49684277-1825b280-fad2-11e8-9983-c743778685ae.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/29592708/49684385-9040a800-fad3-11e8-81b3-25fd7e799d89.png)

**Comment by ghost** [comment]
also, it appears that soem parties can see ODN in the Altcoins list, while others can not. Those who don't see it cannot add a trading account for the coin.

**Comment by ghost** [comment]
one question would be if a downgrade to v 0.8.0, where that worked, would fix the issue, or if this is a user error or something else.

**Comment by ManfredKarrer** [comment]
Obsidian was removed as it was not traded. The basic requirement for asset listing states that not traded coins will be removed after 4 months.

**Comment by ghost** [comment]
Ahh! Hm ok, that's sad. But it was actually traded and there were also orders that were just not filled. So one can stll use v0.8.0? Will it be re-included if it gets over the threshold..?

**Comment by ghost** [comment]
btw, is it possible to get the Bisq market displayed on coinmarketcap.com? That would make the opportunity to trade on Bisq more visible.

**Comment by ManfredKarrer** [comment]
Yes old clients can still use it and old offers are still valid. Open offers are not considered for trade activity, only real trades. 

I close that. Please feel free to continue discussion on the Forum.

**Comment by ghost** [comment]
thank you very much, awesome support!
