### ISSUE TITLE
portfolio screen - cannot edit offer - Error  No value present

### ISSUE THREAD

**Issue by RickMGoldie** [bisq-network/bisq#2110]
On first attempt to edit the offer I get the no value present Error popup. Subsequent attempts to click it produce no reaction. 
This offer has been running for about a month with no takers and it was a fixed price offer which is now overly generous, and I would like to amend it.
it is offering to sell 1000 Burst coin for 0.00012 BTC. 
TX id : 6clio-226c3498-bc8e-4001-84f1-9a735108f999-070
Can this be seen still or is it corrupted somehow?
I don't want to lose the escrow or market makers fee by cancelling and starting again.
Log file attached.
[bisq_log.txt](https://github.com/bisq-network/bisq/files/2667891/bisq_log.txt)
Note. the offer was created on the previous version to the current as there has been an update in the interim. 
MacOs High Sierra. 
Mac mini.
Richard Goldsmith

**Comment by RickMGoldie** [comment]
I noticed the option to delete SPV file and resync, which I did, but problem still persists upon restart exactly as described above.

**Comment by ManfredKarrer** [comment]
I don't find Burst coin neither in the code or a PR. When was it added. Was probably removed due lack of trade activity. There is a missing check in the code which cause that exception if the currency is not found.

**Comment by RickMGoldie** [comment]
I did a burst transaction in the summer.
It is still showing burst in the list of possibles.

**Comment by ManfredKarrer** [comment]
Version 0.9?

**Comment by ManfredKarrer** [comment]
What is the tickersymbol, I dont find anything with "burst"

**Comment by RickMGoldie** [comment]
It is an altcoin. Bisq allows trades between BurstCoin and BitCoin based on
Poloniex exchange rates.

Tx volume is low which is why I’m looking to trade on bisq as timing is
not of the essence. It worked last time round in July.

As I cannot edit the offer, I am concerned that prospective takers cannot
even see it.

Regards,
Richard

**Comment by RickMGoldie** [comment]
Yes, Version 0.9.
I think The Ticker is BURST that is how it shows in the offers screens etc.

**Comment by RickMGoldie** [comment]
I have capitulated and cancelled the offer.
I have tried to register on Poloniex and persevered this time and now verified. I will trade on there.

**Comment by ghost** [comment]
BURST does no more appear in v0.9.1
and was indeed candidate for deactivation -> https://github.com/bisq-network/proposals/issues/41

**Comment by ripcurlx** [comment]
As we can't do anything about that I'm closing this issue.
