### ISSUE TITLE
Accepted offer failed to execute, went through anyway but never happened.

### ISSUE THREAD

**Issue by buzztiaan** [bisq-network/bisq#2112]
i accepted a offer, funded the bisq wallet from external wallet, funded the offer from bisq wallet, and then:

```
An error occurred at task: SellerAsTakerCreatesDepositTxInputs
Exception message: org.bitcoinj.core.InsufficientMoneyException: Insufficient money,  missing 0.011xxx BTC
```

while the actual TX that bisq sent for the trade offer acceptance actually -did- have a 0.011xxx BTC output. 

later on restarting numerous times i get the 0.011xxx back in wallet and log file messages like

`Dec-11 19:24:34.433 [JavaFX Application Thread] WARN  b.core.offer.OpenOfferManager: We found an outdated addressEntry for openOffer RSExxx-xxx-xx-x-x-x-x`

**Comment by buzztiaan** [comment]
trade state now being in 'TAKER_FEE_PUBLISHED' , can i just continue then?
(just checked, nope that wants me to pay the taker fee again)

this interface could really get a 'history' tab ...
(ah, my trade history is hidden in portfolio -_-)

**Comment by buzztiaan** [comment]
retried later , made sure i had -more- inside wallet then needed, instead of exact amount, and didnt hit the same error, trade executed well

**Comment by ManfredKarrer** [comment]
@buzztiaan Seems a bug caused that the reserved funds for the trade got released incorrectly. Have u updated to 0.9? If not tomorrow is a new release, please update, there are many bug fixes. If you have more problems like that please check out  https://bisq.community/t/how-to-switch-to-a-new-data-directory/6753/

**Comment by ManfredKarrer** [comment]
If you lost the trade fee you can request reimbursement here: https://github.com/bisq-network/support/issues/

**Comment by buzztiaan** [comment]
i used 0.9 , it seems the bug has to do with one of these msgs;

 WARN  b.c.b.w.BisqRiskAnalysis: TX considered non-standard due to unknown version number 2 
 WARN  o.b.w.Wallet: Pending transaction was considered risky: Risky due to non-standard tx

either that, or it was just the fact that my bisq wallet held exactly what i needed for the transactions, no extras

**Comment by ManfredKarrer** [comment]
@oscarguindzberg - do you think it can be related to the "version number 2" issue?

**Comment by oscarguindzberg** [comment]
Posting "version number 2" bug here for clarity #1832.
When a user funds the bisq wallet from external wallet with a "version 2 tx":
- "TX considered non-standard due to unknown version number 2" is printed on the log.
- Onstead of the bisq wallet receiving the funds right away (when the tx is broadcasted), the funds are received (and displayed on the UI) when the tx is included in a block (~10 minutes later). 

My first guess is the InsufficientMoneyException is caused by the bisq wallet having exactly the amount it has to send (0.011xxx) and then being unable to pay the tx fee (aka miner fee) of the funding tx.

**Comment by ripcurlx** [comment]
@ManfredKarrer Should this issue still be kept open?

**Comment by ManfredKarrer** [comment]
@ripcurlx Maybe it is related to the other issue with InsufficientMoneyException?

**Comment by ripcurlx** [comment]
@ManfredKarrer Yes, could be. I'll have to dig deeper into the trading process anyways because of #2305. Let's see if I find something suspicious on the way.
