### ISSUE TITLE
Missing checks at DAO Bonds confiscation 

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2123]
A already confiscated Bond can still be confiscated in the next voting round. The Summary of confiscated bonds also counts up here, so the check to not confiscate an already confiscated bond is probably missing in the domain layer.

**Comment by sqrrm** [comment]
I have a fix for this, PR coming

**Comment by ManfredKarrer** [comment]
@sqrrm is that already fixed? If not are you working on that?

**Comment by sqrrm** [comment]
There is a PR waiting for merge at https://github.com/bisq-network/bisq/pull/2242/ which solves this.
