### ISSUE TITLE
Offer book currency dropdown shows all currencies rather than just those that I have specified under Settings > Preferences

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2129]
Under Settings > Preferences, I have limited the national currencies and altcoins that I want displayed:
![image](https://user-images.githubusercontent.com/603793/50025862-ced6d680-ff9b-11e8-930a-f9def78d5915.png)

Yet all currencies are shown in the offer book currency dropdown:
![image](https://user-images.githubusercontent.com/603793/50025873-d39b8a80-ff9b-11e8-9077-a808e507235e.png)

Additionally, it is hard to locate a particular currency because it is sorted by open offers rather than alphabetically.

**Comment by ManfredKarrer** [comment]
That is intended behaviour but I agree its confusing and should be re-worked usability wise. 
The currency list is only used in the list at the Buy/Sell screens.

You can switch in the settings between sorting by trades/offers and alphabetically.

**Comment by devinbileck** [comment]
Ah, OK. I just found that sorting option in the settings. Thanks!
