### ISSUE TITLE
Trade take fail on taker's price and PeerAddress null

### ISSUE THREAD

**Issue by initCCG** [bisq-network/bisq#2130]
Taker has new install 0.9.1. Couldn't take offer with error:

![takererr1](https://user-images.githubusercontent.com/40746153/50038335-ec488680-0015-11e9-8c0a-f4212ddd676f.png)

On maker side, also 0.9.1 with errors:

![makererr1](https://user-images.githubusercontent.com/40746153/50038337-1601ad80-0016-11e9-80d0-72aa2736e294.png)
![makererr2](https://user-images.githubusercontent.com/40746153/50038339-1b5ef800-0016-11e9-8c9c-e88debbfe007.png)
![makererr3](https://user-images.githubusercontent.com/40746153/50038340-2023ac00-0016-11e9-841d-ad7a18e1b133.png)

Where should we send the log?

**Comment by ripcurlx** [comment]
@ManfredKarrer Can be that this is related to the new market price check that was introduced with 0.9.1?

**Comment by ripcurlx** [comment]
@initCCG Could you send me the logs per DM in Slack or Mail? I'll have a look at it.

**Comment by mmhh1910** [comment]
I'm seeing the same problem.

**Comment by ripcurlx** [comment]
The exception was triggered by the rounded fiat value popup and it somehow caused a nullpointer exception in the JavaFX framework, while running a depth test logic. @initCCG Do you see other popups without any problems? To show again all warning popups you could go to settings > preferences > "RESET ALL "DON'T SHOW AGAIN" FLAGS" 
Which OS are you running? Just want to confirm as I found a bug reports with the same problem https://bugs.openjdk.java.net/browse/JDK-8197547, https://bugs.openjdk.java.net/browse/JDK-8205092

**Comment by ripcurlx** [comment]
@initCCG Do you have the "Use animations" toggle activated?

**Comment by initCCG** [comment]
@ripcurlx Yes, other popups show ok.
Taker OS was Win10, maker Ubuntu 16.04
Yes, Ubuntu has Use animations on.
We'll check with taker.

**Comment by initCCG** [comment]
@ripcurlx Taker animations were off.

**Comment by initCCG** [comment]
@ripcurlx FYI: Our testers just completed a VND trade with the same setup using 0.9.3. So, seems either you fixed it in 0.9.3 or it was a transient bug for us.
Thank you very much.
