### ISSUE TITLE
Improve spinner performance

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#2135]
The default spinner implemented by the JavaFX framework causes high CPU load. We want to use/implement an improved version that causes less unnecessary load.

![Bildschirmfoto 2018-12-18 um 10.34.48.png](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/2e243a91-8c34-4aa5-acee-5f98b291d3c8)

**Comment by dreboli** [comment]
Is there any way to remove it manually or work around it somehow?

I can't fund any transaction because my PC hangs when that spinner is present. Opening my wallet app on the desktop is impossible.

**Comment by ghost** [comment]
@dreboli ,
what is your Bisq version ? what is your OS ?

**Comment by dreboli** [comment]
Latest v0.9.3 Bisq
Ubuntu 18.04.1
11.5GB memory
AMD® Athlon(tm) ii x4 630 processor × 4
AMD® Rs880 graphics

**Comment by ripcurlx** [comment]
@dreboli Do you have this issue on app startup? It could also be that this is because of the synchronization task that runs in the background and consumes quite a lot of CPU if you don't start Bisq every now and then. So it might not be the spinner that causes your problem, but something else that just uses the spinner for visualizing that something is going on in the background.

**Comment by dreboli** [comment]
At startup only the app gets slow, the enter your password window pops up but there's no prompt cursor, can't write there for a while I can use other programs in the meanwhile.

After taking an offer there's a tab with details about BTC address and amount I have to send to using an external wallet or the Bisq wallet.
My whole system hangs there, CPU load jumps from 25 to 75%, have to click several times on an icon to open an app etc.

I started using a new Bisq data directory with a new wallet but the problem still present.

**Comment by dreboli** [comment]
v0.9.4 seems to be much quicker, my system doesn't hang where it used to anymore.

**Comment by cd2357** [comment]
> v0.9.4 seems to be much quicker, my system doesn't hang where it used to anymore.

Closing, as the OP said the issue was fixed by a subsequent release.
