### ISSUE TITLE
DAO: Some table headings act like links (color change on hover) but do not load the browser when clicked

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2139]
![image](https://user-images.githubusercontent.com/603793/50182846-3dca6d00-02c5-11e9-9a28-84121d5c2c69.png)

![image](https://user-images.githubusercontent.com/603793/50182875-55095a80-02c5-11e9-99a8-4be54155e820.png)

**Comment by ManfredKarrer** [comment]
@ripcurlx 

In TableGroupHeadline we set the `highlight` style which causes that the headline is green and on rollover gets black. Is that intended? I would need it without that rollover effect as that looks like a interactive link.

 `private void setActive() {
        setId("titled-group-bg-active");
        label.setId("titled-group-bg-label-active");
        label.getStyleClass().add("highlight");
    }`
