### ISSUE TITLE
DAO: My vote weight is not factored into the quorum amount

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2140]
While reviewing vote results, my vote weight is not factored into the quorum amount:
![image](https://user-images.githubusercontent.com/603793/50183548-4e7be280-02c7-11e9-88f4-ede73e364b67.png)

**Comment by ManfredKarrer** [comment]
Which Cycle was that? Cycle 2? If it was a follow up cycle, I think it was related to the bug there. I checked all valid cycles and quorum are all correct. If you still have that your app, please email me your testnet data directory.

**Comment by ManfredKarrer** [comment]
@devinbileck If you dont have that issue anymore, please close that issue

**Comment by devinbileck** [comment]
@ManfredKarrer Yes it is in cycle 2 (the screenshot above is from the first proposal - christoph bonded role). I will email my data dir.

**Comment by ManfredKarrer** [comment]
@devinbileck Can you still reproduce that? I think it was caused by an older bug and got fixed in the meantime.

**Comment by devinbileck** [comment]
I am no longer encountering this issue.
