### ISSUE TITLE
DAO: Scrolling in the proposal vote results table, My Vote changes thumbs up / thumbs down icons randomly

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2141]
Related to https://github.com/bisq-network/bisq/issues/2072 / https://github.com/bisq-network/bisq/pull/2094, there are still UI issues with the My Vote column in the proposal vote results table. Scrolling in the table will change the thumbs up / thumbs down icons randomly.
![image](https://user-images.githubusercontent.com/603793/50183864-3b1d4700-02c8-11e9-83c6-0998dc2f5b83.png)

**Comment by ManfredKarrer** [comment]
Noticed that as well. @sqrrm could you have a look? Seems the same issue as the other one at vote screen.

**Comment by sqrrm** [comment]
Yeah, I'll take a look, most likely the same issue.
