### ISSUE TITLE
ticker API doesnt reflect new pairs or their prices

### ISSUE THREAD

**Issue by buzztiaan** [bisq-network/bisq#2142]
As stated :) would be nice to propagate the actual markets in the 'allprices' ticker interfaces, so sites like coinmarketcap et al can parse it and show the markets being actually available.

**Comment by ripcurlx** [comment]
@buzztiaan You're talking about https://markets.bisq.network/api/ticker?

**Comment by buzztiaan** [comment]
yes exactly , as you can see (after adding it) the 'neos-btc' market should have a value , but its not present in that url at all

**Comment by aejontargaryen** [comment]
looks to be v0.8.0 data

**Comment by ripcurlx** [comment]
I'll have a look how this is configured in the markets API. Haven't touched it myself so far, but shouldn't be more than a config issue.

**Comment by aejontargaryen** [comment]
thank you ripcurlx

**Comment by buzztiaan** [comment]
side case, https://markets.bisq.network/api/ticker?market=neos_btc also gives [ null ] as response

**Comment by devinbileck** [comment]
Might be related to https://github.com/bisq-network/bisq/issues/2047

**Comment by ghost** [comment]
indeed,
the json result of pricenodes also doesn't mention NEOS.

**Comment by buzztiaan** [comment]
> Might be related to #2047

i always though the prices inside Bisq only reflected a value on trade inside Bisq
because -my- Bisq node does give a price for NEOS/BTC in that topright menu

**Comment by aejontargaryen** [comment]
wonmp wonmp...:cry: 
https://markets.bisq.network/api/ticker?market=drgl_btc

this is from https://markets.bisq.network/api/#currencies

**Comment by srhii** [comment]
@ripcurlx anything on that issue?

**Comment by ripcurlx** [comment]
@ManfredKarrer will update the configuration file as soon as he is able to (he‘s traveling a lot these days). It needs to be updated in the markets api server.

**Comment by srhii** [comment]
Thanks

**Comment by ManfredKarrer** [comment]
Fixed.
