### ISSUE TITLE
[UI] cannot generate new address if previous is not used

### ISSUE THREAD

**Issue by agyx** [bisq-network/bisq#2149]
Version: 0.9.1

I have one receiving BTC address, unused. I expect a transaction to be done on this address (eg from an exchange) but it is not yet broadcasted.
I want to generate another address in order to send BTC from another source to my bisq wallet.

Expected: I should be able to generate a new address
Observed: I can't because the UI complains the first address is not used.

I have to wait til the first transaction is seen on the first address

**Comment by ManfredKarrer** [comment]
Yes, I agree would be good to allow multiple ones. I had a similar experience myself once.
