### ISSUE TITLE
Grin mimblewimble integration

### ISSUE THREAD

**Issue by 0xb100d** [bisq-network/bisq#2166]
I thought I read that this issue was already opened but haven't seen it.

Grin p2p atomic swaps already exist (see https://713.mw/), integrating into bisq is a whole other matter. I would like to set up a bounty for integration if there is any interest/ability out there to do so. 

The grin (grin-tech.org) mainnet launch is scheduled for january and there will be immediate desire to trade it and the values of decentralization of bisq are in line with grin.

Would love to get a better idea of the challenges involved in integrating new tx format like mimblewimble into bisq.

**Comment by ManfredKarrer** [comment]
@0xb100d Yes would be definitely great, but I fear that is quite a large enterprise. It would require either some RPC interface to a local Grin deamon or a Java implementation of Grin (prob. not available). Then the atomic swap protocol bot both sides of the chains. I would estimate its about 2-4 months dev effort for a high skilled dev.

**Comment by ripcurlx** [comment]
But just to be able to trade Grin like a regular altcoin on Bisq is an effort of a couple of hours.

**Comment by 0xb100d** [comment]
@ManfredKarrer there is already some atomic swap protocol work fortunately, but I realize that is just one component.

**Comment by ManfredKarrer** [comment]
I will close that as there are not plans to work on that in near future. Feel free to continue discussion on the Forum, we just want to keep Github dedicated to code work issues.
