### ISSUE TITLE
Scan files using VirusTotal as part of release process

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2177]
As part of the release process, we should scan files using https://www.virustotal.com in order to ensure that they are not being flagged as false positives.

We should be able to integrate this into the release script. They provide a free public API that can be used: https://www.virustotal.com/en/documentation/public-api/.

**Comment by devinbileck** [comment]
@ManfredKarrer @ripcurlx Feel free to assign this to me. I wanted to enter this as an issue before I forget about it.

**Comment by ripcurlx** [comment]
@devinbileck For this release (v0.9.2) I'll use it manually, but feel free to integrate it into our build process - you are the expert on this now anyhow 😄

**Comment by devinbileck** [comment]
Sure sounds good.
Hah! lol
It should be automated for our next release.

**Comment by devinbileck** [comment]
I am still planning on working on this.
