### ISSUE TITLE
DAO: "Report to github issue tracker" button is broken

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/bisq#2179]
# "Report to github issue tracker" button is broken. 

## What I expected

When I encountered an error on Bisq testnet, I pressed the button "Report to github issue tracker" and expected that my browser would open with relevant information filled in for a new github issue. 

## What actually happened

- When I press "Report to github issue tracker", a new error message window appears instead of taking me to github. FYI, this is not about the exception shown in the screenshots. 

![error msg window](https://user-images.githubusercontent.com/43150241/50513588-8dacef00-0a90-11e9-8320-2631337c256e.png)

The new error message window is not as detailed as the first one. 

![error msg 2](https://user-images.githubusercontent.com/43150241/50513594-9a314780-0a90-11e9-9296-9f5e160ed9b1.png)

**Comment by arunasurya** [comment]
I tried to reproduce this just now when a separate exception appeared but this time the "Report to github issue tracker" button worked. Perhaps the issue was fixed? Feel free to close the issue if so.

**Comment by ripcurlx** [comment]
@arunasurya I think there were two errors triggered right after each other which causes the other error popup to open after the first one was closed. This is the reason why it is working for you, if only one error is triggered.
