### ISSUE TITLE
Missing cycle check at vote reveal tx publishing

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2183]
If a user creates a vote tx and is return online one cycle later at the vote reveal phase the vote reveal tx is created but is invalid as it is the wrong cycle. We should add a check to not publish a tx in such a case.

**Comment by sqrrm** [comment]
I think it would also burn any associated BSQ inputs, I'm going to have a review of the ways we very strictly burn inputs whenever a tx is considered invalid. You can see in https://github.com/bisq-network/bisq/pull/2171/commits/ec5f12dea3ba9f50d1d56e0e706080eb602ac449 how I went over the compensation request issue but more work on that is definitely needed.

**Comment by ManfredKarrer** [comment]
Is fixed already.
