### ISSUE TITLE
Error report (v0.9.1 DAO testnet | multiple errors)

### ISSUE THREAD

**Issue by BravoIndia** [bisq-network/bisq#2186]
I got the following 2 errors when opening the DAO for the first time after switching to testnet (v0.9.1 on Windows). This was just after updating to v0.9.1 from v0.8. 
I'm not sure what went wrong, I had no issues. Please find me log attached as well.

`VoteResultException.MissingBallotException(existingBallots=[], proposalTxIdsOfMissingBallots=[737fca3d494a8e20c45f91f2c7b9f1baffc0a5fc7f0c376530f1d49ef0ad852e, 098577b0e8b5af3ad7371c148b0717b59200cc8e5a8eefbe37ef0e4eb6b4ea56, 9592b77de86b4d333888b7b18e941e0d0c3aaced0421585afd9960b64d366a87, a5dd6bc771f5114c57c4e1895edd547b7133b351daaaeff2ca7091cc9f3441d8, e9c167a94b2b537dc7ced8106c5c6531b8280c2ada2b7b69342957892047a42e, 484525380920a07f5c11f8c1fefb8a818ed0900b7ae11990a99ee5245f62525f, c4f2a4998cd9a6ab0e0da95240c5d35e234c992212cfe73b5e41fb4d8cb1c823])`

`VoteResultException.MissingBallotException(existingBallots=[], proposalTxIdsOfMissingBallots=[098577b0e8b5af3ad7371c148b0717b59200cc8e5a8eefbe37ef0e4eb6b4ea56])`

[bisq.log](https://github.com/bisq-network/bisq/files/2718120/bisq.log)

Interestingly the errors were back-to-back, and the github page didn't appear until they were both closed (as the 'opening url' notice appeared last), so the first one would've been erased from the clipboard by clicking any button on the second one before copying it down elsewhere. 

Multiple errors popping up in tandem might be a contingency worth considering (should the error be saved to a text file instead of copied to the clipboard?)

**Comment by arunasurya** [comment]
I also saw several similar messages and back-to-back. Here is a screenshot for one of them.
[
![frozen screen](https://user-images.githubusercontent.com/43150241/51129038-49a44300-1821-11e9-8617-f336026a13b4.png)
](url)

(I reported the issue being too long separately in #2266).

**Comment by ManfredKarrer** [comment]
@arunasurya Did you delete the daoStateStore file as described in https://bisq.community/t/dao-testnet-testing/6895

**Comment by arunasurya** [comment]
I clicked the button "Rebuild DAO state from genesis tx" (I assume this is the one you refer to when saying "Reset DAO state"). Afterwards, it took several minutes when I tried to go to the DAO tab but then a separate error message appeared. 

![error msg2](https://user-images.githubusercontent.com/43150241/51197282-f85f8680-18e8-11e9-9ab4-565e6b0f2d43.png)

**Comment by ManfredKarrer** [comment]
Ok. can u send me please the db and the wallet so i can debug it. u can try to delete the other dao files as described in the forum link.

**Comment by arunasurya** [comment]
Can you tell me precisely which files to send you or let me know where I can find the instructions?

**Comment by ManfredKarrer** [comment]
https://bisq.community/t/dao-testnet-testing/6895

**Comment by ripcurlx** [comment]
Closing as complete. See @ManfredKarrer's last comment.
