### ISSUE TITLE
Funds - unable to generate new address

### ISSUE THREAD

**Issue by 0xbytes** [bisq-network/bisq#2193]
Bisq does not want to generate a new bitcoin address because the first address has 0 balance. I believe that is the desired action.  The problem is when I import my 12 words from Bisq running on another PC. The first address that is generated does have a balance of 0, but it had a positive balance in the past. Addresses further down the tree that are generated from the 12 word seed do have positive balances. This is not shown.

**Comment by ripcurlx** [comment]
@ManfredKarrer Didn't we have a similar report in the past or was the past one just about the non-ability to generate new addresses if the old ones have still 0 balance?

**Comment by ManfredKarrer** [comment]
It is an intended feature to avoid that too many addresses are generated. But I agree that there are reasons to lift that restrictions. On the todo list but not highest prio....
