### ISSUE TITLE
DAO-Bug

### ISSUE THREAD

**Issue by keo-bisq** [bisq-network/bisq#2209]
Got this: VoteResultException{
     cause=java.lang.IllegalArgumentException: blindVoteTx is not in correct cycle. blindVoteTx.getBlockHeight()=1448992
} VoteResultException{
} bisq.core.dao.governance.voteresult.VoteResultException$ValidationException: Validation of vote result failed.

**Comment by ManfredKarrer** [comment]
Yes there are know issues with current version. Fixed already on master. Please wait for next release before using it further.
