### ISSUE TITLE
Unable  to download javafx-gradle gradle plugin, Travis CI build failing

### ISSUE THREAD

**Issue by notmandatory** [bisq-network/bisq#221]
I think the issue is 46 below:

https://bitbucket.org/shemnon/javafx-gradle/issue/46/received-status-code-401-from-server

**Comment by cbeams** [comment]
@stevemyers, this is "fixed"—see comment in 5f53fea.

**Comment by cbeams** [comment]
And I've commented on the issue: https://bitbucket.org/shemnon/javafx-gradle/issue/46/received-status-code-401-from-server#comment-12929643

Here's a link to one of the failing Travis builds, just for reference: https://travis-ci.org/bitsquare/bitsquare/builds/37779259

**Comment by notmandatory** [comment]
Thanks Chris.
