### ISSUE TITLE
Add payment method "TWINT" (Switzerland)

### ISSUE THREAD

**Issue by 21isenough** [bisq-network/bisq#2214]
TWINT is a payment method, that has become widely popular and is used by more and more people in Switzerland. 

It is still a little complicated and cumbersome to pay with it in stores and e.g. parking meters, but it's already widely accepted online and in the personal realm. It makes the **payment of small amounts between people** simple and smooth.

Would be fantastic to have it integrated into Bisq. 

https://www.twint.ch/en/

_EDIT:_ If needed, I can provide further details - just let me know what information you need.

**Comment by ManfredKarrer** [comment]
@alfsbs Could you have a look?

**Comment by ManfredKarrer** [comment]
Still relevant. We need somone who takes care of payment methods! Any volunteer?

**Comment by 21isenough** [comment]
I think, this is still relevant. Can it be reopened?

**Comment by smagpro** [comment]
It seems TWINT payments are still not possible unfortunately
