### ISSUE TITLE
Failure when trying to build Bitsquare under Eclipse

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#222]
On Oct 13, 2014, at 11:48 AM, @ManfredKarrer  wrote:

> Thomas wanted to run Bitsquare with Eclipse but got problems with Gradle. Any ideas what might be the reason?
> 
> > ```
> > Error while initializing classpath container
> > org.eclipse.osgi.internal.framework.EquinoxConfiguration$1
> > Could not fetch model of type 'EclipseProject' using Gradle distribution
> > 'https://services.gradle.org/distributions/gradle-2.1-all.zip'.
> > ```

**Comment by cbeams** [comment]
See commit comment in f135873 for instructions how to import Bitsquare into eclipse. Alternatively, one may install the Eclipse Gradle tooling from the Eclipse marketplace, and import directly from `bitsquare/build.gradle`, but generating Eclipse metadata (as described in the commit comment) is the most direct route.

**Comment by cbeams** [comment]
Note that the changes in f135873 were tested against Eclipse Luna SR1. I was able to successfully import the project and run `io.bitsquare.BitSquare#main` in order to launch the UI.

**Comment by ManfredKarrer** [comment]
@cbeams Thanks for looking into that so quickly!

**Comment by cbeams** [comment]
Update regarding the mysterious disappearance of version 8.1.1 of the Gradle JavaFX plugin:

On Oct 13, 2014, at 3:29 PM, willbdaniels issues-reply@bitbucket.org wrote:

> willbdaniels commented on issue 46:
> 
> [Received status code 401 from server: unauthorized](https://bitbucket.org/shemnon/javafx-gradle/issue/46/received-status-code-401-from-server)
> To fix this, you can simply up the version to 8.1.2-SNAPSHOT , I'm not totally sure why the 8.1.1 artifact got dropped. The main commit that allows you to see the change to 8.1.2 is: This commit
> Hope that helps!

I'll do this if we actually return to the JavaFX plugin.
