### ISSUE TITLE
Market, Trades, Currency "Show All" java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by goodc0re** [bisq-network/bisq#2223]
Bisq Version 0.9.2 
macOS Mojave 10.14.2

Upon selecting Currency "Show All" while on the Market, Trades tab, this error popped up: 
java.lang.IllegalArgumentException

**Comment by ManfredKarrer** [comment]
Can you post the log file? Thanks!

**Comment by ManfredKarrer** [comment]
Ah just could reproduce it, no need for log.

**Comment by ripcurlx** [comment]
Closing as complete in v0.9.3
