### ISSUE TITLE
UI pixel blocks / crash

### ISSUE THREAD

**Issue by userzer0x** [bisq-network/bisq#2231]
As seen in gif below, the UI has crashed with distorted pixel blocks here and there.  I noticed this happening after unhiding the app and after a while. Not sure why this is happening. But if i restart the program, the problem is fixed until it happens again.

![ui crash](https://user-images.githubusercontent.com/44409182/50892919-4fa4b900-1408-11e9-947b-71ad89bee905.gif)

**Comment by userzer0x** [comment]
By the way, this happened in v 0.9.1 as well. But it happens more often now in 0.9.3

**Comment by ripcurlx** [comment]
What OS are you using?

**Comment by userzer0x** [comment]
@ripcurlx Xubuntu 18.04
