### ISSUE TITLE
Trade statitic chart for XRC is broken 

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2239]
Trade statitic chart for XRC is broken 
See <img width="1182" alt="screen shot 2019-01-10 at 23 56 11" src="https://user-images.githubusercontent.com/1449498/51002367-5a0fa180-1533-11e9-82d4-01a641fa7856.png">

**Comment by ripcurlx** [comment]
<img width="1175" alt="bildschirmfoto 2019-01-11 um 16 20 25" src="https://user-images.githubusercontent.com/170962/51042563-e87c3580-15bc-11e9-83ed-d61fac1d7009.png">
Not really a bug. The price for one trade was so huge that it dwarfs all other trades.

**Comment by ripcurlx** [comment]
I don't think I can do anything from my side to fix this visualization problem.
