### ISSUE TITLE
Update Arbitration fee concept to flat rate instead of % of trade volume

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#225]

**Comment by remyers** [comment]
I think this is a very good idea and goes inline with the idea that fees are directly related to costs.  The  cost of arbitration should not depend on the amount in question.

**Comment by ManfredKarrer** [comment]
Exactly, and in fact the min trade volume will be determined by the min. arbitr. costs. I assume 0.1 BTC will be the min. cost for dispute, so if you trade only 0.1 BTC you would pay as well 0.1 BTC security desposit, which would be 100% of your volume. So in reality I assume pwople will trade min. 0.5 BTC.
And an arbitrator will lose his security deposit in any case of misbehaviour independent form the trading volume, so he has to work with the same quality independent of the volume.
