### ISSUE TITLE
Getting an alert if seed nodes are failing

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2255]
We need to get an alert from the monitoring if a seed node is not responsive or is out of data (outside some tolerance window). 

See: https://github.com/bisq-network/roles/issues/15#issuecomment-453749038

**Comment by ghost** [comment]
If this monitoring task is still considered as relevant and nobody more skilled is willing, I can throw an eye on it.

**Comment by ManfredKarrer** [comment]
I think that is now part of @freimair monitoring.
