### ISSUE TITLE
Request preliminary data also from non-seed-nodes

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2256]
When a node starts up it connects to a few seed nodes for initital data, that was added for more resilience if one seed node is out of date. We should extend that to include normal peristed non-seed-node peer as well, so in case that the seeds are all failing the network still exchanges at startup the live data. Only first time users would have a problem then.

See: https://github.com/bisq-network/roles/issues/15#issuecomment-453749038

**Comment by ManfredKarrer** [comment]
As the peer connects anyway to normanl nodes in case all seeds fail we don't need to do that. It would decrease startup time and increase network load if we would try to connect to known past nodes which might be offline with quite a high probablity. If we find a solution to clearly detect long runnning stable nodes we could add those to the list of seed nodes some day. But I think that has no priority at the moment, so I will close that issue.

**Comment by ghost** [comment]
Maybe we could simply ask the community for candidatures ? (possibly for a little bounty).
So, the users (eg pros) who have their Bisq appli running 24/7/365 could apply ?

We may monitor those "2nd rank seed nodes" to detect if they are indeed well on-line.

(Of course this may also have some issues. eg candidatures have to be verified a minimum).
