### ISSUE TITLE
Tor does not work on Debian Buster with OpenSSL 1.0.2

### ISSUE THREAD

**Issue by Talkless** [bisq-network/bisq#2257]
I've built v0.9.3 on Debian Buster (current Unstable version), and get these kind of errors:

```
                                                                                              
saus.-12 15:28:03.246 [ERR] ERROR o.b.netlayer.tor.Tor: /home/vincas/.local/share/Bisq/btc_mainnet/tor/tor: error while loading shared libraries: libssl.so.1.
0.0: cannot open shared object file: No such file or directory
```
```
saus.-12 15:50:16.594 [ERR] ERROR o.b.netlayer.tor.Tor: /home/vincas/.local/share/Bisq/btc_mainnet/tor/tor: error while loading shared libraries: libcrypto.so
.1.0.0: cannot open shared object file: No such file or directory
```
Creating libssl.so.1.1 -> libssl.so.1 (same for libcrypto) symlinks does not fix the issue, as it appears OpenSSL v1.1 does not have some symbols that Tor build expects:

```
saus.-12 15:51:29.562 [ERR] ERROR o.b.netlayer.tor.Tor: /home/vincas/.local/share/Bisq/btc_mainnet/tor/tor: symbol lookup error: /home/vincas/.local/share/Bisq/btc_mainnet/tor/tor: undefined symbol: CRYPTO_set_locking_callback 
saus.-12 15:51:29.562 [NetworkNode-9999] ERROR b.n.p2p.network.TorNetworkNode: Could not connect to running Tor: java.io.IOException: Tor exited with value 127
```

**Comment by Talkless** [comment]
DebianBuster actually has 1.0.2 too:
```
$ apt policy libssl1.0.2
libssl1.0.2:
  Įdiegta:    1.0.2q-2
  Kandidatas: 1.0.2q-2
  Versijų lentelė:
 *** 1.0.2q-2 500
        500 http://debian.mirror.vu.lt/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
```
Since `tor` searches for `1.0.0`, so I had to create these two symlinks to make it work:
```
$ file /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: symbolic link to /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
```
```
$ file /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: symbolic link to /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2
```
It works fine now with manual symlinks.

**Comment by freimair** [comment]
Hi @Talkless,

If I got your last line correctly, it works?

The thing with Tor is that we get our binaries by using the official TorBrowser releases and extract the already build binaries from there. That way we do not have to crossplatform build the binaries and we get the official signed binaries from the Tor Devs. So there is not a whole lot we can do about this dependency issue without doing a massive change in how we get our Tor binaries.

**Comment by Talkless** [comment]
> If I got your last line correctly, it works?

It works if I create create appropriate symlinks.

> ...without doing a massive change in how we get our Tor binaries.

Right... Not sure what can be suggested here.
