### ISSUE TITLE
Investigate memory increase/resource limitations on seed nodes

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2258]
Seed nodes on linux run out of memory after a while. We use a memory check and trigger a restart if we hit a certain limit. On OSX it was never reproduceable. So it might be a OS specific issue or related to default settings in Linux. Or maybe it is a memory leak which only occurs at seed nodes and not normal nodes. But I think I remember to have tested it in early days as well with seed nodes on OSX and could never reproduce it there (not 100% sure about that). Also I could connect to much more nodes on OSX as I was able to connect to on Linux.

See: https://github.com/bisq-network/roles/issues/15#issuecomment-453749038

**Comment by ManfredKarrer** [comment]
I tested with a local Bisq desktop node over the night with unlimited connection limit  (--maxConnections=10000) and did not see any memory issues.

- Connected peers: 250
- Bisq reported heap memory: 800-1100 MB
- Reported memory from OS: 1,7 GB
- CPU about 2-10% but sometimes up to 30%
- Bisq reported no. of threads: 554 

So that seems like the memory leak issue is either seed-node-only specific (I doubt and did such tests on OSX 2 years ago and could not reproduce memory leak -  I will make another test with a local seed tomorrow) or it is Linux (of OS settings) specific. My machine has 16 GB ram and a Intel Core i7/4 GHz CPU.

**Comment by freimair** [comment]
closed by https://github.com/bisq-network/bisq/pull/2475
