### ISSUE TITLE
Buying/selling grin not possible through bisq?

### ISSUE THREAD

**Issue by iljah** [bisq-network/bisq#2261]
Grin was added to bisq in https://github.com/bisq-network/bisq/pull/2217 but as far as I can tell it's not possible to (reliably, or maybe at all) buy/sell grin through bisq for two reasons:

 1. grin cannot be transferred without off-chain interaction between accounts in question (see e.g. https://blog.blockcypher.com/mining-grin-on-grinmint-how-to-request-payouts-1593835181eb). Easiest way with bisq seems to be that buyer of grin uses ip address as their grin address in bisq so that seller can send grin by connecting grin wallet/node directly to buyer's wallet/node. This feels awkward and might also be security issue since everything else in bisq runs over tor.
 2. currently it's not possible to prove that grin transfer has taken place: https://github.com/mimblewimble/grin/issues/2336

Was grin added prematurely to bisq?

**Comment by iljah** [comment]
This could be compared e.g. to monero which doesn't require off-chain interaction for transferring and in which sender can prove that monero was sent to another address.

**Comment by ghost** [comment]
grin launch is/was planned for january 15th (in 2 days).
Bisq does not have release every night ;-)
and wanted better to be ready a bit earlier than a bit later.

**Comment by iljah** [comment]
But it doesn't seem like grin is ready to be traded on bisq.

E: so it could've been added to bisq later when grin is ready...

**Comment by lehnberg** [comment]
> Easiest way with bisq seems to be that buyer of grin uses ip address as their grin address in bisq so that seller can send grin by connecting grin wallet/node directly to buyer's wallet/node. 

As far as I understand, support for [grinbox](https://grinbox.io) addresses has also been added to Bisq. The open source [wallet713](https://github.com/vault713/wallet713) has grinbox integrated and a user gets a grinbox address out of the box. Using grinbox to transact will not reveal your IP to other Bisq users, but it will reveal your IP to the grinbox relay. Suggested reading: https://github.com/vault713/wallet713#privacy-considerations

> currently it's not possible to prove that grin transfer has taken place: mimblewimble/grin#2336

If a grin transaction is valid and broadcasted to the network, the transfer has taken place. Participating parties are able to individually prove they participated in a transaction by revealing information only known to them.

**Comment by ManfredKarrer** [comment]
Yes we support both ip:port and grinbox "addresses".

@lehnberg Could you link to a doc where it is described how to proof a tx? The arbitrator need to get that proof in the unlikely and rare cases where one peers claims he sent and the other that he did not received it.

**Comment by iljah** [comment]
> If a grin transaction is valid and broadcasted to the network

In order to create valid transaction isn't some iteration needed between transferring accounts? According to grinmint instructions there are 2 possibilities: 1) sender uses grin wallet to connect to receiver's wallet, 2) around 1 kB of data must be sent off-chain between sender and receiver after which valid transcation can be created.

e: or is this only when using ip:port and iteration isn't required when sending to grinbox address?

**Comment by iljah** [comment]
> arbitrator need to get that proof

Technically isn't it possible to prove that someone sent grin to another address same way that someone would prove that they transferred money from their bank account? For example present live screen recording asking their own wallet what was sent and where. But these are easier to fake than e.g. proof of monero transfer...

**Comment by letatcest** [comment]
> But it doesn't seem like grin is ready to be traded on bisq.
> 
> E: so it could've been added to bisq later when grin is ready...

Also the first Grin has to mature for 24 hours, so it's not possible to move Grin until 15:00 (?) hours UTC Jan. 16 (not sure, but I thought first block mined at 16:00 CET)

**Comment by lehnberg** [comment]
This pull request should allow the sender to provide proof that a transaction was made to the recipient, as long as they use wallet713 and grinbox to transact: https://github.com/vault713/wallet713/pull/88

**Comment by ManfredKarrer** [comment]
Great thanks @lehnberg !

**Comment by iljah** [comment]
About https://bisq.community/t/we-need-to-remove-grin/7013 , wallet713 adds incoming transactions in mempool to total balance (with < 10 confirmations) which might cause people to think they've received grin even though they haven't: https://github.com/vault713/wallet713/issues/93

It's easy to check how many confirmations incoming transfers have by using `txs` or `outputs` command in wallet713.

**Comment by lehnberg** [comment]
FYI there's now a new wallet713 binary, v1.0.1: https://github.com/vault713/wallet713/releases/tag/v1.0.1

It adds transaction proofs which makes it straight forward for a sender to prove that a recipient actually received a certain transaction. It works with grinbox only.

**Comment by iljah** [comment]
So trading grin was disabled at some point because of too many problems, has it been enabled? I don't see any recent trades in https://bisq.network/markets/?currency=grin_btc

**Comment by ghost** [comment]
@iljah 
afaik GRIN has not been relisted atm.
Generally, when a coin is listed or relisted, it is mentioned in the release notes https://bisq.network/roadmap/ , which alas is not the case since the delisting.

**Comment by ManfredKarrer** [comment]
GRIN got deactivated due to too many problems (lack of proof for sender, transfers have been very unstable). I think those issues ware likley resolved now but we did not had time to test it out to decide to re-enable it again.

**Comment by iljah** [comment]
Is GRIN still deactivated?

**Comment by ghost** [comment]
> Is GRIN still deactivated?

Unfortunately yes.
I would be happy to help to relist GRIN on Bisq, but my understanding is that the code is a bit specific.

**Comment by iljah** [comment]
I guess this can be closed since buying/selling gris isn't possible through bisq...

**Comment by ghost** [comment]
Buying/selling GRIN isn't possible through Bisq at the moment, but it was possible at the GRIN early days.
So, it is very probably **still possible today**, but of course there is some technical work involved.
For my part, I find that GRIN is a really interesting altcoin. Would be a pitty not to relist it on Bisq.
I'm ready to help as much as I can technically (which is certainly low).
If I cannot help technically, I'm absolutely ok to pay some BSQ for that.

**Comment by ripcurlx** [comment]
@iljah Yes it is still de-activated atm. Do you know if it is working now stable enough to be listed again? If yes, could someone check if the account properties requirements changed compared to the previous configuration?

**Comment by lehnberg** [comment]
Hello, we're in the process of adding payment proofs on a network protocol level which I believe would solve the issues Bisq has been having in the past: https://github.com/mimblewimble/grin-rfcs/pull/31

This is tentatively targeted to be included in Grin v.3.0.0, released sometime around Jan 15, 2020.

**Comment by newjack777** [comment]
I'd like to bump this issue and provide further assistance to the BISQ developers with GRiN re-listing as the necessary tools and protocols have since been developed so to address the initial barriers to BISQ user convenience and accounting. payment proof have been built into the grin walet and there has since been api development that may be used to confirm transactions by way of [GrinNode Live](https://forum.grin.mw/t/early-beta-version-of-grinnode-lives-public-transaction-proof-verification-service-is-online/9080)
