### ISSUE TITLE
Wrong/autdated logo on installer image on mac

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/bisq#2262]
![screen shot 2019-01-13 at 4 05 05 pm](https://user-images.githubusercontent.com/807505/51090664-522b4980-174d-11e9-83fa-c2f6607afa9b.png)

should be

![dmgbackground](https://user-images.githubusercontent.com/807505/51090688-aafae200-174d-11e9-84af-f79f315ce405.png)
![dmgbackground 2x](https://user-images.githubusercontent.com/807505/51090689-aafae200-174d-11e9-8269-70c04651b233.png)

**Comment by ripcurlx** [comment]
Thanks - will update it.
