### ISSUE TITLE
Wrong app icon when app is running on Mac

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/bisq#2263]
Should be the same as when its closed.

Close (correct)
![screen shot 2019-01-13 at 4 12 00 pm](https://user-images.githubusercontent.com/807505/51090705-fdd49980-174d-11e9-8e34-819632f1e0f6.png)

Running (wrong)
![screen shot 2019-01-13 at 4 05 19 pm](https://user-images.githubusercontent.com/807505/51090699-e4335200-174d-11e9-9901-b98e527cdbe5.png)

**Comment by ripcurlx** [comment]
<img width="162" alt="bildschirmfoto 2019-01-14 um 11 09 08" src="https://user-images.githubusercontent.com/170962/51106717-da146080-17ec-11e9-9352-0fe6bd9e6305.png">
@pedromvpg Which macOSX are you running? Works for me on High Sierra.

**Comment by pedromvpg** [comment]
![screen shot 2019-01-13 at 3 55 15 pm](https://user-images.githubusercontent.com/807505/51156668-9a7c6180-184a-11e9-8326-70cec1dc5c16.png)
