### ISSUE TITLE
Error message overflows

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/bisq#2266]
An error appeared which was too long, and I did not see any buttons because they were below the bottom of the screen. 

Maybe we could add a scroll bar or truncate it and add "...".

![frozen screen](https://user-images.githubusercontent.com/43150241/51129263-ebc42b00-1821-11e9-9be9-3956700aa128.png)

**Comment by ManfredKarrer** [comment]
@arunasurya Did you delete the daoStateStore file as described in https://bisq.community/t/dao-testnet-testing/6895. If so and still an error please send me your db and wallet folders (testnet) and try afterwards to delete the other dao files (as described inn link).

**Comment by arunasurya** [comment]
I did rebuild DAO state from genesis tx for #2186 but the issue I am reporting here is about that a very long exception text can cause the error message to overflow so that the user cannot see the button to report to github/close.

**Comment by ManfredKarrer** [comment]
Fixed with https://github.com/ManfredKarrer/bisq/commit/a7dbbf4c5483efc3cb9443371a263f32ee0cf93b
