### ISSUE TITLE
Multiple SEPA accounts, but cannot choose, when buying!

### ISSUE THREAD

**Issue by Sylo44** [bisq-network/bisq#2276]
I would like to refer to this problem:

https://bisq.community/t/multiple-sepa-accounts-but-cannot-choose-when-buying/6925/2

I have multiple SEPA Options added which were on the same day and use the same bank, and it worked fine up until recently. Maybe someupdate caused the Issue.

Now I cannot chose which SEPA Option I want to buy with as it is greyed out and only one SEPA is prechosen.

Thanks

**Comment by Sylo44** [comment]
Maybe I should notice that the one, that doesn't show up for selection has a german letter "ü"  in it in the name and also a dash "-"

**Comment by ripcurlx** [comment]
@Sylo44 I just tried to reproduce your problem, but wasn't able to do so in current master. Which version are you using?
Could you please verify my steps if they match your use case:
- Multiple account warning is shown
<img width="1284" alt="bildschirmfoto 2019-01-24 um 12 10 23" src="https://user-images.githubusercontent.com/170962/51674569-494e3980-1fd1-11e9-8176-bbb26df8980a.png">

- Payment account can still be selected
<img width="1312" alt="bildschirmfoto 2019-01-24 um 12 10 28" src="https://user-images.githubusercontent.com/170962/51674604-5ff49080-1fd1-11e9-9d39-af2ac8e96702.png">
<img width="1312" alt="bildschirmfoto 2019-01-24 um 12 10 31" src="https://user-images.githubusercontent.com/170962/51674612-67b43500-1fd1-11e9-8ef2-ee50ed9a170d.png">

- Clicking on next in the pay funds screen, the payment accounts cannot be changed anymore.
<img width="1312" alt="bildschirmfoto 2019-01-24 um 12 10 48" src="https://user-images.githubusercontent.com/170962/51674638-7bf83200-1fd1-11e9-922f-de723f74abea.png">

**Comment by Sylo44** [comment]
I am using version v0.9.3
multiple accounts warning showing too
but I cannot select payment account as you can it is already greyed out when I confirm the warning

**Comment by Sylo44** [comment]
using windows 7

**Comment by Sylo44** [comment]
I just saw you are trying to sell BTC.
This happens to me when I want to buy BTC.

When I want to sell BTC I can chose as well. But buying BTC with SEPA I cannot select which SEPA account I want to pay with.

**Comment by ripcurlx** [comment]
Ahhh - damn it. I found the problem. I always have the DAO enabled locally on Regtest and on Mainnet the DAO is not live, which causes this issue. This was introduced in version 0.9.3. I'll push a fix - sorry about that.

**Comment by ripcurlx** [comment]
Will be fixed with https://github.com/bisq-network/bisq/pull/2315.

**Comment by Sylo44** [comment]
Hmm, strange things happening. I was just clicking through a couple of the SEPA Offers for buying BTC and with some of them I was able to chose a specific SEPA account that I want to send money from but with others I wasn't. Maybe this info might also help clarify the situation further.
