### ISSUE TITLE
Wayland: 'GDK_IS_X11_DISPLAY (display)' failed

### ISSUE THREAD

**Issue by fredfortier** [bisq-network/bisq#2279]
I'm using Fedora 29 with Gnome and Wayland and a fractional screen resolution. I built the project from sources. I can run headless modules but get this error when starting the `bisq-desktop`. This seems to indicate that the app expects an X11 server but I'm not sure. If so, is there a way to build for Wayland.
```
(java:26713): Gdk-CRITICAL **: 11:35:39.602: gdk_x11_display_set_window_scale: assertion 'GDK_IS_X11_DISPLAY (display)' failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f9dc46ac42b, pid=26713, tid=26764
#
# JRE version: OpenJDK Runtime Environment (10.0.2+13) (build 10.0.2+13)
# Java VM: OpenJDK 64-Bit Server VM (10.0.2+13, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libX11.so.6+0x3142b]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e" (or dumping to /home/fredfortier/Downloads/bisq-0.9.3/core.26713)
#
# An error report file with more information is saved as:
# /home/fredfortier/Downloads/bisq-0.9.3/hs_err_pid26713.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)
```

**Comment by ghost** [comment]
getting this exact same error.

**Comment by freimair** [comment]
yes, I have stumbled over the issue as well. see https://github.com/bisq-network/roles/issues/78#issuecomment-452638986 for reference.

not sure what we can do about that. sounds to me as if the jdk is at fault.

**Comment by 3cola** [comment]
On manjaro gnome (Arch linux + gnome-wayland), I get the same error with the AUR package bisq (0.9.3-1) and the app crashes.
But with the AUR package bisq-bin (0.9.3-2), by executing the app from the terminal by typing bisq, I see that some errors are still there, but the app displays on the screen and is usable.

**Comment by freimair** [comment]
I found a proposed [fix](https://github.com/javafxports/openjdk-jfx/pull/199) which has been rejected.

However, adding a `-Djdk.gtk.version=2` to the VM arguments does the trick for me!

**Comment by ripcurlx** [comment]
Closing as complete based on https://github.com/bisq-network/bisq/issues/2279#issuecomment-469010726.

**Comment by pandascrape** [comment]
I have the same crash issue running on Debian with GNOME 3 (Wayland). See https://github.com/bisq-network/support/issues/896. Please could you re-open this issue (perhaps the resolution involves javafx upgrade as per https://github.com/bisq-network/bisq/pull/3630)

**Comment by cd2357** [comment]
@pandascrape can you please retry with the latest version (v1.6.4)? It includes the JavaFX upgrade mentioned above.

**Comment by pandascrape** [comment]
> 
> 
> @pandascrape can you please retry with the latest version (v1.6.4)? It includes the JavaFX upgrade mentioned above.

Hi, 1.6.4 works on Wayland.

Thank you Bisq :)

**Comment by tredondo** [comment]
I got the same error from a different Java program and one workaround that function was to set `GDK_BACKEND=x11` before running the executable.
