### ISSUE TITLE
Missing offers in market overview

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2282]
See that from 17 offers there are only a few displayed:

<img width="1168" alt="screen shot 2019-01-17 at 20 03 05" src="https://user-images.githubusercontent.com/1449498/51384602-21685d00-1b1d-11e9-8c4a-895fd2c8db6a.png">

**Comment by ripcurlx** [comment]
@ManfredKarrer Unfortunately I wasn't able to reproduce this. Maybe it is related to the code that filters for relevant offers and there was too much price difference in the offerbook (has to be less than 30% off the best price) https://github.com/bisq-network/bisq/blob/92d15c231ae8d445440f27479afa868d4f24d236/desktop/src/main/java/bisq/desktop/main/market/offerbook/OfferBookChartViewModel.java#L366-L383

**Comment by ManfredKarrer** [comment]
Ah that might be as it was very volatile. Maybe we should only apply that filter if number of offers is < 10 or 20? Or maybe we should just display all....

**Comment by ripcurlx** [comment]
I have the feeling we should display all as well, as it is not clearly communicated how and that a selection is taken place.

**Comment by ManfredKarrer** [comment]
Yes. Lets remove that 30% check.

**Comment by ghost** [comment]
The few times I ran 2 different Bisq instances on 2 separate machines, I was always astonished to see that the number of offers were not the same on both machines. (Debian Stretch)
