### ISSUE TITLE
Support replace by fee withdrawal

### ISSUE THREAD

**Issue by kccheung** [bisq-network/bisq#2290]
I raised a support issue here: https://bisq.community/t/fail-to-withdraw-btc-using-bisq-client/6952

I cannot withdraw my fund which I set a low fee, i.e. 1 sat/b, if there is a feature like replace by fee, it would be good.

**Comment by ManfredKarrer** [comment]
RBF is not implemented in BitcoinJ so far ;-( (Bisq is using BitcoinJ). You can try to make a child pay ofr parent tx. If the tx never gets confirmed your need to delete the spv file (settings/network) and then the wallet gets reysnced and the tx is removed.

**Comment by ManfredKarrer** [comment]
I close the issue as there are no steps planned atm.

**Comment by kccheung** [comment]
In case anyone encounter similar issue like me, I would suggest use other wallet (like Electrum) to import your HD seed from Bisq and send the fund back to your own address.
