### ISSUE TITLE
Show notification about vote reveal

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/bisq#2292]
If a user has voted during the blind vote phase she must be online during the vote reveal phase to publish the vote reveal. Currently there is no indication of this, but it would probably be good to have some kind of indication if vote reveal has been published or is still needed.

**Comment by ManfredKarrer** [comment]
Yes agree. Feel free to make a PR with a suggestion.

**Comment by ManfredKarrer** [comment]
I added more text to the blind vote success popup to explain that the user need to be online in the vote reveal phase.
