### ISSUE TITLE
Show applicable mining fee in bond lockup/unlock confirmation dialog

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2296]
The confirmation message dialog that appears when locking up or unlocking a bond does not mention that there is an applicable mining fee. Mentioning the mining fee would be beneficial so the user is aware there is a BTC cost involved.
![image](https://user-images.githubusercontent.com/603793/51446544-61b80e80-1cc8-11e9-8a4c-88688aa4c7e3.png)

For reference, a proposal transaction indicates the mining fee.
![image](https://user-images.githubusercontent.com/603793/51446528-37fee780-1cc8-11e9-8fa0-970ee5104526.png)

**Comment by ManfredKarrer** [comment]
@ripcurlx Not high prio.

**Comment by ManfredKarrer** [comment]
Impl. with https://github.com/bisq-network/bisq/pull/2577
