### ISSUE TITLE
Bonded role that has not been locked up yet will show a date of "31 Dec 1969 16:00:00"

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2299]
When viewing all the bonds, if a bonded role has not been locked up yet it will show a date of "31 Dec 1969 16:00:00". It should not show a date in this case.
![image](https://user-images.githubusercontent.com/603793/51447078-28cf6800-1ccf-11e9-8918-4c8bb113148f.png)

**Comment by ManfredKarrer** [comment]
We don't know the date at that moment as we take the block time. But we should display "-" or N/A instead.
