### ISSUE TITLE
Current phase is not indicated correctly when in the block right after the proposal phase

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2300]
When in the block right after the proposal phase, the current phase does not indicate it is in the break before the blind vote. Still indicates it is in the proposal phase.
![image](https://user-images.githubusercontent.com/603793/51447022-74cddd00-1cce-11e9-9339-d7ac32ae25b1.png)

It isn't until the following block that the current phase updates:
![image](https://user-images.githubusercontent.com/603793/51447046-bb233c00-1cce-11e9-9787-d8030231a2f7.png)

**Comment by ManfredKarrer** [comment]
Ah that is something special. Technically we are still in the proposal phase but we if the user would create a proposal here the confirmation would be in the next block that would be then the break phase already. So we don't allow to create a proposla in the last block and show the user that the proposal phase is already over even technically its the last block in the proposal phase. To reflect that correctly in the text was missing.
