### ISSUE TITLE
Add indication that BSQ transactions are not up to date

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2303]
When BSQ transactions are not up to date, the only indication of this is in the BSQ Wallet > Transactions tab. It may be beneficial to indicate this in the status bar at the bottom of the UI somehow. Perhaps just an icon that when clicked takes you to the BSQ Wallet > Transactions tab to see the status.
![image](https://user-images.githubusercontent.com/603793/51497984-d13a0680-1d79-11e9-8c98-0ef79bfc935f.png)

**Comment by ManfredKarrer** [comment]
Yes, definitely needed!

**Comment by ripcurlx** [comment]
I've extended the label that gets displayed in the lower left footer (`/ Initializing DAO`, `/ Synchronizing DAO` ) and use the progress bar to indicate if DAO code is parsing blocks. When the synchronization is finished the progress bar is hidden and the additional information is removed. So it is also visible outside of the DAO section if blocks are still getting parsed. This is also important e.g. if you trade BSQ in the regular interface.
- Synchronization in process
![bildschirmfoto 2019-02-07 um 16 47 37](https://user-images.githubusercontent.com/170962/52423350-2e62e580-2af8-11e9-9645-23ae7f211f5d.png)
- Synchronization finished
![bildschirmfoto 2019-02-07 um 16 48 08](https://user-images.githubusercontent.com/170962/52423361-36bb2080-2af8-11e9-81d5-748952a289e0.png)
