### ISSUE TITLE
Validate for sufficient BSQ balance when proposing bonded role

### ISSUE THREAD

**Issue by m52go** [bisq-network/bisq#2307]
I just made a proposal for a bonded role (rocket.chat admin, 20 000 BSQ). I only had ~400 BSQ in my wallet.

The transaction went through without any errors. This shouldn't be possible, right?

[Here is the transaction](https://explorer.bisq.network/tx.html?tx=aff3b311cc2fdc923fcec65a0737d77c1bd3577d85a93961323b5b1a1be65a02).

**Comment by ManfredKarrer** [comment]
Ah good point. There is no check atm for that but would be good.

**Comment by devinbileck** [comment]
Should this be prevented? Or just show a warning? I wonder if it may be necessary to allow this scenario in anticipation of receiving/transferring the necessary BSQ once/if the proposal is approved, since the bond lockup is a separate process once the proposal is approved.

**Comment by m52go** [comment]
Now when I start Bisq, it throws an UnreadableWalletException (duplicate transaction) and it references this transaction (aff3b311cc2fdc923fcec65a0737d77c1bd3577d85a93961323b5b1a1be65a02).

**Comment by ManfredKarrer** [comment]
Did you start over with a new data directory?
Can u try to delete the spv file?

**Comment by m52go** [comment]
New data directory works (basically like new install).

I did try deleting the SPV chain file earlier and it didn't have any effect (same errors).

**Comment by ripcurlx** [comment]
> Should this be prevented? Or just show a warning? I wonder if it may be necessary to allow this scenario in anticipation of receiving/transferring the necessary BSQ once/if the proposal is approved, since the bond lockup is a separate process once the proposal is approved.

I think a warning should be fine. There is no reason IMO that the BSQ amount is already available when requesting the bonded role. We just should prevent that people are not aware that they might need this  amount of BSQ in the end to finish this transaction.
