### ISSUE TITLE
Adjust default buyer security deposit by spread

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2311]
To avoid that buyers can decide to not complete the trade in case price has moved against them we should increase the default value for the buyer security deposit for highly volatile markets.
One metrics we might be able to use is the spread. Usually high volatility is reflected in high spread and we have that data already available.

A more sophisticated method would be to measure volatility from the trade statistics data.

If volatility is higher we could use that as factor to increase the default deposit value (0.01 BTC).

Beside that we should move to % based values.

**Comment by ripcurlx** [comment]
Just referencing two issues regarding this topic:
- [Use Black-Scholes model for calculating depsoit](https://github.com/bisq-network/proposals/issues/64#issuecomment-451446462)
- [Use volatility for setting buyers security deposit ](https://github.com/bisq-network/bisq/issues/1346)

**Comment by ManfredKarrer** [comment]
Still relevant
