### ISSUE TITLE
Stuck on ¾ Hidden Service Published V9.3

### ISSUE THREAD

**Issue by aubits** [bisq-network/bisq#2327]
Running Bisq 0.9.3 on two of my machines 18.04 and 18.10 are stuck on the 3/4 Hidden Services at load. One of them has two offers open. 
I will attach a [log](https://drive.google.com/file/d/1ugNlf_hyTVgjYjrFGeMJtGk-hvUIgYSX/view?usp=sharing) file for your perusal. 
Please advise

**Comment by ManfredKarrer** [comment]
Can u restart and check if it works. If not open the network settings and delete the tor files (if not done vai app make sure to NOT delete the hiddenservice folder!)

**Comment by aubits** [comment]
Deleted all files in TOR folder except the Hidden Services Folder. Now both machines are running Bisq and advertising offers again.
Thanks Manfred.

**Comment by ghost** [comment]
Its happens sometimes that some Tor file(s) got corrupted.
It seems however strange that this could happen on two neighbour machines at the same moment (?)

@aubits ,
are your machines behind a static IP or a dynamic IP ?

**Comment by aubits** [comment]
Dynamic IP. I thought it curious too. Followed Manfred's instructions and restored on the next load.

**Comment by ghost** [comment]
The scenario I imagine is that you got a dynamic IP which, for one reason or another, is blacklisted by the Tor network.
So in fact there are no corrupted Tor file(s), but however it's necessary to reinitialize the Tor files.

Nothing sure however.

**Comment by ripcurlx** [comment]
Closing as complete. Feel free to reopen if the issue occurs again.

**Comment by aubits** [comment]
Repeat of problem, Bisq will not load beyond 3/4 Peers. Have deleted the TOR files and rebooted. To no avail.

**Comment by aubits** [comment]
Issue happening regularly on 0.9.4 Even deleting TOR Files doesn't improve performance. 
I've have an offer that keeps saying "Wait until your are fully connected to the network" before publishing. Has been attempting to connect for hours. HELP!?
