### ISSUE TITLE
Test offer and trade use cases via testnet

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#233]
On Oct 25, 2014, at 3:22 AM, @ManfredKarrer wrote:

@bitsquare/core-team,

the trade process is now basically working with server side seed nodes.

i deactivated port forwarding for the moment as that is not working correctly. in relay mode startup is slower but all works so far as i have tested.

i would suggest that we make a trade with testnet via a hangout session.

to have everything prepared you need to have:
- intellij with java v1.8.0_20 or later
- checked out the actual master
- refreshed gradle (tomp2p jars must have 5.0-Alpha.094d47d-SNAPSHOT in the file name)
- bitcoin core in testnet mode and some test coins (if you need any let me know i can send you some). better start bitcoin core a few hours before so it has catched up the blockchain.

if you need any help let me know.

**Comment by cbeams** [comment]
Thanks, Manfred. I am synchronizing with testnet now.

**Comment by ManfredKarrer** [comment]
Please update all the code, I fixed the bug with the withdrawal at the end of the trade. I also changes the bootstrapping code as the previous version was still using portforwarding internally.
It is still not very stable after a few trades and offer publications things get screwed up often.
I removed @stevemyers seed node to have more direct control (to restart the server) and to exclude potential problems with the connection of the 2 seed nodes.

There is a big pull request from Nico who has worked on relay mode specailly for android. As soon that is merged we can test if helps for our situation as well.

**Comment by ManfredKarrer** [comment]
Please not that the testnet behaves often different to the mainnet. E.g. the confirmation time is atm 20 minutes, see: https://blockexplorer.com/testnet

**Comment by cbeams** [comment]
Closing this issue, as I don't think there's anything further to discuss. Reopen if you see fit.
