### ISSUE TITLE
Add detail popups for proposal and votes

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2334]
As discussed at https://github.com/bisq-network/bisq/issues/2114 we should add a details popup where all data of a proposal or vote are displayed.

**Comment by ManfredKarrer** [comment]
@ben-kaufman Maybe you could take that issue if you would be available?

**Comment by ben-kaufman** [comment]
Yes, I'll start with #2485 first and then will do this.

**Comment by ManfredKarrer** [comment]
Maybe we dont need a popup anymore for proposals as the tx ID was probably the only missing data. But maybe u can cross check if anything else of importance is missing. There are diff. subclasses (comp. request)

**Comment by ripcurlx** [comment]
Already implemented.
