### ISSUE TITLE
Trade initiation confirmation window

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/bisq#2338]
Reduce paddings on the top of each section in order to separate CTA's from the main body.
Move CTA's to the right corner and reduce language. Just "Confirm" is enough no?

We should also consider removing all icons from buttons now that we removed them from the primary navigation. They are too complex and confusing requiring the user to stop to interpret them instead of just reading the language.

<img width="1245" alt="screenshot at jan 29 20-20-30" src="https://user-images.githubusercontent.com/807505/51951703-9b44f400-2403-11e9-9167-68a14234fe01.png">

**Comment by pedromvpg** [comment]
"Cancel" on the left and "Confirm" on the right edge of the box


![screen shot 2019-01-29 at 7 58 14 pm](https://user-images.githubusercontent.com/807505/51952021-c9770380-2404-11e9-8755-6e4eaa8f02f0.jpg)

**Comment by pedromvpg** [comment]
And can we add a max width to the Commitment "With publishing this offer I agree to trade ..." 
or a padding right? Right now the line is way too long.

**Comment by ripcurlx** [comment]
> And can we add a max width to the Commitment "With publishing this offer I agree to trade ..."
> or a padding right? Right now the line is way too long.

Sure, I can apply a max width for this field.

**Comment by ManfredKarrer** [comment]
I assume it is still relevant
