### ISSUE TITLE
error while viewing dao testnet

### ISSUE THREAD

**Issue by Mycelial1** [bisq-network/bisq#2339]
Opened the dao for the first time to check it out and while trying to scroll down It froze for a sec and I got this error.

![51198104_293618058178797_8845159785159458816_n](https://user-images.githubusercontent.com/34950746/51954017-a94b4280-240c-11e9-96ac-718620667540.jpg)

It's similar to this issue,
https://github.com/bisq-network/bisq/issues/2209
but not exactly the same  (I think) so here I am reporting.

**Comment by ManfredKarrer** [comment]
Yes that is a known issue and fixed in master, next release is in about 2 weeks and will be in there. You can just click OK and ignore it.
