### ISSUE TITLE
Min. offer amount for BSQ must be 5.46 BSQ

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2343]
When creating an offer we must ensure that the min. BSQ amount is larger than the dust limit of 546 satoshi (5.46 BSQ).

**Comment by ripcurlx** [comment]
@ManfredKarrer Just to be sure, you mean the trade fee min amount, correct?
![bildschirmfoto 2019-02-06 um 18 04 11](https://user-images.githubusercontent.com/170962/52359280-e41b2f00-2a39-11e9-88c9-ad62c5fe0b8c.png)
The trading amount has already the dust limit check integrated.

**Comment by ripcurlx** [comment]
The dust limit check for BSQ is already properly implemented:
https://github.com/bisq-network/bisq/blob/f4bf209960a0423e9fadac56c715989517594119/desktop/src/main/java/bisq/desktop/util/validation/BsqValidator.java#L85
https://github.com/bisq-network/bisq/blob/f4bf209960a0423e9fadac56c715989517594119/desktop/src/main/java/bisq/desktop/util/validation/BsqValidator.java#L92-L99

**Comment by ripcurlx** [comment]
Closing as complete. Was correctly implemented already.

**Comment by ManfredKarrer** [comment]
As discussed the minAmount might still result in a lower then 5.46 BSQ amount.
