### ISSUE TITLE
Adapt teaser design for "DAO on Testnet" in the Mainnet client

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#2349]
In our upcoming release we are going to enable the DAO section by default to increase visibility and get more testers for Testnet. Atm the design is as follows.
![Bildschirmfoto 2019-01-31 um 11.52.09.png](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/dd215c94-555f-449f-874a-0cc9da774337)

@pedromvpg It would be great if you could come up with a more catchy visualization to make our users eager to try it out on Testnet ;-)

**Comment by ManfredKarrer** [comment]
Maybe we can add a colored badge on the DAO menu item as well to mark it as something new.

**Comment by ripcurlx** [comment]
@pedromvpg Did you have time to work on this screen already?

**Comment by pedromvpg** [comment]
Hi @ripcurlx 

Does this page work? 

Broke down the page in to 3 very distinct areas: intro, BSQ request, and testnet usage.

Added some content so its clear what the user needs to do. 

Teasing out some interruptions so they don't need to leave the client to get a sense of the process. I think its more immediate and we might get more of the user's attention.

All steps have "read more" links that would link to the specific area of the documentation. And at the end there's a link to the DAO Docs page.

https://xd.adobe.com/spec/8aabaf0f-7ec2-42b5-55e6-7d13e1505e7e-fc9a/screen/a08a5285-cdc8-4936-8452-a92aceffb169/DAO-Teaser-page-PROPOSED/

![dao-teaser_page_proposed 2x](https://user-images.githubusercontent.com/807505/52683561-31ebd780-2f11-11e9-9c65-31b519fc2dcd.png)


<img width="1981" alt="screen shot 2019-02-12 at 9 49 57 pm" src="https://user-images.githubusercontent.com/807505/52683567-37e1b880-2f11-11e9-843a-27a0a6867abd.png">

**Comment by ripcurlx** [comment]
@pedromvpg Thanks for the design. Yes, that should be doable to have this teaser page as a complete separate view. 
The `Request Now` button should link to https://docs.bisq.network/dao/phase-zero.html#how-to-request-compensation I guess? 
I'll start working on it right now.
