### ISSUE TITLE
Users are notified automatically of new Bitsquare releases

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#236]
Dependent on the integration of UpdateFX (#102)

**Comment by btcll** [comment]
Can we make it possible for them to click a link to subscribe to the Bitsquare Newsletter from within the UI too?

**Comment by ManfredKarrer** [comment]
@btcll Yes should be possible. Either as weblink, or integrated (in webview). Depends if we will use webviews at all (at the moment I use it for help, but not sure if its worth to ship the webkip just for such stuff where it might be better to just open a webpage)

**Comment by ManfredKarrer** [comment]
I added an isssue #247

**Comment by btcll** [comment]
My preference is to link to their default browser. In App help systems generally suck in my experience!

**Comment by ManfredKarrer** [comment]
True!

**Comment by cbeams** [comment]
Removing this from the 0.1 milestone.
