### ISSUE TITLE
DAO: Add a pop up asking users to wait for the proposal confirmation

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/bisq#2367]
I noticed that there is a delay of 10-15 sec between making a proposal and getting its confirmation in DAO on testnet. It is not clear if a user should wait or go ahead and do something else. 

Suggestion: add a pop-up window that says something like "Please wait for the confirmation of your proposal" while the proposal transaction is being confirmed.

**Comment by ManfredKarrer** [comment]
That seems to be from the timeout at tx publishing. Just saw it myself.... So yes we should keep a spinner until the result is present.

**Comment by ripcurlx** [comment]
@ManfredKarrer It was reset atm by you by intent.
https://github.com/bisq-network/bisq/blob/0b81095ccbaed8d05750cfdc12341a4ad5c175f6/desktop/src/main/java/bisq/desktop/main/dao/governance/make/MakeProposalView.java#L311-L315
I could add a spinner and lock the form until it is published. Maybe the use case that people want to create quickly multiple proposals at the same time is mainly in testing right now, but makes it less user friendly in a real life scenario.

**Comment by ManfredKarrer** [comment]
yes the button should be deactivated so the user cannot create multiple same proposals (as mats did in one cycle).

**Comment by ripcurlx** [comment]
I changed the layout like that:
![bildschirmfoto 2019-02-07 um 10 03 58](https://user-images.githubusercontent.com/170962/52400546-b4166f00-2abf-11e9-917d-67c0923f323d.png)
