### ISSUE TITLE
Add stable coins

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#2369]
As I plan to add a couple of stable coins for v0.9.4 I'd love to get the feedback of people who are actually using them right now.

Based on my short research based on volume following coins would be on my list:
- Tether (ERC-20 and Omni layer based token (Bitcoin))
  - Official project URL: https://tether.to/
  - Official block explorer URL: https://omniexplorer.info (omni layer), https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7 (ERC-20)
- DAI (ERC-20 based token)
  - Official project URL: https://makerdao.com/en
  - Official block explorer URL: https://etherscan.io/token/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359
- TrueUSD (ERC-20 based token)
  - Official project URL: https://www.trusttoken.com/trueusd/
  - Official block explorer URL: https://etherscan.io/token/0x0000000000085d4780B73119b644AE5ecd22b376
- USD Coin (ERC-20 based token)
  - Official project URL: https://www.centre.io/usdc
  - Official block explorer URL: https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48

Is there a coin in the list that shouldn't be added? If yes, why? Is there an important stable coin missing that you're using? Please reply in the comments below - Thanks!

**Comment by phraktle** [comment]
Hi @ripcurlx,

I would love to see Augmint EUR (see https://github.com/bisq-network/bisq/pull/2345). It provides a decentralized, collateralized euro-targeted stablecoin.

**Comment by ripcurlx** [comment]
@phraktle If you change the commit message I'll merge your PR.

**Comment by ripcurlx** [comment]
I've updated the list of stable coins with the requirement for our asset listing. Atm the only problematic one is Tether (surprise, surprise). I'm not sure if we should support both address formats (Omni Layer and ERC-20) as it might cause confusion and arbitration cases in the end. I guess I'll stick to the newer ERC-20 implementation, although the Omni Layer (Bitcoin) based implementation might be the more "secure" one. I start to hate this stable coins already 😉
