### ISSUE TITLE
Error launching Bisq

### ISSUE THREAD

**Issue by lloydsmart** [bisq-network/bisq#2373]
Hi,
I’m having trouble launching Bisq on Linux. It starts to open, but then just exits before the main window appears with no error message.

If I launch from command line, this is the final line of output before the program quits:
`Bisq: ../src/gallium/state_trackers/dri/dri2.c:931: dri2_allocate_textures: Assertion `*zsbuf' failed.`

I’m using PureOS (a Debian derivative), GNOME3, 64bit, installed using Bisq-64bit-0.9.3.deb

This worked with older versions, but it’s been broken for me since the 0.9 series came out.

Any help would be much appreciated!

**Comment by ripcurlx** [comment]
We switched from Java 8 to 10 with the 0.9 release, so it could be related to that. I guess you won't have any logs in the Bisq application log, as it is not able to start the app at all. @HarryMacfinned are you using this kind of Linux system by any chance?

**Comment by ghost** [comment]
Sorry, I don't have PureOS.
I have Debian 9.7 Stretch, GNOME3.22.2, 64bit, installed using Bisq-64bit-0.9.3.deb
and I didn't get any problem at installation.

btw, I thought that when installing the Bisq (self-sufficient (?)) executable, it didn't worry at all about the java already installed on the computer. (At least it's how it works on one of my machine. Bisq v0.9.3 runs well, and the installed java is 1.8.0_181).
Is the Bisq executable not fully self-sufficient in some ways ?

I would however be interested in seeing the logfile if possible.

@lloydsmart 
which PureOS version do you use ? 
on which Debian version is it based ?
and what is the result of <code>lsb_release -a</code> in the CLI please ?

https://distrowatch.com/table.php?distribution=pureos
says that last PureOs is from 2017-08-20 
... that smells not super fresh. I guess this is the reason for this issue.

**Comment by stanfieldr** [comment]
I'm also having this issue on a fresh install of Fedora 29
[bisq_stderr.log](https://github.com/bisq-network/bisq/files/2897257/bisq_stderr.log)
[bisq_stdout.log](https://github.com/bisq-network/bisq/files/2897258/bisq_stdout.log)

**Comment by devinbileck** [comment]
I assume it is a rendering issue, perhaps with the display driver.
Perhaps the output of dmesg might provide some insight?
