### ISSUE TITLE
Can't fully connect to network?

### ISSUE THREAD

**Issue by aejontargaryen** [bisq-network/bisq#2374]
i've had an issue for a couple weeks where i can't edit or delete offers as the info popup gives me the "please wait until fully connected to the network. may take 2 mins" but it lasts for hours/days without fully connecting.  Any tips on how to resolve this?  (on both 0.9.1 & 0.9.3 using both ubuntu16 & 18)

**Comment by aejontargaryen** [comment]
after looking on bisq forum for a 2nd time i found some stuff to try.

[https://bisq.community/t/not-connected-to-the-bisq-network/6579/4](https://bisq.community/t/not-connected-to-the-bisq-network/6579/4)
https://bisq.community/t/unable-to-connect-to-network/7010

**Comment by ghost** [comment]
What are the numbers for the bitcoin network and for the Bisq P2P network ? (bottom left & right).

Maybe you could also post the last lines from the logfile.

**Comment by aejontargaryen** [comment]
I was able to correct it by manually deleting tor folder contents 
(all EXCEPT hiddenservices folder. <- DO NOT DELETE) -in case of future googles-
which was kinda strange as I watched the auto 'delete-outdated-tor-files-option popup at load screen' delete the files from the folder... and it appeared to do the same thing..?
bitcoin & p2p peers have been good. usually around 9+ 

also clicking on log file & directory buttons inside Bisq ui has no response?

**Comment by ghost** [comment]
@aejontargaryen wrote
> also clicking on log file & directory buttons inside Bisq ui has no response?

That's not normal.
I have Debian Stretch 9.7 and both buttons do their job.

Did you always have this problem, or is it something new ?

and btw, we speak about the last release v0.9.3 (?)

**Comment by aejontargaryen** [comment]
it is v093 yea. ubuntu 18.04
i'm not sure about before, this is the first time i ever needed it.
but it is recurring, since.

**Comment by ghost** [comment]
@aejontargaryen 
The logfile is located at ~/.local/share/Bisq
Could you please have a look at the logfile just after trying to open it thru the application, 
and copy/paste some possible relevant lines about this issue ?

I don't remember seing this issue/bug before.

**Comment by traderp** [comment]
I upgraded to v1.1.0. Same problem unfortunately. Here is more info about my config: https://www.whonix.org/wiki/Bisq. I can upload my trace logs if you would like.

![image](https://user-images.githubusercontent.com/50040139/57152145-32826480-6dc2-11e9-8e64-fbc1b999ea90.png)

**Comment by traderp** [comment]
@aejontargaryen Would you mind clarifying which files did you delete specifically?

**Comment by traderp** [comment]
@aejontargaryen What did you delete? This directory `:~/.local/share/Bisq/btc_mainnet/tor` has nothing but the `hiddenservices` in it. Did you delete the contents of `hiddenservices` but kept the directory? Or did you have other files in the `tor` folder root?

**Comment by aejontargaryen** [comment]
@traderp yea that might mean you have already deleted by choosing the startup option of 'delete outdated tor files.." when it asks you in the popup. It is actually doing the same thing. Im guessing that sometimes it just doesn't delete the files.....since it is the same process we are doing manually.
yea I just deleted the contents of tor folder except for hiddenservices. did u get it working?
