### ISSUE TITLE
error when trying to sell bitcoin for SEPA payment

### ISSUE THREAD

**Issue by Sylo44** [bisq-network/bisq#2381]
I wanted to sell some BTC and receive SEPA for that.

After I started trade and chose my SEPA ccount
this error showed up:

http://prntscr.com/mhopzi

**Comment by ghost** [comment]
If you may follow the advice and post your logfile (or at least the 100 last lines), that would indeed help to debug.

Bisq data directory locations:
Mac OSX: /Users/username/Library/Application Support/Bisq 
Linux: /home/username/.local/share/Bisq 
Windows 7,8,10: C:\Documents and Settings\username\AppData\Roaming\Bisq 
Windows XP: C:\Documents and Settings\username\Application Data\Bisq

**Comment by Sylo44** [comment]
simple restart helped, cannot find it anymore in the log file now because did too much after it worked.

should this issue come back again I'll make sure to directly check the log and post it here

**Comment by ripcurlx** [comment]
@Sylo44 please re-open this issue if it happens to you again. Thanks!
