### ISSUE TITLE
Rework color, language, and layout of market > offer book

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/bisq#2383]
<img width="2095" alt="screen shot 2019-02-07 at 2 31 24 am" src="https://user-images.githubusercontent.com/807505/52396678-b4434a00-2a80-11e9-9ae9-bd23411fbd7c.png">

**Comment by devinbileck** [comment]
Isn't the red and green colours common/standard?

**Comment by ManfredKarrer** [comment]
@devinbileck Many exchanges are using different colors. Its the classical color mode but I think others experienced also the issue with those hard and overloaded colors (speacially the red -> alert, warning). Though some related color to red like orange is for sure good to keep some relation.

I like the above suggestion from @pedromvpg. Feels more soft.

**Comment by ManfredKarrer** [comment]
@pedromvpg 
I agree to a more expressive text for buttons and headlines.
But the change from Buy to Sell does not work. In Bisq it is always the users perspective in relation to BTC , so if I want to buy BTC I take an offer from a seller. The right side is the sell side (sell offers) so the table below should contain those offers and the button need to be "Buy BTC".
With altcoins its a bit different as it is intuitive to say "I buy ETH" and not "I sell BTC (to get ETH)".
I think it is realted to what we consider the money side and what we consider the commodity side. We buy or sell commodity not money. You buy bread not sell EUR to get bread. So with BTC the money side is Fiat from our intuition (maybe that changes one day ;-)). For altcoin the money side is BTC. 
Technically altcoins are treated like fiat in Bisq, that made it a bit complicate from UX to support altcoins in an intuitive way. E.g. Buy ETH is the red "Sell BTC" side. We added more text to make it more clear at buttons (Buy ETH for BTC)....

**Comment by aejontargaryen** [comment]
i like the idea of "into btc = orange  &  out of btc || into fiat = green"
looks cool.

**Comment by ripcurlx** [comment]
I guess this will be a discussion that will hunt us forever 😉 

As we are going back and forth with this over a couple of releases how about following:
Maybe let's not be super clever and mix the intent from the user (Buy BTC with USD, Sell BTC for USD) with the appropriate offers that help the user to fulfill the desired action. 

&#x1F49A;**Offers to buy BTC with USD**`[Buy BTC with USD]`&#x1F536;**Offers to sell BTC for USD**`[Sell BTC for USD]` 

So we have the sell offers on the same side where the user can also add its own sell offers to. When it clicks on Sell BTC for USD the Sell BTC section is opened and it can take the existing buy offers or create a new sell offer.

Maybe that is for everyone easier to understand on this page.

**Comment by ManfredKarrer** [comment]
@ripcurlx So layout is at it is now, right? Just red color becomes orange and text might become more clear.

**Comment by aejontargaryen** [comment]
i understand everything thats been said on the subject - as well as the reasoning behind it.
But i still feel the process of it has been....overly simplified?  in the actions of the user.  
Yes, it is correct as to what **step** the user is doing - buying btc with fiat - so therefore green......*but* that is at the smallest scope of a bigger picture...

People don't want to think about what they want to buy - in terms of what they have to buy it with- unless it is in a time of desperation.. (*"who will take my fiat"* - thats not bisq.)

I think its more common way of thinking about what we want to buy-- **in terms of what we want to buy.**  
(*"I want to turn 'whatever' currency I have into bitcoin"* -that sounds more like bisq)

" buy bitcoin orange - sell bitcoin green "  *is* a rather bold route, but it does make sense- to me at least.
just my 2 sats

**Comment by ManfredKarrer** [comment]
I think buy is mostly green in other exchanges. So to flip that would confuse more IMO.

**Comment by aejontargaryen** [comment]
that is true, standard is green and red.
Though Bisq sell buttons *do* also have the word buy on them.

**Comment by aejontargaryen** [comment]
and i personally don't think of Bisq as just an exchange.
When i think of Bisq - I think of Bitcoin.

**Comment by Jon-Hodl** [comment]
I absolutely agree that the colors should be switched so that the Buy orders are green and on the left while the sell orders are in red on the right. 

Literally, every other order book I look at has the buys on the left and the sells on the right. 

![image](https://user-images.githubusercontent.com/50652112/57752881-cc41ef80-76a7-11e9-89f4-85d0807363e7.png)

The verbiage could also be changed so that it makes it easier on the end user. I know that Bisq is doing all they can to make things easier from a new user perspective but why the opposite of all other exchanges out there.

**Comment by Jon-Hodl** [comment]
> 💚**Offers to buy BTC with USD**`[Buy BTC with USD]`🔶**Offers to sell BTC for USD**`[Sell BTC for USD]`
> 

This is the single best response on this page. Offers to BUY on the LEFT and in GREEN with offers to SELL on the RIGHT and in RED or in this case BTC ORANGE.

**Comment by ManfredKarrer** [comment]
Still revevant

**Comment by aejontargaryen** [comment]
Robinhood uses green & orange too, fwiw.
