### ISSUE TITLE
Use BitcoinAverage's global index for BTC/MYR pair

### ISSUE THREAD

**Issue by musdom** [bisq-network/bisq#2390]
Bitcoin Average price feed for Malaysian Ringgit is unreliable, as the biggest exchange suspended fiat deposits indefinitely.

**Comment by ripcurlx** [comment]
@musdom Thanks for reporting. As our dev resources are tied at the moment to everything Bisq DAO related, we are not able to work on this. If you want, feel free to start working on it yourself, which will be up for compensation.
