### ISSUE TITLE
Add payment method: UPI 

### ISSUE THREAD

**Issue by shalzz** [bisq-network/bisq#2391]
# Introduction

UPI (Unified Payment Interface) is a popular payment method in the INDIA. It is a completely cashless,
Bank account to Bank account digital payment method using only a Virtual Payment Address (VPA) [official site][1]

# Requirements verification
 
**Web**: Chargeback risk
**Chargeback risk**: Very low
**Privacy protection to other peer**: High
**Mandatory data for a transaction**: a user chosen VPA of the format [A-Za-z0-9]@[A-Za-z]
**Duration**: Instant
**Region**: India
**Fees**: None
**Verifiable**: through an API (to be explored)
**Fraud risk**: Low
**Conclusion**:
 
# Implementation information

 
**Similar payment method**: Revolut
 
## Setting up National Currency Account

 
**Payment Method**: UPI
**VPA**: **
**Supported currencies**: INR,
**Limitations**: *Rs.1 Lakh per transaction*
**Salt for account age verification**: **
**Account name**: **
 
## Create offer to buy BTC

 
**Enable use of UPI
No other changes necessary.
 
## Create offer to sell BTC

 
**Enable use of UPI
No other changes necessary.
 
## Buying/Selling BTC

 
The buyer of BTC only needs to know the VPA of the seller. All other instructions should be the same as Revolut.
BTC Seller only needs to know the buyer’s trade id

[1]: https://www.npci.org.in/product-overview/upi-product-overview

**Comment by ripcurlx** [comment]
@alfsbs Could you have a quick look at the information provided for this payment method? Thanks!

**Comment by ghost** [comment]
Maybe @m52go has also some knowledge/opinion about UPI ?
