### ISSUE TITLE
An error occurred when taking the offer.

### ISSUE THREAD

**Issue by schulterklopfer** [bisq-network/bisq#2392]
An error occurred when taking the offer.

A timeout occurred.

The taker fee is already paid. In the worst case you have lost that fee.
Please try to restart your application and check your network connection to see if you can resolve the issue.Please try to restart your application and check your network connection to see if you can resolve the issue.

**Comment by schulterklopfer** [comment]
I tried again, same result with same offer. I can provide you with logs if it helps.

**Comment by schulterklopfer** [comment]
[bisq_buy_fail_20190208.txt](https://github.com/bisq-network/bisq/files/2844989/bisq_buy_fail_20190208.txt)

**Comment by schulterklopfer** [comment]
Running bisq v0.9.3, Seller: sxjqskget5mj35w7.onion

**Comment by ManfredKarrer** [comment]
It can be that the peer has an older version or his network connectivity is bad. WIth older versions there have been issues when the app got to standby mode from the OS.

**Comment by schulterklopfer** [comment]
I was thinking the same thing. That's why I tried twice with the same offer. Another offer worked fine :)

**Comment by schulterklopfer** [comment]
Is there a plan to split business logic from UI so ppl who are offering can run their bisq business logic at home on an rpi or at a cheap box on lunanode or amazon?

**Comment by ManfredKarrer** [comment]
Yes APIs are in development. @blabno is the main dev there.....

**Comment by ptmhd** [comment]
https://tradeblock.com/bitcoin/address/1PUXU1MQ82JC3Hx1NN5tZs3BaTAJVg72MC that offer is very popular, getting fees paid all the time since it was published : )  
this issue is going to be quite popular with the users.

**Comment by ripcurlx** [comment]
Yes it seems that the other party is using an older client (not supporting the ACK messages), but still that shouldn't be the problem. As @ManfredKarrer mentioned your taking of the offer failed because a time out occurred.

```
Feb-08 12:47:09.273 [JavaFX Application Thread] ERROR b.c.t.p.TradeProtocol: Timeout reached. TradeID=bPyYrU-0d48bc48-6c90-4d08-b8f7-2b3a60c8c8e2-093, state=TAKER_PUBLISHED_TAKER_FEE_TX 
Feb-08 12:47:09.302 [JavaFX Application Thread] WARN  b.c.t.p.TradeProtocol: cleanupTradableOnFault tradeState=TAKER_PUBLISHED_TAKER_FEE_TX 
Feb-08 12:47:09.305 [JavaFX Application Thread] WARN  b.c.t.TradeManager: We found an outdated addressEntry for trade bPyYrU-0d48bc48-6c90-4d08-b8f7-2b3a60c8c8e2-093 
Feb-08 12:47:09.305 [JavaFX Application Thread] INFO  b.c.b.w.BtcWalletService: swap addressEntry with address 1ATaxNcRAaNjXNiRhSGT3tBVJp189CwQrr and offerId bPyYrU-0d48bc48-6c90-4d08-b8f7-2b3a60c8c8e2-093 from context MULTI_SIG to available 
Feb-08 12:47:09.305 [JavaFX Application Thread] WARN  b.c.t.TradeManager: We found an outdated addressEntry for trade bPyYrU-0d48bc48-6c90-4d08-b8f7-2b3a60c8c8e2-093 
```
I'll close this issue for now, as I don't think we are able to do anything about this right now. Feel free to re-open if it occurs again.
