### ISSUE TITLE
Error  Launching Bisq  on OSX

### ISSUE THREAD

**Issue by alemiranda19** [bisq-network/bisq#2396]
Hello,

I had download Bisq 5 times and restart it about 20 times. Not able  to make it  work.  I do not know what  the problem is. Any help, please? I always get out at 2/4 Thor Node  Create. After that it  just disappear without any other massage.

<img width="559" alt="captura de pantalla 2019-02-02 a las 11 30 57" src="https://user-images.githubusercontent.com/47457297/52497067-02fdfa80-2bcd-11e9-9a69-d924c07283b6.png">

Thanks!

**Comment by ghost** [comment]
Hello @alemiranda19 
There are regularly problems with AV and Tor.
If you have an AV running, you should either tell it that Bisq is safe, either try turning the AV off.

I guess that you use the latest v0.9.3 Bisq version ?

**Comment by alemiranda19** [comment]
Thank you, I’m using a <strike>IOS</strike> OSX computer (macpro) sorry for my ignorance, what is an AV? Yes I had downloaded the latest version.

Thank you

**Comment by ghost** [comment]
apologies, AV = AntiVirus.
Sometimes it could also be a firewall issue.

**Comment by alemiranda19** [comment]
ha,ha

Thanks!  

No AV, Malwarebytes OFF, VPN OFF, still the same problem.... Do not really know what the problem is...

thank you for your help.

Alex

**Comment by alemiranda19** [comment]
Thank you,

I´m using an Apple Computer. MacOS Mojave.
I had tried everything, turn off AV, turn off the VPN just in case.  But the Thor node is not able to be created.
Weird thing is that the first time I download it, it work, then I was not able to log in again so it forced me to erase it and download it again. Since then, not able to connect…..

Thank you,


De: Harry MacFinned <notifications@github.com>
Responder a: bisq-network/bisq <reply@reply.github.com>
Fecha: sábado, 9 de febrero de 2019, 9:29
Para: bisq-network/bisq <bisq@noreply.github.com>
CC: Alejandro Miranda <1938uh@gmail.com>, Mention <mention@noreply.github.com>
Asunto: Re: [bisq-network/bisq] Error Launching Bisq on IOS (#2396)


Hello @alemiranda19<https://github.com/alemiranda19>
What OS do you use ? windows ?
There are regularly problems with AV and Tor under Windows.
If you have an AV running, you should either tell it that Bisq is safe, either try turning the AV off.

**Comment by ripcurlx** [comment]
@alemiranda19 Could you please post your log file, so I'm able to see exactly where the initialization fails?

**Comment by alemiranda19** [comment]
Thank you Christoph,

I’m not a programmer so I wish I could send you the log file, but honestly I do not know where to find it...

Sorry,

----------------------------
Alejandro Miranda

**Comment by ghost** [comment]
@alemiranda19 
On Mac OSX the logfile is located in : /Users/username/Library/Application Support/Bisq

**Comment by alemiranda19** [comment]
Hello,

This might be the problem, there is no Bisq folder under Application support….

https://www.dropbox.com/s/k1is5xyqjdxr3g9/Captura%20de%20pantalla%202019-02-12%20a%20las%200.03.27.png?dl=0
https://www.dropbox.com/s/h48zvs6uazuepy8/Captura%20de%20pantalla%202019-02-12%20a%20las%200.00.10.png?dl=0


Thank you for such a great help!

Alejandro




De: Alejandro Miranda <1938uh@gmail.com>
Fecha: lunes, 11 de febrero de 2019, 15:59
Para: bisq-network/bisq <reply@reply.github.com>
CC: bisq-network/bisq <bisq@noreply.github.com>, Mention <mention@noreply.github.com>
Asunto: Re: [bisq-network/bisq] Error Launching Bisq on IOS (#2396)

Thank you Christoph,

I’m not a programmer so I wish I could send you the log file, but honestly I do not know where to find it...

Sorry,
----------------------------
Alejandro Miranda

El 11 feb 2019, a las 14:19, Christoph Atteneder <notifications@github.com<mailto:notifications@github.com>> escribió:

@alemiranda19<https://github.com/alemiranda19> Could you please post your log file, so I'm able to see exactly where the initialization fails?

**Comment by ripcurlx** [comment]
> This might be the problem, there is no Bisq folder under Application support….

It is hidden by default, so you have to access it like:

# Temporary access to the hidden User Library
## Method 1:

From the Finder, select the Go menu at top of the screen, and choose Go to Folder.
In the window that opens, enter ~/Library, and click Go.
 
## Method 2:

Go to the Finder (or desktop).
Hold the Option key on your keyboard, and click the Go menu at the top of the screen.
With the Go menu open, you'll notice that pressing and releasing Option will display or hide the Library choice in this menu.
Select Library from the Go menu (while holding down Option) to access the hidden folder.

**Comment by ripcurlx** [comment]
You can also go in the app to Account --> Backup 
There is a button to open the log file.

![bildschirmfoto 2019-02-12 um 11 18 16](https://user-images.githubusercontent.com/170962/52628416-e822d300-2eb7-11e9-8297-78e19a222fac.png)

**Comment by alemiranda19** [comment]
First of all I have to thank you for such an incredible support. Amaizing guys!

This is what if found at the .log:

Tor started after 9168 ms. Start publishing hidden service.
################################################################
feb.-11 12:38:43.738 [JavaFX Application Thread] INFO  b.c.a.WalletAppSetup: Initialize WalletAppSetup with BitcoinJ version 0.14.4.11 and LibDohJ version 0.14.4 with hash of BitcoinJ commit cd30ad5b
feb.-11 12:38:43.766 [JavaFX Application Thread] INFO  b.c.b.s.WalletsSetup: Socks5Proxy for bitcoinj: socks5Proxy=localhost:49963     Version 5
feb.-11 12:38:43.786 [JavaFX Application Thread] INFO  o.b.c.Context: Creating bitcoinj 0.14.4.11 context.
feb.-11 12:38:43.799 [JavaFX Application Thread] INFO  b.c.b.n.BtcNetworkConfig: You connect with peerAddresses: [[r3dsojfhwcm7x7p6.onion]:8333, [vlf5i3grro3wux24.onion]:8333, [fz6nsij6jiyuwlsc.onion]:8333, [c6ac4jdfyeiakex2.onion]:8333, [sjyzmwwu6diiit3r.onion]:8333, [3xucqntxp5ddoaz5.onion]:8333, [lgkvbvro67jomosw.onion]:8333, [4jyh6llqj264oggs.onion]:8333, [mxdtrjhe2yfsx3pg.onion]:8333, [3r44ddzjitznyahw.onion]:8333, [i3a5xtzfm4xwtybd.onion]:8333, [z33nukt7ngik3cpe.onion]:8333, [sslnjjhnmwllysv4.onion]:8333]
feb.-11 12:38:43.805 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://xc3nh4juf2hshy7e.onion/
feb.-11 12:38:43.805 [ STARTING] INFO  b.c.b.s.WalletConfig: Wallet directory: /Users/alemiranda/Library/Application Support/Bisq/btc_mainnet/wallet
feb.-11 12:38:43.903 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a PreliminaryGetDataRequest to peer rm7b56wbrcczpjvl.onion:8000.
feb.-11 12:38:44.000 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a PreliminaryGetDataRequest to peer 3f3cu2yw7u457ztq.onion:8000.
feb.-11 12:38:44.509 [NetworkNode-9999] ERROR b.n.p.n.TorNetworkNode: Could not connect to running Tor: Unsupported private_key algorithm. Did Tor get a new key type for hidden services?
feb.-11 12:38:44.585 [NetworkNode:SendMessage-to-3f3cu2yw7u457ztq.onion:8000] INFO  b.n.p.n.NetworkNode: onFailure at sendMessage: peersNodeAddress=3f3cu2yw7u457ztq.onion:8000
                message=PreliminaryGetDataRequest(supportedCapabilities=[0, 1, 2, 7])
feb.-11 12:38:44.585 [NetworkNode:SendMessage-to-rm7b56wbrcczpjvl.onion:8000] INFO  b.n.p.n.NetworkNode: onFailure at sendMessage: peersNodeAddress=rm7b56wbrcczpjvl.onion:8000
                message=PreliminaryGetDataRequest(supportedCapabilities=[0, 1, 2, 7])



Thank you,

Alejandro Miranda


De: Christoph Atteneder <notifications@github.com>
Responder a: bisq-network/bisq <reply@reply.github.com>
Fecha: martes, 12 de febrero de 2019, 10:15
Para: bisq-network/bisq <bisq@noreply.github.com>
CC: Alejandro Miranda <1938uh@gmail.com>, Mention <mention@noreply.github.com>
Asunto: Re: [bisq-network/bisq] Error Launching Bisq on IOS (#2396)


This might be the problem, there is no Bisq folder under Application support….

It is hidden by default, so you have to access it like:

Temporary access to the hidden User Library
Method 1:

From the Finder, select the Go menu at top of the screen, and choose Go to Folder.
In the window that opens, enter ~/Library, and click Go.

Method 2:

Go to the Finder (or desktop).
Hold the Option key on your keyboard, and click the Go menu at the top of the screen.
With the Go menu open, you'll notice that pressing and releasing Option will display or hide the Library choice in this menu.
Select Library from the Go menu (while holding down Option) to access the hidden folder.

**Comment by ghost** [comment]
> feb.-11 12:38:44.509 [NetworkNode-9999] ERROR b.n.p.n.TorNetworkNode: Could not connect to running Tor: Unsupported private_key algorithm. Did Tor get a new key type for hidden services?

ping @freimair 
Does this message help us understand what happens ?

**Comment by freimair** [comment]
Well that should never happen. It basically says that Tor refuses the connection. I will look into these mechanics again once the upcoming monitor release is out.

@alemiranda19 did you try to use an existing Tor instance?

**Comment by alemiranda19** [comment]
Hello guys,

Thank you for help!

Florian, I do not know how to use an existing  TOR instance.

Cheers,

Alemiranda


De: Florian Reimair <notifications@github.com>
Responder a: bisq-network/bisq <reply@reply.github.com>
Fecha: miércoles, 13 de febrero de 2019, 9:55
Para: bisq-network/bisq <bisq@noreply.github.com>
CC: Alejandro Miranda <1938uh@gmail.com>, Mention <mention@noreply.github.com>
Asunto: Re: [bisq-network/bisq] Error Launching Bisq on OSX (#2396)


Well that should never happen. It basically says that Tor refuses the connection. I will look into these mechanics again once the upcoming monitor release is out.

@alemiranda19<https://github.com/alemiranda19> did you try to use an existing Tor instance?

**Comment by alemiranda19** [comment]
Hello guys,

Any news on this issue.

Thank you in advance for your help.

Best,

Alejandro Miranda


De: Alejandro Miranda <1938uh@gmail.com>
Fecha: miércoles, 13 de febrero de 2019, 12:15
Para: bisq-network/bisq <reply@reply.github.com>, bisq-network/bisq <bisq@noreply.github.com>
CC: Mention <mention@noreply.github.com>
Asunto: [bisq-network/bisq] Error Launching Bisq on OSX (#2396)

Hello guys,

Thank you for help!

Florian, I do not know how to use an existing  TOR instance.

Cheers,

Alemiranda


De: Florian Reimair <notifications@github.com>
Responder a: bisq-network/bisq <reply@reply.github.com>
Fecha: miércoles, 13 de febrero de 2019, 9:55
Para: bisq-network/bisq <bisq@noreply.github.com>
CC: Alejandro Miranda <1938uh@gmail.com>, Mention <mention@noreply.github.com>
Asunto: Re: [bisq-network/bisq] Error Launching Bisq on OSX (#2396)


Well that should never happen. It basically says that Tor refuses the connection. I will look into these mechanics again once the upcoming monitor release is out.

@alemiranda19<https://github.com/alemiranda19> did you try to use an existing Tor instance?

**Comment by ghost** [comment]
@alemiranda19 ,
There should be a new release (v0.9.4) in the next days.
With new features which may help to solve this issue.
So the best is to wait just those few days, and to see how it works.

**Comment by alemiranda19** [comment]
PERFECT!!

THANKS

De: Harry MacFinned <notifications@github.com>
Responder a: bisq-network/bisq <reply@reply.github.com>
Fecha: martes, 19 de febrero de 2019, 11:38
Para: bisq-network/bisq <bisq@noreply.github.com>
CC: Alejandro Miranda <1938uh@gmail.com>, Mention <mention@noreply.github.com>
Asunto: Re: [bisq-network/bisq] Error Launching Bisq on OSX (#2396)


@alemiranda19<https://github.com/alemiranda19> ,
There should be a new release (v0.9.4) in the next days.
With new features which may help to solve this issue.
So the best is to wait just those few days, and to see how it works.

**Comment by ManfredKarrer** [comment]
I just had the same error at release testing as well. Seem that the created key at first startup is invalid, at least I tried then the first back up key and that was causing the same error. Good thing is that at that moment deleting the hiddenservice directory has no consequences as no trades/offers/disputes are done.

@freimair We should put that issue on our high prio list. The error message seems to come from netlayer, maybe that could be more clear as well.

**Comment by freimair** [comment]
hm. yes. will look into it.

**Comment by alemiranda19** [comment]
Hello guys,

Thank you for your continuous support.
I had download the new version. In this case, I´m able to open BISQ, but I keep receiving a few messages that prevent me to operate to buy BTC on the market. (ATTACHED).

1.- it tells me that maybe I do not have internet connection, which I do
2.- Due to this failure the green bar at the right bottom is continuously moving and not able to set up a deal in the market,

On the other hand I was able to create an account, pairing it with my mobile and everything else looks fine.

I hope this will help.

Best,

Alejandro Miranda






De: Manfred Karrer <notifications@github.com>
Responder a: bisq-network/bisq <reply@reply.github.com>
Fecha: jueves, 21 de febrero de 2019, 21:07
Para: bisq-network/bisq <bisq@noreply.github.com>
CC: Alejandro Miranda <1938uh@gmail.com>, Mention <mention@noreply.github.com>
Asunto: Re: [bisq-network/bisq] Error Launching Bisq on OSX (#2396)


I just had the same error at release testing as well. Seem that the created key at first startup is invalid, at least I tried then the first back up key and that was causing the same error. Good thing is that at that moment deleting the hiddenservice directory has no consequences as no trades/offers/disputes are done.

@freimair<https://github.com/freimair> We should put that issue on our high prio list. The error message seems to come from netlayer, maybe that could be more clear as well.

**Comment by alemiranda19** [comment]
Hello guys,

I would love if you can help me, I think BISQ is the best tool right now on Crypto, but I´m not able to connect from my laptop (Apple Macbook) but I´m able to connect with other computers, ( my friend Mac).

So it has to be a problem on my Mac.

Can you help me, please?

Best,

Alejandro


De: Alejandro Miranda <1938uh@gmail.com>
Fecha: jueves, 28 de febrero de 2019, 13:04
Para: bisq-network/bisq <reply@reply.github.com>, bisq-network/bisq <bisq@noreply.github.com>
CC: Mention <mention@noreply.github.com>
Asunto: Re: [bisq-network/bisq] Error Launching Bisq on OSX (#2396)

Hello guys,

Thank you for your continuous support.
I had download the new version. In this case, I´m able to open BISQ, but I keep receiving a few messages that prevent me to operate to buy BTC on the market. (ATTACHED).

1.- it tells me that maybe I do not have internet connection, which I do
2.- Due to this failure the green bar at the right bottom is continuously moving and not able to set up a deal in the market,

On the other hand I was able to create an account, pairing it with my mobile and everything else looks fine.

I hope this will help.

Best,

Alejandro Miranda






De: Manfred Karrer <notifications@github.com>
Responder a: bisq-network/bisq <reply@reply.github.com>
Fecha: jueves, 21 de febrero de 2019, 21:07
Para: bisq-network/bisq <bisq@noreply.github.com>
CC: Alejandro Miranda <1938uh@gmail.com>, Mention <mention@noreply.github.com>
Asunto: Re: [bisq-network/bisq] Error Launching Bisq on OSX (#2396)


I just had the same error at release testing as well. Seem that the created key at first startup is invalid, at least I tried then the first back up key and that was causing the same error. Good thing is that at that moment deleting the hiddenservice directory has no consequences as no trades/offers/disputes are done.

@freimair<https://github.com/freimair> We should put that issue on our high prio list. The error message seems to come from netlayer, maybe that could be more clear as well.

**Comment by azulzorzoli** [comment]
Hi @ManfredKarrer,

I seem to be having a similar problem. I'm working from my computer, (managed by my work's IT team). Firewall is off (FireVault on). I have ZERO knowledge about all this, seriously, just heard the word Tor for the first time today.
It's my first time trying to use Bisq. Any ideas to troubleshoot?

![Screen Shot 2019-12-02 at 08 10 31](https://user-images.githubusercontent.com/58421906/69960179-be976e80-1500-11ea-8b30-5af5b893f702.png)
