### ISSUE TITLE
error on taking offer

### ISSUE THREAD

**Issue by Annuit-Coeptis** [bisq-network/bisq#2397]
3 times taking the same offer. I'm paying a fee for that? Also, whilst taking other offers, I've had the price change on me, and not in my favour. Not good, looks dishonest.
[bisqlog feb8.docx](https://github.com/bisq-network/bisq/files/2846520/bisqlog.feb8.docx)

**Comment by ghost** [comment]
You may open an issue here: https://github.com/bisq-network/support/issues

(Look at other issues opened by users, and please provide the necessary informations for reimbursement (in case of)).

**Comment by Annuit-Coeptis** [comment]
I can't find anyone had this issue solved here. I have used the platform several times now and, apart from this problem, I dislike the following: 1) I needed to deposit BTC before I could buy any, 2) my purchase amount is so limited for so long. Not good and very discouraging for someone not interested in the coding, who just wants to buy coin discretely.

**Comment by ghost** [comment]
Since you're not the first to complain about too limited amount,
I have just make a proposal to update the limits here: https://github.com/bisq-network/proposals/issues/71
You can vote for it if you support it.

**Comment by Annuit-Coeptis** [comment]
Thanks! I am certainly not a whale. Nor a trader. However, I would say that most offers are within my modest **quantity** range. Then it's only a question of whether I like the price. But this apparently is only wishful thinking since, it seems, 1) I am restricted with EVEN MY modest volume , and 2) many trades fail because counterparties are allowed to back out. It looks to me that I am paying a trade fee even when the offer I accept backs off because they simply got more greedy. Please sharpen up. Anarchist honest people hope for, encourage and support this kind of platform, but not when they are BSed.

**Comment by ripcurlx** [comment]
> 2) many trades fail because counterparties are allowed to back out. It looks to me that I am paying a trade fee even when the offer I accept backs off because they simply got more greedy.

If the counterparty pulls out of the offer it will loose its deposit which will payed out, depending on the arbitration case, in most of the cases to you.

**Comment by ManfredKarrer** [comment]
Trade limits will be doubled in upcoming release.
If you are the maker you can set the security deposit for the buyer, that will help you to avoid that the buyer does not continue the trade if the price moves against him. We plan also a volatility based security deposit for one of the upcoming releases. Which currencly did you trade?
From reports of arbitrators those "future trades" are usually only a problem with highly volative coins / or in volatile times. The buyers security deposit is the main tool to fight that but atm most makers use the default value which might be too low for such situations.

**Comment by ManfredKarrer** [comment]
Lost trade fee should be history with upcoming release and that PR: https://github.com/bisq-network/bisq/pull/2488
