### ISSUE TITLE
Application dies shortly after launch while attempting to connect with Tor with error "Auth cookie not created"

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2398]
When launching Bisq on my Windows 10 VM, it dies several seconds later and doesn't get past this on the splash screen:
![image](https://user-images.githubusercontent.com/603793/52500223-53a43200-2b92-11e9-8bf9-158e1b611974.png)

In the log:
`Feb-08 10:59:37.065 [NetworkNode-9999] ERROR b.n.p.n.TorNetworkNode: Could not connect to running Tor: java.io.IOException: Auth cookie not created`

I am consistently encountering it on my VM, but not on my primary Windows 10 machine. I have investigated/eliminated possible causes such as firewall, antivirus, file permissions and as of yet been unable to determine the root cause.

I see it is creating an empty tor/.tor/control_auth_cookie file, but not writing to it. While looking at the netlayer module, it throws this exception if the file is not written to within 3 seconds.
https://github.com/JesusMcCloud/netlayer/blob/master/tor.native/src/main/kotlin/org/berndpruenster/netlayer/tor/TorContext.kt#L346

At this point the only thing I can think of is it perhaps could be a timing issue with my VM running slower than my primary machine and it taking longer than 3 seconds to write to this file. But I am not familiar with the netlayer module nor with tor in general.

**Comment by devinbileck** [comment]
I have a fix that will show an error message rather than just exiting the application when this is encountered.
![image](https://user-images.githubusercontent.com/603793/52509382-cb7f5600-2bac-11e9-82d4-1d08c3017a2a.png)

This may also address some of the other recent reported issues with the application exiting shortly after launch.

**Comment by scottydk** [comment]
I just downloaded and installed Bisq for the first time, and I am getting the same error. Do you know how I can fix this issue?

**Comment by ghost** [comment]
If you could give a bit more informations about your configuration (what OS) and connection, it may help.

**Comment by scottydk** [comment]
I installed it on my windows laptop. Not sure about connection.

**Comment by devinbileck** [comment]
At this point I have been unable to determine the cause or a possible workaround. However, this is on the list of things to do for @freimair.

**Comment by freimair** [comment]
seems to be closely related to #1299

**Comment by devinbileck** [comment]
On my VM that consistently exhibits this issue, increasing the COOKIE_TIMEOUT resolves it. I just doubled it to 6 seconds.
https://github.com/JesusMcCloud/netlayer/blob/master/tor.native/src/main/kotlin/org/berndpruenster/netlayer/tor/TorContext.kt#L63

**Comment by ManfredKarrer** [comment]
@freimair Could you change the timeout if that helps?

**Comment by freimair** [comment]
I will prepare a fresh netlayer release and PR it right away

**Comment by user135711** [comment]
I'm still getting this on one of my windows OS's with the newest version bisq 0.9.5.

**Comment by devinbileck** [comment]
@user135711 the fix for this will be available in our upcoming release (this week).

**Comment by milseg** [comment]
For some reason i could bypass that using a VPN

**Comment by Rowdster** [comment]
I regularly get "connecting to bisq network failed error java.io.IOException: auth cookie not created".  I'm using the provided gateways, and I'm running from source build.  Is there anything I can share, or get additional logging?
This is windows 10 VM on a celeron CPU, 5GB ram, so it's on the lower end of hardware.  I don't know that I can modify from 3 to 6 seconds since TorContext.kt is not part of the bisq git pull

**Comment by devinbileck** [comment]
@freimair unless you have another idea, looks like we may need to increase the timeout further?

**Comment by freimair** [comment]
the timeout is already at 10 seconds. This is way too long already. Just think of it. Even windows machines are not that slow :). No, seriously, there is something else going on. Unfortunately, I cannot reproduce the issue with even a VM @devinbileck provided me as faulty.

EDIT: after sifting through the code again I found a code branch giving some insight in what might happen:
```
            if (OsType.current != OsType.WIN) {
                val exit = torProcess.waitFor()
```
with a comment saying that for non-Win OSs, the `torProcess` is only used to start up tor and is then being waited for, which is a guarantee that tor is up and running. On Win, tor is run inside the `torProcess` and hence, there is no such gate.

The timeout therefore has to be bigger for Win to function equally.

**Comment by Rowdster** [comment]
Also, I have available the source build and am currently using as my bisq app.  I can make any local code changes that might help provide any additional insight if you can think of anything helpful

**Comment by theamericans47** [comment]
I've the same issue, I've just installed on Windows 10 and manages firewall rules.
