### ISSUE TITLE
Github Issue Maintenance

### ISSUE THREAD

**Issue by thedon-chris** [bisq-network/bisq#2406]
Dear Bisq maintainers,

I want to get involved with the Bisq project, and contribute some code on beginner issues. But the issues do not seem to be maintained and I don't know where to begin.

Can you organize some the issues, and maybe post/flag some beginner issues to promote contributions.

**Comment by ghost** [comment]
You can browse the issues with some labels relevant for your search,
eg https://github.com/bisq-network/bisq/labels/good%20first%20issue

**Comment by ripcurlx** [comment]
@thedon-chris True - some of the good first issues where already completed. I've just went through them and they should be up-to-date again.
@HarryMacfinned Thanks for pointing out the `good first issue` label.

Some bounty issues that are also up to be taken can be found here: https://github.com/bisq-network/bisq/labels/%24BSQ%20bounty . But some of them need a deeper understanding of the codebase, so the good first issue ones are better to start with.
