### ISSUE TITLE
UI is unresponsive while synchronizing DAO state

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2415]
On Windows 10 I launched a new instance on testnet (new data dir) and the UI was not responding for a few minutes while synchronizing the DAO state with the following messages in the log:
`Feb-12 13:57:44.949 [JavaFX Application Thread] INFO  b.c.d.s.DaoStateService: New Block added at blockHeight 1456012`

![image](https://user-images.githubusercontent.com/603793/52671219-532bd400-2ecf-11e9-938f-c06c2231d393.png)

[bisq.log](https://github.com/bisq-network/bisq/files/2857850/bisq.log)

**Comment by ripcurlx** [comment]
@devinbileck Did you run it from current master?

**Comment by ripcurlx** [comment]
In general I've also the feeling that we might need to distribute the block parsing over a longer period of time to prevent these UI freezes.

**Comment by devinbileck** [comment]
@ripcurlx yes, from master.

**Comment by ManfredKarrer** [comment]
@devinbileck Are you able to reproduce that with dao-betanet?

**Comment by ManfredKarrer** [comment]
I could not reproduce it with lite or full node version. Full node requires about 300 ms for getting the block from bitcoind, so sync can take a bit but no blocking UI.

**Comment by devinbileck** [comment]
@ManfredKarrer I am not able to reproduce on dao betanet (lite node), but am able to reproduce on dao testnet. I suspect because there are not too many blocks on betanet right now to parse, and may encounter it over time.

**Comment by ManfredKarrer** [comment]
As lite node or full node?

**Comment by devinbileck** [comment]
lite node
