### ISSUE TITLE
Splash screen shows confusing message "Initializing / Initializing DAO"

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2416]
Upon launching, the splash screen initially shows the following. Perhaps it should show something like "Initializing Bitcoin network / Initializing DAO"?
![image](https://user-images.githubusercontent.com/603793/52671142-2677bc80-2ecf-11e9-8a76-f146a603deba.png)

**Comment by gibechoes** [comment]
A version number would be good to see on the splash screen too.

ON another topic.  Once presented with the login and we see the forgot password button. I wonder how many people think its recoverable just by the presence of that button and never clicking it until needed. Can do with some re-thinking / have a plain text info message instead stating to not lose password cant be recovered.

**Comment by devinbileck** [comment]
Good suggestion regarding your second point. Perhaps some additional text to clarify that would be beneficial here.
![image](https://user-images.githubusercontent.com/603793/52694155-a7f63b80-2f1d-11e9-82d6-f6eda5280d31.png)

Feel free to open a new issue for this!

**Comment by ripcurlx** [comment]
@devinbileck Good point! I'll change the text.
@gibechoes Yes, it might be a good idea to communicate that better at this point as well. What exactly can be restored and what not if you forget your password.

**Comment by ripcurlx** [comment]
@gibechoes As @devinbileck stated, please open another issue for that as this issue will be closed as soon as the new translation is merged to master.

**Comment by ripcurlx** [comment]
Not 100% sure on the wording. Initializing Bitcoin network sounds a little bit as if we are initializing the Bitcoin network itself. It is more that we are initializing the connection to it.
What about: `Initializing Bitcoin network connection`?
![bildschirmfoto 2019-02-13 um 09 05 19](https://user-images.githubusercontent.com/170962/52696144-95582280-2f6e-11e9-973d-8be73427f504.png)

**Comment by ghost** [comment]
What about 
Connecting to Bitcoin network
or
Initializing connection to Bitcoin network ?

and btw 
> A version number would be good to see on the splash screen too.

would indeed be nice (if easy to implement)

**Comment by ripcurlx** [comment]
> Initializing connection to Bitcoin network

I had this already, but it was just too long. Maybe just `Initializing network connection`?

Regarding the version number, maybe @pedromvpg has a good idea where to put it in this screen? On the very bottom?

**Comment by ManfredKarrer** [comment]
Why not "Connecting to Bitcoin network"?

**Comment by devinbileck** [comment]
Agree with @ManfredKarrer. Is there a need to mention DAO here?

**Comment by ManfredKarrer** [comment]
Also at that stage we are not requesting DAO related data.

**Comment by ripcurlx** [comment]
> Also at that stage we are not requesting DAO related data.

It was just initialization process but yes, I also think it makes sense just to get rid of the initialization DAO part and change the existing one to Connecting to Bitcoin network. 
I'll change the PR accordingly.
