### ISSUE TITLE
System tray icon on Windows and Linux does not scale to right size

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#242]

**Comment by ManfredKarrer** [comment]
Should be fixed, but needs testing on windows/linux and retina display.
@cbeams Can you check if it looks on on retina?

**Comment by cbeams** [comment]
> @cbeams Can you check how it looks on on retina?

Unfortunately it's now pixelated for me.

**Comment by ManfredKarrer** [comment]
ah ok, i need do do extra handling for retina...

**Comment by ManfredKarrer** [comment]
@cbeams can you check again with the last commit?

**Comment by ManfredKarrer** [comment]
On windows 7 and ubuntu it looks ok now.
@bitsquare/core-team Does any one have other OS to test it?
Specially Windows 8.
