### ISSUE TITLE
Restore from seed words when DAO enabled cause CPU peak

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2425]
There seem to be an issue when restoring from seed words at least in one data directory from @devinbileck from testnet.
App is frozen for quite long, restore seems to work but closing the app does not work anymore.
Maybe it is related to the DAO as it only happened on testnet with an app which had many DAO transactions.

**Comment by ManfredKarrer** [comment]
Yes it is DAO related, after deactivating the DAO the wallet restore was quickly done but still closing the app does not work.

**Comment by devinbileck** [comment]
May be related to #2415

**Comment by oscarguindzberg** [comment]
Maybe related to https://github.com/bisq-network/bisq/issues/1823#issuecomment-447605289

**Comment by ManfredKarrer** [comment]
Testnet has atm crazy block confirmation time (seems some ascis are point to testnet), about 15 sec. So lots of blocks are created in short time, which mimics the situation as if the user was not online for several months and need to sync up. Still investigating but the perfromance issue is happening only with old testnet wallets as far I see.

**Comment by ManfredKarrer** [comment]
I think that issue was mainly caused by crazy testnet block creation time. I will close here as the other possible issues are covered anyway in other issues.

**Comment by devinbileck** [comment]
I still encounter this issue on DAO testnet.

**Comment by ManfredKarrer** [comment]
@devinbileck Can you still reproduce it? The issue on testnet might have been related to the huge amount of blocks they created....

I cannot reproduce it on regtest or dao-betanet.

**Comment by devinbileck** [comment]
I cannot reproduce this on dao betanet nor on dao testnet.
Potentially due to now that it forces a shutdown?
