### ISSUE TITLE
Option to see/verify if the orders posted are from the same peer.

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#2437]
Hi,

I would like to see an option to be able to see/verify if different orders posted are from the same peer.

Thanks

Leonardo Costa

**Comment by ripcurlx** [comment]
@bitcoinuser You could give the user a tag (click on avatar icon) e.g. *, then it will be displayed next to the avatar icon for this user (onion address) on all offers. But be aware that a user can have multiple onion addresses if she chooses to.
