### ISSUE TITLE
"Select trading account" is inactive

### ISSUE THREAD

**Issue by dreboli** [bisq-network/bisq#2439]
Sell BTC > Take Offer > "Select trading account" dropdown list is greyed out, even though I have multiple accounts that could be used to fulfill that particular trade. (Offer is SEPA and I have multiple SEPA Accounts)

Tried to remove some accounts from the Accounts menu and re-import them but problem still stands for any offer I'm trying to take, regardless the payment opSelect trading accountion.

**Comment by ripcurlx** [comment]
@dreboli This is fixed in v0.9.4 which will be released on Wednesday.
