### ISSUE TITLE
Survey link is broken after trade is completed

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/bisq#2449]
<img width="826" alt="screen shot 2019-02-20 at 9 01 26 pm" src="https://user-images.githubusercontent.com/807505/53137974-c6c68480-3552-11e9-9783-a496906c6623.png">

currently linking here: https://survey.io/survey/ddfaa

**Comment by ripcurlx** [comment]
Yes, it seems the whole survey is down atm. I've contacted the developer. If it is not online soon, I'll switch to a different service.

**Comment by ManfredKarrer** [comment]
Maybe better use a redirect link, so we have more control.

**Comment by ripcurlx** [comment]
I think we use already a redirect link

**Comment by devinbileck** [comment]
Yep
https://github.com/bisq-network/bisq-website/blob/master/_redirects#L100

**Comment by ripcurlx** [comment]
After talking to the original author of the tool Sean Ellis, I was informed that the company that acquired the tool decided to shut it down. https://twitter.com/SeanEllis/status/1100450499738783744
I'll try to get the latest dump of the responses and update the current backup https://docs.google.com/spreadsheets/d/1KA7tZCiYn0Zs-GcpZ9zlfP-so0u_1bKs48A6W58gOlA/edit#gid=1045444736.

I'll re-build the form in another tool and change the redirect accordingly.
Does anyone have experience with free survey tools besides Google forms?

**Comment by ripcurlx** [comment]
I've created a new form with Google forms and will update the link accordingly.
https://goo.gl/forms/UcKr2D7WNYUZl3Cf1
