### ISSUE TITLE
Javapackager not found when run gradle packageNative

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#245]
i needed to change the javapackager in mac.sh file to 
$JAVA_HOME/bin/javapackager 
to make it run, otherwise it did not find it. probably a missing path in my environment...

**Comment by cbeams** [comment]
Manfred, do you have `javac` on your path?

**Comment by ManfredKarrer** [comment]
i have user/bin and there is javac as alias. at least its in the bash profile.

**Comment by cbeams** [comment]
I see. Ok, will just fully qualify in the script as `$JAVA_HOME/bin/javapackager`. Thx.

**Comment by cbeams** [comment]
Resolving this issue, as I'm managing the installer binaries (at least for 0.1), and `javapackager` calls work for me.
