### ISSUE TITLE
TradesChartsViewModelTest fails

### ISSUE THREAD

**Issue by iljah** [bisq-network/bisq#2458]
On fedora 28 with java_sdk_11, build of v0.9.4 fails at testItemLists test with UnsupportedOperationsException at TradesChartsViewModelTest.java:197 but v0.9.3 builds fine.

**Comment by ghost** [comment]
as stated at https://github.com/bisq-network/bisq/blob/master/docs/build.md
> You will need OpenJDK 10 installed and configured as the default system JDK to complete the following instructions.

**Comment by iljah** [comment]
10 is not available in fedora (28) and 9 which is available cannot build any version of bisq if I remember correctly.

**Comment by ghost** [comment]
I used openjdk_10 on Debian stretch + gnome, and build successfully Bisq v0.9.3 and v0.9.4 with it.

**Comment by iljah** [comment]
Would be nice if fedora was also supported...

**Comment by devinbileck** [comment]
@iljah you can manually download OpenJDK 10 from https://jdk.java.net/archive.
Alternatively, try running the [install_java.sh](https://github.com/bisq-network/bisq/blob/master/scripts/install_java.sh) script.

**Comment by ripcurlx** [comment]
Closing as complete by https://github.com/bisq-network/bisq/issues/2458#issuecomment-466547777
