### ISSUE TITLE
Show available/used BSQ addresses

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2463]
The UI should show all addresses with utxos when sending BSQ, and potentially be able to choose which to use as inputs - just like the BTC wallet. Choosing inputs is more advanced usage, but at least being able to see all available addresses would be useful.

Similarly when receiving BSQ, it should show all used addresses. Since when receiving BSQ, you always get a new address - which is recommended and reusing an old address should not be encouraged - it would at least be nice to be able to see exactly which addresses have been used.

**Comment by ghost** [comment]
@ripcurlx It seems to be already implemented (https://github.com/bisq-network/bisq/pull/5142) - issue could be closed.
