### ISSUE TITLE
Ensure proposals are entered using correct URL

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2473]
URL redirects for proposals, compensation requests, and roles have been implemented by #2429. We now need to consider what approach (if any) to take with regards to entering proposal links within the UI to ensure people are using the correct URL.

If users don't use our redirected URLs, GitHub will be forever recorded in compensation requests and could potentially become dead links if we later relocate them elsewhere. This would be an issue if someone wants to view past proposals and attempts to follow the link to the proposal.

Likely the simplest approach is to only allow the user to enter the proposal id.

**Comment by ManfredKarrer** [comment]
> Likely the simplest approach is to only allow the user to enter the proposal id.

That would mix all proposals and comp. requests.

We could thought use diff. URLs for those types and use the ID.
More flexible maybe might be to use a warning popup in case the user uses a URL not matching the expected URL scheme.

**Comment by devinbileck** [comment]
If the user only enters the id, the ui can assemble the full correct URL depending if it is a compensation request or proposal.
e.g.
```
https://bisq.network/proposals/<id>
https://bisq.network/compensation/<id>
```

**Comment by ManfredKarrer** [comment]
Yes. I am just not sure how strict or how flexible we should be here. At the end its just UI so we can change over time. I would prefer flexibility as that was my learnign over time that flexiblity is more important. But leave it to you, I can live with both approaches...

**Comment by devinbileck** [comment]
I suppose another benefit of entering (and storing) just the id, is that we potentially can detect and flag duplicates and show a warning/error within the UI if that has already been reimbursed/approved.

**Comment by ManfredKarrer** [comment]
We would still need to allow to add a duplicate as it would otherwise be that a malicious user squatter a proposal.
