### ISSUE TITLE
Stuck on ¾ Hidden Service Published V9.4

### ISSUE THREAD

**Issue by aubits** [bisq-network/bisq#2474]
Issue happening regularly on 0.9.4 Even deleting TOR Files doesn't improve performance.
I've have an offer that keeps saying "Wait until your are fully connected to the network" before publishing. Has been attempting to connect for hours. HELP!?

**Comment by ghost** [comment]
You described a similar issue one month ago https://github.com/bisq-network/bisq/issues/2327
I'm afraid there are connection issues on your side.

You should post the relevant lines of your logfile. It may help to understand what happens.

**Comment by ManfredKarrer** [comment]
@aubits Could you try with an old bisq version? You would need to rename the currtent data directory to not overwrite the data there (might be incompatible with downgrade). Not sure if on Window its easy to downgrade, but make a backup just in case before doing it (e.g. de-installing will delete it!).
Maybe you can go back to 0.8.1 or so as we can be sure that its a different tor library version.
https://github.com/bisq-network/bisq/releases/tag/v0.8.1

**Comment by aubits** [comment]
Yes can revert it. Though am away from home for a few days. I'll try early
next week.

**Comment by ripcurlx** [comment]
@ghost @aubits Are you still experiencing this issues with the current version of the client?

**Comment by aubits** [comment]
No, running a-ok at present.

**Comment by ripcurlx** [comment]
Closing as of https://github.com/bisq-network/bisq/issues/2474#issuecomment-579570541.
