### ISSUE TITLE
Test app when connecting to internet via VPN

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#248]
Does anyone has VPN? We need to support that as many privacy aware usere will use VPN.

**Comment by cbeams** [comment]
I'd recommend we turn this into a user story, i.e. "As a user, I can use Bitsquare via a VPN connection". I have an OS X Server that technically has VPN functionality, but I haven't used it much. Can try when the time comes though.

**Comment by ManfredKarrer** [comment]
Have changed the title of #246 for that
