### ISSUE TITLE
Invitation for feedback after DAO cycle

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2485]
Similar to the trade feedback popup we could add a popup with a link to a survey for collecting feedback about the users experience when testing the DAO.

@ripcurlx @pedromvpg If you agree that this is a good idea and have any idea how to make that nice feel free to implement it.

@m52go Maybe you can keep track so the link to the docs page is matching....

**Comment by m52go** [comment]
If we want to do this, I made a form [here](https://docs.google.com/forms/d/e/1FAIpQLSdS4YRE9Eox3bvuo4oSJJQCm5Yy54ZclKC_ThUt702PeU4rxw/viewform).

(feedback on the form is also welcome, and we can discuss opening access to the results as appropriate)

[Docs page](https://docs.bisq.network/getting-started-dao.html) already has a link to this form, and it also specifies a bounty.

**Comment by ripcurlx** [comment]
@ben-kaufman Do you want to take over this issue? We do have something like that already after a completed trade: https://github.com/bisq-network/bisq/blob/master/desktop/src/main/java/bisq/desktop/main/overlays/windows/TradeFeedbackWindow.java.
So it needs to be discussed with @m52go at which place the popup should be displayed and then integrated similar to the TradeFeedbackWindow mentioned above.

**Comment by ben-kaufman** [comment]
@ripcurlx Sure, I think I'll do that before #2334 as it seems to be very similar but easier.

**Comment by ben-kaufman** [comment]
I'm working on this now, but still thinking when should this be displayed. Any ideas @ManfredKarrer @ripcurlx @m52go?

**Comment by ManfredKarrer** [comment]
Maybe at/after the result phase in case the user has created a proposal or voted. with the dont show again flags we can make it a one time popup settting the flag to true automatically after displayed.
