### ISSUE TITLE
Timeout at take-offer attempt

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2486]
We still get many reports for timeouts at the take-offer attempt.
See https://bisq.community/t/0-9-4-update-trade-limit-doesnt-work-correctly/7134/

I assume a reason is standby behaviour at different OS. For OSX it should be fixed with 0.9 by playing a silent sound to avoid that the OS throttles the network which causes timeouts when a taker tries to take the offer. We don't know if that fix works for other OS and how the behaviour is at other OS.

@devinbileck Do you have any info for Windows?

@freimair We need to set higher prio to that topic. If you have any idea what could other issues let me know. I see recently many Tor startup delays when I start a mainnet node. But I have poor internet now...

**Comment by ManfredKarrer** [comment]
One thing we could try for the upcoming release to increase the timeout at take offer to see if that helps. That is a easy change at least.

**Comment by ManfredKarrer** [comment]
I just added a PR for delaying the publishing of the taker gee tx just before the deposit tx gets published. That should eliminate those lost taker fee issues completely.
See https://github.com/bisq-network/bisq/pull/2488

But we still need to find out the issue why it takes so long until the maker replies (or if there is any other reason for the failure, e.g. that the taker offer request fails on the makers side due validation errors...).

**Comment by ManfredKarrer** [comment]
I got the log files from that user who had many failed trades. It was always timeouts as far I saw. he is Windows user and used version 0.9.3.

**Comment by devinbileck** [comment]
I will see what I can determine regarding standby on Windows.

**Comment by ghost** [comment]
Atm, the https://docs.bisq.network/getting-started.html doc doesn't speak about a good internet connection **requirement** (or I missed it).
Given that this is a cause for many issues, maybe we could add some insistent lines about that ?

Maybe we could insist on this point, and even insist stronger for makers ?

edit : we could get inspiration from https://bitcoin.org/en/full-node#minimum-requirements , especially the last lines.

**Comment by ManfredKarrer** [comment]
Just did a test trade with @devinbileck who had his app in standby (Win) and it worked without issues. Are there standby options where the network get throttled? Maybe on laptops its different to safe energy. On OSX they have AppNap and changed the behaviour over the last years and now you cannot avoid that network get throttled even you adjust the setting to allow network access. Only way I found was playing  a sound.
