### ISSUE TITLE
Investigate alternative DHT implementations

### ISSUE THREAD

**Issue by notmandatory** [bisq-network/bisq#249]
Start with:
https://github.com/xxtommoxx/kademlia-dht
https://github.com/fcristovao/KadAct

Manfred with provide list of others to investigate.
- Make simple WAN integration test harness for put/get testing
- Manual setup for NAT UPnP port forwarding

**Comment by ManfredKarrer** [comment]
Other DHT libs:
https://code.google.com/p/openkad/ (that looks interesting, there are soem related project at the bottom of the site -eWolf  Emin Gün Sirer is participant)
https://github.com/rkapsi/ardverk-dht
https://code.google.com/p/openkad/source/browse/
https://code.google.com/p/dht/
https://github.com/mattjubb/Amici
https://github.com/JoshuaKissoon/Kademlia

Mesh VPN (Pedro Vilchez recommended that as possible P2P network base - not sure if that might be a possibility, need to read more about it, but intersting idea!)
http://www.tinc-vpn.org/ , https://en.wikipedia.org/wiki/Tinc_%28protocol%29

Ruediger Moeller suggested to have a look to WebRTC:
http://www.webrtc.org/

Messaging:
https://github.com/RuedigerMoeller/fast-cast (LAN only)

UPnP Lib:
http://4thline.org/projects/cling/

Kademlia:
http://www.scs.stanford.edu/~dm/home/papers/kpos.pdf

Papers about routing:
http://www.cs.rice.edu/~dwallach/pub/osdi2002.pdf
http://www.zora.uzh.ch/55818/1/Hecht_et_al_B-tracker.pdf (Thomas Bocek)
http://www.cs.kent.edu/~javed/class-P2P13F/papers-2013/P08-B-tracker-hecht.pdf (Thomas Bocek)
http://home.ie.cuhk.edu.hk/~dmchiu/jl08.pdf
http://www.cs.cornell.edu/people/egs/papers/beehive.pdf
