### ISSUE TITLE
Not able to spend after wallet seed restore

### ISSUE THREAD

**Issue by Quenos** [bisq-network/bisq#2491]
Yesterday I had to restore the wallet from my seed.
In principle this worked, as I can see all the transactions that have been done with these keys.

However, the balance says 0.00 although there are unspent transactions in the wallet, and they are shown in the transactions section. I can also not spend these transactions.

Any ideas?

**Comment by ghost** [comment]
You can try `Settings/Resync SPV chain.`

Be however aware that, if your account is old,
this can take a long time (some hours) and use ~100% of the CPU.

**Comment by Quenos** [comment]
No that didn't work :(

**Comment by ManfredKarrer** [comment]
@Quenos Do you have latest version 0.9.4? Are you using Windows? With prev. versions there have been issues with restore on Windows.

**Comment by Quenos** [comment]
@ManfredKarrer Yes that is the version I'm using in conjunction with Windows 10

**Comment by ManfredKarrer** [comment]
Could you try with a clean new data directory again? See https://bisq.community/t/how-to-switch-to-a-new-data-directory/6753/ Make a backup of your old before that. Just see if it works from a clean start. Maybe the internal wallet DB has issues.

**Comment by Quenos** [comment]
@ManfredKarrer No that did not solve the problem

**Comment by ManfredKarrer** [comment]
@Quenos Feel free to contact me by email for further help: manfred@bitsquare.io

**Comment by ManfredKarrer** [comment]
Fixed with https://github.com/bisq-network/bisq/pull/2512
See also https://bisq.community/t/forgot-my-password-and-tried-to-restore-wallet/7096/19

**Comment by ManfredKarrer** [comment]
@Quenos You can try cmd+e there you should be able to withdraw the funds. Or run from source/master..
