### ISSUE TITLE
Cannot build 0.9.4

### ISSUE THREAD

**Issue by suvayu** [bisq-network/bisq#2497]
I have been unable to build 0.9.4 or master from source.  I tried `git bisect`ing, and arrived at commit fe864724f3c4b0383c729a80082d28a4be2417ea as the first bad commit.  I'm on Fedora 28, with

    $ java -version
    openjdk version "11.0.1" 2018-10-16
    OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
    OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode, sharing)

**Comment by ManfredKarrer** [comment]
You need java 10. Java 11 is nor supported yet.

**Comment by ghost** [comment]
as stated in the doc https://github.com/bisq-network/bisq/blob/master/docs/build.md
you need openjdk 10.

**Comment by suvayu** [comment]
Sorry, didn't realise.  It's interesting because 0.9.3 was building just fine with OpenJDK 11!
