### ISSUE TITLE
If this takes off, who is going to get the earnings from ta+registering fees ?

### ISSUE THREAD

**Issue by RuedigerMoeller** [bisq-network/bisq#250]

**Comment by ManfredKarrer** [comment]
The fees for registration is just the minimum needed to store some data to the blockchain. Currently 0.0002 BTC later we can decrease that to 0.0001 BTC (the current bitcoinJ API does not allow OP_RETURN output with 0 BTC, but that will be changed).
The trade fees will go to the arbitrators for their service availability. The arbitrators only earn money when they are actually resolving a dispute. If there are not many disputes they would lose the motivation to be available and also to keep their security deposit blocked in a MultiSig address. So we need some incentive that they stay available. It will be a dynamic market process to find the right value for the trading fee. Initially we will put them very low, but later the market will decide it. If too many arbitrators will leave we have to increase the fee. 
The funding model of the project is still open. We plan to fund the development by using Lighthouse (a bitcoin based crowd funding project by Mike Hearn). But its an open experiment, we will see how it will work out.
There are some other ideas but nothing concrete for public discussion yet, but basically all centered about a community driven approach (no investores,...) to keep the decentralized approach intact.

I just read today in your blog and saw some of your projects. Very interesting! 

We are in the process to refactor the trade process to Akka, but your Kontraktor framework seems to be in interesting alternative as well.
But our main problem at the moment is to get the P2P network stable in real web environment.
I read a bit about FastCast but it seems that is designed for LAN only environment. We need something which works stable with all the NAT traversal problems and unreliable connection scenarios in WAN.

We can continue a discussion as well in the mailinglist (https://groups.google.com/forum/#!forum/bitsquare), by mail (mk at nucleo dot io) or at IRC (@freenode, #bitsquare i am mkarrer).

**Comment by cbeams** [comment]
Closing this as the conversation has moved to the mailing list ([here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/bitsquare/DF0aQOOylD8)).
