### ISSUE TITLE
Many WARN  b.n.p2p.network.Connection messages

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#2506]
I'm running v0.9.5 from the CLI (on Debian stretch 9.8, gnome 3.22.2), using the --appDataDir parameter, and I got a lot of those messages :

mars-07 08:21:28.122 [NetworkNode:SendMessage-to-c9d7c681-b104-40c9-9497-f236b643e43b] WARN  b.n.p2p.network.Connection: We got 2 sendMessage requests in less than 20 ms. We set the thread to sleep for 50 ms to avoid flooding our peer. lastSendTimeStamp=1551943288105, now=1551943288122, elapsed=17, networkEnvelope=RefreshOfferMessage 
mars-07 08:21:32.040 [NetworkNode:SendMessage-to-4231424a-913f-48e7-b9b1-ec7f90f28603] WARN  b.n.p2p.network.Connection: We got 2 sendMessage requests in less than 20 ms. We set the thread to sleep for 50 ms to avoid flooding our peer. lastSendTimeStamp=1551943292023, now=1551943292040, elapsed=17, networkEnvelope=RefreshOfferMessage 
mars-07 08:21:32.270 [NetworkNode:SendMessage-to-134eb67d-00ef-44ef-906d-65478dc3100e] WARN  b.n.p2p.network.Connection: We got 2 sendMessage requests in less than 20 ms. We set the thread to sleep for 50 ms to avoid flooding our peer. lastSendTimeStamp=1551943292270, now=1551943292270, elapsed=0, networkEnvelope=RefreshOfferMessage 
mars-07 08:21:40.534 [NetworkNode:SendMessage-to-506a780f-d50d-4c49-83b4-ef6cef6d6c22] WARN  b.n.p2p.network.Connection: We got 2 sendMessage requests in less than 20 ms. We set the thread to sleep for 50 ms to avoid flooding our peer. lastSendTimeStamp=1551943300517, now=1551943300534, elapsed=17, networkEnvelope=RefreshOfferMessage 
mars-07 08:21:41.094 [NetworkNode:SendMessage-to-c9d7c681-b104-40c9-9497-f236b643e43b] 

Those messages are quite numerous.
Is it just my configuration ?
There is 0 open offers/trades/disputes. (edited) 
The app itself seems running ok.

**Comment by devinbileck** [comment]
I dont think those are anything to be concerned with. It appears to be debug messages and @ManfredKarrer already changed the logging level to debug with this commit: https://github.com/bisq-network/bisq/pull/2505/commits/13dfadddcbb8a23f7022ebb88212253491523343

**Comment by ghost** [comment]
Thanks @devinbileck for the answer ,
But do you have an idea why there are so much sendMessage requests in such short time ?
My appli has 0 offers/trades/disputes. Why does it need to speak so much with the network ?
Hopefully it is intercepted. But if each node were sending so much messages, that seems a huge load for the network. Isn't it ?

**Comment by devinbileck** [comment]
Good question, especially since the message type is RefreshOfferMessage. However, I am not familiar with that area so it would be a question for @ManfredKarrer.

**Comment by freimair** [comment]
We are not quite sure why this behavior started to show. It seems that we might have some sort of resonance in the network: 
![screenshot from 2019-03-07 13-41-01](https://user-images.githubusercontent.com/1070734/53957458-b1b72d00-40de-11e9-8b44-7f42b92d2709.png)

the plan of action is as follows:
- manfred added some configuration options to the code #2494 so we can tweak and see if we can change the frequency
- I am working on a simulation environment for the network which might allow us to better understand what is going on
- I am working on a proposal about creating a message collection message. goal is to not put the sender to sleep but instead collecting them and sending the collection later

do you guys have another explanation to the network load behavior?

**Comment by ghost** [comment]
There may indeed be some resonance at work, because it seems there were some quiet hours during the GMT night.
But, for the last hours in GMT (since 12:00 GMT at least), this message is 95% of Bisq's CLI output.

**Comment by ManfredKarrer** [comment]
Is already reverted to debug.
