### ISSUE TITLE
Application freezes on take offer screen

### ISSUE THREAD

**Issue by wallacedf** [bisq-network/bisq#2509]
Hello!

I'm using Bisq 0.9.5 on Linux and I noticed that whenever I try to sell BTC, the application freezes on the screen that asks you to fund the offer either with your Bisq wallet and using an external wallet.

The app becomes impossible to use and I can see that it seems to consume all available RAM until it finally crashes:
![memory-issue](https://user-images.githubusercontent.com/13702153/53960062-013c2f80-40c4-11e9-8ec1-d1ffe03bdfb2.png)

It looks like some loop is leaking memory... I suspect it might be related with the 'Waiting payment confirmation....' process but I can't tell. I really love the whole concept behind Bisq but this is such a really annoying issue and might scare people away from using Bisq, specially because the app may crash right after you confirm that you want to take an offer. It would be a really great thing to fix.

Thank you!

**Comment by ripcurlx** [comment]
@wallacedf Could you please post the log output when you experience this issue, so we can see why this is behaving like that for you.

**Comment by wallacedf** [comment]
@ripcurlx , thanks for the quick reply. That's what I get in the logs when the issue happens:
[bisq.log](https://github.com/bisq-network/bisq/files/2941445/bisq.log)

**Comment by ripcurlx** [comment]
This might be related to https://github.com/bisq-network/bisq/issues/2506.

@ManfredKarrer As we see in the log file `We got 2 sendMessage requests in less than 20 ms. We set the thread to sleep for 50 ms to avoid flooding our peer.` In kind of a endless loop. Can it be that this is related to the deposit and trading fee transaction that are now in version 0.9.5 sent in closer time range than before?

**Comment by ripcurlx** [comment]
But actually not - as this happens during offer creation, not when taking the offer.

**Comment by ripcurlx** [comment]
@wallacedf Are you taking a buy offer to sell BTC or creating a new one?

**Comment by ripcurlx** [comment]
Looking at the log file @wallacedf is taking an existing offer, so it might be related to the latest change to prevent lost trading fees.

**Comment by wallacedf** [comment]
I'm taking an existing offer. And I also had the same issue with 0.9.4. I updated to 0.9.5 hoping that it would be gone but it happens both in 0.9.4 and 0.9.5

**Comment by ManfredKarrer** [comment]
Do you run on a desktop or VM? How much ram do you have? Which OS?

**Comment by wallacedf** [comment]
Hi @ManfredKarrer ,

I run Bisq on a real Lubuntu 16.10 machine. I have 8 GB of RAM. When I run into the issue, RAM starts as low as 1GB and eventually all 8 GB are consumed -- making the whole OS unresponsive until I kill Bisq's process and then everything gets back to normal.

**Comment by peterzen** [comment]
I've been experiencing a memory leak also, running on a VPS with 2G RAM.  The app runs without problems for several days and eventually it runs out of heap space and produces similar symptoms (unresponsive UI).  This happens both with or without buy or sell orders being active.  

Ubuntu 18.04
openjdk-11-jdk-headless

**Comment by ManfredKarrer** [comment]
@peterzen Do you use latest master version or latest release?
jdk 11 is not supported yet. Better use openjdk-10 to be sure that there are not issues.

**Comment by ManfredKarrer** [comment]
@wallacedf Do you use latest master version or latest release?

**Comment by ManfredKarrer** [comment]
If you run master, please update to latest commit, there have been issues in one of the past commits.

**Comment by peterzen** [comment]
Running 0.9.5, been experiencing this since 0.9.3

**Comment by ManfredKarrer** [comment]
@peterzen from master or release? Can you try from master to verify if its still there?

**Comment by peterzen** [comment]
From 0.9.5 release - restarted the app on openJDK 10, will keep it running for a few days and report back to confirm whether the problem persists.

**Comment by peterzen** [comment]
> From 0.9.5 release - restarted the app on openJDK 10, will keep it running for a few days and report back to confirm whether the problem persists.

It is looking good on my end - the leak seems to be gone on the above setup.

**Comment by ManfredKarrer** [comment]
Maybe its related to JDK 11?

**Comment by peterzen** [comment]
Quite possibly, 0.9.3-0.9.5 was reproducibly running out of heap space after a few days with or without active orders being on.

**Comment by wallacedf** [comment]
I'm still experiencing the issue using JDK 8. I'll try to run it using  JDK 10 and see if it also solves for me. Thanks!

**Comment by ManfredKarrer** [comment]
@wallacedf You use prob. an old version of Bisq. If you run from source you need to use JDK 10. If you run the binary the JDK is packed into the binary so your local JDK is irrelevant. If you run from binary which version do you use? Please update to latest as ther has been a fix realted to that.

**Comment by wallacedf** [comment]
I installed and use the version from https://bisq.network/downloads/v0.9.5/Bisq-64bit-0.9.5.deb

Is there an updated one?

**Comment by ghost** [comment]
@wallacedf 
v0.9.5 is the last version.
If you use the binary, the installed java version doesn't matter.

The installed java version only matters if you build from the sources.

**Comment by ripcurlx** [comment]
@wallacedf Are you still experiencing this problem with the current version?

**Comment by cd2357** [comment]
Should be fixed in the most recent release (v1.6.4) which brings massive UI performance improvements. Please try it out and let us know if it's still an issue for you.
