### ISSUE TITLE
Add proposal uid(txid) to the proposal details view

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#2510]
The proposal uid should be added as a field at the end of the selected proposal content to be able to differentiate proposals with the exact same content.
![Bildschirmfoto 2019-03-07 um 16.43.46.png](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/322d0cdb-0322-4b80-bafd-64a901651aab)

e.g. for the general proposal

- Proposal Type
- Name/nickname
- Link to detail info
- **Proposal Id**
- My vote
- Vote result summary

**Comment by ripcurlx** [comment]
@ben-kaufman If you are available also for this task, then it would be yours 😄

**Comment by ben-kaufman** [comment]
@ripcurlx Sure, I'll do that first.

**Comment by ripcurlx** [comment]
@ben-kaufman Great thanks!
Could your ask @ManfredKarrer to add you as a contributor for our repo, so I'm able to assign you?

**Comment by ben-kaufman** [comment]
Will ask on Slack.

**Comment by ManfredKarrer** [comment]
Sent an invite
