### ISSUE TITLE
Remove ghost offers

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#2518]
In the market/spread tab, the bottom has half a dozen (or more) ghost offers
corresponding to delisted altcoins (ACH, PPI, PEPECASH, etc)

If those offers are not removed in a way or another, 
it eats cumbersome and unnecessarily place.
And of course, this unnecessarily occupied place is only growing.

I wonder if it should not be specified in the trading conditions
that offers from delisted assets will be removed,
and that the makers should apply for reimbursement.

**Comment by ManfredKarrer** [comment]
It is valid that users who have setup an account earlier use and trade that. They will fade out over time by itself... But yes we could filter those which are not supported anymore and which you dont have in yout account.
