### ISSUE TITLE
After following building process folder build/distributions is not created

### ISSUE THREAD

**Issue by igarciaes** [bisq-network/bisq#252]
I have tried to build from sources. The build through gradlew was fine but the distributions folder is not created. The folders created inside the build folder are:
classes  dependency-cache  jacoco  libs  reports  resources  test-results  tmp
but not distributions folder :-(
The environment is Ubuntu 14.04 and javac 1.8.0_25
Thanks in adavance!

**Comment by cbeams** [comment]
Sorry, the instructions are out of date. Run the following instead:

```
./gradlew shadowJar
```

and you'll find an executable jar available in 

```
build/libs/bitsquare-0.1.0-SNAPSHOT-all.jar
```

Run it with

```
build/libs/bitsquare-0.1.0-SNAPSHOT-all.jar
```

If you want to build the native installer, run

```
./gradlew packageNative
```

You'll find the result in

```
build/bundles
```

**Comment by igarciaes** [comment]
All right thank you @cbeams, now it works!
