### ISSUE TITLE
Details in confiscation request missing

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2522]
At voting the option field is empty. It should contain the data about the bond to confiscate.
At create proposal it is displayed.

<img width="977" alt="Screen Shot 2019-03-10 at 19 48 31" src="https://user-images.githubusercontent.com/1449498/54094259-a6c5fc00-436d-11e9-85eb-3e9f06180924.png">

**Comment by ManfredKarrer** [comment]
@ben-kaufman If you have time do you want to take that?

**Comment by ManfredKarrer** [comment]
Seems with a bonded role it works. Might be only missing if it was confiscation for a bonded reputation.

<img width="640" alt="Screen Shot 2019-03-10 at 19 53 20" src="https://user-images.githubusercontent.com/1449498/54094352-34a1e700-436e-11e9-9c8e-32a82f62bfd8.png">

**Comment by ben-kaufman** [comment]
Sure, I'll try to fix this.
