### ISSUE TITLE
ERROR i.b.msg.BootstrappedPeerFactory - Bootstrap using relay has failed Future

### ISSUE THREAD

**Issue by igarciaes** [bisq-network/bisq#253]
After build I tried to execute but I get an error message:

ERROR i.b.msg.BootstrappedPeerFactory - Bootstrap using relay has failed Future

Environment Ubuntu 14.04 Java(TM) SE Runtime Environment (build 1.8.0_25-b17)

Full stack trace:

java -jar bitsquare-0.1.0-SNAPSHOT-all.jar 
17:56:24.069 [JavaFX Application Thread] TRACE io.bitsquare.gui.util.Profiler - 

Called by: Bitsquare.start called 
Elapsed time: 0ms 
Total time:   17ms

[DEBUG] [11/04/2014 17:56:24.981] [JavaFX Application Thread] [EventStream] StandardOutLogger started
[DEBUG] [11/04/2014 17:56:25.305] [JavaFX Application Thread] [EventStream(akka://Bitsquare)] logger log1-Logging$DefaultLogger started
[DEBUG] [11/04/2014 17:56:25.305] [JavaFX Application Thread] [EventStream(akka://Bitsquare)] logger log1-Logging$DefaultLogger started
[DEBUG] [11/04/2014 17:56:25.307] [JavaFX Application Thread] [EventStream(akka://Bitsquare)] Default Loggers started
[DEBUG] [11/04/2014 17:56:25.307] [JavaFX Application Thread] [EventStream(akka://Bitsquare)] Default Loggers started
17:56:25.852 [JavaFX Application Thread] TRACE io.bitsquare.persistence.Persistence - File not found is ok for the first execute. 
17:56:25.853 [JavaFX Application Thread] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.trade.TradeManager.offers not found. 
17:56:25.853 [JavaFX Application Thread] TRACE io.bitsquare.persistence.Persistence - File not found is ok for the first execute. 
17:56:25.854 [JavaFX Application Thread] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.trade.TradeManager.pendingTrades not found. 
17:56:25.854 [JavaFX Application Thread] TRACE io.bitsquare.persistence.Persistence - File not found is ok for the first execute. 
17:56:25.854 [JavaFX Application Thread] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.trade.TradeManager.closedTrades not found. 
17:56:27.412 [JavaFX Application Thread] TRACE io.bitsquare.gui.util.Profiler - 

Called by: Bitsquare: messageFacade, walletFacade created 
Elapsed time: 3346ms 
Total time:   3363ms

17:56:27.416 [JavaFX Application Thread] TRACE io.bitsquare.persistence.Persistence - File not found is ok for the first execute. 
17:56:27.596 [JavaFX Application Thread] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.user.User not found. 
17:56:27.849 [JavaFX Application Thread] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.settings.Settings not found. 
17:56:28.033 [JavaFX Application Thread] DEBUG io.bitsquare.util.ViewLoader - load from disc jar:file:/home/igarcia/Documentos/git/bitsquare/build/libs/bitsquare-0.1.0-SNAPSHOT-all.jar!/io/bitsquare/gui/main/MainView.fxml 
17:56:28.476 [JavaFX Application Thread] TRACE io.bitsquare.gui.ViewCB - Lifecycle: initialize MainViewCB 
17:56:28.478 [JavaFX Application Thread] TRACE io.bitsquare.gui.PresentationModel - Lifecycle: initialize MainPM 
17:56:28.479 [JavaFX Application Thread] TRACE io.bitsquare.gui.UIModel - Lifecycle: initialize MainModel 
17:56:28.482 [JavaFX Application Thread] TRACE io.bitsquare.gui.util.Profiler - 

Called by: MainController.initialize 
Elapsed time: 1070ms 
Total time:   4433ms

17:56:32.060 [JavaFX Application Thread] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.msg.BootstrappedPeerFactory.bootstrapCounter not found. 
17:56:32.111 [JavaFX Application Thread] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.msg.BootstrappedPeerFactory.lastSuccessfulBootstrap not found. 
17:56:32.111 [JavaFX Application Thread] DEBUG i.b.msg.BootstrappedPeerFactory - lastSuccessfulBootstrap = default 
17:56:32.133 [JavaFX Application Thread] TRACE io.bitsquare.gui.util.Profiler - 

Called by: MainModel.initFacades 
Elapsed time: 3651ms 
Total time:   8084ms

17:56:34.970 [ STARTING] WARN  org.bitcoinj.core.AbstractBlockChain - Wallet/chain height mismatch: 0 vs 270144 
17:56:34.971 [ STARTING] WARN  org.bitcoinj.core.AbstractBlockChain - Hashes: null vs 00000000000077b9692e5d4fe4f27b372067638da43bd05d8c6c654600cd520b 
17:56:35.483 [ STARTING] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.btc.WalletFacade.addressEntryList not found. 
17:56:37.337 [NETTY-TOMP2P - worker-client/server - -1-8] WARN  net.tomp2p.connection.TimeoutFactory - channel timeout for channel Sender [id: 0x0f267159, /192.168.1.40:35619 => /188.226.179.109:5000] 
17:56:37.339 [NETTY-TOMP2P - worker-client/server - -1-8] WARN  net.tomp2p.connection.TimeoutFactory - Request status is msgid=2143904285,t=REQUEST_2,c=PING,tcp,s=paddr[0x5834a5729bd1a46d0105f58a9da0dfaee3ef7fc6[/192.168.1.35,61648]]/relay(false)/slow(false),r=paddr[0x7728a3c6e3351739891ca100b5fb774ec5af4ddf[/188.226.179.109,5000]]/relay(false)/slow(false) 
17:56:37.351 [NETTY-TOMP2P - worker-client/server - -1-8] INFO  i.b.msg.BootstrappedPeerFactory - We are probably behind a NAT and not reachable to other peers. We try port forwarding as next step. 
17:56:37.389 [NETTY-TOMP2P - worker-client/server - -1-8] INFO  i.b.msg.BootstrappedPeerFactory - Port forwarding has failed. We try to use a relay as next step. 
17:56:37.395 [NETTY-TOMP2P - worker-client/server - -1-8] ERROR i.b.msg.BootstrappedPeerFactory - Bootstrap using relay has failed Future (compl/canc):true/false, FAILED, FutureBootstrap failed <-> Future (compl/canc):true/false, FAILED, You did not provide information where to bootstrap to. This could be also caused if you provided a peer address with a peer ID set to zero. 
17:56:37.475 [NETTY-TOMP2P - worker-client/server - -1-8] ERROR io.bitsquare.msg.P2PNode - onFailure bootstrap java.lang.Exception: Bootstrap using relay failed Future (compl/canc):true/false, FAILED, FutureBootstrap failed <-> Future (compl/canc):true/false, FAILED, You did not provide information where to bootstrap to. This could be also caused if you provided a peer address with a peer ID set to zero. 
17:56:37.475 [NETTY-TOMP2P - worker-client/server - -1-8] ERROR io.bitsquare.msg.TomP2PMessageFacade - java.lang.Exception: Bootstrap using relay failed Future (compl/canc):true/false, FAILED, FutureBootstrap failed <-> Future (compl/canc):true/false, FAILED, You did not provide information where to bootstrap to. This could be also caused if you provided a peer address with a peer ID set to zero. 
17:56:37.477 [JavaFX Application Thread] ERROR io.bitsquare.gui.main.MainModel - java.lang.Exception: Bootstrap using relay failed Future (compl/canc):true/false, FAILED, FutureBootstrap failed <-> Future (compl/canc):true/false, FAILED, You did not provide information where to bootstrap to. This could be also caused if you provided a peer address with a peer ID set to zero. 
17:56:40.645 [PeerGroup] WARN  o.b.net.discovery.DnsDiscovery - DNS seed testnet-seed.bitcoin.schildbach.de: timed out 
17:56:40.676 [PeerGroup] ERROR org.bitcoinj.net.NioClientManager - Could not connect to testnet-seed.bitcoin.petertodd.org/2400:8900:0:0:f03c:91ff:fe6e:8a41:18333 
17:56:40.677 [PeerGroup] WARN  org.bitcoinj.core.PeerGroup - Failed to connect to [2400:8900:0:0:f03c:91ff:fe6e:8a41]:18333: java.net.SocketException: La red es inaccesible 
17:56:40.802 [NioClientManager] ERROR org.bitcoinj.net.NioClientManager - Failed to connect with exception: java.net.ConnectException: Conexión rehusada 
17:56:41.959 [NioClientManager] ERROR org.bitcoinj.net.ConnectionHandler - Error handling SelectionKey: Conexión reinicializada por la máquina remota 
17:56:50.991 [NioClientManager] WARN  org.bitcoinj.core.AbstractBlockChain - Block does not connect: 0000000074cf72f29ab6848daa9bf7721a54b7886b732336efcb50fac70765c1 prev 00000000c0f6e6ce7769fbd489157f5989a5b980282186b030da9766f556e925 
17:58:47.860 [NioClientManager] ERROR org.bitcoinj.net.NioClientManager - Failed to connect with exception: java.nio.channels.ClosedChannelException: null 

^Cigarcia@igarcia-emachines:~/Documentos/git/bitsquare/build/libs$ 
igarcia@igarcia-emachines:~/Documentos/git/bitsquare/build/libs$ java -jar bitsquare-0.1.0-SNAPSHOT-all.jar 
18:04:23.737 [JavaFX Application Thread] TRACE io.bitsquare.gui.util.Profiler - 

Called by: Bitsquare.start called 
Elapsed time: 0ms 
Total time:   2ms

[DEBUG] [11/04/2014 18:04:25.620] [JavaFX Application Thread] [EventStream] StandardOutLogger started
[DEBUG] [11/04/2014 18:04:26.262] [JavaFX Application Thread] [EventStream(akka://Bitsquare)] logger log1-Logging$DefaultLogger started
[DEBUG] [11/04/2014 18:04:26.262] [JavaFX Application Thread] [EventStream(akka://Bitsquare)] logger log1-Logging$DefaultLogger started
[DEBUG] [11/04/2014 18:04:26.264] [JavaFX Application Thread] [EventStream(akka://Bitsquare)] Default Loggers started
[DEBUG] [11/04/2014 18:04:26.264] [JavaFX Application Thread] [EventStream(akka://Bitsquare)] Default Loggers started
18:04:26.933 [JavaFX Application Thread] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.trade.TradeManager.offers not found. 
18:04:26.939 [JavaFX Application Thread] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.trade.TradeManager.pendingTrades not found. 
18:04:26.944 [JavaFX Application Thread] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.trade.TradeManager.closedTrades not found. 
18:04:32.197 [JavaFX Application Thread] TRACE io.bitsquare.gui.util.Profiler - 

Called by: Bitsquare: messageFacade, walletFacade created 
Elapsed time: 8462ms 
Total time:   8464ms

18:04:32.208 [JavaFX Application Thread] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.user.User not found. 
18:04:32.505 [JavaFX Application Thread] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.settings.Settings not found. 
18:04:32.987 [JavaFX Application Thread] DEBUG io.bitsquare.util.ViewLoader - load from disc jar:file:/home/igarcia/Documentos/git/bitsquare/build/libs/bitsquare-0.1.0-SNAPSHOT-all.jar!/io/bitsquare/gui/main/MainView.fxml 
18:04:34.200 [JavaFX Application Thread] TRACE io.bitsquare.gui.ViewCB - Lifecycle: initialize MainViewCB 
18:04:34.204 [JavaFX Application Thread] TRACE io.bitsquare.gui.PresentationModel - Lifecycle: initialize MainPM 
18:04:34.204 [JavaFX Application Thread] TRACE io.bitsquare.gui.UIModel - Lifecycle: initialize MainModel 
18:04:34.208 [JavaFX Application Thread] TRACE io.bitsquare.gui.util.Profiler - 

Called by: MainController.initialize 
Elapsed time: 2011ms 
Total time:   10475ms

18:04:39.048 [JavaFX Application Thread] DEBUG i.b.msg.BootstrappedPeerFactory - lastSuccessfulBootstrap = default 
18:04:39.068 [JavaFX Application Thread] TRACE io.bitsquare.gui.util.Profiler - 

Called by: MainModel.initFacades 
Elapsed time: 4860ms 
Total time:   15335ms

18:04:44.439 [NETTY-TOMP2P - worker-client/server - -1-8] WARN  net.tomp2p.connection.TimeoutFactory - channel timeout for channel Sender [id: 0x55e9ed49, /192.168.1.40:51755 => /188.226.179.109:5000] 
18:04:44.440 [NETTY-TOMP2P - worker-client/server - -1-8] WARN  net.tomp2p.connection.TimeoutFactory - Request status is msgid=649569212,t=REQUEST_2,c=PING,tcp,s=paddr[0xb843ed23ddda52847c5a6a38c85b292c01595956[/192.168.1.35,50955]]/relay(false)/slow(false),r=paddr[0x7728a3c6e3351739891ca100b5fb774ec5af4ddf[/188.226.179.109,5000]]/relay(false)/slow(false) 
18:04:44.449 [NETTY-TOMP2P - worker-client/server - -1-8] INFO  i.b.msg.BootstrappedPeerFactory - We are probably behind a NAT and not reachable to other peers. We try port forwarding as next step. 
18:04:44.474 [NETTY-TOMP2P - worker-client/server - -1-8] INFO  i.b.msg.BootstrappedPeerFactory - Port forwarding has failed. We try to use a relay as next step. 
18:04:44.481 [NETTY-TOMP2P - worker-client/server - -1-8] ERROR i.b.msg.BootstrappedPeerFactory - Bootstrap using relay has failed Future (compl/canc):true/false, FAILED, FutureBootstrap failed <-> Future (compl/canc):true/false, FAILED, You did not provide information where to bootstrap to. This could be also caused if you provided a peer address with a peer ID set to zero. 
18:04:44.542 [NETTY-TOMP2P - worker-client/server - -1-8] ERROR io.bitsquare.msg.P2PNode - onFailure bootstrap java.lang.Exception: Bootstrap using relay failed Future (compl/canc):true/false, FAILED, FutureBootstrap failed <-> Future (compl/canc):true/false, FAILED, You did not provide information where to bootstrap to. This could be also caused if you provided a peer address with a peer ID set to zero. 
18:04:44.549 [NETTY-TOMP2P - worker-client/server - -1-8] ERROR io.bitsquare.msg.TomP2PMessageFacade - java.lang.Exception: Bootstrap using relay failed Future (compl/canc):true/false, FAILED, FutureBootstrap failed <-> Future (compl/canc):true/false, FAILED, You did not provide information where to bootstrap to. This could be also caused if you provided a peer address with a peer ID set to zero. 
18:04:44.554 [JavaFX Application Thread] ERROR io.bitsquare.gui.main.MainModel - java.lang.Exception: Bootstrap using relay failed Future (compl/canc):true/false, FAILED, FutureBootstrap failed <-> Future (compl/canc):true/false, FAILED, You did not provide information where to bootstrap to. This could be also caused if you provided a peer address with a peer ID set to zero. 
18:04:46.611 [PeerGroup] WARN  o.b.net.discovery.DnsDiscovery - DNS seed testnet-seed.bitcoin.schildbach.de: timed out 
18:04:46.636 [PeerGroup] ERROR org.bitcoinj.net.NioClientManager - Could not connect to testnet-seed.bitcoin.petertodd.org/2604:a880:800:10:0:0:12e:4001:18333 
18:04:46.636 [PeerGroup] WARN  org.bitcoinj.core.PeerGroup - Failed to connect to [2604:a880:800:10:0:0:12e:4001]:18333: java.net.SocketException: La red es inaccesible 
18:04:47.638 [PeerGroup] ERROR org.bitcoinj.net.NioClientManager - Could not connect to testnet-seed.bitcoin.petertodd.org/2400:8900:0:0:f03c:91ff:fe6e:8a41:18333 
18:04:47.639 [PeerGroup] WARN  org.bitcoinj.core.PeerGroup - Failed to connect to [2400:8900:0:0:f03c:91ff:fe6e:8a41]:18333: java.net.SocketException: La red es inaccesible 
18:04:48.975 [NioClientManager] ERROR org.bitcoinj.net.ConnectionHandler - Error handling SelectionKey: Conexión reinicializada por la máquina remota

**Comment by ManfredKarrer** [comment]
@igarciaes Thanks for reporting. Seems you cannot connect to the internet. Both the connection ot Bitcoins seed nodes and our seed nodes failed. I restarted our seed node just in case, but the testnet seed node should work basically.
You can test it also locally only when changing to regtest mode for bitcoin and to localhost for tomp2p. you can change that in BitcoinModule and in DefaultMessageModule. Instructions about the regtest mode you can find at the BitcoinJ site (https://bitcoinj.github.io/testing).
If you switch to localhost you need to run a local seednode. Either start SeedNode directly or Bitsquare with the -s flag.
We are doing a lot of testing at the moment so it might be better to use a local node to not rely on our current node.
If you want to test 2 instances to simulate a trade you need to pass a name to one of the instances with teh -n flag (e.g. Bitsquare -n Alice)

**Comment by igarciaes** [comment]
Ok, thank you @ManfredKarrer now It works!

**Comment by ManfredKarrer** [comment]
With the local version?

**Comment by igarciaes** [comment]
Yes at local
