### ISSUE TITLE
Removal of money orders as payment method

### ISSUE THREAD

**Issue by keo-bisq** [bisq-network/bisq#2535]
US money orders cannot be arbitrated well. Only photos can be used for proving a money order was sent and worse is that the receiver name does not have to be written on the money order only on the envelope. If the money order is stolen and cashed who is to blame? The name of the person cashing the MO is typically not checked well or not at all against ID. I have at least one such case now.

Given the low use of money orders I suggest they should be deleted as a possible payment method.

**Comment by ManfredKarrer** [comment]
@keo-bisq Could you create a proposal for removing it at https://github.com/bisq-network/proposals/?

**Comment by ManfredKarrer** [comment]
Seems the proposal got rejected.
