### ISSUE TITLE
Partial Success

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#254]
I would like to participate in this project as a Developer.

I am working on building this from source on my Ubuntu system.  Everything goes pretty well but when I try to run the app I get a few errors.  I suspect it is the result of some incomplete configuration issues.

Here is the output from my gradlew run command:

ivan@zaarkaan:~/workspace_ai/bitsquare$ gradlew run
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
12:01:51.017 [JavaFX Application Thread] TRACE io.bitsquare.gui.util.Profiler - 

Called by: Bitsquare.start called 
Elapsed time: 0ms 
Total time:   40ms

[DEBUG] [11/04/2014 12:01:51.588] [JavaFX Application Thread] [EventStream] StandardOutLogger started
[DEBUG] [11/04/2014 12:01:51.766] [JavaFX Application Thread] [EventStream(akka://Bitsquare)] logger log1-Logging$DefaultLogger started
[DEBUG] [11/04/2014 12:01:51.766] [JavaFX Application Thread] [EventStream(akka://Bitsquare)] logger log1-Logging$DefaultLogger started
[DEBUG] [11/04/2014 12:01:51.767] [JavaFX Application Thread] [EventStream(akka://Bitsquare)] Default Loggers started
[DEBUG] [11/04/2014 12:01:51.767] [JavaFX Application Thread] [EventStream(akka://Bitsquare)] Default Loggers started
12:01:52.081 [JavaFX Application Thread] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.trade.TradeManager.offers not found. 
12:01:52.084 [JavaFX Application Thread] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.trade.TradeManager.pendingTrades not found. 
12:01:52.086 [JavaFX Application Thread] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.trade.TradeManager.closedTrades not found. 
12:01:52.298 [JavaFX Application Thread] TRACE io.bitsquare.gui.util.Profiler - 

Called by: Bitsquare: messageFacade, walletFacade created 
Elapsed time: 1281ms 
Total time:   1322ms

12:01:52.303 [JavaFX Application Thread] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.user.User not found. 
12:01:52.323 [JavaFX Application Thread] INFO  io.bitsquare.persistence.Persistence - Object with key = io.bitsquare.settings.Settings not found. 
12:01:52.366 [JavaFX Application Thread] DEBUG io.bitsquare.util.ViewLoader - load from disc file:/home/ivan/workspace_ai/bitsquare/build/resources/main/io/bitsquare/gui/main/MainView.fxml 
12:01:52.439 [JavaFX Application Thread] TRACE io.bitsquare.gui.ViewCB - Lifecycle: initialize MainViewCB 
12:01:52.440 [JavaFX Application Thread] TRACE io.bitsquare.gui.PresentationModel - Lifecycle: initialize MainPM 
12:01:52.440 [JavaFX Application Thread] TRACE io.bitsquare.gui.UIModel - Lifecycle: initialize MainModel 
12:01:52.442 [JavaFX Application Thread] TRACE io.bitsquare.gui.util.Profiler - 

Called by: MainController.initialize 
Elapsed time: 144ms 
Total time:   1466ms

java.net.BindException: Address already in use
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:414)
    at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:702)
    at sun.nio.ch.DatagramSocketAdaptor.bind(DatagramSocketAdaptor.java:91)
    at io.netty.channel.socket.nio.NioDatagramChannel.doBind(NioDatagramChannel.java:192)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:478)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1021)
    at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:455)
    at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:440)
    at io.netty.channel.ChannelOutboundHandlerAdapter.bind(ChannelOutboundHandlerAdapter.java:35)
    at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:455)
    at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:440)
    at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:844)
    at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:197)
    at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:350)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
12:01:53.174 [pool-2-thread-1] WARN  net.tomp2p.connection.ChannelServer - cannot bind broadcast UDP /0.0.0.0:54837 
12:01:53.202 [JavaFX Application Thread] DEBUG i.b.msg.BootstrappedPeerFactory - lastSuccessfulBootstrap = default 
12:01:53.222 [JavaFX Application Thread] TRACE io.bitsquare.gui.util.Profiler - 

Called by: MainModel.initFacades 
Elapsed time: 780ms 
Total time:   2246ms

12:01:58.383 [NETTY-TOMP2P - worker-client/server - -1-8] WARN  net.tomp2p.connection.TimeoutFactory - channel timeout for channel Sender [id: 0x63a11055, /192.168.0.134:53061 => /188.226.179.109:5000] 
12:01:58.383 [NETTY-TOMP2P - worker-client/server - -1-8] WARN  net.tomp2p.connection.TimeoutFactory - Request status is msgid=1602845184,t=REQUEST_2,c=PING,tcp,s=paddr[0xaa8177922286d81e98f32f46313452ed6e33e078[/172.17.42.1,54837]]/relay(false)/slow(false),r=paddr[0x7728a3c6e3351739891ca100b5fb774ec5af4ddf[/188.226.179.109,5000]]/relay(false)/slow(false) 
12:01:58.388 [NETTY-TOMP2P - worker-client/server - -1-8] INFO  i.b.msg.BootstrappedPeerFactory - We are probably behind a NAT and not reachable to other peers. We try port forwarding as next step. 
12:01:58.398 [NETTY-TOMP2P - worker-client/server - -1-8] INFO  i.b.msg.BootstrappedPeerFactory - Port forwarding has failed. We try to use a relay as next step. 
12:01:58.401 [NETTY-TOMP2P - worker-client/server - -1-8] ERROR i.b.msg.BootstrappedPeerFactory - Bootstrap using relay has failed Future (compl/canc):true/false, FAILED, FutureBootstrap failed <-> Future (compl/canc):true/false, FAILED, You did not provide information where to bootstrap to. This could be also caused if you provided a peer address with a peer ID set to zero. 
12:01:58.414 [NETTY-TOMP2P - worker-client/server - -1-8] ERROR io.bitsquare.msg.P2PNode - onFailure bootstrap java.lang.Exception: Bootstrap using relay failed Future (compl/canc):true/false, FAILED, FutureBootstrap failed <-> Future (compl/canc):true/false, FAILED, You did not provide information where to bootstrap to. This could be also caused if you provided a peer address with a peer ID set to zero. 
12:01:58.414 [NETTY-TOMP2P - worker-client/server - -1-8] ERROR io.bitsquare.msg.TomP2PMessageFacade - java.lang.Exception: Bootstrap using relay failed Future (compl/canc):true/false, FAILED, FutureBootstrap failed <-> Future (compl/canc):true/false, FAILED, You did not provide information where to bootstrap to. This could be also caused if you provided a peer address with a peer ID set to zero. 
12:01:58.415 [JavaFX Application Thread] ERROR io.bitsquare.gui.main.MainModel - java.lang.Exception: Bootstrap using relay failed Future (compl/canc):true/false, FAILED, FutureBootstrap failed <-> Future (compl/canc):true/false, FAILED, You did not provide information where to bootstrap to. This could be also caused if you provided a peer address with a peer ID set to zero. 
12:01:58.815 [PeerGroup] WARN  o.b.net.discovery.DnsDiscovery - DNS seed testnet-seed.bitcoin.schildbach.de: timed out 
12:01:58.828 [PeerGroup] ERROR org.bitcoinj.net.NioClientManager - Could not connect to testnet-seed.bitcoin.petertodd.org/2400:8900:0:0:f03c:91ff:fe6e:8a41:18333 
12:01:58.828 [PeerGroup] WARN  org.bitcoinj.core.PeerGroup - Failed to connect to [2400:8900:0:0:f03c:91ff:fe6e:8a41]:18333: java.net.SocketException: Network is unreachable 
12:01:59.829 [PeerGroup] ERROR org.bitcoinj.net.NioClientManager - Could not connect to testnet-seed.bitcoin.petertodd.org/2604:a880:800:10:0:0:12e:4001:18333 
12:01:59.829 [PeerGroup] WARN  org.bitcoinj.core.PeerGroup - Failed to connect to [2604:a880:800:10:0:0:12e:4001]:18333: java.net.SocketException: Network is unreachable 

> Building 75% > :run

**Comment by ManfredKarrer** [comment]
Hi @ivank2139 
Ah great to hear you are interested in partizipating!

Another user just reported the same issue. Stange, seems that the internet connection ot the bitcoin seed nodes is not working.
I will have a look to the issue tomorrow. I just wrote a description regarding a local test environment in the other issue (#253). Do you tried it also to run from IntelliJ directly?

**Comment by ghost** [comment]
Starting bitcoind first helps it get a little farther along.

**Comment by ManfredKarrer** [comment]
@ivank2139 Let me know if you still have problems. At the moment the local version is better for tesing it out, as we still have problems with the P2P network in WAN.
