### ISSUE TITLE
REQ Chat between trading partners to end frustration during long trades

### ISSUE THREAD

**Issue by pillex** [bisq-network/bisq#2540]
I like Bisq. I recommend Bisq. But currently it's frustrating to the point I don't want to use it anymore.

### **The problem:**

You've done everything right (or you think you did) - but the trade doesn't go through for days and days and days. You don't know whats the problem and you can't do anything to get any info.  You have one week to get more and more frustrated.  

**No solutions:** 

- Early Arbitration - it's not wanted during the waiting phase. It's overkill and most often not needed.
- Posting your problem with all the ids to the public forum - a joke for an exchange that wants be anon.

### **A solution:**

**A means of communication between the two trading partners during the trade. Preferably a chat or messaging window inside bisq.**

Examples of what happened:

Bought BTC with SEPA transfer. Waiting one day. 2 days. 3 days. Nothing. Getting frustrated. Feeling helpless. Whats wrong? I realized i made a mistake. Accidentally chose the wrong account, which will send the money. Is that the problem? Yes? No? Should I start arbitration? Do I have to wait one week? In the end I got the BTC after 6 days. Why so long? I have no idea. Did this for a friend. He said: "Bisq is sh... won't use it anymore"

A trade which is not resolved right now:
Bought BTC with SEPA. Sender and receiver bank accounts are in the same country. I'm sure I made everything right. Amount, account, trade id on sepa transfer. Hope the next day I have the BTC. Next day: Nothing. Second day: Nothing. Restarted Bisq 20 times: Nothing. Restarted PC 5 times: Nothing. Googled the receiver of the money: Tech guy at a university. Fraud chance: Very low. Handling problem on his side: Very low. Third day: Nothing. What can I do? Wait 7 days? A joke. Post everything publicly into the forum? A joke. Start arbitration? I can't, he can release the BTC during the next 4 days. I'm frustrated and start to hate bisq because it's unusable -  although I love it.

**What I want to do:**

Ask the money receiver:

Hey did you get the money?
Did you tell bisq you received the money?

If he doesn't answer, I know theres a problem with him.
If he says he didn't receive the money, I know what the problem is
If he says he received the money but couldn't release the BTC in bisq, I know what the problem is
If he says he released the BTC 2 days ago - I know it's a software problem.

I can wait if I know what the problem is.

But the 7 days without communication are just unacceptable.

### **Some random thoughts about the chat:**

- The chat should be visible for maker, taker - and in case of arbitration for the arbitrator

- The chat should be either an entity of the trade (separate chat for each trade) or an entity of the trader (one chat per trader) 

- One general chat with each trader would bring possibility to propose a trade later on after a successful trade.   

- For anon concerns: An option to auto-delete the chat xx days after completion of the trade

- For anon concerns: A button to delete the chat right now on YOUR OWN machine/account/tor-node

- Arbitrator should be able to read the chat in arbitration even if it was deleted by maker and/or taker.

- If trader has anon concerns with the chat, there could be a trade or trader option: "I do not accept chats" - which is visible before you enter a trade.

**Comment by ManfredKarrer** [comment]
After the DAO is out we will work on improvements for the trade protocol which includes that you can get in touch with the peer and that there is an mediator before it goes to arbitration. 
If you are sure that something went wrong you can open a dispute with cmd+o. But if the peer needs longer or the bank is slow there is unfortunately no good solution yet. The longer trade period for SEPA is required as some banks need 2-3 days and if there are holidays and weekends it gets longer. Though I think most trades gets settled much faster. Might be a bit of bad luck that you traded with a peer who had a slow banks or he was slow with sending the funds.
Atm we have a few p2p network issues so it can be that you do not receive the confirmation of the peer that he sent the funds. 

Regarding deleting data:
You never have any proof that the peer has not made a copy. Deleting data is basically impossible from a conceptula point of view. As soon data is shared (with peer, with arbitrator) you have to assume that is out of your control. You can always start over with a new data directory which improves your privavy. See the forum post about all te context to that topic.

**Comment by ManfredKarrer** [comment]
Btw. Would you mind to move that discussion to the Bisq Forum? We try to keep Github for technical issues (bugs).

**Comment by pillex** [comment]
Thanx for your quick answer. 

Saw this as a feature request. If the issue tracker is not for feature requests i'm fine with closing it.

> After the DAO is out we will work on improvements for the trade protocol which includes that you can get in touch with the peer and that there is an mediator before it goes to arbitration.

Great.

> If you are sure that something went wrong you can open a dispute with cmd+o. 

Thats the problem. I'n not sure at all.  I'm waiting for 3 days and I have no idea if there is a problem and what it might be.

> But if the peer needs longer or the bank is slow there is unfortunately no good solution yet. 

Thats not actually a problem for me. If I KNOW the peer needs longer, I can accept that. If I KNOW the bank needs longer, I can accept that. The problem is, that I have to wait one week before any communcation can take place.

If the trader tells me after 3 days, he hasn't received the money I know whats going on and I can wait. The frustration comes from the potential 7 days without any info or communication.

 
>The longer trade period for SEPA is required as some banks need 2-3 days and if there are holidays and weekends it gets longer. Though I think most trades gets settled much faster. Might be a bit of bad luck that you traded with a peer who had a slow banks or he was slow with sending the funds.

True. But you can compare it to the frustration if the subway isn't coming. 
A) Without getting any info at alland 
B) getting an explanation what happened and an estimated delay.


> Atm we have a few p2p network issues so it can be that you do not receive the confirmation of the peer that he sent the funds.

I read it. Thats ok. I restarted bisq several times.

> Regarding deleting data:
> You never have any proof that the peer has not made a copy. Deleting data is basically impossible from a conceptula point of view. 

True. Just added this in case the argument was "We can't have any chat because of anon concerns". Don't think this is a problem.

**Comment by ManfredKarrer** [comment]
I agree to all and as said we will have a solution for that soon once dev resources allows it.
