### ISSUE TITLE
Improve table layout

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2542]
If table rows are close together the lack of seperator makes the header titles very confusing:
<img width="948" alt="Screen Shot 2019-03-15 at 19 13 25" src="https://user-images.githubusercontent.com/1449498/54467939-7bb91f00-4756-11e9-8699-88251c3e7e92.png">

I think some ligth seperator would be good also in the rows.

**Comment by ripcurlx** [comment]
As this would have an effect on all tables I want to get @pedromvpg's opinion on that. I saw that you have changed it to "Previous hash" atm to workaround this issue.

**Comment by pedromvpg** [comment]
Seems to have been fixed. Can we close?
<img width="1225" alt="Screen Shot 2019-09-09 at 8 58 00 PM" src="https://user-images.githubusercontent.com/807505/64576009-93a7df00-d344-11e9-8741-0aeedc08fb3e.png">
