### ISSUE TITLE
error occured at task: TakerVerifyAndSignContract - contracts are not matching

### ISSUE THREAD

**Issue by sejktmcsdlmfhsc** [bisq-network/bisq#2544]
Hi dear bisq team,
I tried to take an XMR/BTC offer today 
(on debian9 distro:bunsen openbox, bisq 0.9.5) 
but got the following error:
```
error occured at task: TakerVerifyAndSignContract
exception msg: 
Contracts are not matching.
The taker fee is already paid. In the worst case you have lost that fee. 
```
The trade shows up in "open trades" but all the trade process steps are greyed out.
Under "funds" - "transactions" there is no transaction showing up for today - is my 
assumption correct then, that the fee is not lost?

Please advise on how to proceed.
Is there a way to resolve this one, inform the other trader and remove the blocked trade from open trades?
Is it save to try that trade pair / the trader again?
If that helps, I saved the portion of the log, but rather only send it directly.
Neutral excerpt can be found below.

@ManfredKarrer : Not sure for whom this topic would be suitable?

Thank you in advance!!
Best, sej

**Comment by sejktmcsdlmfhsc** [comment]
some excerpts from the log:
```
java.lang.IllegalArgumentException: Contracts are not matching
bisq.common.taskrunner.Task: An error occurred at task: TakerVerifyAndSignContract
Exception message: Contracts are not matching
ERROR b.common.taskrunner.TaskRunner: Task failed: TakerVerifyAndSignContract / errorMessage: An error occurred at task: TakerVerifyAndSignContract
Exception message: Contracts are not matching
ERROR b.c.t.protocol.TradeProtocol: An error occurred at task: TakerVerifyAndSignContract
Exception message: Contracts are not matching
INFO  b.c.t.protocol.TradeProtocol: Send AckMessage for PublishDepositTxRequest to peer xxzzyy.onion:9999. tradeId=xxzzyy, sourceUid=xxzzyy
WARN  b.c.t.protocol.TradeProtocol: cleanupTradableOnFault tradeState=TAKER_RECEIVED_PUBLISH_DEPOSIT_TX_REQUEST
ERROR b.c.t.protocol.TradeProtocol: We have already sent the prepared deposit tx to the peer but we did not received the reply about the deposit tx nor saw it in the network. tradeId=xxzzyy, tradeState=TAKER_RECEIVED_PUBLISH_DEPOSIT_TX_REQUEST
INFO  b.c.t.protocol.TradeProtocol: AckMessage for PublishDepositTxRequest arrived at peer xxyyvv.onion:9999. tradeId=xxyyzz, sourceUid=xxzzyy
WARN  bisq.core.trade.Trade: depositTx is null
WARN  bisq.core.trade.Trade: depositTx is null
INFO  b.core.provider.fee.FeeService: BTC tx fee: txFeePerByte=20
INFO  b.c.b.wallet.BtcWalletService: resetAddressEntriesForOpenOffer offerId=xxzzyy
INFO  b.c.b.wallet.BtcWalletService: swap addressEntry with address xxyyzz and offerId xxyyzz from context RESERVED_FOR_TRADE to available
```

**Comment by ManfredKarrer** [comment]
The error message is wrong. I have forgot a required change to avoid that message. Will fix that soon. So no worry you have not lost the taker fee. You can check in the funds/tx screen to see that there is no taker fee tx made. Otherwise let me know.

Atm there is no way beside sending the peer a private notification message in the app (which I could do but I dont want to use that if its not an emergency). Seems the peer has some buggy version or some data corrupted. Those cases are very rare and I never got data to analyze why it happens but most likely that we broke something at an update (happens rarely but happens ;-)).

**Comment by sejktmcsdlmfhsc** [comment]
Thank you so much for the quick response, @ManfredKarrer !
I am glad to hear the fees did not get lost and it seems to be an edge case - hopefully I will not hit it again.. :slightly_smiling_face: 
Is there a way to remove the entry from the open trades?

P.S. btw, since you mentioned buggy or maybe outdated clients, today I came across some offer, that I could not take as the seller is running the offer on a pre0.9 bisq version. 
is there another way other than the forum to inform them that there are people interested in their offer and so incentivise them to update?

Thank you!

**Comment by ManfredKarrer** [comment]
You can block the onion address. Click the avantar icon, there you see his onion and then add it to the ignored peers list in settings.

Re not updated users:
Not really beside those private notifications which I don't want to over-use.
They get all update messages so if they ignore all we cannot do much.

**Comment by ripcurlx** [comment]
Closing as complete.
