### ISSUE TITLE
Invalidate proposals with invalid data

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2545]
As @devinbileck has tested out in the current proposals he managed to post a proposal with a too high amount (100 000 BSQ is limit). I assume he did that by editing the code as the UI does not permit that. But of course we need to verify that on the domain layer as well and invalidate such proposals so that they are not displayed and would not become valid if accepted in voting. I assume all those checks for the proposal values are atm not dont on the domain layer and also incomplete.

<img width="987" alt="Screen Shot 2019-03-16 at 15 33 19" src="https://user-images.githubusercontent.com/1449498/54481294-ed4da780-4800-11e9-8c29-f7efc18c4f27.png">

**Comment by ManfredKarrer** [comment]
@ben-kaufman If you have time for that would be relatively high prio.

**Comment by devinbileck** [comment]
@ManfredKarrer that was a valid proposal for changing the max BSQ amount for compensation requests. And within the acceptable max increase limit (x2).
I think you confused it with a compensation request?

**Comment by ManfredKarrer** [comment]
Ah yes, I confused it... Then all is OK. 
But can be still that validation is missing on the domain side....

**Comment by ghost** [comment]
Concerning this point of users trading with Bisq home compiled source code (and possibly modified with bad intentions).
Is there atm any signature/fingerprint/checksum (or other technical mean) produced by the appli and showed to the peer nodes in order to prove that the node uses the official and non modified source code ?

**Comment by ManfredKarrer** [comment]
@HarryMacfinned Any modification need to be detected by the consensus code. So anything the user creates is only valid if your node considers it valid. Atm probl. some such checks are missing but of course we cannot rely on validation done at the UI level...
