### ISSUE TITLE
Screen not updating

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2548]
The old issue caused from GUIUtil.setFitToRowsForTableView is still happening ;-(.

Maybe we should use another concept to manage available space with tables...

**Comment by ManfredKarrer** [comment]
It is harder to reproduce now, but If you remove the call from activate it gets easy to reproduce again. I don't know what really causes the issue but seems a bug inside the render logic of JavaFX. Maybe some update on the container is required, but tried also root.layout() and did not help.

**Comment by ripcurlx** [comment]
I'll have a look if we find a better workaround.

**Comment by ripcurlx** [comment]
Superseded by #2601
