### ISSUE TITLE
Unhandled unrecoverable program state following failed handshake with seed nodes

### ISSUE THREAD

**Issue by agb19** [bisq-network/bisq#2549]
Related to: #2547, possibly #2474, #2327 

This is a slightly edited re-post of the issue reported at:
https://bisq.community/t/issue-bisq-startup-problem-on-slow-networks-3-4-problem/7233/3

**Details:**
After a network congestion/degradation during startup (issue #2547), Bisq remains in a dead-end state that doesn't recover even after the network performance is restored. The only way to recover is restarting the program. 
This condition is not properly handled nor reported in the UI, causing confusion to unaware users. 

**Steps to reproduce**
- same as issue #2547, start with a working installation
- close application
- degrade network: `sudo tc qdisc add dev eth0 root tbf rate 100kbit burst 1540 latency 50ms`
- start application
- wait 3 hours, per issue #2547 there should be no progress past step 3/4
- remove network degradation: `sudo tc qdisc del ...`
- wait indefinitely, there will still be no progress past step 3/4, even 12 hours later

**Expected result**
The program should attempt to recover seamlessly from the degraded state when the network conditions allow it.

**Alternative expected result**
The program should detect the dead-end state and report it in the UI along with some information about its probable cause, then exit or restart in order to attempt to recover from this state. 

**Actual result**
The program keeps running, displays a progress indicator and shows the offers, trades, wallet contents, exchange rates etc, creating a false appearance of almost-operational and a false expectation of further progress, when in reality it is in an unrecoverable no-op state.

**Comment by agb19** [comment]
After further testing on this issue, I have some additional information. 
Completely removing network connectivity for 30 seconds, effectively bringing the application into "all connections lost" state, appears to reset this condition and re-enable the application to attempt seed node handshakes, which, subject to improved network conditions, may lead to a successful startup. 

Tested multiple times on a laptop computer using the hardware wifi switch. 

(Bisq versions: 0.9.5 - 0.9.8)

**Comment by ripcurlx** [comment]
Related to: #3797 #1023 #3763 #3347
