### ISSUE TITLE
The price of a single altcoin can not be expressed by BTC price

### ISSUE THREAD

**Issue by lichuan** [bisq-network/bisq#2551]
Because the decimal number of BTC price is 8, it's too few, some altcoin unit price can not be expressed by BTC price, so the decimal number of BTC price should be increased.

I suggest the number of decimal place should be 10 or more.

**Comment by ManfredKarrer** [comment]
Which altcoin do you refer to?
An altcoin which has less value than 0.00000001 BTC (about 0,00004 USD) has either no value or made a big mistake with the amount they issued.... I doubt other software will change its code to support such coins...

**Comment by lichuan** [comment]
No, many exchange support 10 decimal of BTC price, so Bisq should also support

**Comment by lichuan** [comment]
Like graviex exchange supports 9 decimal, and crex24 support 11 decimal, you can refer to this link:
https://crex24.com/zh/exchange/MIC3-BTC

**Comment by lichuan** [comment]
@ManfredKarrer 
You shouldn't assume the price and circulation of altcoins because they come from different scenarios.

**Comment by lichuan** [comment]
You can limit the minimum amount of money in withdrawal and deposit, but in the trading process, you should support the pricing of any altcoin currency as much as possible.
