### ISSUE TITLE
Block request via RPC from Bitcoin Core is slow

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2558]
Requesting the block on mainnet with about 2000 txs takes about 300 ms.
Maybe we should look into alternatives if there are options to speed that up as that is the bottleneck for a full BSQ node sync.
No high prio as most people will not run full node anyway...

**Comment by ManfredKarrer** [comment]
@KanoczTomas Do you know if ZeroMQ is supporting requests for a full block? I doubt as its only publishing data right not supporting request/response model.

**Comment by KanoczTomas** [comment]
@ManfredKarrer correct, zeroMQ is not suitable for this. The way to go is to imho talk to bitcoind via the p2p protocol and fetch the block through that connection directly. The p2p thread has priority compared to rpc.

**Comment by ManfredKarrer** [comment]
I will close that for now as there is no plan to work on that soon. The performance is not a big problem and only affects full nodes.
