### ISSUE TITLE
btc balance in wallet UI not updating after .local/share wallet restore or seed restore even after spv reset

### ISSUE THREAD

**Issue by sejktmcsdlmfhsc** [bisq-network/bisq#2570]
maybe related: #1288 or #2516 or #2491

Dear Bisq-team,

today I restarted my machine for an update: tails 3.13
Before that, I properly shut down bisq 0.9.5 application. 
During the session before the update (a few days long) I opened and closed 
bisq a few times and made/initiated trades - everything worked as expected. 
Due to the live-linux nature of tails linux, the wallet is symlinked from 
persistent drive to ~/.local/share/Bisq.

After starting bisq, post tails update, to my surprise bisq created a new wallet.
This was of course not so pleasant, as I still have an almost finished trade open.
Since I had a backup from ~6 days ago, I restored that into the cleared wallet directory.
Now the trade history was of course older, but much worse the BTC balance was wrong.
So I hit the button to delete spv to have the wallet scan for its transactions again.
I tried this two times with multiple bisq restarts in between, but the balance is still wrong.
In the log however, it arrives at the correct balance after resync, but never shows it in the UI. 
:confused: 

After that I restarted with a clean datadir and restored from seed.
Now I get the correct balance shown, but of course everything else is gone.

So my two questions would be:
* Is it safe to withdraw from from the seed-restored wallet to an address of the backup-wallet?
* Is there a way the arbitrator can release the btc I am expecting 
from an open - already paid - trade once it has settled? (it is still a few days to go)
As I don't see the trade anymore I cannot hit the "transfer to bisq wallet" button 
from the trade dialog. :thinking: 

Your help would be very much appreciated!!
 
Best,
Sej

**Comment by sejktmcsdlmfhsc** [comment]
I finally realized, that I had entered the symlinking in my startup script, but it was probably not yet active in the session before the system update. So by restarting I effectively erased the data.. :man_facepalming: 
Good thing to have backups.. :slightly_smiling_face: 
Unfortunately Frankenstein-combining the two wallets: balance-non-updating-backup-wallet and seed-restored-wallet into one: bisq_BTC.wallet and bisq.spvchain from seed and the rest from the backup wallet did not work out: it also shows the wrong balance.

**Comment by ManfredKarrer** [comment]
If you copy over a old backup wallet the wallet db file (db/AddressEntryList) is not in sync with that. Also you cannot complete the trade and would probably not get in contact with the arbitrator.
Post the trade ID and arbitrator onion address if you have those.
Do you have access to the last version before the OS update? If not the trade will likely end up in dispute and if the arbitrator cannot get in touch with you you might lose the security deposit.

Your can restore the wallet from seeds, then the AddressEntryList gets updated correctly. But the problem with the not accessible trade remains. 
So best would be if you manage to get the data directory from the latest working version before you updated.

**Comment by sejktmcsdlmfhsc** [comment]
@ManfredKarrer  Thank you so much for the quick and informative response!
The trade id is: 0837517
and the arbitrator onion is: urlujknbe7itmiwl.onion
As it was in trade step "3: wait until paymant arrives" and the 
message of started payment arrived successfully at peer, 
I assume the bought BTC would automatically arrive in my 
BTC wallet but not the security deposit?
If I could only lose the security deposit, that would be already good news! :slightly_smiling_face: 
Is there a way to restore a trade from the contract json so it becomes visible in bisq again?
Which kind of database is AddressEntryList?

Unfortunately I do not have access to the state before the update, as the symlink was not active 
yet and tails as a live system drops all the data written to the overlay filesystem. 
Clearly an error on my part I only checked for the symlink entry in my startup script, but not to 
double check if it was active already. :slightly_frowning_face: 

So if I understand it correctly, the backup-wallet does not know about the new addresses where BTC arrived in the last 6 days and thus not showing it in the balance? To me that is understandable, although I thought new addresses are derived from the pivate key? (when I have two wallets of a bitcoin based coin running on multiple machines, the new received balance would show up in all of them, not only on the node where I created that address with its label)
I am puzzeled why it shows the correct balance after spv-resync from the backup-wallet just in the console/log and even in the funds transaction, but not in the balance of the GUI - is there a way to refresh that? :confused: :thinking:

Maybe it is also time for me to start a new wallet (now that I have access to all the single components except for the history after the wallet-backup) - I assume if I export / import the payment accounts they would keep their age?
Thank you!!

**Comment by sejktmcsdlmfhsc** [comment]
..aha seems like there was a AddressEntryList_wallet_restore_1553293xxxxxx that maybe did not make its way into the db - I think there was an error message after one of the spv resyncs, that it could not write a restore file. I will try to resync spv once more then and post the log part with the error if it shows up again. :slightly_smiling_face:

**Comment by sejktmcsdlmfhsc** [comment]
Ok that seem to have worked. :tada:  :slightly_smiling_face:  
I created a combined wallet now, 
that has the payment accounts from the ex/imported,
shows the correct balance from the seed restore wallet from wallet and AddressEntryList,
and still has the history at least until ~6days ago.
Thank you so much for sharing your insights!

**Comment by ManfredKarrer** [comment]
Ah good to hear. I would still recommend to start over with a new data directory after you have closed all trades/disputes/open offers. See https://bisq.community/t/how-to-switch-to-a-new-data-directory/6753/
