### ISSUE TITLE
fix weupnp in TomP2P or add SBBI Router as an alternative

### ISSUE THREAD

**Issue by remyers** [bisq-network/bisq#258]
related to issue #230 I have opened up an [issue](https://github.com/bitletorg/weupnp/issues/11) with weupnp

If I can solve the issue with my router using the portmapper app then it might help us fix wepnp generally for tomp2p and bitsquare.

Another option is to look into using [SBBIRouter](http://sourceforge.net/projects/upnplibmobile/) in place of wepnp in TomP2P.  We can look at portmapper (java) for how they switch between the two.  Maybe include them both and try one and then the other.

Problem with SBBI is it's not clear if it's still supported.

**Comment by ManfredKarrer** [comment]
Here is another upnp library: https://github.com/offbynull/portmapper

**Comment by ManfredKarrer** [comment]
Windows UPNP problem is sovled.
