### ISSUE TITLE
Show the security deposit in the available offers view

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2586]
Since the buyers security deposit is defined when a maker publishes their offer, it would be nice to see the security deposit for each offer in the available offers view. That way a buyer can see at a glance which offer they want to avoid due to a high security deposit, or a seller which offers provide more of a security deposit.

**Comment by ManfredKarrer** [comment]
It is displayed in the offer details window (click on i icon) but I agree it would be good to have it in the table visibel as well. There is not much space so some kind of graphical indicator might be good.
