### ISSUE TITLE
UI improvements when DAO state in conflict

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2588]
Currently if there is even a single conflict with the DAO state from any peer, it will indicate you need to resync (in the network monitor tab of the DAO section):
![image](https://user-images.githubusercontent.com/603793/54979235-e260e880-4f5f-11e9-8de0-aa936dd6452d.png)

I believe it should only indicate a resync is required if a majority of peers are in conflict. Otherwise only show a warning without the resync message/button.

In addition, we should add better indication to the user of a DAO conflict (e.g. error icon in status bar or over the DAO button at the top). Currently it is not obvious and only visible in the network monitor tab of the DAO section.

Also, I assume we should prevent any actions that require publishing a transaction containing BSQ when in conflict (i.e. sending/voting/proposing/bonding/etc), otherwise the BSQ could be rendered invalid?

**Comment by ManfredKarrer** [comment]
Agree.

**Comment by ripcurlx** [comment]
Already fixed.
