### ISSUE TITLE
Do not use port 5000

### ISSUE THREAD

**Issue by remyers** [bisq-network/bisq#259]
Perhaps related to #258, uPnp uses [TCP port 5000 for incoming connections](https://www.grc.com/port_5000.htm).  Like in the case of Bitcoin, we should pick a port that is not otherwise used.

The uPnP discovery sequence looks pretty simple and using port 5000 should be ok since it's setup externally, but it would be less confusing to pick a different port.

The web site gives a good description of how uPnP works.  It would be worth setting a break point and stepping through the code of GatewayDiscover.discover of weupnp to see if anything obvious happens there.

I also noticed that in [SBBI router the default MX is 3](https://code.google.com/p/rugl/source/browse/trunk/fun/Upnp/src/net/sbbi/upnp/Discovery.java) (ie. 3 seconds until response) but in [weupnp they use MX:2 ](https://github.com/bitletorg/weupnp/blob/master/src/main/java/org/bitlet/weupnp/GatewayDiscover.java).

**Comment by ManfredKarrer** [comment]
Ah good catch! I will change the port also to one of a non registered! I will start debuggin gon my win laptop to see where the UPnP fails.

**Comment by ManfredKarrer** [comment]
I changed the defual tprot to 7366 which is unassiged (https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=103).
Lets use ports in that range 7366-7390 for other seed nodes.
I also will use a different now for my testing, so the seednode on port 7366 should run more stable.

**Comment by ManfredKarrer** [comment]
Tested with the changed port on windows, but still failing UPnP
