### ISSUE TITLE
Invalid BSQ transaction

### ISSUE THREAD

**Issue by JohnResh** [bisq-network/bisq#2596]
BUG report:

Version: 0.9.5 / Linux
I got 5000 BSQ tokens, and some test BTC.
https://explorer.bisq.network/testnet/tx.html?tx=02b50817f924c6d8a8258b856d2d9f848d4f3d088186ffb575593f26a1e89ef8

Then I opened one sell offer and one buy offer for BSQ tokens for 500 and 200 BSQ.

Buy 500 BSQ:
Offer ID HsmKdss-5c22574c-339e-4575-8397-0a594f0b349c-095
Maker fee transaction ID 0e0e4a79f7c94e71d252e9c4c33b2f988160bc9384667495f6b2994511d804bb

and

Sell 200 BSQ:
Offer ID CrMyxw-c2b5a2e6-8d9a-4db3-8b80-1768294e80cd-095
Maker fee transaction ID 
8413e0d078f6e266ec1e4119212dba9161951e99217d655f9b7916cf1f4d95d5

Now my BSQ balance shows zero in DAO transactions, and the last (and actually second) transaction is "Invalid BSQ Transaction": 
https://explorer.bisq.network/testnet/tx.html?tx=bf0c744977f8c179a7e41108d234eb8c47dc3ec8006518a66b54d742f4f99be4

Here my initial BSQ funding transaction:
https://explorer.bisq.network/testnet/tx.html?tx=02b50817f924c6d8a8258b856d2d9f848d4f3d088186ffb575593f26a1e89ef8

Let me know if you need more informations.

**Comment by ManfredKarrer** [comment]
Can you go to settings/preferences and scroll down on the left there is s rebuild DAO state button. Click that and check if after the resync its still wrong. If so please send me the dao testnet data directory (manfred@bitsquare.io) so that I can investigate.

**Comment by JohnResh** [comment]
"rebuild DAO state" did not fix the issue.
I will send you the dao testnet data directory per email.

Best

**Comment by ManfredKarrer** [comment]
I could find the issue, was related to some code changes.
