### ISSUE TITLE
"Confirm payment receipt" vs. "Confirm payment received"

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#2599]
I don't know why I never recognized that before, but shouldn't it be in following screen `Confirm payment received` not `Confirm payment receipt`?

<img width="1312" alt="Bildschirmfoto 2019-03-29 um 12 07 05" src="https://user-images.githubusercontent.com/170962/55228822-65619780-521b-11e9-88ac-79f669a64a14.png">

**Comment by ripcurlx** [comment]
@ManfredKarrer Do you know if there is a reason why we use here `Confirm payment receipt` and not `Confirm payment received`?

**Comment by ManfredKarrer** [comment]
No, lets change to "received".
