### ISSUE TITLE
Automatic send "confirm payment received" when trading BSQ

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#2600]
As we do have the wallet management already in the Bisq client anyways, we could speed up the BSQ trading process by sending the BSQ payment received message automatically to the peer.

**Comment by ManfredKarrer** [comment]
Maybe better to invest the effort in an atomic swap trade protocol for BSQ/BTC trades. 

Basic scheme (ignoring fees) for a 1 BTC trade with price 0.0002 BSQ/BTC 
Input 1 (BTC seller): 1 BTC
Input 2 (BTC buyer): 5000 BSQ
Output 1 (BTC buyer): 5000BSQ
Output 2 (BTC seller): 1 BTC

**Comment by ghost** [comment]
@ripcurlx BSQ swap is already implemented, so this issue could be closed.
