### ISSUE TITLE
List Ryoo

### ISSUE THREAD

**Issue by nico1431996** [bisq-network/bisq#2605]
Please fill in the following data to request for a new asset to be listed on Bisq. For more details, be sure to read [the full documentation](https://docs.bisq.network/exchange/howto/list-asset.html) on adding a new asset.

### 1. Asset name
Ryo Original

### 2. Ticker
_Your asset's ticker must not conflict with any national currency tickers (per [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)) or any of the [top 100 cryptocurrency tickers](https://coinmarketcap.com/coins/)._

Ryoo

### 3. Block explorer URL
_Your asset's block explorer must be active and publicly available so that transactions can be verified with a receiver's address...if this isn't possible, [see workarounds here](file:///home/steve/wb/bisq/bisq-docs/build/asciidoc/html5/exchange/howto/list-asset.html#arbitrators-must-be-able-to-look-up-transactions-in-the-asset-block-explorer)._

http://explorer.ryo-original.org

### 4. Additional technical requirements (yes/no)
_Your asset should not have any additional requirements (for example, needing input fields for anything other than an address)._

No

### 5. Initial coin offering (yes/no)
_Bisq will not list your token if it has taken part in an initial coin offering (ICO)_

No

Thanks for your time

Git
https://github.com/ryooriginal

**Comment by ghost** [comment]
Hum, shouldn't be @blabno assigned to this issue ?
And, it is now 2 months that Bisq didn't add new assets. Is there anything which should/could be done to help ?

**Comment by ghost** [comment]
unstale
