### ISSUE TITLE
Message state not updated properly during arbitration

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#2607]
When the arbitrator is offline during opening of a dispute the initial message state will stay "Message saved in receiver's mailbox" forever. Should be "Message arrival confirmed by receiver" after arbitrator is online again.

![Bildschirmfoto 2019-04-01 um 12.18.21.png](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/1c653483-f064-4018-9413-cdb8cf9e443a)

**Comment by beingindot** [comment]
I tried to reproduce in regtest but for me after mediator comes online, alice message state changed to "Message arrival confirmed by receiver". Is there any other specific conditions for this bug?
@ripcurlx 

![Screenshot from 2020-02-19 17-18-05](https://user-images.githubusercontent.com/55691179/74831735-d7633380-533b-11ea-93f0-8abc14857c33.png)

**Comment by ripcurlx** [comment]
> I tried to reproduce in regtest but for me after mediator comes online, alice message state changed to "Message arrival confirmed by receiver". Is there any other specific conditions for this bug?
> @ripcurlx
> 
> ![Screenshot from 2020-02-19 17-18-05](https://user-images.githubusercontent.com/55691179/74831735-d7633380-533b-11ea-93f0-8abc14857c33.png)

@beingindot Sorry - mistake on my side 😬 . I mixed up this issue with a different recent one as I think this one have been resolved already a long time ago.
