### ISSUE TITLE
Issues after netlayer 0.6.5

### ISSUE THREAD

**Issue by freimair** [bisq-network/bisq#2608]
There is something strange going on since the update to netlayer 0.6.5, more specific, it is the tor-binary for linux64 that causes issues.

### Observations so far
- When I run locally (Arch Linux 64) I get:
   ```
   xx@local ...d.tor-binary/tor-binary-linux64/8.0.8 % ls
   60157cbcc40d5b20e6e07b693dc64ba222be217f/  675e7882ce88585c3fdfa323d9c6999125887185/
   xx@local ...d.tor-binary/tor-binary-linux64/8.0.8 % sha256sum    60157cbcc40d5b20e6e07b693dc64ba222be217f/tor-binary-linux64-8.0.8.jar
   6891fcd90029efbdcc9c58b3a3f09ce50febf7038df6c57ac338cc6c040d68e0  60157cbcc40d5b20e6e07b693dc64ba222be217f/tor-binary-linux64-8.0.8.jar
   ```
   build works ok, bisq runs

- When I use my seed node (Ubuntu Linux 64) I get:
   ```
   xx@seednode ...d.tor-binary/tor-binary-linux64/8.0.8 # ls
   4088b8a193aea995588c072c383870f3b6619184/ 675e7882ce88585c3fdfa323d9c6999125887185/
   xx@seednode...d.tor-binary/tor-binary-linux64/8.0.8 # sha256sum 4088b8a193aea995588c072c383870f3b6619184/tor-binary-linux64-8.0.8.jar
   a860c1b29da55008174b2149e113e928514af964e5e3a85f392a373e2564909b  4088b8a193aea995588c072c383870f3b6619184/tor-binary-linux64-8.0.8.jar
   ```
   build works ok, bisq quits with saying that the tor binary is corrupt.

- Jitpack conforms with the hashes of my local build
  - [tor-binary-linux64-8.0.8.jar.sha1](https://jitpack.io/com/github/JesusMcCloud/tor-binary/tor-binary-linux64/8.0.8/tor-binary-linux64-8.0.8.jar.sha1) -> `60157cbcc40d5b20e6e07b693dc64ba222be217f`
  - [tor-binary-linux64-8.0.8.jar](https://jitpack.io/com/github/JesusMcCloud/tor-binary/tor-binary-linux64/8.0.8/tor-binary-linux64-8.0.8.jar) ->
   ```
   xx@local ~/Downloads % sha256sum tor-binary-linux64-8.0.8.jar
   6891fcd90029efbdcc9c58b3a3f09ce50febf7038df6c57ac338cc6c040d68e0  tor-binary-linux64-8.0.8.jar
   ```
   - on my seed node:
   ```
   xx@seednode ~ # wget https://jitpack.io/com/github/JesusMcCloud/tor-binary/tor-binary-linux64/8.0.8/tor-binary-linux64-8.0.8.jar
   [snip]
   xx@seednode ~ # sha256sum tor-binary-linux64-8.0.8.jar
   6891fcd90029efbdcc9c58b3a3f09ce50febf7038df6c57ac338cc6c040d68e0  tor-binary-linux64-8.0.8.jar
   ```

### Solutions
- I just got a build success after doing a
   ```
   xx@seednode ~ # rm -r .gradle/caches/modules-2/files-2.1/com.github.JesusMcCloud.tor-binary/tor-binary-linux64/
   ```
   followed by a
   ```
   ./gradlew clean build -x test -d | grep tor-binary-linux64
   [snip]
   [org.apache.http.impl.execchain.MainClientExec] Executing request GET /com/github/JesusMcCloud/tor-binary/tor-binary-linux64/8.0.8/tor-binary-linux64-8.0.8.jar HTTP/1.1
   [snip]
   ```
   gave me
   ```
   ./gradlew build -x test

   BUILD SUCCESSFUL in 9s
   58 actionable tasks: 3 executed, 55 up-to-date
   ```

### Conclusions so far
- as of now, I believe that the checksum used by gradle is correct
- the [main issue](https://github.com/jitpack/jitpack.io/issues/3572#issuecomment-478532950) with jitpack is still unsolved. Not sure if it has anything to do with this.
- I got it to work on a machine that formerly encountered the issue by clearing the package cache

**Comment by m52go** [comment]
Thanks @freimair. Deleting the `tor-binary-linux64-8.0.8.jar` file from cache did fix the issue for me, for now.

**Comment by ghost** [comment]
@m52go , which OS did you use ?

**Comment by m52go** [comment]
@HarryMacfinned my main system is Ubuntu 18.04 LTS but I also tried on a Windows 10 VM and macOS and got the same error across all of them.

**Comment by freimair** [comment]
the issue seems to be gone as further Bisq versions have been successfully released after this report.
