### ISSUE TITLE
Client becomes stuck synchronizing DAO when generating multiple blocks simultaneously in regtest

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2612]
When generating 3 or more blocks at a time in regtest mode (e.g. `generate 3`) - which is done to quickly advance through the voting phases - the client will become stuck synchronizing the DAO state (as indicated in the bottom status bar). With the following shown in the **BSQ Wallet > Transactions** for example:

> Awaiting blocks... Verified 159 out of 160

Initially I noticed this repeatedly in the log:
```
Apr-01 15:38:09.586 [NetworkNode:SendMessage-to-localhost:3002] INFO  b.n.p2p.network.NetworkNode: onFailure at sendMessage: peersNodeAddress=localhost:3002
	message=GetPeersRequest
	throwable=java.net.ConnectException: Connection refused: connect 
```

Which is to be expected since I only have a single seed node at localhost:2002. So I commented out the `localhost:3002` within [btc_regtest.seednodes](https://github.com/bisq-network/bisq/blob/d9f9baf87abea31a5ea27f95b8441b730f53d8cc/core/src/main/resources/btc_regtest.seednodes#L17) to see if that would help, but I still encounter the issue. So that doesn't appear to be the issue.

Then I noticed the following in the log (not sure if relevant to this issue):
```
Apr-01 15:58:05.266 [JavaFX Application Thread] WARN  b.c.d.g.b.BlindVoteValidator: blindVoteTx is not confirmed. blindVoteTxId=5d13ec6eb0feaf289c8d509a1d3c94ab7717544f4135e58b210b368b01bb2ed7 
Apr-01 15:58:05.300 [JavaFX Application Thread] WARN  b.c.d.g.b.BlindVoteValidator: blindVoteTx is not confirmed. blindVoteTxId=da62bf8ee02fc91db05a02e0466fa0aa4fcef9ebabca5a2956a7537f1074bc4a 
Apr-01 15:58:05.300 [JavaFX Application Thread] WARN  b.c.d.g.b.BlindVoteValidator: blindVoteTx is not confirmed. blindVoteTxId=38409627577c8a283c3723b316b05611870aab08f2f7738b254928d5361ae04e 
Apr-01 15:58:05.301 [JavaFX Application Thread] WARN  b.c.d.g.b.BlindVoteValidator: blindVoteTx is not confirmed. blindVoteTxId=4a5b011a731108b29ce94afb9ae178f8349621254162514c34542a2cc363d561 
```

```
Apr-01 16:28:29.242 [NioClientManager] WARN  o.b.core.AbstractBlockChain: Block does not connect: 74959c3094b48f0bbad6e702ac1f86498d83d63ed677276da2f3c3840f6898b2 prev 2f867d9cd982d6bcdb63e29f4eba20137a4ac35ec3f3e96bb40d035d1e32bf22 
```

Even after waiting a bit and generating a single block, it was still stuck and unable to recover.

Once I restarted the client, it synced successfully.

**Comment by ManfredKarrer** [comment]
I have seen this some times as well. I did not put too much attention on it as it is very unlikely that on mainnet multiple blocks arrive that fast and as a restart resolves the issue.

**Comment by devinbileck** [comment]
Agreed. Just annoying when testing.

**Comment by ManfredKarrer** [comment]
Did it happen often? I could not reproduce it the last days. I created 1000s of blocks and it did not break. But I am aware that there are siuations where it broke...

**Comment by devinbileck** [comment]
Yes it seems to occur every time for me.

**Comment by Giszmo** [comment]
For what it's worth, my client is stuck now with this message indefinitely. As I don't intend to use the DAO it's especially annoying to be locked out and see my listings offline due to some alt-coin syncing.

**Comment by devinbileck** [comment]
Related https://github.com/bisq-network/bisq/issues/2800

**Comment by devinbileck** [comment]
I am no longer encountering this anymore on regtest, even when generating 50 blocks at once. Takes several seconds, but it does not become stuck.
