### ISSUE TITLE
0.9.6 change orders only accepts integer values

### ISSUE THREAD

**Issue by izzytdi** [bisq-network/bisq#2615]
I just tried the new version 0.9.6 and if i try to edit an order from 1 to 2.5% above market price it will round to 3%.  Same if I try 1.3% it rounds down to 1%.

I also have an offer at an odd 1.29% which is now stuck because the update offer button is disabled

All trades were made under 0.9.5 and downgrading back to 0.9.5 returns them to normal

**Comment by mpolavieja** [comment]
Same issue here.  Although I haven´t tried to downgrade.

**Comment by ripcurlx** [comment]
We found the problem and are working on a hotfix release (v0.9.7) right now. Sorry about this issue!

**Comment by ripcurlx** [comment]
Released in [v0.9.7](https://github.com/bisq-network/bisq/releases/tag/v0.9.7)

**Comment by mpolavieja** [comment]
I´ve installed 0.9.7 and it is fixed.  Thanks!
