### ISSUE TITLE
Strip the exception type when showing a checkArgument message to the user

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2620]
When a checkArgument fails and raises an exception, it is shown to the user with the exception type (java.lang.IllegalArgumentException). It may be confusing to show that, and instead should just show the message.
![image](https://user-images.githubusercontent.com/603793/55436712-e5586c00-5551-11e9-94ad-1a4268f8b5a0.png)

Related to #2619

**Comment by devinbileck** [comment]
As suggested in https://github.com/bisq-network/bisq/pull/2614#discussion_r271290565, a better implementation would be input validation where a more user friendly and translated error is shown (at text field validation).

**Comment by ManfredKarrer** [comment]
Excpetion class name is not displayed anymore as I use getMessage(). But still would be good to show a translated and more user friendly popup.

**Comment by ManfredKarrer** [comment]
Close as it is covered in https://github.com/bisq-network/bisq/issues/2619
