### ISSUE TITLE
Incorrect wallet balance after compensation request issuance?

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2623]
Here's a brain teaser that I am struggling to explain at the moment. I need to review it tomorrow with a fresh mind, but creating an issue so as not to lose track of it (and maybe get another mind to review it).

I was testing a scenario where I had submitted a compensation request for 100 BSQ and had just enough BSQ to cover the fees, but not enough to vote (where I found #2622).

Here is the sequence of events (starting from a balance of 0 BSQ):
- Receive 10 BSQ
- Submit compensation request for 100 BSQ, minus 2 BSQ for fee
[balance of 8 BSQ]
- Send remaining 8 BSQ
[balance of 0 BSQ]
- Compensation request approved, BSQ issued
[at this point I would expect to have a balance of 98 BSQ, but the wallet balance indicates 100]

Adding up the amounts shown below (10+98-8) gives us 100. But calculating it based on the sequence of events (10-2-8+98), gives us 98.

![image](https://user-images.githubusercontent.com/603793/55461649-cf769580-55a9-11e9-996b-54198a52fed0.png)

**Comment by sqrrm** [comment]
When making the compensation request you burn 2 BSQ as fee and issue 100 BSQ. I think the transaction list aggregates that to 98 BSQ. The sum makes sense, you have 10, burn 2, send 8 elsewhere, issue 100, ie 10 - 2 - 8 + 100 = 100.

**Comment by ManfredKarrer** [comment]
Yes agree to @sqrrm. Seems all correct to me.
BSQ added: 10 + 100 = 110
BSQ removed: 2 + 8 = 10
Sum: 100

**Comment by devinbileck** [comment]
Ah, that makes sense. Thanks!
