### ISSUE TITLE
Timeout error when taking an offer

### ISSUE THREAD

**Issue by mpolavieja** [bisq-network/bisq#2624]
I am trying to take a HalCash sell offer but I am getting a timeout error.  I am using Windows 7 Professional 64 bits and Bisq version is 0.9.7. Logs attached:
[Bisq_log_20190403.txt](https://github.com/bisq-network/bisq/files/3038137/Bisq_log_20190403.txt)

**Comment by ripcurlx** [comment]
Did you try to take the offer again? Is your client well connected? There might be cases that messages are dropped within the network.

**Comment by mpolavieja** [comment]
I believe that my client was well connected.  Unfortunately, the offer is not available anymore
