### ISSUE TITLE
Cannot create new Siacoin account

### ISSUE THREAD

**Issue by pmknutsen** [bisq-network/bisq#2625]
In Account->Altcoin Accounts->Create new account it is not possible to create a Siacoin account.

In the textfield "Altcoin" typing "Sia" brings up "SiaPrimeCoin (SCP)" and "Siafund (SF)" but "Siacoin (SC)" is missing.

"Siacoin (SC)" is a supported altcoin.

**Comment by ghost** [comment]
@pmknutsen 
Which Bisq version do you use ?
In my v0.9.7 Siacoin doesn't appear anymore, which would mean that it is no more supported.
Generally this happens because of insufficient trading -> https://docs.bisq.network/exchange/howto/list-asset.html

**Comment by pmknutsen** [comment]
v0.9.7

Siacoin is available in Settings->Preferences->Currencies in market price feed lists
So, assumed it was still a supported alt. I do see its been pulled from https://bisq.network/markets/ and Market->Offer Book but perhaps thats just because there are zero orders on the book?

**Comment by ghost** [comment]
If you have already traded an altcoin in the past, then you can still see it in the appli, even if it has been removed (it's a small annoyance which is not well managed atm).

I see however in Market/spread that SpaceCash has the <code>SC</code> ticker ... which was/is Siacoin ticker.
SpaceCash was added in january 2019, and should have had <code>SPACE</code> ticker.
So, maybe there was an improper handling here.
We'll investigate a bit (ping @ripcurlx )

- https://github.com/bisq-network/bisq/search?q=spacecash&unscoped_q=spacecash
- https://github.com/bisq-network/proposals/issues/35 mentions in sept 2018 Siacoin (SC) having 176 trades at this time.
- There is no more a Siacoin.java file in the altcoins repo.

**Comment by ripcurlx** [comment]
@HarryMacfinned There was indeed a wrong name in the removed crypto map. I just fixed it in https://github.com/bisq-network/bisq/pull/2635.
@pmknutsen Siacoin was removed because of lack of trading volume.

**Comment by stevefunk** [comment]
@ripcurlx @HarryMacfinned Hey guys, just curious - do you have data on when Siacoin volume fell? According to that Sept 2018 data above, it looks like Siacoin had the fourth most total trades for all cryptos (not sure what the date range was) - but of course that doesn't talk volume at all.

**Comment by ghost** [comment]
@sia-steve 
I was also perplexed with that, but I have no idea where to find such old data.
2 sure points however :
- SC was traded since 2016 ( https://bisq.community/t/the-right-knack-o-dancing/708 ), so 176 trades in 2 years, that's nice, but no so much for 2 years
- in the last 6 months, apart this thread, there is 0 messages in the Bisq community (forum + github) asking about Siacoin on Bisq. So, sorry, but the interest seems indeed super low.

Anyway, in some weeks, the Bisq DAO should be here, and the willing traders should be able to list by themselves the altcoins they want.

**Comment by stevefunk** [comment]
@HarryMacfinned I'm still confused as to why and when Siacoin was removed, but I appreciate that info you provided.
