### ISSUE TITLE
Add next/previous buttons to proposal details popup

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2628]
During the blind vote phase when you click on a proposal that you are voting on, it opens a popup showing all details about the proposal and allows you to vote on it.
![image](https://user-images.githubusercontent.com/603793/55508429-be13a480-560e-11e9-87f9-894ebbe0ea1e.png)

When you vote on the proposal, it closes the popup and you have to click on the next proposal to bring up its details.

It would be useful to add next/previous buttons to this popup to quickly cycle through and vote on the proposals, and show a count of the proposals (e.g. x of y).

**Comment by ManfredKarrer** [comment]
Good idea!
