### ISSUE TITLE
DAO announcement popup

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2632]
We should have a nice DAO announcement popup to give all our users about an overview about the DAO.
@m52go Could you provide some text?
@pedromvpg Could you help with some design?

**Comment by ripcurlx** [comment]
@m52go @pedromvpg It would be great if we have the final text and design beginning of next week so there is enough time for implementation if the design gets very sophisticated ;-)

It shouldn't be lots of text, but spark enough interest and awareness for everyone who is installing Bisq v1.0.0.

**Comment by m52go** [comment]
Here's an idea, maybe something we can use as a starting point.

Please ignore the design...it's quick and rough and not very good, and I only did it to help communicate the context of my suggested text.

Other notes:
- big grey block in the middle is for a picture. i'm picturing something aggressive but endearing like a honey badger. something like [this](https://i.ytimg.com/vi/x9Jr9JKpsX8/maxresdefault.jpg), but cartoonized/animated and bisq-ified with its design would be great, i think (if possible)
- "90% discount" link can lead to a short user guide for traders
- the birthday link on the bottom-left can lead to a birthday-themed blog post i will publish next week

![v10-draft-1](https://user-images.githubusercontent.com/735155/55642294-162ce100-579e-11e9-920c-788cc3f1ea03.png)

<details>
  <summary>expand for text in graphic above</summary>
Bisq v1.0
The complete vision, realized

Bisq's trading network was already decentralized.
With the Bisq DAO, Bisq's _leadership_ is now decentralized too.
Making Bisq exceptionally resistant to censorship.

<picture>

Learn more in this video series or this written doc.
What's in it for you? A 90% discount on trade fees.

Bisq turns 3 on 19 April 2019!
</details>

**Comment by ManfredKarrer** [comment]
Sounds good to me!

**Comment by pedromvpg** [comment]
Proposed design fo the DAO popup.

The illustration in the center would be an animated gif looping through the action described in the active tab.

Thoughts? The goal is to convey small chunks of information at a time and supporting the information with a visual queue that will prompt users to test the features.

We can then re-appropriate the work done on coding this for a more robust on-boarding in the future.


![01 01 DAO Popup 1 1](https://user-images.githubusercontent.com/807505/55685852-bc0c5700-5928-11e9-8658-17827e22f2b6.png)
![01 01 DAO Popup 1 2](https://user-images.githubusercontent.com/807505/55685853-bc0c5700-5928-11e9-8f5a-99c6a5e143b4.png)
![01 01 DAO Popup 1 3](https://user-images.githubusercontent.com/807505/55685854-bc0c5700-5928-11e9-8eb0-751bcde8c5a6.png)

**Comment by m52go** [comment]
I like this a lot. Text can be improved slightly, will send suggestions soon, but design is on-point in my opinion. Would be nice if we could squeeze something in for the 3-year anniversary, given the timing.

**Comment by pedromvpg** [comment]
Agreed about the text. Just consider it placeholder for now.

The 3 year messaging I think we should leave out just because it feels like a total parallel subject and it distracts from the main message. I think it belongs more in a place like the blog instead of a "New Features" pop-up.

**Comment by ManfredKarrer** [comment]
@pedromvpg Do you consider screenshots inside or reduced graphical representation as in the design? Would be arrowsleft/right be good to quickly skip to other slide?
Agree to keep out birthday. Less is more.
Maybe below menue items could be:
- Governance
- Trade
- Cheaper fees

**Comment by pedromvpg** [comment]
yes maybe a screenshoot is better.


![Screen Shot 2019-04-07 at 12 12 21 PM](https://user-images.githubusercontent.com/807505/55686377-76528d00-592e-11e9-9314-756ee7ddd23f.png)

**Comment by ManfredKarrer** [comment]
Yes, less work also ;-) and looks more real....

**Comment by m52go** [comment]
I wonder...do we really need the 'trade' tab? Governance and trading fees covers it, no?

**Comment by ripcurlx** [comment]
> I wonder...do we really need the 'trade' tab? Governance and trading fees covers it, no?

I think it might be a good idea to keep it, so the traders don't wonder how to get BSQ in the first place.

@pedromvpg I like the design!
Regarding screenshots and illustration: If we want to have animation in there (gif), than the reduced representation might be better for performance and file size issues. But I guess for a desktop client a couple of MBs more ore less aren't such a big deal. In that case we could have a look if MP4 would result in a smaller file size. 

I guess the content of the popup should behave like a carousel, right?

**Comment by ripcurlx** [comment]
I'll prepare the rough layout of the popup to see if I can reuse the tab components to create this carousel.

**Comment by ripcurlx** [comment]
Do we want to link to different pages depending which slide (governance, trade, cheaper fees) is selected or shall I always link to: https://bisq.network/dao/

**Comment by m52go** [comment]
@ripcurlx I think the landing page is fine.
