### ISSUE TITLE
DAO/Browse Open Proposals : "Input is not a valid number"

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#2633]
2019/04/03 ~17:56CET
(with BTC_DAO_REGTEST)
I did just get 100000 BSQ from Manfred (thanks).
In the DAO/Browse Open Proposal tab, I voted on a proposal, accepted, with 50000 BSQ.
Now, I try to vote for another proposal, but my max available BSQ for voting is 49996 BSQ, while the field has already 50000 BSQ written inside, with the red mention "Input is not a valid number"
... and I'm unable to modify that.
I'm certainly missing something and I apologize. But I prefer mention it.

log file ~17:56
<pre>
avr.-03 17:09:06.718 [main] INFO  b.c.s.CoreSetup: 
Log files under: /home/user1/bisq/dataDir-btcdaoregtest/Bisq/bisq 
avr.-03 17:09:06.750 [main] INFO  b.c.u.Utilities: System info: os.name=Linux; os.version=4.9.0-8-amd64; os.arch=amd64; sun.arch.data.model=64; JRE=10.0.2+13 (Oracle Corporation); JVM=10.0.2+13 (Java HotSpot(TM) 64-Bit Server VM) 
avr.-03 17:09:06.938 [main] INFO  b.c.app.Version: Version{VERSION=0.9.7, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=1, BASE_CURRENCY_NETWORK=5, getP2PNetworkId()=15} 
avr.-03 17:09:06.939 [main] INFO  b.c.s.CoreSetup: Path to Bisq jar file: /opt/Bisq/app/desktop-0.9.7-all.jar 
...
Got BTC
avr.-03 17:40:17.171 [NioClientManager] INFO  o.b.w.Wallet: Estimated balance is now: 1.00 BTC 
avr.-03 17:40:17.172 [NioClientManager] INFO  o.b.w.WalletFiles: Saving wallet; last seen block is height 1198, date 2019-04-03T15:35:23Z, hash 4a82bb55bd3d29b019a1d4b6ffb139983d1c1ffb48e9b0f243dd3a6e635ac0b4 
avr.-03 17:40:17.226 [NioClientManager] INFO  o.b.w.WalletFiles: Save completed in 54.36 ms 
avr.-03 17:41:02.202 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 61.014 sec. after last request 
avr.-03 17:41:02.741 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4477.68, timestampSec=1554306169735, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.539 sec. 
avr.-03 17:42:06.205 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 64.003 sec. after last request 
avr.-03 17:42:08.619 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4478.26, timestampSec=1554306259911, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 2.414 sec. 
avr.-03 17:42:52.789 [JavaFX Application Thread] INFO  o.b.w.WalletFiles: Saving wallet; last seen block is height 1198, date 2019-04-03T15:35:23Z, hash 4a82bb55bd3d29b019a1d4b6ffb139983d1c1ffb48e9b0f243dd3a6e635ac0b4 
avr.-03 17:42:52.821 [JavaFX Application Thread] INFO  o.b.w.WalletFiles: Save completed in 32.41 ms 
avr.-03 17:43:08.218 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 62.013 sec. after last request 
avr.-03 17:43:08.835 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4477.43, timestampSec=1554306349732, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.616 sec. 
avr.-03 17:44:09.225 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 61.006 sec. after last request 
avr.-03 17:44:09.818 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4477.43, timestampSec=1554306349732, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.593 sec. 
avr.-03 17:44:51.567 [JavaFX Application Thread] INFO  b.c.p.f.FeeService: BTC tx fee: txFeePerByte=96 
avr.-03 17:45:11.233 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 62.008 sec. after last request 
avr.-03 17:45:11.928 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4477.16, timestampSec=1554306439899, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.695 sec. 
avr.-03 17:45:23.560 [NioClientManager] INFO  o.b.w.Wallet: Received tx for 1.00 BTC: 15d8a498f32dd429be70e4a78fd7855523b638c4667b65ab7001d15ed1ee3358 [1] in block 2ca492f5ce413508e2b9b96de348df8d0fc04bd120e393260c76f155e0f150a4 
avr.-03 17:45:23.561 [NioClientManager] INFO  o.b.w.Wallet:   <-pending 
avr.-03 17:45:23.561 [NioClientManager] INFO  o.b.w.Wallet:   tx 15d8a498f32dd429be70e4a78fd7855523b638c4667b65ab7001d15ed1ee3358 ->unspent 
avr.-03 17:45:23.561 [NioClientManager] INFO  o.b.w.Wallet: Balance is now: 1.00 BTC 
avr.-03 17:45:23.562 [NioClientManager] INFO  o.b.w.Wallet: Received tx for 0.10 BTC: a6e9917a0ce8ffc1729963dc529212cfcd3201a89abc0fa08b1864e089cc4d3f [0] in block 2ca492f5ce413508e2b9b96de348df8d0fc04bd120e393260c76f155e0f150a4 
avr.-03 17:45:23.562 [NioClientManager] INFO  o.b.w.Wallet:   <-pending 
avr.-03 17:45:23.563 [NioClientManager] INFO  o.b.w.Wallet:   tx a6e9917a0ce8ffc1729963dc529212cfcd3201a89abc0fa08b1864e089cc4d3f ->unspent 
avr.-03 17:45:23.577 [NioClientManager] INFO  o.b.w.Wallet: Balance is now: 0.00 BTC 
avr.-03 17:45:23.580 [NioClientManager] INFO  o.b.w.WalletFiles: Saving wallet; last seen block is height 1199, date 2019-04-03T15:45:23Z, hash 2ca492f5ce413508e2b9b96de348df8d0fc04bd120e393260c76f155e0f150a4 
avr.-03 17:45:23.631 [NioClientManager] INFO  o.b.w.WalletFiles: Save completed in 51.00 ms 
avr.-03 17:45:23.632 [NioClientManager] INFO  o.b.w.WalletFiles: Saving wallet; last seen block is height 1199, date 2019-04-03T15:45:23Z, hash 2ca492f5ce413508e2b9b96de348df8d0fc04bd120e393260c76f155e0f150a4 
avr.-03 17:45:23.673 [NioClientManager] INFO  o.b.w.WalletFiles: Save completed in 41.77 ms 
avr.-03 17:45:23.961 [JavaFX Application Thread] INFO  b.c.d.n.l.n.LiteNodeNetworkService: We received blocks from peer Optional[gtif46mfxirv533z.onion:8005] 
avr.-03 17:45:23.961 [JavaFX Application Thread] INFO  b.c.d.n.l.LiteNode: onNewBlockReceived: block at height 1199, hash=2ca492f5ce413508e2b9b96de348df8d0fc04bd120e393260c76f155e0f150a4 
avr.-03 17:45:23.962 [JavaFX Application Thread] INFO  b.c.d.s.DaoStateService: New Block added at blockHeight 1199 
avr.-03 17:45:23.962 [JavaFX Application Thread] INFO  b.c.d.s.DaoStateService: Parse block completed: Block height 1199, 1 BSQ transactions. 
avr.-03 17:45:24.836 [JavaFX Application Thread] INFO  b.c.d.n.l.n.LiteNodeNetworkService: We received blocks from peer Optional[2bnvhfkdrnx5hrlv.onion:8005] 
avr.-03 17:45:24.837 [JavaFX Application Thread] INFO  b.c.d.n.l.LiteNode: onNewBlockReceived: block at height 1199, hash=2ca492f5ce413508e2b9b96de348df8d0fc04bd120e393260c76f155e0f150a4 
avr.-03 17:45:26.388 [JavaFX Application Thread] INFO  b.c.d.n.l.n.LiteNodeNetworkService: We received blocks from peer Optional[b3jnw7fyph2jsu6n.onion:8005] 
avr.-03 17:45:26.388 [JavaFX Application Thread] INFO  b.c.d.n.l.LiteNode: onNewBlockReceived: block at height 1199, hash=2ca492f5ce413508e2b9b96de348df8d0fc04bd120e393260c76f155e0f150a4 
avr.-03 17:45:28.562 [Wallet autosave thread] INFO  o.b.w.WalletFiles: Background saving wallet; last seen block is height 1199, date 2019-04-03T15:45:23Z, hash 2ca492f5ce413508e2b9b96de348df8d0fc04bd120e393260c76f155e0f150a4 
avr.-03 17:45:28.577 [Wallet autosave thread] INFO  o.b.w.WalletFiles: Background saving wallet; last seen block is height 1199, date 2019-04-03T15:45:23Z, hash 2ca492f5ce413508e2b9b96de348df8d0fc04bd120e393260c76f155e0f150a4 
avr.-03 17:45:28.611 [Wallet autosave thread] INFO  o.b.w.WalletFiles: Save completed in 48.77 ms 
avr.-03 17:45:28.633 [Wallet autosave thread] INFO  o.b.w.WalletFiles: Save completed in 55.19 ms 
avr.-03 17:45:29.678 [JavaFX Application Thread] INFO  b.c.d.m.n.StateNetworkService: We received a NewDaoStateHashMessage from peer Optional[xpkxxewd2gsiwfyh.onion:9999] with stateHash=StateHash{
     height=1199,
     hash=c06d7aab553d631a01d10442cbed0ed027909366,
     prevHash=7e394f8edb42e28f6afad60a596881a9e3c61ac8
}  
avr.-03 17:45:32.168 [JavaFX Application Thread] INFO  b.c.d.m.n.StateNetworkService: We received a NewDaoStateHashMessage from peer Optional[gtif46mfxirv533z.onion:8005] with stateHash=StateHash{
     height=1199,
     hash=c06d7aab553d631a01d10442cbed0ed027909366,
     prevHash=7e394f8edb42e28f6afad60a596881a9e3c61ac8
}  
avr.-03 17:45:35.295 [JavaFX Application Thread] INFO  b.c.d.m.n.StateNetworkService: We received a NewDaoStateHashMessage from peer Optional[igowbh7gexv26qky.onion:9999] with stateHash=StateHash{
     height=1199,
     hash=c06d7aab553d631a01d10442cbed0ed027909366,
     prevHash=7e394f8edb42e28f6afad60a596881a9e3c61ac8
}  
avr.-03 17:45:35.672 [JavaFX Application Thread] INFO  b.c.d.m.n.StateNetworkService: We received a NewDaoStateHashMessage from peer Optional[boq6l2ur2jmubfqh.onion:9999] with stateHash=StateHash{
     height=1199,
     hash=c06d7aab553d631a01d10442cbed0ed027909366,
     prevHash=7e394f8edb42e28f6afad60a596881a9e3c61ac8
}  
avr.-03 17:45:35.785 [JavaFX Application Thread] INFO  b.c.d.m.n.StateNetworkService: We received a NewDaoStateHashMessage from peer Optional[xh65xuidoeiugbne.onion:9999] with stateHash=StateHash{
     height=1199,
     hash=c06d7aab553d631a01d10442cbed0ed027909366,
     prevHash=7e394f8edb42e28f6afad60a596881a9e3c61ac8
}  
avr.-03 17:45:36.905 [JavaFX Application Thread] INFO  b.c.d.m.n.StateNetworkService: We received a NewDaoStateHashMessage from peer Optional[t467j4bfbyqj5tqv.onion:9999] with stateHash=StateHash{
     height=1199,
     hash=c06d7aab553d631a01d10442cbed0ed027909366,
     prevHash=7e394f8edb42e28f6afad60a596881a9e3c61ac8
}  
avr.-03 17:45:38.085 [JavaFX Application Thread] INFO  b.c.d.m.n.StateNetworkService: We received a NewDaoStateHashMessage from peer Optional[b3jnw7fyph2jsu6n.onion:8005] with stateHash=StateHash{
     height=1199,
     hash=c06d7aab553d631a01d10442cbed0ed027909366,
     prevHash=7e394f8edb42e28f6afad60a596881a9e3c61ac8
}  
avr.-03 17:45:38.963 [JavaFX Application Thread] INFO  b.c.d.m.n.StateNetworkService: We received a NewDaoStateHashMessage from peer Optional[2bnvhfkdrnx5hrlv.onion:8005] with stateHash=StateHash{
     height=1199,
     hash=c06d7aab553d631a01d10442cbed0ed027909366,
     prevHash=7e394f8edb42e28f6afad60a596881a9e3c61ac8
}  
avr.-03 17:46:11.245 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 60.012 sec. after last request 
avr.-03 17:46:11.798 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4477.03, timestampSec=1554306529739, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.553 sec. 
avr.-03 17:47:15.258 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 64.013 sec. after last request 
avr.-03 17:47:15.912 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4477.03, timestampSec=1554306529739, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.654 sec. 
avr.-03 17:48:18.269 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 63.011 sec. after last request 
avr.-03 17:48:18.954 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4475.8, timestampSec=1554306619837, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.685 sec. 
avr.-03 17:49:11.767 [JavaFX Application Thread] INFO  b.d.app.BisqApp: System load: Memory (MB): 163 / No. of threads: 50 
avr.-03 17:49:22.272 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 64.003 sec. after last request 
avr.-03 17:49:22.806 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4472.25, timestampSec=1554306709812, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.533 sec. 
avr.-03 17:49:51.507 [JavaFX Application Thread] INFO  b.c.p.f.FeeService: BTC tx fee: txFeePerByte=98 
avr.-03 17:50:22.289 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 60.016 sec. after last request 
avr.-03 17:50:22.942 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4472.25, timestampSec=1554306709812, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.653 sec. 
avr.-03 17:51:24.295 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 62.006 sec. after last request 
avr.-03 17:51:24.879 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4472.95, timestampSec=1554306799750, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.584 sec. 
avr.-03 17:52:24.302 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 60.007 sec. after last request 
avr.-03 17:52:24.916 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4466.94, timestampSec=1554306889930, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.614 sec. 
avr.-03 17:53:28.306 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 64.004 sec. after last request 
avr.-03 17:53:29.604 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4466.94, timestampSec=1554306889930, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 1.297 sec. 
avr.-03 17:54:30.307 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 62.0 sec. after last request 
avr.-03 17:54:30.860 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4464.5, timestampSec=1554306979779, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.553 sec. 
avr.-03 17:54:51.414 [JavaFX Application Thread] INFO  b.c.p.f.FeeService: BTC tx fee: txFeePerByte=96 
avr.-03 17:55:24.072 [JavaFX Application Thread] INFO  b.c.d.n.l.n.LiteNodeNetworkService: We received blocks from peer Optional[gtif46mfxirv533z.onion:8005] 
avr.-03 17:55:24.072 [JavaFX Application Thread] INFO  b.c.d.n.l.LiteNode: onNewBlockReceived: block at height 1200, hash=174c721f4e627c26fc1161f4252367f51de136f05f0bce297a6e150266d25abb 
avr.-03 17:55:24.072 [JavaFX Application Thread] INFO  b.c.d.s.DaoStateService: New Block added at blockHeight 1200 
avr.-03 17:55:24.072 [JavaFX Application Thread] INFO  b.c.d.s.DaoStateService: Parse block completed: Block height 1200, 0 BSQ transactions. 
avr.-03 17:55:24.143 [JavaFX Application Thread] INFO  b.c.d.s.DaoStateSnapshotService: Saved snapshotCandidate with height 1180 to Disc at height 1200 took 14 ms 
avr.-03 17:55:24.146 [JavaFX Application Thread] INFO  b.c.d.s.DaoStateSnapshotService: Cloned new snapshotCandidate at height 1200 took 3 ms 
avr.-03 17:55:24.761 [JavaFX Application Thread] INFO  b.c.d.n.l.n.LiteNodeNetworkService: We received blocks from peer Optional[2bnvhfkdrnx5hrlv.onion:8005] 
avr.-03 17:55:24.762 [JavaFX Application Thread] INFO  b.c.d.n.l.LiteNode: onNewBlockReceived: block at height 1200, hash=174c721f4e627c26fc1161f4252367f51de136f05f0bce297a6e150266d25abb 
avr.-03 17:55:24.872 [JavaFX Application Thread] INFO  b.c.d.n.l.n.LiteNodeNetworkService: We received blocks from peer Optional[b3jnw7fyph2jsu6n.onion:8005] 
avr.-03 17:55:24.873 [JavaFX Application Thread] INFO  b.c.d.n.l.LiteNode: onNewBlockReceived: block at height 1200, hash=174c721f4e627c26fc1161f4252367f51de136f05f0bce297a6e150266d25abb 
avr.-03 17:55:28.545 [Wallet autosave thread] INFO  o.b.w.WalletFiles: Background saving wallet; last seen block is height 1200, date 2019-04-03T15:55:23Z, hash 174c721f4e627c26fc1161f4252367f51de136f05f0bce297a6e150266d25abb 
avr.-03 17:55:28.545 [Wallet autosave thread] INFO  o.b.w.WalletFiles: Background saving wallet; last seen block is height 1200, date 2019-04-03T15:55:23Z, hash 174c721f4e627c26fc1161f4252367f51de136f05f0bce297a6e150266d25abb 
avr.-03 17:55:28.602 [Wallet autosave thread] INFO  o.b.w.WalletFiles: Save completed in 57.26 ms 
avr.-03 17:55:28.619 [Wallet autosave thread] INFO  o.b.w.WalletFiles: Save completed in 73.86 ms 
avr.-03 17:55:32.312 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 62.005 sec. after last request 
avr.-03 17:55:32.669 [JavaFX Application Thread] INFO  b.c.d.m.n.StateNetworkService: We received a NewDaoStateHashMessage from peer Optional[igowbh7gexv26qky.onion:9999] with stateHash=StateHash{
     height=1200,
     hash=1f7a719ba8ead4ae5ca9cdd4b40bfdf164d735b8,
     prevHash=c06d7aab553d631a01d10442cbed0ed027909366
}  
avr.-03 17:55:32.854 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4466.19, timestampSec=1554307070016, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.542 sec. 
avr.-03 17:55:35.588 [JavaFX Application Thread] INFO  b.c.d.m.n.StateNetworkService: We received a NewDaoStateHashMessage from peer Optional[t467j4bfbyqj5tqv.onion:9999] with stateHash=StateHash{
     height=1200,
     hash=1f7a719ba8ead4ae5ca9cdd4b40bfdf164d735b8,
     prevHash=c06d7aab553d631a01d10442cbed0ed027909366
}  
avr.-03 17:55:35.854 [JavaFX Application Thread] INFO  b.c.d.m.n.StateNetworkService: We received a NewDaoStateHashMessage from peer Optional[gtif46mfxirv533z.onion:8005] with stateHash=StateHash{
     height=1200,
     hash=1f7a719ba8ead4ae5ca9cdd4b40bfdf164d735b8,
     prevHash=c06d7aab553d631a01d10442cbed0ed027909366
}  
avr.-03 17:55:36.494 [JavaFX Application Thread] INFO  b.c.d.m.n.StateNetworkService: We received a NewDaoStateHashMessage from peer Optional[xpkxxewd2gsiwfyh.onion:9999] with stateHash=StateHash{
     height=1200,
     hash=1f7a719ba8ead4ae5ca9cdd4b40bfdf164d735b8,
     prevHash=c06d7aab553d631a01d10442cbed0ed027909366
}  
avr.-03 17:55:36.774 [JavaFX Application Thread] INFO  b.c.d.m.n.StateNetworkService: We received a NewDaoStateHashMessage from peer Optional[2bnvhfkdrnx5hrlv.onion:8005] with stateHash=StateHash{
     height=1200,
     hash=1f7a719ba8ead4ae5ca9cdd4b40bfdf164d735b8,
     prevHash=c06d7aab553d631a01d10442cbed0ed027909366
}  
avr.-03 17:55:37.547 [JavaFX Application Thread] INFO  b.c.d.m.n.StateNetworkService: We received a NewDaoStateHashMessage from peer Optional[boq6l2ur2jmubfqh.onion:9999] with stateHash=StateHash{
     height=1200,
     hash=1f7a719ba8ead4ae5ca9cdd4b40bfdf164d735b8,
     prevHash=c06d7aab553d631a01d10442cbed0ed027909366
}  
avr.-03 17:55:37.757 [JavaFX Application Thread] INFO  b.c.d.m.n.StateNetworkService: We received a NewDaoStateHashMessage from peer Optional[b3jnw7fyph2jsu6n.onion:8005] with stateHash=StateHash{
     height=1200,
     hash=1f7a719ba8ead4ae5ca9cdd4b40bfdf164d735b8,
     prevHash=c06d7aab553d631a01d10442cbed0ed027909366
}  
avr.-03 17:55:38.968 [JavaFX Application Thread] INFO  b.c.d.m.n.StateNetworkService: We received a NewDaoStateHashMessage from peer Optional[xh65xuidoeiugbne.onion:9999] with stateHash=StateHash{
     height=1200,
     hash=1f7a719ba8ead4ae5ca9cdd4b40bfdf164d735b8,
     prevHash=c06d7aab553d631a01d10442cbed0ed027909366
}  
avr.-03 17:56:36.312 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 64.0 sec. after last request 
avr.-03 17:56:36.859 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4466.19, timestampSec=1554307070016, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.547 sec. 
avr.-03 17:57:38.321 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 62.009 sec. after last request 
avr.-03 17:57:39.052 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4469.21, timestampSec=1554307159756, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.731 sec. 
avr.-03 17:58:38.326 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 60.005 sec. after last request 
avr.-03 17:58:38.908 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4465.85, timestampSec=1554307249853, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.582 sec. 
avr.-03 17:59:11.761 [JavaFX Application Thread] INFO  b.d.app.BisqApp: System load: Memory (MB): 161 / No. of threads: 50 
avr.-03 17:59:41.342 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 63.016 sec. after last request 
avr.-03 17:59:41.844 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4466.81, timestampSec=1554307339824, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.502 sec. 
avr.-03 17:59:51.414 [JavaFX Application Thread] INFO  b.c.p.f.FeeService: BTC tx fee: txFeePerByte=96 
avr.-03 18:00:43.354 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 62.012 sec. after last request 
avr.-03 18:00:44.739 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4466.81, timestampSec=1554307339824, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 1.385 sec. 

</pre>

**Comment by ripcurlx** [comment]
@HarryMacfinned In general you can't vote on different proposals with different vote weight. You make your choices for all proposals and add your stake you want to vote with and create the blind vote transaction. Afterwards you can't change your votes anymore or edit your vote stake. That's why you can't edit the amount anymore.
![Bildschirmfoto 2019-04-04 um 10 58 29](https://user-images.githubusercontent.com/170962/55543104-ae589680-56c8-11e9-80aa-db0e8c7ebfc2.png)
Did you see the wrong validation error message in this screen having the Blind vote transaction ID below?

**Comment by ghost** [comment]
ok.
So I believe it's a misunderstanding from my side.
If I understand well, if I have 100.000 BSQ and want to vote for 10 proposals, I should fix a max amount of 9990 BSQ (I let room for the vote fees), and it will be ok.
I have to read the docs more carefully. Apologies.

However, I don't see the screen above.
The most recent proposal I see is 3 Apr 2019 00:48:21 from Alexej.
How is it that you see proposals from 4 Apr 2019, and not my appli ?

**Comment by ripcurlx** [comment]
The screenshot is from my local regtest setup.
You don't have to split up the vote stake. The total stake is applied to each vote, so you con vote with all your BSQ (just don't forget that it will be locked up until the vote reveal phase)
