### ISSUE TITLE
Appli not shuting down

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#2634]
with BTC_DAO_REGTEST
Clicking the top right close button, but the appli doesnt close.
I had to force quit.
(maybe related to https://github.com/bisq-network/bisq/issues/2489 )
<pre>
avr.-03 17:09:06.718 [main] INFO  b.c.s.CoreSetup: 
Log files under: /home/user1/bisq/dataDir-btcdaoregtest/Bisq/bisq 
avr.-03 17:09:06.750 [main] INFO  b.c.u.Utilities: System info: os.name=Linux; os.version=4.9.0-8-amd64; os.arch=amd64; sun.arch.data.model=64; JRE=10.0.2+13 (Oracle Corporation); JVM=10.0.2+13 (Java HotSpot(TM) 64-Bit Server VM) 
avr.-03 17:09:06.938 [main] INFO  b.c.app.Version: Version{VERSION=0.9.7, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=1, BASE_CURRENCY_NETWORK=5, getP2PNetworkId()=15} 
avr.-03 17:09:06.939 [main] INFO  b.c.s.CoreSetup: Path to Bisq jar file: /opt/Bisq/app/desktop-0.9.7-all.jar 
...
...
avr.-04 09:05:51.019 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 60.012 sec. after last request 
avr.-04 09:05:51.828 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4494.71, timestampSec=1554361701584, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 0.809 sec. 
avr.-04 09:06:54.031 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 63.012 sec. after last request 
avr.-04 09:06:56.286 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4494.71, timestampSec=1554361701584, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 2.255 sec. 
avr.-04 09:07:55.045 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 61.014 sec. after last request 
avr.-04 09:07:56.320 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4487.93, timestampSec=1554361791590, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 1.275 sec. 
avr.-04 09:08:55.046 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 60.001 sec. after last request 
avr.-04 09:08:56.246 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4486.14, timestampSec=1554361881591, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 1.2 sec. 
avr.-04 09:09:11.769 [JavaFX Application Thread] INFO  b.d.app.BisqApp: System load: Memory (MB): 167 / No. of threads: 52 
avr.-04 09:09:51.979 [JavaFX Application Thread] INFO  b.c.p.f.FeeService: BTC tx fee: txFeePerByte=146 
avr.-04 09:09:58.061 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 63.015 sec. after last request 
avr.-04 09:09:59.323 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4486.14, timestampSec=1554361881591, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 1.262 sec. 
avr.-04 09:11:00.072 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 62.011 sec. after last request 
avr.-04 09:11:01.330 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4487.82, timestampSec=1554361971737, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 1.258 sec. 
avr.-04 09:12:04.078 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 64.006 sec. after last request 
avr.-04 09:12:05.323 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4485.8, timestampSec=1554362061682, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 1.244 sec. 
avr.-04 09:13:05.089 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 61.01 sec. after last request 
avr.-04 09:13:06.310 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4485.8, timestampSec=1554362061682, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 1.221 sec. 
avr.-04 09:14:05.090 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 60.001 sec. after last request 
avr.-04 09:14:06.347 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4478.98, timestampSec=1554362151594, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 1.257 sec. 
avr.-04 09:14:51.992 [JavaFX Application Thread] INFO  b.c.p.f.FeeService: BTC tx fee: txFeePerByte=146 
avr.-04 09:15:03.368 [InputHandler-j2go5evebshb3kos.onion:9999] INFO  b.n.p.n.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-04 09:15:03.368 [InputHandler-b3jnw7fyph2jsu6n.onion:8005] INFO  b.n.p.n.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-04 09:15:03.368 [InputHandler-igowbh7gexv26qky.onion:9999] INFO  b.n.p.n.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-04 09:15:03.368 [InputHandler-boq6l2ur2jmubfqh.onion:9999] INFO  b.n.p.n.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-04 09:15:03.368 [InputHandler-5i6b7nnerls7llcj.onion:9999] INFO  b.n.p.n.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-04 09:15:03.368 [InputHandler-gtif46mfxirv533z.onion:8005] INFO  b.n.p.n.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-04 09:15:03.368 [InputHandler-yzab7hbp6hmpcoi6.onion:9999] INFO  b.n.p.n.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-04 09:15:03.368 [InputHandler-2bnvhfkdrnx5hrlv.onion:8005] INFO  b.n.p.n.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-04 09:15:03.368 [InputHandler-rvtp3f5teuinofyc.onion:9999] INFO  b.n.p.n.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-04 09:15:30.252 [Wallet autosave thread] INFO  o.b.w.WalletFiles: Background saving wallet; last seen block is height 1292, date 2019-04-04T07:15:25Z, hash 635bf0822c24a867620bc314f6f4f0584b212cb917123c0c6364d65967cd6a0d 
avr.-04 09:15:30.252 [Wallet autosave thread] INFO  o.b.w.WalletFiles: Background saving wallet; last seen block is height 1292, date 2019-04-04T07:15:25Z, hash 635bf0822c24a867620bc314f6f4f0584b212cb917123c0c6364d65967cd6a0d 
avr.-04 09:15:30.314 [Wallet autosave thread] INFO  o.b.w.WalletFiles: Save completed in 61.72 ms 
avr.-04 09:15:30.314 [Wallet autosave thread] INFO  o.b.w.WalletFiles: Save completed in 61.86 ms 
</pre>

**Comment by ripcurlx** [comment]
@HarryMacfinned Do you experience this every time you shut down the application?

**Comment by ghost** [comment]
@ripcurlx ,
No.
09:07 I did just close v0.9.7 mainnet, and it closed gracefully.

I will count how often this happens.
It may be related to https://github.com/bisq-network/bisq/issues/2634 , since I had this "input is not a valid number" red message still screwed in the DAO/Browse Open Proposal screen ?

11:45 just closed btc_dao_regtest and it closed gracefully
16:00 just closed mainnet and it closed gracefully
17:03 just closed mainnet and it closed gracefully
17:18 just closed btc_dao_regtest and it closed gracefully
17:52 just closed btc_dao_regtest and it closed gracefully
08:55 just closed mainnet and it closed gracefully

**Comment by ManfredKarrer** [comment]
@HarryMacfinned Can you send me the full log?

**Comment by ghost** [comment]
sent

**Comment by ghost** [comment]
On BTC_DAO_REGTEST
14:50 Just got the same shutdown issue.
Last lines from the CLI:
<pre>
...
avr.-05 14:46:05.887 [JavaFX Application Thread] INFO  b.core.provider.fee.FeeService: BTC tx fee: txFeePerByte=152 
avr.-05 14:46:17.190 [JavaFX Application Thread] INFO  b.c.p.price.PriceFeedService: request from provider http://xc3nh4juf2hshy7e.onion/ 62.011 sec. after last request 
avr.-05 14:46:18.013 [JavaFX Application Thread] INFO  b.c.p.price.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4492.65, timestampSec=1554468375205, isExternallyProvidedPrice=true) from provider http://xc3nh4juf2hshy7e.onion/ after 0.822 sec. 
avr.-05 14:47:18.199 [JavaFX Application Thread] INFO  b.c.p.price.PriceFeedService: request from provider http://xc3nh4juf2hshy7e.onion/ 61.008 sec. after last request 
avr.-05 14:47:19.057 [JavaFX Application Thread] INFO  b.c.p.price.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4492.65, timestampSec=1554468375205, isExternallyProvidedPrice=true) from provider http://xc3nh4juf2hshy7e.onion/ after 0.858 sec. 
avr.-05 14:48:22.210 [JavaFX Application Thread] INFO  b.c.p.price.PriceFeedService: request from provider http://xc3nh4juf2hshy7e.onion/ 64.011 sec. after last request 
avr.-05 14:48:22.888 [JavaFX Application Thread] INFO  b.c.p.price.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4490.13, timestampSec=1554468464922, isExternallyProvidedPrice=true) from provider http://xc3nh4juf2hshy7e.onion/ after 0.678 sec. 
avr.-05 14:49:22.228 [JavaFX Application Thread] INFO  b.c.p.price.PriceFeedService: request from provider http://xc3nh4juf2hshy7e.onion/ 60.018 sec. after last request 
avr.-05 14:49:23.211 [JavaFX Application Thread] INFO  b.c.p.price.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4489.71, timestampSec=1554468554908, isExternallyProvidedPrice=true) from provider http://xc3nh4juf2hshy7e.onion/ after 0.983 sec. 
avr.-05 14:50:25.240 [JavaFX Application Thread] INFO  b.c.p.price.PriceFeedService: request from provider http://xc3nh4juf2hshy7e.onion/ 63.012 sec. after last request 
avr.-05 14:50:25.976 [JavaFX Application Thread] INFO  b.c.p.price.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4489.71, timestampSec=1554468554908, isExternallyProvidedPrice=true) from provider http://xc3nh4juf2hshy7e.onion/ after 0.736 sec. 
avr.-05 14:50:56.950 [InputHandler-xpkxxewd2gsiwfyh.onion:9999] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-05 14:50:56.950 [InputHandler-2bnvhfkdrnx5hrlv.onion:8005] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-05 14:50:56.951 [InputHandler-igowbh7gexv26qky.onion:9999] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-05 14:50:56.951 [InputHandler-2o7w2tly4zqfucao.onion:9999] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-05 14:50:56.951 [InputHandler-b3jnw7fyph2jsu6n.onion:8005] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-05 14:50:56.951 [InputHandler-gtif46mfxirv533z.onion:8005] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-05 14:50:56.951 [InputHandler-rvtp3f5teuinofyc.onion:9999] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-05 14:50:56.951 [InputHandler-kaoktbm3pxxnq2xp.onion:9999] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-05 14:50:56.951 [InputHandler-j2go5evebshb3kos.onion:9999] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-05 14:50:56.951 [InputHandler-boq6l2ur2jmubfqh.onion:9999] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-05 14:55:33.595 [Wallet autosave thread] INFO  o.bitcoinj.wallet.WalletFiles: Background saving wallet; last seen block is height 1470, date 2019-04-05T12:55:28Z, hash 38e8137b13aec36c7c9a701587a33952883824b19c05007df78dc5a0ad52974d 
avr.-05 14:55:33.595 [Wallet autosave thread] INFO  o.bitcoinj.wallet.WalletFiles: Background saving wallet; last seen block is height 1470, date 2019-04-05T12:55:28Z, hash 38e8137b13aec36c7c9a701587a33952883824b19c05007df78dc5a0ad52974d 
avr.-05 14:55:33.653 [Wallet autosave thread] INFO  o.bitcoinj.wallet.WalletFiles: Save completed in 57.68 ms 
avr.-05 14:55:33.653 [Wallet autosave thread] INFO  o.bitcoinj.wallet.WalletFiles: Save completed in 57.62 ms 

avr.-05 15:05:33.705 [Wallet autosave thread] INFO  o.bitcoinj.wallet.WalletFiles: Background saving wallet; last seen block is height 1471, date 2019-04-05T13:05:28Z, hash 7123859ad34d087740a1baac83662393ae1b68be7df13498420e973e8d2e01c9 
avr.-05 15:05:33.705 [Wallet autosave thread] INFO  o.bitcoinj.wallet.WalletFiles: Background saving wallet; last seen block is height 1471, date 2019-04-05T13:05:28Z, hash 7123859ad34d087740a1baac83662393ae1b68be7df13498420e973e8d2e01c9 
avr.-05 15:05:33.825 [Wallet autosave thread] INFO  o.bitcoinj.wallet.WalletFiles: Save completed in 119.9 ms 
avr.-05 15:05:33.825 [Wallet autosave thread] INFO  o.bitcoinj.wallet.WalletFiles: Save completed in 120.0 ms 
avr.-05 15:15:33.660 [Wallet autosave thread] INFO  o.bitcoinj.wallet.WalletFiles: Background saving wallet; last seen block is height 1472, date 2019-04-05T13:15:28Z, hash 751e5c36884c9a574104572e8c48ea26c8ac06f55aefd8dea6b35e4560cc6aa6 
avr.-05 15:15:33.660 [Wallet autosave thread] INFO  o.bitcoinj.wallet.WalletFiles: Background saving wallet; last seen block is height 1472, date 2019-04-05T13:15:28Z, hash 751e5c36884c9a574104572e8c48ea26c8ac06f55aefd8dea6b35e4560cc6aa6 
avr.-05 15:15:33.704 [Wallet autosave thread] INFO  o.bitcoinj.wallet.WalletFiles: Save completed in 43.55 ms 
avr.-05 15:15:33.704 [Wallet autosave thread] INFO  o.bitcoinj.wallet.WalletFiles: Save completed in 43.22 ms 
avr.-05 15:25:33.649 [Wallet autosave thread] INFO  o.bitcoinj.wallet.WalletFiles: Background saving wallet; last seen block is height 1473, date 2019-04-05T13:25:28Z, hash 3a1606c244160eabdd9384f968ef23faf203ec20d0aa32a4b41b5ebaa79e6bfa 
avr.-05 15:25:33.651 [Wallet autosave thread] INFO  o.bitcoinj.wallet.WalletFiles: Background saving wallet; last seen block is height 1473, date 2019-04-05T13:25:28Z, hash 3a1606c244160eabdd9384f968ef23faf203ec20d0aa32a4b41b5ebaa79e6bfa 
avr.-05 15:25:33.732 [Wallet autosave thread] INFO  o.bitcoinj.wallet.WalletFiles: Save completed in 82.15 ms 
avr.-05 15:25:33.761 [Wallet autosave thread] INFO  o.bitcoinj.wallet.WalletFiles: Save completed in 109.3 ms 
... ctrl-z in CLI to force-quit
</pre>

My internet connection is ok at the same time.

**Comment by ghost** [comment]
08:28 just closed btc_dao_regtest and it closed gracefully
<pre>
}  
avr.-06 08:25:53.420 [JavaFX Application Thread] INFO  b.c.p.price.PriceFeedService: request from provider http://5bmpx76qllutpcyp.onion/ 64.002 sec. after last request 
avr.-06 08:25:54.220 [JavaFX Application Thread] INFO  b.c.p.price.PriceFeedService: Received new MarketPrice(currencyCode=EUR, price=4478.98, timestampSec=1554531943150, isExternallyProvidedPrice=true) from provider http://5bmpx76qllutpcyp.onion/ after 0.8 sec. 
avr.-06 08:26:18.364 [InputHandler-gtif46mfxirv533z.onion:8005] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-06 08:26:18.365 [InputHandler-7zow4lbxs7ulopbm.onion:9999] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-06 08:26:18.365 [InputHandler-xpkxxewd2gsiwfyh.onion:9999] INFO  b.n.p2p.network.Connection: SocketException (expected if connection lost). closeConnectionReason=CloseConnectionReason{sendCloseMessage=false, isIntended=false} RESET; connection=Connection{peerAddress=Optional[xpkxxewd2gsiwfyh.onion:9999], peerType=PEER, uid='03fd2943-d3dc-4afd-9569-b46260b24fc7'} 
avr.-06 08:26:18.365 [InputHandler-5i6b7nnerls7llcj.onion:9999] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-06 08:26:18.365 [InputHandler-kaoktbm3pxxnq2xp.onion:9999] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-06 08:26:18.365 [InputHandler-b3jnw7fyph2jsu6n.onion:8005] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-06 08:26:18.365 [InputHandler-j2go5evebshb3kos.onion:9999] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-06 08:26:18.365 [InputHandler-2bnvhfkdrnx5hrlv.onion:8005] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-06 08:26:18.365 [InputHandler-igowbh7gexv26qky.onion:9999] INFO  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
avr.-06 08:26:18.389 [PeerGroup Thread] INFO  org.bitcoinj.core.PeerGroup: Stopping ... 
avr.-06 08:26:18.389 [ STOPPING] INFO  org.bitcoinj.core.PeerGroup: Awaiting PeerGroup shutdown ... 
avr.-06 08:26:18.390 [PeerGroup Thread] INFO  org.bitcoinj.core.PeerGroup: Stopped. 
</pre>
