### ISSUE TITLE
List VIVO

### ISSUE THREAD

**Issue by coolblock** [bisq-network/bisq#2641]
Please fill in the following data to request for a new asset to be listed on Bisq. For more details, be sure to read [the full documentation](https://docs.bisq.network/exchange/howto/list-asset.html) on adding a new asset.

### 1. Asset name
VIVO

### 2. Ticker
VIVO

### 3. Block explorer URL
Several available here:
http://vivocoin.net/vivo-explorer/

### 4. Additional technical requirements (yes/no)
no extra requirements

### 5. Initial coin offering (yes/no)
no ico

**Comment by coolblock** [comment]
Any help we can give to move this along?

**Comment by blabno** [comment]
Is it ERC-20 token?
Is it privacy coin like monero?
Is it fork of any other coin?
What are the wallet address validation rules?

**Comment by coolblock** [comment]
It is not an ERC token
It is not a privacy coin
It is a fork of Dash
