### ISSUE TITLE
Allow for input of custom addresses and amount on payout transaction

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#2642]
At present, a Bisq trade has 4 phases:

    1. Make offer:
        A) Maker transaction
        ◦ trade fee
        ◦ security deposit
        ◦ payment (if BTC seller)

    2. Take offer:
        A) Taker transaction
            ▪ trade fee
            ▪ security deposit
            ▪ payment (if BTC seller)

        B) Escrow transaction
            ▪ payment
            ▪ seller’s security deposit
            ▪ buyer’s security deposit

    3. The BTC buyer confirms Fiat/Altcoin payment sent
        A) Payout transaction is created and signed by the buyer
        ◦ seller’s security deposit
        ◦ buyer’s security deposit
        ◦ buyer’s payment

    4. The BTC seller confirms that they’ve received the Fiat/Altcoin payment
        A) Payout transaction is signed and broadcast by the seller
            ▪ seller’s security deposit
            ▪ buyer’s security deposit
            ▪ buyer’s payment

My suggestion is to allow, on phases 1 and 2, traders to set custom addresses on which to receive their payout amounts.
	Bisq is a platform that facilitates trust-less trade. There’s little reason as to why the payout amounts should be deposited in the Bisq internal wallet. Most people will eventually withdraw that amount onto their own external wallets.
So there should be an optional placeholder field for traders to put a specif address of their own to an external wallet. The offer maker could specify theirs on the “Make offer” screen and the offer taker could specify theirs on the “Take offer” screen.

Multiple payout addresses and custom splits

There could also be the option to specify up to 2 outputs (addresses) for the offer taker. This would increase the payout transaction size but since it’s the offer taker who pays for the miner fees, they could make that judgment.
This tool would allow for the enforcement of off-Bisq contracts/deals. The requirement of BTC to conduct trades on Bisq is a detractor for many newcomers to Bitcoin who don’t own any. This would allow for an on-boarding platform for newcomers without having them go to central exchanges. A newcomer would go to the Bisq forum or slack and ask for a loan. Someone would take them on their offer and privately, the bitcoiner would provide the newcomer with a reimbursement address for the loan and they’d agree on values (interest). The newcomer would then present the bitcoiner with the “Take offer” screen, which would show the bitcoiner’s addresses as one of the payout addresses and with the agreed amount set to it. This could be done by a screen-share or a video call. The bitcoiner would then fund the trade by scanning the QR-code on screen (or else).
With this architecture, the lender would be certain that the Bisq software would send them, at the end, their due amount and they wouldn’t have to trust the newcomer.

UI examples
![takeoffernew](https://user-images.githubusercontent.com/44140017/55576767-edf3a280-5709-11e9-8ab7-40b970ee1eda.png)
![makeoffernew](https://user-images.githubusercontent.com/44140017/55576769-edf3a280-5709-11e9-8f44-049cec2e178d.png)

**Comment by ghost** [comment]
@huey735 
You are proposing 2 rather big things.
https://github.com/bisq-network/proposals is the place where such proposals are made.
It may be better there, and imo maybe better have a separate proposal for each.
Anyway, thanks, it's interesting.

**Comment by huey735** [comment]
@HarryMacfinned I'm not a developer so this vehicle seems more appropriate. If I understood correctly from the Bisq etiquette, proposals are to be made by people who can carry them out.
https://docs.bisq.network/proposals.html#submitter

Also, not being a developer, I assumed that changing the lookup method for the payout addresses wouldn't be so difficult and that the value added would be greater. So I apologize in advance for my ignorant presumptions.
I envisioned it as a whole proposal. How are you separating the implementation? What are the two proposals you see?

**Comment by ManfredKarrer** [comment]
I will think when implementing the new trade protocol if customizing the payout address fits in.
I am not very convinced that there are many users who would use that. Adding more customisation adds complexity, risk for bugs and more challenges for UX. There are already many details to learn for users, to add new one without strong benefit need to be considered well.

**Comment by ghost** [comment]
@huey735 wrote:
> I envisioned it as a whole proposal. How are you separating the implementation? What are the two proposals you see?

My bad. I thought that the custom addresses part and the on-boarding mechanism could be separated.

**Comment by huey735** [comment]
@ManfredKarrer I can't share your point of view on its utility. Other than frequent traders, no one has an incentive to have their payout (security deposit or trade amount) land on their Bisq wallet.
I can't comment on the implementation and maintenance complexities . But on terms of the UX, these options could be behind a "Advanced" button so only those interested would check it out.
@HarryMacfinned all I'm proposing to implement on the Bisq software is the custom addresses and amounts. The possibility for an on-boarding mechanism would result from that but would be done "outside" of the Bisq software.

**Comment by ManfredKarrer** [comment]
I will see how it can fit in with the next bigger work package in that area... Atm we dont have an advanced section but that is planned anyway, so lets see when there is that it will be easier to squeeze it in. I don't know how many need/would use that, but as you are the first who request that after 3 years I assume its not so much requested... But I agree it would be useful...

**Comment by ghost** [comment]
Maybe that the access to the advanced section could only be made possible if you launch Bisq in CLI 
with <code>Bisq --advancedSection=true</code> ?
So we'll be sure that only really interested (and knowledgeable) users will use it.
And the "normal" user will absolutely not be worried about this feature.

**Comment by huey735** [comment]
@HarryMacfinned I worry that that may be hiding it too much. Although I agree that it's important to keep the UX simple, I think everybody would benefit from this, even the less knowledgeable.

**Comment by huey735** [comment]
It recently occurred to me that these suggestions aren't enough to allow for a loan of bitcoin to nocoiners. It would be the case if the trade got triggered at the "Take offer" screen after one has scanned the qr-code and sent the funding transaction. But at present, Bisq still allows the user to cancel the trade after this step.

The other pros for the suggestion remain intact.

**Comment by huey735** [comment]
Still relevant.
