### ISSUE TITLE
Create Gradle task for building bootstrap node jar

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#265]
This should be easy to do, but I'm not sure about the configuration. I've asked about this at johnrengelman/shadow#108. In the meantime, @ManfredKarrer, if you want to build the bootstrap node jar, just change the value of `mainClassName` in build.gradle from `io.bitsquare.app.gui.Main` to the BootstrapNode class name, and then run `./gradlew shadowJar` as usual.

**Comment by ManfredKarrer** [comment]
Ah cool!
