### ISSUE TITLE
DAO - Submitting proposals for the next cycle

### ISSUE THREAD

**Issue by mpolavieja** [bisq-network/bisq#2653]
Issue submited for testing the DAO

Why is not allowed to submit proposals for the next cycle?

**Comment by ghost** [comment]
You mean making proposal for cycle5 right now ?

**Comment by mpolavieja** [comment]
Not exactly, I mean making proposals for next cycle when the current proposal phase is closed.

**Comment by ManfredKarrer** [comment]
I think it would management harder. People vote on proposals of that cycle then they would need to separate those which are opened for next cycle.
In real version the proposal phase is about 3 weeks and voting 3+3 days.

**Comment by ripcurlx** [comment]
Closing based on https://github.com/bisq-network/bisq/issues/2653#issuecomment-480436322
