### ISSUE TITLE
Add missing validation at offers received from network

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#2658]
If an user place an order using an old version that in some way is incompatible with newer versions of Bisq, I think Bisq software should notify users about the situation before someone accept the offer.
Something like: This offer has an empty field that in newer versions of Bisq, the imput is mandatory.

See the reason here: https://bisq.community/t/serious-problem-buying-btc-on-bisq/7349/7

**Comment by ghost** [comment]
I agree that it would be useful to display the Bisq version for the offers.
I don't know if the primitive needed to implement that already exist or not.
Could also be that the up to date nodes simply refuse to propagate offers from non-updated nodes. ... maybe a bit harsh.

**Comment by ManfredKarrer** [comment]
@bitcoinuser This error report is the first of its kind and it is not clear if it is related to an older version. We take care to not break backward compatibility, so adding a new property and add complexity to the user is not the right way to go. If there is an issue we need to fix it but not delegate it to the user to make a decision where they cannot have the full picture and context. I will close that issue as I don't think we should add the version to the offer. If you can deliver more info from that offer please do so, maybe we find out what caused that. Maybe a user hacked around with the code...

**Comment by bitcoinuser** [comment]
I don't say we need to add the version to the offer. I mean Bisq shouldn't show offers that doesn't have all fields that is mandatory to be filled in the last version of Bisq.

**Comment by bitcoinuser** [comment]
So if on the last version of bisq, the field CPF is mandatory, if there's an offer that this field is empty, for any reason, maybe old version or modified version of bisq, this offer shouldn't appear on network.

**Comment by ManfredKarrer** [comment]
Yes agree, I will change title and reopen it.

**Comment by ManfredKarrer** [comment]
The validation for CPF (and other mandatory payment account data) should be added when receiving offers from the network.

**Comment by ghost** [comment]
unstale
