### ISSUE TITLE
Test asset fee tx

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2659]
The asset listing fee tx does not use a BTC input in case the BSQ fee is >= miner fee.

A valid tx can look like (tested):
Input 0: 222216.00 BSQ (22221600 Sat)
Output 0: 122217.00 BSQ (12221700 Sat)
Output 1: 0,09961716 BTC (9961716 Sat)
Miner fee: 0,00038184 (38184 Sat)
 
We should test if in case the input is exact the amount of the required miner fee we cannot create the tx as a tx without outputs is not valid. We need to have at least 1 output with 546 sat. This output can be either BSQ or BTC.

**Comment by sqrrm** [comment]
Should be closed, see #2664
