### ISSUE TITLE
Writing json file to disc on Windows fails

### ISSUE THREAD

**Issue by BrettCawley** [bisq-network/bisq#2660]
On a windows machine, launch bisq using the "--dumpStatistics=true" argument.

Observe many temp files in "Bisq\btc_mainnet\db" are continually created.

Issue is due to a failure when renaming the temp file to the correct file name.

**Comment by ManfredKarrer** [comment]
Can you post the log file?

**Comment by BrettCawley** [comment]
Log attached.
My assumption is it's not possible to rename the file when it's still in use
[bisq.log](https://github.com/bisq-network/bisq/files/3050804/bisq.log)

**Comment by ManfredKarrer** [comment]
I think its a windows only issue. There are some temp file handling issues. As that feature is used for exploreres only and they run on linux I did not care much, but yes should be fixed...
