### ISSUE TITLE
Do not connect to a local pruned node

### ISSUE THREAD

**Issue by dreboli** [bisq-network/bisq#2668]
A pruned bitcoin node is running locally.
I don't want Bisq to connect to it because as far as I know it can't use pruned nodes.
I want to use a remote node, but can't set it on the network settings page (greyed out), the only option available was resync spv node, but obviously that won't happen while my bitcoin node is running, because bisq wants to connect to it.

Is the a config file I can set a remote node or some other method to tell bisq to use a remote node?

**Comment by ManfredKarrer** [comment]
You can pass --btcNodes=... as prog. argument. List the remote node there then it should not connect to localhost (not 100% sure if it overrides localhost but should)

**Comment by bisqit** [comment]
What if there is no known reliable remote full (non-pruned) node available? 

I'm running a local pruned bitcoin node but don't have a remote full node available. I'd still like to be able to run Bisq without having to shut down my local pruned node. If I understand correctly, this is currently not possible.

**Comment by timmornYE** [comment]
Use switch `ignoreLocalBtcNode=true` to achieve this. See [list of all cli options](https://github.com/bisq-network/bisq/blob/master/common/src/main/java/bisq/common/config/Config.java#L57).
