### ISSUE TITLE
order shows up in portfolio but not order book (relay mode problem?)

### ISSUE THREAD

**Issue by remyers** [bisq-network/bisq#267]
Before getting port forwarding working I did some testing in relay mode.  The order I added on Nov 9th appears in the portfolio tab, but not in the order book.  The order I added in port forwarding mode on Nov 10th shows up both in the portfolio and order book.   

These shows what it looks like after I have shutdown and restarted my copy of Bitsquare.  

![image](https://cloud.githubusercontent.com/assets/8568892/4975593/d9a3ae32-68da-11e4-806b-b4a8ca7716c5.png)

![image](https://cloud.githubusercontent.com/assets/8568892/4975596/dee3dce6-68da-11e4-93d7-a6f54b5f3e7c.png)

PS> If it turns out to be difficult to debug this issue in relay mode, we should consider disabling relay mode until we feel everything is working well for 0.1 in port forward mode.

**Comment by ManfredKarrer** [comment]
That might be caused as I restarted the bootstrap mode yesterday. But yes relay mode has lots of issues, yet. I will go on testing it now as well. was more focussed on PF mode lately. If we have PF working and relay is still not stabel we will deactivate it.

**Comment by ManfredKarrer** [comment]
I think that is either related to the DHT problems, or to a server restart like described in the comment above. I will close it for now.
