### ISSUE TITLE
"Maker's onion address: localhost"

### ISSUE THREAD

**Issue by userzer0x** [bisq-network/bisq#2671]
I noticed one peer having "localhost" instead of an actual onion address. Can you tell why this is?
If this is an even more privacy feature then can you say how to enable it?

**Comment by ManfredKarrer** [comment]
Are you referring to BTC peers or Bisq P2P network peers?
Are you running on mainnet or the DAO regtest network?
Do you have any loclhost node running?

**Comment by userzer0x** [comment]
Im referring to Bisq P2P network peers as i hovered over the little man icon and saw that peer had 

`Maker's onion address: localhost`

And no, did not meddle with DAO at all. This is the normal mainnet.
I have Bitcoin core running yes, but thats it. All other peers had normal onion addresses, right now all of them have a normal onion address.  But that was really weird yesterday.  Do you know why it showed that?

**Comment by ManfredKarrer** [comment]
Can you post the curreny, price, offer ID and if its buy or sell offer?

**Comment by ManfredKarrer** [comment]
Seems to come from a developer doing weird stuff, an API user with using a buggy version of the API or someone fiddling around with data. Don't take that offer it will fail.

**Comment by userzer0x** [comment]
@ManfredKarrer stupid of me not to take a screenshot. Unfortunately i cannot find that offer at the moment. But if i see it again i will screenshot it.
Do you think a dev was testing something? or maybe you should ask them.

**Comment by ghost** [comment]
If this comes from an actual contributor, probably he would have seen this issue. (github issues are also republished on the slack).
As says Manfred, could also have been a side effect from somebody playing with the API.
(maybe Bisq could have some API mark in the requests, indicating it comes from the API. Or maybe it already exists ?)
Could also be some hacker testing what's doable or not. 
... Hard to know.

**Comment by ghost** [comment]
update:
I observed something similar in my portfolio/history tab.
For one peer, there is no onion address, only "localhost:9999" mentioned in the details popup.
And I'm quite sure that when the trade was just finished, there was an onion address mentioned.
