### ISSUE TITLE
Cannot distinguish between instant offers and regular offers in portfolio view

### ISSUE THREAD

**Issue by m52go** [bisq-network/bisq#2672]
It doesn't seem like someone with multiple offers open can tell which are instant and which aren't. 

If I'm stepping away from my desk and need to disable a live offer, I need to check offer details until I find the ones that are instant.

![Screenshot from 2019-04-08 12-57-30](https://user-images.githubusercontent.com/735155/55743030-49ba7600-59ff-11e9-9e2f-11381c230591.png)

Also, the user will only know the offer is instant if they especially marked it so when creating the payment account—the actual payment method (in this case, "Altcoins Instant") is not specified in the offer details pop-up:

![Screenshot from 2019-04-08 13-06-12](https://user-images.githubusercontent.com/735155/55743037-4d4dfd00-59ff-11e9-8b06-6eb790a3152f.png)

**Comment by m52go** [comment]
Maybe this isn't a problem for most people. Perhaps a quick fix (if it is quick) is to include the payment method in the offer details pop-up or "My Open Offers" table.

**Comment by ripcurlx** [comment]
We also have the same issue with payment methods as well. They are not shown in this screen as well. I'll see if I find a solution to add this information within this limited space.
