### ISSUE TITLE
Adjust margin on "Don't show again" alert for translated strings

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#2681]
Unfortunately due to the nature of translations, strings can vary in length from language to language. I have my adjusted some translations for harmony with the UI where possible, but some places just can't be helped.
Alerting about the security deposit function
![alert](https://user-images.githubusercontent.com/44140017/55806430-231c3e00-5ad8-11e9-9f81-d7b5759af330.png)
Alerting that I've accepted an offer
![offeraccpted](https://user-images.githubusercontent.com/44140017/55806432-23b4d480-5ad8-11e9-8f53-7aa40352eee4.png)

**Comment by ripcurlx** [comment]
Yes, I the construction of the UI in the footer need to be changed. I saw this also in the German translation already.
