### ISSUE TITLE
Remove bold in title (maybe use medium or regular) and make blur overlay darker

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/bisq#2682]
<img width="1192" alt="Screen Shot 2019-04-09 at 1 14 16 PM" src="https://user-images.githubusercontent.com/807505/55820648-94a0c000-5ac9-11e9-904d-460089580d86.png">

**Comment by ripcurlx** [comment]
I use now the regular information style and darked for all popups the background a little bit.

![Bildschirmfoto 2019-04-10 um 15 47 52](https://user-images.githubusercontent.com/170962/55884262-0ea77680-5ba8-11e9-8340-92eaaca48b6b.png)

**Comment by ripcurlx** [comment]
I just saw #2337 which shows a way darker background. I'll adapt the current design to a darker background version.

**Comment by ripcurlx** [comment]
Darkened it now even more.
![Bildschirmfoto 2019-04-10 um 16 10 29](https://user-images.githubusercontent.com/170962/55885977-30eec380-5bab-11e9-9209-e413a5dcfa11.png)

**Comment by ManfredKarrer** [comment]
Does feel a bit too dark for my taste.... But leave it to you and pedro.
