### ISSUE TITLE
Cannot add Semux (SEM) Altcoin account

### ISSUE THREAD

**Issue by ashmaste** [bisq-network/bisq#2684]
Accounts -> ALTCOIN ACCOUNTS -> Create new account
SEM not shown on dropdown list.
Please fix.  I want to sell some SEM on Bisq.

**Comment by ghost** [comment]
SEM (Semux) is no more present in v0.9.8
Probably delisted due to insufficient trading (https://bisq.community/t/never-traded-altcoins/6237 ).
When the DAO will be released, you should be able to have it listed again.

**Comment by ripcurlx** [comment]
Closing based on https://github.com/bisq-network/bisq/issues/2684#issuecomment-481545035.
