### ISSUE TITLE
Bisq doesn't launch with Java 1.8

### ISSUE THREAD

**Issue by Nolaan** [bisq-network/bisq#2694]
Hello,
I'm running java `1.8.0_102` but I can't launch Bisq, I've the following error : 
```
<JAVA_HOME>/lib/ext exists, extensions mechanism no longer supported; Use -classpath instead.
.Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

```

**Comment by ghost** [comment]
@Nolaan ,
if you compile from sources, you need openJDK10 atm.
see https://github.com/bisq-network/bisq/blob/master/docs/build.md

**Comment by Nolaan** [comment]
Nope I didn't.  Is there another way to obtain the mainnet BSQ address?

**Comment by ripcurlx** [comment]
> Hello,
> I'm running java `1.8.0_102` but I can't launch Bisq, I've the following error :
> 
> ```
> <JAVA_HOME>/lib/ext exists, extensions mechanism no longer supported; Use -classpath instead.
> .Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.
> ```

If you run the binary, it doesn't matter which Java version you have installed, as the correct JDK is integrated in the binary. Did you try to start Bisq 0.9.8 to get your mainnet BSQ address?

**Comment by HarryMacfinned** [comment]
afaik, BSQ addresses are only test BSQ addresses atm, and available by running Bisq in BTC_DAO_REGTEST mode.
But the DAO launch seems very close (some days), and then you'll have a mainnet BSQ address.

btw: If you run Bisq from an executable, you shouldn't get any message about the java version.
Bisq executables are compiled and packaged with their java code inside, and they run independently of the java version on your machine.
Would be curious to know how you get your java message above.

**Comment by Nolaan** [comment]
I ran `/opt/Bisq/Bisq`
@ripcurlx yes I'm trying torun 0.9.8 to get my address.

**Comment by ripcurlx** [comment]
> I ran `/opt/Bisq/Bisq`
> @ripcurlx yes I'm trying torun 0.9.8 to get my address.

And if you run it by clicking on the application icon it doesn't start?

**Comment by Nolaan** [comment]
Same error since this is the generated .desktop file :
```
[Desktop Entry]                                                                                                                                                                                                                                                                   
Name=Bisq                                                                                                                                                                                                                                                                         
Comment=The decentralized exchange network.                                                                                                                                                                                                                                       
👉Exec=/opt/Bisq/Bisq                                                                                                                                                                                                                                                           
Icon=/opt/Bisq/Bisq.png                                                                                                                                                                                                                                                           
Terminal=false                                                                                                                                                                                                                                                                    
Type=Application                                                                                                                                                                                                                                                                  
Categories=Unknown                                                                                                                                                                                                                                                                
```

**Comment by ghost** [comment]
What is your exact OS ? 
and your exact graphical interface ?

You should have a look at your OS log file at the moment of the issue.
Maybe there is some useful info there.

Also, the last lines of your Bisq logfile could help.

**Comment by Nolaan** [comment]
KDE + F27
I guess bisq is not launching anyway. So no logs

**Comment by Nolaan** [comment]
```
java -jar /opt/Bisq/app/desktop-0.9.8-all.jar                                                                                                                                                                                    
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: 
bisq/desktop/app/BisqAppMain has been compiled by a more recent version of the Java
Runtime (class file version 54.0), this version of the Java Runtime only recognizes 
class file versions up to 52.0 at java.lang.ClassLoader.defineClass1(Native Method)
 at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
 at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
 at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
 at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
 at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
 at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

**Comment by ripcurlx** [comment]
> ```
> java -jar /opt/Bisq/app/desktop-0.9.8-all.jar                                                                                                                                                                                    
> Error: A JNI error has occurred, please check your installation and try again
> Exception in thread "main" java.lang.UnsupportedClassVersionError: 
> bisq/desktop/app/BisqAppMain has been compiled by a more recent version of the Java
> Runtime (class file version 54.0), this version of the Java Runtime only recognizes 
> class file versions up to 52.0 at java.lang.ClassLoader.defineClass1(Native Method)
>  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
>  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>  at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
>  at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
>  at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
>  at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
>  at java.security.AccessController.doPrivileged(Native Method)
>  at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
>  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
>  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>  at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
> ```

If you are launching the jar file manually than you need to have OpenJDK10 installed on your machine.

**Comment by ghost** [comment]
@Nolaan 
What did you download from Bisq ?
The red hat/fedora package is 
https://github.com/bisq-network/bisq/releases/download/v0.9.8/Bisq-64bit-0.9.8.rpm

Did you download this package, or another one.

**Comment by Nolaan** [comment]
@HarryMacfinned yes I downloaded and installed that package then clicked the desktop icon but it wasn't launching, so I turned to the holy CLI.

**Comment by Nolaan** [comment]
@ripcurlx how to compile it?

**Comment by ghost** [comment]
see my post above:
if you compile from sources, you need openJDK10 atm.
see https://github.com/bisq-network/bisq/blob/master/docs/build.md
openJDK10 is atm mandatory.

**Comment by Nolaan** [comment]
Yeah trying to compile it right now.

**Comment by Nolaan** [comment]
Done Thanks!
