### ISSUE TITLE
Recover from seed

### ISSUE THREAD

**Issue by purpurato** [bisq-network/bisq#2702]
I want to recover my wallet funds from seed, but got this message. 
[bisq.log](https://github.com/bisq-network/bisq/files/3070805/bisq.log)

**Comment by ManfredKarrer** [comment]
Hm... weird exception I never saw before. In the BitcoinJ source code the CouldNotAdjustDownwards is thrown:
> if emptying the wallet was requested and the output can't be shrunk for fees without violating a protocol rule.

Do you have the original wallet still?

@oscarguindzberg Any idea how to help the user?

**Comment by oscarguindzberg** [comment]
Looks like a duplicate of https://github.com/bisq-network/bisq/issues/2640

**Comment by oscarguindzberg** [comment]
I will reply on the original https://github.com/bisq-network/bisq/issues/2640 issue

**Comment by ManfredKarrer** [comment]
Close as duplicate from https://github.com/bisq-network/bisq/issues/2640
