### ISSUE TITLE
No indication of error when vote reveal published out of phase

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2704]
I had submitted my vote during the blind vote phase (DAO regtest network, cycle 6), and then went offline. I then later came back online in the subsequent proposal phase and my client sent a vote reveal transaction (https://explorer.bisq.network/tx.html?tx=0eb496f7ad0cdca09e4979d09ebfbcf61c764979977734cc456b900f1f7ff15c), and showed the popup indicating it was published.

However, when looking at the vote results for the previous cycle, it shows my vote results without any indication that my vote reveal was not published in time (and as a result is not valid).
![image](https://user-images.githubusercontent.com/603793/56056597-7f1dd700-5d11-11e9-97a3-e20855b2d2ce.png)

Expected results:
- Perhaps the vote reveal transaction should not have been published since it was out of phase?
- Show an error icon as opposed to the thumbs up icon when viewing the vote results

**Comment by ManfredKarrer** [comment]
Yes that is missing. Shoule be exceptional with mainnet version as 3 days should be enough for reveal. But yes need to be fixed.
