### ISSUE TITLE
Add brazilian portuguese translation

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#2709]
https://github.com/bisq-network/bisq/commit/8b2396e7e29e50a42321f7c9100f4540c63e2d15 removed pt-br (brazilian portuguese) translation since it was incomplete. 

Now pt-br translation is complete again and should be included in bisq.

**Comment by huey735** [comment]
Hi @rhcastilhos. I've been translating pt_pt and pt_br but only reviewing pt_pt. Jump on bisq.slack.com and maybe you can help to review the remaining strings.

**Comment by ripcurlx** [comment]
Sure as soon as it is translated properly again, I'll add it in the next release.
