### ISSUE TITLE
Add mBit support

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#271]
Currently the user can select mBit in the new preferences screen but it is not supported in all screens. We remove the mBit from the selections for now until we have implemented mBit support in all screens.

**Comment by ripcurlx** [comment]
What is meant with mBit support? Is this still relevant?

**Comment by mrosseel** [comment]
maybe it's about using millibitcoin in the screens instead of bitcoin?

**Comment by ManfredKarrer** [comment]
The first comment is outdated. mBit was initially supported in the UI but I dropped support as I did not consider it important and just adds more work to handle all correctly and to test all. Would like to postpone that feature as long as possible to avoid unneeded work.
