### ISSUE TITLE
Allow text input in all currency drop downs

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#2712]
Right now, only when creating a new altcoin account one is able to type the name of the currency to select it from the long drop down options. This option should be expanded to other drop down currency menus in the software.

**Comment by ripcurlx** [comment]
Yes, we could have a look where else it makes sense to add this functionality.

**Comment by ManfredKarrer** [comment]
Yes that would be definitely good to have at all currency drop downs. We have the code in tha altcoin account setup.

**Comment by shamoons** [comment]
I'll take a look and start working on this

**Comment by huey735** [comment]
@shamoons @battleofwizards @ripcurlx 
This function has been added to the all the Market dropdown menus except for the Settings > Preferences.

**Comment by battleofwizards** [comment]
@huey735 yes, that is correct.

The first PR only introduced autocomplete on major tabs to limit the volume of changes.

I intend to apply autocomplete more widely in the application over the coming weeks.
