### ISSUE TITLE
can not edit some open offers in v 1.0.0

### ISSUE THREAD

**Issue by izzytdi** [bisq-network/bisq#2713]
I can not edit any offer made from previous versions so i deleted all offers and recreated new ones.  2 of them i can edit (for amounts of 1 and 2 BTC) but can not edit 2 others (0.1, 0.25 BTC) as the confirm button is disabled for them.  Maybe it only likes integer trades?

**Comment by ripcurlx** [comment]
> I can not edit any offer made from previous versions so i deleted all offers and recreated new ones. 2 of them i can edit (for amounts of 1 and 2 BTC) but can not edit 2 others (0.1, 0.25 BTC) as the confirm button is disabled for them. Maybe it only likes integer trades?

Thanks for reporting it! I can reproduce this issue and I'm working on it right now.

**Comment by ripcurlx** [comment]
l guess we'll have a v1.0.1 release soon 😉

**Comment by ripcurlx** [comment]
This bug was introduced already with 0.9.5, but just became more visible with v1.0.0 as we increased the minimum security deposit. Sorry about that!
