### ISSUE TITLE
DAO, Network Monitor - "UTXO Conflicts"

### ISSUE THREAD

**Issue by remyers** [bisq-network/bisq#2715]
<img width="584" alt="Screen Shot 2019-04-15 at 10 09 07 PM" src="https://user-images.githubusercontent.com/8568892/56162002-43ae3180-5fcb-11e9-9e07-a21a542a084d.png">

I get this error using Bisq 1.0 from the DAO Network Monitor tab. I'm connecting to a local Bitcoind if that makes any difference. It also says along the bottom:
Bitcoin network peers: 1/Synchronized with Bitcoin Mainnet (localhost) / Synchronizing DAO and the green bar is still moving. I'm connected to 11 p2p network peers.

Any ideas what's causing this?

**Comment by remyers** [comment]
After a restart of Bisq 1.0, the error went away.

**Comment by ManfredKarrer** [comment]
Yes we have issues atm that blocks are not propaged enough. Will release a hotfix soon. In the meantime I start more full nodes to more nodes broadcast.
