### ISSUE TITLE
Error Confirming Offer To Buy Bitcoin:  US Postal Money Order

### ISSUE THREAD

**Issue by bucky911** [bisq-network/bisq#2718]
I am receiving a timeout error when Confirming Taking an Offer to Buy Bitcoin using US Postal Money Order. But taking Zelle offers does not timeout.

I attempted several times with different US Postal Money Order offers but all failed. I am running version v0.9.7

I will upgrade to 1.0 and try again.

**Comment by bucky911** [comment]
I upgraded to v.1.0.0 and now when I review Available Offers all the US Postal Money Order offers are disabled (greyed out) even though that is one of my national currency accounts, and I have completed several trades in the past.

**Comment by ghost** [comment]
@bucky911 it may be a temporary issue.
Could you have a look in your logfile if you find some relevant information.

**Comment by ripcurlx** [comment]
> I upgraded to v.1.0.0 and now when I review Available Offers all the US Postal Money Order offers are disabled (greyed out) even though that is one of my national currency accounts, and I have completed several trades in the past.

@bucky911 We have updated the risk factor for some Fiat payment methods with v1.0.0, so it can be that the offer exceeds now your current limit. Please have a look into Account -> National currency accounts -> select your US Postal Money Order account and have a look at the Limitations field.

**Comment by bucky911** [comment]
That was it, my trade limit was 0.125 BTC but now my limitation is:
Max. trade duration: 8 days / Max. trade limit: 0.0625 BTC / Account age: 25 days

When I was timing out I must have been matching an offer by someone who had upgraded to v1.0.0 then after I upgraded those offers were no longer visible.

That explains it, thanks.
