### ISSUE TITLE
Rename "Preferences" to "Settings"

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#272]
@ManfredKarrer, I wonder if we should rename "Preferences" to "Settings" on the main navigation in the UI, and then rename the "Application preferences" tab to simply "Preferences".

The rationale here is that the two tabs currently under the "Preferences" screen are not really both about "Preferences", but they are both about "Settings". i.e. it's natural to think about "looking at my network settings" to see what my external IP address is, and it's natural to think about going to Settings -> Preferences in order to change my BTC denomination, but it's not as natural to think about going to Preferences -> Network to see what my external IP address is, because it's not a "preference" that I can choose or change.

What do you think?

**Comment by ManfredKarrer** [comment]
Yes, I am also not happy with the naming. I wanted to distinguish between the account setttings which are next to account setup. Might change all a bit when get developed further, but for now the suggested renaming makes sense. Do you have bigger merges open? Otherwise i will change it now.

**Comment by cbeams** [comment]
> On Nov 14, 2014, at 1:56 PM, Manfred Karrer notifications@github.com wrote:
> 
> Do you have bigger merges open? Otherwise i will change it now.

I don't. Go ahead.=
