### ISSUE TITLE
BSQ disappearing 

### ISSUE THREAD

**Issue by izzytdi** [bisq-network/bisq#2721]
![dao](https://user-images.githubusercontent.com/45130468/56190493-9b2fba00-602a-11e9-84d4-b494c528f11f.PNG)

Some error here turned my balance to 0. I was not allowed to use my balance to make more trades or use it in any way.  Once I restarted the app the balance came back and all transactions became fixed

**Comment by ghost** [comment]
What version do you use ? What OS ?
Last version available is v1.0.0, released yesterday.

**Comment by izzytdi** [comment]
This is v 1.0.0, using windows 10

**Comment by ripcurlx** [comment]
@izzytdi It looks like your client wasn't fully synced. Atm we still have some problems with the propagation of new blocks when your client is running. Re-starting the client is a workaround in the meantime to sync your DAO state locally again.

**Comment by izzytdi** [comment]
ok, so far a restart has fixed it, ill come back if it goes wrong again
