### ISSUE TITLE
Selling BSQ shows weird fee

### ISSUE THREAD

**Issue by oscarguindzberg** [bisq-network/bisq#2727]
On the "buy btc screen", create an offer to buy btc with bsq.
Leave "amount of btc to buy" empty.
Set fix price to 0.00020000
Set "amount in bsq to spend" to 100000000000 (100 billion).

Expected:
The calculated fee is 10000000 (10 million) bsq.
If you switch to another program, and come back to bisq nothing is changed.

Problem:
The calculated fee is 0.03 bsq.
If you switch to another program, and come back to bisq, "amount in bsq to spend" is set to -84467440737.10 (negative number) and the calculated fee is 1000000 (1 million) bsq.

Environment:
Mac OSX.
Bisq 1.0.0
Mainnet

**Comment by ben-kaufman** [comment]
I'm experiencing a similar issue. @ManfredKarrer if you'd like you can assign me to this issue and I'll try to fix it.

**Comment by sqrrm** [comment]
@ben-kaufman Is there any progress on this issue?
