### ISSUE TITLE
Qwertycoin (QWC) is not shown in add altcoin function

### ISSUE THREAD

**Issue by Xecute0101** [bisq-network/bisq#2738]
Just about to start trading on Bisq but don't see QWC in altcoin selection. Please fix this.

**Comment by ManfredKarrer** [comment]
With v1.0 Assets are delisted if not traded. They can pay a fee in BSQ to get listed for a trial period where trading activity is not used to check listing status.

So one has to pay a fee in BSQ to get the coin listed. That applied to all assets. Either its traded sufficiently or one pay a fee.

<img width="1199" alt="Screen Shot 2019-04-17 at 21 55 11" src="https://user-images.githubusercontent.com/1449498/56333892-9d456600-615b-11e9-9de4-791d3f04aa8a.png">

**Comment by ripcurlx** [comment]
Closing based on https://github.com/bisq-network/bisq/issues/2738#issuecomment-484337177.
