### ISSUE TITLE
Add wiki page to list known working home routers and setup tips

### ISSUE THREAD

**Issue by notmandatory** [bisq-network/bisq#274]
**Goals**
- must list router models + firmware versions successfully used with Bitsquare
- should also list if UPnP or manual port forwarding was used
- should also list any other tips/instructions for using a particular router
- could be community editable wiki page

**Comment by remyers** [comment]
are these the right instructions for manual port forwarding?

1) forward port TCP/UDP for port 7366 on your router to your computer port 7366
2) add flags: --node.port=7366 --node.useManualPortForwarding=true

**Comment by ManfredKarrer** [comment]
yes. maybe also that the internal IP must be defined, and hint how users find that. if there is also a field for the external ip (like in chris router) i think it can be left with 0.0.0.0 (or our seed node ip?).

**Comment by ManfredKarrer** [comment]
Added to wiki page: https://github.com/bitsquare/bitsquare/wiki/How-to-setup-port-forwarding
