### ISSUE TITLE
User experience: confusing message after making a payment

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/bisq#2741]
When I made a payment for my trade, a message appeared that was a little confusing to me.

I later learned that it means that the trader wasn’t online and will receive the message as soon she gets online again.

Suggestion: Rephrase the message to something like this:  
"Message of payment sent but not yet confirmed by peer."

![Confusing message](https://user-images.githubusercontent.com/43150241/56361213-49c42e00-61d6-11e9-808b-b869d9a49448.png)

**Comment by niyid** [comment]
Can I go ahead with this @ripcurlx ? Please assign.

**Comment by niyid** [comment]
Hello. Can I get this assigned please?

**Comment by ripcurlx** [comment]
But maybe it should be more something like "Message of payment sent but not yet received by peer."
@m52go What do you think?

**Comment by niyid** [comment]
Good enough. Thanks.

**Comment by m52go** [comment]
It depends what the exact intention of the message is...is it meant to say "received but not yet seen by peer"? 

Or is this what shows when the peer is offline? In that case maybe it should be something like "message queued until peer is back online".

**Comment by ripcurlx** [comment]
@m52go Normally it should be in the case if the peer was not online and the message was not delivered.

**Comment by niyid** [comment]
Are we going with this:

> "Message queued until peer is back online".

or 

> "Message of payment sent but not yet received by peer."

or 

> "Notification of payment will not be received by recipient until when back online."

Which is easiest to understand?

**Comment by m52go** [comment]
How about: 

"Message sent; queued until peer is back online."

**Comment by niyid** [comment]
OK. So now we have:

>(a) Message queued until peer is back online.

>(b) Message of payment sent but not yet received by peer.

>(c) Notification of payment will not be received by recipient until when back online.

>(d) Message sent; queued until peer is back online.

I call for a vote. I pick (b)

**Comment by m52go** [comment]
@niyid agree. Probably better since reason peer hasn't received yet is more general.
