### ISSUE TITLE
I cannot take the offer - timeout error

### ISSUE THREAD

**Issue by AndersonLugao** [bisq-network/bisq#2744]
[bisq.log](https://github.com/bisq-network/bisq/files/3095668/bisq.log)
![Error](https://user-images.githubusercontent.com/32845502/56382091-ec87a700-61ec-11e9-8e27-2d995e2e8896.png)
![Print screen](https://user-images.githubusercontent.com/32845502/56382092-ed203d80-61ec-11e9-8b26-ae949de43d4c.png)

**Comment by ghost** [comment]
This may be related to the actual scam attempts,
see https://bisq.community/t/urgent-certain-banks-banned-until-further-notice/7420.
Please read it carefully.
If your counter-party is in the mentioned onion list, do not try to trade with.
Idem if it's a young account.

I may well be something else (a technical issue), but atm we prefer to get you on the safe side.
