### ISSUE TITLE
Remove or update "Donate" hyperlink

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#2745]
Under Settings>About there's a "Donate" hyperlink that leads to the same place the "Contribute" does. This should be updated to a current BTC address or removed if Bisq isn't accepting BTC donations.

**Comment by huey735** [comment]
Still relevant

**Comment by devinbileck** [comment]
@m52go can you confirm if there is a page that mentions donating?

**Comment by m52go** [comment]
@devinbileck there is no page in docs or on the website that mentions donating.

Donate and Contribute links in the software both go to the [Contributor Checklist](https://docs.bisq.network/contributor-checklist.html) doc. At the least, the Donate link should be removed. 

Might be a good idea to go a step forward and add a small line encouraging developers to contribute, etc. Could think of some text and make a PR if desired.

![Screenshot from 2019-10-28 16-01-30](https://user-images.githubusercontent.com/735155/67713485-43d8b200-f99c-11e9-9f62-30d41110c0bb.png)

**Comment by devinbileck** [comment]
Thanks. For now will just remove it.
