### ISSUE TITLE
task failed

### ISSUE THREAD

**Issue by Tharrso** [bisq-network/bisq#2747]
Just tried to purchase BTC and got a "task failed" error. Here's the log.
[bisqlog.txt](https://github.com/bisq-network/bisq/files/3096159/bisqlog.txt)

**Comment by ghost** [comment]
Your logfile says:
<pre>
The peers trade limit is less than the traded amount.
tradeAmount=0.1246 BTC
Peers trade limit=0.0625 BTC 
Apr-18 13:51:16.638 [JavaFX Application Thread] ERROR b.c.t.TaskRunner: Task failed: VerifyPeersAccountAgeWitness / errorMessage: An error occurred at task: VerifyPeersAccountAgeWitness
The peers trade limit is less than the traded amount.
</pre>
This may be related to the scams attempts atm, and the scammer trying to cheat on his account age.
Most safe imo is to abandon this trade and also to avoid trading with the involved onion until further notice.

**Comment by clearwater-trust** [comment]
I just received the same error:

````
Apr-19 15:56:30.581 [JavaFX Application Thread] WARN  b.c.p.AccountAgeWitnessService: The peers trade limit is less than the traded amount.

tradeAmount=0.1249 BTC

Peers trade limit=0.0625 BTC

Apr-19 15:56:30.581 [JavaFX Application Thread] ERROR b.c.p.AccountAgeWitnessService: verifyPeersTradeLimit failed: peersPaymentAccountPayload
``` `

**Comment by m52go** [comment]
This looks the same as https://github.com/bisq-network/bisq/issues/2716.

**Comment by ghost** [comment]
Yes.
Probably related to Peers trade limit being halved due to running scam.
For what I understand, for those (old) orders :
- either delete them
- either return to a pre v1.0.1 Bisq version to get the ability to edit them.
Deleting may be the simplest.

**Comment by clearwater-trust** [comment]
All of my pre 1.0.0 offers need to be deleted? Do I understand correctly? I'd rather not sacrifice the fee, but if they cannot be selected, then I will delete them. Thanks.

**Comment by ripcurlx** [comment]
> All of my pre 1.0.0 offers need to be deleted? Do I understand correctly? I'd rather not sacrifice the fee, but if they cannot be selected, then I will delete them. Thanks.

It depends on the current risk level your payment methods are in. Which ones do you have problems with? We applied new high risk levels to most of the fiat payment methods which means they can't be higher than 0.25 atm.

**Comment by ripcurlx** [comment]
If your offers are below or equal to 0.25 BTC, users with an account age >= 2 months can take them again. Unfortunately it is not possible right now to change the amount of your existing offer. You could also deactivate your offers for now to see if we are able to increase the limits again in the future when the new fighting-scam-strategies are deployed and working.
