### ISSUE TITLE
lost in migration from 0.9.3 to 1.0.1

### ISSUE THREAD

**Issue by littlebit2big** [bisq-network/bisq#2751]
I run Bisq from a live usb linux session and backup to usb. My last backup was 0.9.3. We are now on 1.0.1. It won't take my pw (which I had written down) in either version  and used many times before. Using seeds (bisq freezes for like 3-4 min during word entry), I got warning that my wallet is not empty but could not get in to empty it first. I'm 99.9% certain I finalized my last trade.  I clicked Restore Anyway. It wanted me to restart (then froze again) but also said i need to create a new pw since I was encrypted. Stuck. Oh, also, I get "no such file or dir" when clicking the button to open the bisq.log and there isn't one there now. it didn't generate a log file like the error message said (pointing to the working dir). I don't want to lose my coin.

**Comment by ManfredKarrer** [comment]
I assume there is an issue with your setup. Can you run it from a normal location (no USB)?
Restore from seed can take a while for old wallets, just let it running until complete even if CPU is on 100%. SPV chain sync takes all processing power....

**Comment by littlebit2big** [comment]
Thanks! I was able to recover wallet after running from non-live-usb-OS. However, it isn't clear in which order I should recreate a pw and perform a backup. It looks like seeds for a wallet will never change but how do I get the future backups to be encrypted? It says mine is not.

**Comment by ghost** [comment]
@littlebit2big wrote
> how do I get the future backups to be encrypted? 

It is the setting of a password which provokes the encryption.

Of course, it is recommended to make a backup of your data directory before.
(It's always good politic to make backups).
