### ISSUE TITLE
Customizable browser command line

### ISSUE THREAD

**Issue by PabloWong** [bisq-network/bisq#2759]
https://github.com/bisq-network/bisq/blob/f36823f145a21f7046435b0496a2560b9980bb29/common/src/main/java/bisq/common/util/DesktopUtil.java#L35

I wouyld like to choose which browser to execute, so I would be able to run torbrowser to open the blockexplorer.
Everything is torified, but when I click on a transacion or an address, my privacy get loss.!!!!

**Comment by alexej996** [comment]
I think there is a popup warning users that if Tor browser is not their default browser they should just copy the URL and open in a Tor browser manually.

**Comment by ripcurlx** [comment]
@PabloWong If you confirmed opening weblinks it in your standard browser once it will be saved as a configuration and the popup not shown again. You can reset all your hidden popups by going to Settings > Preferences > Reset all "Don't show again " flags (scroll down in the preferences screen to find this button). After that you should be asked again every time you click on a weblink.
