### ISSUE TITLE
Error at traderSignAndFinalizeDisputedPayout , Then can no longer take offer

### ISSUE THREAD

**Issue by claimlu** [bisq-network/bisq#2760]
I guess what happened was, I took an order, sent coins to the given address, when clicked reviewed order it says offer not available, saying the worst case I would lose my bond or something something, then I moved the coins into bisq wallet. And then somehow this trade went into support/dispute. Then it disappeared, but I got this pop up while using the app. And another side effect is I can no longer take any offers, saying peer offline, cannot connect to market maker something something. It happens to every offer for 2 days now so I'm convinced that because of this pop up error that causes the latter issue.

**Comment by alexej996** [comment]
Consider withdrawing your coins and removing your data directory (after a backup of course).
