### ISSUE TITLE
Security deposit in the offer details screen

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#2761]
In the offer details popup, the security deposit is presented as 
<code>Security deposit : Buyer: n BTC / Seller: m BTC</code>

Maybe it could be more clear as
<code>Security deposit : Maker: n BTC (%) / Taker: m BTC (%)</code>

Mentioning the deposit percentage could also help favouring makers with higher deposits.
Which could help the transition with the new protocol.

**Comment by meapistol** [comment]
Good suggestion. A security deposit higher than 100% could signal that the traders will not use arbitration. There will be very weak (but not zero) incentives for blackmail if the blackmailer can lose more than the trade amount.

**Comment by ManfredKarrer** [comment]
If security deposit is very high disputes can become more difficult as users prefer to not tell the full truth if they risk to lose it. Also trying to argue to deserve the peers deposit might become more troublesome.

**Comment by fresheneesz** [comment]
`n BTC (%)` is not clear to me. Would that read "5 BTC (%)"? What is that? 5%? 

`5% (0.001 BTC)` would be much clearer to me if that's what it would mean.

**Comment by fresheneesz** [comment]
Is this ticket talking about this pop up?:

![bisqofferdetailpop](https://user-images.githubusercontent.com/149531/61999261-e61d8c80-b071-11e9-887c-918002a331ae.png)

If so, it looks pretty clear to me, maybe this has been fixed at this point?
