### ISSUE TITLE
Right-to-Left language compatibility

### ISSUE THREAD

**Issue by initCCG** [bisq-network/bisq#2762]
As some know, the full Persian interface was translated and released several versions ago.
Since then, our tester found that "some texts are really
messed up in absence of RTL".

The needed changes for Right-To-Left compatibility have been completed, and a PR is forthcoming.

**Comment by ripcurlx** [comment]
Do I understand it correctly, that some texts are rendered correctly from right to left and some not or that it is not working at all? If there is just a problem with some translations it would be great to point out two keys of working and not working ones so I can have a look at the difference.

**Comment by initCCG** [comment]
As we understand, the strings that have a mix of English and Persian were not showing right, until the changes in above PR.

**Comment by freimair** [comment]
still relevant
