### ISSUE TITLE
Offer couldnt be taken

### ISSUE THREAD

**Issue by dunkfan** [bisq-network/bisq#2785]
`An` error occurred when taking the offer.

A timeout occurred.

No funds have left your wallet yet.
Please try to restart your application and check your network connection to see if you can resolve the issue.
[bisq.log](https://github.com/bisq-network/bisq/files/3119081/bisq.log)
Please try to restart your application and check your network connection to see if you can resolve the issue.

**Comment by ripcurlx** [comment]
@dunkfan Did this happen to you once when you tried to take this specific offer or every time and for any offer you tried to take?
```
Apr.-26 00:26:04.625 [JavaFX Application Thread] ERROR b.c.o.a.OfferAvailabilityProtocol: AckMessage for OfferAvailabilityResponse failed. AckMessage=AckMessage{
     uid='672afa79-3bc8-4d81-9951-ea003cd8d5b8',
     senderNodeAddress=klgpg3m7xu36yqkd.onion:9999,
     sourceType=OFFER_MESSAGE,
     sourceMsgClassName='OfferAvailabilityResponse',
     sourceUid='c39f4490-f2ec-462f-9277-9e9b8e3dfde8',
     sourceId='86436211-4d14de04-ed77-4d58-bb44-6f5270cfb1ad-101',
     success=true,
     errorMessage='null'
} NetworkEnvelope{
     messageVersion=10
}, makersNodeAddress=rczscnooqxftn2zo.onion:9999, errorMessage=We did not send the EncryptedMessage because the peer does not support the capability. 
Apr.-26 00:26:13.526 [AbstractTimeoutHandler timeouts] INFO  o.b.c.PeerSocketHandler: [r3dsojfhwcm7x7p6.onion]:8333: Timed out 
Apr.-26 00:26:13.526 [BlockingClient network thread for r3dsojfhwcm7x7p6.onion:8333] ERROR o.b.n.BlockingClient: Error trying to open/read from connection: r3dsojfhwcm7x7p6.onion:8333: Connect timed out 
Apr.-26 00:26:13.533 [AbstractTimeoutHandler timeouts] INFO  o.b.c.PeerGroup: [r3dsojfhwcm7x7p6.onion]:8333: Peer died      (8 connected, 0 pending, 9 max) 
Apr.-26 00:26:13.540 [BlockingClient network thread for r3dsojfhwcm7x7p6.onion:8333] INFO  o.b.c.PeerGroup: [r3dsojfhwcm7x7p6.onion]:8333: Peer died      (8 connected, 0 pending, 9 max)
```
It looks like there was a connection problem with your trading peer. Was the offer still available in the offer book after the error? It might be the case that the peer just stopped the client.

I also saw following warnings regarding the deposit transaction. Not sure if this is something that can be ignored in that case. 
```
Apr.-26 00:27:23.655 [JavaFX Application Thread] WARN  b.c.trade.Trade: depositTx is null 
Apr.-26 00:27:23.671 [JavaFX Application Thread] WARN  b.c.trade.Trade: depositTx is null
```
Either the deposit transaction wasn't created or the `depositTxId` or `takeOfferDate` was null. As the takeOfferDate is initialized in the constructor it is probably the depositTxId that was null in that case. 

@ManfredKarrer Is it the case if the deposit transaction is never sent out that it will be reseted on time out and creates this kind of warning. Just to be sure we are not overlooking some issue.

**Comment by ManfredKarrer** [comment]
@dunkfan What is your banks country?

**Comment by ManfredKarrer** [comment]
Please also update to latest version 1.0.1.

**Comment by marian001** [comment]
This issue happened to me as well. I'm on version 1.0.1. Attaching log file.
[bisq.log](https://github.com/bisq-network/bisq/files/3124281/bisq.log)

**Comment by ManfredKarrer** [comment]
@marian001 Which country is your bank?

**Comment by ManfredKarrer** [comment]
Some countries are blocked atm due to chargeback scams. See https://bisq.community/t/urgent-certain-banks-banned-until-further-notice/7420/

**Comment by marian001** [comment]
> @marian001 Which country is your bank?

Germany

**Comment by ManfredKarrer** [comment]
German banks are banned atm due to the chargeback issues. With next version we add more protection tools and we will unblock it afterwards.
