### ISSUE TITLE
Multiple attempts to take two "Buy BTC" offers - always timeout

### ISSUE THREAD

**Issue by iotatau** [bisq-network/bisq#2786]
My last "buy" transaction on March 12 had been successful. Today multiple "buy" attempts with Bisq v0.9.7 failed. I am uploading the error log for the time after I had rebooted the PC after the first few timeout errors. Fast network connection (xxx Mbps), no local Bitcoin node running, Tor browser is working fine.
[bisq.log](https://github.com/bisq-network/bisq/files/3124058/bisq.log)

**Comment by ghost** [comment]
Last Bisq release is v1.0.1.
So please close everything you can close.
Make backups.
And with everything well closed, update to last version.

**Comment by iotatau** [comment]
Thank you for your comment. The application had not alerted to the new version.
I have upgraded to v1.0.1 successfully, rebootet the device, next buy attempt - timeout. Log:
[bisq2.log](https://github.com/bisq-network/bisq/files/3124096/bisq2.log)

**Comment by ghost** [comment]
There was indeed an issue concerning alerting about new version.
(which is or will be solved with next version).
Thanks for the logfile, but is your error still there, or not ?

**Comment by iotatau** [comment]
Yes, as mentioned (" - timeout") I had obtained a timeout after the upgrade. Just now, for this message, I have tried to take a third offer, again a timeout.

**Comment by sejktmcsdlmfhsc** [comment]
Hi, there, same issue on my side(bisq 1.0.1):
timeout on taking the offer. in the log it says:
`WARN  bisq.core.trade.Trade: depositTx is null`

**Comment by ManfredKarrer** [comment]
@iotatau Is it always the same offer or different ones? Can you post the offer details (currnety, payment method, buy or sell, price? Can you post your onion address?

**Comment by iotatau** [comment]
Hi @ManfredKarrer Thanks for tuning in. I have tried three different offers, each one multiple times.
My onion address is vw7sbw37esoexacy.onion:9999
I have just obtained another timeout for offer 27829132-3bf18a84-5d59-42b2-be83-bc86004cda0c-101
All attempts were in the "Buy BTC" section with EUR.

**Comment by ManfredKarrer** [comment]
Which country is your bank account?

**Comment by iotatau** [comment]
Germany. - If you have an option to switch on tracing I could try another attempt for a defined offer.

**Comment by ManfredKarrer** [comment]
That falls into the blocked countries and that is why you get rejected by the peer and that causes a timeout. We are working on a release with more protection against that chargeback scammer and then we can release the ban again. Please wait 1-2 weeks until that is out.

**Comment by iotatau** [comment]
Thank you for clarifying.

All the best.

**Comment by sejktmcsdlmfhsc** [comment]
Dear @ManfredKarrer could you explain the "blocked countries"? 
Or is there a discussion/FAQ on the bisq forum where I can read about it?
Does the blocking come from bisq client?
In my case it was also EUR - DE.
Thank you!

**Comment by iotatau** [comment]
@sejktmcsdlmfhsc Meanwhile I have discovered this comment in the Bisq forum:
https://bisq.community/t/urgent-certain-banks-banned-until-further-notice/7420/36

**Comment by sejktmcsdlmfhsc** [comment]
thank you so much @iotatau !
