### ISSUE TITLE
Add more info for altcoin instant

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/bisq#2790]
It was not fully clear to me that I had to respond to peer taking my offer within an hour of them taking it. It happened when I was asleep so the trade did not go through and a dispute was opened. I think the software should be more explicit in telling the users that they need to respond to peers within one hour of peer taking their offer.

**Comment by m52go** [comment]
Not stale. Seems like a good first issue for a new UI-oriented developer.

**Comment by ghost** [comment]
... probably more important to highlight with instant trade is to use appropriate fees.

**Comment by m52go** [comment]
Yes, that is certainly an issue too. But people cannot choose, right? The software does it automatically? For deposit transaction I mean.

**Comment by ghost** [comment]
Yes. Indeed. As far as I remember there is a part that you can touch, and a bigger part which is decided by the software (and probably difficult to tune properly).
