### ISSUE TITLE
Listing request for Note Blockchain

### ISSUE THREAD

**Issue by NoteBC** [bisq-network/bisq#2792]
Please fill in the following data to request for a new asset to be listed on Bisq. For more details, be sure to read [the full documentation](https://docs.bisq.network/exchange/howto/list-asset.html) on adding a new asset.

### 1. Asset name
Note Blockchain

### 2. Ticker
_Your asset's ticker must not conflict with any national currency tickers (per [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)) or any of the [top 100 cryptocurrency tickers](https://coinmarketcap.com/coins/)._
NTBC

### 3. Block explorer URL
_Your asset's block explorer must be active and publicly available so that transactions can be verified with a receiver's address...if this isn't possible, [see workarounds here](file:///home/steve/wb/bisq/bisq-docs/build/asciidoc/html5/exchange/howto/list-asset.html#arbitrators-must-be-able-to-look-up-transactions-in-the-asset-block-explorer)._
http://explorer.notebc.io/

### 4. Additional technical requirements (yes/no)
_Your asset should not have any additional requirements (for example, needing input fields for anything other than an address)._
No

### 5. Initial coin offering (yes/no)
_Bisq will not list your token if it has taken part in an initial coin offering (ICO)_
No

**Comment by NoteBC** [comment]
Website: www.notebc.com
ANN: https://bitcointalk.org/index.php?topic=5097914.0
Discord: https://discord.gg/YDy42Ks
Twitter: https://twitter.com/BlockchainNote
https://twitter.com/BlockchainNote
iOS app: https://itunes.apple.com/us/app/note-blockchain/id1453956833?ls=1&mt=8
Android app: https://play.google.com/store/apps/details?id=com.crypto.notes&hl=en

**Comment by NoteBC** [comment]
Do you need any additional info in order to process this request?

**Comment by blabno** [comment]
Is it privacy coin like monero?
Is it fork of any other coin?
What are the wallet address validation rules?

**Comment by NoteBC** [comment]
-It is not a privacy coin, all transactions are viewable on the block explorer.
-It's not a fork, but the code is based on litecoin. 
-Validation can be checked via: /^[N][a-km-zA-HJ-NP-Z1-9]{26,33}$/

Git is here: https://github.com/NoteBC/NoteBlockchain

**Comment by blabno** [comment]
You will need a developer to create pull request with necessary code changes.
If you can't find anyone the contact me on Bisq slack (@bernard).
