### ISSUE TITLE
Can't take offer several times - SEPA

### ISSUE THREAD

**Issue by yourwpguy** [bisq-network/bisq#2794]
I did restart application several times.
Log file attached.
[bisq-3.log](https://github.com/bisq-network/bisq/files/3132953/bisq-3.log)

**Comment by yourwpguy** [comment]
Germany is the country of my bank.

**Comment by ManfredKarrer** [comment]
Ok, thats the reason then. We blocked German (and other) banks because of the chargeback scammer. 
See: https://bisq.community/t/urgent-certain-banks-banned-until-further-notice/7420/

**Comment by ManfredKarrer** [comment]
Open a dispute with cmd+o or ctrl+o if the trade is still open.

**Comment by yourwpguy** [comment]
Trade is failed. And the other trader was banned. I think we can delete this ticket.
