### ISSUE TITLE
Failure to open *any* support ticket from within bisq.  Dialog opened with crtl+o just closes after clicking on “OPEN SUPPORT TICKET”.

### ISSUE THREAD

**Issue by nacknacknock** [bisq-network/bisq#2795]
Note that even though that this issue was raised in a similar context, it _differs_ from https://github.com/bisq-network/bisq/issues/2788 in two regards:

1. It is not possible to open _any_ support ticket.
2. Evidence suggests that it _may_ not be limited to the context of stuck trades before step 1.

Description:
1. After pressing crtl+o while navigated to "PORTFOLIO"/"OPEN TRADES" the "Open support ticket"-dialog window appear.
2. After clicking the button "OPEN SUPPORT TICKET", the dialog window disappears and the user is back at the main screen of the application.
3. No other dialog appears.

Context:
- The problem has been reported by at least three different users:
https://bisq.community/t/trade-stuck-before-step-1/7245/6
https://bisq.community/t/trade-stuck-before-step-1/7245/14
https://bisq.community/t/trade-stuck-before-step-1/7245/30
- The problem _could_ be independent of the "trade-stuck-before-step-1"-phenomenon, since one of the affected users _seems_ to report it at another step of the trade process.  
- Bisq versions: 0.9.5 and 1.0.1.
- OS: Linux and OSX.
- The log file shows the following error just right after unsuccessfully trying to open the support ticket:
```
May-01 16:47:31.069 [JavaFX Application Thread] INFO  b.d.m.p.p.PendingTradesDataModel: Trade.depositTx is null. We try to find the tx in our wallet. 
May-01 16:47:31.069 [JavaFX Application Thread] ERROR b.d.m.p.p.PendingTradesDataModel: Trade.depositTx is null and we did not find any MultiSig transaction. 
```

Further thoughts:
- Is it possible that this problem only occurs, when the user did not have any other successful trades in the past?

**Comment by ripcurlx** [comment]
@nacknacknock The dispute is not opened as the there seems to be no deposit tx available. Could you please retry it with v1.1.0 and print the error logs that you might get there?
A couple of additions have been added to this part of the code with v1.1.0 that either solves or would help us to find the root cause of this problem.

**Comment by nacknacknock** [comment]
I've installed 1.1.0 and now magically I'm able to open support tickets!
The problem seems to be solved.

**Comment by ManfredKarrer** [comment]
Yes we fixed an issue there....No magic just code ;-)
