### ISSUE TITLE
Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@35ae73d5, [B@5047f5f9, [B@34927872]

### ISSUE THREAD

**Issue by marian001** [bisq-network/bisq#2796]
This error came at me. I guess resulting from the closed dispute.. 

[bisq.log](https://github.com/bisq-network/bisq/files/3135281/bisq.log)

**Comment by ManfredKarrer** [comment]
What is the trade ID?

**Comment by ManfredKarrer** [comment]
If there was no taker fee tx created that is expected. No deposit tx and therefore no payout tx.

**Comment by marian001** [comment]
> 
> 
> What is the trade ID?

Offer ID is VREVUVZ-0972b89c-576a-4106-a824-ddd8a5c579f3-101

Maker fee: 592d126d96aeb12516329885ada76c0bfff8c5d45113f7d49eadb5b565a7aa55

Deposit transaction: a67bb5c84f0b813c202749856e4c24cb72098793a0f040392309b8fdd87e2456

**Comment by ripcurlx** [comment]
Closing as complete as by https://github.com/bisq-network/bisq/issues/2796#issuecomment-488351306. @marian001 If you still have a problem with this dispute please re-open this issue again.
