### ISSUE TITLE
Cannot edit offer: after a few edits of the "sell BTC" offer, the BTC amount has increased

### ISSUE THREAD

**Issue by gordonel** [bisq-network/bisq#2798]
From https://bisq.community/t/glitch-fixed-amount-of-btc-increased-from-0-0624-to-0-0626-after-a-few-edits-of-the-sell-btc-offer-editing-is-no-longer-available/7565

Summary: after a few edits, the BTC amount in a "sell" offer increased from 0.0624 to 0.0626 and editing became unavailable.

I noticed that when I enter the first four digits in the “fixed price in EUR for 1 BTC” field and then click outside of the text field, the amount of BTC shifts. It shifts in both directions and I haven't noticed a pattern. Still, the “confirm” button is greyed out and I disabled the offer for the time being. It’s starting to look more and more like a bug to me.
![Screenshot from 2019-05-02 15-46-53](https://user-images.githubusercontent.com/45173186/57076325-0d262580-6cf2-11e9-8daf-9508930572e6.png)
![Screenshot from 2019-05-02 15-46-59](https://user-images.githubusercontent.com/45173186/57076326-0dbebc00-6cf2-11e9-8b5d-a90677c97d5d.png)
![Screenshot from 2019-05-02 15-47-38](https://user-images.githubusercontent.com/45173186/57076327-0dbebc00-6cf2-11e9-80fa-9bd4f29fcd66.png)

**Comment by ripcurlx** [comment]
@goraelec Actually you shouldn't be able to edit this offers at all as I assume they have a deposit set that is not in consensus with the new restrictions applied in 1.0.0. Could you please try to edit them in 1.1.0? If my assumption is correct you'll now get now an information popup instead.

**Comment by gordonel** [comment]
@ripcurlx , I got the popup and I deleted the offer and created a similar one anew. If I switch from % to fixed price for BTC, I'm still able to recreate this issue
![Screenshot from 2019-05-03 18-23-47](https://user-images.githubusercontent.com/45173186/57147724-e7bc1900-6dd0-11e9-9da8-d53ca7c527e6.png)
![Screenshot from 2019-05-03 18-23-51](https://user-images.githubusercontent.com/45173186/57147725-e7bc1900-6dd0-11e9-9e8a-6bf8e5b79bc5.png)
![Screenshot from 2019-05-03 18-23-58](https://user-images.githubusercontent.com/45173186/57147726-e7bc1900-6dd0-11e9-9dbe-1463a63864e3.png)

**Comment by gordonel** [comment]
@ripcurlx bumping this one.

So the issue appears to occur whenever the amount of fiat to receive gets rounded up. This also occurs when creating an offer. To reproduce:
1. Create a sell offer with the following parameters: 0.01 BTC amount, 9500 fixed price (any currency, I'm using EUR)
2. change the fixed price to 9550 and observe

You will see that the amount will jump from 0.01 to 0.0101.

Moreover, if you edit an offer that has different min and max trade amounts, both of them will change to the wrong max amount. We need this fixed

**Comment by gordonel** [comment]
@ripcurlx bump again.

I just had to delete two offers because of this bug since I couldn't edit them without making them unusable

**Comment by ripcurlx** [comment]
@gordonel I'll have a look at this soon - thanks for keep on bumping 😉
