### ISSUE TITLE
Incorrect peer account age is shown in portfolio view

### ISSUE THREAD

**Issue by leshik** [bisq-network/bisq#2799]
The history tab in portfolio shows my own trading account age in tooltips for all trades instead of the trading peers ones. The color of the avatar circle is also wrong. I don't have open trades right now, but I'm pretty sure I've seen it incorrect on both `open` and `history` tabs.

**Comment by ghost** [comment]
Which Bisq version do you use ?

**Comment by leshik** [comment]
@HarryMacfinned latest, v1.0.1 (because what’s the point of using an old version?)

**Comment by ghost** [comment]
From time to time we see users with quite old versions (and also some users compiling from sources).

I have also Bisq v1.0.1 (on Debian), and I cannot reproduce your issue.
In fact, I see nobody's account age, nor mine.

Why do you say that the colors of the avatar circle are wrong ?

If you could join a screencopy, it could help.

**Comment by leshik** [comment]
Well, I wouldn’t want to post my trading peers onion addresses. I feel this might be not a good idea from the privacy perspective.

I’m on macOS, but I believe it should be the same on Linux. When you hover the mouse on the avatar of your trading peer, it shows the tooltip with his onion address and his account age. The circle around avatar has the orange color for accounts newer than 30 days, blue for those who are 30-60 days old, and green for older than 2 months. This works in trading view, but not in portfolio.

**Comment by ghost** [comment]
You are right. I got it.
Thanks for reporting. This is a question for the UI specialist @ripcurlx (ping).
Thanks.

**Comment by devinbileck** [comment]
This may have already been resolved by #2753, which will be available in the next release.

**Comment by ripcurlx** [comment]
Which might go live within the next couple of hours 😉

**Comment by ripcurlx** [comment]
Should be fixed in https://github.com/bisq-network/bisq/releases/tag/v1.1.0. Please re-open if this issue still exists for you.
