### ISSUE TITLE
Never ending "awaiting blocks"

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#2800]
Sometimes, for whichever reason, the synchronizing DAO step never ends.
The appli is stucked on "awaiting block" and it doesn't change, even waiting an hour.

Would it be interesting/possible that the appli itself takes notice of being stucked, and suggests restarting ?
It's noticeable that the appli correctly updates the number of the last block.
So the appli could see that the gap is only growing between the last verified block (stucked) and the growing number of blocks.

related (or maybe) to:
- https://github.com/bisq-network/bisq/issues/2781
- https://github.com/bisq-network/bisq/issues/2666
- https://github.com/bisq-network/bisq/issues/2547

I catched this in the CLI:
<pre>
mai-02 19:37:11.936 [TorControlParser] DEBUG o.b.netlayer.tor.Tor: CircuitStatus: 383 BUILT $063BD3BF8C110617E7CA09C96C0EDC0270329F0B~bauruine66,$6D72E970EB5218702C854BE250EC0663CC14D9BD~argus,$91C67730FF602E14702724EA790A56376714CDD5~buttercup 
mai-02 19:37:12.294 [TorControlParser] DEBUG o.b.netlayer.tor.Tor: CircuitStatus: 384 EXTENDED $063BD3BF8C110617E7CA09C96C0EDC0270329F0B~bauruine66,$334DF2164322B98FCC567BC444947B74AC92DAEA~tortillero,$E37724D8AD87B149EAD2F3DFD3E1681624AC9EE0~sheldon,$126B4C9F0964D7F68467D2CD641528BEACF89977~hellzone 
mai-02 19:37:12.295 [TorControlParser] DEBUG o.b.netlayer.tor.Tor: CircuitStatus: 384 BUILT $063BD3BF8C110617E7CA09C96C0EDC0270329F0B~bauruine66,$334DF2164322B98FCC567BC444947B74AC92DAEA~tortillero,$E37724D8AD87B149EAD2F3DFD3E1681624AC9EE0~sheldon,$126B4C9F0964D7F68467D2CD641528BEACF89977~hellzone 
mai-02 19:37:12.713 [TorControlParser] DEBUG o.b.netlayer.tor.Tor: CircuitStatus: 385 LAUNCHED  
mai-02 19:37:12.870 [TorControlParser] DEBUG o.b.netlayer.tor.Tor: CircuitStatus: 385 EXTENDED $063BD3BF8C110617E7CA09C96C0EDC0270329F0B~bauruine66 
mai-02 19:37:13.064 [TorControlParser] DEBUG o.b.netlayer.tor.Tor: CircuitStatus: 385 EXTENDED $063BD3BF8C110617E7CA09C96C0EDC0270329F0B~bauruine66,$4FDDFAD51B24DDABB62FB59071F4DC421E76C685~FissionEx3 
mai-02 19:37:13.139 [TorControlParser] DEBUG o.b.netlayer.tor.Tor: CircuitStatus: 384 CLOSED $063BD3BF8C110617E7CA09C96C0EDC0270329F0B~bauruine66,$334DF2164322B98FCC567BC444947B74AC92DAEA~tortillero,$E37724D8AD87B149EAD2F3DFD3E1681624AC9EE0~sheldon,$126B4C9F0964D7F68467D2CD641528BEACF89977~hellzone 
mai-02 19:37:13.264 [TorControlParser] DEBUG o.b.netlayer.tor.Tor: CircuitStatus: 385 EXTENDED $063BD3BF8C110617E7CA09C96C0EDC0270329F0B~bauruine66,$4FDDFAD51B24DDABB62FB59071F4DC421E76C685~FissionEx3,$3F30E3887FA39352D605BEE7A28597A88C08B5B6~Unnamed 
mai-02 19:37:13.264 [TorControlParser] DEBUG o.b.netlayer.tor.Tor: CircuitStatus: 385 BUILT $063BD3BF8C110617E7CA09C96C0EDC0270329F0B~bauruine66,$4FDDFAD51B24DDABB62FB59071F4DC421E76C685~FissionEx3,$3F30E3887FA39352D605BEE7A28597A88C08B5B6~Unnamed 
mai-02 19:37:13.712 [TorControlParser] DEBUG o.b.netlayer.tor.Tor: CircuitStatus: 386 LAUNCHED  
mai-02 19:37:13.805 [TorControlParser] DEBUG o.b.netlayer.tor.Tor: CircuitStatus: 386 EXTENDED $063BD3BF8C110617E7CA09C96C0EDC0270329F0B~bauruine66 
mai-02 19:37:14.195 [TorControlParser] DEBUG o.b.netlayer.tor.Tor: CircuitStatus: 386 EXTENDED $063BD3BF8C110617E7CA09C96C0EDC0270329F0B~bauruine66,$C7B6A1B76B6476DB3DA8C960E262CC7425B5C5F8~flaus 
mai-02 19:37:15.694 [TorControlParser] DEBUG o.b.netlayer.tor.Tor: CircuitStatus: 386 EXTENDED $063BD3BF8C110617E7CA09C96C0EDC0270329F0B~bauruine66,$C7B6A1B76B6476DB3DA8C960E262CC7425B5C5F8~flaus,$7647B0E5163D06F98F9D49562B5B6DBEFA5DB63E~nodvrelay04 
mai-02 19:37:15.695 [TorControlParser] DEBUG o.b.netlayer.tor.Tor: CircuitStatus: 386 BUILT $063BD3BF8C110617E7CA09C96C0EDC0270329F0B~bauruine66,$C7B6A1B76B6476DB3DA8C960E262CC7425B5C5F8~flaus,$7647B0E5163D06F98F9D49562B5B6DBEFA5DB63E~nodvrelay04 
mai-02 19:37:15.880 [JavaFX A
</pre>

**Comment by traderp** [comment]
Similar problem here, I haven't been able to take a trade yet. It seems like the DOA never connects. I waited hours and even overnight. Here is what I see on the screen. I can post a trace as well if it's helpful.
![Screenshot_2019-05-02_17-36-56](https://user-images.githubusercontent.com/50040139/57095324-1ae3a700-6d02-11e9-9cb1-05c47244c199.png)

I'm using a TOR proxy, here the startup command: `./bisq-desktop --torControlPort 9051 --torControlPassword mypassword --socks5ProxyBtcAddress=127.0.0.1:9050 --useTorForBtc=true --logLevel=TRACE `. I'm building from release bdf163ca2.

**Comment by ghost** [comment]
It's not exactly similar. In my case, the appli is stucked on step (3/4).
And generally, simply restarting the appli solves the problem.

**Comment by traderp** [comment]
I did that several times. I even tried rebuilding from master and the latest release. I can try building from an earlier release if you have one to suggest. Please let me know if posting the logs is useful. I can either post a full trace or filter it based on your recommendation.

**Comment by ghost** [comment]
My small understanding is such issues are often related to the connection quality.
Bisq is a bit greedy, especially on startup.
So if your connection cannot deal with it ... there's few to do (apart getting a better connection).

**Comment by traderp** [comment]
That is an interesting assumption. I do have broadband internet. There must be some ways to validate this assumption by analyzing the logs. What class do you suggest that I trace? What do you figure it is trying to synchronize, the Bitcoin network or the Bisq order book with other peers? I disabled the DAO and still getting the same issue. This issue seems to occur only when using a SOCKS5 Tor proxy.

**Comment by ghost** [comment]
There may be some issue with your tor usage.
But I'm not qualified enough to help.
Maybe @freimair (ping) is more knowledgeable ?

**Comment by ripcurlx** [comment]
@traderp Could you try if this is fixed with [v1.1.0](https://github.com/bisq-network/bisq/releases/tag/v1.1.0)? If not, please let me know and we'll have a closer look.

**Comment by traderp** [comment]
No luck after the upgrade. I have the exact same problem. Here is more info about my config: https://www.whonix.org/wiki/Bisq . Do you want some logs?

**Comment by adrelanos** [comment]
See also discussion in Whonix forums:
https://forums.whonix.org/t/bisq-the-p2p-exchange-network/4953

**Comment by devinbileck** [comment]
This should be fixed with https://github.com/bisq-network/bisq/pull/2821
