### ISSUE TITLE
Add chat system for traders communcation 

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2805]
Once the trade has started the peers should have the ability to communicate with each other via a Bisq internal chat system (same as used in arbitration).

It requires clear rules and the ability to ignore communication if user prefers.
Any violation of the rules (e.g. trying social engineering scam) will lead to a dispute where the violating peer risks to lose his security deposit.
 
With the messaging system in place it would be handy if the buyer could release the btc to the seller also, in case the buyer is unable to pay for some reason.

**Comment by meapistol** [comment]
The chat is a first step towards arbitration. If the traders cannot resolve their differences they can open a dispute. I think that if messaging has started there should be no automatic opening of a dispute. I can easily imagine situations (e. g. bank holidays) where payments come late but there is no reason for arbitration.

**Comment by meapistol** [comment]
I propose (as a interim solution) that a field in the account-data is created, where traders can put their email. Offers from such accounts should have a special symbol/name such that the taker knows he can communicate with the maker. This change is not very heavy to implement and make trading independent of arbitration (in particular if the trading window is made long for these accounts). The offer should preferably show if the maker deposit is above a certain threshold. A high deposit shows that the maker is committed to complete the trade and is unlikely to use a false email. 

The present arbitration system depends on trust and will not survive long with few arbitrators. One rogue arbitrator that arbitrates his own trades will kill it and so might one incompetent arbitrator. Ten independent arbitrators that police each other might work but we are unlikely to reach this situation soon.
If Bisq has an arbitration-less option it is almost unstoppable. But right now it is fully dependent on a few "trusted" people and history has certainly shown this to be unworkable.

**Comment by sqrrm** [comment]
PR at #2871

**Comment by Giszmo** [comment]
Buyer bought 5 times without problem before. I'm sure his payment being short of the required amount was a mistake and doesn't require an arbitration. Please bring some form of chat asap.

Dispute to scale should not be visible to the arbitrator for some time, neither. Let the traders sort it out and only if after 24h no resolution is found, the arbitrator gets to see past chat and everything to come to a verdict.

**Comment by m52go** [comment]
Not stale...about to be released. Merged into master with #3165.

**Comment by sqrrm** [comment]
Released, closing.
