### ISSUE TITLE
Timeout again and again when I try to confirm an offer (I am seller of BC for SEPA)

### ISSUE THREAD

**Issue by maxi299** [bisq-network/bisq#2807]
**Following error was displayed: (attached please see log page)**

Bei der Angebotsannahme trat ein Fehler auf.

A timeout occurred.
[error_log.txt](https://github.com/bisq-network/bisq/files/3145590/error_log.txt)

Es haben noch keine Gelder Ihre Wallet verlassen.
Versuchen Sie bitte Ihre Anwendung neu zu starten und überprüfen Sie Ihre Netzwerkverbindung, um zu sehen ob Sie das Problem beheben können.Versuchen Sie bitte Ihre Anwendung neu zu starten und überprüfen Sie Ihre Netzwerkverbindung um zu sehen, ob Sie das Problem beheben können.

**Comment by ManfredKarrer** [comment]
Please open a dispute. Likely related to current block of some banks. See https://bisq.community/t/urgent-certain-banks-banned-until-further-notice/7420/

**Comment by maxi299** [comment]
This morning (06.05.2019) I was able to accept offer to sell bitcoin.
Is it possible that this issue was connected to  blocking of banks/users etc.?

**Comment by ghost** [comment]
@maxi299 
Yes. Good probability.
See https://bisq.community/t/mandatory-update-to-v1-1-0-removed-ban-for-sepa-regions-and-interac/7588
