### ISSUE TITLE
Error building v1.1.0 from source

### ISSUE THREAD

**Issue by kopite77** [bisq-network/bisq#2812]
uname -a output:
Linux hostname 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

The portion of ./gradlew build output showing the error:

> Task :desktop:test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.powermock.reflect.internal.WhiteboxImpl (file:/home/username/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-reflect/2.0.0-beta.5/4ea415348f15620783a1f26343d6732adfa86bc8/powermock-reflect-2.0.0-beta.5.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.powermock.reflect.internal.WhiteboxImpl
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

bisq.desktop.main.market.trades.TradesChartsViewModelTest > testItemLists FAILED
    java.lang.UnsupportedOperationException at TradesChartsViewModelTest.java:197

90 tests completed, 1 failed, 6 skipped

> Task :desktop:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':desktop:test'.
> There were failing tests. See the report at: file:///home/username/Programs/bisqv110/desktop/build/reports/tests/test/index.html

Output of above mentioned index.html file:

Failed tests
testItemLists

java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the class NestHost or NestMembers attribute
	at java.instrument/sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
	at bisq.desktop.main.market.trades.TradesChartsViewModelTest$1.<init>(TradesChartsViewModelTest.java:197)
	at bisq.desktop.main.market.trades.TradesChartsViewModelTest.testItemLists(TradesChartsViewModelTest.java:197)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ManfredKarrer** [comment]
I just build from master and all works. Are you sure you have updated all?

**Comment by kopite77** [comment]
@ManfredKarrer I simply followed these instructions: https://github.com/bisq-network/bisq/blob/master/docs/build.md

**Comment by devinbileck** [comment]
Make sure you are using JDK 10.
See also:
https://github.com/bisq-network/bisq/issues/2260
https://github.com/bisq-network/bisq/issues/2458

**Comment by kopite77** [comment]
@devinbileck ah, just noticed my system upgraded to JDK 11 about a week ago. Is there a reason Bisq is still using JDK 10?

**Comment by devinbileck** [comment]
See https://github.com/bisq-network/bisq/issues/1787#issuecomment-485899507

**Comment by kopite77** [comment]
closing issue, all working well after reverting to JDK10
