### ISSUE TITLE
Cannot confirm a successfull trade

### ISSUE THREAD

**Issue by maxi299** [bisq-network/bisq#2817]
Successfully sold BC and already received my money.
Now I am not able to confirm the trade and get error message.
UI advises me to open github issue.
[error_log2.txt](https://github.com/bisq-network/bisq/files/3154409/error_log2.txt)

Please advise what to do

**Comment by ManfredKarrer** [comment]
Please open a dispute with cmd+o. Did you do anything special? Seems your wallet is out of sync with the internal wallet db file.

**Comment by maxi299** [comment]
Manfred,
    thank you for your
        reply.
        After all  disputes were closed by keo I switched to a clean
        databse.
        Now everything is working fine again.
    No more complaints :-)
      
    Andreas
