### ISSUE TITLE
List Nano (NANO)

### ISSUE THREAD

**Issue by FernandoBatalha** [bisq-network/bisq#2818]
Official project URL: https://nano.org

Official block explorer URL: https://www.nanode.co

**Comment by FernandoBatalha** [comment]
@cbeams

**Comment by FernandoBatalha** [comment]
> Official project URL: https://nano.org
> 
> Official block explorer URL: https://www.nanode.co

@cbeams  @ManfredKarrer

**Comment by ghost** [comment]
From https://docs.bisq.network/exchange/howto/list-asset.html

> Bisq is always short with devs. Offering a bounty is a good idea to help your asset being listed.
