### ISSUE TITLE
BC transfered to the wrong party

### ISSUE THREAD

**Issue by maxi299** [bisq-network/bisq#2819]
I sold BC.
I received money by SEPA transfer.
I was not able to confirm the receipt in the UI.
Arbitrator s6yrrpezc3zp6biy.onion:9999 closed trade for me. But...
He moved the BC back to me.
Now I have the money and the BC.
An error log is displayed:
[error_log4.txt](https://github.com/bisq-network/bisq/files/3160284/error_log4.txt)

**Comment by ManfredKarrer** [comment]
@maxi299 thanks for being so honest! @keo-bisq will get back to you

**Comment by keo-bisq** [comment]
@maxi299 Thanks for your message and your honesty. i made a mistake. Can you please contact me at stibor@protonmail.com . The other trader has contacted me there already and has discussed the relevant trade on bisq.community and I see that you have too.
