### ISSUE TITLE
Error message on starting application and unable to take offers to buy BTC

### ISSUE THREAD

**Issue by athijssen** [bisq-network/bisq#2823]
I am using v1.1.1. I get an error popup each time I start up Bisq: 

`java.lang.IllegalStateException
`
![Bisq error message screenshot](https://user-images.githubusercontent.com/37818712/57575333-60952380-7416-11e9-9b9f-789fe4b6621a.png)

This also sometimes happens when I try to take an offer to buy Bitcoin for EUR (SEPA). Either that happens or I get the following two error messages, for any offer I try to take:

<img width="739" alt="Bisq Time out peer not responded" src="https://user-images.githubusercontent.com/37818712/57575396-693a2980-7417-11e9-981d-49ca346ee623.png">

<img width="779" alt="Bisq maker is offline" src="https://user-images.githubusercontent.com/37818712/57575399-70f9ce00-7417-11e9-8ba2-35a901bf0954.png">

**Comment by devinbileck** [comment]
@athijssen are you able to provide your bisq.log file?
