### ISSUE TITLE
UI issue syncing DAO

### ISSUE THREAD

**Issue by oscarguindzberg** [bisq-network/bisq#2825]
Steps to reproduce:
- Do a restore from seed with a date back in 2018
- Go to DAO / BSQ Wallet / Transactions

Result
- Label says "Awaiting blocks... Verified 575,868 blocks out of 554,857"
554,857 is an example, the number increases as new blocks arrive.

Expected
- Label says "Awaiting blocks... Verified 554,857 blocks out of 575,868"

<img width="467" alt="Screen Shot 2019-05-13 at 12 48 05" src="https://user-images.githubusercontent.com/1145132/57635439-8426ae00-757d-11e9-8734-e9a9d50e0ddd.png">

**Comment by ManfredKarrer** [comment]
It should repeat BSQ block requests if new BitcoinJ blockes arrived during parsing BSQ blocks, but seems there are unhandled cases. I also saw when I started with a fresh app with an old wallet that sometimes the sync took either very long or did not finish. Restarting usually resolved it.

**Comment by oscarguindzberg** [comment]
it is just a ui thing, 
Label says "Awaiting blocks... Verified X blocks out of Y"
Label should say "Awaiting blocks... Verified Y blocks out of X"

**Comment by ManfredKarrer** [comment]
I am not sure. It can be that the app gets BSQ blocks up to 575,868 from the seed nodes but bitcoinJ has still not received all blocks and is behind that. I assume that is the issue, but might be wrong as well... its a bit cumbersome to test/simulate...

We have here 2 data sources. We request BSQ blocks from seed nodes, they are delivering blocks up to latest block. We also get the latest blockheight from bitcoinJ which is usually the target height but if BitcoinJ is still syncing it can be behind. Normally BitcoinJ sync is faster then the BSQ sync but can be situations where it is not. Maybe we should overwrite the target block (right side) as soon we received response of BSQ blocks and therefore know what is the latest block even if BitcoinJ is behind that.

**Comment by devinbileck** [comment]
I believe you are right @ManfredKarrer. I can reproduce the issue and have a fix pending.
