### ISSUE TITLE
GUI: Endless loop in "Buy BTC" view when entering higher BTC amount than allowed

### ISSUE THREAD

**Issue by spogulis** [bisq-network/bisq#2835]
Steps to reproduce:

1) Click “Buy BTC”
2) Enter price in EUR
3) Enter limit price in EUR at which you want to buy
4) Change the amount of BTC from current limit (0.01 in my case) to (0.02 in my case).
5) Click somewhere else and the “Information” overlay opens. Clicking close just makes it reappear.

Note - it doesn't happen every time. You have to click around multiple times on another field, on an empty space, etc.

Only a forced shutdown through the task manager can close the app (as everything else is unresponsive, including 'X' button on the title).

**Comment by devinbileck** [comment]
@spogulis are you using Windows? I am unable to reproduce this issue.

**Comment by spogulis** [comment]
Recorded steps to reproduce for you. It's Windows 10 Pro 10.0.17134 Build 17134. The windows recorder doesn't show the popup window for some reason but I'm sure you're aware what data is displayed when you enter a higher BTC amount than your account is allowed at this time.

[Bisq 16.05.2019 19_51_56.mp4.zip](https://github.com/bisq-network/bisq/files/3188152/Bisq.16.05.2019.19_51_56.mp4.zip)

**Comment by devinbileck** [comment]
Thanks @spogulis, that recording helped. I am able to reproduce it now. It is dependent on entering a fixed price offer. With the amount > 0.01, if you first click on the fixed price field and then click in the amount field, the informational prompt will continuously reappear.

**Comment by spogulis** [comment]
Still relevant.

**Comment by spogulis** [comment]
Still relevant in latest update.

**Comment by niyid** [comment]
Hello everyone.

Can this be confirmed to be related or not to issue #2936

**Comment by spogulis** [comment]
What matters more is that it's fixed. I have the video attached and at least one person can reproduce it, so are there any developers actually working on this software which has a rather important part of it broken? 

I imagine that force-closing Bisq every time this happens is bound to corrupt the data of the user's local files at some point. There was a large update last week and this has been completely overlooked.
