### ISSUE TITLE
Why Bisq does not run in Macbook?

### ISSUE THREAD

**Issue by diegotco** [bisq-network/bisq#2837]
Check this out

a) https://screencast.com/t/u1tWSvZI

b) https://screencast.com/t/qg4G4egZxa

**Comment by diegotco** [comment]
I cannot run Bisq on my Mac, anyone knows why?

Now I have 1.1.5 version

**Comment by huey735** [comment]
Maybe it's related to this unsolved issue.
https://github.com/bisq-network/bisq/issues/2874

**Comment by diegotco** [comment]
@huey735 can you merge both?, so him/her, I and -maybe more people- will look at just one thread

**Comment by huey735** [comment]
@diegotco I don't have such powers. Ping @ripcurlx

**Comment by diegotco** [comment]
@ripcurlx :)
