### ISSUE TITLE
Tails interop issue - onion-grater config file

### ISSUE THREAD

**Issue by agb19** [bisq-network/bisq#2841]
In the Tails live OS, the preferred method for accessing the system's Tor control port is via the built-in sanitizing proxy [onion-grater](https://github.com/Whonix/onion-grater), described briefly in issue #2840. Each application using Tor control commands needs a configuration file in `/etc/onion-grater.d/` specifying which commands should be allowed for the specific application. 
Absence of this file makes the Bisq experience on Tails confusing and difficult. 

A sample config file for Bisq is provided by the onion-grater project under GPLv3 at: https://github.com/Whonix/onion-grater/blob/master/usr/share/doc/onion-grater-merger/examples/40_bisq.yml 
I have successfully used *a slight variation* of this file in my tests for issue #2840

Would it be possible to include this file in the .deb releases so it gets installed automatically with the application? In conjunction with issue #2840, this would eliminate the need for any admin level workarounds and provide a fully privilege-separated and near seamless Bisq experience to Tails users. If yes, then can someone please import the file in the Bisq tree and I'll open a PR with my modifications.

**Comment by freimair** [comment]
> I have successfully used a slight variation of this file 

@agb19 what did you change to make it work?

(I am in the process of creating a guide once and for all. Would appreciate if you can have a look at it once it is done. Thanks!)

**Comment by freimair** [comment]
https://bisq.wiki/Bisq_on_tails
