### ISSUE TITLE
Altcoin trade history blockchaining

### ISSUE THREAD

**Issue by trustfarm-dev** [bisq-network/bisq#2842]
In case of Altcoin trade,
difficult things to consumer, they don't know how to / when to send altcoins.
btc based escrow is set by buyer, alter coin seller needs to send coin to buyer,
and record transaction id or any other clue, sent altcoins.

So, in that case, consumer guide to complete transaction and submit their clue, what sent.

UX guidance and chain tx description needs.

**Comment by aejontargaryen** [comment]
There are dialog boxes within Bisq app to alert the buyer / seller when you have sent coins. This tells you when to check your altcoin wallet to see if they have arrived.  Is this what you mean?

**Comment by trustfarm-dev** [comment]
@aejontargaryen  , so, I think trading altcoin, coin developers give a wallet / send /receive /explorer link displaying is better,
and most of coin have transaction id, altcoin seller enter txid to input box.
beginner buyer, not receive altcoin , and altcoin seller never send coin , but alt buyer click confirm buyed, then he will not solve what's problem.
