### ISSUE TITLE
Connection to Bitcoin networking failing at startup. 

### ISSUE THREAD

**Issue by fannotastic** [bisq-network/bisq#2850]
Getting an error on startup that says, "Connection to the Bitcoin network failed because of an error: java.lang.NullPointerException". I uninstalled and reinstalled the application but the issue won't solve. Please help.

**Comment by devinbileck** [comment]
@fannotastic thanks for reporting this issue. Are you able to provide the bisq.log, or at least the section of it that contains this error message?

**Comment by fannotastic** [comment]
Where can I access the log file when I can't even get past the startup screen? I'm running Windows.

**Comment by HarryMacfinned** [comment]
For windows, the log files are at:
Windows 7,8,10: C:\Documents and Settings\username\AppData\Roaming\Bisq 
Windows XP: C:\Documents and Settings\username\Application Data\Bisq 

If it is not this exact way, make a search for <code>Bisq</code>

**Comment by fannotastic** [comment]
<img width="378" alt="Capture 1" src="https://user-images.githubusercontent.com/51055022/58398705-c1258280-800a-11e9-9057-72fadc9909fb.PNG">

**Comment by fannotastic** [comment]
<img width="549" alt="Capture" src="https://user-images.githubusercontent.com/51055022/58398751-e0241480-800a-11e9-994d-99e5f78cca82.PNG">

**Comment by devinbileck** [comment]
Slight Correction for Win 7+, the path is C:\Users\<username>\AppData\Roaming\Bisq

**Comment by fannotastic** [comment]
<img width="936" alt="Capture" src="https://user-images.githubusercontent.com/51055022/58399358-c8e62680-800c-11e9-9e75-4a2b94b6e0dc.PNG">

**Comment by fannotastic** [comment]
There are some screenshots above with the error message. Let me know if I'm missing anything, thank you.

**Comment by devinbileck** [comment]
It appears to be coming from BitcoinJ. Perhaps @oscarguindzberg has an idea?

**Comment by oscarguindzberg** [comment]
weird, are you creating a new wallet or openening a wallet you already have?
If you are creating a new wallet, please empty you bisq data dir and start again.

**Comment by fannotastic** [comment]
I was opening my wallet that I already have, the problem started on it's own. But now I deleted all the files and reinstalled the application and it's working now. Thanks for all the help guys!
