### ISSUE TITLE
Bisq jar file contains duplicated native libs

### ISSUE THREAD

**Issue by leshik** [bisq-network/bisq#2851]
There are `macOS` platform native `openjfx` dylibs present inside the root of Bisq `jar` file:
```
libdecora_sse.dylib
libglass.dylib
libjavafx_font.dylib
libjavafx_iio.dylib
libprism_common.dylib
libprism_es2.dylib
libprism_sw.dylib
```
These files are duplicates as `macOS` Java runtime already contains all of them. Shouldn't they be stripped on build?

**Comment by ripcurlx** [comment]
@leshik We bundle the JDK right now within the application so it works without the right JDK version installed. Not sure if there is a reason why it was added by the JDK bundler, but I hope/guess so.

**Comment by leshik** [comment]
@ripcurlx
> We bundle the JDK right now within the application so it works without the right JDK version installed.

Yeah I know, that’s why it’s strange to me that same libraries are added to `jar` which already present in the bundled JDK.

**Comment by ripcurlx** [comment]
Yes, maybe this will be fixed or changed as soon as the open JDK supports native packaging again for Java 11 and above (https://bugs.openjdk.java.net/browse/JDK-8200758)

**Comment by leshik** [comment]
Not sure it's a `jpackager` fault – these files are actually coming from `javafx-graphics-11-mac.jar`.
