### ISSUE TITLE
Karbo Listing

### ISSUE THREAD

**Issue by lukemud** [bisq-network/bisq#2852]
Please fill in the following data to request for a new asset to be listed on Bisq. For more details, be sure to read [the full documentation](https://docs.bisq.network/exchange/howto/list-asset.html) on adding a new asset.

### 1. Asset name

Karbo

### 2. Ticker
KRB

### 3. Block explorer URL
https://explorer.karbo.io/

### 4. Additional technical requirements (yes/no)
NO

### 5. Initial coin offering (yes/no)
NO

**Comment by blabno** [comment]
Is this a privacy related coin, like monero?
