### ISSUE TITLE
Maximum number of bitcoins in circulation

### ISSUE THREAD

**Issue by ulrichard** [bisq-network/bisq#2853]
A couple of days ago, Bisq somehow lost the price for NMC.
Since then the order book chart started looking funny. It goes up to 3*10e42 BTC. I still wonder how such a trade could be settled.

![BisqNMC](https://user-images.githubusercontent.com/1116405/58472845-78bfaf00-8147-11e9-940a-ef0d83a73d5c.png)

**Comment by ghost** [comment]
Weird.
I see 0 offers, but the graphic at least looks normal.
Which Bisq version do you use ? Which OS ?
Do other altcoins look normal ?

**Comment by ulrichard** [comment]
Bisq 1.1.1 on Ubuntu 16.04
The offers don't show in the graphic because there is no price.
Other altcoins look good. After cycling back to NMC it also looks better.

**Comment by ghost** [comment]
There are indeed some issues with refreshing in the appli.
(and it may be due to java/OS itself, so not so easy to tackle).

**Comment by ripcurlx** [comment]
@ulrichard Please re-open this issue if you still experience this problem. Thanks!
