### ISSUE TITLE
New dialogs and notifications windows not visible until dragged bigger

### ISSUE THREAD

**Issue by initCCG** [bisq-network/bisq#2855]
Have a user on latest version of Qubes version 4.19 in VMs based on any default OS - currently Debian 9, Fedora 29, Whonix.

Bisq installs without errors on Fedora 29, but when Bisq opened, this was how:
![QubesStart](https://user-images.githubusercontent.com/40746153/58609517-4e7d0700-8297-11e9-9650-15ccd1f7145d.png)

Remained just like that indefinitely, until user noticed the small bar that's circled. That bar is actually the dialog window.

Dragging it horizontally, shows the window bar:
![QubesStart1](https://user-images.githubusercontent.com/40746153/58609621-c0555080-8297-11e9-8435-68e3192b91f5.png)

Dragging it diagonally, shows the dialog box:
![QubesStart2](https://user-images.githubusercontent.com/40746153/58609636-d236f380-8297-11e9-822a-f5866af6e790.png)

That happens with every new dialog window in the app. It has to be dragged to see what is there.

Maybe the minimal size of the dialog boxes is not specified? So, the OS just considers the minimum size to be 0 pixels?

Just a busywork problem, but it was a long time before the new user understood why the app wasn't starting, when actually it was starting, but the first dialog wasn't visible.

**Comment by ripcurlx** [comment]
@initCCG Thanks for reporting. Actually there is a default width of `668` defined, but something else seems to go wrong there. Needs to be investigated. Unfortunately I don't have this system setup right now. Maybe someone else with the system could do some testing if there is a workaround for this.

**Comment by initCCG** [comment]
@ripcurlx Thank you, sir!
It's interesting that if the whole working directory of bisq is renamed for a recovery test we did, and the app must make it from the beginning, the problem comes back even on dialogs that were previously dragged open. (After a given dialog is dragged open, it remains that size on next appearance.)

So, we think it is something in the initial settings the app makes when it first starts to operate.

**Comment by initCCG** [comment]
We built a new Fedora 30 VM for it, and this problem is still there with version 1.2.3 Bisq.

It's still the only app that does this on  any Qubes VM on any machine we use.

**Comment by wiz** [comment]
Hmm, this feels like a quirk of your OS's Window Manager more than anything...

**Comment by initCCG** [comment]
It's XFCE 4.12, which operates over Fedora and Debian VMs, and other custom qubes with whatever OS installed in them.

If it is XFCE, then seems that other apps of many that we use would also have dialog display quirks.

XFCE is one of the most basic and light of most popular window managers for Linux.

**Comment by initCCG** [comment]
We finally found another app that does a similar thing - LibreOffice Calc on Fedora.
So, it does seem to be something in certain apps and certain window managers on certain OS platforms.
https://github.com/QubesOS/qubes-issues/issues/3281

**Comment by Bigsy11** [comment]
For this problem, can press Alt+F10 to maximize dialog window, but which setting to make this automatic, I don't know.

**Comment by cd2357** [comment]
Have the same problem, even with the latest Bisq on the latest Qubes.

I've tried many things, but the only setup where this works for me is #4242 (but that is still work in progress).
