### ISSUE TITLE
Payment confirmation not being relayed to trading partner

### ISSUE THREAD

**Issue by fung1ble** [bisq-network/bisq#2857]
I opened 2 different trades with the same buyer and he made both payments at the same time, but only one has been marked at paid on my side. It’s been over 24 hours since I confirmed the one that DID come through as paid on my side. I have no way to verify it with the buyer since we can’t communicate.I noticed another user having the [exact same problem](https://bisq.community/t/payment-started-on-buyer-side-stuck-on-seller-side/7757/5)

It seems you have a systemic bug that a user can’t easily know is occuring much less report. I’ve delt with this buyer before and he’s always prompt, and after reading the post I linked above, it just re-inforces my doubts that it is infact a bug.

Thanks!

edit: using ubuntu with latest updates and latest version of Bisq

**Comment by ripcurlx** [comment]
> I opened 2 different trades with the same buyer and he made both payments at the same time, but only one has been marked at paid on my side.

Just to confirm: You mean that you received the e.g. fiat transfer to your personal account for both trades, but payment sent was not triggered within the app for one of the trades?

**Comment by fung1ble** [comment]
> Just to confirm: You mean that you received the e.g. fiat transfer to your personal account for both trades, but payment sent was not triggered within the app for one of the trades?

Yes, that's correct. I just updated from 1.1.1 to 1.1.2 so I'm not sure if that might fix this problem, but if not, you may want to look into it. It been about 7 days since the trade first started and the arbitrator has already closed the case but if there may be any lingering logs (even after the upgrade) that may help you out, you let me know and I can try to anonymize and upload them.

I also noticed another user [reported the same bug here](https://github.com/bisq-network/bisq/issues/2817) 15 days ago.

Thank!
