### ISSUE TITLE
Listing Raven coin (RVN)

### ISSUE THREAD

**Issue by vxix66734** [bisq-network/bisq#2866]
1. Asset name
Ravencoin (RVN).
[ https://getravencoin.org/ ]

2. Ticker
Ravencoin (RVN).
https://coinmarketcap.com/currencies/ravencoin/

3. Block explorer URL
https://ravencoin.network/

 4. Additional technical requirements (yes/no)
Code base: Bitcoin core 0.15.1.

5. Initial coin offering (yes/no)
No ICO.

**Comment by blabno** [comment]
We need values of `addressHeader` and `p2shHeader` and any special validation rules that are different than for Bitcoin addresses.
