### ISSUE TITLE
DAO not syncing after update to v1.1.2

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/bisq#2868]
I had to revert to using v1.1.1, since DAO just kept on syncing endlessly after i updated to v1.1.2.
After going back to previous version all worked fine again.
Reproduced the issue on two systems.

**Comment by ghost** [comment]
What is your OS ?
What kind of internet connection do you use ? (eg wifi/wifi).

**Comment by invertedbobb** [comment]
Ubuntu 18.04 x64.
Both wifi and wired, 400mbps down 100mbps up.

**Comment by ghost** [comment]
Was the behaviour with v1.1.2 systematic ?
Did you try many times ?
From time to time, I had a similar issue with v1.1.1 (I have wifi/wifi connection), but restarting once generally was enough to have Bisq working.

**Comment by invertedbobb** [comment]
I did try several times and it didn't work, however, now, a day later, it works on both systems.
Maybe it was having trouble connecting to the seed nodes or something.
Regardless, the issue appears to have been temporary in nature and is no longer preventing functionality.

**Comment by freimair** [comment]
likely closed by #3112

**Comment by chimp1984** [comment]
No, the issue is not fixed yet. See: https://github.com/bisq-network/bisq/issues/3175
