### ISSUE TITLE
Support of Torv3 (Required for BTCPay Server)

### ISSUE THREAD

**Issue by NicolasDorier** [bisq-network/bisq#2873]
I recently added Bisq to the supported software to connect to your BTCPay hosted node.

![image](https://user-images.githubusercontent.com/3020646/59045298-c01e0c00-88ba-11e9-90b1-90c3642bf2d7.png)

I tried it today, and sadly it does not work. 

BTCPay use Tor version 3 for exposing the full node. 

Tor v2 is not adapted to connect to your own node because you want your own BTC node to whitelist any connection using the Tor address to guarantee having a connection slot available.

But if your Tor is version 2, then your address become discoverable and anybody could connect to it and DDoS you.

```
Jun-07 00:23:18.233 [JavaFX Application Thread] INFO  b.c.b.s.WalletsSetup: Socks5Proxy for bitcoinj: socks5Proxy=sampleapi.example.com:61780	Version 5 
Jun-07 00:23:18.256 [JavaFX Application Thread] INFO  o.b.c.Context: Creating bitcoinj 0.14.7.bisq.1-SNAPSHOT context. 
Jun-07 00:23:18.263 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Jun-07 00:23:18.263 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= Invalid hostname: ######################.onion 
Jun-07 00:23:18.264 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.IllegalArgumentException 
Jun-07 00:23:18.273 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.IllegalArgumentException: Invalid hostname: ######################.onion
	at org.bitcoinj.net.OnionCatConverter.onionHostToIPV6Bytes(OnionCatConverter.java:28)
	at org.bitcoinj.net.OnionCatConverter.onionHostToInetAddress(OnionCatConverter.java:46)
	at bisq.core.btc.nodes.BtcNodeConverter$Facade.onionHostToInetAddress(BtcNodeConverter.java:130)
	at bisq.core.btc.nodes.BtcNodeConverter.convertOnionHost(BtcNodeConverter.java:61)
	at bisq.core.btc.nodes.BtcNodesRepository.lambda$getOnionHosts$1(BtcNodesRepository.java:74)
```

~Torv2 seems required at BitcoinJ level, but there is normally NO NEED to require it. If you have your own fork of BitcoinJ, I advise you to patch it.~

**Comment by NicolasDorier** [comment]
Actually the code break at Bisq level!

**Comment by ripcurlx** [comment]
@freimair Could you please have a look at this issue/requirement?

**Comment by freimair** [comment]
yes will do. but please allow for a week or so as I am off to having a sail in Scotland

**Comment by NicolasDorier** [comment]
@freimair cool I hope you can do something about it and that's not a block at BitcoinJ level!

**Comment by NicolasDorier** [comment]
@freimair any chance to do something about it?
Also if a user try to do it, then it can't open Bisq again without crashing like @britttttk reported.

**Comment by freimair** [comment]
Sorry, has been a couple of busy days.

I looked into it and in fact, I have been planning on bringing the new 
hidden services to Bisq for quite some time now 
(<https://trac.torproject.org/projects/tor/ticket/29669>).

I am currently experimenting on compatibility of v2 and v3 and thinking 
about a good strategy to get Bisq to v3 without the need for a hard 
fork.

**Comment by freimair** [comment]
may require the functionality of #1056

**Comment by ripcurlx** [comment]
@NicolasDorier Just a heads-up that the tor upgrade roadmap is discussed internally right now. Should be an update available soon.

**Comment by wiz** [comment]
@cd2357 can you unassign florian and look into this? :heart:

**Comment by cd2357** [comment]
Seems to depend on bitcoinj

```
java.lang.IllegalArgumentException: Invalid hostname: wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid.onion
	at org.bitcoinj.net.OnionCatConverter.onionHostToIPV6Bytes(OnionCatConverter.java:28)
	at org.bitcoinj.net.OnionCatConverter.onionHostToInetAddress(OnionCatConverter.java:46)
	at bisq.core.btc.nodes.BtcNodeConverter$Facade.onionHostToInetAddress(BtcNodeConverter.java:130)
	at bisq.core.btc.nodes.BtcNodeConverter.convertOnionHost(BtcNodeConverter.java:61)
	at bisq.core.btc.nodes.BtcNodesRepository.lambda$getOnionHosts$1(BtcNodesRepository.java:74)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
```

Will have another look once 1.4.0 is out, since that starts using a new bitcoinj branch.

**Comment by wiz** [comment]
Yes I guess might have to PR the code in Bisq's fork of bitcoinj https://github.com/bisq-network/bitcoinj
Altho the main bitcoinj repo might be working on this already so probably a good idea to check upstream/master

**Comment by cd2357** [comment]
Unfortunately it looks like bitcoinj has no native support for tor, all of that that is added as a custom modification to our own bitcoinj fork (https://github.com/bisq-network/bitcoinj/issues/25).

Our tor code also seems to go pretty deep, affecting `PeerAddress`, serialization, onioncat format support, etc.

I'd rather let someone more knowledgeable handle this, like perhaps @oscarguindzberg if he's interested.

**Comment by ripcurlx** [comment]
bitcoinj/bitcoinj#2067 is implemented already and we are in the process of migrating and testing the Tor v3 support.

**Comment by cd2357** [comment]
Bisq now supports Tor v3 addresses.
