### ISSUE TITLE
Bisq App Launch Failure, Bisq-1.1.2 on OSX Yosemite 10.10.5

### ISSUE THREAD

**Issue by secretsquirl86** [bisq-network/bisq#2874]
**Anyone able to help on this issue?**
June 7 Received message below from Bisq forum. Tried to run bisq from terminal and received this message. 
Last login: Fri Jun  7 13:51:11 on ttys000
XXXXX-MacBook-Pro:~ XXXXX$ /Applications/Bisq.app/Contents/MacOS/Bisq ; exit;
2019-06-07 13:51:23.137 Bisq[512:13541] /Applications/Bisq.app/Contents/MacOS/libpackager.dylib not found.
logout

[Process completed]

Forum**
(((It is possible that Bisq crashes before it even creates the data directory, althought that is very rare.

Not sure where Bisq is installed on Mac, but on linux it is at /opt/Bisq/Bisq. If you find it, you can run it from the command line and look for the output for some warnings/errors.)))
May 29 Bisq forum Member suggested checking for log file. @ /Users/username/Library/Application Support/Bisq, checked and no such Bisq file exists.
May 28 Joined Bisq forum to ask for help.
May 28 Searched youtube & reddit for similar issue.
May 28 Cycled off and on, now off, Bitdefender.
May 28 Nothing happens, re-install twice, Tor browser cycle.
May 28 Attempt to open Bisq through app icon in app folder.
May 28 Install file, move icon into application folder.
May 27 Installed Bisq aforementioned file version.
May 24 Installed Tor Browser.

**Comment by mtelizalde** [comment]
hello, I'm experiencing the same issue. could you please reopen the case;?

**Comment by julianknutsen** [comment]
https://bugs.openjdk.java.net/browse/JDK-8200214

This seems to indicate that there is a problem with the bundled jdk10 on 10.10.X installations in other software as well.

@mtelizalde 
I don't have access to that configuration on a mac, but can you download the jdk-10 directly and run bisq from the command line to see if the same workaround is successful?
