### ISSUE TITLE
Cannot set % value above 100 for IRR currency

### ISSUE THREAD

**Issue by mmahdim** [bisq-network/bisq#2875]
The official rates for BTC to IRR are not accurate, the real IRR/BTC value is 1,099,929,975 at the moment while official rates are around 34,000,000 IRR/BTC, and when making advertisements Bisq doesn’t allow us to use either a fixed coefficient or a % value above 100% for the exchange rate.
So that prevents us from making trades on Bisq.
Please lift that limitation at least for the IRR currency.

**Comment by Mahdi321** [comment]
The correct exchange rate is available here: https://www.coinhills.com/market/btc-irr/
But removing 100% margin limitation is an easier option

**Comment by huey735** [comment]
Bisq uses this service for its fiat prices: https://bitcoinaverage.com/en/bitcoin-price/btc-to-irr

So I guess you'd need to find an alternative that provides the national rates? Looking at Local Bitcoins the offers seem to also use the international rates. But still, you can instead use fixed prices for now.
![iranlb](https://user-images.githubusercontent.com/44140017/63637980-ad75d080-c67a-11e9-851b-72338a41f871.png)

**Comment by mmahdim** [comment]
The rates at LBTC are real. lbtc uses bitcoinaverage price in USD, then the traders set their own fixed coefficient to convert into IRR. In lbtc traders can also use some other math functions, like MIN, MAX, etc. which would be really good if could be implemented in Bisq. Also since lbtc started banning Iranian users Bisq could be a good alternative for us if this issue is fixed.

> Bisq uses this service for its fiat prices: https://bitcoinaverage.com/en/bitcoin-price/btc-to-irr
> 
> So I guess you'd need to find an alternative that provides the national rates? Looking at Local Bitcoins the offers seem to also use the international rates. But still, you can instead use fixed prices for now.
> ![iranlb](https://user-images.githubusercontent.com/44140017/63637980-ad75d080-c67a-11e9-851b-72338a41f871.png)
