### ISSUE TITLE
Zerozed x0z listing request

### ISSUE THREAD

**Issue by CalemS** [bisq-network/bisq#2880]
Please fill in the following data to request for a new asset to be listed on Bisq. For more details, be sure to read [the full documentation](https://docs.bisq.network/exchange/howto/list-asset.html) on adding a new asset.

### 1. Asset name
Zerozed

### 2. Ticker
_Your asset's ticker must not conflict with any national currency tickers (per [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)) or any of the [top 100 cryptocurrency tickers](https://coinmarketcap.com/coins/)._
x0z

### 3. Block explorer URL
_Your asset's block explorer must be active and publicly available so that transactions can be verified with a receiver's address...if this isn't possible, [see workarounds here](file:///home/steve/wb/bisq/bisq-docs/build/asciidoc/html5/exchange/howto/list-asset.html#arbitrators-must-be-able-to-look-up-transactions-in-the-asset-block-explorer)._
https://chainz.cryptoid.info/x0z/

### 4. Additional technical requirements (yes/no)
_Your asset should not have any additional requirements (for example, needing input fields for anything other than an address)._
no - Bitcoin 0.13.0 fork secured via pure scrypt

### 5. Initial coin offering (yes/no)
_Bisq will not list your token if it has taken part in an initial coin offering (ICO)_
no

**Comment by blabno** [comment]
Is it ERC-20 token?
Is it privacy coin like monero?
Is it fork of any other coin?
What are the wallet address validation rules?

**Comment by CalemS** [comment]
Pure Scrypt based coin using the Bitcoin 0.13.x codebase. Relaunched from
genesis.

We have replaced the blockhalving mechanism with an inflation algo based on
the Diffusion of Innovations theory.

Essentially we are what you might call a crypto-economic experiment.
https://bitcointalk.org/index.php?topic=4096286.0

**Comment by blabno** [comment]
So are all your addresses 100% compatible with bitcoin?

**Comment by CalemS** [comment]
We have the same rules as Bitcoin 0.13.x with the following differences.

2min blocktime
DoI Inflation instead of block halving
Scrypt

So I will assume yes.

**Comment by blabno** [comment]
You have to find a developer who will create PR.
I can do that for 50BSQ.

**Comment by CalemS** [comment]
Create PR?

**Comment by blabno** [comment]
Pull request with the necessary code changes.

**Comment by CalemS** [comment]
Ahh... Ok fine. How much USD is 50BSQ

**Comment by blabno** [comment]
around 50USD.

**Comment by CalemS** [comment]
If you haven't noticed.. I can't code.. Please forgive me...

**Comment by CalemS** [comment]
OK. Well. I get paid next week. I'll be in contact then.

**Comment by blabno** [comment]
Ping me on Bisq slack (@bernard)
