### ISSUE TITLE
custom theme / custom style (especially for visually handicapped)

### ISSUE THREAD

**Issue by Mike2019b** [bisq-network/bisq#2882]
Hi!

I’m visually handicapped and would need a dark style / dark theme and if possible bigger font sizes.

I couldn’t find settings for this in the App/GUI, but in the jar file “desktop-1.1.1-all.jar” there is “/styles/awesome_dark.css”.

Does someone have an idea:

  * How I can activate/use a or this dark theme?
  * Or how I could force the App to use a custom css file/theme?

I have some programming knowledge and could work on this or on a general solution for custom themes if someone could give me an idea.

Thanks!
Mike

**Comment by peterzen** [comment]
@Mike2019b at this point there's no documented facility to use a different style sheet.  There's a pending PR that's aimed at making this possible: https://github.com/bisq-network/bisq/pull/2414
