### ISSUE TITLE
java.lang.IllegalArgumentException (Major Issue)

### ISSUE THREAD

**Issue by spottedmarley** [bisq-network/bisq#2886]
java.lang.IllegalArgumentException (Major Issue)
This is a major issue. I had 5 pending trades (money order by mail) open and a few open offers. Someone tried to accept one or more of my open offers and I was flooded with errors. After I restarted Bisq NONE of my pending or open offers are listed in my portfolio!!! I buyer has already initiated payment and now all of those trades are gone. Someone please help

**Comment by spottedmarley** [comment]
! ! ! UPDATE

Ok, so thankfully I had already backed up my data folder when this happened so I was able to restore my old data folder and everything seems to be fine BUT that was a HUGE software error that could have cost a lot of money and/or hardship. TBH Im afraid to post new trades now...but the fire is out at least.

**Comment by ghost** [comment]
@spottedmarley ,
Please upload the concerned logfile here, or at least the concerned part.
This is necessary to try to understand what happened.

**Comment by sqrrm** [comment]
Possibly related to #2815

**Comment by spottedmarley** [comment]
> @spottedmarley ,
> Please upload the concerned logfile here, or at least the concerned part.
> This is necessary to try to understand what happened.

The issue has happened again and I opened a new issue report #2910 that includes screen shot and my log file. Thanks!
