### ISSUE TITLE
add Runebase

### ISSUE THREAD

**Issue by bobpepers** [bisq-network/bisq#2891]
Please fill in the following data to request for a new asset to be listed on Bisq. For more details, be sure to read [the full documentation](https://docs.bisq.network/exchange/howto/list-asset.html) on adding a new asset.

### 1. Asset name

Runebase

### 2. Ticker
_Your asset's ticker must not conflict with any national currency tickers (per [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)) or any of the [top 100 cryptocurrency tickers](https://coinmarketcap.com/coins/)._

RUNES

### 3. Block explorer URL
_Your asset's block explorer must be active and publicly available so that transactions can be verified with a receiver's address...if this isn't possible, [see workarounds here](file:///home/steve/wb/bisq/bisq-docs/build/asciidoc/html5/exchange/howto/list-asset.html#arbitrators-must-be-able-to-look-up-transactions-in-the-asset-block-explorer)._

http://explorer.runebase.io

### 4. Additional technical requirements (yes/no)
_Your asset should not have any additional requirements (for example, needing input fields for anything other than an address)._

No

### 5. Initial coin offering (yes/no)
_Bisq will not list your token if it has taken part in an initial coin offering (ICO)_

No

**Comment by blabno** [comment]
Is it ERC-20 token?
Is it privacy coin like monero?
Is it fork of any other coin?
What are the wallet address validation rules?

**Comment by bobpepers** [comment]
Is it ERC-20 token?
No

Is it privacy coin like monero?
no, It's a smart contract platform (Bitcoin Core merged with the Ethereum Virtual Machine)

Is it fork of any other coin?
Yes, it's a QTUM fork (Bitcoin fork)

What are the wallet address validation rules?
Base58

start letter: 
R

regex:
^[R][a-km-zA-HJ-NP-Z1-9]{33,34}$

extract public key from ECDSA:
https://github.com/Runebase/extractPubAddressFromECDSA/blob/master/pubkey.py

base58Prefixes:
HEX_MAINNET_PUBKEY = "3C";
HEX_MAINNET_SCRIPT = "7B";

DECIMAL_MAINNET_PUBKEY = "60";
DECIMAL_MAINNET_SCRIPT = "123";

if the address validation rules information mentioned above are not sufficient, kindly let us know. then we will provide you with an address validation script.

**Comment by blabno** [comment]
You will need a developer (could be yourself) to create a pull request with necessary code changes.
If you can't find anyone then contact me on Bisq slack (@bernard).
