### ISSUE TITLE
Fees skyrocket over night?

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/bisq#2893]
Not an issue per-se, but I noticed the BSQ fees just more than tripled yesterday, certainly noticeable and preventing certain trades. Not helping liquidity on the network.

How are fees determined? Are they voted upon by stake holders (BSQ), the developers, calculated by some network metric?

**Comment by ghost** [comment]
Bisq uses https://bitcoinfees.earn.com to provide fees.
Please notice that those are **bitcoin mining fees**, which are entirely determined by the bitcoin network being crowded or not. There is nothing Bisq can do on the mining fees.
You can fix yourself the fees you want to use, but do that carefully. If you don't use enough fees, your transaction can be stucked for a long time. If it is a trade, it can be annoying.

**Comment by invertedbobb** [comment]
I'm not talking about mining fees. I'm talking about the trade fees.
Costs are calculated Deposit+tradefee+miningfee. The deposit will be returned after a successful trade.
It's the trade fee that more than tripled over night.

**Comment by ghost** [comment]
The trading fees are fixed.
However, since every tx in Bisq relies on BTC, the global fees vary as the BTC mining fees vary.
See https://bisq.network/faq/#cost-to-trade

**Comment by invertedbobb** [comment]
I thought they were fixed too.
For example creating a max size XMR offer used to cost 1 BSQ and taking an XMR offer would cost 3 BSQ.
That just changed to 3.20 and 9.60 respectively. BSQ/BTC has remained fairly stable and BTC/USD has been going up, with that the effective USD cost of trade fee paid in BSQ.

I don't see where the factor 3.2 increase comes from all of a sudden?

**Comment by ghost** [comment]
In the last 48 hours, the BTC mining fees moved between a minimum of 10 sat/byte and a maximum of 90 sat/byte.
If you know how to predict those moves, you are very welcome to help the Bisq project (and the whole cryptoworld).

**Comment by ManfredKarrer** [comment]
@invertedbobb The BSQ fee was increased in the recent DAO voting. See https://github.com/bisq-network/proposals/issues/94#issuecomment-494813684

**Comment by fresheneesz** [comment]
> You can fix yourself the fees you want to use, but do that carefully.

How? I don't see any way to select a fee whether your a market maker or market taker. The automatically chosen mining fees are far too high. I'm seeing mining fees of between 0.026 mBTC and 0.06 mBTC (~26-60 cents), and for some reason the total mining fees are around 0.114 ($1.14). A transaction should be costing less than 12 cents, since that'll get a 400 byte transaction into the next 1-2 blocks according to bitcoinfees.earn.com. It seems likely that there are multiple transactions happening here, but looks like 2. So the total fee should be less than 30 cents (3000 satoshi). So what gives?

**Comment by fresheneesz** [comment]
How about someone goes through these issues and verifies whether or not they're still an issue instead of having stale bots remove issues that are still valid?

**Comment by ripcurlx** [comment]
> How about someone goes through these issues and verifies whether or not they're still an issue instead of having stale bots remove issues that are still valid?

ATM the BSQ fees are defined by DAO voting. There is a new proposal to adapt it automatically on the current BSQ price https://github.com/bisq-network/proposals/issues/173.

**Comment by ripcurlx** [comment]
Closing this issue as BSQ fees are working correctly on Mainnet.
