### ISSUE TITLE
why do some coins in the market should up with "N/A" in front of the name?

### ISSUE THREAD

**Issue by johnbrown2341** [bisq-network/bisq#2894]
A few coins I am interested in are showing N/A by their name. I assume this means Not Available? If so, what can we do to make that coin be available again?

**Comment by ghost** [comment]
Yes, generally it means that the coin was delisted due to inactivity.
See DAO/Asset listing in the appli about how to relist a coin.
If I'm not wrong, it is 1 BSQ per day to have a coin relisted, with a minimum of 30 days.

**Comment by johnbrown2341** [comment]
thanks for the response.

I went to the DAO section and scrolled down to the coin I was interested in "Particl", but it is not displaying on the list of coins that were delisted.

Think you could take a look for me? See below: 
https://i.gyazo.com/d9279c1a593a2cfd36c1fbdda0bbcbc2.png

**Comment by ghost** [comment]
Particl was listed in november 2017, probably delisted in early 2018. That's very far.
Listing it again must be done through the first time procedure: https://docs.bisq.network/exchange/howto/list-asset.html

**Comment by johnbrown2341** [comment]
well damn, that sucks.

**Comment by johnbrown2341** [comment]
Do you see that there are offers posted on the N/A Particl market? Is this a bug?

**Comment by ghost** [comment]
Yes, I see indeed offers mentioned.
It's indeed a kind of bug ... but managing the 99% of altcoins which are just wind is really tedious.
I will manage those N/A cases for the next release (if it is not too short !).
Thanks for mentioning that.

**Comment by johnbrown2341** [comment]
just curious, approximately how long does it take to relist a coin after the relisting has been approved?

**Comment by ghost** [comment]
First time listing occurs only at the time of a release.
(And if a dev had the time to realize the integration).
