### ISSUE TITLE
Links open externally with Calibre instead of browser - fix/improve link opening

### ISSUE THREAD

**Issue by userzer0x** [bisq-network/bisq#2896]
On my system i have calibre, which has nothing to do with bisq - but the problem is when i click on the links within bisq to check the tx in the browser, it opens it with calibre automatically.
When i uninstalled calibre, and clicking on the link it opens with the default browser.

I dont want to mess with the MIME types so I think there should be an option to open with a certain browser/program once the user clicks on the link to open the tx. Not just open with whatever bisq deems necessary.

Can you fix this issue please?

**Comment by devinbileck** [comment]
This is outside the control of Bisq. Clicking a link will load whatever app your OS has defined to be the default for opening web links - in your case when calibre is installed it is being configured to load web links by default. You will need to change this setting in your OS to use the appropriate browser.

**Comment by userzer0x** [comment]
@devinbileck I am aware of that.  But what i was suggesting is to give the user the option to "open-with" another browser or app of their choice, not assume that it will open with default browser. Give the user the freedom to choose which browser to open it with.
Can this be improved?

**Comment by devinbileck** [comment]
I suppose we could add an option that allows the user to select whether they want to open links in the system default browser or enter a specific command/executable (i.e. browser) to launch when clicking links. This may have the added benefit of being able to explicitly open links in the tor browser.
