### ISSUE TITLE
TrueUSD is nowhere to be found in the Add Altcoins List

### ISSUE THREAD

**Issue by userzer0x** [bisq-network/bisq#2897]
I see TrueUSD has been added and there is a trade open in bisq but i cannot see it anywhere to add it in my list of Altcoins.

There are some other altcoins as well that i cannot find in the list. But havent checked in detail which ones, the list just seems very short and not many to choose from.
Can anyone else confirm?

**Comment by ghost** [comment]
TrueUSD has been delisted from Bisq due to inactivity.
See DAO/Asset listing in the appli.
