### ISSUE TITLE
Can you add DigiByte support to BISQ?

### ISSUE THREAD

**Issue by TwoFace12345** [bisq-network/bisq#2907]
Please fill in the following data to request for a new asset to be listed on Bisq. For more details, be sure to read [the full documentation](https://docs.bisq.network/exchange/howto/list-asset.html) on adding a new asset.

### 1. Asset name
DigiByte

### 2. Ticker
$DGB

### 3. Block explorer URL
https://digiexplorer.info

### 4. Additional technical requirements (yes/no)
Only a DigiByte address is needed for transactions. 
DigiByte is not complex to add, see the attached integration guide!

### 5. Initial coin offering (yes/no)
No, DigiByte was no ICO and is a 100% mine-able independent POW UXTO block-chain.
[DigiByteIntegration-v1.3.pdf](https://github.com/bisq-network/bisq/files/3308308/DigiByteIntegration-v1.3.pdf)

**Comment by blabno** [comment]
Is it ERC-20 token?
Is it privacy coin like monero?
Is it fork of any other coin?
What are the wallet address validation rules?

**Comment by TwoFace12345** [comment]
Hi Bernard,Here are some answers:Is it ERC-20 token?A: No. DigiByte is a POW UXTO blockchain and crypto currency with its own independent globally distributed and 100% decentralized network since 2014.https://digibyte.io/Is it privacy coin like monero?A: No. is has some privacy functions like heuristics (HD addresses) and Dandelion protocol to protect users. But DigiByte is a public ledger and needs that functionality for its use cases.Is it fork of any other coin?A: No. Just like Bitcoin, DigiByte has its own independent genesis block.What are the wallet address validation rules?A: Check this for the code on address validation for DigiByte: https://github.com/mctrivia/DigiSweep/blob/master/DigiByteTX.js#L11Yours sincerely, Rutger KrijnenDigiByte Awareness Team---- On Wed, 07 Aug 2019 07:21:37 +0200  Bernard Labno<notifications@github.com> wrote ----Is it ERC-20 token? 
Is it privacy coin like monero? 
Is it fork of any other coin? 
What are the wallet address validation rules?

**Comment by blabno** [comment]
You will need to find a developer who will prepare PR.
If you don't have anyone I can do that for 300BSQ. Find me on Bisq slack (@bernard).

**Comment by TwoFace12345** [comment]
H Bernard,Yes that would be awesome if you can prepare the PR, as all the devs I personally know are already overloaded.I am on holiday now, but will try to contact you on slack as soon as I return.Is this something you are able to do on short term?Thank you!Yours sincerely, Rutger KrijnenDigiByte Awareness Team---- On Wed, 07 Aug 2019 10:54:45 +0200  Bernard Labno<notifications@github.com> wrote ----You will need to find a developer who will prepare PR. 
If you don't have anyone I can do that for 300BSQ. Find me on Bisq slack (@bernard).

**Comment by blabno** [comment]
Yes I can do that within few days.

**Comment by TwoFace12345** [comment]
Hi Bernard,That would be awesome! Are you also on Telegram? This is where the DigjByte technical community is residing if you run into any issues:t.me/DigiByteDevelopersYours sincerely, Rutger KrijnenDigiByte Awareness Team---- On Wed, 07 Aug 2019 11:15:47 +0200  Bernard Labno<notifications@github.com> wrote ----Yes I can do that within few days.

**Comment by TwoFace12345** [comment]
Hi Bernard!Where you able to add DigiByte to BISQ?Thank you!Yours sincerely, Rutger KrijnenDigiByte Awareness Team---- On Wed, 07 Aug 2019 07:21:37 +0200  Bernard Labno<notifications@github.com> wrote ----Is it ERC-20 token? 
Is it privacy coin like monero? 
Is it fork of any other coin? 
What are the wallet address validation rules?

**Comment by blabno** [comment]
Contact me on Bisq slack (@bernard).

**Comment by TwoFace12345** [comment]
Hi!I am on telegram, but will create a slack account to contact you!Yours sincerely, Rutger KrijnenDigiByte Awareness Team---- On Fri, 16 Aug 2019 16:57:07 +0200  Bernard Labno<notifications@github.com> wrote ----Contact me on Bisq slack (@bernard).
