### ISSUE TITLE
Add --clean param and button in settings to clean data directory

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#291]

**Comment by ManfredKarrer** [comment]
Only param impl. atm. as after startup a dir clean would cause problems. The removal is handled before the startup process, so all files will be created form scratch.

**Comment by cbeams** [comment]
Per aa3fc92, `--clean=true` is now accepted as a convenient shortcut for `--app.data.dir.clean=true` (just to make it as easy as possible for folks trying out the alpha, etc.)
