### ISSUE TITLE
Nullpointer Exception while startup

### ISSUE THREAD

**Issue by endurance1968** [bisq-network/bisq#2914]
Just starting (before entering passwd) I get the stack see attachement
[NullPointerWhileStart.txt](https://github.com/bisq-network/bisq/files/3316631/NullPointerWhileStart.txt)
After entering passwd app hangs in startscreen showing number of peers

**Comment by sqrrm** [comment]
@endurance1968 Thanks for the report.

I have implemented a fix. It's a bit strange that your app hangs as well so it's possible you have some additional issue though. When reproducing it on linux there was only the nullptr exception but the app doesn't hang.

Feel free to build and run from the PR at https://github.com/bisq-network/bisq/pull/2915 and let me know how it goes, or wait for the next release.
