### ISSUE TITLE
Kryptofranc Listing

### ISSUE THREAD

**Issue by NicolasChoukroun** [bisq-network/bisq#2916]
1. Asset name
Kryptofranc

2. Ticker
KYF

3. Block explorer URL
http://pool.kryptofranc.net/explorer/KYF

4. Additional technical requirements (yes/no)
no

5. Initial coin offering (yes/no)
no

**Comment by blabno** [comment]
Is it ERC-20 token?
Is it privacy coin like monero?
Is it fork of any other coin?
What are the wallet address validation rules?

**Comment by NicolasChoukroun** [comment]
We are a fork of Bitcoin 0.18 and we have a way to apply our changes to the future Bitcoin release (0.19 soon)We support SEGWITH and are compatible with lighning network with small changes.Wallet address validation rules are the same as 0.18 Bitcoin core,, via RPC.Source code is compiling for Windows/Linux and MAC here: https://github.com/NicolasChoukroun/Kryptofranc Let me know if you have any questions. Nikko 07.08.2019, 12:19, "Bernard Labno" <notifications@github.com>:Is it ERC-20 token?Is it privacy coin like monero?Is it fork of any other coin?What are the wallet address validation rules?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by blabno** [comment]
So all your wallet addresses have the same validation rules as Bitcoin?

If so then, you have to find a developer who will make research and create PR.
I can do that for 50BSQ.
