### ISSUE TITLE
Set up Jenkins builds for creating / uploading native installers

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#292]
## Motivation

The `packageNative` task in our Gradle build is used to generate native installer binaries for OS X, Windows and Linux (.deb). Currently, this task is run manually on an as-needed basis and requires bringing up virtual machines for each respective platform. In my (@cbeams) case, I run Mint Linux and Windows 8 VM's on VirtualBox running on OS X. The whole arrangement is a pain.
## Solution

Much better would be to have a Jenkins server somewhere hooked up to three machines / VMs where we can just press a button and generate / upload binaries. This is a fairly common arrangement, I think, but I've never done it myself and don't have much hands-on experience with Jenkins.
## Notes

I did look into achieving this kind of multi-os approach using Travis CI, but they've had licensing issues with Microsoft and so cannot host Windows VMs—at least not yet. The Jenkins arrangement described above would not replace our use of Travis for day-to-day CI. It would be special-purpose, just for building the binaries whenever we want to, or evenutally perhaps in a fully automated fashion based on a git tagging convention or some such.

We can probably manage hosting these servers ourselves, especially as costs should be minimal. Anyone interested can work with @btcll (Lloyd) to figure that end of things out.

**Any volunteers?**

**Comment by btcll** [comment]
I don't have experience with Jenkins but let me know how I can help with the hosting side of things :+1:

**Comment by cbeams** [comment]
Thanks Lloyd!

**Comment by notmandatory** [comment]
I've setup Jenkins before but not for multi-platform builds.  But I'll at least get a main Jenkins node setup and take a shot at the rest.   I'm using docker to setup the main node so should be quick to get going.  I'll send out a link when it's up and going.

http://jenkins-ci.org/content/official-jenkins-lts-docker-image

**Comment by cbeams** [comment]
That's great, Steve. I was just searching around again today for (cheap) jenkins-as-a-service providers that could help us out here, but came up empty-handed again. The ideal would be this:
- Job on main Jenkins node kicks off on every commit to master
- That job triggers builds on respective OS X, Windows and Linux nodes (The Linux node probably _is_ the master node)
- Each of the three platform jobs runs `gradle build packageNative`
- If any of the three platform jobs fails, the master job fails and we are notified (via email and ideally IRC)
- As each of the three jobs succeeds, the resulting platform-native installer is stored one way or another such that we (or any user) can always grab the very latest build for their platform.
- Older builds should be purged at some point, so as to avoid sucking up all disk space. Perhaps just keep the last X builds, or X days worth of builds, whatever Jenkins makes easy.
- When we're actually releasing something for general availability, I will change the version in the build configuration, and this will result in the Jenkins builds producing correctly-named artifacts, e.g. `bitsquare-0.1.0.dmg`. In order to publish these artifacts, I will just manually download them from the Jenkins machine and upload them to their respective 'release' under GitHub. (that step could be automated as well at some point later).

**Comment by cbeams** [comment]
Assigned to @stevemyers to reflect the discussion above.

**Comment by cbeams** [comment]
Oh, and one other thing—however the artifacts get stored, it would probably be ideal to avoid network activity, or at least nothing outside of a local network, so as to avoid unnecessary bandwidth costs. In the scenario described above, each push to master would result in 200-300 MB of artifacts being created, so it would be good if we're not paying for transferring that somewhere every time.

**Comment by ManfredKarrer** [comment]
To get the binary build automated would be pretty useful. I have for instance added a few important fixes (removed registration, fixe close popup bug,...) so to get those fixes out fast to the testers would be nice. UpdateFX would make it even more fluent to get our improvements fast to the user.

**Comment by notmandatory** [comment]
I've installed the docker container for Jenkins on my digital ocean server here: 

http://128.199.163.40:8080

You can login with your github credentials (via oauth).  I've installed the Gradle plugin now so it can build our project.  Thanks for the tip on the artifacts size, for now I won't push anything anywhere I'll just focus on getting things built.

**Comment by notmandatory** [comment]
I'm back from a little vacation and will be working on getting the linux native installer created this week.  I'm currently having a little problem getting gradle to find the javapackager.  Once that's resolved I'll start working on other OSs, I think I'll be able to use virtual box to run windows and OSX.

**Comment by cbeams** [comment]
Great, Steve. Thanks!

**Comment by cbeams** [comment]
Moving this back to Ready as I'm not sure whether this is still being worked on. @stevemyers, flip back to Working if indeed progress is still underway. Thanks.

**Comment by notmandatory** [comment]
I've gotten the unix build to work on my docker based jenkins.  The created file is here:

http://128.199.163.40:8080/job/Bitsquare-linux/ws/build/bundles/

Next I have the much trickier part of making builds for osx and win.

**Comment by notmandatory** [comment]
unix build works fine after removing $JAVA_HOME from the script.

http://128.199.163.40:8080/job/Bitsquare-linux/21/console

**Comment by cbeams** [comment]
Great to see the progress, Steve, thanks.

**Comment by notmandatory** [comment]
Looks like installing osx and win virtualbox vms will take alot more RAM than I want to pay for on digital ocean.  I'm going to do a quick investigation and see if I can find a way to make win + osx installers from the existing jenkins linux vm.   I'm going to try the [javafx-gradle](https://bitbucket.org/shemnon/javafx-gradle) plugin first.

**Comment by ManfredKarrer** [comment]
You can pay also per hour at digital ocean, not sure if how easy it is to switch plans then. 
But if it gets too difficult, lets wait how we get progress with updateFX. I created a branch and have impl. the client part. Just need to get it integrated to the gradle build. When we have that we will build binaries very rarely.

**Comment by cbeams** [comment]
@stevemyers wrote:

> I'm going to do a quick investigation and see if I can find a way to make win + osx installers from the existing jenkins linux vm. I'm going to try the javafx-gradle plugin first.

Hey Steve—the javafx-gradle plugin is ultimately just a wrapper around `javapackager`, so it's still required to run on the target platform, i.e. you must run on Windows to produce an .exe, etc. We were actually using javafx-gradle originally, and then I backed it out for reasons I could get into if you're interested (I'd actually like to re-introduce it, btw, just some kinks to work out).

@ManfredKarrer wrote:

> But if it gets too difficult, lets wait how we get progress with updateFX. [...] When we have that we will build binaries very rarely.

I agree that if something becomes prohibitively difficult or costly, we should reconsider the approach, but I  don't want to use UpdateFX as a long-term crutch for being unable to produce platform-specific executables in an automated fashion. In the end, we really should publish complete binaries each time we cut a release. It's just too weird otherwise—it creates a nasty experience for new users. If we don't have binaries for each release, we leave new users in a strange position where even though we just released, let's say, v0.5, the user must first download an older installer (e.g. v0.1, or one that's unversioned, which would also be weird), run it, then immediately get a message that says "a new version is available!", click that button, wait for it to download the new jar, restart the app, and then finally get going.

Really appreciate the effort Steve. Hopefully it's not too much more of a hassle. In the end, I'll continue to build the installers manually if I have to, but automation will make a huge difference.

Manfred, in any case, UpdateFX alone will handle the problem of handling user issues during wan parties and getting them to update right away with minimum effort. That's all good, and cutting a new set of platform installers wouldn't be necessary for those cases. It's really the new user experience that I'm concerned about here.

**Comment by notmandatory** [comment]
Thanks for the info, I didn't realized javafx-gradle just calls `javapackager`, docs are pretty sparse for the plugin.  For now I'll just work on creating osx and win7 virtualbox images that can act as slave builders for the main Jenkins node.  I'll host the virtualbox images on an extra PC on my home network for now.  It shouldn't be too hard to move them to the cloud when we we need to.  I expect we'll need 2-3 GB of system RAM for each one.

**Comment by cbeams** [comment]
> Thanks for the info, I didn't realized javafx-gradle just calls javapackager, docs are pretty sparse for the plugin.

Yeah, I only learned this information myself by reaching out to the plugin's creator (Danno Ferrin), who also works on JavaFX at Oracle, btw. The docs for `javapackager` suck too, though, so at least things are consistent.

> For now I'll just work on creating osx and win7 virtualbox images that can act as slave builders for the main Jenkins node. I'll host the virtualbox images on an extra PC on my home network for now. It shouldn't be too hard to move them to the cloud when we we need to. I expect we'll need 2-3 GB of system RAM for each one.

Cool. The second you run into "missing dll" issues on windows, let me know. I've spent a stupid amount of time solving that problem, and it should indeed be solved if you're using the current packaging scripts in master, but just in case it shows back up, sound the alarm.

**Comment by notmandatory** [comment]
Thanks Chris, will let you know when I run into any win installer issues.  My next steps is doing the osx image, so far I've created a Yosemite ISO and just need to get it loaded into virtualbox and setup as a Jenkins slave.  Once that's all working I'll tackle the ugly beast that is ~~win7~~ win8.1.

**Comment by cbeams** [comment]
Cool. Note that I've been building installers to date on Win8.1

**Comment by notmandatory** [comment]
OK, good to know.  I'll start with win8.1 instead of win7.

**Comment by notmandatory** [comment]
Haven't been able to get the mac osx slave node working yet.. just need to get the Jenkins node ssh access to the osx system.  Will need to take it up when I'm back from vacation.  Moving this one back to Ready until then.

**Comment by notmandatory** [comment]
current wip is here: 
https://github.com/stevemyers/jenkins
