### ISSUE TITLE
BTM untradeable

### ISSUE THREAD

**Issue by piratelinux** [bisq-network/bisq#2921]
I have two issues with BTM. First, the market price is tracking poloniex, and BTM has been delisted from Poloniex almost a year ago (so the market price will never change). This limits the price of bids/offers, even if we are not doing percentage based bids/offers.

Second, when I send a buy order to an offer or a sell order to a bid, it says I need to create an account for this type of trading pair (BTC/BTM), while I already have a BTM accoint in my altcoin accounts list.

We paid for the the 30 day trial period to try to get relisted, but the coin is untradeable, so we can't get any volume...

**Comment by piratelinux** [comment]
By the way, someone managed to buy from my offer (you can see 0.005 btc volume), but still not sure why I wasn't able to sell from a bid. They said they played with the percentage deposit values, not sure. Also, the Poloniex price tracking still needs to be fixed

**Comment by piratelinux** [comment]
I am able now to buy from a bid if I create a new account without the 1 hour limitation. The Poloniex price still shows in the window, but not sure anymore if it's limiting the trading prices; I will update you on this.

**Comment by blabno** [comment]
@piratelinux any update? can we close this issue?
