### ISSUE TITLE
Connect to another seed if current seed does not have recent BSQ blocks

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2927]
We have received several reports of clients stuck/failing to synchronize the DAO state. In most cases we suggest to restart the client to resolve the issue. This may potentially be caused by issues with some seeds not up to date with BSQ blocks, as we have encountered a few times now. As a result, we need to ensure the client is resilient enough to detect and handle issues with seed nodes.

Currently, clients will connect to another seed if one is offline. But does not handle the situation where a seed is online but does not have recent BSQ blocks.

Therefore if a client is not receiving recent BSQ blocks from the current seed node, it should disconnect from that seed node and choose another seed node. Perhaps the client can compare blockheight with the BTC nodes to determine if it is up to date.

This may also help to prevent issues with missed mailboxmessages as a seed node that does not have recent BSQ blocks is likely unstable and could prevent messages from being delivered which can lead to disputes and in the worst case to wrongly closed disputes if an important dispute msg is lost.

**Comment by ghost** [comment]
I confirm what @devinbileck writes , in the last days we had several cases like described. On the forum+slack+github. In many cases restarting is enough but this is still annoying for the users.

**Comment by freimair** [comment]
I agree on the issue.

The challenge lies in finding a suitable algorithm to decide whether we can "trust" a seed node or not. We could incorporate metrics like RTT for example, construct a set of heads for BSQBlockHeight, MailboxMessages, ... and see if one seed node is behind, consult other sources, ... Given the client (or many clients) decide that a seed node is no good - how long do stick to their decision? What if clients block a majority of seed nodes? IMHO this task is by far not trivial and I fear that we introduce more complexity and attack surface into the Bisq network dynamics than we want.

In the case of missing BSQ Blocks, an alternative approch would be for a seed node to not respond to queries as long as a sync is in progress. However, what if for whatever reason 4 out of 8 seed nodes are syncing and are therefore not available? The remaining 4 would get all the requests. Possibly even longer then necessary, as the clients do not sync themselves periodically.
