### ISSUE TITLE
Not sure what this start up error is

### ISSUE THREAD

**Issue by ablas** [bisq-network/bisq#2933]
[bisq.log](https://github.com/bisq-network/bisq/files/3348555/bisq.log)

**Comment by ripcurlx** [comment]
There seems to be an issue with a BTC transaction that isn't send out properly from your wallet. Do you get this exception every time on startup?

**Comment by a123b** [comment]
The peer got a DisputeResultMessage even though the dispute was already resolved. The disputed payout tx it creates conflicts with the payout tx that's already in the blockchain, so it can't get added to the wallet/broadcast and the DisputeResultMessage never gets removed from the mailbox.
