### ISSUE TITLE
When entering an offer exceeding the SEPA trade limit, pop-up  blocks UI 

### ISSUE THREAD

**Issue by DamageIncorporated** [bisq-network/bisq#2936]
When I enter a new offer to buy bitcoin via SEPA, that exceeds my trade limit, the information pop up opens to explain what happened. 

I can close it, but it keeps re-opening so I have no chance to correct the offending value. In my case i forgot a .0 in the BTC amount.

I am using the current .DEB version in Ubuntu Mate 18.10.

Thanks all!

**Comment by freimair** [comment]
a quick solution would be to either
- clear the field
- fill in current trade limit

**Comment by niyid** [comment]
Hi DamageIncorporated,

Please can you help drill down a bit with the actual error in the pop-up?

For instance is it something like:

**> Your payment account has been created x days ago. Your trade limit is based on the account age and is not sufficient...**
