### ISSUE TITLE
Insufficient BSQ error

### ISSUE THREAD

**Issue by Drazen-V** [bisq-network/bisq#2938]
I received the following message:
![bisq](https://user-images.githubusercontent.com/52383635/60752099-c2fb4200-9fc9-11e9-92b3-9dfb2592e999.PNG)

- This happened after I accepted an offer to buy USD. I choose the fee to be in BSQ (0.05 BSQ as shown). At this stage there was no problem, and I continued to the next screen. Then, after clicking on the "Review" button, there is a pop-up with the trade summary. When I clicked on confirm trade, it is trying to confirm and I got this message.
- I have much more that the 0.05 BSQ needed.

When I tried to buy again, the same problem occurred. When I restated the app, I couldn't even get to the Review screen: when choosing paying fees with BSQ, I got an error that I don't have enough funds (0.05 BSQ) and was suggested to use BTC for fees.

I could find the source of the problem. It is based on the fact that I have made another BTC purchase just moments before, using BSQ for fees, and that transaction was not confirmed yet. Suppose I had X BSQ in my wallet.
In DAO tab, under BISQ wallet, there are 4 fields, which showed as follows:
Available for spending: 0 BSQ
Balance of all verified UTXOs: -X BSQ
Balance of all unconfirmed change outputs: X BSQ
Balance of all unverified transactions: X BSQ

For clarification, the X BSQ that I had in my wallet are not new - I have it for some while.
All the X BSQ are in the same address.

The previous transaction I made also used 0.05 BSQ for fees, and under "Transaction" tab I could see that there is so no confirmation for it. Once this was confirmed, the issue was resolved. In particular the 4 fields from above changed to:
Available for spending: X BSQ
Balance of all verified UTXOs: X BSQ
Balance of all unconfirmed change outputs: 0 BSQ
Balance of all unverified transactions: 0 BSQ

Note that there is no reason that the entire X will not be available for trading.
Only the 0.05 that is still pending should be inaccessible. 

Related issue: https://github.com/bisq-network/bisq/issues/2678

**Comment by sqrrm** [comment]
Thanks for the detailed report. Would you be ok to share your log file with me for further investigation? Either here or to sqrrm1@gmail.com

It is likely due to your previous unconfirmed transaction using BSQ. It's a case that should be handled so I'm surprised that you're having problems, would be good to investigate further.

**Comment by Drazen-V** [comment]
Log file attached.
I copied the relevant part.
[bisq.log](https://github.com/bisq-network/bisq/files/3364903/bisq.log)

I actually had 2 earlier trades (both used 0.05 BSQ for the trading fee). But one of them was confirmed, as far as I can tell, before the second one started. So the second is the one that was not confirmed (for quite a long time), which prevented me from taking a third offer to buy BTC. The log contains information about the three transactions (eventually I did not take the third offer, as it was not available anymore).

First transaction has offer id: smfZrsU-3d6da5db-05e9-4c1b-95bd-a69b27fa206b-112
My Bisq app shows that the time of the transaction (the BSQ Trading fee transaction) was at 11:05:10 PM, at my local time.
Second transaction has offer id: 159306-3eac9509-9a8d-4aa9-9b57-d1f51229a715-112
My Bisq app shows that the time of the transaction (BSQ transaction, as well) was at 11:38:56 PM.

I think that the error I reported about is for transaction id: TDGXRK-79a49440-69ad-441a-a4ba-02f05df94995-112
(note: this transaction was not completed, due to the error reported, even though I got to the Review trade popup screen).
You can see the "Exception message: Insufficient BSQ,  missing 0.05 BSQ" message in the log file.

You may see another trade id: ocab6-18d94c9b-482f-4dd1-bf51-2302266e2313-112
This is a trade I was the maker for (the offer was placed four days earlier, and the trading fee transaction was already confirmed), and it was accepted at the same time when the error occurred.

If you need the later parts of the log, please let me know.
I am using the latest version of Bisq v1.1.2 on Windows 10.
