### ISSUE TITLE
KORE Listing

### ISSUE THREAD

**Issue by XxTheMatrix101xX** [bisq-network/bisq#2942]
Please fill in the following data to request for a new asset to be listed on Bisq. For more details, be sure to read [the full documentation](https://docs.bisq.network/exchange/howto/list-asset.html) on adding a new asset.

### 1. Asset name
KORE

### 2. Ticker
KORE (we are listed on coinmarketcap)

### 3. Block explorer URL
https://chainz.cryptoid.info/kore/

### 4. Additional technical requirements (yes/no)
I believe the answer is no. However, we are a Tor coin and Tor is packaged and managed by the KORE application 

### 5. Initial coin offering (yes/no)
no

### 6. Other Notes
Website: https://kore.life

Concerns: I noticed a question on another listing request asking if the coin was a privacy coin. we are a privacy centered coin and that is why we have Tor, I am assuming this question is meaning things along the lines of stealth addresses. KORE does not currently have stealth addresses.

Premine: KORE was not premined

Average daily trading volume (over the last year): 14BTC (on bittrex and upbit)

In preparation for the coming releases, we obtained a cover spot on the 2019 standard catalog of cryptocurrencies, very bottom right is KORE
![2019_crypto_catalog](https://user-images.githubusercontent.com/33000692/60777597-c7724880-a0f8-11e9-810b-91b20dd9474a.jpg)

Please reach out with any questions or concerns you may have, I have noticed the requested listing info has changed a lot so I am unsure if this is all you need. I would like to make this addition to your platform as painless for all involved and will make sure to regularly check in to see if requests have been made of the KORE team.

**Comment by blabno** [comment]
Is it ERC-20 token?
Is it fork of any other coin?
What are the wallet address validation rules?

**Comment by blabno** [comment]
@freimair issue can be closed as the PR is merged.
