### ISSUE TITLE
Missing BSQ in Wallet (unable to sync DAO) following two BTC purchases close together

### ISSUE THREAD

**Issue by ctonbton** [bisq-network/bisq#2950]
I bought BTC in one transaction on July 7 at 2:59PM and then bought BTC in a second transaction on July 7 at 4:08PM. 
I went to make a third purchase about 30 min later using BSQ to pay for fees and it said I had insufficient funds.  (I have plenty of BSQ available). 
I think I am experiencing the same thing as Issue #2938.
I appears that I tried buying BTC using BSQ to pay for fees too close together? Do I need to wait a few hours in between purchases?
So ever since then, I am Not able to Sync with the DAO and my Entire BSQ Wallet in the DAO shows Zero for all categories.  Again, I have BSQ in my wallet but I guess it is not showing up because I am not able to sync.
Please help. Thank you for any advice.

**Comment by ghost** [comment]
> Do I need to wait a few hours in between purchases?

From my experience, I prefer to wait that a previous transaction is 100% finished, before beginning a new one. You can monitor that in DAO/BSQ wallet/Transactions.
Usually 1 hour is enough to have this done (if you are reasonable with the fees).
But more experienced users may have another advice.

Concerning the sync, there are unfortunately issues with 1 or 2 seednodes atm, which may explain some difficulties. It should be back to normal functioning rapidly.

**Comment by ctonbton** [comment]
Thank you for the input. It has been four days since this error occurred. I have logged out and in several times but still no syncing. 
Do you think jsut wait another week?
Or do something more aggressive like  - I actualy have no idea - reload my seed words? 
Is there such a thing as Hard Reset?

**Comment by ManfredKarrer** [comment]
@ctonbton 
If you send BSQ to another user your change is not considered spendable until the block is confirmed as only then the BSQ gets verified. If you send BSQ to yourself that is not the case as it can be assumed that your don't double spend yourself ;-).

So after the block is confirmed you should be able to spend all your BSQ. In the wallet dashboard you see the BSQ which is unconfirmed. If anything is missing your wallet might be corrupted, then you need to resync the SPV chainfile (at settings/network). If the BSQ is not synced (keep progress bar at the bottom animated then try a restart. There are some stability issues with some seed nodes causing that. Should get fixed soon....

**Comment by ctonbton** [comment]
All my BSQ values on the BSQ Wallet dashboard are 0.00. 
Literally every category in my BSQ wallet is zero.  This is not correct. I own a small portion of BSQ which is definitely greater than zero.
So do you think resend the SPV chain file??? I honestly don't know what that means or how to achieve this but is it easy to do by going to settings?
Again, logging in and out has not changed the status.
Does it sound like my BSQ is "lost" because I tried to purchase BTC in two separate transactions too closely together? So the big lesson is wait at least an hour between purchases?

**Comment by m52go** [comment]
EDIT: removed my post to avoid confusion and further problems. Please follow Manfred's advice.

**Comment by ManfredKarrer** [comment]
@ctonbton No worry no BSQ are lost....
Do you see the progress bar animated at the bottom? That means that you have not received yet the BSQ blocks from the seed nodes. There have been issues over the last days but that is fixed now. So you should get the BSQ blocks delivered. Once that is not animating anymore go to the BSQ wallet to see if you see your funds. If not then got to settings/network and click resync SPV chain file. That will require 2 restarts, the app will tell you what to do. SPV resycn is very CPU heavy so expect that the app is not respoinding and CPU on 100% for a while, just leave it until a popup tells you to restart. After the restart the balance should be correct.

Do you run a local BTC node? If so it need to be a not pruned mode otherwise stop it before starting Bisq.

**Comment by ManfredKarrer** [comment]
@ctonbton  @m52go 
Do not resync the DAO state from genesis tx. We discovered yesterday an issue with that as the data are already too large to be sent from the seed node. Should be fixed with next releases...

**Comment by ctonbton** [comment]
Everything is good to go... I didn't do a single thing, LOL.
I shut my computer down overnight and turned it back on when I got back home form work.
The DAO quickly synced automatically (like it normally does) and my BSQ coins were showing up in the wallet.  Apparently the issues were fixed on the back end overnight?
All good here, Thank you to you guys for your time spent helping me with my issue. I really appreciate your concern and effort.
In the future, do you think it was an issue of making two separate purchases too close in time? or just a fluke?
Let at least a few hours pass in between purchases is a good idea?
Thanks again!!

**Comment by ctonbton** [comment]
Sorry, i closed this thread but then re-opened it so that someone might comment on my last question.
Thanks!

**Comment by ManfredKarrer** [comment]
It was probably due the issues with seed nodes.... Good to hear its resolved.

**Comment by ManfredKarrer** [comment]
> Let at least a few hours pass in between purchases is a good idea?

No need for that. You can use all the BSQ which is shown as available to spend.

**Comment by ctonbton** [comment]
Thanks for all your help!!!
