### ISSUE TITLE
Show median value in trade statistics candle popup

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2955]
The trade statistics candle popup currently shows the average, but perhaps should also show the median.

See the discussion in https://github.com/bisq-network/bisq/pull/2937 for more details. But to summarize, showing the median value would be beneficial for determining BSQ price for compensation request purposes. Using the median as opposed to average would ensure outlier trades would have a minimal influence on the determined price.

![image](https://user-images.githubusercontent.com/603793/60825976-c32e4580-a161-11e9-97a2-28cb3d8ef453.png)

**Comment by niyid** [comment]
Hello. I will like to have this assigned to me. Regards.

**Comment by ripcurlx** [comment]
@niyid I just assigned you to this issue.

**Comment by niyid** [comment]
Thanks a lot ripcurlx.
