### ISSUE TITLE
List CMBT Token 

### ISSUE THREAD

**Issue by rafaelstyvie** [bisq-network/bisq#2956]
1. Asset name
CMB Token

2. Ticker
CMBT

3. Block explorer URL
https://etherscan.io/token/0x3edd235c3e840c1f29286b2e39370a255c7b6fdb

4. Additional technical requirements (yes/no)
No

5. Initial coin offering (yes/no)
No

**Comment by rafaelstyvie** [comment]
https://github.com/bisq-network/bisq/pull/2959

I created the pull, with the tests, all compiled without problems, the previous one had reported problem in the compilation, it seems that everything has been solved.

**Comment by blabno** [comment]
PR closed due to ICO rule violation. This issue can be closed.
