### ISSUE TITLE
Receiving "Bootstrapping to p2p network failed" upon startup

### ISSUE THREAD

**Issue by gener16** [bisq-network/bisq#2965]
Cannot to connect to bisq network to access my wallet. I receive a “unsupported private_key algorithm” error and this error every time I try. I am on Windows 10, have no problems connecting to .onion links and have attempted to use all 3 bridge options. My emergency wallet balance is coming up as zero which also concerns me. I would like to find out if I can access my bitcoin wallet address so i can send my funds elsewhere, but can't seem to export my private keys and am not aware of my seed words. Please help a brother out, I bit off more than I can chew here.

https://gyazo.com/c405922b08a64f7b0cc8857ac9dd2873

**Comment by freimair** [comment]
hi,

sorry, but I have to ask you on the version of Bisq you are using? This error should have been resolved a while ago...

also, would you be so kind and provide the logs?

**Comment by gener16** [comment]
> hi,
> 
> sorry, but I have to ask you on the version of Bisq you are using? This error should have been resolved a while ago...
> 
> also, would you be so kind and provide the logs?

I am not sure how to check the version to be honest, but I downloaded the app and did the initial transfer May 6th, reinstalled it July 9th. How can I provide logs?

**Comment by ghost** [comment]
Bisq version is mentioned at the center bottom of the main window.

Bisq data directory locations, where are the logfiles:
Windows 7+ : C:\Users\<username>\AppData\Roaming\Bisq

**Comment by gener16** [comment]
I can't even open the program so I'm unable to see what the version is for sure but I reinstalled 1.1.2 64bit on Windows 10. Logs are attached! Additional info: tried connection with all three bridge options, tried disabling my antivirus/firewall (McAfee Livesafe) when starting the program but to no avail :( will throw some of this BTC to whoever can help me successfully recover these funds honestly need to pay rent bad :(

Also what program can you use to open WALLET files? I'm such an idiot haha

[bisq.log](https://github.com/bisq-network/bisq/files/3409432/bisq.log)

**Comment by ghost** [comment]
If you speak about the *.wallet files , I think that the format is protobuffer. I don't know with what to open that.
Also, 
Do you have your Bisq appli behind a firewall ?
Did you notice your seedwords somewhere ?

**Comment by gener16** [comment]
> If you speak about the *.wallet files , I think that the format is protobuffer. I don't know with what to open that.
> Also,
> Do you have your Bisq appli behind a firewall ?
> Did you notice your seedwords somewhere ?

I do have my Bisq behind my firewall, and I'm not sure where my seedwords are, where can I find them?

**Comment by ghost** [comment]
Concerning seed words, you already got answers in https://bisq.community/t/bootstrapping-to-p2p-network-failed/7816/11
If you didn't write them somewhere, nobody else has done it for you.

My guess is that your current connexion issues come from your firewall.

**Comment by gener16** [comment]
Yup that's me being lazy as hell, my bad. If I disable my firewall and I still cannot start up the program does that just mean I'm screwed?

**Comment by freimair** [comment]
Since we did not hear from you in about a week, I assume that anything is good again?

**Comment by gener16** [comment]
Nope, just a lazy depressed pos with no luck. Here are the logs from when i tried with 1.1.3 but I fear the worst.
[bisq.log](https://github.com/bisq-network/bisq/files/3438844/bisq.log)

**Comment by freimair** [comment]
ok, and no, there is no reason to fear the worst.

Take a look in `C:\Users\18472\AppData\Roaming\Bisq\btc_mainnet\tor\hiddenservice`. There you should find two files `private_key` and `hostname`. Are the files readable, i.e. can you open them in a text editor? (do NOT post the contents here!) In any case, back up these files.

In case the files are broken (or in any case) shut down your bisq application.
There should be a folder `backup` in that very directory. Find an old (intact) private_key-file there, copy the file to `C:\Users\18472\AppData\Roaming\Bisq\btc_mainnet\tor\hiddenservice` and rename the file to remove the timestamp (for example `1546511406807_private_key` -> `private_key`). Restart your Bisq application. Does it work?
