### ISSUE TITLE
Connection issues: Unreadable Wallet Exception

### ISSUE THREAD

**Issue by Drazen-V** [bisq-network/bisq#2966]
I cannot connect to the app on my Mac.

Getting the following messages:
<img width="1201" alt="Screen Shot 2019-07-15 at 1 28 03 PM" src="https://user-images.githubusercontent.com/52383635/61272020-c1423300-a7ae-11e9-9d71-c99218ed565c.png">
<img width="1202" alt="Screen Shot 2019-07-15 at 12 29 54 PM" src="https://user-images.githubusercontent.com/52383635/61272026-c4d5ba00-a7ae-11e9-86d1-735a080236c4.png">

The app has worked in the past, and I have not changed any configuration, including the wallet (so it tries to open a wallet that already exists).

Seems to be a known issue: https://github.com/bisq-network/bisq/issues/2797
Though as you can see above, the error I'm getting is "Could not connect" (while the previous issue had "Wallet contained duplicate transaction".

Also related: https://github.com/bisq-network/bisq/issues/2850

**Comment by freimair** [comment]
is this still relevant?
