### ISSUE TITLE
Could not find javafx-graphics-freebsd.jar

### ISSUE THREAD

**Issue by yurivict** [bisq-network/bisq#2969]
While trying to create the FreeBSD port for ```bisq```, I got this error:
```
* Where:
Build file '/usr/ports/finance/bisq/work/bisq-1.1.3/build.gradle' line: 264

* What went wrong:
A problem occurred evaluating root project 'bisq'.
> Could not resolve all files for configuration ':core:testCompile'.
   > Could not find javafx-graphics-freebsd.jar (org.openjfx:javafx-graphics:11).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/openjfx/javafx-graphics/11/javafx-graphics-11-freebsd.jar
   > Could not find javafx-base-freebsd.jar (org.openjfx:javafx-base:11).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/openjfx/javafx-base/11/javafx-base-11-freebsd.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0/userguide/command_line_interface.html#sec:command_line_warnings
```

I have the ```openjfx8-devel``` package installed:
```
$  pkg info -l openjfx8-devel
openjfx8-devel-8.u172.b11_7,1:
	/usr/local/openjdk8/bin/javafxpackager
	/usr/local/openjdk8/bin/javapackager
	/usr/local/openjdk8/jre/lib/amd64/libavplugin.so
	/usr/local/openjdk8/jre/lib/amd64/libdecora_sse.so
	/usr/local/openjdk8/jre/lib/amd64/libfxplugins.so
	/usr/local/openjdk8/jre/lib/amd64/libglass.so
	/usr/local/openjdk8/jre/lib/amd64/libgstreamer-lite.so
	/usr/local/openjdk8/jre/lib/amd64/libjavafx_font.so
	/usr/local/openjdk8/jre/lib/amd64/libjavafx_font_freetype.so
	/usr/local/openjdk8/jre/lib/amd64/libjavafx_font_pango.so
	/usr/local/openjdk8/jre/lib/amd64/libjavafx_iio.so
	/usr/local/openjdk8/jre/lib/amd64/libjfxmedia.so
	/usr/local/openjdk8/jre/lib/amd64/libjfxwebkit.so
	/usr/local/openjdk8/jre/lib/amd64/libprism_common.so
	/usr/local/openjdk8/jre/lib/amd64/libprism_es2.so
	/usr/local/openjdk8/jre/lib/amd64/libprism_sw.so
	/usr/local/openjdk8/jre/lib/ext/jfxrt.jar
	/usr/local/openjdk8/jre/lib/javafx.properties
	/usr/local/openjdk8/lib/ant-javafx.jar
	/usr/local/openjdk8/lib/javafx-mx.jar
	/usr/local/openjdk8/lib/packager.jar
	/usr/local/share/licenses/openjfx8-devel-8.u172.b11_7,1/GPLv2
	/usr/local/share/licenses/openjfx8-devel-8.u172.b11_7,1/LICENSE
	/usr/local/share/licenses/openjfx8-devel-8.u172.b11_7,1/catalog.mk
```

Please advise how to proceed.

**Comment by ghost** [comment]
Hello,
Please read https://github.com/bisq-network/bisq/blob/master/docs/build.md

> You will need **OpenJDK 10** installed and configured as the default system JDK to complete the following instructions. See the scripts directory for scripts that can be used to install and configure the JDK automatically.

**Comment by yurivict** [comment]
I have both OpenJDK 8 and 12 installed:
```
openjdk8-8.212.4.1             Java Development Kit 8
openjdk12-12.0.1+12.2          Java Development Kit 12
```

How do I make the build use openjdk12 (the latest one) over openjdk8?

**Comment by ghost** [comment]
afaik, atm openjdk10 is **mandatory** .
It's the only openjdk with which Bisq can work actually.

I ping @devinbileck , maybe he knows more on this topic.

**Comment by yurivict** [comment]
OpenJDK was released in 2018, and is now considered obsolete. We have these OpenJDK packages, 10 was even skipped:
```
openjdk6-b45,1                 Oracle's Java 6 virtual machine release under the GPL v2
openjdk-7.161.01,1             Java Development Kit 7
openjdk8-8.212.4.1             Java Development Kit 8
openjdk11-11.0.3+7.2           Java Development Kit 11
openjdk12-12.0.1+12.2          Java Development Kit 12
```

**Comment by ghost** [comment]
see https://jdk.java.net/10/
I have openjdk10 installed, and I can build Bisq with it.

**Comment by niyid** [comment]
Hi Yuri,

Use the update-alternatives command to switch your JDK to version 12. Refer to the page below for details:

https://www.debian.org/doc/manuals/debian-java-faq/ch3.en.html

**Comment by yurivict** [comment]
@niyid This command is for Debian, and I am on FreeBSD.

It should be switchable through the environment variables, or gradle keys, or something like this, because I am trying to build a package, and it should work when OpenJDK 12 is present regardless of what else is installed.

**Comment by niyid** [comment]
Ah, I see. OK, first can we know which of your Java installations are being referenced by checking for $JAVA_HOME variable? What does that point at? Also what do the commands "javac -version" and "java --version" display?

**Comment by wiz** [comment]
@yurivict Hey Yuri. Unfortunately Bisq requires javafx which doesn't support FreeBSD - however I kinda got Bisq working by installing the OpenJDK 10 for Linux on FreeBSD and enabling Linux compatibility, along with a bunch of random hacks to get it to start... I'm not sure Bisq can officially support FreeBSD anytime soon, at least using native OpenJDK for FreeBSD, mostly because it depends on javafx and other things which do not support FreeBSD at all. If you're interested in experimenting with my hacks let me know and I'd be happy to share them, but for now I think we need to close this issue because javafx-graphics simply does not support FreeBSD at all.

**Comment by ripcurlx** [comment]
Closing issue based on https://github.com/bisq-network/bisq/issues/2969#issuecomment-523539896

**Comment by wiz** [comment]
I've since gotten Bisq seednode (headless daemon) running on FreeBSD and at some point will get the full GUI working too... once it's solid I will try to get an official release going for it
