### ISSUE TITLE
List Nano (Nano)

### ISSUE THREAD

**Issue by jgcastro1985** [bisq-network/bisq#2970]
1. Asset name
Nano

2. Ticker
NANO

3. Block explorer URL
nanode.co

4. Additional technical requirements
No

5. Initial coin offering
No

**Comment by jgcastro1985** [comment]
Official project URL:
https://nano.org

Official block explorer URL: https://www.nanode.co

**Comment by blabno** [comment]
Is it ERC-20 token?
Is it privacy coin like monero?
Is it fork of any other coin?
What are the wallet address validation rules?

**Comment by jgcastro1985** [comment]
@blabno
No.
No.
No.
Sorry, I don't know.

**Comment by blabno** [comment]
You have to find a developer who will make research and create PR.
If you deliver me the wallet address validation rules then I can do that for 200BSQ.
If I have to do the research it will be 500BSQ.

**Comment by jgcastro1985** [comment]
@blabno
Look this link: https://www.npmjs.com/package/cryptocurrency-address-validator

**Comment by blabno** [comment]
Contact me on Bisq slack: @bernard
