### ISSUE TITLE
The timezone and time standard

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#2971]
This is the DAO Genesis transaction

bsqAmount | burntFee | height | outputsNum | time | txId | txType | txTypeDisplayString | Date
-- | -- | -- | -- | -- | -- | -- | -- | --
365748000 | 0 | 571747 | 227 | 1555340856000 | 4b5417ec5ab6112bedf539c3b4f5a806ed539542d8b717e1c4470aa3180edce5 | GENESIS | Genesis | 15/04/2019 15:07:36

But under DAO > GOVERNANCE > VOTE RESULTS it says

Cycle | Proposals | Votes | Vote Weight | Issuance | 
-- | -- | -- | -- | -- |
 Cycle 1 started: Apr 15, 2019 4:07:36 PM | 32 | 236 | 442007.82 BSQ | 69318.63 BSQ |

I think the standard should be UTC and [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)

**Comment by niyid** [comment]
Hi Huey,

The date you posted under "Cycle" column shows "Apr 15, 2019 4:97:36 PM". I am quite curious because of the time "4:**97**:36 PM". Was that a typographical error or it was exactly as shown? I refer to the "97". I assume this is a typo and you meant "4:07:36".

**Comment by huey735** [comment]
@niyid you're correct.

**Comment by niyid** [comment]
Ah.

I believe you are suggesting that the time should be UTC when a particular flag is false (default) and of course use the default local time if same flag is true.

**Comment by huey735** [comment]
I'm not going that far because I don't know Java. Is Bisq currently taking into account the client's timezone or is it a static value? I assumed it was a static value because of the 12h time format. My proposal is to change that timezone to UTC.

**Comment by niyid** [comment]
It does take the user's timezone into consideration. I had earlier posted some code but then realized you may not be familiar. It uses a flag called "useLocaleAndLocalTimezone" which when set to false, the timezone is UTC but then uses the US locale; and when this flag is true, the timezone is the default and the locale is the user's set locale.

**Comment by huey735** [comment]
@niyid should this flag appear when I type ```Bisq --help``` ? What is the default value?

PS: The ```Bisq --help``` works on some machines and not in others. And parameters like ```--dumpStatistics``` and ```--daoActivated``` will work for one directory and not the other. Not sure why.

**Comment by niyid** [comment]
Sorry for the delay. I refer to "flag" in the code and not command line. But I believe the time reported under Cycle column in DAO > GOVERNANCE > VOTE RESULTS is UTC.
