### ISSUE TITLE
Request for reimbursement for cancellation of order sffoee5

### ISSUE THREAD

**Issue by xandermccormick** [bisq-network/bisq#2974]
I was advised by the support team to ask for reimbursement of fees occurred for OrderId:  sffoee5-10050a30-f2b6-4390-902e-4782c77b3ab3-112

According to support, tx was bugged and we had to cancel the offer.

**Comment by m52go** [comment]
@xandermccormick reimbursement requests are handled in the support repository. Please reopen your case there—the issue template there specifies everything required to process the reimbursement.

https://bisq.slack.com/archives/C8MNJRADP/p1563326293069700
