### ISSUE TITLE
Error closing the ticket

### ISSUE THREAD

**Issue by arbitrator2** [bisq-network/bisq#2978]
<img width="1214" alt="Captura de pantalla 2019-07-19 a las 10 30 14" src="https://user-images.githubusercontent.com/52173515/61521971-a4596a00-aa11-11e9-9191-dd7697ef35ce.png">

Error closing the ticket. I get this message when trying to close. Please let me know what I can do from here.

**Comment by ghost** [comment]
Does your pseudo correspond to https://bisq.community/u/arbitrator2/summary ?

**Comment by arbitrator2** [comment]
yes

**Comment by freimair** [comment]
please let us have the log files. without them, it is virtually impossible to see what went wrong and suggest a fix. Thanks!
