### ISSUE TITLE
Add a Altcoin Account

### ISSUE THREAD

**Issue by goblinpool** [bisq-network/bisq#2979]
hello , i want to buy ParsiCoin with BTC but i can't set up a PARS account on Account>>Altcoin Accounts section, isn't it supported?!

**Comment by goblinpool** [comment]
i noticed that so many altcoins are missing from this section, so how should we set up accounts and trade?

**Comment by ghost** [comment]
@goblinpool 
Which Bisq version do you have ?
In my Bisq v1.1.3 (released this week), ParsiCoin is in the Settings/Preferences/Add Altcoin list

This is however a bit strange, since PARS is marked as <code>delisted due to inactivity</code> in the DAO/Asset listing tab.

**Comment by blabno** [comment]
Nobody traded that asset for too long. You can re-list it by paying a fee https://docs.bisq.network/exchange/howto/list-asset.html#inactive-assets-will-be-de-listed
