### ISSUE TITLE
Unable to paste receive address with ⌘-V in "Withdraw your bitcoins" section

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#298]
Repro steps:
1. Place an offer to buy bitcoin
2. Have a trading partner take your offer
3. Wait for blockchain confirmation
4. Start payment
5. Wait for payment confirmation
6. When the trade status reaches "Trade successfully completed", scroll down to "Withdraw your bitcoins"
7. From your bitcoin wallet (Bitcoin-Qt in this example), click Recieve->Request payment->Copy address
8. In a textfile or on the command line, press ⌘-V to confirm that the receive address has actually been copied to your clipboard
9. Go back to Bitsquare, and press ⌘-V in the "Withdraw your bitcoins" field.
10. Notice that nothing happens.
11. Right click on that same field and select 'paste' from the context menu.
12. Notice that the receiving address is pasted as expected.
13. Click Withdraw to external wallet to complete the process.

The expected behavior is that ⌘-V would paste the address. The actual behavior is that the user must explicitly select `paste` from the right-click context menu. A pretty significant usability issue, actually!

**Comment by ManfredKarrer** [comment]
Hm... just tried to reproduce it on imac and win 7 but all worked. have never seen that before. can you try if you get paste issues in other areas (create offer, offer book filter)?

**Comment by cbeams** [comment]
Will try, yes, but note that I've experienced this issue consistently over months (should have reported it!) and only with that field. For example I've never had the same problem with pasting values into the deposit fee address text field.

**Comment by ManfredKarrer** [comment]
hm, maybe u can shot me that on screensharing? maybe its realted to the validation which displays an error when the field/app lose focus, which needs to be fixed.
