### ISSUE TITLE
Does blocking SEPA sending with Revolut really make sense?

### ISSUE THREAD

**Issue by rekcus2** [bisq-network/bisq#2982]
I have been reading up on the issue a bit and on top of the many engagements to let the user decide and just display and warning about the issue banks seem to have I have seen someone say its about receiving on that BIC and **not sending** from it to another bank.

Its just anecdotal evidence but I had no issues with two trades I made on Localbitcoins and would prefer to use Bisq for buying BTC with SEPA because apart from the fact that my new Revolut account has a pathetic low limit of 0.01 BTC there are always just a few revolt trades on and way more SEPA trades.

So are there any confirmed and regular issues with sending from Revolut SEPA? I think sending should be allowed at least unless I hear some convincing arguments against it.

Also some time has passed maybe Banks have learned and the BIC issues have been solved? I know it took ages for me to be able add it to PayPal (may have been totally unrelated issues but I had a "try later" for about a week) but eventually it worked out and the transfers there are super fast.

https://transferwise.com/us/swift-codes/bic-swift-code-checker validates my BIC that starts with REVO perfectly fine for both sending and receiving.

**Comment by ManfredKarrer** [comment]
Is using Revolut giving you a dedicated IBAN? If you can proof that you have sent the EUR (IBAN what receiver sees need to be same as the one you have set up in your account) it might be ok. I think there is still some extra risks as there is some option to fund your Revolut account with credit card, which seems a honeypot for cc fraudsters to use that and then cash out via SEPA.

**Comment by rekcus2** [comment]
I never thought about IBANs not being dedicated I am pretty sure they are I got a GB... EUR account and I am curious if I would be even legal and make any sense for them to have multiple customers share same IBAN but I after a quick search I could not find anything that clearly states that IBANS are unique.

I actually want to test it but I currently can not add my own other banks IBAN to Revolut as the app stays stuck after I enter the confirmation code or gives me a error message. This may have to do with the fact that I am using a custom AOSP based rom on my phone and there are no google play services but it worked b4 on a older version and now even downgrading the app wont work. I just spend hours trying to get this fucking app running in a emulator and same issue on top of it there seems to be a specialized build of the up to date version that my phone is downloading through the aurora store but on the emulator it only shows a outdated version.

Anyway I can't test it now with my own other SEPA account, not sure why it does not let me add my own bank as a recipient but as I said it worked fine b4 when I send money to people on Localbitcoins.

Also how am I supposed to prove to you that I can send money with my IBAN? So you want me to reveal my ID to you? You want to give me a account I send a test amount to?

Interesting side-node. My other bank changed their online banking system recently and the modernized one does not let me enter the BIC at all and forces auto detected values on me. But upon entering my GB... Revolut IBAN it detects the BIC just fine so would be curious how many people actually still have or have this issue of wrong BIC numbers. I saw a issue about that and it sounded like that was the reason for disabling it. But again I am just asking for you to enabled sending not receiving. I did not send anything but I think its save to assume that sending to it in my case works perfectly as it should and so does it with PayPal and CC.

One thing is for sure Revolut sucks big time, website accounting is artificially restricted so we fools get their stupid app that has **8 trackers in it**. Only business customers get a web-interface ... why would I want to carry my banking with me on a stupid spy device? Makes no sense to me.

I do not understand how this relates to cc fraudsters. What the difference if they can cache out BTC with revolut to revolut transfers as opposed to caching out BTC with SEPA to SEPA transfers? They can fund their Revolut with CC either way so I do not see how disabling SEPA helps with that.

**Comment by rekcus2** [comment]
Not dropped.

**Comment by rekcus2** [comment]
@stale Stop trying, bitch.

**Comment by ghost** [comment]
It seems that Revolut **does** provides IBAN for both SEPA and SWIFT. I just found out by accident.

<img src="https://user-images.githubusercontent.com/383295/82736457-3ca73600-9d2a-11ea-84d0-cea4d28baed9.png" width="350"/><img src="https://user-images.githubusercontent.com/383295/82736469-50529c80-9d2a-11ea-86b8-e8b542587fc0.png" width="350"/>

So I believe it is possible to trade with it.

**Comment by ghost** [comment]
Ok, now I understand whats the issue:

![image](https://user-images.githubusercontent.com/383295/82736919-5d24bf80-9d2d-11ea-8312-eaed3b77dad2.png)

**Comment by ghost** [comment]
I will try to send some 10 EUR back and forth between my bank acc in EUR and Revolut EUR account. Ill post some screenshots as proof once payments arrive.

**Comment by p3yot3** [comment]
Using Revolut is generally dangerous - the amount of accounts they are locking is staggering & there's absolutely no customer support coming from them - they've even abandoned their own forum, so I'd stay well clear of them TBH. Exit scam incoming.

**Comment by ghost** [comment]
@p3yot3 My experience with Revolut was OKish so far. Both trading and using the card all around the world. Can you provide any sources to those truly worrying news?

**Comment by p3yot3** [comment]
> @p3yot3 My experience with Revolut was OKish so far. Both trading and using the card all around the world. Can you provide any sources to those truly worrying news?

Sure, check out their (censored) abandoned forum, their twitter account, reddit & everywhere else on the internet.

**Comment by ghost** [comment]
I have tried it and I can confirm I was able to send EUR back and forth between Revolut and my Bank Account via SEPA.

**Comment by ghost** [comment]
Non-blackend screens available on request for core-bisq members.

![image](https://user-images.githubusercontent.com/383295/83460389-91ebf180-a466-11ea-8961-277a45fde1c9.png)
![image](https://user-images.githubusercontent.com/383295/83460576-06269500-a467-11ea-9f67-217db66ae7b3.png)

**Comment by nonitex** [comment]
2 years passed, Revolut is still around, SEPA is working, but it's still not allowed on Bisq to receive a SEPA transfer with a Revolut BIC because it wasn't universally recognised back in 2018.

It made no sense to prohibit it then, even less sense to not allow it now.

There's currently 30 offers on Bisq for SEPA, but only 9 for Revolut, not mentioning the spread and amounts, but I can't use SEPA for Revolut because some banks did not recognise the BIC back in 2018.

Isn't it time to support it?

**Comment by pazza83** [comment]
Hi the issue is that many banks treat sending to, or receiving from, Revolut SEPA BIC accounts with more caution leading to more trades being held up or cancelled due to banks.

We recently also banned the SEPA Faster Payment accounts for GBP for similar reasons.

I think Revolut accounts are not best suited for trading on Bisq unless using the Revolut to Revolut payment options.

Maybe look at alternatives to SEPA for Revolut, such as Wise or a more traditional SEPA account.

**Comment by FreddieChopin** [comment]
So it's 2023, Revolut still cannot be used, but it has a very nice feature for non-EUR countries - Revolut supports "SEPA instant", which is never a case for "normal" EUR bank accounts in non-EUR countries.
