### ISSUE TITLE
Error upon startup: java.io.IOException

### ISSUE THREAD

**Issue by gener16** [bisq-network/bisq#2984]
* Off Windows 10 64 bit OS
* No problems connection to .onion links
* Have tried using all bridge options to start-up
* Cannot access emergency funds and wallet is not initialized, seed words have not been written down :(
* Bisq is behind my firewall, McAfee LiveSafe

Please help a brother out, have a decent amount of bitcoin on my local harddrive and will send some out to anyone that can help me regain access to it.

https://gyazo.com/adc025407ef6ef59f4c4654d80f6cb3a

**Comment by huey735** [comment]
Try to disable your antivirus, reboot the computer and launch only Bisq. Use the default options, no bridges. On inside the wallet, do write down your seed.

**Comment by gener16** [comment]
> Try to disable your antivirus, reboot the computer and launch only Bisq. Use the default options, no bridges. On inside the wallet, do write down your seed.

This did not work, upon startup I received an "Unsupported private_key algorithm" error message.

**Comment by huey735** [comment]
Hum, that was supposed to have been corrected with this PR - https://github.com/bisq-network/bisq/pull/2581

Are you using the latest version (1.1.3)?

**Comment by gener16** [comment]
Nope, was on 1.1.2, will give it a try

**Comment by freimair** [comment]
if 1.1.3 does not help, would you care to share the logs?

**Comment by gener16** [comment]
Yes, no lucky unforunately. Thank you for your help.
[bisq.log](https://github.com/bisq-network/bisq/files/3438843/bisq.log)

**Comment by ghost** [comment]
> Bisq is behind my firewall, McAfee LiveSafe

My guess is that this is the problem.

Last lines of your logfile :
<pre>
Tor started after 13119 ms. Start publishing hidden service.
################################################################ 
Jul-24 22:20:52.828 [NetworkNode-9999] ERROR b.n.p.n.TorNetworkNode: Could not connect to running Tor: Unsupported private_key algorithm. Did Tor get a new key type for hidden services? 
Jul-24 22:20:52.830 [JavaFX Application Thread] ERROR b.c.a.P2PNetworkSetup: onSetupFailed 
</pre>

**Comment by gener16** [comment]
Thank you Harry, will try to uninstall it or completely disable it and run bisq after restarting,

**Comment by ripcurlx** [comment]
I think this was fixed already in one of our releases since then. Please re-open this issue if you still have this problem.
