### ISSUE TITLE
Unable to place an offer

### ISSUE THREAD

**Issue by frn13** [bisq-network/bisq#2987]
<img width="1000" alt="Screenshot 2019-07-18 at 7 32 13 PM" src="https://user-images.githubusercontent.com/53206060/61682685-268faa00-ad02-11e9-84d5-07e4b9427087.png">
I’ve created an account, funded it with BTC but every time I’m trying to place an offer I get an error message saying: Element at index 0 is null, restart your application, check network connection…
This has happen for the third time now (never been successful). Maker fees and network fees are always lost.
Many thanks!

**Comment by frn13** [comment]
There is the log file if someone finds it helpful.

[bisq copy.log](https://github.com/bisq-network/bisq/files/3422801/bisq.copy.log)

**Comment by christophsturm** [comment]
investigating

**Comment by christophsturm** [comment]
are you using a binary or are you building from git? if you build from git, can you try to build master and post the new error log?
