### ISSUE TITLE
Improve burned BSQ chart

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2990]
The chart in the app for showing burned BSQ (fees) over time is not very informative atm as it shows a monthly data poit only. I think daily data points would be better (or use a date scope like in the trade charts).

<img width="1070" alt="Screen Shot 2019-07-23 at 19 05 34" src="https://user-images.githubusercontent.com/1449498/61732071-1668e080-ad7d-11e9-97de-405dda4ae750.png">

**Comment by meapistol** [comment]
Connected with this, the y-axis of BSQ issued chart does not start on 0 which makes it highly misleading/difficult to read.

**Comment by ghost** [comment]
I believe that this issue was solved in #3753 I suggest to close it.
