### ISSUE TITLE
Transaction stuck x2 "Waiting on blockchain confirmation"

### ISSUE THREAD

**Issue by slipperybeluga** [bisq-network/bisq#2992]
I have had several successful transactions on Bisq, but my most recent two have failed. One was closed by an arbitrator after being stuck for days, the other appears to be suffering from the same issue but is less than 24h into the process, so figured I would reach out now. 

**OS:** Ubuntu 
**Version:** Bisq 1.1.3

### Current transaction: 
I am maker, someone accepted my offer. Transaction is stuck at step 1, "waiting on blockchain confirmation". Here are the transaction IDs:
Maker fee and transaction ID: 7776cdb450fca41280b7a454d38f151a8f34bd0200e2ea25672f9ce4da2b084d **0 confirmations and seen by 0 peers**
Taker deposit: 94fd957be96751f9cfb9af82ea869a282c45dd930ee9c4088358def00b7be375 **successful with numerous confirmations**
Maker deposit: f825fe4032b79a28e5359e14dd29ef800d61d30729854036e79188f8d157b1db **0 confirmations and seen by 0 peers**

Despite my deposit and fee having 0 confirmations and seen by 0 peers, the funds have been debited from my wallet and show up in my transactions tab (albeit with zero confirmations). Why is this? What puzzles me is that there is no peer acknowledgement.I'm online 24h and connected to peers every time I check bisq. I would assume that there should be peers acknowledging the transfer of funds even if we are still waiting on blockchain confirmation(s). 

### Previous transaction (which was canceled by arbitrator):
Similar issue, but in this case my maker fee was processed but I did not get blockchain confirmation (or peer acknowledgement) for my deposit, despite it being debited from my wallet and SIX DAYS passing. 
Maker fee: 166a29e194ae7768d08bf73e859b6119fa528d3afd67ca9c319ec18ed0fde237 (confirmed in 2000+ blocks)
Taker fee: d15b73149335b9d5872fa91b7757333ddb68979d3b1b2935c224f3f36a537297 (0 confirmations, 0 peers)
Maker deposit: f502ecddffafeca56598c00369ef4c9d694bc9f0dc8ad5f376636879e7a76859

Arbitrator reply: 

> The deposit transaction has not been created because of a bug. No funds have left your wallet even if the UI shows that. After the dispute is closed you should have all your funds as expected. You can ask for reimbursement for the lost trade fee at: https://github.com/bisq-network/support/issues/

Anyone have an idea what the problem is? Could it be related to the upgrade from 1.1.2 to 1.1.3? I successfully completed a transaction as taker since then, but now have two stalled transactions as maker since the update. I really hate to waste my time for days on end, miss out on favorable market conditions, and drag along other individuals in failed transactions.

**Comment by huey735** [comment]
This issue is older than v.1.1.2. What seems to happen is that the transaction is not broadcast at all.
https://bisq.community/t/major-bug-in-bisq-transactions-not-broadcasting-and-timing-out/7478/7 
https://bisq.community/t/my-multisig-payout-isnt-getting-broadcasted-hangs-at-0-confirmations/311/9

So the funds haven't left your wallet at all. Try to follow the advices @ManfredKarrer shares in those threads to see if it wolves the problem. But start by making a backup.

**Comment by slipperybeluga** [comment]
Thanks, Huey. I'll take a look and report back. Did a cursory search before posting but must not have had the right keywords.

**Comment by slipperybeluga** [comment]
> This issue is older than v.1.1.2. What seems to happen is that the transaction is not broadcast at all.
> https://bisq.community/t/major-bug-in-bisq-transactions-not-broadcasting-and-timing-out/7478/7
> https://bisq.community/t/my-multisig-payout-isnt-getting-broadcasted-hangs-at-0-confirmations/311/9
> 
> So the funds haven't left your wallet at all. Try to follow the advices @ManfredKarrer shares in those threads to see if it wolves the problem. But start by making a backup.

I've deleted my Tor files and resynced the SPV chain. Hasn't helped the problem. 

I'm trying to follow the advice in the link you provided, "https://bisq.community/t/major-bug-in-bisq-transactions-not-broadcasting-and-timing-out/7478/3", but I am unsure how to proceed. 

The user who wrote the post resolved his problem by deleting their "roaming folder" (i don't know what that is) and "made a new seed" (which @ManfredKarrer also suggests due to wallet db corruption). I'm not sure how to do this either. I would like to preserve this stuck transaction if possible and complete it and don't want to jeopardize any other aspects of my account. Can you explain how to create a new seed? It seems like I will need to transfer all funds to an external wallet, then delete my Bisq wallet files and transfer all funds back to new wallet. That is very messy, I'm hoping there is a simpler way that I am not thinking of. Thank you!

**Comment by huey735** [comment]
@slipperybeluga Start by making a backup.
This is where you can find your Bisq directory - https://docs.bisq.network/backup-recovery.html#back-up
and this is the process to move to a new directory - https://docs.bisq.network/backup-recovery.html#switch-to-a-new-data-directory

**Comment by slipperybeluga** [comment]
> @slipperybeluga Start by making a backup.
> This is where you can find your Bisq directory - https://docs.bisq.network/backup-recovery.html#back-up
> and this is the process to move to a new directory - https://docs.bisq.network/backup-recovery.html#switch-to-a-new-data-directory

The above resolved my issue, thank you @huey735  for your time. Unfortunately the solution causes you lose all of your open trades and offers. I hope this issue is resolved in the future as it is highly discouraging, and there are already many barriers to use of Bisq, this can be enough to shake someone's faith and cause them to discontinue using it.

**Comment by huey735** [comment]
@slipperybeluga How were you able to move the funds out of the wallet?
Make sure to [issue a reimbursement request ](https://github.com/bisq-network/support/blob/master/.github/ISSUE_TEMPLATE/reimbursement-template.md) to get back your trading fees.
