### ISSUE TITLE
Listing new token (BCN20)

### ISSUE THREAD

**Issue by kategouldcr** [bisq-network/bisq#3006]
### 1. Asset name
Bytecoin 20 
https://gateway.bytecoin.org/

### 2. Ticker
BCN20

### 3. Block explorer URL
https://etherscan.io/
Example: https://etherscan.io/block/8214205

### 4. Additional technical requirements 
No

### 5. Initial coin offering 
No

**Comment by blabno** [comment]
Is it ERC-20 token?
Is it privacy coin like monero?
Is it fork of any other coin?
What are the wallet address validation rules?

**Comment by kategouldcr** [comment]
It is ERC-20 token.
It is not a privacy coin like Monero or Bytecoin.
It is not a fork but it is made by the BCN developers to facilitate cross-chain expansion.
There are various ways to validate the wallet address. If it's possible, we could contact you directly for more details.

**Comment by blabno** [comment]
You will need a developer (could be yourself) to create a pull request with necessary code changes.
If you can't find anyone then contact me on Bisq slack (@bernard).
