### ISSUE TITLE
Label in notification icon on windows not centered

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#301]
Seems a font problem on windows

**Comment by ManfredKarrer** [comment]
Check font usage (if it is embedded)

**Comment by haiqu** [comment]
Which icon is that? They all look good here.

**Comment by ManfredKarrer** [comment]
I think thats already fixed...

**Comment by haiqu** [comment]
Cool, we're cleaning up this bug list fast!
