### ISSUE TITLE
Bisq UI doesn't work well on vertically oriented monitors

### ISSUE THREAD

**Issue by fresheneesz** [bisq-network/bisq#3012]
For a monitor with ~~1800~~ 1000 pixels in width, all the top-menu items are cut off with "...":

![Bisq thin screen](https://user-images.githubusercontent.com/149531/61999052-0ea38780-b06e-11e9-82fa-c94880e92a8b.png)

I would suggest moving the white balance bar up or down to make room for the green menu items in this case rather than cutting off the menu titles.

**Comment by cd2357** [comment]
At 1800px width, the top bar looks good for me. It fits entirely and no text is cutoff.

Is 1800px the width of the monitor or of the resolution you're using?

(The screenshot has about 1000px width)

**Comment by fresheneesz** [comment]
My mistake, I did mean 1000px width.
