### ISSUE TITLE
Please raise trade limits

### ISSUE THREAD

**Issue by fresheneesz** [bisq-network/bisq#3013]
2 BTC maximum is not enough for larger traders, and 0.5 BTC maximum for bank transfers and 0.25 BTC for things like Zelle is far too little. What gives? Why are there drastically different limits for every payment method? 

There needs to be some way for users to get larger limits, either by using the system for longer or by being vouched for by existing users. Also, why is the limit listed in BTC? Shouldn't a less volatile unit of account be used, if you're gonna hard code this stuff into the client?

Almost every single time I see people recommend Bisq, this comes up as a frustration and a reason people aren't using it.

**Comment by huey735** [comment]
Bisq may seem too paternalistic and I sympathize with the argument. But I'm not sure if I'm fully on board.
The limits, for fiat markets, are in place to protect against chargeback and fraud risks. There's [this proposal](https://github.com/bisq-network/proposals/issues/93) in place that will try address some of the issues. But for most fiat payment methods you do have increase your trade amount limit as the Account age increases (they probably are still too low for your taste). 
The limits for altcoin markets, I imagine, are in place to protect against the other week chains' reorgs, confirmation time and price volatility.
I believe were not for these limits, Bisq would get even more bad rep for perceived errors in its architecture when the truth would probably be that the traders hadn't measured their risks properly.

I'm not a Java developer, so I can't on how hard it would be to hard code the limits in USD for example.

**Comment by fresheneesz** [comment]
> for most fiat payment methods you do have increase your trade amount limit as the Account age increases

I think that's fine. Starting people low and increasing as they use the system more makes sense. But I think that once you've successfully made like 20 trades using a particular payment method, your limit should basically be removed, since you've proven you know how to use that payment method properly. It looks to me like they have 3 tiers, and the third tier only has maybe 4 or 5 times the limit of the first tier. Its an oddly tight range. And its especially odd that there looks to be no way to raise your limits to levels competitive with any of the centralized exchanges out there.

> The limits for altcoin markets, I imagine, are in place to protect against the other week chains' reorgs, confirmation time and price volatility.

That would surprise me, again, since there are use-prerequisites to increasing limits in the first place. Once you've made a bunch of trades on a particular alt coin, you'll be familiar with the volatility and lag-time that it takes to make a trade. Putting such strict limits on users who are almost definitely aware of the risks doesn't make any sense to me.

> There's this proposal in place that will try address some of the issues

Looks like a good start. The proposal mentions scammers, but trade limits are not an appropriate mechanism to deter scammers. The escrow and mediation system is the appropriate mechanism. Trade limits should not be trying to deter scammers - what it really does is deter honest traders.

> how hard it would be to hard code the limits in USD for example.

Bisq already has exchange rates it uses in many parts of the system. Putting limits in USD would be probably a one or two line code change.

**Comment by huey735** [comment]
> And its especially odd that there looks to be no way to raise your limits to levels competitive with any of the centralized exchanges out there.

I don't think Bisq can compete with centralized exchanges in the amount traded per trade, in fiat markets. Most fiat payment methods available have daily limits on their side that would prevent Bisq users to trade at those volumes anyway.

> That would surprise me, again, since there are use-prerequisites to increasing limits in the first place. 

Altcoins only have one tier which limit is 2 BTC.

> The escrow and mediation system is the appropriate mechanism. Trade limits should not be trying to deter scammers - what it really does is deter honest traders.

The recent scam wave that that proposal is manly responding to was possibly a single hacker with multiple stolen bank accounts who caused the rightful owners of those accounts to make chargebacks months after the trade had gone through with no dispute. So, the escrow and mediation didn't do much to prevent it. The BTC sellers saw the fiat leave their bank accounts long after the trade period had come to an end.

**Comment by fresheneesz** [comment]
> Most fiat payment methods available have daily limits on their side that would prevent Bisq users to trade at those volumes anyway.

Why limit people when their method of payment has a higher limit?

>  a single hacker with multiple stolen bank accounts... the escrow and mediation didn't do much to prevent it

That's a huge problem. Mediation is *the* solution. If mediation isn't working, then the system is broken. Mediators should be responsible for dealing with chargebacks like that, since dealing with a chargeback is basically the definition of mediation. Plus, a mediator would deal with it from time to time and know how to do it efficiently. Individual users who get screwed almost certainly don't know how to efficiently deal with chargebacks like that. 

Regardless of the failure of mediation to solve that problem, trade limits don't solve the problem either.

**Comment by huey735** [comment]
@fresheneesz I'm quite ignorant on how payment processors work. How would a mediator prevent a chargeback that may happen months in the future? Let's say Alice sells Bob 0.1 btc for 1000 usd. And they use Zelle. The trading period comes to an an end, Alice has received her usd so she releases the btc to Bob. Arbitration wasn't even needed and up till now everything is ok.
But months later, her bank issues a chargeback because that transaction was fraudulent. What can a mediator/arbitrator do in that scenario.

**Comment by fresheneesz** [comment]
> How would a mediator prevent a chargeback that may happen months in the future? 

You can't prevent it. But once the chargeback happens, the mediator could decide how to deal with it if they're in a position to. If you're a merchant, charge backs are [part of the business](https://chargebacks911.com/knowledge-base/first-step-to-handling-chargebacks/). But dealing with them takes some skill. That skill isn't something a customer is usually going to have. 

What you do is present evidence to the payment processor and/or banks involved in the payment that shows that a deal was made and the bitcoin was delivered. This actually should be very easy to do with Bisq because everything is committed on chain and there's an established protocol you can prove the other person followed. It would be best if the method of payment and details about it are recorded in a provable way - for example, if it was a bank to bank transfer, the bank account number could be hashed and recorded in the "take offer" transaction so that the bank account can be verified to have been recorded in the transaction without exposing the account number to others.

Its an enormous pain for an individual to try going through the process of fighting a chargeback for the first time, but mediators that would do that from time to time would know better how to handle it. This would probably require sending fiat to the mediator first, then the mediator would send to the BTC seller.

**Comment by ManfredKarrer** [comment]
> 2 BTC maximum is not enough for larger traders, and 0.5 BTC maximum for bank transfers and 0.25 BTC for things like Zelle is far too little. What gives? Why are there drastically different limits for every payment method?

One of the reasons is risk protection if an arbitrator makes a mistake at a dispute payout. He need to pay tha from his pocket which is with 2 BTC already very high.

> This would probably require sending fiat to the mediator first, then the mediator would send to the BTC seller.

That would open a terrible can of worms. Regulators would have a feast.

**Comment by fresheneesz** [comment]
> He need to pay tha from his pocket which is with 2 BTC already very high.

If there's higher risk, there should be higher reward. If arbitrators were able to charge a fee dependent on the size of the trade, that would allow them to charge enough to cover the cost of the additional risk.

> That would open a terrible can of worms. Regulators would have a feast.

Well I don't see any way to have fast safe fiat payments on Bisq without it. Either you have to wait for fiat finality, which is like 6 months, or you risk someone charging you back. Maybe Bisq should stick to crypto only and F2F.

**Comment by ManfredKarrer** [comment]
> Well I don't see any way to have fast safe fiat payments on Bisq without it. 

If you convert Bisq to a custodial exchange you get that, but then you can use Coinbase as well as you lose all what makes Bisq different. KYC will be mandatory then.

Chargeback is only  a big problem with those crappy "friends and family" payment methods like Paypal, Venmo and Cashapp where you just call customer care to reverse the payment. With normal banks that is not possible (you can do it maybe once but if repeated yor bank we start to ask questions, most banks require an evidence for reason). The incident we had in April was stolen bank account fraud, that is differeny to "friendly chargeback".
Charebacks with "friendly chargeback" have been very few in >3 years (I think it was 2 or 3 cases - not counting the Venmo/Cashapp cases when we supportet those).

**Comment by slipperybeluga** [comment]
> 2 BTC maximum is not enough for larger traders, and 0.5 BTC maximum for bank transfers and 0.25 BTC for things like Zelle is far too little. What gives? Why are there drastically different limits for every payment method?

lol i would kill for 0.25 BTC zelle limits.  I am still stuck with 0.01 BTC limits on zelle after multiple trades and 50 days account age. with high miner fees, trading such small amounts makes bisq _substantially_ more expensive than exchanges. Not only that, but over half of all offers don't even include such low minimums, effectively barring new users from trading. This software already has so many barriers to entry and low liquidity, keeping users stuck in some purgatory low level forever is pretty discouraging. 

**Why not allow higher limits for individuals that have already traded together?** Let the seller determine if the risk is worth it, versus Bisq deciding for them by default. 

Here is an example of the only 0.01 BTC offer open to me the other day:
![Screenshot_20190808_071018](https://user-images.githubusercontent.com/6125744/62749174-e752a000-ba07-11e9-85c3-8c34105f0486.png)

**Comment by huey735** [comment]
> Why not allow higher limits for individuals that have already traded together?

If I have stolen account I can make multiple trades with you before the legitimate owner realizes the fraudulent transactions and requests a chargeback from their bank.

A lot of your questions can be answered by this thread https://github.com/bisq-network/proposals/issues/93

**Comment by fresheneesz** [comment]
> If I have stolen account I can make multiple trades with you before the legitimate owner realizes the fraudulent transactions and requests a chargeback from their bank.

While true, it doesn't invalidate anything slipperybeluga said. If that is a risk you're willing to take, that should be your business, not Bisq's. A stolen account is rather uncommon anyways.

**Comment by ManfredKarrer** [comment]
@slipperybeluga We are working on a new protection tool and it was not expected that it takes so long but we are very short on dev resources atm... Hope in 1-2 months that is out and the limits can get lifted.
