### ISSUE TITLE
"Funds needed" info button freaks out

### ISSUE THREAD

**Issue by fresheneesz** [bisq-network/bisq#3016]
When I hover my mouse onto the info "i" button from the bottom, the info pane flashes open and closed at a rate of about 20 times per second. This is it caught mid flip out:

![bisqfundsneeded](https://user-images.githubusercontent.com/149531/61999284-59270300-b072-11e9-8509-8dd595262def.png)

Please fix.

**Comment by ghost** [comment]
I have some similar effect with my Debian/Gnome.
I guess this is managed by a GUI library and caused by it.
So, probably few chance we can do something here.

**Comment by fresheneesz** [comment]
> I guess this is managed by a GUI library and caused by it. So, probably few chance we can do something here.

What makes you say that? Most times when I've seen behavior like this, its because the opening of the dialog changes the state that causes the dialog to close, which changes the state causing the dialog to open again. For example, if you have a dialog open under where the mouse is, the mouse may not be recognized as hovering over the "i" element anymore, causing the dialog to close, which causes the mouse to be recognized as hovering over the "i" element again, causing the dialog to open... etc etc. Do you think that's not what's happening?

**Comment by ghost** [comment]
> What makes you say that? ... Do you think that's not what's happening?

It was just a guess from my side. I'm not a java and GUI dev.
Thanks for your explanation. Hopefully you're right and so something is doable.
ping @ripcurlx since he manages the GUI.

**Comment by fresheneesz** [comment]
Ugh, this also happens to the "Amount in USD to spend" field's eye-icon in the "Create new offer to buy bitcoin" view, but even worse, there's no position where it won't freak out.
