### ISSUE TITLE
Mouse-wheel scrolling doesn't work well for full-pages that need scrolling

### ISSUE THREAD

**Issue by fresheneesz** [bisq-network/bisq#3017]
The settings page seems to be the only one that has a full-page scroll bar when fully expanded on my wider screen. But I can make other pages have scroll bars by making the window smaller. On my Windows 7 machine, trying to scroll with the mouse wheel scrolls only 1 or two lines for a full wheel scroll, whereas I would expect it to scroll much farther. Everything else in the app that has a scroll bar (other than full pages - eg the Available offers list) scrolls normally. It doesn't help that Bisq lags like hell and seems to refresh at about 1 frame per second...

**Comment by freimair** [comment]
can you be more specific? I just tried a couple of things you suggested on gnome shell and I cannot reproduce slow scrolling, neither can I reproduce lags.

> On my Windows 7 machine, trying to scroll with the mouse wheel scrolls only 1 or two lines for a full wheel scroll, whereas I would expect it to scroll much farther. 

which screen(s) are you referring to?

**Comment by fresheneesz** [comment]
> can you be more specific?

Specifically:

1. Go to the settings screen
2. Ensure the height of the window is small enough for a scroll bar to appear on the right (probably want to make it small enough so maybe half the page can be seen at once, so there's room to scroll)
3. Use the mouse wheel to scroll the whole settings page (eg not the list of currencies or something like that)

This is the kind of UI issue that is very likely to be OS specific. I'm not surprised Gnome Shell operates differently.

**Comment by fresheneesz** [comment]
No, stalebot, this should be fixed.

**Comment by fresheneesz** [comment]
Really? Every 3 months this thing comes through and marks things stale? That is clearly too short of a time. Please fix it.

**Comment by Android-X13** [comment]
I agree that vertical scrolling is very slow in some views, I've added a fix for that.
I didn't see any difference though between Linux GNOME and Windows systems (meaning: scrolling is equally slow in both).
