### ISSUE TITLE
Need to see exact transaction data before committing to a trade.

### ISSUE THREAD

**Issue by fresheneesz** [bisq-network/bisq#3018]
When trying to take an offer, I see nowhere that gives information about what transactions will be created and broadcast. It only has info about the composition of the fees needed, but there's no way to verify that these fees make sense for the transactions given. There needs to be a way for the user to see the exact transactions that need to be sent with as much information as is available. Are multiple transactions going to be created/needed? As a user I have no way to know. Why are the mining fees so high? I have no way to estimate the number of bytes the necessary transaction(s) will contain. I need this information to be able to build trust in a system like this.

**Comment by huey735** [comment]
You can find the high level info [here](https://docs.bisq.network/exchange/whitepaper.html#the-details-of-an-exchange-transaction).
But I think this is the breakdown:
The current trade protocol requires 4 transactions and it uses P2PKH and P2SH for escrow

| tx | Inputs | Outputs | 
| :--: | :--: | :--: |
| Make offer |  1 | 2 
| Take offer | 1 | 2 
| Deposit | 2 | 2
| Payout | 1 | 2

I'm including 1 change output. The inputs in the Make offer and Take offer txs can change depending on how the traders are spending their coins. And when paying the trading fee with BSQ you get 3 outputs in those transactions.
In cases where the Maker's offer is only filled partially, the Deposit transaction has 3 outputs: trade funds, OP_RETURN, change for the Maker.
Everything is unaltered.

The Maker is responsible for 1 on-chain transaction
 * Make offer

The Taker is responsible for 3 on-chain transactions and the fee is calculated at the moment of the taking and multiplied by 3.
 * Take offer
 * Deposit
 * Payout

Bisq uses [this service](https://bitcoinfees.earn.com/api/v1/fees/list) to estimate fees. And the mining fee is aiming at the next block.

You can find info on https://bitcoin.stackexchange.com/ on how to calculate the bytes for transactions with these profiles.

I'm not sure if it's worth putting all this info in the UI.

**Comment by fresheneesz** [comment]
Thanks for the information!

> the mining fee is aiming at the next block.

That is not a reasonable default in my opinion. These trades are up there for days, and settling a trade in an hour should be a reasonable default. Regardless, the taker should be able to choose their fee, and the software should inform the user what it predicts (or what bitcoinfees.earn.com predicts) that means about when the transaction will be confirmed. 

> You can find info on https://bitcoin.stackexchange.com/ on how to calculate the bytes for transactions with these profiles.

That's great for me, but that information needs to be calculated for you in the application, and it should be able to show you all the details about those transactions. 

> I'm not sure if it's worth putting all this info in the UI.

Not only is it worth it, its critical for adoption. People don't trust Bisq because Bisq makes it very hard to understand what its doing. Every other bitcoin software I've ever used can give you all that kind of information, down to looking at the exact transaction details before you sign and broadcast it. Its critical because these are final and irreversible transactions. Users who want to must be given the option to be sure of what they're doing, or they're simply not going to use Bisq. 

> The Taker is responsible for 3 on-chain transactions

This is kind of an aside to this ticket, but why make 3 transactions? Why not combine offer taking and deposit into 1 transaction with 3 outputs instead of 2 transactions with 4 outputs (assuming there's a change output in each transaction). It would make that step more atomic too.

**Comment by huey735** [comment]
I'm not sure, but I think that the offers need their respective transactions to have at least one confirmation for them to be valid. [Look at this](https://docs.bisq.network/exchange/images/payment-protocol.png) and the Bisq's White Paper I've linked above. It'd also lead to a poor experience if it was up to the taker to decide the fee for their Take offer transaction. That could easily lead to the offer maker being in limbo waiting for a confirmation.

Some of the mining fee information is already displayed in the stage before confirming the trade, but I assume that you don't think that that's enough. I don't know how difficult that calculator would be to implement but the current Bisq Java developers have their hands pretty full so I don't think they'll be able to get to it anytime soon.

I think there are 4 transactions required for the current trade protocol because of the check and balances each step requires. I don't have the knowledge to tell if it could be streamlined.

**Comment by fresheneesz** [comment]
> That could easily lead to the offer maker being in limbo waiting for a confirmation.

This is always a possible situation. The taker could simply fail to pay, and then its the same thing. That's why there are mechanisms in place to deal with that kind of thing. This is a peer to peer system, treating people like babies who can't be responsible for setting an appropriate fee is not a reasonable way to operate that kind of system. 

> Some of the mining fee information is already displayed in the stage before confirming the trade, but I assume that you don't think that that's enough

Correct.

> I don't think they'll be able to get to it anytime soon.

It is what it is I guess. I'm curious what the priorities are tho. In my opinion, this is critical information that helps build trust in this system. Since Bisq is a new thing to everyone who uses it, building that trust is critical for retaining first-time users. I certainly don't feel safe using Bisq at the moment because it doesn't give me the information about what will happen when I press Go.

**Comment by freimair** [comment]
maybe we can have a "show me all" button somewhere for the people interested in "all" the data?
