### ISSUE TITLE
Cancelled transactions did not receive deposit back

### ISSUE THREAD

**Issue by inpharmaticist** [bisq-network/bisq#3019]
I have had a couple of transactions not go through for different reasons and I am only just now realizing I never received my deposits back. 

Transaction 722103. Cancelled because the money order was mailed but USPS could not find the seller's address. Deposit 0.00445 BTC.

Transaction creMs. Cancelled because "bank deposit" was a poor choice of seller's method of receiving fiat due to a local bank not located anywhere but their own town.  Deposit 0.006250 BTC.

**Comment by huey735** [comment]
[These are the arbitrators handles](https://bisq.community/t/arbitrators/8074). Contact them to see what's going on.

**Comment by inpharmaticist** [comment]
That just went to the bisq website. Am I supposed to do something when I get there?

**Comment by inpharmaticist** [comment]
I got a message through the creMs support ticket, but it's just a repeat of the last message and I can't respond

**Comment by ghost** [comment]
@inpharmaticist 
For each of those trades, identify the onion of the concerned arbitrator, and the arbitrator
(-> https://bisq.community/t/arbitrators/8074/2 )
You can them contact them by PM on https://bisq.community/

**Comment by huey735** [comment]
@inpharmaticist sorry I pasted the wrong link.

**Comment by inpharmaticist** [comment]
Thanks for the info. I received a message (I am unable to respond as it is closed) for transaction creMs showing me the refunded transaction. I can see that now, so we're good. Now just transaction 722103. Should I close this ticket and handle it at bisq.community?

**Comment by huey735** [comment]
Yeah, I think bisq.community is more appropriate for this kind of discussion.

**Comment by inpharmaticist** [comment]
Will do, thanks.
