### ISSUE TITLE
YANG LISTING

### ISSUE THREAD

**Issue by Yangtoshi** [bisq-network/bisq#3020]
1. Asset name

Yang Bucks

2. Ticker

YANG

3. Block explorer URL

https://etherscan.io/address/0x78fe9e298840a74cefd242bad511ca343c5b4d7b

4. Additional technical requirements

No

5. Initial coin offering

No

6. Other Notes

Yang Bucks is the worlds first vaporwave inspired token, created to support the meme’ing of Andrew Yang into the presidency. We’re developing a modular token that will allow nation states to distribute a Universal Basic Income on the blockchain.  In short, we’re a meme token with a purpose.

More info on our official site: https://www.yangbucks.com/
Official Twitter (DM;s open): https://twitter.com/realyangtoshi

**Comment by blabno** [comment]
Is it ERC-20 token?
Is it privacy coin like monero?
Is it fork of any other coin?
What are the wallet address validation rules?

**Comment by Yangtoshi** [comment]
> Is it ERC-20 token?
Yes
> Is it privacy coin like monero?
No
> Is it fork of any other coin?
No
> What are the wallet address validation rules?
None

**Comment by blabno** [comment]
You will need a developer to prepare GitHub pull request with necessary code changes.
If you don't find anybody, ping me on Bisq slack (@bernard).

**Comment by Yangtoshi** [comment]
pull request submitted
#3109

**Comment by kryptiger** [comment]
Kindly list $YANG @Yangtoshi
