### ISSUE TITLE
Bisq doesn't connect 

### ISSUE THREAD

**Issue by fabfabgo1** [bisq-network/bisq#3021]

**Comment by ghost** [comment]
in your logfile
<pre>
Juli-27 17:27:36.733 [JavaFX Application Thread] WARN  o.b.w.Wallet: Saw two pending transactions double spend each other 
Juli-27 17:27:36.733 [JavaFX Application Thread] WARN  o.b.w.Wallet:   offending input is input 0 
...
...
Juli-27 17:27:36.733 [JavaFX Application Thread] INFO  o.b.w.Wallet: ->dead: ...
Juli-27 17:27:36.735 [JavaFX Application Thread] INFO  b.c.a.DisputeManager: Send AckMessage for DisputeCommunicationMessage to peer g72ouph23eznvpuz.onion:9999.
</pre>

Last line should mean that @Arbitrator2 got messages about this issue.
