### ISSUE TITLE
standardize on one mocking lib (remove jmockit and powermock)

### ISSUE THREAD

**Issue by christophsturm** [bisq-network/bisq#3025]
right now we use 3 different mock libraries: jmockit, mockito, and powermock (with mockito api)

I think we should only use mockito.  There probably should be two subtickets for this, one to remove jmockit(probably a quick change), and one to remove powermock (needs architectural changes but also not hard.)

**Comment by mrosseel** [comment]
What is your reason for chosing mockito?
I've chosen jmockito in the past but no strong opinions

**Comment by sqrrm** [comment]
@christophsturm I support this. If you drive it and make reasonable decisions it will happen. Previously we've discussed it but there need to be someone actually doing it as well. Perhaps add another issue in https://github.com/bisq-network/style/issues on the topic of mocking as well.

**Comment by christophsturm** [comment]
reasons for mockito:
* I know mockito best from previous projects, so I know pretty well how to convert all tests to mockito, with jmockit I would have to read up on it.
* Mockito seems to be the most used mocking lib in java land
* Our jmockit setup is really complicated, we use 2 different jmockit versions, one in p2p and a different one in the other modules.
* Jmockit uses an javaagent which not always works so well in the IDE

last reason and for me the main reason: jmockit and powermock both have powerful static mocking methods which mockito does not have by design, and I think simpler mocking enforces better design. 

It is possible that not all these reasons are true or still true because i don't know much about jmockit, i just saw that we have a pretty complicated setup.

**Comment by blabno** [comment]
This has been discussed here: https://github.com/bisq-network/proposals/issues/74

**Comment by christophsturm** [comment]
ok that proposal seems to mostly agree with my conclusion.

**Comment by freimair** [comment]
are there still other mocking frameworks in use?

**Comment by christophsturm** [comment]
no this is fixed
