### ISSUE TITLE
List VFC token

### ISSUE THREAD

**Issue by vfcash** [bisq-network/bisq#3038]
Please fill in the following data to request for a new asset to be listed on Bisq. For more details, be sure to read [the full documentation](https://docs.bisq.network/exchange/howto/list-asset.html) on adding a new asset.

### 1. Asset name
VF Cash

### 2. Ticker
VFC

### 3. Block explorer URL
https://vfcash.uk/explore

### 4. Additional technical requirements (yes/no)
no

### 5. Initial coin offering (yes/no)
no

**Comment by blabno** [comment]
Is it privacy coin like monero?
Is it fork of any other coin?
What are the wallet address validation rules?

**Comment by vfcash** [comment]
> Is it privacy coin like monero?
no, but the mined addresses can be used like anonymous pre-paid debit cards

> Is it fork of any other coin?
no, written from scratch in C

> What are the wallet address validation rules?
secp256r1

**Comment by blabno** [comment]
I don't think that secp256r1 is validation rules.
Anyway, you have to find a developer that will create GitHub pull request with necessary code changes.
