### ISSUE TITLE
Normalize Phone Numbers

### ISSUE THREAD

**Issue by kdeldycke** [bisq-network/bisq#3042]
Just happened to have an issue on setting up a new Revolut account on Bisq: the phone number I registered is taken as-is and will be displayed as such to the receiving end of the transaction.

I entered my Revolut account's phone number in the local (French) format, i.e. `0612345678` and the other party, not located in the same country as I am, did not find my account. It had to be formatted in the international form: `+ 33 6 12 34 56 78`.

I failed my first transaction on Revolut for that reason. But was able to solve the dispute thanks to a great arbitrator.

To fix this issue for good and reduce the number of disputes, I propose to have all phone number fields in Bisq normalised into their international form.

Good news, there's a great library made by Google to normalise all of them at: https://github.com/google/libphonenumber . Used it myself, it's solid, well maintained and clean! :)

**Comment by ghubstan** [comment]
I'm working on a validator / formatter and tests for this issue.
Please let me know what objections there are to this approach:

- Adding a new 343 kB Google [libphonenumber](https://search.maven.org/artifact/com.googlecode.libphonenumber/libphonenumber/8.10.16/jar) dependency.

- Converting all input phone numbers to [E.164](https://en.wikipedia.org/wiki/E.164) format.
    @kdeldycke's example input `0612345678` would be re-formatted as `+33612345678`.

**Comment by ripcurlx** [comment]
Closing as complete
