### ISSUE TITLE
BSQ tx "Not recognized", change missing

### ISSUE THREAD

**Issue by Bigsy11** [bisq-network/bisq#3046]
Sent BSQ to complete trade.
Peer released BTC.

The  BSQ transactions involved have description "Not recognized", but if the tx IDs are clicked, they show up in the bisq block explorer.
Amount in BSQ "N/A", but both have confirmation circles.

But the change from them doesn't show in the BSQ wallet.

Delete file SPV and resync did not fix it.

**Comment by ManfredKarrer** [comment]
Do you have latest version? If not please update. Otherwise go to the db folder inside the data directory and delete the DaoStateStore file. At new start it should be ok.

**Comment by Bigsy11** [comment]
Thank you! Deleting the State Store fixed this!
