### ISSUE TITLE
List BTS

### ISSUE THREAD

**Issue by froooze** [bisq-network/bisq#3049]
### 1. Asset name
BitShares

### 2. Ticker
BTS

### 3. Block explorer URL
https://bitsharescan.com/

### 4. Additional technical requirements (yes/no)
no

### 5. Initial coin offering (yes/no)
no

**Comment by froooze** [comment]
What bounty is recommended to speed up integration?

**Comment by grctest** [comment]
Additional explorers:
https://bts.ai/
https://open-explorer.io/#/dashboard
https://bitshares-explorer.io/#/dashboard
https://cryptofresh.com/
https://bitshares-kibana.info/app/kibana#/home?_g=()

In-wallet explorers:
https://wallet.bitshares.org/#/explorer/blocks

**Comment by blabno** [comment]
Is it privacy coin like monero?
Is it fork of any other coin?
What are the wallet address validation rules?

**Comment by froooze** [comment]
> Is it privacy coin like monero?

No
> Is it fork of any other coin?

No, BitShars is the first DPOS coin of the graphene family (STEEM, EOS ...)
https://bitshares.org/

> What are the wallet address validation rules?

https://dev.bitshares.works/en/master/bts_guide/tutorials/index.html#wallet-cli

**Comment by blabno** [comment]
Please point me to address validation rules, the above link leads to too general documentation.

**Comment by froooze** [comment]
@blabno: Does this help?
https://github.com/bitshares/bitshares-core/blob/master/libraries/protocol/address.cpp

**Comment by blabno** [comment]
It helps a bit, but will require additional developer time to analyze that.

You will need a developer (could be yourself) to create a pull request with necessary code changes.
If you can't find anyone then contact me on Bisq slack (@bernard).

**Comment by abitmore** [comment]
Just a note, assets(coins) in BitShares aren't stored in addresses, but in named accounts, so I think the "address validation rules" don't apply.

**Comment by ripcurlx** [comment]
JFYI: Asset listing is on hold right now because of bisq-network/proposals#153
