### ISSUE TITLE
Field "Amount in USD to spend" is not working properly.

### ISSUE THREAD

**Issue by fresheneesz** [bisq-network/bisq#3050]
Scenario 1:

1. Create a new offer to buy bitcoin for dollars
2. Put $600 in the "Amount in USD to spend" field
3. Set the "Below % from market price" field to 2%

Result: The "Amount in USD to spend" has been changed to $588.
Expected: The "Amount in USD to spend" should remain $600. 

Scenario 2:

1. Create a new offer to buy bitcoin for dollars
2. Put $600 in the "Amount in USD to spend" field
3. Set the "Fixed price in USD for 1 BTC" field to $100

Result: The "Amount in USD to spend" has been changed to $50.
Expected: The "Amount in USD to spend" should remain $600.

Scenario 3:

1. Create a new offer to buy bitcoin for dollars
2. Put 0.5 BTC in the "Amount of BTC to buy" field
3. Set the "Fixed price in USD for 1 BTC" field to $1000.  The "Amount in USD to spend" field will be updated to read $500.
4. Put $600 in the "Amount in USD to spend" field

Result: The "Amount in USD to spend" field will revert to reading $500.
Expected: The "Amount in USD to spend" field will revert to reading $600 - the number you input. 

Note that this behavior doesn't happen for all inputs. For example, if you delete a 0 in $500, it will update to $50.00. If you put in $50 it will revert. If you put in $50.00 it *won't* revert. The logic on this field is VERY broken. Please don't just try fixing this bug with a patchover. The code obviously needs refactoring so the logic is cleaner.

Scenario 4:

1. Create a new offer to buy bitcoin for dollars
2. Put $600 in the "Amount in USD to spend" field
3. Put 0.05 BTC in the "Amount of BTC to buy" field

Result: The "Fixed price in USD for 1 BTC" or "Below % from market price" remain empty.
Expected: The "Fixed price in USD for 1 BTC" or "Below % from market price" should be updated so the equation is fulfilled (just like the  "Amount in USD to spend" field).

These fields just don't work intuitively or even correctly. Updating one part of the equation should update other parts of the equation, but it should anchor on the values the USER input, not on an arbitrary field.

**Comment by fresheneesz** [comment]
I have to say, this is INCREDIBLY frustrating to try to deal with. Please make this a priority.

**Comment by battleofwizards** [comment]
I confirm the issue. Tested on the latest v1.1.5.

**Comment by ben-kaufman** [comment]
I was able to reproduce the issue as well. If this not taken already, I will try to work on a fix.
I already managed to solve scenario 1 (hopefully). 
Scenario 2 and 3 seems to be caused simply by the limit on the maximum amount you can trade, @fresheneesz can you please check if that is the case?
I am now trying to fix scenario 4.

**Comment by fresheneesz** [comment]
Please reopen this. Neither scenario 1 nor scenario 4 are fixed in v1.1.6, and #3194 doesn't claim to fix scenarios 2 or 3, so this issue should remain open at least for those.

**Comment by ben-kaufman** [comment]
The fix of scenarios 1 and 4 was merged after the release of v1.1.6, so it was not included there.
Regarding scenarios 2 and 3, I have experienced them only to the extent of the maximum limit which you can trade, and therefore it does not seem like a bug. I asked you above to confirm whatever the threshold at which those issues appear match your maximum trade limit, but you have not responded to that. Please check that first, and if you see it happens with no relation to the trade limit then the issue should be re-opened, but I will not be able to work on it as I could not reproduce such behavior.
