### ISSUE TITLE
SUSE detection, download, verification is missing.

### ISSUE THREAD

**Issue by rekcus2** [bisq-network/bisq#3053]
The `.rpm` works perfectly well on Tumbleweed. But after updates there is always a annoying message that only leads me to manual download and manual PGP verification and install. While it schould be automated.

And BTW: If I remember correctly the Ubuntu package adds Bisq to the start menu correctly while the .rpm just adds a desktop file to /opt/Bisq that works fine but I see not reason why its

**Comment by rekcus2** [comment]
Thank you, you stupid stale bot but its still a issue and it should not be dropped and dismissed just because the devs to not care to respond.

**Comment by ripcurlx** [comment]
> Thank you, you stupid stale bot but its still a issue and it should not be dropped and dismissed just because the devs to not care to respond.

Don't be so mean to our stale bot, it has feelings as well 😜 
What kind of annoying message are you relating to?

**Comment by rekcus2** [comment]
@ripcurlx What about this do you not understand?

> The .rpm works perfectly well on Tumbleweed. But after updates there is always a annoying message that only leads me to manual download and manual PGP verification and install. While it schould be automated.

Because you do not support Open SUSE for no reason at all the general process I am used to form Ubuntu where the file does automatically downloaded and verified by Bisq does not work on Open SUSE. Instead a message pops up that I need to manually download the file.

Then I think it leads me to Bisq website where the download is but to actually PGP verify it I then need to go to github, download the the asc as well and copy paste and modify gpg commands to actually verify the package to then only be able to install it with a specific `zypper --no-verification` or some switch like that. Its a incredibly tedious and annoying process for every update. Its like you ACTUALLY WANT people to skip the verification and just install it.

But I do not get the entire process of reinventing the wheel in the first place. Why do you not have repos for distros like everybody else where packages get updated and verified by Linux like they supposed to be?

At least build in a detection in for Open SUSE and make the process like on Ubuntu and download and verify the rpm inside Bisq. That is what I was asking. I guess because it depends just on some Java deps the package you build for fedora works perfectly fine on OpenSUSE. Actually not perfectly to be very specific, sometimes the app crashed on start and I have to start it up to 3 times for the window to actually show up, I think this not happened recently but it did happen a lot.
