### ISSUE TITLE
The change output of 5.41 is below the min dust value of 5,54 ...

### ISSUE THREAD

**Issue by rekcus2** [bisq-network/bisq#3054]
I am trying to place a offer with BSQ.

The trade fee is only 0.08 what is up with this? I already funded the offer but I can not review and place the trade and this message pops up.

> The change output of 5.41 is below the min dust value of 5,54 ...

**Comment by huey735** [comment]
The Bitcoin Network doesn't allow you to create outputs bellow 546 satoshis = 5,46 BSQ.

**Comment by rekcus2** [comment]
So basically buying that BSQ was totally a waste of time and money for the few trades I do on Bisq. I bought them to save money on trades and now I am sitting on them unable to use them. How about telling people that b4 promoting this stupid token?

**Comment by huey735** [comment]
@rekcus2 It's hard to know which minutia of bitcoin is opaque to people and we can only improve the documentation with more feedback.

The bitcoin network has a minimum limit of 546 satoshis to avoid spam attacks. BSQ being colored bitcoin inherits that. What this translates to is that when using BSQ your change always has to be bigger than 5,46 BSQ. So if the amount you have now will result in a change inferior to 5,46 BSQ, the solution, if you want to use BSQ, is to buy more BSQ.

**Comment by freimair** [comment]
can we add a check that prevents that users are getting stuck in this kind of situation?

**Comment by ripcurlx** [comment]
> can we add a check that prevents that users are getting stuck in this kind of situation?

What check do you mean? There is the dust check in place that prevents the publish of a transaction below the dust limit.

**Comment by ghost** [comment]
Can be closed now, was fixed by https://github.com/bisq-network/bisq/pull/4383
