### ISSUE TITLE
Bugreport: Buy BTC -> Create Offer -> Amount gt. 0.01 BTC

### ISSUE THREAD

**Issue by fflo** [bisq-network/bisq#3055]
Hi,

this is a bug report affecting new users.

Clicking [Buy BTC] -> Create Offer... -> Set amount and price: Amount of BTC to buy: Enter any value greater than 0.01 BTC and click again into the same field results into a endless loop displaying:

Information
The allowed trade amount is limited to 0.01 BTC because of security restrictions ...
[Close]

Clicking on [Close] results in popping up the same information again and again.

**Comment by freimair** [comment]
seems to be at least related to #2936 and #2835

**Comment by fflo** [comment]
Yes it's related. Shall I close this copy?
