### ISSUE TITLE
Unable to buy BTC by taking any offers

### ISSUE THREAD

**Issue by Annuit-Coeptis** [bisq-network/bisq#3069]
So I reinstalled v.0.9.3 and I could trade. Also just today I get an error message, telling me to report here. Likely they are connected?
I dragged the bisq.log here - didn't work, 'we don't support that file type'!

**Comment by ghost** [comment]
Bisq's current version is v1.1.5.
If you want to use Bisq, please upgrade.
-> https://bisq.network/
