### ISSUE TITLE
Error Publishing Transaction

### ISSUE THREAD

**Issue by jason-me** [bisq-network/bisq#3071]
Using BISQ v1.1.5 
Ubuntu 16.04

When trying to fund a transaction with BTC received the following error:

An error occurred when taking the offer.

An error occurred at task: TakerPublishFeeTx
Exception message: We got an onFailure from the peerGroup.broadcastTransaction callback.

Please try to restart your application and check your network connection to see if you can resolve the issue.Please try to restart your application and check your network connection to see if you can resolve the issue.

Restarted application and funds appeared in wallet alongside other UTXOs I previously funded. Sent all funds to private wallet address but the tx never broadcast to the mempool. TXID: c169bbea2e86cabde9a0544fdd0c7e33c64adaec30fd78bf568b942b69c4cef0

Now funds in BISQ wallet show 0 and missing .045+ BTC

Saved error logs if needed. Would rather not post entire log in clearnet.

**Comment by jason-me** [comment]
Saved error logs if needed. Would rather not post entire log in clearnet.

**Comment by jason-me** [comment]
Resolved by deleting SPV file, outdated Tor files and re-starting. Funds showed up on chain re-sync. Issue is still a potential bug/defect as the trade should have not have been taken by another user while funding fees for trade in progress.

**Comment by huey735** [comment]
Related to https://github.com/bisq-network/bisq/issues/3306
