### ISSUE TITLE
New Altcoin SixEleven

### ISSUE THREAD

**Issue by fflo** [bisq-network/bisq#3074]
Do you have a hint how to add Altcoin SixEleven with v1.1.5?
Is it necessary to reset the wallet being able to select new added Altcoins?

**Comment by blabno** [comment]
That was just a hot fix release, so despite your code is in master, it has not been released yet.

**Comment by fflo** [comment]
Thx. for the hint. Though it should be included in hotfix release v1.1.5, because the _GitHub_ source three already contains the patches: https://github.com/bisq-network/bisq/tree/hotfix-v1.1.5

**Comment by ripcurlx** [comment]
You are right it looks like as it is part of the PR, but that is just because I merged the current master state into it after the release to be able to merge the hotfix branch into master (as it had conflicts)

**Comment by fflo** [comment]
Do you have an idea why the market api does not show any volume for SixEleven Altcoin?

**Comment by wiz** [comment]
@fflo hey there, I maintain the market API - need to upgrade it to add your new coin, will do it soon

**Comment by fflo** [comment]
@wiz Thx. 
What are the requirements to run a copy of the market API? Bitcoin full node + DAO full node + market API web?

**Comment by wiz** [comment]
Actually you just need to run the Bisq statsnode which is a different entrypoint in the Bisq app, and it will dump the market data to a JSON file. The actual markets API website is currently just a PHP app that serves queries from that JSON file.

**Comment by fflo** [comment]
@wiz do you have any news on updating the market API?
https://bisq.network/markets/?currency=sil_btc is still reporting no trades.

**Comment by wiz** [comment]
@fflo it's updated now

**Comment by fflo** [comment]
Awesome. Thank you!
