### ISSUE TITLE
Portfolio CSV export Headers

### ISSUE THREAD

**Issue by freimair** [bisq-network/bisq#3075]
The first line of a CSV export is
`,,,,,,,,,,,,`

and it is quite hard to figure out what is what. Would be nice to have a header line on what column is what.

**Comment by battleofwizards** [comment]
Work in progress.

**Comment by battleofwizards** [comment]
The same bug is present when exporting transactions to CSV (Funds / Transactions).

**Comment by battleofwizards** [comment]
The fix: #3090
