### ISSUE TITLE
TrumpCoin (TRUMP) asset listing request

### ISSUE THREAD

**Issue by trumpcoinsupport** [bisq-network/bisq#3096]
Please fill in the following data to request for a new asset to be listed on Bisq. For more details, be sure to read [the full documentation](https://docs.bisq.network/exchange/howto/list-asset.html) on adding a new asset.

### 2. TRUMP
_Your asset's ticker must not conflict with any national currency tickers (per [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)) or any of the [top 100 cryptocurrency tickers](https://coinmarketcap.com/coins/)._

### 3. https://chainz.cryptoid.info/trump/#
_Your asset's block explorer must be active and publicly available so that transactions can be verified with a receiver's address...if this isn't possible, [see workarounds here](file:///home/steve/wb/bisq/bisq-docs/build/asciidoc/html5/exchange/howto/list-asset.html#arbitrators-must-be-able-to-look-up-transactions-in-the-asset-block-explorer)._

### 4. No additional technical requirements are needed
_Your asset should not have any additional requirements (for example, needing input fields for anything other than an address)._

### 5. Initial coin offering (No)
_Bisq will not list your token if it has taken part in an initial coin offering (ICO)_

Any questions can be submitted to support@trumpcoin.com
Bounty is available for this request.

**Comment by ManfredKarrer** [comment]
Ah great! Now we can try out to vote on kicking out a coin. I will put all my hard earned stake into it to **kick out that fascist Fuckard Trumpcoin in DAO voting**.
