### ISSUE TITLE
Transaction failed, waiting for blockchain confirmation

### ISSUE THREAD

**Issue by danielv1234** [bisq-network/bisq#3105]
Hi,
Trade id K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 is stuck , we are waiting for confirmation, but was not generated.
Please help us.
Thanks,
Dan

**Comment by danielv1234** [comment]
Hi again, 
How can i send a message @ arbitrator?
s6yrrpezc3zp6biy.onion:9999 
I need to close that stucked transaction.
Thanks again,
Daniel

**Comment by danielv1234** [comment]
Deposit transaction has not been published. 
 What can i do to unstuck this trade?

**Comment by ghost** [comment]
s6yrrpezc3zp6biy -> @keo-bisq (ping)
He is also @keo on the forum.

**Comment by danielv1234** [comment]
Thanks @HarryMacfinned . I hope @keo-bisq will help us.

**Comment by alexej996** [comment]
Keo tells me that he can not see that trade. I suggest you contact him via email at stibor@protonmail.com

**Comment by danielv1234** [comment]
Thanks @alexej996 !

**Comment by danielv1234** [comment]
Looks like UI error. Arbiter cannot see transaction.

**Comment by huey735** [comment]
@danielv1234 are these cases similar to yours?
https://bisq.community/t/how-to-proceed/8274
https://bisq.community/t/transaction-failed-to-broadcast-ui-error/8283

@ManfredKarrer @alexej996 @HarryMacfinned 
Both of the above are from new traders so it probably is due to network problems?

**Comment by danielv1234** [comment]
Yes, second thread is mine too. My problem is similar with /8274 .
I have 20+ trades, not new on this platform.
Also, i have restarted Bisq few times, SPV files deleted, resync done without change.

**Comment by huey735** [comment]
Just commenting with related issues:

[Error at traderSignAndFinalizeDisputedPayoutTx #2788](https://github.com/bisq-network/bisq/issues/2788)

[stuck open trades #2808](https://github.com/bisq-network/bisq/issues/2808)

[Trade stuck before step 1](https://bisq.community/t/trade-stuck-before-step-1/7245/33)

**Comment by huey735** [comment]
@danielv1234 out of curiosity, can you check the transaction fee on that Take offer transaction? You should be able to find it in the 'bisq.log' file inside your directory:
> All Bisq data is stored in one place:

    macOS: /Users/<username>/Library/Application Support/Bisq

    Linux: /home/<username>/.local/share/Bisq

    Windows 7+: C:\Users\<username>\AppData\Roaming\Bisq

    Windows XP: C:\Documents and Settings\<username>\Application Data\Bisq

Look for the Take offer transaction id.

**Comment by danielv1234** [comment]
I have searched for trade id:K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115
Aug-16 13:28:59.238 [JavaFX Application Thread] INFO  b.c.n.a.MyOfferTakenEvents: We got a offer removed. id=K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115, state=AVAILABLE 
Aug-17 15:17:37.384 [JavaFX Application Thread] INFO  b.c.n.a.MyOfferTakenEvents: We got a offer removed. id=K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115, state=AVAILABLE 
Aug-17 15:31:12.303 [JavaFX Application Thread] INFO  b.c.n.a.MyOfferTakenEvents: We got a offer removed. id=K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115, state=AVAILABLE 
Aug-18 21:01:29.516 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received OfferAvailabilityRequest from qaggkzaamp2guqua.onion:9999 with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid 88ab343a-474f-4597-afb6-5dd14bf9c3a4 
Aug-18 21:01:29.553 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send OfferAvailabilityResponse with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid 8ff8601a-5bf3-4fd5-8dcc-a2166afa759c to peer qaggkzaamp2guqua.onion:9999 
Aug-18 21:01:29.569 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send AckMessage for OfferAvailabilityRequest to peer qaggkzaamp2guqua.onion:9999 with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and sourceUid 88ab343a-474f-4597-afb6-5dd14bf9c3a4 
     sourceId='K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115',
Aug-18 21:01:29.586 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: OfferAvailabilityResponse arrived at peer: offerId=K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115; uid=8ff8601a-5bf3-4fd5-8dcc-a2166afa759c 
Aug-18 21:01:30.428 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received AckMessage for OfferAvailabilityResponse with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid 8ff8601a-5bf3-4fd5-8dcc-a2166afa759c 
Aug-18 21:21:08.199 [JavaFX Application Thread] INFO  b.c.n.a.MyOfferTakenEvents: We got a offer removed. id=K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115, state=CANCELED 
Aug-18 21:59:13.515 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received OfferAvailabilityRequest from yi5x3tmcgtewscmn.onion:9999 with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid c259e0a2-a59c-414c-979a-395d905cc6b7 
Aug-18 21:59:13.541 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send OfferAvailabilityResponse with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid 2d5d2a1e-e6c2-4ce9-b57b-807b63456d27 to peer yi5x3tmcgtewscmn.onion:9999 
Aug-18 21:59:13.543 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send AckMessage for OfferAvailabilityRequest to peer yi5x3tmcgtewscmn.onion:9999 with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and sourceUid c259e0a2-a59c-414c-979a-395d905cc6b7 
Aug-18 21:59:13.549 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: OfferAvailabilityResponse arrived at peer: offerId=K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115; uid=2d5d2a1e-e6c2-4ce9-b57b-807b63456d27 
Aug-18 21:59:13.601 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: AckMessage for OfferAvailabilityRequest arrived at takersNodeAddress yi5x3tmcgtewscmn.onion:9999. offerId=K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115, sourceUid=c259e0a2-a59c-414c-979a-395d905cc6b7 
Aug-18 21:59:13.984 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received AckMessage for OfferAvailabilityResponse with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid 2d5d2a1e-e6c2-4ce9-b57b-807b63456d27 
Aug-18 21:59:14.207 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received OfferAvailabilityRequest from yi5x3tmcgtewscmn.onion:9999 with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid 31823003-cf56-4078-bbd6-d769138599b6 
Aug-18 21:59:14.238 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send OfferAvailabilityResponse with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid 9f21bf7d-1c47-4f15-84e8-cde1b93ded75 to peer yi5x3tmcgtewscmn.onion:9999 
Aug-18 21:59:14.239 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send AckMessage for OfferAvailabilityRequest to peer yi5x3tmcgtewscmn.onion:9999 with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and sourceUid 31823003-cf56-4078-bbd6-d769138599b6 
Aug-18 21:59:14.242 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: OfferAvailabilityResponse arrived at peer: offerId=K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115; uid=9f21bf7d-1c47-4f15-84e8-cde1b93ded75 
Aug-18 21:59:14.296 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: AckMessage for OfferAvailabilityRequest arrived at takersNodeAddress yi5x3tmcgtewscmn.onion:9999. offerId=K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115, sourceUid=31823003-cf56-4078-bbd6-d769138599b6 
Aug-18 22:14:26.540 [JavaFX Application Thread] INFO  b.c.n.a.MyOfferTakenEvents: We got a offer removed. id=K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115, state=CANCELED 
Aug-18 22:29:18.463 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received OfferAvailabilityRequest from yi5x3tmcgtewscmn.onion:9999 with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid 90855fee-7853-4b88-90ad-8e0846f90186 
Aug-18 22:29:18.491 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send OfferAvailabilityResponse with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid db6fff1d-c7ea-44ec-84ac-c4714fa955c8 to peer yi5x3tmcgtewscmn.onion:9999 
Aug-18 22:29:18.492 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send AckMessage for OfferAvailabilityRequest to peer yi5x3tmcgtewscmn.onion:9999 with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and sourceUid 90855fee-7853-4b88-90ad-8e0846f90186 
     sourceId='K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115',
Aug-18 22:29:18.494 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: OfferAvailabilityResponse arrived at peer: offerId=K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115; uid=db6fff1d-c7ea-44ec-84ac-c4714fa955c8 
Aug-18 22:29:19.123 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received OfferAvailabilityRequest from yi5x3tmcgtewscmn.onion:9999 with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid 2f24c62f-b436-48ba-a8e9-12e5a70a77ba 
Aug-18 22:29:19.148 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send OfferAvailabilityResponse with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid d903f96b-76f8-45dc-a9b2-9214138cd3e0 to peer yi5x3tmcgtewscmn.onion:9999 
Aug-18 22:29:19.149 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send AckMessage for OfferAvailabilityRequest to peer yi5x3tmcgtewscmn.onion:9999 with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and sourceUid 2f24c62f-b436-48ba-a8e9-12e5a70a77ba 
     sourceId='K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115',
Aug-18 22:29:19.151 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: OfferAvailabilityResponse arrived at peer: offerId=K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115; uid=d903f96b-76f8-45dc-a9b2-9214138cd3e0 
Aug-18 22:29:22.221 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received OfferAvailabilityRequest from yi5x3tmcgtewscmn.onion:9999 with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid 921b47f8-de4a-41d8-8deb-6f46f0bf1cad 
Aug-18 22:29:22.246 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send OfferAvailabilityResponse with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid 4cd123f8-1deb-4921-97f2-ac6c3e1b281d to peer yi5x3tmcgtewscmn.onion:9999 
Aug-18 22:29:22.247 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send AckMessage for OfferAvailabilityRequest to peer yi5x3tmcgtewscmn.onion:9999 with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and sourceUid 921b47f8-de4a-41d8-8deb-6f46f0bf1cad 
     sourceId='K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115',
Aug-18 22:29:22.250 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: OfferAvailabilityResponse arrived at peer: offerId=K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115; uid=4cd123f8-1deb-4921-97f2-ac6c3e1b281d 
Aug-18 22:29:22.802 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received AckMessage for OfferAvailabilityResponse with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid 4cd123f8-1deb-4921-97f2-ac6c3e1b281d 
Aug-18 22:29:29.211 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received OfferAvailabilityRequest from yi5x3tmcgtewscmn.onion:9999 with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid 6cd90ac2-abe3-4204-9bf3-b32569aebe63 
Aug-18 22:29:29.237 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send OfferAvailabilityResponse with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid 23972958-caee-447f-bfd8-76805fbebc2f to peer yi5x3tmcgtewscmn.onion:9999 
Aug-18 22:29:29.238 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send AckMessage for OfferAvailabilityRequest to peer yi5x3tmcgtewscmn.onion:9999 with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and sourceUid 6cd90ac2-abe3-4204-9bf3-b32569aebe63 
     sourceId='K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115',
Aug-18 22:29:29.240 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: OfferAvailabilityResponse arrived at peer: offerId=K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115; uid=23972958-caee-447f-bfd8-76805fbebc2f 
Aug-18 22:29:29.896 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received AckMessage for OfferAvailabilityResponse with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid 23972958-caee-447f-bfd8-76805fbebc2f 
Aug-18 22:29:34.994 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received OfferAvailabilityRequest from yi5x3tmcgtewscmn.onion:9999 with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid 3389b7e5-892f-4d81-aef6-ebb20a82762d 
Aug-18 22:29:35.020 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send OfferAvailabilityResponse with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and uid 4fc99b3c-d82a-4e3f-ba1c-785fb3515705 to peer yi5x3tmcgtewscmn.onion:9999 
Aug-18 22:29:35.021 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send AckMessage for OfferAvailabilityRequest to peer yi5x3tmcgtewscmn.onion:9999 with offerId K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115 and sourceUid 3389b7e5-892f-4d81-aef6-ebb20a82762d 
     sourceId='K2ONFSW-1d9c9152-9186-4d6b-89e8-5d5cafe20a44-115',

**Comment by danielv1234** [comment]
￼
[bisq_2.log](https://github.com/bisq-network/bisq/files/3532188/bisq_2.log)

**Comment by huey735** [comment]
I mean the Take offer transaction id. You should see it by clicking on the little 'i' next to your trade id. Like here:

![trade](https://i.ibb.co/YLhTdHH/1.png)
![detail](https://i.ibb.co/Ct8Crsm/2.png)

It's the second id. And look for it in the bisq.log instead of any other .log file.

**Comment by danielv1234** [comment]
hve7ibq4n46da4mt.onion is taker id, i cannot find him in .log file.
Cannot find taker transaction id too : 
     6b1ee79da3c42ccddf453e86c8dbf6973e5ff6471776af99231109dcee017368

**Comment by danielv1234** [comment]
Any ideas how can i cancel this trade?

**Comment by huey735** [comment]
@danielv1234 you can open a ticket by pressing ctrl/cmd + o and request the arbitrator close it.

**Comment by danielv1234** [comment]
I have opened ticket, thanks for info.

**Comment by danielv1234** [comment]
My issue was solved, transaction was closed. Thanks @huey735  for you help.
