### ISSUE TITLE
Improve withdraw fee calculation

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#3106]
I tried to withdraw some BSQ from Bisq with a 1 sat/byte fee but the software miscalculated it and it ended outputting a value bellow 1 sat/byte. This caused the transaction to not be broadcast. I had to resync the SPV file and increase the custom withdraw transaction fee to 2 sat/byte.

There are two possible solutions:
* a) set the withdraw transaction fee to an obligatory minimum of 2 sat/byte
* b) fix the calculation of the transaction fee

I'd also like to say that this is a first occurrence, I've withdrawn many times at 1 sat/byte without coming across this issue.

**Comment by ManfredKarrer** [comment]
The calculation works usually pretty well. It is a bit complex, and complex to explain as well. Which fee was used in the tx? Was it far off? Should not be more the 10% off.

**Comment by huey735** [comment]
These were the values:
The necessary transaction fee is: 0.00000733 BTC (0.9 satoshis/byte)
Transaction size: 0.816 Kb

So probably increasing the minimum to 2 sat/byte is the easier solution. This is the type of silent error that may leave people in the dark.

**Comment by huey735** [comment]
Ping @wiz @christophsturm @sqrrm

**Comment by christophsturm** [comment]
I'm going to work on this
