### ISSUE TITLE
Altcoins Instant trade period is wrong

### ISSUE THREAD

**Issue by rexi1e** [bisq-network/bisq#3114]
Trade period should start after deposit transaction get 1 confimation, correct?

Instead trade period starts when offer was taken, so if deposit confirms 40 minutes after offer was taken, traders only have 20 minutes to complete trade. Sometimes very hard /impossible when fee jumps.

Notice in after screenshot: end of trade period (8:44pm) is exactly 1 hour after offer was taken (7:44pm).

![before-confirmation-pixelated](https://user-images.githubusercontent.com/51380215/63352847-59ed4500-c351-11e9-957b-607aca26a57f.png)
![after-confirmation-pixelated](https://user-images.githubusercontent.com/51380215/63352844-5954ae80-c351-11e9-9f01-410ed668f86c.png)

**Comment by ripcurlx** [comment]
As far as I remember the timer should only start after the first confirmation. I'll check it locally on regtest how it behaves for Altcoin instant.

**Comment by ripcurlx** [comment]
Just checked it locally on regtest and everything works as expected. The `Remaining time` is updated while waiting on the first blockchain confirmation.
<img width="1312" alt="Bildschirmfoto 2019-08-20 um 16 37 41" src="https://user-images.githubusercontent.com/170962/63357383-9f1d7100-c369-11e9-8a49-6740c88e1035.png">
After the first confirmation comes in the timer is set accordingly.
<img width="1312" alt="Bildschirmfoto 2019-08-20 um 16 42 46" src="https://user-images.githubusercontent.com/170962/63357385-9fb60780-c369-11e9-8c31-a0420e2e974c.png">

But I do see in your screenshots, that it behaves differently. Do you see this behavior every time when using Altcoin Instant?

**Comment by rexi1e** [comment]
Yes, it has happened more than once now. I purposely got before/after screenshots this time to show it. 

Maybe it has to do with being "BSQ seller as maker" instead of taker? Not sure, just the only differrnce i'm seeing in screesnhots.

**Comment by rexi1e** [comment]
For the record I just completed another trade but it worked ok...BSQ seller as maker 🤔

So issue doesnt consistent appear with my software on my machine...tricky

**Comment by ghost** [comment]
For information, I had a very similar issue once (but it was 3 months ago).

**Comment by ripcurlx** [comment]
I'll try to walk through the code soon to see under what circumstances this can happen. I just don't have time to do it right away, but I'd like to keep this issue open to be investigated.
If someone wants to work on this issue right away, just leave a comment and I'll assign it.
