### ISSUE TITLE
Users can reliably connect to the network via UPnP

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#312]
Currently about half of Bitsquare must set port forwarding manually within their routers. For the other half, UPnP (universal plug-and-play) works, and automatically establishes port forwarding on their behalf.

See #305, which deals specifically with understanding and solving these UPnP problems; the ultimate goal is that all Bitsquare users are able to automatically and reliably connect to the Bitsquare network without any manual setup. It should be as easy as working with Skype, for example.
- [ ] Blocked on #305

**Comment by cbeams** [comment]
@ManfredKarrer, I've updated the title and description here. I've dropped any mention of manual port forwarding, because we know that works. I think this user story is really about ensuring that the maximum number of users possible can connect automatically via UPnP. Sound OK to you?

**Comment by ManfredKarrer** [comment]
@Thanks!

**Comment by ManfredKarrer** [comment]
UPnP behaves pretty strange. I tried it with 2 different routers (same brand, diff model) and both work sometimes and sometimes not. I have not found yet clear patterns. We should investigate the weupnp library used inside TomP2P and cross check it with alternative UPnP implementations. 
But seems that UPnP is generally bad implemented by many routers. As we have relay mode working now it is not that hi prio anymore, thought we would need well connected nodes and manual port forwarding will be used rarely by users, so would be good to get that more reliable working mid term.

**Comment by ManfredKarrer** [comment]
Closed as related to TomP2P which is not used anymore.
