### ISSUE TITLE
BSQ buying problem

### ISSUE THREAD

**Issue by goblinpool** [bisq-network/bisq#3123]
hello, i had a problem, Trade process is on step 3 , but i didn't received any BSQ yet, what should i do? just wait for 1 day to pass and don't click on confirm payment receipt button? thanks

**Comment by m52go** [comment]
@goblinpool don't confirm payment receipt if you haven't received payment...if you do, there won't be any way to help you. Just sit tight until the trade period is up. Seller could be at work, in a different time zone, etc.

**Comment by goblinpool** [comment]
@m52go ok thanks man
