### ISSUE TITLE
capture memory snapshot when the app runs out of memory

### ISSUE THREAD

**Issue by christophsturm** [bisq-network/bisq#3132]
add `java -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=bisq-dump` to the start script. then people experiencing out of memory errors automatically have a dump file that they can send to us.

optionally check for the dump file at startup and tell people to create an issue. inspired by #3128

**Comment by christophsturm** [comment]
cc @ripcurlx

**Comment by battleofwizards** [comment]
Memory dumps can potentially contain secrets like private keys, mnemonic seeds, PRNG state, etc.

But maybe that could still be useful if we only allow it for developers (who I assume are testing on regtest and know what they are doing)?

![bisq-regtest](https://user-images.githubusercontent.com/54061429/63618914-9046f080-c5ed-11e9-9fda-84130d8bbc5b.png)

**Comment by christophsturm** [comment]
Good point. We should make some memory dumps and see what data they contain.

**Comment by christophsturm** [comment]
or people could just open up the snapshot in jvisualvm and send us a screenshot.
