### ISSUE TITLE
Bisq does not validate Bitcoin P2P node at configuration time

### ISSUE THREAD

**Issue by wiz** [bisq-network/bisq#3137]
[How to Reproduce]
1) Go to Settings -> Network
2) In the Bitcoin P2P node configuration under "use the following Bitcoin nodes", enter an invalid or unsupported hostname , such as the Tor v3 hostname 32zzibxmqi2ybxpqyggwwuwz7a3lbvtzoloti7cxoevyvijexvgsfeid.onion:8333
3) Bisq indicates it must be restarted, click OK

[Expected Results]
After Step 2, Bisq should validate the hostname is a valid Tor v2 hostname using regex or some other method, and also attempt to connect to this node. If it cannot validate or connect, it should not allow this setting to be changed, and it should not instruct the user to restart Bisq.
After Step 3, Bisq restarts, and despite the Bitcoin node being unreachable, the user should be able to proceed and reconfigure their settings to a reachable Bitcoin node.

[Actual Results]
After Step 2, Bisq did not perform any validation or testing of the user-entered hostname, it allowed the user the proceed, and it requested the user to proceed and restart Bisq.
After Step 3, Bisq restarts, but because the node is unreachable the following error is displayed and user is stuck with no way to correct their Bitcoin node settings, as they cannot get to the configuration screen.

<img width="996" alt="Screen Shot 2019-08-25 at 16 38 49" src="https://user-images.githubusercontent.com/232186/63647636-36663800-c75f-11e9-9b28-ecf43f89d31e.png">

**Comment by freimair** [comment]
first, agreed.

second, once https://github.com/bisq-network/bisq/pull/3044 is merged, I will proceed on getting bisq ready for tor hs v3

**Comment by m52go** [comment]
As a workaround for anyone who gets stuck by this in the interim, run Bisq from the command line with the argument `--btcNodes=[]`.

**Comment by wiz** [comment]
@freimair cool if you get Tor v3 working, but IMO the correct fix for this issue is to correctly handle the case when a user-configured btcnode is unreachable with a dialog that asks "Your configured Bitcoin node is unreachable, would you like to reset your configuration to use the Bisq-supplied set of Bitcoin nodes instead?"

**Comment by wiz** [comment]
For users affected by this bug, temporary workaround to get "unstuck" is to manually start Bisq with the --btcNodes option to a valid node like this:

[Ubuntu]
`/opt/Bisq/Bisq --btcNodes=22tg6ufbwz6o3l2u.onion:8333`
[macOS]
`/Applications/Bisq.app/Contents/MacOS/Bisq --btcNodes=22tg6ufbwz6o3l2u.onion:8333`
[

**Comment by devinbileck** [comment]
I have a fix for this that I will be submitting soon.

**Comment by elkimek** [comment]
For Windows 10 users use PowerShell instead of command line.

Example: `C:\Path\To\Bisq.exe --btcNodes=22tg6ufbwz6o3l2u.onion:8333`
