### ISSUE TITLE
Trade with serious bug

### ISSUE THREAD

**Issue by arbitrator2** [bisq-network/bisq#3138]
<img width="1148" alt="Captura de pantalla 2019-08-25 a las 15 25 47" src="https://user-images.githubusercontent.com/52173515/63654440-97e7d000-c77a-11e9-88d7-8c152caae453.png">

Trade "aikOA" with a very weird bug.
the 3 transactions aren't related:
maker tx - b4b25063df8e060348d7f859e8f6dc1ea9d068c6a58072c18ac4fef7397b8fb6
taker tx - 0750216d97ac246f9d397169cc920eb1b42a7c2c9c163c33f416dac977c7e8f9
deposit tx - 7fd51618161ffc9bf97b0ede7289d3c2168bd43f9394d23bd909c5b9741f651d

the btc seller received the payment and released the btc to the buyer but the payout was never made to the correct btc address. but rather to this one: 1Frhz7rdX7onjfccV8AdeKEjagxuWQd4p7 

there’s no ‘depositTxId’ for the trade ‘aikOA’ when looking in the ‘trades_statistics.json’ file that the Bisq software dumps. In fact the payout to 1Frhz7rdX7onjfccV8AdeKEjagxuWQd4p7 belongs to a different trade (DLPFDYIP). in which everything matches up and had no problem.

**Comment by huey735** [comment]
Here's what we get from the 'trades_statistics.json' file regarding this trade. The empty string for 'depositTxId' implies that it was never successfully made.
![aikOA](https://user-images.githubusercontent.com/44140017/63654799-104c9200-c777-11e9-851a-28d288d39c4a.png)

**Comment by ManfredKarrer** [comment]
Hm thats weird. 

Maker tx did not end in a deposit tx but was used for funding another maker or taker fee tx.
https://www.blockchain.com/de/btc/address/1Dr5YhWY5Ke2XhNf1AfvTZcbsEzU6qmjGB

The maker was funding the tx 9691f80cbd4f2776bb4c92992e987a45c249f2baeea56668069c960f6d770899:
https://www.blockchain.com/de/btc/address/1L8iansqVr9Ct4Cc5wopfTynL2o55562w6


Takerfee tx leads to a deposit tx 952c0e337935fc3500bccc1515c281b1a6330e3ca10315a0f40ff1afbbccdb49:
https://www.blockchain.com/de/btc/address/14oeMLmSXidc6NmbuUULExphzSgpW4MUzF

The maker fee tx to that deposit tx is that:
https://www.blockchain.com/de/btc/address/1CEDoKeRYbhSygapawsvqyFcaNaf2ayTzb

Can you check with thw traders if they received the BTC as expected? I assume they still got it but to a different address. They should not continue to use that app data directory and wallet to avoid any further issued but start over with new app dir.

**Comment by huey735** [comment]
Assuming no depositTx was indeed broadcast, both traders still remain in full control of their funds. They're just 'reserved' inside their Bisq wallets.

**Comment by huey735** [comment]
Related to https://github.com/bisq-network/bisq/issues/3306
