### ISSUE TITLE
Make behaviour on address click configurable in settings

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#314]
Clicking the address should open a btc wallet, but unfortunately that is not very well supported, so it is hard to control which wallet it opens. Better to add an option in the setting to define if it should open a wallet or shoudl just copy the address.

**Comment by ManfredKarrer** [comment]
Need to have preferences data in address component.
Need to find a good solution how to pass domain objects to components. Injection is probably not a good option for components. Passing in from the view is also not nice... Static/Singletons not good as well...
Same probelm we have at balance component (we pass walletService in).

**Comment by cbeams** [comment]
I always assumed that which application gets opened is out of Bitsquare's control, i.e. that it's whatever application is registered as the default handler for bitcoin:// URLs (e.g. it's Hive on my machine). Is this not the case?

**Comment by ManfredKarrer** [comment]
Yes. and it seems hard to change that for a user. So might be annying if its wrong configured.
Thats why I wanted to make it deactivatable, and change the behaviour to simple copy to clipboard.
