### ISSUE TITLE
New Listing: Scala [XLA]

### ISSUE THREAD

**Issue by SilentSeir** [bisq-network/bisq#3140]
Please fill in the following data to request for a new asset to be listed on Bisq. For more details, be sure to read [the full documentation](https://docs.bisq.network/exchange/howto/list-asset.html) on adding a new asset.

### 1. Asset name
Scala

### 2. Ticker
_Your asset's ticker must not conflict with any national currency tickers (per [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)) or any of the [top 100 cryptocurrency tickers](https://coinmarketcap.com/coins/)._

XLA

### 3. Block explorer URL
_Your asset's block explorer must be active and publicly available so that transactions can be verified with a receiver's address...if this isn't possible, [see workarounds here](file:///home/steve/wb/bisq/bisq-docs/build/asciidoc/html5/exchange/howto/list-asset.html#arbitrators-must-be-able-to-look-up-transactions-in-the-asset-block-explorer)._

https://explorer.scalaproject.io

### 4. Additional technical requirements (yes/no)
_Your asset should not have any additional requirements (for example, needing input fields for anything other than an address)._

no

### 5. Initial coin offering (yes/no)
_Bisq will not list your token if it has taken part in an initial coin offering (ICO)_

no ico

**Comment by unsivilaudio** [comment]
+1

**Comment by Mas7erMind** [comment]
+1

**Comment by Mas7erMind** [comment]
Any update regarding this request? Thanks!

**Comment by Mas7erMind** [comment]
We are an active project interested to be listed on bisq.

**Comment by dr3igon** [comment]
Great project with huge potential!

**Comment by Teredic** [comment]
the project has already been on bisk as "stellite" (stl) last year, but it looks like it got removed.

So yeah it should be listed again.

**Comment by Mas7erMind** [comment]
What informatin do you need to get listed here? Thanks.

**Comment by Mas7erMind** [comment]
We are active and just want more information about the procedure. @freimair
