### ISSUE TITLE
Fold bank account subtypes into one for SEPA accounts

### ISSUE THREAD

**Issue by yoshimo** [bisq-network/bisq#3146]
we have multiple account types SEPA, SEPA Instant, "only own bank" , "just the same country".
All these payment options can be served with the same sepa enabled european bank account.
So having to make multiple copies for my bank account to take multiple types of offers is unnecessary. Each copy has their own age and reputation, which is annoying.

Can't we fold it into  "SEPA Account" and depending on your IBAN and bank account enable the restrictions automatically (same bank, same country) or flag it manually (sepa)?

**Comment by freimair** [comment]
Is almost impossible to retrofit that feature into the Bisq network. However, when the queued up "protection tools" are available, we might get rid of the "own age and reputation" and the trade amount restrictions.

**Comment by yoshimo** [comment]
even without the reputation issue i would fold it into one if possible.

**Comment by yoshimo** [comment]
Stale is the wrong mark ,it hasnt been rejected yet

**Comment by gordonel** [comment]
I think we should fold SEPA Instant in the following fashion:
- "SEPA" filter only shows SEPA trades
- "SEPA Instant" shows both SEPA and SEPA Instant

**Comment by yoshimo** [comment]
This is still undecided.
