### ISSUE TITLE
F2F trade stuck in some weird state

### ISSUE THREAD

**Issue by Giszmo** [bisq-network/bisq#3159]
As I shared on [reddit](https://www.reddit.com/r/bisq/comments/cwj1ru/selling_f2f_but_not_sure_what_to_do/):

I see on Portfolio -> open trades a green item/line where I'm "BTC seller as maker" and I assume it's green because it's selected but the bullet points "Wait for blockchain confirmation" etc. are all greyed out.

In the information I see the taker fee transaction and the maker fee transaction and they have 20 and 2800 confirmations respectively but the taker fee transaction doesn't have the tick with the tooltip next to it as the maker fee transaction does.

I restarted bisq. I updated it to the latest version but nothing helps. My full node is not stuck, as the confirmations on the maker tx match what the block explorer says.

The taker is also available to provide his side I think. Just had a call with him and will meet him tomorrow.

![](https://i.imgur.com/EpDxVKa.png)

**Comment by Giszmo** [comment]
Taker chimed in on Reddit. He saw "An error occurred at task: BuyerAsTakerSignAndPublishDepositTx"

**Comment by Giszmo** [comment]
CTRL-O would allow me to open a dispute, so I assume the trade is correctly selected but broken. I'll delay this to see if the current state is of any value to debug this.

I disabled my other trades after having seen a recommendation to not use the same folder after some possible DB corruption.

**Comment by mjlamb** [comment]
Yes that correct I got the "An error occurred at task: BuyerAsTakerSignAndPublishDepositTx" in a popup on screen. My taker fee has been broadcast, but do not know what has happened.

**Comment by ManfredKarrer** [comment]
Check if the maker fee tx leads to the deposit tx (second output of maker fee tx and taker fee tx). You can see them at trade details by clicking the trade id.

**Comment by Giszmo** [comment]
> Check if the maker fee tx leads to the deposit tx (second output of maker fee tx and taker fee tx). You can see them at trade details by clicking the trade id.

I guess I will figure it out but the terminology is not clear yet.

The fee transactions are [this](https://www.smartbit.com.au/tx/64ddc4078b5bf410aa454c3eedf84d03549b11393614b7cb1d548eb204d778bd) and [this](https://www.smartbit.com.au/tx/411d1285026e0b7fa72adfed7161a3e70c214da0ecfd1d8742f777f081597169). I see their respective first outputs go to the [same P2PKH address](https://www.smartbit.com.au/address/1J9U8Vf8oAjB8fboym1CBSVhmopxsNek9m) and not only these two send there ... ok, I assume this is the marker, so all the world knows its a bisq transaction aka the fee for the project transaction? The second outputs go to different addresses.

I'm actually quite surprised to see no P2SH addresses in all this. Would that be the next step? So we don't need an arbitrator to pull out now, apart from the fee being paid for nothing? Wouldn't it make more sense to fork out the fee as part of the payout? Would be less UTXOs and cheaper for both users and the project?

**Comment by Giszmo** [comment]
I emergency-transfered my funds out of bisq as the trade remained broken. I am a bit confused though. The trade remains listed in my portfolio marked as 0.05BTC but top right I read 0BTC available/reserved/locked. That should reliably be all bitcoins in the wallet, right? As I did a backup, I would next close bisq until I feel keen to wipe data, restore from backup, ... whatever to get rid of the broken trade.

**Comment by huey735** [comment]
Related to https://github.com/bisq-network/bisq/issues/3306
