### ISSUE TITLE
Race condition(?) while entering text in autocomplete dropdown

### ISSUE THREAD

**Issue by wiz** [bisq-network/bisq#3171]
[How to Reproduce]
1) Click on Buy BTC from top navigation
2) Double click on "Filter by currency" autocomplete dropdown
2) Type in "USD"

[Expected Result]
Field should contain "USD"

[Actual Result]
Field contains "DUS all"

![combobox](https://user-images.githubusercontent.com/232186/64066991-d0484c00-cc5b-11e9-88c6-c089ebb1c9ac.gif)

@battleofwizards

**Comment by battleofwizards** [comment]
Obviously, you are correct about the expected behavior.

Does it happen right out of the box for you? Or some preparatory "playing" with the app is first required?

Does it happen pretty much all the time? Or occasionally?

**Comment by wiz** [comment]
It reproduces 100% when the text is selected by any method, for example double click and triple click also reproduce this bug so JPY -> PYJ

**Comment by battleofwizards** [comment]
Got it!

Could you please change the "How to reproduce" step 2. to "Double-click" so others can easily recreate the problem?

Can you confirm the single-click is fine?

**Comment by wiz** [comment]
Great. Yeah, since single click does not select text, it does not reproduce this issue.
