### ISSUE TITLE
[Feature] Accept VISA/Mastercard/DebitCard

### ISSUE THREAD

**Issue by gjhklfdsa1** [bisq-network/bisq#3173]
**Feature**: Allow payments via [VISA](https://www.wikipedia.org/wiki/Visa_Inc.)/[Mastercard](https://www.wikipedia.org/wiki/Mastercard)

**Why?**: Despite many privacy concerns with both organizations they are still the most popular way to make transactions.

**Possible Solution**:
Dues to the general centralization of providers like Square, I propose allowing buys/sellers to choose a trustee. Similar to how OpenBazaar does for moderation/escrow.

The trustee could then process the payment and send then send a stable coin to the seller once the payment to the buyer has been sent.

The trustee wouldn't actually need to know either parties and still keep very high anonymity. :)

**But payment processors are proprietary!**: Yes, most are.
However, [MangoPay](https://www.mangopay.com/en_UK/) and [CiviCRM](https://civicrm.org/) don't need to execute any non-free code on the users device.

**Comment by wiz** [comment]
Chargeback risk is too high to accept credit cards as payment methods on Bisq
