### ISSUE TITLE
Display better error message when user cannot connect to network at startup

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#318]

**Comment by cbeams** [comment]
@ManfredKarrer, why remove the "done" label on this issue? The idea is that this work is complete, and should thus shows up in the "Done" column in HuBoard. Good for everyone to see, no? Maybe I missed something here...

**Comment by ManfredKarrer** [comment]
hm.... was not intended, i archived it.

**Comment by cbeams** [comment]
ah! ok. clicking "Archive" removes the "Done" label. That wasn't clear to me.

Let's leave everything marked with the "Done" un-archived until our weekly calls, so that we can use the done column in HuBoard for a quick review of what's been accomplished over the week.

**Comment by ManfredKarrer** [comment]
ok.
