### ISSUE TITLE
UI issues with Dark Theme not fixed in v1.1.6

### ISSUE THREAD

**Issue by wiz** [bisq-network/bisq#3185]
These known UI issues were not fixed in time for v1.1.6 merge cutoff and will be tracked in this new issue instead:

1) Graph icons are black font color
<img width="175" alt="Screen Shot 2019-09-02 at 23 00 01" src="https://user-images.githubusercontent.com/232186/64119713-6c499300-cdd5-11e9-9cd1-aa81bd3026b6.png">

2) Progress bar track remains visible after syncing is completed
<img width="1194" alt="Screen Shot 2019-09-02 at 22 59 06" src="https://user-images.githubusercontent.com/232186/64119639-491ee380-cdd5-11e9-87dc-2a3aad6315c9.png">

3) Certain DAO icons need re-styling for grey theme
<img width="55" alt="Screen Shot 2019-09-02 at 5 16 08" src="https://user-images.githubusercontent.com/232186/64120005-175a4c80-cdd6-11e9-9a8b-41d90d51c5be.png">

4) Trade chat bubbles background color and font color need improvement
![trade-chat](https://user-images.githubusercontent.com/232186/64121390-ae74d380-cdd9-11e9-8ec4-135d98d65b00.png)

**Comment by ghubstan** [comment]
5. MathUtils ArrayIndexOutOfBoundsException occurs after clicking DAO menu tab in Arbitrator client.

[bisq-arb-darkmode-error.log](https://github.com/bisq-network/bisq/files/3585489/bisq-arb-darkmode-error.log)

OS  Ubuntu 18.04.3 LTS
Kernel 5.0.0-27-generic 28~18.04.1-Ubuntu
GNOME Shell 3.28.4

**Comment by wiz** [comment]
@ghubstan I don't understand the issue you're trying to report, but it doesn't seem like an UI issue or related to the Dark Mode theme, so it's probably best to report it as a new issue.

Also, when you report issues, it's best to include the steps to reproduce the issue along with the expected/actual results, and a a screenshot if applicable. Here's an example bug report https://github.com/bisq-network/bisq/issues/3137

**Comment by ghubstan** [comment]
I thought the error was related to darkmode, which I'm
[testing](https://bisq.ontestpad.com/script/90#6/1/) now.
But I'm wrong.  It happens in lightmode too.  I'll create a new issue if one doesn't exist for this bug.
I'd like to delete the above message to get rid of the noise (not just my embarrassment).
That's up to you.

**Comment by ghubstan** [comment]
5. Text bubble activated by hovering over chart icon in Buy & See BTC windows are not readable, nor styled for dark theme.

![unreadable-tooltip-text-2019-09-06](https://user-images.githubusercontent.com/36207203/64461965-39edad80-d0d5-11e9-8467-f9d6880789e0.png)

The chart icon itself is also hard to see.

**Comment by wiz** [comment]
Thanks for reporting, that one is definitely an issue with the Dark Mode, but so far haven't figured out how to style that popup bubble. Maybe @ripcurlx has some advice for me how to fix that one?

**Comment by ghubstan** [comment]
6.  Switching back to light mode after restart does not work on 1st attempt (Linux Ubuntu 18)

[How to Reproduce]
* Start Arbitrator, Alice or Bob desktop
* Enable dark mode
* Shut down Arbitrator, Alice or Bob desktop while in dark mode
* Start Arbitrator, Alice or Bob desktop
* Disable dark mode (no effect)
* Enable dark mode
* Disable dark mode (now it works)

[Expected Results]
Dark mode should be disabled when setting is manually disabled the first time.

[Actual Results]
Dark mode is not disabled when setting is manually disabled the first time.
Dark mode is disabled after manually enabling dark mode, and switching back to light mode a second time.

![Bob-LightMode](https://user-images.githubusercontent.com/36207203/64539381-c5915500-d2f4-11e9-864f-891372f98756.png)
![Arb-LightMode](https://user-images.githubusercontent.com/36207203/64539384-c629eb80-d2f4-11e9-9d1a-443d67e883fa.png)

**Comment by wiz** [comment]
The "remove" button text color is hard to read
<img width="206" alt="Screen Shot 2019-09-17 at 22 23 46" src="https://user-images.githubusercontent.com/232186/65045549-f9761580-d999-11e9-8288-34db65d03950.png">

**Comment by ghubstan** [comment]
Will leaving a comment keep this issue alive?

**Comment by wiz** [comment]
@ghubstan I didn't forget about this. I actually looked into the bubbles background color and tried a few fixes, but they still refused to take any coloring from me. It's either a weird quirk of openjfx GUI element styling, or something unusual in the Bisq code

**Comment by ripcurlx** [comment]
I think everything except the chat bubbles has been fixed already.
