### ISSUE TITLE
[Question] Where is the IOS/Android Source Code?

### ISSUE THREAD

**Issue by ghbjklhv1** [bisq-network/bisq#3198]
**Question**: Where is the [IOS](https://itunes.apple.com/us/app/bisq-mobile/id1424420411) and [Android](https://play.google.com/store/apps/details?id=com.joachimneumann.bisq) application's source code?

Is it possible to have a F-Droid listing?
https://www.wikipedia.org/wiki/F-Droid

**Comment by m52go** [comment]
https://github.com/joachimneumann/bisqremote_Android
https://github.com/joachimneumann/bisqremote_iOS

The Android app uses Firebase for push notifications, which is not allowed by [F-Droid rules](https://f-droid.org/en/docs/Inclusion_Policy/). There may be other issues preventing F-Droid listing but that's probably one of the main ones.

**Comment by devinbileck** [comment]
I think we should fork those repos so that they are within the bisq-network org.
@ripcurlx are you able to do that?
