### ISSUE TITLE
Add error msg in case of bitcoin network problems

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#320]
## Motivation

If a user cannot establish a connection to the bitcoin network (mainnet or testnet), probably due to being behind a restrictive router, the application splash screen will show indefinitely. The bitcoin network progress bar will remain at zero, and the p2p progress wheel will spin forever. This results in a confusing experience for the user, as they have no way of knowing what's wrong
## Approach

Add a timeout for connecting to the bitcoin network and display a message dialog explaining the problem if the timeout is exceeded. Perhaps provide a link to our wiki, where further instructions or workarounds are laid out

**Comment by cbeams** [comment]
@ManfredKarrer I've updated the description here. Please review.

**Comment by cbeams** [comment]
@ManfredKarrer, per https://github.com/bitsquare/management/issues/94#issuecomment-66609017, suggest that we get this implemented before actually releasing v0.1. Have assigned to you, marked as ready. That work for you?

**Comment by cbeams** [comment]
Awesome. Thanks, Manfred.

**Comment by cbeams** [comment]
Reopening for review. I'll test this out.

**Comment by cbeams** [comment]
Reviewed, closing as done. Manfred, see my updates to status and error messages in beb4645.
