### ISSUE TITLE
can not add LTC address

### ISSUE THREAD

**Issue by Ginsley** [bisq-network/bisq#3209]
Hello - installed BISQ today and it looks good so far - but i can not use it :/

To say - i would like to trade in BTC to get LTC - i wanted to set up a LTC account, but cannot use my LTC address (like MMBxeLZtbWvRN9eXWqpuAbTNvq2GNcpeuq) - as the program says its no LTC address.

The address was created by the Litecoin Core wallet.

What am i doing wrong?^^

**Comment by Ginsley** [comment]
![bisq_Ltc](https://user-images.githubusercontent.com/25739540/64352488-6b467a80-cffc-11e9-9f04-1196089f1ab7.png)

**Comment by Ginsley** [comment]
![bisq_Ltc2](https://user-images.githubusercontent.com/25739540/64352547-887b4900-cffc-11e9-8db7-127d2dab4e7d.png)

**Comment by battleofwizards** [comment]
The new-style segwit p2sh Litecoin addresses are not supported, sorry!

Please convert your address to legacy segwit p2sh:
https://litecoin-project.github.io/p2sh-convert/

Or even better generate legacy segwit p2sh with your wallet so you don't have to trust the conversion service.

**Comment by Ginsley** [comment]
Thanks for that hint - will there be support for segwit on LTC?
