### ISSUE TITLE
Overview about gain/loss on trades

### ISSUE THREAD

**Issue by remyers** [bisq-network/bisq#321]
Request from our comment page for a way to track gain/loss when trading bitcoin using Bitsquare.

Subject: gains/losses

Message:
For US residents, tracking purchases and sales of crypto is required
to be entered as gains and losses on a schedule d. this can be a very
time consuming process to record the purchase date, price, and sell
date and price and also calculate any wash sales. currently no crypto
client integrates gains/losses into an easily exportable format as
most wallets do not deal with the actual fiat exchange. Up until a few
years ago stock brokers were not required to submit a gains/losses
sheet to the customer. customers previously had to track this info
themselves. can you please implement a gains/losses feature that can
export to my schedule d in an efficient manner?

**Comment by ManfredKarrer** [comment]
Thanks for adding it. I read it but atm I am not sure about that topic. Lets think about it when time comes, for sure nothing we can work on before 0.8 or so...

**Comment by haiqu** [comment]
US tax issues are a nightmare and really shouldn't be considered in the code. We are not writing an accounting package here, and if we were it would have to account for the rules of every tinpot regime in existence, including yours.

There is sufficient data available in the History view to determine what you need but it will have to be a manual process. There is no way to determine the price paid for incoming transfers to the wallet.

Manfred, please close.

**Comment by ManfredKarrer** [comment]
There is already a csv export feature for transactions, so from that one can render whatever is needed.
