### ISSUE TITLE
Traders chat - testing version 1.1.6

### ISSUE THREAD

**Issue by mpolavieja** [bisq-network/bisq#3210]
OS: Windows 7
Bisq version: 1.1.6-ec633f0c3771893b47956b8d05b17c6f3f1919c1-all (testing 2nd release)

Alice is running version 1.1.5 and Bob is running version 1.1.6.  Bob takes a buy offer from Alice (trade 9778566).  Then Bob sends a message to Alice and sees the text "Message arrived at receiver", when he should be notified that his trading peer does not support direct traders chat.

![image](https://user-images.githubusercontent.com/17677608/64359434-9b941600-d008-11e9-8b52-6c10e316f72d.png)

![image](https://user-images.githubusercontent.com/17677608/64359425-959e3500-d008-11e9-8184-834352daedc7.png)

As an additional issue but not as critical, when Bob sends a message to Alice while she is offline.  Bob sees the sent message as "Message saved in receiver´s mailbox".  Alice comes back online and receives the message correctly, but when she opens the chat, the message sent by Bob is not confirmed as received within Bob Chat box. The text "Message saved in receiver´s mailbox" remains.  Restarting both Bob and Alice does not fix it

**Comment by battleofwizards** [comment]
This maybe due to a bug but in my view it is a **privacy feature**.

You cannot infer software version of the second party. If this would work as you suggest then `=1.1.6` knowledge would vastly limit anonymity set.

Trading partners are not required to answer chat messages anyway.

**Comment by chimp1984** [comment]
Better to wait for more testin of the trader chat as I did massive refactoring when working on the mediation support. 
We will enforce users to update in a few days. Supporting feeback that the peer has an old version and does not see the msg seems not worth is for the short time span.

**Comment by mpolavieja** [comment]
You both make a fair point.  I was just following the test script where it was specified that the peer should get a message about the other peer not having a version with trade chat functionality.  Then maybe we should remove this requirement from the test script?

**Comment by devinbileck** [comment]
Yes good points. I had added that scenario to the test as I thought it may be desired behavior, but as @chimp1984 mentions if we are forcing an update there is likely little benefit to implementing it. I will remove the test scenario.

**Comment by ripcurlx** [comment]
Closing as complete by https://github.com/bisq-network/bisq/issues/3210#issuecomment-528935990
