### ISSUE TITLE
V1.1.6 dao tab click causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ghubstan** [bisq-network/bisq#3220]
DAO tab click in full dao mode v1.1.6 client causes MathUtils ArrayIndexOutOfBoundsException

[How to Reproduce]
Start fresh bitcoind -regtest.
Copy predefined full dao setup to application folders (as you do for testpad v1.1.6 testing).
Start an arbitrator instance in full dao mode.
Start an Alice instance in light dao mode.
Click the DAO tab (Dashboard) in the arbitrator and alice desktops.

An error window will appear to open log / report issue.
Stack Trace:
```
Sep-06 16:39:01.826 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.ArrayIndexOutOfBoundsException: -1
	at bisq.common.util.MathUtils.getMedian(MathUtils.java:102)
	at bisq.desktop.main.dao.economy.dashboard.BsqDashboardView.getAverageAndMedian(BsqDashboardView.java:369)
	at bisq.desktop.main.dao.economy.dashboard.BsqDashboardView.updateAverageAndMedianPrice(BsqDashboardView.java:338)
	at bisq.desktop.main.dao.economy.dashboard.BsqDashboardView.activate(BsqDashboardView.java:174)
```
[Expected Results]
DAO window should open without error message, and no exception thrown.  In general, exception messages shown to user should be human readable, instead of (-1).

[Actual Results]
See screenshot and attached log.
![DAO-TAB-2019-09-06](https://user-images.githubusercontent.com/36207203/64457823-0eb19100-d0ca-11e9-9264-237061bdf6f7.png)
[dao-tab-error.log](https://github.com/bisq-network/bisq/files/3585580/dao-tab-error.log)

After bitcoin blocks are generated and buy / sell offers are created, this error occurs intermittently.

System details:
OS Ubuntu 18.04.3 LTS
Kernel 5.0.0-27-generic 28~18.04.1-Ubuntu
GNOME Shell 3.28.4

**Comment by ghubstan** [comment]
OS Ubuntu 18.04.3 LTS
Kernel 5.0.0-27-generic 28~18.04.1-Ubuntu
GNOME Shell 3.28.4

**Comment by ripcurlx** [comment]
@ghubstan I didn't experience this on local regtest. Please re-open this issue you still get this error on current master. Thanks!
