### ISSUE TITLE
V1.1.6 "Avoid Standby Mode" does not work on Ubuntu 18

### ISSUE THREAD

**Issue by ghubstan** [bisq-network/bisq#3223]
[How to Reproduce]

1.  Create a VM:  Ubuntu 18.04.3 LTS
	Kernel 5.0.0-27-generic 28~18.04.1-Ubuntu
	GNOME Shell 3.28.4 
	Apt update/upgrade should give you the same or more recent kernel & gnome versions.
	
2.  Open VM's Settings->Power->Automatic Suspend->Plugged In
	Set ON with Delay of 15 minutes.
	
3.  Install Bisq (w/ v1.1.6 test jar) and start an Arbitration client.
    Enable Settings -> "Avoid Stanby Mode".
    
4.  Don't touch anything for 15 minutes; watch Ubuntu 18 go into standby mode.

[Expected Results]

The Ubuntu 18 VM should not go into standby mode.

[Actual Results]

The Ubuntu 18 VM goes into standby mode.

**Comment by wiz** [comment]
Ah yeah, it's not going to work on Linux. IMO the correct fix for Linux would be to simply hide the feature. Users on Linux can disable the OS sleep mode on their own.

**Comment by niyid** [comment]
Hello. Is anybody working on this yet?

**Comment by ghubstan** [comment]
@niyid , I am working on this now.

**Comment by ghubstan** [comment]
@chimp1984, the row adjustment fix has been committed.

I have not confirmed there is no need for the Unix sound hack.  Can @wiz or @niyid confirm there is no need for the Unix sound hack?
