### ISSUE TITLE
Add UI for UpdateFX

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#323]

**Comment by cbeams** [comment]
Manfred, I've prioritized this above #102. Do you think you can put together a stubbed-out UI for UpdateFX—progress bar, etc, basically modeled on what Mike has done? I can then provide the backend implementation. Or we can just work together on this stuff more or less at the same time.

**Comment by ManfredKarrer** [comment]
I started yesterday looking into it. It seems a bit more effort as I thought initially, but I think in 1 or 2 days I should have something. I also wanted to understand whats going on in hte backgound exactly. Mike has a demo app in his updateFX lib so I will try to start with that and then create a branch on our app impl. it.

**Comment by ManfredKarrer** [comment]
@cbeams: We can use the incrementing version number from updateFX as build version number so it fits into our semantic versioning. 0.1.1 -> 0.1.999.. 
When we change a minor version  (0.2) we provide a new base binary. So users are about major dev improvements also more aware. As those minor verison updates will be not too often I think we still have a good mix of the benefits of updateFX and dont run into problems with our versioning scheme.
Later we might fork updateFX and add semantic versioning support or find other solution how to deal best with it.

**Comment by ManfredKarrer** [comment]
Another solution would be to provide a mapping layer. So the incrementing version number from updateFX is treated as a pure technical data and converted/represented using a mapping.

**Comment by remyers** [comment]
At work we do major.major.minor.build . Where the build number is always
incrementing and does not reset between versions.

For example 6.0.4.24518 is our current release.  The major version is 6.0
and it's the 4th release to be tested and distributed.  The build number
corresponds to the last check-in number to our source control repository.
I did this to make it easier to automate our builds.  I'm not sure how git
works, but this was the recommended way to do it in Perforce as I recall.
The major/minor versions are incremented by hand, but build is incremented
automagically.

Just sharing my experience.  It sounds similar to what Manfred is
proposing, only with one major version number instead of two.

**Comment by ManfredKarrer** [comment]
Ah true we don't need to reset the updateFX number between version changes (0.1 to 0.2).

Am 15.12.2014 um 14:27 schrieb Richard Myers notifications@github.com:

**Comment by ManfredKarrer** [comment]
@cbeams 
I tried to get the example app running from the UpdateFX sources, but i ended up with a BadUpdateHash exception. Discussed it with Mike but we did not find the reason yet.
Maybe you can try it out if it works for you? 

Not sure if you have already dived into it, if so just ignore the following...
It is pretty straigth forward if you use the build.sh script (see below the updated version as the one checked in is out of date).
If you need assistence let me know, but maybe better if you try it out yourself, so if I did anyhing strange we don't repeat it... 
The description at https://github.com/vinumeris/updatefx is very informative and easy to follow.
Only thing is that you need to change the PubKey in the file after you run it first, and then re-run it so the file with your key gets compiled.

build.sh
#!/bin/bash

mvn clean package -DskipTests
cp examples/target/updatefx-examples-1.3-SNAPSHOT.jar examples/website/builds/1.jar
sed -i .bak 's/public static int VERSION = 1;/public static int VERSION = 2;/' examples/src/main/java/ExampleApp.java
mvn clean package -DskipTests
cp examples/target/updatefx-examples-1.3-SNAPSHOT.jar examples/website/builds/2.jar
mv examples/src/main/java/ExampleApp.java.bak examples/src/main/java/ExampleApp.java
java -jar app/target/updatefx-app-1.3-SNAPSHOT.jar --url=http://localhost:8000/ examples/website
rm -rf examples/deploy/*
$JAVA_HOME/bin/javapackager -deploy -outdir examples/deploy/ -outfile UFXExample.dmg -name UFXExample -native dmg -appclass ExampleApp -srcfiles examples/website/builds/1.jar

**Comment by ManfredKarrer** [comment]
@cbeams Above comment is not relevant anymore (see also mail).
I forked and checked in the changes:
https://github.com/bitsquare/updatefx/

**Comment by ManfredKarrer** [comment]
@cbeams You have seen probably the new branch I created for it. There are a few smaller issues to discuss (see the TODOs) but maybe lets try first to get it working with the builds...
