### ISSUE TITLE
Table view columns should use a numeric-sort algorithm

### ISSUE THREAD

**Issue by wiz** [bisq-network/bisq#3231]
<img width="103" alt="Screen Shot 2019-09-09 at 22 34 48" src="https://user-images.githubusercontent.com/232186/64535664-a3c6bb00-d352-11e9-912d-40b0251e4bcb.png">

**Comment by niyid** [comment]
@freimair 
Who is assigning? I suppose this issue is to be resolved in all table views and not only Bonds view?

**Comment by niyid** [comment]
Hi @sqrrm 

Thanks for this. If you do not mind, please also take a look at this:

https://github.com/bisq-network/bisq/pull/3932
