### ISSUE TITLE
Trouble running Bisq v1.1.5 in Windows 10 x64 (it did not launch anything!)

### ISSUE THREAD

**Issue by GoldenTicket007** [bisq-network/bisq#3233]
Hi, i have been trying to install and run Bisq v1.1.5 in a laptop Dell Inspiron 15R, i7-4500U with Windows 10 x64, now running version 1903.

The download and installation seems to work fine. But when the app is lauched the process from bisq.exe disappear on the task manager and the software did not run. Nothing starts. 

I have tried to uninstall a vpn software, to put a permission for bisq on windows firewall, uninstall and resintallation the bisq software and still nothing happens.

Someone on the internet said to erase manually every file after removing the app. I tried it also but the folder Bisq gets installed is on the AppData\Local and when uninstalled nothing is left there.

Can someone help? What else could I do?
Thanks in advance,

**Comment by GoldenTicket007** [comment]
I think it did not get to run at all. The \AppData\Roaming\ folder did not contain a Bisq folder inside.

In fact, when I execute the shortcut or .exe file, no process appear in the task manager. When I lauch it from setup wizard, I can see the setup/instalation (32 bits) process both in apps and on the background and they quickly disappears after.

What else can be done? It is possible to be a conflict-bug with another software? Could Bisq being blocked by something else?

**Comment by devinbileck** [comment]
Do you have an antivirus program running?

**Comment by ripcurlx** [comment]
> I think it did not get to run at all. The \AppData\Roaming\ folder did not contain a Bisq folder inside.
> 
> In fact, when I execute the shortcut or .exe file, no process appear in the task manager. When I lauch it from setup wizard, I can see the setup/instalation (32 bits) process both in apps and on the background and they quickly disappears after.
> 
> What else can be done? It is possible to be a conflict-bug with another software? Could Bisq being blocked by something else?

Do you have special characters in your user directory? We recently fixed this by checking it during installation and offering alternative install directories as it will prevent the application to start in that case.

**Comment by ripcurlx** [comment]
Closing because of no respond from author.
