### ISSUE TITLE
Error placing offer No funds left wallet

### ISSUE THREAD

**Issue by jason-me** [bisq-network/bisq#3234]
An error occurred when placing the offer:

An error occurred.
Error message:
Insufficient money,  missing 0.001549 BTC

No funds have left your wallet yet.
Please restart your application and check your network connection.

**Comment by jason-me** [comment]
Fixed upon re-start. Logged issue as requested by BISQ UI for tracking purposes.

**Comment by wiz** [comment]
Can you please include steps to reproduce this issue, along with expected and actual results?
