### ISSUE TITLE
Offers not displayed

### ISSUE THREAD

**Issue by cryptopayserver** [bisq-network/bisq#3238]
Hello, I creatd two offers to buy btc. This offers is not displayed in buy book. I can not edit also can not delete offers. I have funds reserved. Please, What I Can do ??

**Comment by ifarnung** [comment]
I think I can solve this issue despite being a noob.  When you create a buy order, your orders would actually appear under the sell tab, as prospective customers would be looking to Sell to you.  So please check in both tabs and you should find your two orders.

**Comment by ifarnung** [comment]
I recommend closing this issue. User may have figured it out on their own as there are only so many tabs to look through,

**Comment by cryptopayserver** [comment]
Solution was restore a backup before I made offers. thanks
