### ISSUE TITLE
Error adding XMR Altcoin account:  Address is not a valid XMR address! invalid address prefix 13 

### ISSUE THREAD

**Issue by ifarnung** [bisq-network/bisq#3242]
Huey in the BISQ Forum recommended I escalate this issue/error.  I am trying to add an altcoin account, XMR, and am using a valid address but it is screening it out due to thinking it starts with a 13.

"Address is not a valid XMR address! invalid address prefix 13"

Thanks for any help and sorry if this is in the wrong place, I'm new here,

Attaching screenshot.
![image](https://user-images.githubusercontent.com/55181240/64695554-1b0c6400-d4a5-11e9-9fbe-5f7f9c196994.png)

**Comment by battleofwizards** [comment]
Thanks for your bug report!

* Could you please state your Bisq version?
* Could you please paste your XMR address as text?
* Does it happen repeatedly for this address or is it a one-time glitch / race condition?

**Comment by ifarnung** [comment]
Version 1.1.5
4GdoN7NCTi8a5gZug7PrwZNKjvHFmKeV11L6pNJPgj5QNEHsN6eeX3DaAQFwZ1ufD4LYCZKArktt113W7QjWvQ7CWD1FFMXoYHeE6M55P9
or I also tried (4GdoN7NCTi8a5gZug7PrwZNKjvHFmKeV11L6pNJPgj5QNEHsN6eeX3DaAQFwZ1ufD4LYCZKArktt113W7QjWvQ7CW82yHFEGvSG3NJRNtH)
Happens every time I try it.

Thanks battleofwizards

**Comment by battleofwizards** [comment]
I can confirm the issue.

Both of your addresses are accepted by Monero GUI but not accepted by Bisq.

**Comment by chimp1984** [comment]
@ripcurlx That might be worth to try to get into the release. 
Buggy validation is a pain....

**Comment by ripcurlx** [comment]
@xiphon Could you have a look at the Monero validation?

**Comment by battleofwizards** [comment]
Address validation in Bisq does not support the so called **integrated addresses**.

As a temporary workaround please use a subaddress.

As a sidenote, in Monero subaddresses are recommended over integrated addresses (but we definitely should support both).

**Comment by battleofwizards** [comment]
I will submit a fix very soon. Stay tuned.
