### ISSUE TITLE
Addition of Cardano (ADA)

### ISSUE THREAD

**Issue by RajaMBZ** [bisq-network/bisq#3257]
-Asset name: Cardano
-Ticker: ADA
-Block explorer URL: https://seiza.com/ or https://cardanoexplorer.com/
-Initial coin offer: Yes, but being one of the top coins (by market cap), it deserves a chance for listing, just like Ethereum.

**Comment by ghost** [comment]
For information,
I had a look at cardano ADA ~one year ago.
It appeared then that ~97% of the coin volume was in fact owned by 3 entities.
My guess was then that, sooner or later, people will be aware of that.
(I'm however in favor of listing altcoins. The more there are markets, the faster the traded price goes to the real value).

**Comment by RajaMBZ** [comment]
Thanks for your reply! I think that ADA should be considered for addition. Right now, it may be available at Binance, Bittrex, BitMEX, KuCoin, etc, but it's still not accessible for trading at many places (such as the New York state).

**Comment by RajaMBZ** [comment]
It'd be great if this issue can gain some more valuable inputs.

**Comment by outermeasure** [comment]
Are there any news regarding this altcoin?
I am looking forward to acquire some ADA, because the underlying technology looks quite promising.

**Comment by ripcurlx** [comment]
> Are there any news regarding this altcoin?
> I am looking forward to acquire some ADA, because the underlying technology looks quite promising.

Unfortunately because of lack of dev resources and based on our experience when adding new assets in the past, adding new altcoins don't have priority right now.
