### ISSUE TITLE
Warning pop-up while selling bsq's

### ISSUE THREAD

**Issue by acrual** [bisq-network/bisq#3267]
Hi, I was in the process of selling bsq for btc. After the first blockchain confirmation, I introduced the buyer's address and the amount in the bsq wallet getting the following error when clicking "send"

![image](https://user-images.githubusercontent.com/6545195/64966083-6b693480-d89e-11e9-9ac2-eca0660cb86d.png)

**Comment by ripcurlx** [comment]
Could you please post the part of the log file where the exception was thrown?

**Comment by ripcurlx** [comment]
Maybe also switch to the light theme to see if there is something written in the error popup.

**Comment by acrual** [comment]
> Maybe also switch to the light theme to see if there is something written in the error popup.

Thanks the error shows identical when in clear mode I'm afraid
![image](https://user-images.githubusercontent.com/6545195/64970208-a327aa80-d8a5-11e9-85d9-52677f7ce43b.png)

**Comment by acrual** [comment]
@ripcurlx please ignore for now. I had selected my localhost bitcoin node, yet I had not started it. I have now chosen the public bitcoin network and when I get the minimum number of connections I will give it a try again and post the result here. Sorry for the inconvenience, just landed and still learning bisq's ins and outs. Thank you

**Comment by chimp1984** [comment]
Please check if you use a local pruned bitcoin node, from the logs you posted on slack it looks so. Bisq does not work with pruned btc nodes.

Popup still should be fixed

**Comment by acrual** [comment]
> Please check if you use a local pruned bitcoin node, from the logs you posted on slack it looks so. Bisq does not work with pruned btc nodes.
> 
> Popup still should be fixed

Yes, popup should be fixed. I have restarted with the public bitcoin network, and then this other error has happened. Please check here: https://github.com/bisq-network/bisq/issues/3272
