### ISSUE TITLE
Dark mode: My Vote coloring unclear.

### ISSUE THREAD

**Issue by ifarnung** [bisq-network/bisq#3268]
Love the new dark mode! Especially because someone always initiates a trade as I'm about to go to bed.  Anyway, is there a way to color this differently?
![image](https://user-images.githubusercontent.com/55181240/64966873-3feb4780-d8a8-11e9-81bf-74b06396a84c.png)
Red like this would be good, for the No Vote.
![image](https://user-images.githubusercontent.com/55181240/64966918-5abdbc00-d8a8-11e9-9f06-3e97ad92c956.png)

Ian

**Comment by wiz** [comment]
Thanks for reporting, but this is a known issue #3185
