### ISSUE TITLE
Error while selling bsq

### ISSUE THREAD

**Issue by acrual** [bisq-network/bisq#3272]
After the error I got here, 
github.com/bisq-network/bisq/issues/3267
I changed my bitcoin connection to "existing public bitcoin network" instead of my local bitcoin node.

I went to my bsq wallet and made the tx. This time it worked. 

While waiting in the "portfolio" tab for the bsq buyer to pay me back, I clicked on the "Funds button" and then got this other error that I paste down here. I also paste the log too.
[bisq.log](https://github.com/bisq-network/bisq/files/3617068/bisq.log)

![image](https://user-images.githubusercontent.com/6545195/64972696-00bdf600-d8aa-11e9-815a-172fe2352dd0.png)

**Comment by acrual** [comment]
The error seems to happen everytime I go to the RECEIVE FUNDS tab within FUNDS tab. Every other tab seems to work normally.

**Comment by chimp1984** [comment]
You run the release binary, right?

**Comment by chimp1984** [comment]
Do not use "existing public bitcoin network" but the provided nodes. That gives you better privacy. It has to be expected that chain analyis companies run public nodes ans try to spy on your wallet. Provided nodes are operated by Bisq contributors.

**Comment by acrual** [comment]
> Do nor use "existing public bitcoin network" but the provided nodes. That gives you better privacy. It has to be expected that chain analyis companies run public nodes ans try to spy on your wallet. Provided nodes are operated by Bisq contributors.

OK!

**Comment by acrual** [comment]
> You run the release binary, right?

I am running the release suggested by version 1.1.5 and I checked the signatures by Christoph and everything was ok

**Comment by chimp1984** [comment]
If all ok now can you close the issue?

**Comment by acrual** [comment]
> If all ok now can you close the issue?

sorry, let me explain: I meant that everything was ok with the signatures, downloading and installation, but at that moment, the issue was still happening, as every time I clicked on Funds and Receive Funds, that error showed up.

However, I shut down the application and restarted again and the error is no longer showing up.

I'll close the issue now. Thanks very much for your help.
