### ISSUE TITLE
If audio is muted on OSX standby gets activated 

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#3276]
The hack to play a sound to avoid network losses due throttled resources by standby mode does not work if you have muted audio. 
We should find a more reliable way to fix that problem.

**Comment by christophsturm** [comment]
what about `pmset noidle`? 
http://osxdaily.com/2011/03/21/temporarily-prevent-a-mac-from-sleeping/

```
~% pmset noidle
Preventing idle sleep (^C to exit)...
```

**Comment by christophsturm** [comment]
even better: `/usr/bin/caffeinate ./bisq-desktop`. if this works we can just add caffeinate to the osx start script.

**Comment by christophsturm** [comment]
it seems `AvoidStandbyModeService` runs on all systems. is it only needed on osx? then we could remove it and use caffeinate instead. Or otherwise we just keep it in and run caffeinate in addition via the mac os startscript.

**Comment by chimp1984** [comment]
It is not tested for other systems but it can be assumed that Windows might have similar behaviour.

**Comment by devinbileck** [comment]
I haven't done any testing with muted audio on Windows, but can if necessary.
Additionally, perhaps this is the cause of #3223?

**Comment by wiz** [comment]
Nah I think Linux power management is very primitive and doesn't care if you are listening to audio

**Comment by christophsturm** [comment]
maybe we can do something similar to #3284 on linux too? https://wiki.archlinux.org/index.php/Power_management#Console

**Comment by freimair** [comment]
looks like this would be a good time to rethink the avoid-standby stuff. I will provide info for arch linux.
