### ISSUE TITLE
Please improve Russia Bank to Bank Transfer payment method  + Sberbank e-banking transfer

### ISSUE THREAD

**Issue by ifarnung** [bisq-network/bisq#3285]
We should consider adding a Russia specific Bank Transfer payment method, similar to Japan, in a similar way. It seems these are the relevant form fields:

1) Hard-coded list of top banks in pull-down box
"Largest banks in Russia in terms of net assets (trillions of rubles) as of Dec. 1, 2013:[9]
Sberbank (15.8)
VTB (5.2)
Gazprombank (3.5)
VTB-24 (2)
Rosselkhozbank (1.8)
Bank of Moscow (1.8)
Alfa Bank (1.4)
Nomos Bank (0.8)
Unicredit (0.8)
Rosbank (0.7)
Promsvyazbank (0.7)
Raiffeisenbank (0.7)

2) Full list of all banks (if reasonable to add)
3) Account Number (IBAN)
4) Customer Name
5) Bank Name
6) Swift Code
7) TIN (Tax Identification Number)

Also:
I would like to see an option for a Sberbank intrabank transfer and all you need is the account number of the other person, I believe.  By far the most common bank account, and a very common commercial solution here in Russia.  You might send with Sberbank to settle a bar tab or at a small shop.

**Comment by wiz** [comment]
Okay, let's do it. This looks like a job for the Payment Method maintainer duo @m52go also cc @y3v63n

**Comment by leshik** [comment]
I can envision a lot of arbitration issues with trades involving Sberbank and VTB. They like to block accounts without giving any reason. Please don't add any government-controlled banks. OTOH, Tinkoff Bank is not in the list but I think it'll have fewer issues than others.

**Comment by wiz** [comment]
@leshik thanks for the feedback - do you think we should not add this payment method at all, or just only allow certain banks?

**Comment by leshik** [comment]
It can be added, why not. I think Unicredit and Raiffeisen from this list are ok (one is Italian, another one is Austrian), Alfabank and Tinkoff should be fine too.

**Comment by leshik** [comment]
Just read a message in one of the russian Bitcoin Telegram channel that Alfabank blocks suspicious ATM cash-ins with no refund. Russian banks are like russian roulette🤷‍♂️

**Comment by rkfg** [comment]
This is still relevant and even more so because of the %current_event%

**Comment by pazza83** [comment]
Hi thanks for posting.

Currently the Russian payments being considered are:

- Qiwi https://qiwi.com/
- YooMoney https://yoomoney.ru/
- Tinkoff
- Sberbank

It would be useful to know which ones users would find most useful.

**Comment by ifarnung** [comment]
Speaking with some Russians lately about this topic, I have some confidence in Qiwi, Tinkoff, and Sberbank.  I haven't heard of yoomoney.ru, nor had my contacts, but maybe it is also fine.   Double checking on LocalBitcoins, you can see Qiwi and Tinkoff and Sberbank are the most common methods by far.

**Comment by pazza83** [comment]
Thanks will do some further investigation

**Comment by rkfg** [comment]
YooMoney was formerly known as Yandex.Money. I'd add VTB and Alfa-Bank to the list because they're mentioned at bestchange.ru in the short list.
