### ISSUE TITLE
When successful transaction funds are withdrawn from FUNDS area the withdraw box still shows under 'Open Trades'

### ISSUE THREAD

**Issue by btcll** [bisq-network/bisq#329]
When I received a successful transaction from moleccc on IRC I then went into Bitsquare and saw the trade had marked as having completed.

I then clicked the FUNDS icon and saw the funds there so withdrew them to my bitcoin core.

Then I went back to the PORTFOLIO icon (which still had a 1 on it). The Open Trade was shown and it was prompting me to put in a withdraw address.

It would not let me clear the trade until I put an address in, then it cleared okay. 

Would be better if when funds are withdrawn from FUNDS icon the PORTFOLIO icon is updated and the trade is automatically moved from OPEN TRADES to HISTORY tab.

**Comment by ManfredKarrer** [comment]
Yes that is currently missing impl. The open for withdrawal might be removed completely later, and widthdrawal always displayed in any case when its possible (cancel offer, failed trade,...). atm i just had let it there as those areas are nto impl.
I will close that issue as it is not planned to impl. that yet, but will be covered later when all those other situations are handled.
