### ISSUE TITLE
Crash on quit on macOS 10.15 Catalina

### ISSUE THREAD

**Issue by rex4539** [bisq-network/bisq#3290]
Bisq 1.1.6

Reproducibility: always

Steps:
Quit Bisq.

What happened:
Crash.

[Bisq_2019-09-18-150800_MacBook-Pro-2018.log](https://github.com/bisq-network/bisq/files/3626296/Bisq_2019-09-18-150800_MacBook-Pro-2018.log)

Expected result:
Bisq does not crash.

**Comment by ripcurlx** [comment]
> Bisq 1.1.6
> 
> Reproducibility: always
> 
> Steps:
> Quit Bisq.
> 
> What happened:
> Crash.
> 
> [Bisq_2019-09-18-150800_MacBook-Pro-2018.log](https://github.com/bisq-network/bisq/files/3626296/Bisq_2019-09-18-150800_MacBook-Pro-2018.log)
> 
> Expected result:
> Bisq does not crash.

@rex4539 Are you able to reproduce this behavior with Bisq v1.2.3 as well?

**Comment by ripcurlx** [comment]
Or lets say do you see this error also with the latest Catalina update?

**Comment by rex4539** [comment]
No, it's not reproducible anymore with the new build.
