### ISSUE TITLE
Show BSQ trade fee in % per day

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#3292]
It would be good to see how much BSQ trade fee in % per day was used in trading. 
In DAO/Fact &Figures we show the daily burned BSQ (mostly trade fee). If that data would be combined with the trade volume we could calculate the % of BSQ used in trades (target is 0.4%).

Not sure what the best graphical solution would be, we don't want to overload that screen. Maybe a secondary series in the same chart might be nice. Also a tooltip with the exact values would be good.

Any dev interested to implement that? Best make a suggestion and discuss with @ripcurlx before implementing it.

In TradesChartsViewModel you see how the volume per day is gathered...

**Comment by niyid** [comment]
@ripcurlx

Can I get details? Assignation?

**Comment by niyid** [comment]
@ripcurlx 

I suppose this should work...
![Screenshot from 2019-10-03 08-16-56](https://user-images.githubusercontent.com/20237127/66106789-a49be700-e5b6-11e9-8473-1baa2c646a41.png)

**Comment by freimair** [comment]
I do not get the idea.

> BSQ trade fee in % per day was used in trading

can be reduced to "BSQ trade fee ~in % per day was~ used in trading" which in turn would result in 100% every day to my understanding.

What is the goal here:
1) show the percentage of trades being payed for with BSQ
  eg. 20 trades have been payed for in BTC, 80 trades have been payed for with BSQ -> 80%
2) show the percentage of BSQ used for paying trading fees vs the total number of BSQ spent in the same timespan?
  eg. 100 BSQ have been burnt in 1 day, 20 BSQ haven been burnt/spent for paying fees -> 20%
3) take the total volume into account: eg. 100 BSQ have been burnt, a total volume of 0,1 BTC (=1000 BSQ) have been traded -> 10%
4) only take burnt BSQ for paying fees into account: eg. 20 BSQ have been burnt/spent for paying fees, a total volume of 0,1 BTC (=1000 BSQ) have been traded -> 2%
5) ?

**Comment by niyid** [comment]
> I do not get the idea.
> 
> > BSQ trade fee in % per day was used in trading
> 
> can be reduced to "BSQ trade fee ~in % per day was~ used in trading" which in turn would result in 100% every day to my understanding.
> 
> What is the goal here:
> 
> 1. show the percentage of trades being payed for with BSQ
>    eg. 20 trades have been payed for in BTC, 80 trades have been payed for with BSQ -> 80%
> 2. show the percentage of BSQ used for paying trading fees vs the total number of BSQ spent in the same timespan?
>    eg. 100 BSQ have been burnt in 1 day, 20 BSQ haven been burnt/spent for paying fees -> 20%
> 3. take the total volume into account: eg. 100 BSQ have been burnt, a total volume of 0,1 BTC (=1000 BSQ) have been traded -> 10%
> 4. only take burnt BSQ for paying fees into account: eg. 20 BSQ have been burnt/spent for paying fees, a total volume of 0,1 BTC (=1000 BSQ) have been traded -> 2%
> 5. ?

This is Total BSQ Burnt / Total Trade Volume ratio on a daily basis expressed as a percentage.

@chimp1984  
Comments?

**Comment by freimair** [comment]
so it is 3) then?

**Comment by niyid** [comment]
> so it is 3) then?

Yes. Option 3.

**Comment by ripcurlx** [comment]
Sorry for replying that late to this issue, as I was completely focusing on v1.2. 
Reading through the description of the issue I think it was not meant to add it to the trade charts view, but rather enrich the `Facts & Figures > BSQ Supply > BSQ burnt` chart.
![Bildschirmfoto 2019-11-12 um 15 18 30](https://user-images.githubusercontent.com/170962/68679199-b4b4c800-055f-11ea-9b86-5e6892e47e5b.png)

So the tooltip you did in the trade charts view (if we do it like that) should be instead a tootip in the BSQ burnt chart.
![Bildschirmfoto 2019-11-12 um 15 17 45](https://user-images.githubusercontent.com/170962/68679165-a49ce880-055f-11ea-8b58-d964702a0334.png)

An alternative would be a second graph that has an alternative y-axis, but I think that is a little bit tricky with the default JavaFX charts. But I haven't tried that out so far.
