### ISSUE TITLE
[Feature] Provide a way to show burned BSQ in a specific timeframe

### ISSUE THREAD

**Issue by erciccione** [bisq-network/bisq#3303]
At the moment is not possible to know how many BSQ are burned in a determined time, but only the total burnt (which can be seen in  "Fact & figures" -> "BSQ supply"). Would be nice to be able to check the amount for a specific timeframe, for example a month or a week, without having to dig the code.

@ripcurlx's suggestion on Slack:

> Maybe we could add some time span setting (days, weeks, months) to the chart. But for detailed analysis an extension of the API would be the best thing to have.

**Comment by chimp1984** [comment]
Agree. Some time selection (day, week, month, year) like in the trade statistics would be ok. Or a more sophisticated time selection with a range slider...

**Comment by niyid** [comment]
Hi @erciccione 

Do you mean to replace the chart shown in the screenshot below with one that the time frame can be adjusted/selected?

![Screenshot from 2019-09-27 02-36-00](https://user-images.githubusercontent.com/20237127/65735724-5b3c2b00-e0d0-11e9-8a53-770e149ef383.png)

**Comment by erciccione** [comment]
@niyid That could be nice yes, but what i think would best is to implement @ripcurlx's suggestion about the API. But whatever will give us the possibility to check the burnt bisq in a given time frame will be appreciated.

**Comment by niyid** [comment]
Are these related?

https://github.com/bisq-network/bisq/issues/3292

**Comment by ghost** [comment]
Seems like it was fixed [in pr#5156](https://github.com/bisq-network/bisq/pull/5156) - @ripcurlx you could probably close this issue.
