### ISSUE TITLE
Error broadcasting transaction

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#3306]
# Summary
Generalizing, a user makes a transaction and unbeknownst to them the transaction isn't successfully broadcast to the Bitcoin Network. This has happened in all types of Bisq transactions:
* make offer
* take offer
* deposit
* payout
* withdraw

@sqrrm @ripcurlx

**Comment by huey735** [comment]
Examples from the forum
https://bisq.community/t/how-to-transfer-bitcoin-out-of-bisq-wallet/8252
https://bisq.community/t/issue-with-the-payment-received-button/8269
https://bisq.community/t/how-to-proceed/8274
https://bisq.community/t/transaction-failed-to-broadcast-ui-error/8283
https://bisq.community/t/arbitratorpubkeyring-must-no-tbe-null/8307, bisq-network/bisq#3144
https://bisq.community/t/solved-transaction-id-not-found-lost-my-btc/8309
https://bisq.community/t/withdraw-transaction-stuck-not-found/8320
https://bisq.community/t/arbitratorpubkeyring-must-no-tbe-null/8307
https://bisq.community/t/the-transaction-is-replenished-only-on-my-part/8352
https://bisq.community/t/cant-withdraw-from-bisq-to-my-wallet/8361

**Comment by sqrrm** [comment]
@huey735 Thanks for collecting these cases. I only found one log file and it seems to have issues with the tor connection #3282 that might be causing broadcast failures. Are they all issues with tx not being broadcast or are some of them a lack of fee?

**Comment by huey735** [comment]
@sqrrm I'm not sure if I fully understand your question, but I assume that all transactions related to the trade protocol are having issues due to issues in the Bisq Network/software. The fees for the makerOfferTx, takeOfferTx, depositTx and payoutTx aren't under control of the user and are usually high enough to get accepted into the mempool.
The issues with the withdraw transactions however can be result of [poor fee calculation](https://github.com/bisq-network/bisq/issues/3106) but I doubt that that's mostly the case.

**Comment by sqrrm** [comment]
From #3305 I see at least one tx being rejected as dust. 

`Sep-22 14:18:20.261 [BlockingClient network thread for r3dsojfhwcm7x7p6.onion:8333] ERROR o.b.core.Peer: [r3dsojfhwcm7x7p6.onion]:8333 /Satoshi:0.16.3/: Received Reject: tx b2bcaabc9b1f9b2a67901730bdabb50a8b484e7b5357addb4230d174506bd670 for reason 'dust' (64) 
`

**Comment by sqrrm** [comment]
@huey735 The more logs we can get the better. We need to see if we can find a pattern on why the txs aren't properly broadcast.

**Comment by huey735** [comment]
@sqrrm I'm not sure that tx is one of @bitsanity's. So I don't think that it's relevant here. For #3305 they were able to solve it with a resync of the spv chain which implies problems with the propagation of the transaction and not with its fee amount.

**Comment by sqrrm** [comment]
That rejection is due to 'dust' which is strange, bisq should not produce dust txs. The other case I saw was the bad tor connection. We need more data to understand if there is a common cause for these failed broadcasts. It would also be good to do rebroadcast automatically, or perhaps even manual but at least not forcing users to do an spv resync.

**Comment by wiz** [comment]
I just reproduced the issue, I had set fee = 1 sat/byte and Bitcoin node rejected it for having too low of a fee
`Oct-01 13:22:11.344 [BlockingClient network thread for jiuuuislm7ooesic.onion:8333] ERROR org.bitcoinj.core.Peer: [jiuuuislm7ooesic.onion]:8333 /Satoshi:0.18.1/: Received Reject: tx 3fd5922bdc88fab8ee866610edc3e54b62dcbf5945813e08813157ad0c842dc6 for reason 'min relay fee not met' (66) 
`

**Comment by wiz** [comment]
It seems bitcoinj creates invalid transactions in multiple cases, so far I've seen:

1) The "dust" consensus rule is being violated, not sure how to reproduce this yet

2) The "min relay fee" consensus rule is being violated when user sets custom fee to 1 sat/byte and virtual TX size gets rounded down and effective fee becomes 0.995 sat/byte

Obviously these 2 bugs should be fixed, but maybe we can also improve the handling the exceptional case of rejected transaction broadcast:

1) The Bisq app should display an error if bitcoinj peer rejects broadcasting of the TX, with the reason given together with the full TX encoded in hex for further debugging

2) The Bisq app should have a method to export the raw TX from the UI list of transactions, encoded in hex for further debugging

3) The Bisq app should have a (hidden) method to manually remove unconfirmed transactions from the wallet so if the broadcast fails the user can try creating a new TX

**Comment by captainreptile** [comment]
I'm having simillar issues , running on Bisq v1.2.3.
After creating my first sell offer i received an error that transaction rejected.
it suggested to restart the app, which i did and now i am unable to connect to bitcoin network (peers 0 and Bisq network peers:9)

I can't see my offer anywhere in portfolio, but i do see fees withdrawn.

The warning on boot:

>  A transaction was rejected from the network for reason 'dust' (64).

**Comment by alexgand** [comment]
@captainreptile Same error here (... for reason 'dust').

Two new transactions I made after the error started had failed to generate the inicial deposit transactions, resulting in mediation.

Any way of avoiding this bug?

**Comment by alexgand** [comment]
@captainreptile I was able to solve the problem doing a "resync SPV chain" (Settings / Network info)!

**Comment by captainreptile** [comment]
@alexgand It seems that its a bug that the team is hunting after. I submitted my log file to the support on https://keybase.io/team/bisq.

P.s: Lol, First time i see the setting / network info! i was looking for such setting but never saw the tab, Thanks i will also try to resync SPV.

**Comment by Forstmann88** [comment]
Hello everybody.
I have the problem in connection with a payout on my private wallet.
since I am not the computer specialist, I would need your help please?
what do I have to do to fix this error?

![Fehlermeldung_2](https://user-images.githubusercontent.com/57730987/68872417-4c501d00-06fe-11ea-9c1d-f76886e81932.png)

![Fehlermeldung_1](https://user-images.githubusercontent.com/57730987/68872446-583bdf00-06fe-11ea-81bb-6c9ba91672ea.png)

**Comment by ripcurlx** [comment]
@Forstmann88 Do you still have this issue?

**Comment by wiz** [comment]
I'm quite sure this is a legitimate issue, as I still see it sometimes, it's just very hard to reproduce - you need to have a very specific set of UTXO inputs and transaction amounts for it to occur. Waiting a few seconds for the fee estimation to change often fixes it, or changing your TX amounts can fix it.

**Comment by federicociro** [comment]
Hello, 
related problem here. I created a tx with 2 sat/vbyte fee (mempool was empty), but was not picked. Is there any way to rebroadcast with more fee (RBF) or some way cancel the tx? It can be seen in mempools.
