### ISSUE TITLE
Bisq using way too much RAM on windows

### ISSUE THREAD

**Issue by fresheneesz** [bisq-network/bisq#3307]
On my windows 7 machine, Bisq v1.1.6 is using 1960 MB of ram. That's almost half my RAM. That's pretty unacceptable. Why in god's name is it using so much? And this is right at startup.

![BisqRam](https://user-images.githubusercontent.com/149531/65393661-63930f80-dd38-11e9-89c8-6fd9c4f98c88.png)

**Comment by huey735** [comment]
Related to https://github.com/bisq-network/bisq/issues/3128

**Comment by freimair** [comment]
related to #3343 too

**Comment by fresheneesz** [comment]
Stale bot is too aggressive for the rate tickets are closed in this project. Please adjust it

**Comment by ghost** [comment]
Bisq take 1.5GB in my RAM right at start and i didn't even made a transaction yet, the install is only few days old. It is kind of not viable for most people. :man_shrugging:
I'm on Ubuntu 20.04m installed from Bisq-64bit-1.3.5.deb

**Comment by cd2357** [comment]
Should be fixed in the most recent release (v1.6.4) which brings several UI performance improvements and generally reduces system resource consumption (especially RAM). Please try it out and let us know if it's still an issue for you.

**Comment by fresheneesz** [comment]
Thanks!
