### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by niyid** [bisq-network/bisq#3314]
Hello All,

Is the mobile app still supported? I tried to use it to monitor trade offers but it keeps crashing whenever notifications are to be received.

**Comment by huey735** [comment]
Ping @devinbileck 
Is it related to this issue: https://bisq.community/t/solved-i-cant-receive-notification-today/8386

**Comment by niyid** [comment]
> Ping @devinbileck
> Is it related to this issue: https://bisq.community/t/solved-i-cant-receive-notification-today/8386

Thanks.

It appears to be different.

@devinbileck
Are there any new updates? My device is not prompting for an app update and I installed it about 2 months ago.

**Comment by devinbileck** [comment]
@niyid I assume you are referring to the mobile app that is crashing, as opposed to the Bisq client? Do you have any more details or error message regarding the crash? What mobile device are you using? There have been no updates to the mobile app in some time. Feel free to open an issue:
https://github.com/joachimneumann/bisqremote_iOS/issues
https://github.com/joachimneumann/bisqremote_Android/issues

**Comment by niyid** [comment]
@devinbileck 

Sorry for the delay. I will try this again but I did not notice any error messages the last time. I will try and record and upload the screen as it crashes as well as the device information.

By the way, is there any crash reporting tool on the app - such as [ACRA](https://github.com/ACRA/acra)

**Comment by devinbileck** [comment]
> By the way, is there any crash reporting tool on the app - such as ACRA

Not that I am aware of, but that would be a question for @joachimneumann.

**Comment by niyid** [comment]
Apparently working fine now. I cannot reproduce.
