### ISSUE TITLE
Trade Info Popup

### ISSUE THREAD

**Issue by niyid** [bisq-network/bisq#3317]
I have attached the trad info pop-up window below.

The sender and receiver altcoin information may be a bit confusing:

In the screenshot at the line titled `BTC Buyer payment details` I see **`Receiver's altcoin address`**

I think this should be **`Sender's BSQ address`** using a placeholder instead of the static `altcoin` text.

Also the `BTC Seller payment details` line should have **`Receiver's BSQ address`**.

![Screenshot from 2019-09-24 02-32-41](https://user-images.githubusercontent.com/20237127/65474883-67787c00-de75-11e9-8039-962862c242d7.png)

**Comment by chimp1984** [comment]
Yes, right in both aspects. Feel free to add a PR for fixing it.

**Comment by niyid** [comment]
> Yes, right in both aspects. Feel free to add a PR for fixing it.

I have: with this [Push Request](https://github.com/bisq-3317/bisq/commit/b5f6d0dc2b858cfcaacb0898a98e78b7b61888d0)

You just have to acknowledge.
