### ISSUE TITLE
Core dump on startup

### ISSUE THREAD

**Issue by wmpedersen** [bisq-network/bisq#332]
I've installed Bitsqaure on Ubuntu 12.04 via the deb, and it crashes in about 2 seconds according to the log because of a core dump. I'm using OpenJDK 6 as my JRE, have also tried Oracle with no change.

I've also tried running `sudo /opt/Bitsquare/Bitsquare` and get "Exception in Application start method"
Seems to work fine when I run the jar file itself.

**Comment by remyers** [comment]
Hi Wade - I would definitely try it with the Oracle JDK, we haven't tested
using OpenJDK; I think cbeams describes how to fix a similar problem:
  https://github.com/bitsquare/bitsquare/issues/100

**Comment by ManfredKarrer** [comment]
You need Java 8.
