### ISSUE TITLE
Builds for 32 bit architecture

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#333]

**Comment by greg121** [comment]
@bitsquare @ChangeTip $2

**Comment by changetip** [comment]
Hi @bitsquare, @greg121 sent you a Bitcoin tip worth 8,150 bits ($2.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/387197)**.

**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by ManfredKarrer** [comment]
@greg121 Thanks a lot! I know changetip is very popular and people using it have the best intentions, but there are some critical voices against it as well: http://hackingdistributed.com/2014/12/17/changetip-must-die/
Changetip triggers  some concerns regarding privacy by matching social network IDs together with BTC addresses and can be misused to weaken the anonymity of Bitcoin.

I would prefer if you could dontate it directly on our webpage, if thats ok for you.

**Comment by greg121** [comment]
Okay, sure I will do that. And thanks for pointing that out.

**Comment by kimmel-** [comment]
hi there manfred still having issues with this, not able to run on most linux distros I try, get amd64 wrong architecture. easy to fix anytime soon? by the way the app is looking great!

**Comment by ManfredKarrer** [comment]
Sorry I still had no time to work on alternative builds. You should be able to run the jar file if you have latest java installed.

**Comment by ManfredKarrer** [comment]
32 bit builds are now available
