### ISSUE TITLE
Stuck transaction even post-arbitrator cancellation.

### ISSUE THREAD

**Issue by ifarnung** [bisq-network/bisq#3335]
![image](https://user-images.githubusercontent.com/55181240/65769456-40070500-e13c-11e9-8e8c-66c02b342341.png)
This transaction that never confirmed on the blockchain and was eventually handled and cancelled by an arbitrator, is still sitting pending in my 'Funds' log.

How to resolve this?
1. What happened to that .003 BTC that was being sent for security deposit?  I guess it never left the UTXO set that I control?  But will BISQ software see that UTXO as spent or available?
2. The fact that I have this pending unconfirmed transaction is making my mining fee estimates higher across all my future BISQ orders, and I haven't replaced any trading orders since this happened because I am waiting for a fix.

This is the final communication from the arbitrator.
![image](https://user-images.githubusercontent.com/55181240/65769732-f8cd4400-e13c-11e9-9bc3-8de59a80ce78.png)

**Comment by wiz** [comment]
Try settings -> network info -> delete spv file and resync

**Comment by ifarnung** [comment]
That worked perfect, thanks.  The .003 is back in my Avail Balance and the pending transaction is gone from the history.  I wonder if I saw it was stuck within the first hour of that trade trying and failing to confirm, had I reset the SPV, could that have gotten the trade to go correctly?  Not sure, but anyway, closing this issue.  Thanks @Wiz

**Comment by huey735** [comment]
Related to https://github.com/bisq-network/bisq/issues/3306

**Comment by huey735** [comment]
> I wonder if I saw it was stuck within the first hour of that trade trying and failing to confirm, had I reset the SPV, could that have gotten the trade to go correctly?

That's a good question, @ifarnung. @sqrrm @ManfredKarrer will the resync of the SPV cause problems to open trades?

**Comment by wiz** [comment]
hey @ifarnung do you remember if you set custom fees to 1 sat/byte in your settings at the time this bug occurred? there seems to be 2 bugs causing TX fail to broadcast, one for "dust" and one for "fee too low", but the latter would only occur if you set fees to 1 sat/byte because default is 10 sats/byte minimum so just want to get more information to help investigation thanks

**Comment by ifarnung** [comment]
No I did not set it so low, maybe 5 or 6 sats was the lowest I used.
