### ISSUE TITLE
Bisq app black screen when left idle

### ISSUE THREAD

**Issue by Rowdster** [bisq-network/bisq#3336]
After leaving bisq idle for 12+ hours, on displaying the app, the app display is black.  Trying to close the app I do finally get a warning about open offers.  It seems that only the base window has lost its canvas.    

Windows 10, 64 bit, bisq 1.1.7

Are there any logs I can share?

![image](https://user-images.githubusercontent.com/575732/65770466-2944bc00-e104-11e9-9a5d-4d9a399fcf21.png)

![image](https://user-images.githubusercontent.com/575732/65770644-80e32780-e104-11e9-82ed-e3fa055c6036.png)

**Comment by Rowdster** [comment]
Just to confirm, I'm encountering this behavior on two different machines, one desktop, one VM

**Comment by FKrauss** [comment]
Got 2 guys in Brazil with what looks like the same issue on Windows.
one of them attempted to delete the tor files (through explorer as Bisq would simply not load) to resync. Didn't work.

I suggested he uninstalled Bisq completely and deleted all the application files. I'm still waiting on him to reply how that went

**Comment by Rowdster** [comment]
I still have the black screen issue, and it is very likely due to accessing the app via remote desktop on windows.

**Comment by bb2k16** [comment]
I have the same issue, I have Bisq installed on a laptop which i access via RDP, the client will go black just like @Rowdster screenshot after disconnecting and reconnecting to the remote machine.

**Comment by Rowdster** [comment]
I'm running from source now, and while the app seems snappier, it still gets the black screen.  Is there any chance of getting some logging around getting handles on the draw canvas here to see why it's doing this?

**Comment by Rowdster** [comment]
![image](https://user-images.githubusercontent.com/575732/70378383-b61ea980-18ed-11ea-88b2-b3b52168dbe8.png)

**Comment by Rowdster** [comment]
I'm going to close this.  When running from source via java with _JAVA_OPTIONS="-Xmx512m" the UI doesn't appear to freeze.  The compiled app is still freezing.
