### ISSUE TITLE
[PRICE] Price for BTCSEK is way off

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#3337]
Forum thread: https://bisq.community/t/price-for-btcsek-is-way-off/8439
![sekprice](https://user-images.githubusercontent.com/44140017/65774731-c28cc600-e136-11e9-8e86-1003afe42a31.png)

**Comment by wiz** [comment]
I confirmed the pricenode API is returning 111000 for SEK, for example http://gztmprecgqjq64zh.onion/getAllMarketPrices

I think BitcoinAverage has a problem as I get a "not found" error here https://bitcoinaverage.com/ua/currency-markets/btc-to-sek

**Comment by wiz** [comment]
I emailed BitcoinAverage support about this bug.
