### ISSUE TITLE
Add and rename Portfolio History columns meaningfully

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#3338]
* Rename "Transaction Fee" column to "Taker trading fee"
* Rename "Maker Fee" column to "Maker trading fee"
* Add maker or taker position of the local trader to "Offer type" column
* Add mining fees columns, named "Maker mining fee" and "Taker mining fee"

How the table looks currently

![exportedhistory](https://user-images.githubusercontent.com/44140017/65778303-99bbff00-e13d-11e9-920b-5731c2ba0743.png)

Related to https://github.com/bisq-network/bisq/issues/2106

@sqrrm @niyid @wiz

**Comment by niyid** [comment]
@huey735 

Noted. Will do.

**Comment by huey735** [comment]
Still relevant.
