### ISSUE TITLE
gradle build fails at java compiling (StackOverflowError)

### ISSUE THREAD

**Issue by konradvoelkel** [bisq-network/bisq#3349]
As detailed here https://scans.gradle.com/s/msd2kqyebk5zw/
there is a very uninformative StackOverflowError.

Some googling shows this might be because of a cyclic dependency graph, but I do not know enough to investigate further (and find this unlikely as well).

System is linux intel 32-bit with JVM 11 (OpenJDK), see link for details.

Took a fresh copy of 1.1.7 from the sources tar.gz and ran the test again from a current HEAD 7bed73e

**Comment by kilo42L** [comment]
I have same issue, Tried to install it many ways and they all fail with this error.  Ive tried java 10 and 11

**Comment by ripcurlx** [comment]
@konradvoelkel Could you please re-try with current master using OpenJDK 10?
