### ISSUE TITLE
Show reputation balance in BSQ wallet stats

### ISSUE THREAD

**Issue by erciccione** [bisq-network/bisq#3352]
Right now we have a lot of information about our BSQ balance in `DAO` -> `BSQ Wallet`, but they are all related to the actual amount of BSQ, not the amount of "reputation BSQ", which is only shown when it's time to vote.

Would be cool to have it always visible in the *My wallet balance* section, so that contributors can always check their reputation weight, expecially since it's a value that decreases over time.

**Comment by wiz** [comment]
This is a really good point. The amount of BSQ in circulation is interesting, but everybody should be able to see the total amount of Voting Rights outstanding, and how many Voting Rights they have - maybe @ManfredKarrer has some comment on this?

**Comment by niyid** [comment]
What is the purpose of the field indicated with the arrow though?

![Screenshot from 2019-10-04 00-21-15](https://user-images.githubusercontent.com/20237127/66170786-86c59500-e63d-11e9-9cdf-db5bd6868877.png)

**Comment by wiz** [comment]
During the "Blind Vote Phase" you actually lock-up the BSQ you use for voting, so it cannot be spent.

**Comment by niyid** [comment]
> During the "Blind Vote Phase" you actually lock-up the BSQ you use for voting, so it cannot be spent.

@wiz 
Ah. Thanks.

@erciccione  @ManfredKarrer
I will add "Reputation BSQ" to that screen. Do you consider that a suitable title?

**Comment by erciccione** [comment]
@niyid sounds good to me :)

**Comment by niyid** [comment]
I am looking through the **`displayStrings.properties`** file for the title of the "Reputation  BSQ" and I cannot be sure which the key is:

1. **`dao.results.votes.table.header.stakeAndMerit`**
2. **`dao.results.votes.table.header.merit`**
3. **`dao.bond.bondedReputation`**

I am tending towards 1.

I also noticed this comment by @wiz 

> Voting Rights outstanding, and how many Voting Rights they have

That implies that the there are multiple values making up the 'Reputation BSQ" - an **outstanding** and a **current**.

**Comment by wiz** [comment]
The currently used term is "vote weight" not "reputation"
<img width="285" alt="Screen Shot 2019-10-11 at 19 10 59" src="https://user-images.githubusercontent.com/232186/66644007-e3870800-ec5a-11e9-84b3-b7a2ac95759f.png">

**Comment by niyid** [comment]
> The currently used term is "vote weight" not "reputation"
> <img alt="Screen Shot 2019-10-11 at 19 10 59" width="285" src="https://user-images.githubusercontent.com/232186/66644007-e3870800-ec5a-11e9-84b3-b7a2ac95759f.png">

It is also referred to as "Reputation" in the documentation:

https://docs.bisq.network/dao/overview.html#reputation-based-voting
![Screenshot from 2019-10-11 12-29-06](https://user-images.githubusercontent.com/20237127/66648295-20370d00-ec23-11e9-8530-1ede3c5906da.png)

**Comment by chimp1984** [comment]
@niyid The doc was not updated over time... The correct term we used in the DAO is: merit. 
Vote weight is the sum of merit + stake.
Reputation might be overloaded with other meanings inside (reputation based on onion address) and outside Bisq.

**Comment by niyid** [comment]
> @niyid The doc was not updated over time... The correct term we used in the DAO is: merit.
> Vote weight is the sum of merit + stake.
> Reputation might be overloaded with other meanings inside (reputation based on onion address) and outside Bisq.

Thanks for the information. I will update accordingly.

Regards.
