### ISSUE TITLE
Bisq v1.1.7-Waiting for funds even after tx got many confirmation on chains

### ISSUE THREAD

**Issue by Bigsy11** [bisq-network/bisq#3355]
Fund my offer using QR code, the tx was confirmed on chains (more than 10 confirmations) but Bisq still says "waiting for funds". it was still like that in 2 days. 

I restarted the app and tried to fund 1 more time, but it didn't work, still "waiting for funds".

 I think there's some bug in the software.

**Comment by niyid** [comment]
@Bigsy11 

Have you been able to resolve the issue?

**Comment by Bigsy11** [comment]
No, I gave up trying to fund from external wallet, because it was costing double the mining fee: try to fund it from external, then restart app, and fund from internal wallet.

Can't waste any more bitcoins on this bug.
