### ISSUE TITLE
CoinMarket cap isn't showing all coins

### ISSUE THREAD

**Issue by danimesq** [bisq-network/bisq#3359]
Bisq site tells here are more than 100 coins, but CoinMarket cap only shows a few:
https://coinmarketcap.com/pt-br/exchanges/bisq/

**Comment by flix1** [comment]
True. For example a different set of coins are chown here:
https://www.coingecko.com/en/exchanges/bisq

**Comment by erciccione** [comment]
I guess would be better to directly contact coinmarketcap's support and let them know, i don't think it's a problem on Bisq side. Also, probably slack is better than the issue tracker to discuss this.

**Comment by freimair** [comment]
agreed in it not being a bisq software issue.

@m52go can you have a look?

**Comment by m52go** [comment]
I reached out a few days ago. Response I got seemed to be automated (or from a drone who didn't understand my request) and not very helpful. 

My guess is it has to do with volume...most of the 100 coins you see on the website have negligible trading activity, so it doesn't make sense for them to be listed.
