### ISSUE TITLE
"Sending message failed" when trying to confirm my payment has started

### ISSUE THREAD

**Issue by jacopocer** [bisq-network/bisq#3372]
Hi there.
My trade is stuck: I (BTC buyer) cannot proceed confirming my payment has started. When I clicked on "Payment started" I got "Sending message failed". I was asked to go with mediator, but he/she is not doing anything about it.
The seller wrote to me in the direct chat that he/she got the payment, the trade is just stuck because of the problem of Bisq.
<img width="577" alt="Schermata 2019-10-07 alle 22 43 00" src="https://user-images.githubusercontent.com/19292930/66369798-1650a800-e99e-11e9-80f6-d044ccb7f545.png">
<img width="829" alt="Schermata 2019-10-07 alle 22 33 51" src="https://user-images.githubusercontent.com/19292930/66369799-1650a800-e99e-11e9-90b3-74f2f7f8a079.png">

Has anyone some ideas on how to resolve this issue?

**Comment by calkob** [comment]
See issue ##3371 for similar problem.  I went to mediation yesterday with the same issue which didn't resolve it.  when i accepted the mediation it just ave me another error.  i then went to Arbitration which worked and i received my BTC, as Arb has a third key.  something is going wrong in that the seller node is getting banned. 

  You may need to go to Arb to fix.  As you may know you can now chat with the seller to inform them of the actions you are taking.

good luck

**Comment by ripcurlx** [comment]
@jacopocer Was your issue solved in the end? We did publish in our latest release (v1.2.7) the option to refresh the trade status which should fix problems as described by you. Please re-open this issue if your problem wasn't resolved by now.
