### ISSUE TITLE
Merge 'sell BTC' and 'Buy BTC' in one menu: 'Sell/Buy BTC'

### ISSUE THREAD

**Issue by erciccione** [bisq-network/bisq#3375]
Right now there are 9 items in the menu, two of these are `BUY BTC` and `SELL BTC`. Each of these two have their own submenu: `BUY BITCOIN` `SELL BITCOIN` (see screenshots).

![buyBTC](https://user-images.githubusercontent.com/28106476/66390904-fb952800-e9cb-11e9-9c1d-e74e72da8512.png)   ![sellBTC](https://user-images.githubusercontent.com/28106476/66390906-fb952800-e9cb-11e9-8cdd-4e1f02639f25.png)

I think the user interface is already quite complex for the layman, with a lot of menus and submenus, what about using a single menu: `TRADE BTC` (or `SELL/BUY BTC`) containing two submenus: `BUY BTC` `SELL BTC` (or `BUY BITCOIN` `SELL BITCOIN`)?

**Comment by niyid** [comment]
Hi @erciccione 

Can you confirm that the screenshots below resolve this issue.

Regards.
![Screenshot from 2019-10-25 15-53-03](https://user-images.githubusercontent.com/20237127/67581651-4a6aed80-f740-11e9-8fa6-6eeb0eac9766.png)
![Screenshot from 2019-10-25 15-52-39](https://user-images.githubusercontent.com/20237127/67581653-4a6aed80-f740-11e9-875f-9fdb708832ab.png)

**Comment by erciccione** [comment]
It does, thanks for working on this @niyid , but looks like "Available offers" became a submenu too in your screenshots. I think would be better to leave that as it is.

**Comment by niyid** [comment]
No. "Available Offers" became a tab label. It was redundant as a heading within a tab (which was previously labeled "BUY BITCOIN" or "SELL BITCOIN") which was moved one level up; and it was the most appropriate label I could think of for the list within the tab.
