### ISSUE TITLE
password is not saving

### ISSUE THREAD

**Issue by bimbachi** [bisq-network/bisq#3379]
Password is not saving!

is saving - only when you click "I have already done a buckup" not other buttons.

![bisq_LI](https://user-images.githubusercontent.com/21200925/66481985-4bdeb980-eaa2-11e9-95e3-f0ed9ec5670b.jpg)

**Comment by ripcurlx** [comment]
@bimbachi Yes, I think the default button should be different and we should adapt the wording.

**Comment by f5b7** [comment]
Thanks for providing the "workaround"!
