### ISSUE TITLE
No fallback to IPv4

### ISSUE THREAD

**Issue by deafboy** [bisq-network/bisq#338]
I have a network interface with IPv6 address assigned which cannot be used to communicate with the internet. Bitsquare is trying to use IPv6 to bootstrap, without any attempt to fallback to IPv4.

log file: https://mega.co.nz/#!84MEDKgD!z3smcHLMaT3TSoFKrbACEKNl6jH-WPNQEWNdE47KpJc

**Comment by ManfredKarrer** [comment]
Thanks for reporting. Seems that BitcoinJ has problems as well with that config.

**Comment by ManfredKarrer** [comment]
I raised that issue on the BitcoinJ mailing list:
https://groups.google.com/forum/#!topic/bitcoinj/1dRPpvH0VsQ

See also: https://github.com/bitsquare/bitsquare/issues/340, https://github.com/bitsquare/bitsquare/issues/339

**Comment by ManfredKarrer** [comment]
Closed as related to TomP2P which is not used anymore.
