### ISSUE TITLE
german translation: Input in Chat window

### ISSUE THREAD

**Issue by DamageIncorporated** [bisq-network/bisq#3384]
When I use the chat to communicate with my trading partner,the translated text-field for input says [de] "_Geben Sie hier bitte Ihre Nachricht an den Vermittler ein_". 

But _Vermittler_ is the german word for arbitrator, who is not my counterpart of the conversation at this point.

But in this window I don't chat with the arbitrator but with my trading partner, so the correct german text should be [de] " _Geben Sie hier bitte Ihre Nachricht an **Ihren Handelpartner** ein_".

**Comment by huey735** [comment]
You can [contribute to the translation ](https://www.transifex.com/bisq/bisq-desktop). And reach out to us on the [#transifex channel on Slack.](https://bisq.network/slack-invite)

**Comment by ripcurlx** [comment]
Closing as complete.
