### ISSUE TITLE
Vote multiple times

### ISSUE THREAD

**Issue by niyid** [bisq-network/bisq#3393]
To vote, you navigate to:

`DAO > GOVERNANCE > BROWSE OPEN PROPOSALS`

And then click on each proposal to make your vote accordingly.

But it appears once you publish your votes for that cycle, you cannot select more proposals to vote on - all proposals not voted will default to ignored. Apart from simplifying the vote process, is there a reason why a voter cannot publish multiple vote transactions?

**Comment by niyid** [comment]
@freimair @m52go @chimp1984 *bump*

**Comment by ripcurlx** [comment]
> But it appears once you publish your votes for that cycle, you cannot select more proposals to vote on - all proposals not voted will default to ignored. Apart from simplifying the vote process, is there a reason why a voter cannot publish multiple vote transactions?

Just a matter of how the vote protocol is implemented right now. Every change on this would be very sensitive and will need lots of backwards compatibility testing. I'm closing this issue because of that, but I do agree that the voting process UX can be improved a lot.
