### ISSUE TITLE
Prepare and notarize release builds for macOS Catalina

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#3402]
As we use javapackager to create our dmg file for macOS we need to investigate and adapt our build pipeline how to prepare and upload the build to be notarized by Apple.

Links:
- https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution
- https://help.apple.com/xcode/mac/current/#/devf87a2ac8f
- https://help.apple.com/xcode/mac/current/#/dev88ff319e7
- https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution/resolving_common_notarization_issues

**Comment by ripcurlx** [comment]
Still relevant.

**Comment by cd2357** [comment]
Still relevant.

**Comment by MaskyS** [comment]
bump

**Comment by ripcurlx** [comment]
It is completely done already in #4242. Just needs the final touches for the remaining build steps.

**Comment by ripcurlx** [comment]
#4242 will be merged soon. Everyone who wants to give it a shot already can find the test binaries and signatures here: https://www.dropbox.com/sh/bos203ga9bq0akp/AAB6j5DPAINCPbCP9vyRB3n-a?dl=0 This version is based on v1.6.2. Please let me know if you still run into any issues on macOS when installing this version. Thanks!

**Comment by cd2357** [comment]
Fixed in the most recent release (v1.6.4).
