### ISSUE TITLE
Vote Reveal - Silent Fail

### ISSUE THREAD

**Issue by niyid** [bisq-network/bisq#3408]
I got this:

```
Oct-15 06:43:21.835 [JavaFX Application Thread] INFO  org.bitcoinj.wallet.Wallet: Completing send tx with 1 outputs totalling 0.00000596 BTC and a fee of 0.00 BTC/kB 
Oct-15 06:43:21.837 [JavaFX Application Thread] WARN  org.bitcoinj.wallet.Wallet: Insufficient value in wallet for send: needed 0.00001606 BTC more 
Oct-15 06:43:21.845 [JavaFX Application Thread] ERROR b.c.d.g.v.VoteRevealService: VoteRevealException{
     voteRevealTx=null,
     blindVoteTxId='3cf435e275b8e1518ea969fe90e0504bbed1d68135310b3c24546244fca90b5d',
     myVote=null
} bisq.core.dao.governance.votereveal.VoteRevealException: Exception at calling revealVote. 
Oct-15 06:43:24.448 [JavaFX Application Thread] INFO  b.c.d.m.DaoStateMonitoringService: Passed checkpoint Checkpoint {
     height=586920,
     hash=523aaad4e760f6ac6196fec1b3ec9a2f42e5b272
} 
```

Of course my BTC balance was vertically challenged  (euphemism for "too low"). If I didn't catch the exception in the logs, I would never have known there was an issue. Once I topped up, and on application restart, vote was published and information pop-up displayed.

I expected the earlier issue to have been reported with a pop-up as well.

I will fix it.

**Comment by wiz** [comment]
Good catch, the silent error should definitely be fixed, but I think the bigger point is more educating new users. Basically if you want to participate in DAO governance, you can never let your BTC or BSQ balance fall to zero.

**Comment by niyid** [comment]
> you can never let your BTC or BSQ balance fall to zero.

I am afraid, that is not a very user-friendly requirement. Users should be allowed to use software without being provided a stringent set of rules (much like babysitting); and be able to discover why it does not work in the expected manner for any use-case.
