### ISSUE TITLE
client trade-flow problems

### ISSUE THREAD

**Issue by PrivateScandal** [bisq-network/bisq#3411]
This issue describes the problems of the Bisq client, that gets stuck during the trading protocol. 

This was collected from slack conversation [thread] and forum thread [forum].

## Stuck in "wait for payment initiation" status

I have accepted an offer to sell bitcoin published by a remote party, i.e. I'm in a position of a bitcoin seller and am supposed to send fiat to their account. After charging the safety deposit together with the trading amount the buyer has completed the fiat transaction which I see on my fiat account. According to his words:

> I pressed the "Payment initiated" button right after the payment was made and the message appears: "the message reached the network user".

However, on my side the trade remained in a "Wait until payment has stared status". Hence I am unable to release the BTC to the buyer.

I might have disconnected during the trade -- I'm not sure.

Also, the buyer says that there is a difference between the trade with me and his previous trades:

> With you it appears in "Status of the payment message started" = "The message reached the network user"
> However, in the other exchanges I have open it seems "Status of the payment message started" = "The network user confirmed the receipt of the message"

## Strange behaviour on side of BTC buyer

This describes an experience of another user ( on slack @ZedF.K) [thread], with a problem that might be related.

> Similar thing happened to me during a Buy BTC order (I was the buyer) Luckily the seller's client did not freeze and he was able to release the funds. On my client I was able to send the funds to my external wallet; at the same time, the trade remained in a "waiting for peer to confirm receipt of payment" status and there was nothing I could do except request mediation. After 1 or 2 days the mediator set the transaction in my favor but the trade still remained in a "waiting for seller to confirm receipt of payment" state until one day it randomly disappeared; I don't know what happened and I don't believe the mediator was able to resolve anything because even after he forced the trade into a state, it was still stuck in my client. Like I said, I was able to withdraw the funds while the trade was stuck (and before I even contacted Support/mediator) so I was more annoyed than anything and I don't think anything was really resolved or reported to the development team. I'm sorry I am unable to offer any suggestion but I thought that my experience should at least be reported somewhere, especially if someone else is having a similar problem.
>
> Edit: the only abnormal thing that happened during this trade was when I first clicked the Confirm Payment Has Been Sent button, it timed out and said to try again. I clicked it several times, each time with the same error. I can only assume that this somehow messed up the internal state of the trade for my client; meanwhile the seller must have actually received the first confirmation of payment message but failed to respond to my client.

[thread]: https://app.slack.com/client/T0336TYT4/C0336TYTG/thread/C0336TYTG-1571131976.064900
[forum]: https://bisq.community/t/stuck-open-trade-status-releasing-the-funds/8522

**Comment by PrivateScandal** [comment]
Update:

I have confirmed to the mediator that the payment has arrived and could chat with him in a secret chat (counter party not included, although I didn’t see any problem in that – it might even be desirable). Then, without seeing the suggestion of the solution the mediator stopped communicating.

When I have contacted the other party a few days later, I was told, that the mediator suggested the payout (in the amounts that we agreed initially, returning the safety deposit) and the BTC buyer accepted the proposal. However, I cannot see any any payout button that would appear in my client.

**Comment by wiz** [comment]
There is a bug which can prevent in-trade chat and support chat from working on bugged trades, so please join Bisq's #support channel on Keybase to communicate with arbitrators and developers directly.

**Comment by PrivateScandal** [comment]
I have contacted the #support on keybase. The issue has now been solved and the traders BTC and my safety deposit were payed back by the arbitrator.

After the issue has been closed I have updated to v1.2.2.

Although the trade has been closed now, it still appear in the Support -> Mediation tab.

**Comment by ripcurlx** [comment]
> Although the trade has been closed now, it still appear in the Support -> Mediation tab.

Is the mediation case still open?
