### ISSUE TITLE
Fee reimbursement for non-existing trade ID (timeout error)

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#3418]
Bisq version: 1.1.7
While using Bisq for the first time and trying to create a ‘new offer to sell BTC for EUR’ I got a timeout error message that seems to have rounded down my available BTC balance to three decimal places.
I’m therefore assuming a fee has been charged although I have no trade IDs in the ‘portfolio’ tab to show.
The value in question (equivalent to roughly 0,90 EUR in BTC) is visible in the ‘funds’ tab as sent to a particular address on Oct 12, although with an unconfirmed status (the info on the ‘confirmations’ column says ‘seen  by 0 peer(s) / 0 confirmations’).
Exactly what information do I need to share publicly (or ideally by PM) in order to make a reimbursement request?

**Comment by A1Z9** [comment]
My opinion (from a user point of view) is the following:
All transactions (and by this I mean anything that changes your account balance) should have a built-in option that allows it to be handled/disputed/reported within the app.
There’s a clear difference between a bug/error that makes your Bisq experience less user-friendly and a bug/error that has a real impact on your account balance.
At the end of the day bugs always happen no matter what software you use, but I’m sure you would agree that some bugs/errors are critical and thus urgent to solve (those who have an impact on your account balance) while others are just nuisances that can be corrected whenever possible.
Critical bugs/errors affect users’ confidence in the platform and should have a built-in reporting mechanism (whether by the app reporting the issue on its own or allowing users to report issues within the app), while the vast majority of other bugs/errors and improvement suggestions can be treated differently (eventually outside the app) without raising any issues in terms of user privacy.
In my case I posted my problem on github (#3418) and after 12 days I still have zero feedback.

**Comment by freimair** [comment]
this is probably loosely related to #3395 

@A1Z9 can you provide us with the logs of around the time you tried to create the offer?

**Comment by A1Z9** [comment]
@freimair,
Thanks for the reply. At first glance it doesn't seem like something related to the issue described in #3395.
As you can see from the screenshot, the value withdrawn from the wallet is still to be confirmed after 15 days, although immediately deducted from the balance.
![image](https://user-images.githubusercontent.com/56651705/68090442-b7326600-fe6b-11e9-9f0d-be9dee3ac197.png)
I’m therefore assuming a fee has been charged although I have no history of trade IDs in the ‘portfolio’ tab to show you.
By looking at all the addresses and transaction IDs, I reach the same conclusion: 19Cc12htSQVpMEmr2GqP8A36tZvQDGygZv looks like a fee address. So it seems I’ve charged with a fee although I see no reason for that fee to be processed.
Maybe by looking at the log in annex you can find some other relevant info?
[bisq.txt](https://github.com/bisq-network/bisq/files/3801982/bisq.txt)
