### ISSUE TITLE
OSX client cannot connect to P2P network

### ISSUE THREAD

**Issue by Sjors** [bisq-network/bisq#342]
It manages to synchronise the (testnet?) blockchain, but connecting to the P2P method fails with the following error:

![error](https://cloud.githubusercontent.com/assets/10217/8266960/6bd92002-174a-11e5-9661-f0caf3f44b5c.png)

I tried with and without the OSX firewall. I also tried with and without the Avast web shield.

Version 0.2.1 running on Yosemite 10.10.3 (14D136)

**Comment by ManfredKarrer** [comment]
There was some issues with the bootstrapping nodes. Now it should work again.

**Comment by Sjors** [comment]
Indeed it works, cool!

Maybe you can embed a little HTML system status page on the start screen.

**Comment by ManfredKarrer** [comment]
They should run normally stabil and later many other users should be able to run bootstrap nodes. Need to investigate what causes those problems, I have seen a few times alreay, happens after a few weeks running fine... In the latest code (which is not commited yet) I have also a more fault tolerant version, so hope that will not happen again even if one bootstrap node crashes.
