### ISSUE TITLE
Waiting for Seller's payment confirmation

### ISSUE THREAD

**Issue by niyid** [bisq-network/bisq#3424]
I am a bit puzzled as to the idea behind the screenshot shown below. It suggests a manual confirmation by the seller in for the trade to complete when it can be automatically confirmed by associating the payment transaction with the trade (for instance after 9 confirmations, payment should be automatically confirmed without any inputs from the receiver).

I am curious as to the choice behind this manual process. Is it a carryover from an old design?

![Screenshot from 2019-10-18 02-00-35](https://user-images.githubusercontent.com/20237127/67058171-91a71c00-f14b-11e9-9f87-42376740a5c2.png)

**Comment by freimair** [comment]
what market is the trade in?

for SEPA trades, this has to be a manual process. I am not aware of this manual process is necessary in eg. BSQ/BTC trades.

**Comment by niyid** [comment]
> what market is the trade in?
> 
> for SEPA trades, this has to be a manual process. I am not aware of this manual process is necessary in eg. BSQ/BTC trades.

@freimair 
Sorry for the delay. I do not know why I did not get a notification (maybe I missed it).

It was a BSQ/BTC trade. So you mean the confirmation is automatic (meaning the BSQ transfer to the seller was automatically confirmed)?

**Comment by ripcurlx** [comment]
> > what market is the trade in?
> > for SEPA trades, this has to be a manual process. I am not aware of this manual process is necessary in eg. BSQ/BTC trades.
> 
> @freimair
> Sorry for the delay. I do not know why I did not get a notification (maybe I missed it).
> 
> It was a BSQ/BTC trade. So you mean the confirmation is automatic (meaning the BSQ transfer to the seller was automatically confirmed)?

This is by design atm. All fiat and alt coin accounts have to be confirmed manually.
