### ISSUE TITLE
Create new intro pop-up for v1.2

### ISSUE THREAD

**Issue by m52go** [bisq-network/bisq#3426]
To replace the current DAO pop-up that shows when new users open Bisq.

I think it's critical that users see **both** announcements—account signing and new trade protocol. If we put them on different panels, it's likely they'll miss at least one of them.

This is also why I've removed the "Dismiss" button from the DAO pop-up and replaced it with a small X in the top-right. Would be great if the pop-up persists until the X is clicked, so that the user can click on both "Learn More" buttons before the box disappears.

The "Learn More" links will lead to documentation, which will hopefully include video descriptions of the new mechanisms too.

@pedromvpg could use your feedback here! cc @ripcurlx.

_Proposed pop-up_

![v12-intro-mockup](https://user-images.githubusercontent.com/735155/67089382-718c5280-f175-11e9-9c0d-46a0d4598fe2.png)

_Old DAO pop-up (for reference)_

![Screenshot from 2019-10-18 06-32-47](https://user-images.githubusercontent.com/735155/67089344-59b4ce80-f175-11e9-8e29-fea57b0d3de0.png)

**Comment by ripcurlx** [comment]
@m52go I'll do my best to layout as good as possible.
@pedromvpg If you have any suggestions on the exact layout feel free to provide one here within EOD.

**Comment by m52go** [comment]
@ripcurlx sounds good. For links:

* Account Signing button can go to https://docs.bisq.network/payment-methods#account-signing.
* New Trade Protocol button can go to https://docs.bisq.network/trading-rules.

**Comment by ripcurlx** [comment]
How about this: 
![Bildschirmfoto 2019-10-21 um 15 39 12](https://user-images.githubusercontent.com/170962/67210221-fea30600-f418-11e9-8a60-b5e241af6883.png)

I kept the cancel icon in green as we don't have action buttons right now that are black.

**Comment by pedromvpg** [comment]
Sorry, only seeing this now.
I think it looks good but I can do a couple of adjustments tonight.

**Comment by m52go** [comment]
Cool. BTW images may be improved too...the ones I used are workable but meant to be placeholders.

**Comment by pedromvpg** [comment]
I think the images are ok.
Here's my proposal with slightly different typographic approach. 


![Bisq Critical Updates](https://user-images.githubusercontent.com/807505/67251698-e2fe2680-f43d-11e9-8158-a26331e9c901.png)

**Comment by pedromvpg** [comment]
I think the CTAs need to be toned down, and in general the modal should feel more like a warning/info than an announcement.

**Comment by ripcurlx** [comment]
> I think the images are ok.
> Here's my proposal with slightly different typographic approach.
> 
> ![Bisq Critical Updates](https://user-images.githubusercontent.com/807505/67251698-e2fe2680-f43d-11e9-8158-a26331e9c901.png)

@pedromvpg  Thanks! I'll try to match it as close as possible. Do you have a Sketch file or something similar so I can take the exact measurements and font sizes?

**Comment by ripcurlx** [comment]
@pedromvpg Is that close enough?
![Bildschirmfoto 2019-10-23 um 12 41 54](https://user-images.githubusercontent.com/170962/67385012-84968c80-f592-11e9-9d44-b48057552b4f.png)

**Comment by m52go** [comment]
@ripcurlx I think it would be better if there was more space before and after the images so the text stands out more.

**Comment by ripcurlx** [comment]
I've increased spacing and changed the wording a little bit. What do you think? 
- Two Critical Updates sounds a little bit too much as if there is a problem.
- 2-of-2 multisig might be too technical or could lead to misconceptions without having the full context.

![Bildschirmfoto 2019-10-24 um 10 54 01](https://user-images.githubusercontent.com/170962/67469525-9c324b80-f64c-11e9-81f9-01037f973554.png)

**Comment by pedromvpg** [comment]
Hi @ripcurlx 
Awesome! Just a couple of comments.

Pedro

CURRENT
![CURRENT](https://user-images.githubusercontent.com/807505/67531865-484a5580-f692-11e9-860f-fab3bca1a7ca.png)

PROPOSED
![PROPOSED](https://user-images.githubusercontent.com/807505/67531866-484a5580-f692-11e9-8b49-5c752eaa30ed.png)

**Comment by pedromvpg** [comment]
Just on last thing.
Can we add a 1px #E0E0E0 solid border around the images to framed them a little better?

Right now its hard to distinguish what is UI and what is part of the message.

![BORDER](https://user-images.githubusercontent.com/807505/67532025-cb6bab80-f692-11e9-9ca5-43f754cbe9c4.png)

**Comment by ripcurlx** [comment]
I applied all changes except for the new link icon. I use atm a link icon from the material design library and I don't have this icon available. I have to find a proper way to extend this library in an own fork, but that would be too much work for this release unfortunately. So I'd keep the external link icon as we have it in the app atm.
![Bildschirmfoto 2019-10-25 um 10 09 04](https://user-images.githubusercontent.com/170962/67554364-86d22580-f70f-11e9-883a-4155968d4843.png)
