### ISSUE TITLE
Minimize to system tray (OSX)

### ISSUE THREAD

**Issue by Sjors** [bisq-network/bisq#343]
I assume my trades won't go through if I close the app? I don't like minimized windows, soI would like to leave the app open with a system tray icon (which should be the default if you close the window, rather than quitting).

**Comment by ManfredKarrer** [comment]
Hi @Sjors, sorry for the late reply...
The behaviour which will be used in the final app (already implemented but deactivated for testing purpose) is like that:
The app will stay in background when you close the window or use cmd+q/w. To quit the application you need to do it in the system tray. So as long the app is not quit all trades get accepted. Only if you quit the app your offers will be removed from the DHT and another peer cannot take any offer (if he missed the offer close, or you kill the app and the close routine does nto succeed). A short time to life makes tangling offers also a short living problem.

**Comment by ripcurlx** [comment]
@ManfredKarrer This is not implemented in the client atm. Is this a feature that was requested a lot on different channels?

**Comment by ManfredKarrer** [comment]
Was never requested by anyone else. I personally find it confusing if a (main) window closes but the app keeps running.
