### ISSUE TITLE
Bisq taking more than 2GB of memory during startup

### ISSUE THREAD

**Issue by BeppeInfo** [bisq-network/bisq#3430]
I can see that during the syncing to Bitcoin network the Java process listed in my system manager takes more than 2GB of memory, and that doesn't go down after the application is fully initialized

That makes my desktop hang for a long time, as I have *only* 8GB of RAM here

The operating system is Manjaro KDE x64

**Comment by spogulis** [comment]
Same on Windows. This is a major flaw for a small app like this one.

**Comment by BeppeInfo** [comment]
It seems like minimizing the application during startup prevents memory usage from rising that much

Still takes quite a bit of RAM, but my system does not hang

**Comment by freimair** [comment]
I just ran out of RAM on my dev-machine. 32GB+4GB swap. Here is a visualvm dump of my always-on bisq.

![Screenshot from 2019-11-25 12-35-09](https://user-images.githubusercontent.com/1070734/69537619-cd21db00-0f80-11ea-8e15-e0a34d3003b1.png)

There seems to be a lot of javafx-related stuff taking and keeping a lot of memory. Can anybody investigate the GUI RAM requirements and how to lower them?

**Comment by chimp1984** [comment]
@freimair Maybe that is related: https://github.com/bisq-network/bisq/issues/3677

**Comment by BeppeInfo** [comment]
Is that Mesa fix related? https://gitlab.freedesktop.org/mesa/mesa/issues/2270

My personal machine uses radeon graphics with the Mesa drives, but I've saw simular issues in a Nvidia System

**Comment by freimair** [comment]
hm that is tricky. I, for starters, cannot reproduce the issue - not at all.

My system is a desktop configuration:
- Intel 8th-gen core processor
- plenty of RAM
- Intel Corporation UHD Graphics 630
- Arch linux

here is my first minute of a bisq startup profiled:
![Screenshot from 2020-02-27 12-48-45](https://user-images.githubusercontent.com/1070734/75442365-9b455980-595f-11ea-9ef4-727df16aaeb0.png)

**Comment by freimair** [comment]
and here is the trace with the old trusty laptop
- Intel Core 2 Duo CPU
- 4 GB of RAM
- Nvidia Corporation  G98M [Quadro NVS 160M] (rev a1)
- Arch linux

![Bildschirmfoto von 2020-02-27 13-46-24](https://user-images.githubusercontent.com/1070734/75447358-8077e280-5969-11ea-904f-aba9b969f34d.png)

@AnCaPepe can you provide a JProfiler trace like the one's above to document the issue?

**Comment by freimair** [comment]
@ghubstan had some success with adding `-XX:MaxRAM=2147483648` to the java opts and I can confirm that doing that limits the RAM usage to under 2GB, even after days of always-on.

Can you try that?

**Comment by chimp1984** [comment]
Can you try out the recommendations at https://github.com/bisq-network/bisq/issues/3918#issuecomment-607198677 ?

**Comment by cd2357** [comment]
Should be fixed in the most recent release (v1.6.4) which brings several UI performance improvements and generally reduces system resource consumption (especially RAM). Please try it out and let us know if it's still an issue for you.
