### ISSUE TITLE
error while creating transaction, and when clicking send in chat

### ISSUE THREAD

**Issue by gmalacrida** [bisq-network/bisq#3437]
[bisq.log](https://github.com/bisq-network/bisq/files/3751917/bisq.log)

**Comment by freimair** [comment]
for the chat issue, these lines seem to be a good hint:
```
oct.-21 18:24:42.239 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.NullPointerException
	at bisq.desktop.main.shared.ChatView.lambda$sendDisputeDirectMessage$12(ChatView.java:653)
	at java.base/java.util.Optional.map(Optional.java:254)
	at bisq.desktop.main.shared.ChatView.sendDisputeDirectMessage(ChatView.java:649)
[snip]
```

@gmalacrida is the message sent?

and I cannot spot anything in the logs indicating an error while creating a transaction. Can you provide more info on this? How to reproduce, what is the actual error, what did you expect to happen?

for the devs out there, there is a fair amount of `WARN  b.c.trade.Trade: depositTx is null` in the logs. Can that have anything to do with the issue?
