### ISSUE TITLE
Bisq sucks!!!

### ISSUE THREAD

**Issue by zanetti74** [bisq-network/bisq#3438]
Bisq works so fine, ok, but when you find a problem like I did that 4 transactions did not had the blockchain confirmation and they got stuck for more than 20 days, forget it. There is nothing to help you. I got more than 20 days with my BTC stuck on this system, the arbitrations seems to read my messagens and do nothing. It is a descentralized system, ok, but if you don´t have the right people that reply to your problem and help you and they get some payment for that, **FORGET!** IT IS NEVER GOING TO GROW! How can I trust a system where the people that suppose to work to get some payment does nothing? How can I tell more people to joing the system and make it grow? Localbitcoins is 1000x better so far.

**Comment by chimp1984** [comment]
Sorry to hear that. We need to make better support a priority after the 1.2 release.

**Comment by niyid** [comment]
This may have something to do with the unobtrusiveness of the **`Support`** section which I referred to in issue #3401. Apparently pending issues in **`Support`** are not treated with the priority they deserve both on the complaint and arbitration side.

**Comment by zanetti74** [comment]
Yep!
21 days stuck, could not sell the coins, buyer could not pay, I could not find an easy way to solve on Bisq, the arbitrator has no knowledge on how to deal with that.

On Mon, Oct 21, 2019 at 10:12 PM niyid <notifications@github.com<mailto:notifications@github.com>> wrote:

This may have something to do with the unobtrusiveness of the Support section which I referred to in issue #3401<https://github.com/bisq-network/bisq/issues/3401>.

**Comment by ripcurlx** [comment]
@zanetti74 Sorry to hear that you had such a bad experience using Bisq. We'll announce some changes this Thursday that will have an effect also on the support handling going forward.

> @channel, we'll hold a call next week to share the outcome of the planning and prioritization efforts that have been underway. The primary audience is active contributors and BSQ stakeholders, but I'm sure many Bisq users and Keybase members will be interested to join as well. All are welcome.
> 
> Who: Bisq contributors, stakeholders and users
> What: Bisq Q1 2020 Update
> When: Thursday, January 30th @ 9a PST / 6p CET
> Where: https://us04web.zoom.us/j/5702741068
> 
> We'll announce this more broadly via Twitter and other channels shortly. For those who can't make the live call, a recording will be posted to the Bisq YouTube channel afterward.
> 
> If it's likely you'll attend, consider giving a 👍 below. Thanks and I hope to see you there!

Are your issues solved already? If not please re-open this issue and I'll have a look at it.
