### ISSUE TITLE
Fatal exception on startup

### ISSUE THREAD

**Issue by Sjors** [bisq-network/bisq#344]
I navigated to the open for withdrawal tab, which resulted in a crash. Now every time I start the, I get the following crash:
![fatal](https://cloud.githubusercontent.com/assets/10217/8267274/002e2626-175a-11e5-9b19-405ccdd63f14.png)

Is there a configuration file where I can tell the app not to open that tab again on launch?

**Comment by ManfredKarrer** [comment]
Have you used the app with earlier versions already? If so you need to delete the data dir, as the persisted data are not compatible. I just treid it with an ampty data dir and could naviate to that screen without problems. Which OS you use?

**Comment by Sjors** [comment]
This is the first version I installed. I'm using OSX Yosemite 10.10.3
(14D136).

I placed a sell order earlier today, perhaps that's related?

**Comment by Sjors** [comment]
I placed a sell order earlier today, perhaps that's related?

**Comment by ManfredKarrer** [comment]
Hm, I don't think so. Can you try to delete the data dir if the error still happens. Can you send me the full error stacktraceby mail (mk at nucleo dot io)?

**Comment by Sjors** [comment]
Wouldn't that delete my trading wallet and deposit? I sent you the stack trace via email.

**Comment by ManfredKarrer** [comment]
You can remove only the db folder inside the testnet dir, or better make a backup.

**Comment by Sjors** [comment]
Removing the db folder did the trick. I also just noticed that I'm running 0.2.1 rather than the latest 0.3.1. I'll upgrade and let you know if I ever see this error again.
