### ISSUE TITLE
Dark Mode's Buy/Sell UI bubble text not clearly visible in v1.2.0

### ISSUE THREAD

**Issue by ghubstan** [bisq-network/bisq#3440]
[How to Reproduce]
1. Start Alice or Bob desktop
2. Set dark mode
3. Create buy or sell order
4. Click (or hover over) any  'i' or 'eye' icon in any of the following windows

[Expected Results]
Bubble text is easy to read in dark mode.

[Actual Results]
Bubble text not easy to read in dark mode -- text should be darker color.
![AdvancedOptionsText](https://user-images.githubusercontent.com/36207203/67334748-0cc85380-f4f9-11e9-9157-2e9f3d646491.png)

This issue was discovered during v1.2.0 [testing](https://bisq.ontestpad.com/script/103#/1) .

**Comment by ripcurlx** [comment]
@wiz Could you please have a look at that? Thanks!

**Comment by objectorange** [comment]
Was this not fixed? It looks like it.

**Comment by wiz** [comment]
Yeah this was fixed by @ripcurlx in #3803

**Comment by ripcurlx** [comment]
Closing as fixed in #3803.
