### ISSUE TITLE
Error occurred at task: SignMediatedPayoutTx

### ISSUE THREAD

**Issue by onlymarcus** [bisq-network/bisq#3443]
An error occurred at task: SignMediatedPayoutTx
Exception message: trade.getDepositTx() must not be null
[bisq.log](https://github.com/bisq-network/bisq/files/3759909/bisq.log)

A transaction has not been published to blockchain. When I click to accept the mediator's proposal, this error appears and my security deposit is still blocked.

**Comment by nicebug5** [comment]
I have the same problem #3502  
@onlymarcus, Did you solve the problem by any chance?

**Comment by wiz** [comment]
@onlymarcus @nicebug5  There is a bug which can prevent in-trade chat and support chat from working on bugged trades, so please join Bisq's #support channel on Keybase to communicate with arbitrators and developers directly.

**Comment by ripcurlx** [comment]
@onlymarcus Was your problem solved already? If not, please re-open this issue.
