### ISSUE TITLE
[1.2.0] Informational prompt explaining trade amount limit displays the limit in BSQ rather than BTC

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#3444]
When attempting to enter a value greater than the trade limit for the amount of BTC to buy/sell, the informational prompt displayed the limit in BSQ rather than BTC.
![image](https://user-images.githubusercontent.com/603793/67366324-20d77980-f528-11e9-9e1a-06a905dbd179.png)

**Comment by ripcurlx** [comment]
ah good catch, obviously took the wrong formatter for this popup.

**Comment by ripcurlx** [comment]
Fixed in https://github.com/bisq-network/bisq/pull/3445
