### ISSUE TITLE
[1.2.0] Update informational prompt upon creating fiat account with account signing details

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#3446]
The informational prompt that appears upon creating a national currency account mentions factors that contribute to the trade limits but does not mention the new account signing feature. It should be updated accordingly.
![image](https://user-images.githubusercontent.com/603793/67366845-1cf82700-f529-11e9-90de-0586f6a94018.png)

**Comment by ripcurlx** [comment]
@m52go Could you please have a look at that? Thanks!

**Comment by m52go** [comment]
Suggestion:

```
payment.limits.info=To limit chargeback risk, Bisq sets per-trade buy limits based on the following 2 factors:\n\
  \n\
  1. General chargeback risk for the payment method\n\
  2. Account signing status\n\
  \n\
  This payment account you just created carries some chargeback risk and is not yet signed by an arbitrator or trusted peer, \
  so it is limited to buying 0.01 BTC per trade.\
  After it is signed, buy limits will increase as follows:\n\
  \n\
  ● Before signing, and 30 days after signing, your per-trade buy limit will be {0}\n\
  ● 30 days after signing, your per-trade buy limit will be {1}\n\
  ● 60 days after signing, your per-trade buy limit will be {2}\n\
  \n\
  Sell limits are not affected by account signing, and increase merely as account age increases. More information is at https://docs.bisq.network/payment-methods#account-signing.\n\
  \n\
  There are no limits on the number of trades you can make.
```

@ripcurlx you mentioned [here](https://github.com/bisq-network/bisq-docs/pull/167#issuecomment-545833816) that signed buyers can sign sellers' payment accounts too. Does this serve the same purpose as signed sellers signing buyers' payment accounts? Can an untrusted seller have their limits raised by selling BTC to a trusted buyer?

Note that the variables in the string above may have changed (e.g., {0} definitely has).

I assume this issue is a more general version of #3457.

**Comment by ripcurlx** [comment]
> @ripcurlx you mentioned [here](https://github.com/bisq-network/bisq-docs/pull/167#issuecomment-545833816) that signed buyers can sign sellers' payment accounts too. Does this serve the same purpose as signed sellers signing buyers' payment accounts? Can an untrusted seller have their limits raised by selling BTC to a trusted buyer?

The seller side doesn't have the 0.01 BTC limit anyways. So it is just about being able to sign other accounts 30 days later.

**Comment by ripcurlx** [comment]
So there are different limits for buyer and seller side.

**Comment by ripcurlx** [comment]
You can see this in the `Limitations` field if you select the payment account.
![Bildschirmfoto 2019-10-25 um 10 44 41](https://user-images.githubusercontent.com/170962/67557000-78d2d380-f714-11e9-8051-34873de0c047.png)

**Comment by m52go** [comment]
I see -- great. I've updated the text above to clarify the difference between buy and sell limits with respect to account signing.
