### ISSUE TITLE
Dark mode not disabled on 1st attempt to turn it off after restart

### ISSUE THREAD

**Issue by ghubstan** [bisq-network/bisq#3447]
[How to Reproduce]
1. Start arbitration desktop on Ubuntu 18
2. Enable dark mode
3. Shut down desktop
4. Restart arbitration desktop
5. Disable dark mode 

[Expected Results]
Dark mode is disabled on 1st attempt to turn it off.

[Actual Results]
Dark mode is not disabled on 1st attempt to turn it off (see bottom left of screen shot below).
It is disabled on 2nd attempt to turn it off.
![DarkModeNotDisabled](https://user-images.githubusercontent.com/36207203/67396315-b8b38280-f57d-11e9-9c48-2beab02c13d3.png)

This issue was discovered during v1.2.0 [testing](https://bisq.ontestpad.com/script/103#/1) .

**Comment by freimair** [comment]
I am not sure if I catch the issue here. Your expected/actual results are for step 5 or afterwards?

**Comment by ghubstan** [comment]
The expected/actual results apply to step 5.  
When you disable dark mode (5), nothing happens.
It does work after you slide the button back to the left, then slide it to the right a second time.

**Comment by Bigsy11** [comment]
This issue also exists in Bisq 1.2.3 on Fedora 30.
If dark mode is disabled and Bisq restarted, it comes back in dark mode.
Tried 3 Bisq restarts just now.

If the dark mode button is moved to light mode, and then user goes to any other part of the app, and then returns to Settings, the dark mode selector automatically moves back to dark mode.

So, in my case, not able to turn off dark mode at all yet.

**Comment by ripcurlx** [comment]
> This issue also exists in Bisq 1.2.3 on Fedora 30.
> If dark mode is disabled and Bisq restarted, it comes back in dark mode.
> Tried 3 Bisq restarts just now.
> 
> If the dark mode button is moved to light mode, and then user goes to any other part of the app, and then returns to Settings, the dark mode selector automatically moves back to dark mode.
> 
> So, in my case, not able to turn off dark mode at all yet.

@wiz Could you please have a look at it? Thanks!
