### ISSUE TITLE
Many trades produces multiple address entry in Send Funds tab and incorrect btc balance

### ISSUE THREAD

**Issue by beingindot** [bisq-network/bisq#3451]
[How to reproduce] 
1. Start Alice
2. Perform many btc trades so that btc balance distributed within the wallet
3. Distribute btc within the bisq wallet.

[Expected Results]
List of address in Send Funds should be unique and btc balance should be real count.

[Actual Results]
List of address displayed one address with two entries.
BTC balance also reflected those two entries. 

![Screenshot from 2019-10-23 21-05-35](https://user-images.githubusercontent.com/55691179/67420990-3b275b00-f5ed-11e9-9b95-47357a960d1b.png)
Figure 1. one btc address having two entries and btc balance also incorrect.

The issue was discovered during v1.2.0 [testing](https://bisq.ontestpad.com/script/110/report)

**Comment by chimp1984** [comment]
Can you make a spv resync at settings/network?

**Comment by beingindot** [comment]
did that. but no change in listing and balance.

**Comment by beingindot** [comment]
investigating to find the reason.
