### ISSUE TITLE
Trade Stuck. User Deleted Bisq. Can’t request Support

### ISSUE THREAD

**Issue by bisqtrader12** [bisq-network/bisq#3455]
I need help someone took my offer was getting a bug instead of reaching out to me they deleted bisq and reinstalled. He doesn't have access to the trade anymore. This trade is in limbo I can’t do nothing someone please help get my btc.

 Please help! I tried the get support button on the bottom left (see picture below) it doesnt do anything. it doesnt take me to support.  See how the bottom no details show up at all. Completely blank and in limbo.

onion address of arbitrator and mediator
exihmfza5343eh7q.onion:9999 / exihmfza5343eh7q.onion:9999

can someone get a hold of them? I don’t know how its possible but i need their help but there is no way in bisq for me to take trade to support because tab doesnt work for me under that trade.  If this always happens when other user deletes bisq thats a serious bug that needs to be fixed.

![bitcoin help](https://user-images.githubusercontent.com/56962498/67482302-8b281100-f631-11e9-8206-a1a1b5828421.png)

**Comment by ripcurlx** [comment]
> they deleted bisq and reinstalled.

How do you know this? Where you able to chat already within the client? Did you receive already one blockchain confirmation before you got the screen above? What is the state of the multisig transaction within Funds > Transactions?

**Comment by ripcurlx** [comment]
If they delete Bisq, but don't delete the data directory she/he should be able to continue with the same trade after a re-install.

**Comment by bisqtrader12** [comment]
I know this because the buyer started a new account and took another offer from me so we chatted he explained situation and apologized.  This is the maker fee transaction id https://blockstream.info/tx/19287ff5011ec2b855b9d092bc0c3e7300c685ed3730f66b98d85109cd10c101

When I go to funds transaction tab all I see is a transaction Maker and tx fee to trader id for .0000851  does this mean my BTC never went into multi sig and I still have it? Trade was for .01 btc

**Comment by ripcurlx** [comment]
One solution would be to do a manual output with the arbitrator for this transaction. It looks like as if the funds are already locked up in the transaction. Do you see that in Funds -> Locked Funds as well?

**Comment by ripcurlx** [comment]
I think we should move the issue into the support repository. I'm quite tied up in release preparations for v1.2.0 (will be released on Monday) right now, but I'm happy to assist further afterwards.

**Comment by ripcurlx** [comment]
Issue moved to [bisq-network/support #316](https://github.com/bisq-network/support/issues/316) via [**ZenHub**](https://www.zenhub.com/)
