### ISSUE TITLE
Account creation info popup not having buyer limits

### ISSUE THREAD

**Issue by beingindot** [bisq-network/bisq#3457]
### Description
Account creation info popup currently explains only about seller trade limits.
It should also contain buyer limits
Also it should clearly separate buyer/seller limits explanation.

#### Version
1.2.0

### Steps to reproduce

1. go to account tab -> currency accounts -> add new account
2. select chase quickpay
3. Fill the account details and click save new account
4. popup appears

### Expected behaviour
Buyer and seller limit should be split mention: @m52go  @ripcurlx 

Buyer Limit:
Your limit for buy offers is 0.01 BTC right now as your account hasn't been signed and the peer limit hasn't been lifted. You'll find more information at https://docs.bisq.network/payment-methods#account-signing.

### Actual behaviour

No buyer limit mentioned. only seller limit mentioned and there is no mention that it's sellers limit.

### Screenshots

![Screenshot from 2019-10-24 21-27-18](https://user-images.githubusercontent.com/55691179/67503637-9cab0080-f6a5-11e9-8a43-8827f3d708d9.png)

#### Device or machine

Ubuntu

**Comment by ripcurlx** [comment]
This is a duplicate issue raised in #3446 already.
