### ISSUE TITLE
National bank transfer doesnt have account number validation

### ISSUE THREAD

**Issue by beingindot** [bisq-network/bisq#3459]
### Description

National bank transfer doesnt have account number validation

#### Version
1.2.0

### Steps to reproduce

create national bank transfer account
select asia and any country
create new account without filling account number.

### Expected behaviour

Atleast account number field validation should be there.

### Actual behaviour

Able to create new account without filling account number.

### Screenshots

![Screenshot from 2019-10-24 22-10-38](https://user-images.githubusercontent.com/55691179/67506709-332df080-f6ab-11e9-9246-f4b8255524ae.png)

#### Device or machine

Ubuntu

**Comment by ripcurlx** [comment]
I think it is tricky to implement this properly for all countries all over the world. We do have special cases for some countries already (e.g. Argentina), but I think doing it properly for all countries is not 
feasible right now.

**Comment by beingindot** [comment]
I agree. but i thought we should have account number fileld should not be empty validation. 
thats why created this bug.
if that's not enforceable pls close this bug.

**Comment by beingindot** [comment]
working on it.
