### ISSUE TITLE
revolut/uphold account - unable to remove after creation

### ISSUE THREAD

**Issue by beingindot** [bisq-network/bisq#3461]
### Description

revolut account is not able to be removed immediately after creation using minus button
Though able to delete after restart.

Able to observe this behavior for uphold too
#### Version

1.2.0

### Steps to reproduce

1. create revolut account
2. remove that account using minus button in account list
3. click yes on confirm popup
4. It is not removed from listing

### Expected behaviour

Account should be removed

### Actual behaviour

Account is not removed

#### Device or machine

Ubuntu

**Comment by beingindot** [comment]
I'm able to reproduce and working on it.

**Comment by chimp1984** [comment]
This issues also happens at Uphold or MoneyGram. All payment methods using a list of tradeCurrencies.
