### ISSUE TITLE
Rephrase the project's slogan

### ISSUE THREAD

**Issue by jonathascarrijo** [bisq-network/bisq#347]
I don't know if this is the right channel, but I'll post it here.

Bitsquare is an excellent idea and a necessary addition to the cryptocurrency ecosystem.

I think the currently used slogan, "the bitcoin descentralized exchange" became somehow misleading. It may lead the user to believe that bisquare is an alternative to bitshares and openledger, who themselves are descentralized asset exchanges.

What makes bitsquare very distinct, in my perception, is that it is a FIAT to bitcoin descentralized exchange. While openledger relies on bridges and gateways to provide a user means to acquire bitshares or obits, bitsquare has a unique intention to enable any two willing parties, small or large, to trustlessly exchange crypto for fiat, in a safe way.

I think this should be very clear to someone who just came by the project, and is trying to figure out what it is.

My suggestion is to adopt the slogan: "The first fiat to bitcoin descentralized exchange".

I read many saying on reddit that such a project is impossible. But from my understanding of your whitepaper, you have proven them to be wrong.

**Comment by ManfredKarrer** [comment]
Hi @jonathascarrijo,
thanks for sharing your thoughts. In fact the initial slogan was "The P2P Fiat-Bitcoin exchange" (https://bitcointalk.org/index.php?topic=647457). One reason for the change was that we support altcoins-bitcoin as well. Other was that some people are not so familiar with terms like fiat and P2P.
But I will consider your input and maybe we adopt the slogan once we start promoting it (when beta version is ready).
If you don't mind we could continue discussion on the mailinglist or by mail. I prefer to use Github for the technical stuff.

**Comment by ManfredKarrer** [comment]
Continued here: https://groups.google.com/forum/#!topic/bitsquare/-ovmxqjJveE
