### ISSUE TITLE
Clean up trade statistics from duplicate entries

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#3470]
Currently we have some duplicate entries (see https://github.com/bisq-network/bisq/issues/3468) in the trade statistic map because the hash has changed with changes in the extraMap field and we added new enties in recent versions. As there was a republish routine for past trade statistics we added duplicates with such updates.
To fix that we should add some cleanup code which deletes those duplicates. We can check for trade ID and the most significant fields like price and amount. 
The republish routine was removed for v.1.2. so there should not be added new duplicates.
For future updates when we add entries to that map it would only be an issue if maker and taker have a different version. 
If the cleanup code does not cause performance issues we could leave it so it would handle such potential future scenarios as well. Alternatively we could add a Json Ignore annotation to the map as well.

**Comment by mrosseel** [comment]
is there a way to easily unit test this so new discrepancies can be detected early?

**Comment by chimp1984** [comment]
The intention of the extra data hashmap is to be flexible to add data without breaking backward compatibility. So if anyone adds a new entry there it will break the hash. Best is probably to exclude the extra map from the hash by json exclude.
A unit test is trivial here but will not help you discover if any new feature adds a new entry.

**Comment by chimp1984** [comment]
@bodymindarts Can you post your code how you observed those duplicates?
I just tried to find duplicates in the TradeStatistics2Store but could not see any using the offerID, amount and price as key.

**Comment by chimp1984** [comment]
I am working on a fix....
