### ISSUE TITLE
Close (X) button on new feature popup is hard to see in dark mode.

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#3472]
### Description

Close (X) button on new feature popup is hard to see in dark mode.

#### Version

release/v.1.2.0 commit 05135a500001131cb6aa85360b3d89fc300b3e71

### Steps to reproduce

- Run Bisq in a previous version and enabled dark mode
- Update to 1.2.0
- The new feature popup will be shown

### Expected behaviour

The close button should be clearly visible.

### Actual behaviour

The close button is hard to see.

### Screenshots

![image](https://user-images.githubusercontent.com/603793/67597894-146a4100-f721-11e9-9593-fc5d2557ba64.png)

#### Device or machine

Windows 10

**Comment by ripcurlx** [comment]
@devinbileck Should be fixed in #3495
