### ISSUE TITLE
Render issues on Linux

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#348]
Font render issues on Linux. See screenshot:
![fonts](https://cloud.githubusercontent.com/assets/1449498/12018108/576b0b20-ad5f-11e5-98ce-983c0aa3802a.png)

**Comment by ManfredKarrer** [comment]
If jar file compiled on Linux the Font (sans-serif) for the Webview is not recognized :-(
Lets remove webview completely, was just inteded as a quick solution.

**Comment by haiqu** [comment]
Was this resolved? Pretty old report.

**Comment by ripcurlx** [comment]
Closing this issue as WebView is not used within the app anymore.
