### ISSUE TITLE
[1.2.0] Adding fiat account that does not utilize account signing mentions signing restrictions in informational popup

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#3483]
### Description

When adding a fiat account that does not utilize signing (i.e. low chargeback risk), the informational popup mentions account signing restrictions.

#### Version

release/v1.2.0 (commit 8a000c100517fe5c2059742774b3a9d4ce1b22e3)

### Steps to reproduce

Add a fiat account with low chargeback risk (e.g. Perfect Money)

### Expected behaviour

The informational popup should not mention account signing restrictions.

### Actual behaviour

The informational popup shows restrictions that are not applicable.

### Screenshots

![image](https://user-images.githubusercontent.com/603793/67631564-6c09c900-f855-11e9-8a5d-992224872ff0.png)

**Comment by ripcurlx** [comment]
@devinbileck This should be fixed in the referenced PR #3497
