### ISSUE TITLE
[1.2.0] Hide account signing status in peer info popup for account types that don't use signing

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#3484]
### Description

When clicking on a peers avatar for an offer, there is no need to show signing status for account types that don't use signing (e.g. altcoin offers), just like it doesn't show payment age for altcoin offers.

#### Version

release/v1.2.0 (commit 8a000c100517fe5c2059742774b3a9d4ce1b22e3)

### Steps to reproduce

- Alice and Bob have created altcoin accounts
- Alice has published a buy offer
- Bob clicks on Alice's avatar icon for the offer

### Expected behaviour

The popup does not need to show account signing status.

### Actual behaviour

The popup indicates the account type doesn't use signing.

### Screenshots

![image](https://user-images.githubusercontent.com/603793/67631649-6791e000-f856-11e9-9112-8691cfcd25f2.png)

#### Device or machine

Windows 10

**Comment by ripcurlx** [comment]
Fixed with https://github.com/bisq-network/bisq/pull/3496

**Comment by devinbileck** [comment]
Verified. Closing.
