### ISSUE TITLE
[1.2.0] Offers for account types that do not utilize account signing show confusing "unsigned" status

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#3486]
### Description

Offers for account types that do not utilize account signing are shown as "unsigned" in the offer list. I don't think this is the best term to use as it may be confused with "not signed yet". Perhaps it should show something like "N/A"?

#### Version

release/v1.2.0 (commit 8a000c100517fe5c2059742774b3a9d4ce1b22e3)

### Screenshots

![image](https://user-images.githubusercontent.com/603793/67631805-492ce400-f858-11e9-9d1c-89949a433e8c.png)

**Comment by m52go** [comment]
Agree -- N/A is a lot better.

**Comment by devinbileck** [comment]
Verified. Closing.
