### ISSUE TITLE
[1.2.0] Results of DAO voting cycle are not visible under governance > vote results until restarting the app

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#3487]
### Description

Results of the DAO voting cycle are not visible under governance > vote results until restarting the app. It should be visible as soon as in the vote result phase.

#### Version

release/v.1.2.0 (commit 8a000c100517fe5c2059742774b3a9d4ce1b22e3)

### Steps to reproduce

Complete a DAO cycle including submitting a compensation request, voting, vote reveal, and vote results. Then view the vote results for the cycle under governance > vote results.

### Expected behaviour

The vote results for the cycle should be shown.

### Actual behaviour

No proposals or vote results are shown, even after progressing to the start of the following cycle. However, once you restart the app, the results are shown.

### Screenshots

Before restarting app:
![image](https://user-images.githubusercontent.com/603793/67631921-f2280e80-f859-11e9-9dfd-925681060d61.png)

After restarting app:
![image](https://user-images.githubusercontent.com/603793/67631962-6c589300-f85a-11e9-9918-0831e8a6906d.png)

#### Device or machine

Windows 10

**Comment by chimp1984** [comment]
Thanks for reporting!
Fixed with https://github.com/bisq-network/bisq/pull/3492

**Comment by devinbileck** [comment]
Verified. Closing.
