### ISSUE TITLE
proposed solution popup for alice comes repeatedly on switch menu

### ISSUE THREAD

**Issue by beingindot** [bisq-network/bisq#3501]
### Description

After mediation, alice accepts proposed solution. but after menu switch and coming back to portfolio menu popup again comes up.

#### Version

v1.2.0

### Steps to reproduce

Mediator suggests alice to send trade amount to bob.
Alice accepts the proposed solution.
Alice switches menu and comes back to portfolio menu.
proposed solution popup comes again.

### Expected behaviour

proposed solution popup should come only once.
clicking on view proposed solution after accept/reject, popup should not have any actionable buttons.

### Actual behaviour

proposed solution popup comes on switching menus. also after accepting viewing proposed solution, should not have any actionable buttons.

### Screenshots
![Screenshot from 2019-10-28 20-10-49](https://user-images.githubusercontent.com/55691179/67691413-8ca46100-f9c4-11e9-96c5-44e3933cdc1e.png)

#### Device or machine
Ubuntu 18.04

**Comment by ripcurlx** [comment]
> clicking on view proposed solution after accept/reject, popup should not have any actionable buttons.

I think the accept button should be deactivated or not available, but the possibility to reject should still be there in the case, that the other trading peer never responses.

**Comment by ripcurlx** [comment]
I think it should be something like this:
![Bildschirmfoto 2019-10-29 um 09 46 24](https://user-images.githubusercontent.com/170962/67751230-ff4b2600-fa30-11e9-8258-994414993536.png)
