### ISSUE TITLE
NinjaCoin Listing Request

### ISSUE THREAD

**Issue by NinjaCoin-Master** [bisq-network/bisq#3505]
### 1. Asset name
NinjaCoin

### 2. Ticker
NINJA

### 3. Block explorer URL
http://explorer.ninjacoin.org/

### 4. Additional technical requirements (yes/no)
no

### 5. Initial coin offering (yes/no)
no

**Comment by wiz** [comment]
> ### 5. Initial coin offering (yes/no)
> no

did you think that we wouldn't take 5 seconds to do a google search for "ninjacoin ico" ?

<img width="591" alt="Screen Shot 2019-10-29 at 22 46 05" src="https://user-images.githubusercontent.com/232186/67772742-efb5f680-fa9d-11e9-8547-e1ddf742ed1c.png">

**Comment by NinjaCoin-Master** [comment]
That was a bad ico attempt, there was no ico. If you want to list the currency well, otherwise it doesn't matter
