### ISSUE TITLE
Bisq block height issue 

### ISSUE THREAD

**Issue by Katana3** [bisq-network/bisq#3509]
### Description

New block must be 1 block above previous block. height={}, daoStateBlockChain.getLast().getHeight()={} [598021, 598040]

### Steps to reproduce

 1) open bisq 
2) click create new account
3) receive issue concerning block height

#### Device or machine
hp pavillion laptop with windows 10 home 

#### Additional info

[bisqlogfilefordebugging.txt](https://github.com/bisq-network/bisq/files/3785064/bisqlogfilefordebugging.txt)

**Comment by ripcurlx** [comment]
@Katana3 Your log file is indicating that you are still syncing with the blockchain (only 71% done)

**Comment by Katana3** [comment]
![image](https://user-images.githubusercontent.com/57149902/67798832-aa240a00-fa5a-11e9-9525-54e0d50aac20.png)

**Comment by ripcurlx** [comment]
I see in the background that your client is still syncing. Could you go to DAO > BSQ wallet > Transactions and wait until your client is fully synced.

**Comment by Katana3** [comment]
![image](https://user-images.githubusercontent.com/57149902/67799336-8ad9ac80-fa5b-11e9-9bee-70e6c6ffed03.png)
could a running proxy service be hindering the block syncing process

**Comment by Katana3** [comment]
proxy is off 
![image](https://user-images.githubusercontent.com/57149902/67799919-aabda000-fa5c-11e9-8fba-6c88b403570c.png)

**Comment by ripcurlx** [comment]
Actually a vpn shouldn't be a problem. I did experience issues with one price node running with a vpn, but regular seednodes should be fine.  Did you try a restart already?

**Comment by Katana3** [comment]
I have downloaded the update and tried a restart and still am receiving the same error message
![image](https://user-images.githubusercontent.com/57149902/67805205-eb221b80-fa66-11e9-899a-9661ca1efb87.png)

**Comment by ripcurlx** [comment]
I'll have a more detailed look at the logs and will let you know if I find something.

**Comment by Katana3** [comment]
Thank you for all your time!

**Comment by freimair** [comment]
should we check for a fully synced DAO before a new account can be created?

**Comment by Katana3** [comment]
Let me know any way I can assist!

**Comment by ripcurlx** [comment]
@Katana3 As we rolled out lots of changes since your issue was created. Does it work for you now already? Please re-open this issue if it still doesn't work.
