### ISSUE TITLE
Available balance pop-up currency wrong

### ISSUE THREAD

**Issue by rafaelpac** [bisq-network/bisq#3515]
### Description

At the top right corner of the window, we have the drop down menu for BTC rates, the available balance, the reserved funds and locked funds (all these last 3 in BTC units).
When the mouse is over any of these last three, the software calculates the value in the respective rate and displays a pop-up with the value converted to whatever currency was selected in the drop down menu.
Even though the conversion is working alright, the symbol that is always shown is "USD".
For example, check below what happens when BTC/COP is selected (Colombian Peso):

![image](https://user-images.githubusercontent.com/6444444/67819947-09ebd680-fa96-11e9-90c7-5979e4636b8a.png)

I wish I had 702k USD!!! :-)

#### Version

v1.2.0

### Steps to reproduce

Change the rate at the drop down and observe.

### Expected behaviour

In the example above, the pop-up should show 702.324,79 COP.

### Actual behaviour

Instead of showing "COP", it showed "USD" (it shows "USD" always)

**Comment by devinbileck** [comment]
Thanks for reporting this. I know where the issue lies. I will work on a fix.

**Comment by rafaelpac** [comment]
Thanks!
I am a total noob on Github. How should it go? If I find something like this and I know how to fix it in the code, how should I do it? Does something like this qualify to compensation on the DAO?

**Comment by devinbileck** [comment]
If you know how/what to fix for this, feel free! If you submit a PR, once it gets merged to master, you are eligible for compensation.
Otherwise let me know and I can work on a fix.
