### ISSUE TITLE
Bugs in Bisq

### ISSUE THREAD

**Issue by avomuc** [bisq-network/bisq#3517]
### Description
I cannot send messages to confirm received payments to users in Bisq. Also cannot answer moderator to a dispute. I attach exception message and log

An error occurred at task: SellerSignAndFinalizePayoutTx
Exception message: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@4cf14ed4, [B@14ae7d62, [B@26dcc5bb]
[bisq.log](https://github.com/bisq-network/bisq/files/3787924/bisq.log)

**Comment by avomuc** [comment]
> ### Description
> I cannot send messages to confirm received payments to users in Bisq. Also cannot answer moderator to a dispute. I attach exception message and log
> 
> An error occurred at task: SellerSignAndFinalizePayoutTx
> Exception message: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@4cf14ed4, [B@14ae7d62, [B@26dcc5bb]
> [bisq.log](https://github.com/bisq-network/bisq/files/3787924/bisq.log)
> 
> ### Steps to reproduce
> ### Expected behaviour
> ### Actual behaviour
> ### Screenshots
> #### Device or machine
> #### Additional info

Windows 10 64 bits
Intel Core i7 6770HQ CPU
32GB RAM

**Comment by chimp1984** [comment]
Probably same situation as in https://github.com/bisq-network/bisq/issues/3520 (trade opened in old protocol and then a trader updated). Please contact the arbitrator (see in trade details the oninon address) on keybase. He has to do a manual payout.

**Comment by cd2357** [comment]
Closing, as it was clarified above.
