### ISSUE TITLE
Mediated trade shows locked funds warning

### ISSUE THREAD

**Issue by v0l** [bisq-network/bisq#3519]
Hi,

I have a mediated trade from a few weeks ago (17th Oct 2019), in my logs its saying i have locked funds for this trade still? 

```
bisq.core.trade.TradeManager: We found a closed trade with locked up funds. That should never happen. trade ID=czvnyxa-XXX
```

Mediator suggested a payout which was accepted.

```json
"mediatorNodeAddress": {
    "hostName": "exihmfza5343eh7q.onion",
    "port": 9999
  },
```

Let me know if you need more info. 

This is potentially just a local wallet state issue since i sometimes send from my Bisq wallet with electrum.

**Comment by ripcurlx** [comment]
> Hi,
> 
> I have a mediated trade from a few weeks ago (17th Oct 2019), in my logs its saying i have locked funds for this trade still?
> 
> ```
> bisq.core.trade.TradeManager: We found a closed trade with locked up funds. That should never happen. trade ID=czvnyxa-XXX
> ```
> 
> Mediator suggested a payout which was accepted.
> 
> ```json
> "mediatorNodeAddress": {
>     "hostName": "exihmfza5343eh7q.onion",
>     "port": 9999
>   },
> ```
> 
> Let me know if you need more info.
> 
> This is potentially just a local wallet state issue since i sometimes send from my Bisq wallet with electrum.

Is the mediation case open in the client as well?

**Comment by sqrrm** [comment]
@v0l We are currently looking at issues with the wallet. If you could share the log file it might help us. I can't say if your case is an issue or not from the information given.

You can email the logfile to sqrrm1@gmail.com

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

mQINBFnl6JQBEACzuRV/fkxeE46RzOH8AYiG7upKAfS9TilvUfInUL53rio3I1ST
knaoeswZiFy5Gtf4z5qSdveIjX6D5Qe+o//69SQwe9mq05KEB3Y6fN+gEjmHykke
fa5Hsdct53Rd9lEhiJN065kaTj2q0Oc9b3WoAZ8DAhYJCJSYg9Q5AxvNXP2DMVfH
lBDHkW+emz2dOSSU1YjVEh0SbtR0qG9SxifsZOoub++FFhYua6xJI7ytmfPgbBvC
nOUAzswHKzVdE1Uf5IKtX8YcqSxf/OuV74fLGw7jmQGEkIm5hvm2I7BJ8abRUnBm
HUo+pjF/ittIKRfQTaIuSPBy7PsJzmhwHZZU98Qy+SVh2P7p594PmD2DPHhVyasC
HraH5BtWqQw5FkH/l2Ww2nngj6wMqCtJms5clFPR+QsR7/qhMLXdiryGMoPi0RQY
MWBGwTfki1yllzHyjTSILBbM8CZcaEgdt7eCXTvvbenfKytJwjGxupA2NfgQ6Mwu
XYz2ZHCtg6Jw0hv7FtkIUrF4dCmI+h7xZjtoCbnPgaFeZRvKR/+aCDvwpOAZEXjY
8XLYhvcuIxYGUScU3aeZuC3Q4mSXUEY1rlUhjQx4THcFvjNVJfMFXeMlIbeMfaNO
CqzVc380y2HYGGh2cKEvYvDWpT1Heec5oQtnKUg8NE11PErfsDe2WNNIkwARAQAB
tBhzcXJybSA8c3Fycm0xQGdtYWlsLmNvbT6JAj0EEwEIACcFAlnl6JQCGyMFCQlm
AYAFCwkIBwIGFQgJCgsCBBYCAwECHgECF4AACgkQRSNfnvhwieydoQ//aRS9opnP
ZvPkOsaN6xPfUdNTov/TzndlQl48qvzI+RNGk97xgXMJrP5vfGaWJZZX2/p37nFS
fEY/5G0m5zheZdFswn09Jr2+uSQfAe8FFjdwx5o1RluRTPrvRYyW0yX37uyu9Hpg
NhYgeBjeCfaKPr68LTIYU4AA+pSon+uEv/+G1i1DSHpkbXLokkAzJhi3EkrVRmNQ
HyVYU1can+HJj2ihsmG9niTo3c4DRxDtOWDOLMCTwwESmOsXAUuceYSK+vCHG6cJ
kRb0kSxDgyNeVi4Kj8TrgemDpgdm6vFx7WJOdGXhs/4kOF21zuBtQd04viYIHidC
X9IY9IehnDqxny3wqqDZVn4/R6aGxSzvLuRFNFPxljaOoJRoF60amt5Z0SVZavka
fJZbeeokBzaXMwIZzKkK+xzsRdSKdXXyazVx/M0WXsZLkq7TBePbN8s8x3ZnhJoE
aBiv/VOj7zy0jCAX/dsYkjvEFN5NEfRbRcLYzUWBkSzHntFnFKwNXslZvU3svaBx
cndjUBpK0K4A0Mg2OrpSgohwRNZaDyBUJdD6ebh1WMpo77EPYUIT+EWE0qwyGGY9
l3DErYmLzgSBj9mTwXLuGIuCX+GRNcPiXtWIaWo7fZkPN/4/2EVWUjnXEBiLby2d
V1OP23NrK4U0SLZjjZ/xWklYJ/kLzjsc4365Ag0EWeXolAEQAL+uRp27z17N63eO
FySBvP+oDBmnaJeV6wZJkne1xmGRxidlcc+xk4VG0Zqt/AGB9aI2HzG47alBv/4V
GkoHvYYZKCMUrVm6tB6/EwgjuxIIPApk7+kf9Z7H3Ehn8ipRvb1dwe+9sjoHmucC
CEEyyvPClV9isGGDAwR1mjdWfvOei5sNAmJaVgaFXh5gcfWpMwvozzst5hTs5C+1
IT6nuPQOkZ2r2kz6d3aO6AmnFRYWefNzecH0wt0J22Qk4r635V+vljxrOC2KvfHW
eZB5U6lIUAe75NfF6iGsOo0J47pCoTLrDWtjoj8XOWlO5T5RrpqneYL8AIVuozar
FuAkq9mcAQhM627YbjV6Dco9dvnuKnuzG8IXppTyTNZGy7CwGau2wF4ksx5qF8hb
tVPZn4Xblwl67OHDgf9VaxXrmp7ja4E3BfhisSfX6uh7gu2TtZdowplKmAD0acib
gvTqEbKIraHSBtA38GJxlh06r4h9jshQk0+srKMGF5l0qPdTouDanHudmVcQTeyQ
fNQcFHeY8/0QuUlGXH1ZwfiVZuzWrsFFHyiO4vDFTYoer+BBsCoNEJ7qnft1SD6l
Fcv1XTNCYJ9PRWRW+nGOXLCvqpzcqY9eH42t9MPrmoba/LuifzLvUZ56ijktSA/2
+0ziQpygAl9M1zVZHqMq7hn8SvHJABEBAAGJAiUEGAEIAA8FAlnl6JQCGwwFCQlm
AYAACgkQRSNfnvhwiezzExAAicYn/ZZlb1XXIQBTDdZFHywbZsmvVqWKo+XYgDh2
fxd7JwhCAP0v3g4sINZ/n+KDJcyUCkSPm8aZ+833spMTj0e+ww98JZDn8kPTG6fg
9rJgPV2EruCcYK78Qn5WfOcHBTpXJ6aERF3OVp723VyGJxGy9oFZz6UkPwa6eruv
EY3TzblDARDzLg76I1/3YrjFKBQ3ISCmsbyZr/8k+7U8vJJWZSSz6UlMZmAHKHU3
Vy+AGHzy8ET9FlISH0I2MJGsJEpDlaDPHhKn3lfWHKM+rESFdptrqk0eomfFBeAE
JQ+RMUFiRLINHkhjFe+GFkhK5lUwc7afJSBOWzr5U6nDbUPf5iNsYhQ5/JaR6laY
9RqkVoyhmvKbo2xrfyDylbPivQehgfN81e37+Mesn/8wwVAd2GETm20q43NxcQ6K
lwX98oTtseKviPVCfi5Xd4FIpVauBM+TgzF5/C7Bu06onJfYm7oyyudPr2M+BUcK
3RMFEMDdRZCVWdMb7U3kVAGCB1CGVOrRUw5khEG7Np3j47kY9gzVdhz4I+Nla39U
zoAuXJl1IyENXrpPKj72nvj/RM7FUPPcIiv2zHVaaWBB88EUWUVcF8crjMJ7UEw2
r5peE4DdrF0nuyUuxNl3PE6Hkr/GgkdKtaU6wZUJzolwGw9rJWj2UwwPXEhcM3Vz
KqY=
=BSFG
-----END PGP PUBLIC KEY BLOCK-----

**Comment by v0l** [comment]
@ripcurlx Its closed on the UI

@sqrrm Do you want a specific date range? Maybe when the mediation was accepted or something?

**Comment by sqrrm** [comment]
If you're the maker, it would be best with logs from when the offer was created so all txs that are part of the trade are included. Otherwise from when you took the offer.

**Comment by v0l** [comment]
Already send, you may need to check your trash folder on gmail..

**Comment by ripcurlx** [comment]
@v0l Was this issue for you solved already?

**Comment by v0l** [comment]
Not that i know of
