### ISSUE TITLE
can't confirm payment receipt... error

### ISSUE THREAD

**Issue by ezeboog** [bisq-network/bisq#3520]
### Description

An error occurred at task: SellerSignAndFinalizePayoutTx
Exception message: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@294ae5f2, [B@45bfd45a, [B@29f9de07]

#### Version

v1.2.1

### Actual behaviour

I've tried multiple times and when I click to confirm payment receipt I immediately get the error pop up described above

#### Device or machine

windows 10

**Comment by avomuc** [comment]
Same Error. Someone have the solution?

**Comment by ezeboog** [comment]
[
[bisqlogfile.txt](https://github.com/bisq-network/bisq/files/3790290/bisqlogfile.txt)
](url)

**Comment by freimair** [comment]
seems to be a duplicate of #3528, #3517 and #3398

**Comment by ezeboog** [comment]
I don’t know what you mean duplicate? I heard from my buyer and they told me my sold bitcoin shows confirmed on their end but on my end I’m still unable to close trade as it won’t let me get past “confirm payment receipt”

Sent from my iPhone

On Oct 31, 2019, at 6:16 AM, Florian Reimair <notifications@github.com> wrote:

﻿

seems to be a duplicate of #3528<https://github.com/bisq-network/bisq/issues/3528>, #3517<https://github.com/bisq-network/bisq/issues/3517> and #3398<https://github.com/bisq-network/bisq/issues/3398>

**Comment by chimp1984** [comment]
I investigated the case. The traders started the trade with the old protocol (pre 1.2) and then updated, which is not supported. The old arbitrator need to do a manual payout with the trader.

**Comment by ripcurlx** [comment]
Closing as of https://github.com/bisq-network/bisq/issues/3520#issuecomment-566316103

**Comment by ezeboog** [comment]
I still have locked funds from a failed trade. I've opened support tickets, done everything the arbitrator on keybase has asked and nothing has been resolved. It's been nearly two months. Please unlock my funds and manually close the trade.
