### ISSUE TITLE
accepting offer to buy BTC vs. EURO SEPA bug

### ISSUE THREAD

**Issue by haukehess** [bisq-network/bisq#3530]
### Description

after clicking "accept offer", a dialog informs me that no account is set up for the payment method

#### Version

1.21

### Steps to reproduce

start bisq
accept SEPA offer
bug

### Expected behaviour

see trade details, enter amount, go

### Actual behaviour

error dialog

#### Device or machine

macbook macos 
![bisq-error](https://user-images.githubusercontent.com/39943892/67927260-6fd07f00-fbb8-11e9-80f3-9c356e8cceaf.png)
[bisq Kopie.txt](https://github.com/bisq-network/bisq/files/3792592/bisq.Kopie.txt)

catalina

**Comment by freimair** [comment]
sorry but I have to ask: you do have a sepa account configured?

if so, what is the account age of your sepa account?

**Comment by haukehess** [comment]
yes, I have a sepa account configured. It had three successful transactions
on it and was a couple of days old, but as it didn't work with 1.21, I
deleted it to start over from zero. Shouldn't be a problem as signing takes
30 days anyway...

**Comment by ExPrgrmmr** [comment]
Same bug here. I couldn't take a particular offer but other offers worked. Occured first time after v1.2.

**Comment by ripcurlx** [comment]
@haukehess There was an error that caused this behavior. It should be fixed already a couple of versions ago. Feel free to re-open if you still have this problem.
