### ISSUE TITLE
Arbitration selection>languages insertion on <cursor down>

### ISSUE THREAD

**Issue by esques** [bisq-network/bisq#354]
Right now in the Arbitration selection>languages combo box 
if you press cursor down
you automatically get "Albanian" as a language. 
I suggest this to classify as an bug, independent from #112 as it is rather confusing and remove keyboard events until #112 is implemented

**Comment by ManfredKarrer** [comment]
Ah ok, thanks. It the arrow down, right whcih causes selection.

**Comment by esques** [comment]
exactly

**Comment by ripcurlx** [comment]
Closing this issue as there is no manual arbitrator selection available anymore in 0.9+.
