### ISSUE TITLE
Remove offer failed in 1.1.7 prior to upgrade

### ISSUE THREAD

**Issue by microlancer** [bisq-network/bisq#3541]
### Description

I saw that the new version will require me to first close my open offers. So I tried to do this in the UI but got an error per the screenshot with only the text "Remove offer failed:" with no additional reason.

In the logs, I see:

```
Nov-01 21:38:11.538 [JavaFX Application Thread] ERROR b.c.o.OpenOfferManager: Add offer to P2P network failed. Please update to the latest Bisq version. A mandatory update was released which disables trading for old versions. Please check out the Bisq Forum for more information. 
Nov-01 21:38:15.842 [JavaFX Application Thread] ERROR b.d.m.p.o.OpenOffersView: Remove offer failed 
```

#### Version

1.1.7

### Steps to reproduce

I have an existing offer, and I am clicking the red "x" trash button to close the offer.

### Expected behaviour

The offer should be closed.

### Actual behaviour

I get an error message saying that "Remove offer failed: " with no explanation.

### Screenshots

![Screenshot from 2019-11-01 21-40-41](https://user-images.githubusercontent.com/869094/68066143-4dda1800-fcf0-11e9-8d0d-a0ec625c7479.png)

#### Device or machine

Ubuntu 18.04.3 LTS

**Comment by ripcurlx** [comment]
@thorie7912 Were you able to solve this issue? If not, please re-open this issue and I'll have a look at it.
