### ISSUE TITLE
Completed Trade Still In 'OPEN TRADES' Tab

### ISSUE THREAD

**Issue by niyid** [bisq-network/bisq#3543]
### Description

I have completed a trade and it is still showing up in **`OPEN TRADES`** tab.

#### Version

v1.2.0
### Steps to reproduce

1. Go to the **`BUY BTC`** tab and take an offer to sell BSQ.
2. Wait for trade to complete.

### Expected behaviour

On Completion, the trade should have moved to the **`HISTORY`** tab.

### Actual behaviour

The trade stays in the **`OPEN TRADES`** tab.
### Screenshots

![Screenshot from 2019-11-02 09-23-34](https://user-images.githubusercontent.com/20237127/68068424-dbe7ea00-fd54-11e9-86d5-8a0f04485acf.png)

#### Device or machine

Fedora 22

**Comment by niyid** [comment]
This issue appears to have been resolved on starting up again.

**Comment by chimp1984** [comment]
It is intended to give the user the chance to move the funds out to an external wallet (better privacy if users separate each trade).
