### ISSUE TITLE
Arbitration doesn't work as per bisq rules

### ISSUE THREAD

**Issue by spogulis** [bisq-network/bisq#3544]
### Description
I opened a support ticket on October 29 and added payment order as provided by my bank. Mediator responded with: "I will ask the seller".

The seller hasn't been online since he/she took my buy order. What is there to ask?

Anyway, it's been 5 days and someone else asked me what my version of Bisq was and warned not to upgrade, but the bug is that 2 days after mediation start it should automatically be escalated to arbitration, does it not?

#### Version
1.1.7

#### Additional info

Trade id: 54086613

**Comment by Bisq2People** [comment]
The update was a hard fork and most users including staff moved to 1.2 after a couple of days. This may happen every time the trading protocol is changed. Sad but true.

**Comment by ripcurlx** [comment]
@spogulis Was your issue already solved? It was during the protocol upgrade phase, which was the reason for not updating while having an open trade. If your issue haven't been resolved yet, please re-open this issue and I'll have a look.
