### ISSUE TITLE
0 peers behind a firewall

### ISSUE THREAD

**Issue by esques** [bisq-network/bisq#355]
Even if I have 8 TOR connections and see all the offers, sync with Mainnet does not work and peers are 0

**Comment by ManfredKarrer** [comment]
Which OS do you use? Do you have a firwall which blocks Bitcoin? If you restart it still is the same? If you had an earlier version installed, have you removed the data directory?

**Comment by esques** [comment]
1. Ubuntu
2. Yes I run a firewall that blocks Bitcoin, but I supposed it goes over TOR? 
3. where is the data dir?

**Comment by ManfredKarrer** [comment]
Ah ok then its the firewall...
No BitcoinJ is running in clearnet atm. It is planned for later to route it over Tor. It has a own Tor support but that need to be investigated and tested more before it will be considered to be used.
Also would like to prevent running 2 Tor instances, but use the existing used for the P2P network for BitcoinJ as well. 

Data dirs are here (https://github.com/bitsquare/bitsquare/wiki/Testing-Bitsquare-with-Mainnet):
Mac OSX: /Users/user/Library/Application Support/Bitsquare/bitsquare.log
Linux: /home/user/.local/share/Bitsquare/bitsquare.log
Windows XP: C:\Documents and Settings\username\Application Data\Bitsquare\bitsquare.log
Windows Vista or 7: %appdata%/Bitsquare/bitsquare.log
