### ISSUE TITLE
Run BitcoinJ over JTorProxy

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#357]
We run BitcoinJ over Tor with its built in Tor support (Orchid). As we use a native Tor instance for the P2P network it would be better to route BitcoinJ over our jTorProxy. 
BitcoinJ uses nio (netty) which does not provide an API for sockets, so that might be difficult to get it working with Socks5Proxy. But it also supports a non nio BlockingClientManager which is also used for when BitcoinJ run over Tor. 
We would need to pass our socket (or socketFactory) to a BlockingClientManager.
We maintain our own fork (https://github.com/bitsquare/bitcoinj) of BitcoinJ so changes should be added there.

**Comment by esques** [comment]
like!

**Comment by ManfredKarrer** [comment]
Done.
