### ISSUE TITLE
Security deposit doesn't work as intended

### ISSUE THREAD

**Issue by spogulis** [bisq-network/bisq#3571]
### Description

When trying to buy Bitcoin amount 0.01 and setting the security deposit to 5%, the security deposit doesn't change (stays at 0.001 BTC or 10% of the amount). When increasing the buying amount to 0.02 BTC, the deposit amount is is 0.001 BTC.

I always left for all transactions on Bisq 0.001 BTC for security deposit but after update to v.1.2.2 can no longer make a buy order due to the security amount. Decreasing amount of BTC to buy doesn't decrease the security deposit amount, so this is a bug.

#### Version

v.1.2.2

### Steps to reproduce

* Enter Bitcoin amount to buy: 0.01 BTC or lower
* Set security deposit to 5%
* Hover on info button of the security deposit to see that the BTC amount of security deposit is, in fact, 10%.

### Expected behaviour

On buy order of 0.01 BTC with 5% security deposit amount the security deposit should be 0.0005 BTC + fees.

### Actual behaviour

The deposit is 0.001 BTC + fees.

#### Device or machine

Windows 10 PC

**Comment by ripcurlx** [comment]
@spogulis Sorry for the late reply! This is caused by the minimum security deposit that is applied for this trade. The UI was changed in v1.2.5 so it is shown during offer creation if the min. security deposit is used. Closing as complete.
