### ISSUE TITLE
SignMediatedPayoutTx Trade.getDepositTx()must not be null

### ISSUE THREAD

**Issue by maurobeltran** [bisq-network/bisq#3579]
### Description

After a mediation where the transaction was not published and was solved returning the funds I receive this error when I try to sign the transaction accepting the mediation.

#### Version

V1.2.2

### Steps to reproduce

Every time I accept the mediation

### Expected behaviour

Unlock the funds and finish the mediation

### Actual behaviour

Error and the impossibility to unlock the funds

### Screenshots

![image](https://user-images.githubusercontent.com/57514423/68447375-b5d7a500-01ad-11ea-8f40-46eb5dd14265.png)

![image](https://user-images.githubusercontent.com/57514423/68447386-c4be5780-01ad-11ea-9193-eab518435c1e.png)

#### Device or machine

Win10 HP OMEN Laptop

#### Additional info

[Log.txt](https://github.com/bisq-network/bisq/files/3822875/Log.txt)

**Comment by ripcurlx** [comment]
@maurobeltran Are you still stuck in this state with the latest version?

**Comment by maurobeltran** [comment]
No, sir, I havent this error for a while
