### ISSUE TITLE
Give option to disable standby/sleep/hibernate mode

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#358]
As the offerer should stay connected to be able to execute take offer requests we want a way to avoid sleep mode.
We could offer 3 options:
- Prevent always OS to go into standby
  -Prevent OS to go into standby when you have an offer open
- Never prevent OS from sleep mode

Here are some links to the topic:
Mac:
https://github.com/newmarcel/KeepingYouAwake
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/caffeinate.8.html
https://bitbucket.org/xnejp03/serviio/issues/631/prevent-sleep-during-serviio-execution-in
https://stackoverflow.com/questions/52874/how-do-you-keep-the-machine-awake/53276#53276

Windows:
http://nipon.blog.com/2011/10/05/java-how-to-detect-windows-stand-by-sleep-mode/
https://bitbucket.org/xnejp03/serviio/issues/241/option-to-disable-machine-going-to-sleep
https://github.com/ps3mediaserver/ps3mediaserver/blob/master/src/main/java/net/pms/io/WinUtils.java
http://www.codeguru.com/cpp/w-p/system/messagehandling/article.php/c6907/JavaC-PC-Standby-Detect-and-Prevent.htm

**Comment by haiqu** [comment]
In Windows this is configurable via the `Control Panel -> Power Options` settings. User problem, not needed.

For Linux and Mac I don't know.

**Comment by haiqu** [comment]
See also #351

**Comment by ManfredKarrer** [comment]
Close as it is probably fixed with the playing of an inaudible sound.
