### ISSUE TITLE
Payment account age not known

### ISSUE THREAD

**Issue by darosior** [bisq-network/bisq#3589]
### Description

I cant see my account age anymore, nor my trading's peer one, after having upgraded to 0.2.3.

#### Version

1.2.3

### Steps to reproduce

Hover the little avatar in many of the pages.

#### Additional info

Might help you with the fix : I've a currently engaged trade and if I go to my portfolio and click on my trade ID, both my payment account age and my peer's one are shown next to our respective IBAN.

**Comment by ripcurlx** [comment]
That will be released in v1.2.4. Already merged to master: https://github.com/bisq-network/bisq/pull/3580

**Comment by darosior** [comment]
Thanks!
