### ISSUE TITLE
Support sell/buy Bitcoin through products/services online

### ISSUE THREAD

**Issue by HostFat** [bisq-network/bisq#359]
I've already suggested this on IRC, but I think that it can be good to write it here to make it easy to remember :)

A good example of this kind o possibility is https://purse.io
Or the defunct Brawker (some videos https://www.youtube.com/channel/UCaZ6K9lv-olWe0mV-5u1F9w )

The idea is to connect the different interests of two users and accomplish both.

An user A will want to buy "something" with his bitcoins (a services or a product)
He will need to compile a form with these informations:
- URL of the product/service (ex: http://store.steampowered.com/app/262120)
- Currency showed on the website link (ex: USD)
- Cost of the product/service (in the specified currency, ex $14.99) 
- Current price of the bitcoin in the specified currency (ex: 416.03    USD)
- Discount preferred by the user (A) (ex: 20%)
- Some more instructions before the acceptance
- Some more instructions after the acceptance
- Possible more contact informations

The user B wants to buy Bitcoin with credit/debit card (or a coupon ...), and find the request of user A on Bitsquare.
He will be able to see:
- The price ($14.99)
- Discount preferred by the user A (ex: 20%)
- The price of the bitcoin chosen by user A 416.03  USD
- How many bitcoins he will receive ( 1 / 416.03 \* 14.99 \* 0.80 = 0.02882484 BTC)
- A part of the url (ex: http://store.steampowered.com/xxxxxx)
- Some more instructions before the acceptance

User B will accept

User A will look at the profile of user B and will choose to accept or not (now for the example he will accept)

Bitsquare will ask to user A to depost the 0.02882484 BTC on the escrow/arbiter address

User B, after the User A acceptance will also see:
- Some more instructions after the acceptance
- Possible more contact informations
  User B will wait to see the depost of Bitcoin and then will buy the product/service requested by user A.

After user A will receive the product/service (after few minutes or days), than he will unlock the bitcoins to user B.

There can be even another step, where user(s) B will say that he will buy the product/service not for 20% of discount but for less (ex 15%)
User A will be able to see many different proposals from different users, and will choose which one he prefers.

This is just an idea, it can be improved for sure ;)

**Comment by ManfredKarrer** [comment]
Thanks for writing it down here! I see also many apps which can be built on top of the basic infrastructure (p2p network) of Bitsquare.

**Comment by bitcoinuser** [comment]
I think this should be implemented as soon as possible. Tomorrow I'll try to explain why on bitsquare forum.

**Comment by HostFat** [comment]
Good, maybe you can also add a direct link to this issue :)

**Comment by ManfredKarrer** [comment]
I close it here as you added it already to the forum (want to keep GH more for bugs, concrete dev features)
