### ISSUE TITLE
Account signing security

### ISSUE THREAD

**Issue by ExPrgrmmr** [bisq-network/bisq#3590]
(Split/rewritten issue)

With _account signing_ anybody virtually gets trusted from simply trading with a signed user. This adds  no protection since no real proof-of-trust is delivered upon signing. A scammer/malignant joining the signed network can always start his agenda. The account signing model should therefore be questioned. One minor benefit though is that a new account's aging can't be triggered by a single self-trade.

Note that scamming does not imply a stolen bank account. Scamming is done with an owned bank account.

https://github.com/bisq-network/proposals/issues/93

https://bisq.community/t/false-security/8691

**Comment by chimp1984** [comment]
Did you read and understood the concept? Does not sound so from your comments....

**Comment by chimp1984** [comment]
> Total number of trades

That is the easiest to fake by doing self trades. Run 2 apps and trade with youself 1000 times... Serves zero for security.

**Comment by ExPrgrmmr** [comment]
Didn't understand what? Please elaborate. Sure one could possibly trade with himself until the PoT goal i reached. Analogous with getting "signed"; where as the scammer owns **full control** over the situation. Don't you really see how weak this signed network is? It adds zero value only costs. You should add distributed KYC to make it reliable.

**Comment by ExPrgrmmr** [comment]
> > Total number of trades
> 
> That is the easiest to fake by doing self trades. Run 2 apps and trade with youself 1000 times... Serves zero for security.

It wouldn't work in 30 days if combined with per 0 months account age.

**Comment by ExPrgrmmr** [comment]
https://github.com/bisq-network/proposals/issues/133#issue-comment-box

https://github.com/bisq-network/bisq/issues/3581#issue-comment-box

**Comment by mpolavieja** [comment]
@ ExPrgrmmr  what you are proposing has been extensively discussed on several previous proposals.  I encourage you to please follow the guidelines to submit proposals, specially Step 0:

https://docs.bisq.network/proposals.html

> Step 0. Research
> 
> Before you submit a proposal, do your homework!
> 
> 1. Discuss your idea with other contributors to see if a proposal is worth submitting at all;
> 
> 2. Search through existing proposals (both open and closed) to see whether something similar has already been proposed;
> 
> 3. Notice which among those proposals have been accepted and rejected, and why;
> 
> 4. Read this document to fully understand the proposal process and guidelines.

**Comment by ExPrgrmmr** [comment]
Up to your organisation. I am for now not interested in doing that.

**Comment by mpolavieja** [comment]
Ok. I appreciate your transparency on this issue.  If you are not willing to follow the guidelines I trust that you will understand that your proposals will be mostly ignored and/or rejected.

**Comment by ExPrgrmmr** [comment]
OK. I don't see that I have any open proposals.

**Comment by mpolavieja** [comment]
Sorry, my bad.  I though this was on the proposal repository.

**Comment by ExPrgrmmr** [comment]
@freimair 
Hi,
There was some misunderstandings above.
You can label it as an investigation...

**Comment by chimp1984** [comment]
@ripcurlx @freimair 
Please close that issue. We don't want to pullute out Github repo with uninformed disucssions.

@ExPrgrmmr Please use the Forum for discussions and inform yourself better by studying the existing documentation before shouting out loud claims. Otherwise I categorize this behaviour as trolling.

**Comment by ExPrgrmmr** [comment]
@chimp1984 
I may understand why you have a problem with me. Sorry for my informal language sometimes.

**Comment by ExPrgrmmr** [comment]
**As a compromise account signing and proof-of-trust could be integrated together for stronger security. Proof-of-trust calculations then starts upon signing.**
