### ISSUE TITLE
UTXO combinations resulting in dust outputs

### ISSUE THREAD

**Issue by eigentsmis** [bisq-network/bisq#3592]
I came across the following error when trying to withdraw my security deposit to an external wallet after a successful trade.

<img width="601" alt="Screen Shot 2019-11-09 at 10 41 43 AM" src="https://user-images.githubusercontent.com/57468555/68547253-521bca80-03ad-11ea-9c2d-0bcca17afbb3.png">

The workaround for this was to send it first to my Bisq wallet and from there send it to my external wallet.

According to Manfred...."this is likely a bug in certain utxo combinations. fee estimation is tricky and can become an infinite task (we break after certain iterations) if utxos are unfortunate... e.g. if u add a input the size is bigger and require more fee, so u need to add another input -> can continue....dust outputs are not allowed so it can become a bit tricky. hard to test those edge cases but we should fix that issue..."

**Comment by ghost** [comment]
The error message box is misleading, its not a dust issue.  The security deposit has released back to the bisq wallet prematurely.   See #4205, and steps to reproduce the issue: https://github.com/bisq-network/bisq/issues/4205#issuecomment-629398073
