### ISSUE TITLE
*High* CPU usage with local bitcoind

### ISSUE THREAD

**Issue by darosior** [bisq-network/bisq#3593]
### Description

Bisq with local bitcoind consumes around 100-120% of CPU (`top` return), while it consumes 10 to 15% with a remote `bitcoind` (federation's ones if I don't make a mistake ?). 

#### Version

v1.2.3 but all prior were also affected.

### Steps to reproduce

Just try running Bisq with a local `bitcoind`.

**Comment by darosior** [comment]
Ok, even better since v1.2.3 I don't have any Bitcoin network peers using local `bitcoind` while I have some using federation's `bitcoind`

**Comment by tasoshi** [comment]
Same problem here while working with local bitcoind: around 150% cpu usage on average.

**Comment by darosior** [comment]
Ok so it seems to be related to "full" nodes: https://docs.bisq.network/dao-technical-overview.html#full-nodes. It might be that we Bisq starts as a "full" node by default if it detects a `bitcoind` runnning ?

**Comment by chimp1984** [comment]
@darosior No by default a Bisq node runs a lite node. You need extra configurations to run a full DAO node. At startup it syncs with past DAO blocks, that can take a while if the app was not used for a while. After the DAO sync is done CPU should go back to normal.

**Comment by chimp1984** [comment]
@darosior Is your local bitcoind node running in pruned mode? If you use latest bitcoind release, you need to enable bloomfilter support.

**Comment by darosior** [comment]
> After the DAO sync is done CPU should go back to normal.

I've used it for 3 months with CPU usage at 100%. With an approximate up time of 6 hours a day, I'd say it isn't due to initial sync. Moreover why would it take more CPU power with a local `bitcoind`

> Is your local bitcoind node running in pruned mode?

nop

> f you use latest bitcoind release, you need to enable bloomfilter support.

Will try, but why don't you use RPC for localhost's bitcoind ?

**Comment by chimp1984** [comment]
This is weird... Usually CPU is about 2-4% after initial sync. Seems some environments cause some issues.  Can you post info about your setup (OS, ram,...)? Do you run inside a VM?

**Comment by darosior** [comment]
Will edit with a `uname -a` but I run a Debian Buster with a 4.19 Kernel. No VM.
Edit: `4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux`

@tasoshi above runs a Ubuntu Bionic (don't know his Kernel though). No VM.

We have different setups, and same symptoms.

**Comment by darosior** [comment]
Here are some logs, it seems to be continuously trying to connect:
```
Dec-02 12:08:16.240 [AbstractTimeoutHandler timeouts] INFO  o.b.c.PeerGroup: [127.0.1.1]:8333: Peer died      (0 connected, 0 pending, 1 max)
Dec-02 12:08:16.241 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Peer discovery took 5.373 μs and returned 0 items
Dec-02 12:08:16.241 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Waiting 114740 msec before next connect attempt to [127.0.0.1]:8333
Dec-02 12:08:50.064 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: Num of latestLivePeers=8
Dec-02 12:08:59.619 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: We have 11 connections open. Our limit is 12
Dec-02 12:10:10.981 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [127.0.0.1]:8333     (0 connected, 1 pending, 1 max)
Dec-02 12:10:10.982 [NioClientManager] INFO  o.b.n.NioClientManager: Connected to /127.0.0.1:8333
Dec-02 12:10:10.982 [NioClientManager] INFO  o.b.core.Peer: Announcing to /127.0.0.1:8333 as: /bitcoinj:0.14.7.bisq.1-SNAPSHOT/Bisq:1.2.3/
Dec-02 12:10:14.446 [JavaFX Application Thread] INFO  b.c.d.s.DaoStateService: New Block added at blockHeight 606298
Dec-02 12:10:14.447 [JavaFX Application Thread] INFO  b.c.d.n.p.BlockParser: Parsing 0 transactions at block height 606298 took 0 ms
Dec-02 12:10:14.447 [JavaFX Application Thread] INFO  b.c.d.s.DaoStateService: Parse block completed: Block height 606298, 0 BSQ transactions.
Dec-02 12:10:15.982 [AbstractTimeoutHandler timeouts] INFO  o.b.c.PeerSocketHandler: [127.0.0.1]:8333: Timed out
Dec-02 12:10:15.982 [AbstractTimeoutHandler timeouts] INFO  o.b.c.PeerGroup: [127.0.0.1]:8333: Peer died      (0 connected, 0 pending, 1 max)
Dec-02 12:10:15.982 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Peer discovery took 7.079 μs and returned 0 items
Dec-02 12:10:15.982 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Waiting 10004 msec before next connect attempt to [127.0.1.1]:8333
Dec-02 12:10:18.439 [JavaFX Application Thread] INFO  b.c.b.w.BsqWalletService: updateBsqBalance took 15 ms
Dec-02 12:10:25.987 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [127.0.1.1]:8333     (0 connected, 1 pending, 1 max)
Dec-02 12:10:25.987 [NioClientManager] INFO  o.b.n.NioClientManager: Connected to darosior/127.0.1.1:8333
Dec-02 12:10:25.987 [NioClientManager] INFO  o.b.core.Peer: Announcing to darosior/127.0.1.1:8333 as: /bitcoinj:0.14.7.bisq.1-SNAPSHOT/Bisq:1.2.3/
Dec-02 12:10:30.987 [AbstractTimeoutHandler timeouts] INFO  o.b.c.PeerSocketHandler: [127.0.1.1]:8333: Timed out
Dec-02 12:10:30.988 [AbstractTimeoutHandler timeouts] INFO  o.b.c.PeerGroup: [127.0.1.1]:8333: Peer died      (0 connected, 0 pending, 1 max)
```

**Comment by darosior** [comment]
Ok, that was the bloom filters apparently........ Thanks @chimp1984 !

**Comment by chimp1984** [comment]
@darosior Did you use latest bitcoind where bloom filters are not supported by default? Or otherwise can you specify what was the issue?
