### ISSUE TITLE
Solve issue with BitcoinJ dependency for pkgbuild Arch Linux

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#360]
See:
https://aur.archlinux.org/packages/bitsquare-git/?comments=all

We need to either put the jars into the maven project or deploy the bitcoinJ fork to a maven repository.
I tried both initially but ha some issues, thats why it is using that un desirable solution with a local build of the BitcoinJ fork.
I would appreciate if any Maven geek can help out. I have so much othere things on my TODO list....

**Comment by ManfredKarrer** [comment]
There will probably more difficulties to get pkgbuild for Arch Linux working:
See the [Enable unlimited Strength for cryptographic keys](https://github.com/bitsquare/bitsquare/blob/master/doc/build.md#7-enable-unlimited-strength-for-cryptographic-keys) issue.

**Comment by dmp1ce** [comment]
Referencing #451 to hopefully help me make some progress with the PKGBUILD.

**Comment by dmp1ce** [comment]
I was able to setup a temporary local maven repository during the Arch PKGBUILD process. I didn't need to do any of the prerequisites in the build notes.

I'm not sure if this will cause a problem at runtime but the application seems to be starting up OK.

**Comment by ManfredKarrer** [comment]
Ah cool. The prerequisites are needed as otherwise there are issues at runtime.

**Comment by dmp1ce** [comment]
Step 2 says "You will get an error when building Bitsquare package if you don't have these." I did not notice an error.

For steps 3 and 4, how can I verify that the steps have been completed correctly? I didn't get a "JCE cannot authenticate the provider BC" exception when I started bitsquare.

**Comment by ManfredKarrer** [comment]
I added some reflection code to get around those nasty issues, but even with that I got bug reports if the setup was not correct. Did not had time to investigate further but wanted to be sure to have all setup like it should be without relying on the workaround hacks.

**Comment by dmp1ce** [comment]
Can I turn the reflection code off to test the package I'm building? I'm not exactly sure how I can do the steps 2-4 as a PKGBUILD. Maybe it is best to keep the hacks in place because the application seems to work fine for me.

**Comment by ManfredKarrer** [comment]
The reflection code is in BitsquareApp:
if (Utilities.isRestrictedCryptography())
            Utilities.removeCryptographyRestrictions();

The part of copying the Oracle security jar files can be omitted with the reflection hack (or if u use OpenJDK as I assume its not needed at all) but the BouncyCastleProvider jar files and adding BouncyCastleProvider to the jre\lib\security\java.security file is required IMO. I am not completely sure what happened if BouncyCastleProvider is not added. Maybe it fall back to the default provider. If so I am not sure if there might be incompatibilities with other nodes then...  

There is an encryption test at startup, which should display a popup if anything is wrong.
A further test is to try to take an offer (without really taking it, just click on take offer). There a msg gets encrypted and if you receive a offer is available msg back, encryption works with that peer.

I got strange issues reported with all that topics so I was not sure if the reflection hack is sufficient and works for all systems so to be safe I compile with all that steps described in the build file.

**Comment by dmp1ce** [comment]
Arch is compiling with [java-openjfx](https://www.archlinux.org/packages/extra/x86_64/java-openjfx/), so I assume I'll not need to add the security jar.

I'll test taking an offer.

I believe I can set the `security.provider.<n>=<className>` on the command line with `-Dsecurity.provider.11=org.bouncycastle.jce.provider.BouncyCastleProvider`.

Do you think that would work?

**Comment by ManfredKarrer** [comment]
Yes to use the command line should work as well. So the BouncyCastleProvider jar is the only missing part then.
Thanks a lot for working on that!

**Comment by dmp1ce** [comment]
Installing BouncyCastleProvider jar is easy enough.

One thing I need to clarify, do steps 3 and 4 need to be done before building? I'm not sure how I can do that, if that is the case.

**Comment by dmp1ce** [comment]
Sorry, I haven't actually used the software yet, so bear with me. I create an Ethereum crypto account. Then I clicked on two "Sell bitcon" buttons. One of them said that the offer was offline. The other one allowed me to click "Next step". I didn't see any errors in the terminal that concerned me.

Can we assume BouncyCastle is working?

**Comment by ManfredKarrer** [comment]
I think the steps 3 and 4 are required at runtime, so not needed at compile time (though not 100% sure).

Yes if you are able to click "next" it seems fine. Did it work without adding BouncyCastle?
If so it prob. use the default provider. I am not 100% sure if that can cause issues, though it should not.

**Comment by ivilata** [comment]
In Debian Sid the only prerequisites that I actually had to build Bitsquare were installing packages `openjdk-8-jdk`, `openjfx` and `maven`, i.e. no Oracle JDK, no steps for unlimited crypto, no special steps for Bouncy Castle.

Then I just cloned the Git repos, built and installed the customized BitcoinJ, then packaged Bitsquare, as indicated under _Steps_ in the build doc.  All Bouncy Castle stuff seemed to be automatically downloaded and added into the resulting jar.

I copied the jar to a newly installed Ubuntu 15.10 machine with no Java.  I only needed to install `openjdk-8-jre` and `openjfx` (`libopenjfx-java` wasn't enough) to be able to run Bitsquare with `java -jar JARFILE`.

I don't know what the differences are between Arch's and Debian/Ubuntu's versions of OpenJDK and OpenJFX, but I hope this can help you better figure dependencies out.

**Comment by dmp1ce** [comment]
@ivilata Arch installed the same way, but I didn't want to have any incompatibilities with other nodes because BouncyCastle was not installed correctly. Perhaps I should remove the extra code in the PKGBUILD for BouncyCastle. I'm not sure, but things seem to be working now.

Here is the PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bitsquare-git

**Comment by ivilata** [comment]
@dmp1ce Very nice work! I'm not very familiar with Arch but the instructions seem right to me.

Regarding BouncyCastle, you can check if your installed jar file contains BouncyCastle classes by executing `unzip -l /usr/share/java/bitsquare/shaded.jar | grep org/bouncycastle`. It should show a bunch of lines.  If it's missing the app is simply unable to encrypt and decrypt messages, so booting it, in case it doesn't crash straight away, wouldn't allow you to exchange direct messages with other peers.

@ManfredKarrer, is there any simple way to trigger these crypto operations from the GUI, to check if BouncyCastle is working properly?

**Comment by ManfredKarrer** [comment]
@ivilata I added a check at the startup. I just did not had time to do a test to be 100% sure if it all works as expected. I got strange error reports regarding that issues, even it seems for my setup to be all ok. So that I required that strict rules at the build doc. If anyone has the time to test that on diff. OS and with a java installation without those setup applied and see if the reflection based approach will work for all OS, as well as there are no issues with BouncyCastle, would be nice. I cannot do that atm as there is too much other stuff to do.
So my recommendation is to follow the steps exactly as described, that is used in the current binaries and at least in the current version I did not got any error reports.

**Comment by ivilata** [comment]
@ManfredKarrer The setup I've been using from the beginning is based on Debian with OpenJDK and OpenJFX, and I'm using Maven there to build the jar that I run afterwards (which contains BC classes).  In this setup, I've never copied the BC jar to the system's library nor manually configured the list of security providers, and I've been using Bitsquare normally without encryption issues.  I've also copied the jar to another Linux machine with a clean OpenJDK JRE with no Maven repo and it also seems to work.  That's why I suspect that this may be the case for other Linux packages built with the same combination of tools, but I haven't tested under other platforms.  However, if that was the case under Arch, then contributed packages may be made a little simpler and easier to maintain.`;)`

**Comment by ManfredKarrer** [comment]
@ivilata Yes probably it works like that. I was just surprised by repeated bug reports, thats why I tried to be as strict with that issue as possible (there is still one open with the 0.4.6 version but I did nto get any reply with more details from the reporter, so not sure whats the reason).

**Comment by ManfredKarrer** [comment]
Is completed (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bitsquare-git)
