### ISSUE TITLE
Modified arbitrator payout mechanism

### ISSUE THREAD

**Issue by ExPrgrmmr** [bisq-network/bisq#3603]
**Due to severe concerns regarding the new trade protocol and donation address holder.**

**Fully automate the trade protocol.**

Instead of confiscating and sending funds to a BTC donation address the funds are sent to a special holding address that is spendable to the trading parties only by the application via the arbitrator. The application is checking that the payee and arbitrator is not the same trader.

The application use safe contracts. Where handels are checked so that the arbitrator cannot trade with himself.

Steps
1. Generate one handle per application instance
2. Broadcast this handle on trading and arbitation with metadata (role, trade id)
3. If only 2 different handles to contract -> cheeting arbitrator
4. If 3 different handles -> ok
5. If ok arrange contract pair

@clearwater-trust 
@mpolavieja 
@sqrrm 
@m52go 
@MwithM
@chimp1984 
@ManfredKarrer 

https://github.com/bisq-network/proposals/issues/135

**Comment by MwithM** [comment]
Applications can't know who a person is. This makes no sense.

**Comment by ExPrgrmmr** [comment]
No. You have some kind of key or id associated with users.. How else can mediation work, it knows who are who. I understand you want your agenda and proposal...

**Comment by ExPrgrmmr** [comment]
@MwithM @ManfredKarrer 
OK. Let's say there is a problem. Wasn't it the same problem with the 2-of-3 multisig? I guess it wasn't for that reason it was abandoned.

**Comment by ExPrgrmmr** [comment]
> Applications can't know who a person is. This makes no sense.

@MwithM @ManfredKarrer 
The application manages two contracts, one per trader, that is checking the payout by urging that the payout is confirmed by the payee. Keys/id's is checked to not be used two times by the arbitrator.

**Comment by xbyvee** [comment]
> Rubbish. There are keys/id's associated with users. Bisq can distinguish them. I understand you want your proposal instead.

A malicious arbitrator isn't limited to using just one set of keys / addresses etc.. They can just fire up a completely seperate Bisq app in seconds with a different private key and different addresses and run as many "traders" as they like. 

This idea will never work. The new 2 of 2 system in 1.2 is fine, it just needs multi-sig on the donation address holder like has been suggested by others and a clear process for making sure some of the keyholders in that role are known.

**Comment by ExPrgrmmr** [comment]
> malicious arbitrator isn't limited to using just one set of keys / addresses etc.. They can just fire up a completely seperate Bisq app in seconds with a different private key and different addresses and run as many "traders" as they like.

Multiple instances of Bisq can be run by the arbitrator yes. It would only have a copy of the contracts and handles in the contracts. These are checked to be of a valid combination with the arbitrator handles. So it will work. It is pure software. Don't mix this up with Bitcoin transactions.

Trader1 <-> arbitrator1
Trader2 <-> arbitrator1

**Comment by ExPrgrmmr** [comment]
@xbyvee 
Corrected some text. Agree now?

**Comment by xbyvee** [comment]
If the arbitrator has the ability to only pay out to one of the trading parties, but can choose which trading party to pay out to it means they can on another instance of Bisq trade with someone and never pay them an altcoin and then use their power as arbitrator to pay themselves the BTC from that trade. This is a completely unavoidable situation and something that isn't possible to solve short of burning the BTC from trades that haven't been signed by both traders.

**Comment by ExPrgrmmr** [comment]
Agree. This obvious risk must have been overseen. By implementing the arbitration protocol in software as I suggest in this issue these things can be taken care of programmatically.

**Comment by xbyvee** [comment]
These things can't be taken care of programatically. As long as the arbitrator gets a say in who the payout goes to there is an incentive for them to act maliciously. It doesn't matter how much you code for this it's not something that can be fixed because at the end of the day someone needs a key that has authority to do something.

**Comment by ExPrgrmmr** [comment]
It is like you say. One can choose to live with it. But v1.2...

**Comment by ExPrgrmmr** [comment]
In the end one needs to trust a human.

**Comment by ExPrgrmmr** [comment]
@xbyvee 
Edited again.

**Comment by ExPrgrmmr** [comment]
1. Generate one handle per application instance
2. Broadcast this handle on trading and arbitation with metadata (role, trade id)
3. If only 2 different handles in contract -> cheeting arbitrator
4. If 3 different handles -> ok
5. If ok arrange contract pair

**Comment by xbyvee** [comment]
it doesn't make sense... for one Bisq does have something like "handles" - onion adresses.  A dishonest arbitrator would just run multiple instances to get around that.

**Comment by ExPrgrmmr** [comment]
It is only broadcasted data from the application.

**Comment by ExPrgrmmr** [comment]
How are you? Ok?

**Comment by chimp1984** [comment]
> How are you? Ok?

I am getting pretty annoyed by your totally pointless posts and proposal.

@mpolavieja Please close that proposal. It makes no sense as most of his other posts.

**Comment by ExPrgrmmr** [comment]
It is an issue. If it matters?

**Comment by bisq-github-admin-3** [comment]
@ExPrgrmmr As I got approached by multiple contributors that you are not following our proposal guidelines, not reading through existing discussions, opening up the same discussions about the same topics again and again and polluting GitHub notifications by tagging multiple contributors to grab their attention I was forced to block you temporarily from the Bisq GitHub organization. This is a first for us and I'm sorry to be forced to take this action.
