### ISSUE TITLE
no payout possible. some mistakes!!

### ISSUE THREAD

**Issue by Forstmann88** [bisq-network/bisq#3606]
Good evening,
with me come various error messages.
Among other things, my payout of yesterday gets no peer confirmation and hangs.

could you please give me additional help?

![Fehlermeldung_2](https://user-images.githubusercontent.com/57730987/68805737-af8d7100-0664-11ea-916c-ad6c49a6a1bb.png)

![Fehlermeldung_1](https://user-images.githubusercontent.com/57730987/68805779-c59b3180-0664-11ea-83da-06f5a404c962.png)

**Comment by ripcurlx** [comment]
Related to #3306. Please join #support at https://keybase.io/team/bisq as this error is under heavy investigation right now and every additional log file helps solving this issue.

**Comment by ripcurlx** [comment]
@Forstmann88 Was your issue solved? If not please re-open this issue. Thanks!
