### ISSUE TITLE
expected miner fees

### ISSUE THREAD

**Issue by ulrichard** [bisq-network/bisq#362]
When I fund an offer using electrum with the dynamic fees slider in the middle, it adds a miner fee that bitsquare thinks is too low. 
It shows the attached warning, switches to the funds tab, and cancels my offer. My only option is to send the funds back to my wallet, and send the funds again with a manually set, higher fee.
Why does bitsquare insist on a certain fee without clearly communicating this beforehand?

**Comment by ulrichard** [comment]
![bildschirmfoto vom 2016-03-03 09 33 00](https://cloud.githubusercontent.com/assets/1116405/13489105/56d4cd28-e125-11e5-88ab-b3031b1c702c.png)

**Comment by ManfredKarrer** [comment]
I know thats a nasty issue. Unfortunately to have too low mining fees will cause difficult to handle issues later in the trade. All the transactions are chaines so if the first funding tx has a too low mining fee and not gets into te blockchain the trade desposit tx also gets delayed. Every trade has a max. trade period attached, for OKPay or altcoins thats 1 day and might be even less in future. If a funding tx needs more then 1 day to get into the blockchain it would trigger a dispute and the other trading peer loses time where his funds are blocked.
That is why we require a min. fee of 0.0002 BTC. It will be communicated more clearly in the upcoming release.

**Comment by ulrichard** [comment]
This specific tx took 43 minutes for inclusion.
But yes, communicating the requirement beforehand will be good.

**Comment by ManfredKarrer** [comment]
Yes usually a fee above 0.0001 should be ok as well, but i have observed cases where it took quite long.... I will close the issue as it will be resolved in the next release (hopefully deployed soon). If you have nay othere comments feel free to add...

**Comment by ManfredKarrer** [comment]
FYI: here is the screenshot of the new version (still WIP)...
![bildschirmfoto 2016-03-03 um 10 52 58](https://cloud.githubusercontent.com/assets/1449498/13490606/05bed86c-e12e-11e5-8c86-4c0a35843adf.png)
