### ISSUE TITLE
Need to press ignore on promt telling me the rpm package is broken due to missing signature.

### ISSUE THREAD

**Issue by emiljoha** [bisq-network/bisq#3620]
First of all I really appreciate the work to get Bisq packaged as a rpm :bowing_woman: 

However, adding a signature to the rpm package whould IMHO improve the UX significantly, especially for a project where software integrity is such an important issue.

### Description

On opensuse yast complain about the rpm package being "broken" as it finds no signature. Even though the integrity of the package can be verified using instructions in the release notes a warning is displayed when installing the package

#### Version

1.2.3

### Steps to reproduce

I have imported the GPG key as:
```bash
 curl https://bisq.network/pubkey/29CDFD3B.asc | gpg --import
```

Verifying the rpm download with gpg works
```bash
gpg --digest-algo SHA256 --verify Bisq-64bit-1.2.3.rpm{.asc*,}

gpg: Signature made Thu 07 Nov 2019 03:11:46 PM CET
gpg:                using RSA key CB36D7D2EBB2E35D9B75500BCD5DC1C529CDFD3B
gpg:                issuer "christoph.atteneder@gmail.com"
gpg: Good signature from "Christoph Atteneder <christoph.atteneder@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: CB36 D7D2 EBB2 E35D 9B75  500B CD5D C1C5 29CD FD3B
```
 
Download the rpm package in opensuse tumbleweed and click 

### Expected behaviour

Expected rmp to be installed by Yast without being reported as broken due to missing signature.

### Actual behaviour

Need to press ignore on promt telling me the rpm package is broken.

### Screenshots
![Screenshot from 2019-11-16 15-10-08](https://user-images.githubusercontent.com/12907343/68995268-01fca680-088c-11ea-8100-784b32cfa902.png)

#### Device or machine

opensuse tumbleweed.

**Comment by ripcurlx** [comment]
I think we tried to add a signature to the rpm package in the past, but it caused some other failure. @devinbileck Do you remember by any chance what the problem was?

**Comment by devinbileck** [comment]
I don’t recall a signature verification failure message, although I did not test it on opensuse - only fedora.

**Comment by ripcurlx** [comment]
Ok - I'll give it a try soon to see if it somehow is working now.

**Comment by emiljoha** [comment]
@ripcurlx Thank you for looking into this! Tested it just now on openSUSE Tumbleweed (20200116-0) and Bisq-64bit-1.2.5.rpm and I still get the message about a broken package.

It is of course entirely possible that I have failed to import the key properly :man_shrugging:
