### ISSUE TITLE
tor already running as torbrowser and isn't identified

### ISSUE THREAD

**Issue by skoria** [bisq-network/bisq#363]
Just got the error "we tried to restart tor 4 times" due to the error with the file control_auth_cookie which couldn't be found in the application path

**Comment by ManfredKarrer** [comment]
Sorry for the late relpy.
Which version did you use? The latest? 0.3.6?
If you don't have bitcoin in your Bitsquare wallet and don't have open offers or trades you can delete the data directory and try to start again.

Location of the data directory:
Mac OSX: /Users/username/Library/Application Support/Bitsquare
Linux: /home/username/.local/share/Bitsquare
Windows XP: C:\Documents and Settings\username\Application Data\Bitsquare
Windows Vista or 7: %appdata%/Bitsquare

**Comment by ManfredKarrer** [comment]
Can u try again with the latest version?
