### ISSUE TITLE
Wrong bank account type in GUI

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#3641]
### Description

Wrong bank account type in national bank transfer (SE-SEK).  

#### Version

1.2.3

### Steps to reproduce

![Konto](https://user-images.githubusercontent.com/57938085/69214804-31e7ca80-0b68-11ea-8015-9b09a451c442.PNG)

### Expected behaviour

![NOK](https://user-images.githubusercontent.com/57938085/69214808-3b713280-0b68-11ea-9c87-33220becc25e.PNG)

### Actual behaviour

![SEK](https://user-images.githubusercontent.com/57938085/69214837-53e14d00-0b68-11ea-8ff0-3c164b24bdcf.PNG)

### Screenshots

Se above.

#### Additional info

"Bankgiro number" accounts are used only by business bank customers. "Kontonummer" is generic and used by private customers. Wrong name here causes misunderstandings.

**Comment by rafaelpac** [comment]
This below is what is in the source code.
It says that Kontonummer should be used only in Norway.

![image](https://user-images.githubusercontent.com/6444444/69263758-b5bfa800-0ba4-11ea-892c-f7779fc8d665.png)

**Comment by rafaelpac** [comment]
If it shows "Kontonummer / Bankgiro number", would it be ok?

**Comment by ghost** [comment]
Norway and Sweden have same word for "account number".

"Bankgiro number" is wrong.

**Comment by ghost** [comment]
Note. Swedish account validation checks that the account number consists of:

11 or 13 or 15 decimal digits.
