### ISSUE TITLE
Hangs the whole OS on startup. Ubuntu 19.10

### ISSUE THREAD

**Issue by dimaatmelodromru** [bisq-network/bisq#3657]
### Description

Hangs the **whole fucking OS** on startup @ "Connecting to Tor 1/4". Ubuntu 19.10. *Even mouse pointer hardly moves*.

#### Version

1.2.3

### Steps to reproduce

Just start on my system. Every time.

### Expected behaviour

App opens

### Actual behaviour

System freezes

### Screenshots

none.

#### Device or machine

AMD CPU
[bisq.log](https://github.com/bisq-network/bisq/files/3875146/bisq.log)

#### Additional info

[bisq.log](https://github.com/bisq-network/bisq/files/3875157/bisq.log)

**Comment by HiDef888** [comment]
Same.  
Ubuntu 19.10 

Slowly eats all RAM then moves to SWAP and eventually crashes machine.

**Comment by clutwo** [comment]
Same here... Running Manjaro 18.1.3 with kernel 5.3.11-1.

System completely frozen... no mouse movement, can't even change to TTY. 

This has never happened to me before on this system. Tried starting Bisq twice... had to punch the reset button both times.

**Comment by devinbileck** [comment]
I just tested on Ubuntu 19.10 and did not encounter an issue.
Are you able to try with a new data dir? Maybe your data dir is in a bad state.
Just curious, how many CPU cores and RAM does your machine have?

**Comment by HiDef888** [comment]
> I just tested on Ubuntu 19.10 and did not encounter an issue.
> Are you able to try with a new data dir? Maybe your data dir is in a bad state.
> Just curious, how many CPU cores and RAM does your machine have?

Ryzen 2200g, 16gb RAM, 2gb Swap space.

What type information would be helpful to you?  Do i need to build from source to use a different data directory? 
I'm on kernel 5.3.0-23

Is there perhaps some other logging I could paste in that'd be more helpful?  I watched my resources and it seemed to be a type of memory leak - RAM continued to fill rapidly and then grind to a halt.  My system hovers around 4gb of RAM usage until I open bisq, then it consumes it ALL.

**Comment by devinbileck** [comment]
Yes there is a known memory leak. See #3128 for more details.

**Comment by RobotDyn** [comment]
8GB RAM, AMD Ryzen

**Comment by dimaatmelodromru** [comment]
8GB RAM, AMD CPU

**Comment by ripcurlx** [comment]
Related to: #3128, #3657, #3918, #3917, #3787, #3786, #3686, #3677, #3343

**Comment by lugaxker** [comment]
Same here. Wanted to try Bisq but it doesn't work.

Ubuntu 18.04.4 LTS
Bisq 1.2.9

**Comment by CryptoD** [comment]
Kubuntu 19.10
Freezes the whole system at launch. Ryzen 7.

Problem didn't occur with Kubuntu 19.4

I've been trying to install it using different sources, removed with command along with manual config folder removal etc I think I tried everything, each time the result is the same: I launch it and within 10 seconds computer freezes

**Comment by chimp1984** [comment]
Can you try out the recommendations at https://github.com/bisq-network/bisq/issues/3918#issuecomment-607198677 ?

**Comment by ezy** [comment]
Getting the same heap crash on:

Processor		: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Memory		: 32800MB (5730MB used)
Machine Type		: Desktop
Operating System		: Ubuntu 20.04.2 LTS
Resolution		: 3840x2160 pixels
SCSI Disks - ATA Lexar SSD

openjdk version "11.0.11" 2021-04-20 LTS
OpenJDK Runtime Environment Zulu11.48+21-CA (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.48+21-CA (build 11.0.11+9-LTS, mixed mode)

Renders bisq unusable, which is a shame because it looks like a promising product.

**Comment by cd2357** [comment]
Should be fixed in the most recent release (v1.6.4) which brings several UI performance improvements and generally reduces system resource consumption. Please try it out and let us know if it's still an issue for you.
