### ISSUE TITLE
Linux version of 0.3.6 crashes on startup 

### ISSUE THREAD

**Issue by guyjames** [bisq-network/bisq#366]
Java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

Quits with error message after creating tor hidden service:
`Error in Bitsquare: double free or corruption (out): 0x00007f3834021c10`

**Comment by ManfredKarrer** [comment]
You need to have the lastes java version (1.8.0_40 ) if you build from source. You need also follow all the steps here: https://github.com/bitsquare/bitsquare/blob/master/doc/build.md

**Comment by ManfredKarrer** [comment]
In case you did not compile yourself but started the binary, please let me know.

**Comment by guyjames** [comment]
yes it is the .deb binary, I did not compile from source.

**Comment by ManfredKarrer** [comment]
Ah thats strange. I tested on Ubuntu 14, there it was not issue. just installed it and opened it. how did you install/start/open the binary? if you started the jar file directy inside the deb, it might be the reason. then probably it does not use the packed java jre but the one installed on your OS.

**Comment by guyjames** [comment]
If I run it normally, it just quits after making the tor connection, if I run it from the command line it quits at the same point with the following error messages:

> # A fatal error has been detected by the Java Runtime Environment:
> 
> #
> 
> # SIGSEGV (0xb) at pc=0x00007f027944a820, pid=8696, tid=139646920730368
> 
> #
> 
> # JRE version: Java(TM) SE Runtime Environment (8.0_66-b17) (build 1.8.0_66-b17)
> 
> # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.66-b17 mixed mode linux-amd64 compressed oops)
> 
> # Problematic frame:
> 
> # C  [libc.so.6+0x91820]

**Comment by guyjames** [comment]
I didn't run the jar file directly from the .deb, I installed it using gdebi by the way.

**Comment by ManfredKarrer** [comment]
Thanks for reporting! Seem sot be a segmentation violation, but no idea why. I will test on my linux boxes again, but never got any issues. Do you have anything specila on your OS?

**Comment by guyjames** [comment]
The only thing I can think of is I am using Kubuntu but with CInnamon instead of KDE, not sure how that would affect things but I suppose it's possible.

**Comment by ManfredKarrer** [comment]
Hm.. I am not expert for Linux, so I don't have nay idea what can cause that issue. Do you know anybody with good Linux skills? Maybe he has an idea and can help?

**Comment by kimmel-** [comment]
Well... 32 bits linux Ubuntu based here:
- .deb -> "wrong architecture amd64"
- .jar with JRE-8u77 -> java virtual machine launcher - A java Exception has ocurred
- .exe -> with WinXP - Bitsquare.exe is not a valid Win32 application

cant test here by now :S

**Comment by ManfredKarrer** [comment]
Thanks for the feedback.
There are unfortunately still no 32bit verions available (linux, windows). It is on the (long) todo list.
If you use OpenJDK you also need OpenJFX installed. If you use Oracle JRE JavaFX is already packed into the JRE. 
Can you provide a bit more information about the error message and your OS setup?

**Comment by ManfredKarrer** [comment]
Can you try again with the latest version?

**Comment by guyjames** [comment]
It's working now with the new version! (0.4.1).

Thanks

**Comment by ManfredKarrer** [comment]
Ah cool!
