### ISSUE TITLE
can't see other offers

### ISSUE THREAD

**Issue by ulrichard** [bisq-network/bisq#367]
I 've had bitsquare running for the last three weeks about 10 hours a day. 
During that period, I saw about 4 other EUR offers, all on the same day. The rest of the time, my 4 CHF offers are the only ones my client displays.
My client usually reports between 10 and 12 peers, and 1 to 4 tor connections. It happens about twice per day that it briefly reports disconnection from tor. Usually it's back on line after a minute.
I find it hard to believe that there is so little activity on bitsquare.

**Comment by ManfredKarrer** [comment]
Do you have the lastest verison installed (0.3.6). 1-4 Tor connections sounds stange, I have 10 at my client. I assuem you use mainnet (on testnet there is not much going on). 
If you select "show all" you can see all offers, but there are not so much yet (about 10 buy and 10 sell offers). 
We did not have started to make much PR as I want to release a new version first with a global Bitsquare wallet so you dont need to fund each individual trade. After that (next 1-2 weeks) we will start with more PR and hopefully more people start using it.

**Comment by ulrichard** [comment]
I had 0.3.4. After upgrading it's much better.
How about an apt repository, so I wouldn't have to upgrade manually?

**Comment by ManfredKarrer** [comment]
Re. apt repository: Will add it to th e(long) todo list!
