### ISSUE TITLE
BSQ balances are shown in BTC

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#3672]
### Description

All BSQ balances are shown in BTC.

#### Version

master (commit hash d12a4049ad423266f42b6987b8e4dc613c23684e)
This seems to be introduced recently. v1.2.3 does not appear to have this issue.

### Steps to reproduce

Observe the BSQ wallet balances.

### Screenshots

The following was from a fresh regtest setup using the dao-setup.zip file.
![image](https://user-images.githubusercontent.com/603793/69487874-40f3a480-0e16-11ea-94e7-10aac0288a6a.png)

**Comment by julianknutsen** [comment]
```
80fda1ec2 (refs/bisect/bad) Inject CoinFormatter via BTC_FORMATTER_KEY
68a988b3a (refs/bisect/skip-68a988b3a81179f33e363ec2a5102813601476b6) Remove dead code
cb8873fa6 (refs/bisect/skip-cb8873fa6d1b9a35fad565a9833357413f840eb1) Move BsqFormatter and ImmutableCoinFormatter under .coin package
d23ae558e (refs/bisect/skip-d23ae558e720b8a18e0d9d0381ba412bc31b64d7) Rename BSFormatter to ImmutableCoinFormatter
ed97f7a9e (refs/bisect/skip-ed97f7a9e50854a2258dc26c2316be00cc9849f4) Use interface instead of class name for CoinFormatter
d10683e19 (refs/bisect/skip-d10683e192c97330de1d5f87dc91ad7929f3bc1f) Extract CoinFormatter interface
2f7a92479 (refs/bisect/good-2f7a9247925f7a16e886accfbccff6f753237de8) Remove dead code from BSFormatter
```

The skipped items either didn't build or had runtime errors, but they are all part of the same merge I think so should be easy to revert/fix. #3634 @freimair @bodymindarts

**Comment by bodymindarts** [comment]
I'm on it will fix it this morning
