### ISSUE TITLE
Investigate if -BjvmOptions for linux build is still needed

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#3677]
We added the jvm options `-BjvmOptions=-Xss1280k` to the Linux build. I am not sure if that is still needed and if it might be related to the reports that on Linux some users have experienced very high RAM consumption.

**Comment by HiDef888** [comment]
Hello Chimp,
I am one of the users having RAM consumption issues starting Bisq.  I commented out the line in Bisq.cfg `-Xss1280k` you refer to, to see if it affected my RAM usage, and it did not fix the issue unfortunately. I have also tried to force limiting the JVM to certain constraints and that doesn't work for me either.
Thanks

**Comment by ripcurlx** [comment]
Related to: #3128, #3657, #3918, #3917, #3787, #3786, #3686, #3677, #3343

**Comment by freimair** [comment]
maybe we should try adding a `-XX:MaxRAM=2147483648` to the java opts of the bisq-desktop binaries. @ghubstan had some success with that and I can confirm that this limits the RAM usage drastically even after days of always-on.

**Comment by cd2357** [comment]
> I am one of the users having RAM consumption issues starting Bisq. I commented out the line in Bisq.cfg `-Xss1280k` you refer to, to see if it affected my RAM usage, and it did not fix the issue unfortunately. I have also tried to force limiting the JVM to certain constraints and that doesn't work for me either.

Should be fixed in the most recent release (v1.6.4) which brings several UI performance improvements and generally reduces system resource consumption (especially RAM). Please try it out and let us know if it's still an issue for you.
