### ISSUE TITLE
Cannot save new SEPA account

### ISSUE THREAD

**Issue by camahama** [bisq-network/bisq#3678]
### Description

Cannot create a new SEPA account (Swedish bank) - no error message.

#### Version

Version 1.2.3

### Steps to reproduce

1. Select payment type -> SEPA
2. Fill in all account details
    - I tried with Swedish Skandiabanken
3. The button Save new account remains grey
4. No error messages appear below any fields
    - Trying with the bank Revolut yields an error message

### Expected behaviour

Able to save new account

### Actual behaviour

Not able to save new account

#### Device or machine

MacBook Pro, MacOS 10.15.1

**Comment by julianknutsen** [comment]
@camahama

Is there a red error message under the IBAN or BIC fields? I just tried this with test data and was successful, but it could be something about your specific codes that might not be handled correctly.

<img width="662" alt="Screen Shot 2019-11-24 at 2 13 47 PM" src="https://user-images.githubusercontent.com/8082291/69502484-ab631e00-0ec4-11ea-9e24-32903fac4057.png">

**Comment by ghost** [comment]
Toggle currency selector by changing it to EUR (SEPA is not SEK) and save is possible. A bug.

**Comment by beingindot** [comment]
I too tested. If we give 8 to 11 letters for BIC it accepts and able to save. (even changed to EUR)

**Comment by seknokdkk** [comment]
Your tests probably didn't fail because you toggled "Country of bank" by not using the default values.

This issue will be resolved by #3833.
