### ISSUE TITLE
High resource usage and responsiveness problems

### ISSUE THREAD

**Issue by dmos62** [bisq-network/bisq#3683]
On my machine Bisq uses ~1.4 GB of RAM (RES column in htop) and about 5-15% CPU when in background, and sometimes up to 100% when clicking around. Also, often there's a noticable response lag when clicking, sometimes the lag is on the order of seconds.

My main concern is the significant power usage when idle, if I want to keep the app running for a long time.

I also experience thick white borders around popups, which isn't a problem, but might provide hints. My graphics driver doesn't support hardware acceleration. Is that part of the requirements? For comparison, Firefox works without problems.

Running manually compiled v1.2.3 on Linux x64, i7-3520M.

I have time on my hands and I would be willing to mull around in the source code. I'm not familiar with the code base, or JavaFX, so I'd need some guidance and pointers.

**Comment by freimair** [comment]
would you care to take a look there https://github.com/bisq-network/bisq/issues/3430. Any input is appreciated!
