### ISSUE TITLE
Fresh installation of Bisq - wrong disclaimer

### ISSUE THREAD

**Issue by FKrauss** [bisq-network/bisq#3684]
### Description

When you install Bisq on a new machine, the first time you open it there is a big text with a disclaimer. The info on it is old and it is referencing the old arbitration system as well as the old documents 

#### Version

1.2.3 - Windows

### Steps to reproduce

- Get a new computer
- install bisq
- read the wrong info before continuing =) ([old document](https://docs.google.com/document/d/1DXEVEfk4x1qN6QgIcb2PjZwU4m7W6ib49wCdktMMjLw/edit))

### Expected behaviour

- the correct information about the mediation system, instead of the old arbitration document

### Actual behaviour

![2019-11-25 14_22_35-](https://user-images.githubusercontent.com/4820683/69544602-5b518d80-0f90-11ea-9f92-e50fca331eca.png)

#### Additional info

@m52go I think you may already have content we can put here, just need to tweat the app code to look for it

**Comment by m52go** [comment]
The link should be corrected, but all the displayed text looks updated to me...do you see something wrong there too?

**Comment by FKrauss** [comment]
I read it too, seems ok. Just the link then
