### ISSUE TITLE
Does not start in VirtualBox Debian (latest) guest

### ISSUE THREAD

**Issue by dimaatmelodromru** [bisq-network/bisq#3686]
### Description

Does not start in VirtualBox Debian (latest) guest

Since Bisq freezes my OS Ubuntu 19.10 I was trying to start it in VirtualBox Debian (latest) guest, 4GB RAM.
Nope. No messages. Nothing.

#### Version

1.2.3

**Comment by dimaatmelodromru** [comment]
logs:

cl1p.net - The internet clipboard cl1p.net/rbtdn
Here is your stuff. Thanks for using cl1p. Tell your friends!

Nov-25 18:36:03.562 [main] INFO  b.c.s.CoreSetup: 


Log files under: /home/user/.local/share/Bisq/bisq 
Nov-25 18:36:03.620 [main] INFO  b.c.u.Utilities: System info: os.name=Linux; os.version=4.19.0-6-amd64; os.arch=amd64; sun.arch.data.model=64; JRE=10.0.2+13 (Oracle Corporation); JVM=10.0.2+13 (Java HotSpot(TM) 64-Bit Server VM) 
Nov-25 18:36:03.788 [main] INFO  b.c.s.CoreNetworkCapabilities: Set Capability.RECEIVE_BSQ_BLOCK 
Nov-25 18:36:04.138 [main] INFO  b.c.app.Version: Version{VERSION=1.2.3, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=2, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10} 
Nov-25 18:36:04.143 [main] INFO  b.c.s.CoreSetup: Path to Bisq jar file: /opt/Bisq/app/desktop-1.2.3-all.jar 
Nov-25 18:37:09.944 [main] INFO  b.c.s.CoreSetup: 


Log files under: /home/user/.local/share/Bisq/bisq 
Nov-25 18:37:10.017 [main] INFO  b.c.u.Utilities: System info: os.name=Linux; os.version=4.19.0-6-amd64; os.arch=amd64; sun.arch.data.model=64; JRE=10.0.2+13 (Oracle Corporation); JVM=10.0.2+13 (Java HotSpot(TM) 64-Bit Server VM) 
Nov-25 18:37:10.209 [main] INFO  b.c.s.CoreNetworkCapabilities: Set Capability.RECEIVE_BSQ_BLOCK 
Nov-25 18:37:10.611 [main] INFO  b.c.app.Version: Version{VERSION=1.2.3, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=2, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10} 
Nov-25 18:37:10.621 [main] INFO  b.c.s.CoreSetup: Path to Bisq jar file: /opt/Bisq/app/desktop-1.2.3-all.jar 
Nov-25 18:38:03.542 [main] INFO  b.c.s.CoreSetup: 


Log files under: /home/user/.local/share/Bisq/bisq 
Nov-25 18:38:03.619 [main] INFO  b.c.u.Utilities: System info: os.name=Linux; os.version=4.19.0-6-amd64; os.arch=amd64; sun.arch.data.model=64; JRE=10.0.2+13 (Oracle Corporation); JVM=10.0.2+13 (Java HotSpot(TM) 64-Bit Server VM) 
Nov-25 18:38:03.841 [main] INFO  b.c.s.CoreNetworkCapabilities: Set Capability.RECEIVE_BSQ_BLOCK 
Nov-25 18:38:04.346 [main] INFO  b.c.app.Version: Version{VERSION=1.2.3, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=2, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10} 
Nov-25 18:38:04.356 [main] INFO  b.c.s.CoreSetup: Path to Bisq jar file: /opt/Bisq/app/desktop-1.2.3-all.jar 
Nov-25 18:49:29.380 [main] INFO  b.c.s.CoreSetup: 


Log files under: /home/user/.local/share/Bisq/bisq 
Nov-25 18:49:29.466 [main] INFO  b.c.u.Utilities: System info: os.name=Linux; os.version=4.19.0-6-amd64; os.arch=amd64; sun.arch.data.model=64; JRE=10.0.2+13 (Oracle Corporation); JVM=10.0.2+13 (Java HotSpot(TM) 64-Bit Server VM) 
Nov-25 18:49:29.840 [main] INFO  b.c.s.CoreNetworkCapabilities: Set Capability.RECEIVE_BSQ_BLOCK 
Nov-25 18:49:30.423 [main] INFO  b.c.app.Version: Version{VERSION=1.2.3, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=2, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10} 
Nov-25 18:49:30.432 [main] INFO  b.c.s.CoreSetup: Path to Bisq jar file: /opt/Bisq/app/desktop-1.2.3-all.jar 
Nov-25 18:49:45.500 [main] INFO  b.c.s.CoreSetup: 


Log files under: /home/user/.local/share/Bisq/bisq 
Nov-25 18:49:45.569 [main] INFO  b.c.u.Utilities: System info: os.name=Linux; os.version=4.19.0-6-amd64; os.arch=amd64; sun.arch.data.model=64; JRE=10.0.2+13 (Oracle Corporation); JVM=10.0.2+13 (Java HotSpot(TM) 64-Bit Server VM) 
Nov-25 18:49:45.729 [main] INFO  b.c.s.CoreNetworkCapabilities: Set Capability.RECEIVE_BSQ_BLOCK 
Nov-25 18:49:46.074 [main] INFO  b.c.app.Version: Version{VERSION=1.2.3, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=2, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10} 
Nov-25 18:49:46.078 [main] INFO  b.c.s.CoreSetup: Path to Bisq jar file: /opt/Bisq/app/desktop-1.2.3-all.jar 
Nov-25 19:12:22.900 [main] INFO  b.c.s.CoreSetup: 


Log files under: /home/user/.local/share/Bisq/bisq 
Nov-25 19:12:22.965 [main] INFO  b.c.u.Utilities: System info: os.name=Linux; os.version=4.19.0-6-amd64; os.arch=amd64; sun.arch.data.model=64; JRE=10.0.2+13 (Oracle Corporation); JVM=10.0.2+13 (Java HotSpot(TM) 64-Bit Server VM) 
Nov-25 19:12:23.125 [main] INFO  b.c.s.CoreNetworkCapabilities: Set Capability.RECEIVE_BSQ_BLOCK 
Nov-25 19:12:23.486 [main] INFO  b.c.app.Version: Version{VERSION=1.2.3, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=2, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10} 
Nov-25 19:12:23.495 [main] INFO  b.c.s.CoreSetup: Path to Bisq jar file: /opt/Bisq/app/desktop-1.2.3-all.jar

**Comment by ripcurlx** [comment]
Related to: #3128, #3657, #3918, #3917, #3787, #3786, #3686, #3677, #3343

**Comment by ghubstan** [comment]
I could not reproduce this problem by installing the 1.2.7 .deb release on the latest Debian 10.3 guest vm  running with 8 GiB, and with 4 GiB (hosted on an Ubuntu 18.04).  

I could also run it on an Ubuntu 19 VM, _but with the reported memory leak problem_.

I could build & run 1.2.7-SNAPSHOT src, and create a .deb installer pkg, install it to /opt, and run that too.

But I could not run the linux javapackager on debian because it crashed while trying to create an "rpm" using version=1.2.7-SNAPSHOT:

	error: line 3: Illegal char '-' (0x2d) in: Version: 1.2.7-SNAPSHOT	

Related to [#4006]( https://github.com/bisq-network/bisq/issues/4006) , [#2200](https://github.com/bisq-network/bisq/pull/2200)

**Comment by ripcurlx** [comment]
@dimaatmelodromru Could you please try to run v1.2.7 on your system as well, just to know if your bug is already fixed?

**Comment by chimp1984** [comment]
> -SNAPSHOT

You have to remove the "-SNAPSHOT" string from any version fields.

**Comment by chimp1984** [comment]
Can you try out the recommendations at https://github.com/bisq-network/bisq/issues/3918#issuecomment-607198677 ?

**Comment by cd2357** [comment]
As per https://github.com/bisq-network/bisq/issues/3686#issuecomment-590523302 above, not reproducible.

I've also been testing most versions since v1.5.0 on the same setup (latest Debian as guest in VirtualBox) with no issues.
