### ISSUE TITLE
java.lang.IllegalAccessException JFXTextFieldSkinBisqStyle error instead of password prompt window

### ISSUE THREAD

**Issue by mercurytoxic** [bisq-network/bisq#3689]
### Description
Instead of password prompt window I get an error window, never get the password prompt, so I can't log into bisq,

#### Version

bisq current master g4c9d91503
https://github.com/bisq-network/bisq/commit/4c9d915031de01ece577d28a554422a6d15b8a5d

### Actual behaviour

```
Nov-26 10:15:37.941 [JavaFX Application Thread] INFO  bisq.core.app.BisqSetup: Wallet password required 
Nov-26 10:15:37.942 [JavaFX Application Thread] INFO  bisq.core.app.BisqSetup: onRequestWalletPassword 
Nov-26 10:15:37.944 [JavaFX Application Thread] INFO  bisq.core.app.BisqSetup: onRequestWalletPassword 
java.lang.IllegalAccessException: class bisq.desktop.components.JFXTextFieldSkinBisqStyle cannot access a member of class javafx.scene.control.skin.TextFieldSkin with modifiers "private"
```

#### Device or machine

Linux red 5.3.12-arch1-1 #1 SMP PREEMPT Wed, 20 Nov 2019 19:45:16 +0000 x86_64 GNU/Linux

#### Additional info

[bisq.log](https://github.com/bisq-network/bisq/files/3889271/bisq.log)

**Comment by chimp1984** [comment]
I assume you run a newer JVM version which is not containing JavaFX packages. If you run from source please be sure to follow build instructions in the docs folder.

**Comment by mercurytoxic** [comment]
Yes, I am using java-13-openjdk
`> env JAVA_HOME=/usr/lib/jvm/java-10-openjdk /usr/bin/bisq-desktop`
fixed the problem.
