### ISSUE TITLE
User Experience: proposal for improvements 

### ISSUE THREAD

**Issue by joachimneumann** [bisq-network/bisq#369]
# Error message "No matching payment account".

This error message can be improved. Users might be confused and wonder things like if their bank account has not been set up correctly or if they do not have the bitcoins needed for the fees? The message should specify the type of payment account needed for the transfer. Especially, users might not be aware that they need separate payment accounts for national transfers and SEPA.
# Creating a new account

The list of countries of the bank is not ordered alphabetically. It might be ordered alphabetically in some language (Spanish?) and then it was translated without beeing orered again
Editing the account name should be possible by just clicking on the account name, without the checkbox "Use Custom account name"
# Purchasing bitcoin

The status "wait for blockchain confirmation" might not be clear to all users. Which confirmation Am I waiting for? Is there anything I should do, is there anything, the seller needs to do or am I waiting for a certain number of confirmation to automatic appear?
# Cancelling Offers

After making an offer, how can I cancel the offer?
How do I get the money back that is "locked in trades" if I wish to do so?
# Startup

The warning "You need to wait until you are bootstrapped to the network." is too technical. It would be nice to tell the user what to look out for (Tor symbol turning from grey to color?)
# Markets

The option to select all currencies is not there (for me)
# Settings

The selection of the option "show my own offers in offer book" lost after a restart of the app

**Comment by ManfredKarrer** [comment]
Thanks a lot! Will try to get them into the upcoming release.

**Comment by ManfredKarrer** [comment]
Here a quick feedback:
- Sorting of countires is fixed. 
- Missing saving of "show my own offers in offer book" in preferences is fixed as well.
  Those will be in at the next release.

Cancelling Offers:
A trade cannot be canceled only an open offer (at Portfolio/Open offers).

Markets:
Show all does nto make sense for the current chart as the currencies (price) would get mixed up.
In future versions there will be multiple chart lines for different currencies or payment methods.

The other issues will be considered in upcoming UI/usability improvement releases.

**Comment by ManfredKarrer** [comment]
Most are implemented now. general wording improvements are on the todo list...
