### ISSUE TITLE
Open trade in mediation, but not in Open Trades

### ISSUE THREAD

**Issue by Bigsy11** [bisq-network/bisq#3697]
### Description

Trade went into mediation, and was resolved.
Still shows Open under mediation, but under Portfolio, there are no open trades  visible.

Neither is the Multisig payout visible under Funds > Transactions or in Funds > Send Funds.

Subsequent trades in different currency completed normally.

#### Version

1.2.2 upgraded to 1.2.3 upgraded to 1.2.4 to try to fix the problem, but didn't help.

### Steps to reproduce

N/A

### Expected behaviour

Ability to agree to mediation result in Open Trades and close trade.

### Actual behaviour

See description.

### Screenshots

N/A

#### Device or machine

Debian 9 on Qubes 4

#### Additional info

Mediation deadline ends in 2 days.
No suggestions or response from mediator are visible last 9 days, but chat box shows that  messages received.

**Comment by chimp1984** [comment]
Do you have the trade at the failed trades or closed trades screen?

**Comment by chimp1984** [comment]
If you do not see the payout, go to funds/tx and look if there is any older tx which is still not confirmed. In doubt do a spv resync (settings/network).

**Comment by Bigsy11** [comment]
Thanks. It's not in failed trades. Can it be in closed trades and open in mediation at the same time?

We already tried spv resync and resync of DAO state.

**Comment by Bigsy11** [comment]
Sometimes I see a blank dialog box appear.
How to read what is in it?

![Screenshot_2019-12-02](https://user-images.githubusercontent.com/53511089/69981497-5bbacd00-152a-11ea-955b-3049bdb26af6.png)

**Comment by Bigsy11** [comment]
> Do you have the trade at the failed trades or closed trades screen?

It is not in failed trades or closed trades. It's only in mediation with open status.

**Comment by Bigsy11** [comment]
I think the blank dialog we see is somehow connected to this failed trade.

Next we tried to create a new data directory to see if anything useful would appear then.
We transferred only the seed words, the exported accounts, and the hidden service folder.

When it syncronized, the bitcoin is there that we had in offers and wallet.
Of course, this trade is not anywhere there - not mediation, failed, open, closed, and  there is no payout for it in the transactions.

So, now switched back to old data directory, and back  where this was before:
trade shows open in mediation, and nowhere else.

No response from mediator since more than 2 weeks. Maybe he can't respond, because of this problem and [issue 3731](https://github.com/bisq-network/bisq/issues/3731)

**Comment by Bigsy11** [comment]
What will happen to the significant sum of BTC that my client is supposed to get from this trade?

**Comment by ripcurlx** [comment]
> What will happen to the significant sum of BTC that my client is supposed to get from this trade?

@Bigsy11 Could you please join the #support channel on keybase and post the onion address of the mediator you haven't received any communication from. Mediators and arbitrators are available in this channel and it should be possible to sort everything out if the in-app communication is broken somehow.

**Comment by Bigsy11** [comment]
> Sometimes I see a blank dialog box appear.
> How to read what is in it?
> 
> ![Screenshot_2019-12-02](https://user-images.githubusercontent.com/53511089/69981497-5bbacd00-152a-11ea-955b-3049bdb26af6.png)

When this blank box comes out, it cannot be closed, and Bisq can't be closed. It has to be killed.
The allocated memory is set to start at 3GB for Bisq to use by itself, as others using this setup told me to do, and it's excluded from memory balancing.
So, Java can use as much real and swap memory as it can waste. ;)

**Comment by Bigsy11** [comment]
Saga continues in version 1.2.4

I was able to contact the mediator on Keybase.
He tried reopening and closing, which turned trade status Closed.

Now he wants me to press the button to Go to Arbitration to get funds unstuck, but there is no such button, because the trade doesn't appear in Open Trades.

It is now not mentioned anywhere, except in Mediation as Closed.

Today blank dialog appeared again. It could be minimized and maximized, but could not be refreshed with F5 or closed. 
Bisq had to be killed to close the dialog.

**Comment by Bigsy11** [comment]
Tried deleting SPV again. No change.

**Comment by ripcurlx** [comment]
> Today blank dialog appeared again. It could be minimized and maximized, but could not be refreshed with F5 or closed.
> Bisq had to be killed to close the dialog.

Is the window style of this empty window similar to other popups? When you receive this popup do you see something suspicious in your app log file?
