### ISSUE TITLE
add auto-update offer price & time limit

### ISSUE THREAD

**Issue by kimmel-** [bisq-network/bisq#370]
Finally up and running :)

Great improvements from last version I tested... I'm greatly missing the ability to set up an offer with dynamic pricing; that means BTCrate +/- X%, and also a validity for the offer in hours, days...

For example: 
sell 0.1 btc
price: BTC Price + 2%
validity: 7 days

I think this features are a must if we pretend this soft to be widely used for Crypto-Fiat purposes...do you have them in mind? how and when are they going to be introduced?

thanks!

**Comment by ManfredKarrer** [comment]
Yes those features are on the ToDo list with hi priority. Though I cannot say when they will get in, but I am aware of the importance.

**Comment by jonathascarrijo** [comment]
This would bring Bitsquare more to be like LocalBitcoins than an exchange.

Jonathas Carrijo
(62) 9135-5306

2016-04-04 6:09 GMT-03:00 Manfred Karrer notifications@github.com:
