### ISSUE TITLE
Wrong BSQ amount in issuance log message

### ISSUE THREAD

**Issue by julianknutsen** [bisq-network/bisq#3709]
### Description

Log messages after new BSQ is issued has wrong units. I think it specifies the number of satoshis that correspond to the BSQ.

#### Version

548a21775

### Steps to reproduce

1. Start regtest cluster with existing dao-setup.zip contents
2. Create Reimbursement Request from Alice
3. Vote thumbs-up for Proposal from Alice
4. Vote thumbs-up for Proposal from Bob
5. Enter `Vote Result` phase
6. See log message

### Expected behavior

The proposal was for 10,000 BSQ so log message should reflect that

### Actual behavior
![10k_proposal](https://user-images.githubusercontent.com/8082291/69767994-93450600-1133-11ea-8c9a-765d88246c8a.JPG)

![bsq_amount_wrong](https://user-images.githubusercontent.com/8082291/69767941-6264d100-1133-11ea-8137-0028dd0819af.JPG)

**Comment by chimp1984** [comment]
Yes it shows the sat value. 100 Sat = 1 BSQ
