### ISSUE TITLE
[1.2.4] Auto correcting trade limit have some round off issue.

### ISSUE THREAD

**Issue by beingindot** [bisq-network/bisq#3711]
### Description
For default new users trade limit 0.01 btc popup coming after entering higher value to buy. then auto set value being 0.0099 btc instead of 0.01

#### Version
1.2.4

### Steps to reproduce
1. create offer to buy btc from alice
2. Enter higher value than trade limit, then limit popup appears
3. Instead of 0.01 btc 0.0099 btc appears in the amount to buy.

### Expected behaviour
reset value should be 0.01 btc

### Actual behaviour
reset value being 0.0099 btc

### Screenshots
![Screenshot from 2019-11-28 12-56-12](https://user-images.githubusercontent.com/55691179/69785956-64846980-11df-11ea-8856-521e365ff240.png)

#### Device or machine
Ubuntu

**Comment by ripcurlx** [comment]
This is because we round the fiat value to increase privacy, which results in some cases to adapt the amount to match the rounded fiat value.
