### ISSUE TITLE
Create Offer info popup steals focus and causes validation errors

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#3715]
### Description

When entering the Create Offer screen, an information popup appears that steals cursor focus from the form, triggering validation errors. When the user dismisses the popup, they are left looking a screen full of scary red errors. See screenshots below.

Because this happens only to users who have not already clicked the "Don't show again" checkbox on that popup, it means that every new / first-time Bisq user experiences it. Likewise, we (experienced users) don't often run into it because we've long since suppressed that popup.

#### Version

release/v1.2.4 (commit 548a21775)

### Steps to reproduce

1. Go to Account->National currency accounts->Add new account and set up a fiat payment account, e.g. Zelle
1. Go to Settings and click "Reset all 'don't show again' flags" to ensure you see the popup in question
1. Go to Market and click "Create new offer to buy BTC"
1. The Create Offer screen appears and the info popup appears immediately afterward
1. Notice the red validation errors appear in the background and persist after dismissing the popup by clicking "I confirm"

Workaround (if you can call it that):
1. Close the Create Offer screen and enter it again by clicking on "Create new offer to buy BTC"
1. This time, when the popup appears, click "Don't show again" and then click "I confirm" to dismiss it.
1. Repeat step (1), notice that the popup does not appear, and that the form is presented without any validation errors.

### Expected behaviour

Validation errors should appear only when the user has actually engaged with the form and entered something invalid.

### Actual behaviour

Validation errors appear no matter what the (first time) user does, creating a poor/frightening experience.

### Screenshots

On entering the Create Offer screen for the first time (note the red validation errors in the background):
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/301810/69835490-574c9680-1242-11ea-962d-7c9747f89ab2.png">

What the user is left looking at when they click "I Confirm" to dismiss the popup:
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/301810/69835535-97137e00-1242-11ea-9ee5-ddcbb157598a.png">

#### Device or machine

macOS 10.14.6

**Comment by cbeams** [comment]
It's not just the popup that causes this problem; it's anything that takes focus away from the form field where the cursor is placed by default on this screen. For example, when the popup has already been suppressed and the user enters the Create Offer screen, clicking on the "Select trading account" dropdown also triggers these validation errors, because it removes focus from the form, form validation fires and sees that the user has "entered empty input", when of course they haven't done anything other than try to change the trading account.

Perhaps a simple and general solution to this problem would be to stop auto-focusing the cursor in the "Amount of BTC to buy" field. This would give the user the chance to choose where to click first. If they click one of the text input fields and then click away from it, then it'll make more sense to them why the validation errors are displayed.

**Comment by beingindot** [comment]
![Screenshot from 2019-12-05 14-20-04](https://user-images.githubusercontent.com/55691179/70219204-682d6880-176a-11ea-997d-328ebac8dddb.png)

one popup which comes on right top when coming to this page, takes focus away from this Review button(makes it look like half disabled), which makes me wonder whether i have clicked it or not. comes in similar situation in make offer too.

**Comment by beingindot** [comment]
if the above comment is not related to this bug, pls let me know will file new one.
