### ISSUE TITLE
Trades with a mediated payout end up in failed trades

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#3727]
If a trades gets payed out via a mediated payout the trade will be moved to failed trades after a restart. This happens with payout to both traders as well as with payout to only 1 trader.

**Comment by chimp1984** [comment]
Fixed with #3726

**Comment by julianknutsen** [comment]
Thanks for splitting this out. It will be easier to verify the fix since they aren't related.

**Comment by julianknutsen** [comment]
I was able to confirm the repro on this bug of 5fa88cc66.

![failed_trade_repro](https://user-images.githubusercontent.com/8082291/70010668-ac7cf680-1527-11ea-9045-7d43b653b89d.JPG)
![failed_trade_repro2](https://user-images.githubusercontent.com/8082291/70010674-ad158d00-1527-11ea-8ad2-a869b5f6397b.JPG)

I was also able to verify it was fixed on c2e8806d1.

![failed_trade_repro3](https://user-images.githubusercontent.com/8082291/70012015-e5b56680-1527-11ea-92f9-0a779ba3b97c.JPG)

I did notice that this is more than just a UI bug. If this bug occurs the trade is marked FAILED even after the software is updated. Is that the intended behavior, @chimp1984?

**Comment by chimp1984** [comment]
@julianknutsen 
> is marked FAILED even after the software is updated

You mean that past trades which ended up in the failed trades list are not reverted to closed trades after the update? 
That would require some more handling to move those trades out of the failed trades list and into the closed trades list. I am not sure if that is highly required for the release but would be good to fix as well.

**Comment by julianknutsen** [comment]
Correct. Past failed trades are not "fixed" and turned into closed trades. I just wanted to verify that the bug was more than just a UI issue and that state exists that would persist previously failed trades. It sounds like that was the case so the fix is working as intended.

**Comment by julianknutsen** [comment]
@chimp1984 @ripcurlx This should be reopened. It just happened again when testing 5880ad99c

I ran the `Mediation/Support Process 0001-0018` and then restarted the localnet.

I'll see if I can get a quicker repro, but here is the data. No logs... dir moved from localnet to .localnet underneath me and didn't realize. If I get another repro I'll add them.


![mediated_trade_failed](https://user-images.githubusercontent.com/8082291/70082112-940beb00-15be-11ea-8c0e-25b92661a628.JPG)
![mediated_trade_failed2](https://user-images.githubusercontent.com/8082291/70082113-940beb00-15be-11ea-8131-4cce79e43fd7.JPG)
![mediated_trade_failed3](https://user-images.githubusercontent.com/8082291/70082174-abe36f00-15be-11ea-9147-f494edcd72f6.JPG)
