### ISSUE TITLE
Revolut account should be a phone number

### ISSUE THREAD

**Issue by trigger-xyz** [bisq-network/bisq#3728]
### Description

I traded with people who had an email instead of a phone number in their revolut account.

I tested to create a new Revolut account in bisq. In the field "Phone number" I was able to put an email.

#### Version

1.2.3

### Steps to reproduce

Account => Add a new account => Revolut => Put an email

### Expected behaviour

When entering an email instead of a phone number, I should see an error message when trying to save.
Maybe limit the field to numbers, parenthesis and the + sign

### Actual behaviour

Email is accepted

#### Device or machine

Windows 10

**Comment by julianknutsen** [comment]
Thanks for filing this. Some info from #general for the dev who picks this up:

I did a quick audit and it looks like when creating a Revolut account, the form says phone #, but the input is not validated so it could be a phone or email. The "Trade information" screen also has logic to show email or phone number depending on how it interprets the field. Not straight forward... Relevant comment in code:
```
    private static String getTitle(String accountId) {
        // From 0.9.4 on we only allow phone nr. as with emails we got too many disputes as users used an email which was
        // not registered at Revolut. It seems that phone numbers need to be registered at least we have no reports from
        // arbitrators with such cases. Thought email is still supported for backward compatibility.
        // We might still get emails from users who have registered when email was supported
        return accountId.contains("@") ? Res.get("payment.revolut.email") : Res.get("payment.revolut.phoneNr");
    }
```

**Comment by ripcurlx** [comment]
I think we should only allow phone numbers when an Revolut account is created to get rid of unnecessary arbitration cases. I think @beingindot is already working on this? Shall I assign you?

**Comment by beingindot** [comment]
yes @ripcurlx.  pls assign to me.
