### ISSUE TITLE
Mediator UI shows closed state when mediation ticket isn't closed.

### ISSUE THREAD

**Issue by julianknutsen** [bisq-network/bisq#3731]
### Description

Mediator UI shows closed state when mediation isn't closed.

#### Version

c2e8806d1

### Steps to reproduce

Working on a repro, but this is what I did...

1. Start localnet cluser
2. Have existing mediation case open
3. Run `Arbitration/Support Process 0030`
4. Start closing mediation tickets to move on to next test
5. Only close Bob's mediation ticket for an issue
5. See UI state that is asymmetrical (Mediator thinks all are closed, Alice sees ticket open)

### Expected behaviour

Mediation ticket with required actions should show as OPEN and not be grey

### Actual behaviour

Mediation ticket with required action shows CLOSED and is grey

### Screenshots

![mediator_ui_shows_closed](https://user-images.githubusercontent.com/8082291/70013750-7f334700-152d-11ea-9d3f-19007cc4610c.JPG)

#### Device or machine

Ubuntu 19.10

#### Additional info

After reboot the mediation UI is correct
![mediator_ui_shows_open_after_reboot](https://user-images.githubusercontent.com/8082291/70013852-c588a600-152d-11ea-9593-d20d923ef433.JPG)

[alice-bisq.log](https://github.com/bisq-network/bisq/files/3914128/bisq.log)
[bob-bisq.log](https://github.com/bisq-network/bisq/files/3914129/bisq.log)
[mediator-bisq.log](https://github.com/bisq-network/bisq/files/3914132/bisq.log)

**Comment by chimp1984** [comment]
The filtering of the list by the "open" predicate is not applied after closing a ticket but only at view activation (switch views or restart). It would require to refresh the list with the filter predicate after the close action.

**Comment by julianknutsen** [comment]
It is more than just a filtering issue. Trade 67144 is in state Closed in the mediation UI, but OPEN on Alice.

**Comment by chimp1984** [comment]
Oh... Does Alice have received the close message?

**Comment by ripcurlx** [comment]
So it seems the dispute result message for Alice wasn't sent out or failed somehow else.
https://github.com/bisq-network/bisq/blob/037f1672ddbf4d9db4f919f1332942fe96102bbb/desktop/src/main/java/bisq/desktop/main/overlays/windows/DisputeSummaryWindow.java#L671-L688
As the closed state is set before sending the message it could be that the mediation case is closed, but the message isn't delivered (we properly should move the setting of the closed state only if onArrived or onStoredInMailbox was successful). What I don't get is that the mediation case is open again after a restart. It should be already queued up to be saved and I don't see any code part that could reset the property. It looks like storage of the dispute failed?

For the failed sending part: Did you see the `...arrived at peer...` log statement in the mediator for Alice\`s dispute closed message? Or do you see a `...failed: ...`?

**Comment by julianknutsen** [comment]
So, after a restart the Mediator sees the state as OPEN which is what I would have expected. I only closed Bob's ticket so it is probably a UI bug somewhere where it marked both rows as CLOSED even though only Alice's should have been CLOSED.

I've updated the description to make it more clear what actions I took.

**Comment by chimp1984** [comment]
> I only closed Bob's ticket so it is probably a UI bug

Yes I think there are some list item update bugs.

**Comment by ripcurlx** [comment]
Yes, maybe it is some list item caching bug, so that the opacity property is not cleared properly.
