### ISSUE TITLE
[REGEST] Mediator doesn't have BTC to exercise refund test cases

### ISSUE THREAD

**Issue by julianknutsen** [bisq-network/bisq#3738]
### Description

The default regtest mediator does not have sufficient starting BTC to pay out refund agent decisions.

#### Version

5880ad99c

### Steps to reproduce

1. Start localnet cluster
2. Run `Mediation/Support Process 0018`
3. Decline request from Bob
4. Enter RefundAgent stage
5. Rule on BTC to buyer
6. Receive error

### Expected behaviour

Test cases can be run with default nodes

### Actual behaviour

A mediator can not pay out decisions due to lack of funds.

### Screenshots

![insufficient_money_exception](https://user-images.githubusercontent.com/8082291/70081122-c6b4e400-15bc-11ea-9c8f-5c1e1dac73da.JPG)

#### Device or machine

Ubuntu 19.10

**Comment by ripcurlx** [comment]
This is related to the fact that there is no prepared refund agent data directory included in the DAO setup file atm, so a refund agent is starting with a fresh account.
