### ISSUE TITLE
Can't select "EUR" currency in Poland

### ISSUE THREAD

**Issue by lazerdye** [bisq-network/bisq#374]
Hi,

I am in Poland, which is in the EU. It's quite easy here to set up a EUR denominated account, with an IBAN and BIC as expected. However, when I create a new account, and select "Poland" as the country, it's chooses PLN for me and do not see a way to change it.
I could choose a different country (such as Germany, or Slovakia) but that would not give the buyer confidence.
Can we have a way to select EUR (or even GBP, USD) as the account denomination, even when the country's national currency is different?

**Comment by ManfredKarrer** [comment]
I am aware of that, that is a missing feature on the TODO list, sorry about that. I will push it higher up the priority list, but cannot guarantee when it will be implemented. In 2 weeks is the Beta launch and I don't want to push in anything beside bug fixes. And afterwards I am busy doing presentations all over Europe... So I fear that will take a bit until its in. 
Maybe you can setup a OKPay account? That is anyway the best way IMO (instant transaction, no chargeback risk).

**Comment by BitcoinHR** [comment]
Exactly the same problem for Croatia. Awesome work BTW.

**Comment by ManfredKarrer** [comment]
Yes I know all SEPA countries which don't have EUR as national currency have their national currency only as option atm. Will get fixed in one of the upcoming releases.

**Comment by devluxg** [comment]
I'm on it.  Send a PR as soon as possible.

**Comment by ManfredKarrer** [comment]
Cool! Its basically all non-euro sepa countries are missing the option to select euro as well.

**Comment by ghost** [comment]
Hi.

It is same for Bulgaria. I have EU account in bulgarian bank.

Regards

Stan

**Comment by ManfredKarrer** [comment]
Already implemented in latest version.
