### ISSUE TITLE
Warning message after changing Language is missing languages that disputes are handled in

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#3740]
### Description

When changing the Language from the preferences view, the warning message is missing the languages that disputes are handled in.

This is only occurring on mainnet. Regtest is fine.

#### Version

release/v1.2.4 (5880ad99c12dc5b33e1de2dc41763d94d389e3d6)

### Steps to reproduce

1. Launch an instance on mainnet.
2. Go into the preferences and change the Language to anything.

### Expected behaviour

A warning message indicating that disputes are handled in English.

### Actual behaviour

The warning message is missing the part mentioning English.

### Screenshots

Mainnet:
![image](https://user-images.githubusercontent.com/603793/70091353-caeafc80-15d0-11ea-84bb-c26105f39638.png)

Regtest:
![image](https://user-images.githubusercontent.com/603793/70091771-b3604380-15d1-11ea-9bcf-959540b4f030.png)

#### Additional info

PreferencesViewModel.getArbitrationLanguages() seems to now be returning an empty set from the v1.2 changes.

**Comment by ripcurlx** [comment]
This was a place that was overlooked when switching to the new refund agents. It needs to change accordingly. I'll prepare a patch for it.

**Comment by ripcurlx** [comment]
This just doesn't fail on Regtest as you might have an old Arbitrator registered, which is not available on Mainnet.

**Comment by ripcurlx** [comment]
As this is an existing bug <= v1.2.3 and needs new translations for each language I think we can delay it until next release.

**Comment by julianknutsen** [comment]
> As this is an existing bug <= v1.2.3 and needs new translations for each language I think we can delay it until next release.

Is there a common place for the translation work backlog?

**Comment by ripcurlx** [comment]
> Is there a common place for the translation work backlog?

Translation is done on [Transifex](transifex.com/bisq/bisq-desktop/).
