### ISSUE TITLE
Feature Request: Update offer fees text to indicate when minimum trading fee is in effect

### ISSUE THREAD

**Issue by julianknutsen** [bisq-network/bisq#3746]
When testing v1.2.4 I ran into a common pitfall that other users have also experienced when using Bisq. When trading smaller amount of coin, the minimum trading fee takes precedence over the maker fee value, but there is no indication that this is what causes the fee to be different than expected.

Here is an example of the same fees w/ two different offer sizes:

1BTC
![1btc](https://user-images.githubusercontent.com/8082291/70162464-8ca61980-1672-11ea-9634-8dfb7e2ded7a.JPG)

.01 BTC
![point_0_1btc](https://user-images.githubusercontent.com/8082291/70162470-8f087380-1672-11ea-8690-bea2e1fcd0f4.JPG)

The trading fee (as a percent) scales down with increased size, but this isn't obvious from the information. I expect most new users to do their first Bisq trade with very small amounts and this misunderstanding could cause a lack of confidence in the software.

**Comment by ripcurlx** [comment]
I think this would be a good first issue with a small scope and a probably big impact for new users.

**Comment by ripcurlx** [comment]
Closing as already fixed.
