### ISSUE TITLE
Error message taking an offer to buy BTC

### ISSUE THREAD

**Issue by jmr690** [bisq-network/bisq#3750]
#3039 # Description

Error message when taking an offer to buy btc

### Screenshots

![Captura de pantalla de 2019-12-05 10-56-56](https://user-images.githubusercontent.com/57159511/70224813-30b0c300-174e-11ea-8a17-428f650cd754.png)

**Comment by cosmasta** [comment]
I have also been encountering the same error message!

**Comment by ripcurlx** [comment]
This should be fixed with v1.2.4 which will be released today.
https://github.com/bisq-network/bisq/pull/3625

**Comment by ripcurlx** [comment]
Closing this as fixed with https://github.com/bisq-network/bisq/releases/tag/v1.2.4. Feel free to reopen if you can reproduce it with v1.2.4 as well.
