### ISSUE TITLE
[Bug]: Revolut account is not getting signed on successful trade

### ISSUE THREAD

**Issue by EvgeniySpinov** [bisq-network/bisq#3761]
### Description

My Revolut account is not getting signed despite successful trade with member who had his account signed.

#### Version

1.2.3

### Steps to reproduce

1. Open application.
2. Open Buy BTC tab
3. Find order where you can by BTC with Revolut. Order should be with the peer whos payment method Revolut has been signed.
4. Perform a normal trade.

### Expected behaviour

When trade is finished - your Revolut account will be signed.

### Actual behaviour

You Revolut account remains unsigned.

### Screenshots

My account:
![image](https://user-images.githubusercontent.com/10797822/70357997-a022d180-1878-11ea-9fb7-04d279591403.png)

Trade with signed Revolut account. Account was signed before the trade:
![image](https://user-images.githubusercontent.com/10797822/70358049-c0529080-1878-11ea-8e06-1fc276467eb8.png)

Peer sign info: 
![image](https://user-images.githubusercontent.com/10797822/70357720-e75c9280-1877-11ea-9781-c28cdc5a15f5.png)

#### Device or machine

Desktop, Windows 10 x64, ver. 1709, build 16299.371

#### Additional info

Probably related. My Revolut account is old. When I try to click on unavailable offer I receive this message: 
![image](https://user-images.githubusercontent.com/10797822/70357820-24c12000-1878-11ea-9ead-51718f36279d.png)

Message is apparently buggy as my account is more than 2 month old.

**Comment by sqrrm** [comment]
From what I see it looks like the counterparty was signed 27 days ago. That means their account doesn't yet have the ability to sign others.

Your account is not old enough to have full limits (only accounts from before march 2019 don't need signing). For unsigned accounts created after 2019 the limit is 0.01 BTC for buying and based on account age when selling.

These rules are obviously not clear, thanks for the screen shots. We'll try to clarify these limits throughout the process.

**Comment by ripcurlx** [comment]
Maybe we should add additional information during taking of the offer if the trade is a signing trade or not. Atm you only know this if you take an offer with a verified badge icon.

**Comment by sqrrm** [comment]
@ripcurlx Yes, I think that would be good. Would be good to change the wording of the warning popup as well, it's quite confusing.

**Comment by EvgeniySpinov** [comment]
Thank you for detailed response. You're right: unclear part is that signed peer without limits being lifted, cannot sign other peers. I thought it's other way around.

Not a bug if that is the case. Probably docs and message inside Bisq (regarding Revolut account age) is to be updated not to confuse others.

**Comment by sqrrm** [comment]
Can this ticket be closed?

**Comment by EvgeniySpinov** [comment]
I believe my case is addressed, yes.
