### ISSUE TITLE
cannot engage arbitration

### ISSUE THREAD

**Issue by inpharmaticist** [bisq-network/bisq#3764]
### Description

Trade went through mediation, I accepted, peer did not respond. Trade now in failure (on day 24). There's no option to send to arbitration. Trade ID alntlvk.

**Comment by sqrrm** [comment]
@inpharmaticist Did you try opening arbitration with ctrl+o, it should work.

**Comment by inpharmaticist** [comment]
Yes, nothing happens

**Comment by sqrrm** [comment]
Then it's best ask in the keybase support channel for your arbitrator to see what can be done.

**Comment by inpharmaticist** [comment]
They closed the support ticket, hoping I could open arbitration but it didn't work.

**Comment by inpharmaticist** [comment]
I have re synced SPV, per one recommendation. That did not fix the problem.

**Comment by chimp1984** [comment]
@inpharmaticist I think your case is resolved now, right? Can you close the issue?

**Comment by inpharmaticist** [comment]
I'm still waiting for the payout but yeah arbitration has been engaged. Thanks.
