### ISSUE TITLE
Filter signed accounts

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/bisq#3768]
### Description

Add option to filter signed account. Will invalidate signing and the entire signed tree below this AccountAgeWitness.

Filtering probably best done on pubkey. All AccountAgeWitnesses using the same pubkey will be filtered out.

**Comment by ripcurlx** [comment]
This feature is for the case that a scammer account got signed by mistake (e.g. bank transfer from stolen bank accounts is not detected within 30 days and a trade with a signer account took place) and started to sign afterwards other stolen bank accounts to be able to lift the 0.01 BTC limit. As soon as the scammer account is detected (a chargeback happens) we should be able to filter during runtime this account an all accounts that got signed by it to prevent further damage to the network. As always users can ignore this filter by using a `--ignoreDevMsg` startup parameters. Doing so the user uses Bisq at its own risk and will not be able for compensation if anything unexpected happens.

**Comment by ripcurlx** [comment]
Closing as complete.
