### ISSUE TITLE
Exception when Internet disconnect 

### ISSUE THREAD

**Issue by esques** [bisq-network/bisq#377]
When I got disconnected from internet, 
sun.awt.imag.BufImgSurfaceDate cannot be cast to sun...XRSurfaceData

**Comment by ManfredKarrer** [comment]
You are on Linux, right? I have seen that as well sometimes after stanby mode. Not sure yet what causes it but I assume the JavaFX Desktop/Graphics support has some issues on some Linux distros.

If any Linux guru has ideas, would be great to get help here!

**Comment by esques** [comment]
confirm, Linux

**Comment by ManfredKarrer** [comment]
Do you still get that issue? Can you reproduce it?

**Comment by esques** [comment]
Werd i morgen probieren. Muss heute noch mincha

Manfred Karrer notifications@github.com schrieb am Do., 28. Apr. 2016
20:56:

**Comment by ManfredKarrer** [comment]
Please re-open if issue is reproduceable.
