### ISSUE TITLE
error when completing trade after accepting mediator proposal

### ISSUE THREAD

**Issue by mtelizalde** [bisq-network/bisq#3774]
An error occurred at task: SignMediatedPayoutTx
Exception message: myMultiSigPubKey from AddressEntry must match the one from the trade data. trade id =75191745-1e6a6d4c-d544-495c-ba24-1d111ae17d8e-123

**Comment by mtelizalde** [comment]
[bisq error.txt](https://github.com/bisq-network/bisq/files/3947776/bisq.error.txt)

**Comment by ripcurlx** [comment]
@mtelizalde Are you still stuck in mediation because of this?

**Comment by mtelizalde** [comment]
Yes, the mediation was still stuck on my platform.

**Comment by ripcurlx** [comment]
Did you receive a manual payout already and the case is just stuck in the client or are your funds still locked?

**Comment by mtelizalde** [comment]
I received the payout after the mediator helped out, but I cant mark the
transaction as completed.
