### ISSUE TITLE
List HEX

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#3775]
### 1. Asset name

HEX

### 2. Ticker

HEX

### 3. Block explorer URL

https://etherscan.io/token/0x2b591e99afe9f32eaa6214f7b7629768c40eeb39
https://ethplorer.io/address/0x2b591e99afe9f32eaa6214f7b7629768c40eeb39

### 4. Additional technical requirements (yes/no)

No. Same requirements as other ERC20 tokens.

### 5. Initial coin offering (yes/no)

No.

### 6. Website and additional resources

https://hex.win/
https://coinmarketcap.com/currencies/hex/

Official wallet: https://go.hex.win/

**Comment by wiz** [comment]
Bisq has a no scam policy

**Comment by cd2357** [comment]
Closing, because asset listing is put on hold: https://github.com/bisq-network/proposals/issues/166
