### ISSUE TITLE
Failed tests when trying to build bisq application on SUSE Leap 15.0

### ISSUE THREAD

**Issue by m00nstar** [bisq-network/bisq#3776]
### Description

Hi !
When i try to build the bisq application on my Linux platform, i have failing java core tests.
The error is always the same 
". . .
Caused by: org.mockito.exceptions.base.MockitoInitializationException: 
Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)
.."

Can someone to tell how to avoid that types of errors when build app from sources  ?
Thanks.

#### Version
bisq-1.2.4

[build.log](https://github.com/bisq-network/bisq/files/3954216/build.log)

**Comment by ripcurlx** [comment]
Are you using the correct Java version 10?
