### ISSUE TITLE
Peer-signed accounts with lifted limits don't have a checkmark icon

### ISSUE THREAD

**Issue by gordonel** [bisq-network/bisq#3778]
### Description

Signed accounts that have been signed by a peer should have the fancy checkmark icon like the ones signed by arbitrators

#### Version

1.2.4

### Steps to reproduce

Since reproducing this would probably mean waiting 30 days, I'd much rather provide an example. See screenshots

### Expected behaviour

When a peer-signed account reached 30 days after being signed, the ! icon should become a checkmark icon

### Actual behaviour

The ! icon remains

### Screenshots

From the order book: 
![image](https://user-images.githubusercontent.com/45173186/70721636-9d076580-1cfe-11ea-8ed4-6eb0f4d1438e.png)

#### Device or machine

Any supported platform. Tested on Ubuntu, Windows and macOS Catalina

**Comment by sqrrm** [comment]
I just checked, it needs to be 60 days old to get the badge. Not sure if that's documented anywhere, we changed it up a bit around the main release and the minor ones.

**Comment by gordonel** [comment]
It's not documented. At least, nowhere that I've read. Closing

**Comment by m52go** [comment]
@sqrrm I guess I missed this. What's the rationale? Can add it to docs. Is it just additional protection for chargebacks in case they're reported in the 30-60 day period?

**Comment by sqrrm** [comment]
There are some inconsistencies on the different time spans for having limits lifted, becoming a signer and more. I will go through and clean it up, #3781

**Comment by ghost** [comment]
Sixty days before being able to sign makes the bootstrapping of signed accounts very slow. I suggest reducing it to thirty days. Bisq is having very low trading volumes and the delay between the first buy and the lifting of the limits should be considered carefully since it affects new users very negatively.
