### ISSUE TITLE
Java heap space error MacOS Bisq

### ISSUE THREAD

**Issue by r3n3x** [bisq-network/bisq#3786]
#3316 # Description

Out of nowhere, Error pop-up with Java heap space error appeared and I am tasked to open a github issue :-)
App unresponsive. Have to force-quit

#### Version

v1.2.4

### Steps to reproduce

keep running on Mac Mini Catalina MacOS for several days

### Expected behaviour

n/a

### Actual behaviour

n/a

### Screenshots

![Screen Shot 2019-12-13 at 8 05 21 PM](https://user-images.githubusercontent.com/23291787/70799189-e8477400-1de3-11ea-87ab-6bc71e3d8940.png)

#### Device or machine

Catalina 10.15.1, Mac Mini late-2014

#### Additional info

LOG EXCERPT

Dec-11 19:49:45.884 [JavaFX Application Thread] INFO  b.c.d.s.DaoStateService: New Block added at blockHeight 607640 
Dec-11 19:49:45.884 [JavaFX Application Thread] INFO  b.c.d.n.p.BlockParser: Parsing 0 transactions at block height 607640 took 0 ms 
Dec-11 19:49:45.884 [JavaFX Application Thread] INFO  b.c.d.s.DaoStateService: Parse block completed: Block height 607640, 0 BSQ transactions. 
Dec-11 19:50:03.571 [Save-file-task-6340] ERROR b.c.s.FileManager: Error in saveToFile toProtoMessage: DaoStateStore, /Users/r3n3/Library/Application Support/Bisq/btc_mainnet/db/DaoStateStore 
Dec-11 19:50:05.782 [Save-file-task-6340] ERROR b.c.s.FileManager: Error at saveToFile, storageFile=/Users/r3n3/Library/Application Support/Bisq/btc_mainnet/db/DaoStateStore java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
	at bisq.common.storage.FileManager.saveToFile(FileManager.java:200)
	at bisq.common.storage.FileManager.lambda$new$0(FileManager.java:83)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:69)
	at bisq.common.storage.FileManager.saveToFile(FileManager.java:195)
	at bisq.common.storage.FileManager.lambda$new$0(FileManager.java:83)
	at bisq.common.storage.FileManager$$Lambda$177/75024191.call(Unknown Source)
	... 5 common frames omitted

Dec-11 19:50:08.000 [JavaFX Application Thread] INFO  b.c.b.w.BsqWalletService: updateBsqBalance took 58 ms 
Dec-11 19:50:08.085 [JavaFX Application Thread] WARN  b.c.d.m.DaoStateMonitoringService: Conflict with seed nodes: We received a block hash from peer 5f4wdwjruxauizpc.onion:9999 which conflicts with our block hash.
my daoStateHash=StateHash{
     height=607640,
     hash=e7f66e5f8a0ae56a83756fb332704e43dd0b231e,
     prevHash=b7e0fdb495b631b39406e5884d1e9994151332f9
}
peers daoStateHash=StateHash{
     height=607640,
     hash=40c60563d0b0db8811fabdba8afbaee7f62b87b2,
     prevHash=9879a200291df966130c6e4d3ce337a9933e7c36
} 
Dec-11 19:50:08.177 [JavaFX Application Thread] WARN  b.c.d.m.DaoStateMonitoringService: Conflict with seed nodes: We received a block hash from peer iaqzas3rsocbphum.onion:9999 which conflicts with our block hash.
my daoStateHash=StateHash{
     height=607640,
     hash=e7f66e5f8a0ae56a83756fb332704e43dd0b231e,
     prevHash=b7e0fdb495b631b39406e5884d1e9994151332f9
}

**Comment by esackbauer** [comment]
Same here with Debian Linux. After running several hours on my Debian 10 VM.

Relevant log part attached.
[bisq.log](https://github.com/bisq-network/bisq/files/4019781/bisq.log)

**Comment by ripcurlx** [comment]
Related to: #3128, #3657, #3918, #3917, #3787, #3786, #3686, #3677, #3343

**Comment by HausIndustries** [comment]
I have the lazy fix although there does need to be a real one implemented. You just click the report to github and it does take a minute for it to start up but at least it doesnt freeze everything.

**Comment by r3n3x** [comment]
Since this bug seems not to be addresses/solved yet, at this moment I am not participating - as in keeping trades open and BisQ running. (I think this bug hinders growth of adoption).
I am not skilled to participate in the bug-fixing myself, sorry.

**Comment by chimp1984** [comment]
I guess it is related to growing data kept in memory. Trade statistics is one of the large data structure and work is in progress to fix that. The other one is the DaoState data, which will be more difficult to fix.

**Comment by cd2357** [comment]
Should be fixed in the most recent release (v1.6.4) which brings several UI performance improvements and generally reduces system resource consumption. Also, several data structures have been optimized since this was reported (>1y ago).

Please try out the latest version and let us know if it's still an issue for you.
