### ISSUE TITLE
Java Heap Space Windows 10, low resource VM

### ISSUE THREAD

**Issue by coinzdude** [bisq-network/bisq#3787]
### Description
Windows 10 VM, Celeron, 5GB RAM
received Error, Java heap space.  Log attached.

### Expected behaviour
[bisq.log](https://github.com/bisq-network/bisq/files/3961773/bisq.log)

**Comment by ripcurlx** [comment]
Related to: #3128, #3657, #3918, #3917, #3787, #3786, #3686, #3677, #3343

**Comment by chimp1984** [comment]
Is likely related to growing TradeStatistics and DaoState objects. A fix for TradeStatistics is in progress.

**Comment by cd2357** [comment]
Should be fixed in the most recent release (v1.6.4) which brings several UI performance improvements and generally reduces system resource consumption. Please try it out and let us know if it's still an issue for you.
