### ISSUE TITLE
Buttons on initial  screen may fall outside display area

### ISSUE THREAD

**Issue by AndreKoster** [bisq-network/bisq#379]
It can happen that the first popup shown after installation (which shows a number of statements that the user should agree with before being able to use the software) has its buttons rendered outside of the screen.

Problem is that (under Windows) the popup cannot be moved to make the buttons in view for clicking by mouse. The only way to solve the problem is to double click the title bar (making it full screen) during the split second that the window is visible, but the pop-up isn't displayed, yet.

**Comment by ManfredKarrer** [comment]
That might be realted to the issue with font scaling on windows. If you have systemwide scaling enabled then the layout gets broken. I fixed that for the next version (tomorrow).
But maybe you can send me a screenshot so I am sure if it is not another issue? For very small screens the layout does not work well yet as there is no scrolling supported in most screens. But that is on the todo list... but so far i have only seen those issues on netbooks with tiny screens.

**Comment by AndreKoster** [comment]
I put the font size on "larger -- 150%" in the display section of the control panel. To make a screenshot I have to de-install the application first. Can do that tomorrow.

**Comment by ManfredKarrer** [comment]
"To make a screenshot I have to de-install the application first" - why?
if you change the font size to 100% all should be visible. if you de-install make a backup of your data dir first , just in case....

**Comment by AndreKoster** [comment]
Because I only linked it to the event of the initial popup where you have to agree with the terms of the application. But you're right, the issue is universal for all the pop-ups: if the pop-up doesn't fit the screen, and the buttons are rendered outside of it, the user cannot click them. However, with all other pop-ups you can simply close the pop-up, move the application window (or make it full screen) and try again. With the initial pop-up you can't. Pressing Esc will close the program.

With the initial pop-up at installation it would already be less of a problem to centre the pop-up at the desktop instead of the application window.

<img width="960" alt="bitsquare" src="https://cloud.githubusercontent.com/assets/18371058/14521610/64c32152-022a-11e6-8180-d84121a2845a.png">

Regarding the backup: I made one (because I'm migrating to a new laptop), but it isn't clear to me how to restore an earlier made backup. Perhaps I just need to copy the backup folder manually? If so, it isn't clear to me where it need to be copied to.

**Comment by ManfredKarrer** [comment]
In the version I will publish today that sould be fixed as the system wide font sacel will no tbe applied anymore to Bitsquare.
Re backup: it makes a backup of the application data dir (where wallet, priv keys, app data are stored).
You can just move that directory to another computer and then when u start Bitsquare is uses the same data. But you must not use it at both computers at the same time as the onion address would be used then 2 times causing problems.

**Comment by ManfredKarrer** [comment]
Fixed in 0.4.1.
