### ISSUE TITLE
No seeds available using bisq on tails

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#3791]
### Description
I have been trying to configure bisq to work on tails, so far I have tried all the possible work arounds from the issue [2278](https://github.com/bisq-network/bisq/issues/2278#issuecomment-472632579) and also added a sample .yml file in the onion-grater.d/ folder in tails mentioned here [2841](https://github.com/bisq-network/bisq/issues/2841). To summarise I have made the auth cookie readable, added iptables rules to connect to the nodes, I then added the 40_bisq.yml file mentioned in [2841](https://github.com/bisq-network/bisq/issues/2841) and entered the command `sudo service onion-grater restart` into the root terminal before starting bisq with all the parameters mentioned in  [2278](https://github.com/bisq-network/bisq/issues/2278#issuecomment-472632579).
#### Version
Latest Tails and Bisq Release

### Expected behaviour
I expect the application to start and connect to the bisq network

### Actual behaviour
Aplication starts and surpasses the loading screen, bisq ui appears although get stucks on finding seed nodes. Before the work arounds listed above bisq could not load past stage 1/4. I get the warning message.

Dec-14 16:03:24.970 [JavaFX Application Thread] WARN  bisq.core.app.P2PNetworkSetup: onNoSeedNodeAvailable

Tails Os

**Comment by freimair** [comment]
https://bisq.wiki/Bisq_on_tails
