### ISSUE TITLE
Bug in handling of Failed trades between v1.2.3 & v1.2.4, user lost BTC from wallet

### ISSUE THREAD

**Issue by llhoppy** [bisq-network/bisq#3794]
### Description

Bisq V 1.2.3 
Trade had become stuck waiting for blockchain confirmation. A support ticket was created using ctrl+O. The mediator suspected the problem was due to the fee being too low. The support ticket was eventually closed and a payout issued. User accepted the payout from the mediator from Open Trades. The BTC appears in users wallet but the trade remained listed in Open Trades and the BTC was locked in a trade. 

Bisq V1.2.4
After upgrade upon first start of Bisq App user is prompted about an open trade (0BHgBN) being in a problem state and was prompted to move the trade to Failed Trades. User accepted the request and the trade was now moved from Open Trades to Failed Trades. The BTC that was previously locked in trade now disappeared from users wallet.

#### Version

1.2.4

### Steps to reproduce

Look at trade 0BHgBN for an example of this problem. User lost 0.157605 bitcoin from wallet.

Arbitrators payout was issued as follows:
Ticket closed on 22 Nov 2019 10:50:29
Summary:
Payout amount for BTC buyer: 0.015010 BTC
Payout amount for BTC seller: 0.157605 BTC
Summary notes:
Not published tx.
Next steps:
Open trade and accept or reject suggestion from mediator

### Expected behaviour

The Payout amount for BTC seller: 0.157605 BTC should have gone back to users wallet after the trade was moved from Open Trades to Failed trades.

### Actual behaviour

The Payout amount for BTC seller: 0.157605 BTC was lost from the users wallet. It was previously showing as Locked in Trade and vanished completely after the trade was moved to Failed trades.

### Screenshots
solved, screenshots removed

#### Device or machine

Qubes OS V 3.2.1
Dell Inspiron Laptop

#### Additional info

Bisq Logs are attached here:
solved, logs removed

**Comment by sqrrm** [comment]
Possibly related to #3764

**Comment by llhoppy** [comment]
Is anyone even looking at this problem? 0.15 BTC have been lost and I have been waiting weeks with no response!

**Comment by chimp1984** [comment]
@llhoppy Can you PM me on keybase? I will have a look.

**Comment by ripcurlx** [comment]
@llhoppy Was this issue solved for you already?

**Comment by llhoppy** [comment]
> @llhoppy Was this issue solved for you already?

Yes, it is resolved.
