### ISSUE TITLE
Not clickable tables - v0.4.1 - Win 10 x64

### ISSUE THREAD

**Issue by HostFat** [bisq-network/bisq#380]
It seems that these tables don't respond at any click.

<img width="917" alt="bs" src="https://cloud.githubusercontent.com/assets/644416/14524252/c162595c-0237-11e6-8a8a-b819e02294f3.png">

**Comment by ManfredKarrer** [comment]
That is intended. It should just give a very basic overview of the top 3 trades. The full overview is the at the offer book. I see that you have scrollbars... that should not be.... Unfortunately fonts are rendered a bit different on each OS. Need to adjust the height for the next version...

**Comment by HostFat** [comment]
v0.4.1 - On Win 10 x64

**Comment by ManfredKarrer** [comment]
I adjusted layout for next version.
