### ISSUE TITLE
Emphasize that traders engage in trader chat to solve trade problems

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#3801]
To reduce number of mediation disputes we should emphazise in the UI that users are using the trade chat and engage together to solve the problem without the need of a mediator.
@m52go @ripcurlx Could you have a look how we could achieve that? Improving some of the popup text might be one way. To make trader chat more prominent another....

**Comment by ripcurlx** [comment]
![Bildschirmfoto 2019-12-18 um 11 21 34](https://user-images.githubusercontent.com/170962/71077897-9bb7bc00-2188-11ea-808e-ee024e96beb1.png)
I think we should adapt this popup with a different text having as first option `Open trader chat` and as secondary option `Open support ticket`.

**Comment by m52go** [comment]
Suggestion below is general. Is there anything specific we want to convey here? Ideally I would like to include a link to chat rules to relieve users concerned to use the chat, but I think it might make the popup too long.

**New popup headline (optional)**

Just making sure 
[OR]
Are you sure?

**Popup text**

Have you tried trader chat? It's often the quickest and most efficient way to resolve disputes.

If you have not received payment, please avoid opening a ticket until the trade period is over.

Are you sure you want to open a support ticket?

**Comment by chimp1984** [comment]
@m52go I think it should have even more emphasize.

People are opening mediation tickets for support questions and getting signed. We have to make very clear that it only shoul dbe opened if the trade period is over and if they could not resolved it via trader chat. We have been a bit cautious when introducing trader chat but I think we can increase the weight of it for problem solution now as we only got positive feedback from it (zero reports about social engineering attempts or the like). Maybe we should also mention to use keybase support channel for questions and problems. We have to get the number of mediation cases down by > 50%.

**Comment by julianknutsen** [comment]
I imagine this discussion has already happened (feel free to point me to it), but why enable mediation at all before the trade period is over? When participating in a transaction there is already an agreement that it could take MAX_TRADE_DAYS to complete.

In the event of an issue < MAX_TRADE_DAYS the options are to either use the chat to solve an issue or wait until MAX_TRADE_DAYS and bring in a mediator.

Is there a good list of which valid issues were solved < MAX_TRADE_DAYS and what the drawback would be if these were instead solved >= MAX_TRADE_DAYS?

If successful mediations for support requests cause signed accounts, it may make sense to add a feature that allows the mediator to skip the signing for requests that are not relevant. This in addition to taking the fee should incentivize the cheaper support channels and offset the cost to the DAO for each case handled by a mediator.

**Comment by ripcurlx** [comment]
> I imagine this discussion has already happened (feel free to point me to it), but why enable mediation at all before the trade period is over? When participating in a transaction there is already an agreement that it could take MAX_TRADE_DAYS to complete.
> 
> In the event of an issue < MAX_TRADE_DAYS the options are to either use the chat to solve an issue or wait until MAX_TRADE_DAYS and bring in a mediator.
> 
> Is there a good list of which valid issues were solved < MAX_TRADE_DAYS and what the drawback would be if these were instead solved >= MAX_TRADE_DAYS?
> 
> If successful mediations for support requests cause signed accounts, it may make sense to add a feature that allows the mediator to skip the signing for requests that are not relevant. This in addition to taking the fee should incentivize the cheaper support channels and offset the cost to the DAO for each case handled by a mediator.

Yes, I agree that we probably should replace the `Get support` button with an `Open trader chat` button until the trade period is over.
