### ISSUE TITLE
Bitcoin localhost node detected pop-up

### ISSUE THREAD

**Issue by porcupinenick** [bisq-network/bisq#3805]
### Description

Pop-up regarding local Bitcoin node which is detected in Bisq.

#### Version

Bisq v1.2.4

### Steps to reproduce

1. Plug-in updating Bitcoin Node
2. Run Bisq

### Expected behaviour

I'm not sure what's supposed to happen. But is this the expected behavior?

### Actual behaviour

While running Bisq with a local Bitcoin node on it, there is the below screenshot which occurs. Is this expected?

### Screenshots

<img width="960" alt="Screen Shot 2019-12-18 at 1 02 34 PM" src="https://user-images.githubusercontent.com/24903257/71111910-6ca94680-2198-11ea-80ce-7dacdc2e1494.png">

#### Device or machine

macOS 10.15.2 Catalina

**Comment by ripcurlx** [comment]
Yes, that is the desired behavior. If we detect a local Bitcoin node we connect to it as it increases privacy and security for the user. The warning is just there to inform you that this is happening in the background.
