### ISSUE TITLE
gpg Bisq releases signatures

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#3811]
atm, the signature process with Bisq released files is that each file is provided with its own hash plus its own gpg signature.

I noticed that eg monero has a different process, where all files have their hashes in one unique hashes.txt file, and this global hashes.txt file is then signed.
So, instead of having 10 signature files, monero has only one.

I guess that from the safety point of view, this is the same (?).
And, if the previous assuption is right, I was wondering if the same lighter process could also be applied to Bisq ?

**Comment by ripcurlx** [comment]
Have to have a look at it. Thanks for pointing this out 👍
