### ISSUE TITLE
Bisq UI becomes unresponsive after running for some time

### ISSUE THREAD

**Issue by Rowdster** [bisq-network/bisq#3814]
### Description
Low resource VM, celeron class CPU, 5GB RAM, after running for several hours, perhaps 12-24, the bisq application base window UI becomes unresponsive and won't redraw.  resize does not refresh.  App must be force closed and restarted.  However, the application is processing orders, and new notifications (new windows) do appear

#### Version

Latest/github pull as of 12/19/2019
### Steps to reproduce

Without fail, run the application for several hours, 12-24 and the base window UI becomes unresponsive and will not refresh/redraw.  

### Expected behaviour

app should continue working normally. 

### Actual behaviour

App UI becomes "frozen" and will not redraw

#### Device or machine

Windows 10 in VM, 5GB RAM, Celeron processor

#### Additional info

the UI freeze does not appear to generate any additional logging.

I am running from source/java, so I do get the console logging, but it contains no useful screen related information.

**Comment by ripcurlx** [comment]
@Rowdster Is your memory filled up when it comes unresponsive (probably a memory leak)?
