### ISSUE TITLE
`ignoreLocalBtcNode` not recognized in `bisq.properties`

### ISSUE THREAD

**Issue by shawnyeager** [bisq-network/bisq#3820]
### Description

Including `ignoreLocalBtcNode=true` in `bisq.properties` does not appear to be read/recognized as with `--ignoreLocalBtcNode=true` on the command line.

#### Version

1.2.4 (macOS)

### Steps to reproduce

Append `ignoreLocalBtcNode=true` to `bisq.properties`.

### Expected behaviour

Bisq launches and ignores the local, running bitcoind in pruned mode.

### Actual behaviour

Bisq launches, sees the local node, and warns of running in pruned mode.

### Screenshots

<img width="1312" alt="Screenshot 2019-12-21 10 37 37" src="https://user-images.githubusercontent.com/980297/71310799-f007a980-23dd-11ea-9777-1064f091e7fd.png">

#### Device or machine

2017 MacBook Pro running macOS 10.15.2

**Comment by ripcurlx** [comment]
@shawnyeager We did some bigger changes on this front for v1.2.5 (already in master).  Would be great if you could test if it fixes your problem. Do other settings work if you use the `bisq.properties` file?

**Comment by phenomeus** [comment]
tested with 1.6.4. and its working, finally a good solid solution. thanks
