### ISSUE TITLE
Buy BTC: Wrong € amount in confirmation screen, Timeout Error breaks trade

### ISSUE THREAD

**Issue by MarcSte** [bisq-network/bisq#383]
I took an offer to buy bitcoin.
1. Wrong € amount shown on confirmation screen: Bought 0.25 btc @ 385€/btc. 0.5 btc were offered. I bought 0.25. Price shown on confirmation screen is 192,50€. See screenshot

<img width="857" alt="bs trade wrong amount" src="https://cloud.githubusercontent.com/assets/9436375/14583567/13224aaa-0426-11e6-9518-bc6ba6ffa6c4.PNG">
1.  An error occurred when taking the offer:

---

A timeout occurred.

The trading fee is already paid. In the worst case you have lost that fee. We are sorry about that but keep in mind it is a very small amount.
Please try to restart you application and check your network connection to see if you can resolve the issue.Please try to restart you application and check your network connection to see if you can resolve the issue.

---

Sending logfile via email

**Comment by MarcSte** [comment]
App restart didn't help. System restart didn't help. Cannot complete the trade.

Bitsquare 0.4.1
Win10  64 Bit

**Comment by ManfredKarrer** [comment]
Thanks for reporting:
Re 1: was a UI disply bug, fixed for the next verison.
Re 2: Will follow up by email...
