### ISSUE TITLE
Use only EUR when creating a SEPA payment account

### ISSUE THREAD

**Issue by seknokdkk** [bisq-network/bisq#3832]
We see a source of failure in non-EUR SEPA countries when creating SEPA payment accounts by selecting the default local currency instead of EUR. Payments in other currencies than EUR is not supported by SEPA.

> SEPA does not cover payments in currencies other than the euro. This means that domestic payments in SEPA countries not using the euro will continue to use local schemes, but cross border payments will use SEPA and euro against eurozone countries.

https://en.wikipedia.org/wiki/Single_Euro_Payments_Area

**Comment by lusarz** [comment]
How it should looks like on UI ? Currently there is combobox on the right side of country select:
![currency-combobox](https://user-images.githubusercontent.com/10059264/71470697-540ae300-27cd-11ea-9517-a7880d2f043c.png)

Should it be always disabled, like that:
![currency-combobox-disabled](https://user-images.githubusercontent.com/10059264/71470750-7d2b7380-27cd-11ea-8380-3d15ff20ef69.png)

or completely removed ?

**Comment by seknokdkk** [comment]
Don't remove it completely

**Comment by wiz** [comment]
@lusarz your PR #3833 looks like it will prevent people from creating new non-EUR accounts for SEPA, but it doesn't address the problem for non-EUR accounts that already exist - perhaps more work is needed to correctly resolve this issue?

**Comment by lusarz** [comment]
@wiz True, I forgot about this case. Thank you for good catch.

**Comment by lusarz** [comment]
@wiz What should happen when user has some non-EUR accounts ? Should they be automatically transformed into EUR accounts during application startup ? Should we show some information alert to user about that ?

**Comment by wiz** [comment]
That's a bit more tricky, we need to check if it would change the hash of the account and invalidate their "account signing"

**Comment by lusarz** [comment]
Ok, I'll try to reproduce this case tomorrow. If I have any thoughts or questions, I will post them here.

**Comment by seknokdkk** [comment]
Maybe easiest and best to erase affected accounts if you really want to handle the case. The user can then take notice.

**Comment by lusarz** [comment]
@seknokdkk Ok, erasing seems to be good idea to me.
@wiz What do you think ? 

Are you guys also considering possibility to not handling the case of existing non-EUR accounts ?

**Comment by lusarz** [comment]
Or maybe we should show some information that these accounts will be removed after some time (30days?) and then erase them ?

**Comment by wiz** [comment]
just hard-code the display to always show EUR
