### ISSUE TITLE
Do not allow domestic SEPA in payments accounts

### ISSUE THREAD

**Issue by seknokdkk** [bisq-network/bisq#3835]
It seems to be a source of trade failure from creating a SEPA payment account when same country is selectable and choosed by default in accepted countries.

A domestic trade will fail because a domestic SEPA payment can not be accomplished.

The origin country should be disabled in accepted countries selection when the payment account is created.

Unfortunately once a payment account is created it can not be changed, at least not manually.

![Skärmklipp](https://user-images.githubusercontent.com/59193427/71480179-2e470380-27f8-11ea-98e7-1f3148b05670.PNG)

**Comment by beingindot** [comment]
Is this issue different from [this one](https://github.com/bisq-network/bisq/issues/3724)?

If not could you add your requirements there.

**Comment by seknokdkk** [comment]
It is different. This is accepted countries. The other is bank banking residence.
