### ISSUE TITLE
Distance from marketprice miscalculated

### ISSUE THREAD

**Issue by MarcSte** [bisq-network/bisq#384]
In
- Sell BTC, Create offer Tab 

Distance from marketprice is off by 2 digits. I assume reference value is taken from wrong field when using 'fixed' price.

When you use 'percentage' everything's displayed correctly.

See screenshot:
<img width="851" alt="bs distance from market price" src="https://cloud.githubusercontent.com/assets/9436375/14599838/08659970-055a-11e6-8c8e-010ac2f93666.PNG">

When you actually use the percentage feature to determine the price, calculations are correct.

**Comment by ManfredKarrer** [comment]
Oops damn... yes 200 too much... so 2% instead of 202 % in your case....

But in case of fixed price its just informational so does not has any further consequences.

**Comment by ManfredKarrer** [comment]
Fixed.
Just uploaded a hotfix to the yesterdays replease. I did not create a new version as it was not a critical bug just a display issue.

Please re-install with the updated version on Github.
https://github.com/bitsquare/bitsquare/releases/tag/v0.4.2
