### ISSUE TITLE
Missing Bisq-1.2.4.dmg.asc file on bisq.network/downloads/

### ISSUE THREAD

**Issue by faxotherapy** [bisq-network/bisq#3844]
### Description

I try to verify the binary. So…

```
curl https://bisq.network/pubkey/29CDFD3B.asc | gpg --import
```
OK

```
gpg --digest-algo SHA256 --verify Bisq-1.2.4.dmg{.asc*,}
```
Does not work as I did not manage to find the `Bisq-1.2.4.dmg.asc` file on the Bisq.network site.

#### Version
1.2.4

#### Device or machine

---

Thank you for the help.

**Comment by ripcurlx** [comment]
@faxotherapy You can find it in the GitHub release: https://github.com/bisq-network/bisq/releases/tag/v1.2.4

- https://github.com/bisq-network/bisq/releases/download/v1.2.4/Bisq-1.2.4.dmg.asc
