### ISSUE TITLE
List price as BTC/ALT for altcoins globally

### ISSUE THREAD

**Issue by pmknutsen** [bisq-network/bisq#385]
Exchanges list prices of the exchange BTC/ALT for altcoins, but use FIAT/BTC for fiat (USD, EUR etc) pairs. Bitsquare currently lists altcoin prices as ALT/BTC and fiat as FIAT/BTC.

It would be preferable that Bitsquare follows conventions that users are accustomed to. Therefore, Bitsquare should follow the common convention of listing altcoin prices as BTC/ALT.

The current UI version supports switching the direction only in the drop-down menu in the toolbar.

The direction for altcoins should therefore be reversed (by default I would argue) in the Order Book chart, buy/sell listings, input fields when placing orders and anywhere else where the price of an altcoin is quoted.

**Comment by ManfredKarrer** [comment]
Hm... I don't know why the altcoin exchanges used that bad convention... also prices gets mostly un-readable (0.000003) fo low value coins. But I understand your concern and partly agree.
To switch might be confusing as well as it is context sensitive, so when u have in the offerbook eur selected and the in the market overview ETH then you would swap those prices when switching screens.
but yes, maybe its better... will consider a change....

**Comment by ManfredKarrer** [comment]
@pmknutsen: 
Can you discuss that issue with others in the forum? 
I am not sure what is the better way: 
Swapping when changing curreny or get used to the ALT/BTC version and do the swap manually if u prefer the other way round. 
I personally don't like the BTC/ALT as it is harder to read and remember (I remember better 5 000 000 than 0.0000002 - SC price for instance).

But I leave it to the community to find out what people prefer.
If there are sufficient people coming to a consensus that it should be changed I will setup a new GH issue for that task. 
Will close it for now to clean up a bit the issue list.
