### ISSUE TITLE
UI enhancement: do not place modal dialogs over other app's windows

### ISSUE THREAD

**Issue by ivilata** [bisq-network/bisq#386]
I've noticed that sometimes Bitsquare requests the attention of the user by showing a modal dialog. In my system (Debian with i3 wm), these dialogs appear over other applications' windows, so it's very easy to accidentally dismiss them by hitting enter while typing in the other app (e.g. a shell in a terminal emulator, a word processor or a chat window), and the situation gets more confusing since the Bitsquare window is brought to the front afterwards.

I haven't tested the situation in other platforms, so it might be a problem with i3.  However, I've seen in other applications (terminal emulators, Firefox) that they can set an emergency flag that visibly marks their window without disrupting other applications' input or focus. Maybe a behavior like that would be nicer.

Thanks!

**Comment by ManfredKarrer** [comment]
It is planned for future releases to use native notifiactions instead of the in-app notifications. Thought other popups would still trigger that. Would need support to know if the app is in background to handle display of such popups different.
