### ISSUE TITLE
Remove unused i18n strings

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/bisq#3860]
It seems like this string is no longer referenced from the source code, so we should remove it (see the link below). It creates confusion for translators who think that it should be translated. We should probably review the strings to check that there are no unused ones in general to save unnecessary work for translators.

```
portfolio.pending.support.text.getHelp.arbitrator=If you have any problems you can try to contact the trade peer in the trade \
  chat or ask the Bisq community at https://bisq.community. \
  If your issue still isn't resolved, you can request more help from an arbitrator.
```

https://github.com/bisq-network/bisq/blob/567684172d49a89c90119f41a329c0170930e111/core/src/main/resources/i18n/displayStrings.properties#L793

**Comment by ripcurlx** [comment]
I'll run a check for all translations to remove every key that is not used anymore.

**Comment by niyid** [comment]
@ripcurlx 
I had been unsure of the status (priority/importance) of this issue since it was listed for so long with no decoration. If you have not done it already, you may reassign to me.
