### ISSUE TITLE
Min security deposit should be worded in info popups

### ISSUE THREAD

**Issue by beingindot** [bisq-network/bisq#3868]
### Description
Since we have minimum security deposit (0.006 btc) it should be shown as minimum secuirty deposit instead of 6000% of trade amount.

#### Version
1.2.5

### Steps to reproduce
1. Fill 0.0001 btc as buy amount
2. verify 15% as security deposit
3. click Next Step 
4. popup appears with 6000% percent of trade amount for security deposit

### Expected behaviour
Better wording of minimum security deposit in popups and security deposit input field(if possible)

### Actual behaviour
popup doesnt have info about minimum security deposit

### Screenshots
![Screenshot from 2020-01-07 13-57-07](https://user-images.githubusercontent.com/55691179/71880586-aeedf400-3156-11ea-8868-3addef205e02.png)

**Comment by ripcurlx** [comment]
Yes, I also think the naming should be adapted for this cases. Same goes for trading fees. I'll have a look if I can come up with a quick fix.
