### ISSUE TITLE
Move seed node argument parsing to SeedNodeMain

### ISSUE THREAD

**Issue by ivilata** [bisq-network/bisq#387]
The `SeedNode` class contains a `processArgs(…)` method that processes command line arguments and sets up private fields so that the `createAndStartP2PService(boolean useDetailedLogging)` method can be used next, with a richer version of the method available for testing.  However, when running a seed node, the class with the `main(…)` method is `SeedNodeMain`, which instantiates a `SeedNode` and calls `processArgs(…)` and `createAndStartP2PService(…)`.

I think that it would make more sense for `SeedNodeMain` to parse command line arguments and instantiate a `SeedNode` with the needed parameters.  Also, a single version of `createAndStartP2PService(…)` would be needed, even for testing purposes.

Not an important issue, I can try to do a PR myself later.

**Comment by ManfredKarrer** [comment]
Yes agree, would make more sense.

**Comment by ivilata** [comment]
Also, `PeerManager.setMaxConnections()` is only called when parsing arguments, so that using `SeedNode.createAndStartP2PService()` directly doesn't set the maximum number of connections and it must be done by hand.
