### ISSUE TITLE
Price rounding with fixed price

### ISSUE THREAD

**Issue by dgyg** [bisq-network/bisq#3871]
* The price for an offer is fixed e.g. 6452.3042
* The maximum amount for this offer has been chosen: 0.05
* The fiat price results in having decimal places e.g. 6452.3042 * 0.05 = 322.61521
* The fiat price is rounded up 323.00
* The bitcoin amount is adjusted 323.00 / 6452.3042 = 0.050059636
* The bitcoin amount is now higher than the maximum amount to be traded
* The validation fails and the offer can not be taken

![bisq](https://user-images.githubusercontent.com/7886722/71925695-859a8b80-3189-11ea-9f3b-ed9c14b692f0.png)

**Workaround**: Adjust the amount to buy manually 
**Improvement**: The final fiat amount should be rounded down in this case e.g. 322.00

**Comment by ghost** [comment]
bad bot, still relevant.
