### ISSUE TITLE
Bisq does not handle SIGTERM properly

### ISSUE THREAD

**Issue by wiz** [bisq-network/bisq#3884]
[Background]
On posix/unix systems, when you send a SIGTERM to a process, it should save all data and gracefully shut down.

[How to Reproduce]
1) Prepare a Bisq Seednode using installer script
2) Start the Bisq Seednode service
3) Wait a few minutes
4) Stop the Bisq Seednode service

[Expected Result]
After step 4, Bisq should save all data and gracefully shut down within a few seconds.

[Actual Result]
Bisq's child Tor process gracefully shuts down, but Bisq does not. For the next 60 seconds, Bisq floods the logs with Tor connection failure errors, until systemd forcefully `kill -9`'s the Java process

[Log Snippet]
```
Jan 10 08:15:05 wizvm bisq-seednode[68826]: #011message=GetPeersRequest
Jan 10 08:15:05 wizvm bisq-seednode[68826]: #011throwable=java.io.IOException: Cannot connect to hidden service
Jan 10 08:15:05 wizvm bisq-seednode[68826]: #033[0;39m#033[34mJan-10 08:15:05.939 [SeedNodeMain] INFO  b.n.p.n.NetworkNode: onFailure at sendMessage: peersNodeAddress=extj4rlmchb3zzzn.onion:9999
Jan 10 08:15:05 wizvm bisq-seednode[68826]: #011message=GetPeersRequest
Jan 10 08:15:05 wizvm bisq-seednode[68826]: #011throwable=java.io.IOException: Cannot connect to hidden service
Jan 10 08:15:06 wizvm bisq-seednode[68826]: #033[0;39m#033[34mJan-10 08:15:06.339 [NetworkNode:SendMessage-to-bcrhutzsmvgvp6lh.onion:9999] INFO  b.n.p.n.NetworkNode: onFailure at sendMessage: peersNodeAddress=bcrhutzsmvgvp6lh.onion:9999
Jan 10 08:15:06 wizvm bisq-seednode[68826]: #011message=GetPeersRequest
Jan 10 08:15:06 wizvm bisq-seednode[68826]: #011throwable=java.io.IOException: Cannot connect to hidden service
Jan 10 08:15:06 wizvm bisq-seednode[68826]: #033[0;39m#033[34mJan-10 08:15:06.540 [SeedNodeMain] INFO  b.n.p.n.NetworkNode: onFailure at sendMessage: peersNodeAddress=ikicl65q45twvmyu.onion:9999
Jan 10 08:15:06 wizvm bisq-seednode[68826]: #011message=GetPeersRequest
Jan 10 08:15:06 wizvm bisq-seednode[68826]: #011throwable=java.io.IOException: Cannot connect to hidden service
Jan 10 08:15:06 wizvm systemd[1]: bisq-seednode.service: State 'stop-sigterm' timed out. Killing.
Jan 10 08:15:06 wizvm bisq-seednode[68826]: #033[0;39m
Jan 10 08:15:06 wizvm systemd[1]: bisq-seednode.service: Main process exited, code=killed, status=9/KILL
```

**Comment by ripcurlx** [comment]
@freimair Could you have a look at this? Thanks!

**Comment by wiz** [comment]
To be clear, this issue is not related to Tor, that is merely a symptom of the Tor process properly handling SIGTERM and Bisq ignoring it

**Comment by wiz** [comment]
@ripcurlx @freimair can you guys prioritize this issue? it really affects running bisq on linux because if you reboot a server you have a ~10% (guessing) chance of corrupting the bisq node from not getting shut down properly. one of my nodes got corrupted again today.

**Comment by freimair** [comment]
I will look into it

**Comment by freimair** [comment]
I have not seen any graceful shutdown attempts when shutting down any Bisq app product (except for the monitor) when not using the GUI. I strongly believe that adding such a thing will affect https://github.com/bisq-network/bisq/issues/4026.
