### ISSUE TITLE
Java Heap crash on ubuntu 19.10, bisq 1.2.5

### ISSUE THREAD

**Issue by coinzdude** [bisq-network/bisq#3892]
[bisq.log](https://github.com/bisq-network/bisq/files/4050140/bisq.log)
Logs attached.

**Comment by coinzdude** [comment]
Got a new crash
[bisq.log](https://github.com/bisq-network/bisq/files/4067821/bisq.log)

**Comment by ripcurlx** [comment]
Probably related to #3128, #3657, #3918, #3917.
