### ISSUE TITLE
DAO governance open proposals show delete icon on wrong items

### ISSUE THREAD

**Issue by wiz** [bisq-network/bisq#3899]
On my proposals, there is no "delete" icon visible, but there is for another CR by devin:

<img width="918" alt="Screen Shot 2020-01-14 at 20 09 24" src="https://user-images.githubusercontent.com/232186/72339530-c6eee600-3709-11ea-9524-45b2cf488696.png">

Further down the list, I am not beingindot but for some reason a "delete" icon appears on his CR for me.

<img width="917" alt="Screen Shot 2020-01-14 at 20 07 31" src="https://user-images.githubusercontent.com/232186/72339434-9018d000-3709-11ea-9091-80755f62ec2f.png">

**Comment by niyid** [comment]
Strange. I didn't notice any discrepancies on my list.

**Comment by chimp1984** [comment]
I think that happens at scrolling with some missing updates/resets at cell renderers.

**Comment by niyid** [comment]
> I think that happens at scrolling with some missing updates/resets at cell renderers.

@wiz 
If the suggestion by @chimp1984 is correct, then the result will never be consistent - meaning I expect a different result on each try in reproducing the result.

I will suggest you try this again and see the result.

**Comment by ripcurlx** [comment]
I quickly read through the code in ProposalsView and it could happen if the `iconButton` that is returned from `item.getIconButton()` is null. In that case the graphic is not updated and an old value could be seen. Need to be checked if that actually can happen (probably can, otherwise the iconButton null check is unnecessary)

**Comment by niyid** [comment]
It will be safe to call **`setGraphic(null)`** in the **`else`** block of **`if (iconButton != null) {`**.
