### ISSUE TITLE
Support for multiple languages

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#390]
Support for localized strings is setup but should be evaluated if the current solution (java resource bundle properties) is the best solution. That was used as it had good support for JavaFX but as FXML is (nearly) not used anymore that requirement can be ignored.
Then we would need to find the best soltuion for translation management (transiflex?).
And then convert all the display strings to the locale (property) files.

**Comment by JoshLambda** [comment]
Localization management services do support Java .properties files (transifex, crowdin...).Then choosing one is more a matter of features and pricing.

**Comment by JoshLambda** [comment]
Here is a list of online translation plateforms, all do support `.properties` files according to their websites
http://pootle.translatehouse.org/ _(free, open source, self-hosted)_
http://zanata.org/ _(free, open source, self-hosted)_
https://poeditor.com/ _(free up to 1000 strings)_
https://www.transifex.com/ _(best known but most expensive)_
https://crowdin.com/

**Comment by ManfredKarrer** [comment]
.properties files are very comfortable to edit if u have intellij (community verison is free). i know its not suited for non devs but just to mention it...
encoding must be utf8 to have no issues with special chars (as far i remember).

**Comment by WillemKvanderMerwe** [comment]
Hi Manfred, I would also like to help, as I mentioned on another post I can translate to South African (Afrikaans). Would you be able to point me in the right direction Re: What software to use to edit it?

PS: I started learning javascript about a week ago and that is the extent of my knowledge in programming, so maybe simpler is better?

**Comment by ManfredKarrer** [comment]
@WillemKvanderMerwe Thanks! We still are not ready for translation work. We need a developer who take that as his task. I hope after my tour mid june we are able to start on that.
You will not need prgramming skills we will use some simple tools for the translators.

**Comment by haiqu** [comment]
I have added many more .properties files and they are available to Manfred in the PR made a few days ago. There is also a forum topic asking for help with translations of them: 

https://forum.bitsquare.io/t/any-cunning-linguists-among-us/721

**Comment by haiqu** [comment]
Just went through my frinds list on Facebook, which is only 158 people. I have contacts who are native speakers in Bosnian, Greek, French (Belgium), Flemish (Belgium), French (Canadian), Hebrew, Vietnamese, Portuguese, Danish, German, Lithuanian, Spanish (Chile) and one whose second language is Maltese (Australian).

If we all checked our friends lists I think it could be done fairly easily.

**Comment by haiqu** [comment]
See also #145

**Comment by riclas** [comment]
@haiqu  any reason why we haven't setup a transifex page for the project yet?
I don't mind taking on that task and putting our properties files there.

@ManfredKarrer could you create a branch for us to PR property string changes and translations into?

**Comment by haiqu** [comment]
1. It's a commercial website.
2. Because I've been investigating other options.
3. Only about half of the text is in the English property file.
4. Lack of interest or inability to follow through from most "volunteers".
5. I've been doing embedded programming for the past few weeks.

**Comment by riclas** [comment]
even though it's commercial, it's free for OSS projects, so we should be good.
https://forum.bitsquare.io/t/any-cunning-linguists-among-us/721/31?u=riclas
besides, it's widely used and requires little setup.

If we don't setup properly it's harder to get the volunteers to work... That's why i'm saying we should setup the project asap, and a branch to put more text into the property file. I'll setup the project on transifex if noone objects.

**Comment by ManfredKarrer** [comment]
I would recommend to first move all strings to the property files, otherwise maintenance becomes much harder if part is translated and u need to add the new strings all the time to many language files.
I am fine with transifex and I think it makes it easier to non-tech contributors to help.

Here is a fresh branch created form the Dev branch:
https://github.com/bitsquare/bitsquare/tree/Translations

Please keep it in sync with dev otherwise merge might get hard.

**Comment by riclas** [comment]
That's quite simple to manage on transifex afaik, updating the property files with new strings.

**Comment by riclas** [comment]
@haiqu @ManfredKarrer has created the transifex project for us.
Can you tell me where i can see what languages you have collected translations for, so i can upload their files?

Anyone who would like to help translating Bitsquare, please go to: https://www.transifex.com/bitsquare

**Comment by haiqu** [comment]
The link is in the referenced forum thread you mentioned earlier.

**Comment by ManfredKarrer** [comment]
We have now all display strings supported for translation. Please help us to get the missing translation strings filled up!
https://forum.bitsquare.io/t/any-cunning-linguists-among-us/
https://www.transifex.com/bitsquare/bitsquare/

**Comment by haiqu** [comment]
I haven't been on github in months and find that several people have sent me files for translation. One has done all of Croatian (in both Cyrillic and Latin) and the other made some German corrections. I'll try to find time to upload them to Transifex.

**Comment by ManfredKarrer** [comment]
@haiqu Please coordinate with @riclas, he manages transifex

**Comment by riclas** [comment]
@haiqu let me know your transifex id and i'll add you as project manager so you can upload those resources.

**Comment by haiqu** [comment]
Username: haiqu

Thanks riclas

**Comment by rudygodoy** [comment]
Hello, I was unaware of the project using Transifex until now. I've updated the Spanish translation for grammar/spelling fixes from the file `in_dev/displayStrings_es.properties`. I've already asked to be included in Transifex, btw. Keep up the good work!

**Comment by rudygodoy** [comment]
I've got access to Transifex but it seems that the account for Bitsquare has reached it's plan limit. Let me know how to proceed.

**Comment by riclas** [comment]
please disregard that message and proceed to translations.

2017-06-12 17:06 GMT+01:00 Rudy Godoy <notifications@github.com>:
