### ISSUE TITLE
Custom node constant disconnect and reconnect

### ISSUE THREAD

**Issue by Bayernatoor** [bisq-network/bisq#3900]
### Description

Unable to connect to Bisq using my personal node running through Tor. Bisq does start up fine but is unable to hold a connection to my onion address. See logs for details. 

#### Version

1.2.5

### Steps to reproduce

Happens every time i start Bisq. Unable to provide steps on how to reproduce.

### Expected behaviour

Prior to version 1.2.4, I had not encountered this issue. Bisq connected to my node without any problems. 

### Actual behaviour

Connection to my node dies constantly, Bisq reconnects for a second then the connect dies again.

#### Device or machine

Running Ubuntu 19.10

#### Additional info

![Bisqlog](https://user-images.githubusercontent.com/55212954/72369719-4c50a700-36c6-11ea-9e0b-86a8108dea76.png)

**Comment by ripcurlx** [comment]
@freimair Do you have an idea what could cause this issues?

**Comment by freimair** [comment]
@AlBayer can you please elaborate

> Unable to connect to Bisq using my personal node running through Tor. Bisq does start up fine but is unable to hold a connection to my onion address. See logs for details.

I do not understand exactly what you mean:
- "using my personal node": what is "node" in this context? is it your Bisq client, a local BTC node, another Bisq client, an external Tor instance?
- "unable to hold a connection to "my onion address": what service does "my onion address" provide?

**Comment by Bayernatoor** [comment]
@freimair 

Hey, sorry about the delay. By node i mean my  local BTC node. My BTC node runs over tor therefore i don't have a public address i have an onion address such as: sslmjhifufdyfgb4.onion:8333. 

So in Bisq I'll select Use custom Bitcoin Core nodes as well as Use Tor for Bitcoin network. Doing this using my local BTC node gives me the above error. 

Let me know if you need more info!

**Comment by Bayernatoor** [comment]
Solved : bitcoin v0.19 has disabled peerbloomfilters by default therefore whenever BISQ tries to connect to my local node it gets disconnected immediately. This can be fixed by including peerbloomfilters=1 in the bitcoin.conf file or by whitelisting certain connections.

https://github.com/bitcoin/bitcoin/pull/16248

https://github.com/bitcoin/bitcoin/issues/17589
