### ISSUE TITLE
BitcoinAverage Price feed for DAI broken.

### ISSUE THREAD

**Issue by opticbit** [bisq-network/bisq#3901]
### Description

Price feed for DAI stopped.
DAI is USD stable so DAI/BTC should be similar to USD/BTC
DAI/USD is not a perfect 1:1 but stays close.

using usd/btc till the proper data feed is back is close enough for me.  others may not agree.

#### Version

1.2.5

### Steps to reproduce

check DAI price from market tab.
DAI price when creating buy/sell offer

### Expected behavior

show live price DAI/BTC

### Actual behavior

Only Last trade price is available.

#### Device or machine

Mac OS 10.15.2
Ubuntu 18.4, 19.10

#### Additional info

problem started around the time of the change over from DAI to SAI (single collateral to multi collateral)

Broken Feed: https://bitcoinaverage.com/hr/exchanges/bitfinex/dai-to-btc

**Comment by beingindot** [comment]
@ripcurlx suggested it might be because of name change from DAI to SAI. 

however instead of renaming it to SAI, we can keep the name as DAI. since SAI is going to be deprecated soon as per their notice.
https://blog.makerdao.com/looking-ahead-how-to-upgrade-to-multi-collateral-dai/

@opticbit what could be your pick here.

**Comment by beingindot** [comment]
In prod,am able to see market value. 
Hence i tried to reproduce in regtest environment, able to get market price there also. so not sure about this issue.

![Screenshot from 2020-01-30 18-13-38](https://user-images.githubusercontent.com/55691179/73450868-4a583a80-438c-11ea-8776-3ed0a035f36c.png)

Only problem in prod i found is, could not create "DAI" altcoin account.

**Comment by cd2357** [comment]
Closing, as the DAI pricefeed is now working (see above comment, also tested with latest version).
