### ISSUE TITLE
Seller unable to confirm payment received

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/bisq#3905]
### Description
Many mediation cases lately are a result of seller not being able to confirm the payment has been received. On most cases the buyer confirms they have pressed ‘payment made’ but for some reason is not showing on the other end.

### How to fix
It's hard to reproduce and might be a result of a missed mailbox message. A simple option ask for a resend from the seller side might be enough. Thinking a bit further it would be nice to be able to confirm transmission failures of these messages. Not sure how that could be done though.

I can't think of any other reason that the seller wouldn't see the confirm payment button than a failed message.

**Comment by stejbac** [comment]
That happened to me once in November (as the seller). I tried searching the log for `CounterCurrencyTransferStartedMessage` and couldn't find anything associated with that trade, so I guess the message was never sent (even though it showed up in the log for other buy & sell trades). Restarting the application didn't help. Unfortunately, I wasn't able to find out if the message had appeared in the buyer's logs anywhere, as they weren't really technical enough to locate and search the logfile, it seems.

**Comment by sqrrm** [comment]
@stejbac I suspect the message got lost somehow but I don't know how. I have a fix that allows the seller to send a refresh request to ask the buyer to send the `CounterCurrencyTransferStartedMessage` again. It seems to work but I'm not sure if this is the right way to go in the long run. I'll push a PR later to at least avoid this issue as it seems to be happening frequently.
