### ISSUE TITLE
Arbitrator payout options set wrong values

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/bisq#3906]
### Description
Arbitrator reported that the `BTC seller gets trade amount payout` is giving the seller more than the option `BTC seller gets all`.

Have not tried to reproduce but sounds like a simple issue with calculation and should be reproducible.

**Comment by sqrrm** [comment]
I have managed to reproduce this by starting a trade in 1.2.4 with a low security deposit and running the mediator in version 1.2.5.

The new mediation payout rules force the min payout to non zero (Restrictions.getMinRefundAtMediatedDispute(), 0.003 BTC currently) which works well with trades started in client 1.2.5 but might not work nicely with all 1.2.4 trades.

I suggest the mediator to run 1.2.4 for trades that need it.

**Comment by ripcurlx** [comment]
Will be fixed with v1.2.6 which will be set as minimum required version after a couple of days.

**Comment by sqrrm** [comment]
I think this is mainly a problem for old trades, but at least there should be a way to finalize those disputes for the mediator.

**Comment by sqrrm** [comment]
Won't fix, mediators seem ok with handling it through the old client.
