### ISSUE TITLE
can't buy order - peer offline

### ISSUE THREAD

**Issue by lattice0** [bisq-network/bisq#393]
Every time I try to buy an order from my friend, it stays "checking ir order is available" and then says that I cannot take that order because the offerer is offline. Bitsquare twitter profile said they could buy the order, so the problem is with my PC. I'm running debian 8 x64.

**Comment by ManfredKarrer** [comment]
I discovered the reason for that problem. Just wondering that it works for others. but anyway i will release today a new version where that is fixed.
