### ISSUE TITLE
Bisq doesn't connect to default Bitcoin Core version v0.19.0.1

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#3935]
### Description

The default Bitcoin Core version v0.19.0.1 can't connect to Bisq 

#### Version

Bisq v1.2.5 and Bitcoin Core version v0.19.0.1

### Steps to reproduce

Update to Bitcoin Core version v0.19.0.1

### Expected behaviour

Bisq should recognize that there's a local Bitcoin node and connect to it.

### Actual behaviour

Bisq does recognize that there's a local Bitcoin node running but can't connect to it and instead it shows "Bitcoin network peers: 0" and keeps printing the following in the command line:

``
Feb-03 22:36:08.775 [NioClientManager] INFO  org.bitcoinj.core.PeerGroup: [127.0.0.1]:8333: New peer      (1 connected, 0 pending, 1 max) 
Feb-03 22:36:08.775 [NioClientManager] INFO  org.bitcoinj.core.PeerGroup: Setting download peer: [127.0.0.1]:8333 
Feb-03 22:36:08.775 [NioClientManager] INFO  o.b.c.l.DownloadProgressTracker: Chain download switched to [127.0.0.1]:8333 
Feb-03 22:36:08.778 [NioClientManager] INFO  org.bitcoinj.core.PeerGroup: [127.0.0.1]:8333: Peer died      (0 connected, 0 pending, 1 max) 
Feb-03 22:36:08.778 [NioClientManager] INFO  org.bitcoinj.core.PeerGroup: Download peer died. Picking a new one. 
Feb-03 22:36:08.778 [NioClientManager] INFO  org.bitcoinj.core.PeerGroup: Unsetting download peer: [127.0.0.1]:8333 
Feb-03 22:36:08.778 [PeerGroup Thread] INFO  org.bitcoinj.core.PeerGroup: Peer discovery took 5.771 μs and returned 0 items 
Feb-03 22:36:08.779 [PeerGroup Thread] INFO  org.bitcoinj.core.PeerGroup: Waiting 1500 msec before next connect attempt to [127.0.0.1]:8333 
``

### Screenshots

![bisq-alertb](https://user-images.githubusercontent.com/44140017/73697799-6420b700-46d7-11ea-81be-464ac6a2f6fa.png)

#### Device or machine

64-bit Pop!_OS 18.04

#### Solution

This is solved by adding
``
peerbloomfilters=1
``
to the bitcoin.conf file. This info should be added to the "Background information" text box that alerts that Bisq has detected a local node and to make sure that it's not pruned. An additional note should warn Bitcoin Core 0.19 users of this issue.

**Comment by ripcurlx** [comment]
Related to https://github.com/bisq-network/bisq/issues/3273. See https://github.com/bisq-network/bisq/issues/3273#issuecomment-581488897

**Comment by ripcurlx** [comment]
Hopefully @dmos62 is able to detect this somehow for a local node. Worst case would be as suggested by you to add this and the not use a pruned node info to the Background information.

**Comment by ripcurlx** [comment]
I've added an additional message in https://github.com/bisq-network/bisq/pull/3939 for our v1.2.6 release.
