### ISSUE TITLE
Java Heap Space

### ISSUE THREAD

**Issue by mpolavieja** [bisq-network/bisq#3936]
### Description

Error - Java Heap Space

#### Version

version 1.2.6

### Steps to reproduce

This happened after leaving Bisq running for several days.  This is what I do all the time and it did not happen before, so I don´t know how to reprocude it

#### Device or machine

Windows 7 64bit (not supported anymore by Microsoft)

**Comment by ripcurlx** [comment]
Probably related to #3787 on Windows.
Linux memory issues for reference as they might all be related: #3128, #3657, #3918, #3917, #3686, #3677, #3343
MacOS memory issues for reference as the might all be related: #3786

**Comment by chimp1984** [comment]
Can you try out the recommendations at https://github.com/bisq-network/bisq/issues/3918#issuecomment-607198677 ?

**Comment by M0ns1gn0r** [comment]
Bisq (v1.5.9) consumed ~3.5Gb on my Win 7 x64 until I went to `Bisq.cfg` and added
```
[JVMOptions]
-XX:MaxRAM=4g
```

Now it consumes 1.3 Gb.

**Comment by cd2357** [comment]
Should be fixed in the most recent release (v1.6.4) which brings several UI performance improvements and generally reduces system resource consumption (especially RAM). Please try it out and let us know if it's still an issue for you.
