### ISSUE TITLE
popup warning not needed for bisq offer creation

### ISSUE THREAD

**Issue by beingindot** [bisq-network/bisq#3949]
### Description

while creating buy offer with bsq, it shows popup that percent based price not available whereas it was not there in UI. hence popup not needed.
#### Version
1.2.6

### Steps to reproduce
1. start alice
2. enter amount of btc to buy
3. enter fixed price in btc(0.0001)
4. press tab

### Expected behaviour
No popup needed here.

### Actual behaviour
popup warning comes about percent based price

### Screenshots
![Screenshot from 2020-02-07 14-51-51](https://user-images.githubusercontent.com/55691179/74017503-5cecf800-49ba-11ea-949d-2ea94594b004.png)

#### Device or machine

Ubuntu 18.04

**Comment by ripcurlx** [comment]
I think we need the warning or some similar kind of information as users might not be aware why they can only set fixed price offers at that point of time.
