### ISSUE TITLE
List StorJ Token

### ISSUE THREAD

**Issue by konard** [bisq-network/bisq#3955]
Please fill in the following data to request for a new asset to be listed on Bisq. For more details, be sure to read [the full documentation](https://docs.bisq.network/exchange/howto/list-asset.html) on adding a new asset.

### 1. Asset name
StorJ

### 2. Ticker
[STORJ](https://coinmarketcap.com/currencies/storj/)

### 3. Block explorer URL
https://etherscan.io/token/0xb64ef51c888972c908cfacf59b47c1afbc0ab8ac

### 4. Additional technical requirements (yes/no)
no

### 5. Initial coin offering (yes/no)
no

**Comment by konard** [comment]
Any news on that?

**Comment by konard** [comment]
Hello?

**Comment by cd2357** [comment]
Closing, because asset listing is put on hold: https://github.com/bisq-network/proposals/issues/166
