### ISSUE TITLE
Missing dark mode styling of popover trade period warning box

### ISSUE THREAD

**Issue by stejbac** [bisq-network/bisq#3957]
### Description

In dark mode, the _"If the period is exceeded..."_ warning box of the info popover in the trade step view appears to have the wrong styling. It looks like it should be dark yellow/pink rather than the same light yellow/pink for both modes. This also makes the warning text hard to read in dark mode.

#### Version

Latest snapshot of master.

### Steps to reproduce

Select dark mode, start a trade and check the info popover

### Expected behaviour

Different background colour in dark mode (say, dark yellow), to match the rest of the popover.

### Actual behaviour

Same warning message background colour (light yellow/pink) in light and dark mode.

### Screenshots

![Warning Box Styling](https://user-images.githubusercontent.com/54855381/74135657-9a34ce00-4be4-11ea-95dc-35b405ceafc1.png)

#### Device or machine

Linux

#### Additional info

N/A

**Comment by ghost** [comment]
css `.warning-box` should be customized in

 `theme-light.css` :

    .warning-box {
        -fx-background-color: -bs-yellow-light;
    }

`theme-dark.css` :

    .warning-box {
        -fx-background-color: -bs-color-primary-dark;
    }

**Comment by cd2357** [comment]
Closing, as it was fixed in #4316

**Comment by ghubstan** [comment]
Styling issues may be related to https://github.com/bisq-network/bisq/issues/4639
