### ISSUE TITLE
App doesn't start on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by dskloet** [bisq-network/bisq#396]
I have installed Bitsquare but when I try to run it it says it doesn't exist.

```
$ sudo dpkg -i Bitsquare-32bit-0.4.3.deb 
(Reading database ... 665175 files and directories currently installed.)
Preparing to unpack Bitsquare-32bit-0.4.3.deb ...
Removing shortcut
Unpacking bitsquare (0.4.3) over (0.4.3) ...
Setting up bitsquare (0.4.3) ...
Adding shortcut to the menu

$ ls -l /opt/Bitsquare/
total 580
drwxrwxr-x 2 root root   4096 Apr 24 18:38 app
-rwxr-xr-x 1 root root   8076 Apr 23 12:48 Bitsquare
-rw-rw-r-- 1 root root    165 Apr 23 12:48 Bitsquare.desktop
-rw-rw-r-- 1 root root  28734 Apr 23 12:48 Bitsquare.png
-r--r--r-- 1 root root 539118 Apr 23 12:48 libpackager.so
drwxrwxr-x 3 root root   4096 Apr 24 18:38 runtime

$ /opt/Bitsquare/Bitsquare 
-bash: /opt/Bitsquare/Bitsquare: No such file or directory
```

**Comment by ManfredKarrer** [comment]
@ivilata Do you have any idea? I am not so familiar with linux.... But never heard about that issue before...

**Comment by vergecurrency** [comment]
try ./Bitsquare? or do you not have permission? 

try chmod 755 /opt/Bitsquare/

**Comment by vergecurrency** [comment]
i was able to reproduce this error on a fresh Ubuntu 14.04 vm. im looking for a solution.

**Comment by vergecurrency** [comment]
@dskloet sudo apt-get install libc6-i386 lib32stdc++6

**Comment by dskloet** [comment]
Thanks. I will try it later.
Will you fix the package file to include a dependency on that?

**Comment by ivilata** [comment]
@dskloet It looks like you have installed a 32-bit package in a 64-bit environment. You can make sure by running `uname -m` in a terminal. If it says `x86_64` you should install the 64-bit package.

@vergecurrency's solution may also work since recent Ubuntu/Debian versions allow installing 32-bit packages in 64-bit environments, and they provide 32-bit versions of some basic libraries as well.  But you should be better off and avoid other potential issues by running the 64-bit version.

**Comment by dskloet** [comment]
Thanks, I'll try the 64 bit version. Is it possible it wasn't available on the download page before? I don't remember seeing it but maybe I just wasn't paying attention.

**Comment by dskloet** [comment]
I was able to start the 64 bit version but before I finished reading the user agreement it crashed

```
org.bitcoinj.core.ProtocolException: Peer does not have a copy of the block chain.
    at org.bitcoinj.core.Peer.processVersionMessage(Peer.java:459) ~[Bitsquare-0.4.3.jar:na]
    at org.bitcoinj.core.Peer.processMessage(Peer.java:376) ~[Bitsquare-0.4.3.jar:na]
    at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:180) ~[Bitsquare-0.4.3.jar:na]
    at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223) [Bitsquare-0.4.3.jar:na]
    at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) [Bitsquare-0.4.3.jar:na]
    at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) [Bitsquare-0.4.3.jar:na]
    at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60) [Bitsquare-0.4.3.jar:na]
    at com.google.common.util.concurrent.Callables$3.run(Callables.java:95) [Bitsquare-0.4.3.jar:na]
    at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:35) [Bitsquare-0.4.3.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
Apr-25 09:02:25.695 [NioClientManager] WARN  o.b.n.ConnectionHandler: Error handling SelectionKey: java.lang.IllegalStateException 
*** Error in `/opt/Bitsquare/Bitsquare': double free or corruption (out): 0x00007fc49800fd40 ***
Aborted (core dumped)
```

**Comment by ManfredKarrer** [comment]
That error is not critical, not exactly sure what causes it, maybe full nodes who are kind of sybils (not delivering the data) or it comes when there are issues with ipv6. but that should nto cause a crash. when u install the 64 bit version u might remove all old files.

**Comment by vergecurrency** [comment]
@dskloet are you behind a firewall?

**Comment by dskloet** [comment]
I did `sudo dpkg -r Bitsquare` before installing the 64 bit version.
I don't have a firewall but I have a local network so it's possible peers won't be able to connect to me before I do some configuring.
I don't know what you mean by the error not being critical but the program crashed and it dumped core.
However, I just tried again and while I get many errors on the console it didn't core dump again so far.

**Comment by ManfredKarrer** [comment]
" error not being critical" I referred to the "ProtocolException: Peer does not have a copy of the block chain." I have seen that error often as well. Though not sure if the "Error handling SelectionKey: java.lang.IllegalStateException " is related to your issue.

**Comment by ManfredKarrer** [comment]
Have you tried to unistall the old version and install the beta (0.4.4)? Do u still have the issues?

**Comment by dskloet** [comment]
I was able to start the 64 bit version of the app. There were still many errors on the console but I guess they were not critical as you said.

**Comment by ManfredKarrer** [comment]
Yes those error are mostly from BitcoinJ and not critical.
