### ISSUE TITLE
Bisq v1.2.6 fails to start on macOS Mojave

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#3969]
#### Version

v1.2.6

### Steps to reproduce

Run the release build macOS executable on macOS Mojave (10.14.6 in my case)

### Expected behaviour

App should start up as per usual without errors.

### Actual behaviour

App freezes up at what appears to be the point the password prompt would show up. It behaves as if a modal popup (such as the password prompt) were present, but no such popup is visible. The UI becomes unresponsive to any click and system error bells are sounded on every attempt.

### Screenshots

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/301810/74469266-9c28b680-4e9c-11ea-8e2b-430653a09d68.png">

Notice the fuzzed-out background, again, as if a modal popup or dialog were in the foreground.

#### Device or machine

macOS 10.14.6 (18G103)

#### Additional info

We've verified that the change that caused this problem is PR #3883. It is unknown as to why exactly this change causes this problem, and why it causes it only on Mojave (Catalina is fine, and High Sierra is fine). @ripcurlx is preparing a v1.2.7 hotfix with this change reverted as we speak.

Note that at least two other users reported this issue as well:

1. https://bisq.community/t/new-install-not-starting-up/8963/5
2. https://www.reddit.com/r/bisq/comments/f3afym/stuck_on_latese_update_grey_screen/

**Comment by cbeams** [comment]
I can confirm that the newly-released v1.2.7 resolves this problem for me. Thanks @ripcurlx, and please close this issue at will.

**Comment by ripcurlx** [comment]
Closing as complete with v1.2.7.
