### ISSUE TITLE
Trading fee decimals not displayed

### ISSUE THREAD

**Issue by MwithM** [bisq-network/bisq#3972]
### Description

After #3926 the trading fee prices converted to EUR is not displaying decimals when creating or taking an order. I'm using Bisq v1.2.7

### Expected behaviour

At least for EUR, where decimals have significant value, it's preferred to display one or two decimals.

### Screenshots

![paste](https://user-images.githubusercontent.com/50149324/74587588-f63c8f80-4ff4-11ea-977d-a4e51747f702.png)

CC @milesap

**Comment by ghost** [comment]
I’ll investigate and fix. I agree that the fee amounts should not be rounded.
