### ISSUE TITLE
Notifications on mobile confusing flow

### ISSUE THREAD

**Issue by gustavonalle** [bisq-network/bisq#3981]
1) I downloaded the BISQ app for android;
2) Sent an email with the token to myself;
3) Pasted the token on BISQ: is there no OK, CONFIRM, TEST button? Simply pasting it is enough?
4) Nothing arrives in the phone, it keeps on the screen with some text and "Resend email link"

What now?

**Comment by ghost** [comment]
After messing with alerts (added one for price), some notifications starts to arrive, with text "+ Bisq Notification", when I click on it, it opens the app and shows the app with some text and a button "PAIR"....

**Comment by ripcurlx** [comment]
Yes, UX on this should be improved. If you get a notification paring should have worked, but it looks like as if your client can't decrypt the message. @joachimneumann Do you have an idea what could going wrong?

**Comment by ghost** [comment]
Indeed, I get notifications for trades but they all have the text "+ Notification" and the app on android always asks me to pair

**Comment by MwithM** [comment]
This issue was already open here:
https://github.com/joachimneumann/bisqremote_Android/issues/11
