### ISSUE TITLE
Utilizing the Enable Checkbox Results in Unexpected Results When Multiple Orders Exist

### ISSUE THREAD

**Issue by dav1dpgit** [bisq-network/bisq#3984]
### Description
When multiple orders are open, when trying to utilize the "Enable" checkbox to deselect and select what order should be displayed, multiple orders appear to change their classification from Enabled to Disabled, or Disabled to Enabled, across multiple positions with a single click.

#### Version
1.2.7

### Steps to reproduce
Create multiple bids and offers across many currencies.  In my case, the number of open orders are above 30, and the list of open orders on the PORTFOLIO=>MY OPEN ORDERS extends below the bottom of the screen.  Scroll down below the bottom of the screen (this is important to cause the bug.)  Upon attempting to enable or disable a given transaction after scrolling down—particularly after resorting the list by buy/sell or by currency—the results are not as expected.

### Expected behaviour
Only the selected trade should be toggled between enabled and disabled.

### Actual behaviour
Multiple transactions toggle between enable and disable, sometimes not including the actual intended toggle target trade.  It is difficult to discern whether the list resorts, as well.

### Screenshots
Prior to scrolling down:
![image](https://user-images.githubusercontent.com/60247151/74728128-94468900-5285-11ea-998a-29e32103dcc2.png)

Slight scroll down:
![image](https://user-images.githubusercontent.com/60247151/74728178-a1fc0e80-5285-11ea-958f-38cc956cbece.png)

Results after clicking the 7th trade on the list (one click); note the changes at the bottom:
![image](https://user-images.githubusercontent.com/60247151/74728429-146cee80-5286-11ea-9aaa-c2886b8dc8b2.png)

#### Device or machine
PC Windows 10

**Comment by ripcurlx** [comment]
Sounds like a rendering issue on the list. Did you check if also all of them were removed from the orderbook?

**Comment by dav1dpgit** [comment]
I could not fully confirm one way or the other, but cursory review showed only the clicked item (whether or not the check mark changed) was the only thing changed in the order book.

**Comment by beingindot** [comment]
I'm able to reproduce it now.
