### ISSUE TITLE
Short questions for students.

### ISSUE THREAD

**Issue by eupn11** [bisq-network/bisq#3989]
Hi guys!

I am part of a group of students, and for a certain course (digital innovation) we want to learn about how a github project is coordinated. We are looking for two contributors in this project, who want to help us out. We have some short questions. We are willing to contribute to this project as well, by for example testing out.

You can email me at eupn11@gmail.com

**Comment by ripcurlx** [comment]
@eupn11 Using a GitHub issue is not the right place to ask this. Please join us on keybase e.g. in the #dao channel.
