### ISSUE TITLE
Allow emptying wallet with sales

### ISSUE THREAD

**Issue by Giszmo** [bisq-network/bisq#3993]
### Description

Bisq allows funding trades with the internal wallet but if the amount defined is 1sat more than the funds available, your only option is to cancel the offer and make a new one from scratch and if it's 1000sat less, you produce a change output that will link this trade with the next one.

#### Version

1.2.7

### Expected behaviour

Provide an easy way to empty the wallet. The amount field should have a "max" option.

#### Further ideas

Not being able to empty the wallet in this way is bad for privacy as trades become linked on the blockchain. This same issue applies for external wallet funding, as there again I cannot empty my external wallet accounts.

I try to rotate accounts and often remain with odd amounts that I would love to sell on bisq but end up consolidating at the detriment of my privacy.

**Comment by huey735** [comment]
@Giszmo I'm not sure I understand. You can withdraw all your funds from your Bisq wallet under FUNDS > SEND FUNDS. Choose "Use all available inputs", "Amount includes mining fees" and it should empty it.

**Comment by Giszmo** [comment]
Well, that is when you want to send the funds but when you want to sell them for fiat you don't have that option.

**Comment by huey735** [comment]
I understand better what you meant.
When creating an offer there's a lot more to consider: mining fees, security deposit, trading fees. And I don't know the sequence of things, so a "SELL ALL" button may be difficult to implement.

**Comment by Giszmo** [comment]
closed due to lack of love :(
