### ISSUE TITLE
Trader API?

### ISSUE THREAD

**Issue by anonproject** [bisq-network/bisq#3994]
I am seeing the same trend over and over again.  Somehow the software is getting developed with an emphasis on GUI.  You can see it in Electrum when you are unable to do RBF via cli.  You can see it in Wasabi Wallet when you have to install and run XFCE to start an app.  And now Bisq.  You've created a decentralized marketplace.  And suppose one want to write an arbitrage bot.  And how exactly one has to do it if there is no Trader API in the main repository?  I just don't understand what the hell is going on. :D

So right now what I have to do?  Try this experimental repo: https://github.com/bisq-network/incubator-bisq-api

Huh?  Does it actually works?

**Comment by anonproject** [comment]
Okay.  This one: https://github.com/bisq-network/incubator-bisq-api/pull/20

?

**Comment by anonproject** [comment]
Well, I looked around and discovered that EU introduced 5AMLD which requires apparently all centralized exchangers/marketplaces to do KYC/AML policy.  So ... apparently there is no other option but to use p2p marketplaces then.

So apparently I have to try that branch with Trader API then. Hm..

**Comment by ripcurlx** [comment]
@anonproject There is ongoing work on a gRPC API. Please see https://github.com/bisq-network/projects/issues/11 for details. There is also a keybase channel (#grpc-api) for anyone interested in discussing their use cases and trying out what was merged to master already.

**Comment by ripcurlx** [comment]
Closing this issue, as this feature is already being worked on.
