### ISSUE TITLE
Lacks market history

### ISSUE THREAD

**Issue by buzztiaan** [bisq-network/bisq#400]
Without seeing a market history, how will we ever trust this?

**Comment by bitcoinuser** [comment]
Answer of Bitsquare project dev: https://forum.bitsquare.io/t/show-all-trades-that-happened-on-bitsquare/60/8

**Comment by buzztiaan** [comment]
yes please implement it

**Comment by konard** [comment]
Yes this would be nice.

**Comment by ManfredKarrer** [comment]
It is all planned but need some time and more resources. Will close that issue here and add a dev issue once it gets closer to get implemented.
