### ISSUE TITLE
Moneygram Payment method.  ARS currency missing

### ISSUE THREAD

**Issue by mpolavieja** [bisq-network/bisq#4000]
It is not possible to post offers in ARS/BTC pair with Moneygram payment method, but Moneygram does support ARS currency (see picture below).   Argentina is very underveloped market pair in Bisq compared to the strong Bitcoin activity in that country.  I am willing to post offers in ARS/BTC pair, and payment methods such as Moneygram (or Western Union) are a very good option to bootstrap markets with no Bisq activity, but at this moment Bisq does not allow to use them. 

![image](https://user-images.githubusercontent.com/17677608/75101163-8cb21780-55d8-11ea-80ff-60c6ba811fcc.png)

**Comment by ripcurlx** [comment]
@mpolavieja Is not within our dev priorities. But as it was so easy to fix I quickly created a free PR for it :smile:
