### ISSUE TITLE
Issued BSQ chart uses start date instead of issuance date

### ISSUE THREAD

**Issue by burningman2** [bisq-network/bisq#4001]
<img width="1281" alt="Screen Shot 2020-02-23 at 16 53 33" src="https://user-images.githubusercontent.com/58760636/75120898-21f6ef80-565d-11ea-9306-fd3b38ee95fb.png">

**Comment by dmos62** [comment]
I worked on these charts and this aspect baffled me a bit, so I left it as it was. More specifically, I was sometimes surprised how the BSQ issued and BSQ burnt plots aligned. Could you elaborate what you mean by start date?

For context, there's two things going on in this chart, in terms of dates. One is the series generation, where we have to decide what date to assign to each data point group/bucket. The other is labeling, where we print the X axis tick labels (notice two Oct 19).

**Comment by burningman2** [comment]
The date shows the start of the phase, but the issuance is done at the end of the phase. So it is confusing.

**Comment by dmos62** [comment]
I'm pondering pinning all issue and burn events to their cycles, or the date of the last block in the cycle more specifically. If I understand the problem correctly, that should optimize the dissonance between "monthly" burn and issue plots. I quote "monthly", because these charts would now be cycly (per cycle, not per month).

**Comment by ifarnung** [comment]
Cycle would be a better way to track it, imo.  Thanks for working on that.  I've never found the charts that readable, would it be possible to add a table below them with the same data?  I know @m52go has a nice script that spits out all the burn data, maybe if that were just put in a monthly report or ongoing spreadsheet?

**Comment by m52go** [comment]
Yes I've created trading activity and DAO scripts with the intention of replacing the current [stats page](bisq.network/stats/) with one that has actual stats on trading activity and DAO activity (including compensation metrics), and relates both, on a per-cycle basis.

It's more of a mid-term priority for me, something I'm shooting to get to in about 2-3 months.

One prerequisite is [structured compensation requests](https://github.com/bisq-network/projects/issues/7#issuecomment-587050443), which I should get to soon.

**Comment by dmos62** [comment]
Because the upcoming API should allow us to extract this data and
chart it with external tools (JavaFX charting library is difficult to
work with), and in light of other ongoing projects, I consider this
issue low priority. If anyone disagrees, provide pushback.
