### ISSUE TITLE
Lightning support

### ISSUE THREAD

**Issue by anandpatel010** [bisq-network/bisq#4011]
Lightning support should increase bitcoin liquidity and help streamline trades.
LND & C-Lightning both fantastic implementations with communities which can assist in development

**Comment by ghost** [comment]
Still relevant.

**Comment by fresheneesz** [comment]
Please reopen. Stale bot is closing a bazillion relevant tickets on here.

**Comment by ripcurlx** [comment]
I reopened it, but ATM it is not possible to implement our trade protocol on top of Lightning.

**Comment by fresheneesz** [comment]
I would expect that a new trading protocol would be needed for lightning. Is that something you need someone to help design?

**Comment by ripcurlx** [comment]
I think for those ideas the Bisq 2.0 project would be the place for further discussions. https://github.com/bisq-network/proposals/issues/330

**Comment by jonathancross** [comment]
It seems work is continuing here: https://github.com/bisq-network/bisq2

However it doesn't seem that Lightning support is being actively pursued: https://github.com/bisq-network/bisq2/blob/15607f2912506d6e661d3c054c18809135c78fbb/docs/aims.md?plain=1#L41

Apparently @stejbac is working on feasibility?

**Comment by Giszmo** [comment]
I just paid $86 in mining fees. Add the maker's fees and the trading fees and Bisq is dead in its current form for trades under $10k. Requiring **4** on-chain transactions per trade is not sustainable and in the long-run, requiring one will be neither.

I have no idea when v2 will be ready but in a high fee environment, Bisq is obsolete.

**Comment by jonathancross** [comment]
@Giszmo  Apparently they plan to launch Bisq2 _without_ LN support, but add it later.
There are some constants in the code for it:
https://github.com/search?q=repo%3Abisq-network%2Fbisq2%20LIGHTNING_ESCROW&type=code
