### ISSUE TITLE
Dark mode: ColoredDecimalPlacesWithZerosText not working as intended

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#4019]
### Description

Bisq has a cool feature where trailing zeros after the decimal place are grayed out so that the user's eye can quickly see the relevant number.  Instead of 0.1000 it shows 0.1 (the extra 000 is almost invisible).

In dark mode the trailing zeros are shown in full.  

Screenshots highlighting the problem are included below.

#### Version
1.2.7

### Steps to reproduce

Look at the BSQ market offer book in light mode, verify that irrelevant zeros in the BTC amount are grayed out.
Switch to dark mode, then look at the BSQ market offer book.  Irrelevant zeros in the BTC amount are shown in full.

### Screenshots

![image](https://user-images.githubusercontent.com/47253594/75593680-bb524700-5a4b-11ea-860e-9dc66dbfe9a8.png)

![image](https://user-images.githubusercontent.com/47253594/75593714-d329cb00-5a4b-11ea-8bc2-02249bd7cde0.png)

#### Device or machine
Ubuntu 18.04 LTS

#### Additional info
This might be a CSS issue.

**Comment by ghost** [comment]
The `fx-text-fill` property is not responding to changes.  From experimentation, the property only responds if `-bs-text-color` is #000000 (as is the case in light mode but not dark mode).  Its a bit mysterious.

It relates to this piece of css:

    .zero-decimals {
        -fx-text-fill: -bs-color-gray-3;
    }

**Comment by wiz** [comment]
omg just close this issue it's not worth it trust me lol

**Comment by ghost** [comment]
omg yes sir lol
