### ISSUE TITLE
Cannot run bitsquare.exe on Windows 10

### ISSUE THREAD

**Issue by konard** [bisq-network/bisq#402]
If I try to start bitsquare.exe it does nothing. The only way to start app working for me is - `AppData\Local\Bitsquare\app\Bitsquare-0.4.3.jar`

Is it ok?

Where is also no shortcuts to bitsquare at start menu and on desktop after installation.

**Comment by ManfredKarrer** [comment]
Have you had installed an earlier version?
Do you have installed the right binary (32 bit or 64 bit)?
Running the jar file will use the OS default jvm and cause issues. 
Can you try to delete both the install directory (AppData\Local\Bitsquare) as well as the data directlry (if you have used it before backup the directory first).
Maybe you have a issue with the firewall? Bitsquare is still not code signed and MS might need a bit extra love to let it install..

I just tried installing it from scratch on my VM and worked fine.

**Comment by konard** [comment]
I uninstalled 0.4.2 as it was written at releases page. (using `AppData\Local\Bitsquare\unins000.exe` and removing `AppData\Roaming\Bitsquare` folder)
When 0.4.2 had been installed there was the same issue. Yes it is correct binary 64 bit binary on 64 bit system (Windows 10). Here is a log of first startup and shutdown: [bitsquare.txt](https://github.com/bitsquare/bitsquare/files/234990/bitsquare.txt)

> Can you try to delete both the install directory (AppData\Local\Bitsquare) as well as the data directlry (if you have used it before backup the directory first).

I already did it to install 0.4.3. Do you suggest to do it again?

> Maybe you have a issue with the firewall? Bitsquare is still not code signed and MS might need a bit extra love to let it install..

It was turned off (totally, I don`t like to slow down my pc) all the time for both 0.4.2 and 0.4.3 installation.

**Comment by ManfredKarrer** [comment]
Maybe the uninstall caused some issues? You can simply install the new version without uninstall. 
The log is from running the jar right? JRE: 1.8.0_40-b25 is not the packed jvm.

**Comment by konard** [comment]
> Maybe the uninstall caused some issues? You can simply install the new version without uninstall. 

At first installtion (0.4.2) I had the same problem, so uninstallation did nothing to change this issue.

> The log is from running the jar right? JRE: 1.8.0_40-b25 is not the packed jvm.

Yes, from jar.

I also tried to reinstall right now last version (0.4.3) and result is the same: bitsquare.exe does not show anything.

**Comment by ManfredKarrer** [comment]
Hm... I don't have any idea what can cause that. I tried it on several win machines and never got any like that. If you are a dev you can follow the build instructions here (https://github.com/bitsquare/bitsquare/blob/master/doc/build.md) and build if from source or if you follow the points under Prerequisites you can run the jar.

**Comment by ManfredKarrer** [comment]
Have you tried to uninstall all and install the beta?

**Comment by ManfredKarrer** [comment]
A new version has been deployed:
https://github.com/bitsquare/bitsquare/releases/tag/v0.4.5

**Comment by ManfredKarrer** [comment]
Please re-open if issue still exist.
