### ISSUE TITLE
Minor issue - sound always "on" with Bisq

### ISSUE THREAD

**Issue by Bisq-knight** [bisq-network/bisq#4034]
### Description
I put on my headphones and noticed that there was whitenoise coming through them. I disconnected the other devices and left it only connected to my windows PC. Bisq was running all the time. 

I then quit Bisq and the whitenoise was gone. Then I opened it. Whitenoise was back.

This leads me to suspect that the notification features that do require sound might not be implemented 100% correctly.

Also, while Bisq is open I do get the headphones to trigger their own notification sounds every now and then.

#### Version

1.2.7

### Steps to reproduce

*  plug in a bluetooth headphone that has a clear whitenoise when it is expecting sound to come from the computer
* open Bisq

### Expected behaviour

* silence

### Actual behaviour

* active noise cancelation trying to counter the ambient sound while Bisq is running

#### Device or machine
Windows 10

I can provide logs or further detail over Keybase ;)

But this is a very minor issue, no core functionality is affected nor core usecase

**Comment by cbeams** [comment]
The white noise is an unfortunate side effect of the way that "avoid standby mode" was implemented. If you can do without this feature, go to Settings and turn the `Avoid standby mode` toggle off.

**Comment by ripcurlx** [comment]
Closing this issues based on https://github.com/bisq-network/bisq/issues/4034#issuecomment-596201255.

**Comment by ghubstan** [comment]
@cbeams I am going to submit a PR to fix this for most linux desktops (after one more test).  Not Windows... though it might be modified to work on Cygwin if certain 'inhibitors' are present.

**Comment by ghubstan** [comment]
PR https://github.com/bisq-network/bisq/pull/4049     Use Linux OS suspend inhibitors to avoid standby
