### ISSUE TITLE
In Windows, Bisq app does not redraw/resize properly when display DPI changes.

### ISSUE THREAD

**Issue by Rowdster** [bisq-network/bisq#4038]
### Description

Start Bisq in one DPI display, say standard 1080p screen.  Then, resize desktop to 4K or similar, via remote desktop from a hdpi display.  The app will not "resize" as most other windows applications do, to adjust for fonts, etc.  However, if the app is closed and restarted, the display "DPI" is correct.

**Comment by coinzdude** [comment]
Still an issue
