### ISSUE TITLE
Order drop down boxes alphabetically!

### ISSUE THREAD

**Issue by Codes4Fun** [bisq-network/bisq#404]
Especially consider this when you have a large number of items in your drop down box such as when adding a new cryptocurrency account. This means its easier for people to find what they are looking for.

Also consider putting the list of supported currencies on your website. When I first came to check out your program I saw the release notes list a few cryptocurrencies I never heard of and thought ¯_(ツ)_/¯ and went back to reddit.

**Comment by ManfredKarrer** [comment]
Thanks for your input. Will consider all u said!

**Comment by ManfredKarrer** [comment]
Altcoin list: https://bitsquare.io/faq/#altcoins
