### ISSUE TITLE
Bisq allows requesting "arbitration" before timelock expires on payout TX

### ISSUE THREAD

**Issue by wiz** [bisq-network/bisq#4064]
### Description

Since the timelocked payout TX will be rejected by the Bitcoin network if broadcast before the timelock expires, Bisq must not attempt to broadcast the TX before then. However, it seems currently Bisq allows this, which causes major support issues for mediators.

#### Version

v1.2.8

### Steps to reproduce

1) Create an offer on Alice
2) Take the offer on Bob
3) Alice requests mediation
4) Mediator closes mediation case (suggested payout can be anything, doesn't matter)
5) Alice requests "arbitration"

### Expected behaviour

Alice's node should not attempt to broadcast timelocked payout TX until after timelock expires

### Actual behaviour

Alice's node broadcasts still-timelocked payout TX which is rejected by Bitcoin network, and funds are not donated to the Bisq donation address

**Comment by chimp1984** [comment]
@wiz Are you sure, if so thats a serious bug. Will add it to my list... Ticket should be reopened.

**Comment by wiz** [comment]
It was 6 months ago but IIRC there was a trader who had this issue and I came up with the steps to reproduce from analyzing their bisq.log

**Comment by chimp1984** [comment]
I tested it on regtest (there is only 5 blocks locktime) and all worked as expected. Maybe there was some earlier bug? If you see it again please let me know!
