### ISSUE TITLE
Can't withdraw Bitcoin due to java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by b3dk7** [bisq-network/bisq#407]
I am running Debian 64 bit and installed bitsquare using the .deb package

I get a java.lang.reflect.InvocationTargetException when trying to withdraw via the "Available for withdrawal" tab

I have a balance of 0.51 bitcoins and trying to withdraw 0.5 bitcoins

Log below

Apr-28 01:01:27.677 [JavaFX Application Thread] WARN  o.b.core.Wallet: Insufficient value in wallet for send: needed 0.0001 BTC more 
Apr-28 01:01:27.688 [JavaFX Application Thread] ERROR i.b.g.m.f.w.WithdrawalView: null 
Apr-28 01:01:27.691 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
Apr-28 01:01:27.691 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= java.lang.reflect.InvocationTargetException

**Comment by dougbebber** [comment]
I am running Ubuntu Desktop 14.04 LTS and installed BitSquare-64bit-0.4.4.deb

I receive a java.lang.reflect.InvocationTargetException when trying to withdraw via "Available for Withdraw" tab. I have a balance of 0.1 and tried to withdraw 0.09 bitcoins. I get the same error when attempting to withdraw smaller amounts such as 0.08.

Log below:

Apr-27 19:44:38.199 [JavaFX Application Thread] WARN  o.b.core.Wallet: Insufficient value in wallet for send: needed 0.0001 BTC more 
Apr-27 19:44:38.204 [JavaFX Application Thread] ERROR i.b.g.m.f.w.WithdrawalView: null 
Apr-27 19:44:38.205 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
Apr-27 19:44:38.205 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= java.lang.reflect.InvocationTargetException

**Comment by ManfredKarrer** [comment]
i am working on it and will release soon a bugfix.

if you need to withdraw now you can do either manually edit the amount field to a little bit smaller amount or if you don't have offers or trades open use the emergency tool for withdraw all the availabel funds on the wallet. you can open that with cmd+e (or ctrl+e).

**Comment by dougbebber** [comment]
Thanks Manfred!

You have done an excellent job with BitSquare! I'm really excited about using this platform and seeing it evolve.

Doug Bebber
Chariot Trading Company

**Comment by b3dk7** [comment]
ctrl+e worked for me. Thank you Manfred for your reply and your work on this platform. It is very exiting

**Comment by ManfredKarrer** [comment]
A new version has been deployed with a bug fix for that issue:
https://github.com/bitsquare/bitsquare/releases/tag/v0.4.5
