### ISSUE TITLE
About 15 trades which cannot be confirmed (payment+mediation) in any way. They lost data in keypub FUNDS-LOCKE FUNDS.

### ISSUE THREAD

**Issue by FlyingAtomPL** [bisq-network/bisq#4072]
#### As a seller I got payments from the buyers, but I wasn't unable to confirm the trade in Bisq wallet due to any bug (there is an error during "confirm the payment"). I tried several times, without results.
It went to mediation, mediator proposed the solution to finish the trade, but I cannot do anything. 
####  I wrote also to Manfred Karrer on Reddit about all these cases.
![17-03-2020-typical -case-of-lost-locked-funds](https://user-images.githubusercontent.com/62290471/76856126-e7930380-6852-11ea-9f14-5b478c8dcf31.jpg)
[log-file-17-03-2020-zp3EakDt.txt](https://github.com/bisq-network/bisq/files/4343417/log-file-17-03-2020-zp3EakDt.txt)

**Comment by wiz** [comment]
@FlyingAtomPL can you come on Keybase #support channel to discuss privately?

**Comment by FlyingAtomPL** [comment]
@wiz, sure, no problem, but I am only a trader, not a developer, so please let me know hot to go to Keybase #support channel to discuss there?

**Comment by FlyingAtomPL** [comment]
OK, we are in touch on Keybase
