### ISSUE TITLE
maxTradeLimit is not matching one of our default values. maxTradeLimit=0.00 BTC

### ISSUE THREAD

**Issue by aubits** [bisq-network/bisq#4076]
### Description

1.2.9 Version

### Steps to reproduce
One offer in Bisq for $AUD 1 has me getting this message on two Bisq terminals running 19.10

### Screenshots
[Screenshot from 2020-03-19 15-34-03](https://user-images.githubusercontent.com/27845142/77033185-a9384880-69fa-11ea-967b-b9bea88b27c1.png)

#### Device or machine
Two machines running 19.10

#### Additional info
[19032020_Bisq.log](https://github.com/bisq-network/bisq/files/4352718/19032020_Bisq.log)

**Comment by ripcurlx** [comment]
@aubits After contacting the offer maker she/he took down the offer. I'm working right now on a fix that handles this cases more gracefully and enables us to filter out offers completely.
