### ISSUE TITLE
Error on withdraw security deposit to external wallet

### ISSUE THREAD

**Issue by dougbebber** [bisq-network/bisq#409]
I installed Bitsquare-64bit-0.4.4.deb on Ubuntu Desktop 14.04 LTS.

I receive the following error while attempting to place a security deposit into an external wallet:
org.bitcoinj.core.ECKey$KeyIsEncryptedException

Log entry below:
Apr-28 08:27:57.106 [JavaFX Application Thread] WARN  o.b.core.Wallet: Insufficient value in wallet for send: needed 0.0001 BTC more 
Apr-28 08:27:57.109 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
Apr-28 08:27:57.109 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= null 
Apr-28 08:30:59.291 [JavaFX Application Thread] WARN  i.b.p.s.P2PDataStorage: Checks for refreshTTL failed

**Comment by ManfredKarrer** [comment]
I assume you did not run from source and did nto run the jar file directly, right?
If so, can you send me your data directory so I can try to reproduce the issue?
Please remove password protection. I wont steal you the coins :-). If you don't want to send me the data dir, please send me the log files.
My email u can find on the webpage / contact.

**Comment by ManfredKarrer** [comment]
A new version has been deployed:
https://github.com/bitsquare/bitsquare/releases/tag/v0.4.5

**Comment by kirillkovalenko** [comment]
I have just updated to 0.4.5 and still have this error.
(on Windows 10 1511)

**Comment by ManfredKarrer** [comment]
@kirillkovalenko Have you had installed an earlier version? If so can you try to uninstall and install new?
You are using the correct exe I assume (64 bit for 64 bit machine). Can you describe more in details what and how you get the error? Same like reported above?

**Comment by kirillkovalenko** [comment]
I had 0.4.4 (x64) and installed the 0.4.5 (x64) _over_ it. That might have been the problem.
Now I did a clean 0.4.5 install. But cannot test the issue any more since a moved the money to the built-in wallet. And that is where I have another problem now. 
Now I'm trying to withdraw the money to an external account and I get [this beautiful warning](https://onedrive.live.com/redir?resid=9844FDC23B276A96!4339&authkey=!AP1zGUQdoN1S9RI&v=3&ithint=photo%2cpng). Any ideas?

**Comment by ManfredKarrer** [comment]
Hm... that's strange never saw that before. So completely empty warning popup?
Can u send me the log files?

**Comment by kirillkovalenko** [comment]
@ManfredKarrer the log file is sent to your email.

**Comment by ManfredKarrer** [comment]
Found the issue. password protection cause a problem at fee calculation. Need to push another update unfortunately :-(
