### ISSUE TITLE
Allow for opening of arbitration after a certain time

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#4101]
### Description

Currently one can't open Arbitration without first going through Mediation.

#### Version

Bisq v.1.2.9

### Steps to reproduce

Alice and Bob enter into a trade and one of them opens Mediation. If for any reason the Mediator doesn't act, the traders can't move into arbitration. 

### Expected behaviour

After the locked payout becomes available (10 days for altcoins, 20 for national currencies) the user should be able to bypass Mediation and open Arbitration.

### Actual behaviour

The user gets stuck waiting for Mediation. If for some reason the Mediator is unresponsive the user is left without option inside the software

#### Additional info

[Relevant case](https://bisq.community/t/request-arbitration-with-unresponsive-mediator/9155)

**Comment by MwithM** [comment]
I think these issues can be merged:

https://github.com/bisq-network/bisq/issues/4126

I think that this suggestion makes sense in the current dispute protocol, but not very much in the suggestion I'm making at the other issue.
