### ISSUE TITLE
can't start bitsquare because java error 

### ISSUE THREAD

**Issue by rorschach707** [bisq-network/bisq#411]
![2016-04-27_125413](https://cloud.githubusercontent.com/assets/18729172/14905554/3348637e-0dcb-11e6-8660-44cb872b62ce.jpg)
OS windows 7 ultimate 64 bit

**Comment by HostFat** [comment]
Which version are you using? Is it the last one?
https://github.com/bitsquare/bitsquare/releases/tag/v0.4.5

Which version of Java are you using?

**Comment by rorschach707** [comment]
Java (Version 8 Update 91), last version

**Comment by rorschach707** [comment]
may be should i try 32 bit version of bitsquare?

**Comment by HostFat** [comment]
Which is your version of Bitsquare? Are you using the last one?
https://github.com/bitsquare/bitsquare/releases/tag/v0.4.5

**Comment by rorschach707** [comment]
sorry for mistake my version was 0.4.4. start download 0.4.5

**Comment by HostFat** [comment]
Maybe you have to give the permission to connect on your firewall.
Anyway, it's better if you wait an answer from the dev.

**Comment by rorschach707** [comment]
yep i disable firewall and antivirus and program has started. thanks.

**Comment by ManfredKarrer** [comment]
If you are on a 64 bit machine you need to install the 64 bit version. Can u send me the log files?

**Comment by HostFat** [comment]
Maybe with some kind of errors, it's good to show a message that asks the user to check his firewall/router.

**Comment by ManfredKarrer** [comment]
@HostFat Until yet it was other issues. Seems the installer (oracle java packager) does not produce very solid packages for some OS. And some issues was simply wrong architecture (32/64 bit) but for that I added a check in the code.

**Comment by ManfredKarrer** [comment]
Please re-open issue if issue still exist.
