### ISSUE TITLE
List BRL Coin

### ISSUE THREAD

**Issue by ah2020b** [bisq-network/bisq#4117]
Please fill in the following data to request for a new asset to be listed on Bisq. For more details, be sure to read [the full documentation](https://docs.bisq.network/exchange/howto/list-asset.html) on adding a new asset.

### 1. Asset name
BRL Coin

### 2. Ticker
_Your asset's ticker must not conflict with any national currency tickers (per [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)) or any of the [top 100 cryptocurrency tickers](https://coinmarketcap.com/coins/)._
BRLC

### 3. Block explorer URL
_Your asset's block explorer must be active and publicly available so that transactions can be verified with a receiver's address...if this isn't possible, [see workarounds here](file:///home/steve/wb/bisq/bisq-docs/build/asciidoc/html5/exchange/howto/list-asset.html#arbitrators-must-be-able-to-look-up-transactions-in-the-asset-block-explorer)._
https://etherscan.io/token/0x84e1c8823850d8adc3286f31bc1178f14d243168

### 4. Additional technical requirements (yes/no)
_Your asset should not have any additional requirements (for example, needing input fields for anything other than an address)._
No.

### 5. Initial coin offering (yes/no)
_Bisq will not list your token if it has taken part in an initial coin offering (ICO)_
No.

**Comment by FKrauss** [comment]
We have people in BR using [CryptoBRL](https://cryptobrl.com/) as if it was a regular Bank Account in Brazil, have you looked into it instead?

This way you don't need to share CPF nor your full name when trading on Bisq

**Comment by ah2020b** [comment]
Thanks for replying to me. BRL Coin is the most stable coin used in Brazil,
please take a look and compare:

BRLC
https://etherscan.io/token/0x84e1c8823850d8adc3286f31bc1178f14d243168

CryptoBRL
https://etherscan.io/token/0xA6FA6531acDf1f9F96EDdD66a0F9481E35c2e42A

Lets include BRLC at Blisq?

Atenciosamente,







Em seg., 6 de abr. de 2020 às 20:18, FKrauss <notifications@github.com>
escreveu:

**Comment by FKrauss** [comment]
I don't think we should add stable coins like that. All stablecoins have mindbending business models, where they have absolutely no fees as well as no "cost" for keeping up the maintainers and the banking infrastructure to keep the collateral. For me that's the telltale sign of a scam. You can claim it's because it is in exchange already but that math still doesn't hold.

The CryptoBRL guys are using the existing payment methods with their stablecoin which I think is what you should do too. F2F method in major cities also can work in that way as you have a freeform text field. 

But I honestly don't think we should list stablecoins, it is way too likely that we'll have a scam listed

**Comment by ah2020b** [comment]
Thank you for your sincerity, what is f2f? And by the way, I charge 1.89%
of fee to exchange BRLC to BRL, so I have a profit, a math, it is not a
scam.

**Comment by FKrauss** [comment]
Face 2 Face

btw, I think you'd have more voice in the telegram group :) [Check it out](https://t.me/bisqbrasil)

**Comment by CryptoBRL** [comment]
Hi everybody!

I would like to invite you all to analyse **CryptoBRL listing**, it's a greate project and we already have people using it at BISQ (unfortunately not in the proper way, cause there is no official support yet).

[CryptoBRL Listing Request](https://github.com/bisq-network/bisq/issues/4128)

 It's a consortium of several Brazilian companies. It's already accept on several exchanges as several payment companies too.

You can use CryptoBRL to **pay your bills, recharge UBER, recharge prepaid cell phones, recharge your Mastercard or Visa prepaid credit card, transfer funds between 3 different exchanges** and much more coming soon.

Please, take a look in the website and Whitepapers too.

Whitepaper: https://cryptobrl.com/assets/wp/Whitepaper-CBRL-EN.pdf
Website: https://cryptobrl.com
