### ISSUE TITLE
Feature Request: display ETA until lock time of payout TX expires in trade details screen

### ISSUE THREAD

**Issue by wiz** [bisq-network/bisq#4120]
Currently the only way for users to check if they can request arbitration is to restart bisq with `--dumpDelayedPayoutTxs=true`, open their bisq data folder, open the JSON file, search for their trade ID, copy the payout TX encoded as a hex string, paste it into a block explorer website that decodes it, and checks the block time, and then doing some math to figure out when that will unlock.

This should simply be displayed in the GUI as "time until arbitration can be requested" somewhere

**Comment by Bisq-knight** [comment]
This could also be added to the JSON contract, no? in the section where the multisig is described it could be there when the locktime expires

**Comment by ghost** [comment]
@Bisq-knight @wiz is this like what you want?  (This screenshot shows the JSON contract with the request arbitration screen which has the same information about arbitration time).

![image](https://user-images.githubusercontent.com/47253594/78740758-3ea16b00-791d-11ea-9a21-2b6ed9cf6408.png)
