### ISSUE TITLE
Feature Request: add column to Portfolio -> My Open Offers

### ISSUE THREAD

**Issue by FKrauss** [bisq-network/bisq#4125]
### Description

I trade in multiple Bisq payment methods. The current view of `My Open Offers` gives me a good overview of the spreads I'm asking around, but a critical piece is left out: the Payment Method.

So I'd like to propose that `My Open Offers` gets a bit closer to `Open Trades` and have Payment method there too

#### Version

1.2.9

**Comment by ripcurlx** [comment]
I think this is mainly a matter of space. So we would need to check how to squeeze everything together to make this visible. But I agree it is a pain if you have to go through all info popups to find out the right offers to activate/deactivate

**Comment by ghost** [comment]
Proposed solution (bisq default width):
![image](https://user-images.githubusercontent.com/47253594/80148092-2155d900-857a-11ea-81b5-c75bfa789e7e.png)

Proposed solution @ smallest width:
![image](https://user-images.githubusercontent.com/47253594/80147862-c45a2300-8579-11ea-996d-9d6051ab19b7.png)

Old bisq for comparison:
![image](https://user-images.githubusercontent.com/47253594/80147935-e358b500-8579-11ea-8009-1129ef6717c1.png)

**Comment by FKrauss** [comment]
Looks nice!
