### ISSUE TITLE
To list CryptoBRL Brazilian Stablecoin

### ISSUE THREAD

**Issue by CryptoBRL** [bisq-network/bisq#4128]
1. Asset name
CryptoBRL (cBRL)

2. Ticker
CBRL

3. Block explorer URL
https://etherscan.io/token/0xA6FA6531acDf1f9F96EDdD66a0F9481E35c2e42A

4. Additional technical requirements (yes/no)
No.

5. Initial coin offering (yes/no)
No.

**Comment by CryptoBRL** [comment]
**CryptoBRL** is a token from the "CBRL Company", created by a consortium of Brazilian companies, with transparent open and distributed audit. 

**It's the most adopted stable token in Brazil**, listed already on 5 exchanges/payments companies, and with a dozen of companies in the consortium that must list the token soon into their platforms.

Nowadays you can use CryptoBRL to pay your bills, recharge UBER, recharge prepaid cell phones, recharge your Mastercard or Visa prepaid credit card, transfer funds between 3 different exchanges and much more coming soon.

You can see more details on the whitepaper (https://cryptobrl.com/assets/wp/Whitepaper-CBRL-EN.pdf)
And its website: https://cryptobrl.com

**Comment by huey735** [comment]
Asset listing was put on hold - https://github.com/bisq-network/proposals/issues/166
