### ISSUE TITLE
Can't set up proxy connection to connect to Tor network

### ISSUE THREAD

**Issue by vandome** [bisq-network/bisq#413]
Hi all,

When launching Bitsquare in Windows 7, the app tries to connect to Tor network automatically. This fails because my connection MUST pass through a proxy. I cannot set it up anywhere. I tried to edit the torrc file manually (C:\Users\myUsername\AppData\Roaming\Bitsquare\mainnet\tor\torrc), where I can add my proxy settings with the "HTTPSProxy" setting, but this torrc file gets overwritten every time I run bitsquare, thereby losing the HTTPSProxy setting.

Any easy way around this?

Cheers!

**Comment by ManfredKarrer** [comment]
Bitsquare uses its own native tor instance so you dont need to start tor or setup anything.

**Comment by ManfredKarrer** [comment]
@vandome - Mike just told me that you need that setup for policy reasons. I fear there is atm no way to do that as the torrc gets overwritten. If that use case is required by more people we need to check how we can support that.

**Comment by vandome** [comment]
Well, is the torrc file overwritten for security reasons? If not, maybe I could modify the source code? Where in the code would I do that?

**Comment by ManfredKarrer** [comment]
No you could try to disable the overwrite in the code (OnionProxyContext.java) and check if you get it running then. If it helps we can merge that in.

**Comment by xrwz007** [comment]
hi,all
i want to set the socks5 for the frontproxy , i found the torrc, but the files how to set then they can work for socks5?

**Comment by ManfredKarrer** [comment]
You can use program argument socks5ProxyBtcAddress or socks5ProxyHttpAddress for the proxy used for the btc network and the one used to the pricefeed provider node. The P2P network proxy cannot be set.
