### ISSUE TITLE
Can't place an offer after deleting and recreating the same account with different name (modifying account)

### ISSUE THREAD

**Issue by Tvax** [bisq-network/bisq#4139]
### Description

After deleting my account on Bisq and recreating it to modify my display name I can't place an offer

#### Version

1.2.9

### Steps to reproduce

Create bank account
Successfully finish an offer (buying BTC in my case)
Deleting account
Creating it again with a different name, but same bank informations
Trying to create the same offer, this popup is displayed and I can't place an offer

### Expected behaviour

Being able to place an offer following the procedure above

### Actual behaviour

The popup is displayed, and I can't place the offer

### Screenshots

<img width="1012" alt="ThePopupError" src="https://user-images.githubusercontent.com/19556689/78758436-6ffe5300-797e-11ea-92e5-6350f038211c.png">

#### Device or machine

MacOS Catalina, MBP

**Comment by wiz** [comment]
https://bisq.community/t/trading-halted-until-v1-3-0-hotfix/9208

**Comment by Tvax** [comment]
> https://bisq.community/t/trading-halted-until-v1-3-0-hotfix/9208

Another issue, but a problem like that should be displayed in the soft, not only on the forums

**Comment by ghost** [comment]
> a problem like that should be displayed in the soft, not only on the forums

This alert is displayed in the software:

![image](https://user-images.githubusercontent.com/47253594/78786519-7e447300-796e-11ea-8ac5-0926b0b1b6cb.png)

**Comment by Tvax** [comment]
> > a problem like that should be displayed in the soft, not only on the forums
> 
> This alert is displayed in the software:
> 
> ![image](https://user-images.githubusercontent.com/47253594/78786519-7e447300-796e-11ea-8ac5-0926b0b1b6cb.png)

OK I guess I didn't see it, that's weird

**Comment by ghost** [comment]
And now the update.

![image](https://user-images.githubusercontent.com/47253594/78791281-4bea4400-7975-11ea-87ed-2b2eac6f6158.png)

**Comment by Tvax** [comment]
OK the update "fixed" the issue
