### ISSUE TITLE
Review bloom filter fixes in Bitsquare's BitcoinJ fork

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#414]
I made changes in our fork of BitcoinJ [1] to allow the library user to have more control over bloom filters and avoid the privacy flaws [2, 3] in the default BitcoinJ implementation [4].

There are basically those features added:
- setBloomFilterTweak
- setInsertPubKey
- setLookaheadSize

setBloomFilterTweak:
Persist the nonce used to create the filter to avoid a simple attack. Default implementation creates a new nonce each start and so makes it very easy to collect several filters and gain information about the real addresses of a wallet. Bitsquare persists the nonce so avoiding to re-create a filter on startup.

setInsertPubKey:
A flag to define if the pubKey is added to the filter in addition to the pubKeyHash. Default implementation adds both and reduces privacy of filter dramatically. See [2].
Bitsquare set the flag to false and only adds the pubKeyHash to the filter. Pay to pubKey is not used in normal wallets as far I know, so that should be at least for Bitsquare not be an issue. 
Quote from a research paper:
"In fact, more than 99% of all Bitcoin transactions consist of payments to Bitcoin addresses (or the public key hash);  moreover, only 4587 out of 33 million total addresses in the system received transactions destined for both their public keys and their public key hashes (We obtained these numbers by parsing the Bitcoin block chain till block # 296000)". [3]

setLookaheadSize:
Defines the number or generated keys. Default there are 266 keys generated. When the 200th key is used a new batch of keys is generated which triggers the creation of a new filter. As above collecting filters with partially the same content is an attack vector to reduce privacy of the filter.
Bitsquare creates 1333 keys at startup which should be sufficient for most users to never re-create the filter. 

Furthermore the setBloomFilterFalsePositiveRate is set to 0.00005 which results in probability of 32 %  that a pub key is in our wallet. Setting the FR higher can cause higher bandwith consumption.
Rudimentary tests have shown that in some cases (e.g. 1 of 10) the bandwith consumption is pretty high (e.g. if you have bad luck and get a nonce which covers a Satoshi Dice address).
The FP rate is problematic as it is very unpredictable what you get. And as we don't change the filter anymore would stay high for each start of the app if we have bad luck with the nonce. 
One approach might be to re-create the nonce if we detect high bandwith, so taking a certain privacy loss in account.
Another better solution would be to set the FP very low (close zero) but fill the filter with a random set of pre-checked addresses from a big pool (e.g. 100 000 or more) of collected addresses from the blockchain. A tool could remove those addresses which are used in too many transactions to avoid high bandwidth consumption from the filter. Also the set can be filtered to match a statistical similar set of addressess (avoid too old addresses,...). 

Tasks:
- Review the current implementation if it covers all the edge cases (probably not, I did it in a few hours and I am not an expert in BitcoinJ - but we have not seen any issues so far).
- Test more in details the bandwidth consumption related to the FP rate
- Route BitcoinJ over our native Tor instance instead using BitcoinJ's Orchid implementation (not sufficiently stable)
- Find optimal value for nr. of generated keys for Bitsquare (make performance tests on low end machines for key creation time)
- Investigate the approach to use a random set of addresses instead of the FP rate.
- Discuss with the researchers and the BitcoinJ community [4] the approach and results.
- Reach out to @jonasnick, @devrandom and @apetersson for a review

[1] https://github.com/bitsquare/bitcoinj
[2] https://jonasnick.github.io/blog/2015/02/12/privacy-in-bitcoinj/
[3] https://eprint.iacr.org/2014/763.pdf
[4] https://groups.google.com/forum/#!msg/bitcoinj/Ys13qkTwcNg/9qxnhwnkeoIJ

**Comment by jonasnick** [comment]
Concept ack because these measures have a fair impact on attack cost.
Avoiding to insert the pubKey defends against simple mass-collection attack described in [2]. However, mass-collection is still a threat because "probability of 32 % that a pub key is in our wallet" is quite high and can be further increased by using transaction graph analysis. I hope the false positive rate can be further tuned.
Persisting the tweak and increasing the lookahead size defends against an attacker that is able to capture two different Bloom filters from the same wallet. Their intersection contains a the correct keys with very high probability. Note that very targeted attacks are still possible where for example the attacker tricks the victim into quickly creating many keypairs.

@kristovatlas might also be interested in reviewing this.

**Comment by ManfredKarrer** [comment]
@jonasnick Thanks for your input!

**Comment by ManfredKarrer** [comment]
Update: 
I found that not adding the pubKey to the filter caused a problem that the client does not get the deposit MultiSig transaction. Could reproduce that on localhost/regtest, though had no time to look closer into it.
Needed to fix that in the latest release as it caused several severe issues for users (failed trades).
That issue appeared only in the 0.4.9.7 release as in earlier versions the pubKey was still added due a bug. In version 0.4.9.7 that "bug" was fixed and caused then the issues that some MS transactions did never receive the confirmations. Version 0.4.9.8 added again the pubKey so the privacy fix is reverted to solve that critical problem to not receive MS transactions. 
Need investigations what causes it exactly and try to fix that.
If anyone is interested to work on that please get in touch with me I will offer a bounty (https://github.com/bitsquare/bitsquare/issues/487). 

Currently best practice to not be exposed to those privacy leaks is to run a local Bitcoin Core node, then the app connects only to that node. Alternatively you can add a program argument (--btcNodes=...) to connect only to those nodes passed in the argument (comma separated).

**Comment by remyers** [comment]
Update with some recent links on this topic:
- "Committed bloom filters for improved wallet performance and SPV security" ([May 2016](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-May/012636.html))
- "BIP Proposal: Compact Client Side Filtering for Light	Clients" ([June 2017](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-June/014474.html))
- "Block Filter Digest profiling" ([June 2017](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-June/014469.html))
