### ISSUE TITLE
An error occurred at task: BuyerVerifiesFinalDelayedPayoutTx. DelayedPayoutTx is not spending depositTx correctly

### ISSUE THREAD

**Issue by mattmill30** [bisq-network/bisq#4145]
### Description

'BuyerVerifiesFinalDelayedPayoutTx' error occurs during the finalising stage of taking a BTC offer, and failed trade warning is displayed upon transaction blockchain confirmation, but trade continues to appear in Open Trades and is waiting for confirmation of 'Payment Started'.

#### Version

v1.3.0

### Steps to reproduce

Took a BTC offer, using funds from Bisq wallet. After reviewing and finalising the transaction, the following error was encountered:
```
An error occurred at task: BuyerVerifiesFinalDelayedPayoutTx
DelayedPayoutTx is not spending depositTx correctly
```
After closing the error, the 'Successfully taken an offer' message was displayed and the trade showed correctly in Portfolio > Open Trades.
However, the trade details included the error:- Screenshot attached
```
Error message:
An error occurred at task: BuyerVerifiesFinalDelayedPayoutTx
DelayedPayoutTx is not spending depositTx correctly 

Trade state:
DEPOSIT_PUBLISHED
```
Once the first transaction was confirmed, the confirmation notification was displayed, along with a failed trade warning:
```
You have locked up funds from a failed trade.
Locked up balance: 0.009360BTC
Deposit tx address: 1KnbWh81aZS4vYFL1L8MQExzi8UM7FodoT
Trade ID: 65822208-d0d39d91-0f5b-4cbe-81e8-a0f76febb54f-129
```

### Screenshots

'Successfully taken an offer' dialog is displayed after 'BuyerVerifiesFinalDelayedPayoutTx' error:
![image](https://user-images.githubusercontent.com/6415621/78903052-8a195d80-7a72-11ea-84fd-81fdd3f86a65.png)

'BuyerVerifiesFinalDelayedPayoutTx. DelayedPayoutTx is not spending depositTx correctly' error message show in open trade details:
![image](https://user-images.githubusercontent.com/6415621/78820672-1e7eb400-79d0-11ea-8d2e-52b9fe2e3f68.png)

Trade fails upon transaction confirmation with warning:- Warning appears 4 times
![image](https://user-images.githubusercontent.com/6415621/78818828-2d179c00-79cd-11ea-8466-8f28b22a7578.png)

Opening Portfolio displays 'Attention required for trade' pop-up:- bank details redacted
![image](https://user-images.githubusercontent.com/6415621/78819935-ec208700-79ce-11ea-8637-a718e73d9d62.png)

Failed Trades section isn't accessible under Portfolio, and trade continues to appear in Open Trades:- bank details redacted
![image](https://user-images.githubusercontent.com/6415621/78902307-876a3880-7a71-11ea-8906-02cc4d6145ec.png)

Trade details has a new Trade State of DEPOSIT_CONFIRMED:
![image](https://user-images.githubusercontent.com/6415621/78820892-77e6e300-79d0-11ea-84df-518eaa54b44b.png)

#### Device or machine

Windows 10 laptop

#### Additional info

[bisq.log](https://github.com/bisq-network/bisq/files/4452126/bisq.log)

**Comment by huey735** [comment]
These issues may have been fixed with the latest update v.1.3.1
https://github.com/bisq-network/bisq/releases/tag/v1.3.1

**Comment by mattmill30** [comment]
The update dialog claims "trades with older versions of Bisq (including v1.3.0) will be rendered invalid". What impact will installing this upgrade have on the open trade, and how should I proceed before/after upgrade?

![image](https://user-images.githubusercontent.com/6415621/78844542-ef7f3700-79fd-11ea-8bd7-b548687a4f49.png)

Is it possible and safe to complete the open trade in v1.3.0, given trading has been disabled?
If the counterparty has already upgraded to v1.3.1, can the trade be safely completed while my client is v1.3.0?
![image](https://user-images.githubusercontent.com/6415621/78844824-d5922400-79fe-11ea-96db-fb37ee2e0f4f.png)

v1.3.0 continues to report a failed trade, though the trade continues to remain in Open Trades waiting for confirmation of 'Payment Started'.
![image](https://user-images.githubusercontent.com/6415621/78845499-949b0f00-7a00-11ea-859f-a0eff9d81d57.png)

**Comment by leo816** [comment]
this bug is still happening with users on 1.3.1

**Comment by ripcurlx** [comment]
> this bug is still happening with users on 1.3.1

Is this exactly this message or the donation address comparison issue?

```
Error message:
An error occurred at task: BuyerVerifiesFinalDelayedPayoutTx
DelayedPayoutTx is not spending depositTx correctly 

Trade state:
DEPOSIT_PUBLISHED
```

**Comment by sqrrm** [comment]
Looked at the log and version, seems the verification is an artifact of the 1.3.0. The verification for connected output failed. That wasn't a good check and it's not present in 1.3.2.

I recommend upgrading to 1.3.2 and continue with trade.

**Comment by mattmill30** [comment]
After upgrading to v1.3.2, the 'locked up funds from a failed trade' error appears twice after start up, but the trade is still not appearing in Failed Trades, but continues to be in Open Trades.

![image](https://user-images.githubusercontent.com/6415621/78845499-949b0f00-7a00-11ea-859f-a0eff9d81d57.png)

[bisq.log](https://github.com/bisq-network/bisq/files/4510699/bisq.log)
Apr-21 14:34:47.378 - 'Locked up funds' error post v1.3.2 upgrade

**Comment by sqrrm** [comment]
@mattmill30 Looked at the logs and the blockchain and it looks like you completed the trade, or got it sorted through mediator. Is it still appearing in the open trades? If so you can move it to failed trades with ctrl+y.

If it's claiming funds are still locked up you might have to do ctrl+e to be able to send all the funds from the wallet as I think the internal address management might be a bit out of sync.
