### ISSUE TITLE
Can't add an offer

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#416]
Hi,

See the video uploaded.

Thanks
[out.ogv.zip](https://github.com/bitsquare/bitsquare/files/243412/out.ogv.zip)

**Comment by ManfredKarrer** [comment]
Upps the amount input check is here missing for 0 values... thanks for reporting! Will close it and add it to next release.

**Comment by ManfredKarrer** [comment]
Thanks for the effort to report with video btw!
Bug is fixed already and will go out with next release.

**Comment by bitcoinuser** [comment]
Hi, If I create an offer to buy bitcoins and specify how much in fiat money I want to spend and select percentage, the fields "(amount of bitcoins to buy) and (minimum amount of bitcoin to buy) should be disabled, no?

**Comment by bitcoinuser** [comment]
I'm very confused when I place an order to buy bitcoins and the maximum in fiat that I want to spend is 300 BRL. The bitcoins value value may fluctuate but the fiat no. Understand?

**Comment by bitcoinuser** [comment]
Other thing: I want to specify that I want to spend 300 BRL in maximum, but that I accept offers of 200 BRL. I din't see an option to do this.

**Comment by bitcoinuser** [comment]
Because all of this "bugs" I had to remove my offers. Lost bitcoin money in fees.

**Comment by ManfredKarrer** [comment]
@bitcoinuser The btc amount is the fixed part also if you define a min. amount there is a range the taker can select. So to use the fiat amount as fixed part would not work here. Of course we could support both so you can define if the fiat amount is fixed (then we need a min fiat amount field as well) or the btc amount.  But I think most people are more familiar with the current version and haveing both would just confuse more. Also the btc amount is more likely the limitation (e.g. u have 1 btc to sell) rather then the fiat amount (most people have more on their bank as what they need to send to the buyer). 
I am aware that opinions will differ here but I think the current situation is better from usability point of view. It is also the first time that I hear that complaint (does not mean that I don't take it serious and I am happy that you gave that feedback!).

**Comment by bitcoinuser** [comment]
Hi Manfred,

Sorry, but I disagree. I only have 300BRL on my bank account. If the value goes to 320 and someone accept the offer, I can't transfer the money because I don't have the money.
I just would like to buy bitcoins (bitsquare ask price - 3%) using the maximum of 300 BRL. I don't care if I will receive 0.002, 0.02 or 2 btc. 
Understand? I think this is not possible today, right?

**Comment by ManfredKarrer** [comment]
No that is no possible yet.

**Comment by bitcoinuser** [comment]
A appreciate you work on bitsquare. But without this, I can't place an offer. Hope you implement this soon. Thanks

**Comment by bitcoinuser** [comment]
Imagine you implemented my suggestion. I ask: I "insert" 300 BRL in the (fiat amount to spend) field. And we have a field of minimum amount of Fiat, that I add 10 BRL. Someone accept my offer to sell the value of 10BRL in bitcoins, ok. Will the remaining 290BRL still be available to other offers or I'll need to place a new offer. In my opinion, the ideal solution is not be necessary place another buy offer. 

What do you think?

**Comment by ManfredKarrer** [comment]
Offer renewal is on the todo list.
