### ISSUE TITLE
 No deposit transactions -> failed?

### ISSUE THREAD

**Issue by Nadumanov** [bisq-network/bisq#4160]
### Description

My trades don't have the usual confirmation flow where a 24-hr window pops up with the details of the trade. So far two have been lost as failed ([one](57864087) and [two](Cg0H9t))

#### Version

v.1.3.1

### Steps to reproduce

Make a sell order - match - go to portfolio/trades

#### Device or machine

MacBook Pro, MacOS High Sierra 10.13.6

<img width="600" alt="Screen Shot 2020-04-11 at 12 06 03 PM" src="https://user-images.githubusercontent.com/55026777/79048539-16b44f00-7c1e-11ea-8e50-0c824508f6e3.png">

**Comment by Nadumanov** [comment]
Happened again after I did an SPV resync. Third trade already I can't sell my btc.

**Comment by ripcurlx** [comment]
Could you please join #support on keybase for solving this issue?

**Comment by ripcurlx** [comment]
> Happened again after I did an SPV resync. Third trade already I can't sell my btc.

@Nadumanov Where you able to solve your problem?

**Comment by Nadumanov** [comment]
Yep, eventually. No actions from my side really.
