### ISSUE TITLE
Bisq allows seller to omit mediation

### ISSUE THREAD

**Issue by MwithM** [bisq-network/bisq#4162]
### Description

1. Buyer pays seller XMR. 
2. Seller doesn't confirm or respond chat.
3. Buyer waits one hour and opens mediation. 
4. Mediator demands proof of payment, which is provided by buyer.
5. Seller still doesn't answer to buyer or mediator.
6. Seller has 10 days to release locked funds, omitting mediator's suggestion.

### Expected behaviour

Trade protocol should allow to keep multisig deposit locked when mediation has been requested.
I don't know how to technically solve this flaw, but once trade period expires and mediation is open, both traders should agree on payout before multisig funds are released.

### Actual behaviour

As long as he acts before arbitration, seller doesn't have any incentive to accept mediator suggestion once they have received buyer's payment.

#### Related

https://github.com/bisq-network/bisq/pull/4099
https://github.com/bisq-network/bisq/issues/4064

**Comment by huey735** [comment]
I don't think that there's a solution to that "problem" with the current protocol. Reducing the locktime may help??

**Comment by MwithM** [comment]
As revoking a signature is not possible, the proposal above could be a solution.

**Comment by chimp1984** [comment]
@MwithM We could disallow it on the UI level which is probably good enough for the majority of cases but of course a user could change the code and un-do that. Technically I guess there is no solution beside buyer not sending the signature when confirming payment sent. But then the Buyer needs to be online again when the seller confirms, delaying the protocol. It also would require a extra trade message which increases risks of msg lost. I guess the trade off would not be justified. I will consider the UI option as that might be good enough to avoid that sellers are abusing that situation. Can you re-open the ticket?

**Comment by MwithM** [comment]
It doesn't look like i can re-open it. To me, the UI option is good enough for now, and I would like to see it implemented soon, so mediators can impose sanctions to late responding sellers.

**Comment by chimp1984** [comment]
I will try to get it in for the releasae.

**Comment by gordonel** [comment]
@MwithM will this affect fiat trades and signing? If the seller can't release funds during mediation, any mediation request will make signing impossible for a trade

**Comment by MwithM** [comment]
The way it's going to be solved (UI not displaying the "payment received" button, it should not change anything about signing for fiat trades.
I'm not sure if now a mediated trade that ends successfully stops the signing process.
Users should only open mediation when there's an urgent issue.

**Comment by chimp1984** [comment]
If signing is not done at mediated payout its a bug and need to be fixed.

**Comment by gordonel** [comment]
> If signing is not done at mediated payout its a bug and need to be fixed.

Not so sure about that as it has been used to negate signing, especially when a trade has to be aborted

**Comment by chimp1984** [comment]
Ah good point. I will check....
