### ISSUE TITLE
“Bisq” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by yaaminu** [bisq-network/bisq#4165]
I'm unable to run bisq application on my machine. I downloaded it from the official website (https://bisq.network/downloads/v1.3.1/Bisq-1.3.1.dmg). 

Macbook pro 2018, MacOS catalina 10.15.2 (19C57). 

![Screenshot 2020-04-13 at 6 58 09 AM](https://user-images.githubusercontent.com/5977878/79099865-9a705780-7d54-11ea-962a-a5db9405f28e.png)

**Comment by leshik** [comment]
@yaaminu go to your `/Application` folder, then `Ctrl + click` on `Bisq` and click `Open`. It will then ask if you really like to launch it.
