### ISSUE TITLE
Error : No value present

### ISSUE THREAD

**Issue by Warz** [bisq-network/bisq#417]
I right clicked on bitsquare in system tray and clicked on "show", got a popup saying "Error: No value present" and was asked to create an issue here. 

Afterwards I went to system tray and chose hide, then show again and bitsquare appeared. However none of the buttons seems to do anything (buy btc, sell btc, portfolio, funds, support). Market and Settings seemed fine. I restarted the application to fix it.

Later, the next day, the same popup appeared when I clicked "Spreads" under Market. It kept popping up this time despite clicking close, so I had to shut the application.

After restarting the application I got the same error again. Clicked closed, then I got:
java.lang.NullPointerException. It kept popping up again even if I clicked closed, so I had to shut down the application again.

Started it again and things looked fine, but then I clicked "Spead" and I got "No value present issue" again.

System:
Windows 10 64-bit
Bitsquare v0.4.5

EDIT: I noticed version v0.4.6 is out so I upgraded to that. Everything seems fine so far. Closing it.

**Comment by remyers** [comment]
I just got this error, I wasn't doing anything but the Offer Book screen was up when I brought Bitsquare to the foreground.  After error popup, system continues to run as normal.

System:
Windows 10 64-bit
Bitsquare v0.4.6

**Comment by ManfredKarrer** [comment]
I just released a new version. Hope that has fixed that issue... I assume you cannot reproduce that, right?
