### ISSUE TITLE
Removed my offer but bitcoins didn't show on available balance

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#418]
Hi,

I removed my offer but bitcoins didn't show on available balance. (see the screenshot)

Obs: When I restarted bitsquare, the bitcoins appeared on available balance.

![captura de tela de 2016-04-30 09-36-44](https://cloud.githubusercontent.com/assets/1178856/14935905/9c41a60e-0eb8-11e6-8329-dac7d7f2e526.png)

**Comment by ManfredKarrer** [comment]
Resolved in next version.
