### ISSUE TITLE
Building Bisq on OpenBSD

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#4180]
### Description
I wanted to build Bisq on OpenBSD and ran into an error.

#### Version
master ([4fd8be6b6836d035b470d18dc000bf7bdb8f2065](https://github.com/bisq-network/bisq/commit/4fd8be6b6836d035b470d18dc000bf7bdb8f2065))

### Steps to reproduce
1. `git clone`
2. `cd bisq`
3. `./gradlew build`

### Expected behaviour
Bisq gets build.

### Actual behaviour
Got the following error:
````
Could not determine the dependencies of task ':desktop:shadowJar'.
> Could not resolve all files for configuration ':desktop:runtimeClasspath'.
   > Could not find javafx-fxml-openbsd.jar (org.openjfx:javafx-fxml:11.0.2).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/openjfx/javafx-fxml/11.0.2/javafx-fxml-11.0.2-openbsd.jar
   > Could not find javafx-controls-openbsd.jar (org.openjfx:javafx-controls:11.0.2).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/openjfx/javafx-controls/11.0.2/javafx-controls-11.0.2-openbsd.jar
   > Could not find javafx-swing-openbsd.jar (org.openjfx:javafx-swing:11.0.2).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/openjfx/javafx-swing/11.0.2/javafx-swing-11.0.2-openbsd.jar
   > Could not find javafx-graphics-openbsd.jar (org.openjfx:javafx-graphics:11.0.2).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/openjfx/javafx-graphics/11.0.2/javafx-graphics-11.0.2-openbsd.jar
   > Could not find javafx-base-openbsd.jar (org.openjfx:javafx-base:11.0.2).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/openjfx/javafx-base/11.0.2/javafx-base-11.0.2-openbsd.jar
````

#### Device or machine
OpenBSD-current

**Comment by wiz** [comment]
unfortunately the version of javafx that bisq uses only supports linux, windows, and macos

**Comment by ghost** [comment]
okay, thanks @wiz

**Comment by ghost** [comment]
Just out of curiosity (I would really like to use bisq), will this ever change?
Probably not enough people using OpenBSD as their OS.

**Comment by wiz** [comment]
The problem is JavaFX. I actually run some headless Bisq nodes on FreeBSD fine despite it being completely unsupported, using a bunch of hacks I made. For example mempool.space/bisq is running on FreeBSD.

**Comment by wiz** [comment]
The problem is JavaFX. I actually run some headless Bisq nodes on FreeBSD fine despite it being completely unsupported, using a bunch of hacks I made. For example https://mempool.space/bisq is running on FreeBSD.
