### ISSUE TITLE
Forced Close, Now Won't Connect to TOR

### ISSUE THREAD

**Issue by DeanScottWalsh** [bisq-network/bisq#419]
I have a low power machine which struggles to maintain connections to Bitsquare when other applications are running. I had this problem and tried to close Bitsquare, but while closing windows gave me an error saying it had encountered and error and had to shut down Bitsquare. When I try to repoen it now I get this error:

We tried to restart Tor 4 times, but it continued to fail with error message:
C:\Users\deans\AppData\Roaming\Bitsquare\mainnet\tor.tor\control_auth_cookie (The system cannot find the file specified)

I've included an attachment with everything in the log file from today, I presume its only the latter parts that are relevant though.

[bitsquarelog.txt](https://github.com/bitsquare/bitsquare/files/244134/bitsquarelog.txt)

**Comment by DeanScottWalsh** [comment]
Update: Got the same error twice, then left it 15 minutes and tried again and its opened, connected and seems to be working fine. I didn't actually do anything to make it work other than keeping on trying to open it.

**Comment by ManfredKarrer** [comment]
Tor has sometimes issues e.g. if you get a bad route. That cannot be avoided completely. I have seen that once in 100 times more or less, but I can imagine that bad connection will make those issues more likely. There are timeouts which trigger that. Trying to restart again is the only you can do for now. But we will try to investigate and improve that.
Will close it, but I am aware of the issue and its on the todo list (hope some Tor dev will join to help).
