### ISSUE TITLE
OSX: "Bisq can't be opened because Apple cannot check it for malicious software"

### ISSUE THREAD

**Issue by cd2357** [bisq-network/bisq#4196]
### Description

After downloading and installing the Mac version, starting it fails with "Bisq can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information"

#### Version

1.3.2

### Steps to reproduce

* Download / verify Bisq package for Mac (v1.3.2)
* Open dmg
* In newly opened window: copy Bisq application to Applications folder
* Try to open Bisq application (from Applications folder)

### Expected behaviour 

On the last step above, Bisq application should open.

### Actual behaviour

Opening Bisq fails with OSX error mentioned above.

### Screenshots

<img width="420" alt="Screenshot 2020-04-27 at 09 08 29" src="https://user-images.githubusercontent.com/15956136/80343708-ab49be80-8866-11ea-8d9e-c0c1f470386c.png">

#### Device or machine

MacBook Pro
macOS Catalina 10.15.4

#### Additional info

* Seems to also occur for other software packages on OSX: https://github.com/dotnet/core/issues/3943
* The workaround mentioned there (right click on app > Open) works
  * But issue should still be addressed (it creates friction for new users, even before they open Bisq app)
* Seems like fixing it would involve some kind of notarization of the app by Apple -- https://github.com/dotnet/core/issues/3943#issuecomment-576844597
  * which is already tracked here: https://github.com/bisq-network/bisq/issues/3402 (perhaps that issue needs a higher prio? reported on v1.2.1, still affects v.1.3.2)

**Comment by MaskyS** [comment]
bump

**Comment by ripcurlx** [comment]
It is completely done already in #4242. Just needs the final touches for the remaining build steps.

**Comment by cd2357** [comment]
Fixed in the most recent release (v1.6.4) which includes binary notarization for macOS.
