### ISSUE TITLE
Warning after payment confirmed

### ISSUE THREAD

**Issue by pmknutsen** [bisq-network/bisq#420]
I have confirmed a bank payment through Bitsquare (after someone bought bitcoins from me). There is now a warning displayed that says "You have still not reported the reciept of the payment!" (lower left in screenshot):

![screenshot from 2016-05-01 16 43 37](https://cloud.githubusercontent.com/assets/1565499/14945059/5cd0e20a-0fbc-11e6-9349-b4e1c785d4e0.png)

**Comment by ManfredKarrer** [comment]
Upps, thats a wrong text displayed. As soon the peer goes online the payout will be published.

**Comment by ManfredKarrer** [comment]
Fixed for next release.
