### ISSUE TITLE
Error when trying to post an order

### ISSUE THREAD

**Issue by sombra-dot** [bisq-network/bisq#4200]
[

### Description
![bsiq](https://user-images.githubusercontent.com/64437856/80414491-80338f00-88a7-11ea-84b8-88a9f54be1aa.png)

**Comment by ripcurlx** [comment]
@sombra-dot Do you still have this issue?

**Comment by sombra-dot** [comment]
Yes, I don't know what happens, I've tried changing it to altcoins account but it won't help. I really don't know what's happening. I'm using the most recent version. The thing is: when I use btc to pay the fee it works perfectly. When I chenge it to bsq it has an error.

Enviado via ProtonMail móvel

-------- Mensagem Original --------
Ativo 27 de jul de 2020 07:06, Christoph Atteneder escreveu:

**Comment by ripcurlx** [comment]
Could you please provide the part of your log when this problem occurs to see more details on this? Thanks!
