### ISSUE TITLE
Final step of trade (withdraw BTC to external wallet) fails

### ISSUE THREAD

**Issue by cd2357** [bisq-network/bisq#4205]
### Description

I went through a trade to buy BTC (as a market taker).

In the last step I was told the trade is complete, I can now withdraw the BTC to the Bisq wallet, or to an external wallet.

The amount available to withdraw was 0.016 BTC (amount bought + deposit).

I chose the "External wallet" option, entered the destination address (P2SH, starting with 3..).

Attempting to withdraw failed with

> The fees for that transaction exceed the available funds or the resulting output value is below the min. dust value:
> Missing 0.016 BTC 

Withdrawing to the Bisq wallet went through though.

#### Version

1.3.2

### Steps to reproduce

In the last step of the trade, when withdrawing BTC, attempt to withdraw to an external wallet (P2SH address).

### Expected behaviour

The same behavior as with withdrawing to Bisq wallet. When initiating withdrawal to external wallet, it should:

* show overview of prepared tx (fee, amount, destination address) + ask for final confirmation
* on confirm, successfully broadcast tx

### Actual behaviour

Clicking the "Withdraw to external wallet" fails with the error above, before even the confirmation popup is shown.

### Screenshots

Didn't take a screenshot, but see log snippet below.

#### Device or machine

Fedora 30

#### Additional info

```
Apr-28 21:01:11.592 [JavaFX Application Thread] INFO  org.bitcoinj.wallet.Wallet: Completing send tx with 1 outputs totalling 0.016 BTC and a fee of 0.00 BTC/kB 
Apr-28 21:01:11.595 [JavaFX Application Thread] WARN  org.bitcoinj.wallet.Wallet: Insufficient value in wallet for send: needed 0.016 BTC more 
Apr-28 21:01:11.596 [JavaFX Application Thread] ERROR b.d.m.p.p.s.b.BuyerStep4View: The fees for that transaction exceed the available funds or the resulting output value is below the min. dust value:
Missing 0.016 BTC 
bisq.core.btc.exceptions.InsufficientFundsException: The fees for that transaction exceed the available funds or the resulting output value is below the min. dust value:
Missing 0.016 BTC
	at bisq.core.btc.wallet.BtcWalletService.getFeeEstimationTransaction(BtcWalletService.java:923)
	at bisq.desktop.main.portfolio.pendingtrades.steps.buyer.BuyerStep4View.reviewWithdrawal(BuyerStep4View.java:182)
	at bisq.desktop.main.portfolio.pendingtrades.steps.buyer.BuyerStep4View.lambda$onWithdrawal$2(BuyerStep4View.java:166)
...
```

**Comment by ghost** [comment]
### Steps to reproduce, example 1

- Alice: Create two trades with Bob as either maker/taker, and take them through to step 4.
- Alice: At step 4, withdraw one of the trades to external wallet.
- Alice: At step 4, attempt to withdraw the other trade to external wallet.  It will fail with this error.

### Steps to reproduce, example 2

- Alice: Create one trade with Bob as either maker/taker, and take it to step 4.
- Alice: Shut down bisq application, and restart.
- Alice: At step 4, attempt to withdraw the trade funds to external wallet.  It will fail with this error.

In both scenarios the following warning will be observed in the log, some point earlier:

`WARN  bisq.core.trade.TradeManager: We found an outdated addressEntry for trade [offerid]: entry=AddressEntry{offerId='[offerid]', context=TRADE_PAYOUT, address=[address]}`

That log message represents a point in the code where the reserved address is (prematurely) released from the offer back to the bisq wallet.

Then you get the Missing x.xxxx BTC / Insufficient Funds error:

![image](https://user-images.githubusercontent.com/47253594/82081050-49cd8080-96ab-11ea-9eb4-2de7c6f7cbcb.png)
