### ISSUE TITLE
Exporting trade history to CSV has incorrect fee values

### ISSUE THREAD

**Issue by dextertd** [bisq-network/bisq#4207]
### Description

Exporting the trade history CSV using the EXPORT TO CSV button in PORTFOLIO -> HISTORY produces incorrect fee values ("Transaction Fee" and "Maker Fee").

#### Version

1.3.2

### Steps to reproduce

See description.

### Expected behaviour

EXPORT TO CSV creates a CSV with correct values for columns "Transaction Fee" and "Maker Fee". 

### Actual behaviour

EXPORT TO CSV creates a CSV with incorrect values for columns "Transaction Fee" and "Maker Fee". For example, my CSV says Transaction Fee: 0.00006080; Maker fee: 0.00043750; but that trade's JSON data is "txFee": 6560, "makerFee": 36. The fees for this trade were paid in BSQ.

#### Device or machine

Linux Mint 19.3 Tricia x86_64
MATE

**Comment by ghost** [comment]
- `Maker Fee` : This is sometimes displaying the counterparty's trading fee.  In addition to fixing the logic about displaying the correct fee, it should be renamed to `Trading Fee` since the user is not always maker.
- txFee : it is sometimes displaying the counterparty's txFee.
