### ISSUE TITLE
timeouts are keeping me from trading in China, possible to raise timeouts?

### ISSUE THREAD

**Issue by jagottsicher** [bisq-network/bisq#4220]
### Description

ERROR occurs for at least 4 weeks now for every order I take:

An error occurred when taking the offer.

A timeout occurred.

No funds have left your wallet yet.
Please try to restart your application and check your network connection to see if you can resolve the issue.Please try to restart your application and check your network connection to see if you can resolve the issue.
#### Version

als version from 1.2.9 - 1.3.4

### Steps to reproduce

Taking a sell order to buy btc

### Expected behaviour

it shall work smootly like it did before

### Actual behaviour

Error occurs (timeout)

#### Device or machine

Intel i3, Linux ubuntu 18.04 LTS with desktop Gnome

#### Additional info

In China you have to use VPN to tunnel through GFoC, nevertheless, I use TOR with the provides bitcoin Core nodes and Tor obfuscation V4. Problem occurs with both Astrill VPN and nordVPN and also without any VPN.

During startup for some weekd it talways takes quite long and after reaching connection 3/4 often the Tor-settings windows pops up. So it just takes quite long to connect.

Is it possible to extend the "time-to-live" to have a longer timeout tolerance?

[bisq.log](https://github.com/bisq-network/bisq/files/4562143/bisq.log)

**Comment by ripcurlx** [comment]
This should be solved with https://github.com/bisq-network/bisq/pull/4233. Unfortunately because of the complexity of this PR testing & roll out will take some time.

**Comment by ripcurlx** [comment]
@jagottsicher Did the changes introduced in v1.4.2 improve your situation?

**Comment by ripcurlx** [comment]
@jagottsicher ☝️
