### ISSUE TITLE
UI: Synchronize currency filter across views

### ISSUE THREAD

**Issue by cd2357** [bisq-network/bisq#4224]
### Description

There are several views with currency filters. Currently these filters are mostly independent from each other, although sometimes they are "linked" with the currency of the price ticker in the top right.

This means if a user is interested in a specific currency, he has to always re-select that currency in each view he navigates to.

It would be better to apply the currency filter consistently, to all views (+ to the price ticker top right).

#### Version

v1.3.4

### Steps to reproduce

* Go to `Market > Offer Book` and filter by GBP
* Go to any other view (for example, `Market > Trades`) and notice the currency filter is not GBP

### Expected behaviour

If a user chooses to filter by a currency in one view, the same currency filter would also be applied to all other views

### Actual behaviour

Currency filters are set per view (they are not synchronized across views)

**Comment by ghost** [comment]
I agree it is extremely counter-intuative when switching between `BUY BTC`, `SELL BTC`, `MARKET`, `OFFER BOOK`, and `TRADES` that the currency filter is set to a different value between them all.  As described above, it should be one filter applied across all those screens.

Another annoyance is the`OFFER BOOK` currency drop down which contains every currency under the sun, whereas it should be limited to what was chosen via `Settings`.

**Comment by ripcurlx** [comment]
> Another annoyance is the`OFFER BOOK` currency drop down which contains every currency under the sun, whereas it should be limited to what was chosen via `Settings`.

I think atm it displays all currencies that have currently offers available. Maybe we could change that when we implement the new onboarding where the Settings list for currencies is populated in that process. Or we change it that we only add additional to the main fiat & crypto currencies only the one based on the locale of the user.

**Comment by ghost** [comment]
Please keep this open.

**Comment by pazza83** [comment]
This seems like a good idea. I would also like to figures in the DAO section in local currency.
