### ISSUE TITLE
'Input of 0 is not allowed' popup persists on top of offers if incomplete offer not canceled

### ISSUE THREAD

**Issue by paultroon** [bisq-network/bisq#423]
Repo:
- click 'Buy Tab' and 'Create new offer for buying bitcoin' button
- start to fill out a trade, but 'Amount of Bitcoin to buy' is zero
- click 'Account'
- click 'Buy Tab'

Expect:
- normal list of offers

Instead:

![image](https://cloud.githubusercontent.com/assets/1126871/14961834/1c4811e6-109c-11e6-9628-38f6049d339e.png)

This floating error persists until you cancel the incomplete buy offer

**Comment by ManfredKarrer** [comment]
Fixed with https://github.com/bitsquare/bitsquare/commit/e522fed5d15f5d12d3c97d444d84299a5d4bb599
