### ISSUE TITLE
Erro on first selling

### ISSUE THREAD

**Issue by zora-li** [bisq-network/bisq#4234]
### Description

Erro when tried to sell first time btc.

### Steps to reproduce

After created a sell bid I added the valur to bisq wallet and clicked the red button.

#### Additional info

Ocorreu um erro ao colocar a oferta:

Attached log
[log_bisq.txt](https://github.com/bisq-network/bisq/files/4576805/log_bisq.txt)

**Comment by ripcurlx** [comment]
I see in your logs that it seems your wallet was missing the correct amount of BTC.

´An error occurred at task: CreateMakerFeeTx org.bitcoinj.core.InsufficientMoneyException: Insufficient money,  missing 0.0000052 BTC\`

At what point of the trade did you fund your Bisq wallet?

**Comment by ghost** [comment]
The mining fee increased from 96 to 98 sats per byte between offer entry and funding from external wallet.
This issue was fixed by #4345 in release 1.3.6.


    mai-04 14:48:59.334 [JavaFX Application Thread] INFO  b.c.p.f.FeeService: BTC tx fee: txFeePerByte=96 \
    mai-04 14:49:46.023 [JavaFX Application Thread] INFO  o.b.w.Wallet: Completing send tx with 2 outputs totalling 0.01205 BTC and a fee of 0.00 BTC/kB \

    mai-04 14:51:39.811 [JavaFX Application Thread] INFO  b.c.p.f.FeeService: BTC tx fee: txFeePerByte=98 \

    mai-04 14:52:05.782 [BlockingClient network thread for 4jyh6llqj264oggs.onion:8333] INFO  o.b.w.Wallet: Received a pending transaction 90db35f9610a21c559a4488016b6878b7b3eb158f31be5292acc195b064cc3e1 that spends 0.00 BTC from our own wallet, and sends us 0.0122996 BTC \

    mai-04 14:53:38.133 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: CreateMakerFeeTx \

    mai-04 14:53:38.150 [JavaFX Application Thread] WARN  b.c.b.w.TradeWalletService: createBtcTradingFeeTx failed: tradingFeeTx=  4267c62222a10f0bf186fe6bef2e79a5e0f7a531eecc6a4626e5b48ab19b3b65\
    mai-04 14:53:38.156 [JavaFX Application Thread] ERROR b.c.t.Task: An error occurred at task: CreateMakerFeeTx org.bitcoinj.core.InsufficientMoneyException: Insufficient money,  missing 0.0000052 BTC\

**Comment by ripcurlx** [comment]
Closing as complete based on https://github.com/bisq-network/bisq/issues/4234#issuecomment-668009808.
