### ISSUE TITLE
bisq app doesn't open

### ISSUE THREAD

**Issue by 11235j** [bisq-network/bisq#4241]
### Description

bisq won't open...I've tried many dozens of times and keep getting a keyPair error...I've attached an image of the error message and my log file
I have BTC in my account and can't access it

I've also deleted outdated Tor files dozens of times as well

#### Version

64bit-1.3.4.exe

### Expected behaviour

bisq should open

### Actual behaviour

bisq doesn't open
[d bisq logfile.txt](https://github.com/bisq-network/bisq/files/4589833/d.bisq.logfile.txt)

#### Device or machine

desktop Windows 10

#### Additional info

![d bisq error](https://user-images.githubusercontent.com/64932486/81236170-700b6600-8fb1-11ea-8d1b-26304971a985.jpg)

**Comment by cd2357** [comment]
You might want to check with support as well, but I believe `Alt+E` will open some kind of "emergency wallet sweep" popup, letting you retrieve the BTC from your Bisq wallet.

**Comment by 11235j** [comment]
Thanks for your help cd2357.  I hit alt+e and was asked for a destination address.  Can that be the public key to any BTC wallet I own?  I was also told to backup my data directory by going to Account/Backup, but I don't know how I can access that without opening the bisq app.  I also have my bisq password and my 12 word seed.
