### ISSUE TITLE
Only two offers in porfolio, but each listed 3+ times in offer screen

### ISSUE THREAD

**Issue by paultroon** [bisq-network/bisq#425]
Form Offer screen:

![image](https://cloud.githubusercontent.com/assets/1126871/14963136/963e6f1c-10a2-11e6-923b-c9ab31b8099f.png)

but from  my portfolio / open offers:

![image](https://cloud.githubusercontent.com/assets/1126871/14963184/c6e3b3d4-10a2-11e6-9d3d-abd3027bb262.png)

You can see I have two offers, one is % and one is fixed price.

version 0.4.6, Windows 10 x64

**Comment by paultroon** [comment]
Restarting bitsquare fixed the problem, so maybe some sort of transitory issue related to #424

**Comment by ManfredKarrer** [comment]
Yes I think it is related to #424. Tried to fix it but still happening some times. Will try to get that fixed with the next release.
