### ISSUE TITLE
Error when trying to confirm payment reciept

### ISSUE THREAD

**Issue by jeforson** [bisq-network/bisq#4252]
### Description

Cannot Confirm Payment Reciept
#### Version

1.3.4
### Steps to reproduce

Currently on step 3 of a trade where I am the BTC seller.  The buyer has sent me the money but now when I click "Confirm Payment Receipt", I get an error and it won't send confirmation and close the trade out.
### Expected behaviour

Allowing me to confirm I got money and to close the trade out.
### Actual behaviour

Giving an error
### Screenshots

see attached
[Doc1.docx](https://github.com/bisq-network/bisq/files/4606163/Doc1.docx)

#### Device or machine

Windows 10

**Comment by jeforson** [comment]
See below for the log:
[bisq log.txt](https://github.com/bisq-network/bisq/files/4606187/bisq.log.txt)

**Comment by ghost** [comment]
Same issue as #4065

**Comment by jeforson** [comment]
After about two hours of pressing the confirm button every so often, it just went through.  I tried multiple reboots, spv file delete, etc. before it basically worked itself out.
