### ISSUE TITLE
Raspberry Pi build as a "server" and local Web"client"

### ISSUE THREAD

**Issue by phenomeus** [bisq-network/bisq#4254]
hi everybody,

Bisq is awesome. Bisq is revolutionary but Bisq has to run 24/7 to operate correctly. 
the best machine to run 24/7 is a raspberry pi that is already running because its a bitcoin fullnode that Bisq can use. 

why is there no headless server solution that can be controlled from a browser frontend, that even can be controlled from outside with vpn/wireguard? 

that would be sooooo cool. :) and no, I don't have the skills. unfortunately

**Comment by cd2357** [comment]
As far as I know, there are already efforts in this direction -- an API is being worked on which could be used in many ways. The web client you mentioned would probably be just one of the clients and integrations possible :)

**Comment by phenomeus** [comment]
ETA?! :D

**Comment by cd2357** [comment]
See #4257
