### ISSUE TITLE
Couldn't generate key

### ISSUE THREAD

**Issue by loviswater** [bisq-network/bisq#426]
Couldn't generate key

Error comes up when starting the program and again when I attempted to start a buy offer for ETH.  I was able to do MAID fine?

Here is similar error when attempting to sell BTC for ETH

An error occurred when taking the offer.

An error occurred.
Error message:
Couldn't generate keyPlease try to restart you application and check your network connection to see if you can resolve the issue.

**Comment by ManfredKarrer** [comment]
Do you have the latest version installed? 04.6.

**Comment by ManfredKarrer** [comment]
Please re-open if you get that issue wiht the latest version.

**Comment by loviswater** [comment]
Yes it was 04.6.

**Comment by ManfredKarrer** [comment]
So if you still get that issue with the latest verion (assuming you arre using the binary and not a self compiled version) could you send me your data directory, so I can investigate (my email u find on the webpage)? You can open the data dir under account/backup. You can remove the wallet (mainnet/bitcoin) before sending me the zipped directory. If you dont want to do that, could u send me the log file?

**Comment by loviswater** [comment]
Using surface Pro Win 10.  AppData/local/Bitsquare  What files from there?

**Comment by MarcSte** [comment]
In the Bitsquare software go to ->**Account** ->**Backup** ->**Open Directory**

You looked here: AppData/local/Bitsquare
but it's there: AppData/**roaming**/Bitsquare

**Comment by ManfredKarrer** [comment]
@neo-thematrix 
Could you sned me your data directory? Otherwise it is hard to investigate further that issues as it is not reproduceable for me.
