### ISSUE TITLE
Support tBTC token

### ISSUE THREAD

**Issue by danimesq** [bisq-network/bisq#4261]
I know, users can simply use an Ethereum's decentralized exchange (such as UniSwap) for that.

But the matter is: tokenizing Bitcoin to Ethereum, in a trustless way.

tBTC is the first to do it, if you've heard. The problem is: smart-contract fees are very high for tokenizing your Bitcoin, which means it can be done just with high amounts.

Bisq can help on that. By supporting tBTC and adding a swap pair BTC <> tBTC, users can tokenize Bitcoin (or redeem tBTC) with very small amounts.

**Comment by huey735** [comment]
Asset listing is on hold - https://github.com/bisq-network/proposals/issues/166

**Comment by danimesq** [comment]
@huey735 

tBTC will be launched soon.
Bisq can start by listing renBTC.

**Comment by cd2357** [comment]
Closing, because asset listing is put on hold: https://github.com/bisq-network/proposals/issues/166
