### ISSUE TITLE
build failed: could not open terminal

### ISSUE THREAD

**Issue by dchmelik** [bisq-network/bisq#4267]
### Description

FAILURE: Build failed with an exception.

* What went wrong:
Could not open terminal for stdout: could not get termcap entry

#### Version

1.3.4

### Steps to reproduce

gradlew build

### Expected behaviour

build

### Actual behaviour

doesn't finish

#### Device or machine

Slackware64 14+-current

**Comment by cd2357** [comment]
Seems to an issue that gradle has in some environments:

https://pt.stackoverflow.com/questions/297804/could-not-open-terminal-for-stdout

https://github.com/gradle/gradle/issues/4426

Perhaps try some of the workarounds in the 2nd link, like this one: https://github.com/gradle/gradle/issues/4426#issuecomment-483658712

**Comment by dchmelik** [comment]
That fixed that problem, but now I get the following.

```
> Task :assets:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':assets:compileJava'.
> Could not target platform: 'Java SE 10' using tool chain: 'JDK 8 (1.8)'.
```

I think I know what to install.

However, please list full dependencies--independent of any OS distribution--for Bisq.
