### ISSUE TITLE
connection to the bitcoin network failed

### ISSUE THREAD

**Issue by onlymarcus** [bisq-network/bisq#4271]
### Description

Bisq is unable to connect to the network

#### Version

bisq 64bit 1.3.4

### Expected behaviour

connection

### Actual behaviour

not connection

### Screenshots

![bisq1](https://user-images.githubusercontent.com/36059034/82676561-fe702080-9c1c-11ea-9c80-4e85ef80b1fc.PNG)
![bisq1 1](https://user-images.githubusercontent.com/36059034/82676580-05972e80-9c1d-11ea-960a-46e2adbeb27e.PNG)
![bisq2](https://user-images.githubusercontent.com/36059034/82676600-0b8d0f80-9c1d-11ea-85c6-9d4db341db21.PNG)
![bisq3](https://user-images.githubusercontent.com/36059034/82676616-10ea5a00-9c1d-11ea-87b0-1eb1aad542eb.PNG)

#### Device or machine

VAIO
Positivo tecnologia S.A.
Inter Core i7-7500U CPU 2.7GHz
4 GB
Windows 10 64bits

**Comment by onlymarcus** [comment]
Please can someone from support help me?

**Comment by Bayernatoor** [comment]
Hey @onlymarcus That error is wallet related. Is this an old wallet, have you generate a lot of addresses from it?

**Comment by wiz** [comment]
Delete your .spvchain file and restart
