### ISSUE TITLE
Maker Payout Account null/ 0 blockchain confirmations error

### ISSUE THREAD

**Issue by leo816** [bisq-network/bisq#4276]
### Description

User got this error message when he created an offer. After a day the offer got accepted but it's not getting blockchain confirmations. It's been nearly 24hrs later and still nothing.
 the tx fees were set correctly. There isn't enough traffic in the network to explain this delay.

#### Version

1.3.4

### Steps to reproduce
User mentioned that before creating this offer he had to use the seed words to get his wallet back from a previous computer formatting he had done. This has never happened to him before so that seems to be the cause with this particular issue.

### Screenshots

![WhatsApp Image 2020-05-26 at 11 49 35](https://user-images.githubusercontent.com/54798241/82993445-d871c400-a000-11ea-9a6b-f11efe01365f.jpeg)

![WhatsApp Image 2020-05-27 at 09 41 08](https://user-images.githubusercontent.com/54798241/82994124-f4c23080-a001-11ea-9178-71c39f7f94c3.jpeg)

#### Device or machine

MacBook Pro

**Comment by ripcurlx** [comment]
Is this issue already handled?
