### ISSUE TITLE
Error occured at task CreateMakerFeeTx

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#4278]
### Description

I made an offer to buy 0.01 Bitcoin. After I sent the transaction fees which was asked for (0,006516 BTC), and hit the confirmation button, the error message occured as mentioned in the title.  

The offer is placed. Can the trade be done?!
**EDIT:** My order has been accepted meanwhile and the trade is being performed at the moment. 

#### Version

1.3.4

### Steps to reproduce

What I did was
1. setting up offer with buying 0.01 BTC with -3% below market price
2. waiting for about 10-20 minutes as I was doing other things meanwhile; after this wait time, it was not possible to change the "below market price" entry anymore (greyed out with a yellow warning triangle saying something I can't remember)
3. Transferring the deposit and fees
4. Confirming the offer

### Expected behaviour

The placement of my offer.

### Actual behaviour

The offer has been placed but the error message created concerns if the trade could be executed, see also: https://github.com/bisq-network/bisq/issues/4277#issue-626819328

### Screenshots

![screenshot](https://user-images.githubusercontent.com/66221034/83361134-b4a6d900-a386-11ea-8cc1-63685dcee743.jpg)

#### Device or machine

HP Envy i7 Notebook Win 10

#### Additional info
[Protokolldatei.txt](https://github.com/bisq-network/bisq/files/4708278/Protokolldatei.txt)

**Comment by ghost** [comment]
Sounds similar to https://github.com/bisq-network/bisq/issues/4227.  Is it the same steps as what you encountered?  https://github.com/bisq-network/bisq/issues/4227#issuecomment-629521456

**Comment by ghost** [comment]
- Empty Bob's bisq wallet to an external wallet.
-> I didn't do that.
- Bob enters an offer to buy BTC, funds it from external wallet (exact amount), BUT DOES NOT YET PLACE THE OFFER.
-> Yes, I did that too. 
- Bob leaves the review: place offer to sell bitcoin message up for some time. This is to allow a new fee estimate to arrive from the web. For this problem to manifest, fees should be rising.
->I left this window open 1-2 minutes
- Finally Bob hits the button to review, then place the offer.
-> Yes
- The error dialog pops up: "An error occurred at task: CreateMakerFeeTx" "Insufficient money, missing 0.xxxx BTC".
-> Yes

Please see my edited thread opener. The trade could be eventually executed.

**Comment by ghost** [comment]
Thanks for the input @sturmsignal, it is helpful!  Your log file seems to match mine.  See these last lines from the log, at that point the offer is not created, it shows the error screen then takes you back to the `Review: Place offer to sell` screen.  Did you keep trying and eventually the offer was able to be placed?

    Mai-31 20:37:24.213 [JavaFX Application Thread] ERROR b.c.t.TaskRunner: Task failed: CreateMakerFeeTx / errorMessage: An error occurred at task: CreateMakerFeeTx 
    Mai-31 20:37:24.213 [JavaFX Application Thread] ERROR b.c.o.p.PlaceOfferProtocol: An error occurred at task: CreateMakerFeeTx 
    Mai-31 20:37:24.213 [JavaFX Application Thread] ERROR b.d.m.o.c.CreateOfferDataModel: An error occurred at task: CreateMakerFeeTx 
    Mai-31 20:37:35.177 [JavaFX Application Thread] INFO  b.c.p.f.FeeService: BTC tx fee: txFeePerByte=25

**Comment by ghost** [comment]
Yes, this is exactly what I did.

**Comment by supertestnet** [comment]
I experienced the same issue. The app spent maybe 3 minutes waiting for me to fund my wallet while I fiddled with my phone to get it to scan the qr code. When I reviewed the order and hit the confirm button, it said there was an error involving the maker fee transaction. My fourth attempt succeeded. My logfile (up til the error occurred) is attached.
[logfile.txt](https://github.com/bisq-network/bisq/files/4755409/logfile.txt)

**Comment by ghost** [comment]
@supertestnet thanks for providing the report.  I'm fairly sure that your issue is related to https://github.com/bisq-network/bisq/issues/3666 (wrong miner fee displayed for offer maker).  There is a [fix](https://github.com/bisq-network/bisq/pull/4223) scheduled for release 1.3.5, due in a few days.  A workaround is to click on the QR code which opens a bigger QR code that always has the correct amount.
