### ISSUE TITLE
A bug in Dockerfile

### ISSUE THREAD

**Issue by wangluochao902** [bisq-network/bisq#4279]
https://github.com/bisq-network/bisq/blob/bc3e12288dc3927b7204ce22015bb6629c9095f0/desktop/package/linux/Dockerfile#L13
Hi, we are developing a tool to detect typos/bugs in dockerfiles automatically. Our tool finds a potential bug above. Is it a bug? we believe it needs a '\\' at the end of the line. Our tool is currently available here https://wangluochao902.github.io/clcheck/

**Comment by ripcurlx** [comment]
@mrosseel Do you want to have a look at this?

**Comment by mrosseel** [comment]
this is a reasonable suggestion, see https://docs.docker.com/develop/develop-images/dockerfile_best-practices/ and search for 'line continuation'

utACK

**Comment by ripcurlx** [comment]
> this is a reasonable suggestion, see https://docs.docker.com/develop/develop-images/dockerfile_best-practices/ and search for 'line continuation'
> 
> utACK

Could you prepare a PR for it? Thanks!
