### ISSUE TITLE
Confirmations not updating, accepted offer stuck in dev mode

### ISSUE THREAD

**Issue by woodser** [bisq-network/bisq#4289]
### Description

Funds > Receive Funds shows new incoming transfers but the confirmations are not updating - they show a static image of a spinning progress wheel.

Also, a test trade is stuck waiting for a blockchain confirmation before starting the payment.

The buyer, Bob, shows this message:
```
Deposit transaction has been published.
You need to wait for at least one blockchain confirmation before starting the payment.
```

The status bar says "Bitcoin network peers: 1 / Synchronized with Bitcoin Regtest"

`generatetoaddress amount address` in bitcoin-qt does not resolve the issue.

#### Version

1.3.4 and master

### Steps to reproduce

1. start bitcoin-qt, the seed node, arbitrator/mediator, and 2 trader instances in regtest per the dev readme.
2. `generatetoaddress 1 "address"`.  the guis show they are connected.
3. Incoming transfers to Funds > Receive Funds appear but confirmations do not update.
4. Test trade between Bob and Alice is stuck with message "Wait for blockchain confirmation" and `generatetoaddress` does not resolve it.

#### Device or machine

Mac

**Comment by ghost** [comment]
I'm using the older, [deprecated version](https://github.com/bisq-network/bisq/tree/master/docs/autosetup-regtest-dao) of the dev environment and in that version there is a [blocknotify](https://github.com/bisq-network/bisq/blob/master/docs/autosetup-regtest-dao/blocknotify) script that bitcoin core invokes to publish new blocks to a port which the seed nodes/Alice/Bob instances listen to.

I think the most recent dev setup information is contained in [Makefile](https://github.com/bisq-network/bisq/blob/master/Makefile).  That also uses a blocknotify script.  See if you can get your environment up and running using that, it has instructions in the file comments.

Maybe the [dev doc](https://github.com/bisq-network/bisq/blob/master/docs/dev-setup.md) is missing a detail.  @petrhejna you recently followed the normal dev setup, did you run into any issues with blocks not being propagated to bisq_desktop?
