### ISSUE TITLE
Rel/v1.3.5 TestCase restore wallet from seed at app startup failed (regtest/dev mode only)

### ISSUE THREAD

**Issue by ghubstan** [bisq-network/bisq#4293]
#### Test Case fails in regtest / dev mode only
The test case described in https://bisq.ontestpad.com/script/200#11
_"Scenario: Password protected wallet can be restored using seed words from the password prompt at application startup"_ failed.

Each window in the process freezes my Ubuntu 18 display multiple times, and procedure fails to restore the password encrypted wallet.  Note:  the frozen display problem may be related to running multiple Bisq processes on a single host.  This happens during every test cycle I work on, but the problem is not as pronounced as it is in this test case failure.

#### Version

release/v1.3.5   at   commit 4ee2f355dca1e0b8e6a482a192d1c0b0c214b4d8

#### Test case passes when running single Bisq process (desktop) on mainnet

BITCOIND  Start bitcoind in regtest mode

SEEDNODE 
	`seednode/build/libs/seednode-all.jar --seedNodes=localhost:2002 --bitcoinRegtestHost=localhost --rpcBlockNotificationPort=5000 --rpcHost=localhost --rpcUser=me --rpcPassword=password --baseCurrencyNetwork=BTC_REGTEST --rpcPort=18443 --daoActivated=true --fullDaoNode=true --useLocalhostForP2P=true --useDevPrivilegeKeys=true --nodePort=2002 --appName=bisq-BTC_REGTEST_Seed_2002`

ARBITRATION NODE (register mediator and refund agent after arbitration desktop starts up)
	`desktop/build/libs/desktop-1.3.5-all.jar -seedNodes=localhost:2002 --daoActivated=true --fullDaoNode=true --genesisBlockHeight=111 --genesisTxId=30af0050040befd8af25068cc697e418e09c2d8ebd8d411d2240591b9ec203cf --baseCurrencyNetwork=BTC_REGTEST --useLocalhostForP2P=true --nodePort=4444 --appName=bisq-BTC_REGTEST_Arb_dao --useDevPrivilegeKeys=true --bitcoinRegtestHost=localhost --rpcHost=localhost --rpcUser=me --rpcPassword=password --rpcPort=18443 --rpcBlockNotificationPort=5001`

BOB
	`desktop/build/libs/desktop-1.3.5-all.jar --seedNodes=localhost:2002 --daoActivated=true --fullDaoNode=false --baseCurrencyNetwork=BTC_REGTEST --bitcoinRegtestHost=localhost --rpcHost=localhost --rpcPort=18443 --rpcUser=me --rpcPassword=password --rpcBlockNotificationPort=5003 --genesisBlockHeight=111 --genesisTxId=30af0050040befd8af25068cc697e418e09c2d8ebd8d411d2240591b9ec203cf --useDevPrivilegeKeys=true --useLocalhostForP2P=true --nodePort=6666 --appName=bisq-BTC_REGTEST_Bob_dao` 

#### Click "FORGOT PASSWORD?" under "Enter password to unlock" prompt

	
![forgot-pwd-1](https://user-images.githubusercontent.com/36207203/84409744-26cbb900-abe4-11ea-9136-dfded1721121.png)

#### Type or paste seed words into "Restore wallets from seedwords" text box, and click "RESTORE WALLETS" button

![forgot-pwd-2](https://user-images.githubusercontent.com/36207203/84409924-3519d500-abe4-11ea-8c91-b92faed439db.png)

#### Click "I WANT TO RESTORE ANYWAY" button

![forgot-pwd-3](https://user-images.githubusercontent.com/36207203/84410079-406d0080-abe4-11ea-9d13-48d7c38c8d19.png)

	
#### Find yourself back to the "Restore wallets from seedwords" window (nothing changed)
	
![forgot-pwd-4](https://user-images.githubusercontent.com/36207203/84410148-45ca4b00-abe4-11ea-8b17-c0a85dba2a55.png)

	 

### Expected behaviour

After completing the steps described above, the wallet should be restored, unencrypted, and desktop should shut down.  On failure, an error message describing the failure should appear.

### Actual behaviour

Bisq UI goes into a loop:  "RESTORE WALLETS" -> "I WANT TO RESTORE ANYWAY"
		->  "RESTORE WALLETS" -> "I WANT TO RESTORE ANYWAY" 
		->  "RESTORE WALLETS" -> "I WANT TO RESTORE ANYWAY" 
		...

And each window freezes the computer screen.  
(This could be a problem specific to my NVIDIA on Ubuntu 18 GPU.)		

#### Device or machine

MSI laptop, Ubuntu 18, NVIDIA GTX 960M

**Comment by ghubstan** [comment]
Still an issue in release v1.3.6 test session:
See https://bisq.ontestpad.com/script/214#19/2

**Comment by ghost** [comment]
This issue also happens in production (mainnet).

It is a race condition in PopupManager when with a stack of 2 popups, the top popup is being replaced by another top-level popup.  The base layer popup ends up on top of the z-order, obscuring the correct one.  

(If you are using Ubuntu, click on the Bisq icon on the left of the screen, it will show you the three windows in the stack and you can select the correct one).

Fix incoming.
