### ISSUE TITLE
Error java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by dougbebber** [bisq-network/bisq#431]
Running BitSquare 0.4.6 on Mac OS X El Capitan version 10.11.2.

Just received the following error while navigating from "Support" window back to the Offer book page.

I have had the previous Error messages I reported here (Error -9 and Error -1).

<img width="670" alt="screen shot 2016-05-04 at 8 34 17 am" src="https://cloud.githubusercontent.com/assets/2474050/15015703/0780af42-11d3-11e6-9425-79c1da1151fd.png">

**Comment by dougbebber** [comment]
This is repeatable when I move from the "Support" page (after receiving information popup) back to the "Offer" page - I receive the Error - java.lang.ArrayIndexOutOfBoundsException.

**Comment by ManfredKarrer** [comment]
Fixed with https://github.com/bitsquare/bitsquare/commit/afb8c18d31825453e0070c0dc944867c42e627e7
Will be deployed with next version.
