### ISSUE TITLE
v1.3.5 source code archives can not be build

### ISSUE THREAD

**Issue by CheckQ** [bisq-network/bisq#4310]
### Description

build.gradle' line: 280 contains a sanity check if p2p/src/main/resources/ProposalStore_BTC_MAINNET has a specific format.

This check fails in all provided archives. E.g.
https://github.com/bisq-network/bisq/archive/v1.3.5.tar.gz
https://bisq.network/downloads/archive/v1.3.5.tar.gz
https://bisq.network/downloads/archive/v1.3.5.zip

In the v1.3.4 archives it was a big binary file - build was successful
In the v1.3.5 archives it is a small text file - build fails because of gradle sanity check

#### Version

In the provided v1.3.5 source code archives

### Steps to reproduce

Extract archive and try to build

### Actual behaviour

Task :p2p:processResources FAILED

FAILURE: Build failed with an exception.

Where:
Build file '/var/tmp/pamac-build-xxx/bisq/src/bisq-1.3.5/build.gradle' line: 280

What went wrong:
Execution failed for task ':p2p:processResources'.
p2p data store files have not been synchronized. To fix this, ensure you have Git LFS installed and run git lfs pull. See docs/build.md for more information.

**Comment by freimair** [comment]
we moved to git lfs for the big binary files.

You need to do a `git lfs install` ~~in the Bisq repo directory~~ once

EDIT: `git lfs install` will setup your git configuration for the user. after you did that, everything should work as before.

**Comment by CheckQ** [comment]
When I'm using git I can build bisq.
So, if it was intended to create the archives without the binary files then there is no issue.

**Comment by freimair** [comment]
well, that is not intended but github does it that way. sadly.

if you do not want to download all and everything consider doing a shallow clone (`git clone --depth=1 --branch=...`) or something.
