### ISSUE TITLE
Sort by time/date not working properly in the transaction tab under funds (0.4.6)

### ISSUE THREAD

**Issue by b3dk7** [bisq-network/bisq#432]
dates are not ordered correctly - see screenshot.
![sortbybitsquare](https://cloud.githubusercontent.com/assets/8342083/15039066/60bd1d9c-12a1-11e6-81c1-3ffbd0ccc54a.png)

**Comment by ManfredKarrer** [comment]
Fixed with https://github.com/bitsquare/bitsquare/commit/3bf861561b896e2ff3dd7cf1cfbc1d3037b06871.
Will be deployed with next release.
