### ISSUE TITLE
Create Snap / AppImage / Flatpak for linux

### ISSUE THREAD

**Issue by wuniversales** [bisq-network/bisq#4325]
I just think it is necessary for it to be really Linux compatible.

**Comment by rbrooklyn** [comment]
Anyone working on this?

I might be interested in creating a flatpak, but I don't wish to duplicate work.

**Comment by cd2357** [comment]
@rbrooklyn nobody working on it, AFAIK.

If you're interested in it, please give it a shot.

Feel free to create a PR, or you can also just post here the steps and instructions on how to create the flatpak.

**Comment by cd2357** [comment]
See https://docs.appimage.org/packaging-guide/introduction.html for how to package AppImages.

**Comment by flusedev** [comment]
I threw a quick and dirty script together that creates an appimage: [https://gitlab.com/-/snippets/3670160](https://gitlab.com/-/snippets/3670160)
