### ISSUE TITLE
Bisq does not retain bitcoin addresses & transactions following wallet recovery

### ISSUE THREAD

**Issue by mattmill30** [bisq-network/bisq#4338]
### Description

Attempting to recover a Bisq wallet in a fresh datadir on a separate computer, in an effort to mitigate #4307 results in a temporarily recovered wallet, which is erased when Bisq is shutdown after the recovery completes.

#### Version

v1.3.4

### Steps to reproduce

1. Launch Bisq with a fresh datadir
2. Begin wallet restoration using seed phrase and creation date (Account > Wallet Seed)
3. Restart Bisq and allow DAO synchronisation and wallet balance discovery to complete
4. Shutdown Bisq
5. Launch Bisq

### Expected behaviour

Wallet balance and receive addresses recovered through Wallet Restore are retained between Bisq relaunches.

### Actual behaviour

1. Wallet addresses and balances are recovered using Wallet Restore
![image](https://user-images.githubusercontent.com/6415621/85856578-2ae50280-b7b0-11ea-8c4f-2d38fd272cb5.png)

2. Wallet addresses and balances disappear following shutdown and relaunch of Bisq
![image](https://user-images.githubusercontent.com/6415621/85705849-87292300-b6d9-11ea-9155-db8bfac9aa16.png)

#### Device or machine

Win10 x64

**Comment by mattmill30** [comment]
I attempted to repeat the wallet recovery over the same datadir, and was presented with the following warning message, which I accepted "I want to restore anyway".
![image](https://user-images.githubusercontent.com/6415621/85863902-b2843e80-b7bb-11ea-80a5-988137d1bfd5.png)

After the recovery completed and I restarted Bisq an increased number of receive addresses were retained.
![image](https://user-images.githubusercontent.com/6415621/85864062-ed867200-b7bb-11ea-97e4-50ce13e92a59.png)

**Comment by mattmill30** [comment]
I attempted another recovery using the method in the previous post to see whether it would successfully retain additional receive addresses recovered during Wallet Restoration.
(https://github.com/bisq-network/bisq/issues/4338#issuecomment-650189343)

However, results were similar to the original restoration attempt in the original post.
![image](https://user-images.githubusercontent.com/6415621/85880936-ba041180-b7d4-11ea-98d3-6670f21e1fb7.png)

**Comment by cd2357** [comment]
> 2. Wallet addresses and balances disappear following shutdown and relaunch of Bisq

Can you recover the addresses and balances if you attempt a recovery a 2nd time? (So after the shutdown and relaunch which lost some of them)

**Comment by cd2357** [comment]
FYI from the [Backup and Recover](https://docs.bisq.network/backup-recovery.html) documentation:

> **The safest, quickest, easiest, and most comprehensive thing you can do is to back up this whole folder at regular intervals.** You can either close Bisq and copy this folder to your backup location, or you can export a backup directly to your backup location while Bisq is running from the Backup tab of the Account screen.

So if possible, aim to do a full data directory backup as described there.
