### ISSUE TITLE
Got error trying to place offer to buy several times, the problem is now solved, hoping I could get the fees back

### ISSUE THREAD

**Issue by namename555** [bisq-network/bisq#4344]
### Description

Was getting an error when trying to place an offer, got help on keybase, turns out I just had to update my version of Bisq (if only the error msg had said so!), and now the problem is solved.

Problem is each time I failed to place an offer (which I had to keep doing to see if the problem was fixed after trying different things like checking my network, doing a resync and so on) I was charged a fee, and I was hoping I could have those back, considering no offer was actually made.

#### Version

1.3.5

### Screenshots

![bsqq](https://user-images.githubusercontent.com/67520899/86042731-7fea7800-ba3f-11ea-9bcf-0f2f72f8de0f.jpg)

#### Device or machine

desktop, win10

Thanks!

**Comment by namename555** [comment]
Just wondering if I've missed anything? 
Would be great to get this sorted out.

**Comment by ripcurlx** [comment]
> Just wondering if I've missed anything?
> Would be great to get this sorted out.

@namename555 Please follow [this guide](https://bisq.wiki/Making_a_reimbursement_request) for reimbursement.

**Comment by namename555** [comment]
@ripcurlx only just managed to get back to this and saw your reply.
Thanks for the link, I will go through it now.

**Comment by namename555** [comment]
@ripcurlx I've read through and just want to confirm - in the form on bisq, where it asks for link to proposal, do I link to this post?

**Comment by namename555** [comment]
and one last question - it asks for the amount in BSQ, is it a 1=1 conversion to BTC?

**Comment by Bayernatoor** [comment]
@namename555 

You can submit this request by opening a new issue here: https://github.com/bisq-network/support/issues ... you can also follow this [guide](https://github.com/bisq-network/bisq/issues/4344) as mentioned by @ripcurlx. 

You can also refer to the other fee reimbursement requests on that issues page as a guide!

If you still have questions please let me know.
