### ISSUE TITLE
No way to receive SF in Bisq despite outstanding Sell order

### ISSUE THREAD

**Issue by harej** [bisq-network/bisq#4351]
### Description

When attempting to sell BTC for Siafund, I am asked to add an altcoin wallet. Except SiaCoin/Siafund wallets are not supported in the Bisq UI.

#### Version

1.3.5 macOS binary

### Steps to reproduce

1. Open Bisq

2. Go to "Sell BTC"

3. Filter by currency -> "SF - Siafund"

4. Click "take offer to buy SF".

5. A prompt comes up: "No matching trading account. To take this offer, you will need to set up a payment account using this payment method. Would you like to do this now?" Click Go to "Account"

6. You are taken to the "Account" tab. Click through to "Altcoin Accounts."

7. Click "Add New Account"

8. SiaCoin/Siafund is not on the list, and it is therefore impossible to submit a bid for a Siafund, even if you have the necessary BTC in your wallet.

### Expected behaviour

I expect to be able to add a SiaCoin wallet unlock hash (which supports Siafund as well) as a method of receiving payment.

### Actual behaviour

SiaCoin/Siafund is not on the menu of altcoin wallets.

### Screenshots

<img width="327" alt="Screen Shot 2020-07-01 at 8 43 11 PM" src="https://user-images.githubusercontent.com/150027/86314039-7c8bf380-bbdb-11ea-8783-e76eea067eb6.png">

#### Device or machine

2019 iMac running macOS 10.15.4 Catalina.

**Comment by harej** [comment]
After I filed this report, a Siafund trade was completed on the Bisq network. Afterward, the ability to add a Siafund wallet magically appeared in my settings where it did not before. This resolves the issue at least for my use case but it would be interesting if there were conditions that would cause certain altcoins to not show up.

**Comment by ripcurlx** [comment]
> After I filed this report, a Siafund trade was completed on the Bisq network. Afterward, the ability to add a Siafund wallet magically appeared in my settings where it did not before. This resolves the issue at least for my use case but it would be interesting if there were conditions that would cause certain altcoins to not show up.

@harej Altcoins get de-listed from the account selection as soon as they don't reach trading volume over a certain amount of time. If you do have an altcoin account already of a de-listed altcoin you can still trade. In this case after a trade occurred it was listed again and you were able to create an account.
