### ISSUE TITLE
New Action Protocol for MEDIATORS

### ISSUE THREAD

**Issue by leo816** [bisq-network/bisq#4356]
This is a proposal for a fixed action protocol for mediators, up until now was less vaguely established. These are some common situations that mediators stumble upon:

1) **_If the seller provides the wrong banking/address information_**

The seller will lose 50% of the deposit in favor of the buyer. Regardless as to whether the buyer wants to continue with the trade or not, this will be a fixed policy. 

2) **_If the buyer has made the payment and the seller is unresponsive:_**

Mediator will have to wait 48hrs for an answer from the btc seller, if he doesn’t respond, the seller will lose 100% of the deposit.  (keep in mind that it the seller will never lose 100% if the deposit because a fraction will always go back to him as we have had issues in the past with previous versions)

If the seller responds on time but from then on goes missing for 48hrs, the same applies.

3) **_If the buyer doesn’t pay from the correct account._**

+ Will incur in a penalty, losing 50% of the deposit. Regardless whether the seller wants to continue with the trade or not. (he has priority when choosing if he wants to continue)

Steps to follow:
+ Ask the buyer for a screenshot of the payment as proof using [Veruv.com](https://veruv.com).(where you can see the account he made it from) And an explanation as to why he didn’t comply with the contract.

+ Given that the seller wants to continue with the trade. The mediator will penalize the buyer by having him wait to receive his btc. 3 days before indicating the seller to release. Reminding him that this is a crucial issue at bisq and this is a way to protect it from a scam.
 + If the buyer doesn’t respond and the seller wants to cancel he can choose to return the payment and cancel the trade.

**Comment by MwithM** [comment]
I like standardizing dispute outcomes.

About case 2: If sellers loses all or nearly all in case of mediation,  the trades will end up in arbitration as sellers have nothing to lose they reject mediation.

**Comment by dcod3d** [comment]
> If the buyer doesn’t respond and the seller wants to cancel he can choose to return the payment and cancel the trade.

I'm running into this now with Zelle where there's a mismatch in the Bisq account name and the Zelle payer name. However, Zelle has no option to return payment so cancelling a trade does not seem to be an option.

**Comment by MwithM** [comment]
@ncstdc Can't you make a payment to the btc buyer's account just with the data extracted from zelle when receiving a payment?

**Comment by dcod3d** [comment]
@MwithM There is no way to return a Zelle payment. Sure, I can send it to the buyer, but if they're not the same person, I'm out twice if the payer is able to file a chargeback. I have cases with all current mediators with name mismatch, which is a direct violation of the trade protocol, and received different responses/rulings.

**Comment by leo816** [comment]
>  I have cases with all current mediators with name mismatch, which is a direct violation of the trade protocol, and received different responses/rulings.

@ncstdc That is the reason why im trying to establish an action protocol that can standarize this procedure. Please remember the mediator can only suggest an outcome, he doesn't have the power to make a payout. If the seller decides to release the btc, there is nothing that can be done from the side of the mediator. 

regarding @MwithM : 

> About case 2: If sellers loses all or nearly all in case of mediation, the trades will end up in arbitration as sellers have nothing to lose they reject mediation.

 Remember that these trades we are talking about (where the seller disappears) are all already ending up in arbitration for the most part, so It wouldn't make much difference. If the seller never responds, the trade will eventually go into arbitration and the refund agent can make the correct payout considering the mediator's suggestion. 
If you are talking about that time between the mediation ticket closed and the funds going to the donation address then that is definitely an issue we are working on but not there yet. 
Also, when making a mediation ticket there is a minimum payout mediators have to give back from the deposit (I believe is 0,003) so The seller could potentially lose that as well if the trade goes into arbitration for the sole purpose of penalizing the other party.

**Comment by MwithM** [comment]
> If the seller never responds, the trade will eventually go into arbitration and the refund agent can make the correct payout considering the mediator's suggestion.

The idea is to reduce arbitration cases, so leaving a space for sellers to save some btc if they accept the mediation makes sense to me. Refund agent should not take the mediator's suggested payout as the final decision, but ask why the mediator's suggestion was rejected and act accordingly: in this case, refund buyers with all the sellers' security deposits + trade funds.
