### ISSUE TITLE
Incorporate BitMessage communication in open trades

### ISSUE THREAD

**Issue by stevenroose** [bisq-network/bisq#436]
Just like OpenBazaar does, it could be useful to have a way to communicate with the people you are making trades with. This can be really valuable when trying to resolve disputes without having to rely on the arbitrator. Often there is just a misunderstanding or an error of the bank.

**Comment by MarcSte** [comment]
The absence of a messaging system is deliberate. Installing a message system imposes new risks for users like threatening, extortion and social engineering scams. In my opinion the benefits are slim as there's a an arbitration system in place for these cases. The risks outweigh the benefits and security is a primary concern of bitsquare.
