### ISSUE TITLE
Cannot delete selected Altcoin Instant Account

### ISSUE THREAD

**Issue by ghubstan** [bisq-network/bisq#4364]
### Description

You cannot delete an `Altcoin Instant Account` by selecting the account and clicking the `DELETE ACCOUNT` button.
(You can delete the account by clicking the stripped, red dot to the right of the listed account.)

This bug only affects Altcoin Instant Accounts, _basic_ Altcoin accounts can be deleted after selecting them.

#### Version

v1.3.5

### Steps to reproduce

Create an `Altcoin Instant Account`.  Here is a random `XMR` address:
`48f4GRtFf5Z2NyHZszseuJ7VuWvppfMHFBKScqFx5wGbNxiJWuFUTTLJggdcXPhAtsAJGBx7pXgqZG4WxA9sFv274mqSJWF`

Select the new Altcoin Instant Account.

![1](https://user-images.githubusercontent.com/36207203/87052561-4cde7c00-c1d7-11ea-9819-51d1f63953e1.png)

Click the DELETE ACCOUNT button.

Close the warning prompt by clicking YES.

![2](https://user-images.githubusercontent.com/36207203/87052587-523bc680-c1d7-11ea-98ba-5d10db3475d4.png)

Notice the Altcoin Instant Account has not been deleted.

![3](https://user-images.githubusercontent.com/36207203/87052623-59fb6b00-c1d7-11ea-8038-e6e9110c3d2c.png)

### Expected behaviour

Altcoin Instant Account is deleted.

### Actual behaviour

Altcoin Instant Account is not deleted.

#### Device or machine

Ubuntu 18

**Comment by ghost** [comment]
I've pushed a commit  https://github.com/bisq-network/bisq/pull/4362/commits/4364d55b0f39494e859719b72bbc9e7f850e0e82 to fix this.
