### ISSUE TITLE
Balances in bisq not displayed

### ISSUE THREAD

**Issue by JamesTwitter** [bisq-network/bisq#4367]
### Description

Bisq is not displaying all funds in wallet.

#### Version

1.3.2

### Steps to reproduce

1) Load bisq and add up funds under Available Balance & Reserved
2) Load electrum and import seed and add up addresses with funds.

### Expected behaviour

Bisq to display a balance of .9+ BTC

### Actual behaviour

Bisq to display a balance of ~.09 BTC

### Screenshots

<img width="1195" alt="Screen Shot 2020-07-11 at 5 25 56 PM" src="https://user-images.githubusercontent.com/46251733/87236257-bc9d6400-c39b-11ea-8835-956d3387fe4a.png">
<img width="827" alt="Screen Shot 2020-07-11 at 5 25 00 PM" src="https://user-images.githubusercontent.com/46251733/87236258-c0c98180-c39b-11ea-8a19-bfcee53ac84e.png">

#### Device or machine

Mac OS

**Comment by JamesTwitter** [comment]
Updated to 1.3.5. Same issue.

**Comment by dcod3d** [comment]
have you tried to `delete spv file and resync`

do you have the same addresses with coins? 
* electrum > `coins`
* bisq > `funds` > `send funds` and `reserved funds`

**Comment by JamesTwitter** [comment]
I have not tried that. If it would help you debug, I would be happy to give it a shot. I'm personally not worried about it since I have access to the coins in electrum. I just wanted to post this because I happened to load this wallet in electrum by pure chance. I very easily could have never found these coins. I wonder if there are any other bisq users who have coins and are unaware of it.

The same addresses have the coins in electrum and bisq. However, the addresses with balances in electrum aren't listed in bisq under "Send Funds" or "Reserved Funds."

**Comment by cd2357** [comment]
@JamesTwitter wrote:
> However, the addresses with balances in electrum aren't listed in bisq under "Send Funds" or "Reserved Funds."

Are they perhaps a different type of address, like bech32?

**Comment by JamesTwitter** [comment]
No, they all belong to the same address scheme.

**Comment by cd2357** [comment]
Is this still the case with the latest version (v1.6.4)? The BitcoinJ library used to manage the wallet got a few updates since you reported this 1y ago.
