### ISSUE TITLE
Confirm to buy leads to timeout

### ISSUE THREAD

**Issue by proof-of-reality** [bisq-network/bisq#4369]
### Description

Can't confirm take offer to buy bitcoin
A timeout exception was raised.

#### Version

1.3.6

### Steps to reproduce

1. Load Bisq and take an offer to buy bitcoin.
2. Add funds and confirm review.
3. Confirm review

### Expected behaviour

Go to next page of the process of buying btc

### Actual behaviour

Timeout occured.

### Screenshots

![image](https://user-images.githubusercontent.com/43297242/87712997-e5e53800-c77f-11ea-99ab-84c0b1fca4ea.png)

#### Device or machine

Win 10 Pro

#### Additional info

jul-16 16:14:08.258 [JavaFX Application Thread] ERROR b.c.t.p.TradeProtocol: Timeout reached. TradeID=KSEKXDGY-a10dbff4-9e92-415c-8bbf-e4f1fc285c87-135, state=PREPARATION 
jul-16 16:14:08.300 [JavaFX Application Thread] WARN  b.c.t.p.TradeProtocol: cleanupTradableOnFault tradeState=PREPARATION 
jul-16 16:14:08.302 [JavaFX Application Thread] WARN  b.c.t.TradeManager: We found an outdated addressEntry for trade KSEKXDGY-a10dbff4-9e92-415c-8bbf-e4f1fc285c87-135: entry=AddressEntry{offerId='KSEKXDGY-a10dbff4-9e92-415c-8bbf-e4f1fc285c87-135', context=MULTI_SIG, address=12iQWpBuBTh7jSeTi6UhhWsjfi83pezc8H} 
jul-16 16:14:08.302 [JavaFX Application Thread] INFO  b.c.b.w.BtcWalletService: swap addressEntry with address 12iQWpBuBTh7jSeTi6UhhWsjfi83pezc8H and offerId KSEKXDGY-a10dbff4-9e92-415c-8bbf-e4f1fc285c87-135 from context MULTI_SIG to available 
jul-16 16:14:08.303 [JavaFX Application Thread] INFO  b.c.b.w.BtcWalletService: swap addressEntry with address 1Q63AKqSZ4itKUtBKXrRXKQu197SMpWgAf and offerId KSEKXDGY-a10dbff4-9e92-415c-8bbf-e4f1fc285c87-135 from context TRADE_PAYOUT to available 
jul-16 16:14:08.303 [JavaFX Application Thread] WARN  b.c.t.TradeManager: We found an outdated addressEntry for trade KSEKXDGY-a10dbff4-9e92-415c-8bbf-e4f1fc285c87-135: entry=AddressEntry{offerId='KSEKXDGY-a10dbff4-9e92-415c-8bbf-e4f1fc285c87-135', context=TRADE_PAYOUT, address=1Q63AKqSZ4itKUtBKXrRXKQu197SMpWgAf} 
jul-16 16:14:10.759 [JavaFX Application Thread] INFO  b.d.app.BisqApp: System load: Memory (MB): 412 / No. of threads: 83 
jul-16 16:15:24.973 [JavaFX Application Thread] INFO  b.c.p.f.FeeService: BTC tx fee: txFeePerByte=30 
jul-16 16:17:30.116 [JavaFX Application Thread] INFO  b.c.d.n.l.LiteNode: New block at height 639544 from bsqWalletService 
jul-16 16:17:30.375 [JavaFX Application Thread] INFO  b.c.b.w.BsqWalletService: updateBsqBalance took 23 ms 
jul-16 16:17:32.871 [JavaFX Application Thread] INFO  b.c.d.s.DaoStateService: New Block added at blockHeight 639544 
jul-16 16:17:32.871 [JavaFX Application Thread] INFO  b.c.d.n.p.BlockParser: Parsing 0 transactions at block height 639544 took 0 ms 
jul-16 16:17:32.872 [JavaFX Application Thread] INFO  b.c.d.s.DaoStateService: Parse block completed: Block height 639544, 0 BSQ transactions. 
jul-16 16:17:32.872 [JavaFX Application Thread] WARN  b.c.d.g.p.ProposalValidator: proposal data fields are invalid. proposal=ChangeParamProposal{

**Comment by chimp1984** [comment]
This can happen if the peers got disconnected at the time when you took the offer.

**Comment by cd2357** [comment]
Closing, the reason for the popup is explained above.

@proof-of-reality When this happens, restart your Bisq and try to take the offer again. If it keeps happening for a specific offer (but not for others), then that peer has an unreliable connection, not much can be done about that.
