### ISSUE TITLE
Cannot resort with seed words

### ISSUE THREAD

**Issue by loviswater** [bisq-network/bisq#437]
I have BS installed 04.6 on windows machine. Saved my seed phrase and creation date. Installed BS on a Ubuntu with 04.6. Saved a password. input all the words for restore seed and place the correct creation date.  The "restore wallet" button still is not active.

**Comment by ManfredKarrer** [comment]
The creation date need to be the one from the wallet you want to apply the restore (the Ubuntu one in your case). Usually it is the same wallet but if you want to apply it to another wallet you need the creation data of that wallet. You can simply try a few days if you are not sure when you have created the Ubuntu wallet and see when the button gets enabled. 

The creation data is not very useful (and not intuitive in such cases like yours) and I don't know why BitcoinJ (the bitcoin lib I use) uses it at all. I wanted to get rid of it but it needs more time to investigate if that is possible without big changes in BitcoinJ.

If that does not help, let me know.

**Comment by ManfredKarrer** [comment]
Please re-open if you still have issues.
