### ISSUE TITLE
Bisq crash, logs provided

### ISSUE THREAD

**Issue by coinzdude** [bisq-network/bisq#4376]
### Description

Built bisq from source (Jul 25 2020), under WSL2, Ubuntu 20.04, running desktop bisq with vcXsrv 

#### Version

1.3.6

### Steps to reproduce

Just run bisq until crash.  Logs attached.

#### Additional info

[bisq.log](https://github.com/bisq-network/bisq/files/4977918/bisq.log)

**Comment by ripcurlx** [comment]
There is nothing obvious (exception or such) in you log. Was it a hard crash without any error popup from OS? Does it still start after the crash?

**Comment by coinzdude** [comment]
It's a hard crash.  App is gone, and I can restart it fine after the crash.  Any way to get more log data, or somehow catch the exception when it dies?

**Comment by coinzdude** [comment]
I just set ulimit -c unlimited, so I can send a core file soon if it captures the next crash

**Comment by coinzdude** [comment]
Even with ulimit -c unlimited set, there is no crash log, so it seems the app is just exiting itself?  I have no idea how to capture that detail if so.  I've compiled from source.  Is there a way to run it in debug mode and catch it shutting off?

**Comment by coinzdude** [comment]
I found that I was missing xdg-utils, and I'm also going to try the shipping binary.  Will report back.

**Comment by coinzdude** [comment]
I'm going to close this.  I have the pre-built running for 12 hrs without crash
