### ISSUE TITLE
Stuck on connecting to P2P network with 11 peers.

### ISSUE THREAD

**Issue by Codes4Fun** [bisq-network/bisq#438]
The program sits on the launch screen, it says it is connected and synced to the bitcoin mainnet with a green check icon, but sits there with a spinning icon for the P2P network. It shows 11 peers but that number changes to 12 and 10 sometimes.

It was actually running for a few days straight and I shut it down a few days ago working on the computer and only today I am trying to start it and have this problem. (Hoping my ISP is maybe not doing something against Tor :/)

If anything I would have expected to be able to get to the wallet so I can withdraw funds! Seems kind of bad that I can't use the wallet even if the bitsquare P2P network is not connectable for some reason.

**Comment by Codes4Fun** [comment]
Okay, it finally connected!

I also started ZeroNet which uses Tor, and it took a very long time to start as well, and in it's log I saw this: Your Guard *********\* is failing more circuits than usual. Most likely this means the Tor network is overloaded.

So I guess this was just the Tor network for some reason.

I am still concerned though about wallet access when unable to connect bitsquares P2P network.

**Comment by ManfredKarrer** [comment]
Yes Tor sometimes fail to get a reliable circuit, or it takes very long and then timeouts trigger a "restart" popup. Your ISP should not be the problem and does not see anything Tor related as long as you are not in China (there they block Tor with DPI). So in such cases a restart is usually the best way to get another circuit and hopefully faster startup. 30-40 sec. is the normal case. I observed e.g. 1 in 100 times that it needs a few minutes and then triggers the timeout. We will try to get the improved in future.

**Comment by ManfredKarrer** [comment]
You can always access the emergency wallet tool by clicking cmd+e (ctrol+e) even in the startup screen. But that whould be only used in emergency as if you have open offers those will get canceled as you would withdraw all your funds making open offers invalid. So I don't recommend that, and thats why it is a bit hidden with a shortcut and for emergency only if a UI bug might prevent you from withdrawing funds.
