### ISSUE TITLE
Spurious error about insufficient balance in Bisq wallet (0 BTC) while wallet has enough funds.

### ISSUE THREAD

**Issue by radfish** [bisq-network/bisq#4384]
### Description

Bisq wallet has balance, confirmed with 6 confirmations, reported in the balance indicator on top. But, when placing a buy BTC order, error popup is raised stating that Bisq wallet has 0 balance. After restarting Bisq, the error is no longer occurring. Can be a deterrent to new users.

Some state related to the balance goes stale, probably.

#### Version

1.3.6
AUR package: bisq
Arch Linux

**Comment by ripcurlx** [comment]
> Bisq wallet has balance, confirmed with 6 confirmations, reported in the balance indicator on top. But, when placing a buy BTC order, error popup is raised s

Did you have the `Create buy BTC` offer open already, before you funded your wallet?

**Comment by radfish** [comment]
On Wed, Jul 29, 2020 at 01:30:29AM -0700, Christoph Atteneder wrote:
> > Bisq wallet has balance, confirmed with 6 confirmations, reported in the balance indicator on top. But, when placing a buy BTC order, error popup is raised s
> 
> Did you have the `Create buy BTC` offer open already, before you funded your wallet?

I had no successfully opened offers in Portfolio, this was my first ever
offer that I was trying to create. However, the screen/tab for the
"Create buy BTC" was indeed open and in the "waiting for payment" stage,
while I was funding the Bisq wallet; but, I even tried canceling the
screen/tab and re-creating the offer and it still resulted in the same
error popup about insufficient funds in Bisq wallet (0 BTC), while
there were plenty of funds and 6 confirmations.

It should be reproducible, on a new installation of Bisq, I would bet.
