### ISSUE TITLE
Add download option + instructions for QubesOS

### ISSUE THREAD

**Issue by cd2357** [bisq-network/bisq#4386]
Looking at the [GitHub issues](https://github.com/bisq-network/bisq/issues?q=is%3Aissue+qubes), it seems there are quite a few QubesOS users of Bisq.

Since the Qubes setup is not very straightforward, it would help to add a section on the Downloads page with instructions specific to QubesOS.

Here are the instructions I came up with sofar.

---
### 1. Create a new Qube `bisq-vm` based on the `debian-10` template

* Q Menu > Create Qubes VM > Qube based on a template
* Template: choose `debian-10`
* Check "Launch settings after creation"
* Press OK

Within a few seconds, the Qube is created and the Qube Settings popup opens. Adjust it as follows:

* Basic > Disk Storage > Private Storage max size
  * Set this to at least `5000MiB`
  * Assuming you only use this Qube for Bisq, this amount of storage will be used for all Bisq files (downloaded installer, installation folder, your local Bisq settings and profile, your Bisq wallet, Bisq logs, etc). Therefore it is important to have enough disk space available, because if Bisq runs out of storage space, this may lead to data corruption and loss of funds.
  * For reference: A fresh Qube containing only a fully sync-ed new installation of Bisq 1.3.6, with no trades / accounts / balances, uses about 1GB of space.
* Advanced > Memory / CPU
  * Set "Initial memory" `6000 MB`
    * Bisq needs 4 GB, the rest is for other OS processes
  * Set "vCPUs no." to `4`
  * Uncheck "Include in memory balancing"
    * This will ensure that the RAM allocated to this Qube is not shared with other Qubes
* Press OK

### 2. Setup binding dirs mapping for the system folders needed for the Bisq installation

```
sudo mkdir -p /rw/config/qubes-bind-dirs.d
```

### 3. Specify which system folders are mapped to binding dirs

Create the configuration file:

```
sudo nano /rw/config/qubes-bind-dirs.d/50_user.conf
```

Add the following lines in the file:

```
binds+=( '/opt/Bisq' )
binds+=( '/usr/share/desktop-directories' )
```

Save and close the file.

### 4. Create the binding dirs needed for the Bisq installation

```
sudo mkdir -p /rw/bind-dirs/opt/Bisq
sudo mkdir -p /rw/bind-dirs/usr/share/desktop-directories
```

### 6. Download the Debian package

Go to the Bisq Downloads page https://bisq.network/downloads and download the Debian package.

Make sure you download the `.deb` package and the corresponding PGP signature.

### 7. Verify the PGP signature (see Verifications section on the [Bisq GitHub releases page](https://github.com/bisq-network/bisq/releases/))

```
# Go to the folder where you downloaded the .deb package and the PGP signature
cd Downloads

# Import the signing key of Christoph Atteneder
curl https://bisq.network/pubkey/29CDFD3B.asc | gpg --import

# Verify the signature of the downloaded binary
gpg --digest-algo SHA256 --verify Bisq-*.asc
```

### 8. Install package

```
sudo dpkg -i Bisq-*.deb
```

### 10. Optional: Create a keyboard shortcut

* Q Menu > System Tools > Keyboard > Application Shortcuts
* Add a shortcut where the command has the format `qvm-run -q -a <qube-name> <command>`
  * For example, in our case:  `qvm-run -q -a bisq-vm /opt/Bisq/Bisq`
* Assign a system-wide key combination for starting Bisq
  * For example `Ctrl+Alt+B`
* Press OK

Now pressing the key combination anywhere in QubesOS will automatically start the Bisq application.

### References:

* See [Qubes tutorial](https://www.qubes-os.org/doc/bind-dirs) for what binding dirs are and how they work
* See [Qubes documentation](https://www.qubes-os.org/doc/qmemman/) for how memory balancing works
* The `/usr/share/desktop-directories` is not really used, but is required during installation. See #848
* See https://www.whonix.org/wiki/Bisq for a similar setup guide for a [Whonix](https://www.whonix.org) Qube

**Comment by ripcurlx** [comment]
@cd2357 Could you as a first step add this documentation to the [wiki ](https://bisq.wiki/Downloading_and_installing#Qubes)similar how we did it with Tails? Thanks!

**Comment by chimp1984** [comment]
We should show a popup for those OS with a link to the wiki docs so users get the required info before getting frustrated...

**Comment by cd2357** [comment]
> Could you as a first step add this documentation to the [wiki ](https://bisq.wiki/Downloading_and_installing#Qubes)similar how we did it with Tails? Thanks!

@ripcurlx : Done: https://bisq.wiki/Running_Bisq_on_Qubes

> We should show a popup for those OS with a link to the wiki docs so users get the required info before getting frustrated...

@chimp1984 : Done, added a link from the Downloads page to the Qubes setup guide: bisq-network/bisq-website#397

**Comment by chimp1984** [comment]
@cd2357 Do you think an in-app popup with the link might be useful? Not sure how to detect if OS is Qubes but you know probably...

**Comment by cd2357** [comment]
Qubes can be detected in the app (via the `os.version` system property, which looks like `4.19.132-1.pvops.qubes.x86_64`).

Question is, when and where to show the popup?

The idea makes sense, just not sure what a simple and elegant UI solution would look like.

Maybe as an extra row on the startup splash screen?

**Comment by chimp1984** [comment]
You can look at BisqSetup.checkOSXVersion and do it in a similar way.
