### ISSUE TITLE
UI: Replace java.util.Collections with FXCollections

### ISSUE THREAD

**Issue by cd2357** [bisq-network/bisq#4388]
As per a [JavaFX performance tuning thread](https://wiki.openjdk.java.net/display/OpenJFX/Performance+Tips+and+Tricks), the use of the `FXCollections` API is encouraged when optimizing for performance.

As per the [`FXCollections javadoc`](https://docs.oracle.com/javase/8/javafx/api/javafx/collections/FXCollections.html):

> Utility class that consists of static methods that are 1:1 copies of `java.util.Collections` methods.
>
> The utility methods are here mainly for performance reasons. All methods are optimized in a way that they yield only limited number of notifications. On the other hand, `java.util.Collections` methods might call "modification methods" on an `ObservableList` multiple times, resulting in a number of notifications.

Replace all usages of `java.util.Collections` with `javafx.collections.FXCollections` in the `bisq-desktop` project (the only one where JavaFX is used).

**Comment by cd2357** [comment]
This is a low-hanging fruit sort of change, minimal effort required.

Could even be a "good first issue".

**Comment by ripcurlx** [comment]
Yes, might make sense to tackle a couple of this performance optimizations. But especially it would be good to update first to the new JavaFX version.

**Comment by vvkpd** [comment]
I would like to work on this card please let me know if required.

Thanks

**Comment by cd2357** [comment]
Yes sure, you can take it. Please submit a PR when you have it ready.

**Comment by vvkpd** [comment]
@cd2357 Thanks for assigning me on this task. I just started working on it.
Just a small suggestion: Could you please add **hacktoberfest** topic to repo and **hacktoberfest** as label in this task?
Background: I am participating in hacktoberfest 2020.
Thanks

**Comment by deusmax** [comment]
@vvkpd,  @cd2357 
Is work in this being done ?
