### ISSUE TITLE
Bisq connexion problem

### ISSUE THREAD

**Issue by svpi11** [bisq-network/bisq#4389]
Hello,

Since today I have an issue connecting to my bisq account. 

I can't understand well the error message, but I tried all I could (changing VPN, "deleting tor files" from the help bisq connexion page, restarting my rooter, laptop... etc) and nothing is changing.

Could someone help me to understand what is going on, or explaining me the error message ?

Sincerly thank you !!!
![image](https://user-images.githubusercontent.com/69041623/89036773-92591980-d33d-11ea-89ca-197f15f8c0aa.jpeg)

**Comment by svpi11** [comment]
It's ok, I found a solution charging a backup of bisq, but I am still curious about what happened...

**Comment by ripcurlx** [comment]
@svpi11 Could you please provide us with a log of the incident, so we can see more details on this exception?
@sqrrm Do you know why this can happen?

**Comment by svpi11** [comment]
Thank you for your answer ! :)

Sadly I have lost the logs now...
But I can understand it is more useful for you than an simple screenshot ! Next time I will publish it I promise ;)

**Comment by chimp1984** [comment]
Seems a protobuffer message was corrupted.

**Comment by svpi11** [comment]
Thanks all !
