### ISSUE TITLE
Error When Confirming Payment

### ISSUE THREAD

**Issue by dougbebber** [bisq-network/bisq#439]
When attempting to "Confirm payment receipt" I receive the following dialog (I have attempted to confirm numerous times now and get the same Warning):
<img width="600" alt="screen shot 2016-05-06 at 8 05 35 pm" src="https://cloud.githubusercontent.com/assets/2474050/15089323/41970ace-13c6-11e6-957e-9a998677bd15.png">

**Comment by ManfredKarrer** [comment]
Have you tried to restart the app? Otherwise you can open a support ticket by clicking cmd+o (or ctrl+o) at the trade screen with the trade selected for which you want to open a ticket.
Can you send me the logs as well?

**Comment by ManfredKarrer** [comment]
Should be resolved in the current version. Otherwise please re-open.
