### ISSUE TITLE
Deprecate Revolut phone numbers, require Revolut username

### ISSUE THREAD

**Issue by wiz** [bisq-network/bisq#4390]
Due to the recent changes with Revolut, I feel we should make username usage mandatory. We should replace the payment account creation text validation to disallow phone numbers and only allow usernames.

cc @bisq-knight @leo816 @m52go

**Comment by ripcurlx** [comment]
We have to do it similar as we did it with the move from e-mail to phone numbers in the past to be backwards compatible. But besides that :+1:

**Comment by wiz** [comment]
Yeah, discussed with @m52go on a long call yesterday, we found your previous work, and fortunately the code is using a generic "accountId" string, so we are planning to change the string input validation.

**Comment by pingiun** [comment]
This is a duplicate of #4155
