### ISSUE TITLE
Fix maven build, add builds for native app deployment

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#44]

**Comment by notmandatory** [comment]
I've got the javafx plugin working and the jfx:run goal works.  I just need to test creating a native app which I think requires me to install some packaging tools.

https://blogs.oracle.com/talkingjavadeployment/entry/native_packaging_for_javafx

**Comment by bisq-network** [comment]
Cool. 
Btw. I had problem with the version of the org.twdata.maven. I think it was 2.2.0 (or was it 2.1.0?) before and I could not find that and IntelliJ reported it as red, with 2.0 it worked. I also tried to add the repository but did not help either... Anyway feel free to change it back if needed...

Edit: Ah just saw you merged it back... mvn build works, just IntelliJ shows it red, but has no effect to any build...

**Comment by cbeams** [comment]
Closing as wontfix, superseded by #66.
