### ISSUE TITLE
Null Pointer when trying to open a dispute

### ISSUE THREAD

**Issue by b3dk7** [bisq-network/bisq#441]
1. I press the red "open dispute" button"
2. I get  a null pointer exception pop-up
3. the "open dispute" button grays out
4. I don’t get the opportunity to contact the arbitrator - I am expecting a text box of some sort

basically the only issue is that the counter party forgot to click on "I sent the funds". I already received my altcoins from him or her
## Log File

May-07 08:36:13.827 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-07 08:36:13.828 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= null 
May-07 08:38:36.625 [JavaFX Application Thread] WARN  i.b.p.p.k.KeepAliveManager: Connection with id b501694b-3f94-445d-bdf9-95b0c2e632d1 has not completed and is still in our map. We will try to ping that peer at the next schedule. 
May-07 08:41:16.193 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-07 08:41:16.193 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= null

**Comment by ManfredKarrer** [comment]
Can you send me by email (u find it ont the webpage) your trade ID and your onion address (settings/network)? I have a dispute open where one party is not reacting that might be you and caused by a bug in the dispute chat system. 
Seems that bug is related to another where the arbitrator data was not available in the P2P network.

**Comment by b3dk7** [comment]
The counterparty finally confirmed that they sent the altcoin, so the trade went through in the end.
