### ISSUE TITLE
Show current tx fee rate on main screen

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#4412]
### Description

It would be very useful for the current fee estimation to be shown on the main screen - at the moment the only way to see it is to watch the Bisq log file for a message like this:

    INFO  b.c.p.f.FeeService: BTC tx fee: txFeePerByte=11 

If `txFeePerByte=11` was shown in the main screen it would be much easier to determine if it is a good time to make a transaction.
It is more useful than the `0.00 BTC Reserved` and `0.00 BTC Locked` currently shown because they can also be found on the Funds screen.

#### Version

all Bisq, up to currently 1.3.7

### Expected behaviour

Show the tx fee on the main screen, to the right of Available balance, replacing Reserved/Locked balances.

**Comment by chimp1984** [comment]
The fee is shown in the settings if one has selected to use the fee estimation. but I agree its hard to find and it would be nice to see it more promonent. Maybe @pedromvpg could make a suggestion how we can add it to the UI? We should avoid overloading the UI with information as well, so its a hard balance we the UI is already very information heavy.

**Comment by ghost** [comment]
:+1: 
Doesn't necessarily have to be on the main screen it would be great if it was shown anywhere.. even Settings/Network Info screen would be good.  But I don't see it anywhere, hence the current need to tail the logs.  As a trader looking to make or take an offer, I want to know what Bisq is thinking regards the current mempool state (it can be 5 minutes behind https://mempool.space), and that only seems to be in the logs at the moment.

**Comment by chimp1984** [comment]
Its here: withdrawal tx fee
<img width="343" alt="Screen Shot 2020-08-27 at 21 32 55" src="https://user-images.githubusercontent.com/54558767/91514656-e7406f00-e8ac-11ea-9f61-bce018a0b6f8.png">

**Comment by chimp1984** [comment]
But I agree its nto very visible... Feel free to make a UI suggestion where you think it fits in best.

**Comment by ghost** [comment]
That's the withdrawal fee.  I'm referring to the fee used for making or taking an offer, which varies from 10 to whatever mempool.space currently reports.

**Comment by chimp1984** [comment]
It is the same if user has not set it to custom. E.g. we use the fee from estimation service for recommended withdrawal fee and for trade txs. But as said I agree its hard to see and would prefer to have it explicit displayed.

**Comment by cd2357** [comment]
Good idea, how about in the Bitcoin connection info in the bottom left?

<img width="655" alt="Screenshot 2020-10-20 at 11 27 57" src="https://user-images.githubusercontent.com/15956136/96568265-0addcf80-12c8-11eb-808b-c8b845f72869.png">

Not sure why it was closed, reopening as it looks like a simple, doable (and very useful) improvement.
