### ISSUE TITLE
Tooltip for unsigned accounts needs to provide more information

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/bisq#4416]
### Description

Users have been reaching out too many time asking about the lifts. All information is documented on the wiki but users don't know that when using the client. We need to provide more information on the tooltips.

#### Version

1.3.7

### Screenshots

<img width="1505" alt="Screen Shot 2020-08-18 at 9 59 48 PM" src="https://user-images.githubusercontent.com/807505/90583905-4b717d80-e19f-11ea-8eab-621e895999bd.png">

<img width="1886" alt="Screen Shot 2020-08-18 at 10 07 46 PM" src="https://user-images.githubusercontent.com/807505/90583893-47456000-e19f-11ea-9985-8785182d0ede.png">

<img width="1860" alt="Screen Shot 2020-08-18 at 10 10 46 PM" src="https://user-images.githubusercontent.com/807505/90584084-c175e480-e19f-11ea-86ea-2e12fbf40f5f.png">

**Comment by wiz** [comment]
I predict another joint collaboration between pedro and wiz coming soon

**Comment by pedromvpg** [comment]
Let's do it!

Also the user should be told how many days are left after the first signing.

![image](https://user-images.githubusercontent.com/807505/90595607-399dd380-e1bb-11ea-93be-2523464aca7f.png)

**Comment by ripcurlx** [comment]
Although we removed limits wherever possible I think the current tooltip can still be improved by the design suggestions by @pedromvpg .

**Comment by pedromvpg** [comment]
Anything I can do on my side to get this implemented?

**Comment by Conza88** [comment]
Also think this is great, and needed. Similar as above, removing limits better. But clearer indications helps immensely.

**Comment by ripcurlx** [comment]
> Anything I can do on my side to get this implemented?

I just labeled it as a `good first issue` to get it more visible for new developers. I'll hopefully will have more time at hand soon for development myself.

**Comment by ghost** [comment]
@pedromvpg Where I can retrieve icons visible on tooltip desings?

**Comment by ripcurlx** [comment]
> @pedromvpg Where I can retrieve icons visible on tooltip desings?

For using scalable icons please have a look at the helper methods in Formbuilder L2177 and below. Also to see all available icons you can run MaterialDesignIconDemoLauncher or AwesomeFontDemoLauncher in desktop/test/java/bisq.desktop
