### ISSUE TITLE
can't build on FreeBSD Unix

### ISSUE THREAD

**Issue by dchmelik** [bisq-network/bisq#4419]
### Description

When I try to build on FreeBSD Unix 13-CURRENT, your build system can't find things: [bisq_build_err.txt](https://gist.github.com/dchmelik/872dfa64fe31ef80225d615da7aaefb6) (gist.)

#### Version

1.3.7

### Steps to reproduce

./gradlew build

### Expected behaviour

Build.

### Actual behaviour

Build-system/gradlew can't find things.

#### Device or machine

FreeBSD Unix 13-CURRENT AMD Ryzen x64_64 workstation.

**Comment by wiz** [comment]
Yeah, I know. Unfortunately, javafx no longer supports FreeBSD. It's possible to run Bisq headless on FreeBSD using the old javafx jar from jdk 8 pkg, but if you try running the GUI it crashes. We can probably do some kind of headless GRPC API for FreeBSD when the GRPC API is working, but for now I don't think we can fix this.

**Comment by dchmelik** [comment]
I'm unfamiliar with all that, but hope to see Bisq available on all classic *BSD Unix (Net, Free, Open) and maybe ones oriented to average users (like boot to KDE or GNOME) and any main Open Solaris/Indiana/IllumOS Unix.  As there isn't an actual solution for now (rather than adding design in the future) you could close this... I'll probably try in the future but would normally search for all past (including closed) bugs for my current operating system...

**Comment by wiz** [comment]
Yeah, I want to get Bisq working on FreeBSD someday, but so far only headless works. For example mempool.space/bisq is Powered by FreeBSD.

**Comment by dchmelik** [comment]
Does that mean it could work command-line first?  I prefer command-line for programming, but might hate to use it for something with such a complicated user interface, but would be better than nothing...

**Comment by wiz** [comment]
Yes, the Bisq CLI is still under development, but when it is working it will likely work on FreeBSD using my hack method

**Comment by skrech** [comment]
Hello,

I see that on  2020-10-28 17 a new port was added into FreeBSD -> openjfx14.
Unfortunately, bisq seems to be using JavaFX 15, is there some config that can be tweaked so I can try building it with this relatively new version?

I have installed `java/openjdk11` and trying to build with the following:
`JAVA_HOME=/usr/local/openjdk11 ./gradlew build `

And the error is:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':desktop:shadowJar'.
> Could not resolve all files for configuration ':desktop:runtimeClasspath'.
   > Could not find javafx-fxml-15-freebsd.jar (org.openjfx:javafx-fxml:15).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/openjfx/javafx-fxml/15/javafx-fxml-15-freebsd.jar
   > Could not find javafx-controls-15-freebsd.jar (org.openjfx:javafx-controls:15).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/openjfx/javafx-controls/15/javafx-controls-15-freebsd.jar
   > Could not find javafx-swing-15-freebsd.jar (org.openjfx:javafx-swing:15).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/openjfx/javafx-swing/15/javafx-swing-15-freebsd.jar
   > Could not find javafx-graphics-15-freebsd.jar (org.openjfx:javafx-graphics:15).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/openjfx/javafx-graphics/15/javafx-graphics-15-freebsd.jar
   > Could not find javafx-base-15-freebsd.jar (org.openjfx:javafx-base:15).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/openjfx/javafx-base/15/javafx-base-15-freebsd.jar
```

**Comment by wiz** [comment]
Interesting, if you get it working please submit a PR :)

**Comment by aperechnev** [comment]
Are there any news about running Bisq in FreeBSD?
