### ISSUE TITLE
Recommended security deposit display

### ISSUE THREAD

**Issue by MwithM** [bisq-network/bisq#4426]
### Description

Not exactly a bug, but UX improvement. 
I don't know how to see the security deposit suggestion, my security deposit is always the same. Removing the security deposit and going back and forth when creating an order doesn't make the suggested security deposit appear.

#### Version

2.3.7

### Steps to reproduce

Make an offer when you already used your own security deposit for another offer in this market and it will use this security deposit, without even being able to know what the suggestion is at this time.

### Expected behaviour

I suggest to display suggested security deposit when clicking the "i" info next to "set both traders' security deposit" field. Any other way to be able to consult suggested security deposit easily is welcome.

### Actual behaviour

I'm not able to find the suggested security deposit. If there's a way and there's no need to make further changes, I'll document how on the wiki.

### Screenshots

![issue recommended deposit](https://user-images.githubusercontent.com/50149324/91031028-4b8ad680-e600-11ea-88ce-a1e22a3e5737.jpg)

### Additional info

Related PR: https://github.com/bisq-network/bisq/pull/4347

**Comment by luisantoniocrag** [comment]
Currently how can I know the secure deposit suggested?
I have seen other users ask it too.

**Comment by ghost** [comment]
There are three variables that go into the calculation for the number displayed in the security deposit field:

* maximum security deposit (system defined, currently 50%)
* volatility based security deposit calculation
* minimum security deposit (user definable with a hard lower bound of 15%)

If the `volatility based calculation` is lower than the minimum then the `minumum security deposit` is shown which is a user defined parameter.  At the moment, with the current volatile price swing from USD 12500 to 10400 the calculated value is around 33%.  So if you enter 15% for the user defined minimum then close and re-open the order entry screen you should see 33%.

In going through the above I noticed a bug.  By moving the cursor through the security deposit field on the order entry screen, you're setting the value for `minimum security deposit` that will be used in future.  So in this example, setting it to 33%.  When volatility goes down, the 33% still exists in the user preference for `minimum security deposit` so in essence **you'll never see lowered estimates, only higher ones**.  I think this field should not be used to persist the user preference `minimum security deposit`.  Instead I think that value should be placed on the settings screen under `General preferences`.

**Comment by MwithM** [comment]
So that bug is what makes it impossible to me to find what the recommended security deposit is? I can find it for EUR, but not for XMR. I must have used a low security deposit for EUR while a higher one for XMR in the past, right?

What about always displaying at order entry screen the recommended security deposit and leave the decision to make it higher or lower to users for every offer (opt out)? I'm quite sure this way the recommended security deposit will be used a lot more, and there will be no doubt what the recommended security deposit is.

When taking an offer, an alert should be displayed when security deposit is too low. Specially when you are taking an offer to sell BTC, because there's higher risk of BTC buyer performing future trading.

![imagen](https://user-images.githubusercontent.com/50149324/93856647-9ceabc00-fcb9-11ea-830d-a4078e40a092.png)

At this time, I can only get to see security recommended deposit for EUR/BTC. Maybe alts volatility is so low that the recommended security deposit is under 15%?

**Comment by ghost** [comment]
> At this time, I can only get to see security recommended deposit for EUR/BTC. Maybe alts volatility is so low that the recommended security deposit is under 15%?

Yes -> The volatility based security deposit comes to 13.7% for XMR, therefore it chooses the `minimum security deposit` which can only be as low as 15%.

> What about always displaying at order entry screen the recommended security deposit and leave the decision to make it higher or lower to users for every offer (opt out)? I'm quite sure this way the recommended security deposit will be used a lot more, and there will be no doubt what the recommended security deposit is.

Well this is the way it works currently - the recommended security deposit is shown, and the user can go and change it within the 15% - 50% boundaries.

I like your earlier idea of displaying all the information in the popup window when hovering over the (i) icon.  And the idea of an alert if the user chooses a deposit which is lower than what was calculated.

What about moving the edit of min security deposit value from order entry to Settings/General preferences?

**Comment by MwithM** [comment]
It could be displayed as it is now (without the bug) and the other two new possibilites, the (i) icon popup and the alert when user choses low deposit.

About changing the min security deposit value, I think it's fine, but personally I will stick to suggested recommendation unless I think that the offer will be not taken for long.

**Comment by ghost** [comment]
> It could be displayed as it is now (without the bug)

I don't understand, there is no **display** bug.  I think either I did not explain the bug very clearly, or we are misunderstanding each other.  :confused: 

It would be nice if @sqrrm / @ripcurlx could step in and say what they think needs doing.

**Comment by ripcurlx** [comment]
> > It could be displayed as it is now (without the bug)
> 
> I don't understand, there is no **display** bug. I think either I did not explain the bug very clearly, or we are misunderstanding each other. 😕
> 
> It would be nice if @sqrrm / @ripcurlx could step in and say what they think needs doing.

@jmacxx If it is as you described (an automatically suggested deposit percentage is persisted in preferences), than this is not the desired behavior. Still if we would persist the value if it is changed by the user she won't see any other suggestions afterwards. So having this suggested deposit based on volatility, I would remove the stored preference completely. That way it would always show the suggested value. A sophisticated trade will adapt it anyways and noobs will just use the suggested default which is good.

**Comment by MwithM** [comment]
Removing the stored preference looks like the most simple and effective solution. If every time user creates an offer the suggested security is displayed, there's no way to miss that information. Then it's up to the traders to follow that recommendation or not.

The warning when taking an offer should be discussed somewhere else, maybe is not that important.
