### ISSUE TITLE
Pop up windows open minimized on Fedora under Qubes OS

### ISSUE THREAD

**Issue by crowphale** [bisq-network/bisq#4449]
### Description

This is on Fedora 31, running under Qubes OS. When Bisq opens a pop-up window, for instance when I open the chat in Portfolio -> Open Trades, it opens minimized, or rather minimal size of window. You can't see anything. You need to drag the corner of this window to make it usable.

#### Version
1.3.7 (installed from .rpm)

### Steps to reproduce

Open Portfolio -> Open Trades
Click on chat (face icon on the right)
Minimal window opens, you can't see anything and must expand the window by dragging a corner.

### Expected behaviour

Open a reasonable sized window so that the user can interact with it, without manually expanding the window.

### Actual behaviour

Minimal sized window opens.

### Screenshots
![image](https://user-images.githubusercontent.com/70079617/91640394-499f8980-e9eb-11ea-836c-ecefa62d71f0.png)

#### Device or machine
Lenovo X230, Qubes OS, Fedora 31

#### Additional info

Happy to provide more info if needed.

**Comment by cd2357** [comment]
Definitely related to / fixed by #4242
