### ISSUE TITLE
Developer can't be verified in Big Sur

### ISSUE THREAD

**Issue by invious** [bisq-network/bisq#4465]
### Description

App doesn't open in Big Sur

### Steps to reproduce

Opening the app

### Expected behaviour

App should open

### Actual behaviour

App doesn't open

### Screenshots

![image](https://user-images.githubusercontent.com/1996089/92005565-a19efe80-ed11-11ea-8b6e-d65c673a292b.png)

#### Device or machine

Mac Big Sur 11.0 Beta (20A4300b)

**Comment by chimp1984** [comment]
Apple does not miss an opportunity to screw up user-experience and developers.

Can you still open it with right click mouse -> Open?

**Comment by chimp1984** [comment]
Or are there setting in the security preferences which can be changed to a lower level as it has been in the current versions?

**Comment by wiz** [comment]
You need to open settings -> security -> and click "open anyway"

**Comment by ripcurlx** [comment]
This will be fixed as soon as #4242 gets merged.

**Comment by cd2357** [comment]
This should be fixed with the latest version (v1.6.4) which notarization for the macOS binaries.

Please try it out and let us know if this is still an issue for you.
