### ISSUE TITLE
Completed trades stay in 'Open trades' list

### ISSUE THREAD

**Issue by AndreKoster** [bisq-network/bisq#447]
My completed trades are not taken off my list of open trades. I finalize the trade by redeeming my BTC 0.01 security deposit, but instead of moving to the history tab, the trade stays on the open trade tab. Attempting to redeem the deposit again gives a error "amount too low" (of course). After a week has passed, I'm offered to open a dispute.

(While I was writing this, all but two trades have moved to the history list! The two in question are open for arbitration. I have opened a dispute for one of them.)

**Comment by ManfredKarrer** [comment]
Can u email me the trade ID so i can see which dispute it is?
Did you try to restart the app? If so and/or if that does not solve the issue, could you send me by email your data directory (at account/backup u can open it)? You can/should remove the wallet file (and backups of the wallet), for debugging it should be ok for me to reproduce it without your real wallet.

**Comment by AndreKoster** [comment]
The dispute I had opened just resolved.

I restarted the app many times the past week (usually once a day). I will send you my data dir and the trade ID.

**Comment by ManfredKarrer** [comment]
@AndreKoster Do u still have that issue?

**Comment by ManfredKarrer** [comment]
Assuming the issues is resolved. Otherwise please re-open.
