### ISSUE TITLE
Trading with Revolut between v1.3.7 and v1.3.8 clients will fail

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#4476]
### Description

As we are requiring now a username to trade Revolut based on feedback from Mediators it won't be possible to trade Revolut between v1.3.7 and v1.3.8 clients. This is caused by a breach of contract.

#### Version

v1.3.8

### Steps to reproduce
Use old client (v1.3.7) with Revolut account using phone number and new client (v1.3.8) using a username.

### Screenshots
![Bildschirmfoto 2020-09-04 um 11 09 12](https://user-images.githubusercontent.com/170962/92223318-94fce080-eea0-11ea-8d57-ed93cf8d8f35.png)

This might cause confusion during the transition phase.

We could either force everyone to update to v1.3.8 or mention it in the update message so people are aware of this problem.
The problem with just mentioning is, that it will affect clients updating to v1.3.8 and clients who stay on v1.3.8 causing this error when trying to take an incompatible offer.

If we don't want to do a force update maybe we should filter out at least v1.3.7 Revolut offers for v1.3.8 clients.

**Comment by ripcurlx** [comment]
@chimp1984 What do you think? ☝️

**Comment by chimp1984** [comment]
I will have a look. Is probably because we set username to old accountID fields so for old and new there are different values, so the contract does not match.
