### ISSUE TITLE
Reconsider adding Venmo

### ISSUE THREAD

**Issue by crowphale** [bisq-network/bisq#4478]
Already discussed in https://github.com/bisq-network/bisq/issues/1347.

I believe the conclusion was "no", because a/ high probability of charge backs, and b/ relatively low limits. However, the issue is over 2 years old, and I wonder if Venmo changed:
- the limits seem higher (5K; see https://help.venmo.com/hc/en-us/articles/221010968-Payment-Limits)
- they say you can't cancel payment, only request a refund from the other person (you can only cancel payments to non-existing/non-active users; see https://help.venmo.com/hc/en-us/articles/235171088-Cancel-Payment)

Do you think it's worth re-opening the issue?

**Comment by wiz** [comment]
AFAIK venmo still has very high chargeback risk, and venmo scams are still quite common. Of course they say that on their website, but in practice you can just say you got hacked and they will reverse the payments even months later.

**Comment by crowphale** [comment]
Hmm, that's too bad. I think you are right: "But remember, payments made from stolen payment methods could be removed from your Venmo account even after they’ve been made available to you." (from https://help.venmo.com/hc/en-us/articles/360048404533-Common-Scams-on-Venmo)

**Comment by crowphale** [comment]
I'm surprised (and glad) that Zelle or Revolut don't do the same.
