### ISSUE TITLE
Cant Create new offer to sell/buy Bitcoin

### ISSUE THREAD

**Issue by GeneralNazrin01** [bisq-network/bisq#448]
Hello sir....i want to try to sell the bitcoin with this exchange .....but the Bitsquare crash (the program close ) to desktop after i click the create new offer  ....

Version running with v0.4.6
I running in Window 7 ,

**Comment by ManfredKarrer** [comment]
Hm, strange. Can you send me the log files? You can find thatm under Acount/backup -> open data directory -> there are the log files.

**Comment by GeneralNazrin01** [comment]
sorry for late reply...here the logs

http://pastebin.com/7kEPWdMK

**Comment by ManfredKarrer** [comment]
@GeneralNazrin01 Could u send me the log files which are inside the data directory? u can open it at account/backup/open app data directory button.
On the webpage u can find my email address.

**Comment by ManfredKarrer** [comment]
If u still have issues plese re-open.
