### ISSUE TITLE
Account age popup shows wrong durations

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#4482]
Account age signing requires only 1 month but the popup at account creation shows 2 months. Maybe there are more relicts from the time when 2 months was considered.
<img width="598" alt="Screen Shot 2020-09-04 at 20 37 04" src="https://user-images.githubusercontent.com/54558767/92294120-948b3680-eeee-11ea-8aa6-149717ad1a22.png">

**Comment by ghost** [comment]
This seems to match what is described in the wiki.  https://bisq.wiki/Account_limits

The code matches the description too.

I don't see a problem.

**Comment by chimp1984** [comment]
@sqrrm Can you chime in? I thought the code has been changed so that after 1 months there is the full trade amount?

**Comment by sqrrm** [comment]
It's quite confusing actually. I think I'll take another look at this and clean up the signing code.

Currently the limit is 0.01 BTC for the first month, 0.125 BTC (0.5 max amount for risky account type) for the second month and then 0.25 BTC (max amount). Users can sign others 1 month after signing. Sellers have some rules that I think are not actually used. There were too many changes in the months after signing release that it's not very clear.

I think it's best to make it:
- sellers can sell full amount at all times
- buyers limit first 30 days after signing is 0.01 BTC
- buyers get full limit and can sign other after 30 days

Very easy to explain, can remove many cases in code and should be mostly backwards compatible. (I think there will be a conflict for some old users taking offers from accounts signed 30-60 days back that make larger offers).
