### ISSUE TITLE
Synchronization between computers

### ISSUE THREAD

**Issue by ulrichard** [bisq-network/bisq#449]
Bitsquare offers wallet backup and restore. As well as manual full backup.
To have a bit more interoperability between my computers, I'm synchronizing some of the files in the directory ~/.local/share/Bitsquare/mainnet/db/ using git.
That seems to work for my open offers (didn't thoroughly test, but at least, they appear on both machines).
But it didn't work for an open dispute. There I saw only old messages and sending a message didn't get through.
Are there any guidelines on what should be synchronized?

**Comment by ManfredKarrer** [comment]
Interesting idea to use git for syncing.
I assume you did not let run both instances of Bitsquare at the same time. Tor would get confused doing that (I don't know how Tor handles 2 same onion addresses but I assume one would be ignored).
I have no explaination why the dispute msg was not handled correctly (if you had both running, that would explain it, but I assume that was not the case).

When you are not online the dispute (or trade) messages are stored in the P2P network as encrypted "mailbox" messages. When u go online again u decrypt them and remove them from the P2P network.

There are no guidelines, but all relevant data is in the data dir and there are 3 subsections: bitcoin, db, tor. 

In future a headless app which can run on your private server and get accessed by light UI clients (also mobile) would be a solution, also to mitigate the issues that the offerer need to be online. But that is not planned soon as it comes with considerable effort.

**Comment by ulrichard** [comment]
The trades also don't update the state. One that was closed still displays as open on the notebook.
Yes, I'm pretty sure I never ran them both simultaneously. 
I didn't synchronize the tor nor the bitcoin subfolders, only db and keys.
My assumption was that the bitcoin folder stores just plumbing information that can be easily fetched independently, and that the tor subfolder stores stoff how to connect to the network.
Could that be the reason, that the recipient is the tor id?

**Comment by ManfredKarrer** [comment]
Hm.... when you have the exact same db content it should display the same. 

Tor and the bitcoin subfolder dont need to get synced.
The btc folder holds the wallet and tor the priv key and address for the hidden service. all other data are created at startup.
In some rare cases deleting the Bitsquare.spvchain file might help, but that should not be related at all to dispute cases.

**Comment by ulrichard** [comment]
Right after syncing it does display the same, but the second computer does not update the state on its own.

**Comment by ulrichard** [comment]
Deleting Bitsquare.spvchain didn't change anything. 

With a bit of further testing, I discovered a possibly more serious problem:
- Create an offer on computer A
- Synchronize the files to computer B
- Cancel the offer on computer B, thus getting the security deposit back.
- On Computer A, the offer is still listed as active, and shows up in the order book.
- I don't know what happens when somebody tries to accept the offer. 
  If somebody wants to try, it's offer id 892a9924 the one for 8 LTC @ 110

The same effect could maybe be achieved by just rolling back the files locally.

**Comment by ManfredKarrer** [comment]
The security deposit is always on the local wallet it is just reserved to not get spent unintendedly and render a take offer attempt invalid if the funds are not in the wallet anymore.

Do u run both at the same time? That would confuse Tor, not sure how it reacts as one onion address would be published 2 times. I assume one will be not available in the network.

The offer on Computer A is still there as u did not sync again (i assume). It re-publishes the offer and as the sec. deposit is also there all is correct. Canceling an offer sends a remove data msg. Re-publishing again an add data msg.

**Comment by ulrichard** [comment]
I moved the security deposit on computer B to my external wallet.
But bitsquare on computer A still displays the offer as valid. If it is checked when somebody tries to take the offer as you say, at least no fraud can happen.
But it would be even better if that invalid offer could not be published again.
No I don't run them both at the same time.
How exactly are the onion addresses handled. I didn't sync the tor sub-directory.

**Comment by ManfredKarrer** [comment]
Ah ok, if the sec. deposit is gone then the take offer attempt should fail as the deposit tx cannot be created. I have not tested that case, so not 100% sure if it behaves like I assume but the worst what can happen is a double spended deposit tx will be published which will never make it into the blockchain and so will cause a dispute. 
Those special edge cases are not handled yet as too much other normal use cases still need to be improved... Though an interesting find and good to know!

The onion address is created at first start up and does nto change over time. Its just a priv key + onion address inside the tor dir (hiddenservice).

**Comment by haiqu** [comment]
I use three different computers for trading crypto. When I move from one to the other the wallet directories are backed up to USB memory - actually I keep two copies on USB - and restored on the next machine. They could never be used at the same time, but if I ever mess up and lose a backup my other machines still have the data and just need to download the blockchain from where they left off.

It takes a bit of attention to keep it current but it works for me. Of course the industry standard for this would be Google Cloud or something equally unsafe. I trust Mozilla to hold my bookmarks in sync, that's about as far as I go.

**Comment by steve-vincent** [comment]
Here's an odd case.
I copied the "bitcoin" & "db' folders to another BitSquare folder.

Everything seemed to work, except an open transaction where my role="BTC seller as offerer" shows as "BTC buyer as taker" on the copied instance. I even have a button to click "payment started".
