### ISSUE TITLE
Post steps on how to generate .deb

### ISSUE THREAD

**Issue by dmp1ce** [bisq-network/bisq#451]
I was looking for documentation on how to build the .deb to maybe help out with the Arch PKGBUILD but I didn't see it. How is the .deb built?

**Comment by ManfredKarrer** [comment]
Here is the deb build file:
https://github.com/bitsquare/bitsquare/blob/master/package/linux/create_64bit_app.sh
The jar file is built by the mac build file.

We had earlier arch support but as the build process has the dependency to our bitcoinj fork and you need to follow some extra steps regarding security settings (https://github.com/bitsquare/bitsquare/blob/master/doc/build.md#prerequisites) an arch build is probably a bit complicate.

See https://github.com/bitsquare/bitsquare/blob/master/doc/build.md for all details.

**Comment by dmp1ce** [comment]
Thanks for pointing out the shell script. I'll keep working on this for Arch.
