### ISSUE TITLE
Add option to specify which type of release to upgrade to (i.e. release/pre-release)

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#4532]
We recently started providing pre-release versions that are available a few days prior to an official release in the hopes of preventing unnecessary hotfixes after a release by allowing those that wish to try it out and provide feedback.

However, these pre-release versions are not notified/downloaded within the application and must be manually downloaded from Github. This means the user must rely on being notified of the pre-release through Keybase or by being subscribed to the repository. In addition, they must (hopefully) manually verify the downloaded files.

If we were to add the option to allow the user to specify which type of releases they want to upgrade to, that would allow them to be notified within the application and make the upgrade process much easier as it would handle the download and verification steps automatically. The biggest benefit may be that it potentially make more users try out the pre-release versions and provide early feedback.

**Comment by chimp1984** [comment]
Good idea. I think to add a checkbox to the settings to enable "notify on pre-releases" which is used once a update notification is received to either ignore the popup or to show it (as well as related UI updates like the update text in the footer). 

Would you mind to change the term capability to "option" or the like? I got first the impression you refer to the Capabilities (a feature we use to manage migration/compatibility of new features).

**Comment by devinbileck** [comment]
Yes good point. I updated the wording.

**Comment by ghost** [comment]
Still relevant.
