### ISSUE TITLE
Linux: /opt/Bisq/Bisq fails when called as root

### ISSUE THREAD

**Issue by cd2357** [bisq-network/bisq#4535]
### Description

Bisq fails to start on an Xfce-based recent Debian.

#### Version

1.3.9

### Steps to reproduce

Download the deb package for Bisq v1.3.9

Install it on Debian 10.5 with Xfce

Attempt to start it via `/opt/Bisq/Bisq`

### Expected behaviour

Bisq starts successfuly

### Actual behaviour

Bisq fails to start

### Screenshots

```
root@debian:/# /opt/Bisq/Bisq
Sep-17 22:30:58.599 [main] INFO  bisq.core.setup.CoreSetup: 


Log files under: /root/.local/share/Bisq/bisq 
Sep-17 22:30:58.608 [main] INFO  bisq.common.util.Utilities: System info: os.name=Linux; os.version=4.19.0-10-amd64; os.arch=amd64; sun.arch.data.model=64; JRE=10.0.2+13 (Oracle Corporation); JVM=10.0.2+13 (Java HotSpot(TM) 64-Bit Server VM) 
Sep-17 22:30:58.610 [main] INFO  b.c.s.CoreNetworkCapabilities: Set Capability.RECEIVE_BSQ_BLOCK 
Sep-17 22:30:58.713 [main] INFO  bisq.common.app.Version: Version{VERSION=1.3.9, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=2, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10} 
Sep-17 22:30:58.714 [main] INFO  bisq.core.setup.CoreSetup: Path to Bisq jar file: /opt/Bisq/app/desktop-1.3.9-all.jar 
Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:173)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:171)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at javafx.graphics/com.sun.glass.ui.Application.run(Application.java:146)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:257)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:255)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:154)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:731)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:751)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.base/java.lang.Thread.run(Thread.java:844)
Bisq Failed to launch JVM
```

#### Device or machine

Debian 10.5 with Xfce

(Would probably also happen with KDE or other non-GNOME setups)

#### Additional info

The issue seems to be that Bisq / JavaFX expect a GTK environment

> Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:173)

However this was an Xfce environment.

#### Suggested solution

Bisq should inform the user why its failing to start with a more informative message, like:

> "Bisq cannot start because it found an incompatible UI environment on this Linux system. Please install the GNOME desktop environment and try again."

**Comment by cd2357** [comment]
Update:

In addition to the Xfce Debian 10.5, I also tested this on a (VirtualBox VM) Debian 10.5 with GNOME as well, for both Bisq v1.3.7 and v1.3.9 and in **all 4 cases** (both Bisq versions, in both VirtualBox Debian versions) :

* trying to start Bisq via `/opt/Bisq/Bisq` fails with the stacktrace above
* Bisq starts fine when started from the menu shortcut

This was not an issue with Debian 10.5 running in Qubes (`/opt/Bisq/Bisq` ran fine).

Also, running Bisq v1.3.7 in a (VirtualBox) Ubuntu 20.04 worked fine.

So its probably a "VirtualBox and Debian as guest OS"-specific issue.

Workaround: simply start Bisq via the the OS menu shortcut.

Closing this, as its not a bug per se, more of an environment setup issue.

@ripcurlx : Perhaps it makes sense to add to the Linux section in the release notes a paragraph like:

> "If running a virtualized Debian setup with VIrtualBox, starting Bisq from the command line using /opt/Bisq/Bisq will likely not work. However, Bisq can be successfuly started by using the Bisq shortcut in the Debian application menu. See #4535 for details."

**Comment by wiz** [comment]
can you "export DISPLAY=:0" then try it again

**Comment by cd2357** [comment]
@wiz Thanks, didn't work, but it gave me some ideas to try out and I found out the issue:

Problem is, I was starting Bisq as root.

```
root@debian:/# /opt/Bisq/Bisq
```

If I run it as a normal user, it works fine.

Its not even a problem with root, but its with calling `su` from a normal user session. If I login to GNOME/Xfce as root, calling `/opt/Bisq/Bisq` works. However, if I login as a normal user, then try `su` or `su -` in a terminal, then `/opt/Bisq/Bisq` fails.

@ripcurlx : In this case, the release notes for Linux could say:

> "Running `/opt/Bisq/Bisq` as root, after using `su` or `su -` from a normal user session, may fail. Instead, call `/opt/Bisq/Bisq` as the normal user directly, or use the Bisq shortcut in the OS application menu. See #4535 for details."

**Comment by wiz** [comment]
Yeah... this is just how Xorg works, and isn't related to Bisq at all. You can grant the root user on your system access to the X window system console, but that's out of the scope for Bisq documentation.
