### ISSUE TITLE
bisq-statsnode entrypoint logs all Bitcoin blocks serialized as hex in bisq.log

### ISSUE THREAD

**Issue by wiz** [bisq-network/bisq#4537]
As the Markets Operator I might be the only person running the bisq-statsnode entrypoint, but I noticed in v1.3.9 it is logging an insane amount of data, just check the timestamps on the below log files, it is logging over 200MB of data per minute:

```
% ls -la
total 130285
drwxr-xr-x  3 bisq  bisq        15 Sep 18 00:00 .
drwx--x--x  5 bisq  bisq        14 Sep 17 23:50 ..
-rw-r--r--  1 bisq  bisq       267 Sep 18 00:00 bisq.log
-rw-r--r--  1 bisq  bisq       114 Sep 17 23:52 bisq.properties
-rw-r--r--  1 bisq  bisq  15743372 Sep 18 00:00 bisq_1.log
-rw-r--r--  1 bisq  bisq  16441604 Sep 18 00:00 bisq_10.log
-rw-r--r--  1 bisq  bisq  13904782 Sep 18 00:00 bisq_2.log
-rw-r--r--  1 bisq  bisq  13791199 Sep 18 00:00 bisq_3.log
-rw-r--r--  1 bisq  bisq  15889477 Sep 18 00:00 bisq_4.log
-rw-r--r--  1 bisq  bisq  14904522 Sep 18 00:00 bisq_5.log
-rw-r--r--  1 bisq  bisq  16501712 Sep 18 00:00 bisq_6.log
-rw-r--r--  1 bisq  bisq  16841696 Sep 18 00:00 bisq_7.log
-rw-r--r--  1 bisq  bisq  16175507 Sep 18 00:00 bisq_8.log
-rw-r--r--  1 bisq  bisq  15936970 Sep 18 00:00 bisq_9.log
drwxr-xr-x  6 bisq  bisq         6 Sep 17 23:50 btc_mainnet
```

**Comment by cd2357** [comment]
Can you post a 20-30 line snippet from one of the logs?

Could help pin-point what the chatty classes are.

**Comment by wiz** [comment]
I think it's related to the initial DAO sync. If you just run `./bisq-statsnode` entrypoint I would guess it reproduces. Logs look like this screenshot, all hex data, I think they are serialized Bitcoin transactions or maybe even the raw blocks themselves
![Screen Shot 2020-09-18 at 20 44 20](https://user-images.githubusercontent.com/232186/93593889-d38db180-f9ef-11ea-9f9f-8b111fdbeffb.png)

**Comment by wiz** [comment]
I found the start point of the line, I guess it's all a single line?

<img width="2560" alt="Screen Shot 2020-09-18 at 20 49 53" src="https://user-images.githubusercontent.com/232186/93594292-88c06980-f9f0-11ea-9a22-7d96035e5bab.png">

**Comment by chimp1984** [comment]
Just add 
`<logger name="com.neemre.btcdcli4j" level="WARN"/>`
to logback.xml in the module src dir.

**Comment by wiz** [comment]
```<logger name="com.neemre.btcdcli4j" level="WARN"/>```

**Comment by wiz** [comment]
thank you sir :heart:

**Comment by chimp1984** [comment]
the lib by default logs way too much. its set in all modules just in stats it was missing
