### ISSUE TITLE
Font is too small on 2K or 4K laptop displays on Linux

### ISSUE THREAD

**Issue by bubersson** [bisq-network/bisq#4541]
### Description

On smaller laptops (13" or 15") that have 2K or 4K displays the font in the Bisq app is almost unreadably small. Ideally Bisq would take the zoom config from system (GNOME) settings, but it would also be useful to provide zoom/font-size option in Bisq settings. (I didn't find it there - but maybe that's because the font is too small :P)

Same report was posted here (not by me): https://bisq.community/t/fonts-too-tiny-for-4k-monitor-not-usable/8861 

#### Version
1.3.9
ElementaryOs (Linux 5.8)

**Comment by ghost** [comment]
Do either of these suggestions help?
https://github.com/bisq-network/bisq/issues/1425#issuecomment-459392275
https://github.com/bisq-network/bisq/issues/1425#issuecomment-448164197

**Comment by bubersson** [comment]
Unfortunately not. 
`org.gnome.desktop.interface scaling-factor scaling-factor` and `GDK_SCALE` are integers. 
On 2K 13" display: "1" is too small, "2" is way too big (it actually results in Bisq window not fitting on screen, I'm guessing because of min-width). 
Other applications seem to work well with: `org.gnome.desktop.interface scaling-factor text-scaling-factor` which is double, so e.g. setting 1.25 works well. It doesn't seem to be taken into account in Bisq. I think this is especially issue on small 2K monitors where the ideal scaling is somewhere between 1 and 2. 

For reference: IntelliJ provides scaling in their settings: https://intellij-support.jetbrains.com/hc/en-us/articles/360007994999-HiDPI-configuration

**Comment by ghost** [comment]
Try changing the VM options like this: `DEFAULT_JVM_OPTS="-Dglass.gtk.uiScale=1.25 -XX:MaxRAM=4g"`  in `bisq-desktop` startup script.  This worked on my Ubuntu 18.04.

ref:
https://wiki.archlinux.org/index.php/HiDPI#JavaFX
https://news.kynosarges.org/2018/01/26/javafx-dpi-scaling-in-java-9/

**Comment by wiz** [comment]
would you mind adding that to the wiki?

**Comment by bubersson** [comment]
Nice, applying that approach worked with small modification! Thank you!

`DEFAULT_JVM_OPTS` didn't work, but this command works to execute Bisq with the right zoom from the commandline:
```shell
JAVA_TOOL_OPTIONS="-Dglass.gtk.uiScale=1.4 -XX:MaxRAM=4g" /opt/Bisq/Bisq
```

### Short Tutorial
To make this work from the dock (clicking on icon) I had to create `/opt/Bisq/Bisq-runner.sh` with
```shell
#!/bin/bash
JAVA_TOOL_OPTIONS="-Dglass.gtk.uiScale=1.4 -XX:MaxRAM=4g" /opt/Bisq/Bisq
```
Make it executable `chmod +x /opt/Bisq/Bisq-runner.sh`.
And  then update `/opt/Bisq/Bisq.desktop` and/or `/usr/share/applications/Bisq.desktop` to 
```
...
Exec=/opt/Bisq/Bisq-runner.sh
```

(I had to create the runner, because the .desktop spec doesn't seem to allow variable setting: https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-1.0.html)

**Comment by m52go** [comment]
YUUGE. I've had to use my OS's magnifier to read numbers in Bisq sometimes. 

Added to the wiki [here](https://bisq.wiki/Running_on_HiDPI_screen).

**Comment by cd2357** [comment]
Closing the issue, as it looks like we have a documented, working solution.

**Comment by boozyy** [comment]
Font is too small even on a 70" TV which i use as a monitor. I don't care to make some workarounds. Why not fix it in the software? Other apps work just fine.

**Comment by bocekm** [comment]
A solution to the small font issue if you use [the Bisq flatpak](https://flathub.org/en/apps/network.bisq.Bisq): https://github.com/bisq-network/bisq2/issues/2197#issuecomment-3799803263.
