### ISSUE TITLE
Column sorting

### ISSUE THREAD

**Issue by ulrichard** [bisq-network/bisq#455]
The Date/Time column in Funds->Transactions is sorted alphanumerically. This might work with an ISO date format, but not with the Swiss one : "31.03.2016 00:11:33"

The currency column in Market->Spreads is sorted in a funny order.
My guess is that it is sorted on the un-translated values or 3 letter codes. That would explain why "Schweizer Franken" comes very early, and "Baht" very late in the alphabet.

There may be more, but those are the ones that were most obvious.

**Comment by ManfredKarrer** [comment]
The Date/Time column in Funds is alreadz fixed but not deployed.
The other is prob. sorted by currencz code instead of display name. Will fix that as well for the next release and check other sorting issues if there are...

**Comment by ManfredKarrer** [comment]
Fixed for the next release. Also checked other tables....
