### ISSUE TITLE
[Feature] Satoshis as unit

### ISSUE THREAD

**Issue by dimsav** [bisq-network/bisq#4556]
### Description

New users initially trade small amounts, first because they are forced by Bisq and second because they might want to experiment and learn how the platform works without risk.

It would be useful to have the option to show bitcoin amounts in satoshis because this makes it easier to understand the amounts. Also, since the bitcoin price raises over time, this feature becomes more and more relevant.

**Comment by cd2357** [comment]
It's already on the list ;) #4380

**Comment by dimsav** [comment]
Great!
