### ISSUE TITLE
Running under WSL, desktop app runs for a while then exits 'on its own'

### ISSUE THREAD

**Issue by coinzdude** [bisq-network/bisq#4565]
### Description

Running under WSL under Win 10, the desktop app runs well and responsive under vcxsrv but then "stops" on its own. Log attached.

#### Version
Windows 10, WSL with Ubuntu 20.04
Bisq built from github on 2020/09/26, OpenJDK 11

### Steps to reproduce

Run bisq-desktop, app runs fine, then wait.  App closes on its own, no particular errors are visible.  Logs attached 

### Expected behaviour

App should run until closed.

#### Device or machine
Windows 10, fast ring
Ubuntu 20.04 under WSL 2

#### Additional info
[bisq.log](https://github.com/bisq-network/bisq/files/5287259/bisq.log)

**Comment by cd2357** [comment]
>  Sep-26 15:32:47.483 [SIGTERM handler] INFO  bisq.core.app.BisqExecutable: Start graceful shutDown

Seems like Bisq received a `SIGTERM` signal, which is basically a command from the OS to stop the process.

**Comment by coinzdude** [comment]
Closed, and thanks.  I'll see if I can recreate it
