### ISSUE TITLE
User agreement text should be updated to reflect new Bisq price indices

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#4571]
bisq-network/projects#35 removed BitcoinAverage as a price oracle, but the User agreement text still mentions it:

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/301810/94553373-ba3efd80-0258-11eb-8af3-cab9f0193d39.png">

The text should be updated to reflect this change, and should perhaps link to the https://bisq.wiki/Bisq_Price_Indices page for further details.

**Comment by wiz** [comment]
Ah good catch yeah we missed that one.

**Comment by ripcurlx** [comment]
@wiz will you create the PR for this or @m52go ☝️ ? So we get it into 1.4.0 already.

**Comment by wiz** [comment]
@ripcurlx okay #4587
