### ISSUE TITLE
Big mining fees

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#4575]
Actually, the trading fees (mining fees especially are quite high). It makes trading of smaller amounts very problematic. (Like 4% on mining fee is quite a lot).

![image](https://user-images.githubusercontent.com/383295/94627262-4c78ed00-02bd-11eb-8652-d29a0898654b.png)

This must be pain for new users who has new account and low limits. And I am little bit afraid it may discourage them from using Bisq.

----

I understand that implementing SegWit will help. But also, is would be nice to have possibility to lower fees per byte (I don't mind longer waiting times).

**Comment by ghost** [comment]
Here it is even 8%, it is extremely unreasonable to trade at such high transaction cost.

![image](https://user-images.githubusercontent.com/383295/94659390-815c6280-0304-11eb-9ddf-d2dbda9b42df.png)

**Comment by cd2357** [comment]
@petrhejna unfortunately, there are other considerations at play that make this not a very straightforward choice.

The most reasonable workaround for this is to avoid trading small amounts when the [mempool](https://mempool.space) is full.

It is usually almost empty on weekends, so that's when you'll generally get the lowest fees.

**Comment by ghost** [comment]
Thank @cd2357 for clearing it out. 

But sadly :( even when mempool is quite empty (for few hours now) the estimation is `BTC tx fee: txFeePerByte=102` which is enormous. 

![image](https://user-images.githubusercontent.com/383295/94989644-a952fc80-0576-11eb-8ee0-252671c2a2db.png)

**Comment by ghost** [comment]
Another big problem is on-boarding of new users. This creates **big entry barrier**.

Even for me. I have a signed Revolut account but I also want to trade with wire transfers. 

So I am forced to take small trade (the seller charges 8% plus) and additional 4-7% of the trade in mining fees. And then wait 30 days.

**Comment by wiz** [comment]
> But sadly :( even when mempool is quite empty (for few hours now) the estimation is BTC tx fee: txFeePerByte=102 which is enormous.

Yes, we've just increased yesterday to always have Bisq use "high" priority fee estimate. The problem is that it's impossible to do fee estimation accurately because of mining variance and random people suddenly broadcasting huge amounts of transactions, so if you use "medium" priority fee your TX can easily get buried and trade can get delayed for hours or days. This is simply the consequence of Bisq trades being on-chain Bitcoin transactions and the only solution is to move to a Layer 2 Network like Liquid or Lightning.

**Comment by softsimon** [comment]
It might be a lot but it is in fact the minimum cost to get into the next block with a high probability.

Switch to medium fee priority fee level would lower the fees but also increase the confirmation wait to 20-30 minutes or longer if new high fee transactions suddenly start to come in fast, as @wiz said.

So it comes down to how long time are you willing to wait for the transactions to confirm, and pay accordingly.

**Comment by ghost** [comment]
I would be willing to wait a lot. Even week in some cases. Maybe would be an option to somehow select the fee (or configure)?

**Comment by cd2357** [comment]
See #4597 -- the fee estimation has been optimized, especially for the scenario you mentioned above (relatively empty mempool).

**Comment by bitcoincoredotbin** [comment]
Just so it is known, I think users would love the ability to set a lower fee and wait, especially during full mempools.

I understand people can come back when it clears, but could we not have a section where both participants indicate they are willing to wait x amount of blocks for a tx to complete? Could RBF or Child Pays for Parent work into the takers security deposit if the fees run away from everyone?

I'm just wanting to provide some liquidity for smaller amounts but highly discouraged by the mining fees at this very moment. Especially when im only seeing 6,000 txs ahead of a reasonable fee rate.

**Comment by pazza83** [comment]
> Just so it is known, I think users would love the ability to set a lower fee and wait, especially during full mempools.

I agree, this would make life a lot easier when placing a number of trades at once. I am not bothered if it takes a long time to confirm. I want to hold onto more sats!

**Comment by ghost** [comment]
I like to share here my post from Keybase (that I made some time ago).

> Hi, did onboarding to few new users (some before the BTC price pumped, some after). I like to share my experience. I am huge fan of Bisq, but I have to be honest here even to myself. Here it is:
> 
> 1) All of the were super positive about Bisq's idea and concept of decentralized exchange. Once they grasped the idea of multisignature escrow, the "click" moment was so beautiful to withness 🥰.
> 
> Rest of it was however not so positive.
> 
> 2) Bisq is slow, I have heard "slow Java" multiple times.
> 
> 3a) Bisq is expensive. Someimes I am doing trades to enable them build trust in Bisq in controlled environment. It was expensive before, but now, its hell. They need to sign accounts and the trade costs 35€ (maker+taker). Trade of 0.01BTC (= 330€) makes it 10% transaction costs. 
> 
> 3b) TRansaction costs are not clearly visible upfront. It was hard to sumarize fees. I think user needs some easy way to see: I buy 0.01 BTC and will pay 330€ + 0.00005 BTC (16.5€) in fees to accept this trade. I think he needs to see it direcly on the offers' list page.
> 
> 4) It takes a lot of time. We had to wait for mempool to be emptier to even be able to do that 35€ trade, if we went yolo, it would be maybe even double of that.
> 
> 5) BSQ token is unaquirable for a new user. Currently the spread is 0.000048 - 0.000069 and the smallest unit the new user can reasonably buy is 150! One trade on Bisql is usually 0.7 (mabye up to 3?) BSQ in fees. New users needs 5-10 BSQ, not 150.
> 
> -------------
> 
> All of them understants that this is a price for privacy and some were willing to pay it. But many of them wont and turned to big exchanges sending them all the dickpics they require.
> 
> ------------
> 
> I would love to see, some ideas and improvents for those users, to lower the barrier of entry.

**Comment by pazza83** [comment]
Hi @petrhejna thanks for posting your experiences.

With regards point 5 BSQ token is unaquirable for a new user. 

I have made the proposal here to [Add 'low priority' payment account type to BSQ](https://github.com/bisq-network/bisq/issues/5153)

@mwithm has also made the recent proposal to [Improve BSQ accessibility through OTC market and bonded reputation](https://github.com/bisq-network/proposals/issues/308)
