### ISSUE TITLE
Trade Step 1: Add "click here to buy BSQ" link next to trade fee selector

### ISSUE THREAD

**Issue by cd2357** [bisq-network/bisq#4579]
In step 1 of a trade, both the maker and the taker have to choose how they pay for the trade fee: in BTC or BSQ.

Most people don't know what BSQ is or where they can get it, especially new users. They probably assume that, since they don't already have any BSQ, they can't choose that option.

Therefore, Bisq should add a link to the BSQ market next to the BTC/BSQ fee selector, like this:

<img width="515" alt="Screenshot 2020-09-30 at 09 48 11" src="https://user-images.githubusercontent.com/15956136/94658422-0fcfe480-0303-11eb-9f1b-45d3cc7038b8.png">

Clicking that link should open the "SELL BTC" view, with the BSQ currency pre-selected.

**Comment by davidlevinwork** [comment]
This issue is still open?
I can take crae of it

How do i get to this specific loaction?

**Comment by cd2357** [comment]
Yes it's still open, you can take it.

For how to get to the location, see how it's done in similar components (for example, in the Market view under the chart, the "Buy BTC" and "Sell BTC" buttons will redirect the UI to those views).

**Comment by davidlevinwork** [comment]
OK, you can assign me?

**Comment by ripcurlx** [comment]
@pedromvpg Could you please come up with a design for it, so it matches the rest of the UI?

**Comment by cd2357** [comment]
Marking it as high prio, since it would improve BSQ liquidity.

**Comment by cd2357** [comment]
@davidlevinwork any progress so far? Did you face any issues, or do you have any open questions?

**Comment by pedromvpg** [comment]
This is a great idea.
I think the premiss of what @cd2357 proposed is great. I would consider to make the copy as short as possible.
Adding an option that has a little more of a flashy button that calls more attention to itself. 

Should we also consider an overlay to explain and entice users to use BSQ? 
What do you think? Too transactional?

 https://www.figma.com/proto/Lmpb1dwCMVByxhsjk7S4Zf/Buy-BSQ-CTA?node-id=1%3A4&scaling=min-zoom

<img width="1010" alt="_Overview" src="https://user-images.githubusercontent.com/807505/95932568-33326f00-0d9a-11eb-8579-a93cf50366b8.png">

![Option A - Dark](https://user-images.githubusercontent.com/807505/95932904-0fbbf400-0d9b-11eb-830d-861f48966b3a.png)
![Option A - Light](https://user-images.githubusercontent.com/807505/95932905-10548a80-0d9b-11eb-97f9-6028ee64cfa2.png)
![Option B - Dark](https://user-images.githubusercontent.com/807505/95932906-10548a80-0d9b-11eb-99c9-566385912361.png)
![Option B - Light](https://user-images.githubusercontent.com/807505/95932907-10548a80-0d9b-11eb-820f-16bf744fe470.png)
![Option C - Dark 1](https://user-images.githubusercontent.com/807505/95932908-10548a80-0d9b-11eb-9493-dcc6f839da3e.png)
![Option C - Dark 2 Overlay](https://user-images.githubusercontent.com/807505/95932910-10ed2100-0d9b-11eb-82f3-4222bf34b412.png)
![Option C - Light 1](https://user-images.githubusercontent.com/807505/95932912-10ed2100-0d9b-11eb-986d-da0ba07ea7f3.png)
![Option C - Light 2 Overlay](https://user-images.githubusercontent.com/807505/95932913-10ed2100-0d9b-11eb-9600-e047c9e4b94f.png)

**Comment by pedromvpg** [comment]
Any thoughts on this @cd2357 @ripcurlx ?

**Comment by cd2357** [comment]
The "Buy BSQ / Learn more" option looks good, but might be overwhelming for new first-time contributors.

So I would suggest the simpler option (with only the "Buy BSQ" button, as you showed it).

**Comment by ripcurlx** [comment]
I'm also for the simple green `BUY BSQ` button with the additional information popup.

![Screenshot](https://user-images.githubusercontent.com/807505/95932906-10548a80-0d9b-11eb-99c9-566385912361.png)

**Comment by chimp1984** [comment]
Anyone working on that? Would be nice to get that in for next release.

**Comment by Jakub-CZ** [comment]
> Anyone working on that? Would be nice to get that in for next release.

I'd like to give it a go. Lately, I've been looking into some simpler GUI-related issues to learn the code base, and I think I'm ready for this one now.

**Comment by cd2357** [comment]
Go ahead @Jakub-CZ 👍

**Comment by Jakub-CZ** [comment]
I've opened my PR as a draft for now, as I've been struggling with some strange behavior in the UI when we switch from one tab to another, especially from _CREATE OFFER_ (under _SELL BTC_) to _SELL BITCOIN_.

Feel free to provide feedback. Hints about what to do with the outstanding UI bug would be most welcome 😏
