### ISSUE TITLE
Dont allow opening mediation if deposit tx is not confirmed

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#4582]
Currently a user can open mediation with cmd+o at trade step 1 where the deposit tx is still not confirmed.
As this might be convenient for helping a user in case of not broadcast txs it is not the purpose of mediation as there cannot be a payout if deposit tx is not confirmed.

Also if both users would agree to the mediated payout suggestion nothing happen and they would get the popup again once the deposit tx gets confirmed.

Not sure if we should not allow to open mediation if deposit tx is not confirmed yet.
Once we have mempool check API requests implemented the user can get a popup with instruction what to do in such cases of not published deposit txs and no mediation is needed. Until that is implemented it might be better to keep it as it is now.

But wanted to document the issues so its not lost...

**Comment by sqrrm** [comment]
It does cause some trouble if a payout is suggested and accepted before the deposit tx confirms and the deposit tx later confirms. I think the accept cannot be done again so the users are stuck and have to open a refund case to continue. That should be pretty rare though since the problem was that the deposit tx didn't confirm to begin with, but could happen with low fee txs that confirm much later.

**Comment by wiz** [comment]
How about fixing the trade protocol so "failed trades" can't occur in the first place?

**Comment by sqrrm** [comment]
@wiz I like how you think. no more troubles!

I think the latest protocol changes will get rid of the missing delayed payout txs, at least the common case we've seen. There are many other things that can happen in async systems though and I doubt we'll ever be failed trades free if we want to continue adding features to bisq.

**Comment by chimp1984** [comment]
> It does cause some trouble if a payout is suggested and accepted before the deposit tx confirms and the deposit tx later confirms. I think the accept cannot be done again so the users are stuck and have to open a refund case to continue. That should be pretty rare though since the problem was that the deposit tx didn't confirm to begin with, but could happen with low fee txs that confirm much later.

I just tested it and the accept popup comes again after deposit tx confirmation (master version). Not sure if last release version has same behaviour, but at least now its not a critical issue.
