### ISSUE TITLE
Distorted UI after suspend

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#459]
Hello.

I get these colored distortions then I wake up x64 ubuntu 14.04 from suspend
![Screenshot](http://s32.postimg.org/vmqwvdzk5/Screenshot_05212016_05_14_41_PM.png)

No other application is affected, the hardware is not overclocked. The distortions do not go away when I resize, move window or switch to other tabs.

**Comment by ManfredKarrer** [comment]
Strange never saw that so far. Seems your graphic driver has issues with java fx after a standby. When you close the app and start new, all is ok, right?

**Comment by ghost** [comment]
Yes, restarting fixes that. FYI I am using proprietary NVIDIA driver v352.63

**Comment by ManfredKarrer** [comment]
That NVIDIA driver might have issues with JavaFX...
