### ISSUE TITLE
100% cpu of v0.4.6 on debian 8

### ISSUE THREAD

**Issue by metabit** [bisq-network/bisq#460]
The UI just got stuck on the warning window "Bitsquare is not a company...".
Trying to click "Close" on that window doesn't help.
It started with 100% CPU, moved to 200%, 300%, 400% CPU (everything this VM has).
Eventually, I sent a kill signal (no need for -9).

top - 18:26:32 up 5 days,  5:23,  2 users,  load average: 0.74, 0.49, 0.26
Tasks: 137 total,   1 running, 136 sleeping,   0 stopped,   0 zombie
%Cpu(s): 25.1 us,  0.0 sy,  0.0 ni, 74.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   1178964 total,   741628 used,   437336 free,    68084 buffers
KiB Swap:  1048572 total,    46896 used,  1001676 free.   146468 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND  
15058 user      20   0 3906444 381788  42212 S 206.3 32.4  78:29.67 Bitsquare

**Comment by ManfredKarrer** [comment]
Can you send me the logs?

**Comment by metabit** [comment]
next time.

**Comment by ManfredKarrer** [comment]
Related to https://github.com/bitsquare/bitsquare/issues/463
