### ISSUE TITLE
Get Bisq into the Hacktoberfest event!

### ISSUE THREAD

**Issue by sam-sla** [bisq-network/bisq#4613]
### Description

Add `hacktoberfest` topic to the Bisq repository(ies), or introduce the label `hacktoberfest-accepted` during October to allow participation into the Hacktoberfest event: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by ripcurlx** [comment]
Just made a shout-out in the keybase #dev channel. If it gets some 👍 , I'll add the topic to the repo for one month.
