### ISSUE TITLE
Memo field is empty after memo was set at withdrawal

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#4616]
### Description

Memo field is empty after memo was set at withdrawal

#### Version

release testing 1.4.0

### Steps to reproduce

create a withdrawal tx (segwit) in send funds with some text set in memo field

### Expected behaviour

memo should be visible in tx list

### Actual behaviour

memo is not visible in tx list

**Comment by chimp1984** [comment]
Could not reproduce it anymore after repeating the test it worked.

**Comment by wiz** [comment]
I've also experienced this many times in 1.3.x

**Comment by chimp1984** [comment]
Ok, then I reopen seems a bug which happens only in certain circumstances.

**Comment by ripcurlx** [comment]
Closing as complete as merged into release branch.
