### ISSUE TITLE
Cannot take fiat offer with very low amount if not having a signed witness

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#4617]
### Description

I tried to take an offer with 0.001 BTC from a new dev app with a new AliPay account. Not account witness signed.
Got greyed out offer and popup that i cannot take offer. 

UPDATE: Seems that happens only at startup, after a restart I could not reproduce it anymore. The account age was probably not available first. Still we should look if the behaviour of the code below is as intended.

#### Version

1.4.0

#### Additional info

At debugging it seem the verifyPeersTradeLimit is not called as there is no witness found and we return false in that case.
```
   public boolean verifyPeersTradeAmount(Offer offer,
                                          Coin tradeAmount,
                                          ErrorMessageHandler errorMessageHandler) {
        checkNotNull(offer);
        return findWitness(offer)
                .map(witness -> verifyPeersTradeLimit(offer, tradeAmount, witness, new Date(), errorMessageHandler))
                .orElse(false);
    }
```

When having 2 accounts, 1 is signed the other not, this check is not executed, I can go to take offer screen and select any of the 2 accounts.  If I try to take an offer with 1 BTC and I have 2 accounts, I can select both but the not-signed one disables the next button without any info why. There should be a popup or some sort of info or better not add the account to the selction list in the first place.

@sqrrm Can you have a look?

**Comment by sqrrm** [comment]
I think the AccountAgeWitness hadn't been propagated when the offer was taken. That would make it impossible to take the offer. I think it's reasonable to disallow taking offers if data on the p2p network is having issues.

**Comment by chimp1984** [comment]
I think we should treat the case that a ccount age witness is not found the same way as when it would be a new account, so apply min. limits but allow trading. Now the offer cannot be taken (taker has the issue - so he cannot take any fiat offer).
