### ISSUE TITLE
Modify account nr field text for "Create new account" under OKPay

### ISSUE THREAD

**Issue by metabit** [bisq-network/bisq#462]
Currently the field is called "Account nr."
OKPay has either account ID or wallet id.
The name "Account nr" may confuse a user to put the account id.
Please change the name to "Wallet ID".

**Comment by metabit** [comment]
validation of the field input may help avoiding mistakes. The string must start with "OK" and contain only digits (in my case, 9 digits).

**Comment by ManfredKarrer** [comment]
Thanks for the suggestion, will change that. Input validation is also on the todo list for the next release.

**Comment by ManfredKarrer** [comment]
Will be in next release.
