### ISSUE TITLE
Wallet restore at startup causes exception in 1.4.0

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#4622]
### Description

Wallet restore at startup causes exception in 1.4.0

#### Version

1.4.0

### Steps to reproduce

Set a wallet pw and store seeds with 1.3.9. Restart with 1.4.0. At initial pw request window click forgot pw, then the screen extends and shows seed recovery fields. enter seeds and click restore. 

### Expected behaviour

Recovered from seeds.

### Actual behaviour

Throws exception.

#### Additional info
Expects checkState(vRunning); but we have not started wallet configs service (block download) at that moment.

It does not happen after wallet has been migrated, so at a second start with 1.4.0 it works. Because it is only at migration time an issues it does not need to be fixed IMO if a fix is difficult to achieve as it is a very unlikely event and can be resolved with a restart.

```
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:492)
	at org.bitcoinj.core.PeerGroup.stopAsync(PeerGroup.java:1130)
	at org.bitcoinj.core.PeerGroup.stop(PeerGroup.java:1161)
	at bisq.core.btc.setup.WalletConfig.shutDown(WalletConfig.java:471)
```

**Comment by cd2357** [comment]
Solved in #4631
