### ISSUE TITLE
Freeze due to out of memory v0.4.6 on debian 8

### ISSUE THREAD

**Issue by metabit** [bisq-network/bisq#463]
I just kept the Bitsquare open on the market window.
log below.

broadcastQueue=[ayfxhikmv3bosb2h.onion:9999, hbma455xxbqhcuqh.onion:8000, 2zxtnprnx5wqr7a3.onion:8000, uadzuib66jupaept.onion:8000] 
May-22 22:56:02.453 [JavaFX Application Thread] WARN  i.b.p.p.BroadcastHandler: Timeout: Broadcast did not complete after 120 sec. 
May-22 22:56:02.686 [JavaFX Application Thread] WARN  i.b.p.p.BroadcastHandler: Timeout: Broadcast did not complete after 120 sec.
    numOfPeers=4
    numOfCompletedBroadcasts=0
    numOfCompletedBroadcasts=0
    numOfFailedBroadcasts=0
    broadcastQueue.size()=4
    broadcastQueue=[hbma455xxbqhcuqh.onion:8000, pee7azoka5dstdkf.onion:9999, 2zxtnprnx5wqr7a3.onion:8000, uadzuib66jupaept.onion:8000] 
May-22 22:56:02.687 [JavaFX Application Thread] WARN  i.b.p.p.BroadcastHandler: Timeout: Broadcast did not complete after 120 sec. 
May-22 23:01:34.288 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-22 23:01:34.509 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:3332)
    at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
    at java.lang.StringBuilder.append(StringBuilder.java:136)
    at io.bitsquare.p2p.storage.storageentry.ProtectedStorageEntry.toString(ProtectedStorageEntry.java:72)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-19"
May-22 23:01:51.894 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-22 23:01:51.895 [PeerGroup Thread] ERROR o.b.c.PeerGroup: Exception in ping loop java.lang.OutOfMemoryError: Java heap space

java.lang.OutOfMemoryError: Java heap space
May-22 23:01:51.894 [Wallet autosave thread] WARN  o.b.core.Wallet: Temp file still exists after failed save. 
May-22 23:01:51.896 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
java.lang.OutOfMemoryError: Java heap space
May-22 23:04:48.449 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-22 23:04:48.450 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
java.lang.OutOfMemoryError: Java heap space
May-22 23:05:25.631 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-22 23:05:26.072 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
java.lang.OutOfMemoryError: Java heap space
May-22 23:06:51.706 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-22 23:06:52.168 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
java.lang.OutOfMemoryError: Java heap space
May-22 23:07:29.646 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-22 23:07:30.115 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
java.lang.OutOfMemoryError: Java heap space
May-22 23:08:09.351 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-22 23:08:09.808 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
java.lang.OutOfMemoryError: Java heap space
May-22 23:08:50.752 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-22 23:08:50.980 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
java.lang.OutOfMemoryError: Java heap space
May-22 23:09:37.472 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-22 23:09:38.389 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
java.lang.OutOfMemoryError: Java heap space
May-22 23:10:30.434 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-22 23:10:40.936 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
May-22 23:11:13.869 [PeerGroup Thread] ERROR o.b.c.PeerGroup: Exception in ping loop java.lang.OutOfMemoryError: Java heap space

java.lang.OutOfMemoryError: Java heap space
May-22 23:11:14.572 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-22 23:11:15.782 [InputHandler-localPort=46894/port=54603] WARN  i.b.p.n.Connection$SharedModel: Unknown reason for exception at socket Socket[addr=/127.0.0.1,port=54603,localport=46894]
    connection=SharedSpace{, socket=Socket[addr=/127.0.0.1,port=54603,localport=46894], ruleViolations={}}
    Exception= 
May-22 23:11:23.103 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
java.lang.Exception: java.lang.OutOfMemoryError: Java heap space
    at io.bitsquare.p2p.network.Connection$InputHandler.run(Connection.java:777)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
May-22 23:11:37.108 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-22 23:11:43.878 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
java.lang.OutOfMemoryError: Java heap space
May-22 23:11:50.019 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-22 23:11:55.709 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
java.lang.OutOfMemoryError: Java heap space
May-22 23:12:03.099 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-22 23:12:08.308 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
java.lang.OutOfMemoryError: Java heap space
May-22 23:12:20.188 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-22 23:12:29.195 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
May-22 23:12:46.421 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-22 23:12:46.421 [PeerGroup Thread] ERROR o.b.c.PeerGroup: Exception in ping loop java.lang.OutOfMemoryError: Java heap space

java.lang.OutOfMemoryError: Java heap space
May-22 23:12:50.548 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
java.lang.OutOfMemoryError: Java heap space

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "NioClientManager"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AWT-XAWT"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AWT-EventQueue-0"

**Comment by ManfredKarrer** [comment]
Can u send me the complete log files? its in shared/local/Bitsquare. you can open it also under Account/Backup.
Do you have another machine where u can try it? I did not get OutOfMemoryErrors reported from others, so I assume its some config issue on that vm.

**Comment by metabit** [comment]
logs sent in private.

**Comment by seamlik** [comment]
I do not have a generated log but from the GNOME Monitor I can see BitSquare fills **ALL** of my RAM which is 8 GiB, as well as **ALL** of my swap area. This is terrible.

Note that I live in China and the Internet censorship might block the P2P connections of BitSquare and the Tor Network it is using.

**Comment by ManfredKarrer** [comment]
You can find the logs under .local/shared/Bitsquare. It would be great if you coudl send me the logs as that issue never happened so far i know. It usually consumes 100-300 MB.
