### ISSUE TITLE
Text field labels not fully visible (v1.3.9, v1.4.0, jfoenix=9.0.10)

### ISSUE THREAD

**Issue by ghubstan** [bisq-network/bisq#4639]
### Description

Note:  built with ` jfoenixVersion=9.0.10` (upgrade).  This bug may not appear when using jfoenix v9.0.6.

Almost 1/2 of the "A" in two "Address" labels at the bottom of the FUNDS -> RECEIVE FUNDS view is hidden, as seen in the the v1.3.9 + v1.4.0 screenshot:

![AddressLabels-2020-10-13](https://user-images.githubusercontent.com/36207203/95883137-f3936500-0d50-11eb-85c6-5683141b2926.png)

#### Version

v1.3.9, v1.4.0

### Steps to reproduce

Navigate to FUNDS -> RECEIVE FUNDS

### Expected behaviour

Address field labels should be fully visible.

### Actual behaviour

Address field labels are not fully visible.

#### Device or machine

Ubuntu 20

**Comment by ghubstan** [comment]
The same problem exists in Chat windows -- the "Enter Message" text box label:

![Chat-2020-10-13](https://user-images.githubusercontent.com/36207203/95884706-d069b500-0d52-11eb-9414-436aa700bc2a.png)

**Comment by ghubstan** [comment]
And in the "Withdraw to address" and "Withdrawal memo" text box labels in the FUNDS -> SEND FUNDS view:
![send-funds](https://user-images.githubusercontent.com/36207203/95885117-453cef00-0d53-11eb-9e00-64b60f02ef9d.png)

**Comment by cd2357** [comment]
A similar issue on a diferent branch was fixed with https://github.com/bisq-network/bisq/pull/4242/commits/8137cb982f443c90d7f103f370fac8814bd370f3

There (#4242) the misalignment came after the jfoenix and JavaFX versions were updated.

Not sure why it is happening on 1.3.9/1.4.0 though.

**Comment by ghubstan** [comment]
> A similar issue on a diferent branch was fixed with [8137cb9](https://github.com/bisq-network/bisq/commit/8137cb982f443c90d7f103f370fac8814bd370f3)
> 
> There (#4242) the misalignment came after the jfoenix and JavaFX versions were updated.
> 
> Not sure why it is happening on 1.3.9/1.4.0 though.

@cd2357  Oops!  This is with `jfoenixVersion = '9.0.10'`

I had to upgrade to avoid those jfoenix 9.0.6 reflection related NPEs when I use `apitest` harness to start all the apps (to save time).  I will not close the issue but I will change the title & description to emphasize this is JFoenix 9.0.10 related.

**Comment by cd2357** [comment]
Fixed in the most recent release (v1.6.4) which includes the fix mentioned above https://github.com/bisq-network/bisq/issues/4639#issuecomment-707840375.

Please try it out and let us know if it's still an issue for you.
