### ISSUE TITLE
No blockchain confirmation, to low transaction fee?

### ISSUE THREAD

**Issue by kristoffernolgren** [bisq-network/bisq#464]
This is my second attempt at performing an exchange. The bitcoins were in my bitsquare wallet and I used the default values suggested by the bitsquare app. After 24 hours, the transaction was not complete. Was the transactionfee to low? Should the default fee be a bit higher or even change dynamically? Can I manually set the transaction fee?

contract:
`{
  "offer": {
    "direction": "BUY",
    "currencyCode": "ETH",
    "paymentMethodName": "BLOCK_CHAINS",
    "arbitratorNodeAddresses": [
      {
        "hostName": "ntjhaj27rylxwvnp.onion",
        "port": 9999
      }
    ],
    "id": "391eabdc-2cda-477e-8fd8-cefaa1e33e86",
    "date": 1463522956065,
    "protocolVersion": 1,
    "useMarketBasedPrice": true,
    "fiatPrice": 0,
    "marketPriceMargin": 0.001,
    "amount": 100000000,
    "minAmount": 50000000,
    "offererNodeAddress": {
      "hostName": "dm5jlpof7sk3ld75.onion",
      "port": 9999
    },
    "offererPaymentAccountId": "503666f9-12ee-4b37-8465-0762bb9ed4e5",
    "offerFeePaymentTxID": "2c8031db3d2b9317f399e5e413e0ef4b9d05d801b06d426001f014496dd67829"
  },
  "tradeAmount": 98900000,
  "tradePrice": 305200,
  "takeOfferFeeTxID": "7cc0a052f6833c7ad56186a42aac21b0c2afb1c531d597ec34f5425af37dae93",
  "arbitratorNodeAddress": {
    "hostName": "ntjhaj27rylxwvnp.onion",
    "port": 9999
  },
  "isBuyerOffererAndSellerTaker": true,
  "offererAccountId": "1571906013",
  "takerAccountId": "1891045316",
  "offererPaymentAccountContractData": {
    "address": "0xe4e13a5d9c71a42198882c6de533af0c64a07433",
    "paymentMethodName": "BLOCK_CHAINS",
    "id": "503666f9-12ee-4b37-8465-0762bb9ed4e5",
    "maxTradePeriod": 86400000
  },
  "takerPaymentAccountContractData": {
    "address": "0x749f65F44040CAF295211685f0f5481FBB8ee811",
    "paymentMethodName": "BLOCK_CHAINS",
    "id": "73e0d294-2d0b-41ef-8027-168fad5dd23c",
    "maxTradePeriod": 86400000
  },
  "buyerNodeAddress": {
    "hostName": "dm5jlpof7sk3ld75.onion",
    "port": 9999
  },
  "sellerNodeAddress": {
    "hostName": "xlr2kjffxybxilwy.onion",
    "port": 9999
  },
  "offererPayoutAddressString": "15CM9B7RzCskZhczmVP6SCCJyvJeyxLrnk",
  "takerPayoutAddressString": "19rsmmSTcBocPV2pTG7VCaGcEieLtUymK1"
}`

**Comment by ManfredKarrer** [comment]
If u have been the taker then your funding fee (from your external wallet) was too low.
The taker offer fee tx is still not in the blockchain. 
https://blockchain.info/tx/7cc0a052f6833c7ad56186a42aac21b0c2afb1c531d597ec34f5425af37dae93
if you have been the offerer then the other peer has caused that issue.

Unfortunately we cannot control the mining fee used from external wallets. We had a fee check earlier in to not accept tx with too low fees, but that caused also much issues. Need to improve that though as it seems that there are still many old wallets out which does nto handle fee calculation good.

For now the only option is to either try to do a double spend from the external wallet, so the whole trade becomes invalid, or to wait until the tx gets into the blockchain. I will close the dispute, so as soon the initial funding tx gets intot the blockchain all the follow up tx will become valid as well.
Btw. If u try to double spend I am not sure if the UI handles that correctly, the bitcoin will not have left your wallet but might need some extra steps to get the right balance displayed. So better to wait.

Which exterenal wallet did u you?

**Comment by kristoffernolgren** [comment]
Yes I was the taker, but I had the bitcoins in my bitsquare wallet, not an external wallet. I could not see  what fee was set for my transaction or how I could change it. Now the exchange has gone throug. I don't have to invalidate the trade, if the other party wants to go through with it. I'm not sure what the timelimit is suppose to indicate.

Thanks, let me know if I can help in any other way!

**Comment by ManfredKarrer** [comment]
In Bitsquare we use 0.0002 BTC which is about 50%-100% over the average fee, so that should be fine.
I just checked the tx and it seems indeed that all the previous tx had 0.0002 BTC. I did not follow the stress level on the blockchain, but maybe there was "stress-tests/spamming/create blocksize increase pressure attacks" ongoing? Or you simply got the tx delivered to a miner who preferred other tx for whatever reason. 

The trade period  limit is needed that the btc buyer has time pressure to send the fiat (altcoin), otherwise he could wait forever... 
But seems the wording is not very intuitive, you are not the first who don't understand what it means. Do u have a suggestion for a better term?

**Comment by ManfredKarrer** [comment]
Ah forgot to answer the rest: As there is a dispute already open you cannot continue normally. I will close the dispute an d both get back their btc.

**Comment by kristoffernolgren** [comment]
Now it just says "time left", maybe "Time left for X to do Y" would be more clear. 

Maybe this is a bigger change, but it would make more sense if it's a countdown for a specific task that the count down starts once the user can initiate the change, in this case after the blockchain is confirmed. I'm assuming big fluctuations in transactioncosts and delays for aslong as the core/classic-conflict rages on. I'm hoping lighting networks will help, but if they do there are probably years before they are fully deployed across the echosystem.

**Comment by ManfredKarrer** [comment]
Close the issue as the tx is in the blockchain. But i am aware of the problem and try to find a solution in upcoming releases.
