### ISSUE TITLE
Proposed changes to the 'Trades', 'History' and 'My Open Offers' sections in the Bisq client

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#4641]
### Description

Following the discussion #4630 I thought it would be useful for me to include what are hopefully some simple changes that would make it easier for traders with multiple offers to use Bisq.

I think the changes would also be of benefit all Bisq users by adding more transparency about trade history. 

I would like to propose changes to the following areas on the Bisq client:

- Trades
- History
- My Open Offers

#### Proposed changes - Trades

In the 'Trades' section  add the following:

A column that displays trade 'percentage deviation from market', this should be sort-able by percentage size upon clicking.

An 'EXPORT TO CSV' at the bottom button similar to 'Portfolio > History'

Proposal:

![image](https://user-images.githubusercontent.com/66367547/95908599-2d865a80-0d95-11eb-916a-68d10e40bc86.png)

#### Proposed changes - History

In the 'History' section add the following:

A column that displays trade 'percentage deviation from market', this should be sort-able by percentage size upon clicking.

Proposal:

![image](https://user-images.githubusercontent.com/66367547/95908672-468f0b80-0d95-11eb-88d4-9289742f8b4f.png)

#### Proposed changes - My Open Offers

In the 'My Open Offers' section currently price and percentage deviation from market are combined together in one column. Break them up into two separate columns. Make each sort-able.

Proposal:

![Bisq - Open Offers](https://user-images.githubusercontent.com/66367547/96002308-dfbf3000-0e30-11eb-8f78-8ca45ce3cc8c.png)

#### Version

v.1.3.9

### Steps to reproduce

View existing screens in the following sections 

Market >Trades
Portfolio > History
Portfolio > My Open Offers

### Expected behaviour

Be able to see percentage deviation from market price in all the above sections.

Be able to sort 'percentage deviation from market price' in all the above sections.

Be able to export Trade history to CSV file within the Bisq client. I think the export all markets CSV might take be resource intensive as it would be exporting every offer that has ever taken place on Bisq. However, it would be great if this where achievable.  

### Actual behaviour

You are currently unable able to see percentage deviation from market price in the Trades and History section.

You are currently unable to sort 'percentage deviation from market price' in all the above sections.

You are currently unable Trade history to CSV file within the Bisq client. NB you can download your own history but it would be great to download the whole of Bisq's history (All markets, or per market).

#### Additional info

I believe the above changes would add to the usability a Bisq for all users, especially those managing a large number of offers.

Please let me know your thoughts.

**Comment by sqrrm** [comment]
These all sound like reasonable and easy additions. I think all the data is already available so it would be a matter of adding some UI elements. Seems like some good first issues to implement each of the suggestions.

**Comment by Conza88** [comment]
Tangentially related: ability to tag the trades and this is exportable with the other data. E.g. putting in funds for honeymoon, or a transaction with a friend you want to record, funds you're holding for your mother, friends or family (who they are), spouses input etc.

Really think this would be a good value add.

**Comment by ghost** [comment]
@sqrrm What do you think about OP's proposal to add "% deviation from market" to the Market/Trade History display?  It would imply adding that data to TradeStatistics3 which is widely used.  @chimp1984 has already added the Export to CSV part in https://github.com/bisq-network/bisq/pull/4702.  Personally, I'm not for messing with TradeStatistics3 but interested to hear your take.
