### ISSUE TITLE
Lower default minimum amout of bitcoin when creating offer.

### ISSUE THREAD

**Issue by kristoffernolgren** [bisq-network/bisq#465]
The default value is a very powerful one. The default minimum amount of bitcoin when creating an offer is equal to the amount of bitcoin value. If the minimum amount was some fraction, maybe 30%, it would result in more available deals and a closer to perfect market.

**Comment by ManfredKarrer** [comment]
Do you mean the 0.0001 BTC? That is already lower than the mining fee....

**Comment by kristoffernolgren** [comment]
It seems to default to minimum price of 1BTC if the offering = 1btc, lots of offers between btc and eth are on 1btc or .5btc....
![screen shot 2016-05-25 at 16 25 05](https://cloud.githubusercontent.com/assets/485125/15543494/6c39c9fa-2295-11e6-9eea-7da0b4d3f9ff.png)

**Comment by ManfredKarrer** [comment]
Thats what users put in, there is no default value for that.

**Comment by ManfredKarrer** [comment]
Ah sorry I misunderstood... The auto fill is just for convenience. People who want to offer an amount range need to edit the field. I cannot set a lower amount as than people will complain that they have not been aware of that.

**Comment by kristoffernolgren** [comment]
So the assumption is that people who want to trade an equivalent of 450 USD want to trade exactly 450 usd, no more and no less.

From a takers perspective, it's very inconvinient if you already have money in your bitsquare wallet. If you for example put in 1btc, that will exactly not be enough to do barley any trades.

**Comment by ManfredKarrer** [comment]
The offer has better chances to find a taker if he offers a range. But I think I cannot seta  default for that what he want to accept as min. amount. He need to do that by himself. Earlier I did nto fill in but usability testers complained that it is inconvenient to need to fill it themselfes.
