### ISSUE TITLE
Nullpointer exception while creating new "Transfer with same bank"-fiat account 

### ISSUE THREAD

**Issue by DanielWeigl** [bisq-network/bisq#466]
App throws a java.lang.NullPointerException when I try to create a new fiat account of the type "Transfer with same bank"
1. go to "Account"
2. "National currency accounts"
3. "Manage accounts", "Add new account"
4. change "payment method" to "Transfer with same bank"
5. Select "Europe", select any country -> App throws error.

Logfile does not show that much info:

> Mai-25 21:16:40.206 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
> Mai-25 21:16:40.207 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= null 

Ubuntu, 64bit, version 0.4.7

**Comment by ManfredKarrer** [comment]
Thanks! Need to push a new update with that fix and another for XMR :-(...
Will be out in about 1 hour....
