### ISSUE TITLE
Tagging peer only updates one row instead of all affected rows before restart

### ISSUE THREAD

**Issue by MarioIshac** [bisq-network/bisq#4660]
### Description

Tagging a peer only applies that tag to the selected row of that peer instead of all their rows, until a restart is done.

#### Version
1.3.9

### Steps to reproduce
Tag an untagged peer who has multiple rows on the offer sheet. 

### Expected behaviour
All rows of this peer would update to reflect the new tag.

### Actual behaviour
Only the selected row of this peer updates to reflect the new tag.

### Screenshots
Before restarting:
![before_restart](https://user-images.githubusercontent.com/14341439/96291794-7446a100-0f9d-11eb-800c-bfa6a039ea5e.png)

After restarting (now that all rows are reloaded):
![after_restart](https://user-images.githubusercontent.com/14341439/96291720-5416e200-0f9d-11eb-8b97-aede29cd484e.png)

#### Device or machine
Ubuntu 20.04

#### Additional info
It's a very minor issue, but I can attempt to solve it as my first issue to get familiar with Bisq repository.

**Comment by cd2357** [comment]
Until a restart is done -- or until the user navigates to another view and comes back. That triggers a "reload" / refresh of the view, which shows the tag on all the rows for that peer.
