### ISSUE TITLE
Lagged back window instead of popup

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#4663]
### Description

After popup shows, there is delay and the popup appears black. After some time, popup will appear and works

I thought that it may be RAM related, but I have checked and it happend when only 6gigs/16 are full.

#### Version
`1.3.9`

### Steps to reproduce

Every single poupup.

#### Device or machine
- 16GB of RAM
- `Ubuntu 20.04.1 LTS`

#### Additional info
- Maybe related to: https://github.com/bisq-network/bisq/issues/4370

#### Screenshots
![image](https://user-images.githubusercontent.com/383295/96334406-dae8bf00-1070-11eb-9894-ad042258b30c.png)

**Comment by cd2357** [comment]
Will probably be fixed by #4242

**Comment by cd2357** [comment]
Should be fixed in the most recent release (v1.6.4) which upgraded several UI components and libraries. Please try it out and let us know if it's still an issue for you.
