### ISSUE TITLE
Controll fees for wIthrawl 

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#4664]
I like to propose an adding of some slider (or input) to manually set fees (sat/byte) for withdrawals.

**Use case:** 

1. I can correct the estimate when mempool is actually empty. 
2. I pay nearly always only 1sat/byte and I am OK to wait a week for confirmation.

![image](https://user-images.githubusercontent.com/383295/96334815-c954e680-1073-11eb-91ea-9a019034cefb.png)

**Comment by huey735** [comment]
This feature is available under Settings > Preferences with the minimum value allowed of 2 sats/byte

![preferences](https://user-images.githubusercontent.com/44140017/96514916-5064b300-125c-11eb-90ec-ae434e9678ed.png)

**Comment by ghost** [comment]
Ah, thanks a lot. I overlooked it.

However I think it can be useful to be able to control fees easily per translation.

But it has OFC low priority.

**Comment by cd2357** [comment]
Closing, as the question was answered above.

Regarding custom fees per transaction, that's covered in more detail in other issues like #4575.
