### ISSUE TITLE
Binaries: Hash validation error with the signed hashes file; it is not SHA512

### ISSUE THREAD

**Issue by oriolpont** [bisq-network/bisq#467]
File signed_sha256_hashes.txt contains sha256 hashes (as its filename says) but inside it reads: -----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512
(...)

sha512 gives twice longer, completely different hashes.  

Actually, this is a rather minor issue: I did not have the filename in my view, yet I immediately realized I needed 256-bit-long not 512-bit-long hashes. It is nevertheless in a very sensitive location so it is probably worth fixing it.

**Comment by ManfredKarrer** [comment]
Unfortunately that "Hash: SHA512" string is created by gpg  and it just means that it is used for the hashing of that text for the signature.
So the binary hashes are sha256 and if u run gpg --verify signed_sha256_hashes.txt u never need to do anything with SHA512.
But I know its confusing, someone else has reported already as well.

**Comment by oriolpont** [comment]
Part of the pgp message, of course; my bad! Not an issue then.

May I ask though why do not you sign the binaries themselves? Then users would just need to run gpg --verify filename.asc and that is it. Currently, we need to: gpg for the hashes file, then sha256 on the binary, then copy paste the hash to a text file and diff to check that they match (or do a riskier visual comparison).

**Comment by ManfredKarrer** [comment]
I wanted to have all compact and Bitcoin Core uses the same structure, so I though I am in good company :-)
