### ISSUE TITLE
UI tips to avoid sell/buy confusion

### ISSUE THREAD

**Issue by ivilata** [bisq-network/bisq#468]
Hi, I'm not very familiar with trading and I find one detail in Bitsquare a little bit confusing for beginners: when one clicks on _Create new offer for buying bitcoin_ under the _Buy BTC_ tab, the offer ends up under the _Sell BTC_ tab, and conversely, when one clicks on _Create new offer for selling  bitcoin_ under the _Sell BTC_ tab, the offer ends up under the _Buy BTC_ tab.  Although why it is so should be clear after a little thought, it's somehow shocking UI-wise that the add action under one tab creates an entry under the other one.

The case for expert traders should be clear since they probably go straight to the right button.  However, not so expert users may be more interested in creating an offer only when they don't see an adequate one to take in the list, so a little text in the UI may be helpful.  For instance, under the _Buy BTC_ tab, a text label to the left of the _Create new offer for buying bitcoin_ may say _Not finding an interesting offer?_ (a tooltip version over the button may be an option, but not so informative), then in the new _Create offer_ tab, just before the input fields, a text may read _You may create a new offer for buying bitcoin if you do not find an interesting offer, or if you want to sell other currency you already have in exchange for bitcoin. The new offer will be available under "Sell BTC" for others to take it._.

I'm sure the wording can be made a lot better, but the point is to widen the scope of users from traders to other people that can need some more sporadic trades. Thanks!

**Comment by ManfredKarrer** [comment]
Yes I am aware of that. Maybe I add to the popup after creating an offer the info that the offer can be found at the other side.

**Comment by haiqu** [comment]
I also had issues with this, but I can also see that having a button under the Buy BTC view that says "Create new offer to Sell BTC" would equally confuse the newbie.

It is what it is, I think we should close this one.
