### ISSUE TITLE
Issues with buyer's first Zelle transfer

### ISSUE THREAD

**Issue by dcod3d** [bisq-network/bisq#4684]
As a seller, I'm starting to get more and more first time buyers (account age 0 days) trying to buy with Zelle (presumably on a new bank account) and getting their bank account frozen. So far, every case has ended up in mediation with the buyer never going through with the purchase (with 2 more going into mediation this week). Of course, each buyer is accusing me that I was the reason their account was flagged for fraud and almost every case ended up in arbitration. I presume it's because they left the platform as I usually have waited about a week past the time lock to decline the mediator's suggestion to send it to arbitration. Few of the buyer's did disclose which bank they were using and it was always the same bank. So, I went ahead and tried to open a new bank account at this bank and then tried to send a $5 Zelle payment to myself (not an account I use for Bisq). And this bank also froze my account for suspicious activity even though they saw I was sending money to myself. 

I'm not sure how many other sellers are having this issue, but I would l like to see additional verbiage in the Zelle account creation process to inform the user it's their responsibility to be able to send a Zelle payment and they should test it out before their first purchase.

**Comment by ghost** [comment]
Still relevant.  @pazza83 could you suggest wording for this?

**Comment by pazza83** [comment]
Hi @jmacxx 

Thanks I will take a look.

It would be good to hear if any other users are having these problems.

I think @ncstdc advice about checking the payment method before making payment is sound advice. I will look at adding something in the Wiki about this.

@ncstdc have you got any more information about this to see if it affects all Zelle users or just those sending payment to yourself :)

**Comment by dcod3d** [comment]
For about ~70% of the cases, I was able to confirm with the buyer it was their first external transfer and at a specific bank. The other ~30% would not confirm. 

It's less common now as I get fewer first time (unsigned) buyers and I try to send them a message first requesting they try to send a Zelle payment first.. I probably still get this once a month based on buyer hitting the payment started button and waiting several days for the payment to clear. I am guessing it is easier now to unfreeze an account which requires a visit to a branch.

**Comment by pazza83** [comment]
Hi @ncstdc thanks for the quick feedback.

I am keen to add wiki's for all the payment methods on Bisq.

I have never used Zelle and due to my location am not able to.

Would you be interested in creating any content for a Zelle wiki with  guidelines for new users?

Here is a link to the payment methods wiki: https://bisq.wiki/Payment_methods
