### ISSUE TITLE
Tor startup too slow in Bisq app

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#4687]
Tor startup takes about 30 sec for me. Hidden service another 3-5 sec (which is expected). Before update to v3 we had about 3-5 sec. for tor startup. While working on the new monitor using a very lightweight tor setup I observed to have a startup of about 3-5 sec. So something went wrong when adding v3 support in the way how Tor get initialized on Bisq.

**Comment by wiz** [comment]
What do you mean exactly by "update to v3" ? AFAIK we have supported v3 onions since Bisq v0.9.7, it was just not enabled by default

**Comment by chimp1984** [comment]
Was not related to that. Reason was that we always deleted the tor files (beside HS dir), that slowed down startup. Was even a todo and comment there... Another low hanging fruit ;-) If we would just read the todos and fix them Bisq would be 10 x better....
