### ISSUE TITLE
Enable [Return key] when in Password field

### ISSUE THREAD

**Issue by tkemmere** [bisq-network/bisq#469]
Hi,

Upon opening the Bitsquare Application, the user has to type his/her password. When having done that, "hitting return" has no effect. The user has to use the mouse and click on the button Proceed. This is counter-intuitive.

Issue experienced with Windows-64-bit version.

It is a minor thing, but a "nice to have".

Thomas.

**Comment by ManfredKarrer** [comment]
I just tested on Mac and here it works, though it takes a bit for decrypting. Need ot test on Windows as well, but maybe u can have a look if it was not only a delay?

**Comment by ManfredKarrer** [comment]
Closed as not reproduceable. Please re-open if still a problem.

**Comment by tkemmere** [comment]
Hi Manfred,

Sorry for not coming back to you about this. It is good you closed the 
issue.

I just tested your suggestion and waited after hitting return. It takes 
4 seconds and then is works! Indeed.

So now the 'nice to have' would be an hour-glass-type-of-thing. But it 
is so minor. I suggest to just drop it. But if you would like I can make 
an issue for that. Up to you.

Cheers, Thomas.

Greenlight Consultancy
Korte Vleerstraat 22, 2513VM Den Haag, Nederland
Mob: +31 (0)6-4000.7771
E-mail: thomas @ greenlight - consultancy . nl
Web: www.greenlight-consultancy.nl

(Duurzaamheid gaat veel verder dan e-mails niet uitprinten).

**Comment by ManfredKarrer** [comment]
Yes will put a busy indicator... (no need for an issue i put it on my todo list).
