### ISSUE TITLE
BSQ Issued not updated since February

### ISSUE THREAD

**Issue by leo816** [bisq-network/bisq#4690]
### Description

BSQ issued doesn't show up since February

#### Version

1.4.2

### Steps to reproduce

DAO/ Facts and Figures/ BSQ supply

### Screenshots

![8A1BD93B-D4AC-4A69-8E5D-6B161374BDDD](https://user-images.githubusercontent.com/54798241/96975673-107f2380-151b-11eb-9a7a-4a628c1b15d9.jpg)

#### Device or machine

MacBook Pro 
MacOS Mojave

**Comment by cd2357** [comment]
The green progress bar in the bottom left shows "Synchronizing DAO" is stil ongoing?

**Comment by leo816** [comment]
yes, all good now. Thanks for pointing it out

**Comment by cd2357** [comment]
Sure 👍 

Then I'll close this.
