### ISSUE TITLE
[Q] when do I choose the fiat currency account during buy?

### ISSUE THREAD

**Issue by thob** [bisq-network/bisq#470]
I currently have 2 accounts and it seems I can't choose during the process or I missed it.
can you help?

**Comment by MarcSte** [comment]
You can add accounts in the 'Account' tab under 'Manage accounts'.

When creating an offer you can choose the bank account in the dropdown menu of the 'sell btc' or 'buy btc' tab.

When taking an offer, you can select the account in the 'Take offer' screen. This would look like the following:

'Buy btc' tab
'Buy btc' button

You will be prompted to the 'Take offer' tab.

You can now choose a bank account from the dropdown menu in the 'Payment info' field.

**Comment by thob** [comment]
Thanks, seems I missed it last time. Will look more carefully next time.
