### ISSUE TITLE
Take Offer Error: LockTime of Maker is more than 3 blocks different to the LockTime I have

### ISSUE THREAD

**Issue by mpowacht** [bisq-network/bisq#4707]
#### Version
1.3.9 and 1.4.2

### Actual behaviour

When taking an offer for 0.01 BTC with EUR/Revolut with trade ID izxdhj-877b1ad8-1aa3-4fa1-b471-30758e64ba71-139 I get:
Take Offer Error: LockTime of Maker is more than 3 blocks different to the LockTime I calculated.
Screenshot below. 
Tried several times. The same happens when I perform a local take offer in national currency THB and national bank transfer.

### Screenshots

![image](https://user-images.githubusercontent.com/59683372/97126029-57158d80-1768-11eb-9611-462734f7d60e.png)

![image](https://user-images.githubusercontent.com/59683372/97126211-d1dea880-1768-11eb-8f65-531c42919ee6.png)

![image](https://user-images.githubusercontent.com/59683372/97126356-2eda5e80-1769-11eb-92ed-ac3fc7e60d08.png)

**Comment by ghost** [comment]
What are the two lockTime numbers shown in the error message?  (they are clipped out of view in the screenshot).

**Comment by mpowacht** [comment]
I see them in the first screenshot above, but here they are:  makers LockTime=657184, myLockTime=647999

**Comment by ghost** [comment]
Maker's lock time is good, yours is not.  Probably your SPV state is stalled, please resync it from the Bisq interface as described here: https://bisq.wiki/Resyncing_SPV_file

Unfortunately the trade is failed, but after resyncing any further trades should complete normally.  You can request a reimbursement for lost trade fees here: https://github.com/bisq-network/support/issues

**Comment by mpowacht** [comment]
Thanks, I am trying to sync the SPV state and will get back.

**Comment by chimp1984** [comment]
@mpowacht Did you take the offer when your app was still syncing the BTC blockchain?

**Comment by mpowacht** [comment]
SPV is now synced without any errors. I'll try taking an offer today. I haven't taken an offer while the blockchain was  syncing.

**Comment by mpowacht** [comment]
Took an offer without any problems.

**Comment by mpowacht** [comment]
> @mpowacht Did you take the offer when your app was still syncing the BTC blockchain?

Hi there, I now recall that the syncing process (syncing indicated in bottom status bar) was incomplete while taking the offer. I also seem to recall that syncing was actually always in progress and never completed.  So deleting SPV and re-sync was a good remedy.

**Comment by chimp1984** [comment]
I opened a issue to fix that problem: https://github.com/bisq-network/bisq/issues/4727
