### ISSUE TITLE
Dynamic BTC transaction fees

### ISSUE THREAD

**Issue by AlexMinty** [bisq-network/bisq#472]
Utilise dynamic transaction fees like electrum wallet. Possibly from https://bitcoinfees.21.co/#delay

Current 10 satoshi default will take a very long time, if ever, to transact. Newbies will be unaware of this setting.

**Comment by ManfredKarrer** [comment]
I increased user defined default fee to 2000 sat./bytes. For the fees at the trade process it is more complex as the fee need to be the same for both users. But will try to improve that in future.

**Comment by ManfredKarrer** [comment]
I added a feature to give the user option how much fee (or better estimated time to get a confirmation) he want to pay at withdrawal to the roadmap. Though there are many more hi-prio tasks so will prob. not be added soon. Will close here for now.
