### ISSUE TITLE
Updates to 'Edit Offer' to allow for change of market and payment method

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#4720]
### Description

Currently on Bisq when editing on an offer you are able to edit the following:

- Deviation from market price
- Fixed price for BTC

It would be useful for those making offers on Bisq if they could also edit the following:

- Market (eg XMR/BTC, EUR BTC etc)
- Payment method

Here are some practical use cases I see as reasons for enabling editing of the market and payment method as follows:

- New Swiss Bisq user trying to sell 0.01 BTC for Swiss Francs using a National Bank will likely not get any trades due to low liquidity. If they can edit the offer to instead sell 0.01 BTC for Euros using SEPA they would likely be able to complete a trade. The option currently is they cancel the trade and lose mining and trade fees.

- EU based Bisq user with multiple offers to sell 0.01 BTC using Revolut. User receives a 'proof of funds request'. Rather than cancel all their offers, losing mining and trade fees, they could edit them to sell using their SEPA account.

- US based trader with offer to buy 0.25 BTC for cash gets no offers and wants to edit offer to US Postal Money Order.

- UK based trader with 3 offers to buy 0.25 BTC with Faster Payments. One offer is taken, bank asks buyer to provide more information about seller. Buyer refuses. Bank places funds on hold. Buyer is frustrated and would like to edit offer to one of their other banks without losing out on trader fees / mining fees.  

- Bisq contributor with 0.15 BTC tied up in deposit for selling 1 BTC's worth of BSQ wants to take advantage of a drop in the price of BTC and move their offer of buy BTC from BSQ/BTC to a Fiat/BTC market. It would be good if they did not have to pay new trade and miner fees, especially if the mempool is busy.

It would be great if both changes could be implemented. In terms of use cases I think the editing of 'Payment Method' would get much more use than the editing of 'Market' 

Being able to edit more aspects of the offer would make users be more engaged in the process.  It would also likely lead to less 'set and forget' types of offers that @sqrrm and @chimp1984 have commented on Keybase and here as adding unnecessarily to the resources Bisq requires. 

In summary I see the proposed updates as:

- Improving user experience for Bisq trade makers
- Decreasing the possibility of lost fees for Bisq trade makers
- Increasing the right sort of liquidity (that which is taken quickly)
- Decreasing the number of trades on Bisq which never get taken and therefore requiring less resources  
- Encouraging more people to put on maker offers adding more liquidity as a whole

#### Version

1.4.2

### Steps to reproduce

Bisq client > Portfolio > 'click on the pencil next to the offer'

### Current 'Edit offer' section

![edit offer 1](https://user-images.githubusercontent.com/66367547/97379507-e338c980-18bc-11eb-9ca7-bd19481215f5.png)

### Proposed 'Edit offer' section

![edit offer 2](https://user-images.githubusercontent.com/66367547/97379537-ef248b80-18bc-11eb-898e-ccc6541484e2.png)

**Comment by chimp1984** [comment]
I agree. Only restriction we have for technical/conceptual reasons is that we cannot change the BTC amount as the reserved BTC are already held in the wallet and as we use the same offer ID that would cause problems. Such a change would render the edit offer feature to a larter engineering effort and as trade fee are derived from the BTC amount there is a conecptual problem how to deal with it (e.g. create offer with min. amount/fee then change amount to save fee). 

@jmacxx I know you have already a lot on your table, but if you are interested in that, would be great to get it implemented.

**Comment by ghost** [comment]
I have to say, this is an amazing suggestion!!  Very useful feature, thanks @pazza83 :heart:

**Comment by pazza83** [comment]
Thanks, Looking forward to it being implemented so I can edit some offers and save fees. Especially with the mempool being so busy at the moment!

**Comment by chimp1984** [comment]
@pazza83 if you are familiar with running from source cod you can build the branch (or master once its merged) and benefit from the feature even before its released.

**Comment by pazza83** [comment]
@chimp1984 Thanks I am not sure how to do it. Will give it a try though and test it out. Have you a link you could point me too?

**Comment by chimp1984** [comment]
https://github.com/bisq-network/bisq/blob/master/docs/build.md but is more developer focussed.

@m52go Do we have a more non-delveloper orientated doc about how to run from source? If not do you think it would make sense to create such?

**Comment by m52go** [comment]
No, will look into it. The developer guide is quite nice and concise but I guess it would be good to include the other "little" things like installing Java and running a testing environment on regtest.

**Comment by chimp1984** [comment]
Its more for users to run Bisq mainnet not for testing with regtest. A full install script starting installing java, git etc. would be good...
