### ISSUE TITLE
Improve 'Receive payement' screen

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#4721]
### Description

The way how we present new unused addresses, specially in the context of the new native segwit addresses leads to confusion. We should rething the way how it is done now.

Currently we only allow to create a new address if there is no unused address in the list. I assume when the user has an ununsed legacy address they cannot create a new Bech32 address. 
Even if a new Bech32 address was created it can be that it is overlooked in case there are several unused addresses.
The reason why there can be several unused addresses is when an offer got canceled the reserved address for that offer gets available again and is marked as unused. 
There have been requests in the past that we should not restrict to only 1 new unused addresses as there might be use-cases where a user wants to create multiple addresses to give it to some senders. the popup displayed when unused addresses are available should be replaced by a info popup telling the user that it is better to use one of the already created addresses (or we remove it - too many popups/information anyway). To create too many addresses will slow down BitcoinJ wallet and lead to a Bloomfilter update when a new batch of addresses gets created (I guess its every 100 addresses). Thats why we tried to keep the number of addresses low (but that was back in times when we used the public Bitcoin network for BitcoinJ which had more severe privacy implications from Bloomfilters).  

So I think the whole way how it is done now requires a re-design (UI/UX not BTC wallet internal).

**Comment by oscarguindzberg** [comment]
Currently, you are allowed to create a new address if you don't have any unused address of that type. E.g. if you just have an unused legacy address you can create a segwit address.

When doing the UI/UX redesign it is important to keep in mind there is a  problem with unlimited unused addresses. There is a scenario where the wallet is not aware of funds it received:
- The user generates 101 unused addresses. 
- She does not use the first 100.
- She sends funds to address 101 and the tx is confirmed
- User recovers her wallet with recover from seed.
- bitcoinj pre-generates 100 addresses and includes them in the bloom filter.
- The wallet is not aware of the tx sent to address 101.

**Comment by chimp1984** [comment]
@oscarguindzberg A thanks, I was not aware of that issue. 

So it still important then to keep some limit. But we can stretch the limit so that normal users wont reach it (e.g. allow to create max new 10 unused addresses).

**Comment by Conza88** [comment]
This got me confused lately. 
Had unused in RECEIEVE, but all 1... addresses.
Wanted to send bech32 etc. 

Wasn't clear at all, and decided to avoid Bisq wallet altogether.
