### ISSUE TITLE
Don't allow trade start if BitcoinJ is not fully synced

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#4727]
### Description

While BitcoinJ is syncing the lock time would be incorrectly calculated leading to a failed trade. Currently users could take and offer or offers of a maker can be taken during sync.  

We should add for both maker and taker side the check that BitcoinJ need to be synced. The sync of a new block (veyry short time) can be ignored as the locktime has some tolerance built it to not fail in case both traders have a small difference of the block height.

Case of a user who had that problem:
https://github.com/bisq-network/bisq/issues/4707#issuecomment-718417697

**Comment by mpowacht** [comment]
@chimp1984  thanks and kudos to this great community and this amazing project !! Bisq is incredible!

**Comment by mpowacht** [comment]
@chimp1984 Thanks!!
