### ISSUE TITLE
java.lang.nullpointerexception

### ISSUE THREAD

**Issue by othexmr** [bisq-network/bisq#473]
I got a java.lang.nullpointerexception on startup of Bitsquare

Mai-29 14:59:44.638 [JavaFX Application Thread] INFO  i.b.a.BitsquareApp: Log files under: xxx 
Mai-29 14:59:44.746 [JavaFX Application Thread] INFO  i.b.app.Version: Version{VERSION=0.4.8, P2P_NETWORK_VERSION=4, LOCAL_DB_VERSION=4, TRADE_PROTOCOL_VERSION=1, BTC_NETWORK_ID=0, getP2PNetworkId()=0} 
Mai-29 14:59:44.746 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.name: Mac OS X 
Mai-29 14:59:44.746 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.version: 10.11.5 
Mai-29 14:59:44.747 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.arch: x86_64 
Mai-29 14:59:44.747 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: sun.arch.data.model: 64 
Mai-29 14:59:44.747 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JRE: 1.8.0_92-b14 (Oracle Corporation) 
Mai-29 14:59:44.747 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JVM: 25.92-b14 (Java HotSpot(TM) 64-Bit Server VM) 
Mai-29 15:00:09.689 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
Mai-29 15:00:09.689 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= null 
Mai-29 15:00:38.479 [Thread-21] INFO  c.m.t.t.OnionProxyManagerEventHandler: Hidden service vocl7qbbbggv3owc.onion:9999 published. 
Mai-29 15:01:09.602 [NioClientManager] WARN  o.b.n.NioClientManager: Failed to connect with exception: java.nio.channels.ClosedChannelException: null 
Mai-29 15:01:09.605 [NioClientManager] WARN  o.b.n.NioClientManager: Failed to connect with exception: java.nio.channels.ClosedChannelException: null

**Comment by ManfredKarrer** [comment]
Thanks for reporting! In the logs is unfortunately no stacktrace. DO you remember at which screen or activity that happened?

**Comment by othexmr** [comment]
Hey Manfred, this happened when i started Bitsquare, latests tagged release on OSX El Capitan.

**Comment by ManfredKarrer** [comment]
Did it continue to start or caused it a crash?

**Comment by ghost** [comment]
I got the same error after adding a national currency account and clicking on the Buy BTC menu button. When I closed the prompt the application was frozen. I am using Mac OSX Yosemite.

**Comment by ManfredKarrer** [comment]
@adriaanjoubert Could u send me the log files (account/backup -> open app dir button)?

**Comment by ManfredKarrer** [comment]
@adriaanjoubert I tried to reproduce the issue but could not. If you can send me the log files it would be easier to me to find the source for the null pointer. I fixed a few cases where null pointers happened, so might be that it is already fixed. Will close as long I cannot reproduce it.
