### ISSUE TITLE
Document how to build bisq without gradle.

### ISSUE THREAD

**Issue by crocket** [bisq-network/bisq#4730]
Gentoo Linux doesn't allow build system to access network. So, gradle will not have access to network during build process.
It can't fetch dependencies.

This means I have to figure out how to build bisq manually or write a script for building bisq with javac.

I don't really understand gradle enough to reverse-engineer build.gradle.
How can I do that?

**Comment by bjacquin** [comment]
Outside of this, while version of each individual dependencies are specified in `build.gradle`, none of dependencies packages checksum are stored in bisq git repo, making the overall build vulnerable to supply chain attack.

See https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610 for a bit of literature around it.


Edit: checksums are actually stored in `gradle/witness/gradle-witness.gradle`

**Comment by bjacquin** [comment]
However, I concur with @crocket here, it would be a good thing for packager to be able to download all the needed archives using their own respective process and let gradle use a local predefined directory to pick each pom/jar so the build can be made in a network restrict sandbox. (Especially when `gradle/witness/gradle-witness.gradle` only store SHA1 vulnerable to pre-image attack)

**Comment by cd2357** [comment]
> Especially when `gradle/witness/gradle-witness.gradle` only store SHA1 vulnerable to pre-image attack

It's actually SHA-256 (see #5372).

> it would be a good thing for packager to be able to download all the needed archives using their own respective process and let gradle use a local predefined directory to pick each pom/jar so the build can be made in a network restrict sandbox

Something like that might be possible using this approach: https://stackoverflow.com/questions/7016226/how-to-configure-gradle-to-use-a-local-repository-only-for-certain-dependency-gr

However this is a very esoteric sort of setup with its own set of challenges. It might be worth enabling network access for the build process, or just building on a separate dedicated VM, if necessary.
