### ISSUE TITLE
BTC seller is unable to confirm payment

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#4748]
### Description

BTC seller gets stuck on step 2 `Wait until payment has started` and is unable to confirm the receipt of the payment after the BTC buyer has confirmed that they started the payment.

#### Version

Bisq v.1.4.2

### Steps to reproduce

Unable to reproduce.

### Expected behaviour

After the BTC buyer clicks "Payment Started" both traders should move to step 3 in the **Trade Process**, **Wait until payment arrived** for BTC buyer and **Confirm payment received** for BTC seller.
### Actual behaviour

BTC seller remains at step **2 - Wait until payment has started**

**Comment by huey735** [comment]
@wiz @Bisq-knight @leo816

**Comment by ripcurlx** [comment]
@chimp1984 @sqrrm Could this be related to some changes introduced in v1.4.2?

**Comment by sqrrm** [comment]
Possible, the button to refresh was changed to do automatic requests so something in this area was changed. @huey735 do you have logs from the users? Could you send them to me on keybase?

**Comment by chimp1984** [comment]
Yes we removed the refresh button by a resend procesudure if no ack msg was received. If the user can provide logs we might find out more. The ack is only sent after the msg was processed, but maybe there was a bug in the processing....

**Comment by lugarc** [comment]
I have the same problem described here, with funds stuck since October 30th.

**Comment by chimp1984** [comment]
@lcgar If you are on keybase can you PM me (i have same username there) your log files and the trade ID so I can investigate the issue?

**Comment by lugarc** [comment]
@chimp1984 Okay, as soon as I can.

**Comment by ripcurlx** [comment]
@chimp1984 @sqrrm As this seems to be a problem, based on the support requests. Wouldn't it be an idea to add back the manual option to refresh the trade state, beside having the automated re-send in the background? I think it would be good to get this into the v1.5.0 release as well.

**Comment by chimp1984** [comment]
@lcgar Would be great if you can send me the logs to investigate so we can fix it for upcoming release!

**Comment by chimp1984** [comment]
@wiz @Bisq-knight @leo816 @huey735 How many such cases have happened since last release? Please request the logs from the traders, so we can find out the reason for the issue.

**Comment by chimp1984** [comment]
> @chimp1984 @sqrrm As this seems to be a problem, based on the support requests. Wouldn't it be an idea to add back the manual option to refresh the trade state, beside having the automated re-send in the background? I think it would be good to get this into the v1.5.0 release as well.

Not a strong opinion here but would prefer to investigate first to find out the reason. Adding patches makes all more complex and do not solve the underlying problem, e.g. the real problem will likely not be fixed but ignored then... But if @sqrrm wants to add it again I am ok with it. I am busy with another issues I discovered yesterday which needs to get fixed for 1.5.0 (mailbox msg issues)...

**Comment by leo816** [comment]
> @wiz @Bisq-knight @leo816 @huey735 How many such cases have happened since last release? Please request the logs from the traders, so we can find out the reason for the issue.

I would say 20-30% (about 7 per cycle) of mediation tickets are just from users not being able to confirm.  @wiz @Bisq-knight @huey735 did you experience the same?

**Comment by sqrrm** [comment]
After discussing with @chimp1984 I don't think we can add the the button again in a simple matter. The button worked in some sense, but it also caused some other issues with the trade protocol that I wasn't aware of while implementing the button originally.

**Comment by chimp1984** [comment]
@wiz @Bisq-knight @leo816 @huey735 
Can you send me the logs of those cases so we can find out what causes it? Please if you observe such obvious errors push us devs harder so we can fix those issues and make Bisq better. I was totally unaware of that issues which seems to be around since weeks.

**Comment by Bisq-knight** [comment]
> @wiz @Bisq-knight @leo816 @huey735 How many such cases have happened since last release? Please request the logs from the traders, so we can find out the reason for the issue.

Quite a lot, the majority of cases in the last week or so were related to this issue. I'm asking traders to send the logs via keybase, not all do. But I have a treasure trove here. I'll share with you shortly, I'm just gonna take a step back to organise them and write proper notes to the files

**Comment by chimp1984** [comment]
@Bisq-knight can u send me at least some, so i can start investigating. We are already late in the testing phase, so we should get that fixes soon...

**Comment by chimp1984** [comment]
@wiz @Bisq-knight @leo816 @huey735 Would be great if any of you could send me the logs.

**Comment by sunnytoes** [comment]
I can also report this problem.

**Comment by lugarc** [comment]
> @lcgar Would be great if you can send me the logs to investigate so we can fix it for upcoming release!

@chimp1984 My user in keybase is **lugarc** and the sunday 8 I sent you by Keybase my Bisq's log with the described problem.

**Comment by Bisq-knight** [comment]
> @wiz @Bisq-knight @leo816 @huey735 Would be great if any of you could send me the logs.

I'm packaging them now. Will send you on Keybase in a bit

**Comment by cyplo** [comment]
Happy to help, I have multiple trades affected myself :/ happy to send logs, just let me know how :)

**Comment by chimp1984** [comment]
@cyplo Thanks! Are you on keybase? If so can you PM me there the logs? I use same handle as here on GH...

**Comment by cyplo** [comment]
will do a bit later today and will let you know :)

**Comment by polaris1205** [comment]
I got this bug on 11/12 from the buyer's position, issue is still unresolved (meaning my $ was received by seller, but the BTC has not been release). 

It's good to know developers are looking at it, but given that the incidence rate seems to be so high (getting that sense from keybase support chat), is there any consideration to make an announcement to warn users until this is fixed?

**Comment by cyplo** [comment]
@chimp1984 - created a chat on keybase, same username as here

**Comment by chimp1984** [comment]
@polaris1205 This week will be likely the 1.5.0 release with several bug fixes.

**Comment by KainerW** [comment]
Warning users untill this is fixed would have been a great idea. For many this has been the first Bisq experience and it has been terrible for them.

**Comment by myhau** [comment]
I have the same problem (1.5.0 version).

Seller said to me on chat that he's not able to confirm the payment. 

I'm not yet sure which version he has installed.

**Comment by chimp1984** [comment]
@Myhau please get in touch with your mediator (cmd+o opens a mediation ticket)

**Comment by HeadyWook** [comment]
I had a similar issue happen to me. Except I could not find the "Payment started" button. Turned out I had my computer screen zoomed in too much. That is, I changed my computer's settings to display everything bigger (i.e., >100%). If you have done this to your computer settings then the Bisq app will not display properly. If you have changed your display settings to show bigger, set it back to normal and Bisq should display appropriately. While this may not be your exact issue, it was similar enough to mine. I thought it was worth commenting on for troubleshooting sake.

**Comment by Bisq-knight** [comment]
@chimp1984  Did you get enough logs to understand the issue? I summed up the ones I got and the side where the problem originated didn't share the logs with me. Not sure if that's valuable 

I did send you one though of a guy who contacted me even before going to mediation, right when the problem happened.

**Comment by bisqta** [comment]
This just happened to me with version 1.5.4. Trading partner says he is also on version 1.5.4.

**Comment by Renato1478** [comment]
Just happened here in version 1.9.17... I'm opening mediation as a workaround.
