### ISSUE TITLE
An error occurred at task: ProcessPayDepositRequest

### ISSUE THREAD

**Issue by songproducer** [bisq-network/bisq#475]
An error occurred at task: ProcessPayDepositRequest
Takers tradePrice is outside our market price tolerance.
tradePriceAsFiat=552.36 XMR
offerPriceAsFiat=539.55 XMR

Trade state: PREPARATION

**Comment by songproducer** [comment]
http://imgur.com/yjDQbAd

**Comment by ManfredKarrer** [comment]
Thanks for reporting. There is a check for the max. dtolerance for both users price calculaed based on the actual price feed. It might be that either volatitility was so hight that it triggered that toleranc, or one has had network issues and the price feed was outdated, or one tried to scam (not assuming that).
But in that stat you should not have lost anything (no taker fee is paid). You can check that under funds/transactions.
Will add a better popup msg in the next verison.
If you have already paid the take offer fee please let me know (but should not be that case).

**Comment by songproducer** [comment]
Only the offer fee 0.0005 tx was paid. Transaction has disappeared from open trades as it expired. It's not in history.

**Comment by ManfredKarrer** [comment]
Ah you have been the offerer. Is the offer not visible anymore? It should keep open/available. But that might be a bug. Need to check that...

**Comment by songproducer** [comment]
My mistake, sorry - it's still open.

**Comment by ManfredKarrer** [comment]
Ah good.
