### ISSUE TITLE
No key found for absolute path

### ISSUE THREAD

**Issue by CognitiveDiss** [bisq-network/bisq#4758]
### Description
I had a problem completing a trade yesterday. I had paid EUR and confirmed payment the day before but then received a mediator message, which I assumed the btc seller asked for. I contacted the seller, who thought I initiated the mediator! But the seller confirmed receipt to me of my EUR. I waited assuming delivery but this morning nothing had happened and I though the program (ver 1.3.4 I think) had frozen. I tried to reload it but without success so I downloaded ver. 1.4.2 from the website. No luck. I understand this is probably a wallet issue. Any ideas, please?

### Screenshots

![image](https://user-images.githubusercontent.com/74058624/98379283-af5a6280-2079-11eb-989a-261ccff3c1bb.png)

![image](https://user-images.githubusercontent.com/74058624/98379326-c13c0580-2079-11eb-8ee7-bf83aaf6e846.png)

![image](https://user-images.githubusercontent.com/74058624/98379397-d3b63f00-2079-11eb-9d14-01b45baa20d0.png)

#### Device or machine

OS Mac Catalina 10.15.6

**Comment by ripcurlx** [comment]
@oscarguindzberg Do you have an idea what could cause this issue? It occurred after the user updated to v1.4.2.

**Comment by CognitiveDiss** [comment]
No it started before I updated. I updated because I left it open during the night and it appeared frozen this morning.

**Comment by CognitiveDiss** [comment]
![Skärmavbild 2020-11-06 kl  15 27 33](https://user-images.githubusercontent.com/74058624/98378070-21ca4300-2078-11eb-8fb9-4191b91087fe.png)

**Comment by oscarguindzberg** [comment]
This is probably due to a corrupted wallet file.
I would follow the "standard" procedure to restore the wallet when the user has a trade open.

Probably something like:
- Stop Bisq.
- Do a backup of Bisq data dir (not really needed, but I strongly suggest to do ir)
- Start Bisq in a new data dir. Wait for it to sync
- Do a restore from seed. Restart Bisq when you are asked for it. Wait for it to sync. 
- Shut down Bisq on the new data dir.
- Copy these files from the new data dir to the standard data dir:
  - btc_mainnet/wallet/bisq.spvchain
  - btc_mainnet/wallet/bisq_BSQ.wallet
  - btc_mainnet/wallet/bisq_BTC.wallet
- Start Bisq in the standard dir

**Comment by huey735** [comment]
This did indeed help get past the `No key found for absolute path` error but @CognitiveDiss is still having connection issues when trying to open their standard Bisq client.

**Comment by CognitiveDiss** [comment]
Yes, synchronizing is very slow, gets up to about 5%, then the Tor file delete pop-up appears. Deleting there doesn't help unfortunately.

**Comment by CognitiveDiss** [comment]
![Skärmavbild 2020-11-07 kl  07 49 39](https://user-images.githubusercontent.com/74058624/98434201-2c301f80-2100-11eb-8c9a-09aa1d4833f1.png)
Does this mean something maybe?

**Comment by ghost** [comment]
Its just an informational message saying you've started an SPV resync.  You can close it.  Progress will be indicated on the screen behind it.

**Comment by CognitiveDiss** [comment]
Thanks! I did close it and also the pop-up suggesting deleting Tor files. It's been syncing since then for 12 hours now. We're up to 64%! I'll see what happens, probably tomorrow morning. Praying my BTC stash shows this time!

**Comment by CognitiveDiss** [comment]
Resync completed, so I shut down and restarted. No luck. I got the pop-up to delete Tor files, which I closed, and it's now churning getting nowhere.
![Skärmavbild 2020-11-07 kl  22 11 10](https://user-images.githubusercontent.com/74058624/98451485-7b199b80-2178-11eb-8890-d7dca6cfa209.png)

Anyone got an idea please?

**Comment by CognitiveDiss** [comment]
This is the pop-up 'no key found' which I had to start with. So it looks like the same problem.
![Skärmavbild 2020-11-07 kl  22 14 12](https://user-images.githubusercontent.com/74058624/98451556-4bb75e80-2179-11eb-9296-ec2009412d59.png)

**Comment by ghost** [comment]
I'm pretty sure you are accidentally running an older version of Bisq.  I get the same error as above when running an old version of Bisq - that's because the wallet was upgraded to Segwit in 1.4.2 but older versions of Bisq cannot read the new format.  To check this you can tail or notepad the log file, when Bisq starts it writes a message indicating the version, e.g. `Nov-07 15:50:05.768 [main] INFO  b.c.app.Version: Version{VERSION=1.3.7`  Find your log file [here](https://bisq.wiki/Data_directory#Default_Locations)

**Comment by CognitiveDiss** [comment]
Thanks jmacxx! Huey735 helped me follow Oscar instructions above and after a whole day of syncing I got the original message about 'no key...' Back to square one I thought. But, just in case, I ran what I thought was the new dir as per Oscar's instructions and, without a password, I was in! My btc was there and 2 messages to transfer btc from the 2 transactions to bisq or external wallet. I transferred both to bisq but received no funds, nor my deposits for the transactions. I removed the btc on the account without a problem and surprisingly with no password. Looking at the transactions tabs, I only see the deposit and fee debits for these transactions and it looks like the btc form a third transaction, which I assumed closed on 3 Nov, were also not credited. Very strange.

**Comment by chimp1984** [comment]
> This is probably due to a corrupted wallet file.
> I would follow the "standard" procedure to restore the wallet when the user has a trade open.
> 
> Probably something like:
> 
>     * Stop Bisq.
> 
>     * Do a backup of Bisq data dir (not really needed, but I strongly suggest to do ir)
> 
>     * Start Bisq in a new data dir. Wait for it to sync
> 
>     * Do a restore from seed. Restart Bisq when you are asked for it. Wait for it to sync.
> 
>     * Shut down Bisq on the new data dir.
> 
>     * Copy these files from the new data dir to the standard data dir:
>       
>       * btc_mainnet/wallet/bisq.spvchain
>       * btc_mainnet/wallet/bisq_BSQ.wallet
>       * btc_mainnet/wallet/bisq_BTC.wallet
> 
>     * Start Bisq in the standard dir

The AddressEntryList file in db folder need to be in sync as well. If you dont have open offers or trades, you can delete it (backup first) and it will be recreated based on the wallet.

**Comment by oscarguindzberg** [comment]
I could reproduce the error message by opening a Bisq v1.4.2 datadir with the Bisq v1.3.9 codebase.

Nov-09 20:55:31.156 [JavaFX Application Thread] ERROR b.core.btc.setup.WalletsSetup: Service failure from state: STARTING; failure={} java.lang.IllegalArgumentException: No key found for absolute path M/44H/0H/0H/0/16.
	at org.bitcoinj.crypto.DeterministicHierarchy.get(DeterministicHierarchy.java:89)
	at org.bitcoinj.wallet.DeterministicKeyChain.getKeyByPath(DeterministicKeyChain.java:617)
	at org.bitcoinj.wallet.DeterministicKeyChain.getKeyByPath(DeterministicKeyChain.java:612)
	at org.bitcoinj.wallet.KeyChainGroup.createCurrentKeysMap(KeyChainGroup.java:762)
	at org.bitcoinj.wallet.KeyChainGroup.fromProtobufUnencrypted(KeyChainGroup.java:658)
	at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:477)
	at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:444)
	at bisq.core.btc.setup.WalletConfig.loadWallet(WalletConfig.java:543)
	at bisq.core.btc.setup.WalletConfig.createOrLoadWallet(WalletConfig.java:499)
	at bisq.core.btc.setup.WalletConfig.startUp(WalletConfig.java:380)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.base/java.lang.Thread.run(Thread.java:834)

java.lang.IllegalArgumentException: No key found for absolute path M/44H/0H/0H/0/16.
	at org.bitcoinj.crypto.DeterministicHierarchy.get(DeterministicHierarchy.java:89)
	at org.bitcoinj.wallet.DeterministicKeyChain.getKeyByPath(DeterministicKeyChain.java:617)
	at org.bitcoinj.wallet.DeterministicKeyChain.getKeyByPath(DeterministicKeyChain.java:612)
	at org.bitcoinj.wallet.KeyChainGroup.createCurrentKeysMap(KeyChainGroup.java:762)
	at org.bitcoinj.wallet.KeyChainGroup.fromProtobufUnencrypted(KeyChainGroup.java:658)
	at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:477)
	at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:444)
	at bisq.core.btc.setup.WalletConfig.loadWallet(WalletConfig.java:543)
	at bisq.core.btc.setup.WalletConfig.createOrLoadWallet(WalletConfig.java:499)
	at bisq.core.btc.setup.WalletConfig.startUp(WalletConfig.java:380)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by CognitiveDiss** [comment]
Very happy I'm done. Thanks guys for your suggestions, time, and patience. Now back to buying BTC!
