### ISSUE TITLE
Lost trade fee

### ISSUE THREAD

**Issue by cristinaboga** [bisq-network/bisq#4759]
### Description

Error while taking an offer to sell btc, I lost the fee

#### Version
1.4.2

### Steps to reproduce
find this seller:
tqntwx2girdmfunqiukhah5a4gruh3k5sga4z6aeweumn5yxta663gad.onion:9999
try to take his offer

### Expected behaviour
offer should be open and established

### Actual behaviour
error, fee is stuck cannot be recovered

### Screenshots

![image](https://user-images.githubusercontent.com/49342772/98411580-97cdaa80-2076-11eb-828e-803256b7934b.png)

#### Device or machine

Bisq 1.4.2 on Windows 10

**Comment by cd2357** [comment]
If you have not done so already, please open a fee reimbursement request here: https://github.com/bisq-network/support/issues
