### ISSUE TITLE
Repeated ArrayIndexOutOfBoundsException after idle period

### ISSUE THREAD

**Issue by ivilata** [bisq-network/bisq#476]
While using v0.4.8, after a while of being idle, Bitsquare has started showing errors like this in its log, between 18:43 and 20:30, with no fixed periodicity:

```
de maig-30 18:43:14.777 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
de maig-30 18:43:14.778 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= null 
java.lang.ArrayIndexOutOfBoundsException
```

After closing the error dialog, the app seemed to keep on working.

**Comment by MarcSte** [comment]
The bug keeps reappearing here as well. Like 5 times in the last 5 minutes.

This seems not critical to any functions.

**Comment by ManfredKarrer** [comment]
Same as https://github.com/bitsquare/bitsquare/issues/421. Close here as it will be fixed in next version.
