### ISSUE TITLE
Bisq locks up when trying to take an offer

### ISSUE THREAD

**Issue by daveblack1** [bisq-network/bisq#4760]
### Description

Bisq stalls on "Take offer in progress..." when I try to take an offer. Prior to this I receive an error saying, "Warning: You cannot take this offer because you already took it earlier. It could be your previous take offer resulted in a failed trade. I am unable to leave this screen and have to forcibly close Bisq. It shows I have 1 bitcoin network peer and 12 Bisq network peers. 

I previously had this error and had to reset my SPV:
https://github.com/bisq-network/bisq/issues/4707

#### Version

v1.4.2

### Steps to reproduce

Try to purchase from 2pcrnibhco3gzwtu.onion:9999. Fail.

### Expected behaviour

Complete purchase

### Actual behaviour

Bisq locks up

### Screenshots

![image](https://user-images.githubusercontent.com/74085629/98432049-9efdb400-2088-11eb-8101-8b584e933e4e.png)

#### Device or machine

Windows 

#### Additional info

N/A

**Comment by invertedbobb** [comment]
Got the same issue earlier today.
Tried to take an offer, got a time-out. Tried to take it again but unable to.
Noticed the trade was in my active trade list indicated as failed (no taker tx, no deposit tx).
Decided to move it to the failed trades list, hoping it would resolve the issue. It did not.

Restarting Bisq doesn't help.
This was with a different peer than mentioned by OP.

**Comment by ghost** [comment]
Bisq does not let you take an offer if it is already stored in the list of trades including failed trades.  This is an edge case (take offer, time out) which should never happen (you'd expect the counterparty to also have a failed trade therefore no open offer  but as can be seen this has happened to two users on different open offers already).  

I'd prefer @chimp1984 to weigh in with an opinion on whether this needs a fix.

**Comment by chimp1984** [comment]
Yes, we added that to avoid those bugs with repeated failed take-offer attempts. The offer ID is the trade ID, if you could take an offer several times (if it failes first and get moved to failed trades) we get problems as the trade ID should be unique. So there have been several areas where that situation can lead to bugs, so we decided to disallow take an offer again once its failed. Better than running into bugs when taking again.  Engineering effort to change all that so support all those potential error situations would be too big to justify the use case.

**Comment by bsmate** [comment]
I had this same thing happen.

Do I have to do anything to this transaction that is in open trades with the red exclamation? It can be moved to failed trades. Is this affecting a second trade with the same seller? He is no releasing.

**Comment by chimp1984** [comment]
If no deposit tx has been created you can move it to failed trades. It does not affect other trades, u just cannot take the same offer again if the offer would be still there.

**Comment by menkaur** [comment]
having the same issue
