### ISSUE TITLE
Delayed payout transaction is missing

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#4762]
### Description
Bisq failed to create the delayed payout transaction needed to send funds to Arbitration.

#### Version
1.4.2

### Steps to reproduce
Unable to reproduce

### Expected behaviour
Bisq should create a delayed payout transaction sending funds to the Arbitrator address along with the deposit transaction.

### Actual behaviour
Bisq failed to create the delayed payout transaction needed to send funds to Arbitration.

### Screenshots

<img width="957" alt="btcBuyerTaker-errorMessage" src="https://user-images.githubusercontent.com/44140017/98450377-43890000-2134-11eb-9c97-9fdc2d29f249.PNG">

<img width="960" alt="btcBuyerTaker-tradeDetails" src="https://user-images.githubusercontent.com/44140017/98450359-15a3bb80-2134-11eb-9553-719271f2c3aa.PNG">

#### Device or machine
Windows 10

**Comment by chimp1984** [comment]
As stated in the popup, instruct both traders to open a mediation and accept the suggested payout so that the trade amount goes back to seller (assume buyer has not send funds as stated in the popup). That way the trade can be closed without further risk. Please request the log files from both traders and PM me.

**Comment by huey735** [comment]
The Deposit transaction also wasn't successfully created despite the message. So the trade failed in the end. I'll send you the logs.

**Comment by chimp1984** [comment]
Was the trader the seller or buyer? It would be helpful if users dont blur so much data. Most data is not relevant regarding privacy...
