### ISSUE TITLE
Auto self sign feature not working

### ISSUE THREAD

**Issue by viperperidot** [bisq-network/bisq#4763]
### Description

I was told in support that if you create a payment account with the same account owner name as a different signed account it will be automatically signed when it is created. I tried this out and it appears that the auto self sign feature is not working right now. I created another payment account with the same owner name and it did not get signed.
#### Version
1.4.2

### Steps to reproduce
1. Create payment account with same account owner name as different signed account
2. The new account gets created but is not signed

### Expected behaviour
I think the new account should be self signed from what I have heard.

### Actual behaviour
It does not get signed.

#### Device or machine
Linux, Ubuntu

**Comment by ripcurlx** [comment]
@viperperidot What payment method account are you trying to get self signed?

The pre-condition to make this work are:
- you need at least on signed account that is able to sign other accounts
- account id of the signed account and the newly created account need to match exactly (e.g Name for SEPA accounts)

**Comment by viperperidot** [comment]
@ripcurlx I have a signed SEPA account that I am trying to get to sign a SEPA Instant and National bank account. I have double checked that the 'Account owner full name' field matches for the accounts. Would it be possible to have a different way to enable the auto-sign feature like a button in the GUI so that it can be more definitive than the current method?

Does the account that is signed have to also be fully aged in order to self-sign another account?

**Comment by MwithM** [comment]
> Does the account that is signed have to also be fully aged in order to self-sign another account?

It has to be able to sign other accounts, so yes. At least 30 days since signing.

**Comment by ripcurlx** [comment]
> @ripcurlx I have a signed SEPA account that I am trying to get to sign a SEPA Instant and National bank account. I have double checked that the 'Account owner full name' field matches for the accounts. Would it be possible to have a different way to enable the auto-sign feature like a button in the GUI so that it can be more definitive than the current method?
> 
> Does the account that is signed have to also be fully aged in order to self-sign another account?

I checked the owner id of SEPA and National bank account and they both use the holder name as the owner id, so it should be possible to self sign your other account. As @MwithM mentioned is your account that is signed already fully aged and able to sign other accounts? That is a pre-condition as I mentioned above.

**Comment by viperperidot** [comment]
Ok sorry about that, I didn't realize that the account had to be 30 days old to self-sign. I will wait the time period and then try again.

Thanks
