### ISSUE TITLE
100%CPU on ubu 14.04 when funding trade (v.0.4.8)

### ISSUE THREAD

**Issue by themighty1** [bisq-network/bisq#477]
With Sell BTC -> Take offer tab open, the cursor is blinking and CPU is near 100% (the Waiting for funds circle is spinning)
When I switch to Buy BTC menu, the CPU goes to normal, when switching back to Sell BTC, the spike happens again.
The log doesnt show any info when I clink to and from the Sell BTC menu when the spike happens.

**Comment by ManfredKarrer** [comment]
The rotating spinner is unfortunately pretty cpu intense (its a badly implemened java component), but 100% should not be reached, on my 7 years old imac its about 10% when the spinner is active. Maybe your graphic card has issues with the rendering (or gc rendering is not working in your setup and it gets rendered by the cpu?). Will try to replace that crappy component soon...

**Comment by themighty1** [comment]
Very likely. Im running bitsquare inside virtualbox.

**Comment by ManfredKarrer** [comment]
In the next release I don't use the animated spinner anymore, so that issue should be resolved.
