### ISSUE TITLE
Lost trade fee

### ISSUE THREAD

**Issue by Baiskey** [bisq-network/bisq#4770]
### Description

Error while taking an offer to sell btc, I lost the fee

#### Version

v.1.4.2

### Steps to reproduce

find this seller: 6jxwjzla2vi5mrgq.onion:9999
try to take his offer
after that you will be notified that some problem occured and you lost your deposit fee

### Expected behaviour

buy offer is taken without problems

### Actual behaviour

buy offer was taken with problems, I neither can finish my transaction nor get back my deposit fee

### Screenshots

![image](https://user-images.githubusercontent.com/25394185/98552544-de9de900-229e-11eb-89ca-360fb288035b.png)

#### Device or machine

macOS 10.15.7

**Comment by Bayernatoor** [comment]
Hey, this will happen at times where the deposit transaction fails. No funds are lost except for the fees. 

You can request a reimbursement here:
https://github.com/bisq-network/support/issues


Feel free to look at other issues there for guidance!

**Comment by cd2357** [comment]
If not done so already, please open a reimbursement request as per the comment above.
