### ISSUE TITLE
[v1.5.0] Translations for simplified account limits have to be adapted

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#4776]
We need to adapt following translations keys to match the new simplified account limits:
- [ ] payment.limits.info
<img width="1268" alt="Bildschirmfoto 2020-11-10 um 09 18 50" src="https://user-images.githubusercontent.com/170962/98648468-a0ec9f00-2336-11eb-880c-6910d9971879.png">

- [ ] payment.limits.info.withSigning
![Bildschirmfoto 2020-11-10 um 09 11 27](https://user-images.githubusercontent.com/170962/98648505-ab0e9d80-2336-11eb-8b4a-f79e77314549.png)

**Comment by ripcurlx** [comment]
@m52go Could you have a look at the translations above? Thanks!

**Comment by cd2357** [comment]
Fixed with #4783
