### ISSUE TITLE
Allow direct conversion between Cryptocurrencies

### ISSUE THREAD

**Issue by Nutomic** [bisq-network/bisq#478]
Assuming I want to sell my Ether for Dash. Right now I would have to sell the Ether for Bitcoin, and then use the Bitcoin to buy Dash. It would be cool if I could do a direct conversion between altcoins instead.

The same goes for conversion between fiat and altcoins.

**Comment by ManfredKarrer** [comment]
Yes I agree that would be cool, but unfortunately it is a lot of engineering effort and it would not scale for many altcoins. Beside that the altcoin need to support MultiSig which is not widely supported by altcoins which are not clones of Bitcoin (which are usually the interesting ones).
In future we might support direct excahnge for a few top altcoins but too much other work need to be done first...

**Comment by ManfredKarrer** [comment]
I close it as it is not planned for the near future (though on the future roadmap)

**Comment by Nutomic** [comment]
Why are you closing the issue then? I think it's better to keep issues like this open so other people can find them easier.

But of course it's your project and you can do what you want ;)

**Comment by ManfredKarrer** [comment]
I see Github issues better used for bugs and work packages rather than feature requests and future roadmap. At least for me it gets hard to keep overview if there 100s of open issues....
