### ISSUE TITLE
BHHZ34I - Cannot Accept Proposed Resolution due to Deposit TX ID = N/A

### ISSUE THREAD

**Issue by jeforson** [bisq-network/bisq#4811]
BHHZ34I - Cannot Accept Proposed Resolution due to Deposit TX ID = N/A
Leo816 is the mediator, and suggested a resolution due to both sides having issues with the trade.  If I click on "View Proposed Resolution" button, I get a pop-up error that says "The deposit transaction is null. You can move the trade to failed trades."  However, I have no option to move to failed trades because there is no red box with an arrow to the side of the trade (as i've seen before).

Attempted SPV reboot about 3 times now, and same result.

1.4.2

**Comment by chimp1984** [comment]
@jeforson Can you PM me the logs files and a screenshot of the trade details + all tx IDs in keybase (same user name).

**Comment by chimp1984** [comment]
The deposit tx was not created.
@jeforson Can you close the case.
