### ISSUE TITLE
Java heap error

### ISSUE THREAD

**Issue by microlancer** [bisq-network/bisq#4812]
### Description

Bisq crashed due to Java heap error

#### Version

1.4.2

### Steps to reproduce

Not sure, but Bisq was running for several days.

### Expected behaviour

No heap error

### Actual behaviour

Heap error

### Screenshots

Forgot to take a screenshot, sorry.

#### Device or machine

Debian Linux

#### Additional info

Attached bisq.log

**Comment by microlancer** [comment]
[bisq.log](https://github.com/bisq-network/bisq/files/5544205/bisq.log)

**Comment by cd2357** [comment]
Should be fixed in the most recent release (v1.6.4) which brings several UI performance improvements and generally reduces system resource consumption. Please try it out and let us know if it's still an issue for you.
