### ISSUE TITLE
Remove FAIR price feed

### ISSUE THREAD

**Issue by MwithM** [bisq-network/bisq#4815]
### Description

Feed for FAIR/BTC price is too different from the market price at Bisq, and FAIR users can't put offers as they're considered spam because they're over 50% difference.

### Actual behaviour

Faircoin traders can't place offers at desired price.

### Screenshots

![Screenshot from 2020-11-16 20-31-06](https://user-images.githubusercontent.com/50149324/99363057-8ecdac00-28b4-11eb-8b8f-1d59f9e56e4a.png)

### Aditional info

The fix for this I think it's to remove the price feed (Huobi) for FAIR and let only fixed price offers. Huobi volume for this coin is tiny anyway.

**Comment by wiz** [comment]
@cd2357 can you look into this
