### ISSUE TITLE
Error when creating new trade

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#482]
I just tried to set up a trade offer to sell BTC for ETH. When I hit accept, there was some sort of network timeout error that told me to "try restarting the application" and that "no coin has left my wallet yet", but when I restarted the app I saw that the coin had indeed left my wallet. I've been trying for hours to figure this out and get my coin back but there seems to be no way. That's a $100 investment down the drain!

Here's the transaction: https://blockchain.info/address/13myXPj1wnyYmu4F9mNHb55v99Hx4bTFkB. My designated Bitsquare address is the 1KPJEqXfEqPHLJ58Ge5Subi8McZBG2XVSo and the receiver must be the address that it tried to send to.

There are no open trades/offers/history listed in my Bitsquare wallet and my funds are .001 BTC.

PLEASE HELP!

Can someone please reassure me that it will eventually post and/or refund me? Can this be fixed, not just for me but for the long term as well?

**Comment by ManfredKarrer** [comment]
The receiving address (13myXPj1wnyYmu4F9mNHb55v99Hx4bTFkB) is an address of your wallet, so now worry, the funds are still there. Seems to be an UI bug (as the offer publishing failed due a timeout but the offer got actually published) is preventing the display of the correct balance. 
You can open an emergency withdrawal tool by clicking cmd+e (or ctrl+e). There you can empty your whole local wallet to any external address. There the 0.1702 BTC should be visible.
After you have done that, I would recommend to clean your data directory (assuming you dont have open offer, trades or disputes). You can find the data dir under account/backup (button to open data dir).

**Comment by ghost** [comment]
Thank you so much! Much faith restored in the Bitsquare software. Was very afraid that my coin was gone. Everything is working smoothly now.

**Comment by ManfredKarrer** [comment]
Good to hear :-)
