### ISSUE TITLE
Markets API: only display actively traded assets / markets

### ISSUE THREAD

**Issue by wiz** [bisq-network/bisq#4826]
Currently when bisq is launched with `--dumpStatistics=true` we output a `crypto_currency_list.json` and `fiat_currency_list.json` which is what is served from the Markets API at https://bisq.markets/api/markets

However, this is a very large list mostly full of de-listed coins that were never even traded on Bisq, or fiat currencies that aren't actively traded on Bisq. Many API users query every asset on the list every few minutes, which causes a huge load on the server.

Can you please create new files of only actively traded crypto and fiat assets? 
<img width="503" alt="スクリーンショット 2020-11-19 23 59 33" src="https://user-images.githubusercontent.com/232186/99762128-25130380-2b3b-11eb-90ef-1d410f159541.png">

**Comment by wiz** [comment]
@jmacxx can you look into this

**Comment by ghost** [comment]
I'm assuming that an asset traded within the past 365 days is active.  That would produce lists with ~24 fiat and ~24 altcoins.

Or would you prefer a narrower definition, e.g. 1 month, or 1 day?

**Comment by wiz** [comment]
Thanks, that's probably fine and we can always tweak it in the future if necessary
