### ISSUE TITLE
Could not decrypt bytes

### ISSUE THREAD

**Issue by polaris1205** [bisq-network/bisq#4832]
### Description

Cannot get my private keys when I go to ctrl+j, and check the box "include private keys"
#### Version

1.4.2
### Steps to reproduce

ctrl+j, and check the box "include private keys"
### Expected behaviour

Private keys would be shown.
### Actual behaviour

Error message pops up (see screenshot)
### Screenshots

![Capture](https://user-images.githubusercontent.com/66457627/99863754-9ec3e500-2b6d-11eb-80fa-f18c35e449cc.JPG)

#### Device or machine

HP-Envy-15 2040nr (2012)
Windows 7

#### Additional info

[bisq.log](https://github.com/bisq-network/bisq/files/5576803/bisq.log)

**Comment by huey735** [comment]
I believe you have a password to your wallet. You may need to go to Account and unlock the wallet before being able to check `include private keys`.

**Comment by polaris1205** [comment]
After removing the password, I got a different error message: "java.lang.NullPointerException"

![Capture](https://user-images.githubusercontent.com/66457627/99891819-237d3480-2c3c-11eb-9d46-ff5f0f9803cd.JPG)

[bisq.log](https://github.com/bisq-network/bisq/files/5578786/bisq.log)

**Comment by polaris1205** [comment]
Found a work-around. If you delete the wallet file, then restore that same wallet from the seed within BISQ, the bug goes away. Not sure why, but it does solve the issue.
