### ISSUE TITLE
Fix various 'account management' usability issues in the Bisq client to optimize for traders with multiple fiat and altcoin accounts

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#4837]
### Description

When a user creates multiple fiat or altcoin accounts it creates usability problems. 

Bisq could make a the proposed changes below to allow traders to optimize their fiat or altcoin accounts for increased usability. 

This would increase usability, facilitating traders to add more accounts to the platform and and in turn has a positive impact on liquidity. The more multiple fiat or altcoin accounts someone has the more options they have to trade.

I am hoping these suggestions are all low hanging apples :apple::apple::apple:

#### Version

1.4.2

### Examples and suggestions

***

#### National currency account screen

![National currency account page](https://user-images.githubusercontent.com/66367547/99932444-fde14f80-2d4f-11eb-8de1-6ed40f9cfe00.png)

Switching being national currency accounts becomes unusable/difficult when the account selected has multiple lines of information.

`Suggestion - There is lots of space on the right. I would suggesting using a wo column layout (account info on the right).
`
***

#### Select trading account - in Buy / Sell A

![buy and sell](https://user-images.githubusercontent.com/66367547/99932567-5add0580-2d50-11eb-9e97-a3c07148ea23.png)

The trading account field is too short for payment account names.

`Suggestion - Treble the size of the field (you can see from the image below, even doubling it would be too short for Revolut)
`

***

#### Select trading account - in Buy / Sell B

![select trading account](https://user-images.githubusercontent.com/66367547/99932698-c1622380-2d50-11eb-90bb-91dcd20fa3b2.png)

If you have more than a scrollable window of account types this field becomes messy quickly.

`Suggestion - alphabetize list. It would also be good if the client discounted payment options based on selected currency. For example in the list above only two of the account types shown is able to make / take offers of the currency selected 
`

***

#### Manage accounts

![manage accounts](https://user-images.githubusercontent.com/66367547/99932891-5533ef80-2d51-11eb-8e11-5bbd85a0dcaf.png)

Fiat and altcoin accounts accounts get messy when more than a scrollable windows worth of accounts are added. 

`Suggestion - alphabetize list. I would also add 25% to the field width. You can see Revolut being cut off again.
`

***

#### Allow renaming of 'account name' field

![selected account](https://user-images.githubusercontent.com/66367547/99932979-95936d80-2d51-11eb-9c8c-61bb4ad85a2b.png)

Traders are unable to edit the 'account name' field. NB: The account name field is the local nickname given to the account. it is different from the Account owner full name field. I assume this information is only stored locally on the traders client.

`Suggestion - allow traders to edit 'account name' for fiat and altcoin accounts. There are lots of reasons a trader might want to edit account nickname. Practicing good account management being the major use I can think of.
`

**Comment by chimp1984** [comment]
Thanks for all the good suggestions! 

> Suggestion - There is lots of space on the right. I would suggesting using a wo column layout (account info on the right). 

I changed that for 1.5.0 already.

Another improvement to consider:
It would be good to see more exactly the miner fee in BTC and in user currency (using market price) as well as % of trade amount (that is shown atm). Not sure if in the create offer/take offer screen there is enough space but at least in the confirm popup I think there should be enough space. But to see it earlier at funding screen would be better IMO. 

In a popup (i guess most people click `dont show again` like myself so they only see it initially) we have the costs listed, but still not converted in the user currency.

<img width="559" alt="Screen Shot 2020-11-26 at 22 07 09" src="https://user-images.githubusercontent.com/54558767/100406434-cf0af800-3033-11eb-8a79-93bb1929d5ee.png">

Something like:
Trade amount: 0.1 BTC (~1890 USD)
Security deposit: 0.015 BTC (~283  USD / 15% of trade amount)
Trade fee: 0.1 BSQ (~0.12  USD / 0.0044% of trade amount)
Miner fee: 0.000123 BTC (~2.23  USD / 0.015% of trade amount / fee rate: 34 sat/vByte, tx size: 342 kb)

Not sure if tx size is needed, maybe too nerdy ;-)

Another issue is that the selected payment method is not remembered in the create offer screen. It would be good if the last used payment method is used the next time when making an offer (if the selected currency matches).

**Comment by pazza83** [comment]
> > Suggestion - There is lots of space on the right. I would suggesting using a wo column layout (account info on the right).
> 
> I changed that for 1.5.0 already.

Thanks, being wider helps. But it is still a pain scrolling through accounts. See screenshot below. I can only see 2 other accounts. It take ages to scroll and is not very usable. I also do not know what will happen if something like SWIFT is added with multiple fields.

I think a 2 column layout would improve usability.

![new layout](https://user-images.githubusercontent.com/66367547/100409914-0b0a8100-3065-11eb-94ab-79ea7eed095b.png)

**Comment by pazza83** [comment]
> Another improvement to consider:
> It would be good to see more exactly the miner fee in BTC and in user currency (using market price) as well as % of trade amount (that is shown atm). Not sure if in the create offer/take offer screen there is enough space but at least in the confirm popup I think there should be enough space. But to see it earlier at funding screen would be better IMO.

Yes, this would save me getting out my calculator 👍 

> In a popup (i guess most people click `dont show again` like myself so they only see it initially) we have the costs listed, but still not converted in the user currency.

I keep all my pop ups. I do not know how people manage trades with not knowing what miner fees they will pay. I think there should not be an option on not showing the pop up that appears prior to confirming your trade.

**Comment by pazza83** [comment]
> Another issue is that the selected payment method is not remembered in the create offer screen. It would be good if the last used payment method is used the next time when making an offer (if the selected currency matches).

On my Bisq it remembers last payment method used / selected between making offers. I can put multiple offers on in a row without switching between payment methods.

**Comment by chimp1984** [comment]
> On my Bisq it remembers last payment method used / selected between making offers. I can put multiple offers on in a row without switching between payment methods.

I tried it just with create offer, select a diff. method but without actually completing the offer. Maybe its safed later in the process. But I remember that it confused me several times that the wrong method was selected. Maybe its because it adjusts to the selected currency of the offer screen.

I also had a bug today that when editing an offer it changed the payment method to prob the first in the list. Could not reproduce it afterwards though....

**Comment by pazza83** [comment]
> I tried it just with create offer, select a diff. method but without actually completing the offer. Maybe its safed later in the process. But I remember that it confused me several times that the wrong method was selected. Maybe its because it adjusts to the selected currency of the offer screen.

For me it keeps the selected payment method even if I do not complete an offer.

> I also had a bug today that when editing an offer it changed the payment method to prob the first in the list. Could not reproduce it afterwards though....

With the latest update to the edit offer. What happens if a user try to change an offer where the limit is above the selected payment method. For example could I create a 2 BTC offer with a Western Union account and transfer the funds to an unsigned, recently created, Revolut account. I would not like people to try using it to get around payment limits.

**Comment by chimp1984** [comment]
@pazza83 Is there anything missing or all covered by last releases? If so I think we can close it.

**Comment by pazza83** [comment]
Hi @chimp1984 

Thanks for all the changes much appreciated 👍 

Everything has vastly improved. it is now a lot more usable.

My comments are:

**National currency account screen**

It is still difficult to scroll. On my account I have gone from being able to see 2 other accounts to 4. So an improvement. I still think this is too little. I think about 8 is the right number. My preference would be to divide the screen space in 2 top half showing national currency accounts, bottom half showing selected account details. If it was fixed it would also stop the jumping around that happens when scrolling. 

**Allow renaming of 'account name' field**
I think you mentioned this was difficult to achieve. It would be nice to have, does not affect trading though. 

**Buy / Sell > Create Offer Screens**

I think the below is a new problem as a result of the update?

When a non multi-currency trading account is selected you cannot change the currency.

I think it would be good to be able to change both trading account and currency at all times. Otherwise to change currency you have to selected a supported trading method. It is not very intuitive

![currency](https://user-images.githubusercontent.com/66367547/103471498-332e8380-4d79-11eb-9f6d-411e8e2c31a4.png)
.

**Comment by chimp1984** [comment]
> When a non multi-currency trading account is selected you cannot change the currency.

> I think it would be good to be able to change both trading account and currency at all times. Otherwise to change currency > you have to selected a supported trading method. It is not very intuitive

Not sure if I understand right. If you select a single currency account the single currency is shown and changing that would not work with the selected account.

**Comment by pazza83** [comment]
Ok fair point,

It was pre loaded at British Pound GBP (maybe because that is what I was looking at last, or because my first 'trading account' is 'Amazon eGift Card' in Pound GBP.

I am thinking it would be nice if when currency was selected the app only showed payment options based on selected currency.

I guess I am thinking it would be nice to be able to change between currencies on this screen. This is not possible at the moment as you can only change between payment accounts.

Not sure if the update has removed a 'blank' option trading account that makes it behave a little differently? Ie it now loads to the first currency that matches the payment account as opposed to letting the user select??

**Comment by Conza88** [comment]
Relates to: https://github.com/bisq-network/proposals/issues/288 - vital to future and continued success of Bisq imo.

**Comment by pazza83** [comment]
Closing this but will review the account section again soon as there are still lots of improvements that can be made. I will make a fresh issue for this and likely wait till the new payment methods have been added.
