### ISSUE TITLE
Bounty: Script that installs Bitsquare on Raspbian Jessie

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#484]
See: https://forum.bitsquare.io/t/1-btc-edit-now-3-25-btc-bounty-for-bitsquare-on-raspberry-pi/
for more information. That bounty is offered by user TheKoziTwo.

**Comment by SjonHortensius** [comment]
FYI; I have received this bounty for my script posted here: https://github.com/SjonHortensius/BitSquareOnRpi/blob/master/bitsquare.sh. There were a few issues fixed:
- The default rpi repo's doesn't include _openjfx_, requiring the addition of another repo
- #491 - improve architecture detection for arm
- #492 - use already installed tor binary when available (torproject doesn't distribute binaries for arm)
