### ISSUE TITLE
My offers (open offers, trade, history) are not displayed.

### ISSUE THREAD

**Issue by MwithM** [bisq-network/bisq#4844]
### Description

After Bisq start, there are no offers at open offers, open trades or history. I did not force close Bisq, but performed regular and small update to OS before shutting down laptop. Available funds are displayed, but there's no locked or reserved funds.

#### Version

v1.4.2
Tested after upgrade to v1.5 without results.

### Expected behaviour

Display open offers, and two ongoing trades I have.

#### Device or machine

OpenSUSE Tumbleweed 20201121

#### Additional info

Logs are shared at Keybase, this issue is opened for register.

**Comment by ghost** [comment]
Tracked this down to an edge case where at startup the user data files are persisted back to disk before they have been read.  

The app was closed within 3 seconds of starting, before persisted data had been read.  Not sure why or how, perhaps user accidentally clicked close?  I've not been able to reproduce this, as data is read extremely quickly at startup, usually before any human actions can be processed.

As can be seen from this trimmed down log, ClosedTrades, FailedTrades, OpenOffers, PendingTrades are **written before being read** (other files were too, but I omitted from this excerpt for brevity).

    nov.-24 07:29:25.594 [main] INFO  b.c.u.Utilities: System info: os.name=Linux;
    nov.-24 07:29:25.606 [main] INFO  b.c.app.Version: Version{VERSION=1.4.2,
    nov.-24 07:29:25.620 [main] INFO  b.c.s.CommonSetup: Path to Bisq jar file: /opt/Bisq/app/desktop-1.4.2-all.jar 
    nov.-24 07:29:25.621 [main] INFO  b.c.u.Profiler: System report: Used memory: 9 MB; Free memory: 55 MB; Total memory: 64 MB; No. of threads: 1 
    nov.-24 07:29:28.477 [JavaFX Application Thread] INFO  b.c.a.AvoidStandbyModeService: Started -- disabled power management via /usr/bin/systemd-inhibit --who Bisq --what sleep --why Avoid Standby --mode block tail -f /dev/null 
    nov.-24 07:29:28.823 [SIGINT handler] INFO  b.c.a.BisqExecutable: Start graceful shutDown 
    nov.-24 07:29:28.973 [SIGINT handler] INFO  b.n.p.n.NetworkNode: Shutdown immediately because no connections are open.
    nov.-24 07:29:28.988 [BisqExecutable-read-RefundDisputeListService] INFO  b.c.p.PersistenceManager: Reading RefundDisputeList completed in 73 ms 
    nov.-24 07:29:28.989 [BisqExecutable-read-MyBlindVoteListService] INFO  b.c.p.PersistenceManager: Reading MyBlindVoteList completed in 70 ms 
    nov.-24 07:29:29.129 [JavaFX Application Thread] INFO  b.c.a.BisqExecutable: P2PService shutdown completed 
    nov.-24 07:29:29.130 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Start flushAllDataToDisk at shutdown 
    nov.-24 07:29:29.212 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Serializing ClosedTrades took 22 msec 
    nov.-24 07:29:29.218 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Serializing FailedTrades took 2 msec 
    nov.-24 07:29:29.327 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Serializing OpenOffers took 10 msec 
    nov.-24 07:29:29.329 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Serializing PendingTrades took 2 msec 
    nov.-24 07:29:29.342 [BisqExecutable-read-OpenOfferManager] INFO  b.c.p.PersistenceManager: Reading OpenOffers completed in 433 ms 
    nov.-24 07:29:29.387 [BisqExecutable-read-TradeManager] INFO  b.c.p.PersistenceManager: Reading PendingTrades completed in 478 ms 
    nov.-24 07:29:29.643 [Write-FailedTrades_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized FailedTrades completed in 425 msec 
    nov.-24 07:29:29.646 [BisqExecutable-read-Preferences] INFO  b.c.p.PersistenceManager: Reading PreferencesPayload completed in 739 ms 
    nov.-24 07:29:29.778 [BisqExecutable-read-FailedTradesManager] INFO  b.c.p.PersistenceManager: Reading FailedTrades completed in 866 ms 
    nov.-24 07:29:29.791 [BisqExecutable-read-ClosedTradableManager] INFO  b.c.p.PersistenceManager: Reading ClosedTrades completed in 880 ms 
    nov.-24 07:29:29.898 [Write-ClosedTrades_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized ClosedTrades completed in 685 msec 
    nov.-24 07:29:30.141 [Write-OpenOffers_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized OpenOffers completed in 813 msec 




Thanks to @MwithM for graciously providing logs.  Instrumental to finding this issue.

**Comment by MwithM** [comment]
Thank you for letting me get a workaround to get my offers and its funds back online again.
Main issue I found now is that I have open offers but reserved funds is 0.

**Comment by chimp1984** [comment]
Fixed with https://github.com/bisq-network/bisq/pull/4907
