### ISSUE TITLE
Feature Request: Support for External Tor Node

### ISSUE THREAD

**Issue by NetworkJack2** [bisq-network/bisq#4853]
### Description

For added security some people, perhaps including myself run an external TOR node. There should be an option in settings for IP and Port of TOR Node. I see there is already an area to enter bridge information.

Both of these should be asked on first run, because it is often not safe for some people to run a local TOR node.

**Comment by chimp1984** [comment]
This is supported already. I am not sure where the docs for that can be found. @m52go Do you know where/if we have documented usage of that?

> Both of these should be asked on first run

I dont agree to that. People get confused already enough with so much info at the first start/usage. This would just add more confusion for not tech-savvy users.

**Comment by NetworkJack2** [comment]
It needs to be asked first run because for many people running a local TOR node is not safe.

If this is already supported, its not in settings. There is an option for custom bridge, but not custom node. There is a difference.

**Comment by ripcurlx** [comment]
Following tor related command line parameters can be set:
- torDir
- useTorForBtc  // default true, except for local core node
- torrcFile
- torrcOptions
- torControlPort
- torControlPassword
- torControlCookieFile
- torControlUseSafeCookieAuth
- torStreamIsolation

I'm also not sure if it is a good idea to ask everyone on startup if they want to manually configure tor. Maybe we could display on first app run a button/link with a 5 sec countdown or so if you want to manually configure tor. For those who just ignore it the app start continues and for those who click on manual configuration they get an extended tor config screen. For all succeeding app starts we don't ask for this anymore.

I don't think we have a specific wiki entry for tor configuration atm. @m52go ?

**Comment by NetworkJack2** [comment]
All of those config keys need to be in the GUI. command line parameters for a GUI app are for debugging, or automation. GUI apps need GUI configs.

Here is an option for first run:
Radio button with two options: "default TOR options", the other is "custom". Default is default. that if you just click through it works.

If you select "custom" you have the ability to set either a bridge or external tor instance.

**Comment by m52go** [comment]
> I don't think we have a specific wiki entry for tor configuration atm. @m52go ?

No, but thank you for outlining them—I'll add.

**Comment by ripcurlx** [comment]
Just checked existing issues and I'm closing this one as a duplicate of https://github.com/bisq-network/bisq/issues/3010.
