### ISSUE TITLE
add max log size field to Account >> Backup

### ISSUE THREAD

**Issue by Bisq-knight** [bisq-network/bisq#4856]
### Description

Not a bug, but a suggestion.

We often run into problems that occurred multiple days back and the bisq logs seem to be insufficient to investigate the moment of some reported problem. I understand that many people would not be fond of keeping +500mb of logs but I do think there are some people who would be fine with it.

With that in mind I'd like to propose that we put a field in Account >> Backup with the max size of the logs you would allow.

Currently it is about 100mb  (~10  files)

**Comment by chimp1984** [comment]
See https://github.com/bisq-network/bisq/pull/4891

**Comment by chimp1984** [comment]
It is set to 20 now. I am not sure if adding it as user preference is good as users might set it very low and then in case of bugs we don't have enough data to figure out the issue. Also as the logs are set up very early in setup its not as trivial as other preferences, but require prob. to do it via properties file.

**Comment by cd2357** [comment]
Looks like the increase to 20 log files is a good compromise.
