### ISSUE TITLE
Bounty: Fix issue causing BufImgSurfaceData exception on Linux

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#486]
There are several bug reports (https://github.com/bitsquare/bitsquare/issues/445) with an BufImgSurfaceData exception on Linux systems. 
Probably they are caused after standby mode. I could reproduce them after a monitor resolution change.

Anyone who can fix that issue will get a bounty (get in touch to negotiate amount).

**Comment by dan-da** [comment]
Was this fixed?   It appears the bounty was paid out.   or refunded/cancelled?

**Comment by mrosseel** [comment]
In the jdkfix module there are two fixes, of which only one worked. The other one will be fixed in v112 of Java. I think Manfred decided to wait for that release and not spend time on it now

**Comment by Giszmo** [comment]
For what it's worth, this bug `Error message: sun.awt.image.BufImgSurfaceData cannot be cast to sun.java2d.xr.XRSurfaceData` hit me today, using 0.4.9.8

**Comment by ManfredKarrer** [comment]
Seems Oracle still has not fixed that...
I assume it happened when your monitor came back from standby, or you changed monitor/resolution.

**Comment by Giszmo** [comment]
I have a dual screen setup and do disconnect the external, portrait mode screen at times.

**Comment by ManfredKarrer** [comment]
I filtered that exception to not display an error popup. I think it has no critical consequences but is a UI render issue in the jdk, which is unfortunately still not fixed. It still logs a warning though...

**Comment by ManfredKarrer** [comment]
Close as that issues is likely solved with the Java 10 upgrade. If not please re-open.
