### ISSUE TITLE
Unable to proceed in trade  BUG

### ISSUE THREAD

**Issue by f321x** [bisq-network/bisq#4864]
### Description
 I cant proceed in my trade because it doesnt accept when i press "Payment made". It suddenly switches between trading step 2 and 3 and doesnt stay. I think the counterparty (seller) doesnt see the trade as payment done and we arent able to process in the trade. Did SPV resync but it didnt help.

#### Version
1.5.0

### Steps to reproduce
Do sepa trade, press "Payment made" and it switches randomly between step 2 and 3 and doesnt stay. Also when i restart bisq it is always back at step 2 until i press "payment made" several times then it switches between 2 and 3 again.

### Expected behaviour
I expected it to go to step 3 so the seller can send me the funds i bought of him.

### Actual behaviour
Switches back and forth between step 3 and 2 and we cant complete the trade

### Screenshots
![Screenshot1](https://user-images.githubusercontent.com/51097237/100517081-89ac0f00-3188-11eb-8a1a-99495f2e819d.png)
![Screenshot2](https://user-images.githubusercontent.com/51097237/100517085-8ca6ff80-3188-11eb-82d2-8c464c70d53f.png)

#### Device or machine
Lenovo Laptop with Ubuntu 20.04.1 LTS, Core i7, 8gb ram, 1gbit/s internet connection

#### Additional info
Can provide log file if it helps

**Comment by ghost** [comment]
Thanks for reporting this.  Logfiles are always helpful and appreciated.  Alternatively you could open terminal and use the following command to watch the log file, then press Payment made and see what errors are reported.

    tail -n 100 -f ~/.local/share/Bisq/bisq.log

**Comment by f321x** [comment]
[bisq.log](https://github.com/bisq-network/bisq/files/5610941/bisq.log)
[bisq_1.log](https://github.com/bisq-network/bisq/files/5610942/bisq_1.log)
[bisq_2.log](https://github.com/bisq-network/bisq/files/5610944/bisq_2.log)
[bisq_3.log](https://github.com/bisq-network/bisq/files/5610945/bisq_3.log)

Hey, here are the logfiles out of an new bisq backup, hope they help in finding the issue

**Comment by ghost** [comment]
From looking at the logs and recreating this scenario in test, it seems to me that your peer `sb2pykuwbllsefnc` has gone offline  after the trade was confirmed.  The following log exerpt shows the messages exchanged with the peer.  It can be seen that after `sb2pykuwbllsefnc` disconnects, all further messages get stored in the mailbox, including the trader chat message.  My advice would be to wait until the trade times out, then open mediation.

    ~/Downloads/kaschmirrr$ grep -i 'sb2pykuwbllsefnc' *.log
    b.c.o.OpenOfferManager: Received OfferAvailabilityRequest from sb2pykuwbllsefnc.onion:9999 with offerId 7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150 and uid 75bc80c2-4498-4405-bb19-dd370cd36a11 
    b.c.o.OpenOfferManager: Send OfferAvailabilityResponse with offerId 7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150 and uid 5f638d93-031b-4b8e-a07e-7c1d884e97f9 to peer sb2pykuwbllsefnc.onion:9999 
    b.c.o.OpenOfferManager: Send AckMessage for OfferAvailabilityRequest to peer sb2pykuwbllsefnc.onion:9999 with offerId 7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150 and sourceUid 75bc80c2-4498-4405-bb19-dd370cd36a11 
    b.c.o.OpenOfferManager: AckMessage for OfferAvailabilityRequest arrived at takersNodeAddress sb2pykuwbllsefnc.onion:9999. offerId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, sourceUid=75bc80c2-4498-4405-bb19-dd370cd36a11 
    b.c.o.OpenOfferManager: Received OfferAvailabilityRequest from sb2pykuwbllsefnc.onion:9999 with offerId 7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150 and uid 7fe320fd-333c-4f73-94c2-93b98b46fd5d 
    b.c.o.OpenOfferManager: Send OfferAvailabilityResponse with offerId 7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150 and uid 2981b702-0f9e-42d7-90b1-847466842c04 to peer sb2pykuwbllsefnc.onion:9999 
    b.c.o.OpenOfferManager: Send AckMessage for OfferAvailabilityRequest to peer sb2pykuwbllsefnc.onion:9999 with offerId 7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150 and sourceUid 7fe320fd-333c-4f73-94c2-93b98b46fd5d 
    b.c.o.OpenOfferManager: AckMessage for OfferAvailabilityRequest arrived at takersNodeAddress sb2pykuwbllsefnc.onion:9999. offerId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, sourceUid=7fe320fd-333c-4f73-94c2-93b98b46fd5d 
    b.c.t.TradeManager: Received inputsForDepositTxRequest from sb2pykuwbllsefnc.onion:9999 with tradeId 7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150 and uid eb8c0526-bc08-4c39-a689-597605958b32 
    b.c.t.p.t.m.MakerSendsInputsForDepositTxResponse: Send InputsForDepositTxResponse to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=84278f8d-fa0f-4d63-9374-a154f96fcf88 
    b.c.t.p.t.m.MakerSendsInputsForDepositTxResponse: InputsForDepositTxResponse arrived at peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=84278f8d-fa0f-4d63-9374-a154f96fcf88 
    b.c.t.p.TradeProtocol: Send AckMessage for InputsForDepositTxRequest to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, sourceUid=eb8c0526-bc08-4c39-a689-597605958b32 
    b.c.t.p.TradeProtocol: AckMessage for InputsForDepositTxRequest arrived at peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, sourceUid=eb8c0526-bc08-4c39-a689-597605958b32 
    b.c.t.p.BuyerProtocol: Received DelayedPayoutTxSignatureRequest from sb2pykuwbllsefnc.onion:9999 with tradeId 7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150 and uid d490fce1-4ef9-4476-b0c3-223cfdf9b9ca 
    b.c.t.p.t.b.BuyerSendsDelayedPayoutTxSignatureResponse: Send DelayedPayoutTxSignatureResponse to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=4b84f1fb-d4cd-4389-b9f5-52d598fda1c5 
    b.c.t.p.t.b.BuyerSendsDelayedPayoutTxSignatureResponse: DelayedPayoutTxSignatureResponse arrived at peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=4b84f1fb-d4cd-4389-b9f5-52d598fda1c5 
    b.c.t.p.TradeProtocol: Send AckMessage for DelayedPayoutTxSignatureRequest to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, sourceUid=d490fce1-4ef9-4476-b0c3-223cfdf9b9ca 
    b.c.t.p.TradeProtocol: AckMessage for DelayedPayoutTxSignatureRequest arrived at peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, sourceUid=d490fce1-4ef9-4476-b0c3-223cfdf9b9ca 
    b.c.t.p.TradeProtocol: Received AckMessage for InputsForDepositTxResponse from sb2pykuwbllsefnc.onion:9999 with tradeId 7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150 and uid 84278f8d-fa0f-4d63-9374-a154f96fcf88 
    b.c.t.p.BuyerProtocol: Received DepositTxAndDelayedPayoutTxMessage from sb2pykuwbllsefnc.onion:9999 with tradeId 7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150 and uid 7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150sb2pykuwbllsefnc.onion:9999 
    b.c.t.p.TradeProtocol: Send AckMessage for DepositTxAndDelayedPayoutTxMessage to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, sourceUid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150sb2pykuwbllsefnc.onion:9999 
    b.c.t.p.TradeProtocol: AckMessage for DepositTxAndDelayedPayoutTxMessage arrived at peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, sourceUid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150sb2pykuwbllsefnc.onion:9999 
    b.c.t.p.TradeProtocol: Received AckMessage for DelayedPayoutTxSignatureResponse from sb2pykuwbllsefnc.onion:9999 with tradeId 7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150 and uid 4b84f1fb-d4cd-4389-b9f5-52d598fda1c5 
    b.n.p.p.PeerManager: onDisconnect called: nodeAddress=Optional[sb2pykuwbllsefnc.onion:9999], closeConnectionReason=CloseConnectionReason{sendCloseMessage=false, isIntended=false} NO_PROTO_BUFFER_ENV 
    b.n.p.p.p.PeerExchangeManager: onDisconnect closeConnectionReason=CloseConnectionReason{sendCloseMessage=false, isIntended=false} NO_PROTO_BUFFER_ENV, nodeAddressOpt=Optional[sb2pykuwbllsefnc.onion:9999] 
    b.c.t.p.t.SendMailboxMessageTask: Send CounterCurrencyTransferStartedMessage to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: CounterCurrencyTransferStartedMessage stored in mailbox for peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: Send CounterCurrencyTransferStartedMessage to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: CounterCurrencyTransferStartedMessage stored in mailbox for peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: Send CounterCurrencyTransferStartedMessage to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: Send CounterCurrencyTransferStartedMessage to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: CounterCurrencyTransferStartedMessage stored in mailbox for peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: CounterCurrencyTransferStartedMessage stored in mailbox for peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: Send CounterCurrencyTransferStartedMessage to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: Send CounterCurrencyTransferStartedMessage to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: CounterCurrencyTransferStartedMessage stored in mailbox for peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.s.SupportManager: Send ChatMessage to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=c899ca59-6957-4872-a3e2-7df48ff6f4aa 
    b.c.s.SupportManager: ChatMessage stored in mailbox for peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=c899ca59-6957-4872-a3e2-7df48ff6f4aa 
    b.c.t.p.t.SendMailboxMessageTask: Send CounterCurrencyTransferStartedMessage to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: CounterCurrencyTransferStartedMessage stored in mailbox for peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: Send CounterCurrencyTransferStartedMessage to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: CounterCurrencyTransferStartedMessage failed: Peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999, errorMessage=Message was not sufficiently broadcast.
    b.c.t.p.t.SendMailboxMessageTask: Send CounterCurrencyTransferStartedMessage to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: Send CounterCurrencyTransferStartedMessage to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: CounterCurrencyTransferStartedMessage stored in mailbox for peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: CounterCurrencyTransferStartedMessage stored in mailbox for peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: Send CounterCurrencyTransferStartedMessage to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: Send CounterCurrencyTransferStartedMessage to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: CounterCurrencyTransferStartedMessage stored in mailbox for peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: CounterCurrencyTransferStartedMessage stored in mailbox for peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: Send CounterCurrencyTransferStartedMessage to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: Send CounterCurrencyTransferStartedMessage to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: CounterCurrencyTransferStartedMessage stored in mailbox for peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: CounterCurrencyTransferStartedMessage stored in mailbox for peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999 
    b.c.t.p.t.SendMailboxMessageTask: Send CounterCurrencyTransferStartedMessage to peer sb2pykuwbllsefnc.onion:9999. tradeId=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150, uid=7555561-e97513b6-eea5-402a-8625-5b862d47bcd3-150yvhwgmu34yrddoimgrylwnk3shzl65zlvhtdjcte2sdrf4oz7up24zad.onion:9999

**Comment by f321x** [comment]
Ok thank you then i will open a mediation if time runs out. But it is unclear to me why it doesnt accept when i press on "Payment made" and switches constantly between trading step 2 and 3, could this be also because the seller is offline or is this a bug?

**Comment by ghost** [comment]
In terms of the trading protocol, it appears to be operating properly, i.e. attempting to deliver `CCTSM`* to your trading peer.  In terms of the UI it does look a bit glitchy if you close/restart the Bisq app, it resends `CCTSM` and the trade state jumps back to 2 and then moves again to 3 as you mentioned.  The button for stage 2 is shown and can even be pressed which all adds to the confusion.  So yes, that could be improved upon, but I'll re-iterate that the protocol seems to be functioning fine.  In my testing this scenario only happens if the peer is offline and has yet to receive that `CCTSM` message and the Bisq app is restarting.  
<sub>* CCTSM = CounterCurrencyTransferStartedMessage</sub>

We can leave this issue open so that it can be addressed when resources become available.

**Comment by f321x** [comment]
Yes, the trade has now been fulfilled and the seller could send me the funds even though it looked otherwise on my client, as you say seems like a UI only glitch. Thank you for your help.

**Comment by chimp1984** [comment]
Fixed with https://github.com/bisq-network/bisq/pull/4885

**Comment by f321x** [comment]
Nice
