### ISSUE TITLE
BSQ trading fee in fiat not calculated properly

### ISSUE THREAD

**Issue by MwithM** [bisq-network/bisq#4865]
### Description

When placing or taking an offer, BSQ paid in EUR displayed is overestimated. It should use the [30 day average](https://github.com/bisq-network/bisq/pull/4781) but seems like something is failing.

#### Version

v1.5

### Steps to reproduce

Try taking or making an offer.

### Expected behaviour

Use 30 day average to give a value approximate to half of BTC trading fee in fiat.

### Actual behaviour

It gives a EUR value 5 times higher than paying in BTC.

### Screenshots

![imagen](https://user-images.githubusercontent.com/50149324/100525314-04dce780-31c0-11eb-892d-e4b541dd3439.png)

### Additional info

I checked 30 day average and it's normal (5122 sats/BSQ, 0.86 USD/BSQ) so that is not missing. Maybe it still taking the info from only the last trade?

**Comment by pazza83** [comment]
I think the 'Market Capitalisation' in the DAO > Dashboard could also be updated to be based on 30 day average rather than last trade price.

**Comment by MwithM** [comment]
I just realized that that PR 4781 is going to be merged on v1.5.1.
I leave this open only to see if pazza's suggestion can be merged as well.

**Comment by chimp1984** [comment]
> I think the 'Market Capitalisation' in the DAO > Dashboard could also be updated to be based on 30 day average rather than last trade price.

That is already done and in master.

**Comment by chimp1984** [comment]
> I checked 30 day average and it's normal (5122 sats/BSQ, 0.86 USD/BSQ) so that is not missing. Maybe it still taking the info from only the last trade?

Yes I assume it takes the last trade and so distorts the value. Should take for both BSQ and USD the average value.

**Comment by chimp1984** [comment]
Fixed with https://github.com/bisq-network/bisq/pull/4909
