### ISSUE TITLE
An error occured at a task: TakerProcessesInputsForDepositTxResponse

### ISSUE THREAD

**Issue by menkaur** [bisq-network/bisq#4866]
### Description

All attempts to take offers fail with error that looks like follows:

An error occurred at a task:TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lock time I calculated. Makers lock time: 660786, myLockTime: 660412

#### Version

Bisq version: 1.5.0

### Steps to reproduce

1. Go to market tab
2. Use BSQ-BSQ currency
3. Take trade as buyer
4. Go through steps
5. Trade fails after you commit to it

### Expected behaviour

Trade should have completed

### Actual behaviour

Trade should had completed successfully

### Screenshots

![Untitled](https://user-images.githubusercontent.com/171994/100606121-b32f7c80-32e7-11eb-9d0b-2a549ad276e5.png)

#### Device or machine

Windows 7 pc

#### Additional info

I'm using full unpruned node, I've also sent some funds to the internal wallet, and they arrived successfully. However, the app keeps saying that it's connecting to bitcoin and that it's synching dao without seeming to make any progress at either

![2](https://user-images.githubusercontent.com/171994/100606639-8039b880-32e8-11eb-81b2-172fa40d76d5.png)

**Comment by ripcurlx** [comment]
@menkaur Did you apply the required configurations to connect your personal node? https://bisq.wiki/Connecting_to_your_own_Bitcoin_node

**Comment by menkaur** [comment]
Setting  peerbloomfilters=1   seems to have fixed the synchronization
problem. There is another related bug, where I can't take any of the offers
where I tried and they failed, and the app hangs if I try, but it seems to
have been opened by another person. I'll let you know if the problem is
fully resolved once I see any new offers

**Comment by menkaur** [comment]
I can confirm that setting  peerbloomfilters=1  fully fixes the issue

**Comment by ghost** [comment]
Relevant PR for v1.5.1 https://github.com/bisq-network/bisq/pull/4764
