### ISSUE TITLE
Feature Request: Memo when withdrawing funds to external wallet after completed trade

### ISSUE THREAD

**Issue by viperperidot** [bisq-network/bisq#4869]
Would it be possible to allow for adding a memo when withdrawing funds to an external wallet when a trade is completed? There is a memo field when withdrawing funds from your Bisq wallet, but no such option when withdrawing funds directly after a completed trade.

**Comment by chimp1984** [comment]
Implemented with https://github.com/bisq-network/bisq/pull/4908

**Comment by viperperidot** [comment]
Thanks!

**Comment by ripcurlx** [comment]
Closing as complete.
