### ISSUE TITLE
When not in the foreground as topmost app in Windows, bisq unexpectedly closes with a certain keystroke

### ISSUE THREAD

**Issue by dav1dpgit** [bisq-network/bisq#4882]
### Description
On a Windows PC with the bisq application open, synced and running, when a microsoft edge internet browser is also open and in the foreground (prioritized), the keystroke for closing the microsoft edge foreground browser somehow also closes the bisq application (at the same time.

**NOTE: I see the same keystroke will also close bisq when bisq is in the foreground.  This may or may not be the developers' intention, but the issue I am raising is the same keystroke will terminate bisq unexpectedly in a certain situation and not in the foreground.**

#### Version
Bisq version 1.5.0

### Steps to reproduce

Open bisq, and open Microsoft Edge browser.  Make the Microsoft Edge browser not a full screen, but not minimized, either.  This way both the Edge browser and bisq are visible on the same desktop or monitor.  Click the header bar of the Microsoft Edge browser to ensure it is in the foreground (and bisq is not the primary foreground application.)

Click Ctl-W to close the Edge browser and it will shut down.  At the same time, bisq is closed.

### Expected behaviour

Only the Microsoft Edge browser should have closed and bisq should have remained open.  When bisq is the 3rd deep application (1st = Microsoft Edge browser, 2nd = another Microsoft Edge browser, 3rd = bisq), the Ctl-W close command only closes the topmost application (the 1st Microsoft Edge browser,) all the rest, including bisq, continue to run.

### Actual behaviour

Both the topmost application and bisq both close.  Again, bisq should not have closed.

#### Device or machine

Microsoft Windows 10, most current version

**Comment by chimp1984** [comment]
This seems to be a Windows problem that the event is not swallowed by the Microsoft Edge browser but forwarded to other applications. Never heard of that. Maybe some other windows users can try to reproduce that to see if that is only a local issue on your side of happens elsewhere as well.

**Comment by dav1dpgit** [comment]
It must be a Windows-only problem.  I tested the same keystrokes with the following apps as the 2nd layer but the problem did not happen like it did with bisq:

Microsoft Edge
Google Chrome
Microsoft Excel, Word,PowerPoint
Bitcoin Core
Keybase
Ubuntu app window

I look forward to hearing if others have the same issue with bisq.

Might be good to note that one can close a window inside a Microsoft application with the same ctl-W keystroke when said application is on the top layer, e.g. closing a spreadsheet in excel but not closing excel completely.  This is the first instance I have seen it pass through to the second layer of applications.
