### ISSUE TITLE
Find solution for restore from seed not using all the created addresses

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#4887]
### Description

We get repeated bug reports (like https://github.com/bisq-network/bisq/issues/4868) with missing transactions and addresses from users who did restore from seed words.
The problem is that those useres have created more addresses than the default batch (133 I guess). With a restore from seed they are missing those additional batches and only get txs related to the first 133 addresses (default batch). 

@oscarguindzberg Any idea how to fix that?
If not increasing the batch value from 133 to a much higher value would at least mitigate it for most users who don't get to the situation to create another batch (and do a restore from seed later). Do you think it causes a lot of performacne costs?

**Comment by chimp1984** [comment]
Restore from seed shoulld only be used in emergency cases when data directly is lost or wallet file is corrupted (even then its better to look up for a not corrupted backup file).

To verify the problem you can search in the wallet data (wallet tool opened by cmd+j) for the missing txs and addresses. Those txs are confirmed in the blockexplorer but not visible in bisq as the addresses are missing in the wallet as those addresses have been created in some future batches.

To fix open issues and if there is a backup available from the time before the restore from seed was done, I recommend following:

1. Make a backup for the data directory
2. Look up for the most recent wallet backup files before the restore from seed was done. The file size is likely larger then the newer ones. You can lookup in the backup folder as well
3. Copy over both the bisq_BTC.wallet and bisq_BSQ.wallet file to the current data dir and replace the old one
4. Delete the spv file
5. Start Bisq, it will do a spv resycn. it can take quite some time and use 100% CPU
6. After synced, restart
7. Now the missing addresses and transactions should be there.

**Comment by chimp1984** [comment]
@oscarguindzberg 
What about that idea to fix that problem if it is not easy to get fixed on the bitcoinj side:

- Add a button to the settings/network UI to trigger a new address batch creation
- If user has issues with missing addresses, he can repeat creating new batches until the address is found
- All that could be also done autimatically in code if we can detect that an address / tx is missing

Also we could use a higher number for the default batch in case of a restore to mitigate the problem.

**Comment by oscarguindzberg** [comment]
I was provided the xpub for the BSQ wallet and derived 20k addresses. The missing address is not there. #4868 seem not to be a bitcoinj lookahead problem.
Let's talk to the user and see if he can provide any further info to find out whether we have a bug or he is messing things up.

**Comment by chimp1984** [comment]
I could verify that this is not the issue with a local test. The missing lookahead addresses get created at restore from seed.
