### ISSUE TITLE
muisxp3 Two rows with the same Trade ID

### ISSUE THREAD

**Issue by Jan877** [bisq-network/bisq#4888]
[

### Description

Trade ID muisxp3
I have two rows with the same Trade ID.
I am trying to open a ticket with ctrl+O, but it is not working. I have received the payment from the buyer, but cannot confirm it. I also have a failed trade with the same Trade ID (please see screen shot). I have tried contacting the mediator with onion address "sjlho4zwp3gecspf.onion" on Keybase (Leo816?), but noone is responding.

#### Version
1.5.0

#### Additional info

<img width="891" alt="muisxp3" src="https://user-images.githubusercontent.com/44270690/101074805-79899a80-35a1-11eb-9b17-2916772bf654.png">
[bisq.log](https://github.com/bisq-network/bisq/files/5638338/bisq.log)

**Comment by chimp1984** [comment]
Can you move the failed trade to failed trades via the button on the right side?

**Comment by Jan877** [comment]
Yes, I could move the failed trade.

-- 
 Skickad med Tutanota, den säkra reklamfria e-posttjänsten: 
 https://tutanota.com


7 dec. 2020 17:01 av notifications@github.com:

**Comment by chimp1984** [comment]
Does the deposit tx show now? if not can u do a spv resync (settings/network)?
