### ISSUE TITLE
Error when attempting to take an offer

### ISSUE THREAD

**Issue by dougbebber** [bisq-network/bisq#489]
I received an error when attempting to take an offer (Sell BTC buy ETH)
<img width="572" alt="screen shot 2016-06-11 at 11 10 39 am" src="https://cloud.githubusercontent.com/assets/2474050/15986115/52ee5b22-2fc5-11e6-95ac-d1efe2af7cf2.png">

**Comment by d0x2f** [comment]
I got the same error just now, also with ETH.
I'm curious if the deposit is lost, where exactly does it go?

**Comment by ManfredKarrer** [comment]
@dougbebber @d0x2f : Could you post the offer ID with which that happened?
It should be a very rare case, so I am surprised to see it 2 times.
The security desposit has not left your wallet. The take offer fee (0.001 BTC) would be the only funds lost. In the process of taking the offer there is a very short time window where that can happen (e.g. if the network fails after take offer fee is paid, the process cannot complete).
You can see all transactions under funds/transactions.

**Comment by d0x2f** [comment]
I can't seem to find the offer again, but here are the trade details.
![ss 2016-06-12 at 11 15 16](https://cloud.githubusercontent.com/assets/8149130/15988427/87e9b550-3093-11e6-95d3-dca1250f8a66.png)

**Comment by ManfredKarrer** [comment]
I found the offer and tried to take it. It failed also 2 times,. After increasing the timeout and trying again the offer was already taken by someone else. The roundtrip time was quite slow (0.5-1 sec, normal is 200 ms), so I assume the reason for the issue was a very slow and unstable internet connection on the offerers side.
I will increase the timeout to avoid such failed attempts for the next release.

**Comment by ManfredKarrer** [comment]
Just managed to try again (seemed someone else who tried to take his offer failed as well, so the offer kept available after a while) with very long timeout but failed again. Round trip time is more then 1 sec.
Lost connection afterwards to him. So looks like a terribly bad connected peer. Hard to find a solution how to deal with such cases....

**Comment by dougbebber** [comment]
Manfred,

I remember seeing the offer disappear after the error. Is there a log where I may be able to find it?

Doug

**Comment by ManfredKarrer** [comment]
@dougbebber You can see it under failed trades (click on trade id opens details window) if it has the same trade id (offer id) as @d0x2f reported it was the same case.
I cannot see that trader anymore atm.
I found another possible reason for the issue: in the processing of the last step for the take offer process, there are a few checks. If any of those fail that would have triggered that as well. I will try to move those checks to an earlier step so avoiding such failures, as well as send a failure message to not trigger the timeout but report the details back to the taker if the take offer attempt fails.

**Comment by dougbebber** [comment]
Manfred,

Here is a screenshot of the Failed offer:

Doug
