### ISSUE TITLE
Error reported with no user action determined to trigger it

### ISSUE THREAD

**Issue by dougbebber** [bisq-network/bisq#490]
<img width="570" alt="screen shot 2016-06-11 at 2 53 46 pm" src="https://cloud.githubusercontent.com/assets/2474050/15987163/845c885e-2fe4-11e6-99f0-48133f88ff2b.png">

**Comment by ManfredKarrer** [comment]
Thanks for reporting. Do you remember which screen you had displayed? Probably the offer book.

**Comment by dougbebber** [comment]
Yes it was the offer book.

**Comment by ManfredKarrer** [comment]
Same as https://github.com/bitsquare/bitsquare/issues/421. Close here as it will be fixed in next version.
