### ISSUE TITLE
Promote Keybase as a support channel within Bisq GUI

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#4904]
# Promote Keybase as a support channel within Bisq GUI

As far as I am aware Bisq uses Keybase as it's primary support channel.  Keybase, however, Keybase is hardly mentioned in the Bisq client. I do not recall meeting a new trader on Bisq yet that is aware of Keybase.

From a personal perspective the time between me making my first trade and installing Keybase was 5 months. I was using Bisq daily in this time, so I think lots of new users might leave before then even become aware of Keybase, and by extension the community and support resources Bisq provides.

Reflecting on this, I would have preferred the client to persuade me to access Keybase sooner. It is very helpful, especially for new users. Things that are helpful to new users will likely make new users feel part of a community and stick around for longer and complete more trades. 

## Problem

The below problems decrease user experience and engagement of Bisq users, especially amongst new users:

- Bisq users are not always aware then can contact support via Keybase
- Bisq client does not reference Keybase anywhere within the client
- Bisq traders that are aware of Keybase have to break trade protocol to send user a link to Keybase.
- Bisq trader unware of Keybase may be suspicious of such a link
- Keybase is a great resource. Not enough new users are funned though to Keybase 
- Similar to the above Bisq client does not direct users to https://github.com/bisq-network/support
- Similar to the above Bisq client does not have a simple contact/community section. Bisq is a P2P network. It should encourage community. It misses out by not doing so.

**Example of problem:**

The image below is a recent conversion. It was a New Bisq user experiencing difficulties during a trade. The trader was unaware of Keybase. In an effort to be helpful the trader breaks protocol (do not send urls), putting their security deposit at risk to send the buyer a link to Keybase :roll_eyes:

This is a common chat. More common in the last 2 weeks since the issues around confirmations not being registered within the client.

![b5](https://user-images.githubusercontent.com/66367547/101299186-20cc3300-3829-11eb-8155-bcf463fa01e6.png)

## Desired outcome

The below would all be good outcomes.

- Improved user experience and increased engagement of Bisq users.
- New users to be more sticky and become life long Bisq users
- All traders to be aware of where to access support, resources, and community information
- Experienced traders not to feel awkward in breaking protocol to send someone to the Bisq team on Keybase

## Solutions (screenshots showing actual behavior and expected behavior)

Here are examples of current screenshots taken from the current client v1.5.0. I have made recommendations for some simple solutions that can be implemented to move closer to the desired outcomes.

#### Trade process being need help section outdated

![b6](https://user-images.githubusercontent.com/66367547/101299386-f464e680-3829-11eb-8eba-e78b5c116fe7.png)

The help section should point people to keybase. People going to community page will likely get sent onwards anyway.

---

#### Trader chat - no information about Keybase displayed

![b4](https://user-images.githubusercontent.com/66367547/101299463-39891880-382a-11eb-8887-81f39f7738a0.png)

Display information about Keybase being a support channel. 

> Need help? Why don't you chat with one of our friendly support agents on Keybase in the bisq team support channel. Download it here https://keybase.io/team/bisq 

---

#### Example of pop up new users see - no mention of Keybase

![b3](https://user-images.githubusercontent.com/66367547/101299593-a43a5400-382a-11eb-9e24-c61ae3024ebc.png)

Mention Keybase (text as above)

---

#### Popup new users see when they visit the Support section - no mention of Keybase

![b2](https://user-images.githubusercontent.com/66367547/101299642-d21f9880-382a-11eb-9ad9-cd559e8891ac.png)

Mention Keybase (text as above)

---

#### Setting page - No mention of Keybase

![b1](https://user-images.githubusercontent.com/66367547/101299673-f0859400-382a-11eb-9eb8-60c02d66f08d.png)

Link to https://keybase.io/team/bisq

---

#### Alerts - No mention of Keybase

![error2](https://user-images.githubusercontent.com/66367547/101299733-1ca11500-382b-11eb-8b75-28b6d26b8d80.png)

Mention Keybase (text as above)

---

#### Error in trade information screen  - No mention of Keybase

 ![error 3](https://user-images.githubusercontent.com/66367547/101299799-5bcf6600-382b-11eb-9eb0-5f0d9e25bd1d.png)

Mention Keybase (text as above)

---

#### Warning - Mentions keybse

![error](https://user-images.githubusercontent.com/66367547/101299864-92a57c00-382b-11eb-9273-c468bfa97275.png)

Add link to https://keybase.io/team/bisq

---

#### Bisq Client menu bar - No community section

![b7](https://user-images.githubusercontent.com/66367547/101301922-2712dd00-3832-11eb-86e2-75be25547171.png)

Add community section links to things like:

![community](https://user-images.githubusercontent.com/66367547/101302095-a6a0ac00-3832-11eb-8d8c-a6d689011f05.png)

## Additional info

Keybase is a good resource for bisq users. I would like to see more people using it, or at least decrese the percentage of new users that come to Bisq try it out and leave without ever knowing that Bisq had options for support.

Please see my tangentially related proposal to [Use Keybase to increase accessibility to Bisq for new traders with no funds for security deposit, trading and mining fees](https://github.com/bisq-network/proposals/issues/283)

**Comment by CryptoD** [comment]
Good idea.

**Comment by Conza88** [comment]
Fantastic idea. Needs to be done.
Growing community is key. Lowering barriers of entry. Helping newbs

**Comment by chimp1984** [comment]
Any dev who works on that?
@ripcurlx Can you tag is for "good first issue" or the like?

**Comment by forcryptos** [comment]
I will be taking this issue !

**Comment by pazza83** [comment]
@forcryptos that is great if you need me to provide any links or text just let me know I am `pazza` on Keybase

**Comment by forcryptos** [comment]
Cool, I will let you know and get your feedback once I get something figured out

**Comment by pazza83** [comment]
Hi @forcryptos are you still doing this? If not any other @bisq-network/bisq-devs that can take it on?

**Comment by wallclockbuilder** [comment]
I'll take it. @ripcurlx

**Comment by pazza83** [comment]
@wallclockbuilder that is great. Do you want me to design you the community section?

**Comment by wallclockbuilder** [comment]
Sure. That way we are all on the same page.

**Comment by pazza83** [comment]
Ok, will upload one next week :)

**Comment by pazza83** [comment]
Hi @wallclockbuilder here is the design for the Bisq community tab.

@m52go let me know if you are happy with the design or if you would like any changes.

![Community tab - B](https://user-images.githubusercontent.com/66367547/115155714-03319480-a079-11eb-9663-90d3ef64fa51.png)

**Comment by m52go** [comment]
I think this looks good, but it comes across as overwhelming to me. 

I suggest arranging the list of channels by use case, i.e. to answer the question "what would a user want to do?"

For example:
- **follow development** on github
- **chat with contributors** on keybase
- **get support** on keybase, the forum, reddit, telegram
- **get project updates** on twitter and youtube
- **get started** with the getting-started guide
- **see documentation** on the wiki

**Comment by pazza83** [comment]
Hi @m52go 

Thanks for the feedback. Yes organizing by what a user wants to do sounds great.

How about the following order / headings:

---

**Follow development**

- GitHub

**Get support**

- Keybase
- Forum
- Reddit

**Get project updates**

- Twitter
- YouTube
- Masterdon
- Bisq Blog
- Bisq Markets

**Chat with other users**

- Telegram
- Freenode IRC
- Matrix

**Get started** 

- Get started with the getting-started guide

**Read documentation**

- Bisq website
- Bisq wiki
- DAO


---

Let me know if you would like to add / remove any of the above?

I wanted to emphasize GitHub and Keybase by using a larger graphic. Let me know if you think this is ok?

**Comment by m52go** [comment]
Looks good. I'd recommend only listing the wiki for documentation -- I'm gradually trying to slim down the main website (bisq.network). FAQs will be gone soon, and DAO page will look totally different. Best DAO link will probably be https://bisq.wiki/Introduction_to_the_DAO.

**Comment by pazza83** [comment]
Thanks I will update and re-upload

**Comment by pazza83** [comment]
Hi @wallclockbuilder / @m52go 

Here is the updated design for the community section:

![Community tab - B2 (1)](https://user-images.githubusercontent.com/66367547/115615153-7ee44900-a2e6-11eb-8eb8-418ddfc417e0.png)

Let me know if you would like any edits

**Comment by m52go** [comment]
How about another section titled "Chat with developers" and include Keybase? Users in Matrix often ask to talk with contributors but they only hang out on Keybase, so I think it would be good to make that clear.

**Comment by pazza83** [comment]
Happy to add it. What about adding GitHub to "Chat with developers" too?

**Comment by Conza88** [comment]
TBH, Keybase has all. Chat with users etc. Support. Devs. Should be stated. If we want to push that, then at least a sentence at top calling it out.
________________________________

**Comment by pazza83** [comment]
Here you go I have emphasized Keybase more and included @m52go's suggestions also:

![Community tab - B3](https://user-images.githubusercontent.com/66367547/115622252-82c89900-a2ef-11eb-9a81-a40e78dac7e3.png)

Let me know if you would like any changes :)

**Comment by m52go** [comment]
> Happy to add it. What about adding GitHub to "Chat with developers" too?

GitHub isn't really chat, but it's a good idea anyway -- maybe change the heading to "Get in touch with developers and get support".

**Comment by pazza83** [comment]
Yes that sounds great, here are the changes.

@wallclockbuilder this is now complete for you to add. If you would like the Adobe XD file just let me know.

![Community tab - B3 (1)](https://user-images.githubusercontent.com/66367547/115628875-3a15dd80-a2f9-11eb-84d7-27ebe864a9b2.png)

For the the open URL and copy URL icons I took them from the font awesome icon packs. You might want to use these or otherwise a Bisq specific set.

I have also added a hover effects if you think it is appropriate.

![hover](https://user-images.githubusercontent.com/66367547/115629070-86f9b400-a2f9-11eb-8478-2e22bc63d574.JPG)

Any questions let me know.

**Comment by pazza83** [comment]
Hi @wallclockbuilder any updates with this?

**Comment by ghost** [comment]
@ripcurlx Would you assign this issue to me? I see there was a long silence on it, and I opened WIP pull request today.

**Comment by pazza83** [comment]
Hi @xyzmaker123 thanks for the comments. It would be great to get some progress made on the above.

**Comment by ghost** [comment]
@pazza83 Do you have Adobe XD file? I'm on linux and using gimp - if you can export to some format supported by it, that would be nice. I need it to retrieve colors, font sizes etc.

**Comment by pazza83** [comment]
Hi @xyzmaker123 yes it was made in Adobe XD I can send you the .xd file, I can export to .png .sgv .pdf and .jpg 

Let me know what format would be good for you.

**Comment by ghost** [comment]
@pazza83  .xd and .svg should be okay. However I think I implemented this view quite correctly based on existing materials already :)

**Comment by pazza83** [comment]
@xyzmaker123 

Great, happy to send the files over. Please can you message me on Keybase. My username there is: pazza

**Comment by pazza83** [comment]
Hi @xyzmaker123 how is this going. Let me know if you need any info from myself.

**Comment by ghost** [comment]
@pazza83 Pull request was reverted. There was a few faults on my side, but @chimp1984 and @m52go also has some good [remarks](https://github.com/bisq-network/bisq/issues/5732) about strings and top menu placement. I'd like to establish some final decisions and implement it properly.

**Comment by pazza83** [comment]
Hi @xyzmaker123 thanks, I will take a look at the comments and come back to you.

**Comment by pazza83** [comment]
Hi @m52go happy to include the changes you mention here https://github.com/bisq-network/bisq/issues/5732#issuecomment-929370707 for the community tab.

Is there anything else you would like changed or included?

**Comment by m52go** [comment]
I didn't really make any specific suggestions in that comment regarding text.

I'm not even sure if the symbols thing is possible. Need a developer's feedback on that first, and if it's not possible, we might need to come up with a more creative way of implementing this.

**Comment by pazza83** [comment]
@m52go in the meantime do you think we could update the text in the below sections:

- Trade process
- Trader chat 
- Pop up new users see 
- Support Popups 
- Setting page 
- Alerts
- Error in trade information screen

Currently there is a lack of mention where users should seek support, or they are pointed to the Bisq community forum. Rarely is Keybase mentioned.

The above changes would be text only so should be straightforward to implement, providing strings were agreed prior.
