### ISSUE TITLE
Architecture Check fails on Arm systems (like Raspberry Pi)

### ISSUE THREAD

**Issue by amustafa** [bisq-network/bisq#491]
When attempting to install BitSquare on the Raspberry Pi, I get this error:

```
You have probably the wrong version installed for the architecture of your computer. 
Your computers architecture is: 64. 
The Bitsquare binary you installed is: 32. 
Please shut down and re-install the correct version (64).
```

I'm using the RPi v2, which has an 32 bit ARMv7 architecture (https://en.wikipedia.org/wiki/Raspberry_Pi).

Looking through the code, I found the culprit. In the file: common/src/main/java/io/bitsquare/common/util/Utilities.java:

```
    public static String getOSArchitecture() {
    String osArch = System.getProperty("os.arch");
    if (isWindows()) {
        // See: Like always windows needs extra treatment
        // https://stackoverflow.com/questions/20856694/how-to-find-the-os-bit-type
        String arch = System.getenv("PROCESSOR_ARCHITECTURE");
        String wow64Arch = System.getenv("PROCESSOR_ARCHITEW6432");
        return arch.endsWith("64")
                || wow64Arch != null && wow64Arch.endsWith("64")
                ? "64" : "32";
    } else if (isLinux()) {
        return osArch.startsWith("i") ? "32" : "64";
    } else {
        return osArch.contains("64") ? "64" : osArch;
    }
}


public static boolean isCorrectOSArchitecture() {
    boolean result = getOSArchitecture().endsWith(getJVMArchitecture());
    if (!result) {
               ...
    }
    return result;
}
```

System.getProperty("os.name") returns Linux
System.getProperty("sun.arch.data.model") returns 32
System.getProperty("os.arch") return arm

So the check for osArch.startsWith("i") ? "32" : "64" fails.

**Comment by ManfredKarrer** [comment]
Thanks for reporting!
Do you know what 64 bit models of arm report as os.arch?

**Comment by amustafa** [comment]
Unfortunately, I don't and I don't have a device that I can check. But if it's analogous at all, it will still just say arm. 

Running "uname -m" in a terminal yields "armv7l". Anything less than ARM 8 is going to be 32 bit for sure. ARM 8 is the first arm processors with 64 bit instructions. I'm not sure if there is the same distinction in java's System.getProperty("os.arch") call though.

**Comment by ManfredKarrer** [comment]
I will add:
...else if (osArch.contains("arm")) {
            return osArch.contains("64") ? "64" : "32";
        } 
...
to the getOSArchitecture method.
Hopefully arm 64 will be covered by that. Though not sure if arm 64 is used at any desktops at all (I think its mainly mobile).
