### ISSUE TITLE
Mediator can't see opened case

### ISSUE THREAD

**Issue by CryptoD** [bisq-network/bisq#4924]
### Description

I opened a trade with the buyer who never paid me. After several days of waiting I opened case with mediator. For 2-3 days I didn't get any response from the mediator so I contacted him on Keybase. Mediator told me that he doesn't see my case. I sent him screenshot of transaction but received no response. It's been 5 days since I contacted mediator on keybase and case is till open.

#### Version

1.5.1

### Expected behaviour

Mediator responds to open case on Bisq and case is closed. 

### Actual behaviour

No response on Bisq from mediator. Mediator says he can't find the case.

### Screenshots

![image](https://user-images.githubusercontent.com/25362387/101636891-407f7900-3a2c-11eb-80eb-252f8915cef0.png)
![image](https://user-images.githubusercontent.com/25362387/101637107-9522f400-3a2c-11eb-8ff8-f254940e768e.png)

#### Device or machine

Linux Manjaro

**Comment by ripcurlx** [comment]
@cryptapus Who is the mediator for this case?

**Comment by CryptoD** [comment]
```
"mediatorNodeAddress": {
    "hostName": "sjlho4zwp3gecspf.onion",
    "port": 9999
```

**Comment by MwithM** [comment]
@leo816 you don't have trade with id jvcy9e?

**Comment by chimp1984** [comment]
@CryptoD Can you re-open the case with selecting the trade and click cmd+o. Confirm the warnings.

**Comment by CryptoD** [comment]
@chimp1984 Will do it now

**Comment by CryptoD** [comment]
@chimp1984 Case re-opening didn't create new separate case. I still see the same case with chat history. I sent a new message yesterday but so far no response from mediator.

**Comment by chimp1984** [comment]
Yes that is expected. But mediator got a new message in case he did not receive the first one. Contact the mediator in keybase as well.

**Comment by CryptoD** [comment]
It worked. Mediator now can see my messages and responds. Thank you @chimp1984
