### ISSUE TITLE
BISQ does not update transactions conformed to blockxhain

### ISSUE THREAD

**Issue by khyra-glich** [bisq-network/bisq#4926]

**Comment by ripcurlx** [comment]
Related to https://github.com/bisq-network/bisq/issues/4870

**Comment by chimp1984** [comment]
@khyra-glich 
Can you try to do a spv resync (at settings/network u see the button). Make sure that you dont interrupt it and you restart after resync. If it still not resolved you need to restore from seed words.
Make a backup first. Then copy seedwords and enter in into the restore field. Use the correct wallet date.
