### ISSUE TITLE
Development depends on BitcoinJ 0.13.1.3 but it's in version 0.13.1.2

### ISSUE THREAD

**Issue by ivilata** [bisq-network/bisq#493]
Trying to build Bitsquare branch `Development` 7943d1f1 with `mvn package -DskipTests` I get the following error:

```
[ERROR] Failed to execute goal on project common: \
 Could not resolve dependencies for project io.bitsquare:common:jar:0.4.8: \
 Could not find artifact org.bitcoinj:bitcoinj-core:jar:0.13.1.3 in sonatype-oss-snapshot \
 (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
```

In effect, latest BitcoinJ branch `FixBloomFilters` version 4f179977 is in version 0.13.1.2 instead of 0.13.1.3!  Maybe there are some changes there pending to be pushed?

Thanks!

**Comment by ManfredKarrer** [comment]
Latest BitcoinJ  (https://github.com/bitsquare/bitcoinj/commit/bca80f0608f246e3466e2399ae1be9ddaa5595fd) has already 0.13.1.3.
https://github.com/bitsquare/bitcoinj/blob/FixBloomFilters/pom.xml

**Comment by ivilata** [comment]
I'm able to pull the latest BitcoinJ commit and build successfully now, thanks!
