### ISSUE TITLE
Improve Transferwise account

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#4931]
### Description
From feedback from Transferwise users <strike>it seems that the sender always need to enter the full name of the receiver</strike>.
The receiver also sees the full name of the sender, so the email-only attribute does not add privacy.

<strike>So I think we have to add the full name field to the account.</strike> We can update the account similar as we did with Revolut, to check at startup if the field is set and if not open a popup to add it to existing accounts.  

Some users report that they need to know the address as well, it is likely depending on the currency. I suggest that we do not 
add that to the account but leave it to the users at the trader chat. 

<strike>The receiver can only receive from currencies where they have a bank account linked. The internal multi currency accounts are useless.</strike>

The sender can use any currency supported. So if the sender has AUD as linked account and the receiver has EUR as linked **or local** account the trade currency need to be EUR. 

I think it does not make sense to limit the sending currencies but only the receiving currencies, so we should change the currency selection to make that more clear. As most people will have only very few linked **or local** currency accounts I think we should  not select any currency by default and let the user select it. So if I hava EUR and CHF as linked **or local** accounts and defined those, I will only be able to create TW sell offer with those currencies. For buy offers I could support all currencies. This is a bit tricky to support. We could add an artificial currnecy code for refecting that (TW-multi-currency), so such buy offers would be displayed in all supported TW currencies, e.g. if the user filters for ARS he will see the same buy offer as when they filter for CHF. I am not 100% sure if all the currencies we have in our list can be used for sending from any country/account. I hope so but there might be exceptions and then it would get more complicate/impossible to do that.

So to get the full potential of the cross market possibilities of TW I think we should impl. that but its quite a bit of effort. 
Also if we change the way how the currencies are handled it will require another update for the account with a bit more complexity to communicate to the user the context.

The 1 day periods seems to be too low as the payment is to the bank account not to the TW internal account (which should be instant). I think it takes usually about 2 days, so changing it to 4 days like national bank tansfer would be more appropriate.

<strike>I still don't understand why TW does not allow to send funds to the internal accounts, then it would be really multi currency in both directions. As far I understand one can fund from his own bank to the internal account, but seems it does not support funding from other foreign bank accounts.</strike>

UPDATE:
I figures out in the meantime how to use the local accounts and they are great. Was just somehow complicate to find how to access them.

**Comment by chimp1984** [comment]
After further discussions I plan to do following:

- Add a button to the offer book next to currency and payment methods dropdowns: "Show all Transferwise offers"
This selectes show all in currency and TW in the method dropdown. A info icon with a tooltip gives background info ("With Transferwise one can send from nearly any currency and can receive funds with multiple currencies as well, so the currency selection does not make that much sense. The currency is mainly used for defining the trade price but Transferwise works as a global cross-currency payment processor")
- When the user selects a currency and then TW in the payment method dropdown we could show a popup with "dont show again" checkbox explaining that the currency selection has no relevance for buyers as they can send from any currency. By accepting the suggestion the currency selection switches to "show all", otherwise it stays to the currency the user selected. This is only at the BUY screen (showing sell offers). For the SELL screen (showing buy offers) the users is intending to sell BTC and receive fiat, so there the selection would make more sense to limit to the currencies he has enabled in his accounts. Here we could add a featuer to filter and show only those currencies (e.g. if I have EUR, SGD and CHF then my SELL screen shows offers with those currencies as only those I can receive). Maybe that could be combined with a general UI improvement to add a button for show only currencies supported in my account.  

- The popup after account creation will get better info and a link to the wiki. We should mention also the issue with primary accounts (only problemativ if linked accounts are set as primary) and that they become visible to any peer, which is a terrible privacy/security failure from TW side. 

- <strike>Add Full name to account</strike>
- Change currency selection to be only used for receiving funds and not have selected any by default. Add some link to the wiki so that users can set up their local account before they set up the Bisq account. 

If a user had already an account setup he will get a popup at startup where he need to enter the full name and the currency selection.

UPDATE:
Full name is not required.

**Comment by pazza83** [comment]
> * Add a button to the offer book next to currency and payment methods dropdowns: "Show all Transferwise offers"
>   This selectes show all in currency and TW in the method dropdown. A info icon with a tooltip gives background info 

This sounds good. Could this work for Revolut also for the same benefits?

>"With Transferwise one can send from nearly any currency and can receive funds with multiple currencies as well, so the currency selection does not make that much sense. The currency is mainly used for defining the trade price but Transferwise works as a global cross-currency payment processor")

Who are you referring to the currency selection not making sense for? Buyer, seller or both?  It might be helpful is you have a screen shot of how the implementation above would look.  

> * When the user selects a currency and then TW in the payment method dropdown we could show a popup with "dont show again" checkbox explaining that the currency selection has no relevance for buyers as they can send from any currency. By accepting the suggestion the currency selection switches to "show all", otherwise it stays to the currency the user selected. This is only at the BUY screen (showing sell offers). For the SELL screen (showing buy offers) the users is intending to sell BTC and receive fiat, so there the selection would make more sense to limit to the currencies he has enabled in his accounts. Here we could add a featuer to filter and show only those currencies (e.g. if I have EUR, SGD and CHF then my SELL screen shows offers with those currencies as only those I can receive). Maybe that could be combined with a general UI improvement to add a button for show only currencies supported in my account.

From my perspective I would be less likely to buy a Kenyan Shilling offer at 3% above market rate then a EUR offer at 5% above market rate. I think the Kenyan Shilling offer would result in higher risks of AML / compliance checks. 

> * The popup after account creation will get better info and a link to the wiki. We should mention also the issue with primary accounts (only problemativ if linked accounts are set as primary) and that they become visible to any peer, which is a terrible privacy/security failure from TW side.

Agreed.

> * Add Full name to account

Not needed. One can have multiple names linked to Transferwise. Adding names would cause problems when name does not match. Eg 'John Smith' is shown as 'Smith, j' or 'John Richard Smith', 'Jane Smith' or ACME Corp. All of these could be linked to John Smith one email address on Transferwise (johnsmith@gmail.com). The primary payment account does NOT have to belong to the user.

> * Change currency selection to be only used for receiving funds and not have selected any by default. Add some link to the wiki so that users can set up their local account before they set up the Bisq account.

Good idea

**Comment by pazza83** [comment]
> From feedback from Transferwise users it seems that the sender always need to enter the full name of the receiver.
> The receiver also sees the full name of the sender, so the email-only attribute does not add privacy.
> 
> So I think we have to add the full name field to the account. We can update the account similar as we did with Revolut, to check at startup if the field is set and if not open a popup to add it to existing accounts.
> 
> Some users report that they need to know the address as well, it is likely depending on the currency. I suggest that we do not
> add that to the account but leave it to the users at the trader chat.

I think this was due to confusion with someone using USD with TransferWise. 

USD is currently an unsupported currency.

**Comment by pazza83** [comment]
I would like to add TransferWise USD as a payment method.

Would this be best discussed here or on another issue?

**Comment by chimp1984** [comment]
Maybe better to open a new issue. It would be handled as new payment method (TransferWise-USD)

**Comment by viperperidot** [comment]
I dont think some of the assumptions made about this payment method are correct, in your OP @chimp1984 you say that you cannot receive to the local multi-currency accounts on TransferWise (and that they are useless). But myself and @pazza83 tested this feature and we were able to send and receive entirely on the TW local accounts and it was instant (with none of the delays you are referring to using outside bank accounts). Maybe @pazza83 can explain this in more detail because he is probably the TW expert but we did not run into to any of the issues you are describing here. 

On another note, I was going to put in a feature request issue but I think it may be more suited to add to the to-do list on this thread. What I was wondering is: would it be possible to allow sorting trade offers by % market value? This is useful when looking at all TransferWise offers across all markets. Currently you are unable to sort by price because Bisq is not able to determine the conversion rates for all the different currencies. I think rather that figuring out a way for Bisq to convert all the different currencies into a standard and sort them in the background it may be easier to sort by % market price. Assuming the price of BTC is the same in all the markets (relative to say the US dollar) then sorting by % market price should still give you the best rates on top. Unless I am missing something here? In any case it would be nice to be able to see the best offers on top when looking at all TW offers listed on Bisq if possible.

**Comment by pazza83** [comment]
> Myself and @pazza83 tested this feature and we were able to send and receive entirely on the TW local accounts and it was instant (with none of the delays you are referring to using outside bank accounts). Maybe @pazza83 can explain this in more detail because he is probably the TW expert but we did not run into to any of the issues you are describing here.

I think TW local accounts are really useful. I think speed is to do with the system they have in place for each currency. In my experience:

- EUR - TW user SEPA instant. If your trading partner has a SEPA Instant account payment in instant.
- GBP - TW user Faster Payments. If your trading partner has a Faster Payments account  (any UK account) payment is instant.
- RON - Takes 1 day
- USD - Takes 2-3 days
- NZD - Takes 1-2 days
- AUD - Instant - 2 days
- SGD - ???

- All TW - TW payments are instant as long as funds are available for payment (eg pay with balance, debit or credit card, or instant payment from a bank). Payment will take longer if user choose to deposit from a bank that does not support instant payment eg ACH.

> On another note, I was going to put in a feature request issue but I think it may be more suited to add to the to-do list on this thread. 

I think this will be out in the new update tonight 👍

**Comment by chimp1984** [comment]
> I dont think some of the assumptions made about this payment method are correct, in your OP @chimp1984 you say that you cannot receive to the local multi-currency accounts on TransferWise (and that they are useless).

Yes, I will add a comment there. I found out in the meantime how to use the local account and they are great. Just not easy to figure out how it works...

**Comment by chimp1984** [comment]
> would it be possible to allow sorting trade offers by % market value

Is in progress: https://github.com/bisq-network/bisq/pull/4949
But not sure if it makes it into 1.5.2.

**Comment by viperperidot** [comment]
Just wanted to add that the full name of the receiver appears when entering their TW e-mail address so you can just copy that into the name field. No need to add it to the Bisq payment method requirements, but it looks like this has also been removed from the to-do list. It is fantastic having a payment method where you only need an e-mail address (inside Bisq).

It seems as though the initial run of adding TransferWise has been a big success imo, lots of open offers adding liquidity and promoting user adoption across several markets!

**Comment by Conza88** [comment]
Worth putting on hold given TW deactivating accounts in bulk recently? 

I think improvements are worth doing. Leaving as well, seeing if the lack of trade ID's helps make any change to the deactivations at all.
