### ISSUE TITLE
Add KRW as a fiat currency.

### ISSUE THREAD

**Issue by crocket** [bisq-network/bisq#4939]
### Description

I have KRW, but it is not listed as a fiat currency in bisq.

Version: bisq-1.5.1

**Comment by wiz** [comment]
All fiat currencies are supported by Bisq, you just need to enable them in the Settings -> Preferences -> Add National Currency

**Comment by crocket** [comment]
Okay, but there is no deal in KRW unfortunately.

**Comment by pazza83** [comment]
Hi @crocket thanks for posting. 

Do you know you are able to make a Buy / Sell offer for KYW. 

It would be great to have some offers up.

Let me know me know if you need any help or have any problems with the current available payment methods suitable for South Korea.

**Comment by crocket** [comment]
* Postal money order
* Cash By Mail or Cash By Delivery

**Comment by pazza83** [comment]
Thanks for letting me know. Are you able to add any KRW bank accounts?

**Comment by crocket** [comment]
I have several KRW bank accounts, but it is not a preferred payment method because it requires a government ID. My long-term goal is to live without government IDs. How good is cryptocurrency if it practically requires government ID?

For now, if I want to buy any kind of cryptocurrency without KYC, I better buy USD and send it to americans in exchange for cryptocurrency.
