### ISSUE TITLE
Request: Permanent (recurring) orders/offers

### ISSUE THREAD

**Issue by MarcSte** [bisq-network/bisq#494]
This is especially interesting for large volume traders/btc sellers.

After an order of a btc seller is taken, a new and identical one should be automatically generated as long as the local wallet is funded. This, of course, should be made opt-in.

The option shouldn't exist for buy btc orders because offers could be filled without the fiat account being sufficiently funded. (outside of Bitsquare's influence)

**Comment by ManfredKarrer** [comment]
Good idea.
