### ISSUE TITLE
UI / Performance: Remove dependencies on AWT (system tray icon)

### ISSUE THREAD

**Issue by cd2357** [bisq-network/bisq#4940]
As per https://stackoverflow.com/a/11121207 having AWT dependencies in a JavaFX application can lead to more CPU/RAM usage than necessary, because two separate graphics stacks are loaded and active at the same time.

From what I can tell, Bisq mainly uses AWT for the system tray icon.

If that's the case, then with AWT we have:

* benefits: ability to show Bisq in the system tray
* drawbacks: a separate graphics stack (older, superseded by JavaFX) loaded in Java, with possible impact on RAM and CPU usage

To me, it seems the drawbacks outweigh the benefits.

Therefore, I suggest to remove the AWT dependencies from Bisq (and with that, the system tray icon).

**Comment by cd2357** [comment]
Looks like we also use AWT for the webcam/QR code reader, via the class `java.awt.image.BufferedImage`.

As per https://stackoverflow.com/questions/30970005/bufferedimage-to-javafx-image there is a JavaFX equivalent to that.

**Comment by ripcurlx** [comment]
> Looks like we also use AWT for the webcam/QR code reader, via the class `java.awt.image.BufferedImage`.
> 
> As per https://stackoverflow.com/questions/30970005/bufferedimage-to-javafx-image there is a JavaFX equivalent to that.

Besides that it also stopped working with Catalina as it doesn't work without notarization anymore to access the webcam. So I think it would be good to tackle the webcam part anyways.

**Comment by ripcurlx** [comment]
Related to #4374.

**Comment by ghost** [comment]
There remains outstanding issue of the library `com.github.sarxos.webcam` which uses awt in its public interface and so puts `java.awt.image.BufferedImage` and `java.awt.Dimension` into Bisq code.  To remove awt from the runtime stack the whole webcam library will need to change.

**Comment by cd2357** [comment]
A good non-AWT webcam alternative might be [JavaCV](https://github.com/bytedeco/javacv) (see [sample](https://github.com/rladstaetter/javacv-webcam)).

**Comment by ripcurlx** [comment]
And we really need to get rid of it now:

```
{
  "logFormatVersion": 1,
  "jobId": "b28d2a4f-7f18-4539-ac05-a2858b7cf1f2",
  "status": "Invalid",
  "statusSummary": "Archive contains critical validation errors",
  "statusCode": 4000,
  "archiveFilename": "Bisq-1.6.2.dmg",
  "uploadDate": "2021-04-14T08:20:07Z",
  "sha256": "4e4258559e1765428b067697c810cc4c05394fd87c393b21d3b9d43b1d8890d3",
  "ticketContents": null,
  "issues": [
    {
      "severity": "error",
      "code": null,
      "path": "Bisq-1.6.2.dmg/Bisq.app/Contents/app/desktop-1.6.2-SNAPSHOT-all.jar/com/github/sarxos/webcam/ds/buildin/lib/darwin_universal/libOpenIMAJGrabber.dylib",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "i386"
    },
    {
      "severity": "error",
      "code": null,
      "path": "Bisq-1.6.2.dmg/Bisq.app/Contents/app/desktop-1.6.2-SNAPSHOT-all.jar/com/github/sarxos/webcam/ds/buildin/lib/darwin_universal/libOpenIMAJGrabber.dylib",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"
    }
  ]
}
```

It prevents us to build notarized versions now for macOS as well.

**Comment by ripcurlx** [comment]
I'll give JavaCV a shot if I'm able to port our QR-Code reader to this supported lib.
