### ISSUE TITLE
Add filter by available payment methods

### ISSUE THREAD

**Issue by aicbaicb** [bisq-network/bisq#4945]
Currently, it is possible to either view all possible trades, with the trades that do not have a set up payment method grayed out, or filter by one particular payment method.

For someone that uses, say four payment methods, he has the choice of either filtering for one method, then repeating for the other three, or not filtering and seeing the irrelevant greyed out options.

There should be an option to filter by available methods, ie those that are not greyed out.

**Comment by pazza83** [comment]
Good idea. 

I think more filters should be available:

- Minimum deviation from market price
- Maximum BTC amount
- Minimum BTC amount
- Maximum fiat amount
- Minimum fiat amount
- Choice of payment methods
- Ignore unsigned accounts

I am planning to create a few designs to improve the UI.

**Comment by cd2357** [comment]
At the top of the "Buy BTC" and "Sell BTC" views there is now indeed a toggle to show only "Offers matching my accounts".

So if you have multiple payment methods (accounts), enabling that option would only show offers matching any of your configured accounts.
