### ISSUE TITLE
Duplicate orders causing ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by pmknutsen** [bisq-network/bisq#495]
I got this error when recovering from hibernation. When navigating to the Buy BTC tab, this error was displayed in a dialog: `java.lang.ArrayIndexOutOfBoundsException`

`Jun-14 08:20:01.213 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread`
`Jun-14 08:20:01.213 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= null`

The screen also displays duplicate orders:
![screenshot from 2016-06-14 08 17 08](https://cloud.githubusercontent.com/assets/1565499/16048529/4c20393c-3209-11e6-8739-3cf51b2b4f98.png)

After this error appeared a couple of times, the orders list does not refresh when I choose to filter by a different currency. When I restarted the app I got the error `problem.java.lang.NullPointerException`:
`Jun-14 08:25:04.769 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread`
`Jun-14 08:25:04.770 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= null`

When I continued to unlock the wallet the problem was no longer present.

Latest version 0.4.8 using the 64-bit .deb.

**Comment by ManfredKarrer** [comment]
Same as https://github.com/bitsquare/bitsquare/issues/421. Close here as it will be fixed in next version.
