### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by dougbebber** [bisq-network/bisq#496]
On the "Open trades" screen received the following error:
<img width="565" alt="screen shot 2016-06-17 at 5 13 25 pm" src="https://cloud.githubusercontent.com/assets/2474050/16166254/709acdf6-34af-11e6-9f9a-51263b49c1dc.png">

java.lang.ArrayIndexOutOfBoundsException

**Comment by ManfredKarrer** [comment]
Did you get that after standby mode? Until yet I saw that issue only at the offer book.

**Comment by dougbebber** [comment]
Manfred,

It happened on an "Open trades" screen in the "Confirm payment received"
step of the "Trade process". I have an open trade waiting for payment. That
is when the error window displayed. The computer was not in stand by.
However, the screen saver may have been on. I can't remember now. I'll keep
an eye out and see if it happens again.

Doug

**Comment by ManfredKarrer** [comment]
Thanks! Restart is recommended after such an event.

**Comment by ManfredKarrer** [comment]
Same as https://github.com/bitsquare/bitsquare/issues/421. Close here as it will be fixed in next version.
