### ISSUE TITLE
Always Connecting and Synchronizing

### ISSUE THREAD

**Issue by pfergi42** [bisq-network/bisq#4967]
### Description

Bisq is always "Connecting to Bitcoin network" and "Synchronizing DAO"

#### Version

v1.5.1

### Steps to reproduce

1. Launch Bisq.
2. Wait.

### Expected behaviour

Message should say "Connected to Bitcoin Network" and "Sync Complete"

### Actual behaviour

Bisq never stops "Connecting" and "Synchronizing"

### Screenshots

![Screen Shot 2020-12-17 at 12 02 12 PM](https://user-images.githubusercontent.com/4021240/102537716-295e0e00-4060-11eb-906b-86bc5af0f356.png)

#### Device or machine

Mac / Big Sur

**Comment by themighty1** [comment]
Similar here on 1.5.1, with CPU at 100% I see "Synchronizing DAO".
And on the console I see "b.c.d.node.parser.BlockParser: Parsing 0 transactions at block height 661779 took 0 ms "

I think it is in Bisq's best interest  to give the user some idea of what's going on.
Like for example, when the user mouses over the "Synchronizing DAO" text, there could be a brief explanation of what's going on and how much time is left until full sync.

My first thought was "Bisq is broken and stuck in an endless loop." Then I google "bisq high cpu" and I walk away with the impression that "bisq occasionally has such issues".

However, if there was an explanation upfront as to why the high CPU and when it will end, I would not quit the app, I would have no problem waiting when I know that this is normal.

**Comment by ghost** [comment]
OP's symptoms are usually experienced when local Bitcoin node is not configured with `peerbloomfilters=1`
https://bisq.wiki/Connecting_to_your_own_Bitcoin_node

**Comment by davterra** [comment]
I'm having the same issue, using 1.5.1 on Debian 10 in a qubes VM (setup in accordance with the qubes vm recommendations).
I am not seeing unusual CPU usage....that seems normal, but the message on the status bar is the same as OP's.
I do have `peerbloomfilters=1` in my bitcoin.conf

**Comment by pfergi42** [comment]
Setting `peerbloomfilters=1` in my bitcoin.conf fixed the first part, I'm now able to connect to the Bitcoin Network, but it never stops "Syncing the DAO"...

<img width="804" alt="Screen Shot 2020-12-20 at 7 22 13 PM" src="https://user-images.githubusercontent.com/4021240/102736106-fb472b00-42f8-11eb-8616-1a1b94245ceb.png">

**Comment by ghost** [comment]
Go to `DAO -> Bsq Wallet -> Transactions`, at the bottom of the screen it will show the status of the sync.  If the block number is behind the latest block at https://mempool.space and not progressing, try restarting Bisq.  If restarting does not cause the sync to progress then perhaps an SPV resync is required (`Settings -> Network -> SPV Resync`).

**Comment by pfergi42** [comment]
Thank you. Somehow it just fixed itself in the last 25 minutes. The "Syncing" text has disappeared. Thanks jmacxx for the tip anyhow!
