### ISSUE TITLE
Cannot take the offer

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#497]
Hi,

I'm trying to buy bitcoins with SEPA payment, but most orders I try to take, I see this message: (you cannnot take the offer because the offer was already taken by another trader)

Since yesterday the same orders I try to take still appear on bitsquare and I cannot take it. Why the orders that was already taken it's not removed from bitsquare?
Obs: I restarted bitsquare and I still see the same orders.

See the screenshots uploaded

![bitsquare](https://cloud.githubusercontent.com/assets/1178856/16172050/cae7c90c-3555-11e6-8997-39526432d28e.png)

![bitsquare 1](https://cloud.githubusercontent.com/assets/1178856/16172053/d1e9389e-3555-11e6-8c04-b765365f280d.png)

**Comment by ulrichard** [comment]
I had the same issue yesterday for 5 different blockchain offers that I tried to take.
It was the first time yesterday that I had this problem, and it is still happens today.
That was with v0.4.8 on Trisquel.

**Comment by ManfredKarrer** [comment]
Thanks for reporting! That was actually mine offers. Was running my node with a new dev version where I had an issue with backward compatibility. Is fixed now...
There might be still issues as I distributed a dev test version to a few people. Will send them soon an updated version so it should not appear anymore.

**Comment by ManfredKarrer** [comment]
I sent out new dev test versions to the testers, so that issue should not accore anymore as soon they have updated.
