### ISSUE TITLE
Improve performance of ParseBlockChainComplete

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#4972]
### Description

Seems a bottleneck at DAO parsing is the hash cain handling:
`DaoStateMonitoringService: ParseBlockChainComplete: Accumulated updateHashChain() calls for 32 block took 2979 ms (93 ms in average / block) `

Also `BsqWalletService: updateBsqBalance took 113 ms ` seems to be too slow.

**Comment by cd2357** [comment]
Duplicate of #5779, fixed with #5782
