### ISSUE TITLE
Add edit offer button next to the remove button in the offer book

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#4986]
### Description
A edit offer button next to the remove button in the offer book would be a nice feature. Should open the edit offer screen.

**Comment by pazza83** [comment]
This would be a great feature. I would like to see this added. It would save a lot of back and forth between 'offer book' and 'my open offers'

**Comment by Conza88** [comment]
Yes. Agreed. Just condense the "- Remove" and add "edit" beforehand... 

Probably should highlight how you can now CHANGE the currency? (and payment method?) as a (i) constant reminder to new folks and old... that way people are MORE inclined to MAKE offers...
