### ISSUE TITLE
Add featured payment methods fields

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#4990]
### Description
We should add recommendations and info links to the payment account screen.
For new users the account screen is filled with an empty list view.
We could use that space to show 2 or 3 fields for featured payment methods.
A short headline, followed by a short summary text and a button to the wiki for more information.
Once the list view get polulated with more than 3 payment accounts we can hid the feature boxes to safe space. It can be assumed that such users have already learned about it. Also at adding of viewing a payment method the boxes should be hidden to not degrade UX.

Goal is to motivate new users to look into those payment methods and consider to use them. 
I think specially Transferwise would deserve such promotion as it has a huge potential for Bisq and seems to be not well enough known yet.

**Comment by Conza88** [comment]
I like the essence of this. Or the payment method highlighted in the fiat currency options as no. 1, given its international fiat/global access. 

What I do currently is look at transferwise as method and all currencies. I think most people are looking just at their local market only though, and thus is being under-utilised. 

A transferwise buy BTC offer could be in all btc sell fiat currency lists for every single market. 

A transferwise sell btc offer could be in all btc buy fiat currency lists for every single market. 

If the maker has selected that currency in their account.

**Comment by chimp1984** [comment]
> What I do currently is look at transferwise as method and all currencies. I think most people are looking just at their local market only though, and thus is being under-utilised.

Yes good point! I wanted to add some kind of UI element next to the payment method drowdown but did not work well from UI POV. Maybe we should just switch to "show all" in the currency selection if transferwise is selected?

**Comment by pazza83** [comment]
> We should add recommendations and info links to the payment account screen.

Yes, I think a labels 'Popular Payment Method', 'Multi-Currency' or 'Instant' would work well. 

> Goal is to motivate new users to look into those payment methods and consider to use them.

This would be good. Not sure though if users will take the time to consider all the payment methods.  Some of them are a little complex and require a little research. I still have not got my head around Perfect Money and am put off when I look at reviews. Ideally each payment method should have it's own wiki with more information. 

Maybe the goal should be: Make it easy for users to see which payment methods are available to them and a good choice for Bisq trades. 

I think another good UX improvement would be to select currency and then see the payment methods available for that particular currency.

There are quite a lot of payment methods available that are only for one specific currency but it is not immediately obvious what they are or if they are suitable.
 
> I think specially TransferWise would deserve such promotion as it has a huge potential for Bisq and seems to be not well enough known yet.

Yes, I agree it is instant, multi-currency and has a large user base. I think this will end up competing with Revolut for number of trades on Bisq.

Happy to do some mock ups if you like to see what it could look like?

**Comment by pazza83** [comment]
Some of the payment methods also overlap which is a bit confusing.

You can have a local EUR TransferWise account details and add it to:

- SEPA
- SEPA Instant
- National Bank
- Transfers with the Same Bank
- Transfers with specific banks

You do sometimes see offers like the above where someone has added them incorrectly.

There was a National Bank (BE) recently that was top of the SEPA markets for a while selling BTC at -1% but no one took it for a couple of months as they would have to set up their payment account in Bisq in such a way to make this offer available, and then wait until they were signed + 30 days.

**Comment by chimp1984** [comment]
> Not sure though if users will take the time to consider all the payment methods
I was thinking of kind of "Bisq recommended" methods like TW, not all... many are rather obsolete and not worth the effort (like Perfect Money).

> I think another good UX improvement would be to select currency and then see the payment methods available for that particular currency.

Good point. Will put it on my list.

> Happy to do some mock ups if you like to see what it could look like?

Yes that would be great!

**Comment by chimp1984** [comment]
> Some of the payment methods also overlap which is a bit confusing.

Yes I saw that offer as well. Restricted to BE, and even a TW account so the user made 2 mistakes. Limiting SEPA access to Belgium and not using TW which would be better anyway... I tried to give a bit hints in the forum post... https://bisq.community/t/how-to-make-your-offers-more-successful/10117

The "Transfers with the Same Bank" and "Transfers with specific banks" have been added for counties where banks charge extra fees for specific other banks, so trader wanted to define which banks they want to use to not pay bank fees... For SEPA market those are irrelevant usually, same as "National Bank" IMO.
Maybe we should show some warning in the OS language suggests that its a European user? But I think most people get that by themself anyway...

**Comment by Conza88** [comment]
What about instead of this.... or in addition: having a filter: "acceptable trades", for BUY and SELL. 

e.g. Transferwise account can accept any fiat etc. but people only look at their local market. Instead of manually going through all fiat, just change payment method ALL, right? 

BUT if I have multiple payment methods... which I do... that's also a pain... so just have "acceptable trades" ALL, and then its about making all the accounts I can to cover all offers I'd want etc.

**Comment by Conza88** [comment]
> > What I do currently is look at transferwise as method and all currencies. I think most people are looking just at their local market only though, and thus is being under-utilised.
> 
> Yes good point! I wanted to add some kind of UI element next to the payment method drowdown but did not work well from UI POV. Maybe we should just switch to "show all" in the currency selection if transferwise is selected?

Forget where this was added, but possible to do for Revolut as well? Given it's essentially same with TW - fiat currencies?

> Goal is to motivate new users to look into those payment methods and consider to use them.
> I think specially Transferwise would deserve such promotion as it has a huge potential for Bisq and seems to be not well enough known yet.

There is the addition of payment method details screen coming I think? This will highlight motivation clearly for all about where the liquidity is... and can spur investigation. 

TW - was superb until deactivating quite a few. No trade ID in 1.5.5 will be interesting to see how it plays out, i.e. may revive TW.
Revolut seems best replacement? maybe SWIFT eventually?

**Comment by ripcurlx** [comment]
> There is the addition of payment method details screen coming I think? This will highlight motivation clearly for all about where the liquidity is... and can spur investigation.

This will be part of v1.5.5 which will be probably released today.
