### ISSUE TITLE
Deactivate offer if market price is above or below a user defined trigger price

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#4998]
### Description

When using % based price there is a risk that if market price moves too drastically that the offer gets taken to a price which the maker would not like to accept. By adding a trigger price which deactivates the offer automatically if the market price hits that price we can protect makers against such price swings.

If its a sell offer the maker is interested to protect themself against too low prices. If its a buy offer the maker is interested to protect themself against too high prices. So only one field is needed.

Here is a WIP version of the implementation in the create offer view:
<img width="1197" alt="Screen Shot 2020-12-23 at 20 29 36" src="https://user-images.githubusercontent.com/54558767/103049030-88d78480-455e-11eb-8392-950eb858f02e.png">

In the open offer view at portfolio we will add a new column for the value and in edit offer it can be changed.

Re-activating the offer once the price exits the undesired range might be an option as well, but is not planned for the initial version.

Please leave comments if you have any inputs/feedback to that feature.

**Comment by ripcurlx** [comment]
Closing as complete.
