### ISSUE TITLE
Impossible to take offer after first attempt time out.

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/bisq#5007]
### Description

Whenever i take an offer and it fails for whatever reasons, usually a time out, no funds are spent, no txs are created, but the trade is still considered failed and moved to the failed trades list.
As a result, I'm unable to try to take the offer again at a later point or after switching networks.
This is an issue on the taker-side, I'm able to try again with a new bisq-profile. Just not the one where i tried it before.
This is new behavior and i used to be able to try again if i got a time out.

#### Version

Bisq v1.5.1

### Steps to reproduce

1. Take offer, hope it fails or disconnect your network immediately after initiating the trade.
2. Get message that taking the offer failed and no funds have moved from the wallet.
3. Try to take the offer again, resulting in message, unable to take offer, already in the failed trades list.

### Expected behavior

When the offer has not actually been taken and no txs were created, it should not be moved to the failed trades list and should remain available to try to take the offer again.

### Actual behavior

Unable to try to take an offer after a first attempt failed with a time out.

**Comment by ripcurlx** [comment]
@invertedbobb Do you see this issue still in the current version?
