### ISSUE TITLE
Open trade data lost upon update

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#5019]
### Description

Upon update, trade data was lost. We can still see the transactions under the Funds > Transactions tab but they're not interpreted as trade transactions - "Taker and tx fee:" or "Multisig deposit" -  and are instead labelled as simple "Withdrawn from wallet" or "Miner fee for BSQ tx".

#### Version

Update from 1.5.1 to 1.5.2
### Screenshots

In this case the trader was the Taker on all trades. The transactions are colored in pair by their trade.

<img width="1440" alt="BTCSellerTaker-transactions-edited" src="https://user-images.githubusercontent.com/44140017/103288552-04ad5300-49dd-11eb-9383-1acd84ef93bf.png">

#### Device or machine

 Mac OS Big Sur 11.1

#### Additional info

The trader had other open trades that seem unaffected by this issue.

**Comment by ripcurlx** [comment]
@sqrrm @chimp1984 Can it be that this was caused by the v1.5.2 update?

**Comment by chimp1984** [comment]
@huey735 Can you check if there is a corrupted files folder in the data directory (in the db folder)? seems one of the db files got corrupted.

**Comment by huey735** [comment]
@chimp1984 Do you want me to ask them for their db/ folder?

**Comment by chimp1984** [comment]
They can have themself a look into the db folder if there is any corrupted_files sub folder

**Comment by cd2357** [comment]
@huey735 any updates? Investigation ongoing, or can this be closed? Thanks.

**Comment by huey735** [comment]
@cd2357 I think it has been fixed by https://github.com/bisq-network/bisq/pull/5280
@jmacxx @chimp1984 am I right?

**Comment by ghost** [comment]
Correct, fixed by #5280 :+1:
