### ISSUE TITLE
Taking offer fails - Timeout

### ISSUE THREAD

**Issue by martysto** [bisq-network/bisq#502]
When buying Bitcoin, taking the offer failed twice with the following error.

Error Report:

Error message:
An error occurred when taking the offer.

A timeout occurred.

The trading fee is already paid. In the worst case you have lost that fee. We are sorry about that but keep in mind it is a very small amount.
Please try to restart you application and check your network connection to see if you can resolve the issue.Please try to restart you application and check your network connection to see if you can resolve the issue.

**Comment by ManfredKarrer** [comment]
Do you remember which offer you tried to take? (offer ID)

**Comment by martysto** [comment]
Trade ID: 36147db9

**Comment by ManfredKarrer** [comment]
I cannot find that offer, seems the offerer is offline. Can you try to restart and see if it still there, if so can you send me the currency and price so its easier to find for me?
Thanks!

**Comment by martysto** [comment]
It's going on- and offline ... 
EUR.BTC 0.4BTC; Price 466
How could I check uptime/availability of an offer?

**Comment by martysto** [comment]
I just try to hit it again, ... I think there is some kind of spoofing going on.

**Comment by ManfredKarrer** [comment]
Don't try again you lose the taker fee. 
It can be that he gets an error at the step where you take the offer. I changed stuff for the next version so that those checks are done before the fee is paid. Theoretically it could be a sabotage as well, but most likely its a bug/flaw with the current version.

**Comment by ManfredKarrer** [comment]
Something similar happened a while ago...
