### ISSUE TITLE
Error  java.lang.NullPointerException  at creation of sell offer 

### ISSUE THREAD

**Issue by 23Yc8z** [bisq-network/bisq#5023]
After creating sell offer, this error popped out. 
It seems that the sell offer has been created properly, though.

java.lang.NullPointerException

1.5.2

Error popped out, but sell offer created

![Bisq error java](https://user-images.githubusercontent.com/57015173/103301537-ec036400-4a01-11eb-8b0f-f432f45f1bdf.jpg)

Win 7 x64

**Comment by ripcurlx** [comment]
Could you please provide us with the log file, so we can see more details where this NullPointerException came from?

**Comment by fran-rial** [comment]
Not the same trade but the same issues 
[bisq.log](https://github.com/bisq-network/bisq/files/5752777/bisq.log)
Trades failed with different errors while setting up the offer. 
Please let me know if you need further logs or if you need a separate issue.

**Comment by cd2357** [comment]
@fran-rial is it still happening with the latest version? Many things have changed since v1.5.2 which might have also fixed this issue.

**Comment by 23Yc8z** [comment]
Hi,

I have installed v1.6.1, 
moved the trade from "failed" to "open" 
and I get some warning messages (see attached screenshots):


There is an issue with a missing or invalid transaction.
Please do NOT send the fiat or altcoin payment.
Open a support ticket to get assistance from a Mediator.
Error message: Deposit transaction is null or has unexpected input count.

The trade protocolol encountered some problems.
The deposit transaction (the 2-of-2 multisig transaction) is missing.
Without this tx, the trade cannot be completed. No funds have been locked but your trade fee has been paid. You can make a request to be reimbuersed the trade fee here: https://github.com/bisq-network/support/issues.
Feel free to move this trade to failed trades.

The deposit transaction in null. You can move the trade to failed trades.


Kind regards.





    En lunes, 29 de marzo de 2021 16:52:30 CEST, cd2357 ***@***.***> escribió:  
 
 


@fran-rial is it still happening with the latest version? Many things have changed since v1.5.2 which might have also fixed this issue.

**Comment by fran-rial** [comment]
Hi
Did not have this issue again, had other issues with network synchronisation, etc in previous releases. I’ve updated to the latest version.
Greetings 
Fran

**Comment by ripcurlx** [comment]
Closing as complete.
