### ISSUE TITLE
After upgrading to 1.5.2 app never compeletely starts

### ISSUE THREAD

**Issue by robster7674** [bisq-network/bisq#5025]
### Description

When launching the application, it never gets passed the splash screen, see screenshot.

#### Version

1.5.2

### Steps to reproduce

Upgrade to 1.5.2, start app.

### Expected behaviour

Be able to use the app.

### Actual behaviour

App never gets passed splash screen

### Screenshots

![image](https://user-images.githubusercontent.com/70331923/103343879-64fbcd80-4a8d-11eb-956a-6b8732a76386.png)

#### Device or machine

MacBook Pro early 2015, OS 10.15.4, latest updates.

#### Additional info

This happens both with and without VPN connection active.

**Comment by robster7674** [comment]
After waiting over an hour, the application finally started.

**Comment by ripcurlx** [comment]
> After waiting over an hour, the application finally started.

We are under a DoS attack right now and v1.5.2 is still vulnerable against it. Please update to v1.5.3 and try to start again.
