### ISSUE TITLE
An error occurred when taking the offer.

### ISSUE THREAD

**Issue by tkemmere** [bisq-network/bisq#503]
Saw interesting offer.
Clicked on Buy
Had insufficient funds.
Funded wallet (didn't wait for confirmation)
Came back to buy-screen
Confirm offer for buying Bitcoin.
Take offer in progress...............
Error:

_An error occurred when taking the offer.
A timeout occurred.
The trading fee is already paid. In the worst case you have lost that fee. We are sorry about that but keep in mind it is a very small amount.
Please try to restart you application and check your network connection to see if you can resolve the issue.Please try to restart you application and check your network connection to see if you can resolve the issue._

Restarted application.
Offer was still there.
Tried again.
You may need to wait till you are fully connected to network. might take 2.
Tried again.
Fund wallet.
Confirm offer for buying Bitcoin.
Take offer in progress...............
Same error.

I must say the offer is tóó good to be true: € rate is now 592, offer was 466.

Tried one final time. Same thing.

![offer](https://cloud.githubusercontent.com/assets/9845848/16268613/6ca366e8-388f-11e6-96bb-8b0935b7bbda.jpg)

![negative spread](https://cloud.githubusercontent.com/assets/9845848/16268385/8b12e046-388e-11e6-899f-1827fd85e5e5.jpg)

**Comment by tkemmere** [comment]
![fail](https://cloud.githubusercontent.com/assets/9845848/16268773/e895af54-388f-11e6-82c9-4cc7334701ff.JPG)

**Comment by ManfredKarrer** [comment]
Hm, is same offer id as https://github.com/bitsquare/bitsquare/issues/502.
Did you lose the take-offer fee (you can see it in funds/transactions)?

I made a change for the new version (not deployed yet, but soon) to reduce the risk that this can happen.
The price is really stange though...

I cannot see the offer though, but will keep an eye on it.

**Comment by tkemmere** [comment]
Indeed same id as #502. I'm not surprised that more than only I tried. The offer was 'too good to be true', Over a hundred euro under marketprice. It must have been a mistake by the seller. Could it be that you can't see the offer because the seller realised that it was a mistake and he/she **withdrew** it, **yet** it is still visible for (amongst others) me and martysto of #502? While it was actually long gone?

I confirm I lost 3 x 0,001 btc to 1FdFzBazmHQxbUbdCUJwuCtR37DrZrEobu = € 1,67 @ 555.

**Comment by ManfredKarrer** [comment]
I suspect the user has an old version where there was a problem with getting the arbitrator data. the check for the arbitrator is unfortunately after the fee payment in the current version (fixed in the new verison), so that might be the case. do u see the offer right now? I dont get the offer anymore. He could have canceled the offer or is offline...

**Comment by tkemmere** [comment]
No, the offer is not visible anymore.

**Comment by bitsgh** [comment]
I just hit the same problem trying to accept an offer (except the offer I was trying to accept has a fairly reasonable price).  I also closed the program, restarted, tried again, and got exactly the same error.  I seem to have lost 2 x 0.001BTC.  I'll guess that I won't be 3rd time lucky?

**Comment by ManfredKarrer** [comment]
Seems that the other user has still not updated to the new version, the 0.4.8. version caused a bug. 
Do you remember the offer id/price/currency?

**Comment by bitsgh** [comment]
The offer ID I was given during my second attempt was: 9f361023-4861-4765-b630-dd17518c07e4.  I presume this will be the same as the one from my first attempt too?  That offer is still standing at the time of writing - the only current "National Banks" offer for BTC in exchange for GBP.  Hope this helps.

**Comment by ManfredKarrer** [comment]
I just tried it as well and got the same timeout. So I assume he has either the old version or it is another issue which will be fixed in the next version. Sorry cannot do anything atm. In the next version I have added some protection against such cases.

**Comment by bitsgh** [comment]
Ah well, thanks for confirming!  Hopefully I'll be able to free up some time to help out with dev work.  Really love what you have built here!

**Comment by ManfredKarrer** [comment]
That would be great! There is plenty to do :-)
