### ISSUE TITLE
Buy tx are recorded as sell tx and vice versa

### ISSUE THREAD

**Issue by mpolavieja** [bisq-network/bisq#5035]
### Description

Transaction side (Buy/Sell) is recorded backwards on Portfolio History and also when exporting transactions to csv

#### Version

This happens on current version v.1.5.3, but it seems that this is a bug from version 1.1.5 and previous versions (August 2019), so transactions made with those versions are wrongly recorded in the database, so they are still wrongly shown at Portfolio / History in current versions.

### Steps to reproduce

You need to have transactions previous to August 2019.  Go to Portfolio / History and pick a transaction older than August 2019. See below how at the top Bisq says I am the buyer, but in the payment details it says I am the seller.  I have checked it with the bank and I was the seller.

![image](https://user-images.githubusercontent.com/17677608/103409827-d8bed880-4b68-11eb-8f81-e6e0107f0db1.png)

 

### Expected behaviour

To correctly record and show buy transactions as buy transactions and sell transactions as sell transactions

### Actual behaviour

Old transactions (older than august 2019) are showed with the side reversed.  This is also happening when exporting those transactions to csv.  Most transactions prior to that date have the side reversed, but there are just a few that are correct. I have not figured out any pattern so far. 

#### Device or machine

Windows 7

**Comment by ghost** [comment]
Could it be that you have imported your bisq directory to a new machine?  I see similar effects after importing Bisq `db` directory from one machine to another.  My original machine shows the trade correctly, the new one shows the trade maker/taker reversed.
For example, in trade details:

    Trade 7802846 You are: BSQ seller (maker) / Taker is: BSQ buyer   <=== original machine
    Trade 7802846 You are: BSQ buyer (taker) / Maker is: BSQ seller   <=== new machine (imported db)

Everything else (txids etc) is displayed correctly.  The trade contracts match exactly.  

I'll continue investigating.

**Comment by mpolavieja** [comment]
I have a CSV file generated in August 2019 where all the trade sides are already reversed.   At that date I changed the ubication of my window user folder to another drive, and I am almost sure that I generated the CSV before that folder structure change (not completely sure, though).   At this moment I am accessing those trades after restoring a back-up for that date, but as I said, the old CSV file shows the same problem.

**Comment by ghost** [comment]
Bisq compares the identity key (AFAIK your onion) stored in the Bisq directory (`share/Bisq/btc_mainnet/keys`) with the `pubKeyRing` stored in the offer payload.  If they don't match it assumes you are not the maker.  Therefore if your key has changed, Bisq no longer recognizes offers you made using an older onion as your own, and therefore those offers may have the maker/taker information reversed because for offers in which you were the maker it will assume you were the taker.
See `TradeManager.java:isMyOffer()`

**Comment by mpolavieja** [comment]
Ok, but that's a bit weird. Shouldn't the side (buy or sell) and the taker/maker property of the transaction in the historical data be a fixed data like the price, the amount in BTC or Fiat, etc... instead of being dynamically calculated?  Is there some reason to have that historical data dynamically calculated?

**Comment by ripcurlx** [comment]
Don't know anymore if there is a reason for using the `pubKeyRing` to find out if it is my offer or not, but I think it is to make the data structure more flexible using it on both sides of the trade.

**Comment by mpolavieja** [comment]
Is this fixed now?
