### ISSUE TITLE
Error on https when accessing the bitsquare forum

### ISSUE THREAD

**Issue by agardener** [bisq-network/bisq#504]
https://forum.bitsquare.io/t/using-bitsquare-in-mainland-china/214

I am getting a invalid certificate error when attempting access the forums.  I am using a recent copy of chrome on android, I did not have issues accessing the same link last week.   Thanks!

**Comment by ManfredKarrer** [comment]
Thanks for reporting! Is it only Chrome/Android or any other browser as well? On my OSX desktop all browsers are fine with it.

**Comment by agardener** [comment]
Weird.... Its working now.  I'll reopen if it happens again.
