### ISSUE TITLE
Add filter option of "Takeable trades"

### ISSUE THREAD

**Issue by Conza88** [bisq-network/bisq#5043]
I have a variety of account types, as I suspect, almost everyone does... instead of having to constantly filter between "currency" and "payment method" for different currencies/methods etc... 

**It would be fantastic if there was an option to: _only_ show ALL takeable / acceptable trades across Bisq... whether that is BUY, and then also for SELL.**

That way with transferwise across all fiat currency platforms / Amazon gift card / national banks / same banks etc. I could automatically and easily see as default all 'takeable trades'. 

This also addresses the issue of folks seemingly only looking at their local EUR market for instance, although with a transferwise account - they can essentially have access to all other transferwise offers. Most don't seem to be filtering to this option yet, and this gives more exposure to others that are immediately acceptable. 

EDIT:

Just realised this is slight replica of: https://github.com/bisq-network/bisq/issues/4945

**Comment by pazza83** [comment]
I think this is a good idea and would fit in well with https://github.com/bisq-network/bisq/issues/4945

A extra option on the Buy BTC / Sell BTC would be good.

Have you tried selecting show all for currencies / and show all for payment methods. 

![show all - Copy](https://user-images.githubusercontent.com/66367547/103450369-4b38d100-4cad-11eb-9c11-f25cb6424c13.png)

It also works well when selecting my multi-currency payment method such as Transfer or Revolut.

A 'Show takeable' option would work well here in payment method.

**Comment by Conza88** [comment]
I think that's it, currently a "show all" option as shown above... _**then logically, a "Show all available" / "Show all takeable"**_

Then you have the standard specific stuff. Ideally I think international highlighted (e.g. transferwise, SWIFT [when in] etc.) but that's likely a separate matter. 

* I do toggle between "show all currencies" and "Payment method: transferwise" etc, or just e.g. AUD / payment method: show all... but various other combo's just want to see all the SELL offers I can take immediately across all markets, and same with BUY...

**Comment by pazza83** [comment]
Hi @Conza88, @chimp1984 has done the following: 
[Add toggle for hiding not takable offers
#5048](https://github.com/bisq-network/bisq/pull/5048)

Let him know your comments 😃

**Comment by Conza88** [comment]
Ha, excellent. That's better I suspect. To include own offers, I suspect - yes - that would be wanted? Although not technically 'takeable' (but can action i.e. 'remove')
