### ISSUE TITLE
Add a 'payment method details' screen in Bisq client

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#5049]
### Description

Bisq has a section that shows active offers per currency. It is in a screen called 'details'

It would be great if Bisq had a section that shows active offers per payment  method. 

I proposed the current screen called 'details' to be renamed to ' currency details' and a new screen to be added called 'payment method details'

### Benefits

It would be great for Bisq users to see how many deals are available for what particular types of payment methods eg; Zelle, Revolut, TransferWise.

This would help traders see what is currently popular / available. It might prompt traders to create / add payment methods that are popular to their Bisq client. 

It would also be really useful to my role of Payment Maintainer when generating reports of payment method activity. 

#### Version

1.5.4

### Actual behaviour

On Bisq client

Market > Details

### Expected behaviour

On Bisq client there to be two options

Market > Payment Method Details

Market > Currency Details

### Screenshots

![Add payment method details](https://user-images.githubusercontent.com/66367547/103471902-2eb89980-4d7e-11eb-8ee6-bc0e42a39410.png)

**Comment by Conza88** [comment]
Yes indeed 💯

**Comment by ghost** [comment]
Is this what you had in mind? (screenshot)

![image](https://user-images.githubusercontent.com/47253594/103474183-de820d00-4d66-11eb-814e-f893a55d4ef1.png)

**Comment by Conza88** [comment]
Possible to group methods? E.g. transferwise stats across entire method, then if someone wants to see specific markets they can?

**Comment by pazza83** [comment]
> Is this what you had in mind? (screenshot)

Yes, that would be perfect. 

I agree with @Conza88 grouping would be great. Similarly to how it is done in the growth-alterts Keybase channel.

![grouping - Copy](https://user-images.githubusercontent.com/66367547/103483610-52acc700-4de0-11eb-905f-f62de71a650b.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/47253594/103490621-c223b600-4de2-11eb-8620-dad9da8e1c1a.png)

----

![image](https://user-images.githubusercontent.com/47253594/103490631-d2d42c00-4de2-11eb-9444-90994b77ec82.png)

**Comment by pazza83** [comment]
@jmacxx that would be perfect.  I like the toggle also!
