### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by bluesteal** [bisq-network/bisq#5058]
This .deb crashes upon launch consistently on both debian and Whonix.

what's the path to logs files?

**Comment by bluesteal** [comment]
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000c31b0000, 97845248, 0) failed; error='Not enough space' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 97845248 bytes for committing reserved memory.
# An error report file with more information is saved as:

**Comment by bluesteal** [comment]
How much memory does this app use?

**Comment by T3rm1** [comment]
I have the same problem. After 2 minutes the program uses more than 4GB of memory. This can't be right.

**Comment by pazza83** [comment]
I am finding that the Bisq is crashing a little more frequently.

If I leave it running overnight (no other activity) it will crash about 1/3 times.

If I am running multiple programmes it is also likely to crash.  For example I used to be able to make Zoom calls while Bisq was running. Now I often close Bisq if I need to use Zoom. It is similar if I also run any other memory intensive apps.

**Comment by cd2357** [comment]
This should be fixed with the latest version (v1.6.4) which upgrades several UI libraries and dependencies, which in turn use less system resources (especially RAM).

Please try it out and let us know if this is still an issue for you.
