### ISSUE TITLE
Need help trade hung up for almost a week, cannot communicate with moderator.

### ISSUE THREAD

**Issue by alphaonion** [bisq-network/bisq#5060]
### Description
Trade: evQfA6
Mediator: apbp7ubuyezav4hy.onion
half of the trade is locked in multisig and there is no communication with any mediator.
I also believe this is a bug and can be used against bisq.  Trade is stuck on both sides.

#### Version

bisq 1.5.4-1

**Comment by ripcurlx** [comment]
Your mediator should be @bisq-knight based on the onion address you provided. Could you please join the support channel on Keybase for further support? Thanks!

**Comment by alphaonion** [comment]
Having a problem with finding support on keybase.  I have the software and keys setup but all i see is an admin by the name of wiz who i don't have permission to contact. I don't see any support section.

**Comment by ripcurlx** [comment]
That is the team on Keybase: https://keybase.io/team/bisq
After joining the team you can browse all channels (see under cog icon). There should be a #support channel to join.

**Comment by cd2357** [comment]
@alphaonion since the last comments here were so long ago, I assume you already coordinated with someone from support on Keybase.

If not, let us know and we'll see the next steps.
