### ISSUE TITLE
Show mediation summary to the trader who did not open arbitration

### ISSUE THREAD

**Issue by refund-agent2** [bisq-network/bisq#5062]
### Description

The part who opens arbitration receives the mediation report when opening an arbitration ticket. The other does not.

### Steps to reproduce

Reject mediation suggestion.

### Expected behaviour

Display mediation summary to both traders.

**Comment by ripcurlx** [comment]
@chimp1984 I think we talked about this already, but I don't remember anymore what the reason was to do so.

**Comment by chimp1984** [comment]
I think there was some technical reasons which made it difficult to access that data, dont remember details though...

**Comment by Conza88** [comment]
Definitely makes sense to do

**Comment by pazza83** [comment]
This is closed but I think the other peer will already have the mediation summary report from the mediation proposal?
