### ISSUE TITLE
1.5.4 throws more errors than ever

### ISSUE THREAD

**Issue by bathrobehero** [bisq-network/bisq#5064]
I'm not even going to list individual errors but 1.5.4 shouldn't have gone live as it is!

It threw me dozens but 8 different error messages in a couple of hours. It accidentally accepted two of the same trades and I can't even reply to the owner as it throws yet another java error. And then there are "trade protocol encountered a serious problem",  "missing required transaction", "trade is in invalid state", sprinkled with "N/A" and tons of timeouts and lag and retroactively duplicated actions and it's just absolutely awful and probably even unsafe to our funds to use. There are transaction under "open trades" but nothing is happening if I click on anything, can't do anything (but hey, the buttons just doesn't do anything instead of errors). There's a constant siege of error messages, all cutely suggesting to post here. You have to arm wrestle with the client with every command against all the errors and even then it won't do what you wanted.

I really appreciate all that you have done but this version should have never made it live in its current form.

**Comment by T3rm1** [comment]
Bisq is a mess and is unusable for quite some time now. It is not beginner friendly, the UI is unintuitive and the whole program is slow and laggy. After 2 minutes it already uses more than 4 GB of memory. Development is slow, there is barely any developer communication and it seems there is no person on the team who knows how to do things right. Most of the last commits come only from 2 developers. The idea of Bisq is awesome but the implementation is not. I think this project is dead.

**Comment by Conza88** [comment]
Most trades ever done lately and no issues. More volume than ever before as well AFAIK through Bisq? Project is dead?! 

Laughably _**bad**_ take.

**Comment by ripcurlx** [comment]
> I'm not even going to list individual errors but 1.5.4 shouldn't have gone live as it is!
> 
> It threw me dozens but 8 different error messages in a couple of hours. It accidentally accepted two of the same trades and I can't even reply to the owner as it throws yet another java error. And then there are "trade protocol encountered a serious problem", "missing required transaction", "trade is in invalid state", sprinkled with "N/A" and tons of timeouts and lag and retroactively duplicated actions and it's just absolutely awful and probably even unsafe to our funds to use. There are transaction under "open trades" but nothing is happening if I click on anything, can't do anything (but hey, the buttons just doesn't do anything instead of errors). There's a constant siege of error messages, all cutely suggesting to post here. You have to arm wrestle with the client with every command against all the errors and even then it won't do what you wanted.
> 
> I really appreciate all that you have done but this version should have never made it live in its current form.

So you didn't experience this issues in previous versions?
If developers should be able to fix stuff, making proper bug reports is the only way being able to re-produce this bugs.

**Comment by ripcurlx** [comment]
> Bisq is a mess and is unusable for quite some time now. It is not beginner friendly, the UI is unintuitive and the whole program is slow and laggy. After 2 minutes it already uses more than 4 GB of memory. Development is slow, there is barely any developer communication and it seems there is no person on the team who knows how to do things right. Most of the last commits come only from 2 developers. The idea of Bisq is awesome but the implementation is not. I think this project is dead.

Feel free to contribute on your own to make Bisq better. Just posting this kind of stuff will change nothing.
