### ISSUE TITLE
Disorienting warnings during BSQ sending of funds

### ISSUE THREAD

**Issue by Stam57** [bisq-network/bisq#5067]
### Description

After I took an offer to sell BSQ and asked to start the transfer of funds, I entered the BSQ amount and the buyers address in the appropriate fields in the SEND page of the DAO tab and I pressed "SEND BSQ FUNDS.
A pop up window appeared asking me to enter my password to verify the sending of funds.
After I entered correct the pass, the fields "Receiver's BSQ address" and "BSQ amount to sent" became red informing me that "empty input is not allowed".
That made me think that for some reason after I entered my pass the fields were cleared and I had to re-enter the values.
I did it and I sent the same amount to the same address twice!
Can you please correct that and instead of making red the fields, show a message of successful sending?

#### Version

1.5.4

### Steps to reproduce

- Take offer to sell BSQ
- Go to DAO tab
- Enter amount and receiver's address in appropriate fields and press "Send BSQ Funds"
- Pop up window appears asking for password to verify sending
- Enter password correctly
- Password pop up window closes and fields "Receiver's Address" and "Amount to Withdraw" immediately become red with a notice underneath "empty input is not allowed".

### Expected behaviour

It would be more clear if instead of turning the fields red and showing the "empty input is not allowed" notice, for a pop up window to appear informing whether the password was correct and the withdrawal successful (or initiated). Maybe even a prompt to check the "Transactions" tab and see if the transaction has started.

### Actual behaviour

The red fields and the warning notice under the fields gives the impression that something went wrong. In my case I thought that I had to first enter my password and then enter the input in the fields, so I did the withdrawal twice.

### Screenshots

![Red_Fields](https://user-images.githubusercontent.com/25206145/104080935-3915e000-5223-11eb-96cb-cd45bd79722d.jpg)

#### Device or machine

Desktop PC, Windows 10

#### Additional info

I can always upload the bisq log files if it is necessary.

Thanks for your help!

**Comment by ghost** [comment]
Thanks for the report.  I'm working on a fix for this, will be submitted tomorrow.
