### ISSUE TITLE
Compile issue: BountyCastle not found

### ISSUE THREAD

**Issue by Z819** [bisq-network/bisq#507]
Hi,

I did
    `$ apt-get install maven`

and after a first run I indeed had a `$HOME/.m2` directory, but there was no such thing as a `bcprov-jdk15on-1.53.jar` file. I have zero knowledge about maven so I gave up at that point.

**Comment by ManfredKarrer** [comment]
you need to run bitsquare once so it resolved the BountyCastle jars. after then copy it to the ext dir and when the setup is complete, rung bitsquare again.
I know it's cumbersome but I did not had time to investigate better solutions. Maybe some build system guru can help out to get that easier....
