### ISSUE TITLE
attempting to take trade, error "Lock time of maker is more than 3 blocks different to the lockTime I calculated."

### ISSUE THREAD

**Issue by northben** [bisq-network/bisq#5073]
### Description

Attempted to take a trade, received error:

An error occurred when taking the offer.

An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 668400, myLockTime=668413

No funds have left your wallet yet.
Please try to restart your application and check your network connection to see if you can resolve the issue.Please try to restart your application and check your network connection to see if you can resolve the issue.

#### Version

v1.5.4

### Steps to reproduce

attempt to take a trade

### Expected behaviour

the trade should progress to the next step

### Actual behaviour

the error message above is displayed

**Comment by ripcurlx** [comment]
@northben It seems to be your possible trading peer is not in sync right now. This could be related to the tor issues we saw recently. Should fix by itself soon. Please re-open this issue if you continue to see this problem.
