### ISSUE TITLE
Bisq won't launch and update

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#5075]
### Description

Bisq won't launch. After login it shows the screen of how many Bitcoin network peers are established. But it won't continue from that. I tried several times. Yesterday, it worked once but I couldn't do trades as my version was outdated. I was not prompted to update to a newer version.

#### Version

1.3.9

### Expected behaviour

Launching and prompting to update 

### Actual behaviour

gets stuck and doesn't prompt to update

### Screenshots

![grafik](https://user-images.githubusercontent.com/66221034/104185758-b30dbb00-5415-11eb-93dc-31d6339965c3.png)

#### Device or machine

hp envy bw00xxx, Windows 10 version 10.0.19042

**Comment by ripcurlx** [comment]
@sturmsignal Could you please manually download and verify the current release [v1.5.4](https://github.com/bisq-network/bisq/releases/tag/v1.5.4) and try to start again?

**Comment by ghost** [comment]
Ok, worked that way. Wasn't sure if a new installation would overwrite my profile, account settings etc.
Thank you.
