### ISSUE TITLE
Wrong program icon flashes when alt-tabbing in Windows 10

### ISSUE THREAD

**Issue by nonremittal** [bisq-network/bisq#5085]
### Description

When alt-tabbing in Windows 10, the program icon for Bisq is displayed as the default program icon for a few frames.

#### Version

1.5.4

### Steps to reproduce

Hit Alt + Tab while in a different application.

### Expected behaviour

Bisq displays the correct icon.

### Actual behaviour

Bisq instead displays the default Windows program icon.

### Screenshots

![alt-tab](https://user-images.githubusercontent.com/58081816/104821879-daf68780-5836-11eb-85d6-11466e16ee34.jpg)

#### Device or machine

Windows 10

**Comment by ripcurlx** [comment]
I'll test it when I test the new Windows builds (using wix). Maybe this is fixed automatically because of this build setup change.
