### ISSUE TITLE
Navigation Responsive Layout

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/bisq#5086]
### Description
I've been noticing a lot of users using the client in fullscreen or constantly resizing the width of the window. The layout of the navigation looks broken whenever the width goes beyond the default on load. It would look a lot more polished if we keep the navigation contained in its original width.

#### Version
1.5.1

### Expected behaviour
Navigation should have a maximum width so we maintain equal distances between elements.

### Actual behaviour
Navigation elements align to the edges of the container.

### Screenshots

![00 Overview](https://user-images.githubusercontent.com/807505/104861643-b6fe7900-58fe-11eb-9cbd-4a8dacdc841e.png)
![01 Current Default Width](https://user-images.githubusercontent.com/807505/104861644-b6fe7900-58fe-11eb-8599-4995b237879a.png)
![02 Current Increased Width](https://user-images.githubusercontent.com/807505/104861645-b7970f80-58fe-11eb-9355-b7ed25217756.png)
![03 Proposed with max width](https://user-images.githubusercontent.com/807505/104861646-b7970f80-58fe-11eb-89ed-02a5bb762ffe.png)

**Comment by Conza88** [comment]
This is also me using max width, and it looking weirdly space. 
Great work.

**Comment by ripcurlx** [comment]
That was an easy fix 😉
