### ISSUE TITLE
Open Trades View contains duplicates

### ISSUE THREAD

**Issue by viciousvex** [bisq-network/bisq#5088]
### Description

Sometimes a the list of trades in the trade view contains duplicates in row n+2 and n+3 (where n is the number of open trades).

#### Version

1.5.4

### Steps to reproduce

Confirm a payment with the "open trades" view open. 

### Expected behaviour

The confirmed trade should be gone from the "open trades" view.

### Actual behaviour

The "open trades" list gets corrupted and shows the confirmed trade at position n+2 as duplicate of n, followed by another trade at n+3 as duplicate of n-1 (see screenshot). 

### Screenshots
![bisq-open-trades-view](https://user-images.githubusercontent.com/1662172/104916171-fb872480-5991-11eb-8a17-bee560f97871.png)

#### Device or machine

OS Name	Microsoft Windows 10 Pro
Version	10.0.18363 Build 18363
System Type	x64-based PC

**Comment by ripcurlx** [comment]
This looks like a rendering issue. Maybe some recent changes didn't clean up everything properly in the list.

**Comment by cd2357** [comment]
Should be fixed with the latest release (v1.6.4). It upgrades several UI libraries and frameworks that should address such rendering issues.

Please try it out and let us know if this is still an issue for you.
