### ISSUE TITLE
Bisq won't start because denies itself permission to run TOR

### ISSUE THREAD

**Issue by dchmelik** [bisq-network/bisq#5095]
### Description

Bisq won't start because denies itself permission to run TOR.

#### Version

1.4.n to 1.5.4
### Steps to reproduce

1. Start Bisq even fresh (no ~/.local/share/Bisq)
2. Denies itself permission to run TOR.

### Expected behaviour

Run TOR right or don't force people to use it.

### Actual behaviour

Doesn't run TOR and can't opt-out.

### Screenshots

![Screenshot_20210119_165740](https://user-images.githubusercontent.com/10347890/105115497-c526d380-5a7d-11eb-9094-a9ba3da9df11.png)

#### Device or machine

KDE Neon GNU/Linux (based on Ubuntu 20.04) Intel Core i7 CPU desktop.

**Comment by wiz** [comment]
That distribution of Linux isn't officially supported, so when you can figure out how to fix it please submit a PR and write an article for the wiki

**Comment by davij** [comment]
Same thing seems to be happening to me on Windows 10.  Everything was working fine a month ago now all of a sudden bisq is stuck WTF?!?! is bisq turning into windows inc.? 

I have waited 3 hours to see if it loads no luck. Would reinstalling make a difference?? Please help us.

**Comment by dchmelik** [comment]
I knew it wasn't something specific to KDE Neon (as if I should fix it.)  All they do is update KDE as if a newer Kubuntu.  Behind that it's the stock Ubuntu 20.04 (KDE claims Neon "isn't even a distribution.")  Turns out it wasn't even something specific to GNU/Linux...

**Comment by cd2357** [comment]
@dchmelik @davij is it still happening with the latest version? The tor version has been updated.

**Comment by dchmelik** [comment]
> @dchmelik @davij is it still happening with the latest version? The tor version has been updated.

In Bisq 1.6.2 on KDE Neon GNU/Linux 5.21 (simply like Kubuntu 20.04 with newer KDE, nothing behind that changed) it still happens... also I built Bisq on Slackware GNU/Linux 15β and it seems it might start to work on that.
