### ISSUE TITLE
Add Notification icon for Mediation and Arbitration chat

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#5097]
### Description

Add a chat icon for notification on new messages to the Mediation and Arbitration chats like the one on the Trader's chat.

![chatNotification](https://user-images.githubusercontent.com/44140017/105354275-3c787680-5be8-11eb-880a-1d043841ab17.png)

**Comment by pazza83** [comment]
Yes, I think this would be good.

I think it would also be good to pull in the avatar for the mediator. So it is easy to see what mediators you have that are dealing with which cases.

**Comment by Conza88** [comment]
Great. Also tangentially related to: https://github.com/bisq-network/bisq/issues/5074 any 'action icons' similar to be added to the tab at the top of "Support"? 

![image](https://user-images.githubusercontent.com/51952482/106219905-7a038200-622e-11eb-999d-01175dbf624b.png)

**Comment by Conza88** [comment]
Q - what is the record of those chats after the event is finished? Auto delete or sit on a harddrive somewhere?

**Comment by pazza83** [comment]
The new update has names on the mediators which I think is a good improvement 👍 

It also has names for the arbitrators but I think refundagent1 is showing as 'N/A'

**Comment by huey735** [comment]
@Conza88 currently sit on the hard drive of the traders and the Mediator responsible for the dispute. Also on the Arbitrators if the trader reaches that stage.

**Comment by pazza83** [comment]
@huey735  Where can users access past trader chats? Someone was asking how to do this on Keybase.

**Comment by huey735** [comment]
Oh, I thought you meant Mediator's chat. Trader's chat are discarded with the end of the trade.

**Comment by pazza83** [comment]
Thanks

**Comment by ghost** [comment]
@huey735 @refundagent2 would this be an acceptable approach:

- Notification of new chat messages (as requested).
- Details icon shows the dispute summary view.
- Process icon shows the dialog which allows you to suggest / payout (same as "Close Ticket").
- Chat pops up the chat window with the user (similar to trader chat).
- There is more vertical space to display the list of tickets.

![image](https://user-images.githubusercontent.com/47253594/107539766-e8c7d000-6b8a-11eb-8e0b-713cfef9fc61.png)

**Comment by Conza88** [comment]
Also related imo: https://github.com/bisq-network/bisq/issues/5044 **Add ability for mediator's & arbitrator's to see "Trader Chat" (upon escalation)**
