### ISSUE TITLE
Specify Amazon eGift Card country

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#5098]
### Description
I can't buy a gift card on amazon.de to send to someone whose email is for an account on amazon.fr. It's important that the sender buys the Amazon eGift Card on same country site as the receivers. This is easily circumvent because any user with an Amazon account can simply log onto different Amazon sites and buy the gift card there. So maybe we don't need to restrict this payment method by countries but it should be explicit to the BTC buyer what Amazon website the BTC seller is using.

@chimp1984

**Comment by pazza83** [comment]
Thanks for documenting this issue. 

I know of another similar case that ended in arbitration.

I will investigate and come up with a solution for it.

**Comment by pazza83** [comment]
Hi @huey735 

I propose solving this by adding in the 'currency selection - drop down combo' same as in the national bank account payment account.

Only selectable options to be:

- Australia - AUS - https://www.amazon.com.au
- Canada - CAD - https://www.amazon.ca
- France - EUR - https://www.amazon.fr
- Germany - EUR - https://www.amazon.de
- Italy - EUR - https://www.amazon.it
- Netherlands - EUR - https://www.amazon.nl
- Spain - EUR - https://www.amazon.es
- United - Kingdom - GBP - https://www.amazon.co.uk
- India - INR - https://www.amazon.in
- Japan - JPY - https://www.amazon.co.jp
- Saudi - Arabia - SAR - https://www.amazon.sa
- Sweden - SEK - https://www.amazon.se
- Singapore - SGD - https://www.amazon.sg
- Turkey - TRY - https://www.amazon.com.tr
- United - States - USD - https://www.amazon.com

_The above are the only local Amazon accounts that allow users to purchase and send Amazon eGift cards._

**Current Amazon eGift Card Payment Account**

![amazon current](https://user-images.githubusercontent.com/66367547/105657326-03782480-5ebc-11eb-9241-5a15705b99e8.png)

**Proposed Amazon eGift Card Payment Account**

![amazon proposed](https://user-images.githubusercontent.com/66367547/105657338-0b37c900-5ebc-11eb-8528-a40601b19ee6.png)

The country code would then be displayed on the offer (same way SEPA is).

- Pop-up to be added when taking the offer to inform client to send using specified Amazon account
- [Wiki ](https://bisq.wiki/Amazon_eGift_card) to be updated  to inform client to send using specified Amazon account

Let me know if you think that would work. If so I will check with devs that it can be implemented.

**Comment by huey735** [comment]
This seems reasonable. It's important that it doesn't stop a Alice with account from France to take an offer from Bob, who's in Germany. Given that Alice could simply log in to amazon.de and send the gift card.

**Comment by pazza83** [comment]
No it would not stop the trade. It would still appear on the EUR market. It would just make Alice aware Bob's Amazon account is a German one so she should log in to https://www.amazon.de to make payment.

Are any @bisq-network/bisq-devs available to make this update?

**Comment by ghost** [comment]
> Are any @bisq-network/bisq-devs available to make this update?

I'll give it a shot.

**Comment by ghost** [comment]
Since existing Amazon payment accounts do not have country information, users will have to delete and and re-add them with the appropriate country.

We could pop up a message if any old Amazon payment accounts are found, informing users of the need to do this.

And also check to prevent offers / trading on the old invalid account format.

**Comment by pazza83** [comment]
Ok, hope that is not too big a job.
