### ISSUE TITLE
Test environment for TomP2P

### ISSUE THREAD

**Issue by bisq-network** [bisq-network/bisq#51]
Test a cluster of TomP2P nodes in real life conditions.

**Comment by cbeams** [comment]
@ManfredKarrer I've removed the v0.1 milestone from this issue. It seems to me that v0.1 will be our first test environment for TomP2P, i.e. given everything else necessary to be done, we probably won't have time for this. Agree?

**Comment by ManfredKarrer** [comment]
yes, fine!

**Comment by ManfredKarrer** [comment]
TomP2PTests is a start for getting a testing suite.

Test result report at TomP2P GH see here: https://github.com/tomp2p/TomP2P/issues/57

Asking at the mailing list if anyone knows about a testing framwork:
http://lists.tomp2p.net/pipermail/users/2014-November/000419.html

**Comment by ManfredKarrer** [comment]
Closed as related to TomP2P which is not used anymore.
