### ISSUE TITLE
GUI error: can't order the offers per "Amount in BTC" or "Price"

### ISSUE THREAD

**Issue by gustavklopp** [bisq-network/bisq#510]
config: Ubuntu 64bit, Bitsquare 0.4.8

step to reproduce the bug:
tab "Sell BTC"
Do not modify the filter (by currency or by payment method)
Click on "Amount in BTC (Min)", or "Price": nothing happens.
Clicking on "Amount (Min)" or 'Payment method" do activate the ordering of the list.

You can modify the "filter by payment method": Same result.

But: choosing in the "Filter by currency" any choice as "Euro (EUR)"
Clicking on "Amount in BTC (Min)", or "Price" do activate the ordering as expected.

**Comment by ManfredKarrer** [comment]
That is intended because when you have selected "show all currencies" you get mixed prices, so a sorting does not make sense. The price sorting is only applies when you have selected a currency and then in the way that the best offers are on top.
