### ISSUE TITLE
"An error occured at task: MakerProcessessInputsForDepositTxRequest" 

### ISSUE THREAD

**Issue by ThisMightHelp** [bisq-network/bisq#5102]
### Description

Not sure if this is a bug, but was suggested to open a new issue. "Taker's trade price is too far away from our calculated price based on the market price. The trade protocol encountered some problems. The trade contract is not set. The trade cannot be completed and you might have lost your trade fee. If so, you can request a reimbursement for lost trades"

#### Version

1.5.4

### Steps to reproduce

 One time occurrence overnight while my offer (maker buy) was open.

### Expected behaviour

 Accept the seller's offer.

### Actual behaviour

Error message above.

#### Device or machine

Dell laptop, Win 10 Pro

**Comment by ThisMightHelp** [comment]
Request trade fee reimbursement.

**Comment by huey735** [comment]
Probably due to bad price node data. Try restarting your Bisq client. Please reach out to me on Keybase (https://keybase.io/team/bisq) for logs. Identify yourself by trade ID and role (BTC seller/buyer, maker/taker). I'm huey735.

**Comment by ThisMightHelp** [comment]
Thanks. New to keybase, installed the Windows app, and having an issue opening up a chat. The New Chat window is Loading... I'm bloodrestriction.

EDIT: I installed the keybase app, opened it, and getting: https://postimg.cc/fkKgWy0x

**Comment by cd2357** [comment]
@ThisMightHelp did you manage to coordinate with @huey735 on keybase? If yes, we can close this issue here.
