### ISSUE TITLE
Clean up Explorer Overlay Selection Trigger

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/bisq#5106]
### Description

In settings, to edit the explorers, the button that tiggers the overlay doesn't match the rest of the design.
Can we:

- Adjust the color and the height
- Center the type vertically on the container
- Add padding between the 2 elements

#### Version

1.5.4

![Frame 1](https://user-images.githubusercontent.com/807505/105564715-610c4580-5cf1-11eb-97aa-174bbc1f2f7e.png)
![Frame 2](https://user-images.githubusercontent.com/807505/105564716-610c4580-5cf1-11eb-845a-ece180a7873f.png)

**Comment by ahmedadan** [comment]
Is this something I can actively participate on?

**Comment by chimp1984** [comment]
@ahmedadan Sure if you can fix that your contribution is very welcome!

**Comment by ahmedadan** [comment]
@chimp1984 Do you happen to have the CSS used to style the button in the above example?

**Comment by chimp1984** [comment]
I am not very familiar with the CSS and UI code. But yes there is a css...

**Comment by ahmedadan** [comment]
I've found were to make the edit, I will just try to replicate the look using trial and error
