### ISSUE TITLE
Remove borders on separators in main nav

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/bisq#5107]
### Description

The navigation would look cleaner and more up to date if we clean out the small lines in between the elements.
I really don't think we need them.

#### Version

1.5.4

![Frame 3](https://user-images.githubusercontent.com/807505/105564918-438bab80-5cf2-11eb-9ebe-80552bd0b89f.png)
![Frame 4](https://user-images.githubusercontent.com/807505/105564920-44244200-5cf2-11eb-88c6-d4b40af0c415.png)

**Comment by AdrianMirica** [comment]
Hello, I want to help this project and I want to know if this issue is still available?
Thanks

**Comment by ripcurlx** [comment]
> Hello, I want to help this project and I want to know if this issue is still available?
> Thanks

It is not a high priority task, but it is a good step to get into the project :smile:
