### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by GildedHonour** [bisq-network/bisq#5112]
I've run it on 2 modern machines and both times it's been barely usable due to being slow. Do you have plans to re-write it to a natively compiled language?

**Comment by ripcurlx** [comment]
It can be on first start when it is syncing the DAO that the app feels slow. Did you wait until DAO sync has finished?

**Comment by cd2357** [comment]
Should be fixed in the most recent release (v1.6.4) which brings several UI performance improvements and generally reduces system resource consumption. Please try it out and let us know if it's still an issue for you.
