### ISSUE TITLE
javax.imagio.IIOException: Can't create catch file

### ISSUE THREAD

**Issue by haraslub** [bisq-network/bisq#5113]
### Description

javax.imagio.IIOException: Can't create catch file

#### Version

Bisq-64bit-1.5.4

### Actual behaviour

The error pops up once I start the bisq app and bisq does not start running at all. 

#### Device or machine

Lenovo IdeaPad S540-14IWL
Win 10 Home

**Comment by ripcurlx** [comment]
@haraslub I see that it tries to access a temp file at following location: `R:\Local\Temp\imageio1765192458096170908.tmp` Does this location exist at all? It sounds as you have manually set the java temp directory to a location you don't have write access or just doesn't exist.

**Comment by haraslub** [comment]
@ripcurlx Thank you for the response and I am sorry for my late reaction. Yes, the problem is in the location. I have dedicated the part of my RAM memory for a Temp folder. Once I needed to reinstall something, I had to change the directory and after that I forgot to put it back. My bad. Anyway, thank you very much again.
