### ISSUE TITLE
timeout occurred

### ISSUE THREAD

**Issue by krynne** [bisq-network/bisq#512]
first two times I try to use bitsquare to buy btc and I'm down 2mBtc already with fees and two timeouts:
fee txid :
fd45ac83ddf215b6359b37974ebce4655d2d701926f4d5e9aa4771ddd343887c
and
668d1de219a748068a1daeaa72510100867111597765b5490b91b105a443bd1a

any hope to recover funds ?
what's wrong  (windows 10 + bitsquare 0.4.8) ?
Thx for your help

**Comment by ManfredKarrer** [comment]
There seems to be one trader who has either an outdated version, or some corrupted data. I fixed that issue for the next release so the checks which causes the rejection happens before the taker fee is paid.
If you send me an email (u find it on the webpage/contact) with a btc address I can refund you for that losses.

**Comment by ManfredKarrer** [comment]
Ah do you remember which offer has caused that? (offer id, price, currency)

**Comment by krynne** [comment]
Thx for your help.
Details sent by mail.
