### ISSUE TITLE
Can't take offer - Same bank DE

### ISSUE THREAD

**Issue by MarcSte** [bisq-network/bisq#513]
So there's an offer to buy btc which I can't take
<img width="657" alt="sb" src="https://cloud.githubusercontent.com/assets/9436375/16546344/b59e4d20-4147-11e6-8c1e-cc188a2b42f3.PNG">

From 'Bank Name' (BIC) I can tell that it's Fidor bank that I have an account with. This account is registered at the bitsquare client.

I have two fiat bank accounts linked in bitsquare. That should be the reason I get the following message:
<img width="415" alt="nmpa" src="https://cloud.githubusercontent.com/assets/9436375/16546366/405b2294-4148-11e6-90ac-2e602afeca95.PNG">

**Comment by ManfredKarrer** [comment]
Yes that is not supported atm. But should be improved.
If someone setup his account with same bank u cannot take if if u have sepa or any other, you would require an account wiht same bank selected as well. That same banks option was mainly used for countries with higher bank fees, smae bank is mostly free or very cheap then (eg. Brazil).

**Comment by MarcSte** [comment]
Ah ok, so I could use 1 bank account (eg FIDOR) as 'SEPA' account AND as 'Transfer with same bank'.

I agree, that is not very intuitive.

**Comment by ManfredKarrer** [comment]
Yes. I know it should be improved, but too much other stuff to do as well....

**Comment by haiqu** [comment]
You might also experience issues transferring into Fidor from other banks if your account is related to Kraken. There have been a number of frauds on their accounts and other banks refuse to deal with the Fidor Kraken account.
