### ISSUE TITLE
Integrate full blockchain nodes and wallets of every supported coin into Bisq

### ISSUE THREAD

**Issue by kevATin** [bisq-network/bisq#5135]
This would make a lot of sense to me given that you would no longer have to rely on third party nodes, which is not only a privacy advantage but also gives independence. Apart from that I could imagine having a local blockchain node and wallet being useful for automated trading and similar.
There would be no more need to set every node up yourself if Bisq came integrated with them.
Obviously this would have to be optional since it requires more than a terabyte of storage. Maybe users could also pick and choose which nodes they want to self host and which to connect to, during the first run setup of Bisq.

**Comment by cd2357** [comment]
Bisq already supports running a local BTC node. So that is already a good starting point for someone who wishes to customize their setup in this direction. See https://bisq.wiki/Connecting_to_your_own_Bitcoin_node

As for other blockchains, it's probably overkill for Bisq right now.
