### ISSUE TITLE
Error when clicking Open Dispute

### ISSUE THREAD

**Issue by pmknutsen** [bisq-network/bisq#514]
I have a single pending order that has passed the max period. When clicking Open Dispute I get this error:
`java.lang.NullPointerException`

Restarting BitSquare has no effect: the same error occurs when clicking Open Dispute after a fresh restart.

**Comment by ManfredKarrer** [comment]
Could you get in touch with me by email? (u find the email address on the webpage)

**Comment by pmknutsen** [comment]
Just did.
