### ISSUE TITLE
Low priority: reword the "HD Keychain Paths" text in "Account" tab

### ISSUE THREAD

**Issue by Conza88** [bisq-network/bisq#5143]
Wording on the below, highlighted needs some work...

![image](https://user-images.githubusercontent.com/51952482/106418916-6f095580-64ab-11eb-8331-d89c74f4056e.png)

Suggestion:

"NEVER send BSQ from another wallet, as that very likely leads to an invalid BSQ transaction and your BSQ will get burned."

**Comment by ripcurlx** [comment]
@m52go ☝️  What do you think?

**Comment by m52go** [comment]
Improvements to these strings are already merged. Can't find the exact PR at the moment, but it was likely merged just after the last release, so the next release will include the improvement.

https://github.com/bisq-network/bisq/blob/master/core/src/main/resources/i18n/displayStrings.properties#L1426

**Comment by Conza88** [comment]
Nice. Thanks.
