### ISSUE TITLE
Increase liquidity by allowing each offer to have multiple payment methods & currencies associated with it

### ISSUE THREAD

**Issue by Conza88** [bisq-network/bisq#5147]
This highlights [#288](https://github.com/bisq-network/proposals/issues/288) @[Pazza83](https://github.com/pazza83)'s proposal which builds on top of @wiz's proposal [#201](https://github.com/bisq-network/proposals/issues/201).

I won't replicate the threads but desire to draw attention to them (this repository gets more love than #[proposals](https://github.com/bisq-network/proposals)). Think this is a massive _MUST_ for Bisq. 

>_Liquidity wise - makes life a lot easier for traders / those selling BTC.
Their offers can be in ALL markets they want to be AT the SAME TIME... and ALL those in SMALL markets, locally - seeing offers available... a whole lot easier, its next level.

>I am not in EUR, but I sought out EUR offers - because of liquidity. I know sellers not in EUR, but sought out EUR because it became known as having liquidity.

>I know locals who join a small market, and lament NO offers etc. This solves all of these problems, and more folks sticking around - spruiking Bisq as a result._

The simple vision with e.g. Transferwise/SWIFT/Revolut that has multiple currency possibilities... instead of the offer only showing in ONE fiat market e.g. EUR, it would be shown in ALL selected FIAT MARKETS. This is a truer representation and for new folk who are ONLY looking at their local market (and seeing NO offers)... they would see the actual option. 

It would provide more accurate assessment of where each region is actually at in terms of bootstrapping e.g. because they can take the offer in their local market now, where they would have otherwise used other payment methods to try get in EUR, USD etc.  

I think this would have a bigger impact than continually trying to add new payment methods for #growth

**Comment by lestephane** [comment]
@all Is anyone already working on this in a feature branch?

**Comment by Conza88** [comment]
Noone is as far as I know.
