### ISSUE TITLE
Lock total fiat amount on buy bitcoin offer

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#515]
I think should have an option to lock total fiat amount on buy bitcoin offer. 
Ex: the total of bitcoins I'll buy could fluctuate, but the fiat amount I'll spend, needs to be the same.
Understand?

**Comment by bitcoinuser** [comment]
Hi,

Look at the video uploaded.

1- If I can't lock the fiat amount to spend, I think the field should not be "active"
2- If I can specify the fiat amount to spend, why the field (amount of bitcoin to buy) doesn't update?

My opinion: The field (amount in fiat to spend) should not be active. I think should, instead, have an field like: Never spend more than ..... in fiat money,
[Bitsquare.zip](https://github.com/bitsquare/bitsquare/files/391992/Bitsquare.zip)

**Comment by ManfredKarrer** [comment]
Upps thats a bug. I think once u change the fiat price it will work, but will have a look....
Good point regarding to lock the fiat field (to not make it editable). Will consider it...

**Comment by bitcoinuser** [comment]
Yes, when i change fiat price, it will work.
I think bitsquare should clone how kraken exchange works. See the video.
Obs. As you can see in the video, users can choose the fiat amount to spend.
What do you think? 
[Bitsquare.zip](https://github.com/bitsquare/bitsquare/files/392041/Bitsquare.zip)

**Comment by ManfredKarrer** [comment]
Yes good point. Will consider that once I work on improvements for the UI.

**Comment by haiqu** [comment]
Philosophically, when you lock the fiat amount that becomes the base currency. Since our base currency is - and should be - bitcoin, I can't see this as being a useful feature, especially since it would fail if the price feed data suddenly wasn't available.

We're not a fiat exchange, we're a bitcoin exchange.

**Comment by stiell** [comment]
It would be useful to at least have a limit on the fiat/altcoin amount in cases where you have some kind of transfer limit or don't want to risk ending up in a short position.

**Comment by haiqu** [comment]
Stiell, I agree that a limit order would be useful. I was trying to buy 1 BTC at AU$1200 about a month ago and had no sellers to buy from. If I hadn't cancelled the order I would now be paying over AU$2000
