### ISSUE TITLE
Trade closed by arbitrator won't disappear from "Open Trades" tab

### ISSUE THREAD

**Issue by 66300** [bisq-network/bisq#5150]
### Description

One of my trades has been processed by an arbitrator and funds were paid out but the trade still shows as active.

#### Version

1.5.5

### Steps to reproduce

Unable to reproduce, this was my first and only trade that went to arbitration.

### Expected behaviour

Trade should disappear from the active trades and move to history.

### Actual behaviour

Trade still shows in active trades.

### Screenshots

n/a

#### Device or machine

Windows 10

**Comment by ghost** [comment]
I tried reproducing this issue, but to no avail -> the arbitrated trade moved to Portfolio/History.  
Could you could share screenshots of the issue with personal information scrubbed-out?

---

p.s. If you have no other active trades at the moment, then deleting the file `db/PendingTrades` in your [data directory](https://bisq.wiki/Data_directory) would clear your active trades.  Just make a [backup](https://bisq.wiki/Backing_up_application_data) first.

**Comment by 66300** [comment]
Sure, here are the screenshots.
![bisq1](https://user-images.githubusercontent.com/49838895/106873797-1e754080-66d5-11eb-819f-d5e5ef97a965.png)
![bisq2](https://user-images.githubusercontent.com/49838895/106873808-2208c780-66d5-11eb-9095-be24c53e5741.png)
