### ISSUE TITLE
Small subset of Offer Maker Tx do not reach the mempool

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#5151]
A number of offers have been showing up in the offer book with transaction ids that cannot be found in either the mempool or the blockchain.  When such an offer is taken it causes an immediate failed trade.  Not much is known about the cause of this but this issue is to track progress of the investigation.

- These phantom maker txIds are coming in at a rate of 1 or 2 per day, out of approx. 100 new offers per day.
- I am checking all Bisq offers using a javascript tool that looks up each txid on a block explorer.  The txIds are extracted in a log file from Bisq's offer book.
- We've in-app messaged the onion address of some offers in this state asking them to get in touch with Bisq developers.  So far no one has come forward.
- Some of them have, after a while (like 24 hours), managed to correct the issue and the txid will suddenly be found by the block explorer with a few confirmations.  Looking at those txids nothing looks out of the ordinary.  These "fixing itself" events seem to coincide with the offer maker going offline and coming back online again.  **Perhaps a reboot / SPV resync fixes it?**
- It is assumed that some of them end up causing failed-trade fee reimbursement by the taker. e.g. https://github.com/bisq-network/support/issues/809 looks like one.

---

**Example 1:** (offer has been open for 7 days at the time of writing this; this user has another similar offer open with the same problem.  Has not responded to a couple of in-app messages from devs yet.)

![phantomA](https://user-images.githubusercontent.com/47253594/106838303-a588d100-6661-11eb-8fd8-420d60413e18.png)
![phantomB](https://user-images.githubusercontent.com/47253594/106838308-a7529480-6661-11eb-99ef-2775da208805.png)

---

**Example 2:**

![phantom0](https://user-images.githubusercontent.com/47253594/106837471-28109100-6660-11eb-828a-1eda1381811a.png)
![phantom1](https://user-images.githubusercontent.com/47253594/106837474-2a72eb00-6660-11eb-8077-f69b69d32037.png)

**Comment by Conza88** [comment]
> * We've in-app messaged the onion address of some offers in this state asking them to get in touch with Bisq developers.  So far no one has come forward.

Sorry off topic: interested if any documentation on how that can be done? ;o

**Comment by ganaque** [comment]
This is the issue I'm facing

**Comment by ghost** [comment]
@ganaque Yes my interpretation of your case is the maker tx was never published which caused a failed trade for you the taker; you'll receive reimbursement of your fee, 0.00014000 BTC.  Someone will be in touch with you on your reimbursement claim, they are typically done monthly.
@Conza88 messaging a user directly can only be done by Bisq admins, they hold a special key, its for emergencies only.

**Comment by RififiCastorjunior** [comment]
In the past week there are a lot of issues "exactly" like this one. Scam or not scam ? any advice or ways to handle this ?

**Comment by ghost** [comment]
To be sure, I am referring to this exact issue: transactions that Bisq created, that do **not show up in any mempool explorer**.  Not unconfirmed transactions, it is **unknown** transactions.  These are offer maker transactions, so the txIds are advertised in the offerbook / offer payload.

As mentioned above I did a monitoring of the offer book txIds and it was indicating a couple offers having this problem daily.  In the past week though, that has dropped to zero.  No new occurrences of this issue in the past week.  Not in the offer book, at least.  Maybe you have seen similar instances with trade payouts?

Does not seem like a scam, but still it remains a mystery.  My advice on how to handle this is treat it like a bug; collect logs so the steps leading up to the transaction can be investigated.  So far, we have not been able to collect any log of this issue.

**Comment by ghost** [comment]
**Update 2021-02-20:** Currently 1 offer in the market with an unknown maker tx.  Mempool.space => `Transaction not found`

     offerFeePaymentTxId='2f01aea547980c24312641972da7f1be0e97633600abdff7083108ccd7b7e825',
     id='93023-66e60145-286d-481a-a141-6bfda4cf344f-156',
     date=Sat Feb 20 10:28:45 CST 2021,
     direction=SELL,
     amount=2000000,
     counterCurrencyCode='EUR',
     paymentMethodId='SEPA',


Offer is from an onion that has previously had the same issue, so reinforcing the idea this may be related to the state of their system.

**Comment by ghost** [comment]
Closing as fixed by #5325
