### ISSUE TITLE
Add option to chart trade statistics in terms of number of trades

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#5154]
This is a follow on to the feature released in v1.5.5 that allow charting USD-denominated trade volumes (#5066).

Ideally, we would allow three options for charting trade statistics:

1. Trade volume in BTC (current default)
2. Trade volume in USD (new option in v1.5.5)
3. Number of trades (proposed new option)

I tweeted about this at https://twitter.com/cbeams/status/1357298837052866560, here's a screenshot:

<img width="304" alt="image" src="https://user-images.githubusercontent.com/301810/106892658-a6b31000-66ec-11eb-962b-dd4c6177d964.png">

The graph shown in the lower tweet is available at https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=86481090 (not currently publicly available)

I see the number of trades per month as one of Bisq's best health metrics. It keeps growing, it's a positive story, and it's a missed opportunity not to show this more prominently to users.

This could be implemented by offer three radio buttons above the chart instead of a toggle slider, e.g.:

`[ ] Show volume in BTC   [ ] Show volume in USD   [x] Show number of trades`

**Comment by chimp1984** [comment]
I will soon have a PR with an improved chart component. So maybe worth to wait for that and use that then as base to extend the feature... Any dev welcome to pick that up...
