### ISSUE TITLE
Allow refundagents to set their own fees for payouts.

### ISSUE THREAD

**Issue by refund-agent2** [bisq-network/bisq#5158]
### Description

Bisq takes the recommended fee rate for payouts, which is too volatile for refund agent needs. I wait for days with low fees but as I need a few minutes to prepare the payout, it jumps from 10 or 15 sats to over 50 sats/vB and I have to wait until a block is mined.

#### Version

1.5.5

### Steps to reproduce

Make a payout with withdrawal transaction fee set to 12. Bisq will use the recommended fee rate, displayed at the bottom left.

### Expected behaviour

Use the witdrawal tx fee or let me set it when creating the payout. I will respect the 10 sat min set by the software for trading transactions and keep an eye for stuck transactions.

### Screenshots
About 10 minutes ago, recommended fee was 10 sats/vbyte.

![imagen](https://user-images.githubusercontent.com/75325927/107112951-3e327300-6853-11eb-9282-e5cc55adfda4.png)

**Comment by pazza83** [comment]
I hate waiting for a block to be mined too!

Makes sense if you can do you refunds in batches and choose the sat/vB yourself.
