### ISSUE TITLE
Memo records disappeared in the transactions tab

### ISSUE THREAD

**Issue by viperperidot** [bisq-network/bisq#5161]
Over the course of using Bisq I have been using the Memo feature to create notes with my transactions. A few days ago I went into the transactions tab and noticed that most of my notes were gone. I do not know exactly when this happened but there appears to be a bug or error somewhere that does not allow the memo records to persist indefinitely. If the devs need more information to try and figure out the root cause I can answer any questions. I consider this to be a fairly major bug as some people rely on the memo to keep track of their transaction history.

Maybe we should look at how the memo records are stored and make sure this cannot happen again, also make sure that memos are being backed up if they are not already.

Thanks

**Comment by Conza88** [comment]
I REALLY wish the "memo" / "label" / "notes" function was NOT just for the transactions being sent from Bisq wallet to where-ever. 

I really think the notes function needs to be a persistent option through-out the process. Naturally, getting exported in Trade History or Transactions history via csv export. 

I think aiding people using it as a daily driver makes sense i.e. "Honeymoon Fund" (so they can recall the trade they're doing).
"New computer", "Bro's money" etc.

**Comment by ripcurlx** [comment]
> Maybe we should look at how the memo records are stored and make sure this cannot happen again, also make sure that memos are being backed up if they are not already.

Did you transfer your account to a new computer or restore your account from seed? It is weird that not all are gone.

**Comment by viperperidot** [comment]
> > Maybe we should look at how the memo records are stored and make sure this cannot happen again, also make sure that memos are being backed up if they are not already.
> 
> Did you transfer your account to a new computer or restore your account from seed? It is weird that not all are gone.

No I did not transfer my account or restore from seed, same laptop and account etc. that I always use.

I have had my computer go non-responsive while Bisq is running in the past though and I use the Alt+PrtScr+REISUB command to restart my laptop, I am running Ubuntu. So maybe that somehow caused some of the memos to be erased? I am not sure how they are stored or if that is possible. I have also had a few different errors over the course of using bisq but not sure if they were related to this or not. 

I have done SPV resyncs if that matters, I have also deleted outdated Tor files on occasion.

**Comment by ripcurlx** [comment]
We changed some code on persisting data a while ago, which in some cases only persist on shutdown. I'm not sure if it could happen if this shutdown sequence could be skipped on a forced shutdown. We do listen for OS INT and TERM signals so we should catch even those cases, but it sounds a little bit as this was skipped somehow.
