### ISSUE TITLE
Errror when placing an offer.

### ISSUE THREAD

**Issue by bisquser1** [bisq-network/bisq#5162]
Tried to make an offer to buy, didn't allow me to finalize.

#### Version

v1.5.5

### Screenshots

![Screen Shot 2021-02-06 at 10 43 17 PM](https://user-images.githubusercontent.com/77044917/107139038-1122a680-68cd-11eb-9222-32c12194f8ab.png)

**Comment by ghost** [comment]
Could you provide the log please, specifically the part leading up to the message `An error occurred at task: CreateMakerFeeTx`.
Also, is the problem reproducible?

**Comment by cd2357** [comment]
@bisquser1 can you please answer the questions above? Especially whether it happened just once, or keeps happening (is reproducible)? Thanks.
