### ISSUE TITLE
Null Pointer exception

### ISSUE THREAD

**Issue by haukehess** [bisq-network/bisq#5166]
### Description

I switched the payment account while preparing an offer to buy bitcoin

#### Version

1.5.5

### Steps to reproduce

can't

### Expected behaviour

no null pointer exception

### Actual behaviour

see logfile (null pointer exception dialog)

### Screenshots

too late, screen cleared after clicking on report issue

#### Device or machine

macOS Big Sur on MacMini M1

#### Additional info
[bisq.log](https://github.com/bisq-network/bisq/files/5938874/bisq.log)

**Comment by ghost** [comment]
Hi, the log is useful, thanks!  Can you give an idea what type of payment accounts you were switching between?  e.g. Revolut to BSQ, etc..  Also what possible currencies would be used?  Are you able to reproduce the issue?

**Comment by haukehess** [comment]
Sepa to sepa.

I will try to reproduce

**Comment by haukehess** [comment]
Not (easily) reproducible on my side. Just tried the same, and it didn’t crash.

**Comment by ghost** [comment]
Thanks for the report, that helped to reproduce & fix issue.

- You have two or more SEPA accounts.
- Fill in fields for a new offer using SEPA -> e.g. Buy 0.01 EUR/BTC at 1% above market price.
- Enter a value in the field "Deactivate offer if market price is above" value.
- Switch the trading account to the other SEPA account.
- NPE.

**Comment by haukehess** [comment]
Yes, that’s what I did but didn’t remember when I tried to reproduce it!
