### ISSUE TITLE
Start bitsquare with my offers disabled

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#517]
Should have an option to start Bitsquare with my offers disabled.

**Comment by ManfredKarrer** [comment]
Why?

**Comment by ManfredKarrer** [comment]
Can you use the forum for discussions? I prefer to keep the Github more for bugs and concrete features.

**Comment by bitcoinuser** [comment]
Hi,

Imagine I create an sell bitcoin offer with fixed price. So I travel and forget to remove the order. When I came back from travel, the bitcoin price appreciate 100%. So I open bitsquare and someone see my offer and take it before I have chance to remove it.

**Comment by ManfredKarrer** [comment]
Good point. Though I don't have an easy solution for this. But I think it is nothing critical at the current state.

**Comment by haiqu** [comment]
Fixed price offers are definitely a bad idea in this situation, but it's a user issue. Any such trades should be closed before traveling. Either that or use % from market.

Please close Manfred.

**Comment by ManfredKarrer** [comment]
Usually if you travel you will shut down your computer and then the offer will be removed anyway.
I will keep the feature request in mind but I think atm there are no plans to support that as there is too much other hi-prio stuff to do.
