### ISSUE TITLE
Bitcoin node tor v3 support?

### ISSUE THREAD

**Issue by Ts00P** [bisq-network/bisq#5179]
### Description

Bisq can't connect to bitcoin nodes running tor v3, but works fine with same config on v2

#### Version

1.5.5

### Steps to reproduce

settings -> network info -> use custome bitcoin core nodes - > tor v3 address

### Expected behaviour

connection

### Actual behaviour

Endless loading and unable to recover bisq without backup

**Comment by huey735** [comment]
Bisq doesn't support Tor v3.

**Comment by ripcurlx** [comment]
Depends on https://github.com/bitcoinj/bitcoinj/issues/2067 which is in progress right now.

**Comment by jonatack** [comment]
For info, v2 support appears to have been removed on tor master: https://github.com/torproject/tor/commit/c0a23303140fedce06e0b7d88ce475c39703717a

**Comment by jonatack** [comment]
See also:

https://github.com/bitcoin/bitcoin/issues/21351#issuecomment-789737457

https://gitlab.torproject.org/tpo/core/team/-/wikis/NetworkTeam/CoreTorReleases

https://blog.torproject.org/v2-deprecation-timeline

"July 15th, 2021: 0.4.6.x: Tor will no longer support v2 and support will be removed from the code base. October 15th, 2021: We will release new Tor client stable versions for all supported series that will disable v2."

**Comment by ripcurlx** [comment]
https://github.com/bitcoinj/bitcoinj/issues/2067 is implemented already and we are in the process of migrating and testing the Tor v3 support.

**Comment by cd2357** [comment]
Bisq now supports Tor v3 addresses.
