### ISSUE TITLE
Max allowed trade period/date

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#518]
Hi,
I would like to know if, when someone place an offer, is it possible to decrease this 4 days (Brazil national bank transfer)? that look like is added by bitsquare as standard.

**Comment by ManfredKarrer** [comment]
I think that would make all very complicate as on weekends or long weekends banks are closed and you cannot take such offers then....

**Comment by bitcoinuser** [comment]
Agree
