### ISSUE TITLE
UX is not great with bisq

### ISSUE THREAD

**Issue by McFranko** [bisq-network/bisq#5180]
### Description

This app is very very slow. It's very hard to use because of this, and it has turned away many of my friends who I've tried to get to use this.

#### Version

1.5.5

### Steps to reproduce

Try to use the app

### Expected behaviour

This app should be able to run much better on lower end hardware. Especially since many of the people who a decentralized exchange (and bitcoin in general) benefits do not have access to good hardware (I'm thinking people in third world countries and such)

### Actual behaviour

The app is very hard to use even on a decent modern laptop

#### Device or machine

Artix Linux \
Asus Vivobook X510UAR 1.0 \
Intel i7-8550U, 4 cores @ 4GHz \
16gb of ram

### Additional Info

I think this is an important issue to solve. It turns away many people from using bisq. I have to buy bitcoin on bisq for my friends because they don't want to use the app because it's too slow. I understand that it has to do a lot in the background (what with using tor for everything), but still, I imagine some optimization could be done. Or maybe just making a public API for it, so that people can make their own clients for it.

I also would like to add that I mean no disrespect to the developers working on this, you are doing god's work. This is a great program, I just think it needs some more work.

**Comment by Conza88** [comment]
> ### Description
> This app is very very slow. It's very hard to use because of this, and it has turned away many of my friends who I've tried to get to use this.

**Implement new-user-onboarding and new UI design** (https://github.com/bisq-network/projects/issues/47) 


>Or maybe just making a public API for it, so that people can make their own clients for it.

**Prepare roll out of API for January or February release** [https://github.com/bisq-network/projects/issues/46](https://github.com/bisq-network/projects/issues/46)

**Comment by cd2357** [comment]
In addition to the projects mentioned above, the most recent release (v1.6.4) contains an updated UI library (JavaFX 15) which is more responsive and consumes less system resources.
