### ISSUE TITLE
Issue when changing trading account from edit offer tab

### ISSUE THREAD

**Issue by cherryclam** [bisq-network/bisq#5183]
Getting an error while switching an existing offer from Cash deposit to Zelle.
I'm new to Github so I'm not sure what I need to provide, (also cautious of giving out the console file as it had some personal info on there). Let me know what else you need!

**Comment by ripcurlx** [comment]
@cherryclam Please provide a log file or at least a screenshot of the error screen otherwise it will be very hard to reproduce.

**Comment by ghost** [comment]
I think it is same as https://github.com/bisq-network/bisq/issues/5166.  Reproduced this issue with Cash deposit => Zelle.   Gives a NPE if the deactivate price field is used and then the account switched.  There's already a merged fix of that issue, for next release.
