### ISSUE TITLE
Restoring a wallet via seed with opened dispute.

### ISSUE THREAD

**Issue by piuhyufo** [bisq-network/bisq#5184]
Hello. 

I opened a deal for the exchange of BTC-XMR, when my hard drive broke. I made backup but it was on the same disk. The seller sent me XMR, but I did not have possibility to confirm the deal because couldn't go into the wallet. A month later, I was able to restore the seed (got it from the broken disk) and the date when the wallet was created. But I have no disputes, no history of the transaction in my account.
In the address history, I see 2 used addresses. Checked them on the blockchain and saw that the funds from the second address were automatically transferred after 10 days to the donate address bisq.

I lost my deposit ... which was 0.3 bitcoin, a lot.

Is there any way to get my deposit back?

It is very strange that disputes are not restored through a seed phrase. In this case, you need to make a full backup of the wallet for each new open transaction.

**Comment by ripcurlx** [comment]
> It is very strange that disputes are not restored through a seed phrase. In this case, you need to make a full backup of the wallet for each new open transaction.

Yes, seed phrases are only used for the wallet any other data needs to be backed up separately, to be able to restore everything again. Did you try to contact anyone (mediator, arbitrator) during this month? I fear your case went into mediation and afterwards to the refund agent because you didn't respond in any way. I'm sorry that this was caused because of a hardware failure, but I guess your deposit was sent to the other trading peers because of a violation of the trade protocol.

**Comment by piuhyufo** [comment]
> Yes, seed phrases are only used for the wallet any other data needs to be backed up separately, to be able to restore everything again. Did you try to contact anyone (mediator, arbitrator) during this month? I fear your case went into mediation and afterwards to the refund agent because you didn't respond in any way. I'm sorry that this was caused because of a hardware failure, but I guess your deposit was sent to the other trading peers because of a violation of the trade protocol.

Thanks for answer.

I do not know how to contact with a mediator or an arbitrator, since I do not have a history of trades in my account and there is no way to create a support ticket from the bisq app.

I have read in detail the bisq documentation and it does not say anywhere that the deposit can be sent to other trading peers ... It says that it should be sent to the bisq donation wallet. Please tell me with who I should contact to resolve this issue?

**Comment by pazza83** [comment]
Hi @piuhyufo check out the wiki's below:

- [Security deposit](https://bisq.wiki/Security_deposit) 
- [Trading Rules](https://bisq.wiki/Trading_rules)
- [Dispute resolution](https://bisq.wiki/Dispute_resolution)

Also there was a recent support case where there are similarities with what you are describing: https://github.com/bisq-network/support/issues/684 

You have not said when your trade was but if it was for 2 BTC the payout would need to go through the DAO for a vote. That is what happened with the trade above.

Do you know you Trade ID for this trade?
