### ISSUE TITLE
You must have bootstrapped before adding data to the P2P network

### ISSUE THREAD

**Issue by ypt0** [bisq-network/bisq#5190]
### Steps to reproduce

Any time trying to start the application the error is thrown and that's it.

### Expected behaviour

Open even after the error message

### Actual behaviour

Stuck with one useless application and losing money

### Screenshots

![image](https://user-images.githubusercontent.com/73359715/107812982-6dc00e80-6d70-11eb-9af3-74cee1b03e7f.png)

#### Device or machine

Linux

#### Additional info

Restarted and several times re-trying.
[error_bisq.log](https://github.com/bisq-network/bisq/files/5973929/error_bisq.log)

**Comment by ghost** [comment]
Reproduced this issue using the following example:

- Create offer Buy BTC/USD 0.01 BTC at spot (e.g. if spot is 47000), choose "Deactivate offer if over 47100"
- Close down Bisq and wait for the market price to move over the deactivation price.
- Start Bisq, the error message above will pop up.
 

To stop the error, you can edit the offer and remove the deactivation price.

@ypt0 you say "starting Bisq is not possible" but I'm not experiencing that in v1.5.5.  Could you expand on that if it is stopping you from running Bisq.

**Comment by Willi2814** [comment]
Hi.
I have today the same issue.

My device:
Apple Macbook Air 
OS X El Captain
10.16.6

The issue:
I start Bisq type the passwort - than the issue "You must have boot..." pop up
The program dosen´t start. The surface look like during the starting process. 

I try it several time, rebooting the computer - no effect.
I was lucky the BTC price rise to my stop limit of the open trades.
After that I was able to start bisq without any problem.
I have now erase the trigger price in my open trades.
I hope this will help.

**Comment by ghost** [comment]
@ripcurlx This problem still exists in production v1.5.5 and as the users above have mentioned, it does prevent access to Bisq app in any form while their offer is triggered.  I think we need to address this quickly because it can affect any user of this feature.

Possible solutions:

1. Warn users by issuing an app alert.
2. Advise affected users to delete their `OpenOffers` db file (losing open offers & fees).
3. Do an emergency release to patch it.

**Comment by ripcurlx** [comment]
> 3\. Do an emergency release to patch it.

This issue was auto-closed as the PR referencing it, was merged. But yes, that seems to be real problem. 

I do think we should go with 3) as all other options doesn't solve the issue at hand and cause even more issues for the DAO for reimbursement in case 2) is done.

**Comment by ripcurlx** [comment]
Unfortunately all affected users will have to update manually as they will never reach the update-dialog.

**Comment by ripcurlx** [comment]
@jmacxx I just prepared a hotfix branch for this https://github.com/bisq-network/bisq/tree/hotfix/v1.5.6. Would be great if you could run it as well to test for this issue.

**Comment by ghost** [comment]
Tested successfully on both regtest and mainnet.  :+1:
