### ISSUE TITLE
wallet seed - only 3 words

### ISSUE THREAD

**Issue by yononima** [bisq-network/bisq#5195]
### Description

I changed the ‘wallet password’, restarted bisq, however bisq couldn’t accept my new pass. Clicked ‘forgot password’ and tried to put seed password to restore wallet. When all 12 words and date were written in the text field, i couldn’t press the ‘restore wallet’ button, it wasn’t green. It changed to green, when i had only the 3 of the 12 words written. Pressed ‘restore wallet’, and bisq started again. Now my seed word is only three-words long. I dont think this is normal. 

That was 10 days ago (Feb 6th). Today (Feb 16th) i still have 3 words as my seed pass. 

#### Version

1.5.5

just installed 1.5.6  - same issue

### Screenshots

<img width="1192" alt="Screenshot 2021-02-06 at 20 08 19" src="https://user-images.githubusercontent.com/70004866/108088693-702cac00-7081-11eb-90c1-0fc36b2230a7.png">

#### Device or machine

macOS Big Sur (Version 11.2.1)

#### Additional info
PLS help as which log to upload. The incident happened on Feb 6th, however the log files as i can see is from feb 10th.

<img width="836" alt="Screenshot 2021-02-16 at 17 55 56" src="https://user-images.githubusercontent.com/70004866/108087676-58a0f380-7080-11eb-9ee4-54deb03d48fc.png">

[bisq log files.zip](https://github.com/bisq-network/bisq/files/5989934/bisq.log.files.zip)

**Comment by MwithM** [comment]
That is very strange, your 12 wallet word should work if it's correct (it does a checksum to make sure there are no mistakes).
I would try again with that seed, because I doubt a 3 word seed will retrieve your keys.

Did you backup your wallet to keep trying the regular password?

**Comment by yononima** [comment]
I do have backed up my wallet. 

Do you suggest to do a 'restore wallet from seed words' ?

**Comment by MwithM** [comment]
I would rather keep trying with regular password and possible variations.
To import the seed, you have to input it into the 'restore wallet from seed words' field and the date, so the addresses will be updated from that time.

**Comment by yononima** [comment]
Sorry but i don't fully understand what do you mean with the 'trying with regular password'?

**Comment by MwithM** [comment]
Try to put the password into the wallet where you have the backup. I once needed 2 days to put the password correctly because I was missing one capital letter.
