### ISSUE TITLE
On "Send Funds" screen add ability to change withdrawal trans fee sats rate

### ISSUE THREAD

**Issue by Conza88** [bisq-network/bisq#5199]
I have seen many questions asked about when withdrawing funds from Bisq Wallet, if/where you can edit the transaction fee rate.

On the "Send Funds" screen, there is no reference that it is hiding in the settings section. 

Either a link or "(i)" reference would be good. Or alternatively, have the option to adjust the withdrawal trans. sats v/byte on that screen. 

![image](https://user-images.githubusercontent.com/51952482/108135992-3f925400-710d-11eb-8b81-ae119919bf78.png)

"Settings" tab — lower left side

![image](https://user-images.githubusercontent.com/51952482/108136112-7ff1d200-710d-11eb-97ea-5101d57e61aa.png)

Better CS experience is the goal. It's not intuitive at all currently.

**Comment by pazza83** [comment]
Yes, makes sense for you to be able to set the withdrawal transaction fee on the same page. Maybe there should also be a warning about setting the fee too low.

`Please note that setting too low a fee may cause your transaction to remain unconfirmed for a long time and possibly be rejected. Customize your transaction fee at your own risk.`

**Comment by Conza88** [comment]
Yep, nice. Any handy wikipedia entry that elaborates more? Or a link to https://mempool.space/ ?

https://twitter.com/CoreFeeHelper breakdown? 

Next: 105.9 sat/byte  $13.06
1h:   79.0 sat/byte  $9.75
6h:   53.2 sat/byte  $6.56
12h:  31.2 sat/byte  $3.85
1d:   31.2 sat/byte  $3.85
3d:    7.1 sat/byte  $0.88
1wk:   3.0 sat/byte  $0.37
Min:   3.7 sat/byte  $0.47
Block height: 670,924
Mempool depth: 82

**Comment by ghost** [comment]
Seems like it was duplicated by https://github.com/bisq-network/bisq/issues/5298 and fixed via https://github.com/bisq-network/bisq/pull/5312
