### ISSUE TITLE
Unable to buy bitcoin (SEPA)

### ISSUE THREAD

**Issue by goestin** [bisq-network/bisq#520]
An error occurred when taking the offer.

A timeout occurred.

The trading fee is already paid. In the worst case you have lost that fee. We are sorry about that but keep in mind it is a very small amount.
Please try to restart you application and check your network connection to see if you can resolve the issue.Please try to restart you application and check your network connection to see if you can resolve the issue.

(Is there no way to first establish the communication and then pay the fee? I know it is an small amount, but is still burned btc to me)
[bitsquare.log.zip](https://github.com/bitsquare/bitsquare/files/352025/bitsquare.log.zip)

**Comment by ManfredKarrer** [comment]
Thanks for reporting. Do you have version 0.4.8.1 installed? I t might be that the other trader has still the old verison. 
The communication and offer availability is checked before the fee is paid. But some other checks like if the arbitrator is available or the market price is in the range are done later.
In the upcoming version that is already fixed and all possible checks are done before the fee is paid. You can send me by email your btc address and I refund your fee loss.

**Comment by goestin** [comment]
Hi Manfred,
 
That is excellent news!
There is no refund necessary :)
Thanks for your quick response!

Kind Regards,
Goes Sépouse

  edit: removed email footer

**Comment by goestin** [comment]
Almost forgot, yes I have 0.4.8.1 installed.
 
Kind Regards,
Goes Sépouse

edit: removed email footer

**Comment by ManfredKarrer** [comment]
Thanks!
