### ISSUE TITLE
Bank id leaking 

### ISSUE THREAD

**Issue by Bl5ckj5ck** [bisq-network/bisq#5201]
Hey guys 👋 
One of the strongest point of Bisq is to keep users’ info private and to show them just to the users who are involved in the trade.
However, if you pick randomly one buy btc SEPA offer and expand its details, you can see the bank id near the description of the payment method. Example: SEPA (XXXX)
This potentially lets everyone put the id online and find the bank where the creditor will get the payment.

Wouldn’t be better for privacy purposes to hide the bank id from the payment details and to show it just when you accept the offer?

**Comment by pazza83** [comment]
Hi @Bl5ckj5ck thanks for this. I agree I thought this has been removed. I do not see any reason why any bank account details need to be shown.

Users will know the offer is SEPA and what country the bank is in. No need for them to know the actual bank before taking the offer.

On the GBP market it does not show the Faster Payments sort code which is essentially the same thing as the SEPA BIC.

I think they should be removed.

**Comment by pazza83** [comment]
Here is an example:

![Capture](https://user-images.githubusercontent.com/66367547/108429538-073b6480-7238-11eb-8079-87c4b8ca5979.PNG)

Here how I propose it should look:

![Capture2](https://user-images.githubusercontent.com/66367547/108429671-35b93f80-7238-11eb-8fe5-81744766a8dd.png)

**Comment by Bl5ckj5ck** [comment]
I’d leave the “SEPA” specification but without the bank id (xxxxx).
So that the taker has a visual confirmation in the details of the offer too that he will do a SEPA transfer

**Comment by BtcContributor** [comment]
I will take a look at this tomorrow.

**Comment by pazza83** [comment]
@BtcContributor thanks.

Thinking about this I think it is very important.

If a compliance officer from ACME Bank downloads Bisq they should not be able to search for what offers on the platform are trading using ACME Bank by checking sort codes / BIC / routing number etc

**Comment by BtcContributor** [comment]
Fixed for SEPA and a couple of other instances while maintaining method payment as said by @Bl5ckj5ck.

Do you think that the _Accepted banks_ field is needed when using _Transfer with specific banks_? Otherwise I would completely delete that line.

<img width="840" alt="bisq5" src="https://user-images.githubusercontent.com/79100296/109072721-af986f80-76f5-11eb-8cd8-d3c9201529ba.png">

**Comment by Bl5ckj5ck** [comment]
The “Accepted Banks” field might be useful for the taker since this would tell him which banks he should put in his Bisq payment account in order to accept the offer. At the same time I think that this info does not reveal any personal financial details of the maker

What do you think about it @pazza83 ?

**Comment by pazza83** [comment]
> Do you think that the _Accepted banks_ field is needed when using _Transfer with specific banks_? Otherwise I would completely delete that line.

Yes for specific bank it is needed. There is no way not to leak ID as the taker would need to know the Bank being used. I think it is a rarely used payment method on Bisq.

Same for "Transfers with same bank" payment option.

**Comment by pazza83** [comment]
> The “Accepted Banks” field might be useful for the taker since this would tell him which banks he should put in his Bisq payment account in order to accept the offer. At the same time I think that this info does not reveal any personal financial details of the maker

Yes agreed. For specific bank and same bank this info is needed. I do not think these are used very much and the trader would be choosing to leak their bank name in order to achieve a trade. I think, therefore, it is ok for these 2 payment methods.

**Comment by pazza83** [comment]
@BtcContributor please can you also check what info is leaked when making a payment using 'Japan Bank Furikomi' it is a payment option in Bisq.

Also "SEPA Instant" instant payment option should be the same as SEPA.

**Comment by BtcContributor** [comment]
@pazza83 

Everything seems good to me.

<img width="811" alt="bisq7" src="https://user-images.githubusercontent.com/79100296/109414232-282b5480-79b2-11eb-9db0-77577adcf64c.png">

<img width="627" alt="bisq6" src="https://user-images.githubusercontent.com/79100296/109414235-2d889f00-79b2-11eb-8831-f5368d8b44f2.png">

**Comment by Bl5ckj5ck** [comment]
Hi @BtcContributor any updates on this? I noticed that your commits still have to be merged and you’re waiting for @ripcurlx to review them

**Comment by BtcContributor** [comment]
Hi! That's correct @Bl5ckj5ck.
Waiting for @ripcurlx review and eventual merge.

**Comment by ripcurlx** [comment]
I'm just focusing on the v1.6.0 release right now. Will review it soon. Maybe we could even push this in the end one step further to actually also remove this information in the protocol level.

**Comment by Bl5ckj5ck** [comment]
Thanks for the update @ripcurlx 
Removing this info on the protocol level would definitely solve this issue completely (not just partially)

**Comment by bisqubutor** [comment]
Imagine a Taker of BTC buy offer have several bank accounts. He may already prefer to choose offers of bank account that matches his and use this for trade and receive fiat to speed up fiat transfer time and overall trade time.

Imagine a Taker of BTC sell offer have several bank accounts. He may already prefer to choose offers of bank account that matches his and use this for trade and send fiat the fastest possible to speed up fiat transfer time and reduce overall trade time.

**Comment by Bl5ckj5ck** [comment]
@bisqubutor The “_Transfer with specific bank_” payment method currently meets the needs that you pointed above. 
The “_Accepted banks_” field won’t be removed in this case since it’s an info specifically required by both traders

**Comment by pazza83** [comment]
@bisqubutor I agree that knowing what bank a trader is user might be useful when buying from the same seller. But in this instance I think privacy beats convenience.
