### ISSUE TITLE
Change Verify result button text in Dispute View

### ISSUE THREAD

**Issue by JaredBoone** [bisq-network/bisq#5208]
### Description

The"Verify result" button in the Dispute View is unclear and problematic. The button is intended for checking the signature of the mediator or arbitrator and the button text should reflect that. "Verify result" implies that pushing the button will confirm the result of the dispute. In my opinion the text for this button should be changed. I suggest "View signature", "Inspect signature" or "Check signature". 

#### Version

v1.5.6

### Steps to reproduce

* Open the Dispute View
* See the "Verify result" button
* Don't push it because it's too scary

### Expected behaviour

* Open the Dispute View
* See the "Check signature" button
* Push it with confidence

#### Additional info

/core/src/main/resources/i18n/displayString.properties
support.sigCheck.button=Verify result

**Comment by Conza88** [comment]
I assumed that's what it'd be as well.
