### ISSUE TITLE
Popup notifications

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#521]
Hi,

I would like to see a popup notification when someone add an offer to sell or buy bitcoin for Brazilian Real.

Thanks

**Comment by haiqu** [comment]
I'd like to extend this to using a system sound rather than a popup, and allowing the user to choose one or the other.

Should also add notifications for an online offer taken, although I think this already has a popup.

**Comment by ManfredKarrer** [comment]
If anyone can research Java support for all supported OS regarding system sound we would get a good base fro adding that.
