### ISSUE TITLE
$200 Bitcoin bounty: Bisq with browser UI on Raspberry Pi 4

### ISSUE THREAD

**Issue by MaxSikorski** [bisq-network/bisq#5220]
I'd like to offer a bitcoin bounty to run Bisq on my raspberry pi 4. Payout to be delivered once first successful launch & order fill on Bisq from RPi can be verified. 

Requirements (I could be missing some):
1. Complie Bisq for 'arm64 v8'
2. Integrate into Docker
3. same Docker container to expose browser interface using VNC

I tried to download Bisq directly to my Umbrel in terminal
------
umbrel@umbrel:~ $ docker run -d --rm --name bisq-on-docker -p 3389:3389 -v bisq-on-docker-data:/bisq fflo/bisq-on-docker
Unable to find image 'fflo/bisq-on-docker:latest' locally
latest: Pulling from fflo/bisq-on-docker
83ee3a23efb7: Pull complete 
db98fc6f11f0: Pull complete 
f611acd52c6c: Pull complete 
ef0ba8560927: Pull complete 
c1ef14b76fad: Pull complete 
fd47c44fd858: Pull complete 
07f39bb81c6f: Pull complete 
3de654a0bdf4: Pull complete 
088786579bc4: Pull complete 
Digest: sha256:ee0e119aab02a4f24029d990dcc91c121d490358f68138a81c87f29882dfae7c
Status: Downloaded newer image for fflo/bisq-on-docker:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
62d9c6a90e97b73f80dc72e479598ef8ffdfac16c26cc2b6b52b4efd44efb743
umbrel@umbrel:~ $ docker run fflo/bisq-on-docker
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error
umbrel@umbrel:~ $ 
------

First, it started download, and completed. It seems that everything is available to do so, but need a few things such as compiling Bisq to run on 'arm64 v8'. After searching for any issues, I thought issue#2861 was most relevant, with @wiz & @leshik comments below to be most accurate. 
---
"@leshik Actually, can you do a pull-request to Bisq to add the Dockerfile? I'd like to request that Bisq officially support the configuration of running in Docker using VNC"

_Originally posted by @wiz in https://github.com/bisq-network/bisq/issues/2861#issuecomment-518434021_
---

cc: @ghubstan
Let's continue discussion. Feel free to reach out to me anytime, and hope to see more sats added to this bounty as well.

**Comment by MaxSikorski** [comment]
My apologies on character boldness in text. Will fix in edit once I find how to do so.

**Comment by MaxSikorski** [comment]
@getumbrel: @lukechilds, @mayankchhabra
[@Raspiblitz](https://github.com/rootzoll/raspiblitz): @openoms, @rootzoll 
Bisq: @ghubstan, @leshik, @wiz

**Comment by wiz** [comment]
Yes, this is a long term goal. While you can run it on the native display or use VNC to connect to Bisq running on a RPI, the performance is very slow: https://twitter.com/wiz/status/1180530812694888448?s=21

The solution is to run Bisq headless, and make a web interface or mobile app to pair with it over a GRPC API, the latter which has recently been developed over the past year. Now a web interface or mobile app can be developed as the next piece.

**Comment by leshik** [comment]
> over a GRPC API, the latter which has recently been developed over the past year. Now a web interface or mobile app can be developed as the next piece

@wiz where we are at now? The last time I looked API was very limited in functionality.

**Comment by wiz** [comment]
Last I heard the GRPC API was basically ready to start hacking on

**Comment by ripcurlx** [comment]
> > over a GRPC API, the latter which has recently been developed over the past year. Now a web interface or mobile app can be developed as the next piece
> 
> @wiz where we are at now? The last time I looked API was very limited in functionality.

We are shipping with v1.5.7 everything to start playing around with the API. The official release is planned for v1.6.0 (next release), but we want to have some beta testers first. @leshik Would be great if you could join the #api channel and ping @ghubstan for guidance. Thanks!

**Comment by wallclockbuilder** [comment]
Bisq is a Java application. Why can't they just run it on the JVM?

**Comment by mlewk** [comment]
Yes, I totally think it would be great to be able to run Bisq on my Raspberry Pi!

**Comment by tmakerman** [comment]
Just sharing - I've had success getting v1.9.6 built from source running on Raspberry Pi 4.  The performance is slow but still quite usable I believe.

https://gist.github.com/tmakerman/ee53a94c3cfc8362192ad9df20709547
