### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by GogoFC** [bisq-network/bisq#5228]
High CPU usage running bisq.  Lags.  It takes few seconds for mouse to change shape to be able to click link. Feels like WIN95 :)
This computer isn't the newest but it's still an i5-5300U, platform is Windows 10. I could probably do a trade but waiting after each mouse click a few secs gets old real quick. Feels like there is no pause or timeout of processes, my cpu temp went up to 80 degrees celsius, normally it's 46.

so do u need any logs from me (have to tell me the location), is it possible to time out the cpu consuming process for a few ms more, or is it time for a new laptop :)

![Screenshot 2021-02-23 203443](https://user-images.githubusercontent.com/9360410/108939664-aafd8980-7617-11eb-89dd-ca396b8f536a.jpg)

**Comment by GogoFC** [comment]
I guess I have to wait till it's synced with DAO. So closing,

**Comment by ciriousjoker** [comment]
It would be very(!) helpful to show a sync progress bar (if possible) and a huge warning about the cpu usage during the first open. Many users probably won't search the Github issues for their problem and just abandon the software because "the programmers couldn't make lagfree software while everyone else can".

**Comment by ripcurlx** [comment]
> It would be very(!) helpful to show a sync progress bar (if possible) and a huge warning about the cpu usage during the first open. Many users probably won't search the Github issues for their problem and just abandon the software because "the programmers couldn't make lagfree software while everyone else can".

Actually we had a progress bar animation, but it was so poorly implemented by JavaFX that it even created more lag to the CPU intensive process. But I agree that if we are not able to multi-thread this properly we should give an indication what is about to happen on first start. Additionally as we jumped from JavaFX 11 to JavaFX 16 recently we have to re-visit the  CPU usage of the progress animation.
