### ISSUE TITLE
Bisq does not check mempoolminfee when creating new transactions

### ISSUE THREAD

**Issue by wiz** [bisq-network/bisq#5229]
Following up from discussions on Keybase, Bisq needs to enforce `mempoolminfee` value, since it currently uses a hard-coded value and the network value is variable:

1) Pricenode needs to save the `minimumFee` value from https://mempool.space/api/v1/fees/recommended
2) Pricenode needs to serve the `minimumFee` value from (1) on https://price.bisq.wiz.biz/getFees
3) Bisq needs to save the `minimumFee` value it gets when updating from (2) once per minute
4) Bisq needs to return the `minimumFee` value it gets from (3) in `bisq.common.config.BaseCurrencyNetwork::getDefaultMinFeePerVbyte()`

cc @jmacxx

**Comment by wiz** [comment]
Also, we should multiply by the `minimumFee` by 2, so even if it goes down to 1 the actual minimum is still 2 as it was before with the hard-coded value, and when it's > 1 this gives some buffer to avoid immediate purging of the user's TX

**Comment by Emzy** [comment]
Alternative option, or quick fix, could be to increase the mempool on our nodes we use for TX transmissions.

**Comment by wiz** [comment]
No, it doesn't matter if our nodes accept or reject the low-fee transactions, no other nodes will accept them

**Comment by Emzy** [comment]
Sure. It was about the problem of the resync of the wallet part. But if I think more about it, the increase will make the problem even bigger. So not a good idea.

**Comment by wiz** [comment]
Yes, this is why typically only miners and block explorers change their mempool settings - normal users changing it does not have any benefit and only negative effects
