### ISSUE TITLE
Fix color of message status information in Dark mode

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#5230]
It is hardly readable in dark mode right now if message is saved in receivers's mailbox.
![Bildschirmfoto 2021-02-24 um 10 21 11](https://user-images.githubusercontent.com/170962/108978696-2ac43c00-768a-11eb-88df-c87844e29148.png)

Same issue exists for other info messages.

![Bildschirmfoto 2021-02-24 um 10 24 18](https://user-images.githubusercontent.com/170962/108979066-94dce100-768a-11eb-9192-ca2c88928c80.png)

**Comment by BtcContributor** [comment]
I am taking a look. 

Edit: fixed

**Comment by myreadlove** [comment]
> It is hardly readable in dark mode right now if message is saved in receivers's mailbox.
> ![Bildschirmfoto 2021-02-24 um 10 21 11](https://user-images.githubusercontent.com/170962/108978696-2ac43c00-768a-11eb-88df-c87844e29148.png)
> 
> Same issue exists for other info messages.
> 
> ![Bildschirmfoto 2021-02-24 um 10 24 18](https://user-images.githubusercontent.com/170962/108979066-94dce100-768a-11eb-9192-ca2c88928c80.png)

how to add you
