### ISSUE TITLE
Offer confirmation failed

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#524]
Error message :A timeout occurred.
Offer fee transaction ID:cdbc8e35e12b085620fb7c52126c8d4db2bd2e98bf100b38bd4cd26a65ce070f
Taker fee transaction ID: 9dd4cde0ef07138777bf54d2bf79484a82d7b8343745ed9775eaeb0f6ecdb8f9
Trade state: TAKER_FEE_PAID
Deposit missing

**Comment by ManfredKarrer** [comment]
Do you have updated to the latest version 0.4.8.1?
Are you sure the deposit is missing? The take offer fee only should have been lost in such a case.
You can check all transactions under funds/tx.
