### ISSUE TITLE
Mainnet bats tests are working now.

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#5252]
Mainnet bats tests are working now.

_Originally posted by @ghubstan in https://github.com/bisq-network/bisq/issues/5250#issuecomment-787219197_

**Comment by ghost** [comment]
.

**Comment by bisq-github-admin-3** [comment]
@mehmet-sys Please don't use GitHub issues like that, otherwise I have to prevent you from spamming our GitHub issues.
