### ISSUE TITLE
Errors while opening DAO proposal links on Windows

### ISSUE THREAD

**Issue by BtcContributor** [bisq-network/bisq#5261]
### Description

When trying to open a DAO proposal link on Windows, the file explorer is wrongly opened instead of the browser due to the fact that the URL is not surrounded by double quotes.

<img width="1510" alt="bisq9" src="https://user-images.githubusercontent.com/79100296/109646812-da9d1c00-7b58-11eb-9891-ff32fee179e8.png">

Everything is working fine on MacOS and Ubuntu (just tested).

#### Version
1.5.8

**Comment by pazza83** [comment]
Hi @BtcContributor thanks for picking this up.

The issue is also appearing on:

- Settings > about
- DAO > Bonding > Bonded roles
- DAO > Governance  > Vote results (name / link)
and proposal info screens when clicked on in 'Proposals' and 'Vote results'

**Comment by BtcContributor** [comment]
Thanks, I will take a look. 

My fix already handle those cases @pazza83.

**Comment by pazza83** [comment]
Hi @BtcContributor is this issue raised on Bisq also relate to your fix? https://bisq.community/t/how-to-make-bisq-open-bitcoin-core-as-it-used-to-until-recently/10546

The user cannot create a GitHub issue so if it fixes it I will let them know

**Comment by BtcContributor** [comment]
@pazza83 yes, this should fix also that issue as well.
