### ISSUE TITLE
Backup size over 11 GB

### ISSUE THREAD

**Issue by angubite** [bisq-network/bisq#5263]
### Description

The creation of a backup takes about ten minutes and the backup size is over 11 GB. The last backups were about 0.5 GB. 
A backup folder is created with the current date including the log files as well as a number of additional backup folders from previous dates. These backup folders in turn include a number of backup folders from previous dates and so on. This pattern is passed on from folder to folder. 

#### Version

v1.5.8

### Steps to reproduce

Update to v1.5.8 and create a backup.

### Expected behaviour

Create backup folder of about 0.5 GB

### Actual behaviour

Create backup folder of over 11 GB

### Screenshots

![grafik](https://user-images.githubusercontent.com/79634095/109649502-ea663180-7b53-11eb-8bd9-635c3db9ef20.png)

![grafik](https://user-images.githubusercontent.com/79634095/109649025-3cf31e00-7b53-11eb-8573-fc478aaf5cd2.png)

![grafik](https://user-images.githubusercontent.com/79634095/109649145-657b1800-7b53-11eb-88e8-c7aafb289117.png)

#### Device or machine

Laptop: Win10 Home

**Comment by pazza83** [comment]
Hi @angubite thanks for documenting this issue. I am also experiencing the same large backup issue.

**Comment by ripcurlx** [comment]
@pazza83 @angubite Could you please look into the db folder of the backup to see which file causes this? Thanks!

**Comment by wallclockbuilder** [comment]
My first 2 backups are both =~ 500MB each.

**Comment by RififiCastorjunior** [comment]
The size of the backup depend of the activity of the trader, on my end only one file are above 100MB `backups_DaoStateStore`

**Comment by pazza83** [comment]
Hi @ripcurlx 

I just checked my Bisq and it is not as bad as I thought.

Most of the bulk is in: \roaming\Bisq\btc_mainnet\db\backup

But there is only 300 MB in there.

The total size of the Bisq folder in roaming is 1GB
The total size of the Bisq folder in local is 300 MB

**Comment by ripcurlx** [comment]
> But there is only 300 MB in there.

That is quite similar to what I see in my installation.

**Comment by cd2357** [comment]
> A backup folder is created with the current date including the log files as well as a number of additional backup folders from previous dates. These backup folders in turn include a number of backup folders from previous dates and so on. This pattern is passed on from folder to folder.

This got me thinking.

@angubite when you do the backup from within Bisq, it asks you for the backup location.

What do you select there?

Is it
a) the target folder into which you wish to make the new backup, or
b) the folder containing the previous / latest / a recent backup?

If a) then I can't reproduce the behavior you described. With each new backup, I get a fresh new folder in the chosen target backup folder. None of them contains any previous backup folders.

If b) I can see how Bisq could place one backup within another, which could lead to a "parent" backup folder appearing huge + containing several other backups subfolders as you described.

**Comment by ghost** [comment]
I see that backup contains a lot of logs.

![image](https://user-images.githubusercontent.com/78184669/113950616-4bdb8900-9801-11eb-895a-c514e84f1f40.png)

Why is that? Can I delete them from each backup?

**Comment by cd2357** [comment]
@peterflock About 2-300 MB of logs are normal behavior, AFAIK. You don't need to worry about that, as new logs are added, older ones are automatically removed.

@angubite As per the 3rd screenshot you attached in the description, you placed a backup in a backup in a backup (at least 3 nested levels). See my previous comment https://github.com/bisq-network/bisq/issues/5263#issuecomment-808798720.

When you run the backup:
* Do NOT choose the "previous Bisq backup folder" as destination (for example, `D:\bisq_backups\bisq_backup_2021-03-02-115001`). This can make the top-most folder appear huge, when in fact it just contains many many backups (which are then re-backed-up when you trigger the next backup).
* Instead, as backup destination please choose "the folder in which you wish Bisq to create the backup" (like for example `D:\bisq_backups`).

**Comment by ghost** [comment]
@cd2357 I am thinking, do logs need to be part of the backup at all?
