### ISSUE TITLE
Bug trade failed after update to 1.5.8, error message, BuyerSendCounterCurrencyTransferStartedMessage

### ISSUE THREAD

**Issue by f321x** [bisq-network/bisq#5265]
### Description
An error occurred at task: BuyerSendCounterCurrencyTransferStartedMessage
Exception message: You must have bootstrapped before adding data to the P2P network.
This message shows up right after starting Bisq after the 1.5.8 update.
Then my trade failed and i got a message the funds were locked right after the update (before everything was fine). See added screenshots. Can we fulfill the trade anyways or do we need mediation now?

#### Version

1.5.8

### Steps to reproduce

Install 1.5.8 update, start bisq.

### Screenshots

Screenshots added
![Bildschirmfoto vom 2021-03-02 16-08-10](https://user-images.githubusercontent.com/51097237/109669752-b3ebdf00-7b72-11eb-82bb-64db0e36af04.png)
![Bildschirmfoto vom 2021-03-02 16-09-51](https://user-images.githubusercontent.com/51097237/109669760-b817fc80-7b72-11eb-899e-bc180108a28d.png)
![Bildschirmfoto vom 2021-03-02 16-09-39](https://user-images.githubusercontent.com/51097237/109669773-bc441a00-7b72-11eb-92f3-114f81cf9bb3.png)

#### Device or machine

Ubuntu 20.10

**Comment by f321x** [comment]
Addition: Also it is not possible to me to contact the trade partner because the messaging window always resets after typing in some words and is empty again, so its not possible to write a complete message.

**Comment by ghost** [comment]
Can you provide a log file leading up to the error message?

**Comment by f321x** [comment]
How can i create a log file?

**Comment by ghost** [comment]
Account -> Backup -> Open Directory.  `Bisq.log`

**Comment by f321x** [comment]
[bisq.log](https://github.com/bisq-network/bisq/files/6069992/bisq.log)
Here it is

**Comment by ghost** [comment]
Thanks and thanks for reporting the issue, I'll look into it and will update here. 
 
Are you on [Keybase](https://keybase.io/team/bisq)?  It is much easier to reach out to a mediator or myself and get support for your trade.

**Comment by f321x** [comment]
Yes already wrote the issue in the keybase general chat, you can contact me there. Should i start a mediation with alt+o like the message recommends me to do or should i wait for now?

**Comment by ghost** [comment]
**Problem summary:**

PR https://github.com/bisq-network/bisq/pull/5219 was created to fix a startup issue.  That change to the module startup sequence has caused this problem with the CounterCurrencyTransferStartedMessage re-sent at startup.

Steps to reproduce: (v1.5.8)

- Bob makes offer to buy
- Alice takes offer
- Alice goes offline
- Blockchain confirms
- Bob initiates payment
- Bob shuts down and restarts bisq, then the error message is reported at startup.

When Alice comes online, receives CounterCurrencyTransferStartedMessage from the seednode, clicks on Payment received the trade can finish normally.

I will liase with @ripcurlx and @chimp1984 to work on a fix.

[edit] changed to reference the appropriate PR.
