### ISSUE TITLE
Make the decision which fiat payment account to use more active

### ISSUE THREAD

**Issue by MarcSte** [bisq-network/bisq#527]
A problem arises when a buyer in a fiat-btc trade has more than one bank account registered in the app, and only one of it is sufficently funded for the trade. The buyer forgets to choose the right payment account in the 'Take offer' screen, can't pay from the correct payment account and thereby breaks the contract.

This case has happened here: [Used wrong payment account](https://forum.bitsquare.io/t/payment-account-question-suggestion/286)

Possible solutions:
- Create an extra step to choose pament account with one-sentence advice, if more than one payment account is registered.
- Bold warning message in payment info field (there's enough space to the right of the drop-down menu)

Could be:
**Make sure you choose the correct payment account. If you fail to use the account chosen here, you break the contract.**

**Comment by bitcoinuser** [comment]
Great.

Idea: For national bank payment, users could select more than one bank account. So if the user is unable to transfer with a specific bank account, he could choose the other too, without break the contract.

**Comment by haiqu** [comment]
Yes, I had a problem with this in creating an offer too. I didn't select my bank account and the default was Cash Deposit which is on the top of the list. That trade is still open after two weeks but I've made three sales to my bank account in the meanwhile.

**Comment by cbeams** [comment]
I just had an arbitration case arise (`hrxflalh`) where a seller ran into this UX issue. It's a real issue, and it's come up several other times in trades I've arbitrated.
