### ISSUE TITLE
Add tooltip(on hover) to BondUnlockTime column title

### ISSUE THREAD

**Issue by wallclockbuilder** [bisq-network/bisq#5275]
![Screen Shot 2021-03-04 at 10 39 55 AM](https://user-images.githubusercontent.com/2033945/110013901-05ad7a00-7cd7-11eb-9dc5-999dc788a8f9.png)

I couldn't figure out what unlock time meant or what format it was in. The documentation does not mention that.
I had to actually dig into the code, where it was commented as unlock time in blocks.
A tooltip will make it easy for first time users to hover and learn what unlock time means.

**Comment by BtcContributor** [comment]
If @ripcurlx or others from dev team validate this issue, I can take care of that.

**Comment by wallclockbuilder** [comment]
![image](https://user-images.githubusercontent.com/2033945/110014884-2b874e80-7cd8-11eb-9fdd-d5e527ce4225.jpeg)

This is where I got my answer from

**Comment by wallclockbuilder** [comment]
> If @ripcurlx or others from dev team validate this issue, I can take care of that.

Thanks I will love to use this to get my feet wet. Perhaps you can review my code.

**Comment by wallclockbuilder** [comment]
@ripcurlx You think this is worth working on? 
Assign it to me if so.

**Comment by ripcurlx** [comment]
I think it probably should be the other way round. Show the timeframe (≈25 days) in the column and on hover over the (i) icon show the information that it is further locked until x blocks are passed. So we also communicate better what this unlock time actually means.

**Comment by wallclockbuilder** [comment]
Sounds good. Go ahead and assign it to me.

**Comment by ripcurlx** [comment]
Hint: You'll find the calculation part in the government section, where it is already used to calculate the estimated timeframe for each phases of the cycle.

**Comment by wallclockbuilder** [comment]
I think you mean governance section. I got you.

**Comment by cd2357** [comment]
@wallclockbuilder any updates? You asked to have this assigned to you.

Would be a very useful feature, let us know if you need help with anything.

**Comment by wallclockbuilder** [comment]
It's pretty much done. I discovered another bug that I'm fixing. Will push soon.
