### ISSUE TITLE
DAO and Fund section in Bisq seems to be missing ability to copy links 

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#5278]
### Description

A minor annoyance of mine but the whole DAO and Fund section in Bisq seems to be missing ability to copy links.

Links all have a little link icon. They all seem to be missing the little copy icon.

This is most annoying when doing a transaction and then providing the Tx ID. Currently I users have to visit the website and then copy the Tx ID from the URL or the webpage. It would be much easier if users could just press the little 'copy icon'. It would also reduce the risk of user less error, 

#### Version

v1.5.9

### Steps to reproduce

Go to the DAO section is Bisq (No option to copy links in multiple sections)
Go to the Funds section is Bisq (No option to copy links in multiple sections)

You can copy from places such as Trade ID details screen

### Expected behaviour

Go to the DAO section is Bisq (option to copy links in multiple sections)
Go to the Funds section is Bisq (option to copy links in multiple sections)

Use the same icon as in the Trade ID details screen

### Screenshots

![funds - Copy](https://user-images.githubusercontent.com/66367547/110191187-06e9be80-7e1f-11eb-84f1-d388b7f22e9e.png)
No option to copy Tx ID

![bonds - Copy](https://user-images.githubusercontent.com/66367547/110191190-0d783600-7e1f-11eb-8b10-2464a6c9c359.png)
No option to copy Tx Id or GitHub issue

**Comment by BtcContributor** [comment]
I can take care of this.

**Comment by BtcContributor** [comment]
Update: I had several testing to do for Bisq and other fixes but I already started with this.
It will be released ASAP.

**Comment by pazza83** [comment]
Hi @BtcContributor how are you progressing with this issue?

**Comment by BtcContributor** [comment]
Hi @pazza83,
unfortunately this is stuck at this moment as I had other tasks to do.

Btw, I am honestly having some issues implementing the fix, so if this is high priority please assign it to someone else.

**Comment by pazza83** [comment]
Hi @BtcContributor thanks for letting me know.

@xyzmaker123 let me know if you would like to work on this issue.

**Comment by ghost** [comment]
@pazza83 There is no "copy" button there, but links are clickable (after click browser with btc/bsq explorer is opened). Isn't it enough?

**Comment by pazza83** [comment]
Hi @xyzmaker123 the copy button is more secure, private and user friendly.

When trying to get transaction IDs you are forced to open a new window with a blockchain explorer and then copy the transaction ID from that site. This has some privacy concerns and creates a second point of error that you are copying the transaction id from a 3rd party website not from within your Bisq app.

**Comment by ripcurlx** [comment]
> Hi @xyzmaker123 the copy button is more secure, private and user friendly.
> 
> When trying to get transaction IDs you are forced to open a new window with a blockchain explorer and then copy the transaction ID from that site. This has some privacy concerns and creates a second point of error that you are copying the transaction id from a 3rd party website not from within your Bisq app.

But you are asked the first time you click on such link if you just want to copy them or open them within a browser.

**Comment by ghost** [comment]
@ripcurlx Got it - just wanted to be sure everybody agree we want this feature.

**Comment by xyzmaker123** [comment]
@chimp1984 Any input here?

**Comment by xyzmaker123** [comment]
@ripcurlx, @chimp1984, @pazza83  I'm considering implementing it, and I wonder if I'll be able to charge 350USD for it?

**Comment by ripcurlx** [comment]
The problem I see with this feature request is the concrete implementation part. ATM there is the icon for the link, which is used everywhere in the client. When we want to introduce the copy icon, where should it be? Next to the link icon would be confusing IMO.

**Comment by pazza83** [comment]
Hi @ripcurlx 

Maybe having the transaction IDs selectable / copy-able as per @jmacxx's solution here https://github.com/bisq-network/bisq/pull/5747 would work.

Main issue is trying to navigate the DAO > Wallet > Transaction information none of the text is able to be selected.
