### ISSUE TITLE
Cannot pair with Bisq Mobile – Timeout error discovering webcam & MobileNotificationService certificate expired

### ISSUE THREAD

**Issue by pjfreese** [bisq-network/bisq#5279]
### Description

When I go to Accounts > Notifications > Scan QR Code to pair the Bisq desktop app with Bisq Mobile, I receive an error dialogue `java.util.concurrent.TimeoutException: Webcams discovery timeout (1000 ms) has been exceeded`

When I email myself a pairing token from my iPhone, I am able to enter it into the Bisq desktop notification pairing field — where it remains — but that does not result in pairing with the mobile app or any other activity.

bisq.log (attached) shows separate errors of the notification certificate having expired and a timeout error discovering the webcam. (I can confirm my webcam works properly in other apps, and those apps are properly requesting user permission via com.apple.TCC)

### Version

Bisq desktop version 1.5.9 (macOS)

```
java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```
(editing comment to add java version) 

Bisq mobile version 1.1 (iOS)

Network version: 1; P2P message version: 10; Local DB version: 1; Trade protocol version: 3

### Steps to reproduce

Open the Bisq desktop app and enter password. In the menu bar, click "Account", then "Notifications" in the submenu. 

Open the Bisq mobile app and tap "Pair" to generate a QR code.

_QR method:_
1. In the Bisq desktop app, click the button "Scan QR Code" 
2. Receive error dialog box. 

_Pairing Token method:_
1. In the Bisq desktop app, either click "I don't have a webcam" or fail the QR method approach. This will generate a field for submitting a pairing token.
2. In the Bisq mobile app, on the screen with the QR code, tap "send token to myself" to generate an email containing the pairing token.
3. Send email to self, open that email on the same computer as the Bisq desktop app, and copy the pairing token.
4. Paste that pairing token into the Account > Notifications > Pairing Token field.
5. There is no resulting activity/response on either the desktop or mobile app.

### Expected behaviour

_QR method:_
On macOS, this should request that the user approve Bisq's access to the webcam if that hasn't happened before, then the webcam should become active. When the Bisq Mobile QR code is held up in the camera's field of vision, this should result in pairing between the desktop and mobile app.

_Pairing Token method:_
Entering the pairing token into the submission field should result in pairing between the desktop and mobile app.

### Actual behaviour

_QR method:_
The desktop app brings up an error dialog box. (Screenshot and Bisq.log attached below.)

_Pairing token method:_
No error message or response from either the desktop or mobile app.

### Screenshots

<img width="1005" alt="bisq_webcam_error_dialog" src="https://user-images.githubusercontent.com/34946742/110196168-a1360c00-7df7-11eb-8edf-86752f38c058.png">

### Device or machine

_OS:_
macOS Big Sur version 11.2.2

_Laptop:_
Model Name:	MacBook
Model Identifier:	MacBook10,1
Processor Name:	Dual-Core Intel Core i5
System Firmware Version:	429.80.1.0.0

_Built-in camera:_
Model ID: Apple Camera VendorID_0x106B ProductID_0x1570

### Additional info

Prior report of Bisq notification certificate expiration
#https://bisq.community/t/solved-i-cant-receive-notification-today/8386

Prior report of Bisq webcam failure on Mac
#https://github.com/bisq-network/bisq/issues/4374

Active non-Bisq issue with Java developer troubleshooting webcam permissions on Mac
#https://github.com/sarxos/webcam-capture/issues/723

[bisq.log](https://github.com/bisq-network/bisq/files/6094763/bisq.log)

**Most relevant portion:**
```
Mar-05 20:25:35.948 [sendMobileNotification-42697...] INFO  b.c.n.MobileNotificationService: sendMobileNotification result: Error: java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Received fatal alert: certificate_expired 
Mar-05 20:25:35.948 [JavaFX Application Thread] ERROR b.c.n.MobileNotificationService: sendMessage failed. throwable=java.lang.IllegalArgumentException: Result was not 'success'. result=Error: java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Received fatal alert: certificate_expired 
Mar-05 20:25:42.718 [JavaFX Application Thread] INFO  b.d.m.a.c.n.MobileNotificationsView: Start WebCamLauncher 
Mar-05 20:25:42.730 [Thread-99] INFO  c.g.s.w.Webcam: WebcamDefaultDriver capture driver will be used 
Mar-05 20:25:43.732 [Thread-99] ERROR b.d.m.a.c.n.WebCamLauncher: java.util.concurrent.TimeoutException: Webcams discovery timeout (1000 ms) has been exceeded 
Mar-05 20:25:43.732 [webcam-discovery-service] ERROR c.g.s.w.d.b.WebcamDefaultDriver: Processor has been interrupted 
Mar-05 20:25:43.734 [JavaFX Application Thread] ERROR b.d.m.a.c.n.MobileNotificationsView: java.util.concurrent.TimeoutException: Webcams discovery timeout (1000 ms) has been exceeded 
```

**Comment by pjfreese** [comment]
Confirmation that the iOS certificate has indeed expired.
#https://github.com/bisq-network/roles/issues/82#issuecomment-788224677

Thank you @devinbileck

**Comment by ripcurlx** [comment]
@pjfreese @devinbileck released a new iOS version a couple of days ago that fixes some other issues as well. The certificate issue you've mentioned was already fixed in the release before.
