### ISSUE TITLE
The package 0.4.9 64 bit .deb is of bad quality

### ISSUE THREAD

**Issue by OpenGrid** [bisq-network/bisq#528]
Package manager on Ubuntu 14.04 declares says so

**Comment by ManfredKarrer** [comment]
Yes I think I saw that as well once. Don't know really why. I use the Oracle Java packager and seems somthing is not setup like it should be. If anyone has an idea the build script is in package/linux.

**Comment by rodol-fo** [comment]
Hello @OpenGrid - Does the package install via command line?
`sudo dpkg -i Bitsquare-64bit-0.4.9.deb`

I am on Xubuntu 15.04 and can't reproduce the bad quality .deb package message.

**Comment by ripcurlx** [comment]
Closing as we didn't run into any build issues for deb packages in the last couple of months. Feel free to re-open if the problem still exists.
