### ISSUE TITLE
Transferwise Payment Accounts are created without any Trade Currencies when using bisq-cli

### ISSUE THREAD

**Issue by jimmyneutront** [bisq-network/bisq#5281]
### Description

When a Transferwise payment account is created using bisq-cli, it is not assigned any trade currencies. Because of this, any offers created using Transferwise as a payment method will not be visible to any takers.

#### Version

Bisq daemon version 1.5.9 (Linux)
OpenJDK version 11.0.9.1 2020-11-04
### Steps to reproduce

1. Let Alice create a new Transferwise payment account using the 'createpaymentacct' command, which produces the following output: (Note that the 'Currency' field is blank!)
payment account saved
Name                                Currency    Payment Method    ID
Tw: alice@example.com                     TRANSFERWISE     [alice's tw id here]

2. Let Bob create a new Transferwise payment account using the 'createpaymentacct' command, which produces the following output:
payment account saved
Name                                Currency    Payment Method    ID
Tw: bob@example.com                      TRANSFERWISE     [bob's tw id here]

3. Alice creates an offer to buy BTC with CHF using the 'createoffer' command and her Transferwise payment account ID.

4. Alice uses the 'getmyoffers' command to view her CHF offers in the BUY direction, and sees the Transferwise offer that she just created.
### Expected behaviour

5. [Expected] Bob should be able to use the 'getoffers' command to view CHF offers in the BUY direction and see Alice's offer as a result.

### Actual behaviour

5. [Reality] Bob uses the 'getoffers' command to view CHF offers in the BUY direction and sees nothing but the message "no BUY CHF offers found"

#### Additional info

This problem is related to commit #4944 which causes Transferwise payment accounts to be created with no trade currencies by default. Usually, trade currencies are added via checkboxes in the Bisq app, but there is currently no way to add currencies using the API.

**Comment by ghubstan** [comment]
I will work on this soon.

**Comment by ghubstan** [comment]
PR https://github.com/bisq-network/bisq/pull/5284 should resolve this.

**Comment by ghubstan** [comment]
PR https://github.com/bisq-network/bisq/pull/5284 should close this.

**Comment by ripcurlx** [comment]
Closing as complete.
