### ISSUE TITLE
Offer error

### ISSUE THREAD

**Issue by toddrunner** [bisq-network/bisq#5289]
An error occurred when taking the offer.

An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 676109, myLockTime=676666

No funds have left your wallet yet.
Please try to restart your application and check your network connection to see if you can resolve the issue.Please try to restart your application and check your network connection to see if you can resolve the issue.

**Comment by ripcurlx** [comment]
This can happen if your trading peer is not in sync. It should solve itself over time as soon as the peer is fully synced again.
