### ISSUE TITLE
Failed to Generate Key

### ISSUE THREAD

**Issue by scottbourne** [bisq-network/bisq#529]
Couldn't generate key
[bitsquare.log.txt](https://github.com/bitsquare/bitsquare/files/371360/bitsquare.log.txt)

**Comment by ManfredKarrer** [comment]
Did you build yourself form source code? If so you need to follow exactly the steps in the build doc:
https://github.com/bitsquare/bitsquare/blob/master/doc/build.md#prerequisites
I see in the log that u have jre: 1.8.0_20-b26 so it seems you are not using the binary as they have a more recent jre.

**Comment by scottbourne** [comment]
No, I downloaded the .exe (64-bit) and installed it that way.

**Comment by ManfredKarrer** [comment]
Have you used an older verion before? If so, can you delete the app dir (or if you don't have any funds, offers,... you can uninstall Bitsaquare, but that removes the data dir, so better backup that first if u do that).
App dir:
C:\Users\asd\AppData\Local\Bitsquare

Data dir: 
C:\Users\asd\AppData\Roaming\Bitsquare

I just checked my win VM and tested it again and all works fine.

If you look intot the log it should show 1.8.0_92-b14 as JRE version.

**Comment by scottbourne** [comment]
No, this was my first-time installation.

Nothing to loose, so I'll remove it and download and try again.  

Thanks

**Comment by scottbourne** [comment]
OK, I removed the old directories, downloaded, reinstalled once more and no errors!

Thanks for the quick response,

Scott

**Comment by ManfredKarrer** [comment]
Ah good. Maybe u  installed an older version before?

**Comment by scottbourne** [comment]
Can't explain it - this was the first time I downloaded and installed the software (I heard your interview on Epicenter Bitcoin and went right to the web site.  Good interview, by the way!).

Thanks again for the speedy response!

**Comment by ManfredKarrer** [comment]
Hm, strange... just looked again to the log. Its v0.4.9 but uses the wrong jre. I assume you have java installed as well. So there might be some case where the app does not start up with the packaged jre but with the system jre, where stuff is missing causing that issue.
No idea why that can happen though, but seems the java packager for windows does not work very well. Got a few other issues as well...

Maybe u can check in the terminal with java -version if u get 1.8.0_20-b26.

Thanks for your feedback!
