### ISSUE TITLE
Unhide custom mining fee option(from settings-page to send-bitcoin-page)

### ISSUE THREAD

**Issue by wallclockbuilder** [bisq-network/bisq#5298]
### Description
Sending bitcoin from Bisq with a custom mining fee is impossible. 
The option does not exist on the `send bitcoin` page.
A closer investigation shows the option exists but is hidden 2 levels deep under `Preferences` on the `settings` page.

#### Version
v1.5.9

### Steps to reproduce
![send bitcoin form should but does not have custom tx fee](https://user-images.githubusercontent.com/2033945/111016590-af3ddc80-8363-11eb-9c04-d0bbb69edb8b.png)
Try sending bitcoin with custom mining fees.

### Expected behaviour
![send bitcoin should have custom tx fee](https://user-images.githubusercontent.com/2033945/111017182-a995c600-8366-11eb-9efa-b711be35bdab.png)
Custom mining fee option should be on the `send bitcoin` page.

### Actual behaviour
![custom mining fee should not be in settings  its hard to find  it should be on the send bitcoin page](https://user-images.githubusercontent.com/2033945/111016607-c5e43380-8363-11eb-8f7c-34f1f5962c77.png)
Custom mining fee option does not exist on the `send bitcoin` page.
Custom mining fee option is actually hidden on the settings page.

**Comment by pazza83** [comment]
Good idea. I think this would improve usability. I cannot see why it should not be implemented. 

Should also be on Send BSQ when that allows user to choose sat/vb.

**Comment by ripcurlx** [comment]
@BtcContributor could you comment on this issue so I can assign you to it. Thanks!

**Comment by BtcContributor** [comment]
Hi, yes I would like make a fix of this issue.
Thanks! @ripcurlx
