### ISSUE TITLE
3 timeouts with 0.4.9 on Windows10 64bits

### ISSUE THREAD

**Issue by krynne** [bisq-network/bisq#530]
trade ids : 
#1) 2b19f862-7b15-4779-a574-4b4b6927d1fb
#2) nop
#3) 0700728c-8097-4c16-bb27-d9559ab6f878

The second attempt timed out with no fee being payed (?)...
I relaunched the program before the 3rd attempt.
As a taker, the system checks that the offer is still available before proceeding and I validated as fast as possible.
Something seems wrong here...

**Comment by ManfredKarrer** [comment]
Do you remember the currency/amount/price? So its easier for me to spot those offers.
It can be that the offerer has nto updated to the latest version.

**Comment by krynne** [comment]
EUR/SEPA (SE) for 0.75 @ 637.60 & @625.22€/BTC
I beleive

**Comment by ManfredKarrer** [comment]
Hm, I don't see those offers at all. Mayeb there where just temporary available...
