### ISSUE TITLE
Currency filtering is inconsistent

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#5300]
### Description

Currency filter (selection drop-down menu) is not working consistently. For instance, there are offers for Zcash and for Doge. I can filter only for Zcash, not for Doge. LBC coin was previously not selectable too, but after an LBC altcoin account was 

created. Either I should be able to filter after I have created the specific altcoin account, or I should be able to filter by all altcoins no matter which accounts I have. I assume, the ladder should apply.

#### Version

1.5.9

### Steps to reproduce

Use the drop-down menu to filter for an altcoin. Some you can filter (in my case for instance Zcash), some you cannot (in my case for instance DOGE). 

### Expected behaviour

Currency filter should be consistent, either with after having created that altcoin account, or filtering through all altcoins no matter which altcoin accounts you have

### Actual behaviour

Not possible to filter for certain altcoins.

### Screenshots

![1](https://user-images.githubusercontent.com/66221034/111143384-06bb9280-8586-11eb-8285-ed42d153a79b.jpg)
![2](https://user-images.githubusercontent.com/66221034/111143404-0d4a0a00-8586-11eb-9d3d-823731cfe6a1.jpg)

#### Device or machine

Windows 64 bit

**Comment by Conza88** [comment]
I think I've see fiat national currencies randomly pop back up into my listing.

**Comment by ghost** [comment]
Update: screenshots attached

**Comment by pazza83** [comment]
Default currency selection is missing NGN a currency Bisq is trying to promote.

I am for adding all currencies and not making users have to add them. Not sure if their are any reasons for not doing this?

**Comment by ghost** [comment]
So we want to remove this whole section from Settings -> Preferences
![Screenshot_2022-02-10_10-05-28](https://user-images.githubusercontent.com/84982606/153374366-92bc2239-6610-4fa5-b48d-6f0e65a3ddf6.png)

and show all currencies in filter?

**Comment by pazza83** [comment]
Hi @xyzmaker123 

I think it would be good to make all currencies to be added be default (national currencies and altcoins),

The section can be kept. Users can then use it to remove currencies they do not want to see.

I think removing currencies is better than adding currencies for user experience.

**Comment by ghost** [comment]
I think [set of possible national currencies](https://github.com/bisq-network/bisq/blob/235e2fa9f1927fdc38ec5ce3ff5b453b3021e962/core/src/main/java/bisq/core/locale/LocaleUtil.java#L30-L276) is really big - I don't think it's good idea to add them all by default. Default national currencies are [defined in code](https://github.com/bisq-network/bisq/blob/a113b3ddfb4224ca768ab0d94b8734a2299092bc/core/src/main/java/bisq/core/locale/CurrencyUtil.java#L106-L113)

Similar situation with altcoins - list of available by default is also [defined in code](https://github.com/bisq-network/bisq/blob/a113b3ddfb4224ca768ab0d94b8734a2299092bc/core/src/main/java/bisq/core/locale/CurrencyUtil.java#L151-L162). We could possibly extend this list about popular altcoins like Dogecoin.

**Comment by pazza83** [comment]
Hi @xyzmaker123 I have been using Bisq for a while now with all national currencies / altcoins selected and have experienced no decrease in usability.

It just requires one to remember the currency name / ticker when selecting the required market.

My concerns are if currencies are missing users like the one here from [Philippines](https://bisq.community/t/btc-php-options/11371/4) will think their country is not supported.

I think having all currencies selected by default is a net positive.

**Comment by ghost** [comment]
OK, I'll prepare appropriate pull request.
