### ISSUE TITLE
Unhide custom mining fee option for sending BSQ

### ISSUE THREAD

**Issue by wallclockbuilder** [bisq-network/bisq#5304]
### Description
Sending BSQ with a custom mining fee is impossible as there is no option on the `Send BSQ` page.
A closer investigation reveals that the option for sending BSQ with a custom fee exists but is hidden 2 levels deep under `Settings`-->`Preferences`.

### Steps to reproduce

Try sending BSQ with a custom mining fee.

### Expected behaviour
![sending BSQ should have custom fee option on the same page](https://user-images.githubusercontent.com/2033945/111087506-39f71680-84df-11eb-8163-f38309b17d4b.png)
Custom mining fee option should be on the `Send BSQ` page.

### Actual behaviour
![sending bsq does not have custom fees](https://user-images.githubusercontent.com/2033945/111087312-2eefb680-84de-11eb-98c5-2c9f9059daef.png)
`Send BSQ` page does not have custom mining fee option.

![custom mining fee should not be in settings  its hard to find  it should be on the send bitcoin page](https://user-images.githubusercontent.com/2033945/111087332-44fd7700-84de-11eb-81a6-8ca56217e6f4.png)
Custom mining fee option is actually hidden 2 levels deep under `Settings` --> `Preferences`

**Comment by wallclockbuilder** [comment]
This can be implemented after the custom mining fee option for Bitcoin(#5298) has been coded.

**Comment by Conza88** [comment]
Nice! #5046 related.

**Comment by wallclockbuilder** [comment]
Ready to implement. Waiting for assignment.

**Comment by BtcContributor** [comment]
@wallclockbuilder Hi, any update on this?

@ripcurlx if he is unavailable I would like to take this issue as I already implemented #5312

**Comment by wallclockbuilder** [comment]
Its in the works. I'll let you know when its ready so you can review.
