### ISSUE TITLE
Transaction Details dialog should display exact amount of BTC sent. No more. No less.

### ISSUE THREAD

**Issue by wallclockbuilder** [bisq-network/bisq#5305]
### Description

Confirmation for BTC sent displays `0.00BTC` sent.
This is because the BTC sent has more than 2 decimal places.
#### Version
v.1.5.9

### Steps to reproduce
Send a Bitcoin transaction with an amount that has more than 2 decimal places e.g. 0.00001234BTC.

### Expected behaviour
Confirmation dialog should display exactly what I sent.

### Actual behaviour
![sending confirmation shows ast 0 00BTC when BTC sent is has more than 2 decimal places  It should display full amount](https://user-images.githubusercontent.com/2033945/111087854-3795bc00-84e1-11eb-98e5-57106eb10455.png)

Confirmation dialog displays `0.00BTC` Sent.

**Comment by BtcContributor** [comment]
This happened to me yesterday on Mainnet and I wanted to fix it.

However, I am not able to reproduce it on Regtest v1.5.9, although I am following your steps.

**Comment by wallclockbuilder** [comment]
Please assign to me.

**Comment by ghost** [comment]
I am testing a fix.
[Update] Fix tested & ready.
