### ISSUE TITLE
Let user enter human friendly time for locking up BSQ. Let Bisq handle the conversion to block time.

### ISSUE THREAD

**Issue by wallclockbuilder** [bisq-network/bisq#5306]
### Description
Locking up BSQ with a human friendly time is not possible.
User is required to specify time in blocks.
Google does not show any time to block time converters.
User is forced to do it by hand. After multiple tries its apparent the human calculated time in blocks almost always never matches what Bisq comes up with.
Allowing the human to specify time in a format familiar to them, makes the process straightforward. No googling needed. Bisq handles the conversion from human time to block time.

#### Version
v1.5.9

### Steps to reproduce
Try locking up some BSQ for any amount of time.

### Expected behaviour
![Expected - User enters human friendly time  Bisq displays the approximate time in blocks](https://user-images.githubusercontent.com/2033945/111088945-d375f680-84e6-11eb-9c10-7e48120f729b.png)
User enters human friendly time (Bisq displays the approximate time in blocks).

### Actual behaviour
![Actual - user has to enter unlock time in blocks](https://user-images.githubusercontent.com/2033945/111088950-da046e00-84e6-11eb-85a5-164c88a396fb.png)
User has to enter `Unlock time in blocks`

![Actual - user has to calculate unlock time in blocks themselves and is likely to be wrong as it is not clear what algorithm bisq is using for the block time calculation](https://user-images.githubusercontent.com/2033945/111089141-c4437880-84e7-11eb-8d09-e394aca83bd9.png)
User has to calculate unlock time in blocks themselves and is likely to be wrong as it is not clear what algorithm bisq is using for the block time calculation

![Actual - bisq shows human friendly time on the confirmation screen AFTER locking up bsq. It should be on the lock page](https://user-images.githubusercontent.com/2033945/111088948-d83aaa80-84e6-11eb-848c-13aab5c5ea7a.png)
Bisq shows human friendly time on the confirmation screen AFTER locking up bsq. It should be on the lock page instead. Having this on the lock page would have prevented the human from going through so many headaches calculating it in the first place.

**Comment by wallclockbuilder** [comment]
This will also make it possible for those not in the tech/crypto community to use the lockup tool as long term investors.

**Comment by wallclockbuilder** [comment]
![Apparently the formula is to multiply the number of days by 1440 and divide by 10](https://user-images.githubusercontent.com/2033945/111089565-b1ca3e80-84e9-11eb-839a-cb8fd6c8ee70.png)
Apparently the formula for calculating time in blocks is to multiply the number of days by 1440 and divide by 10.
Took forever to figure out. Then I found out on the confirmation page Bisq could have done it for me this whole time.

**Comment by Conza88** [comment]
> Then I found out on the confirmation page Bisq could have done it for me this whole time.

Able to elaborate on that? What confirmation page? ;o
All your work is still valid though, yeah? 

I've not gone through this process.

**Comment by wallclockbuilder** [comment]
The confirmation page is the dialog bisq shows you after a successful 'Send BTC' transaction.

**Comment by wallclockbuilder** [comment]
Requesting assignment.

**Comment by cd2357** [comment]
> Requesting assignment.

@wallclockbuilder no need to wait for assignment :) When you have the change ready, feel free to open a PR and link it to this issue.

Let us know if you have any issues or face any roadblocks.
