### ISSUE TITLE
Add a filter to the 'Funds' section in Bisq to able searching of; Trade IDs, Tx IDs, BTC amount, etc

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#5307]
### Description

To make it easier to search for; Trade IDs, Tx IDs, BTC amount, etc in the Bisq client their is the possibility to add a search filter in the following sections:

- Portfolio > My Open Offers
- Portfolio > History'
- Support > Mediation
- Support > Arbitration 

This makes it easy to find information quickly.

The ability to search for ; Trade IDs, Tx IDs, BTC amount, etc is missing from the following sections:

- Funds > Receive Funds
- Portfolio > Send Funds
- Support > Locked Funds
- Support > Transactions

If you have lots of transactions this makes it difficult to find information quickly in the funds section.

Therefore, a filter should be added to the 'Funds' section in Bisq

#### Version

v1.5.9

### Steps to reproduce

Go to the Funds section in Bisq and try and search for ; Trade IDs, Tx IDs, BTC amount. It has to be done manually. There is no search option.

### Expected behaviour

Go to the Funds section in Bisq and be able to search for ; Trade IDs, Tx IDs, BTC amount. It has to be done manually. There is no search option.

### Screenshots

![portfolio filter - Copy](https://user-images.githubusercontent.com/66367547/111092884-486d1e80-852f-11eb-8395-e6cf62b4f5d3.png)
Example of funds filter

![funds filter - Copy - Copy](https://user-images.githubusercontent.com/66367547/111092953-79e5ea00-852f-11eb-841c-668442ee85ce.png)
Example of missing funds filter

**Comment by pazza83** [comment]
Hi are there any @bisq-network/bisq-devs able to take this on?

**Comment by wallclockbuilder** [comment]
Yes.

**Comment by pazza83** [comment]
Hi @wallclockbuilder how are you progressing with this issue?

**Comment by pazza83** [comment]
Hi @xyzmaker123 let me know if you would like to work on this issue.

**Comment by ghost** [comment]
@pazza83 I'm starting working on this issue now
