### ISSUE TITLE
Separate Transaction Details and Trade ID in 'Reserved Funds', 'Locked Funds' and 'Transactions' sections in Bisq

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#5308]
### Description

The Funds section in Bisq becomes a little difficult to use when there is a large amount of transactions.

One proposal to make it more usable is to [add a filter to the 'Funds' section in Bisq to able searching of; Trade IDs, Tx IDs, BTC amount.](https://github.com/bisq-network/bisq/issues/5307)

Another suggestion is to separate transaction details and trade ID in the following sections

- Reserved Funds
- Locked Funds
- Transactions

This would allow for effective sorting of columns and make it easier to sort Trade IDs and transaction details both natively in the Bisq app, but also when exporting to CSV.

#### Version

v1.5.9

### Steps to reproduce

Try sorting by Trade ID in the above sections. You will not be able to. Want to find a specific trade ID? You will need to spend some time to do so if you have a large number of transactions.

Try exporting the above sections to a CSV file. You still will not be able to sort by trade ID without some additional work.

### Expected behaviour

It should be easy to sort by trade ID.

### Actual behaviour

It is impossible to sort by trade ID

### Screenshots

As an example my current Bisq wallet has almost 2,500 transactions. This makes finding a specific trade ID a pain. Here is a screen shot showing the column that combines the transaction details with the Trade ID. These should be separated into two columns.

![transactions2](https://user-images.githubusercontent.com/66367547/111094016-38a30980-8532-11eb-9b69-2709cca03e8f.png)

**Comment by wallclockbuilder** [comment]
Makes a lot of sense. 
Seems obvious in hindsight.

**Comment by pazza83** [comment]
They are separate everywhere else. It is only the Funds section they have been combined for some reason.

**Comment by pazza83** [comment]
Hi @wallclockbuilder think you would be able to take this issue on?

**Comment by wallclockbuilder** [comment]
Yes.

**Comment by pazza83** [comment]
@wallclockbuilder that is great. I just posted a lot more issues that are in need of a dev. Might be some other things you would like take on also.

**Comment by wallclockbuilder** [comment]
Tag moi!

**Comment by pazza83** [comment]
> Tag moi!

Thanks will send you a Keybase message now 👍

**Comment by pazza83** [comment]
Hi @wallclockbuilder how are you progressing with this issue?

**Comment by pazza83** [comment]
This would be good to implement still

**Comment by pazza83** [comment]
Hi @xyzmaker123 let me know if you would like to work on this issue.
