### ISSUE TITLE
Error  cannot run the program

### ISSUE THREAD

**Issue by vikezz** [bisq-network/bisq#531]
After entering the bridge lines I got the error message:

> We tried to restart Tor 4 times, but it continued to fail with error message:
> Cannot run program "/home/amnesia/.local/share/Bitsquare/mainnet/tor/tor" (in directory "/home/amnesia/.local/share/Bitsquare/mainnet/tor"): error=2, No such file or directory
> 
> Please check your internet connection and firewall and try to start again.

Please help with suggestions for troubleshooting the error.

OS: Tails 2.4

**Comment by ManfredKarrer** [comment]
Seems you have some connection issues. Can you try to test if Torbrowser is working? Maybe there is some firewall setup preventing Bitsquare Tor to connect?

**Comment by vikezz** [comment]
Hi Manfred, 

Thanks for your quick reply :) 

My Tor browser is working flawlessly without connection issues and I'm running a simple Shorewall one-interface firewall configuration.

**Comment by ManfredKarrer** [comment]
So I assume there is an issue with the firewall not allowing the Bitsquare Tor instance to connect. The Tor instance Bitsquare uses is the same as the one used inside Tor Browser. Maybe you can try to shutdown Tor browser and see if that helps?

**Comment by vikezz** [comment]
Alrighty, I'll try that and give an update when I know more. Thanks for your help so far :)

**Comment by ManfredKarrer** [comment]
Could you solve the issue?

**Comment by ManfredKarrer** [comment]
Assuming it is resolved, otherwise re-open.

**Comment by blabno** [comment]
I'm getting this on linux:

>ERROR b.n.p2p.network.TorNetworkNode: Tor node creation failed: java.io.IOException: java.io.IOException: Cannot run program "/mnt/pen/Bisq/btc_mainnet/tor/tor" (in directory "/mnt/pen/Bisq/btc_mainnet/tor"): error=13, Permission denied 

however it seems that the tor file has correct (executable) permission:

>ls -l /mnt/pen/Bisq/btc_mainnet/tor
-rw-r--r--  1 bernard bernard 4295464 Mar 18 06:46 geoip
-rw-r--r--  1 bernard bernard 2615115 Mar 18 06:46 geoip6
-rwxr--r--  1 bernard bernard 2282608 Mar 18 06:46 libcrypto.so.1.0.0*
-rwxr--r--  1 bernard bernard  371064 Mar 18 06:46 libevent-2.1.so.6*
-rwxr--r--  1 bernard bernard  622427 Mar 18 06:46 libgmp.so.10*
-rwxr--r--  1 bernard bernard  486600 Mar 18 06:46 libssl.so.1.0.0*
drwxr-xr-x  2 bernard bernard    4096 Mar 18 06:46 libstdc++/
drwxr-xr-x 13 bernard bernard    4096 Mar 18 06:46 PluggableTransports/
-rwxr-xr-x  1 bernard bernard 3190832 Mar 18 06:46 tor*
-rw-r--r--  1 bernard bernard     707 Mar 18 06:46 torrc

This must be something related to running from usb flash drive...
Right, just a glimpse at /etc/mtab and I see this:
 >/dev/sda2 /mnt/pen ext4 rw,nosuid,nodev,noexec,relatime,data=ordered 0 0

Critical bit is `noexec` which means that executables cannot be run from that partition.

A quick fix is to add dedicated entry just for mounting usb flash drive with Bisq:
>/dev/sda2       /mnt/Bisq       auto    noauto,user,exec        0 0

Now I can run Bisq from my usb flash drive with `--appDataDir=/mnt/Bisq/Bisq`.
