### ISSUE TITLE
Display total fee estimate when choosing to fund trade with BTC or BSQ

### ISSUE THREAD

**Issue by phinneaus** [bisq-network/bisq#5327]
### Description

When issuing a maker offer, user is presented with the option of funding the transaction with either BTC or BSQ.   BSQ appears to be significantly cheaper, but this does not take into account that there is an extra input / output to the transaction, resulting in mining fees that can be significantly higher.

Suggest displaying the total estimated cost (trade fee + mining fee estimate) when selecting between BTC and BSQ.

![paste](https://user-images.githubusercontent.com/79758657/111654584-e33b5680-87d6-11eb-98b6-4bee3e1b1e17.png)

Here are the two steps when choosing BSQ:
![Screenshot from 2021-03-18 16-22-34](https://user-images.githubusercontent.com/79758657/111661325-efc2ad80-87dc-11eb-9242-6cd8ba3688e5.png)
![Screenshot from 2021-03-18 16-23-30](https://user-images.githubusercontent.com/79758657/111661384-fc470600-87dc-11eb-8d58-19ecfb3d7d3b.png)

And here are the two steps when choosing BTC:
![Screenshot from 2021-03-18 16-22-16](https://user-images.githubusercontent.com/79758657/111661445-05d06e00-87dd-11eb-880c-948a1b51fab1.png)
![Screenshot from 2021-03-18 16-22-55](https://user-images.githubusercontent.com/79758657/111661464-0963f500-87dd-11eb-972e-0cd212991b35.png)

Total estimated fees in USD: $14.14 for BTC, $21.38 for BSQ (51% higher)

#### Version

1.5.9

### Steps to reproduce

1. Create offer to buy
2. Observe trade fee currency options between BTC and BSQ

### Expected behaviour

In addition to trade fee, show mining fee so user can evaluate total cost of trade before committing.

### Actual behaviour

Trade fee alone is displayed on the initial create offer screen, estimated mining fee is not shown until the next step for committing the offer.

**Comment by wallclockbuilder** [comment]
What statistics are you using to arrive at the 80% higher probability? It'll be helpful if you can show a screenshot comparison, bsq vs btc.

**Comment by phinneaus** [comment]
Thanks @wallclockbuilder - I got the 80% # from the thread in Keybase, that was lazy of me, I'm sorry.

I added a set of screenshots to the original description and updated that - in my trial it was just over 50% higher total fees to use BSQ.  

Especially since a user might click "Don't Show Again" on the confirmation screen, I think it would be helpful to push the mining fee estimate forward to the initial screen with the toggle.  

Let me know if you have any feedback on that, and thank you again!

**Comment by wallclockbuilder** [comment]
$BSQ increased the mining fee by 89%.
Thats an extra `17,000 Satoshis` =~$10 #satstackers would rather avoid.
|
|
Mining fees increased by $10
![Mining fee paid when fees in BTC](https://user-images.githubusercontent.com/2033945/111665951-791fb300-87d0-11eb-8eb4-f5fe279bcbbf.png)
 from about $11
|
|
![Mining fee paid when fees in BSQ](https://user-images.githubusercontent.com/2033945/111665963-7cb33a00-87d0-11eb-983d-d83aad8fceba.png)
to about $21

**Comment by wallclockbuilder** [comment]
The cause of all this is the tx size. The tx size in vBytes for a trade fee(e.g. $1) is bigger in BSQ than BTC because the bitcoin wallet has segwit implemented. BSQ does not. Which reflects in the higher mining fee.

This is  will be fixed when Segwit is fully implemented for BSQ.
Part one has already been merged into the v1.6.0 release(https://github.com/bisq-network/bisq/releases/tag/v1.6.0)
BSQ Segwit has been scheduled for activation at bitcoin block height 680300, which is approx April 25th(about a month away).

**Comment by Aman-1412** [comment]
> Part one has already been merged into the v1.6.0 release(https://github.com/bisq-network/bisq/releases/tag/v1.6.0)
> BSQ Segwit has been scheduled for activation at bitcoin block height 680300, which is approx April 25th(about a month away).

Looks like the second part of the PR was merged 3 hours ago and will be part of 1.6.3 https://github.com/bisq-network/bisq/pull/5109

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/47253594/116623193-7d7cd700-a90b-11eb-8a69-e87266b89087.png)

**Comment by phinneaus** [comment]
@jmacxx - are you indicating that it is almost never a good idea to fund with BSQ?  As a new user I was fairly swayed by all the comments in the documentation about how significant the savings would be for using BSQ.  If your graphic is indicative of the situation moving forward those statements should probably be softened or clarified.

**Comment by ghost** [comment]
It depends on trade size - the chart above is an example for "small" offers.  You have to consider the different dynamics of trade size and trading fee vs mining fee at different mempool rates.  The BSQ trading fee is priced at 50% of BTC but for small offers the trading fee is negligible compared to the mining fee.  If you were making an offer for 1 BTC the discount offered by using BSQ would be 50% making it worthwhile.


In defense of the documentation, a year ago mining fees were routinely 10 sats/vB and at that price point using BSQ does give an overall discount.  It could and should be explained more detail so people don't feel they've been scammed, but there is a tendency to gloss over the technicalities for "better UX".  Perhaps if the existing documentation had a link to a "more technical" explanation it would satisfy both sets of users.

**Comment by phinneaus** [comment]
That makes sense.  Just comes down to education and understanding.  FWIW the fiat method I use to trade (Fiat -> BTC) has a fairly low daily max, so .01 BTC is about the biggest possible trade unless I went to cash / postal money order.  Thanks for your feedback!
