### ISSUE TITLE
Trade process blocked waiting for blockchain confirmation

### ISSUE THREAD

**Issue by krynne** [bisq-network/bisq#533]
trade id : 61fc6c1d-6952-4d71-bc30-151ac05ccf34
date : 21/07 13:21:35

now it's 19:10 and still no confirmation of the multisig deposit tx (no trace on blocktrail.com either)
is this "normal" and what is the reason? 
Thx

**Comment by ManfredKarrer** [comment]
If one of the traders used a very small mining fee when sending funds to bitsquare from an external wallet it might take longer. i added a popup warning but people seem to ignore that. inside bitsquare we use a high enough mining fee but what people use form their exterenal wallet is outside of our control. u can check if u open the details window (click on the id) then u see both trade fee tx. open those and check if one is not confirmed and follow back to the unconfirmed tx and check the mining fee.
I wanted to add a fee check to put such deposit tx in quarantene until they are confirmed but it did nto made it to the current release, though planned for future releases.

**Comment by krynne** [comment]
sounds good but I'm not quite sure I understand it all ! ;-)
the "Offer fee" is confirmed, the "deposit tx" shows "seen by 0 peers / 0 confirmations" and the "Taker fee tx" shows nothing...
Don't know how to "follow back" the unconfirmed tx to check the mining fee with blocktrail giving http 404 "Oh snap!" messages.

**Comment by ManfredKarrer** [comment]
Did you open the tx id in the blockexplorer (click on them to open the blockexplorer)? If u like you can email me the 3 tx id s u see in the details popup.

**Comment by krynne** [comment]
I really appreciate your support and I hope my problems help improve this
awesome system.
the tx ids are:
Offer fee
(confirmed): 4c6d5d48277890ae6f31b5a0a851a7c932b1e8fd921bc9f21580d0bb8931c55e
Taker fee
(void): b125d08043105cc18e2e45b5147752823f51966249adf2485c5a5a0aa6bab282
Deposit (seen 0 peers/0
confirms): 20d42b5e70f3c1d6c094b263a13ef090dda81e15cde9f4484aed4aa312b4057b

2016-07-21 21:44 GMT+02:00 Manfred Karrer notifications@github.com:

**Comment by ManfredKarrer** [comment]
I dont find the Takers tx in 2 diff. block explorers. That does not mean that it will not be published. They dont keep track of all transactions in the mempool. Seems the fee was very low :-(. So you have to wait until the trade period times out then you can open a dispute. It might be that the tx gets confirmed in time though.

**Comment by krynne** [comment]
Wait & see it is then I guess.
I hope it will not end up in a dispute even though I am curious about how
dispute resolution works.
Could it be done on purpoise to remove a more attractive offer and favor
one's own offer?
In case of a dispute what would it cost each party (I guess I can look this
up)?
Thx.

2016-07-21 22:19 GMT+02:00 Manfred Karrer notifications@github.com:

**Comment by ManfredKarrer** [comment]
If a dispute happens the loser loses his security deposit, if he was violating the trade protocol. Canceling an open trade is not possible.

**Comment by ManfredKarrer** [comment]
I see that the tx is confirmed now: https://blockchain.info/de/address/3EisnYKWzLfecA5x9cYDwbW2LA27hDdwRE

It was prob. that tx causing the delay:
https://blockchain.info/de/tx/d47eb8bb0a3714bc49c3d2d3246423b1ad1d8f195d3f684a92742caf03fa9850
