### ISSUE TITLE
'Send Funds' reports BTC amount and recipient as NULL following withdrawal

### ISSUE THREAD

**Issue by mattmill30** [bisq-network/bisq#5331]
### Description

After filling out the 'Send Funds' form, selecting particular addresses as funds inputs, and clicking 'Withdraw Selected', and accepting the pop-up confirmation box, the 'Transaction Details' dialog displays:
Amount: 0.00 BTC
Send to: <blank>
TxId: 352d0a9fabb713b1ac823b65e7540f97832e8263d829411987d614329d568652

However, the 'Send funds' interface reflects the withdrawal and all previously selected input addresses disappeared.

Due to a sudden drop in transaction fees, I attempted to click the 'Cancel' button on the 'confirm withdrawal request' dialog immediately after clicking the 'Yes', so I could make a withdrawal with lower fees. This may have contributed to the blank fields, though due to the withdrawal completing successfully, I would have expected the BTC amount and destination address in a confirmation dialog to be obtained from the Bitcoin client subsystem, rather than the Bisq UI, as otherwise subsystem errors may be overlooked.

This is an **extremely serious** UX issue, as we've seen incorrect reporting of balances and transactions by apps result in suicides, such as the notable [robinhood incident](https://www.forbes.com/sites/sergeiklebnikov/2020/06/17/20-year-old-robinhood-customer-dies-by-suicide-after-seeing-a-730000-negative-balance/) and consequent [repercussions](https://www.telegraph.co.uk/technology/2021/02/08/robinhood-sued-suicide-young-trader-thought-had-lost-730000/)

#### Version

v1.5.9

### Steps to reproduce

Haven't attempted to reproduce, but the original steps were:
1. Navigate to 'Funds' > 'Send Funds';
2. Select desired addresses with funds as inputs;
3. Choose "amount includes mining fee";
3. Specify withdrawal address;
4. Provide optional Withdrawal name;
5. Click "Withdraw Selected" button;
6. Review 'Confirm withdrawal request' dialog and agree to withdrawal.

### Expected behaviour
Withdrawal confirmation dialog appears with the following information:
> ####Transaction details
> You have sent BTC.
> Amount: 0.01507989
> Sent to: 17FjUKyydoQ1u44vq2Df47XtcD2rFmdbsd
> TxId: 352d0a9fabb713b1ac823b65e7540f97832e8263d829411987d614329d568652

### Actual behaviour

Withdrawal confirmation dialog appears with the following information:
> ####Transaction details
> You have sent BTC.
> Amount:
> Sent to:
> TxId: 352d0a9fabb713b1ac823b65e7540f97832e8263d829411987d614329d568652
### Screenshots

![image](https://user-images.githubusercontent.com/6415621/111785447-8746ff80-88b4-11eb-806c-bdd608f3ce51.png)

#### Device or machine

Windows 10 20H2

#### Additional info
Transaction accepted: Mar-19 11:34:00.013
Transaction completed: Mar-19 11:40:12.096
[bisq.log](https://github.com/bisq-network/bisq/files/6171380/bisq.log)

**Comment by BtcContributor** [comment]
This issue was already known: #5305

Unfortunately I am not able to reproduce that on Regtest, but I experienced that as well on Mainnet.
@wallclockbuilder is taking care of that

@mattmill30: I suggest you delete those TxID and addresses if they are real.

**Comment by ghost** [comment]
I am testing a fix.
[Update] Fix tested & ready.
