### ISSUE TITLE
Add pop-up warning for peers sellers selling 0.01 using risky payment methods

### ISSUE THREAD

**Issue by m52go** [bisq-network/bisq#5343]
To address the situation raised in https://github.com/bisq-network/proposals/issues/322. 

Pop-up should be shown whenever making a sell offer <= 0.01 BTC or when taking a buy offer <= 0.01 BTC of an unsigned account.

@ripcurlx here is some suggested text.

```
(!) Important

With the recent rise in BTC price, beware that selling 0.01 BTC or less incurs higher risk than before.

It is highly recommended to either:
- make/take offers >0.01 BTC, so sellers only deal with signed/trusted buyers
- keep any deals to sell <0.01 BTC to around ~100 USD in value, as this value has (historically) discouraged scammers 

Bisq developers are working on better ways to secure the payment account model for such smaller trades. Join the discussion here: [HYPERLINK:https://github.com/bisq-network/bisq/discussions/5339].
```

**Comment by m52go** [comment]
Might be better to have separate pop-ups for making and taking offers. Would be more clear, but it is a bit more repetitive. Up to you guys.

Making

```
(!) Important

With the recent rise in BTC price, beware that selling 0.01 BTC or less incurs higher risk than before.

It is highly recommended to either:
- make offers >0.01 BTC, so you only deal with signed/trusted buyers
- keep any offers to sell <0.01 BTC to around ~100 USD in value, as this value has (historically) discouraged scammers 

Bisq developers are working on better ways to secure the payment account model for such smaller trades. Join the discussion here: [HYPERLINK:https://github.com/bisq-network/bisq/discussions/5339]. 
```

Taking

```
(!) Important

With the recent rise in BTC price, beware that selling 0.01 BTC or less incurs higher risk than before.

It is highly recommended to either:
- take offers from signed buyers only
- keep trades with unsigned/untrusted buyers to around ~100 USD in value, as this value has (historically) discouraged scammers 

Bisq developers are working on better ways to secure the payment account model for such smaller trades. Join the discussion here: [HYPERLINK:https://github.com/bisq-network/bisq/discussions/5339].
```

**Comment by ghost** [comment]
Screenshot: Taking a buy offer of (any amount) of an unsigned account:

![image](https://user-images.githubusercontent.com/47253594/112018236-6375fa80-8afc-11eb-801c-4362d42495bd.png)

**Comment by m52go** [comment]
Thanks for posting that. I missed that the pop-up will be shown for all amounts

**Comment by ghost** [comment]
Popup for making a sell offer with an account type that features chargeback risk (e.g. Zelle) :
Shown after validating the offer amounts, when minAmount <= 0.01.

![image](https://user-images.githubusercontent.com/47253594/112029912-b73a1100-8b07-11eb-8903-4377bad8aec1.png)

**Comment by m52go** [comment]
Both look good to me. 

Great that you're validating offer amount for sellers...the fewer pop-ups a user needs to see, the better :+1:

**Comment by ghost** [comment]
@m52go what if the peer account was signed today, i.e. is not "limits lifted"?  Is that considered risky status?

**Comment by m52go** [comment]
I think peers in that state should be considered risky...integrity hasn't been proven to the intended standard until 30 days have passed and limits are lifted.
