### ISSUE TITLE
Display last trade price if available.

### ISSUE THREAD

**Issue by dan-da** [bisq-network/bisq#536]
Question:  do all p2p nodes see all executed trades?    If so, then couldn't the app display the real "Last" price for a given orderbook, once it sees at least one trade occur?

The app could still display the price from a 3rd party service if user's node hasn't yet seen a trade.  and/or maybe could get "Last" from a peer?

If price of executed trades is private between the 2 parties and not broadcast, then I guess this is impossible...?

Having a real "Last" price in bitsquare seems good in general but right now there is a very good use case where bitsquare is pretty much the only exchange listing ETHC (ethereum classic) and so is basically setting the reference price... but shows "N/A" for the price!

**Comment by ManfredKarrer** [comment]
No, actually nobody sees an executed trade, only the 2 traders. The other nodes only see that an offer got removed but it might be also that the offerer went offline or canceled the offer. The arbitrator sees that he received a take offer fee which indicates that a trade started. So with that we can derived the info that a trade got executed. But he does not see who and which offer. 
You need to get the blockchain data and match it with the offerbook data to get the price info when a trade has been executed. One dev is working on a subproject to get those market data (https://forum.bitsquare.io/t/bitsquare-proxy).

To use Bitsquare's prices will be considered once there is sufficient liquidity. But as we use market price for %based prices it is a bit tricky to be sure that it cannot get manipulated.
But to display that info will definitely happen as soon we have statistics.

**Comment by ManfredKarrer** [comment]
In upcoming release there are statistics for price and trade volume.
