### ISSUE TITLE
Portfolio/History page is not showing all of the columns

### ISSUE THREAD

**Issue by SamJamGin** [bisq-network/bisq#5360]
I worked with tech support in the Keybase app and he said I should submit a support ticket after we tried working through an issue. 

### Description_

All of the columns are not being displayed on my page in the Bisq app as compared with the tech's. We are both running the same version 1.5.9. He sees the columns:

Trade Id
Date/Time
Market
Price
Deviation
Amount in BTC
Amount
Transaction fee
Trade fee
Buyer Deposit
Seller Deposit
Offer type
Status

I have the columns in the attached picture. I also cannot see anything to the right of this column after the user picture. I see what looks like updates or new chat messages, but I can't open it and I can't see anything to the right no matter how much I change the window size, try to scroll to the right, etc.

![image](https://user-images.githubusercontent.com/81429183/112654519-ddbcbc80-8e25-11eb-82f6-f4d4f95d0000.png)

#### Version

1.5.9

### Actual behaviour

I should have the same columns as the tech does.

### Screenshots

I am missing several columns under the Portfolio/History page. As a result, I cannot see Trade fee, Buyer Deposit or Seller Deposit.

![image](https://user-images.githubusercontent.com/81429183/112654122-74d54480-8e25-11eb-89d7-e076511cce74.png)

#### Device or machine

Dell Windows OS

**Comment by ghost** [comment]
To see the new fields you can install v1.6.0 or newer.  Perhaps the tech was using a pre-release that did not have the version number updated.
You can find the latest release here:  https://github.com/bisq-network/bisq/releases

**Comment by cd2357** [comment]
Closing, as the issue seems addressed.

@SamJamGin let us know if you still have the issue even with v1.6.0.
