### ISSUE TITLE
GUI not functioning.

### ISSUE THREAD

**Issue by RandomAccountt** [bisq-network/bisq#5362]
### Description

When opening Bisq, the GUI does not start.

#### Version

1.5.9

### Steps to reproduce

1. Open Bisq.

### Expected behaviour

GUI opens.

### Actual behaviour

GUI does not open, but the application exists in the background. Uses resources as normal. The app appears open in the taskbar, but clicking on it does not bring up the GUI.

### Screenshots
This appears in the windows key+tab menu.
![win-tab](https://user-images.githubusercontent.com/30158779/112684808-7de90480-8e6b-11eb-91c8-d51fac366452.png)
#### Device or machine

ASUS TUF FX505DT
Running latest version of Windows 10.

#### Additional info

Issue persists after reinstall. Additionally, I would like to know if there is a way to export my wallet to electrum or any other wallet. I do not have the wallet seed, but I have my backup files. Thanks

**Comment by wallclockbuilder** [comment]
Fastest way around this is to use a VM(e.g. Ubuntu on virtualbox).

**Comment by cd2357** [comment]
Is this the first time you run Bisq? Or did you run it before and it ran fine, but it started behaving like this after a Bisq upgrade / OS upgrade / etc ?

One thing you can try is to disable the use of Hardware Graphics Acceleration in Bisq by doing the following:

1. Using notepad open the file `Bisq.cfg` located in `C:\Users\<your username>\AppData\Local\Bisq\app`
2. Under the section `[JVMOptions]` add the following `-Dprism.order=sw` such that it now looks like this:
```
[JVMOptions]
-Dprism.order=sw
```
3. Close/save the file and start Bisq again

---

Reference threads:
* https://www.reddit.com/r/javahelp/comments/84w6i6/problem_displaying_anything_with_javafx_only/
* https://stackoverflow.com/questions/18754803/how-to-disable-or-bypass-hardware-graphics-accelerationprism-in-javafx

**Comment by cd2357** [comment]
Might be related to #5366 because there

> "the Bisq window usually turns into a blank white rectangle"

**Comment by RandomAccountt** [comment]
> Is this the first time you run Bisq? Or did you run it before and it ran fine, but it started behaving like this after a Bisq upgrade / OS upgrade / etc ?

Nope, it happened after a while using the app. Definitely not from a bisq upgrade, perhaps from a Windows update but I cannot remember.

Although the issue was not fixed after a complete reinstall, I was afterwards advised by Mawueli on the Keybase to reinstall C++ redistributable packages and check for corrupted files on my windows device. After doing these steps, AND reinstalling, I could no longer replicate the issue, and Bisq works as intended now.

**Comment by cd2357** [comment]
Alright @RandomAccountt thanks for the update. Then I'll close this, since your problem is fixed.
