### ISSUE TITLE
The 1.6.0 mediation style is confusing

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/bisq#5367]
Hello. I would like to point out that the new mediation style introduced in 1.6.0 is very confusing. Now the chat with the mediator is opened in a separate window, just like chat with the peer. They look the same, so it is very easy to send message to the peer instead of the mediator and the other way around, without even noticing it which may result in unnecessary delays. The previous style, where chat with the mediator had no separate window was immune to this confusion. Thank you.

**Comment by wallclockbuilder** [comment]
Its not working as intended. Perhaps you should file a bug report. Use the format.


### Description

-- brief description of the bug --

#### Version



### Steps to reproduce



### Expected behaviour



### Actual behaviour



`### Screenshots





#### Additional info

`

**Comment by ripcurlx** [comment]
@jmacxx Maybe we could add a visual border indication that it is clear if it is a dispute window or a trader chat window.

**Comment by Conza88** [comment]
Good solution
