### ISSUE TITLE
Java Heap Error

### ISSUE THREAD

**Issue by paulmercier-bisq** [bisq-network/bisq#5368]
### Description

Bisq seems to crash

#### Version

Version 1.6.0.

### Steps to reproduce

Seems to happen after leaving Bisq open with computer hibernating, unsure tho.

### Expected behaviour

Bisq should work smoothly.

### Actual behaviour

Bisq crashes.

### Screenshots

![heap](https://user-images.githubusercontent.com/46323936/112745967-4b92f080-8fac-11eb-90f1-c8a7cf1f2354.png)

#### Device or machine
Ubuntu 20.04.2 LTS, Gnome 3.36.8, X11.

#### Additional info

Last 1,000 lines of bisq.log : 
[1000.log](https://github.com/bisq-network/bisq/files/6217005/1000.log)

**Comment by wallclockbuilder** [comment]
Is it permanently broken? 
Is your hard drive SSD or HDD?
Have you tried a system restart? 
Share the last page of your log file if it breaks again after doing a post-restart run.

**Comment by cd2357** [comment]
> Seems to happen after leaving Bisq open with computer hibernating, unsure tho.

Generally its not a good idea to hibernate the computer while Bisq is running. For it to work properly, it needs to maintain several tor connections open and constantly listen for network and trade updates, among other things. Hibernation/sleep interrupts and prevents this.

If you do plan to hibernate/sleep the PC, best to first close Bisq. If you have open trades or other reasons why you'd like to keep Bisq running, then ideally you'll disable hibernation in the OS settings.

If it still happens even when not hibernating/sleeping, let us know, I'll reopen the issue.
