### ISSUE TITLE
“Bisq” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by klement** [bisq-network/bisq#5369]
### Description

When opening bisq I get error that “Bisq” can’t be opened because Apple cannot check it for malicious software.

#### Version
Bisq 1.5.9

### Steps to reproduce

download
start

### Expected behaviour

app starts

### Actual behaviour

app doesn't start

#### Device or machine

macbook air m1

**Comment by ripcurlx** [comment]
Will be fixed with #4242

**Comment by cd2357** [comment]
Until it is fixed, see the section "Known issues / MacOS Catalina" in the release notes for a workaround: https://github.com/bisq-network/bisq/releases/tag/v1.5.9

> _Bisq can't be opened because Apple cannot check it for malicious software_
>
> This happens the first time Bisq is run on macOS Catalina. It is because a new security feature in Catalina has newer requirements of how apps are packaged. We are working on ways to address this (see #3402 and #4196 for details).
>
> Workaround: Right click on the installed Bisq app > Click Open (warning popup shown again, but with new button available) > Click Open

**Comment by cd2357** [comment]
FYI: Works as expected with the latest version v1.6.4.
