### ISSUE TITLE
price discovery is difficult

### ISSUE THREAD

**Issue by dskloet** [bisq-network/bisq#537]
Most trading pairs do their price discovery on other exchanges, but ETHC isn't traded anywhere else and price discovery seems to be quite difficult.
It would help if we could see past trades, or if that's not possible at least see past orders.
What do you think?

**Comment by ManfredKarrer** [comment]
I am working on it...

**Comment by dskloet** [comment]
Great!

**Comment by ManfredKarrer** [comment]
In upcoming release price and volume statistics are included.
