### ISSUE TITLE
Delete SPV File And Resync Button doesnt work properly

### ISSUE THREAD

**Issue by mlewk** [bisq-network/bisq#5379]
After pressing the button in Setting -> Network Info every time I log into bisq it says that I deleted the SPV file and it needs to resync and then it says I need to shutdown, so I shutdown but upon restart it says the same thing that it needs to download the SPV file again and it keeps doing this loop. I have resynced and restarted bisq 4 or 5 times already as well as restarted my computer but nothing has changed. I have open trades and Id like to know how to fix this?

**Comment by MwithM** [comment]
Hi, yours seems like another case of this issue: https://github.com/bisq-network/bisq/issues/5335

**Comment by mlewk** [comment]
So How exactly do I fix this issue? I cannot log into Bisq because it is stuck in the SPV chain downloading loop.

**Comment by cd2357** [comment]
The fix should be in v1.6.2, have you tried upgrading to that version?

**Comment by cd2357** [comment]
Fixed in v1.6.2
