### ISSUE TITLE
Reimbursement request: Trade pbbycjn

### ISSUE THREAD

**Issue by jimmyfj** [bisq-network/bisq#5382]
My trade failed after deleting SPV and resync after receiving no onchain confirmations for 7 hrs. I had the SPV resync issue where Bisq continued to resync. I fixed this by changing the name of PreferencesPayload file. 

My deposit funds are still locked in my wallet and I was not able to open mediation due to the issue being a deposit null set. 

I am requesting the release of my locked funds and whatever reimbursement of fees can be provided. 

<img width="579" alt="Screen Shot 2021-03-30 at 11 38 42 PM" src="https://user-images.githubusercontent.com/81696060/113158198-319e1b80-9201-11eb-9e20-a040dcac94f6.png">

**Comment by cd2357** [comment]
This is the wrong place to open a reimbursement request.

Here is the correct one, please open your request here: https://github.com/bisq-network/support/issues
