### ISSUE TITLE
Bug when clicking on an offer

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#539]
Hi,

I clicked on a sell offer and appear this message:

![captura de tela de 2016-07-23 15-20-54](https://cloud.githubusercontent.com/assets/1178856/17079547/1c070ca8-50ea-11e6-8e79-85a07b2082aa.png)

I clicked on close button and tried to open the offer again. I see this message:

![captura de tela de 2016-07-23 15-23-14](https://cloud.githubusercontent.com/assets/1178856/17079551/3f727baa-50ea-11e6-8415-7977c442dd37.png)

Obs. Bitsquare.log uploaded here.
[bitsquare.log.zip](https://github.com/bitsquare/bitsquare/files/379919/bitsquare.log.zip)

**Comment by bitcoinuser** [comment]
I think it's because someone created a profile (transfer with same bank), but didn't specify the bank name. (The field is blank)

**Comment by bitcoinuser** [comment]
The bank name field should NOT be optional.

**Comment by bitcoinuser** [comment]
Look the offer info window. As you can see, the bank name field has no information.

![captura de tela de 2016-07-23 15-46-00](https://cloud.githubusercontent.com/assets/1178856/17079635/b0607838-50ec-11e6-845e-4800ea7bdb42.png)

**Comment by bitcoinuser** [comment]
I tried to create an account with same bank, and I see that bank name field is not optional. So, how the user created this account?

![captura de tela de 2016-07-23 15-54-40](https://cloud.githubusercontent.com/assets/1178856/17079670/ef793f22-50ed-11e6-904b-53d02a72b3ce.png)

**Comment by ManfredKarrer** [comment]
Thanks for reporting! I got an email from prob. that user. Don't know how he did it. Requested more info from him.

**Comment by bitcoinuser** [comment]
@ManfredKarrer Do you think is possible to list all banks from Brazil? So the user could select the bank name from a pre defined list.
Do you think is a good idea? I can try to search an oficial list of banks of Brazil.

**Comment by ManfredKarrer** [comment]
I started once to list the bank names, but it turned out to be too much work, so I left it for later (or another dev who can take that). If I add that I want to do it globally, and then it is considerabel effort... But will setup a bounty soon for that...

**Comment by bitcoinuser** [comment]
I changed my mind. Keep the list of banks updated is a hard work. I think should work like today.

**Comment by ManfredKarrer** [comment]
i used lists from other platforms, so i hope they are mroe or less ok. but yes would require an extra field for manual edit to be flexible... a suggestion component like in google search bar would be good.

**Comment by ManfredKarrer** [comment]
The bug with missing bank name is fixed for the next version.
