### ISSUE TITLE
Bisq UI hangs if you remotely connect to Windows

### ISSUE THREAD

**Issue by msadikyildiz** [bisq-network/bisq#5390]
### Description

Bisq client hangs if you remotely connect to Windows 10.

#### Version

Bisq 1.6.2 

### Steps to reproduce

If you restart the client it fixes. Problem reproduced every time you disconnect/connect to Windows through RDP.

### Expected behaviour

UI work as expected.

### Actual behaviour

UI hangs.

#### Device or machine

Windows 10 Pro
Version 20H2 Build 19042

**Comment by ripcurlx** [comment]
@msadikyildiz Do you see anything suspicious in the log file when this client freeze occurs?

**Comment by msadikyildiz** [comment]
Nothing on the log files, no errors produced in GUI either. Even open trades work as intended in the background, but the UI goes permanently unresponsive until I have to restart it to be able to click anything.

**Comment by ripcurlx** [comment]
> Nothing on the log files, no errors produced in GUI either. Even open trades work as intended in the background, but the UI goes permanently unresponsive until I have to restart it to be able to click anything.

I think best would be to wait for #4242 getting merged and try it again. It will compile the client with Java 11 and has Java 15 as a bundled runtime. This might fix some issues with newer OS versions (I hope so).

**Comment by cd2357** [comment]
@msadikyildiz can you please update to the latest version (v1.6.4), try the solution described here https://bisq.community/t/resolved-win10-rdp-bisq-gui-is-stuck/9871/4 and tell us if it works for you?

**Comment by msadikyildiz** [comment]
yes that solved the issue with the v1.6.4!

**Comment by cd2357** [comment]
Great to hear that.
