### ISSUE TITLE
Change 'Optional additional information' field text on 'Cash by Mail' payment method to encourage traders to state the country they are located and the region / countries they are willing to accept offers from

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#5394]
### Description

'Cash by Mail' payment method allows traders to  place and take offers from any location.

Some traders may only wish to trade with users from a particular region or country.

This has lead to at least a couple of 'Cash by Mail' trades entering mediation and being cancelled. 

To avoid this I propose changing the 'Optional additional information' field text on 'Cash by Mail' payment method to encourage traders to state the country they are located and the region / countries they are willing to accept offers from

#### Version

1.6.2

### Steps to reproduce

Go to > Accounts > National Currency accounts > Add new account > cash by mail

No prompt for country / region to be considered

### Expected behaviour

Maker places offer to sell BTC via cash by mail and includes the countries they are located and the region they are willing to accept trades from.

Maker places offer to buy BTC via cash by mail and includes the countries they are located and the region they are willing to accept trades from.

### Actual behaviour

No prompt for countries / regions.

### Screenshots

![cash by mail](https://user-images.githubusercontent.com/66367547/113592414-02d2db80-962d-11eb-880c-80e47246e976.png)
Current screenshot

#### Text to change in (Optional additional information)

Change current text: 
`Define any special terms, conditions, or details, you would like to be displayed with your offers for this payment account (users will see this info before accepting offers).`

to

```
Please state on your offers:

Country you are located (eg France):
Countries / regions you would accept trades from (eg France, EU, or any European country):
Any special terms/conditions:
Any other details:
```

**Comment by ghost** [comment]
:+1:   Thanks, I will work on this.

**Comment by ghost** [comment]
@pazza83 You chose an implementation that does not enforce the country restriction.  I like it, not adding complexity etc.  Probably some traders don't bother to read the offer details though.  Do you think it is worth a popup at take offer stage to confirm that the trader has read the restrictions and accepts them?  (a specific popup case for CashByMail only).

The alternative would be to enforce the country restriction by specifying country or region in a new field of the account and having that match in maker & taker.  Harder to implement, but maybe more consistent?

**Comment by pazza83** [comment]
Hi @jmacxx 

Yes I thought it would be best to not enforce the country restriction.

I didn't want to enforce country restriction as:

- People could live in dependencies, autonomous Communities, or small nations like Monaco, Canary Islands, Isle of Mann and therefore have slightly different requirements. 
- People might have differing countries, regions, geographies they are willing to trade with.

The current text implies 
> (users will see this info before accepting offers).

I think a pop-up to confirm they have read this information would be great. Maybe include the information in the pop-up if this can be achieved?

**Comment by ghost** [comment]
The popup verification showing the maker's specified restrictions seems to be the most flexible solution in this case.

(Some CashByMail sellers are asking for the ability to exclude New York residents due to BitLicense, that's another example of hard to implement restrictions).

**Comment by ghost** [comment]
@pazza83 Trying this out with some existing open CashByMail offers and they have an awful lot of text in the `Optional Additional Information` field, it fills up the entire screen and even then only 75% is shown.  On a smaller laptop display it would show only half as much as what's in this screenshot.  Are there any other risks displaying user-entered data in this way?

Screenshot below:
![image](https://user-images.githubusercontent.com/47253594/113616070-41ab6600-961a-11eb-9f52-79a77d00aa2b.png)

**Comment by pazza83** [comment]
Hi @jmacxx 

That does look like a lot of text.

Not sure what you mean by: 

> Are there any other risks displaying user-entered data in this way?

**Comment by ghost** [comment]
Nevermind, we can display it in a readonly TextArea control which comes with a scrollbar.

**Comment by huey735** [comment]
My intuition is that enough traders won't read the disclaimer and will take offers that they don't intend to follow through. However more difficult it may be, I prefer that we had a `National Bank Transfer`-like model where the trader can choose their country in the creation of the account.

**Comment by ghost** [comment]
@huey735 The CashByMail terms will be shown with an "I CONFIRM" button they have to press before they can take the offer.  That should make it pretty clear.

![image](https://user-images.githubusercontent.com/47253594/113747218-c3f46280-96cc-11eb-9e0f-f75bbc07c97d.png)

**Comment by huey735** [comment]
Honestly the amount of popups in Bisq makes me close most of them without reading and any non-rigid rule is likely to not be followed.

**Comment by ghost** [comment]
Discussed with @pazza83 and @huey735 in support team meeting and concluded that for now the initial/simpler [solution proposed here](https://github.com/bisq-network/bisq/issues/5394#issuecomment-813528619)  is best, esepcially as CashByMail is a niche market.  If traders end up ignoring the popup we can revisit and implement a hard account restriction by country.
