### ISSUE TITLE
payment reason BLANK message alert when trading (some banks require to write a reason)

### ISSUE THREAD

**Issue by Tracachang** [bisq-network/bisq#5395]
Hello,

As a buyer, when a trade is accepted and deposit confirmed you receive an alert to pay precising that transfer reason must be BLANK. This information is "incomplete" and I think it would be good to add from bisq FAQ:

> **If a reason is required, it should be something trivial like a "-" or "payment"**. If you want to use something else, please agree on an alternative with your peer using trader chat.

I think in case of a reason is required should be the "-" the standard since it does not give any information, even if "payment" it is trivial too, it would not be something that people would use in most of EU countries where English is not spoken.

**Comment by pazza83** [comment]
Hi @Tracachang thanks for the issue.

I ran into this issue recently when taking on offer to buy BTC on Bisq using a bank that would not accept a blank reason for payment. It pre-populated instead with my name.

I think entering you name (same as bank account) is an acceptable solution to this, as is entering a dash.

If the trader enters something not agreed there would be a penalty, see [Trade Penalties Table  ](https://bisq.wiki/Table_of_penalties)

**Comment by Tracachang** [comment]
Thanks @pazza83, then it is clear, in case of a reason is required must be dash or name. Do I close this issue? Or I keep it open until it is fixed?

**Comment by pazza83** [comment]
Hi @Tracachang leave it open and I will add it to the wiki before commenting back here and then it can be closed.

**Comment by pazza83** [comment]
Hi @Tracachang I have included the information here: https://bisq.wiki/Trading_rules#Leave_the_.22reason_for_payment.22_field_empty

Thanks for opening this issue it can now be closed.
