### ISSUE TITLE
Cannot install .deb on Qubes / Debian VM

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#5408]
### Description

```
$ sudo dpkg -i Bisq-64bit-1.6.2.deb 
Selecting previously unselected package bisq.
(Reading database ... 134470 files and directories currently installed.)
Preparing to unpack Bisq-64bit-1.6.2.deb ...
Unpacking bisq (1.6.2) ...
Setting up bisq (1.6.2) ...
Adding shortcut to the menu
xdg-desktop-menu: No writable system menu directory found.
dpkg: error processing package bisq (--install):
 installed bisq package post-installation script subprocess returned error exit status 3
Errors were encountered while processing:
 bisq
```

#### Version

1.6.2

### Steps to reproduce

Download package, install with `dpkg` or `apt`.

#### Device or machine

Qubes 4 operating system, in a Debian 10 virtual machine.

**Comment by ripcurlx** [comment]
We are changing the packaging pipeline in #4242 which will be merged soon, but I'm not sure if it will fix this issue.

**Comment by ghost** [comment]
Awesome, thanks @ripcurlx, please let me know when I can test a new package and give feedback.

**Comment by ripcurlx** [comment]
@MaxHillebrand It is not merged into master, but this is the last testing step before it is merged.
Could you give the deb bundle a shot you can find here: https://www.dropbox.com/sh/bos203ga9bq0akp/AAB6j5DPAINCPbCP9vyRB3n-a?dl=0

This is based on the v1.6.2 release compiled with Java 10, latest JavaFX library and bundled with a current Java 15 JRE. So in the best (normal) case it should behave as before, but faster or at least more reliable. 

Please make a backup of your data directory before testing the linux binary. I've used it on macOS for quite some time, but I only did some smoke tests on Linux so far.

**Comment by ripcurlx** [comment]
You'll find the required signature in the directory as well.

**Comment by ghost** [comment]
tested Bisq-64bit-1.6.2.deb af9e48facc0abea93bb35c09978c445e165b553d1716f8e8a829700079374ee3

getting the same error
```
$ sudo dpkg -i QubesIncoming/disp8789/Bisq-64bit-1.6.2.deb 
Selecting previously unselected package bisq.
(Reading database ... 134470 files and directories currently installed.)
Preparing to unpack .../disp8789/Bisq-64bit-1.6.2.deb ...
Unpacking bisq (1.6.2-1) ...
Setting up bisq (1.6.2-1) ...
xdg-desktop-menu: No writable system menu directory found.
dpkg: error processing package bisq (--install):
 installed bisq package post-installation script subprocess returned error exit status 3
Errors were encountered while processing:
 bisq
```

I'm on a disposable debian 10 VM in Qubes 4, I can reproduce in multiple VMs with different templates. 

Might this be some Qubes specific issue?

**Comment by ripcurlx** [comment]
hmm - I'm not a Linux expert, but did you give it a shot manually creating the desktop directories (https://askubuntu.com/questions/405800/installation-problem-xdg-desktop-menu-no-writable-system-menu-directory-found)?

```
sudo mkdir /usr/share/desktop-directories/
```

**Comment by ripcurlx** [comment]
And running the installer afterwards

**Comment by ghost** [comment]
```
~$ sudo mkdir /usr/share/desktop-directories/
~$ sudo dpkg -i QubesIncoming/disp8167/Bisq-64bit-1.6.2.deb 
Selecting previously unselected package bisq.
(Reading database ... 134331 files and directories currently installed.)
Preparing to unpack .../disp8167/Bisq-64bit-1.6.2.deb ...
Unpacking bisq (1.6.2-1) ...
Setting up bisq (1.6.2-1) ...
```

It seems to have succeeded. 

But what's the command to start bisq from cli?

**Comment by ripcurlx** [comment]
> ```
> ~$ sudo mkdir /usr/share/desktop-directories/
> ~$ sudo dpkg -i QubesIncoming/disp8167/Bisq-64bit-1.6.2.deb 
> Selecting previously unselected package bisq.
> (Reading database ... 134331 files and directories currently installed.)
> Preparing to unpack .../disp8167/Bisq-64bit-1.6.2.deb ...
> Unpacking bisq (1.6.2-1) ...
> Setting up bisq (1.6.2-1) ...
> ```
> 
> It seems to have succeeded.
> 
> But what's the command to start bisq from cli?

I think `/opt/Bisq/Bisq` should work.

**Comment by ghost** [comment]
`/opt/bisq/bin/Bisq` did the magic, it works well now, thanks for the help @ripcurlx!

Even recognizes it's running in Qubes.
![screenshot_20210420_171753](https://user-images.githubusercontent.com/30683012/115421688-7283c180-a1fc-11eb-9196-3e3c00b16a66.png)

And https://bisq.wiki/Running_Bisq_on_Qubes actually has a reference to create the desktop-directories.
![screenshot_20210420_171928](https://user-images.githubusercontent.com/30683012/115421868-a4952380-a1fc-11eb-810a-bb2df16fef8d.png)

:clap: READ :clap: THE :clap: FUCKING :clap: DOCS :clap: :smile:
