### ISSUE TITLE
DO NOT confirm payment received when enter key is pressed

### ISSUE THREAD

**Issue by Gooberpatrol66** [bisq-network/bisq#5415]
### Description

I just lost $400 because I was multitasking and didn't click out of the Bisq window before hitting the enter key, and it released my bitcoin, and the seller had not sent funds yet.

#### Version

1.6.1

### Steps to reproduce

1. open trade
2. get to "confirm payment received"
3. press enter

### Expected behaviour

You should have to manually click on the confirm button.

### Actual behaviour

Hitting the enter key can unexpectedly close a trade.

#### Device or machine

Linux

**Comment by pazza83** [comment]
Hi @Gooberpatrol66 thanks for creating this issue. I have also made this mistake once before when trying to do multiple things at once!

I think to release the BTC you need to press two confirmations so it is not too easy a mistake to make.

BTC Sellers only have the option to release funds once the buyer has confirmed they have sent the fiat / alt coins. Hopefully it is the case that the buyer has sent the payment and they just have not arrived yet.

If the buyer has not sent the funds then I think there is not much you can do.

**Comment by maxim-belkin** [comment]
I haven't made this particular mistake in the Bisq app... but I did make a similar mistake in a different setting and I have to say that having multiple prompts that all default to the same answer (all "Yes" or all "No") does *not* help -- you just rush through them. So, I think the best solution is to have multiple prompts (2) that either default to different answers or make the second one ask you to type something like "CONFIRM".
