### ISSUE TITLE
Update Bisq Github teams to include active members and remove inactive members 

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#5422]
### Description

The GitHub teams members are not accurate: https://github.com/orgs/bisq-network/teams

I regularly make use of the feature to include @bisq-network/mediators @bisq-network/bisq-devs and @bisq-network/arbitrators in relevant GitHub issues.

The above are all out-of-date and some include no members.

I have not realized this before. Might explain why I have had trouble having @bisq-network/arbitrators comment on issues when there are no members in the team!! cc @refund-agent2

Not sure if this falls under the role of @bisq-network/team-leads or @bisq-github-admin-3 / @ripcurlx 

#### Version

N/A

### Steps to reproduce

View the 62! teams on Bisq: https://github.com/orgs/bisq-network/teams 

I am unsure how many are active / up-to-date

### Expected behaviour

Teams on Bisq should include all current team members.

Teams on Bisq should not include any members that are not current team members.

I am not sure if inactive teams should be retired so as to not cause confusion.

Maybe 'people' could also be reviewed: https://github.com/orgs/bisq-network/people

### Actual behaviour

information is out-of-date

**Comment by cbeams** [comment]
> Not sure if this falls under the role of @bisq-network/team-leads or @bisq-github-admin-3 / @ripcurlx

This would fall under the @bisq-network/roles-maintainers, for which I am the role owner.

The team structure is probably overkill at this point. The reasons they exist are:

1. To reflect and codify role assignments defined in the issues in the bisq-network/roles repository
2. To allow for @mentioning and getting the attention of role owners without having to look up their specific usernames
3. To assign role owners appropriate access to repositories
4. To be used for focused team communication via GitHub Team Discussions

Reason (1) is not strictly necessary. We record role assignments in the role issues already, so having it reflected in GH team structures is actually duplication.

Reason (2) is handy, but it doesn't get used a whole lot.

Reason (3) is useful too, but only for a subset of teams/roles, certainly not all 62.

Reason (4) is obsolete. Using GH Team Discussions never really worked out, despite trying pretty hard to make it happen.

My suggested course of action would be to go through the teams with the intention of removing many or even most of them that do not directly benefit from (2) and especially (3). Leave the ones in place that are practical, and make sure they reflect the current assignments.

Further feedback welcome. Thanks for raising the issue @pazza83.

**Comment by pazza83** [comment]
Closing as @cbeams has taken ownership of this issue as mentioned in [Roles Maintainer - Cycle 24 report](https://github.com/bisq-network/roles/issues/28#issuecomment-832500339)

**Comment by cbeams** [comment]
@pazza83, as mentioned at https://github.com/bisq-network/roles/issues/28#issuecomment-884026874, I've updated the mediators, arbitrators and bisq-devs teams to make sure they're accurate.
