### ISSUE TITLE
Show bank name on National bank transfer method

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#543]
Hi,

1- On Brazil, people usually have more than one bank account. I have three bank accounts on different banks.
2- Transfers from one bank to other different bank, from monday to friday, usually take 30 min to one hour. The transfers for different banks only works until 17:00pm and doesn't work on weekends or holidays.
3-  Transfers for a same bank, works all days (24 hours a day), including weekends and holidays.

Sometimes I see an offer (National Bank Transfer) on Bitsquare, on weekends, holidays or after 17:00pm. I'm sure the person or me, would like to receive the fiat money and release the bitcoins as soon as possible.
So I think the offers of National Bank transfer, should show the bank name. Looking this info, I could choose the bank to transfer the money. So the transfer will work even on weekends, holidays or later night. Understand?

Thanks.

**Comment by MarcSte** [comment]
Showing the bank is a privacy leak. You can use 'Transfer with same bank' that you can choose in the account tab.

Though, the offer will not be shown when 'National bank transfer' is selected from the drop-down menu in 'Buy BTC' / 'Sell BTC' tabs.

A workaround would be to have multiple offers with 'National bank transfer' and 'Transfer with same bank'.

**Comment by bitcoinuser** [comment]
Sorry but I can't imagine why show name bank is a privacy leak.
Could you elaborate?

**Comment by MarcSte** [comment]
You're right. It's not critical.

The bank name can be tied to an onion adress, that is all. It is what happens when you trade with specific banks, the bank name is displayed.

**Comment by bitcoinuser** [comment]
Right.

Hope this be implemented.

Thanks

**Comment by ManfredKarrer** [comment]
You can use transfer with specific banks, where u can define a list of accepted banks.

**Comment by ManfredKarrer** [comment]
But I understand, to dispaly that info would make it more flexible... Will look into it.

**Comment by ManfredKarrer** [comment]
Added it for the next release. So in the offer details popup u will see the Bank nr (e.g. BIC, SWIFT). the bank name is not available in the offer object so that cannot be used (cannot change that without breaking backward compatibility).

**Comment by bitcoinuser** [comment]
In my use case, only helps if show bank name. Maybe on future releases?

**Comment by ManfredKarrer** [comment]
bank name and BIC/SWIFT correspond. maybe u find a lookup page

**Comment by bitcoinuser** [comment]
Look the window of bitsquare when adding a national bank from Brazil. I don't see BIC/SWIFT field. But I see Bank name. 

![captura de tela de 2016-07-26 14-05-03](https://cloud.githubusercontent.com/assets/1178856/17147684/3418aba6-533a-11e6-9af4-3b81ed6df780.png)

**Comment by ManfredKarrer** [comment]
Ah ok. Fixed it will display bank name if bank ID is not defined.
