### ISSUE TITLE
Misaligned 'Enter wallet seed words' text-box label (v1.6.3 release test)

### ISSUE THREAD

**Issue by ghubstan** [bisq-network/bisq#5435]
### Description

The `Enter password to unlock` window has a slightly hidden text box label.  
Probably needs style tweak after `jfoenix` upgrade.

#### Version

v1.6.3

### Steps to reproduce

- Start UI
- Set your wallet password
- Shutdown UI
- Forget your wallet password
- Start UI
- Try to unlock wallet with seed

### Expected behaviour

Left hand side of text box label should show entire letter 'E'.

### Actual behaviour

'E' is partially hidden.

### Screenshots

![enter-seed](https://user-images.githubusercontent.com/36207203/115769868-6d507f00-a382-11eb-8f61-1607494cb2a0.png)

#### Device or machine

Ubuntu 20

#### Additional info

Mentioned in testpad v1.6.3 test case:  https://bisq.ontestpad.com/script/359#15/2/

**Comment by ghost** [comment]
Same for all TextArea fields.  Prompt text is clipped, presumably by a border on the control.

![image](https://user-images.githubusercontent.com/47253594/115776764-1cd52380-a37a-11eb-80a6-5313ffca48c4.png)

**Comment by BtcContributor** [comment]
This happens on Windows 10 as well.

**Comment by ripcurlx** [comment]
Good catch! Only fixed it for the TextField component. Will push a fix for TextArea in a minute.
