### ISSUE TITLE
After downloading and installing the Mac version, starting it fails with "Bisq can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information"

### ISSUE THREAD

**Issue by WarrenMg5** [bisq-network/bisq#5445]
After downloading and installing the Mac version, starting it fails with "Bisq can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information"

Version : 11.2.3 (20D91)

Steps to reproduce
Download / verify Bisq package for Mac  11.2.3 (20D91)
Open dmg
In newly opened window: copy Bisq application to Applications folder
Try to open Bisq application (from Applications folder)
Expected behaviour
On the last step above, Bisq application should open.

Actual behaviour
Opening Bisq fails with OSX error mentioned above.

![176255385_177527224124452_1739479668787685677_n](https://user-images.githubusercontent.com/83341483/116383334-d7799000-a86a-11eb-850f-65052f5daa2d.jpg)

**Comment by ripcurlx** [comment]
This will be fixed with the upcoming release v1.6.3 which might be pre-released tomorrow or Friday and publicly released early next week. This error is because of the missing notarization of the binary.

**Comment by cd2357** [comment]
This is fixed in the most recent release. Please try it out and let us know if it's still an issue for you.
