### ISSUE TITLE
Display link to the dispute resolution process including table of trade penalties at relevant points in trade process

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#5456]
### Description

References: 

- [Table of trade penalties](https://bisq.wiki/Table_of_penalties)
- [Dispute resolution wiki](https://bisq.wiki/Dispute_resolution)

As part of the project to [improve support and mediation](https://github.com/bisq-network/projects/issues/48) a table of trade penalties was produced to make it clear to users what penalties could be expected if the trade protocol was not followed correctly.

This table will work best if all users are aware of it. To make users more aware the following was recommend on a support call on 28 April 2021.

- Include table of trade penalties in the [Dispute resolution wiki](https://bisq.wiki/Dispute_resolution).
- Reference table of trade penalties at relevant points in the trade process.

This issue covers where the dispute resolution wiki should be referenced.

#### Where to reference dispute resolution wiki in Bisq.

The dispute resolution wiki in Bisq should be referenced in the following places:

- System message: Your trading peer has opened mediation
- System message: You opened a request for support.
- System message: You opened a request for a dispute.
- System message: Your trading peer opened a request for a dispute
- Mediation result for Trade ID: XXXXXX
- Support 'Background information'
- On making offer confirmation screen
- On taking offer confirmation screen

#### Version

v1.6.2

### Steps to reproduce

Check out the above screens / system messages. @bisq-network/bisq-devs  I am unsure if there is anywhere they are all easily visible to a non dev?

### Expected behavior

Messages to reference the dispute resolution wiki. 

### Actual behavior

Currently it references the soon to be retired docs section eg: https://docs.bisq.network/trading-rules.html

**Comment by BtcContributor** [comment]
I can take care of this issue.

@m52go do you have proper wording to suggest?

@pazza83: I can not find old references to docs, do you have specific paths to look at?

Thanks!

**Comment by pazza83** [comment]
Hi @BtcContributor that is great.

The old documents linked to are: https://docs.bisq.network/trading-rules.html 

The best place for linking to the dispute process is: https://bisq.wiki/Dispute_resolution

@m52go do you know where the system messages / pop up alerts can be accessed to see what the current text is?

**Comment by BtcContributor** [comment]
Yes @pazza I can check from the source code all the texts, no problem.

**Comment by pazza83** [comment]
Any easy way for a non dev like me to check? 

Can I look at the source code on my local Bisq?

**Comment by BtcContributor** [comment]
@pazza83 check in this strings here: https://github.com/bisq-network/bisq/blob/master/core/src/main/resources/i18n/displayStrings.properties

**Comment by m52go** [comment]
@pazza83 FYI I just made a pull request with some of these changes a few days ago ;)

https://github.com/bisq-network/bisq/pull/5442

**Comment by BtcContributor** [comment]
That's why I did not find references to old docs @m52go  😂

@pazza83 check that and let me know if you need some other changes.

Thanks!

**Comment by pazza83** [comment]
Will do I will revert back once checked :)

**Comment by pazza83** [comment]
I have made some edits to the following wikis to include this info:

- https://bisq.wiki/Dispute_resolution#When_are_you_eligible_for_a_penalty.3F
- https://bisq.wiki/Trading_rules

Links and updated text have also been included with @m52go's pull request #5442

Therefore, closing this issue.
