### ISSUE TITLE
Unable to send funds from custom inputs (low res screens) (v1.6.3)

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#5457]
On limited resolution screens, it is impossible to select a custom input to send funds, because the table usually at the upper part of the screen is not visible.

I think this screen needs some rework to make it usable.  Too much vertical space is taken up by the bottom 6 fields.
Additionally, it is possible to get the fields drawn over each other when resizing (double click title bar).

---

As far as I understood, Bisq was designed to support a minimum screen resolution of 1020 x 620

https://github.com/bisq-network/bisq/blob/ec4ce6027d9f1eccb1d7aabd291644188a97bee4/desktop/src/main/java/bisq/desktop/util/Layout.java#L23-L24

---

**Screenshots:**
a laptop with resolution 1366 x 768 the table of custom inputs is not reachable at all, there is no scroll bar to access it.

![image](https://user-images.githubusercontent.com/47253594/116827871-0ccef800-ab61-11eb-9eec-0fb48cadb087.png)

**Comment by cd2357** [comment]
Looks similar to #5471 and #4036
