### ISSUE TITLE
1.6.3 Market price distance is always 0.00% when editing an offer

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/bisq#5460]
### Description
When you edit an existing offer, the "Above % from market price" section is shown as 0.00% while the real distance is different.

#### Version
1.6.3

### Steps to reproduce
1. close bisq
2. start bisq
3. wait until it's synced
4. go to Portfolio/My open offers
5. click on the pencil icon to edit an offer (this assumes that you have some offers published)
6. notice the percentage of the offer is correct, like "10.41%"
7. change the percentage to, say, "10.15%" and press Enter to save changes
8. notice the percentage on the offers list is shown correctly, like "10.15%"
8. click again on the pencil icon of the offer in Portfolio/My open offers
9. notice the percentage is show as "0.00%" in the Edit offer screen

### Expected behaviour
The market price distance from point 3 should be the same as in the Deviation section of the Portfolio/My open offers screen no matter whether you press Enter or click "Confirm: Edit offer" when editing the offer

### Actual behaviour

The distance from market price is shown as 0.00% when you earlier pressed Enter when editing an offer, it is correct when you clicked on the button "Confirm: Edit offer"

### Screenshots
![grafik](https://user-images.githubusercontent.com/63785272/116845303-c40d5280-abe5-11eb-8849-e9fe4c34ae47.png)

#### Device or machine
MS Windows 10

#### Additional info
This bug first occured in 1.6.3. After I have updated, sometimes the shown distance was correct, sometimes it wasn't, now it's exclusively 0.00%, though most of my offers were not taken.

**Comment by BtcContributor** [comment]
I would like to help but I can not reproduce this bug on Regtest.

**Comment by Akira45-0** [comment]
I can provide logs if necessary.

**Comment by BtcContributor** [comment]
Yes please.

**Comment by Akira45-0** [comment]
I don't want to post them in public,I can send you them on keybase

**Comment by Akira45-0** [comment]
What's your username on Keybase? I can't find you

**Comment by Akira45-0** [comment]
Updated the report, the bug occurs only when pressing Enter when editing an offer instead of clicking on the "Confirm: Edit offer" button.

**Comment by Akira45-0** [comment]
Bug occurs also in v1.6.4
