### ISSUE TITLE
1.6.3 Different deposit percentage size when cloning an offer

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/bisq#5470]
### Description

When you choose the option "Create new offer like this..." all data from the old offer is replicated except for the security deposit size which is newly calculated. It is easy to miss it.

#### Version

1.6.3

### Steps to reproduce

1. Go to Portfolio/Open trades
2. Right click on an offer and choose "Create new offer like this..."
3. "Duplicate offer" section will show up
3. Notice the "Set both traders' security deposit (%)" value is different than in the offer being cloned

### Expected behaviour

In point 3 the value should be like in the original offer which is being cloned.

### Actual behaviour

The security deposit size is newly calculated

### Screenshots

![grafik](https://user-images.githubusercontent.com/63785272/117123403-41c49000-ad97-11eb-9c68-55929f7a90b7.png)

#### Device or machine

Windows 10

**Comment by ripcurlx** [comment]
@jmacxx Could you please have a look at this? Thanks!

**Comment by Akira45-0** [comment]
Occurs also in v1.6.4
