### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by hotdocMD** [bisq-network/bisq#5472]
[Bisq error log 05062021.txt](https://github.com/bisq-network/bisq/files/6435731/Bisq.error.log.05062021.txt)

**Comment by cd2357** [comment]
Looks like this happened with Bisq v1.5.9.

Can you please upgrade to the latest v1.6.4 and check if it still happens?

**Comment by hotdocMD** [comment]
Ok. Thanks.
