### ISSUE TITLE
Option to select more than one national bank account

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#548]
For national bank payment, users could have an option to select more than one bank account. So if the user is unable to transfer with a specific bank account, he could choose the other, without break the contract.

Related to #527

**Comment by ManfredKarrer** [comment]
Yes the whole handlin gof bank account shoudl be improved, though need a find a dedicated dev to work on that.

**Comment by bitcoinuser** [comment]
Not same request, but related to: https://forum.bitsquare.io/t/cant-take-an-offer-of-same-bank/606

**Comment by haiqu** [comment]
The Paypal method - selecting a payment account before finalizing the transaction - would work here. It adds one more step but people are used to doing things that way anyhow. It's also the way the Buy option works.

I can see a privacy problem however, it exposes all your bank account info to a trace or a malicious user.
