### ISSUE TITLE
Trade failed but fees still charged

### ISSUE THREAD

**Issue by youss833** [bisq-network/bisq#5488]
Hi,
I tried creating a trade (for selling) in Bisq but when I clicked on the confirm button it said that it failed to create the trade.  I tried again and same thing happened. The problem is that I still got charged the trade and transaction fees both times, even though no trade was created. How do I get my funds back?

After restarting the app I managed to create a trade without a problem.

Thank you.

Version 1.6.4

**Comment by cd2357** [comment]
Please ask on keybase in the support channel and/or open a reimbursement request here: https://github.com/bisq-network/support/issues
