### ISSUE TITLE
cannot launch it, it also dissapears from the menu (ubuntu 16.04)

### ISSUE THREAD

**Issue by roberto68** [bisq-network/bisq#549]
I'm encountering this strange problem the program just periodicaly dissapears. I reinstall it like 2-3 times. 
But now I've some coins in there and do not wanna do it (btw what's the config folder so I can back it up, assuming some hidden folder in home ??) Or the new installation won't delete the config folder ? and what's the name of the binary (where is it ) cause when I do "find / -name bitsquare" nothing
Thanks Rob : )

**Comment by ManfredKarrer** [comment]
Hm.... the app data dir is at ~/.local/share/Bitsquare. Just backup the complete directory.
Inside Bitsquare under backup you can open it as well or do a backup from the app.
The application is under /opt/Bitsquare/Bitsquare.

**Comment by roberto68** [comment]
thanks Manfred

**Comment by ManfredKarrer** [comment]
Could u resolve the issue?

**Comment by roberto68** [comment]
yeah. it works fine I just have to launch it via terminal but that's fine.
