### ISSUE TITLE
Text overlapping

### ISSUE THREAD

**Issue by paulmercier-bisq** [bisq-network/bisq#5491]
### Description

Text overlapping under Account>Wallet Info>HD key chain paths

#### Version

v1.6.4

### Steps to reproduce

Run bisq as usual

### Expected behaviour

Text should display properly

### Actual behaviour
HD keychain paths overlaps with BSQ segwit wallet

### Screenshots

![Screenshot from 2021-05-12 20-17-22](https://user-images.githubusercontent.com/46323936/118024768-5be60b80-b35f-11eb-9afd-51cba67d4e8a.png)

#### Device or machine

Ubuntu 20.04 LTS

#### Additional info

N/A

**Comment by paulmercier-bisq** [comment]
Digged a bit, seems to happen at : 
`        addXpubKeys(bsqWalletService, "BSQ", ++gridRow, -Layout.FLOATING_LABEL_DISTANCE);`
of [https://github.com/bisq-network/bisq/blob/master/desktop/src/main/java/bisq/desktop/main/account/content/walletinfo/WalletInfoView.java](url), line 98.

**Comment by BtcContributor** [comment]
This should be easy to fix I guess if I can reproduce it.

I will take a look tomorrow, thanks for the hint!
