### ISSUE TITLE
There is an issue with a missing or invalid transaction

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#5494]
### Description

Myself and at least one other user have been experiencing error messages at the time offers are taken.

Related community post: https://bisq.community/t/there-is-an-issue-with-a-missing-or-invalid-transaction-help-needed/10746 

The error message shows as:

>There is an issue with a missing or invalid transaction.
>
>Please do NOT send the fiat or altcoin payment.
>
>Open a support ticket to get assistance from a Mediator.
>
>Error message: Deposit transaction is null or has unexpected input count.

Despite the message everything is ok, seems Bisq is checking the offer too early?

#### Version

Error message started to appear in 1.6.3 and also shows in 1.6.4

### Steps to reproduce

Offer is taken.

Bisq loads offer into 'Open Trades'

Trade that was taken initially shows as failed trade for a few seconds, then updates to a non-failed trade.

User is then shown a error 'pop up' as follows

![bisq issue github 2](https://user-images.githubusercontent.com/66367547/118381125-a70e5180-b5df-11eb-95a1-aa95a81ff23a.PNG)

### Expected behaviour

Error message is not shown for successful trades.

**Comment by cd2357** [comment]
@pazza83 can you add some log snippets from when this happens? Would help pin-point the issue.

**Comment by pazza83** [comment]
Thanks @cd2357 send you via Keybase

**Comment by pazza83** [comment]
Despite the error messages, everything is working as expected. @cd2357 informs me it is likely down to a Tor connectivity issue. Closing as resolved.
