### ISSUE TITLE
Change Western Union Payment Method to be Multi-Currency

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#5498]
### Description

Western Union supports multiple currencies.

Currently when adding Western Union as a payment method to Bisq it requires you to select only one currency.

Sending payments to people in multiple other currencies is what Western Union is for.

The Western Union payment method in Bisq should be updated to included ALL currencies, barring the ones listed below.

#### Version

1.6.4

### Steps to reproduce

Go to Accounts > National Currency Accounts

Select Add New Account, choose Western Union

You will be required to select only one currency.

### Expected behaviour

Go to Accounts > National Currency Accounts

Select Add New Account, choose Western Union

You will be required to select out of all currencies available.
 
### Screenshots

This is how it currently is:

![WU](https://user-images.githubusercontent.com/66367547/118415361-c5d51c80-b6a1-11eb-9f14-19c19e63e82d.png)

You should have the option to select multiple currencies from a list of all currencies available in Bisq. The only currencies NOT supported by Western Union are as follows:

- Iran (IRN)
- North Korea (PRK)
- Syria (SYR) 
- Sudan (SDN)
- Cuba (CUB)

**Comment by BtcContributor** [comment]
Hi @pazza83,
I can handle this issue.

**Comment by BtcContributor** [comment]
@pazza83 should we also entirely delete the "Select region" and "Select country" dropdown menu?

Not sure how they could help, I think it is a useless information if we enable all currencies for all users unless these are useful from a recipient perspective.

**Comment by pazza83** [comment]
> @pazza83 should we also entirely delete the "Select region" and "Select country" dropdown menu?

Yes

> Not sure how they could help, I think it is a useless information if we enable all currencies for all users unless these are useful from a recipient perspective.

I agree it is useless information. The trade currency will be determined by what fiat/BTC pair the offer is placed. So "Select region" and "Select country" dropdowns are not needed.

**Comment by BtcContributor** [comment]
@ripcurlx I don't have much time to dedicate to dev right now unfortunately and this is taking me more time that I anticipated so I don't want to slow things down more than this

Please assign this issue to someone else, thanks!

**Comment by pazza83** [comment]
Thanks @BtcContributor for letting us know. Is any other @bisq-network/bisq-devs able to take this on?
