### ISSUE TITLE
payment account is not verified

### ISSUE THREAD

**Issue by jjefferson15** [bisq-network/bisq#5505]
1.6.

### Description

Hello,

I have the problem that my payment account is not verified, although it meets all the requirements. I have already made several trades with it, such as:

66891542-0cccf9e6-2ec6-4530-b5c2-2ea814dbaa5e-164

#### Version

1.6.4

**Comment by ripcurlx** [comment]
@jjefferson15 Could you please double check the requirements to get signed here: https://bisq.wiki/Account_limits#How_to_get_an_account_signed

If you have fulfilled all those requirements it would be great to see the log entries at the point when a signing trade was completed and your account age witness should have been signed.

**Comment by jjefferson15** [comment]
I have made several trades with 0.01 BTC each, with several sellers whose account was older than 30 days or signed. How can I send you the logs?

**Comment by pazza83** [comment]
Hi @jjefferson15 have you checked the account signing status of your account? 

Accounts > National Currency Accounts

Click on the payment method and see what it says under 'account signing status'

If the trades where fairly recent it might not have reached the 30 day requirement.

You can access the logs in the root Bisq data directory folder. They are plane txt files called:

bisq.log
bisq_1.log
bisq_2.log

I would recommend sharing them on [Keybase](https://keybase.io/team/bisq). Ripcurlx has the same username there.

**Comment by jjefferson15** [comment]
Thanks, but now its signed. :)
