### ISSUE TITLE
Minor bug on trades window

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#551]
I changed the currency to BTL, but the price still appear BRL/BTC.

See:

![captura de tela de 2016-07-27 15-49-32](https://cloud.githubusercontent.com/assets/1178856/17188111/324720fe-5412-11e6-8b1f-ab36146cb684.png)

**Comment by ManfredKarrer** [comment]
Can you restart and see if you can reproduce that? I cannot reproduce it.

**Comment by ManfredKarrer** [comment]
I found the bug. Thanks for reporting! There will be a new update soon with minor bug fixes.
