### ISSUE TITLE
Expecting a double but found infinity

### ISSUE THREAD

**Issue by dawiepoolman** [bisq-network/bisq#5511]
[bisq.log](https://github.com/bisq-network/bisq/files/6506111/bisq.log)
<img width="762" alt="Bisq2" src="https://user-images.githubusercontent.com/2351212/118761668-1650a380-b875-11eb-85db-d32e8e4286f9.PNG">
<img width="1307" alt="Bisq2b" src="https://user-images.githubusercontent.com/2351212/118762676-e7d3c800-b876-11eb-97af-264ef362da9c.PNG">

### Description

When I woke up this morning I saw this error. I do have a pending trade in progress if that could be relevant of which I took a screenshot for myself yesterday as well (for which I suspect the buyer has not paid btw).

I had to restart bisq

#### Version

Bisq-64bit-1.6.4.exe

### Screenshots

attached

#### Device or machine

Win 10

**Comment by dawiepoolman** [comment]
the application now stays minimized and wont maximize
<img width="182" alt="Bisq3" src="https://user-images.githubusercontent.com/2351212/118764296-8f51fa00-b879-11eb-991f-49f7d8527f14.PNG">

**Comment by ripcurlx** [comment]
@dawiepoolman The exception was because of a wrong value in the offerbook chart view. So that is something that should be gone after a restart or switching between sections. If you quit the app again and try to start does it always stay minimized? If yes, could you please check the log file in that case and post the startup log part to see if there is some error logged in there.

**Comment by dawiepoolman** [comment]
Hi ripcurlx
Tx for checking.  
I did a reboot and it stayed minimized.  Log attached
[bisq.log](https://github.com/bisq-network/bisq/files/6506813/bisq.log)
.

**Comment by ripcurlx** [comment]
I didn't see anything suspicious in the log file. Could you try to shut down Bisq again and check in the Taskmanager if no Bisq process is running (kill it if there is one) and try to start afterwards again. Unfortunately I'm no Windows user so I don't know by hard if there is a way to force a minimized window to be maximized again.

**Comment by dawiepoolman** [comment]
I have killed the process a few times via Taskmanager.  It keeps starting in minimized window now.  I figured when I press Alt+Space the window(s) maximise one by one.  Bit odd.

**Comment by ripcurlx** [comment]
> I have killed the process a few times via Taskmanager. It keeps starting in minimized window now. I figured when I press Alt+Space the window(s) maximise one by one. Bit odd.

So are you able now to login and use Bisq again?

**Comment by dawiepoolman** [comment]
yes thank you.  at least the Alt+Space workaround seem to work.  I also ran a repair with the .exe but it still opens in minimized mode so it must be some stuck config I suppose.

**Comment by ripcurlx** [comment]
> yes thank you. at least the Alt+Space workaround seem to work. I also ran a repair with the .exe but it still opens in minimized mode so it must be some stuck config I suppose.

maybe a re-install after doing a backup could be worth a try.
