### ISSUE TITLE
Typo in Portfolio>Open trades>Trade information>Wait for blockchain confirmation.

### ISSUE THREAD

**Issue by HeadyWook** [bisq-network/bisq#5513]
### Description

Typo in Portfolio>Open trades>Trade information>Wait for blockchain confirmation.

#### Version

1.6.2

### Expected behaviour

It should read, "...The BTC buyer must wait for..."

### Actual behaviour

It reads, "The BTC buyer need to wait for..."

It is missing an "s" after "need". Also, "must wait" sounds better in my opinion.

### Screenshots

![image](https://user-images.githubusercontent.com/38931215/118931782-2fe8fe00-b8fc-11eb-973f-83540c60fe09.png)

#### Device or machine
Linux Manjaro

#### Additional info

I wanted to make the pull request myself but I failed at locating where the string is in the code base. If someone points it out, I will be happy to make my first pull request on the Bisq repository.

**Comment by ripcurlx** [comment]
@m52go ☝️
