### ISSUE TITLE
Cannot choose installation location on Windows

### ISSUE THREAD

**Issue by destenson** [bisq-network/bisq#552]
When you install BitSquare from the windows installer (i.e. Bitsquare-64bit-0.4.9.1.exe) it installs BitSquare in AppData/Local. I want to install it somewhere else, but it doesn't provide that option.

**Comment by ManfredKarrer** [comment]
Hm... I use the standard java packager which does not offer such options as far I know, but have nto looked closer into it. Why you want to install it somewhere else?

**Comment by destenson** [comment]
Because my user folder is on a hard drive that constantly runs out of space, so I always install things elsewhere when I can.

**Comment by ManfredKarrer** [comment]
ah ok.
