### ISSUE TITLE
Unreliable network delivery causing trading issues.

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#5526]
_Opening this to give the problem more visibility and hoping that more eyes can lead to a fix._

This is an attempt to describe a long-standing issue with messaging in Bisq.  Rare, but frequent enough to be an almost daily occurrence in the network.  Some messages supposedly arrive, but don't get seen by the recipient Bisq application layer.  Causing such problems as failed trades and miscommunication between users.

[Update - just noticed #1172 from 2018 describes the same problem.  Seems that many people investigated but it was never resolved.  Looks like a problem with TOR.]

---

Bisq uses TCP for networking which is a "reliable" protocol.  [However, what this actually means is](https://stackoverflow.com/questions/14303198/is-tcp-100-reliable#14303258):

> TCP is reliable in the sense that messages sent will either be received as they were sent (same order, same contents); assuming that the built-in checksum does not happen to fail, which it may, since it is only 16 bits **OR not be received at all**

The small percentage of messages **not received at all** are causing these issues.

---

### Example 1:

- Mediator sends a chat message to Trader, status=Message arrival confirmed by receiver.  All good.
![image](https://user-images.githubusercontent.com/47253594/119432319-c0975380-bcd9-11eb-84bd-2d042e07462a.png)
- Trader sends a chat message to Mediator, status=Message arrived at receiver.
![image](https://user-images.githubusercontent.com/47253594/119432441-f63c3c80-bcd9-11eb-9bea-f7458f52c23e.png)
- Looks good from the sender's side, **however, Mediator never actually received the message**.  

---

### Example 2:

- Alice clicks "Payment started".  (status=`Message arrived at receiver`)
- No `ack` message is received back so Alice is prompted again to click "Payment started".
- And again and again until they ask in support why the button is not working.
- **Bob never receives the Payment started message**.

This used to be known as `Seller cannot confirm` (#4748) since they did not receive Payment started, however since #5401 the burden is shifted to the buyer who is told to try again.  Its still causing a problem but at least there's an option to retry now, whereas before the only option was mediation.  What can be learned from this is that retrying the send message, and even rebooting the sender does not help.  Perhaps rebooting the recipent side would help, but no one has come forth to report that as successful yet.

---

@leo816 has experienced it multiple times and reported both examples above.

`Seller-cannot-confirm` is a high cause of mediation tickets, e.g. 

> [...] biggest issue we faced was the bug that had to do with the seller not being able to confirm that he had received the payment, even though the buyer had clicked on "payment made" correctly.

https://github.com/bisq-network/roles/issues/83#issuecomment-570814818 from 18 months ago

---

### Example 3:

Trader opens dispute but the `OpenNewDisputeMessage` is not received by mediator, leading to trades which cannot be mediated.  This has been reported a number of times, do we have logs for this @huey735?

---

### Example 4:

Payment info is not delivered to the open trade.  Reported by @leo816, waiting for logs to confirm but presumably could be the same issue of unreliable network delivery.

**Comment by ripcurlx** [comment]
Do we have logs from the party that didn't send the ACK message? To see why it is received, but not processed properly to send the corresponding ACK message.

**Comment by ghost** [comment]
I concluded that the messages don't get seen at the recipient Bisq application layer.  But lets double-check the logs again to make sure.

**Comment by ghost** [comment]
Confirmed with logs from @leo816 that in these cases, messages are not seen by the receiver.  That is why no ACK is sent back.  Creating a PR for Chat messages to expect an ACK and indicate the problem if not received.

**Comment by ghost** [comment]
Not stale, please re-activate.

**Comment by ghost** [comment]
> Looks like a problem with TOR.

Seems this was an easy but incorrect conclusion on my behalf.
Now I'm convinced the issue is within the Bisq message handling code. #6785
