### ISSUE TITLE
Cannot close app after it launches without entering a password

### ISSUE THREAD

**Issue by destenson** [bisq-network/bisq#553]
When the app launches, it asks for a password to unlock, but it won't let you do _anything_ until you do. You can't move the window, or resize it, or even close it. The only way I've found to close it without entering a password is to kill it forcefully with task manager.

**Comment by ManfredKarrer** [comment]
On the mac you can quit it with cmd+q. On windows its prob. ctrl + q.
But it is a know issue that the modal popups block the main screen. I had tried to solve that but did not find yet how.
