### ISSUE TITLE
Market price display at the top doesn't update

### ISSUE THREAD

**Issue by mmortal03** [bisq-network/bisq#554]
The market price display at the top doesn't seem to update.  I have BTC/XMR selected, for example.  Neither the ask price or the bid price has changed since I loaded Bitsquare. I'm using 0.4.9.1 64-bit on Windows 7 64-bit. This also doesn't seem to have been working in previous versions.

I read in another issue thread that altcoins get updated every 3 min, but I'm also watching Poloniex in my browser, and this clearly isn't the case.

**Comment by ManfredKarrer** [comment]
thanks for reporting. have found the bug. Will be fixed with next release....
