### ISSUE TITLE
High CPU usage while user not performing any actions.

### ISSUE THREAD

**Issue by dan-da** [bisq-network/bisq#555]
Yesterday I left bitsquare running most of the day on a laptop and I noticed that the machine got very hot.  I checked top and bitsquare was continuously using between 100% and 180% of the CPU, on a dual core machine.  This is with bitsquare ostensibly idle offscreen.  no user interactions.  And judging from the orderbooks, very light trading.  It didn't seem to matter if I changed to another screen or tab.

Worried it might be related to bitcoinj over tor, I restarted with that disabled, and also with the dump stats disabled.  That seemed to improve a bit, but it was still using 60-100% cpu.

I updated to the latest code in Development branch, commit 5915e670078256cade8dc71e5b9951b04f4988bf and restarted    This helped quite a bit, but it has been running about 10 minutes now and still the CPU is hovering between 20 and 30% usage.

I suspect this processing is due to either the bitcoin network or p2p.  Anyway, it's a serious issue for an app that needs to be left open for extended periods while trades complete.

I guess a next step diagnosing would be to disable the bitcoin network and see if that improves matters further.

**Comment by ManfredKarrer** [comment]
I fixed a few bugs related to persistance. Did u see any errors in the logs?

I got on one client sometimes stackoveflow but did not find out yet from where it is caused. Seems the btc transaction objects gets caught in a recursive serialisation. 

On my 7 years old macbook i have 3 nodes running and they consume about 3-12% cpu usage each. But I lose sometimes nearly all peers. That did not happen before.
I changed some params in the p2p network code, might be that one of those changes causes that. Need to investigate further to see whats the reason...

**Comment by dan-da** [comment]
I'm seeing these warnings in console output.  peer = unknown address?

seemingly not frequent enough to contribute to high cpu usage.... 

```
Jul-28 12:06:15.856 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: ++ Connection created: peer = unknown address 
Jul-28 12:11:22.496 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: -- Connection closed: peer = oqfgqmlzmyvn7cxt.onion 
Jul-28 12:12:17.390 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: -- Connection closed: peer = uadzuib66jupaept.onion (SeedNode) 
Jul-28 12:14:17.124 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: ++ Connection created: peer = unknown address 
Jul-28 12:15:52.165 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: ++ Connection created: peer = unknown address 
Jul-28 12:17:23.390 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: ++ Connection created: peer = unknown address 
Jul-28 12:20:13.716 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: ++ Connection created: peer = unknown address 
Jul-28 12:20:23.930 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: -- Connection closed: peer = wgthuiqn3aoiovbm.onion (SeedNode) 
Jul-28 12:20:23.933 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: -- Connection closed: peer = iwarjoxceslr5kra.onion 
```

**Comment by ManfredKarrer** [comment]
Thats ok. I just added that to see better when peers are leaving... (used warn because with INFO comes too much logs). unknown address is when the other connects before he has his hidden service published.
u can try to set --logLevel=INFO or DEBUG. TRACE will peob. deliver way too much logs.

**Comment by ManfredKarrer** [comment]
The cpu usage should be ok now again with the new version. Otherwise re-open....
