### ISSUE TITLE
Bug clicking on price

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#556]
Hi,

1- Go to Portfolio/History. 
2- Click three times on price
Result: Bug

See the video uploaded to reproduce the bug
[Bitsquare.zip](https://github.com/bitsquare/bitsquare/files/389736/Bitsquare.zip)

**Comment by ManfredKarrer** [comment]
Thanks a lot for reporting. Found the bug and fixed it. You earned the "Top bug reporter" badge :-) Will convert that into shares once the Synco is in place...

**Comment by bitcoinuser** [comment]
Wow. Thanks.
