### ISSUE TITLE
Illegal reflective access operation by com.google.inject.internal.cglib.core..

### ISSUE THREAD

**Issue by buddhalore** [bisq-network/bisq#5567]
After a transaction got stuck in moderation and unable to progress to arbitration, moderator suggested doing the dump delayed payout, which partly solved the hanging pending payout (missing still the fee).

https://bisq.wiki/Command_line_options#Dump_delayed_payout_transactions to dump the payout transaction for this trade

I get this error message in the console and upon venting it to the moderation leader he/she suggested I post it as an issue:

![Bisq error delayed payout](https://user-images.githubusercontent.com/85696011/121557658-39eeb000-ca15-11eb-8e10-5b6ba30f4833.png)

**Comment by buddhalore** [comment]
> The warning is fine and is fixed in the latest release of Google Guice (5.0.1). If it doesn't cause any other side effects it will be shipped in the next release.

Tx, in addition got a GPG signature fail from downloading 1.6.5 straight from bisq.io/downloads yesterday around 6 CET. Can't recall it having happened before over the years
![Attender PGP fail](https://user-images.githubusercontent.com/85696011/121726821-565d1c00-caeb-11eb-83f4-646ac7ed747e.png)

**Comment by ripcurlx** [comment]
> > The warning is fine and is fixed in the latest release of Google Guice (5.0.1). If it doesn't cause any other side effects it will be shipped in the next release.
> 
> Tx, in addition got a GPG signature fail from downloading 1.6.5 straight from bisq.io/downloads yesterday around 6 CET. Can't recall it having happened before over the years
> ![Attender PGP fail](https://user-images.githubusercontent.com/85696011/121726821-565d1c00-caeb-11eb-83f4-646ac7ed747e.png)

You are not the first one reporting this 🤔 . I checked it after the first report myself again and got a valid signature and binary. Could you please try it again if it is happening all the time?

**Comment by buddhalore** [comment]
Hi again ripcurlx, so verification fail again today with 1.7.0 several times from the download page on bisq.io (.dmg for mac)

The updater in the client worked for GPG verification and seemed to have installed correctly

**Comment by ripcurlx** [comment]
> Hi again ripcurlx, so verification fail again today with 1.7.0 several times from the download page on bisq.io (.dmg for mac)
> 
> The updater in the client worked for GPG verification and seemed to have installed correctly

That is a pretty weird behavior. Could you please paste the hash of the binary when you download it? So I can verify if it is what it should be.

**Comment by buddhalore** [comment]
Am I correct in assuming you mean doing "shasum -a 256" in terminal for the downloaded .dmg ?

This is the result (image): Top one is binary hash from terminal and bottom one is Bisq-1.7.0.jar.txt

![Hash](https://user-images.githubusercontent.com/85696011/124615576-b2f6f100-de75-11eb-87c0-9545e38bd06b.png)

**Comment by ripcurlx** [comment]
The one in the txt file is for the jar file not for the binary. The hash you've posted is fine.

**Comment by ripcurlx** [comment]
If you follow https://bisq.wiki/Downloading_and_installing#macOS_and_Linux and run `gpg --digest-algo SHA256 --verify ~/Downloads/Bisq-1.7.0.dmg.asc` what does it print?

**Comment by buddhalore** [comment]
So the signature verifies for 1.7.1 both from the client installer and in terminal
At least some good news here

![Screen Shot 2021-07-13 at 15 26 53](https://user-images.githubusercontent.com/85696011/125460675-f9ef45c0-233b-41ac-8e94-8e89579c3487.png)
