### ISSUE TITLE
Unable to build 0.4.9.1

### ISSUE THREAD

**Issue by dougbebber** [bisq-network/bisq#557]
Building on 64-bit Ubuntu Desktop 16.04 LTS.

I was able to build 0.4.9.0 but get the following error when attempting to build v 0.4.9.1 anyone else experience this? any suggestions? (build output follows):

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] parent
[INFO] common
[INFO] jsocks
[INFO] jtorctl
[INFO] jtorproxy
[INFO] network
[INFO] core
[INFO] gui
[INFO] headless
[INFO] seednode
[INFO] monitor
[INFO] jdkfix
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building parent 0.4.9.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ parent ---
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building common 0.4.9.1
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.bitcoinj:bitcoinj-core:jar:0.13.1.5 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] parent ............................................. SUCCESS [  0.135 s]
[INFO] common ............................................. FAILURE [  0.112 s]
[INFO] jsocks ............................................. SKIPPED
[INFO] jtorctl ............................................ SKIPPED
[INFO] jtorproxy .......................................... SKIPPED
[INFO] network ............................................ SKIPPED
[INFO] core ............................................... SKIPPED
[INFO] gui ................................................ SKIPPED
[INFO] headless ........................................... SKIPPED
[INFO] seednode ........................................... SKIPPED
[INFO] monitor ............................................ SKIPPED
[INFO] jdkfix ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.381 s
[INFO] Finished at: 2016-07-29T11:49:41-05:00
[INFO] Final Memory: 10M/162M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project common: Could not resolve dependencies for project io.bitsquare:common:jar:0.4.9.1: Failure to find org.bitcoinj:bitcoinj-core:jar:0.13.1.5 in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-oss-snapshot has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :common

**Comment by ManfredKarrer** [comment]
You need to built the latest BitcoinJ (Bitsquare fork) verison 0.13.1.5. There was an update.

**Comment by dougbebber** [comment]
I tried that but must have missed something. I completely removed my prior bitcoinj directory and recloned and did a clean install. That worked!

Thank you!
