### ISSUE TITLE
Trade failed but security deposit is still locked

### ISSUE THREAD

**Issue by SoldadoBTC** [bisq-network/bisq#5574]
### Description

I made a transaction and it has failed (it got stucked in OPEN TRADES), i moved it to FAILED TRADES but the security deposit is still locked.

Already tried to remove PendingTrades files in db folder and do a spv resync only to remove invalid invalid transactions, but it did not work. Actually the locked funds disapeared as well as the transaction (it is not in FAILED nor in the OPEN TRADES anymore)

Bellow you can find the original screenshots of the transaction.

#### Version

1.6.5

### Steps to reproduce

I can't reproduce

### Expected behaviour

Locked funds to return to the available balance.

### Actual behaviour

Funds Locked

#### Device or machine

WINDOWS 10

#### Additional info
![Capturar](https://user-images.githubusercontent.com/85647096/122293941-ecb78600-cecd-11eb-893f-194ec837cf6a.PNG)
![Capturar2](https://user-images.githubusercontent.com/85647096/122293951-f04b0d00-cecd-11eb-8f9c-a4208b33edc0.PNG)
![Capturar3](https://user-images.githubusercontent.com/85647096/122293966-f50fc100-cecd-11eb-8667-59a73bd73217.PNG)
![Capturar4](https://user-images.githubusercontent.com/85647096/122293988-f8a34800-cecd-11eb-9802-0a96a80c10b3.PNG)

**Comment by ripcurlx** [comment]
> Already tried to remove PendingTrades files in db folder and do a spv resync only to remove invalid invalid transactions, but it did not work. Actually the locked funds disapeared as well as the transaction (it is not in FAILED nor in the OPEN TRADES anymore)

So you are saying, after deleting the pending trades file, you don't see the locked deposit amount in your available balance anymore? Could you please verify if the deposit transaction got included in a block or not?

**Comment by SoldadoBTC** [comment]
Yes, after deleting the pending trades file and resync i don't see the locked deposit neither in my available balance nor in my locked balance anymore it simply desapeard.

The deposit transaction (ef3126e5bceacb6e00ee673d1392e84084ffe6f8c48db51b93f6b93ec9ad7211 - showed in red in one of theprevious  screenshots) was not included in any block as screenshot below:
![Capturar5](https://user-images.githubusercontent.com/85647096/122467833-61072d80-cf91-11eb-95e9-0cb5f63d6f96.PNG)

**Comment by ripcurlx** [comment]
Could you please try to open the emergency wallet and check there the balance: https://bisq.wiki/Emergency_wallet. Just to see if it has all the original account balance there.

**Comment by SoldadoBTC** [comment]
> Could you please try to open the emergency wallet and check there the balance: https://bisq.wiki/Emergency_wallet. Just to see if it has all the original account balance there.


Hi, 
Already did it, but now, after the resync the locked amount simply desapeard. It is not in my available balance anymor neither apears in the LOCK FUNDS.

The only amount that appears to me to transfer using the emergency wallet is the available balance.

**Comment by ripcurlx** [comment]
@SoldadoBTC Could you please provide me your log file over Keybase? My username is the same as on GitHub so I can search through the steps that lead to this issue and reproduce the transaction flow.
