### ISSUE TITLE
Transaction was made with 20 sat/vb instead of 2 sat/vb

### ISSUE THREAD

**Issue by ottosch** [bisq-network/bisq#5575]
### Description
Yesterday I wanted to send all of my funds to a cold storage. I chose 1 sat/vb fee and a dialog told me the minimum was 2 sat/vb (no idea why, since mempool was almost empty).  
I then chose 2 sat/vb and continued. IIRC, the confirmation dialog didn't show the fee in sat/vb, only the total fee (if that is right, then I would suggest to add the sat/vb info as it would have saved me).
I saw ~13K sats as fee and thought that was alright, since the transaction had many inputs, but it turns out that was actually a 20 sat/vb fee.

I remember going back to the previous screen and saw 2 sat/vb was still there.

I am not sure this report will be useful, as it might be difficult to reproduce and happened only once (no balance left to try again).

#### Version

1.6.5 downloaded from Arch User Repository (AUR).
`bisq.common.app.Version: Version{VERSION=1.6.5, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=3, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10}`.

### Steps to reproduce

I don't think it can realiably be reproduced.

### Expected behaviour

Create the transaction with the correct fee: 2 sat/vb.

### Actual behaviour

Transaction was created with a different (10x) fee: 20 sat/vb.

#### Device or machine

Arch Linux; Linux 5.12.10.

#### Additional info

Logs don't seem to have anything useful, just thousands of exceptions about some BSQ reimbursement.
Edit: realised there are many log files. Any particular string I could grep?

**Comment by qxotk** [comment]
Earlier today (6/19/2021) my withdrawal to external wallet was made with 100sat/vb - and it would have made more sense to have been 10sat/vb.  If a link to the block on mempool.space shows the range and median fees on that block: https://mempool.space/block/0000000000000000000adee6d2d531f2c654d6b5b524ece6036d1ef5ea9e7acb

**Comment by MatthewCroughan** [comment]
I can confirm that this also happened to me. I attempted to send with a fee of 3 sat/bv but it instead sent it with a fee of 86 sat/vb which was the automatically chosen default prior to me modifying it. This lost me quite a bit of money.

This happened on the latest v1.7.0 release.

**Comment by MatthewCroughan** [comment]
I've created a discussion that could prevent this issue from happening again in future, please upvote it if you find it useful. 

https://github.com/bisq-network/bisq/discussions/5601
