### ISSUE TITLE
Fail to connect to the bitcoin network after upgrading to 0.4.9.2 (from 0.4.9.1)

### ISSUE THREAD

**Issue by AndreKoster** [bisq-network/bisq#558]
Upon startup, bitsquare gives a warning followed by an error (unreadableWalletException). Both are attached, as well as the bitsquare.log . (EDIT: can't upload the bitsquare.log, file type not supported. I have added .txt to make it uploadable
[bitsquare.log.txt](https://github.com/bitsquare/bitsquare/files/391804/bitsquare.log.txt)
)

![bitsqaure warning](https://cloud.githubusercontent.com/assets/18371058/17269488/f0f44962-5649-11e6-8328-08a6885deae2.png)
![bitsquare error](https://cloud.githubusercontent.com/assets/18371058/17269489/f45b7db4-5649-11e6-897c-f7f6a036922b.png)

**Comment by ManfredKarrer** [comment]
Can you open the application data directory and open mainnet/bitcoin/backup/backups_Bitsquare_wallet. There are the last 10 backups created at each startup.
Make a backup copy of the whole application data directory first just in case.
Then replace the mainnet/bitcoin/Bitsquare.wallet file with the 2 latest backup wallet file. 

If that does not help delete the Bitsquare.spvchain file. If still issues send me the data dir by email (if you trust me :-)).

You can find the application data directory under those locations:
Mac OSX: /Users/username/Library/Application Support/Bitsquare
Linux: /home/username/.local/share/Bitsquare
Windows 7,8: C:\Documents and Settings\username\AppData\Roaming\Bitsquare
Windows XP: C:\Documents and Settings\username\Application Data\Bitsquare

**Comment by AndreKoster** [comment]
It worked. I put the last wallet back that I had before the upgrade, and it started normally.
