### ISSUE TITLE
Improve Bisq Notification app by adding additional information to notifiications

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#5580]
### Description

Many thanks to @devinbileck for getting the Bisq app back up and functioning again. I have been using it for a few weeks now and it has improved my experience of using Bisq.

Generally I find the app most useful to let me know when the 'Trade state has changed'. This often means I have something that I need to action on Bisq.

Currently the Trade State changed notification includes the following (from a sellers perspective_):

`The BTC buyer has started the payment for the trade with the ID XXXXXX`
`received: Date/Time`
`transaction ID: XXXXXX`
`event: Date/Time`

It would be useful if it also had the following info:

`The BTC buyer has started the payment for the trade with the ID XXXXXX`
`received: Date/Time`
`transaction ID: XXXXXX`
`event: Date/Time`
`Amount: eg 100 USD`
`Payment method: eg Zelle`
`Account Name: eg Pazza's Zelle Account`
`Remaining time: eg 20 hours, 10 minutes (until 30 Jun 2021 20:23:36)`

The additional information above would allow users to be able to know if there is something they need to action on Bisq, and when it needs actioning by.

This would be especially useful when the user is away from their instance of Bisq.

The other notifications seem less time critical for something to be actioned eg; The offer was taken, New dispute message.

However maybe it would be good to know if the offer that was taken was to buy or sell BTC. That way the user would know if there is an action required from them.

Eg Make an Instant Altcoin payment, or send a Revolut payment.

#### Version

v.1.3 (iphone)

### Steps to reproduce

Link Bisq notification up with your Bisq instance and make some trades.

### Expected behaviour

Notification app gives you additional trade information that can prompt you to take a certain action within a particular time without the need to be near the Bisq instance.

### Actual behaviour

Notification app gives you trade IDs, but it is hard to know what they are if away from Bisq instance.

**Comment by ripcurlx** [comment]
I think we reduced the amount of information to prevent any data harvesting for a specific mobile identifier. But as they are end-to-end encrypted I don't remember anymore why we kept the limitation (maybe we didn't plan to encrypt them in the beginning) @chimp1984 @devinbileck Do you still remember the reasoning behind this?

**Comment by devinbileck** [comment]
I was not involved in the initial design/implementation so am not familiar with those decisions. But since the message is encrypted this should not be a concern.

**Comment by pazza83** [comment]
Closing this issues as it is superseded by https://github.com/bisq-network/proposals/issues/342
