### ISSUE TITLE
Users in Argentina and Lebanon unable to use Bisq 

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#5581]
### Description

Users in Argentina and Lebanon effectively unable to use Bisq as price controls in their countries mean the difference between the official and unofficial exchange rate exceeds >50%.

Looking at [How to run a Bisq price relay node](https://docs.bisq.network/exchange/howto/run-price-relay-node.html) it would appear Bisq uses the [BitcoinAverage](https://bitcoinaverage.com/) API for fiat prices. The prices on Bitcoin average are the official currency rates.

As both Argentina and Lebanon have foreign currency controls in place. The difference between the official and unofficial rate is 60% for Argentina and 280% for Lebanon.

Bisq limits offers to buy/sell BTC to be a max deviation of 50% from the market price. Unfortunately as this market price is the official rate it effectively prevents users in these countries trading on Bisq.

I think it is important for Bisq to enable users in all countries to be able to trade on Bisq. I think it is especially important to allow users to trade on Bisq where there are current currency controls in place and/or their currency in a state of crisis.

#### Version

1.6.5

### Steps to reproduce

Check the price feeds on the Bisq app for Argentina and Lebanon they use the official rates.

Rate of USD in Argentina / Argentine Peso 
https://bluedollar.net/
Difference between offical and unofficial is 60%

Rate of USD in Lebanon / Lebanese Pound
https://lebaneselira.org/
Difference between official and unofficial is 280%

### Expected behaviour

Remove the max deviation of 50% for currencies with capital controls in place i.e a large percentage difference between official and unofficial rates. 

This would allow users in those countries to place buy and sell offers that are economic and likely to be taken.

### Actual behaviour

Users in Argentina and Lebanon unable to use Bisq due to the difference in official/unofficial exchange rates being uneconomical

**Comment by ghost** [comment]
I believe this can be achieved by excluding the specified currencies from the PriceNode feed.  That way the marketplace will be free to set the price via trading, much the same way as already happens in unquoted markets like BSQ/BTC. 


I did a quick experiment in regtest and successully made a trade using a self-defined unofficial LBP/BTC rate of 535500000.

![image](https://user-images.githubusercontent.com/47253594/122697336-bc902000-d20a-11eb-9c02-f3466ac9f260.png)


![image](https://user-images.githubusercontent.com/47253594/122697147-56a39880-d20a-11eb-90d6-6e09523686f5.png)

![image](https://user-images.githubusercontent.com/47253594/122697177-64f1b480-d20a-11eb-887b-b09e4ce78504.png)


A PR can be made to exclude a configurable list of currencies from the PriceNode,  I already have a rough draft of such a PR running to perform this test.  Let me know if this is a suitable solution.  @wiz

**Comment by stopfeds** [comment]
I was just wondering if other currencies are also affected. I checked a few currencies with high inflation and a shady monetary policy (as all the central banks out there lol) but it's really hard to find out the unofficial/real exchange rate. A good way to find out is to compare the price from Bisq Price Index with the price on liquid exchanges. For TRY (Turkey) f.e. it's correct (compared to Bitpanda & Localbitcoins) but it's hard to find liquid markets, with real order books, for currencies like ZWL (Zimbabwe), CDF (Congo), IRR (Iran), VES (Venezuela) etc.

So maybe it would make sense to look into more currencies then the two mentioned above. Especially because some of them [rely a 100% on Bitpay.](https://bisq.wiki/Bisq_Price_Indices).

I will try to find liquid FIAT/BTC markets or sources with unofficial/real exchange rates for some of the currencies.

Of course, if the max deviation gets removed, we should warn the user with a short explanation.

**Comment by pazza83** [comment]
I think it is not so much a problem with inflation. It is more a case of countries that limit currency exchanges or provide only allow currency exchanges as an artificial rate to try and limit capital flight occurring. 

I have a look at Venezuela and the difference there was only 3% presumably as despite the high inflation foreign exchange is still relatively easy. 

Sudan's difference was 10%.

Zimbabwe seems to be about 15%. 

I don't think Turkey has implemented currency controls yet so their is no black market rate.

> I checked a few currencies with high inflation and a shady monetary policy (as all the central banks out there lol) but it's really hard to find out the unofficial/real exchange rate

Yes, I found it difficult to find any good resources that showed data for multiple counties. 

> Of course, if the max deviation gets removed, we should warn the user with a short explanation.

Agreed.

**Comment by stopfeds** [comment]
> I think it is not so much a problem with inflation. It is more a case of countries that limit currency exchanges or provide only allow currency exchanges as an artificial rate to try and limit capital flight occurring.

Of course but if the currency is quiet stable there won't be any foreign currency controls. So I'd say there is a high correlation between inflating the national currencies and shady monetary policy (canceling free market by controlling exchange rates).

I have asked a around and it seems like it is indeed quiet difficult to get reliable sources in terms of BTC price and official exchange rates for smaller currencies. 
In Africa, for example, a lot of trading happens in Facebook & Whatsapp groups as there are no exchanges offering the FIAT/BTC pair.

Where did you get your numbers from?

**Comment by pazza83** [comment]
Yes agreed, it looks like differences would be due to whatever currency controls are put in place so differences can be quite transient.

Numbers I got where from:

Argentina / Argentine Peso - https://bluedollar.net/
Lebanon / Lebanese Pound - https://lebaneselira.org/

I did not record the others as the price difference was not too much to impact Bisq trading.
