### ISSUE TITLE
Mediation requested grammar

### ISSUE THREAD

**Issue by BitcoinLabrador** [bisq-network/bisq#5583]
The grammar in the 'mediation requested' section isn't correct:
![image](https://user-images.githubusercontent.com/69748779/123076155-267e1480-d419-11eb-9e55-bf2fa19f89f7.png)

Should be:
You already opened a dispute.

Please communicate with the mediator in the "support" screen.

**Comment by ripcurlx** [comment]
@m52go Could you please have a look at it? Thanks!
