### ISSUE TITLE
Is the trade protocol upgraded?

### ISSUE THREAD

**Issue by typhu-xyz** [bisq-network/bisq#5590]
### Description

Just upgraded to 1.7.0. Realized that 'trade protocol' has become 4. Looked through code (for 1.7.0) and see it's still clearly 3. Dug into the installed jar file and found it's 4 there (somehow). The way I upgraded is via downloading the exe from the official site. The PGP signature looks correct.

#### Version

Version{VERSION=1.7.0, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=4, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10}

### Expected behaviour

It seems to me that the trade protocol has not really upgraded. But it could be that I've missed something in the source code.

**Comment by bisqubutor** [comment]
https://github.com/bisq-network/bisq/blob/d03a472d017642505f98b7124e2cb8db757ac793/common/src/main/java/bisq/common/app/Version.java#L102

**Comment by ripcurlx** [comment]
The trade protocol upgrade is done in the privacy patch that wasn't disclosed publicly yet. As soon as v1.7.0 will be the mandatory version (within days) we'll push the source to the release branch which will also include the updated trade protocol version.

**Comment by bisqubutor** [comment]
@typhu-xyz you are correct. I compiled from source of v1.7.0 release and still on old version of trade protocol. so the released sources do not match the precompiled releases. 

`[main] INFO  b.c.app.Version: Version{VERSION=1.7.0, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=3, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10}  `

The 1.7.0 sources or git sources do not actually match.

![TRADE_PROTOCOL_VERSION](https://user-images.githubusercontent.com/79169291/123945830-12dd2b80-d98e-11eb-81d2-d9fa51a1a828.png)

**Comment by ripcurlx** [comment]
> @typhu-xyz you are correct. I compiled from source of v1.7.0 release and still on old version of trade protocol. so the released sources do not match the precompiled releases.
> 
> `[main] INFO b.c.app.Version: Version{VERSION=1.7.0, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=3, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10} `
> 
> The 1.7.0 sources or git sources do not actually match.
> 
> ![TRADE_PROTOCOL_VERSION](https://user-images.githubusercontent.com/79169291/123945830-12dd2b80-d98e-11eb-81d2-d9fa51a1a828.png)

☝️ please see my comment before your comment

**Comment by typhu-xyz** [comment]
Gotcha, will wait for the release
