### ISSUE TITLE
Missing tar.gz.asc for 1.7.0 release 

### ISSUE THREAD

**Issue by dmp1ce** [bisq-network/bisq#5592]
The tar.gz.asc is used for verification in the Arch Linux `bisq` package. https://aur.archlinux.org/packages/bisq/

Unfortunately, the tar.gz.asc is missing for the 1.7.0 release.

**Comment by ripcurlx** [comment]
> The tar.gz.asc is used for verification in the Arch Linux `bisq` package. https://aur.archlinux.org/packages/bisq/
> 
> Unfortunately, the tar.gz.asc is missing for the 1.7.0 release.

@dmp1ce This wasn't published yet, as the source of the privacy patch that was released isn't public yet as well. We'll set within the next few days v1.7.0 as required version and will disclose the issue at that point and also push the source code and update the release tag. After that I can publish the signature.

**Comment by lavinger** [comment]
> The tar.gz.asc is used for verification in the Arch Linux `bisq` package. https://aur.archlinux.org/packages/bisq/
> 
> Unfortunately, the tar.gz.asc is missing for the 1.7.0 release.

@dmp1ce The file is already there.

**Comment by ripcurlx** [comment]
> > The tar.gz.asc is used for verification in the Arch Linux `bisq` package. https://aur.archlinux.org/packages/bisq/
> > Unfortunately, the tar.gz.asc is missing for the 1.7.0 release.
> 
> @dmp1ce The file is already there.

Yes, I pushed the source including the privacy patch now to the release.
