### ISSUE TITLE
Timeout Reached. Protocol did not complete in 60 sec.

### ISSUE THREAD

**Issue by CLPBH** [bisq-network/bisq#5594]
![image](https://user-images.githubusercontent.com/86716344/123943824-cbaa6700-d99c-11eb-819f-ab8452f4113f.png)

**Comment by ripcurlx** [comment]
@CLPBH Could you please provide us with the log file when this happened? Maybe best via DM on Keybase. My handle is the same as here on GitHub. To check if there was just a network issue or something else causing this.

**Comment by dgyg** [comment]
I also encountered this issue:

```
Jan-15 13:14:19.777 [JavaFX Application Thread] ERROR b.c.t.p.TradeProtocol: Timeout reached. TradeID=XXXXX, state=MAKER_SAW_ARRIVED_PUBLISH_DEPOSIT_TX_REQUEST, timeoutSec=120 
Jan-15 13:16:06.368 [JavaFX Application Thread] ERROR b.d.m.o.w.TradeDetailsWindow: trade.getDepositTxId() and trade.getDepositTx().getTxId().toString() are not the same. trade.getDepositTxId()=null, trade.getDepositTx().getTxId().toString()=null, depositTx=null 
```
After that it was not possible to confirm the payment.

In the UI the taker fee transaction was missing (even it was confirmed in the blockchain)

The situation could be resolved with the help of the mediator.
