### ISSUE TITLE
account info in orderbook was not changed to the related trading account

### ISSUE THREAD

**Issue by stakoholic** [bisq-network/bisq#5597]
account info in orderbook was not changed to the related trading account

### Description

i created an offer to buy btc, but wrongly with the F2F account, after changing to SEPA, the payment method is changed correct to SEPA but the account info in orderbook is still show the info from the F2F account which has no trades and is not signed

#### Version

since 1.6.4 and still exist with 1.7

#### Device or machine

manjaro linux

**Comment by pazza83** [comment]
For additional information please see users post here: https://bisq.community/t/account-info-in-orderbook-was-not-changed-to-the-related-trading-account/10985

Are any of the @bisq-network/bisq-devs able to look into this or let @stakoholic know what more info is needed.

**Comment by ghost** [comment]
Questions:

- It would be useful to know if it is repeatable.
- What happens if you edit the offer again, to a different account.
- Do other offers experience the same phenomenon?
 

It would be useful to see:

- Screenshots of the steps taken, offer being edited, and of the incorrect info shown in the offerbook 
- Screenshot of the offer details screen (click on offer ID in portfolio).

**Comment by stakoholic** [comment]
everytime i editing this offer from sepa to f2f and back, the bug is repeatable yes. f2f shows correct infos, but sepa shows me the account info from the never used and not signed f2f account. (which i would like to delete soon...)
thats the offer
![Bildschirmfoto_2021-08-03_00-32-30](https://user-images.githubusercontent.com/42588964/127934176-46acc085-72b0-4d48-888a-607604f9182d.png)

orderbook origin made with f2f
![f2fob](https://user-images.githubusercontent.com/42588964/127934037-288394ce-2c44-45b5-90ac-34123e6c94f7.png)

orderbook edited to sepa
![Bildschirmfoto_2021-08-03_00-29-51](https://user-images.githubusercontent.com/42588964/127934124-18f49ea8-0ba9-477b-ae98-0b50939e44f9.png)




just now i made a new offer, origin made with the sepa account, sepa offer shows all correct but when i switch this offer to f2f it shows me now the complete age from my sepa account instead of the 186 days from f2f account

![Bildschirmfoto_2021-08-03_00-54-30](https://user-images.githubusercontent.com/42588964/127934231-19ac7243-7de2-4122-bb9b-d0d1dd966248.png)

![Bildschirmfoto_2021-08-03_00-55-32](https://user-images.githubusercontent.com/42588964/127934241-5a33e27b-a39e-43d2-b59d-217f1b23ca29.png)

**Comment by ghost** [comment]
Thanks for the helpful report @stakoholic, a code fix has been submitted.

**Comment by Dpalazue** [comment]
? And what do I am new and it's confusing to me
