### ISSUE TITLE
Bug on stats page

### ISSUE THREAD

**Issue by gustawdaniel** [bisq-network/bisq#5604]
On page:

https://bisq.network/stats/

there is typed

![Screenshot from 2021-07-04 20-04-57](https://user-images.githubusercontent.com/16663028/124395161-d77e8c00-dd02-11eb-9773-862b2d2d3c31.png)

But 96997/30 = 3233 it is much more than 118.

Probably this should be better described or there is error in calculations.

**Comment by ripcurlx** [comment]
@m52go That is true - 96,997 is the number of total trades since the beginning not through last month.

**Comment by m52go** [comment]
Updated with https://github.com/bisq-network/bisq-website/commit/55b0a9f6471e36c9a8f21eea9bb336c17840750d...

@ripcurlx this issue can be closed.
