### ISSUE TITLE
Client crash when closing from X.

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#561]
Using Ubuntu 14.04.4, When closing the client bitsquare, it freezes, i wait for a few minutes then closes eventually but has actually crashed, because ubuntu comes up with error of the app.

**Comment by ManfredKarrer** [comment]
Can u send me the logs? u find it under .local/share/Bitsquare

**Comment by ghost** [comment]
[bitsquare_logs.txt](https://github.com/bitsquare/bitsquare/files/392674/bitsquare_logs.txt)

**Comment by ManfredKarrer** [comment]
There have been many "Saw duplicated block in main chain" form bitcoinJ.
If the crash repeats you can try to delete the Bitsquare.spvchain file inside the bitcoin directory in the app dir. Make a backup of the complete app dir before, just in case.

**Comment by ManfredKarrer** [comment]
Do u still have issues? I will close for now, if you still have problems please re-open.

**Comment by ghost** [comment]
Just want to let you know, the crash kept happening until i updated to your latest version today and when i closed it, it closed normally. Will keep you posted if anything else happens.  Thanks for your hard work!
