### ISSUE TITLE
Bisq cant load

### ISSUE THREAD

**Issue by BENDYMAN20** [bisq-network/bisq#5619]
Java.io.FileNotFoundException c:\Users\*******\Appdata\Roaming\Bisq\\Bisq.Properties (Access Denied)

**Comment by ripcurlx** [comment]
> Java.io.FileNotFoundException c:\Users*******\Appdata\Roaming\Bisq\Bisq.Properties (Access Denied)

Do you have access to this file without admin rights?

**Comment by BENDYMAN20** [comment]
Thanks for the feedback,
But where do I find this file please?

**Comment by BENDYMAN20** [comment]
did you mean access to this file

c:\Users\user\Appdata\Roaming\Bisq\Bisq.Properties

Unfortunately if so, I cant open it and here is a screen shot I took using GYAZO.

https://gyazo.com/f9234f30482718836071499e6500cf35
