### ISSUE TITLE
Show different colors for sell and buy on trades graph

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#562]
The trades graph only show one blue color. I think the graph should be two colors to differentiate the buy and sell trades.

**Comment by bitcoinuser** [comment]
I mean here: (look the blue graph)

![captura de tela de 2016-08-02 17-05-05](https://cloud.githubusercontent.com/assets/1178856/17344476/9af1f582-58d8-11e6-9d9c-1a10e7f3a92d.png)

**Comment by ManfredKarrer** [comment]
Will consider to add that. But have too much other hi prio stuff on the table...

**Comment by haiqu** [comment]
This graph show the overall trading direction for the period, with highs and lows. The graph posted above just shows volume.

![price](https://cloud.githubusercontent.com/assets/13131219/19270898/a14d1254-9005-11e6-9b7a-a7efed3ef852.png)

User needs to update to a later version. It seems as if this ticket should be closed.

**Comment by ManfredKarrer** [comment]
I think @bitcoinuser meant to split the volume bar in a buy and sell bar with diff. colors.
But after reconsidering I think that adds too much info and confuses more than it helps. Also midterm there should nto be so much difference anymore. I will close, if anyone wants to continue to discuss feel free.

**Comment by haiqu** [comment]
Graph I posted wasn't available in v0.4.9.2 which is what he was showing. I agree, it's no longer an issue.
