### ISSUE TITLE
TakerProcessesInputsForDepositTxResponse

### ISSUE THREAD

**Issue by buddhalore** [bisq-network/bisq#5622]
### Description
Another bug here, from the patch update to Mac 10.13.1, Bisq 1.7.0 : failed trade

"Lock time of maker is more than 3 blocks different to the lockTime calculated."
"(No funds have left you wallet)"

Could be VPN interfering giving connection problems?

#### Version

1.7.0 patch

### Steps to reproduce
Taking a new trade from a buyer, the maker lock time is different

### Expected behaviour

Lock times should match

### Actual behaviour
3 blocks difference btwn maker and taker

### Screenshots

![Bisq error 3](https://user-images.githubusercontent.com/85696011/125298080-23938700-e328-11eb-9fa7-b5971cc52300.png)

![Att bisq](https://user-images.githubusercontent.com/85696011/125300326-3444fc80-e32a-11eb-918c-a7c8c33eb6ac.png)

#### Device or machine

Mac High Sierra OSX 10.13.1

#### Additional info

Couldn't quite figure out where the correct log starts and end for this bug as there's now 3 error messages from trades reoccuring in my log.
Here's the log seperated with search with the particular trade ID. It will not be the correct log for the entire bug so let me know and I will post it all if needed

Jul-12 15:41:25.741 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: SendOfferAvailabilityRequest 
Jul-12 15:41:25.742 [JavaFX Application Thread] INFO  b.c.o.a.t.SendOfferAvailabilityRequest: Send OfferAvailabilityRequest with offerId xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170 and uid be4cb700-d0cb-4c54-aa64-7b596ede5ca9 to peer q7pcsjzwq6orvkyauboowl7ov7klopidocvk2gf7ulfcgxfnh5l77pqd.onion:9999 
Jul-12 15:41:25.753 [JavaFX Application Thread] INFO  b.c.o.a.t.SendOfferAvailabilityRequest: OfferAvailabilityRequest arrived at peer: offerId=xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170; uid=be4cb700-d0cb-4c54-aa64-7b596ede5ca9 
Jul-12 15:41:27.741 [JavaFX Application Thread] INFO  b.c.o.a.OfferAvailabilityProtocol: Received handleOfferAvailabilityResponse from q7pcsjzwq6orvkyauboowl7ov7klopidocvk2gf7ulfcgxfnh5l77pqd.onion:9999 with offerId xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170 and uid 0d9cfe80-076f-49e9-9134-be32263f8eb0 
Jul-12 15:41:27.741 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: ProcessOfferAvailabilityResponse 
Jul-12 15:41:27.741 [JavaFX Application Thread] INFO  b.c.o.a.OfferAvailabilityProtocol: Send AckMessage for OfferAvailabilityResponse to peer q7pcsjzwq6orvkyauboowl7ov7klopidocvk2gf7ulfcgxfnh5l77pqd.onion:9999 with offerId xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170 and sourceUid 0d9cfe80-076f-49e9-9134-be32263f8eb0 
Jul-12 15:41:27.747 [JavaFX Application Thread] INFO  b.c.n.a.TradeEvents: We got a new trade. id=xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170 
Jul-12 15:41:27.768 [JavaFX Application Thread] INFO  b.c.t.p.FluentProtocol$Condition: We received a TAKE_OFFER event at phase INIT and state PREPARATION, tradeId=xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170 
Jul-12 15:41:27.772 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: ApplyFilter 
Jul-12 15:41:27.773 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: TakerVerifyMakerFeePayment 
Jul-12 15:41:27.774 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: CreateTakerFeeTx 
Jul-12 15:41:27.776 [JavaFX Application Thread] INFO  b.c.b.m.AddressEntryList: swapAvailableToAddressEntryWithOfferId newAddressEntry=AddressEntry{address=bc1qclj83dtl2n9jzsxv2x52ay957ye96wvur6sxuq, context=MULTI_SIG, offerId='xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170', coinLockedInMultiSig=0, segwit=true} 
Jul-12 15:41:27.785 [JavaFX Application Thread] INFO  o.b.w.WalletFiles: Saving wallet; last seen block is height 690707, date 2021-07-12T13:40:13Z, hash 0000000000000000000fba0409a1164c5e264b69a4c4123447bc924afa1d62ef 
Jul-12 15:41:27.831 [JavaFX Application Thread] INFO  o.b.w.WalletFiles: Save completed in 46.38 ms 
Jul-12 15:41:27.832 [JavaFX Application Thread] INFO  b.c.b.w.BtcWalletService: getOrCreateAddressEntry: new AddressEntry=AddressEntry{address=bc1qqspsqstlgvjhgycjdpeagpncz6sf0dr8jt4sc7, context=TRADE_PAYOUT, offerId='xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170', coinLockedInMultiSig=0, segwit=true} 
Jul-12 15:41:27.833 [JavaFX Application Thread] INFO  b.c.b.m.AddressEntryList: addAddressEntry: add new AddressEntry AddressEntry{address=bc1qqspsqstlgvjhgycjdpeagpncz6sf0dr8jt4sc7, context=TRADE_PAYOUT, offerId='xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170', coinLockedInMultiSig=0, segwit=true} 
Jul-12 15:41:27.836 [JavaFX Application Thread] INFO  o.b.w.WalletFiles: Saving wallet; last seen block is height 690707, date 2021-07-12T13:40:13Z, hash 0000000000000000000fba0409a1164c5e264b69a4c4123447bc924afa1d62ef 
Jul-12 15:41:28.045 [JavaFX Application Thread] INFO  o.b.w.WalletFiles: Save completed in 208.9 ms 
Jul-12 15:41:28.046 [JavaFX Application Thread] INFO  b.c.b.w.BtcWalletService: getOrCreateAddressEntry: new AddressEntry=AddressEntry{address=bc1qe44xnu8y4w0rhyjpqsqf85npz3e8ke350jzauv, context=RESERVED_FOR_TRADE, offerId='xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170', coinLockedInMultiSig=0, segwit=true} 
Jul-12 15:41:28.046 [JavaFX Application Thread] INFO  b.c.b.m.AddressEntryList: addAddressEntry: add new AddressEntry AddressEntry{address=bc1qe44xnu8y4w0rhyjpqsqf85npz3e8ke350jzauv, context=RESERVED_FOR_TRADE, offerId='xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170', coinLockedInMultiSig=0, segwit=true} 
Jul-12 15:41:28.051 [JavaFX Application Thread] INFO  o.b.w.WalletFiles: Saving wallet; last seen block is height 690707, date 2021-07-12T13:40:13Z, hash 0000000000000000000fba0409a1164c5e264b69a4c4123447bc924afa1d62ef 
Jul-12 15:41:28.095 [JavaFX Application Thread] INFO  o.b.w.WalletFiles: Save completed in 43.50 ms 
Jul-12 15:41:28.095 [JavaFX Application Thread] INFO  b.c.b.w.BtcWalletService: getOrCreateAddressEntry: add new AddressEntry AddressEntry{address=bc1ql89ewlr2p2cs8he6rduaevnzhqw7ec0mnwdnl6, context=AVAILABLE, offerId='null', coinLockedInMultiSig=0, segwit=true} 
Jul-12 15:41:28.096 [JavaFX Application Thread] INFO  b.c.b.m.AddressEntryList: addAddressEntry: add new AddressEntry AddressEntry{address=bc1ql89ewlr2p2cs8he6rduaevnzhqw7ec0mnwdnl6, context=AVAILABLE, offerId='null', coinLockedInMultiSig=0, segwit=true} 
Jul-12 15:41:28.136 [JavaFX Application Thread] INFO  o.b.w.Wallet: Completing send tx with 2 outputs totalling 0.0140819 BTC and a fee of 0.00 BTC/vkB 
Jul-12 15:41:28.137 [JavaFX Application Thread] INFO  o.b.w.Wallet:   with 0.03953325 BTC change 
Jul-12 15:41:28.144 [JavaFX Application Thread] INFO  o.b.w.Wallet:   with a fee of 0.00013759 BTC/kB, 0.00003495 BTC for 254 bytes 
Jul-12 15:41:28.144 [JavaFX Application Thread] INFO  o.b.w.Wallet:   completed: Transaction{fbdc1aa62ecdceca679cba4113d24c6d70c4ebd053a6b04db468a2152b9ac3fa, wtxid a7765ceb321911ceeb801063fd3c4b03994951acea28eb0055c9fa5b2bb90fcc
weight: 689 wu, 173 virtual bytes, 254 bytes
purpose: USER_PAYMENT
   in   <empty>  0.0536501 BTC (5365010)
        witness:30440220544b71fdf2b9f9daccf4f33c00e82ab449a3f1b6a3fde86a3341a2f6d10cca030220267df2bc24b81fb0a4c4ace862fc16229ad1b02faaa06c2c9e89c85be6bc362f01 02547879aeef57fe8b467901698a3044f7b70510bb397dbf222d7fff22894af363
        P2WPKH addr:bc1qzmgslxzx7kf0s260zkr8t0pwleayjcplqc6h76  outpoint:70d2514f9c8d988c55db628c0c3a1c3c0995f6852642740c48755fd0052b8915:2
   out  HASH160 PUSHDATA(20)[4bc07b10e86df307c408da115896a0e8293c24c4] EQUAL (a9144bc07b10e86df307c408da115896a0e8293c24c487)  0.00007 BTC (7000)
        P2SH addr:38bZBj5peYS3Husdz7AH3gEUiUbYRD951t
   out  0[] PUSHDATA(20)[cd6a69f0e4ab9e3b9241040093d26114727b6634] (0014cd6a69f0e4ab9e3b9241040093d26114727b6634)  0.0140119 BTC (1401190)
        P2WPKH addr:bc1qe44xnu8y4w0rhyjpqsqf85npz3e8ke350jzauv
   out  0[] PUSHDATA(20)[f9cb977c6a0ab103df3a1b79dcb262b81dece1fb] (0014f9cb977c6a0ab103df3a1b79dcb262b81dece1fb)  0.03953325 BTC (3953325)
        P2WPKH addr:bc1ql89ewlr2p2cs8he6rduaevnzhqw7ec0mnwdnl6
   fee  0.00005072 BTC/wu, 0.00020202 BTC/vkB, 0.00013759 BTC/kB  0.00003495 BTC
} 
Jul-12 15:41:28.147 [JavaFX Application Thread] INFO  b.c.b.w.BtcWalletService: swap addressEntry with address bc1qk23sy8enx9al6lftqpzn5unpejwqt9ar0f5fsz and offerId xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170 from context OFFER_FUNDING to available 
Jul-12 15:41:28.147 [JavaFX Application Thread] INFO  b.c.b.m.AddressEntryList: swapToAvailable addressEntry to swap=AddressEntry{address=bc1qk23sy8enx9al6lftqpzn5unpejwqt9ar0f5fsz, context=OFFER_FUNDING, offerId='xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170', coinLockedInMultiSig=0, segwit=true} 
Jul-12 15:41:28.147 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: SellerAsTakerCreatesDepositTxInputs 
Jul-12 15:41:28.150 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: TakerSendInputsForDepositTxRequest 
Jul-12 15:41:28.153 [JavaFX Application Thread] INFO  b.c.t.p.t.t.TakerSendInputsForDepositTxRequest: Send InputsForDepositTxRequest with offerId xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170 and uid f20c9a1a-79e4-467c-b9cb-f4526c5e50d4 to peer q7pcsjzwq6orvkyauboowl7ov7klopidocvk2gf7ulfcgxfnh5l77pqd.onion:9999 
Jul-12 15:41:28.177 [JavaFX Application Thread] INFO  b.c.o.a.OfferAvailabilityProtocol: AckMessage for OfferAvailabilityResponse arrived at makersNodeAddress q7pcsjzwq6orvkyauboowl7ov7klopidocvk2gf7ulfcgxfnh5l77pqd.onion:9999. offerId=xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170, sourceUid=0d9cfe80-076f-49e9-9134-be32263f8eb0 
Jul-12 15:41:28.206 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received AckMessage for OfferAvailabilityRequest with offerId xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170 and uid be4cb700-d0cb-4c54-aa64-7b596ede5ca9 
Jul-12 15:41:28.207 [JavaFX Application Thread] INFO  b.c.t.p.t.t.TakerSendInputsForDepositTxRequest: InputsForDepositTxRequest arrived at peer: offerId=xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170; uid=f20c9a1a-79e4-467c-b9cb-f4526c5e50d4 
Jul-12 15:41:28.207 [JavaFX Application Thread] INFO  b.c.t.p.TradeProtocol: TaskRunner successfully completed. Triggered from TAKE_OFFER, tradeId=xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170 
Jul-12 15:41:29.738 [JavaFX Application Thread] INFO  b.c.t.p.SellerProtocol: Received InputsForDepositTxResponse from q7pcsjzwq6orvkyauboowl7ov7klopidocvk2gf7ulfcgxfnh5l77pqd.onion:9999 with tradeId xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170 and uid f561bdff-a240-4483-ab5c-2de69fbf7a8d 
Jul-12 15:41:29.739 [JavaFX Application Thread] INFO  b.c.t.p.SellerAsTakerProtocol: Received InputsForDepositTxResponse from q7pcsjzwq6orvkyauboowl7ov7klopidocvk2gf7ulfcgxfnh5l77pqd.onion:9999 with tradeId xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170 and uid f561bdff-a240-4483-ab5c-2de69fbf7a8d 
Jul-12 15:41:29.745 [JavaFX Application Thread] INFO  b.c.t.p.FluentProtocol$Condition: We received a InputsForDepositTxResponse at phase INIT and state PREPARATION, tradeId=xeeOt-9218cd4c-00fd-4784-823f-410ff40077a5-170 
Jul-12 15:41:29.746 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: TakerProcessesInputsForDepositTxResponse 
Jul-12 15:41:29.785 [JavaFX Application Thread] ERROR b.c.t.Task: An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 692922, myLockTime=693587 
Jul-12 15:41:29.785 [JavaFX Application Thread] ERROR b.c.t.TaskRunner: Task failed: TakerProcessesInputsForDepositTxResponse / errorMessage: An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 692922, myLockTime=693587 
Jul-12 15:41:29.785 [JavaFX Application Thread] ERROR b.c.t.p.TradeProtocol: Task runner failed with error An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 692922, myLockTime=693587. Triggered from InputsForDepositTxResponse

**Comment by ripcurlx** [comment]
This just means the maker is not in sync. This normally solves itself over time as soon as the other peer is fully synced.
