### ISSUE TITLE
Cannot invoke "javafx.scene.Node.getLayoutBounds()" because "this.textNode" is null 

### ISSUE THREAD

**Issue by nunyabidnes** [bisq-network/bisq#5624]
Whenever I try to run Bisq, I get the attached message and logs. After clicking Close on the error message, Bisq is stuck in the splash screen, and I can't do anything other than close it.

Bisq was installed via the AUR. Running Manjaro, kernel 5.10.49-1-MANJARO

![Screenshot_2021-07-13_19-18-45](https://user-images.githubusercontent.com/48492119/125537615-2f211067-f636-4dd5-af9c-2f47955e29cc.png)
[bisq.log](https://github.com/bisq-network/bisq/files/6812513/bisq.log)

**Comment by Premik** [comment]
Seems to be related to the `jre` version. I'm getting this on `java-16-openjdk`. But it works on `java-11-openjdk`.

**Comment by ripcurlx** [comment]
> Seems to be related to the `jre` version. I'm getting this on `java-16-openjdk`. But it works on `java-11-openjdk`.

Could be - we haven't tested Bisq on Java 16 yet. It should run on a Java 15 JRE without any problems.

**Comment by nunyabidnes** [comment]
I followed a suggestion I found at the AUR page for Bisq that fixed it:
sudo archlinux-java set java-11-openjdk
