### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jacobbubble** [bisq-network/bisq#563]
I'm following the prompt I received in app. Although I think it asked me for the log file in the application directory but I'm not sure where that is. I checked my home directory but didn't see anything.

OS: Ubuntu 16.04 

sun.awt.image.BufImgSurfaceData cannot be cast to sun.java2d.xr.XRSurfaceData

**Comment by ManfredKarrer** [comment]
The app dir is under USER/.lcoal/share. you can open it under account/backup.
That bug is a known Java JDK bug and will hopefully be fixed in the next Oracle JDK release.
I think it happens after standby mode or change of monitor resolution.
