### ISSUE TITLE
Cannot invoke "bisq.core.payment.payload.PaymentAccountPayload.getAgeWitnessInputData()" because "paymentAccountPayload" is null

### ISSUE THREAD

**Issue by githubby10** [bisq-network/bisq#5631]
I have received a trade and the taker accidentally hit the dispute button and opened a support ticket after I had already sent the payment. I get a notification in the support tab that I have an open ticket, but when I try to click on the notification I get this error.

**Comment by ripcurlx** [comment]
> I have received a trade and the taker accidentally hit the dispute button and opened a support ticket after I had already sent the payment. I get a notification in the support tab that I have an open ticket, but when I try to click on the notification I get this error.

Could you please try to install the v1.7.1 pre-release: https://github.com/bisq-network/bisq/releases/tag/v1.7.1 This should fix your problem.

**Comment by githubby10** [comment]
I did install the patch and everything is working fine now. Thank you for
your help
