### ISSUE TITLE
Cannot invoke "bisq.core.payment.payload.PaymentAccountPayload.getAgeWitnessInputData()" because "paymentAccountPayload" is null

### ISSUE THREAD

**Issue by woosmokies** [bisq-network/bisq#5635]
### Description

I am getting this error: Cannot invoke "bisq.core.payment.payload.PaymentAccountPayload.getAgeWitnessInputData()" because "paymentAccountPayload" is null

#### Version

1.7

### Steps to reproduce

I launch the application, I get an immediate error that funds have been locked and to open a support case. I go to open a support case as this is when I get the error. 

### Expected behaviour

The expected behavior is to allow my trade to go through

### Actual behaviour

Funds were locked and I get this error now

#### Device or machine

Windows 10 [PC]

**Comment by ghost** [comment]
Please upgrade to the [latest release](https://github.com/bisq-network/bisq/releases), e.g. v1.7.2.  There was a fix made for this issue I believe, #5621
