### ISSUE TITLE
! error cannot invoke "bis.cor.payment.payload.Paymentaccountpayload.getAgeWitnessinputData()

### ISSUE THREAD

**Issue by trailbossgit** [bisq-network/bisq#5637]
I am trying to report this error as suggested by a popup within bisq.

! Error
Cannot invoke "bis.core.payment.payload.PaymentAccountPayload.getAgeWitnessInputData()" because "paymentAccountPayload" is null

To help us to improve the software please report this bug by opening a new issue at...

I got this error message when I clicked on a trade and attempted to open a dispute/mediation by clicking control + o.
This was suggested by support as a situation I described sounded like a failed trade.

"I'm stuck on a trade to buy btc with zelle in usd. I'm at the point where I'm supposed to "start payment using ...."  But there is no phone number or email or name shown in bisq to know whom to send the $ to using zelle.  I used zelle about 6 or 7 times so far  (keeping under daily limit) and each time, there was info in bisq for me to know where to send the money.  Is there a penalty to cancel the trade, or do I ask the seller to give me info in chat or ???  Very baffled."

I will try to attach the log file:
[bisq.log](https://github.com/bisq-network/bisq/files/6874837/bisq.log)

**Comment by trailbossgit** [comment]
And now, when bisq opens, the error message shows up, and won't close.  Clicking on report makes the error message go away, but then there is nothing showing under the tabs market, buybtc, sellbtc, porfolio 1, funds, etc.

**Comment by ghost** [comment]
Your log shows v1.7.0, please upgrade to the [latest release](https://github.com/bisq-network/bisq/releases), e.g. v1.7.2.  There was a fix made for this issue I believe, #5621

**Comment by trailbossgit** [comment]
I found 1.7.1 not 1.7.2 but that still resolved the issue, and of course I'll look for 1.7.2 soon.  I still need to resolve the payment issue but I see now that is a separate issue from this error message I reported, which effectively crashed my bisq.  Up and running again :)  Thank-you so much!
