### ISSUE TITLE
Canceling a trade

### ISSUE THREAD

**Issue by Jacobbubble** [bisq-network/bisq#564]
Is there anyway to cancel a trade after the security deposit is made but before the payment is sent?

Is there anyway to refresh the price after a trade is started? Such as if the buyer and seller both want to trade at exactly market price at the time of the trade. If a trade takes several days both parties are exposed to a bit of volatility.

If a seller sells bitcoin, but the price immediately increases a significant amount; it might make more sense to lose out on the security deposit, not complete the trade, and trade again with another buyer at the current, now higher, price.

**Comment by MarcSte** [comment]
> Is there anyway to cancel a trade after the security deposit is made but before the payment is sent?

No, you explicitly agree to a contract and have to fulfil your part.

> Is there anyway to refresh the price after a trade is started?

No, you're accepting the contract terms at the time of taking an offer. When you trade cryptocurrencies, you're subject to volatility. No matter when a trade closes, the price could go either way immediately after the transaction. In Bitsquare it makes the most sense to fix the price when the user decides to make the deal.

> If a seller sells bitcoin, but the price immediately increases a significant amount; it might make more sense to lose out on the security deposit, not complete the trade, and trade again with another buyer at the current, now higher, price.

This case didn't happen to this day. If that would be abused significantly, the security deposit would have to be raised.

**Comment by ManfredKarrer** [comment]
If you want to follow up the discussion please use the Forum (I try to use GH more for bugs and concrete features)
