### ISSUE TITLE
AUR - the key has expired.

### ISSUE THREAD

**Issue by jerzybrzoska** [bisq-network/bisq#5645]
I ran `gpg --recv-keys CD5DC1C529CDFD3B` and then cloned the AUR git repo to proceed with the installation by running: 
```
git clone https://aur.archlinux.org/bisq.git && cd bisq && makepkg -sirc 
```

The installation succeded, nevertheless I got the following warning:
>Verifying source file signatures with gpg...
>    bisq-1.7.2.tar.gz ... Passed (WARNING: the key has expired.)

**Comment by ripcurlx** [comment]
Hi @jerzybrzoska ! I've updated the key already in the repository some time ago. Not sure if it is need to be update somewhere in the AUR configuration as well? Maybe @freimair knows more about this.

**Comment by Dpalazue** [comment]
Thx
