### ISSUE TITLE
Fee rate doesn't match mempool.space

### ISSUE THREAD

**Issue by xmready** [bisq-network/bisq#5646]
Medium priority says 1 sat/vB on mempool.space, however the automatic fee rate on Bisq stays at 10 sat/vB

**Comment by pazza83** [comment]
Bisq is coded to ensure a min of 10 sat/vB is used for trades. 

When the mempool is empty like now it would be good if this was moved lower.

The problem is if the fee is coded too low than mempool fee spikes cause problems with trades failing and payout transactions getting delayed.
