### ISSUE TITLE
BISQ 64bit 1.7.2 won't launch on windows 10

### ISSUE THREAD

**Issue by ranakp** [bisq-network/bisq#5648]
I installed Bisq about 5 days ago but today it won't open. The icon is there and when I hover over it it shows a blank black window but it won't start up.  I tried system restore  to when I first installed and used it but still didn't help. I have already moved some bitcoins to my account there for sale and would greatly appreciate any tips on how to get access back!

**Comment by ripcurlx** [comment]
What was the last Bisq version that worked for you? Could you have a look at your log file if anything suspicious is logged?

**Comment by ranakp** [comment]
The 1.7.2 that I installed was working fine, but it stopped working. I have 2 log files that end in July 31 entries, the latest around 6pm.  The last entries  say " Peer discovery didn't provide us any more peers, will try again in 10000m" and "Peer discovery took 200.0 ns and returned 0 items". It has registered none of my attempts to open BISQ today , apparently. I have removed and reinstalled BISQ but it didn't help.

**Comment by ranakp** [comment]
Anyone had a similar issue? I copied the BISQ appdata folder, deleted it and reinstalled the program, but it still won't launch :(

**Comment by 58gems** [comment]
I had this issue and the way I solved it was holding shift key while right-clicking the Bisq plate on the Taskbar.  When you get that to work, select maximize.  Bisq now only runs in full screen mode.  Its window may have become minimized to 1 pixel so it's hard to undo.

Whilst this shift-key right-click trick works well on other programs, i was having trouble getting it to work on the Taskbar with Bisq.  The fix was to use this technique right after you enter the command to open Bisq, before it finishes loading.

**Comment by veaz** [comment]
I have the same problem, when I try to use the program, I only see a blank window. The last backup I have of my bisq wallet was on 2020-11-15, after that, I formatted my computer and I could not use bisq again

I use Windows 10 Home

**Comment by ranakp** [comment]
I was able to install it on my friend's laptop, I returned the funds I had moved there, then uninstalled it everywhere. I did all that before trying shift right-click

**Comment by ranakp** [comment]
I was able to install it on my friend's laptop, I returned the funds I had moved there, and ran out!  Uninstalled it everywhere. I did all that before trying shift right-click, but it does seem like a graphical glitch like @58gems was saying.

**Comment by danydanay** [comment]
Same problem here. Maybe its a java route problem?

**Comment by teambitcoin** [comment]
same problem. Uninstalled. Re-installed latest version(verified signatures manually) in a fresh directory. Issues un-resolved.

**Comment by ripcurlx** [comment]
What exact Windows 10 version are you using? I just have a Windows 10 VM, where it runs without any problems. But I can try to re-produce it on the exact same version.

**Comment by ranakp** [comment]
Mine is Windows 10 Education

**Comment by ranakp** [comment]
> 
> 
> I had this issue and the way I solved it was holding shift key while right-clicking the Bisq plate on the Taskbar. When you get that to work, select maximize. Bisq now only runs in full screen mode. Its window may have become minimized to 1 pixel so it's hard to undo.
> 
> Whilst this shift-key right-click trick works well on other programs, i was having trouble getting it to work on the Taskbar with Bisq. The fix was to use this technique right after you enter the command to open Bisq, before it finishes loading.

I only get that Maximize window for a split second when I open the app and then it disappears and doesn't come up anymore.

**Comment by ranakp** [comment]
> 
> 
> same problem. Uninstalled. Re-installed latest version(verified signatures manually) in a fresh directory. Issues un-resolved.

Tried it, didn't solve anything for me. I had my friend install it on her Windows and then used remote access to take out my funds.

**Comment by teambitcoin** [comment]
I'm on win10 Pro 64 bit 10.0.19043

**Comment by ranakp** [comment]
My windows:  10.0.19042 Build 19042, x64

**Comment by ghost** [comment]
https://www.howtogeek.com/howto/windows/bring-misplaced-off-screen-windows-back-to-your-desktop-keyboard-trick/


https://old.reddit.com/r/bisq/comments/o27ikt/bisq_for_windows_not_working_for_me/

**Comment by teambitcoin** [comment]
Tried all those traditional methods. Doesn't work. Reinstalling 1.7.0 window pops open fast and presents the out of date warning.

**Comment by veaz** [comment]
My windows is Windows 10 Home Single Language, version 20H2

**Comment by teambitcoin** [comment]
Found a work around. Right click shortcut, select the "shortcut" tab,  drop down that says RUN: Normal size window 

Change that to RUN: Maximized. 

I have no explanation why this worked but it did

**Comment by cd2357** [comment]
Solution by @teambitcoin documented in https://bisq.wiki/Troubleshooting

**Comment by stefanoklett** [comment]
it doesn't work for me. Is there any other way to take control of BISQ?
I have tried uninstalling and re-installing....
But will there be a way to delete everything and start over?
regards

**Comment by pazza83** [comment]
> it doesn't work for me

I would recommend accessing Bisq's Matrix room for support: https://bisq.wiki/Matrix_bisq.chat
