### ISSUE TITLE
Connecting to Tor Network...

### ISSUE THREAD

**Issue by SeeUnsharp** [bisq-network/bisq#565]
Mainnet connection works fine and is synced but the Tor connection could not be established. It should not be my ISP (Unitymedia - Germany). I have very few cases where it works, but the last 2 weeks, I tried it once a day it didn't work one time.

![image](https://cloud.githubusercontent.com/assets/20801755/17375904/61528db0-59b3-11e6-83c0-faaceb7244fe.png)

I also allowed Bitsquare in Windows Firewall for incoming and outgoing connections. 

I also tried to reinstall (with deleting the app folder) without success.

Cheers!

**Comment by ManfredKarrer** [comment]
Hm strange. Which OS do u use? Can u send me the log files?

**Comment by SeeUnsharp** [comment]
I use Windows 10 Enterprise N x64.

> Aug-03 17:39:58.890 [JavaFX Application Thread] INFO  i.b.a.BitsquareApp: Log files under: C:\Users\Daniel\AppData\Roaming\Bitsquare\bitsquare 
> Aug-03 17:39:58.893 [JavaFX Application Thread] INFO  i.b.app.Version: Version{VERSION=0.4.9.2, P2P_NETWORK_VERSION=4, LOCAL_DB_VERSION=4, TRADE_PROTOCOL_VERSION=1, BTC_NETWORK_ID=0, getP2PNetworkId()=0} 
> Aug-03 17:39:58.893 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.name: Windows 10 
> Aug-03 17:39:58.893 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.version: 10.0 
> Aug-03 17:39:58.893 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.arch: amd64 
> Aug-03 17:39:58.893 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: sun.arch.data.model: 64 
> Aug-03 17:39:58.894 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JRE: 1.8.0_92-b14 (Oracle Corporation) 
> Aug-03 17:39:58.894 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JVM: 25.92-b14 (Java HotSpot(TM) 64-Bit Server VM) 
> Aug-03 17:44:00.881 [JavaFX Application Thread] WARN  i.b.g.m.MainViewModel: startupTimeout called 
> Aug-03 17:47:50.585 [JavaFX Application Thread] INFO  i.b.a.BitsquareApp: Log files under: C:\Users\Daniel\AppData\Roaming\Bitsquare\bitsquare 
> Aug-03 17:47:50.588 [JavaFX Application Thread] INFO  i.b.app.Version: Version{VERSION=0.4.9.2, P2P_NETWORK_VERSION=4, LOCAL_DB_VERSION=4, TRADE_PROTOCOL_VERSION=1, BTC_NETWORK_ID=0, getP2PNetworkId()=0} 
> Aug-03 17:47:50.588 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.name: Windows 10 
> Aug-03 17:47:50.588 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.version: 10.0 
> Aug-03 17:47:50.588 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.arch: amd64 
> Aug-03 17:47:50.588 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: sun.arch.data.model: 64 
> Aug-03 17:47:50.589 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JRE: 1.8.0_92-b14 (Oracle Corporation) 
> Aug-03 17:47:50.589 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JVM: 25.92-b14 (Java HotSpot(TM) 64-Bit Server VM) 
> Aug-03 17:51:52.561 [JavaFX Application Thread] WARN  i.b.g.m.MainViewModel: startupTimeout called 
> Aug-03 18:10:07.198 [JavaFX Application Thread] INFO  i.b.a.BitsquareApp: Log files under: C:\Users\Daniel\AppData\Roaming\Bitsquare\bitsquare 
> Aug-03 18:10:07.201 [JavaFX Application Thread] INFO  i.b.app.Version: Version{VERSION=0.4.9.2, P2P_NETWORK_VERSION=4, LOCAL_DB_VERSION=4, TRADE_PROTOCOL_VERSION=1, BTC_NETWORK_ID=0, getP2PNetworkId()=0} 
> Aug-03 18:10:07.201 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.name: Windows 10 
> Aug-03 18:10:07.201 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.version: 10.0 
> Aug-03 18:10:07.201 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.arch: amd64 
> Aug-03 18:10:07.201 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: sun.arch.data.model: 64 
> Aug-03 18:10:07.201 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JRE: 1.8.0_92-b14 (Oracle Corporation) 
> Aug-03 18:10:07.201 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JVM: 25.92-b14 (Java HotSpot(TM) 64-Bit Server VM)

**Comment by ManfredKarrer** [comment]
Can you try to leave it running a while even the timeout message gets displayed? Sometimes Tor needs longer if u get a bad route.
Do u have another computer where u can try it? Or with another internet connection (mobile hotspot). There might be ISP who block tor, though I am not aware of (as long u are not in China).

**Comment by SeeUnsharp** [comment]
I stared it now and almost immediately got the Windows Firefall popup. After allowing Bitsquare, it is now connected and working.

Yesterday I deleted all Firewall entries about Bitsquare and tried it a few times without success (Also not getting Firefall popup). It just tried to connect till timeout.

I'll try it again tomorrow and report back.

**Comment by ManfredKarrer** [comment]
I close it for now but feel free to re-open if you still have problems.
