### ISSUE TITLE
error occur when making offer 

### ISSUE THREAD

**Issue by Scoop193** [bisq-network/bisq#5654]
#### Version
1.7.2

UUEZRWQM-cc10d08d-b93a-4812-847f-2d6fb201c0d2-171
#### Device or machine
HP 14

windows 10

**Comment by Scoop193** [comment]
![2021-08-05](https://user-images.githubusercontent.com/77167690/128457824-352f29bf-c2d4-4f09-886d-69a60ac9b462.png)

**Comment by Scoop193** [comment]
![2021-08-05 (2)](https://user-images.githubusercontent.com/77167690/128457858-b4d6d90b-0c05-40b4-af9c-7228cf97c255.png)

**Comment by Scoop193** [comment]
![2021-08-05 (1)](https://user-images.githubusercontent.com/77167690/128457886-67292ec7-cb83-47ed-8368-964a54acc060.png)

**Comment by Scoop193** [comment]
this is everything that show up

**Comment by ripcurlx** [comment]
> this is everything that show up

@Scoop193 Could you please join #support channel on Keybase and provide your full log file there so we can have a closer look why the trade contract failed to be created. Thanks!
