### ISSUE TITLE
error when trying to buy an offer

### ISSUE THREAD

**Issue by Scoop193** [bisq-network/bisq#5655]
### Description
An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 695920, myLockTime=697228

#### Version
v1.7.2

#### Device or machine

windows 10 HP

#### Additional info

![2021-08-06](https://user-images.githubusercontent.com/77167690/128555744-703a5188-f450-4e6b-b158-b13c9992baa6.png)
![2021-08-06 (1)](https://user-images.githubusercontent.com/77167690/128555778-5bb7a68e-decd-4151-9d77-1bc19bc0f6a5.png)
![2021-08-06 (2)](https://user-images.githubusercontent.com/77167690/128555794-45fd863b-6dba-4ff0-8dc4-c85a93a142b4.png)

**Comment by ripcurlx** [comment]
This is because the maker of the offer is not in sync with the lastest block. It should fix itself automatically over time.

**Comment by Scoop193** [comment]
ok do I need to resync my bisq

**Comment by ripcurlx** [comment]
> ok do I need to resync my bisq

No it seems to be the opposite. Based on the error message it looks like as if the maker is behind.
