### ISSUE TITLE
Christoph Atteneder's certificate has expired.

### ISSUE THREAD

**Issue by cerko** [bisq-network/bisq#5660]
Christoph Atteneder's certificate has expired, making it impossible to verify his signature in the files of the new v1.7.2 version.

**Comment by ripcurlx** [comment]
The certificate was extended already some time ago. Are you doing manual verification or the automatic verification within the client? If you are using the manual verification you need to import the certificate again from the repository or keyserver the get the updated public key. Please let me know if you still run into any problems after doing this. Thanks!

**Comment by cerko** [comment]
Maybe it is my mistake but:

In     **https://github.com/bisq-network/bisq/releases/tag/v1.7.2** **>> Verification**,    there is the key Url https://bisq.network/pubkey/29CDFD3B.asc which is out of date (?)
