### ISSUE TITLE
Forced to overpay tx fees

### ISSUE THREAD

**Issue by initCCG** [bisq-network/bisq#5662]
### Description

Did not find any voted proposals on minimum custom fee recently. If so, it has been arbitrarily set at 15 sat, which is too high.
Being forced to pay even 2 sats is too high for withdrawals.

Now app seems to force even new offer tx fees too high by failing offer creation with CreateMakerFeeTX error, even after funding TX already confirmed.
Then have to withdraw at 15 sat fee, and waste more sats. 

#### Version

1.7.2
### Steps to reproduce

Create new offer to sell BTC
Fund with 2 sat tx fee from external wallet

### Expected behaviour

Minimum custom fee to fund or withdraw set by the user works as it did in previous versions with 2 sat minimum.

### Actual behaviour

Minimum tx fee errors and failed offer funding.

#### Device or machine

Linux Fedora 33

**Comment by pazza83** [comment]
Thanks for opening the issue.

Just for reference there is no proposal open for reducing fees. Feel free to create one here: https://github.com/bisq-network/proposals/issues

As fees have dropped recently I feel it is a worthy proposal topic.
