### ISSUE TITLE
'Account info' details do not update in offer book when Open Offers are edited

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#5665]
### Description

If a user edits their offers (eg changes payment method) the 'account info' details in offer book is not updated. I have observed this for offers edited when the currency market remains the same.

For example:

User has 2 SEPA accounts.

Account A - aged 3 days
Account B - aged 100 days

User edits offer to sell BTC using account A to account B.

Offer book still shows age of account B.

I have been unable to test if signed status is also affected.

I have also not tested what happens when currency market is changed (I would assume this is unaffected and the problem is related  only to offers on the same offer book).

A restart of Bisq does no fix it for either offer creator or peers.

#### Version

1.7.2

### Steps to reproduce

Create offer with one account, edit the offer to use another account. The account info section in the offer book displays the wrong information. 

### Expected behaviour

Create offer with one account, edit the offer to use another account. The account info section in the offer book should display the the correct information.

**Comment by ghost** [comment]
Duplicate of #5597 / Fixed by #5651
