### ISSUE TITLE
Not receiving confirmation email.

### ISSUE THREAD

**Issue by louisLavery** [bisq-network/bisq#567]
I've been trying to sign up to bitsquare's forum but I'm not receiving the confirmation email I'm supposed to reply to. If I try to log in it recognises the email address but says the password is incorrect, so I ask for a reset but never receive the confirmation email.

**Comment by ManfredKarrer** [comment]
have u checked your spam filter?

**Comment by louisLavery** [comment]
Yes. I've just been fiddling with the setting. I've set the filter low and for it to just mark spam as SPAM. I can see your reply above in my on line web mail box but there's nothing in there from my attempts to sign up, or log on, to bitsquare forum.

**Comment by louisLavery** [comment]
I've now turned the filter off but still nothing's getting through. I'll try again in the morning. Thanks.

**Comment by ManfredKarrer** [comment]
I will do a test sign up to check if the forum has an issue...

**Comment by ManfredKarrer** [comment]
I just tested it with a gmail address and it worked. Though with another email I also did not receive a reply. Will check...

**Comment by ManfredKarrer** [comment]
Was an issue on the mail server. should work again now. Please re-open if u still have issues.

**Comment by louisLavery** [comment]
Nope. Still not working for me. I am unable to reopen the issue as I didn't close it and I'm not a repo collaborator.

**Comment by ManfredKarrer** [comment]
Do you have another email address with which you can try?

**Comment by louisLavery** [comment]
I've just tried my other email address but that doesn't work either. I also tried it yesterday.

I don't know if this will help, but when I tried to sign up I'm pretty sure I didn't get the pass word wrong. I first tried to sign up with my zen email address, but that failed to send a confirmation email and when I tried to log in it said the password didn't match so I tried to reset but again I didn't receive the confirmation email. I tried it all again with my other email address and the same thing happened.   

I've also tried a dummy email and it responds by saying it's not a recognised account, so it's getting that right.

**Comment by louisLavery** [comment]
Today I tried signing up using a throw away email address, that worked fine (I've deleted the account). 

I then tried signing up with another throw away email address only this time I did not reply to the activation email. I then tried to log in. I was then told to reply to the activation email (or click for a new one) - **that did not happen when I originally tried to sign up**, instead it let me enter the password and then told me it did not match.

Am I the only person having this problem? At the moment I have an account (actually 2), cannot access it and cannot reset the password! How about deleting the account(s) and I try again?

**Comment by ManfredKarrer** [comment]
I forwarded it to the admin of the forum. Hope we can resolve that soon.

**Comment by ManfredKarrer** [comment]
@louisLavery Can u send me an email, I will forward u to our forum admin. my email is manfred[at]bitsquare[at]io

**Comment by ManfredKarrer** [comment]
I assume that is resolved, otherwise please re-open.
