### ISSUE TITLE
Snap Package

### ISSUE THREAD

**Issue by ksthiele** [bisq-network/bisq#568]
Offering a snap package of bitsquare would be very nice and would make it compatible to the most important Linux distros.

**Comment by dmp1ce** [comment]
I am working on a Snap package here: https://github.com/dmp1ce/bitsquare-snap

Right now it gets the error `Segmentation fault (core dumped)` but it does build. I'm not sure how to debug the `Segmentation fault (core dumped)` error to see what is wrong with the package.

Here is more information on debugging a Snap package. It may be that the application needs to be modified to work as a Snap. https://developer.ubuntu.com/en/snappy/build-apps/debug/

The core dump on my machine doesn't reveal much information. Here is the core dump:

```
> coredumpctl info -1
           PID: 23710 (java)
           UID: 1000 (dmp1ce)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Thu 2016-09-08 10:38:56 EDT (12min ago)
  Command Line: /snap/bitsquare/x1/usr/lib/jvm/default-java/bin/java -Dsecurity.provider.11=org.bouncycastle.jce.provider.BouncyCastleProvider -jar /snap/bitsquare/x1/gui/shaded.jar
    Executable: /snap/bitsquare/x1/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
 Control Group: /
         Slice: -.slice
       Boot ID: dbc7e03954374d25adc0810dce5ddaa5
    Machine ID: 1e4f9ee982834cb9a8fd87bbe38278eb
      Hostname: samus
      Coredump: /var/lib/systemd/coredump/core.java.1000.dbc7e03954374d25adc0810dce5ddaa5.23710.1473345536000000000000.lz4
       Message: Process 23710 (java) of user 1000 dumped core.

                Stack trace of thread 23731:
                #0  0x00007ff356413754 n/a (/lib/x86_64-linux-gnu/libc-2.23.so)
```

**Comment by dmp1ce** [comment]
I published a Snap which should work. Please send bugs for this Snap my way.

https://github.com/dmp1ce/bisq-snap
https://snapcraft.io/bisq-desktop

**Comment by ghost** [comment]
Hello,
Did you test the install yourself ?
How does it deal with the signatures ?

**Comment by dmp1ce** [comment]
Yes, I tested the install myself.
I'm not sure what you mean by signatures. I just ran `snapcraft` from the git repository I linked to to produce the `.snap` which I published. I think you need to trust both me and the snap repository. It would be a good idea to create an official snap for Bisq if you want it to be more trustworthy.

**Comment by ghost** [comment]
With Debian, the download is provided with signature files, which authenticates the provenance.
I just wanted to know if snap provides also such authentification mechanism.
Anyway, thanks for your efforts.

**Comment by dmp1ce** [comment]
I was trying to figure that out myself but I couldn't find an authentication mechanism.

**Comment by dmp1ce** [comment]
I created a Snap here: https://snapcraft.io/bisq-desktop. Perhaps the code could be added to this repository and the Snap could be made official.

**Comment by ghost** [comment]
@dmp1ce 
Thanks for your efforts, but, concerning this kind of software, without a proper authentification mechanism, I don't see how this could be made official.
I doubt Bisq contributors are willing to take such a risk.
Plus that for the last releases, the official download page supports now more Linux distros.

Anyway, I feel that such a decision should probably be a proposal at first -> https://github.com/bisq-network/proposals

**Comment by dmp1ce** [comment]
Soon Snapcraft.io will fetch source from Github and build the Snap from the information in the `snapcraft.yaml` file. They will authenticate that they pulled the source and built the binary. Would the be sufficient authentication? I'll create a pull request once I know it is working.

**Comment by ghost** [comment]
if the described mechanism can be considered as _sufficient authentication_ is a question of personal feeling imo. And I'm certainly not in situation to decide that for Bisq.
It's either the founders who decide, either a collective decision following a proposal.

I wonder however, what are the Linux distros which would benefit from having such a snap package which are not already addressed by Bisq's real **official** download page ?
(If there are none, then what is Bisq's interest on having such supplementary download page on which Bisq has not plain control ?)

Such questions would not arise if we speak about ordinary software. But here it concerns wallet software, imo it's no the same story.

**Comment by dmp1ce** [comment]
The Snapcraft Store claims it serves 41 Linux distributions. I only see `.deb` on the official download page which only directly serves Debian based distributions. Ubuntu, arguably the most popular Linux distribution, is moving towards Snaps as a way of distributing end user applications.

My reason for creating the Snap is not to allow Linux distributions to use Bisq but to better market Bisq and make it easier to get Bisq installed. All Linux distributions could build Bisq from source if the user is so inclined.

**Comment by dmp1ce** [comment]
I added a pull request which builds a snap for version 0.9.3. Adding the code to this repository should allow this Github repository to be linked to the Snapcraft store which will automatically try to build the Bisq Snap.
