### ISSUE TITLE
Cannot migrate to Tor v3: No hiddenservices folder to delete in ~/Library/Application Support/Bisq

### ISSUE THREAD

**Issue by Piste** [bisq-network/bisq#5684]
Hello friends!
I couldn't find anything relevant in the log file.
Let me know how I can help you troubleshoot.

**Comment by pazza83** [comment]
Hi @Piste what operating system are you using?

**Comment by Piste** [comment]
This is on macOS. Thank you for your attention to this.

**Comment by pazza83** [comment]
Can you see your hidden service folder here:  /Applications/Bisq.app/Contents/MacOS/Bisq/btc_mainnet/tor/hiddenservice

Also see the wiki: https://bisq.wiki/Changing_your_onion_address

There is also a video about updating your Tor address here: https://www.youtube.com/watch?v=s7Zb3mY1y9U

**Comment by Piste** [comment]
in `/Applications/Bisq.app/Contents/MacOS/` there is only a `Bisq` executable.
the wiki you point to says I should delete the `hiddenservice` folder I cannot find.
the video also says to delete the `hiddenservice` folder I cannot find.
Any other idea?

**Comment by ripcurlx** [comment]
> in `/Applications/Bisq.app/Contents/MacOS/` there is only a `Bisq` executable.
> the wiki you point to says I should delete the `hiddenservice` folder I cannot find.
> the video also says to delete the `hiddenservice` folder I cannot find.
> Any other idea?

You find your application folder (which contains the hiddenservice folder) on macOS under `~/Library/Application\ Support/Bisq/btc_mainnet/tor/hiddenservice/`

**Comment by Piste** [comment]
That did it. Thank you for your help, @pazza83 and @ripcurlx!
