### ISSUE TITLE
japanese.validation.regex should accept U+3007

### ISSUE THREAD

**Issue by Liisachan** [bisq-network/bisq#5688]
### Description
`JapanBankData.getString("japanese.validation.regex")` only lets kanji/kana pass. As a kanji, currently `U+4E00`  … `U+9FAF` will be seen as valid (according to `JapanBankData.java`), which may be practically good enough. However, there is one special character out of the above range that should be also accepted. Namely:

`U+3007` [ 〇 ] IDEOGRAPHIC NUMBER ZERO

This letter (the kanji version of number 0) is used in many branch names of a specific Japanese bank. Thus one should add the following to that RegEx:

"〇" + // IDEOGRAPHIC NUMBER ZERO (0x3007)

#### Version
1.7.3

### Steps to reproduce
As a test, try to input a random (hypothetical) Japanese Bank account info, with a branch name e.g. "〇一二". This branch name is well-formed but will be refused with an error message.

**Comment by Liisachan** [comment]
Additional info:
`U+3005` [ 々 ] IDEOGRAPHIC ITERATION MARK
is also commonly used as part of various kanji names, e.g. https://en.wikipedia.org/wiki/Yoyogi 
(代々木).

**Comment by ripcurlx** [comment]
@wiz Do you want to/can take this one?

**Comment by Liisachan** [comment]
I'd love to but I'm new to git/github/etc. and this will be a minor change.
For now, will you just add 2 lines for me? I can test the result when ready:

[tmp.diff.txt](https://github.com/bisq-network/bisq/files/7153526/tmp.diff.txt)

**Comment by ripcurlx** [comment]
@Liisachan It is never too late to start OS contributing: https://github.com/bisq-network/bisq/pull/5694
Let me know if that works for you now in the PR.

**Comment by Liisachan** [comment]
@ripcurlx Yeah, you're right. I wish I had more time. The code change itself is looking good. While double-checking I noticed some other unimportant issues around there, though everything works fine as-is.
1) These two lines are almost identical and so mostly redundant:
`"ぁ-ゔ" + // full-width hiragana (0x3041 ~ 0x3094)`
`"ぁ-ゞ" + // half-width hiragana` (0x3041 ~ 0x309e)
One could simplify the above two lines as one line:
`"ぁ-ゞ" + // hiragana (0x3041 ~ 0x309e)`
Note, Unicode hiragana is always full-width, there's no "half-width hiragana" afaik.

2) The comment is incorrect in this line, which includes 5 code points, not 4:
`"ヽヾ゛゜ー" + // 0x309e, 0x309b, 0x309c, 0x30fc`
The first two code points are:
U+30FD [ ヽ ] KATAKANA ITERATION MARK
U+30FE [ ヾ ] KATAKANA VOICED ITERATION MARK
So you can change `0x309e` to `0x30fd, 0x30fe`. The other three (`0x309b, 0x309c, 0x30fc`) are fine as-is.

**Comment by wiz** [comment]
Thanks for reporting this! Sure, I can make the change

**Comment by ripcurlx** [comment]
> Thanks for reporting this! Sure, I can make the change

I'm already on it 😄  ->  https://github.com/bisq-network/bisq/pull/5694

**Comment by ripcurlx** [comment]
> @ripcurlx Yeah, you're right. I wish I had more time. The code change itself is looking good. While double-checking I noticed some other unimportant issues around there, though everything works fine as-is.
> 
> 1. These two lines are almost identical and so mostly redundant:
>    `"ぁ-ゔ" + // full-width hiragana (0x3041 ~ 0x3094)`
>    `"ぁ-ゞ" + // half-width hiragana` (0x3041 ~ 0x309e)
>    One could simplify the above two lines as one line:
>    `"ぁ-ゞ" + // hiragana (0x3041 ~ 0x309e)`
>    Note, Unicode hiragana is always full-width, there's no "half-width hiragana" afaik.
> 2. The comment is incorrect in this line, which includes 5 code points, not 4:
>    `"ヽヾ゛゜ー" + // 0x309e, 0x309b, 0x309c, 0x30fc`
>    The first two code points are:
>    U+30FD [ ヽ ] KATAKANA ITERATION MARK
>    U+30FE [ ヾ ] KATAKANA VOICED ITERATION MARK
>    So you can change `0x309e` to `0x30fd, 0x30fe`. The other three (`0x309b, 0x309c, 0x30fc`) are fine as-is.

Just pushed the changes. Could you please have a look at it and utACK or ACK the PR in a comment? Thanks!
