### ISSUE TITLE
Pls see attaced

### ISSUE THREAD

**Issue by happygit4712** [bisq-network/bisq#5689]
[

#### Additional info

No error but dialogue box asked that I make a report.

**Comment by happygit4712** [comment]
I am sorry I could not give more information.  It is the first time that I have made such a report.   There is not issue with my wallet from what I can see, so I need no further update.  

In the event of further issues, I will capture a screenshot of the dialogue box.  sorry.

**Comment by ripcurlx** [comment]
@happygit4712 If you don't have the screenshot at hand anymore you can always open the log file and search for this exception. So to do further investigation we'd need the log file.
