### ISSUE TITLE
sun.awt.image.BufImgSurfaceData cannot be cast to sun.java2d.xr.XRSurfaceData

### ISSUE THREAD

**Issue by nikolajsheller** [bisq-network/bisq#569]
After disconnecting and reconnecting an external screen, I received the error in the title.

**Comment by ManfredKarrer** [comment]
Yes that is a known JDK bug. It should be fixed in the next JDK version. Will close it for now as there are no plans (possibilities) to fix that earlier. After a restart all should be ok again.
