### ISSUE TITLE
Not possible to modify accepted countries 

### ISSUE THREAD

**Issue by Bl5ckj5ck** [bisq-network/bisq#5692]
### Description

Hey guys👋 I’ve noticed that once I create a payment method (bank transfer) I can’t then modify the list of accepted countries other than by deleting it.  

#### Version

 1.7.3

### Steps to reproduce

Create a payment method which involves bank transfers (like SEPA)

### Idea

Of course there are some important info defining the details of the payment method that should not be changed in order to prevent the workaround of the “account signing” functionality. Indeed, this avoids that a user could wait for the signing of a payment method and then change its info.

However, I think that the the modification of the “accepted countries” field does not pose a risk in this sense. Thus, what about adding an option to modify this field so that there’s not need delete and recreate the payment method?

This would allow users to change their preferences in case they want to limit/change countries from which they can receive payments.

Hope you find this idea helpful. Please let me know what you think about it

**Comment by pazza83** [comment]
Thanks @Bl5ckj5ck 

I agree with your suggestion.

Also think users should be able to change the "Account Name" the one shown locally as their own account name in Bisq as this also posing no risk as it is not shared with other traders.

**Comment by pazza83** [comment]
Also recently a [few extra SEPA countries / IBANs were added](https://github.com/bisq-network/growth/issues/209) but it is not backwards compatible so allowing users to add in the new countries would be good.

**Comment by pazza83** [comment]
Hi @xyzmaker123 is this something you could look into?

**Comment by ghost** [comment]
@pazza83 How it should be solved from UI/UX perspective? Should we add some "Save changes" button?

**Comment by pazza83** [comment]
Yes a save changes button would be good

**Comment by Bl5ckj5ck** [comment]
Any update on this @xyzmaker123 ?
@pazza83

**Comment by ghost** [comment]
@Bl5ckj5ck I'm planning to work on it now
