### ISSUE TITLE
Cannot accept agreement on Chromebook installed with .deb

### ISSUE THREAD

**Issue by dmp1ce** [bisq-network/bisq#5693]
### Description

Installing a .deb on a Chromebook in the Linux container. I can start the application but cannot accept the agreement.

If I start from the cli then it works fine! There must be something wrong with the desktop launcher process for Chromebooks.

#### Version

v1.7.3

### Steps to reproduce

Install Bisq on Chromebook with .deb. Start Bisq with GUI launcher.

### Expected behaviour

The GUI would be responsive enough for me to accept agreement when starting with Chromebook GUI launcher.

### Actual behaviour

I cannot click on the "I agree" button.

### Screenshots

![Screenshot 2021-09-12 10 08 33 AM](https://user-images.githubusercontent.com/58784/132990935-08734acd-a61c-4643-b03b-3e0751879c24.png)

#### Device or machine

Google Pixelbook

**Comment by dmp1ce** [comment]
Update! I started from the terminal using `/opt/bisq/bin/Bisq` and I was able to accept fine. So, it is something to do with starting Bisq with the desktop launcher.

**Comment by ripcurlx** [comment]
@dmp1ce Could you please provide the exact version of your Chromebook so we can try to find other users to confirm this issue? Thanks!

**Comment by dmp1ce** [comment]
`Version 92.0.4515.162 (Offical Build) (64-bit)`

I'm not sure what the hardware is exactly. It is a Google Pixelbook.
