### ISSUE TITLE
No seed nodes available

### ISSUE THREAD

**Issue by StefekVUT** [bisq-network/bisq#5697]
### Description

During bisq startup bisq does not receive filter object from seed nodes. No offers arevisible, no connection to bisq network is created. Connection to bitcoin core via tor is succesfull. Mempool is synchronised.

Restoration of old user data did not helped.
Reinstall did not helped.

#### Version

v1.7.3

### Steps to reproduce

Just start the bisq, issue persist

### Expected behaviour

bisq/dao network is connected and synchronised

### Actual behaviour

bisq dao connection is not established. no offers visible

### Screenshots

![image](https://user-images.githubusercontent.com/16528492/133659611-73ff49d2-2b85-49c8-bc3f-49ed0ca42624.png)

![image](https://user-images.githubusercontent.com/16528492/133659684-12f73eef-e355-4337-8754-e897c1070d8c.png)

![no connection to bisq network](https://user-images.githubusercontent.com/16528492/133659720-bf02af98-27c0-4707-9a53-8ff7f08d3a3e.PNG)

#### Device or machine

dell lattitude 5420,
Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎7/‎8/‎2021
OS build	19042.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0

#### Additional info
[bisq_bug_report.txt](https://github.com/bisq-network/bisq/files/7179935/bisq_bug_report.txt)

**Comment by ripcurlx** [comment]
This looks weird indeed. You seem to be able to publish your Tor v3 hidden service address to the network and connect to Tor v2 BTC core nodes. Do you have some special Tor configuration on your system?
