### ISSUE TITLE
Notifications not working, no option to sync

### ISSUE THREAD

**Issue by macmiller** [bisq-network/bisq#5698]
### Description
There are two related issues with Notifications.
1.)  When I go to the Account / Notifications tab there is no option to sync and read barcode.  I have the mobile app ready on the phone to pair but the option to synch desktop is not there.  
2.)  Getting a 'no web cam' email link and then specifying it in the 'Enter pairing token you received by email'.  Here nothing else happens once the code is pasted in there.  There is no confirm button and no action is performed on the code.  

#### Version

1.7.3

### Steps to reproduce

see 1. and 2 above.

### Expected behaviour

1.)  There is a option on the screen to activate webcam to scan bar code.
2.)  Once pairing token is filled in there is an option to commit and utilize the token.  

### Actual behaviour

1.)  No option.  
2.)  Nothing happens.

### Screenshots
![210917_Account_Notifications tab no option](https://user-images.githubusercontent.com/7886587/133717104-7c4b3d93-7ef5-4bb7-bd0f-218e25f127b8.JPG)

#### Device or machine

Windows 10 desktop.

**Comment by macmiller** [comment]
[reddit thread](https://www.reddit.com/r/bisq/comments/ppa0y3/notifications_dont_seem_to_be_working/)  As I reported on the reddit thread, I now see that if the entire pairing token is entered then the behavior is as expected.  Option 1. above is still valid, there should be a link to read the bar code.  Also please add under option 2 an enhancement request to check and see if the pairing token is valid and give an error if not.

**Comment by ripcurlx** [comment]
The bar code reader was temporarily removed as it failed the Apple notarization process as the library is not maintained anymore. We need to come up with a light weight replacement for enabling bar code reading again.
