### ISSUE TITLE
Bitsquare is already running. You cannot run 2 instances of Bitsquare

### ISSUE THREAD

**Issue by AndreKoster** [bisq-network/bisq#570]
After a crash of my laptop, while Bitsquare was running, I get this error at startup: "Bitsquare is already running. You cannot run 2 instances of Bitsquare".

I looked for any lock files, and found one in AppData\Roaming\Bitsquare\mainnet\tor, named "lock". I tried to start without this file, but with the same result.

I had a trade open, and two offers. I have a backup. However, it's a week old from before the open trades and offers.

Please advise how to resolve this.

**Comment by AndreKoster** [comment]
p.s. Running the latest version of Bitsquare, on Windows 7 64 bit.

**Comment by ManfredKarrer** [comment]
hi @AndreKoster, seems the wallet file got corrupted by the crash. Go to the data dir inside the bitcoin dir there is a backup folder. use one of the latest before the crash and replace the Bitsquare.wallet (rename the backup file). do a backup for all before any changes. if it does nto help u can send me the data dir by email.

**Comment by AndreKoster** [comment]
It didn't help. I'll send you the data dir.

**Comment by AndreKoster** [comment]
data dir sent to your .io email.

**Comment by AndreKoster** [comment]
As Manfred found out, it was the Bitsquare.spvchain file that got corrupted. The issue could be resolved simply by deleting it.

Thank you Manfred for helping me out.
