### ISSUE TITLE
Bitsquare Icon Missing on compiled release

### ISSUE THREAD

**Issue by SMH17** [bisq-network/bisq#572]
The latest windows releases have no more Bitsquare icon (there is the default Java icon). 
Not a real problem for advanced users, but would be nice include the official icon with the compiled release on the website.

**Comment by ManfredKarrer** [comment]
What the latest 0.4.9.2 showing hte icon? Will check...

**Comment by SMH17** [comment]
Updated to latest 0.4.9.5 still default java coffee cup, no Bitsquare icon

**Comment by haiqu** [comment]
Not seeing the issue with 0.4.9.6 and only one problem report on the issue - close?

**Comment by SMH17** [comment]
In 0.9.6 the program shows the right icon when opened, but still Java default Icon in both Start Menu link and Setup installer. (I have tried x64 version)

**Comment by haiqu** [comment]
No problem here but I'm in Win 32-bit and have no way to test 64-bit. I'll let Manfred take this one on.

**Comment by ManfredKarrer** [comment]
Yes seems some strange win64 build issue.

**Comment by haiqu** [comment]
Check this for me: look in `C:\Users\<your name>\AppData\Local\Bitsquare` and see if the file Bitsquare.ico exists. You'll have to make the AppData directory visible first.

**Comment by SMH17** [comment]
@haiqu The icon file  "Bitsquare.ico" exists but is the Java default icon, not Bitsquare icon

**Comment by haiqu** [comment]
Hmmmm, OK. It's definitely correct in the repository. Must be in Manfred's build setup.

**Comment by ManfredKarrer** [comment]
Will give a bounty to the one who fix that issue for WIn32 and Win64 build scripts (get in touch to negotiate amount). The existing scripts in package/windows should not be altered too much.

**Comment by SMH17** [comment]
Looking `64build.bat` I have found an issue with the way how the path is written
eg
`-Bicon=package/windows/Bitsquare.ico`
must be replaced with
`-Bicon=package\windows\Bitsquare.ico`

assuming that root of the path is correctly configured, otherwise you can try to place the icon in `%outdir%`
and write

`-Bicon=%outdir%\Bitsquare.ico`

My Bitcoin Address: 1LfKiPgCeEz9UnoZsYRADgBEFxk2D1Xte3

**Comment by ManfredKarrer** [comment]
Ah thanks, on win32 I fixed it, forgot on the other build. But on win32 the icon is also missing and I built with the right separators.
Maybe it is an issue with the path. It was working on older version though, and I am not really aware of a change here...
%outdir% is not a good place to put the icon as that need to be checked in.
I am pretty sure the separator is not sufficient for fixing the problem. I will check next time I do a build but as said Win32 has the same issues and there the separator was correct.

**Comment by haiqu** [comment]
OK, in 4.9.9.1 64-bit this is still an issue. I downloaded the correct icon and over-wrote the one that came with the package and this fixed the error. I have no idea why the wrong icon is being installed.

**Comment by ManfredKarrer** [comment]
Some issue in the build setup (wrong path or such BS)...

**Comment by SMH17** [comment]
I have updated Bitsquare today but the issue is still present.

In `package\windows\Bitsquare.iss` file try to replace

`SetupIconFile=Bitsquare\Bitsquare.ico`

with

`SetupIconFile={app}\Bitsquare.ico`

**Comment by SMH17** [comment]
the lines 
```
SetupIconFile={localappdata}\Bisq.ico 
UninstallDisplayIcon={localappdata}\Bisq.ico 
```
are wrong, Bisq folder is located in {localappdata} and the icons are inside Bisq\ path so a more coherent change would be 
```
SetupIconFile={localappdata}\Bisq\Bisq.ico 
UninstallDisplayIcon={localappdata}\Bisq\Bisq.ico 
```

but even this would be wrong since `SetupIconFile `directive as it is used on compile time only and should contain the absolute path to the icon

proposed change:
https://github.com/bitsquare/bitsquare/compare/master...SMH17:patch-2

**Comment by ManfredKarrer** [comment]
Thanks! I merged into dev branch and test with next release.

**Comment by SMH17** [comment]
@ManfredKarrer 
I have noticed that even  `WizardSmallImageFile={localappdata}\Bisq-setup-icon.bmp `
has the same problem this must be addressed in the same way
sorry for the double pull 
https://github.com/bitsquare/bitsquare/compare/master...SMH17:patch-3

**Comment by SMH17** [comment]
I have seen that unfortunately  the bug isn't completely fixed even in latest 0.6.0 (that however shows right uninstall icon now and right top bar icon). 
So the problem depends (also) on your build path, please at the line 
`SetupIconFile=Bisq.ico `
in `bisq.iss` add the absolute path of the `Bisq.ico`

**Comment by ManfredKarrer** [comment]
Yes I have seen as well.
SetupIconFile={app}\Bisq.ico should do it. There will be a new release anyways very soon. Hope that it works then... 
Thanks!

**Comment by SMH17** [comment]
@ManfredKarrer` {app}\` doesn't work for `SetupIconFile ` attribute, since this attribute is evaluated at compile time, you have to use the explicit path. You can use `{app}\` for `UninstallDisplayIcon `because is evaluated at runtime.

**Comment by ManfredKarrer** [comment]
Oh damn, then it was wrong again. Next release....

**Comment by ManfredKarrer** [comment]
Hope that will work now: https://github.com/bisq-network/exchange/commit/02a5b1386ddc5422652d7b9bfa85b94cf1d1d3eb

**Comment by ghost** [comment]
Still here, also related to https://github.com/bisq-network/bisq-desktop/issues/1040

**Comment by devinbileck** [comment]
@ripcurlx This can be closed now.

**Comment by ripcurlx** [comment]
Closing as complete.
