### ISSUE TITLE
payment.amazonGiftCard.info = Inconsistent with wiki about Message Field

### ISSUE THREAD

**Issue by Liisachan** [bisq-network/bisq#5726]
### Description

In `\core\src\main\resources\i18n\displayStrings.properties` (and its translations), `payment.amazonGiftCard.info` states: “you must **include the trade ID** in the gift card''s message field. Please see the wiki”.

In https://bisq.wiki/Amazon_eGift_card#Step_2._Customize_eGift_card however, it is said that the Message field **should be left blank**.

This can confuse the user as to whether or not they should include the trade ID there. Maybe writing the ID there is usually not necessary nor desirable...?

It's not really a bug - more like a documentation issue.

#### Version
v1.7.3

**Comment by pazza83** [comment]
I removed the reference from the image. 

I cannot find any other reference to trade ID on the page.

Let me know if I have missed anything.

**Comment by Liisachan** [comment]
Sorry if I was not clear. I'm talking about source code:
https://github.com/bisq-network/bisq/blob/484998815c7e15d32b5845e53c907289eee974e3/core/src/main/resources/i18n/displayStrings.properties#L3542

**Comment by pazza83** [comment]
Hi @m52go are you able to remove this from Bisq source code?

**Comment by Liisachan** [comment]
Maybe not just removing, but explicitly advising the user not to say anything about btc there? While sending a gift card to your friend is perfectly legal, commonly done by millions of amazon users,  it may be safer to keep a low profile to avoid unwanted attentions...?

**Comment by ripcurlx** [comment]
> Maybe not just removing, but explicitly advising the user not to say anything about btc there? While sending a gift card to your friend is perfectly legal, commonly done by millions of amazon users, it may be safer to keep a low profile to avoid unwanted attentions...?

Good catch! I think just removing the trade id reference should be fine as during the trade this is mentioned explicitly anyways. 

https://github.com/bisq-network/bisq/blob/484998815c7e15d32b5845e53c907289eee974e3/core/src/main/resources/i18n/displayStrings.properties#L657-L659

**Comment by ripcurlx** [comment]
I just checked the remaining payment methods and only found it for halcash which is fine as there it is sent via text message.
