### ISSUE TITLE
Fix layout/text issues in Community screen

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#5732]
The new community screen has some layout as well as small text issues.

Text:
- "We are interested in helping make Bisq better, we'd love to hear from you!" shouldn't that be "If you are interested in helping make Bisq better, we'd love to hear from you!"
- Matrix link is not working for me

Layout:
- The text "Keybase and Github are the top two platforms..." is truncated. Need to be a mulitline textfield instead of a label.
- Some logos are distorted (GH, keybase, freenode,...). 
- I think a grid layout with fixed width for the boxes would be better. Now it looks somehow irregular, different width, different number of columns.

I am not sure the copy URL link is needed as the link will only open a browser if the user has agreed to that at first time opening a URL. So the protection to not open a webbrowser if not wanted is already built in in the generic URL handling. 

Beside all that I am not sure if the added value justifies an additional main menu item. The menu gets more overloaded and I think the content could be added to support as well. A dropdown menu for support with the most important links might be another option. Bisq is already very content and text heavy, adding more does not add value IMO. 

As it is now, I would recommend to revert the merge and consider more though on UX first how to add the content best. 
 
<img width="1218" alt="Screen Shot 2021-09-28 at 16 28 57" src="https://user-images.githubusercontent.com/54558767/135107532-d1436068-a9e5-4443-8759-133389d939d9.png">

**Comment by m52go** [comment]
Couple more items:
- Bisq markets link is wrong
- text throughout is questionable

Can the main links at the top be symbols? Maybe "settings" could be turned into a [cog](https://forkaweso.me/Fork-Awesome/icon/cog/) and community could get [its own icon](https://forkaweso.me/Fork-Awesome/icon/users/) too. Otherwise yeah I agree the top menu is kind of crowded as-is.

Matrix link seems to work for me.

**Comment by ghost** [comment]
1) I agree that this view is not good candidate to be placed in top menu. Where to move it - Support or maybe Settings?
2) I see there is also Settings -> About tab that contains a few links - probably we should consider removing them to avoid duplication? 
3) @ripcurlx How much I'll be able to request in compensation if this view will be finally implemented and approved? 
4) Can I treat requests from @chimp1984 (text updates, grid layout changes) as final? I don't want to spent my time on it, and then someone finally say that we actually don't want this view :)
5) Is it possible to reopen original issue and keep whole conversation there?

**Comment by chimp1984** [comment]
@xyzmaker123 I would not continue on fixing that screen but rather work on an alternative approach. 
A UX dev working on that should make a proposal how to integrate the content in the best way and then make a estimation about the costs. The result is to be expected to not have tons of review issues and no major flaws (everyone make mistakes but that screen contained too many trivial ones for my taste).

**Comment by ghost** [comment]
@chimp1984 Please don't put too much blame on me. I agree I did a few stupid mistakes, but I thought general idea of this tab was already accepted [on issue](https://github.com/bisq-network/bisq/issues/4904#issuecomment-824404569) - including top menu placement, irregular columns and messages.

If it was not accepted - with whom I should talk before start working on an issue?

**Comment by chimp1984** [comment]
The https://github.com/bisq-network/bisq/issues/4904#issuecomment-824404569 has a grid for the items below the first row with same width. Anyway, we don't need to discuss that further....

**Comment by chimp1984** [comment]
I close that here as I think the solution should be reconsidered and best discussed in the issue.
