### ISSUE TITLE
Why does mediation chat has a blue background?

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#5733]
Why does mediation chat has a blue background?
The color does not match at all to Bisq CI and it is not clear to me what is the meaning/benefit.

<img width="789" alt="Screen Shot 2021-09-28 at 17 04 05" src="https://user-images.githubusercontent.com/54558767/135113913-7c4fa29e-20eb-450c-bdd1-80b6f04c3045.png">

**Comment by pazza83** [comment]
I agree it does not look in keeping with the brand. 

I seem to remember it was requested as a way to differentiate trader and mediator chat but I cannot find any reference in the GitHub issues.

**Comment by Conza88** [comment]
I do think it was something like Pazza mentioned. Differentiation
