### ISSUE TITLE
Exception message: Not able to find peers witness, unable to sign for trade

### ISSUE THREAD

**Issue by slipperybeluga** [bisq-network/bisq#5744]
This is a new ticket for a [closed issue from 2020.](https://github.com/bisq-network/bisq/issues/4065) I haven't used Bisq in months, so I had to install the latest version 1.7.4 and delete my hiddenservice folder to support v3 nodes. Unsure if that is relevant. 

Here is the error message that occurs when I click "confirm payment receipt":
**An error occurred at task: SellerSendPayoutTxPublishedMessage
Exception message: Not able to find peers witness, unable to sign for trade {} [Trade{**

While I am unable to click the "confirm payment receipt" button to close the transaction, both parties have received their deposits back and the buyer has gotten their BTC. The transaction still appears open in Bisq.

I have more complete logs I can send if helpful. I do not want to post them here.

**Comment by ghost** [comment]
> While I am unable to click the "confirm payment receipt" button to close the transaction, both parties have received their deposits back and the buyer has gotten their BTC. The transaction still appears open in Bisq.

The trade has completed but still shows up in your open trades list.

The following advice involves clearing the data structure which keeps track of open trades.  This is only applicable in extreme circumstances when the normal flow of operations did not happen, as is the case here.  As always, [make a backup](https://bisq.wiki/Backing_up_application_data) first.

[Prerequisite: you must have no other open trades, as all current open trades will be removed.  If you have other open trades, do not continue until they have all completed].  

To remove the open trades, close down Bisq then delete the file `PendingTrades` file from the `db` folder within the [data directory](https://bisq.wiki/Data_directory).

**Comment by slipperybeluga** [comment]
> > While I am unable to click the "confirm payment receipt" button to close the transaction, both parties have received their deposits back and the buyer has gotten their BTC. The transaction still appears open in Bisq.
> 
> The trade has completed but still shows up in your open trades list.
> 
> The following advice involves clearing the data structure which keeps track of open trades. This is only applicable in extreme circumstances when the normal flow of operations did not happen, as is the case here. As always, [make a backup](https://bisq.wiki/Backing_up_application_data) first.
> 
> [Prerequisite: you must have no other open trades, as all current open trades will be removed. If you have other open trades, do not continue until they have all completed].
> 
> To remove the open trades, close down Bisq then delete the file `PendingTrades` file from the `db` folder within the [data directory](https://bisq.wiki/Data_directory).

Deletion of PendingTrades db file has resolved the issue. Thank you.
