### ISSUE TITLE
Feature Request: Automatic update of client app

### ISSUE THREAD

**Issue by jeroenvanagt** [bisq-network/bisq#575]
It would be nice to be able to upgrade the client app  to the newest version with a press of a button (after a notification when a new version is available). The user can either skip the new version or install it. Suggestion: In the menu is always an option to upgrade to the newest version.

**Comment by ManfredKarrer** [comment]
Good idea. I would like to add an auto-update but it takes a bit of effort and I don't have time for that yet. I will add a bounty for it.

**Comment by haiqu** [comment]
This could be a source of security leak for someone trying to trace the whole network. Update via Tor in a way similar to bittorrent would be excellent. It also needs to be OFF by default, for those of us who are on low bandwidth connections or working on the code.
