### ISSUE TITLE
Fee reimbursement for Failed trade 23773143 

### ISSUE THREAD

**Issue by A-Simon** [bisq-network/bisq#5754]
Maker: 3968db85d14a1e98d6781233b1960d1a8263c64c94431f419ca6f1b4cff90098
Taker: N/A
Deposit: N/A

Bisq version: v1.7.4
BTC address for reimbursement: bc1qurt78pf637r69d8pke68kc7mumw0zn2lqkny0e

Other notes:

The trade protocol encountered some problems.
The trade contract is not set.

Received a failed trade error as soon as I funded my wallet. Attempted to move from failed trades back to active for mediation to receive deposit back but was unsuccessful. 

https://mempool.space/address/bc1qd2aqjvwhl3gzqnc49ee8g8jaj3j8tnewtr2g6qaefdz8sng448hsrj0xh8
https://mempool.space/tx/ec198d87377eedb53db3db11ff7297bbccb8ed1485961cb9f1d83cd8804ffd4b

I posted a week ago [here](https://github.com/bisq-network/support/issues/1009) - Original date of the trade was 9/28

Screenshots:

<img width="901" alt="Screen Shot 2021-09-28 at 5 56 49 PM" src="https://user-images.githubusercontent.com/46980254/137371399-2e1e31b7-709a-489b-9a62-ac160967d913.png">
<img width="826" alt="screenshot 2" src="https://user-images.githubusercontent.com/46980254/137371489-2264c74d-5476-4e51-8119-80b1636a8ce8.png">
<img width="814" alt="Screen Shot 2021-09-28 at 5 53 13 PM" src="https://user-images.githubusercontent.com/46980254/137371526-d1870f45-9ff6-4411-9964-a6d1ad15c508.png">

**Comment by pazza83** [comment]
Hi @A-Simon thanks for raising the issue.

As you were the taker for this trade you have not lost any fees.

No taker transaction took place.
