### ISSUE TITLE
How to remove offer before recreating wallet in case of forgotten password

### ISSUE THREAD

**Issue by AndreKoster** [bisq-network/bisq#577]
Hi,

Today I helped a friend install Bitsquare and create an offer. I also made him write down the seed and make a backup. When retrieving the seed he used the password.

Later today he wanted to start Bitsquare again, and it turned out his password was incorrect. So he used the "Forgot password" option. He entered the seed and creation date. Then the application gives a warning "You must empty the wallet first.... Please finalise your trades and close all your open offers.... In case you cannot access your bitcoin you can use the emergency tool to empty the wallet... To open press cmd + e".

Since he has an open offer, he should close that first (at least, that how this instruction sounds), but he can't, because he can't get access without the correct password. It may refer to the situation where one tries to restore a DIFFERENT wallet (not the case here), but I'm not sure if that interpretation is correct.

Secondly, typing cmd + e (for opening the emergency tool) doesn't do anything.

Thirdly, there's no way to exit this dialog. Basically, the only way out is to restore the wallet despite the warning, or kill the application. Opting for "I will empty my wallet first" brings your back to the previous dialog.

How to proceed?

![bitsquare-error](https://cloud.githubusercontent.com/assets/18371058/17568455/1c9993c6-5f44-11e6-8f5f-c5ca3a6994df.png)

Best regards,
André

**Comment by ManfredKarrer** [comment]
As the wallet is the same he can use I wan tot restore anyway. He should make a backup before that though, just in case.

**Comment by AndreKoster** [comment]
Thanks! (BTW, he solved the password mystery. Turned out he had his capslock during the first session...)

Final remark: the warning about "emptying the wallet first" could be more clear that it only applies when a different wallet is restored.

**Comment by ManfredKarrer** [comment]
Yes I will improve the text.
