### ISSUE TITLE
Cannot Confirm Payment Received

### ISSUE THREAD

**Issue by tut4499** [bisq-network/bisq#5772]
I am unable to confirm received SEPA payment.

Version 1.7.4

Does not show 
"Your trading account"
"Buyer account data"

Cannot invoke "bisq.core.payment.payload.PaymentAccountPayload.getAgeWitnessInputData()" because "paymentAccountPayload" is null

[bisq.log](https://github.com/bisq-network/bisq/files/7386776/bisq.log)

**Comment by ghost** [comment]
Unfortunately that logfile does not go back far enough to show why paymentAccountPayload was missing.  Could you arrange to send the older log files to your mediator so this can be investigated?  Thanks.

**Comment by tut4499** [comment]
How to export them? So i should contact the mediator now yes?

**Comment by ghost** [comment]
Yes, contact the mediator (ctrl-o).  Log files are located in the data directory, see https://bisq.wiki/Data_directory

**Comment by tut4499** [comment]
Impossible to attach bigger files to mediator over 200kb.

**Comment by ghost** [comment]
Your mediator can advise you on how to transfer the files.  Also https://bisq.wiki/User_support#Via_Keybase_chat
