### ISSUE TITLE
Trigger price doesn't automatically reactivate offer after price falls below threshold

### ISSUE THREAD

**Issue by RequestPrivacy** [bisq-network/bisq#5773]
### Description

If a Trigger price above the current price level is set and the price moves above, but comes back down after some time, the offer remains inactive and isn't reactivated.

#### Version

Bisq v1.7.4

### Steps to reproduce

- Make an offer to buy Bitcoin
- Set trigger price above current price level
- Check that offer is active
- Wait until price rises above said level 
- Observe how trigger sets offer inactive

(_If price comes back down_)

- Offer remains inactive

### Expected behaviour

Automatic reactivation of the offer after price falls below Trigger price level.

**Comment by Conza88** [comment]
Yeah dang, should certainly do that.
