### ISSUE TITLE
Make clone offer feature more visible

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#5774]
The right click funtionality for cloning an existing offer is not very obvious to find. I think an additional icon in the open offer view next to edit would be better.

**Comment by Conza88** [comment]
Indeed.

**Comment by pazza83** [comment]
It would also be a great addition to clone your existing offers from the 'offer book'.

Right click offer, or click associated clone icon, and you are take to create offer screen with the details pre-filled.

**Comment by ghost** [comment]
Seems like duplicate icon button was added in https://github.com/bisq-network/bisq/pull/5886, but right click functionality still exists. Should we remove it?

**Comment by ripcurlx** [comment]
> Seems like duplicate icon button was added in #5886, but right click functionality still exists. Should we remove it?

Right click still makes sense in certain conditions e.g. open trade view to prevent confusion. So I didn't remove it in general.

**Comment by ghost** [comment]
> Right click still makes sense in certain conditions e.g. open trade view to prevent confusion. So I didn't remove it in general.

Sounds good - I just thought it's something I can work on. Otherwise we can close this issue
