### ISSUE TITLE
BSQ Missing Fund Warning

### ISSUE THREAD

**Issue by dgyg** [bisq-network/bisq#5776]
### Description

When trying to create a new offer paying with BSQ early after the startup of Bisq then a misleading warning may be displayed saying there is not enough BSQ funds available:

![bsq-warning](https://user-images.githubusercontent.com/7886722/138551927-57a5dda9-1284-4a02-bc59-385deae2927c.png)

In fact however there are enough funds available but the blockchain is still being scanned for BSQ transaction in the background and the current balance is not yet fully calculated:

![verifying](https://user-images.githubusercontent.com/7886722/138551820-fd680f9b-92f9-429f-9c97-35426fbb5efc.png)

#### Version

v1.7.4

### Expected behaviour

Warning saying that you have to wait for the blockchain to be fully verified. 

### Workaround

Wait for the blocks to be fully verified.

**Comment by cd2357** [comment]
Thanks for the report @dgyg .

Good news is, this has been known for a while and @sneznaj already prepared a fix with #5766.

I will close this for now, the fix should be delivered probably in the next release.
