### ISSUE TITLE
An error occurred when taking the offer

### ISSUE THREAD

**Issue by ddomingues1970** [bisq-network/bisq#5777]
### Description

An error occurred when taking the offer

v1.7.4

### Steps to reproduce

Same steps to take take offer and the error occurred after clicking the button review and take the order.

### Expected behaviour

Order taken

### Screenshots

![image](https://user-images.githubusercontent.com/25759599/138553109-6da2d70b-1e4f-4c15-a3f2-cee1541a08fe.png)

#### Device or machine

System:    Kernel: 5.11.0-38-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.0.6 
           wm: muffin dm: LightDM Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: Dell product: Vostro 5490 v: N/A serial: <filter> Chassis: 
           type: 10 serial: <filter> 
           Mobo: Dell model: 0M9F58 v: A04 serial: <filter> UEFI: Dell v: 1.12.1 date: 11/20/2020 
Battery:   ID-1: BAT0 charge: 29.8 Wh condition: 29.8/42.0 Wh (71%) volts: 12.4/11.4 
           model: SMP DELL VM73283 serial: <filter> status: Full 
CPU:       Topology: Quad Core model: Intel Core i7-10510U bits: 64 type: MT MCP arch: Kaby Lake 
           rev: C L2 cache: 8192 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 36799 
           Speed: 800 MHz min/max: 400/4900 MHz Core speeds (MHz): 1: 794 2: 790 3: 788 4: 800 
           5: 800 6: 800 7: 800 8: 800 
Graphics:  Device-1: Intel UHD Graphics vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 
           chip ID: 8086:9b41 
           Device-2: NVIDIA GP108M [GeForce MX230] vendor: Dell driver: N/A bus ID: 01:00.0 
           chip ID: 10de:1d11 
           Display: x11 server: X.Org 1.20.11 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel UHD Graphics (CML GT2) v: 4.6 Mesa 21.0.3 
           direct render: Yes 
Audio:     Device-1: Intel vendor: Dell driver: sof-audio-pci bus ID: 00:1f.3 chip ID: 8086:02c8 
           Sound Server: ALSA v: k5.11.0-38-generic 
Network:   Device-1: Intel Wireless-AC 9462 driver: iwlwifi v: kernel port: 5000 bus ID: 00:14.3 
           chip ID: 8086:02f0 
           IF: wlp0s20f3 state: up mac: <filter> 
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Dell 
           driver: r8169 v: kernel port: 3000 bus ID: 02:00.0 chip ID: 10ec:8168 
           IF: enp2s0 state: down mac: <filter> 
           IF-ID-1: br-6f4f3f70148c state: down mac: <filter> 
           IF-ID-2: docker0 state: down mac: <filter> 
Drives:    Local Storage: total: 3.18 TiB used: 980.21 GiB (30.1%) 
           ID-1: /dev/nvme0n1 vendor: A-Data model: IM2P33F3A NVMe ADATA 256GB size: 238.47 GiB 
           speed: 31.6 Gb/s lanes: 4 serial: <filter> 
           ID-2: /dev/sda vendor: SanDisk model: SSD PLUS 240GB size: 223.58 GiB speed: 6.0 Gb/s 
           serial: <filter> 
           ID-3: /dev/sdb type: USB vendor: Seagate model: Expansion size: 1.82 TiB 
           serial: <filter> 
           ID-4: /dev/sdc type: USB vendor: JMicron Tech model: Generic size: 465.76 GiB 
           serial: <filter> 
           ID-5: /dev/sdd type: USB vendor: Hitachi model: HTS545050B9S size: 465.76 GiB 
           serial: <filter> 
Partition: ID-1: / size: 238.00 GiB used: 170.99 GiB (71.8%) fs: btrfs dev: /dev/nvme0n1p2 
           ID-2: /home size: 238.00 GiB used: 170.99 GiB (71.8%) fs: btrfs dev: /dev/nvme0n1p2 
Sensors:   System Temperatures: cpu: 58.0 C mobo: N/A 
           Fan Speeds (RPM): cpu: 2535 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/additional-repositories.list 
           1: deb [arch=amd64] https: //download.docker.com/linux/ubuntu bionic stable
           Active apt repos in: /etc/apt/sources.list.d/brave-browser-release.list 
           1: deb [arch=amd64] https: //brave-browser-apt-release.s3.brave.com/ stable main
           Active apt repos in: /etc/apt/sources.list.d/deadsnakes-ppa-focal.list 
           1: deb http: //ppa.launchpad.net/deadsnakes/ppa/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/focal-dell.list 
           1: deb http: //dell.archive.canonical.com/updates/ focal-dell public
           2: deb http: //dell.archive.canonical.com/updates/ focal-oem public
           3: deb http: //dell.archive.canonical.com/updates/ focal-somerville public
           4: deb http: //dell.archive.canonical.com/updates/ focal-somerville-melisa public
           Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
           1: deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
           Active apt repos in: /etc/apt/sources.list.d/maarten-fonville-android-studio-focal.list 
           1: deb http: //ppa.launchpad.net/maarten-fonville/android-studio/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/microsoft-edge-dev.list 
           1: deb [arch=amd64] http: //packages.microsoft.com/repos/edge/ stable main
           Active apt repos in: /etc/apt/sources.list.d/microsoft-prod.list 
           1: deb [arch=amd64,armhf,arm64] https: //packages.microsoft.com/ubuntu/20.04/prod focal main
           Active apt repos in: /etc/apt/sources.list.d/mongodb-org-4.4.list 
           1: deb [ arch=amd64,arm64 ] https: //repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //mirror.ufscar.br/mint-archive uma main upstream import backport
           2: deb http: //sft.if.usp.br/ubuntu focal main restricted universe multiverse
           3: deb http: //sft.if.usp.br/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //sft.if.usp.br/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
           Active apt repos in: /etc/apt/sources.list.d/slack.list 
           1: deb https: //packagecloud.io/slacktechnologies/slack/debian/ jessie main
           Active apt repos in: /etc/apt/sources.list.d/sublime-text.list 
           1: deb https: //download.sublimetext.com/ apt/stable/
           Active apt repos in: /etc/apt/sources.list.d/teams.list 
           1: deb [arch=amd64] https: //packages.microsoft.com/repos/ms-teams stable main
           Active apt repos in: /etc/apt/sources.list.d/teamviewer.list 
           1: deb https: //linux.teamviewer.com/deb stable main
           Active apt repos in: /etc/apt/sources.list.d/ubuntuhandbook1-apps-focal.list 
           1: deb http: //ppa.launchpad.net/ubuntuhandbook1/apps/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/vscode.list 
           1: deb [arch=amd64,arm64,armhf] http: //packages.microsoft.com/repos/code stable main
Info:      Processes: 444 Uptime: 3d 2h 03m Memory: 15.43 GiB used: 5.47 GiB (35.5%) Init: systemd 
           v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Client: Unknown python3.8 client 
           inxi: 3.0.38 

#### Additional info

Connection 3
Age: 1 hour, 16 minutes, 47.911 seconds
Peer: crq6fmhtlsnyaganzlqzgyeupipc2n4betr3vdyokg7jylrtidkwyqad.onion:9999 
Type: PEER 
Direction: Outbound
UID: f46ce511-eb21-4777-9a01-f8652119ac36
Time since last message: 5.350 seconds
Sent data: 1.864 MB; {AddDataMessage=899, NewDaoStateHashMessage=12, AddPersistableNetworkPayloadMessage=8, RefreshOfferMessage=1458, RemoveDataMessage=20, NewBlockBroadcastMessage=7, GetPeersRequest=1, RemoveMailboxDataMessage=9, BundleOfEnvelopes=527}
Received data: 2.295 MB; {AddDataMessage=1104, NewDaoStateHashMessage=12, AddPersistableNetworkPayloadMessage=8, GetPeersResponse=1, RefreshOfferMessage=1681, RemoveDataMessage=27, NewBlockBroadcastMessage=11, RemoveMailboxDataMessage=16}
CPU time spent on sending messages: 0.933 seconds
CPU time spent on receiving messages: 2.832 seconds

Connection 4
Age: 1 hour, 10 minutes, 25.983 seconds
Peer: 2qpl24kkf6dgtbh2pcmtamwmhgqdgkj2ikvyl5lpg47vlq75ijzo4yqd.onion:9999 
Type: PEER 
Direction: Outbound
UID: 2685d0e7-5637-48a9-8521-bb77eee93798
Time since last message: 0.415 seconds
Sent data: 1.722 MB; {AddDataMessage=820, NewDaoStateHashMessage=12, AddPersistableNetworkPayloadMessage=6, RefreshOfferMessage=1335, NewBlockBroadcastMessage=8, RemoveDataMessage=18, GetPeersRequest=1, RemoveMailboxDataMessage=14, BundleOfEnvelopes=469}
Received data: 1.833 MB; {AddDataMessage=873, NewDaoStateHashMessage=12, AddPersistableNetworkPayloadMessage=5, GetPeersResponse=1, RefreshOfferMessage=1503, NewBlockBroadcastMessage=6, RemoveDataMessage=27, RemoveMailboxDataMessage=8}
CPU time spent on sending messages: 0.799 seconds
CPU time spent on receiving messages: 4.375 seconds

Connection 5
Age: 1 hour, 10 minutes, 13.730 seconds
Peer: bjwxrjyspyo6qxpo4bkb56jws3i2l24tvrwcxiv45qqqo4bye7zmj2ad.onion:9999 
Type: PEER 
Direction: Outbound
UID: f65e66d1-2ecf-447e-bff1-3534cb13a49b
Time since last message: 0.118 seconds
Sent data: 1.802 MB; {AddDataMessage=860, NewDaoStateHashMessage=12, AddPersistableNetworkPayloadMessage=6, RefreshOfferMessage=1393, NewBlockBroadcastMessage=7, RemoveDataMessage=22, GetPeersRequest=1, RemoveMailboxDataMessage=13, BundleOfEnvelopes=504}
Received data: 2.059 MB; {AddDataMessage=984, NewDaoStateHashMessage=11, AddPersistableNetworkPayloadMessage=6, GetPeersResponse=1, RefreshOfferMessage=1798, NewBlockBroadcastMessage=9, RemoveDataMessage=23, RemoveMailboxDataMessage=7, BundleOfEnvelopes=7}
CPU time spent on sending messages: 0.944 seconds
CPU time spent on receiving messages: 3.581 seconds

Connection 6
Age: 1 hour, 10 minutes, 8.235 seconds
Peer: 7k5h362xgrnhxd7lngbg677rovcoiozopc6angi64437yyqbngu3nxid.onion:9999 
Type: PEER 
Direction: Outbound
UID: fc7dc572-85ee-48d2-84e6-603a1fbd656c
Time since last message: 4.886 seconds
Sent data: 1.68 MB; {AddDataMessage=804, NewDaoStateHashMessage=12, AddPersistableNetworkPayloadMessage=5, RefreshOfferMessage=1316, RemoveDataMessage=19, NewBlockBroadcastMessage=6, GetPeersRequest=1, RemoveMailboxDataMessage=10, BundleOfEnvelopes=481}
Received data: 1.937 MB; {AddDataMessage=907, AddPersistableNetworkPayloadMessage=4, GetPeersResponse=1, RefreshOfferMessage=1698, NewBlockBroadcastMessage=7, RemoveDataMessage=27, RemoveMailboxDataMessage=15}
CPU time spent on sending messages: 1.109 seconds
CPU time spent on receiving messages: 3.974 seconds

Connection 7
Age: 1 hour, 9 minutes, 45.703 seconds
Peer: ztv7vjk5bzmwyrys3ycjuh3f544rbgedap3e6g2vxfpvtltlu46xkcad.onion:9999 
Type: PEER 
Direction: Outbound
UID: 63fc9ad5-0327-4454-8214-1c26052edfc3
Time since last message: 6.284 seconds
Sent data: 1.522 MB; {AddDataMessage=729, NewDaoStateHashMessage=12, AddPersistableNetworkPayloadMessage=6, RefreshOfferMessage=1408, NewBlockBroadcastMessage=8, RemoveDataMessage=5, GetPeersRequest=1, RemoveMailboxDataMessage=7, BundleOfEnvelopes=466}
Received data: 1.81 MB; {AddDataMessage=859, NewDaoStateHashMessage=12, AddPersistableNetworkPayloadMessage=5, GetPeersResponse=1, RefreshOfferMessage=1543, NewBlockBroadcastMessage=6, RemoveDataMessage=21, RemoveMailboxDataMessage=10}
CPU time spent on sending messages: 0.815 seconds
CPU time spent on receiving messages: 2.562 seconds

Connection 8
Age: 1 hour, 8 minutes, 30.716 seconds
Peer: r63nibw7csoxvqizw3koyhwkpc6ddo5dmjpcfnwg47coma7fw3tzg5ad.onion:9999 
Type: PEER 
Direction: Outbound
UID: a0a64aae-ddb9-4ee3-8a3f-33d8f3d18a46
Time since last message: 7.502 seconds
Sent data: 1.53 MB; {AddDataMessage=734, NewDaoStateHashMessage=11, AddPersistableNetworkPayloadMessage=4, RefreshOfferMessage=1262, RemoveDataMessage=16, NewBlockBroadcastMessage=3, GetPeersRequest=1, RemoveMailboxDataMessage=8, BundleOfEnvelopes=432}
Received data: 2.149 MB; {AddDataMessage=1023, NewDaoStateHashMessage=11, AddPersistableNetworkPayloadMessage=7, GetPeersResponse=1, RefreshOfferMessage=1787, NewBlockBroadcastMessage=9, RemoveDataMessage=22, RemoveMailboxDataMessage=15}
CPU time spent on sending messages: 0.970 seconds
CPU time spent on receiving messages: 4.629 seconds

Connection 9
Age: 54 minutes, 22.820 seconds
Peer: vdqdsvz7o3fykz5galmo272mpxc63fxkfjijzjztco6v6d5ycglpz5ad.onion:8000 
Type: PEER 
Direction: Inbound
UID: a2cfb22d-b64b-4ef9-a05d-f5d705be21e3
Time since last message: 3.653 seconds
Sent data: 1.33 MB; {AddDataMessage=629, NewDaoStateHashMessage=10, AddPersistableNetworkPayloadMessage=5, GetPeersResponse=1, RefreshOfferMessage=1148, RemoveDataMessage=17, NewBlockBroadcastMessage=8, RemoveMailboxDataMessage=8, BundleOfEnvelopes=383}
Received data: 1.25 MB; {AddDataMessage=596, AddPersistableNetworkPayloadMessage=2, RefreshOfferMessage=1000, RemoveDataMessage=9, GetPeersRequest=1, RemoveMailboxDataMessage=14}
CPU time spent on sending messages: 0.722 seconds
CPU time spent on receiving messages: 1.636 seconds

Connection 10
Age: 21 minutes, 51.619 seconds
Peer: f4aofdr2isiwfnginhc2dsb7faxf4vf22l3zvtcwgte7be5dcfa3lpid.onion:9999 
Type: PEER 
Direction: Inbound
UID: b70ad285-0759-4c1a-bde7-c934bf79e8c3
Time since last message: 2.589 seconds
Sent data: 548.567 kB; {AddDataMessage=262, NewDaoStateHashMessage=5, AddPersistableNetworkPayloadMessage=1, GetPeersResponse=1, RefreshOfferMessage=365, RemoveDataMessage=4, NewBlockBroadcastMessage=2, RemoveMailboxDataMessage=3, BundleOfEnvelopes=149}
Received data: 754.868 kB; {AddDataMessage=356, NewDaoStateHashMessage=5, AddPersistableNetworkPayloadMessage=4, RefreshOfferMessage=613, RemoveDataMessage=5, NewBlockBroadcastMessage=4, GetPeersRequest=1, RemoveMailboxDataMessage=3}
CPU time spent on sending messages: 0.478 seconds
CPU time spent on receiving messages: 2.334 seconds

Connection 11
Age: 11 minutes, 20.016 seconds
Peer: yt2qy7nzy76iap5g2pgicknln7n4j7ppeyzpco5hlbsgqmkj5iytfwid.onion:9999 
Type: DIRECT_MSG_PEER 
Direction: Outbound
UID: 2b337856-9961-4eec-b500-d54fc0decf4a
Time since last message: 1.978 seconds
Sent data: 260.445 kB; {AddDataMessage=119, NewDaoStateHashMessage=1, AddPersistableNetworkPayloadMessage=1, RefreshOfferMessage=202, PrefixedSealedAndSignedMessage=7, NewBlockBroadcastMessage=1, RemoveMailboxDataMessage=1, BundleOfEnvelopes=70}
Received data: 417.305 kB; {AddDataMessage=199, NewDaoStateHashMessage=1, AddPersistableNetworkPayloadMessage=1, RefreshOfferMessage=284, PrefixedSealedAndSignedMessage=8, NewBlockBroadcastMessage=1, RemoveDataMessage=1, RemoveMailboxDataMessage=1}
CPU time spent on sending messages: 0.569 seconds
CPU time spent on receiving messages: 0.868 seconds
 
Oct-23 07:34:58.344 [JavaFX Application Thread] INFO  b.n.p.n.Statistic: Accumulated network statistics:
Bytes sent: 107.625 MB;
Number of sent messages/Sent messages: 35993 / {PreliminaryGetDataRequest=2, NewDaoStateHashMessage=126, GetBlocksRequest=6, RefreshOfferMessage=6114, RemoveDataMessage=163, GetPeersRequest=81, BundleOfEnvelopes=27412, AddDataMessage=1841, GetDaoStateHashesRequest=5, AddPersistableNetworkPayloadMessage=61, Ping=56, GetPeersResponse=24, NewBlockBroadcastMessage=58, PrefixedSealedAndSignedMessage=7, GetUpdatedDataRequest=16, RemoveMailboxDataMessage=14, Pong=7};
Number of sent messages per sec: 1.1880054130772024;
Bytes received: 106.6 MB
Number of received messages/Received messages: 33979 / {NewDaoStateHashMessage=83, RefreshOfferMessage=5210, GetProposalStateHashesResponse=4, RemoveDataMessage=106, GetPeersRequest=24, GetBlindVoteStateHashesResponse=4, BundleOfEnvelopes=27123, AddDataMessage=1174, GetDaoStateHashesResponse=5, AddPersistableNetworkPayloadMessage=56, GetPeersResponse=80, Ping=7, GetDataResponse=8, CloseConnectionMessage=16, NewBlockBroadcastMessage=39, PrefixedSealedAndSignedMessage=8, RemoveMailboxDataMessage=9, GetBlocksResponse=6, Pong=17};
Number of received messages per sec: 1.121530184506717;
 
Oct-23 07:36:24.170 [JavaFX Application Thread] INFO  b.c.u.DesktopUtil: Trying to exec: cmd = kde-open args = %s file = /home/user1/.local/share/Bisq/bisq.log 
Oct-23 07:36:24.173 [JavaFX Application Thread] WARN  b.c.u.DesktopUtil: Error running command. java.io.IOException: Cannot run program "kde-open": error=2, No such file or directory 
Oct-23 07:36:24.173 [JavaFX Application Thread] INFO  b.c.u.DesktopUtil: Trying to exec: cmd = gnome-open args = %s file = /home/user1/.local/share/Bisq/bisq.log 
Oct-23 07:36:24.175 [JavaFX Application Thread] WARN  b.c.u.DesktopUtil: Error running command. java.io.IOException: Cannot run program "gnome-open": error=2, No such file or directory 
Oct-23 07:36:24.175 [JavaFX Application Thread] INFO  b.c.u.DesktopUtil: Trying to exec: cmd = xdg-open args = %s file = /home/user1/.local/share/Bisq/bisq.log 
Oct-23 07:36:24.177 [JavaFX Application Thread] INFO  b.c.u.DesktopUtil: Process is running.

**Comment by ghost** [comment]
Please contact support on keybase if possible https://bisq.wiki/User_support

**Comment by ddomingues1970** [comment]
I gave up using Bisq. Too many bugs. 

Thank you.
