### ISSUE TITLE
Still v2 addresses used in BitcoinJ?

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#5778]
I see that error in the logs:

`[BlockingClient network thread for wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid.onion:8333] WARN  org.bitcoinj.core.Peer: Peer{[wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid.onion]:8333, version=70016, subVer=/Satoshi:0.20.99(@wiz)/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2021-10-23 22:28:21, height=706355}: Received unhandled message: org.bitcoinj.core.SendAddrV2Message@2f5d3a99 `

Looks like there is still usage of v2 addresses?
@ripcurlx any idea?

**Comment by cd2357** [comment]
Getting the same warning when using the BTC node `wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid.onion`:

`Oct-30 14:42:27.156 [BlockingClient network thread for wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid.onion/<unresolved>:8333] WARN  org.bitcoinj.core.Peer: Peer{[wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid.onion]:8333, version=70016, subVer=/Satoshi:0.20.99(@wiz)/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2021-10-30 14:42:26, height=707422}: Received unhandled message: org.bitcoinj.core.SendAddrV2Message@2374be06`

However:
- NOT getting that warning when using my own node (also via tor v3)
- NOT getting that warning when using another of wiz's BTC nodes, `jto2jfbsxhb6yvhcrrjddrgbakte6tgsy3c3z3prss64gndgvovvosyd.onion`

@wiz any difference in setup between `wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid` and `jto2jfbsxhb6yvhcrrjddrgbakte6tgsy3c3z3prss64gndgvovvosyd` ? Are they running the same bisq version?

**Comment by cd2357** [comment]
> `subVer=/Satoshi:0.20.99(@wiz)/`

Tor v3 support was added in Bitcoin Core v0.21

**Comment by wiz** [comment]
Ah okay, looks like this can be fixed by upgrading that one node. It was a custom build of Bitcoin Core v0.20 before the PR to get Tor v3 supported was merged so it supports both v2 and v3 but if that causes issues I can just remove it.

**Comment by cd2357** [comment]
Sounds good. Let me know when its upgraded, I can then check if this warning is gone.

**Comment by ripcurlx** [comment]
This has nothing to do with Tor v2 addresses. This is a new P2P message based on https://github.com/bitcoin/bips/blob/master/bip-0155.mediawiki that supports Tor v3 addresses. So the naming is a little bit confusing. I looked at the code where this logging takes place and it seems that this is sent from @wiz's node to indicate that it is preferring and understands addrv2 messages. I don't know why it only happens with @wiz node and why it is logged as a warning in that case.

**Comment by ripcurlx** [comment]
@wiz Did you change anything already with this node, as I still see this warning?
```
Nov.-10 09:22:14.877 [BlockingClient network thread for wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid.onion/<unresolved>:8333] INFO  org.bitcoinj.core.Peer: Peer{[wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid.onion]:8333, version=70016, subVer=/Satoshi:0.20.99(@wiz)/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2021-11-10 09:22:14, height=709044} 
Nov.-10 09:22:14.877 [BlockingClient network thread for wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid.onion/<unresolved>:8333] INFO  org.bitcoinj.core.PeerGroup: Peer{[wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid.onion]:8333, version=70016, subVer=/Satoshi:0.20.99(@wiz)/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2021-11-10 09:22:14, height=709044}: New peer      (7 connected, 0 pending, 7 max) 
Nov.-10 09:22:14.877 [BlockingClient network thread for wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid.onion/<unresolved>:8333] INFO  org.bitcoinj.core.Peer: Peer{[wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid.onion]:8333, version=70016, subVer=/Satoshi:0.20.99(@wiz)/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2021-11-10 09:22:14, height=709044}: Sending Bloom filter and querying mempool 
Nov.-10 09:22:14.878 [BlockingClient network thread for wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid.onion/<unresolved>:8333] WARN  org.bitcoinj.core.Peer: Peer{[wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid.onion]:8333, version=70016, subVer=/Satoshi:0.20.99(@wiz)/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2021-11-10 09:22:14, height=709044}: Received unhandled message: org.bitcoinj.core.SendAddrV2Message@58fd0c6f
```

**Comment by wiz** [comment]
Fixing this is in my task queue, however as it's merely a warning in the log prints I am treating this as a low priority issue and will get to it after Taproot activation.
