### ISSUE TITLE
Suggestion: better alerts when user interaction needed.

### ISSUE THREAD

**Issue by dan-da** [bisq-network/bisq#578]
I think one reason that trades are often very slow is that people are doing other things outside bitsquare or even afk and the bitsquare app does not get their attention when it is needed.

I think that a good first step in this direction would be to play a sound.  maybe even a voice recording or something that is clearly from bitsquare.  "You've got payment".  haha.

Other ideas would be to flash the window or popup an OS level modal dialog/alert... if that's even possible from java-land.

Sending an email would be cool, but takes away from privacy.

**Comment by ManfredKarrer** [comment]
Yeah OS notifications are planned, but that requires a bit of extra work as java does not support that directly.
Other notification (email, mobile) would be even better but to protect privacy is a bit challenging here. 
I asked the signal guys if they have any API and if there would be some way to use it but did not get an answer.
A Simple mobile app just for that would be another possibility. Could utilize the tor hidden services even...

**Comment by jonathancross** [comment]
+1 for sending a message via Signal.
Looks like you'd need this:
https://github.com/WhisperSystems/libsignal-service-java

**Comment by ManfredKarrer** [comment]
Ah that would be good. A candidate for a bounty?
Btw @jonathancross did you receive my email?

**Comment by jonathancross** [comment]
@ManfredKarrer Yeah, great candidate for a bounty.

I responded to your email as well, thanks for telling me (I get too much email and things get lost sometimes).

**Comment by haiqu** [comment]
See also #521

**Comment by ripcurlx** [comment]
Isn't this now superseded by https://github.com/bisq-network/exchange/issues/1022?
