### ISSUE TITLE
Improve DAO state peristence

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#5783]
The DAO state is getting larger with each new block and is a major issue for memory consumption of Bisq.
Currently it is about 150 MB, where 135 MB are the blocks. We load it at startup which takes about 2-4 sec on my machine and then after parsing is complete we write snapshots to disk (every 20 blocks) which also takes a few seconds. Persistence happens on background threads so it is not a major problem but still quite slow.

I was wondering what we could do to improve that situation.
Best would be if we could avoid to load 150 MB into memory but I fear that is not feasible without either a huge and risky effort to optimize and customize the data access or try to use some DB but I am pretty sure that would degrade performance a lot as we need most of the data for different forms of access (the large chunk of data are transactions and we need to look up those for various properties in the DAO context). In Bitcoin it is easier as there the spendability is the only real aspect to consider, so pruning of data which is not relevant for furture use cases can be done easier. In Bisq the DAO has many different use cases where old data is still relevant, so pruning is likely not really possible. The only way I see is to create all kind of data views (lookup maps) for the various use cases we have. E.g. If we need to iterate all txs for finding potential locked outputs we could just make a lookup map where the txOutputType we are interested in is used as key and we hold only the few relevant txs there. If all use cases could be optimized that way we could release the blocks/txs and only keep the relevant views, which likely will be much smaller. That would be one approach but I am not 100% sure if it would really lead to less data and it comes with considerable effort and risks for the DAO consensus.

But the 150 MB in memory are not the only concern. At snapshot creation we have to keep a copy of that in memory. Here we could optimize with much less risks and less effort.
We could extract the blocks from the daoState into a dedicated data store and split that up either automatically in buckets of e.g. 1000 blocks or use a similar versioning model as we use for trade statistics (historical data store). The automatically managed approach would be probably better as it would not require work from the release manager. As blocks are immutable we could treat all old buckets as immutable closed data structures and therefor wont need to persist them. They are only loaded for getting the data and concatenated with all the other buckets to form the full BSQ block chain. We only persist the current one which will be much faster as data size will be a few MB not 150 MB.
The other DAO state is about 15 MB so that is also ok for fast persistence.
There is still a smaller issue with re-org. Say we just moved to a new bucket with a new block and then there is a 3 block deep re-org so it changes our blocks in the previous bucket which we considered as immutable/closed. But that is a minor issue and there are ways to deal with that, like considering the previous bucket not as closed but preliminarily closed so we still can mutate it. After deleting the reorged blocks we would resync from there. Thats similar as we do a resync from the last snapshot in case of reorgs in the current model. We do not need to support arbitrarily deep re-orgs as realistically reorgs are never deeper than 3-4 blocks. 

Another smaller improvement is that I guess it would decrease memory requirements if we serialize the cloned snapshot candidate immediately so we avoid the overhead for Java data sturctures and required memory should be smaller. Have to try out how much difference that makes.

So I think that approach is feasible to implement and comes with little risks for DAO consensus issues.

Any other ideas? Feedback?

**Comment by sqrrm** [comment]
I think the splitting of blocks in 1000 block buckets is a reasonable thing to do that doesn't carry much risk.

Modding the data structures for the DAO consensus carries a lot more risk but could perhaps be done. I would avoid it if possible but perhaps just mimicking the current behavior with new data structures in parallel for a while could be a way to get there with reduced risk.

**Comment by chimp1984** [comment]
Found an interesting approach using MappedByteBuffer. 
https://blogs.oracle.com/javamagazine/post/creating-a-java-off-heap-in-memory-database

Still heavy work in progress but got all blocks stored in that MappedByteBuffer as individual records. Reading of all live blocks takes 1.5 sec instead of about 5-8 sec for the DaoState. Write takes about 1 ms, remaining daoState data is about 18MB and takes about 300 ms. But still much faster than with all blocks in the daoState which took about 5-8 sec.

Have not seen yet how much it improves the memory usage, but as we do not clone the large daoState anymore but only the 18MB data + the blocks since the last write, I guess it will have some positive impact. And protobuf serialisation is much faster as well if we don't persist all blocks at each snapshot.

**Comment by chimp1984** [comment]
Here an update of my work on that:

I tried out a few different key/value DB solutions ([MapDB](https://github.com/jankotek/mapdb), [LevelDB](https://github.com/pcmind/leveldb), [LMDB](https://github.com/lmdbjava/lmdbjava), [Xodus](https://github.com/JetBrains/xodus), [Chronicle-Map](https://github.com/OpenHFT/Chronicle-Map)...). I did not get Xodus and Chronicle-Map fully working for my example case due APIs which did not fit well to my use cases. I also tried to use the standard logging framework by adding a custom logger but it would have required to write a custom rolling file adapter for our needs and parsing all byte array data to hex was not convenient as well (and would have been probably slow), so did not follow further on that approach.

LevelDB was my favorite candidate for a DB solution but after reading more about its [concepts](https://www.igvita.com/2012/02/06/sstable-and-log-structured-storage-leveldb/) I realized that it does not fit really our use case and requirements as it would not provide determinisitic storage files. It also would add risky dependencies (from the not much used java lib) and would be an overkill for what we need. I tried it also in the PersistenceManager for all sotrage files, but that would lead to pretty bad performance as there are too many compactation cycles triggered by the kind of persistence we do (replacing data and not mainly appening data).

The goal to get off-heap by using memory mapped files (e..g by using MappedByteBuffer,...) would not have led to the desired result as we use Protobuf and that does not has zero-copy support (Capt'n Proto and FlatBuffers does). Also that would have been a large refactoring and not really sure if that would work out well. But its something to keep in mind for Misq/Bisq 2 as it could reduce a lot of memory footprint and performance by avoiding those copy operations and parsing as with Capt'n Proto. 

So after all that, I came to the conclusing its best to do only the minimal changes where it hurts most (BSQ Blocks) and use the simple file based model we use already in the PersistenceManager but split up the blocks in buckets.

Here are our requirements:
- Read only once at startup
- Write infrequent (each 20 blocks for snapshotting)
- Persist in a deterministic manner so we can ship files as resources with a deterministic set of blocks
- Avoid manual management of the resource files as we require for the version based historical data stores
- Fast write and read, low memory costs
- If possible avoid adding new dependencies, specially if from not from well established repos
- If possible avoid JNI based libraries as that might reduce compatabilty with some systems (Raspberry Pi,...)

Implemented solution:
- Split BSQ blocks in buckets of 1000 blocks (about 1 MB, about each week a new bucket) and store those inside a BsqBlocks directory. Buckets are named with the block range inside that bucket (BsqBlocks_584001-585000)
- Auto-migrate existing DaoStateStore to the new model by adding all blocks to the new data structure and then not storing blocks them anymore inside the DaoState which is persisted in DaoStateStore. We keep the rest of the DaoStateStore untouched (blockHashes, DaoState). So only the blocks got extracted to its own persistence structure.
- At snapshots we keep only the blocks from the last persisted snapshot up to the most recent (usually 20 blocks as that is the snapshot interval). This reduces memory requirement for the snapshot from 135 MB to a few kb. The rest of the DaoState is about 18MB. The Hashes could be treated also according to the new model but as they are tiny its not worth it.

I made some performance comparision from the branch with the optimizations for the hashChain and that new implementation.

I tested with a fresh start syncing from resources and full-mode for daoStateMonitoring (otherwise we do not do snapshots during parsing).

Here are the results:

**Old version:**
READ:
Reading 150 MB large DaoStateStore about 3-4 sec

WRITE:
Writing the serialized DaoStateStore completed in 2-3 sec

SNAPSHOTS:
Parsing 5808 blocks took 2010.5 seconds (33.51 min.) / 346.16 ms in average / block 
Total GC invocations: 242 / Total GC time 125.883 sec 

**New version:**
READ:
Reading and deserializing 135814 blocks took 1342 ms  (135 MB in total)
PersistenceManager: Reading 18 MB large DaoStateStore completed in 303 ms 
-> Total time for datState+blocks: about 1.5-2 sec

WRITE:
Persist (serialize+write) 806 blocks took 15 ms 
Writing the serialized 18 MB DaoStateStore completed in 265 msec 
-> Total time for datState+blocks: about 200-300 ms

SNAPSHOTS:
Parsing 5808 blocks took 1575.13 seconds (26.25 min.) / 271.2 ms in average / block 
Total GC invocations: 130 / Total GC time 60.478 sec 

So READ performance is about half of the old verison, WRITE performance about 10 times faster and total parsing is about 20-25% faster (hashing is the slow operation here) and there is about 50% less work for GC (I am still in the process to optimize that further). Peak memory was also a bit lower in the new version.
