### ISSUE TITLE
Unable to start Bisq on macOS

### ISSUE THREAD

**Issue by xmijo** [bisq-network/bisq#5789]
### Description

I'm a longtime Bisq user. Startup is often slow but lately Bisq just does not start at all, I have been waiting for close to an hour. It gets stuck on startup after entering the password and appears like it's just really slow to connect to peers or creating the hidden service, and eventually times out or loses connections. I have restarted many times of course and on different days. I've had this issue for quite some time before opening this report.

I wonder if it has something to do with upgrading to v3 onion protocol a couple months ago. I think I followed the process as outlined in the docs.

Please let me know what additional info is required to debug this.

#### Version

Bisq 1.7.5

### Steps to reproduce

Start Bisq.

### Expected behaviour

Bisq starts as normal.

### Actual behaviour

Bisq gets stuck during startup.

#### Device or machine

macOS Big Sur 11.5.2

#### Additional info

Getting many FAILED log entries, e.g.
`[TorControlParser] DEBUG o.b.n.tor.Tor: CircuitStatus: 262 FAILED BUILD_FLAGS=IS_INTERNAL,NEED_CAPACITY`
`[TorControlParser] DEBUG o.b.n.tor.Tor: CircuitStatus: 167 FAILED $.....25B21FC3B7781CDD......~DTFNODE19`

It also looks like connections are being closed for some reason:
`TorControlParser] DEBUG o.b.n.tor.Tor: CircuitStatus: 394 CLOSED`

Not sure if these are normal in the logs.

**Comment by xmijo** [comment]
Took a very, very, long time to start up but I eventually got in. At least I know it isn't broken. Closing this.

**Comment by ripcurlx** [comment]
> Took a very, very, long time to start up but I eventually got in. At least I know it isn't broken. Closing this.

This should change with v1.8.0 a lot, as it will bring down the DAO synchronization to a couple of seconds.
