### ISSUE TITLE
Bid/Ask lists should summarize trades per price-level.

### ISSUE THREAD

**Issue by peertrade** [bisq-network/bisq#580]
On other exchanges the bid and ask lists present a single line for each price with the total volume at that price level.   So if 2 traders have made buy offers of:

```
3@10
2@10
```

Then the displayed price would be 10 and the total amount would be 5.  Look at pretty much any exchange as an example:  btc-e, poloniex, etc.

Bitsquare instead displays invididual orders even if they are at the same price level.  Plus, it only shows the top 3, where other exchanges typically show all price levels.

I would suggest modifying the behavior to be like that of other exchanges, as that is what traders are used to and expect.

Attaching screenshots  of bitsquare showing duplicate behavior limited to top 3 offers, and of poloniex showing aggregate totals with scrollbars.

Bitsquare:
![screen](https://cloud.githubusercontent.com/assets/6629088/17651060/90a1b4ea-624d-11e6-90fb-b612ef982717.png)

Poloniex:
![screen2](https://cloud.githubusercontent.com/assets/6629088/17651088/6b4f55c0-624e-11e6-889e-837d03c69aaf.png)

**Comment by peertrade** [comment]
thinking about this some more, I can see that it is of some value to display individual orders given that there is no automated order matching system, and traders must pick individual orders themselves.

Still, I think it is useful to be able to see the aggregated data, so perhaps there could be an option (checkbox) to display aggregated or not.

Also, in either case I think there should be a scrollbar.

**Comment by ManfredKarrer** [comment]
The overview is just for a quick overview, at the buy/sell screens you see the full offer book. I wanted to avoid duplicated features and there is not much space to display both sides in the overview screen with all the additional details on the buy/sell screens.

**Comment by peertrade** [comment]
Well its just a suggestion.  As a new user on the platform it feels like a rough edge to me, compared to what I am used to with other exchanges.   not a showstopper by any means.

**Comment by ManfredKarrer** [comment]
The UI would need some improvements, but there are other tasks which have higher priority atm, and I need a dedicated UI dev to get those things done, otherwise I get blocked too much on that issues.... But I am aware that there is much headroom for improvements. Just need a bit more time...
