### ISSUE TITLE
HIGH CPU USAGE

### ISSUE THREAD

**Issue by SynapseScribe** [bisq-network/bisq#5806]
i get extremely high cpu usage on latest version 1.7.5 (windows) - 55% even on idle (on 6 core proc)

**Comment by cd2357** [comment]
Check the bottom status bar of the Bisq window.

If it says "Synchronizing DAO", thats a phase which is indeed a bit CPU-hungry. However, once its finished, CPU usage should go back down. This has been known for a while: https://github.com/bisq-network/bisq/issues/4370#issuecomment-744247834

Good news is, "Synchronizing DAO" is being reworked for the next release (#5782) aiming to make it much less resource-hungry.

Given all that, I'll close this ticket.

Let us know below if you still see very high CPU usage even after "Synchronizing DAO".

**Comment by SynapseScribe** [comment]
Indeed CPU usage dropped after sync. Thank you and good news that the engine is being reworked. Good job!
