### ISSUE TITLE
BUG: Market price sometimes displays incorrectly after startup.

### ISSUE THREAD

**Issue by peertrade** [bisq-network/bisq#581]
In the following screenshot notice that the XMR price from poloniex is displayed 582.2, but the bid/ask prices are all in the 200's.

![screen](https://cloud.githubusercontent.com/assets/6629088/17715224/ba91264a-63f2-11e6-8531-a1e9368d3560.png)

This seems to happen mostly (only?) soon after startup.  Specifically, immediately after startup the correct market price is shown, then after a few seconds it changes to the 582 price.  Then some minutes later back to the correct price.

I duplicated this behavior three times with XMR. ( three re-starts ).

On two of the occasions I was able to manually restore the correct price by:
1. selecting another currency in the market-price drop-down list.
2. clicking again on the market-price drop-down list and now the correct xmr price is displayed.

This hints to me that it may be a display or initialization issue related to the drop-down list control, rather than a problem with the underlying price data.

**Comment by peertrade** [comment]
I just noticed one more detail/hint.  In the screenshot, "Poloniex" is not displayed by the market price control.  But after it corrects itself, it is.   So perhaps it is some sort of transitory state while the market price data is being fetched.

**Comment by peertrade** [comment]
As an additional data point I tested with another currency (DASH) by choosing it in the order book before restarting.  result:  582.89 DASH/BTC.   The same integer number (582) as I saw with XMR.

AND!  looking at other currencies in the drop-down, I see it matches the USD price.   So perhaps USD is somehow being used as a default value?

![screen2](https://cloud.githubusercontent.com/assets/6629088/17715805/62fb9b2e-63f5-11e6-837b-ae4d36eef5df.png)

**Comment by ManfredKarrer** [comment]
Thanks for reporting. Seems that the USD price is overriding the selected currency. Will have a look into it....

**Comment by haiqu** [comment]
I get this too, except the AUD price overrides the selected currency.

**Comment by stachrom** [comment]
CHF is as well way off - kind of stuck. 

Displayed: 1016.24 
Expected: around 1047.73

**Comment by ManfredKarrer** [comment]
Thanks for the report. The provider nodes have had issues. I restarted them and now the price should be correct again.

**Comment by ripcurlx** [comment]
Closed by comment from @ManfredKarrer?
