### ISSUE TITLE
CreateMakerFreeTx error

### ISSUE THREAD

**Issue by greenadmin** [bisq-network/bisq#5810]
An error occured while placing a trade
![Bildschirmfoto von 2021-11-05 14-32-06](https://user-images.githubusercontent.com/37071192/140519350-1bed9dff-fde5-4130-b181-d3a264e54c34.png)
[bisq.log](https://github.com/bisq-network/bisq/files/7486370/bisq.log)

### Description
This error occurs every time while a trade is going to be placed. The Bisq wallet is sufficiently funded. The network connection is stable. Application reboot done twice. 

#### Version
1.7.5

### Steps to reproduce
Try to set a bid

### Expected behaviour
The trade is placed into Bisq 

### Actual behaviour
Error warning

**Comment by ghost** [comment]
- Try reducing the BTC amount of the offer so it leaves more change in your wallet.

If that does not help,

- Check the wallet balance shown in `Account -> Account Info` and in `Funds -> Send`.
- Maybe try an SPV resync.  https://bisq.wiki/Resyncing_SPV_file

**Comment by greenadmin** [comment]
The issue was the BTC amount. Once I left more change in the wallet it worked immediatly. Thanks for help.
