### ISSUE TITLE
Bug with v1.7.0

### ISSUE THREAD

**Issue by Funk4Lif3** [bisq-network/bisq#5814]
#### Device or machine

<Apple Macbook Air 2012 i5 1.8 Ghz>

#### Additional info
[bisq.log](https://github.com/bisq-network/bisq/files/7500178/bisq.log)

<>

**Comment by ripcurlx** [comment]
@Funk4Lif3 Could you please provide a little bit more context on this bug as in the template above suggested? Thanks!
