### ISSUE TITLE
Error on open: Header bytes do not equal SPVB

### ISSUE THREAD

**Issue by lesterhv** [bisq-network/bisq#582]
Installed yesterday, following reboot am unable to open today - receive the error Header bytes do not equal SPVB.

Luckily no btc in wallet, but would like to know how to resolve if there was.

Error log:
[hs_err_pid2584.zip](https://github.com/bitsquare/bitsquare/files/421887/hs_err_pid2584.zip)

**Comment by ManfredKarrer** [comment]
Can you send me the app log file (its in the data directory)?

Location of the data directory:
Mac OSX: /Users/username/Library/Application Support/Bitsquare
Linux: /home/username/.local/share/Bitsquare
Windows XP: C:\Documents and Settings\username\Application Data\Bitsquare
Windows Vista or 7: %appdata%/Bitsquare

**Comment by ManfredKarrer** [comment]
It might be a corrupted Bitsquare.spvchain file. u can delete that file it will get re-created at a new startup.
If u still have issues, please send me the app data log files and re-open.
