### ISSUE TITLE
Bug install Ubuntu

### ISSUE THREAD

**Issue by Copinmalin** [bisq-network/bisq#5828]
[bisq.log](https://github.com/bisq-network/bisq/files/7534484/bisq.log)

**Comment by ripcurlx** [comment]
@Copinmalin Based on the log file it looks like as if you are running multiple Bisq instances with the same data directory on the same machine. Could you please check your running processes if there are any other Bisq processes running?

**Comment by Copinmalin** [comment]
Is I have another instance on the same network (not the same computer) does I have this problem ?

**Comment by ripcurlx** [comment]
> Is I have another instance on the same network (not the same computer) does I have this problem ?

Having another instance with a different data directory shouldn't be a problem at all. I am running multiple instances without any problems on the same machine. But just for testing purpose could you stop the other machine before trying to run the other one you have problems with. I don't think this should make a difference, but to be on the safe side. Regarding the bisq instances on the same machine: did you see multiple bisq processes on this machine? Maybe some got stuck and are still loitering around.

**Comment by Copinmalin** [comment]
OK I restart and now it's OK, problem solved, thanks !
