### ISSUE TITLE
IDEA: implement dynamic offer fee to provide market incentives.

### ISSUE THREAD

**Issue by dan-da** [bisq-network/bisq#583]
**Background**:  there is presently an offer fee of 0.0005 per offer that is collected even if an offer is cancelled.  This fee is in place as an anti-spam/DOS measure, but feedback has been received that it may be a problem (disincentive) for market-makers or higher volume traders.   At this point in time, liquidity is low in all bitsquare markets, so it is helpful to remove disincentives to trade.  At the same time, we should not do anything that opens the system up to attack, or that we might wish to reverse later.

As such, I came up with the idea for dynamic offer fees.  The general idea is that the offer fee can adjust according to how much liquidity there is in the market.  During periods of insufficient liquidity on either side, the fee can drop to zero. During periods of high(er) liquidity, the fees can increase significantly (linearly or superlinearly)  and should thus combat spam.

@ManfredKarrer  extended the idea to incentivize offers that are close to the market price and disincentivize those that are further away.  In his words:

> another aspect would be to add incentives for offers which are close to the market price. they should have lower fees as they produce less network load when they get taken fast. to use a fee which is based on the margin to the market price might be a strategy here. an offer with 10% distance to the market price has less value for the exchange and produce higher network costs as it will probably stay in the offer book for weeks or months so they should pay more.

I am creating this issue as a focal point for discussion of the idea, algorithm(s) to use, any potential issues, and mostly so we don't just forget about it.  :)

These were my initial comments on the subject:

> The offer fee is a disincentive to volume traders.  Their model is to be constantly making and cancelling (updating) orders.  If we can provide a way to edit an order WITHOUT fee, I believe that could help at least until there is sufficient ongoing liquidity.
> 
> I understand that the offer fee is intended as an anti DOS/Spam mechanism.  But presently we have the opposite problem:  not enough offers.  So, is there a way that we could algorithmically remove the fee until such time as there is a liquid market?   Something like:  
> 
> ```
>     If orderbook has less than 10 open orders on each side OR
>         no trades conducted in last 10 minutes THEN
>           offer_fee = 0
> ```
> 
> Similarly, it seems like logic could also be applied to make the offer fee increase if there are too many open orders.   Eg:
> 
> ```
>     offer_fee = min( 0.0005, 0.0005 * num_open_offers / 100 )
> ```
> 
> though it might be better to increase non-linearly.

Followed by:

> I do not propose simply setting the offer fee to 0.  Such a change/fork now would imply another change/fork in the future to change it back.  Also, it is harder in the future to get people to accept a change that increases fees.
> 
> Instead I propose an algorithm that would remove offer fees entirely during periods of low liquidity and impose and even increase fees during periods of high liquidity (or spam offers).  So it adjusts with the market dynamics... sort of like bitcoin's mining difficulty.
> 
> If it can be implemented, I think such an algo is the best of both worlds:   it incentivizes participation when there is low liquidity and it brings in fees when there is high liquidity as well as disincentivizing spam offers.
> 
> I have not put much thought yet into the exact algo or params.

This would be a consensus-level rule change.  So it is important to get the algorithm right from the start.  And we probably also need to think about how to deploy it without breaking older clients... or perhaps as part of a larger-scope hard-fork.

**Comment by A2be** [comment]
Yes, my first look at Bitsquare recently did reveal very thin markets on many (most?) of the trading pairs.  Seems, therefore, that a dynamic adjustment of the transaction fee by some mechanism is a useful idea to consider at a requirements level.  

A related item, possibly also a factor in the thinness of the market (few offers to buy or sell) is the need to leave a system turned on with bitsquare software operating.  As a new Bitsquare tester, with my first-ever operation of the Bitsquare client 0.4.9.6 only yesterday, I'm just not yet comfortable with the app, nor clear on its friendly interoperation with other parts of my system, to leave it on while I'm not at the terminal.  I'm guessing that other newbies might feel similarly.

**Comment by haiqu** [comment]
Seems to me we just don't have a lot of market penetration yet. I'd be interested to know how many copies have been downloaded. My first impression was of a very rough UI and non-intuitive operation, which would be enough for most people to give up.

Simplicity is always the best answer, and the current system is simple. It can be tweaked if/when the program becomes popular, but I doubt the 0.0005 BTC fee (about US$0.30) is stopping users. In any case do we really want bots and constant price changes - like everyone else has - to clog up the network? Some of us have to pay per gig for wireless bandwidth, which would be more expensive than the fee if that happened.

Next you'll be asking for a trollbox. ;)

**Comment by ManfredKarrer** [comment]
Download stats:
http://www.somsubhra.com/github-release-stats/?username=bitsquare&repository=bitsquare

I think low promotion activity is the main reason why liquidtiy is low (again).

UI need to be improved but I need more help on the dev front, I cannot do all myself, too much work already.

Yes I agree to your concern regarding a lot of offer coming and going.
A P2P network has different properties than a server architecture, decentralisation has its costs.

**Comment by haiqu** [comment]
Thanks. I'd also like to say that despite my criticisms of the superficial interface, the basic design is very good. But I also think that focusing on the core product is essential. I've stopped using MANY software products because of 'feature bloat' that makes them sluggish and complex to the point of useless.

It's good for people to have ideas about what they want to see in Bitsquare, but we have to ask ourselves whether implementing some of them would be beneficial or just a distraction from the task and a waste of scarce dev resources.

Only 23,000 downloads? Yep, we need PR.

**Comment by jkelly99** [comment]
I'd like to also ask if the offer / take offer fees could maybe be based on the size of the transaction? I becomes expensive (relatively speaking) if one is buying/selling small amounts, such as 0.01 btc. I would think making it a percentage fee rather than fixed would encourage more trading.

**Comment by ManfredKarrer** [comment]
Yes we are planning to change that. Probably it will be based on the distance to the market price. Good offers should be cheaper...
The fees serve as spam protection so too low fees don't give that protection anymore.

**Comment by ManfredKarrer** [comment]
% based offers are impl. already. Will close that.
