### ISSUE TITLE
Extract pricenode subproject to dedicated repository

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#5837]
For the reasons discussed at https://github.com/bisq-network/bisq/pull/5824#issuecomment-970178637.

Note that a `bisq-pricenode` repository already exists and may be un-archived and wiped (or deleted and re-created) for this purpose.

Will need to think about:

- Process, documentation, sysctl / docker config changes for @bisq-network/pricenode-operators 
- Versioning
- Cleaning up no-longer used dependencies from the `gradle/verification-metadata.xml` file introduced in #5824. These entries won't be deleted by default, so must remember to do it manually after the extraction is complete.

**Comment by cbeams** [comment]
Update: the work to extract the pricenode has now been done by @ghubstan and others. See https://github.com/bisq-network/bisq-pricenode.

**Comment by ghubstan** [comment]
> Update: the work to extract the pricenode has now been done by @ghubstan and others. See https://github.com/bisq-network/bisq-pricenode.

Thanks, @cbeams .  I might hand the new `bisq-pricenode` off to OPS / @Emzy this week.   Extracting the monitor is almost ready, but I want to fix some problems in it before trying to give it to OPS.  Inventory is done.   Other repo extractions should be quick and easy.  

I will remove bisq :subprojects after hand-off to OPS.

**Comment by wiz** [comment]
I forgot to tell you guys but we implemented a whole price server from scratch into the @mempool project a while back, it queries multiple exchanges for multiple currencies etc. so we would just need to implement the same bisq API spec into the mempool backend and bisq could drop the bisq-pricenode entirely.
