### ISSUE TITLE
please add Stellar coin

### ISSUE THREAD

**Issue by antb123** [bisq-network/bisq#584]
XLM or STR 

We are interested to ensure it is available

Thanks

**Comment by ManfredKarrer** [comment]
I think stellar used a second data field, so that would cause extra effort.

**Comment by antb123** [comment]
Second field is optional (memoid)

Wallets use just the address... Thanks

On 25 August 2016 3:24:05 PM GMT-04:00, Manfred Karrer notifications@github.com wrote:

> I think stellar used a second data field, so that would cause extra
> effort.
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/bitsquare/bitsquare/issues/584#issuecomment-242507630

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by haiqu** [comment]
All coin add requests should be directed to the following forum topic:

https://forum.bitsquare.io/t/how-to-add-your-favorite-altcoin

**Comment by m52go** [comment]
If this is possible to include in v1.1.6, could be good. Apparently Keybase is [doing an airdrop](https://www.theblockcrypto.com/post/38925/stellar-foundation-to-airdrop-121m-in-xlm-tokens-to-users-of-slack-alternative-chat-app-keybase/) of Stellar and people are wondering where/how to dump it for bitcoin.

https://twitter.com/nvk/status/1171239691221385216
https://twitter.com/Excellion/status/1171396372362227712

EDIT: disregard this comment; got a [better work-around](https://twitter.com/bisq_network/status/1171467059034652672).
