### ISSUE TITLE
SEPA Instant with identical name to aged SEPA account (same IBAN) not getting self signed

### ISSUE THREAD

**Issue by GordianLN** [bisq-network/bisq#5841]
### Description

I decided to eat my bank's instant transfer commissions and try using instant for my offers, but when I went to my Account > National currency accounts to add the SEPA instant (just copying over every detail except selecting SEPA Instant instead of plain SEPA), my account will not get automatically signed. My SEPA account has had all its limits lifter by now, not just the first 30 days.

#### Version

1.7.5

### Steps to reproduce

Have signed SEPA account, over 60 days from signature, add SEPA instant with *same* details.

### Expected behaviour

SEPA Instant account will get automatically signed.

### Actual behaviour

I receive warning about account limits and aging and need to get signed to buy amounts higher than 0.01btc

### Screenshots

Not applicable

#### Device or machine

Windows

#### Additional info

Please ask me to provide additional details if needed

**Comment by pazza83** [comment]
What does the account signing status say?

It should be signed pending limits being lifted in 30 days.

The name need to match exactly but sounds like it should do if you copy / pasted.

You could try deleting and re-adding the SEPA Instant and/or restarting Bisq to see if it fixes the issue.

**Comment by GordianLN** [comment]
I see, adding the account as is won't make it signed.
But I need to add the account AND restart Bisq, it will indeed show it's signed and waiting for 30 days... which is still a bummer as I was expecting it would have been both signed and aged as the self-signing account :(

**Comment by pazza83** [comment]
Yes, there is no way to avoid the 30 day wait for limits to be increased.
