### ISSUE TITLE
Slight timeout during offer process. caused it to fail. now it cant be redone.

### ISSUE THREAD

**Issue by Rake03** [bisq-network/bisq#5843]
### Description

As a result offer went to fail and I could not make the same offer...should be able to erase the failed offer, specially if its due to technical difficulties like a minor connection time out.  Its the only offer that I'm interested in....so what now

**Comment by Rake03** [comment]
Found the thread below filled with identical issues

https://github.com/bisq-network/bisq/issues/4760

**Comment by ghost** [comment]
For release 1.8.0 the threshold has been increased, to reduce cases of timeout during the take offer process.  -> https://github.com/bisq-network/bisq/pull/5904
