### ISSUE TITLE
Error: Overflow

### ISSUE THREAD

**Issue by pandascrape** [bisq-network/bisq#5844]
### Description

On startup I receive an Error box with message "Overflow"

#### Version

1.7.5

### Steps to reproduce

Happens each time on startup, immediately after entering password.

[UPDATE: Third time starting, error was no longer there].

### Expected behaviour

Bisq should start normally.

### Actual behaviour

Error is flagged and asks me to report it. Bisq app looks as if it has started up OK.

#### Device or machine

Debian 11 with GNOME

#### Additional info

Log output attached
[bisqlog.TXT](https://github.com/bisq-network/bisq/files/7568584/bisqlog.TXT)

**Comment by ripcurlx** [comment]
@pandascrape This sounds like someone published either an offer with an incorrect Altcoin amount or there was a problem with the price feed. Do you remember which offerbook (which Altcoin) you had open?

**Comment by pandascrape** [comment]
It was either EUR or GBP.

If it's relevant, Bitcoin Core was running on the same machine and it's possible (although unlikely) that it was not quite synced to the blockchain tip at the time of error.
