### ISSUE TITLE
Offers getting disabled

### ISSUE THREAD

**Issue by PrinceAvada** [bisq-network/bisq#5861]
Since I updated to v1.7.5, my offers don’t stay active very long, and get disabled in a few minutes. If i enable it again, it gets disabled automaticaly…

Restarted PC and bisq but no improvements.

And I never got the message “We did not receive a filter object from the seed nodes. etf…"
Everything seems fine with the DAO state Status.

Someone has a solution to this?

V1.7.5

**Comment by ghost** [comment]
Could you let me know your affected offers maker fee txid (click on the offer id to see it).

**Comment by pazza83** [comment]
Hi @PrinceAvada 

- Are you using Tor v3? https://bisq.wiki/Changing_your_onion_address#Determine_which_Tor_version_Bisq_is_running
- Is your computer date and time set correctly?

**Comment by w0000000t** [comment]
I was having this same problem, offer getting auto-disabled after a few minutes tops, tried restarting Bisq and now, touching wood, it's staying enabled.
