### ISSUE TITLE
Adapt column resizing policy in offer book

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#5862]
### Description

Launching the app in another language (e.g. German) reveals a problem with the column resizing in the offerbook

#### Version

v1.7.5-

### Steps to reproduce

- Switch to German
- Open offer book

### Expected behaviour

Column should resize properly if enough space is available so that no text is truncated.

### Actual behaviour

Text stays truncated

### Screenshots

![Bildschirmfoto 2021-11-24 um 11 07 08](https://user-images.githubusercontent.com/170962/143218217-51affd88-5c1c-4c55-b2a6-a7e61f92f343.png)

#### Device or machine

Not OS related

**Comment by alvasw** [comment]
I'm working on this. Just letting everyone know.
