### ISSUE TITLE
[v1.8.0] Duplication of BSQ swap offers not supported

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#5865]
When trying to duplicate a BSQ swap offer nothing happens.

![Bildschirmfoto 2021-11-25 um 11 18 07](https://user-images.githubusercontent.com/170962/143423223-78328cb1-6964-40e0-bacc-4ca292c19dd2.png)

### Description

Duplication of BSQ swap offers not possible

#### Version

master, v1.8.0 release branch

### Steps to reproduce

- Try to duplicate an existing offer in `Portfolio > My Open Offers`

### Expected behaviour

- BSQ swap offer can be duplicated

### Actual behaviour

Nothing happens (not even an error log)

### Screenshots

![Bildschirmfoto 2021-11-25 um 11 18 07](https://user-images.githubusercontent.com/170962/143423638-a020eb14-cd3f-42f9-b058-41fa457738bb.png)

**Comment by chimp1984** [comment]
Edit offer and duplication is not supported. Wanted to limit effort and see how much it will be used. Edit offer is also not really needed as BSQ offers have no maker fee at offer creation. 

The duplication feature should though be deactivated. But to be honest, it is so hidden that most users are not aware of it anyway I assume.... (right click context menu is usually not used on Bisq as UX element - I think it should be changed to some more visible solution).

**Comment by ripcurlx** [comment]
> Edit offer and duplication is not supported. Wanted to limit effort and see how much it will be used. Edit offer is also not really needed as BSQ offers have no maker fee at offer creation.

True - I forgot about that.

> The duplication feature should though be deactivated. But to be honest, it is so hidden that most users are not aware of it anyway I assume.... (right click context menu is usually not used on Bisq as UX element - I think it should be changed to some more visible solution).

I personally use it all the time. It is a power user feature, but I think it is a very used one. I'll have a look if I can add the support for it.
