### ISSUE TITLE
Bisq Telegram channel (bisqex) about to self-destruct

### ISSUE THREAD

**Issue by xanoni** [bisq-network/bisq#5871]
<img width="607" alt="image" src="https://user-images.githubusercontent.com/77220130/143671318-4dce3c67-d612-4818-91ac-f4962ca70525.png">

https://t.me/bisqex

saw this and thought maybe someone here might be able to fix it

**Comment by pazza83** [comment]
Hi @xanoni 

thanks for posting.

The correct group is: https://t.me/bisq_p2p

**Comment by xanoni** [comment]
k, if it is not one of the official channels, then I guess we don't care
