### ISSUE TITLE
Testing platform for latest Bisq will not run, reporting problems with blockchain sync

### ISSUE THREAD

**Issue by w0000000t** [bisq-network/bisq#5872]
### Description

I followed to the letter the instructions on the testing doc (+build.md + dev-setup.md).
I am running a Xubuntu Virtualbox VM with 6GB of RAM and 17GB VDD, installed bitcoin core 0.22 from the standard software repository, this is my `bitcoin.conf` contents:
```
server=1
regtest=1
peerbloomfilters=1
```

I start the seednode instance, then the arbi trator instance and register both arbitrator and mediator, then Alice and then Bob (4 separate terminal windows).
Every desktop instance keeps reporting "connecting to the bitcoin network" bottom left.
When I try and create any offer from the Alice or Bob I see the "bisq blockchain height no synced correctly [...] can try SPV resync", which I did on the Bob instance, that now won't start after the "SPV has been deleted" notification.
All desktop instances report bottom right 1 bitcoin network peer, and 3 bisq network peers.
#### Version

Latest as per build.md

### Steps to reproduce

Have linux VM, follow all instructions including running the linux java install sh script

### Expected behaviour

Being able to run the instances to simulate activity

### Actual behaviour

Cannot connect to the bitcoin network.

### Screenshots

//

#### Device or machine

VirtualBox 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

#### Additional info

Please request what needed

**Comment by ghost** [comment]
Sounds like Alice and Bob are having problems connecting to bitcoind.
You could search your log for "Error", "Connecting", "Connected".
Normally would expect something like the following in the log.  Could you post your log if you see something different.

    Nov-27 08:26:38.888 [ STARTING] INFO  b.c.btc.nodes.LocalBitcoinNode: Local Bitcoin node detected on port 18444 
    Nov-27 08:26:38.889 [ STARTING] INFO  b.core.btc.setup.WalletConfig: We try to connect to 1 btc nodes 
    Nov-27 08:26:38.927 [PeerGroup Thread] INFO  org.bitcoinj.core.PeerGroup: Starting ... 
    Nov-27 08:26:38.928 [JavaFX Application Thread] INFO  b.c.btc.model.AddressEntryList: Create AddressEntry for IssuedReceiveAddress. address=bcrt1qv5fvml868zhc3w27mxnfxrdff4t80czfn2fv49 
    Nov-27 08:26:38.941 [PeerGroup Thread] INFO  org.bitcoinj.core.PeerGroup: Localhost peer detected, trying to use it instead of P2P discovery 
    Nov-27 08:26:38.954 [PeerGroup Thread] INFO  org.bitcoinj.core.PeerGroup: Attempting connection to [127.0.0.1]:18444     (0 connected, 1 pending, 0 max) 
    Nov-27 08:26:38.976 [NioClientManager] INFO  o.b.net.NioClientManager: Connected to localhost/127.0.0.1:18444 
    Nov-27 08:26:38.976 [NioClientManager] INFO  org.bitcoinj.core.Peer: Announcing to localhost/127.0.0.1:18444 as: /bitcoinj:0.15.10.bisq.15/Bisq:1.8.0/ 
    Nov-27 08:26:39.003 [NioClientManager] INFO  org.bitcoinj.core.Peer: Peer{[127.0.0.1]:18444, version=70015, subVer=/Satoshi:0.19.0.1/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2021-11-27 08:26:38, height=518} 
    Nov-27 08:26:39.022 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 0 entries from SignedWitnessStorageService to the excluded key set of our request 
    Nov-27 08:26:39.023 [NioClientManager] INFO  org.bitcoinj.core.PeerGroup: Peer{[127.0.0.1]:18444, version=70015, subVer=/Satoshi:0.19.0.1/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2021-11-27 08:26:38, height=518}: New peer      (1 connected, 0 pending, 1 max) 
    Nov-27 08:26:39.024 [NioClientManager] INFO  org.bitcoinj.core.Peer: Peer{[127.0.0.1]:18444, version=70015, subVer=/Satoshi:0.19.0.1/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2021-11-27 08:26:38, height=518}: Sending Bloom filter and querying mempool

**Comment by w0000000t** [comment]
Problem is with arbitrator as well, all of the desktop instances permanently show "connecting to bitcoin network", here's my log though:

```
cat bisq/balice.log | grep -i -B 2 -A 12  localbitcoinnode
   nonce: 2
 
Nov-27 17:29:08.254 [ STARTING] INFO  b.c.btc.nodes.LocalBitcoinNode: Local Bitcoin node detected on port 18444 
Nov-27 17:29:08.255 [ STARTING] INFO  b.core.btc.setup.WalletConfig: We try to connect to 1 btc nodes 
Nov-27 17:29:08.290 [PeerGroup Thread] INFO  org.bitcoinj.core.PeerGroup: Starting ... 
Nov-27 17:29:08.293 [PeerGroup Thread] INFO  org.bitcoinj.core.PeerGroup: Localhost peer detected, trying to use it instead of P2P discovery 
Nov-27 17:29:08.300 [PeerGroup Thread] INFO  org.bitcoinj.core.PeerGroup: Attempting connection to [127.0.0.1]:18444     (0 connected, 1 pending, 0 max) 
Nov-27 17:29:08.330 [NioClientManager] INFO  o.b.net.NioClientManager: Connected to localhost/127.0.0.1:18444 
Nov-27 17:29:08.330 [NioClientManager] INFO  org.bitcoinj.core.Peer: Announcing to localhost/127.0.0.1:18444 as: /bitcoinj:0.15.10.bisq.15/Bisq:1.7.5/ 
Nov-27 17:29:08.332 [NioClientManager] INFO  org.bitcoinj.core.Peer: Peer{[127.0.0.1]:18444, version=70016, subVer=/Satoshi:22.0.0/, services=1036 (BLOOM, WITNESS, NETWORK_LIMITED), time=2021-11-27 17:29:08, height=105} 
Nov-27 17:29:08.335 [NioClientManager] INFO  org.bitcoinj.core.PeerGroup: Peer{[127.0.0.1]:18444, version=70016, subVer=/Satoshi:22.0.0/, services=1036 (BLOOM, WITNESS, NETWORK_LIMITED), time=2021-11-27 17:29:08, height=105}: New peer      (1 connected, 0 pending, 1 max) 
Nov-27 17:29:08.335 [NioClientManager] INFO  org.bitcoinj.core.Peer: Peer{[127.0.0.1]:18444, version=70016, subVer=/Satoshi:22.0.0/, services=1036 (BLOOM, WITNESS, NETWORK_LIMITED), time=2021-11-27 17:29:08, height=105}: Sending Bloom filter and querying mempool 
Nov-27 17:29:08.339 [NioClientManager] INFO  org.bitcoinj.core.PeerGroup: Not yet setting download peer because there is no clear candidate. 
Nov-27 17:29:08.341 [NioClientManager] INFO  org.bitcoinj.core.Peer: Peer{[127.0.0.1]:18444, version=70016, subVer=/Satoshi:22.0.0/, services=1036 (BLOOM, WITNESS, NETWORK_LIMITED), time=2021-11-27 17:29:08, height=105}: Announced fee filter: 0.00001 BTC/kB 
Nov-27 17:29:08.431 [JavaFX Application Thread] INFO  bisq.core.app.BisqSetup: walletInitialized=true, p2pNetWorkReady=false 

```

**Comment by ghost** [comment]
I noticed that your log differs in that the services are different.

- Yours `services=1036 (BLOOM, WITNESS, NETWORK_LIMITED)`
- Mine `services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED)`

This indicates that your bitcoind is not able to provide the full blockchain download, see https://old.reddit.com/r/Bitcoin/comments/8wkuod/full_node_node_network_limited_1037_what_does_it/

Coupled with the message `PeerGroup: Not yet setting download peer because there is no clear candidate. ` seems to be the problem.  Try to find out why your bitcoind is operating in pruned mode?  One of the flags I use with bitcoind is `prune=0`

**Comment by w0000000t** [comment]
By the holy cow, it was indeed running in pruned mode, even if I never authorized it to during the initial setup process, adding `prune=0` and restarting the node, all bisq instances reported successful connection and the current block height, thanks for the fast solution! Closing as solved :)
