### ISSUE TITLE
App remain in white screen on MacOS Big Sur 11.1 on M1

### ISSUE THREAD

**Issue by andoniabedul** [bisq-network/bisq#5877]
### Description

The app doesn't start and it doesn't gives you errors. Only white screen. 

#### Version

Bisq version: 1.7.5

### Steps to reproduce
1. Download.
2. Open the .dmg 
3. Drag the app to Applications folder
4. Open the app

### Expected behaviour

Open the app correctly.

### Actual behaviour

Remain in a white screen

### Screenshots

<img width="1274" alt="Captura de Pantalla 2021-11-28 a la(s) 20 36 15" src="https://user-images.githubusercontent.com/8060346/143783232-8a7e067a-3765-472f-bbd6-efb22d767178.png">

#### Device or machine

Mac OS version: Big Sur 11.1
Type of chip running: M1

#### Additional info

Trying to see whats going on, I opened the app as administrator using the command line, and I found this stack trace from Java:
Launching without sudo gives the same error. 

> λ ~/ sudo /Applications/Bisq.app/Contents/MacOS/Bisq
nov.-28 20:34:11.956 [main] INFO  bisq.common.util.Utilities: System info: os.name=Mac OS X; os.version=10.16; os.arch=x86_64; sun.arch.data.model=64; JRE=15.0.2+7 (AdoptOpenJDK); JVM=15.0.2+7 (OpenJDK 64-Bit Server VM)
nov.-28 20:34:12.013 [main] INFO  bisq.common.app.AsciiLogo:

                    ........                  ......
                ..............                ......
              .................               ......
            ......   ..........   ..          ......
           ......      ......   ......        ...............        .....     .........         ..........
          .......              ........       ..................     .....   .............     ...............
          ......               ........       ..........  .......    .....  ......   ...     ........   .......
         ......                   .....       .......        .....   .....  .....            .....        ......
         ......    ...        ...             ......         ......  .....   ...........    ......         ......
         ......   .....      ....             ......         ......  .....    ............  .....          ......
          ......                               .....         ......  .....         ........ ......         ......
           ......       ....        ...        ......       ......   .....    ..     ......  ......      ........
            ........     ..      .......        .................    .....  ..............    ...................
             ..........       .........           .............      .....   ............       .................
               ......................                 .....                      ....               ....   ......
                  ................                                                                         ......
                        ....                                                                               ......
                                                                                                           ......

> nov.-28 20:34:12.022 [main] INFO  bisq.common.app.Version: Version{VERSION=1.7.5, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=4, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10}
> nov.-28 20:34:12.023 [main] INFO  bisq.common.setup.CommonSetup: Path to Bisq jar file: /Applications/Bisq.app/Contents/app/desktop-1.7.5-all.jar
> nov.-28 20:34:12.026 [main] INFO  bisq.common.util.Profiler: Total memory: 128 MB; Used memory: 19.922 MB; Free memory: 108.078 MB; Max memory: 2 GB; No. of threads: 1
> nov.-28 20:34:12.051 [main] INFO  b.c.s.CoreNetworkCapabilities: TRADE_STATISTICS [0], TRADE_STATISTICS_2 [1], ACCOUNT_AGE_WITNESS [2], PROPOSAL [5], BLIND_VOTE [6], ACK_MSG [7], RECEIVE_BSQ_BLOCK [8], DAO_STATE [9], BUNDLE_OF_ENVELOPES [10], SIGNED_ACCOUNT_AGE_WITNESS [11], MEDIATION [12], REFUND_AGENT [13], TRADE_STATISTICS_HASH_UPDATE [14], NO_ADDRESS_PRE_FIX [15], TRADE_STATISTICS_3 [16]
> nov. 28, 2021 8:34:12 P.M. com.sun.javafx.application.PlatformImpl startup
> ADVERTENCIA: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @7857fe2'
> nov.-28 20:34:14.997 [AvoidStandbyModeService-thread] INFO  b.c.a.AvoidStandbyModeService: Started
> nov.-28 20:34:15.440 [JavaFX Application Thread] INFO  b.c.n.p.s.DefaultSeedNodeRepository: Seed nodes: [sn5emzyvxuildv34n6jewfp2zeota4aq63fsl5yyilnvksezr3htveqd.onion:8000, devinv3rhon24gqf5v6ondoqgyrbzyqihzyouzv7ptltsewhfmox2zqd.onion:8000, sn4emzywye3dhjouv7jig677qepg7fnusjidw74fbwneieruhmi7fuyd.onion:8000, sn4bsqpc7eb2ntvpsycxbzqt6fre72l4krp2fl5svphfh2eusrqtq3qd.onion:8000, sn2bisqad7ncazupgbd3dcedqh5ptirgwofw63djwpdtftwhddo75oid.onion:8000, wizseedscybbttk4bmb2lzvbuk2jtect37lcpva4l3twktmkzemwbead.onion:8000, devinsn2teu33efff62bnvwbxmfgbfjlgqsu3ad4b4fudx3a725eqnyd.onion:8000, devinsn3xuzxhj6pmammrxpydhwwmwp75qkksedo5dn2tlmu7jggo7id.onion:8000, sn3bsq3evqkpshdmc3sbdxafkhfnk7ctop44jsxbxyys5ridsaw5abyd.onion:8000, wizseed7ab2gi3x267xahrp2pkndyrovczezzb46jk6quvguciuyqrid.onion:8000, sn3emzy56u3mxzsr4geysc52feoq5qt7ja56km6gygwnszkshunn2sid.onion:8000, wizseed3d376esppbmbjxk2fhk2jg5fpucddrzj2kxtbxbx4vrnwclad.onion:8000]
> nov.-28 20:34:15.560 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Uncaught Exception from thread JavaFX Application Thread
> nov.-28 20:34:15.561 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableMessage= null
> nov.-28 20:34:15.561 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableClass= class java.lang.IllegalArgumentException
> nov.-28 20:34:15.563 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Stack trace:
> java.lang.IllegalArgumentException
> 	at java.base/java.util.Currency.getInstance(Unknown Source)
> 	at bisq.core.locale.CurrencyUtil.getCurrencyByCountryCode(CurrencyUtil.java:631)
> 	at bisq.core.user.Preferences.initNewPreferences(Preferences.java:279)
> 	at bisq.core.user.Preferences.lambda$readPersisted$6(Preferences.java:246)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
> 	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
> 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
> 
> java.lang.IllegalArgumentException
> 	at java.base/java.util.Currency.getInstance(Unknown Source)
> 	at bisq.core.locale.CurrencyUtil.getCurrencyByCountryCode(CurrencyUtil.java:631)
> 	at bisq.core.user.Preferences.initNewPreferences(Preferences.java:279)
> 	at bisq.core.user.Preferences.lambda$readPersisted$6(Preferences.java:246)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
> 	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
> 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
> nov.-28 20:34:15.569 [JavaFX Application Thread] WARN  bisq.desktop.app.BisqApp: Scene not available yet, we create a new scene. The bug might be caused by an exception in a constructor or by a circular dependency in Guice. throwable=java.lang.IllegalArgumentException

**Comment by ripcurlx** [comment]
@andoniabedul Did it work for you in older versions? Could you please provide us with your output if you run `locale` in the Terminal? Thanks!

**Comment by andoniabedul** [comment]
Hi @ripcurlx! Sorry but I didn't test older versions, this it's my first attempt to use Bisq. 

Sure, if I run `locale` I got this:

> LANG="es_ES.UTF-8"
> LC_COLLATE="es_ES.UTF-8"
> LC_CTYPE="es_ES.UTF-8"
> LC_MESSAGES="es_ES.UTF-8"
> LC_MONETARY="es_ES.UTF-8"
> LC_NUMERIC="es_ES.UTF-8"
> LC_TIME="es_ES.UTF-8"
> LC_ALL=

I will try with older versions to see if I have different results. I will update the comments if I have different results. 

Regards, it's a pleasure for me help on something :-)

**Comment by ripcurlx** [comment]
Ah - I just read that you are running on an M1 chip. I personally haven't tried to run an existing binary with that setup. 
@cbeams Are you able to run v1.7.5 on your M1 machine?

**Comment by cbeams** [comment]
Building and running from source is a problem on an M1, per #5835, but I have no problem running the binary dmg distribution on Big Sur 11.2.3. Looking at the stack trace, I too thought maybe a malformed locale ID is causing the problem, but the above looks sane enough.

**Comment by andoniabedul** [comment]
I tested with 1.7.4 and it has the same result: white screen. I was thinking that maybe the issue it was that I don't have setted the LC_ALL, but I setted and nothing changed. 

I'm thinking in change the locale of my machine to see if I have the same error.

**Comment by Lenninlasd** [comment]
Same error, white screen but in MacOs Monterey, but Intel Core i9

![image](https://user-images.githubusercontent.com/7197750/152561108-efd74962-51b1-4659-b29a-d4d32ade8149.png)

```
feb. 04, 2022 10:54:25 A.M. com.sun.javafx.application.PlatformImpl startup
ADVERTENCIA: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @69c81773'
feb.-04 10:54:28.719 [AvoidStandbyModeService-thread] INFO  b.c.a.AvoidStandbyModeService: Started 
feb.-04 10:54:28.799 [JavaFX Application Thread] INFO  b.c.n.p.s.DefaultSeedNodeRepository: Seed nodes: [devinsn3xuzxhj6pmammrxpydhwwmwp75qkksedo5dn2tlmu7jggo7id.onion:8000, wizseed3d376esppbmbjxk2fhk2jg5fpucddrzj2kxtbxbx4vrnwclad.onion:8000, wizseed7ab2gi3x267xahrp2pkndyrovczezzb46jk6quvguciuyqrid.onion:8000, sn3bsq3evqkpshdmc3sbdxafkhfnk7ctop44jsxbxyys5ridsaw5abyd.onion:8000, devinsn2teu33efff62bnvwbxmfgbfjlgqsu3ad4b4fudx3a725eqnyd.onion:8000, sn2bisqad7ncazupgbd3dcedqh5ptirgwofw63djwpdtftwhddo75oid.onion:8000, sn5emzyvxuildv34n6jewfp2zeota4aq63fsl5yyilnvksezr3htveqd.onion:8000, devinv3rhon24gqf5v6ondoqgyrbzyqihzyouzv7ptltsewhfmox2zqd.onion:8000, sn3emzy56u3mxzsr4geysc52feoq5qt7ja56km6gygwnszkshunn2sid.onion:8000, sn4emzywye3dhjouv7jig677qepg7fnusjidw74fbwneieruhmi7fuyd.onion:8000, sn4bsqpc7eb2ntvpsycxbzqt6fre72l4krp2fl5svphfh2eusrqtq3qd.onion:8000, wizseedscybbttk4bmb2lzvbuk2jtect37lcpva4l3twktmkzemwbead.onion:8000] 
feb.-04 10:54:28.876 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
feb.-04 10:54:28.876 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableMessage= null 
feb.-04 10:54:28.877 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableClass= class java.lang.IllegalArgumentException 
feb.-04 10:54:28.878 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Stack trace:
java.lang.IllegalArgumentException
	at java.base/java.util.Currency.getInstance(Unknown Source)
	at bisq.core.locale.CurrencyUtil.getCurrencyByCountryCode(CurrencyUtil.java:637)
	at bisq.core.user.Preferences.initNewPreferences(Preferences.java:279)
	at bisq.core.user.Preferences.lambda$readPersisted$6(Preferences.java:246)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
 
java.lang.IllegalArgumentException
	at java.base/java.util.Currency.getInstance(Unknown Source)
	at bisq.core.locale.CurrencyUtil.getCurrencyByCountryCode(CurrencyUtil.java:637)
	at bisq.core.user.Preferences.initNewPreferences(Preferences.java:279)
	at bisq.core.user.Preferences.lambda$readPersisted$6(Preferences.java:246)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```

**Comment by andoniabedul** [comment]
Great! I'm confirm that this issue it doesn't happen anymore on Bisq 1.8.4

Thanks!
