### ISSUE TITLE
Deprecated Gradle features causing error in v1.7.5

### ISSUE THREAD

**Issue by rszyma** [bisq-network/bisq#5881]
I wanted to install the latest v1.7.5 build from AUR on Manjaro Linux using `yay -S bisq` but it failed with an error. Then I tried building bisq from source - still the same error:

```
$ make
./gradlew :seednode:build

> Configure project :
Project :common => no module-info.java found
Project :p2p => no module-info.java found
Project :core => no module-info.java found
Project :desktop => no module-info.java found
Project :monitor => no module-info.java found
Pricenode: Skipping spot provider tests

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':desktop'.
> Checksum failed for com.github.JesusMcCloud:jtorctl:389d61b1b5a85eb2f23c582c3913ede49f80c9f2b553e4762382c836270e57e5

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
make: *** [Makefile:120: seednode/build] Error 1

```

**Comment by ripcurlx** [comment]
This is a known issue: https://github.com/bisq-network/bisq/issues/5807

On master this was solved as we now accept both hashes for now after we verified the content of the delivered jar files.
As this was solved by doing a major gradle build file change to support also the latest gradle version, your best shot is to update the hash with `6465e0b22b921344a065a6e82a5390ab2f9dac5ab293c38bd8a76baddead6492` in the gradle-witness file and try to build it again.

**Comment by rszyma** [comment]
Where do I find `gradle-witness` file? I couldn't find it in this repo.

**Comment by ripcurlx** [comment]
If you checkout the v1.7.5 tag or release branch you'll find it in `gradle/witness/gradle-witness.gradle` file it will look like:
```
...
'com.github.JesusMcCloud:jtorctl:389d61b1b5a85eb2f23c582c3913ede49f80c9f2b553e4762382c836270e57e5',
...
```

You need to change this into
```
'com.github.JesusMcCloud:jtorctl:6465e0b22b921344a065a6e82a5390ab2f9dac5ab293c38bd8a76baddead6492',
```

That should work IMO.
