### ISSUE TITLE
[1.8.0] New user DAO sync required 4 restarts to complete

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#5882]
### Description

Starting Bisq v1.8.0 with a fresh data directory, the initial DAO sync threw up a reboot popup 4 times.
Logs attached.

### Steps to reproduce

Run Bisq release/v1.8.0 with a fresh data directory, connect to local bitcoind.

### Expected behaviour

DAO sync fast and painless.

### Actual behaviour

It required restart of the app 4 times; each after the message in the log `The RECIPIENT_BTC_ADDRESS is not as expected. The DAO state is probably out of sync and a resync should fix that issue`

### Screenshots

![image](https://user-images.githubusercontent.com/47253594/144145446-503ad4f4-c535-460d-85ac-0a29c81b0007.png)

#### Additional info

Once the BTC chain sync completed, the DAO sync seemed to go smoothly, see log after 4th restart.
[bisq.log](https://github.com/bisq-network/bisq/files/7629556/bisq.log)

**Comment by ripcurlx** [comment]
I saw the same with an old user directory. I haven't tried it 4 times yet, but after the second restart it is still popping up for me as well.

**Comment by ripcurlx** [comment]
The address that was causing this warnings for me is `3A8Zc1XioE2HRzYfbb5P8iemCS72M6vRJV` (Burningman 2). It looks like as if the fee param validation check on startup is triggered before the client was able to sync the DAO.

**Comment by ripcurlx** [comment]
With a fresh user directory the initial DAO sync works just fine, but when I look at the DAO monitor it is complaining.
<img width="1312" alt="Bildschirmfoto 2021-12-01 um 16 06 42" src="https://user-images.githubusercontent.com/170962/144259628-d374feb9-d31b-4492-9746-8e4be77e7108.png">

What looks suspicious to me is that for block 712099 the hash is generated by the node itself, but for the next block it is taken from a Peer, which is kind of odd.

**Comment by chimp1984** [comment]
> With a fresh user directory the initial DAO sync works just fine, but when I look at the DAO monitor it is complaining. 
> 
> What looks suspicious to me is that for block 712099 the hash is generated by the node itself, but for the next block it is taken from a Peer, which is kind of odd.

Could you reproduce that?
