### ISSUE TITLE
Bitsquare 0.4.9.3 crashes randomly on Debian Jessie 32bit

### ISSUE THREAD

**Issue by ElLamparto** [bisq-network/bisq#589]
I see nothing special in the log (attached).
Bitsquare crashes randomly while left alone (with no user interaction). It may take 2 hours or 2 days before the crash occures.
[bitsquare.zip](https://github.com/bitsquare/bitsquare/files/437707/bitsquare.zip)

**Comment by ManfredKarrer** [comment]
There have been a lot of Saw duplicated block in main chain at height... maybe that is the reason?

**Comment by ElLamparto** [comment]
What can be done about it?
Can such a crash damage data? If so, does making backups at every step of a transaction provide sufficient security?
By the way, thank you for your magnificent piece of software. Brilliant work!

**Comment by ManfredKarrer** [comment]
There is a rolling backup mechanism in the app. How does the crash appear? Is it that the app becomes not resonding? Can you test it on another system? Maybe there are issues with graphic drivers? JavaFX seems to not work 100% reliable on all systems :-(

**Comment by ElLamparto** [comment]
No, the application does not freeze. It disappears completely. There is a small anomaly: often when Bitsquare is running, there is a small, static rectangle in the upper left corner of the screen (below the panel bar).

![blacksquare](https://cloud.githubusercontent.com/assets/9163437/18029213/4220b4a2-6c92-11e6-8e6b-f2523e904eb1.png)

It may be an issue of the graphic drivers, who knows....

I am in the middle of my first transaction :-) It is incredible how you keep the user informed every step of the way and how you anticipate user mistakes. Congratulations again!

**Comment by ManfredKarrer** [comment]
Yes that black rectable sounds like a graphic driver issue...

Thanks! Still much to improve but getting better ;-)
