### ISSUE TITLE
Make it easier for users to provide logs to mediators and support agents

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#5906]
### Description

When traders experience a bug mediators and support staff will often request copies of the users logs to diagnose the issue. For trade bugs it is often the case that both buyers and sellers logs are required to understand what went wrong.

Currently it is can be difficult for users to provide logs, especially if they are less technical, or just not experienced providing them before. 

As it can be difficult for users to provide logs the request for logs can often be quite tedious for users, and, therefore, is often ignored. This makes diagnosing issues harder. 

Some of the things that make it difficult are:

- Logs are found mixed in with the Bisq root data directory
- Different operating systems have the Bisq root data directory in different default locations
- The size of log files mean they cannot be sent as attachments in mediator chat in Bisq
- Lack of wiki detailing how to provide logs files.

#### Version

1.7.5

### Proposed behaviour

1. Change the location of logs in the data directory to `Bisq\Logs` This will mean all logs are in one place and easily distinguishable as logs files.
2. Maybe change formatting of log files rename to bisq-log-1, bisq-log-2, etc this would make it easier for users to identity logs an not over look bisq.log being a log file.
3. Decrease the size of the logs so they can be sent within mediator chat messages OR Increase the size of the files that can be sent in mediator chat messages to allow for the sending of logs
4. Add a shortcut to Bisq App > setting > About to automatically open Bisq log files folder eg `'Ctrl + l' or 'alt + l' or 'cmd + l'` opens Data directory log folder in user's operating system. This would make it easier for support agents to request log files.
5. Add a button on mediation chat to `Attach log file` this would make it easy for mediators to request logs (subject to no.3 being achievable). 
6. Create a wiki page detailing how users can provide logs and include link to other relevant wiki pages.

**Comment by ghost** [comment]
Good proposal.  Might be easier for that manual process to be done by Bisq from a button like "`Send logs to Mediator`" in the support UI or other suitable place.

- have Bisq zip the logs up in an archive (`java.util.zip`).
- have Bisq transmit the file to the mediator by direct message instead of trader chat.


[edit] Volunteering myself to implement this.  :point_up:   :thinking:
