### ISSUE TITLE
Cannot sell BTC

### ISSUE THREAD

**Issue by shubrich76** [bisq-network/bisq#591]
No value present error - just reporting it!

**Comment by shubrich76** [comment]
[Screen Shot 2016-08-30 at 2.24.24 PM.png](https://postimg.org/image/di9jxznth/)

I have tried restarting.

I am unable to locate bit square.log file since I'm on mac os

**Comment by ManfredKarrer** [comment]
Do u have the latest version installed?

**Comment by shubrich76** [comment]
I will try that now!

**Comment by shubrich76** [comment]
That worked! Thank you
