### ISSUE TITLE
wrong available wallet balance after consolidate UTXOs in Electrum

### ISSUE THREAD

**Issue by romanneuromancer** [bisq-network/bisq#5912]
### Description

My Bisq client displays a wrong wallet balance after I imported my Bisq wallet in Electrum to consolidate my UTXOs. I used Electrum to save fees, because Bisq doesn't allow 1 sat/vbyte tx. Of cause no offer or trade was open by myself.

#### Version

Bisq version 1.7.5

### Steps to reproduce

1. Import Bisq wallet in Electrum (with its BIP39 seed)
2. Consolidate UTXOs (do a self send)
3. Restart Bisq

### Expected behaviour

Bisq displays my right balance, like Electrum does.

### Actual behaviour

In Electrum everything works as expected (all my funds are there). Opening my wallet in Bisq now, the `available balance` is wrong. Every UTXOs which got used inside Electrum is "gone" in my Bisq `available balance`, but haveing a look in `Account` --> `Wallet info` the correct balance is shown. Have a look at the attachment below, basically my issue is that these 2 balances are not the same.

### Screenshots

![bisq_error](https://user-images.githubusercontent.com/62653718/145676686-e49d0ed4-6e0e-44ae-b0e7-506c7770461e.JPG)

#### Device or machine

same on both os:
Win10 64bit
Ubuntu 20.04 LTS

**Comment by romanneuromancer** [comment]
I already found out how to fix this issue, but I think it is bad UX so I want to report is anyways.
To fix it, I need to (self) send to the exact same address Bisq is providing. E.g.:
![bisq_addresses](https://user-images.githubusercontent.com/62653718/145676626-88fc4881-0c41-4d5e-9b14-2a596c989aa7.JPG)
I need to self send my UTXOs which I want to consolidate to that first address in the list (marked with green). When using an address out of Electrum which also belongs to this wallet, than that balance won't be availbale in Bisq.

## Conclusion
To fix this issue, I need to generate an address with Bisq and consolidate my UTXOs to **this** address.

**Comment by ghost** [comment]
Bisq [wallet](https://bisq.wiki/Wallet) uses non standard derivation path. It could be reason of your troubles.
