### ISSUE TITLE
v1.8.0 BSQ swap offers falsely advertise ability to set minimum amount

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#5913]
When creating a BSQ swap offer, the form allows the user to set a minimum amount, but the minimum amount ends up being ignored and the only value published in the actual offer is the maximum amount. That is presumably due to constraints inherent in the swap protocol, but the form should disallow the minimum amount option so as not to confuse or mislead users.

**Comment by ripcurlx** [comment]
Why do you think so? I just tested it again on Regtest to be sure and it works as expected (see screenshots)
<img width="1301" alt="Bildschirmfoto 2021-12-12 um 10 22 16" src="https://user-images.githubusercontent.com/170962/145707043-d9fc68d7-7ec1-47a4-b5c9-54b2de573769.png">
<img width="1442" alt="Bildschirmfoto 2021-12-12 um 10 22 31" src="https://user-images.githubusercontent.com/170962/145707040-0732f7da-9425-4c5d-853a-88bca4246fd8.png">
<img width="1442" alt="Bildschirmfoto 2021-12-12 um 10 22 49" src="https://user-images.githubusercontent.com/170962/145707032-74b8f3f3-0e2d-4735-aaab-37a6f4bc99b3.png">

**Comment by cbeams** [comment]
Great! Must have been user error on my part. Closing as invalid, thanks.
