### ISSUE TITLE
Trade failed at task TakerVerifyAndSignContract

### ISSUE THREAD

**Issue by dgyg** [bisq-network/bisq#5916]
### Description

Trade failed with _An error occurred at task: TakerVerifyAndSignContract_ at the maker side:

```
Dec-14 20:17:27.522 [JavaFX Application Thread] WARN  b.c.t.p.b.DisputeProtocol: Received AckMessage with error state for 
InputsForDepositTxResponse from XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.onion:9999 with tradeId 
XXXXX-XXXXXXX-XXX-XXXX-XXXX-XXXXXXXXXX-XXX and errorMessage=An error occurred at task: TakerVerifyAndSignContract
Contracts are not matching 
```
#### Version

v1.8.0 (maker)
unkown (taker)

#### Additional info

Payment Method: National Bank Transfer

Possible related forum thread: https://bisq.community/t/failed-taker-after-v1-8-0/11273

**Comment by ghost** [comment]
In your `bisq.log` it will have listed out both contracts (search for `WARN b.c.t.Contract`), you can paste them into a [diff tool](https://www.w3docs.com/tools/code-diff/) and it will show you what did not match.  In previous ones I've seen, it was the % price that was different.  Would be useful if you could let us know what is not matching in your case.

Here's an example:

![image](https://user-images.githubusercontent.com/47253594/146080849-42adf3ce-920b-40bd-8eb3-7b8228d5e826.png)

**Comment by ghost** [comment]
The issue is an incompatibility between old and new Bisq versions due to some fields removed from the trade contract.  Expect an update from @ripcurlx soon.

Thankyou for reporting it.

**Comment by dgyg** [comment]
@jmacxx Thanks for your answer

There is no other log statement on Level WARN in my log file around this time. Maybe there is older log configuration active on my machine.

But I found this:
```
Dec-14 20:09:43.891 [JavaFX Application Thread] INFO  b.c.offer.Offer: Price at take-offer time: 
id=XXXXXX, currency=XXX, takersPrice=4XXXXXXXX, makersPrice=4XXXXXXXX, deviation=0.01659913537079838%
```
Did the indicated deviation of 0.01659913537079838% triggered the failure?

Interesting is the time difference of 7 minutes and 44 seconds between that statement and the final failure at 20:17:27.

**Comment by ghost** [comment]
Ah yes, indeed looking at your original error at the top of this post, it was your trade counterparty that sent a (N)ACK with the error message to you.  We're solving this trading incompatibility between versions by making >= v1.8.0 mandatory, older clients will be prompted to upgrade.
