### ISSUE TITLE
heightOfLastBlock must match chainHeight

### ISSUE THREAD

**Issue by SiweiGIT** [bisq-network/bisq#5917]
### Description

When opening BISQ, I get the error and it doesnt connect to TOR.
Recently upgraded to Windows 11 and to BISQ 1.8

#### Version

1.8.0
### Steps to reproduce

Double click to open BISQ, happens every time

### Expected behaviour

Succesfully open BISQ

### Actual behaviour

Not able to load BISQ, throws error : heightOfLastBlock must match chainHeight and displays reporting options.

#### Device or machine

Windows 11

#### Additional info

[bisq.log](https://github.com/bisq-network/bisq/files/7715174/bisq.log)

**Comment by ghost** [comment]
@SiweiGIT it is being looked into, apologies for the delay.

**Comment by ghost** [comment]
It looks like a bug where the Dao state files have become corrupted.  After encountering the same error, what worked for me ([make a backup first](https://bisq.wiki/Backing_up_application_data#While_Bisq_is_closed)) was to close Bisq, delete `DaoStateStore` and `BsqBlocks` from the [data directory](https://bisq.wiki/Data_directory), and then restart Bisq.

**Comment by SiweiGIT** [comment]
> It looks like a bug where the Dao state files have become corrupted. After encountering the same error, what worked for me ([make a backup first](https://bisq.wiki/Backing_up_application_data#While_Bisq_is_closed)) was to close Bisq, delete `DaoStateStore` and `BsqBlocks` from the [data directory](https://bisq.wiki/Data_directory), and then restart Bisq.

This worked perfectly, I'm now back online, thanks jmacxx!

**Comment by so7ow** [comment]
Seeing the same "heightOfLastBlock must match chainHeight" error on Bisq 1.8.0 but no DaoStateStore to delete. Should I open a new issue?

**Comment by jmacxx** [comment]
What is the directory path you are looking in & what files do you see?
