### ISSUE TITLE
Wrong reference to "Sepa instant" where normal sepa account was selected

### ISSUE THREAD

**Issue by w0000000t** [bisq-network/bisq#5919]
### Description

The "send payment" dialogue after seller taker accepted my offer is telling me to "start payment using sepa instant"; the account I used is normal sepa.
#### Version

1.8.0
### Steps to reproduce

have a buy offer taken by seller using normal sepa account
### Expected behaviour

seeing "sepa" instead of "sepa instant"
### Actual behaviour

sepa instant is requested as payment method
### Screenshots

![instant](https://user-images.githubusercontent.com/95026987/146199557-2c4549b9-3134-4b04-b5b3-68c2ab18cef1.jpg)

#### Device or machine

windows 10

**Comment by ghost** [comment]
I was not able to reproduce this issue using localnet. I've tried scenario:

1) Bob: create two accounts - SEPA and SEPA Instant
2) Bob: create offer for buy BTC for EURO
 A) Choose **SEPA** account in "Select trading account" section
 B) Choose **SEPA Instant** account in "Select trading account" section
3) Alice: take offer for sell BTC
4) Bob: check send payment dialogue
 A) Bob see "Start payment using SEPA" heading
 B) Bob see "Start payment using SEPA Instant Payments" heading
 
 I tried a few times and I always saw heading that corresponds to the choice I made in second step. I reviewed code and don't see anything suspicious there. 
 
 
 @w0000000t A few questions that might be helpful for further debugging:
 1) Do you have both - SEPA and SEPA Instant accounts created in Account tab?
 2) Are you sure you have chosen "SEPA" during offer creation? 
 3) Could you find this trade in _Portfolio -> History_, open details popup and check which account you see in "BTC buyer payment details"?

**Comment by w0000000t** [comment]
1. Yes, multiple SEPA and SEPA Instant with multiple EU-only or all countries selected
2. Absolutely, couldn't have made that offer with the still unaged SEPA Instant version of the account
3. I could not identify for certain the trade where this happened, yet I am 100% sure it was the non-instant SEPA account, I created the instant version later on but I have never used it yet.

**Comment by ghost** [comment]
Thank you @w0000000t - I'll check if there is something suspicious in the code. If you have or you'll find any additional information that might be helpful here please share them

**Comment by w0000000t** [comment]
I actually don't plan to use SEPA anymore for other reasons, but in case I do, count on it!

**Comment by Android-X13** [comment]
I confirm that this happens exactly as outlined in the OP and it creates a sort of confusion to the buyer...
Added a fix
