### ISSUE TITLE
No payout transaction after dispute ticket closed

### ISSUE THREAD

**Issue by LaxtonRush** [bisq-network/bisq#592]
A trade did not go through before the time ran out.  Dispute was opened and closed.

Summary note: "buyer had crash and did not see XMR address of peer"

There was a payout amount that I have not received as the seller. No refund has been posted.

transaction ID: 69c5a026-9d5f-4554-b1e5-fcc8280ab0cd

**Comment by ManfredKarrer** [comment]
i am traveling, will look tonight into it

**Comment by haiqu** [comment]
I assume this was resolved and can be closed?

**Comment by ManfredKarrer** [comment]
I will look into it in the next days.

**Comment by LaxtonRush** [comment]
I still do not see any refund from this trade.

**Comment by ManfredKarrer** [comment]
@LaxtonRush Can you send me an email with the trade ID (manfred at Bitsquare io)?
