### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#5920]
[ 10.66.66.2/32 ] [ /dev/pts/17 ] [~]
→ yay -S bisq
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  bisq-1.7.5-1

  1 bisq                                     (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: PKGBUILD up to date, Skipping (1/0): bisq
  1 bisq                                     (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: (1/1) Parsing SRCINFO: bisq
==> Making package: bisq 1.7.5-1 (Wed 15 Dec 2021 07:26:48 PM UTC)
==> Retrieving sources...
  -> Found bisq-1.7.5.tar.gz
  -> Found bisq-1.7.5.tar.gz.asc
  -> Found bisq.desktop
==> Validating source files with sha256sums...
    bisq-1.7.5.tar.gz ... Passed
    bisq-1.7.5.tar.gz.asc ... Skipped
    bisq.desktop ... Passed
==> Verifying source file signatures with gpg...
    bisq-1.7.5.tar.gz ... Passed
==> Making package: bisq 1.7.5-1 (Wed 15 Dec 2021 07:26:49 PM UTC)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found bisq-1.7.5.tar.gz
  -> Found bisq-1.7.5.tar.gz.asc
  -> Found bisq.desktop
==> Validating source files with sha256sums...
    bisq-1.7.5.tar.gz ... Passed
    bisq-1.7.5.tar.gz.asc ... Skipped
    bisq.desktop ... Passed
==> Verifying source file signatures with gpg...
    bisq-1.7.5.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting bisq-1.7.5.tar.gz with bsdtar
==> Sources are ready.
==> Making package: bisq 1.7.5-1 (Wed 15 Dec 2021 07:26:52 PM UTC)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
  -> Building bisq...

> Configure project :
Project :common => no module-info.java found
Project :p2p => no module-info.java found
Project :core => no module-info.java found
Project :desktop => no module-info.java found
Project :monitor => no module-info.java found
Pricenode: Skipping spot provider tests

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':desktop'.
> Checksum failed for com.github.JesusMcCloud:jtorctl:389d61b1b5a85eb2f23c582c3913ede49f80c9f2b553e4762382c836270e57e5

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: bisq

**Comment by ripcurlx** [comment]
@ech1 Please try out our latest release v1.8.0 or master which should solve your issues.
