### ISSUE TITLE
The same Trade exists as failed and completed

### ISSUE THREAD

**Issue by Der-Stephan** [bisq-network/bisq#5921]
After getting notified, that someone accepted my offer, i did the suppoesed SEPA payment and clicked on the payment sent button afterwards. Surprisingly the Trade was instantly ready and i took it on the Bisq wallet. Now i have the same Trade ID in completed and in failed. I first wondered about a completed payment transaction, until i noticed that it has the payment ID of a previous succesful trade.
I unfortunately cannot chat with the trade partner of the "supposedly completed trade", while i can with the one of the failed trade, which is another one.
What can i do now?

**Comment by ghost** [comment]
The issue you described sounds quite complex so it would be best if you could go on Keybase and DM your mediator (they have the same ID on keybase).  https://bisq.wiki/User_support#Via_Keybase_chat

Look in the trade contract to [find your mediator](https://bisq.wiki/Finding_your_mediator) (click on trade id, trade details => click on `detail data`).  Mediator is listed at the bottom of the contract info.
