### ISSUE TITLE
Closed trade pays out to Bisq wallet before user chooses fund destination

### ISSUE THREAD

**Issue by kev-vl** [bisq-network/bisq#5922]
### Description

This is possibly just 'how it works', but the following leads to unexpected behavior.
When completing a trade, the user is offered two options: 

1. Keeping funds in the Bisq wallet, or... 
2. withdrawing to an external wallet. 

The payout from the escrow however, first is to the user's Bisq wallet regardless of the user's choice. The choice of the user affects the coins that have already been paid out from the escrow as a result of the completed trade and effectively represent a choice between: 

1. Doing nothing (Keep funds in Bisq wallet), or..
2. 'forward' the received funds from Bisq wallet to an external wallet..

#### Version

1.8.0

### Steps to reproduce

1. Close a trade
2. Choose to withdraw funds to an external wallet

### Expected behaviour

The escrow pays out to the Bisq wallet or an external wallet based on the user's choice when completing the trade.

### Actual behaviour

The escrow payout is to the Bisq wallet. The funds either remain there or are 'forwarded' to an external address when choosing 'Keep funds in Bisq wallet' or 'Withdraw to external wallet', respectively.

#### Device or machine

Intel-based, macOS 12

**Comment by pazza83** [comment]
Hi @kev-vl thanks for this.

I agree this wording wording is a little confusing .

Any ideas on what the wording should say to make for a more clear user experience?

**Comment by kev-vl** [comment]
I don't have a closing trade at the moment so I took a still from BTCSession's YT vid.

<img width="387" alt="Bisq_complete_trade" src="https://user-images.githubusercontent.com/40802941/146456488-9fdaffc6-2bd5-4bd2-9eeb-2f38aa3712bf.png">

I think the confusion comes from the "Withdraw your bitcoin" section title in combination with the options. It implies that the bitcoin is still sitting in escrow and moving to either your Bisq wallet or an external wallet as a result of your choice. 

It's hard to come up with better wording for this. Maybe the "Withdraw your bitcoin" section should be removed altogether, and replaced with a mention that funds have been deposited to the Bisq wallet and a "Close trade" button. The section currently provides no other functionality than a send with coin-control, which is also available in the wallet if the user wants to withdraw the funds.

It could be interesting to give the user the option to provide an external wallet address when making/taking a trade where the escrow payout is sent, that would cover the functionality that I expected of this section.

**Comment by ghost** [comment]
See https://github.com/bisq-network/bisq/discussions/5410 and https://github.com/bisq-network/bisq/pull/5870#issuecomment-980492455

**Comment by kev-vl** [comment]
Thanks @jmacxx, it seems that the issue is already actively being discussed/worked on elsewhere, closing.
