### ISSUE TITLE
Startup error - heightOfLastBlock must match chainHeight

### ISSUE THREAD

**Issue by Olugbo** [bisq-network/bisq#5925]
### Description

heightOfLastBlock must match chainHeight
[Uploading bisq.log…]()

**Comment by ghost** [comment]
Thanks for reporting it, it helps us know there's something that needs to be looked into.
There's a workaround fix here => https://github.com/bisq-network/bisq/issues/5917#issuecomment-994911406

**Comment by Olugbo** [comment]
great. fix worked. thanks
