### ISSUE TITLE
Crash upon reopening app after attempting to reset wallet from seed.

### ISSUE THREAD

**Issue by hotdocMD** [bisq-network/bisq#5929]
#### Additional info

[](url
[bisq.log](https://github.com/bisq-network/bisq/files/7747571/bisq.log)
)

**Comment by ghost** [comment]
Thanks @hotdocMD.  That issue is being looked into.
There's a workaround fix described here:  https://github.com/bisq-network/bisq/issues/5917#issuecomment-994911406

**Comment by ghost** [comment]
@ripcurlx https://github.com/bisq-network/bisq/pull/5935 is merged, so this issue could be closed I suppose
