### ISSUE TITLE
Cannot invoke "bisq.core.locale.TradeCurrency.getCode()" because "currency" is null 

### ISSUE THREAD

**Issue by ArmandoRampas** [bisq-network/bisq#5932]
Hi,

I was setting up a new Transferwise account.

I added my email, selected only the EUR currency, and I got this error message when I was trying to take an offer to buy btc:

Cannot invoke "bisq.core.locale.TradeCurrency.getCode()" because "currency" is null 

![error](https://user-images.githubusercontent.com/96501539/147004434-ac786952-76b1-4dd8-9f8b-bbc0e4bb60d0.jpg)

Please find attached the Bisq log file.

Any suggestions?

Thanks!

[bisq.log](https://github.com/bisq-network/bisq/files/7758612/bisq.log)

**Comment by ghost** [comment]
@ArmandoRampas thanks for reporting this.  The problem is being investigated.

As a temporary workaround, delete the account and re-create it with more than one selected currency.
