### ISSUE TITLE
Graph altcoin prices indistinguishable.  Show 8 decimal places instead.

### ISSUE THREAD

**Issue by peertrade** [bisq-network/bisq#594]
The prices (BTC denominated) on the X axis are all the same.  It seems that 8 decimal digits should be displayed instead of 4.  at least in cases where the amounts are smaller than 0.001.

![screen](https://cloud.githubusercontent.com/assets/6629088/18232944/6215e356-728f-11e6-91c6-3438f9370f68.png)

**Comment by ManfredKarrer** [comment]
Thanks for reporting. Fixed for next version.
