### ISSUE TITLE
Does not start the bisq

### ISSUE THREAD

**Issue by Lucas-Ed** [bisq-network/bisq#5945]
### Description

log: out.-25 14:58:27.592 [JavaFX Application Thread] INFO  b.c.d.n.p.BlockParser: Parsing 0 transactions at block height 702097 took 952 ms 

#### Version
 1.8.0
![bisq](https://user-images.githubusercontent.com/30055762/147880164-cb8ac7cf-8707-4c06-9884-3596cc3ac0c8.png)

**Comment by ghost** [comment]
To resolve, see https://github.com/bisq-network/bisq/issues/5917#issuecomment-994911406.

**Comment by Lucas-Ed** [comment]
I managed to solve here following comment #5917, thank you!
