### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by MarcSte** [bisq-network/bisq#595]
Error with no interaction: java.lang.UnsupportedOperationException

Win10 64

Bitsquare 0.4.9.6

**Comment by ManfredKarrer** [comment]
Can you send me the logs?

**Comment by claudineyns** [comment]
I have been facing the same issue.
See log:
[bitsquare.txt](https://github.com/bitsquare/bitsquare/files/461730/bitsquare.txt)

**Comment by ManfredKarrer** [comment]
Thanks for reporting. Found the issue and will be fixed in next release.

**Comment by claudineyns** [comment]
What is the expectation for next release?

**Comment by ManfredKarrer** [comment]
Depends on how many critical issues arise. I need to work on the synergetic cooperation, so did not plan a new release soon. But a minor release with some smaller fixes might get out.
Though that issue should not be too critical. If the offer book looks strange after that, do a restart.
