### ISSUE TITLE
Trade failed - Buy BTC with XMR

### ISSUE THREAD

**Issue by Chalas21** [bisq-network/bisq#5954]
Please, I need help!
[bisq.log](https://github.com/bisq-network/bisq/files/7827297/bisq.log)

**Comment by Chalas21** [comment]
Trade ID: Fkpoh-f77ca661-f732-4f0a-831d-1b6fbb8614a6-180

**Comment by Chalas21** [comment]
My BTC are reserved and I can't move. I try reopen but failed. How I proceed?

**Comment by ghost** [comment]
Looking at the log file, I do not see any funds reserved.  It looks like a trade which failed to start.

Does your Funds -> `Reserved Funds` screen list any reserved funds?

Try an SPV resync.  https://bisq.wiki/Resyncing_SPV_file#From_the_Bisq_interface

**Comment by Chalas21** [comment]
I try an SPV resync, but didnt work. 
After the trade start failed my funds were in the reserved tab. I put the transaction as failed. Then I tried to reopen it but got an error message.![20220107_195731.jpg](https://user-images.githubusercontent.com/97278944/148618400-583d4e33-28c6-4b0d-8426-a35d0c33eae2.jpg)![20220107_195748.jpg](https://user-images.githubusercontent.com/97278944/148618425-bdccc2d7-d370-4c98-b0c3-9227918b72ce.jpg)![20220107_195802.jpg](https://user-images.githubusercontent.com/97278944/148618438-4fd220a7-04ae-4aba-960d-5ef170913540.jpg)![20220107_200645.jpg](https://user-images.githubusercontent.com/97278944/148618593-5022c8ce-82ac-46a3-8bcd-1f54645f0996.jpg)

**Comment by ghost** [comment]
Your reserved funds should add up to what is reserved for your open offers.  Check the screen Funds -> Reserved funds.

**Comment by Chalas21** [comment]
Cheers man! Problem solved! Grateful!
