### ISSUE TITLE
Crash on Windows machine with 0.4.9.6

### ISSUE THREAD

**Issue by A2be** [bisq-network/bisq#596]
I downloaded the 64-bit Windows version of v0.4.9.6 and installed it on a Win7 machine yesterday.

After testing a variety of scenarios, which all seemed to work, I was unable to shut down the instance of Bitsquare.  Ultimately, I closed down all other apps (successfully), and after failing again to get the Bitsquare instance to kill, forced a hard shutdown by holding the (laptop) power switch down for 10 s.

On power up, got this, which I had never seen before over several years with this PC
![2016-09-08 20 57 54](https://cloud.githubusercontent.com/assets/19943243/18385439/e9944c5c-764d-11e6-9066-d8047a09a9b1.jpg)
:

Any ideas?  Is this similar to issues previously reported?

**Comment by ManfredKarrer** [comment]
Never saw that before. Maybe your disc had issues and that caused Bitsquare not be able to shut down. Hopefully your disc could recover. I would recommend a full disc backup, just to be safe. Also do backups of Bitsquare so in such cases you are not losing data or btc in worst case if u dont have the seed words and no backup.
