### ISSUE TITLE
Boolberry market

### ISSUE THREAD

**Issue by 1blockologist** [bisq-network/bisq#597]
Hello, I am interested in a boolberry market, around 20% of the float sits on exchanges right now and I am interested in encouraging OTC trading of it.

My organization is the new steward of the boolberry project

**Comment by ManfredKarrer** [comment]
Boolberry is CryptoNote, right? So you need a similar solution like Monero to make the transaction verifyable for the arbitrator in case of a dispute. The blockexplorer is not sufficient for CryptoNote coins.

**Comment by mrosseel** [comment]
A viewkey could be provided to the arbitrator? Ideally only in case of a
dispute.

Mike

**Comment by ManfredKarrer** [comment]
The viewkey is not enough. I don't remember the details but we had discussion with the Monero devs and they added some special support for a tx private key in simplewallet and a tool for checking (http://xmr.llcoins.net/checktx.html) the tx. Those things are not CryptNote features as far I know but added by Monero, so I assume other coins will not have that.
In the GH issues u will find the discussion (or when u set up a XMR accoun tin bitsquare u get all the info).

**Comment by eric-townsquared** [comment]
@ManfredKarrer I read that discussion, issue #392 and it doesn't seem like something was actually added

Boolberry may need to duplicate luigi's tool for the boolberry network but the functionality should already be analogous

**Comment by 1blockologist** [comment]
@ManfredKarrer  I read that discussion, issue #392 and it doesn't seem like something was actually added
Boolberry may need to duplicate luigi's tool for the boolberry network but the functionality should already be analogous

**Comment by haiqu** [comment]
All coin add requests should be directed to the following forum topic:

https://forum.bitsquare.io/t/how-to-add-your-favorite-altcoin

**Comment by ManfredKarrer** [comment]
Once Boolberry has the required support please add a request.

**Comment by b4h4mu7** [comment]
Hello @ManfredKarrer we're adding required support. Will update you when it is completed.
