### ISSUE TITLE
heightoflastblock must match chain height

### ISSUE THREAD

**Issue by Hoss79** [bisq-network/bisq#5970]
### Description

 unable to open the wallet and give me an error of   (heightoflastblock must match chain height)

**Comment by ghost** [comment]
The issue is being looked into.  The workaround fix is:

Close Bisq, delete `DaoStateStore` and `BsqBlocks` from the [data directory](https://bisq.wiki/Data_directory), and then restart Bisq.

**Comment by Hoss79** [comment]
Could you please explain a bit more? where is data directory?

**Comment by ripcurlx** [comment]
Closing because of https://github.com/bisq-network/bisq/issues/5970#issuecomment-1013965470.

> Could you please explain a bit more? where is data directory?

Please see the link provided above in @jmacxx' comment: https://bisq.wiki/Data_directory

**Comment by Hoss79** [comment]
Thank you for your help. I am backed online now. appreciated.
