### ISSUE TITLE
"Timeout reached. Peer has not responded" on all trades after laptop wipe :(

### ISSUE THREAD

**Issue by Nadumanov** [bisq-network/bisq#5971]
### Description

Hey folks, I've been keeping some dry powder for days like these and would like to stack some fat sacks in a trust-minimized non-KYC way aka bisq.

All my transactions result in "Timeout reached. Peer has not responded" after checking if sellers' offers were still online.

I did a laptop wipe and clean OS reinstall a few months back obviously the deleting old instance of bisq. But through my backup I could relaunch my profile with some sats and a couple of old payment accounts. However ever since then no trades have gone through.

Any idea where to look to fix this? I've done SPV resync, DAO state resync, etc. etc. Didn't find anything useful on FAQ and Wiki. Hoping a collective mind can help out here.

#### Version

v 1.8.0

### Steps to reproduce

Buy BTC —> choose fiat order (Revolut, FasterPayment, Wise, etc.) —> Take offer to buy BTC —> bug "Timeout reached..."

### Actual behaviour

https://preview.redd.it/d5swf5729rb81.png?width=1282&format=png&auto=webp&s=9fea566106fbd39b48419f18b5213a292b1fbb76

#### Device or machine

Macbook Pro Mid-2017 macOS Big Sur

**Comment by ghost** [comment]
One thing to try is using a [default fresh user data directory](https://bisq.wiki/Switching_to_a_new_data_directory), not your backup.
I'd suggest you seek support either on matrix (https://bisq.chat) or Keybase (https://bisq.wiki/User_support#Via_Keybase_chat).

**Comment by Nadumanov** [comment]
> One thing to try is using a [default fresh user data directory](https://bisq.wiki/Switching_to_a_new_data_directory), not your backup. I'd suggest you seek support either on matrix (https://bisq.chat) or Keybase (https://bisq.wiki/User_support#Via_Keybase_chat).

Thank you sir! Fixed
