### ISSUE TITLE
Problem in v1.8.0 on debian 11 - A fatal error JRE

### ISSUE THREAD

**Issue by reba222** [bisq-network/bisq#5978]
### Description

The Bisq application window closes itself.
#### Version 

1.8.0
### Steps to reproduce

Random
#### Device or machine

Intel Core i5-4460 CPU @ 3.20GHz, 4 cores, 8GB RAM, 
Linux 5.10.0-10-amd64 - debian 11

#### Additional info
[bisq.log](https://github.com/bisq-network/bisq/files/7891977/bisq.log)

[hs_err.log](https://github.com/bisq-network/bisq/files/7891980/hs_err.log)

**Comment by ghost** [comment]
From what is reported in `hs_err.log`, looks like an issue between the JRE and `libc.so`.  I'd suggest to try Bisq on the same hardware with a fresh Linux distro, maybe from a live USB of Debian or Ubuntu.  If it works then, would point to some incompatibility / corruption of your existing OS.

**Comment by reba222** [comment]
Thanks, I'll try the live distribution of Debian. I'll write the result.

**Comment by reba222** [comment]
I assumed that the problem occurred during a hard reset after
the graphical environment froze. (freezing, including mouse
and keyboard, but the system respond to a ping from another computer).

I tried live debian 11 and live debian 10. It's the same.
Sometimes the graphical environment freezes, and on debian 10,
the bisq crash as described in the previous post. I enclose a logs.
JRE versions on deb 10 and 11 are the same.

dmsg reports a problem with ACPI (debian 10 and 11)
and nouveau (debian 11). Problem with my hardware ?

[bisq.log](https://github.com/bisq-network/bisq/files/7944377/bisq.log)
[hs_err_pid3472.log](https://github.com/bisq-network/bisq/files/7944380/hs_err_pid3472.log)

**Comment by reba222** [comment]
Problem solved. 
I reinstalled the graphics card driver from nouveau to nvidia. 
Since then, everything is working fine.
