### ISSUE TITLE
java.lang.NullPointerException (v.0.4.9.6)

### ISSUE THREAD

**Issue by ElLamparto** [bisq-network/bisq#598]
When leaving the Spreads form.
[bitsquare.log.zip](https://github.com/bitsquare/bitsquare/files/465525/bitsquare.log.zip)

**Comment by ManfredKarrer** [comment]
Thanks for reporting.

**Comment by ElLamparto** [comment]
Manfred, there are many more exceptions and I have an impression, that v.0.4.9.6 is particularily instable.
The exceptions are thrown with or without user interaction. One of them is in the attached log. I can keep sending you logs if it helps you.

[bitsquare.zip](https://github.com/bitsquare/bitsquare/files/476520/bitsquare.zip)

**Comment by ManfredKarrer** [comment]
Do you get the same exception always or are there different ones? If so please send me the logs of the others. The one in the log is fixed already for a new release, but I am on vacations and have bad internet so I don't want to do a release if not absolutely needed.
The exception seems to come from a jdk bug with sorted lists. Not sure if it breaks offerbook lists updates when it occures but if not it should not be too critical. A restart though will get u a correct offerbook list state again.

**Comment by ManfredKarrer** [comment]
I see only one exception in the logs:

java.lang.NullPointerException
    at io.bitsquare.gui.main.market.spread.SpreadView.deactivate(SpreadView.java:114)

From code logic that must not happen.
Maybe that happened after another exception or hidden error?
I never saw that before as well, so I will close. If you have other exceptions or if you know how to reproduce it please re-open.
