### ISSUE TITLE
Open offer edit dialogue disappears after switching payment method to Bisq Swap

### ISSUE THREAD

**Issue by w0000000t** [bisq-network/bisq#5982]
### Description

When opening the edit open offer dialogue made with a fiat payment account, if switching the payment method to BSQ Swap the editing dialogue will vanish and go back to the previous panel, giving out the impression of some sort of bug.
#### Version

1.8.0
### Steps to reproduce

Open edit dialogue for open offer to trade with fiat, change payment method to BSQ Swap.
### Expected behaviour

If intended to not let the user switch from fiat payment method to BSQ Swap, then a dialogue would be appropriate to explain this, and then, closing the dialog, the user will be presented with the same edit offer panel, where the previous payment method has been restore in the selection dropdown

### Actual behaviour

Edit panel just vanishes

#### Device or machine

Windows 10

**Comment by ripcurlx** [comment]
As there is no option to switch an offer to a BSQ swap payment method (you can only create or delete BSQ swap offers) I think we should filter out the BSQ swap payment method from the dropdown.

**Comment by ripcurlx** [comment]
@xyzmaker123 Do you want to work on this?

**Comment by ghost** [comment]
@ripcurlx Yes, I'd like to deliver it in upcoming cycle.
