### ISSUE TITLE
heightOfLastBlock must match chainHeight

### ISSUE THREAD

**Issue by mstrslv** [bisq-network/bisq#5990]
### Description

I keep getting an error trying to open Bisq. Error states something about block height. Not really sure what to do.

#### Device or machine

Lenovo t440p using Windows 10

[LogFile Bisq.txt](https://github.com/bisq-network/bisq/files/7916561/LogFile.Bisq.txt)

**Comment by ghost** [comment]
@mstrslv see more info and suggested workaround here: https://github.com/bisq-network/bisq/issues/5917#issuecomment-994911406
