### ISSUE TITLE
Switching between payment accounts doesn't update currency related fields

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#5999]
![bug](https://user-images.githubusercontent.com/170962/151151075-995ef4ef-cab7-46fa-9313-a8ea8cf34570.gif)

### Description

When switching between payment accounts in e.g. create offer the updating of currency related fields don't work as expected

### Steps to reproduce

- Go to Create Offer
- Select a e.g. SEPA Account and fill in amount and market price margin
- Switch to e.g. Revolut (if EUR is a supported currency in this account and USD was selected before for this payment method) 

### Expected behaviour

Currency fields are changed to USD

### Actual behaviour

EUR is still displayed although USD is displaced in the currency dropdown

**Comment by ripcurlx** [comment]
☝️ @xyzmaker123

**Comment by pazza83** [comment]
I think changing payment methods where currency is the same is also an issue.

Eg SEPA to SEPA Instant. EUR will still be selected but to make offer live you need to choose something other than EUR and then change it back to EUR again.

**Comment by ghost** [comment]
@pazza83 Thanks for information - I'll try to check this scenario during my tries to fix original issue.
