### ISSUE TITLE
DAO > Bonding > Bonded roles, ordering by column not working

### ISSUE THREAD

**Issue by w0000000t** [bisq-network/bisq#6000]
### Description

Open app panel as per title, try ordering columns by `Name` (easier on the eyes to check), no matter the ordering, it will be all over the place. Same goes for all other columns.

#### Version

1.8.2

### Steps to reproduce

See `Description` above

### Expected behaviour

Rows are ordered by the selected column, either ascending or descending

### Actual behaviour

Rows get somehow "ordered", just the rationale is not apparent, but it's not by the selected column; sometimes usernames are grouped together, but not completely still.

### Screenshots

![image](https://user-images.githubusercontent.com/95026987/151312465-3eb90f70-32f2-4ee0-aade-c8732f4f1133.png)
#### Device or machine

Windows 10

**Comment by ripcurlx** [comment]
@xyzmaker123 Do you want to have a look at this as well?

**Comment by ghost** [comment]
@ripcurlx Yes, sounds like something for me
