### ISSUE TITLE
flatpak installation of Bisq cannot save it's settings and acts like a new installation every time it's started.

### ISSUE THREAD

**Issue by rbrooklyn** [bisq-network/bisq#6004]
### Description

bisq available from https://flathub.org/apps/details/network.bisq.Bisq does load, but will not save it's files. Upon every load, I see the "User Agreement" and all my settings are missing from my non-flatpak installation.

Checking the files in ~/.var/app/network.bisq.Bisq/ shows that no configuration files are being saved. Even renaming the ~/.local/share/Bisq folder does not fix this. Bisq will show the user agreement on every start and will be treated as if it's a new installation.

#### Version

1.8.2

### Steps to reproduce

```
flatpak install network.bisq.Bisq
flatpak run network.bisq.Bisq
```
Observe that the settings are wiped clean on every run and the existing settings are not imported automatically.

### Expected behaviour

Either Bisq to create new settings in ~/.var/app/network.bisq.Bisq/data, or to import and/or update ~/.local/share/Bisq as needed

### Actual behaviour

Bisq behaves as if it's a fresh installation each time it is started. Any accounts or wallets created/imported are simply forgotten on the next run.

#### Additional info

Curiously, Flatseal (another app I use to manage permissions for flatpak installations) shows that no permissions are given to access my home folder. This is absolutely fine and I'd expect files to be present in ~/.var/app/network.bisq.Bisq/data, but the folder is always empty.

I see no mention of flatpak on the bisq.network website, or https://bisq.network/downloads/ so I do have a concern that I've downloaded something either malicious or "unofficial".

**Comment by ghost** [comment]
That seems to be an unofficial build.  The [website link you provided](https://flathub.org/apps/details/network.bisq.Bisq) shows:

    NOTE: This release is not verified by, affiliated with, or supported by Bisq Network.

AFAIK the person who uploaded that to flatpak is not a known Bisq contributor.  I will ask the @bisq-network/support team about what can be done about this.

flathub / flatpak is not a supported release platform.  

Official releases of Bisq for various architectures can be found on [github](https://github.com/bisq-network/bisq/releases) or at https://bisq.network/downloads/


Thanks for reporting.

**Comment by ripcurlx** [comment]
I was contacted by a user if it is fine to add Bisq to Flatpak and after reviewing the possibilities to verify the binary downloaded from Flatpak I rejected it as an official Bisq distribution platform. It might not be a malicious download, but it is definitely not a a verified and maintained one by Bisq.

**Comment by nanonyme** [comment]
Note that this is a bug in Bisq and can have impact to other platforms than just flatpak. XDG-compliant apps are expected to read XDG_DATA_HOME environment variable, then *only* if it's not present, use $HOME/.local/share.

**Comment by ripcurlx** [comment]
> Note that this is a bug in Bisq and can have impact to other platforms than just flatpak. XDG-compliant apps are expected to read XDG_DATA_HOME environment variable, then _only_ if it's not present, use $HOME/.local/share.

As we use jpackage someone needs to investigate if we are able to adapt this for our build pipeline.

**Comment by Christian891** [comment]
You have to set write permissions:
 `sudo flatpak override --filesystem=/home/user/Downloads:create network.bisq.Bisq `
Please check `https://wiki.ubuntuusers.de/Flatpak/`

If you like this please send some sats to: _https://lnurl.com/lnurlp/2145_ thx :-)
