### ISSUE TITLE
Wallet private keys shown without requesting password

### ISSUE THREAD

**Issue by w0000000t** [bisq-network/bisq#6006]
### Description

In Account > Wallet info > Show raw details and private keys, the user has access to private keys and to copy everything to clipboard (!) without any request for wallet password, nor notification about the dangers of copying to clipboard any sensitive wallet info

#### Version

1.8.2

### Steps to reproduce

Unlock wallet with password after starting Bisq, go to Account > Wallet seed and verify how it will ask for password to show the seed.
Do not enter password.
Go to Account > Wallet info, and push "Show raw wallet[...]", click on checkbox to show private keys, then click on "copy to clipboard".
No request for password, nor any notification about the dangers of clipboard, is shown.

### Expected behaviour

Request for password in order to show private keys. Big red dialogue about copying anything to clipboard, especially if containing private keys, especially if someone asked you to.

### Actual behaviour

As per `Description`.

#### Device or machine

Windows 10

**Comment by ghost** [comment]
Existing discussions related to that are in https://github.com/bisq-network/bisq/issues/5152, https://github.com/bisq-network/bisq/issues/5276 and https://github.com/bisq-network/bisq/discussions/5398.  I guess this issue had dropped off my radar.  Thanks for the reminder.

FYI there's also [this list](https://github.com/bisq-network/bisq/discussions/5668) of unresolved issues which I try to keep updated.

**Comment by w0000000t** [comment]
Oh, got it, when I noticed it I thought that, had someone already reported it, it would have definitely been fixed 😅 
Should I close this thread then, as it's a duplicate?
