### ISSUE TITLE
bisq bug

### ISSUE THREAD

**Issue by FizzyLloyd** [bisq-network/bisq#6007]
#### Additional info

[bisq bug 1.txt](https://github.com/bisq-network/bisq/files/7967149/bisq.bug.1.txt)

**Comment by ghost** [comment]
Your log contains `heightOfLastBlock must match chainHeight`.  Fix that by following the workaround described in https://github.com/bisq-network/bisq/issues/5917#issuecomment-994911406

**Comment by FizzyLloyd** [comment]
> Your log contains `heightOfLastBlock must match chainHeight`. Fix that by following the workaround described in [#5917 (comment)](https://github.com/bisq-network/bisq/issues/5917#issuecomment-994911406)

I tried that but still have same issue. I've also tried uninstalling and installing again but the error is persistent

**Comment by ghost** [comment]
Make sure Bisq is not running when you follow the instructions in https://github.com/bisq-network/bisq/issues/5917#issuecomment-994911406

**Comment by FizzyLloyd** [comment]
> Make sure Bisq is not running when you follow the instructions in [#5917 (comment)](https://github.com/bisq-network/bisq/issues/5917#issuecomment-994911406)

Yes I did. Also had a friend do it for me too and I still have the same issue. I don't know if we both did it right because I'm not that computer savvy. He is moreso than me. I did it by searching PC for those components, DaoStateStore and BsqBlocks, and deleting from there. So bisq wasn't running or attempting to run. Is there a different way to do it?

**Comment by ghost** [comment]
1. Install the latest Bisq release v1.8.2.  https://github.com/bisq-network/bisq/releases
2. Remove DaoStateStore and BsqBlocks one more time, before running Bisq.  Make sure you're removing them from the correct data directory (not a backup).  https://bisq.wiki/Data_directory#Windows
3. If there's still an issue could you send your latest bisq.log

Feel free to contact live support agents on Matrix or Keybase.   https://bisq.wiki/User_support#Via_Matrix_bisq.chat

**Comment by FizzyLloyd** [comment]
Ok we recovered the small amount of btc by sending it to my phone. 
Then cleaned all Bisq from the PC and did a clean install from v1.8.2
All ok now.
Thank you so much for your help :)
