### ISSUE TITLE
Make account names editable for all account types

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#6009]
### Description

Recently @xyzmaker123 made [SEPA account names editable](https://github.com/bisq-network/bisq/pull/5930)

This was a great usability addition.

It would be good if this was extended to ALL account types (National Currency and Altcoins).

The account name is only saved and shared locally so it does not effect any trades in progress.

#### Version

1.8.2

### Steps to reproduce

If you have a SEPA or SEPA Instant account you can change the name.

You cannot change the name for any other account type Altcoin or National Currency Account

### Expected behaviour

ALL payment account type names to be editable.

### Actual behaviour

Only SEPA and SEPA Instant payment account type names are editable.

**Comment by pazza83** [comment]
Hi @xyzmaker123 would you be able to take on this issue?

**Comment by ghost** [comment]
Yes, I can take this task
