### ISSUE TITLE
backup directory locked when directory not existing

### ISSUE THREAD

**Issue by KanoczTomas** [bisq-network/bisq#601]
Hello, 

I was doing a backup to a USB stick on computer A than moved it to another (B). Then wanted to do a backup of bitsquare on B and move it to C, but the old backup folder was remembered. I had to manually create the non existing folder to be able to choose a new folder - a window with error about non existing directory showed. 

The fix was super easy, I just created the directory than was able to set the new one, but it would be very confusing for a novice user - so I believe it should be changed. Showing the error is fine, just having the option to choose a new directory is missing.

was running Xubuntu:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:    14.04
Codename:   trusty

thanks!

**Comment by ManfredKarrer** [comment]
Thansk for reporting. Will put it on the (long) todo list. 
Or maybe any volunteer will take that low hanging fruit :-)

**Comment by haiqu** [comment]
Just tested creating a backup to a non-existent USB stick subdirectory on Windows 7 and it works fine. May be a bug with the Java implementation under Linux, or an OS limitation.

**Comment by KanoczTomas** [comment]
Hello,

just to make sure you replicated the problem exactly. The backup was made
on another linux machine (machine A), lets say the directory was
/media/placeA. Than the backup was copied to another linux machine (machine
B), where the backup was restored to the box successfully. After a day I
wanted to make a backup on machine B and it was complaining about the non
existent directory /media/placeA and did not allow me to create a backup. I
had to manually create /media/placeA (and of course changing ownership of
the folder to the appropriate user) to be prompted for a new folder,
otherwise I just saw an error message and could not get further.

Just want to make sure you replicated the same in windows, if yes fine(just
making sure). If not, could u please replicate?

Thanks a lot!

Dňa 21.10.2016 17:33 používateľ "Rob Judd" notifications@github.com
napísal:

**Comment by r8d8** [comment]
I wasn't able to reproduce  on ArchLinux (kernel 4.13) using `v0.6.1` with following steps:
* make backup into folder `X`
* Quit bisq app
* Remove folder X
* Launch app again, and  select new backup folder 
Can also make `HowTo` required in this issue https://github.com/bisq-network/docs/issues/18

**Comment by r8d8** [comment]
So, maybe we can close this bug?
