### ISSUE TITLE
DAO - BSQ Wallet - Select Inputs popup does not accommodate multiple inputs.

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#6023]
### Description

The recently added select Inputs for the DAO BSQ wallet it a great feature. However, if the user has inputs that go over one page then the displayed pop-up is unusable and must be force closed with `ESC`.

#### Version

1.8.2

### Steps to reproduce

With an active BSQ wallet with multiple inputs Go to > DAO > BSQ Wallet > Select Inputs 

### Expected behaviour

Some sort of limitation to window pop-up size with a scroll should inputs exceed screen size.

### Actual behaviour

Window pop-up size fills with inputs and becomes unusable.

### Screenshots

![BSQ inputs](https://user-images.githubusercontent.com/66367547/152423628-09f9cd3a-7629-4896-9a74-44ba77c0de55.PNG)
Low amount of inputs

![multiple inputs](https://user-images.githubusercontent.com/66367547/152424173-8c12a2b4-41b9-419f-8646-5f54c509283b.png)
High amount of inputs

**Comment by ghost** [comment]
Tangentially related:  Whenever I've tried to send from a specific BSQ input, it has not worked.  It seems like wallet algorithm chooses whatever inputs it thinks are necessary, regardless of selection in the UI.  Anyone else noticed this?
