### ISSUE TITLE
Bisq won't launch getting "heightOfLastBlock must match chainHeight"

### ISSUE THREAD

**Issue by swidgen** [bisq-network/bisq#6037]
I recently updated my Bisq to version 1.8.2 for Mac OS. It worked for about a day but now on launch i get an error that says

> heightOfLastBlock must match chainHeight

Then it gets stuck on "Connecting to Bitcoin Network"

Do I need to reinstall? And if i do need to reinstall how do I make sure I don't lose any of my data files such as backups I saved etc...?

Log file is included here
[bisq.log](https://github.com/bisq-network/bisq/files/8046255/bisq.log)

**Comment by ghost** [comment]
@swidgen  a [fix for this issue](https://github.com/bisq-network/bisq/pull/6018) is planned for Bisq 1.8.3, coming soon<sup>TM<sup>.

---

In the meantime, there's a workaround fix described here: https://github.com/bisq-network/bisq/issues/5917#issuecomment-994911406
Also see here if you run into problems:  https://github.com/bisq-network/bisq/issues/6016

**Comment by swidgen** [comment]
@jmacxx ya the fix worked.  In the Bisq community board @w0000000t [linked to the FAQ](https://bisq.wiki/Frequently_asked_questions#Common_Technical_Niggles)
