### ISSUE TITLE
Can't select currency unless trade is active

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#605]
This one was mentioned on the forum as a bug with NZD but it's actually more pervasive.

If a currency account is created and the user wishes to Buy or Sell, they can't select their currency unless an active trade is online in that currency. The currency is actually missing from the list drobox. Workaround is counterintuitive, but essentially one has to use 'Show All' then enter their trade.

The currency list should include:
1. All currencies for which there are active trades (which it already does), AND
2. All currencies for which an account has been created.

See also #603

**Comment by ManfredKarrer** [comment]
Earlier behavior was: Show all currencies which are selected in the preference list (yet used for market rate currencies only). If you add a currency in an account it gets added automatically to the preference list. I tend to go back to that old strategy. People want to filter away currencies they are not interested in.

**Comment by haiqu** [comment]
OK, that works for me.

**Comment by ManfredKarrer** [comment]
Will be fixed for next release.
