### ISSUE TITLE
Trede ID lCwuO-6dccf075-121b-4b44-9747-6049e0e08fa0-115

### ISSUE THREAD

**Issue by kicco-sk** [bisq-network/bisq#6050]
Hi 

The problem with this transaction has been since 2019. Payment has been made, but I do not have the opportunity to confirm receipt of payment. This business is therefore still open.

Thank you

**Comment by pazza83** [comment]
Hi @kicco-sk thanks for opening this issue. 

Please can you open this issue on https://github.com/bisq-network/support/issues using the template provided here: https://github.com/bisq-network/support/issues/new?assignees=&labels=&template=reimbursement-template.md&title=Fee+reimbursement+for+trade+XXXXX

**Comment by pazza83** [comment]
Can be closed as issue opened here: https://github.com/bisq-network/support/issues/1066
