### ISSUE TITLE
Navigation Hierarchy Adjustments

### ISSUE THREAD

**Issue by UX-P** [bisq-network/bisq#6061]
According to [research](https://github.com/bisq-network/proposals/issues/349#issuecomment-989074156) some Monero traders are not aware Bisq trades XMR. 
Currently on the landing page, the app menu bar only indicates that Bisq sells BTC. This terminology does not clearly describe the app's content and features.

UX web standards suggest that a mislabelled menu affects traffic, conversion and user-friendliness. 
Users rely on visual cues from menus to navigate through the site effectively and allows them access to commonly used commands.

**Current state**

Menu bar does not clearly define app options 

<img width="849" alt="Screenshot 2022-02-19 at 12 50 37" src="https://user-images.githubusercontent.com/92308399/154801699-a8614002-986c-414a-b002-53b4a280a167.png">

 
 
Expected state
The user understands that BTC and other cryptocurrency coins are available for trade.

<img width="856" alt="Screenshot 2022-02-19 at 13 02 49" src="https://user-images.githubusercontent.com/92308399/154802711-e2792920-3997-484b-a016-130aacaa72fe.png">

Altering the top-level menu bar helps to alleviate the user's cognitive load, guides the user to their desired location and decreases the Bisq drop off rate. 

_Description_ 

### **'BTC' nav** 

**1st Level nav**
Replace ‘buy bitcoin’ for ´BTC’- a clear indication BTC is available for purchase 
 
**2nd Level nav**  
Replace ‘Buy Bitcoin’ 
For ‘Buy’ and ‘Sell’ tab 
 
Buy tab: Show all available trades to Buy Bitcoin using FIAT  
Sell tab: Show all available trades to sell Bitcoin using FIAT  
 
**3rd level (filters)**
Change ‘filter by currency’ wording to the common term ‘choose currency’
Change ‘filter by payment method’ to the common term ‘choose payment method’
Filter should only include Fiat options with no altcoin options

### **'Altcoins' nav**

<img width="886" alt="Screenshot 2022-02-19 at 13 11 08" src="https://user-images.githubusercontent.com/92308399/154802805-60e04755-e91e-4520-9a08-7449e41bd81b.png">

**1st Level nav**
Replace ´Sell BTC’ for ‘Altcoins’- a clear indication that Altcoins are available for purchase 
 
**2nd Level nav**
Replace ‘Sell Bitcoin’ tab 
For ‘Buy’ and ‘Sell’ tab 
 
**3rd level (filters)**
Change ‘filter by currency’ wording to the common term ‘choose currency’
Change ‘filter by payment method’ to the common term ‘choose payment method’
Filter should only include Altcoin options with no Fiat options

### **'Create New offer' button**

**Current State**

<img width="386" alt="Screenshot 2022-02-17 at 21 49 44" src="https://user-images.githubusercontent.com/92308399/154802430-74d3737e-1634-4eab-a689-3e9569d9998d.png">

With this new hierarchy, it would no longer be necessary for the UI to specify the asset. 

<img width="273" alt="Screenshot 2022-02-19 at 13 23 50" src="https://user-images.githubusercontent.com/92308399/154802868-7b8aab46-cb9e-42a6-83ac-b13212e79f34.png">

@jmacxx , @xyzmaker123,  @ripcurlx are there any tech considerations that would complicate this change, or is this doable?

**Comment by ghost** [comment]
IMO the existing menu structure was well designed, using "Bitcoin first" principles.
Has this proposed change been discussed & approved by the community?  
Maybe this adjustment fits better for [Bisq2](https://github.com/bisq-network/bisq2/)

**Comment by pazza83** [comment]
I never use the 'Buy BTC' 'Sell BTC' tabs.

I always just select the market and then choose buy / sell from there.

I imagine most people using Bisq know that XMR can be traded there.

Maybe changes could be made to the [Bisq website](https://bisq.network/), where a potential user would be more likely to land, to show what currencies / alts are actively traded.

**Comment by UX-P** [comment]
Hi @jmacxx , @pazza83 Thanks for the feedback. Yes, this design is based on community research and all solutions have been listed in my previous proposals including the potential change to ‘add XMR tab’. However, this would narrow the market considering there are other altcoins available for trade on bisq hence the decision to use the wording ‘Altcoins’.

These small changes will help Bisq’s developments towards Bisq 2. There are specific protocols where Bisq is expecting to funnel users from Bisq 2 to Bisq 1, and these UX considerations will have a significant effect on attracting new users.

I would like to clarify that this change is not for expert users. It is aimed at what has been analysed as [nipx231](https://github.com/UX-P/Monero-user-profile/blob/main/Bisq%20Monero%20User%20profile.pdf). The personas have been created considering the current user, potential user,  bisq values, web standards and competitive research.
This design alteration has been made for someone starting on Bisq and seeking to trade XMR. So while there is some awareness from current users that the ‘buy bitcoin’ and ‘sell bitcoin’ tab is interpreted as ‘buy and sell XMR’, this information should nevertheless, be clearly stated on the menu bar for those who are not regulars of bisq and therefore not as knowledgeable. 

Perhaps we can do a comparison vote in the Eth and Monero community? We often do A/B tests in my line of work. I can post both menu versions and review feedback from potential users? 

Meanwhile, do you have any more information on the ‘BTC first principles’ Bisq follows. I would like to relate these to all user focused decisions going forward.

**Comment by chimp1984** [comment]
Thanks @UX-P for the proposal!

I think that fixes the main source of confusion for new altcoin traders. 
Bisq is using the wrong mental model for altcoins by putting Bitcoin at the center, but for altcoins the altcoin would be the <strike>quote</strike> base currency and BUY/SELL relates to the altcoin not BTC (e.g. I want to BUY XMR).

The mental model of base currency and quote currency is determined by the market price as all prices are quoted on that model. Left is the base currency and right the quote currency. The quote is the price for 1 unit of the base currency, e.g. 50 000 USD for 1 BTC or 0.004 BTC for 1 XMR in case of an altcoin.

By having the Buy BTC and Sell BTC in the menu we have the contradiction that at the buttons we use the correct language (e.g. BUY XMR) but at the top menu we have SELL BTC. This cause confusion.

As much I appreciate the change I am also a bit worried about implementing it as the incorrect model represented in the UI have traces in the domain models and much care is required to not break things. But I think its at least worth a maybe time boxed attempt to see if in e.g. 2 days an experienced dev like @jmacxx or @ripcurlx can implement the changes without causing an avalanche of problems.

**Comment by UX-P** [comment]
@chimp1984 Very helpful feedback, and I agree that the 'Altcoins' wording, although a step in the right direction, this alteration could cause a little confusion due to the current top-level nav structure. I decided on this wording to not completely delete BTC from the nav as the change could become disruptive to current users. @jmacxx @ripcurlx and I have had a discussion on how to make the nav redesign work with the technical considerations.

Here is an update to the design:
<img width="1278" alt="Screenshot 2022-02-23 at 18 37 54" src="https://user-images.githubusercontent.com/92308399/155385549-0bfed2a7-a1ca-4c16-ac51-76b11423c509.png">


<img width="1150" alt="Screenshot 2022-02-23 at 18 09 18" src="https://user-images.githubusercontent.com/92308399/155382292-32cfe303-ba01-44cc-8ba3-29d0024c87b1.png">

<img width="1148" alt="Screenshot 2022-02-23 at 18 09 31" src="https://user-images.githubusercontent.com/92308399/155382579-fc3639d0-e138-49bb-9fa9-9d32b31f2b40.png">

### **1st Level nav**
Change ‘Buy BTC’ to ‘Buy’
Change ‘Sell BTC’ to ‘Sell’

### **2nd Level nav**
Add Altcoin tabs (as shown on ‘P2P’ Binance section)
<img width="599" alt="Screenshot 2022-02-23 at 19 03 34" src="https://user-images.githubusercontent.com/92308399/155389442-eb284ae2-ff55-4a47-af83-bb22d3fae487.png">

Add ‘Other coins’ tab. @ripcurlx Could you confirm the preferred wording here? 
Suggestions:
Crypto
Altcoins
Cryptocurrencies

Recommended 3-5 tabs

### **3rd Level nav**
**Altcoin tabs (XMR, BTC etc.)**
Remove ‘filter currency’ tab
Move ‘choose payment method’ filter to the left

**Other coins tab**
Change 'filter currency'
Replace with ‘Choose Altcoin’  (wording depending on what the 'other' tab is named)

### **Wording**
**3rd level nav**
In BTC tab change ‘Available offers’
Replace with ‘Fiat to BTC’ in Buy >BTC tab
Replace with ‘BTC to Fiat’ in Sell > BTC tab

For all altcoin tabs change ‘Available offer’
Replace with ‘{altcoin} to BTC in Buy > {altcoin} tab
Replace with ‘BTC to {altcoin} in Sell > {altcoin} tab
Change ' filter currency' to 'Choose Altcoin'

Change ‘Filter Currency’ to ‘Choose Currency’
Change ‘Filter Payment Method’ to ‘Choose Payment Method’

Change button from ‘Create new offer to sell ETH (Buy Bitcoin) to ‘Create New offer’
Change button from ‘Take offer to sell ETH’ to ‘Take Offer’

Let me know of any tech issues that could affect this design, thanks!

**Comment by alkum** [comment]
@UX-P I like this diagram you posted:

> Add Altcoin tabs (as shown on ‘P2P’ Binance section) <img alt="Screenshot 2022-02-23 at 19 03 34" width="599" src="https://user-images.githubusercontent.com/92308399/155389442-eb284ae2-ff55-4a47-af83-bb22d3fae487.png">

Its compact, elegant and gives the user all the key information.

**Comment by ripcurlx** [comment]
> @chimp1984 Very helpful feedback, and I agree that the 'Altcoins' wording, although a step in the right direction, this alteration could cause a little confusion due to the current top-level nav structure. I decided on this wording to not completely delete BTC from the nav as the change could become disruptive to current users. @jmacxx @ripcurlx and I have had a discussion on how to make the nav redesign work with the technical considerations.
> 
> Here is an update to the design: <img alt="Screenshot 2022-02-23 at 18 37 54" width="1278" src="https://user-images.githubusercontent.com/92308399/155385549-0bfed2a7-a1ca-4c16-ac51-76b11423c509.png">
> 
> <img alt="Screenshot 2022-02-23 at 18 09 18" width="1150" src="https://user-images.githubusercontent.com/92308399/155382292-32cfe303-ba01-44cc-8ba3-29d0024c87b1.png">
> 
> <img alt="Screenshot 2022-02-23 at 18 09 31" width="1148" src="https://user-images.githubusercontent.com/92308399/155382579-fc3639d0-e138-49bb-9fa9-9d32b31f2b40.png">
> 
> ### **1st Level nav**
> Change ‘Buy BTC’ to ‘Buy’ Change ‘Sell BTC’ to ‘Sell’
> 
> ### **2nd Level nav**
> Add Altcoin tabs (as shown on ‘P2P’ Binance section) <img alt="Screenshot 2022-02-23 at 19 03 34" width="599" src="https://user-images.githubusercontent.com/92308399/155389442-eb284ae2-ff55-4a47-af83-bb22d3fae487.png">
> 
> Add ‘Other coins’ tab. @ripcurlx Could you confirm the preferred wording here? Suggestions: Crypto Altcoins Cryptocurrencies
> 
> Recommended 3-5 tabs
> 
> ### **3rd Level nav**
> **Altcoin tabs (XMR, BTC etc.)** Remove ‘filter currency’ tab Move ‘choose payment method’ filter to the left
> 
> **Other coins tab** Change 'filter currency' Replace with ‘Choose Altcoin’ (wording depending on what the 'other' tab is named)
> 
> ### **Wording**
> **3rd level nav** In BTC tab change ‘Available offers’ Replace with ‘Fiat to BTC’ in Buy >BTC tab Replace with ‘BTC to Fiat’ in Sell > BTC tab
> 
> For all altcoin tabs change ‘Available offer’ Replace with ‘{altcoin} to BTC in Buy > {altcoin} tab Replace with ‘BTC to {altcoin} in Sell > {altcoin} tab Change ' filter currency' to 'Choose Altcoin'
> 
> Change ‘Filter Currency’ to ‘Choose Currency’ Change ‘Filter Payment Method’ to ‘Choose Payment Method’
> 
> Change button from ‘Create new offer to sell ETH (Buy Bitcoin) to ‘Create New offer’ Change button from ‘Take offer to sell ETH’ to ‘Take Offer’
> 
> Let me know of any tech issues that could affect this design, thanks!

Looking good! Following two remarks:
- When XMR or any other altcoin is chosen there won't be a `Choose payment method` section. Just the create offer button and the list of available offers to be taken.
- Yes I think we should limit the amount of tabs to ~5. I would put hardcoded BTC and BSQ, afterwards the top 2 coins based on volume in the last 30/90 days (ATM XMR and ETH) and ~other shitcoins~ 😜  `other coins` although it might not be the 100% perfect naming (we would throw tokens and coins into one bag). Using `other assets` might be too unfamiliar for newbies and `other crypto` sounds a little bit scammy IMO. But I'm no native speaker. @m52go What's your take on this?

**Comment by UX-P** [comment]
@ripcurlx thanks!

> When XMR or any other altcoin is chosen there won't be a Choose payment method section. Just the create offer button and the list of available offers to be taken.

on the Bisq app,  'Altcoin' and 'Altcoin instant' are listed as payment methods, will these options no longer be necessary?
 
> Using other assets might be too unfamiliar for newbies

Yes, also assets are described as coins that belong to the trader shown on a portfolio app for example, so would not be too appropriate. 

<img width="429" alt="Screenshot 2022-02-24 at 12 21 25" src="https://user-images.githubusercontent.com/92308399/155523154-0921a41a-f4b0-42f4-84a7-7b4d770627f8.png">

> other crypto sounds a little bit scammy IMO

I've looked at a few terms used by other exchanges and 'crypto' actually seems to be the most popular displayed on the menu bar. 
That does not mean you're incorrect in thinking the term sounds scammy, but these popular exchanges have gained success in onboarding new traders while using this terminology, which has gained familiarity even amongst expert users. 

**Etoro** _(Located in drop down, under 'Trade' tab in menu bar)_
<img width="208" alt="Screenshot 2022-02-24 at 12 05 20" src="https://user-images.githubusercontent.com/92308399/155521548-6aa7a2be-05dd-4b2e-8428-4ed0d6dd80cb.png">

**Kraken**
<img width="423" alt="Screenshot 2022-02-24 at 11 49 09" src="https://user-images.githubusercontent.com/92308399/155531548-e4cf9c61-8acc-4d24-991a-c54697b0203c.png">

**Coinbase _(Located under the `Learn' tab)_**
<img width="157" alt="Screenshot 2022-02-24 at 13 10 18" src="https://user-images.githubusercontent.com/92308399/155530348-040b9a94-f45e-48c7-9267-9c6612d5b079.png">

**Binance**
<img width="1040" alt="Screenshot 2022-02-24 at 11 49 56" src="https://user-images.githubusercontent.com/92308399/155524548-cbacb0b7-4d4b-4e3c-80cf-74d3411b00c5.png">

Just something to consider in regards to language-  It must be easy for users to become familiar with the term, easy for the user to remember the term when they revisit the app and able to help the user to accomplish their objective quickly. 

Feedback welcome:)

**Comment by m52go** [comment]
I agree with jmacxx's [original comment](https://github.com/bisq-network/bisq/issues/6061#issuecomment-1046042349) above. I don't like the direction of these changes. I can't imagine that aping the "crypto" wording of shitcoin casinos is going to help much with usability...but it will certainly tarnish the brand and turn away its core bitcoin-focused demographic. 

Bisq 1 is a bitcoin-only exchange however you word it. The only difference is in how you pay for it.

If the goal is to make Bisq's most active trading pairs more clear, I suggest doing it more subtly:
- ordering currencies in the currency dropdown by activity instead of alphabetically
- changing "Filter by currency" text to "Buy BTC with..." for buy screen and "Sell BTC with..." for sell screen
- changing "Filter by payment method" text to "Using these payment methods..."

**Comment by ghost** [comment]
Rolling back my initial skepticism a bit, after meeting to discuss the proposal.  @ripcurlx's change (buy/sell at the top level menu) made it much more palatable.  I do still have a visceral reaction to seeing screenshots of shitcoin casinos posted above, and definitely react against the word "crypto" being used anywhere.

It seems to me the improvements discussed at the meeting are not readily apparent by reading this thread, maybe the medium of discussion makes a difference.

**Comment by UX-P** [comment]
The design aims to accommodate to the user needs mentioned above and could be viewed as a progressive step towards improving Bisq’s current user experience.

Regardless of their reputation, the above screenshots are from Bisq’s direct competitors in reference to a particular target audience. A group of users who buy non-kyc XMR from CEXs mostly due to their lower fees, quick transactions and user-friendly journey instead of opting for a decentralised exchange. I have addressed this in detail in my previous proposal [here](https://github.com/bisq-network/proposals/issues/349#issuecomment-982793772). 

I tend to keep my opinions separate to any design based solutions as this could potentially cloud my judgement and discourages a user focused approach.

The hierarchy buy/sell applies to real world conventions, which fulfils a common UX principle while clearly displaying all available buy/sell options on bisq. This could be encouraging for new bisq users, particularly those seeking to transition from a CEX to a DEX platform as exchanges are increasingly becoming regulated by governmental laws and legislations. 

The term ‘Crypto’ appears to be the most popular and familiar used term in the industry to describe altcoins and is a suggestion based on market research. However, If anyone has any other suggestions this is also welcome.

**Comment by ripcurlx** [comment]
> n the Bisq app, 'Altcoin' and 'Altcoin instant' are listed as payment methods, will these options no longer be necessary?

True - I missed the Altcoin Instant option.

Before going into the discussions on the "crypto" wording my 2 cents for this navigational change.

I think changing the current UI from

| MARKET | **_BUY BTC_** | SELL BTC  | PORTFOLIO | FUNDS |
| - | - | - | - | - |
| BUY BITCOIN |  |  |  |  |
| Available offers |  |  |  |  |

to 

| MARKET | **_BUY_** | SELL  | PORTFOLIO | FUNDS |
| - | - | - | - | - |
| **_BTC_** | BSQ | XMR | ETH | OTHER ASSETS |  |
| Fiat to BTC |  |  |  |  |

helps to solve the mind bending handling of BTC <> FIAT against BTC <> Altcoins trading.
So I'm not seeing it so much about promoting altcoins, but rather to improve the usability of our existing offering.

Yes, I agree that we put with this change our most traded altcoins more into the light compared to before, where they were just in a dropdown mixed with fiat currencies.  Hiding all other assets in the other assets dropdown besides BTC and BSQ could be one option if we think this change is problematic from a reputation/marketing perspective.

**Comment by m52go** [comment]
Featuring XMR and ETH alongside BTC is a mistake, plain and simple. Using the term "crypto" is even worse. These are the exact same things CEXes did years ago as they recognized the profit opportunity in shitcoining. The 90% of people who use Bisq for trading fiat will recognize it immediately and hate it. Once this kind of damage is done, no code changes can revert it.

It seems the core reason for this proposal in the first place is to address XMR users who don't know Bisq trades XMR...this strikes me as a flimsy premise to begin with since Bisq is routinely mentioned in XMR circles, events, etc.

@UX-P can you detail the extent to which you believe this is an issue? Or link to where you already have?

Or are there other reasons for this change?

**Comment by UX-P** [comment]
@m52go overall, there appears to be an understanding that this navigation change is necessary based on the information I have provided. I’ll be happy to go through it in more detail over a call and discuss your concerns as it seems it may go beyond the subject of usability and more of a reputation issue. As @jmacxx  mentioned, the form of communication may make a difference and should lead to a more informative discussion.

**Comment by m52go** [comment]
> @UX-P can you detail the extent to which you believe this is an issue? Or link to where you already have?

Apparently the answer to this question is 37% of _general_ XMR users polled...i.e. that 37% of general XMR users are not aware that Bisq trades XMR. To me this is not a convincing figure, especially for such a major change, and I would expect a poll of _Bisq_ XMR users to produce an even lower figure.

If better awareness is desired among general XMR users, then that awareness would be better achieved through an awareness campaign, not UX changes.

As I see it, the case for this major change is weak but the risks are strong.

**Comment by UX-P** [comment]
During a [survey](http://boe45ypstq2rawrbmx72wqoiarnlkn62dzesba27urcezaol3byd5vyd.onion
) the question ‘Please summarise your reasons why you do not use Bisq to trade Monero’ was asked to non bisq users who trade XMR, 37% of these responses included users not being aware XMR is traded on bisq, other responses also included users not having enough knowledge of bisq. 
This design solution is aimed to expand bisq’s current altcoin market by clarifying all available trades that could be made using BTC by providing an easier, well defined user journey:

current journey to buy altcoin:

Sell bitcoin > Sell bitcoin > filter currency > choose payment > take offer to buy XMR (Sell BTC) 

Proposed journey to buy altcoin:
Buy> XMR> choose payment method> take offer

@m52go has expressed some concerns with this new navigation menu design as it could possibly shun ‘btc maximalists’ who make up 90% of bisq fiat btc users according to his research. I agree this is quite a significant amount of potentially displeased users.

As I have mentioned, I am experienced in conducting A/B and usability tests, if necessary, I propose to organise a small scale user lab. This involves having 3-4 users test out the current navigational system and the new navigational system design(I will create a prototype). Each journey will be time based and users will provide feedback regarding ease of use, design layout, understanding, efficiency and what this design represents at first glance. 

The target market this will be aimed at are:

New user transferring from CEX to DEX wanting to trade XMR
A current ‘btc maximalist’ user wanting  to buy BTC-  
New onboarding user wanting to trade BTC

These are scenarios and won’t actually involve the user making any real purchases, this will be carried out unbranded if preferable.

Feedback on this is welcome!

**Comment by m52go** [comment]
Beyond maximalists...it's also important to consider Bisq's strengths and market positioning. It does not directly compete with big CEX offerings doing 1,000,000,000 USD per day optimized for speed with automatic order matching and a million trading pairs. It has a different appeal and a different purpose, and trying to make it look and feel like those casinos is misguided.

Bisq's UX _should_ be improved, but that should be accomplished through [novel approaches](https://github.com/bisq-network/bisq/discussions/5959#discussioncomment-2269644) that take its unique value proposition into consideration.

Altcoin trading also never caught on despite several attempts. Why is that? I think it's because most people who trade most altcoins don't value the benefits Bisq provides, so therefore cannot justify its downsides, and so they go elsewhere to trade more conveniently. The exception is XMR, but UX-P's own research indicates many of the reasons XMR users avoid Bisq will never be addressed in Bisq 1. So why attract them to it? All of this effort is much better spent on Bisq 2 where there is actually a future for this demographic.

**Comment by chimp1984** [comment]
> Hiding all other assets in the other assets dropdown besides BTC and BSQ could be one option if we think this change is problematic from a reputation/marketing perspective.

I think thats a good compromise. The difference in trade volume of XMR to the next traded altcoin is huge anyway, so no need to select/boost one. Another probably better option would be to let the user decide and add a settings option (similar as we let them define the currencies in the dropdown list) where they can choose which tabs are displayed next to BTC. XMR and BSQ could be considered the default ones but users can add anything next to BTC what they want.
Giving the user the option would be in line with the Bisq 2 strategy to avoid trying to be paternalistic to users and give them maximal freedom.

From naming I think "Others" might be sufficient as well. Seeing 2 well known currencies (BTC, XMR) should be enough to let users understand that Others refer to other currencies/assets.

@m52go 
> It seems the core reason for this proposal in the first place is to address XMR users who don't know Bisq trades XMR...this strikes me as a flimsy premise to begin with since Bisq is routinely mentioned in XMR circles, events, etc.

I think the core problem which confuses users is that we conflate the base/quote currency mental model by using "BUY/SELL Bitcoin" in the main menu for altcoins, where the mental model would interpret the altcoin as the base currency to which BUY/SELL refers to. This was a relict from initial Bisq supporting only Fiat and is the main source for the confusion with the BUY/SELL terminology we got reported many times. The base/quote currency mental model is determined by the market price which following that model as well. 

I think if we do not empasize any other altcoin beside XMR and BSQ we do not risk to upset Bitcoin maximalists.
