### ISSUE TITLE
heightOfLastBlock must match chainHeight

### ISSUE THREAD

**Issue by Centaur77** [bisq-network/bisq#6071]
Just keep getting this screen come up when i try to load Bisq on my laptop = 

heightOfLastBlock must match chainHeight

Keeps telling me to report it here?

**Comment by ghost** [comment]
a [fix for this issue](https://github.com/bisq-network/bisq/pull/6018) is planned for Bisq 1.8.3, coming soon<sup>TM<sup>.

---

In the meantime, there's a workaround fix described here: https://github.com/bisq-network/bisq/issues/5917#issuecomment-994911406
Also see here if you run into problems:  https://github.com/bisq-network/bisq/issues/6016

**Comment by Centaur77** [comment]
I've tried the workaround and its still not working. Just won't load up.

**Comment by ghost** [comment]
Have to ensure the specified file and folder get properly deleted -- did you check 
the `shift-delete` suggestion here: https://github.com/bisq-network/bisq/issues/6016#issuecomment-1026936688

If you continue to have a problem, send your [`bisq.log`](https://bisq.wiki/Data_directory) file, either here or via any other [bisq support channels](https://bisq.wiki/User_support).
