### ISSUE TITLE
Buttons to Buy BTC and Sell BTC are on the wrong pages

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#608]
![buy xvg](https://cloud.githubusercontent.com/assets/13131219/18808870/31f7cd7e-82b1-11e6-9d29-4f9179cb74cb.png)

As can be seen in the above snapshot of the Sell BTC page, the button at the bottom asks the user to 'Create new offer for buying XVG (Selling BTC)'. Since this page allows the user to BUY XVG then from his point of view to add to that page he would want to SELL XVG if the trade were to land on that page.

The same is true for the Buy BTC page, except in reverse.

**Comment by ManfredKarrer** [comment]
Yes the inversion of buy/sell with altcoin is a bit tricky to get right from UX. Once we have mroe resources we will try to work out a redesign. For the moment we need to stick with the concept that BTC is always the center but I am aware that is not optimal....

**Comment by haiqu** [comment]
BTC being the center is not the issue. Sell BTC page shown above should have a button that says "Create new offer for **selling** XVG (**buying** BTC)". Then the resulting trade ends up on this page.

**Comment by ManfredKarrer** [comment]
But then Sell BTC and buyin BTC conflicts.

**Comment by haiqu** [comment]
No it doesn't. One is "User wants to Buy" and the other is "Vendor wants to sell (to User)".

Have a look at the Offer Book page, it's correct there.

edit: Argh, no that's backwards too. You've just changed the heading from 'Buy BTC' to 'Offers to Sell BTC'.

**Comment by ManfredKarrer** [comment]
The concept is that the users is the center of the view: So Buy BTC means he wants to buy BTC (is interested in offers of users who want to sell BTC). With altcoins it is counter intuitive as u dont say I want to sell BTC to buy ETH but u say I want to buy ETH. But as altcoins was not supported in the initial version I did not consider that in the UI design and to change that now is a big UI redesign, which will be done once we have a dedicated UI dev and graphic designer.

**Comment by haiqu** [comment]
OK, I'm closing this one. After using it for a few days I realized that whether you're an end user or a trader, clicking the 'Buy BTC' or 'Sell BTC' button at the top gets you to the right place to enter a trade.
