### ISSUE TITLE
Error. heightOfLastBlock must match chainHeight

### ISSUE THREAD

**Issue by Pepperino** [bisq-network/bisq#6089]
[Uploading bisq.log…]()

**Comment by ghost** [comment]
@Pepperino please try Bisq v1.8.3 which includes a fix for this issue: https://github.com/bisq-network/bisq/releases 

If you prefer not to, there is a workaround described here:  https://github.com/bisq-network/bisq/issues/5917#issuecomment-994911406

**Comment by Pepperino** [comment]
Thanks... The workout 5917 don´t work for me. And I don´t know how install 1.8.3 on a MacOs. Sorry :/

**Comment by ripcurlx** [comment]
> Thanks... The workout 5917 don´t work for me. And I don´t know how install 1.8.3 on a MacOs. Sorry :/

The public release will be out today.
