### ISSUE TITLE
Feature request: Filter currency dropbox

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#609]
Currently the market price feed list can be filtered in settings to eliminate currencies of no user interest, but the dropbox still shows the full list of available currencies and altcoins. As the number of altcoins grows this will become unweildy.

I suggest the filter be also applied to the dropbox.

**Comment by ManfredKarrer** [comment]
Yes will revert to the old behavious (smae like in market price currency list).

**Comment by ManfredKarrer** [comment]
Will be fixed for next release
