### ISSUE TITLE
Error Can't load library: /usr/lib/jvm/java-17-openjdk/lib/libawt_xawt.so & Error Could not initialize class java.awt.image.BufferedImage

### ISSUE THREAD

**Issue by cocaesprit** [bisq-network/bisq#6095]
### Description
Cannot see the Bisq GUI correctly.

#### Version
Bisq 1.8.4

### Steps to reproduce
Open Bisq.

### Expected behaviour
Open Bisq and visualise the standard Bisq GUI.

### Actual behaviour
You'll see parts of the Bisq interface scattered around in a messy way, or, not see anything.

### Screenshots
<img width="1440" alt="Screenshot 2022-03-08 at 14 43 24" src="https://user-images.githubusercontent.com/71024527/157252651-91dd7546-b86e-43a7-9d91-f95631645320.png">
<img width="1440" alt="Screenshot 2022-03-08 at 15 02 41" src="https://user-images.githubusercontent.com/71024527/157253122-3e97f38c-d520-4f28-a299-370a9c10eabd.png">

#### Device or machine
ThinkPad X230 running Arch Linux *headless*. The GUI is being run through Xpra. Kernel version: 5.15.21-hardened1-3-hardened.

#### Additional info
Running the Bisq GUI through Xpra and then viewing it trough my macOS client. Honestly, I haven't tried running Bisq on the local monitor.

**Comment by ghost** [comment]
AFAIK Bisq doesn't works on java 17, only 11 and 15. How did you installed bisq?

**Comment by cocaesprit** [comment]
@xyzmaker123 AAAAAAAAA my fault thanks a lot!!! I installed it regularly trough the AUR but then changed the version of Java with `archlinux-java set <JAVA_ENV>`, to comply with the newest versions of Minecraft haha
