### ISSUE TITLE
Show changes in BSQ Supply over time in app

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#6100]
### Description

It would be good if if the Bisq client was able to show the Total BSQ issued net of BSQ burned for fees.

#### Version

1.8.4

### Expected behaviour

A nice graph can be seen here: https://bisq.network/dashboard/

![BSQ Supply](https://user-images.githubusercontent.com/66367547/157554554-e49c0ef1-04fb-41f5-a80b-d49c956b35c8.PNG)

It would be good to have this shown in app in BSQ supply. > DAO > Facts and Figures > BSQ Supply

![BSQ Supply 2](https://user-images.githubusercontent.com/66367547/157554767-bdbdb377-66f3-4caf-a73c-fd8e1c7fa7b1.PNG)

Might make sense to keep the 'x' axis in time as opposed to cycles.

**Comment by xyzmaker123** [comment]
I opened draft pull request - everything works but values are hardcoded so far - I'm trying to figure out way to calculate them dynamically.
