### ISSUE TITLE
Bitcoin Core v22 deprecated addresses is not handled

### ISSUE THREAD

**Issue by softsimon** [bisq-network/bisq#6119]
### Description
Since Bitcoin Core v22, the Bitcoin API has changed the format of how addresses are returned. So since v22 `deprecatedrpc=addresses` is required to get the old format and in v23 it's removed completely.

Bisq JSON blocks data export does not seem to handle this transition which breaks the Bisq block explorer if upgrading to the latest versions as addresses are not visible.

### Steps to reproduce
Run Bitcoin Core v22 or later with default settings.
Latest Bisq version v1.8.4

### Expected behaviour
The `address` field should be present

<img width="566" alt="Screen Shot 2022-03-24 at 17 35 38" src="https://user-images.githubusercontent.com/8561090/159927899-e5768e54-9671-4ecb-a4e3-95130cceecb0.png">

### Actual behaviour

`address` is now missing in the JSON data that is dumped.

<img width="792" alt="Screen Shot 2022-03-24 at 17 33 57" src="https://user-images.githubusercontent.com/8561090/159927601-59ca7ced-2483-437e-8701-cd9179df8d51.png">

**Comment by wiz** [comment]
@chimp1984 would appreciate if you can take a look, currently this is holding up an upgrade of the mempool.space servers since it will break BSQ addresses from displaying on bisq.markets - thanks

**Comment by chimp1984** [comment]
Ah damn Bitcoin RPC devs keep breaking APIs. @jmacxx could you have a look?

**Comment by ghost** [comment]
Working on it.

https://github.com/bisq-network/bisq/blob/a384071cfff94572c201737a0a4cf8954659dc40/core/src/main/java/bisq/core/dao/node/full/RpcService.java#L354-L355


The following change should fix it:

    String address = new Script(Hex.decode(scriptPubKey.getHex()))
        .getToAddress(Config.baseCurrencyNetworkParameters()).toString();

**Comment by chimp1984** [comment]
Please invite me for review once a PR is ready. DAO code is always a bit risky....

**Comment by alkum** [comment]
I think it should support both node behaviors (if v <= 22, .., else ..), otherwise `RpcService.SUPPORTED_NODE_VERSION_RANGE` would have to get more restrictive.

**Comment by wiz** [comment]
@jmacxx thanks, do you have a PR that I can test out?
