### ISSUE TITLE
BSQ balance returned by CLI is 0.00

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#6120]
### Description
BSQ balance returned by CLI is 0.00

#### Version
1.8.4

### Steps to reproduce
1) Run daemon
`./bisq-daemon --apiPassword=xyz`

2) Run cli
`./bisq-cli --password=xyz getbalance`

3) Compare BSQ values with those displayed in desktop app (`./bisq-desktop`)

### Expected behaviour
Should return same values like those displayed in desktop app

### Actual behaviour
Displays 0.00

### Screenshots
![bsq-balance](https://user-images.githubusercontent.com/84982606/160246215-623791c2-548e-462c-94f4-12550dc238ad.png)

**Comment by alkum** [comment]
Did you wait until "Synchronizing DAO" finished? BSQ balance is zero until DAO is up to date.

**Comment by ghost** [comment]
Hmm, it's weird - now I see proper value. 



> Did you wait until "Synchronizing DAO" finished? BSQ balance is zero until DAO is up to date.

I'd be surprised if that was a problem - I run daemon just after running desktop, which uses same data directory etc. And I saw proper BSQ balance in desktop, so I guess DAO was synchronized.

**Comment by ghubstan** [comment]
I expect to see a zero BSQ balance in the desktop for a ~few minutes after startup.

**Comment by xyzmaker123** [comment]
OK, let's close this issue.

**Comment by alkum** [comment]
Would it make sense to have a `getStatus` or similar API call? Could return whether or not different parts (like BSQ wallet) are ready. Would be useful for callers of the API.

**Comment by ghost** [comment]
Sounds reasonable to me

**Comment by ghubstan** [comment]
There has been some effort to track the combinations of states that need to be reached before wallet-affecting operations can be done.  See `bisq.core.app.AppStartupState` and its uses.   I'm not sure _a single_ Status code could or should do the job you want -- to characterize the daemon state in one code.  Maybe an API method should show a list of states reached and not reached at a particular instant.  I understand the need, just need help and more time analyzing this issue before a solution is implemented.

Currently, the implicit rule about the daemon's (ON) readiness for calls affecting wallets is:  the instant wallet balances can be accessed.

**Comment by ghost** [comment]
I agree that list of states should be better than single status. 

Despite of additional method for status we could consider showing additional warning in BSQ section returned from `getBalance` API call when DAO is not yet synchronized.
