### ISSUE TITLE
Bisq does not support high res monitor

### ISSUE THREAD

**Issue by pabo3000** [bisq-network/bisq#6126]
### Description

Bisq does not support high res monitor

#### Version

1.8.4-1

### Steps to reproduce

Open bisq on desktop with high res monitor

### Expected behaviour

Should recognize high res monitor and scale

### Actual behaviour

Does not recognize high res monitor and either does not scale. So it is not readable.

### Screenshots

![Bildschirmfoto von 2022-04-01 19-18-28](https://user-images.githubusercontent.com/918640/161311913-a97f4db2-efa8-4597-825c-45ff83e6bb1b.png)

#### Device or machine

Thinkpad x1 extreme with high res monitor
Ubuntu 21.10

**Comment by ghost** [comment]
https://bisq.wiki/Running_on_HiDPI_screen

**Comment by ripcurlx** [comment]
Closing issue because of https://github.com/bisq-network/bisq/issues/6126#issuecomment-1086772662
