### ISSUE TITLE
"Deactivating open offer due to mempool validation" does not produce any GUI explanation

### ISSUE THREAD

**Issue by JeremyRand** [bisq-network/bisq#6127]
### Description

The "Deactivating open offer due to mempool validation" error (introduced by https://github.com/bisq-network/bisq/pull/5160 ) does not result in any GUI prompt telling the user what's wrong.  The user must check the log file to gain any understanding of why their offer spontaneously disabled itself (and the GUI does not instruct the user to check the log).  This is a UX issue.

#### Version

v1.8.4.

### Steps to reproduce

1. Have an open offer that fails mempool validation.
2. Enable it by clicking the Status toggle.
3. Wait a few minutes.

### Expected behaviour

When the offer disables itself, the GUI should display a message somewhere (perhaps as an icon with popup next to the offer) that explains why the offer was disabled, and preferably give some suggestions on how to fix it.

### Actual behaviour

No indication in the GUI is given as to what's wrong.  The offer just disables itself without explanation.  User has to think of checking the logs to figure out what happened.

### Screenshots

N/A (issue is lack of GUI, not a bug in GUI that exists).

#### Device or machine

Haswell i7, Whonix 16 inside Qubes 4.1.

#### Additional info

N/A.

**Comment by ghost** [comment]
Thanks for the writeup.  I agree, whenever user's offers are auto-disabled it does cause support issues.  The most common cause is an offer that has a maker Txid which cannot be found.  Perhaps the best way to handle that would be an informational popup advising the user to delete the offer(s) and do an SPV resync.

**Comment by ghost** [comment]
![info](https://user-images.githubusercontent.com/84982606/161736982-0422df18-2497-4de3-be57-6940d0b5eac7.png)

Probably it could be similar popup like we have when bsq swap offer has missing funds :point_up: Let me know if you agree, I could implement it then.

**Comment by JeremyRand** [comment]
@xyzmaker123 No objection here.

**Comment by ghost** [comment]
Are there any plans to get this done?
Currently I get many offers deactivated due to mempool validation. Not only that there is no indication for the reason of deactivation, but no notification at all that offers were automatically deactivated.

At lease a notification telling the user that offers are deactivated should be given and preferably a reason.

**Comment by snex** [comment]
I am currently seeing this issue - what exactly does it mean to "fail mempool validation?" How would one go about fixing that?
