### ISSUE TITLE
'Panic button' required

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#613]
Found a user comment on the forum tonight that he didn't know how to contact the arbitrator. I know it's Ctrl-O but even I had to look it up.

We need a simple button for this.

**Comment by ManfredKarrer** [comment]
Will consider to add that.

**Comment by haiqu** [comment]
Appropriate location would be bottom left in the Open Trades view. It should have a popup with details about this incurring a cost if the issue was the user's fault, and a Confirm button. I haven't tested the Ctrl-O option (lucky me, all trades so far have been faultless) but I assume it already does that.

**Comment by ManfredKarrer** [comment]
I will leave that for a later usability improvement. When a user goes the first time to support, there is a popup with all the info. So I think most will try that first (look at support).  
I agree it is not optimal as it is, but I am not 100% sure if adding a button is the best way to deal with it.

**Comment by haiqu** [comment]
Main issue is that if a transaction goes wrong early then the user has no way to know how to contact support. It's not urgent but some new users could be lost. As an interim, maybe a text field telling them to press Ctrl-O would do?

**Comment by ManfredKarrer** [comment]
Will reconsider if I add it for that release....
