### ISSUE TITLE
Misleading error dialog when firewall is misconfigured

### ISSUE THREAD

**Issue by JeremyRand** [bisq-network/bisq#6141]
### Description

The error dialog appearing when an offer is open but the firewall is misconfigured to block incoming connections is misleading.

#### Version

Bisq v1.8.4

### Steps to reproduce

1. Install Bisq on Whonix as per the instructions on the Whonix wiki, but forget to configure the firewall on the Whonix-Workstation VM (thus, incoming onion connections from the Tor daemon to Bisq will be dropped).
2. Create an open offer.
3. Wait a week.

### Expected behaviour

The error dialog from Bisq should suggest to check the firewall settings (in addition to the other things it suggests).

### Actual behaviour

The error dialog from Bisq says:

> Important private notification!
> 
> You might need to clear your tor cache / restart your Bisq instance, as your 2 offers have not been reachable for at least a week.
> 
> To do that from the Bisq application menus:
> Settings -> Network Info -> Open Tor Settings -> Delete Outdated Tor Files and Shutdown

It does not suggest checking the firewall settings, thus users who have a misconfigured firewall will go on a wild goose chase and not find the actual problem.

### Screenshots

N/A; issue is with text, not graphical.

#### Device or machine

Haswell i7; Whonix 16 inside Qubes 4.1.

#### Additional info

In my experience, firewall misconfiguration is a very common newbie error, and it's often not obvious to newbies that this is something they need to check.

**Comment by ghost** [comment]
@bisq-network/bisq-devs  Any idea how we could reproduce this issue using popular linux firewalls (iptables, ufw)?

**Comment by Emzy** [comment]
The problem is that your setup runs not the included tor from Bisq.
 
I'm against changing the message. This will otherwise mislead normal users without special Tor setup on Qubes OS / Whonix.

The clarification is better put in the Whonix wiki. (https://www.whonix.org/wiki/Bisq)
