### ISSUE TITLE
No seed nodes at the beginning.

### ISSUE THREAD

**Issue by cekickafa** [bisq-network/bisq#6144]
### Description

Cannot connect seed nodes.
#### Version
V1.8.0

#### Device or machine

Windows 10.

#### Additional info

Nis-11 15:14:43.233 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Nis-11 15:14:43.234 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= Cannot invoke "java.util.List.isEmpty()" because "peers" is null 
Nis-11 15:14:43.235 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.NullPointerException 
Nis-11 15:14:43.239 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "peers" is null
	at org.bitcoinj.core.PeerGroup.getMostCommonChainHeight(PeerGroup.java:2290)
	at bisq.desktop.main.settings.network.NetworkSettingsView.updateBitcoinPeersTable(NetworkSettingsView.java:507)
	at bisq.desktop.main.settings.network.NetworkSettingsView.lambda$activate$7(NetworkSettingsView.java:299)
	at org.fxmisc.easybind.EasyBind.subscribe(EasyBind.java:262)
	at bisq.desktop.main.settings.network.NetworkSettingsView.activate(NetworkSettingsView.java:298)

**Comment by cekickafa** [comment]
![Adsız](https://user-images.githubusercontent.com/74456317/162773402-6cd1f9f2-d651-453d-a3ad-da3a12e45eac.png)

**Comment by cekickafa** [comment]
i used also Tor Bridges. Didnt work either.
https://matrix.to/#/!kAbNUeIFukYxWXxyFY:bitcoin.kyoto/$Z1SDaDbpXx9TUxZEWD1cfvHPIiH8UW9TQRwwZEUUx6Q?via=matrix.org&via=halogen.city&via=monero.social

**Comment by ghost** [comment]
Could you post the full log?  The little snippet seems like an error which occurred after the event.

**Comment by cekickafa** [comment]
Mar-15 21:08:58.924 [main] INFO  b.c.app.Version: Version{VERSION=1.8.0, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=4, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10} 
Mar-15 21:08:58.925 [main] INFO  b.c.s.CommonSetup: Path to Bisq jar file: C:\Users\selim\AppData\Local\Bisq\app\desktop-1.8.0-all.jar 
Mar-15 21:08:58.927 [main] INFO  b.c.u.Profiler: Total memory: 128 MB; Used memory: 20,923 MB; Free memory: 107,077 MB; Max memory: 2 GB; No. of threads: 1 
Mar-15 21:08:58.935 [main] INFO  b.c.s.CoreNetworkCapabilities: TRADE_STATISTICS [0], TRADE_STATISTICS_2 [1], ACCOUNT_AGE_WITNESS [2], PROPOSAL [5], BLIND_VOTE [6], ACK_MSG [7], RECEIVE_BSQ_BLOCK [8], DAO_STATE [9], BUNDLE_OF_ENVELOPES [10], SIGNED_ACCOUNT_AGE_WITNESS [11], MEDIATION [12], REFUND_AGENT [13], TRADE_STATISTICS_HASH_UPDATE [14], NO_ADDRESS_PRE_FIX [15], TRADE_STATISTICS_3 [16], BSQ_SWAP_OFFER [17] 
Mar-15 21:09:00.753 [AvoidStandbyModeService-thread] INFO  b.c.a.AvoidStandbyModeService: Started 
Mar-15 21:09:01.057 [JavaFX Application Thread] INFO  b.c.n.p.s.DefaultSeedNodeRepository: Seed nodes: [] 
Mar-15 21:09:01.060 [JavaFX Application Thread] INFO  b.c.n.p.s.DefaultSeedNodeRepository: Seed nodes: [] 
Mar-15 21:09:01.062 [JavaFX Application Thread] INFO  b.c.n.p.s.DefaultSeedNodeRepository: Seed nodes: [] 
Mar-15 21:09:01.085 [JavaFX Application Thread] INFO  b.c.n.p.s.DefaultSeedNodeRepository: Seed nodes: [] 
Mar-15 21:09:03.307 [JavaFX Application Thread] INFO  b.c.b.n.LocalBitcoinNode: No local Bitcoin node detected on port 8333. 
Mar-15 21:09:03.310 [JavaFX Application Thread] INFO  b.c.n.p.s.DefaultSeedNodeRepository: Seed nodes: [] 
Mar-15 21:09:03.314 [JavaFX Application Thread] INFO  b.c.n.p.s.DefaultSeedNodeRepository: Seed nodes: [] 
Mar-15 21:09:03.315 [JavaFX Application Thread] INFO  b.c.n.p.s.DefaultSeedNodeRepository: Seed nodes: [] 
Mar-15 21:09:03.316 [JavaFX Application Thread] INFO  b.c.n.p.s.DefaultSeedNodeRepository: Seed nodes: [] 
Mar-15 21:09:04.291 [JavaFX Application Thread] INFO  b.d.a.BisqAppMain: Using JavaFX 16 
Mar-15 21:11:48.290 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=SignedWitnessStore_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\SignedWitnessStore 
Mar-15 21:11:48.359 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=ProposalStore_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\ProposalStore 
Mar-15 21:11:48.363 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=BlindVoteStore_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\BlindVoteStore 
Mar-15 21:11:48.388 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have created the AccountAgeWitnessStore store for the live data and filled it with 0 entries from the persisted data. 
Mar-15 21:11:48.391 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=AccountAgeWitnessStore_1.4.0_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\AccountAgeWitnessStore_1.4.0 
Mar-15 21:11:48.392 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: Could not find resourceFile AccountAgeWitnessStore_1.4.0_BTC_MAINNET. That is expected if none is provided yet. 
Mar-15 21:11:48.394 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=AccountAgeWitnessStore_1.5.0_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\AccountAgeWitnessStore_1.5.0 
Mar-15 21:11:48.395 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: Could not find resourceFile AccountAgeWitnessStore_1.5.0_BTC_MAINNET. That is expected if none is provided yet. 
Mar-15 21:11:48.395 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=AccountAgeWitnessStore_1.5.2_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\AccountAgeWitnessStore_1.5.2 
Mar-15 21:11:48.433 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=AccountAgeWitnessStore_1.5.5_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\AccountAgeWitnessStore_1.5.5 
Mar-15 21:11:48.438 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=AccountAgeWitnessStore_1.5.7_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\AccountAgeWitnessStore_1.5.7 
Mar-15 21:11:48.444 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=AccountAgeWitnessStore_1.6.0_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\AccountAgeWitnessStore_1.6.0 
Mar-15 21:11:48.450 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=AccountAgeWitnessStore_1.6.3_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\AccountAgeWitnessStore_1.6.3 
Mar-15 21:11:48.455 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=AccountAgeWitnessStore_1.6.5_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\AccountAgeWitnessStore_1.6.5 
Mar-15 21:11:48.461 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=AccountAgeWitnessStore_1.7.2_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\AccountAgeWitnessStore_1.7.2 
Mar-15 21:11:48.466 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=AccountAgeWitnessStore_1.7.4_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\AccountAgeWitnessStore_1.7.4 
Mar-15 21:11:48.470 [PersistenceManager-read-AccountAgeWitnessStore_1.6.0] INFO  b.c.p.PersistenceManager: Reading AccountAgeWitnessStore_1.6.0 completed in 16 ms 
Mar-15 21:11:48.472 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=AccountAgeWitnessStore_1.8.0_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\AccountAgeWitnessStore_1.8.0 
Mar-15 21:11:48.471 [PersistenceManager-read-AccountAgeWitnessStore_1.5.7] INFO  b.c.p.PersistenceManager: Reading AccountAgeWitnessStore_1.5.7 completed in 26 ms 
Mar-15 21:11:48.472 [PersistenceManager-read-AccountAgeWitnessStore_1.6.3] INFO  b.c.p.PersistenceManager: Reading AccountAgeWitnessStore_1.6.3 completed in 17 ms 
Mar-15 21:11:48.474 [PersistenceManager-read-AccountAgeWitnessStore_1.5.5] INFO  b.c.p.PersistenceManager: Reading AccountAgeWitnessStore_1.5.5 completed in 35 ms 
Mar-15 21:11:48.502 [PersistenceManager-read-AccountAgeWitnessStore_1.7.4] INFO  b.c.p.PersistenceManager: Reading AccountAgeWitnessStore_1.7.4 completed in 30 ms 
Mar-15 21:11:48.503 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have created the TradeStatistics3Store store for the live data and filled it with 0 entries from the persisted data. 
Mar-15 21:11:48.512 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=TradeStatistics3Store_1.4.0_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\TradeStatistics3Store_1.4.0 
Mar-15 21:11:48.532 [PersistenceManager-read-AccountAgeWitnessStore_1.6.5] INFO  b.c.p.PersistenceManager: Reading AccountAgeWitnessStore_1.6.5 completed in 59 ms 
Mar-15 21:11:48.565 [PersistenceManager-read-AccountAgeWitnessStore_1.8.0] INFO  b.c.p.PersistenceManager: Reading AccountAgeWitnessStore_1.8.0 completed in 83 ms 
Mar-15 21:11:48.567 [PersistenceManager-read-AccountAgeWitnessStore_1.7.2] INFO  b.c.p.PersistenceManager: Reading AccountAgeWitnessStore_1.7.2 completed in 50 ms 
Mar-15 21:11:48.622 [PersistenceManager-read-BlindVoteStore] INFO  b.c.p.PersistenceManager: Reading BlindVoteStore completed in 244 ms 
Mar-15 21:11:48.640 [PersistenceManager-read-AccountAgeWitnessStore_1.5.2] INFO  b.c.p.PersistenceManager: Reading AccountAgeWitnessStore_1.5.2 completed in 206 ms 
Mar-15 21:11:48.645 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=TradeStatistics3Store_1.5.0_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\TradeStatistics3Store_1.5.0 
Mar-15 21:11:48.664 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=TradeStatistics3Store_1.5.2_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\TradeStatistics3Store_1.5.2 
Mar-15 21:11:48.666 [PersistenceManager-read-ProposalStore] INFO  b.c.p.PersistenceManager: Reading ProposalStore completed in 300 ms 
Mar-15 21:11:48.679 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=TradeStatistics3Store_1.5.5_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\TradeStatistics3Store_1.5.5 
Mar-15 21:11:48.744 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=TradeStatistics3Store_1.5.7_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\TradeStatistics3Store_1.5.7 
Mar-15 21:11:48.770 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=TradeStatistics3Store_1.6.0_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\TradeStatistics3Store_1.6.0 
Mar-15 21:11:48.776 [PersistenceManager-read-TradeStatistics3Store_1.5.0] INFO  b.c.p.PersistenceManager: Reading TradeStatistics3Store_1.5.0 completed in 103 ms 
Mar-15 21:11:48.787 [PersistenceManager-read-SignedWitnessStore] INFO  b.c.p.PersistenceManager: Reading SignedWitnessStore completed in 428 ms 
Mar-15 21:11:48.794 [PersistenceManager-read-TradeStatistics3Store_1.5.2] INFO  b.c.p.PersistenceManager: Reading TradeStatistics3Store_1.5.2 completed in 109 ms 
Mar-15 21:11:48.831 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=TradeStatistics3Store_1.6.3_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\TradeStatistics3Store_1.6.3 
Mar-15 21:11:48.833 [PersistenceManager-read-TradeStatistics3Store_1.5.7] INFO  b.c.p.PersistenceManager: Reading TradeStatistics3Store_1.5.7 completed in 63 ms 
Mar-15 21:11:48.843 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=TradeStatistics3Store_1.6.5_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\TradeStatistics3Store_1.6.5 
Mar-15 21:11:48.922 [PersistenceManager-read-TradeStatistics3Store_1.5.5] INFO  b.c.p.PersistenceManager: Reading TradeStatistics3Store_1.5.5 completed in 181 ms 
Mar-15 21:11:48.924 [PersistenceManager-read-TradeStatistics3Store_1.6.0] INFO  b.c.p.PersistenceManager: Reading TradeStatistics3Store_1.6.0 completed in 91 ms 
Mar-15 21:11:48.929 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=TradeStatistics3Store_1.7.2_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\TradeStatistics3Store_1.7.2 
Mar-15 21:11:48.942 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=TradeStatistics3Store_1.7.4_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\TradeStatistics3Store_1.7.4 
Mar-15 21:11:48.944 [PersistenceManager-read-TradeStatistics3Store_1.6.3] INFO  b.c.p.PersistenceManager: Reading TradeStatistics3Store_1.6.3 completed in 78 ms 
Mar-15 21:11:48.961 [JavaFX Application Thread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=TradeStatistics3Store_1.8.0_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\TradeStatistics3Store_1.8.0 
Mar-15 21:11:49.000 [PersistenceManager-read-TradeStatistics3Store_1.6.5] INFO  b.c.p.PersistenceManager: Reading TradeStatistics3Store_1.6.5 completed in 70 ms 
Mar-15 21:11:49.029 [PersistenceManager-read-TradeStatistics3Store_1.7.2] INFO  b.c.p.PersistenceManager: Reading TradeStatistics3Store_1.7.2 completed in 84 ms 
Mar-15 21:11:49.053 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from AccountAgeWitnessStore_1.6.0 3850 historical items. 
Mar-15 21:11:49.054 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.6.0 was applied 
Mar-15 21:11:49.061 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from AccountAgeWitnessStore_1.5.7 5287 historical items. 
Mar-15 21:11:49.062 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.5.7 was applied 
Mar-15 21:11:49.067 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from AccountAgeWitnessStore_1.6.3 3930 historical items. 
Mar-15 21:11:49.068 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.6.3 was applied 
Mar-15 21:11:49.071 [PersistenceManager-read-TradeStatistics3Store_1.7.4] INFO  b.c.p.PersistenceManager: Reading TradeStatistics3Store_1.7.4 completed in 100 ms 
Mar-15 21:11:49.073 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from AccountAgeWitnessStore_1.5.5 5985 historical items. 
Mar-15 21:11:49.074 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.5.5 was applied 
Mar-15 21:11:49.078 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from AccountAgeWitnessStore_1.7.4 5542 historical items. 
Mar-15 21:11:49.078 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.7.4 was applied 
Mar-15 21:11:49.083 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from AccountAgeWitnessStore_1.6.5 3465 historical items. 
Mar-15 21:11:49.083 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.6.5 was applied 
Mar-15 21:11:49.089 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from AccountAgeWitnessStore_1.8.0 9517 historical items. 
Mar-15 21:11:49.090 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.8.0 was applied 
Mar-15 21:11:49.093 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from AccountAgeWitnessStore_1.7.2 3818 historical items. 
Mar-15 21:11:49.094 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.7.2 was applied 
Mar-15 21:11:49.132 [PersistenceManager-read-TradeStatistics3Store_1.8.0] INFO  b.c.p.PersistenceManager: Reading TradeStatistics3Store_1.8.0 completed in 118 ms 
Mar-15 21:11:49.147 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from AccountAgeWitnessStore_1.5.2 70283 historical items. 
Mar-15 21:11:49.148 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.5.2 was applied 
Mar-15 21:11:49.287 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from TradeStatistics3Store_1.5.0 3000 historical items. 
Mar-15 21:11:49.287 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.5.0 was applied 
Mar-15 21:11:49.289 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from TradeStatistics3Store_1.5.2 4230 historical items. 
Mar-15 21:11:49.289 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.5.2 was applied 
Mar-15 21:11:49.291 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from TradeStatistics3Store_1.5.7 3800 historical items. 
Mar-15 21:11:49.291 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.5.7 was applied 
Mar-15 21:11:49.293 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from TradeStatistics3Store_1.5.5 5954 historical items. 
Mar-15 21:11:49.294 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.5.5 was applied 
Mar-15 21:11:49.295 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from TradeStatistics3Store_1.6.0 3660 historical items. 
Mar-15 21:11:49.295 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.6.0 was applied 
Mar-15 21:11:49.297 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from TradeStatistics3Store_1.6.3 3436 historical items. 
Mar-15 21:11:49.298 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.6.3 was applied 
Mar-15 21:11:49.301 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from TradeStatistics3Store_1.6.5 3515 historical items. 
Mar-15 21:11:49.301 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.6.5 was applied 
Mar-15 21:11:49.303 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from TradeStatistics3Store_1.7.2 5195 historical items. 
Mar-15 21:11:49.303 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.7.2 was applied 
Mar-15 21:11:49.307 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from TradeStatistics3Store_1.7.4 6760 historical items. 
Mar-15 21:11:49.308 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.7.4 was applied 
Mar-15 21:11:49.313 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from TradeStatistics3Store_1.8.0 10225 historical items. 
Mar-15 21:11:49.313 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.8.0 was applied 
Mar-15 21:11:49.394 [PersistenceManager-read-TradeStatistics3Store_1.4.0] INFO  b.c.p.PersistenceManager: Reading TradeStatistics3Store_1.4.0 completed in 741 ms 
Mar-15 21:11:49.412 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: We have read from TradeStatistics3Store_1.4.0 75912 historical items. 
Mar-15 21:11:49.412 [JavaFX Application Thread] INFO  b.n.p.s.p.HistoricalDataStoreService: No pruning from historical data store with version 1.4.0 was applied 
Mar-15 21:11:50.424 [copyBsqBlocksFromResources] INFO  b.c.d.s.s.BsqBlocksStorageService: Copying 143 resource files took 2045 ms 
Mar-15 21:11:50.425 [copyBsqBlocksFromResources] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=DaoStateStore_BTC_MAINNET, destinationFile=C:\Users\selim\AppData\Roaming\Bisq\btc_maınnet\db\DaoStateStore 
Mar-15 21:11:50.893 [PersistenceManager-read-DaoStateStore] INFO  b.c.p.PersistenceManager: Reading DaoStateStore completed in 237 ms 
Mar-15 21:11:51.925 [Read-BsqBlocksStore] INFO  b.c.d.s.s.BlocksPersistence: Reading 141494 blocks took 1021 msec 
Mar-15 21:11:52.332 [Read-BsqBlocksStore] INFO  b.c.d.s.s.BsqBlocksStorageService: Reading and deserializing 141494 blocks took 1429 ms 
Mar-15 21:11:52.344 [JavaFX Application Thread] INFO  b.c.a.BisqSetup: Init P2P network 
Mar-15 21:11:52.356 [NetworkNode-9999] INFO  b.n.p.n.NewTor: Starting tor 
Mar-15 21:11:52.357 [JavaFX Application Thread] INFO  b.c.a.BisqSetup: walletInitialized=false, p2pNetWorkReady=false 
Mar-15 21:11:54.885 [NetworkNode-9999] INFO  o.b.n.tor.Tor: Starting Tor

**Comment by ghost** [comment]
Thanks.  Bisq gets its list of seednodes from three possible places, firstly a Java resource file which is built into the executable; or `bisq.properties` (under C:\Users\selim\AppData\Roaming\Bisq), or a command line parameter `--seedNodes=`.  The built-in resource is used for the vast majority of users.  Judging by the logs, it seems to have failed to read the resource file, which is very weird.

Could you try running bisq with the following command line parameter added:

```--seedNodes=devinsn3xuzxhj6pmammrxpydhwwmwp75qkksedo5dn2tlmu7jggo7id.onion:8000```

Or add seedNodes to your `bisq.properties` file:


    daoActivated=true
    bannedSeedNodes=
    bannedBtcNodes=165.227.34.198:8333,btc1.dnsalias.net:8333
    bannedPriceRelayNodes=
    seedNodes=devinsn3xuzxhj6pmammrxpydhwwmwp75qkksedo5dn2tlmu7jggo7id.onion:8000, wizseed3d376esppbmbjxk2fhk2jg5fpucddrzj2kxtbxbx4vrnwclad.onion:8000, wizseed7ab2gi3x267xahrp2pkndyrovczezzb46jk6quvguciuyqrid.onion:8000, sn3bsq3evqkpshdmc3sbdxafkhfnk7ctop44jsxbxyys5ridsaw5abyd.onion:8000



The full list can be seen [here](https://github.com/bisq-network/bisq/blob/master/core/src/main/resources/btc_mainnet.seednodes).

**Comment by xyzmaker123** [comment]
> it seems to have failed to read the resource file, which is very weird.

According to  [this article](https://github.com/bisq-network/bisq/blob/35ede06037dba8df57ed36f5fb946d3094fbf227/core/src/main/java/bisq/core/network/p2p/seed/DefaultSeedNodeRepository.java#L92) there is difference how `ClassLoader` vs `Class` handles file name.

There is a chance that change in [this line](https://github.com/bisq-network/bisq/blob/35ede06037dba8df57ed36f5fb946d3094fbf227/core/src/main/java/bisq/core/network/p2p/seed/DefaultSeedNodeRepository.java#L92) could fix issue:

```
DefaultSeedNodeRepository.class.getClassLoader().getResourceAsStream(...)
```
to
```
DefaultSeedNodeRepository.class.getResourceAsStream(...)
```

**Comment by cekickafa** [comment]
bisq.properties file was missing, I created a new file under roaming and it connected to tor.

Note:
One other thing I noticed, _Appdata\Roaming\Bisq\mainnet_ folder is created as _Appdata\Roaming\Bisq\maınnet_  
It uses Turkish lower 'ı' instead of "i" in folder name.
