### ISSUE TITLE
Onion shouldn't listen on 127.0.0.1 if running on Whonix

### ISSUE THREAD

**Issue by JeremyRand** [bisq-network/bisq#6149]
### Description

Bisq's P2P onion listens on `127.0.0.1`.  This is typically correct, but is not correct behavior on Whonix, since the Tor daemon is on a different VM and therefore cannot connect to a localhost socket.

#### Version

Bisq v1.8.4.

### Steps to reproduce

1. Install Bisq on Whonix as per the Whonix wiki instructions.
2. `netstat -lnt`

### Expected behaviour

The local address associated with the Bisq P2P onion should have an IP of `0.0.0.0`.

### Actual behaviour

The local address associated with the Bisq P2P onion has an IP of `127.0.0.1`.

### Screenshots

N/A, not GUI-related.

#### Device or machine

Haswell i7; Whonix 16 inside Qubes 4.1.

#### Additional info

The current best practice for detecting what IP to listen on for onion connections is at http://www.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion/wiki/Dev/Project_friendly_applications_best_practices#Listen_Interface .  Specifically, Bisq should check for the existence of `/usr/share/anon-ws-base-files/workstation`, and if that file exists, Bisq should listen on `0.0.0.0`, otherwise use `127.0.0.1`.

Note that these best practices are currently being restructured by the Whonix, Tor, Ricochet, and Namecoin devs, so the advice will change at some point -- but for now, the above recommendation is what should be followed.

**Comment by Emzy** [comment]
Ok I see Whonix only allows tor trough a proxy.
Opening 0.0.0.0 for all Bisq users is a very bad thing. Think of using your notebook with Bisq in a public WIFI.
This needs to be a special option only for Whonix.
