### ISSUE TITLE
Removing an offer should specify fee amount lost

### ISSUE THREAD

**Issue by jonathancross** [bisq-network/bisq#615]
When a user removes an offer, they are presented with this warning message:
_"The offer fee you have paid will be lost if you remove that offer."_ [1]

The specific offer fee amount should be included in that message so that the user can make an informed decision.

[1] https://github.com/bitsquare/bitsquare/blob/master/gui/src/main/java/io/bitsquare/gui/main/portfolio/openoffer/OpenOffersView.java#L114

**Comment by ManfredKarrer** [comment]
Good idea.

**Comment by haiqu** [comment]
OK, this one should be closed.
