### ISSUE TITLE
 Chat message high CPU and long processing time

### ISSUE THREAD

**Issue by progonkpa** [bisq-network/bisq#6150]
### Description

Chat message high CPU and long processing time

#### Version

1.8.4

### Steps to reproduce

- start trade
- send message

### Expected behaviour

Message sent after a few seconds.

### Actual behaviour

Processing took minutes first, now it doesn't arrive anymore

#### Device or machine

Linux Manjaro.

#### Additional info

I have chatted successfully with this person.
It was only later on that this issue started.
The message still went through at that point after a long time.
Now they don't arrive anymore.

I did change the font-size in bisq-desktop though I don't think this could cause the issue, at any rate, it's this line.

`DEFAULT_JVM_OPTS="-XX:MaxRAM=8g -Xss1280k -XX:+UseG1GC -XX:MaxHeapFreeRatio=10 -XX:MinHeapFreeRatio=5 -XX:+UseStringDeduplication -Djava.net.preferIPv4Stack=true -Dglass.gtk.uiScale=1.25"`

-Dglass was simply added.

There was also a big Manjaro update of 1,4GB in the timespan of the issue.
Here are some logs of the update that might be of relevance.

[2022-04-14T21:51:52+0200] [ALPM] upgraded bisq (1.8.2-1 -> 1.8.4-1)
[2021-12-14T11:10:21+0100] [ALPM] installed jdk11-openjdk (11.0.13.u8-1)
[2021-12-14T11:10:21+0100] [ALPM] installed java-environment-common (3-3)
[2021-12-14T11:10:21+0100] [ALPM] installed jre11-openjdk (11.0.13.u8-1)
[2021-12-14T11:10:21+0100] [ALPM] installed jre11-openjdk-headless (11.0.13.u8-1)

**Comment by ghost** [comment]
Maybe Tor got a stale circuit in its cache.

If you are having problems sending a message, try clearing your tor cache.  In the UI, go to Settings -> Network Settings -> `Open Tor Settings` -> `Delete Outdated Tor Files And Shutdown`
Then after restart, try sending a new message.

**Comment by progonkpa** [comment]
> Maybe Tor got a stale circuit in its cache.
> 
> If you are having problems sending a message, try clearing your tor cache. In the UI, go to Settings -> Network Settings -> `Open Tor Settings` -> `Delete Outdated Tor Files And Shutdown` Then after restart, try sending a new message.

I did this and the issue went away. Ty sir !

**Comment by progonkpa** [comment]
> Maybe Tor got a stale circuit in its cache.
> 
> If you are having problems sending a message, try clearing your tor cache. In the UI, go to Settings -> Network Settings -> `Open Tor Settings` -> `Delete Outdated Tor Files And Shutdown` Then after restart, try sending a new message.

I did this and the issue went away. Ty sir !
