### ISSUE TITLE
Invalid dates displayed in "Market/Trades" view

### ISSUE THREAD

**Issue by ahmogit** [bisq-network/bisq#6151]
### Description
The price and volume charts in the "Market/Trades" view often show invalid dates on the time axis. See example screenshot.

Unable to reproduce consistently, but have seen it many times. The invalid date is often the unix epoch 0 date (Dec. 31, 1969), as in the attached example. 

#### Version
1.8.4, Arch linux, from package bisq-bin 1.8.4-1

### Steps to reproduce

Unable to find the magic incantation that causes it, but have seen it many times during normal use. It is not a rare occurrance.

### Expected behaviour

Correct dates shown.

### Actual behaviour

Wrong dates shown. See time axis on screenshot

### Screenshots

attached

#### Device or machine

i86_64 commodity laptop
![bisq_ui_date_bug](https://user-images.githubusercontent.com/5025879/163672165-9bbac028-f305-4a28-86c6-1ae775c56f91.jpg)

**Comment by ghost** [comment]
I tried but couldn't reproduce this issue. It's probably either:
- bug in [number to date string converter code](https://github.com/bisq-network/bisq/blob/a659a78db6bac144edc432f5b87417ac0702dd88/desktop/src/main/java/bisq/desktop/main/market/trades/TradesChartsView.java#L640-L678)
- invalid data [stored on disk](https://github.com/bisq-network/bisq/blob/589404f928fe368eecd0beec89c2ed993e00859b/core/src/main/java/bisq/core/trade/statistics/TradeStatisticsManager.java#L113-L118)

**Comment by ahmogit** [comment]
Interesting. I'll try to come up with a recipe for reproducing it. 

The interesting thing is that on my system, this  behavior is quite common;  I'd guess that invalid dates are displayed on startup about 1/3 of the time,  perhaps even more often than that. 

One additional observation, fwiw: Iirc, the invalid dates usually show up only when the candle time interval (upper right selector) is set to "day".  If I switch the candle interval to "hour" and then immediately back to "day", the dates shown in the "day" view have reverted to correct.

**Comment by ghost** [comment]
To reproduce:

- Click on Market -> Trades.  The volume chart is shown correctly.
- Change the currency filter.
- Click on another menu, e.g. Settings.
- Click on Market -> Trades.  The volume chart is shown with all dates=31/Dec/1969.

**Comment by ahmogit** [comment]
Nice detective work Opie, thanks!   I can confirm it fails for me consistently in bisq 1.9.1, using exactly the sequence you state.

How did you find this? I clicked and clacked around for the better part of an hour and couldn't come up with the magic formula that would reproduce it consistently. 

Anyway...  thanks again for the legwork. Your recipe ought to render it easily debuggable by the devs.
