### ISSUE TITLE
running near 1000x slower on x11 forwarding from linux host

### ISSUE THREAD

**Issue by protontopeon** [bisq-network/bisq#6155]
### Description

Have installed bisq on linux server both fedora and debian.  When using MobaXterm and starting bisq I get the following messages and error.  Messages have been trunkated.

Apr-23 15:12:16.581 [main] INFO  bisq.common.util.Utilities: System info: os.name=Linux; os.version=5.16.8-200.fc35.x86_64; os.arch=amd64; sun.arch.data.model=64; JRE=15.0.6+5-MTS (Azul Systems, Inc.); JVM=15.0.6+5-MTS (OpenJDK 64-Bit Server VM)
Apr-23 15:12:16.656 [main] INFO  bisq.common.app.AsciiLogo:

                    ........                  ......
                ..............                ......
              .................               ......
            ......   ..........   ..          ......
           ......      ......   ......        ...............        .....     .........         ..........
          .......              ........       ..................     .....   .............     ...............
          ......               ........       ..........  .......    .....  ......   ...     ........   .......
         ......                   .....       .......        .....   .....  .....            .....        ......
         ......    ...        ...             ......         ......  .....   ...........    ......         ......
         ......   .....      ....             ......         ......  .....    ............  .....          ......
          ......                               .....         ......  .....         ........ ......         ......
           ......       ....        ...        ......       ......   .....    ..     ......  ......      ........
            ........     ..      .......        .................    .....  ..............    ...................
             ..........       .........           .............      .....   ............       .................
               ......................                 .....                      ....               ....   ......
                  ................                                                                         ......
                        ....                                                                               ......
                                                                                                           ......

Apr-23 15:12:16.667 [main] INFO  bisq.common.app.Version: Version{VERSION=1.8.4, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=4, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10}
Apr-23 15:12:16.669 [main] INFO  bisq.common.setup.CommonSetup: Path to Bisq jar file: /opt/bisq/lib/app/desktop-1.8.4-all.jar
Apr-23 15:12:16.674 [main] INFO  bisq.common.util.Profiler: Total memory: 128 MB; Used memory: 10.41 MB; Free memory: 117.59 MB; Max memory: 2 GB; No. of threads: 1
Apr-23 15:12:16.698 [main] INFO  b.c.s.CoreNetworkCapabilities: TRADE_STATISTICS [0], TRADE_STATISTICS_2 [1], ACCOUNT_AGE_WITNESS [2], PROPOSAL [5], BLIND_VOTE [6], ACK_MSG [7], RECEIVE_BSQ_BLOCK [8], DAO_STATE [9], BUNDLE_OF_ENVELOPES [10], SIGNED_ACCOUNT_AGE_WITNESS [11], MEDIATION [12], REFUND_AGENT [13], TRADE_STATISTICS_HASH_UPDATE [14], NO_ADDRESS_PRE_FIX [15], TRADE_STATISTICS_3 [16], BSQ_SWAP_OFFER [17]
Apr-23 15:12:16.706 [main] INFO  b.core.locale.GlobalSettings: Locale info: en_US
Apr 23, 2022 3:12:16 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6e2829c7'
libGL error: MESA-LOADER: failed to open swrast: /usr/lib64/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix _dri)
libGL error: failed to load driver: swrast
Prism-ES2 Error : GL_VERSION (major.minor) = 1.4
Apr-23 15:12:54.446 [JavaFX Application Thread] INFO  b.c.a.AvoidStandbyModeService: Started -- disabled power management via /usr/bin/systemd-inhibit --who Bisq --what sleep --why Avoid Standby --mode block tail -f /dev/null

Then the x11 window pops up with the disclaimer, once clicked it appears to be frozen but the cursor still moves.  About 10 minutes later the screen changes to a screen with a black rectangle in a larger white rectangle which I assume will eventually turn into whatever is past the disclaimer screen.  Window eventually turns into a "Must not create multiple "PersistanceManager instances for file TradeStatistics3Store." error.  Unfortunately because it is running so slow I was unsure what button I pressed but eventually found out I pressed report to github since the log file never opened but the github link window did.

It appears to be progressing to the app at 1000x slower than expected speed but I am seeing the following error on the host CLI

Apr-23 15:34:13.708 [JavaFX Application Thread] INFO  bisq.common.util.DesktopUtil: Trying to exec: cmd = gnome-open args = %s file = https://bisq.network/source/bisq/issues?utm_source=desktop-client&utm_medium=in-app-link&utm_campaign=language_en
Apr-23 15:34:13.710 [JavaFX Application Thread] WARN  bisq.common.util.DesktopUtil: Error running command. java.io.IOException: Cannot run program "gnome-open": error=2, No such file or directory

#### Version

v1.8.4

### Steps to reproduce

Spin up debian or fedora 35 host

If running fedora install x11 with these instructions https://ostechnix.com/how-to-configure-x11-forwarding-using-ssh-in-linux/

Install Bisq v1.8.4

run Bisq from MobaXterm SSH with x11 forwarding

### Expected behaviour

Run Bisq in x11 window on guest computer without issue

### Actual behaviour

Get Bisq to open in x11 window but receive error messages and extremely slow response, to the point it appears frozen.

### Screenshots

![bisq](https://user-images.githubusercontent.com/36967364/164913042-f1e92995-f55b-4607-92b2-9d792ac93960.PNG)

#### Device or machine

Fedora 35 4 gig ram host via MobaXTerm on a windows 10 pro guest.

**Comment by ghost** [comment]
See if this helps: https://stackoverflow.com/questions/40092796/libgl-error-failed-to-load-driver-swrast-running-ubuntu-docker-container-on#61280907
