### ISSUE TITLE
When creating an offer it does not recognize the account currency

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#6157]
With current main branch version If the user has set up an account and has the offer book set to Show all currencies and creates an offer they get displayed the popup that they need to set up an account. Only if the user selects the currency of their account first they can create an offer.

**Comment by ghost** [comment]
I wasn't able to reproduce it - it seems to be an edge case scenario. Could you provide more details about your setup (f.e. preferred currency in settings, existing accounts, market etc.)?

![reproduce](https://user-images.githubusercontent.com/84982606/164973296-b4754bdc-d02e-4102-b257-f3cb9bdc261f.gif)

**Comment by ghost** [comment]
UPDATE: 
I switched preferred currency to GBP, I didn't had GBP account. Now I see "need to set up an account." popup always when trying to create new FIAT offer, no matter of chosen currency in filters.

@ripcurlx It seems to be related with [Improve navigation structure](https://github.com/bisq-network/bisq/pull/6135).

**Comment by chimp1984** [comment]
I used an new app with AliPay account. Had offerbook with ShowAll currencies. The clicked create offer and got the popup.
Only if I selected CNY first I could create an offer.

**Comment by ripcurlx** [comment]
> I switched preferred currency to GBP, I didn't had GBP account. Now I see "need to set up an account." popup always when trying to create new FIAT offer, no matter of chosen currency in filters.

Yes, both cases are because of the default currency set, with no payment account available. I'll have a look to make this more robust against such use cases.
