### ISSUE TITLE
Big privacy issue

### ISSUE THREAD

**Issue by Ersuin** [bisq-network/bisq#6159]
I am not sure about if this is a bug, or a request. By the nature of the problem, I think it is a bug. Sorry if it is not

### Description

Visible onion addresses are a big privacy issue: as long as onion address-based tags can be set or simply viewed, different offers taken or made by users can be interconnected. For example, if a user wants to exchange F2F without giving any personal data, an attacker could take that offer and then analyze all the new offers that this user could create (this is very easy if he only has to put a label). In this way, if the user creates a new SEPA order after the F2F trade, the attacker could have the face, first name, last name, the bank and the meeting city. The same happens if a bizum offer is created.
This destroys all the privacy of a regular Bisq user, because over time, a malicious attacker could interrelate the different offers that a user takes and thus create a profile with all his information.

My idea is to keep the possibility of tagging a payment account, but nothing further than that. This label will not be maintained in any case between new payment accounts, nor will the onion address be displayed. Ideally, no one could relate that 2 payment accounts belong to the same user.

#### Version

1.8.4

**Comment by jmacxx** [comment]
[You can switch to a fresh onion address](https://bisq.wiki/Changing_your_onion_address) after each trade if necessary.  Bisq2 (currently being developed) will make it easier to switch identities.

There's some tradeoff with wiping your onion though, as buyers like to make repeat purchases from sellers, which is less likely to happen if they cannot find the seller again.  The reason for that stickiness is trading with someone who has proved to be reliable reduces risk.

**Comment by Ersuin** [comment]
Thank you.

Could be difficult to implement a system similar to friend request in social media?
I mean, if anyone wants to keep trading with somebody, he could send "friend request" and if the other trader accepts, both onion address become visible. 
In this way, nobody could be able to track a user if that user doesn't allow it.

**Comment by Ersuin** [comment]
I see... Anyway, not every attacker is a sophisticated one or a hacker. Sometimes people isn't just healthy and does not know how to find that address, or it's lazy... If hide it from IU could increase the difficulty, maybe it is a good way to mitigate the problem until the new version is released.

Anyway, thank you for your attention in this matter. I really want to see Bisq2 🚀
