### ISSUE TITLE
[v1.9.0] Newly created SEPA account can't be deleted

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#6161]
### Description

A newly created payment account can't be deleted immediately

#### Version

v1.9.0

### Steps to reproduce

1. Create SEPA account
2. Delete SEPA account

### Expected behaviour

Account is deleted and removed from list.

### Actual behaviour

It is not deleted from list.

#### Additional info

Existing accounts can be deleted.

**Comment by ripcurlx** [comment]
@xyzmaker123 Can it be that this is related to one of your changes?

**Comment by ghost** [comment]
I'll check it
