### ISSUE TITLE
[v1.9.0] Trying to change account name of same bank account fails with Nullpointer exception

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#6162]
### Description

Use existing transfer with same bank account and try to change the account name.

#### Version

v1.9.0

### Steps to reproduce

1. Use existing account (e.g. Transfer with same bank)
2. Click into Account name and try to change it.

### Expected behaviour

You are able to change the account name.

### Actual behaviour

It throws a Nullpointer exception

### Screenshots

<img width="1337" alt="Bildschirmfoto 2022-04-25 um 13 05 01" src="https://user-images.githubusercontent.com/170962/165077341-5ea699c0-c6c5-4e9f-8377-5e20408493c4.png">

#### Additional info

It does work e.g. with Perfect Money.

**Comment by ripcurlx** [comment]
@xyzmaker123 Another one for you? ☝️  😅

**Comment by ghost** [comment]
I'll investigate it :)
