### ISSUE TITLE
bisq-statsnode fails to dump JSON for a valid BSQ transaction

### ISSUE THREAD

**Issue by wiz** [bisq-network/bisq#6165]
I created a compensation request proposal DAO transaction and it was mined into a block.
However, bisq-statsnode does not create a `<txid>.json` file for this transaction. This causes the following issue:

Layer 1: https://mempool.space/tx/e92376b61e76dc59961b9d570cc6700603c37c1a58ff5330847782db5a949b47
Layer 2: https://bisq.markets/tx/e92376b61e76dc59961b9d570cc6700603c37c1a58ff5330847782db5a949b47

The comp req TX is valid on other bisq nodes, so I'm not sure why this TX fails to appear on my bisq-statsnode instances.
I am running v1.8.4 - any idea?

**Comment by Emzy** [comment]
For what it's worth the transaction shows up on my explorer:
 
Layer 2: https://bisq.mempool.emzy.de/tx/e92376b61e76dc59961b9d570cc6700603c37c1a58ff5330847782db5a949b47

**Comment by wiz** [comment]
@chimp1984 was this the issue you said was caused by the state getting out of sync between DAO and JSON objects?
