### ISSUE TITLE
Bitsquare app doesn't detect if already running

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#617]
I just managed to start two instances of the Bitsquare app. That shouldn't be allowed to happen.

**Comment by ManfredKarrer** [comment]
You get displayed then a popup, right? I cannot prevent that users click the app 2 times to start, but it stops when it tries to load the wallet as that has a lock.
If you managed to startup 2 times the app in normal mode (no error popup) then please let me know hwo u managed that.

**Comment by haiqu** [comment]
No, it fails to start due to the lock, but it can be confusing to work out why it won't run properly. I did it by accidentally double-clicking the taskbar shortcut and they both started before either of them was at the stage to lock the other one out. Not sure how that can be prevented.

**Comment by ManfredKarrer** [comment]
Then the second should get the popup where the text gives info that it was probably started twice. If you did not get that it might be a rare race condition causing the popup to not get displayed.

**Comment by ManfredKarrer** [comment]
If u can reproduce it u can have a look how to fix it.

**Comment by haiqu** [comment]
I'll add it to the list. :)

**Comment by ManfredKarrer** [comment]
If u can reproduce please re-open.
