### ISSUE TITLE
In Market/OfferBook: Highlight user's own offers

### ISSUE THREAD

**Issue by ahmogit** [bisq-network/bisq#6171]
### Description
In Market/OfferBook,  the user's own offers are visually identical in format wih everyone else's. It would be nice to visually distinguish them in some way, e.g. highlighting or outlining.

Why? Because the icons currently used to identify users are too small to visually differentiate without zooming in. It's not easy to tell who is "you".  Many icons appear nearly identical from typical screen viewing distance. Highlighting one's own offer lines would be helpful. (Or, as a more general solution: Replace the existing user icons with a more orthogonal and visually differentiable set, so that you can distinguish your own icon more easily from others)

#### Version
1.8.4

### Steps to reproduce
Make offer. Open Market/OfferBook view.

### Desired behaviour
Highlight or somehow distinguish user's own offers in Market/OfferBook view

### Actual behaviour
User's own offers appear idential to everyone else's (afaict)

#### Device or machine
Arch linux, commodity laptop.

**Comment by ripcurlx** [comment]
If you go to the actual offerbook where you can take offers, your own offers will jump out as they have the option to be deleted or edited.

**Comment by ahmogit** [comment]
I'm aware of that, but it doesn't really address what I had asked for, which was to highlight the user's own trades directly on the Market/OfferBook screen, so they can be observed simultaneously with the offer volume plot, which displays the current spread situation.

The view that you're talking about is one level deeper than the Market/OfferBook view itself, and it does not actually show the full offer book; it shows only either buy-side orders or sell-side offers, and also does not display the volume chart. So if you have open orders on both sides, you can't see both, only one set. This is exactly the reason for asking that the user's offers be highlighed on the Market/OfferBook screen, i.e. so that the user can see all of his offers within the context of the current spread situation (which is only understandable if you can see both sides of the book.)
