### ISSUE TITLE
Add macOS Universal Binary with Apple Silicon M1 support

### ISSUE THREAD

**Issue by k0gen** [bisq-network/bisq#6180]
### Description

Right now bisq runs on M1 Macs via Rosetta2 (intel emulator) and can be quite heavy on resources. 

#### Version

v1.8.4

### Steps to reproduce

1. Use any M1 Mac machine
2. Run bisq

### Expected behaviour

Recompile bisq for native M1 support as an separate or universal binary

### Screenshots
<img width="1061" alt="Screenshot 2022-04-28 at 16 07 44" src="https://user-images.githubusercontent.com/3606313/165772988-07f7c689-79b4-4c5c-b5f2-21ace5d9229a.png">

**Comment by acantril** [comment]
any update on this one, it seems a bit silly not to have one years after introduction.

**Comment by acantril** [comment]
i'd sponsor or part sponsor the work ... it's just silly it isn't available yet

**Comment by ripcurlx** [comment]
> i'd sponsor or part sponsor the work ... it's just silly it isn't available yet

There is work going on in https://github.com/bisq-network/bisq/pull/5835, but I'm not sure if it is worth the effort as Bisq 2 will be M1 compatible and the first iteration of it might be released soon.

**Comment by finnatsea** [comment]
Is there an eta for an apple silicon build?

I'm of fan of bisq and the mission but the app is a TOTAL lag fest on an M1 atm.

**Comment by azizsayfiddin** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/114720383/209735358-316dfce2-4581-46e4-8d67-18aa46d3bc74.png">

**Comment by k0gen** [comment]
Ah, those bots nowadays. 🙄

**Comment by javihache** [comment]
Is this expected at some point?

**Comment by javihache** [comment]
> > i'd sponsor or part sponsor the work ... it's just silly it isn't available yet
> 
> There is work going on in #5835, but I'm not sure if it is worth the effort as Bisq 2 will be M1 compatible and the first iteration of it might be released soon.

I got Bisq 2 and it's not compatible with Apple Silicon.
