### ISSUE TITLE
Select arbitrator in development mode

### ISSUE THREAD

**Issue by ligi** [bisq-network/bisq#619]
I am following the following documentation to setup an bitsquare development environment:

Development Mode section at: https://github.com/bitsquare/bitsquare/blob/master/doc/build.md

I can start the local seed node - the arbitrator + alice + bob like this:

```

$ java -jar seednode/target/SeedNode.jar --bitcoinNetwork=REGTEST --useLocalhost=true --myAddress=localhost:2002 --nodePort=2002 --appName=Bitsquare_seed_node_localhost_2002 

$ java -jar gui/target/shaded.jar --bitcoinNetwork=REGTEST --useLocalhost=true --myAddress=localhost:2222 --nodePort=2222 --appName=Bitsquare-Local-Regtest-Arbitrator  

$ java -jar gui/target/shaded.jar --bitcoinNetwork=REGTEST --useLocalhost=true --myAddress=localhost:3333 --nodePort=3333 --appName=Bitsquare-Local-Regtest-Alice 

$ java -jar gui/target/shaded.jar --bitcoinNetwork=REGTEST --useLocalhost=true --myAddress=localhost:4444 --nodePort=4444 --appName=Bitsquare-Local-Regtest-Bob
```

. But I see no arbitrator in the list for alice and bob - but I would need this to continue. 

![bitsquare_problem](https://cloud.githubusercontent.com/assets/111600/19017032/65cca3d8-882c-11e6-9e95-aa8347cb28e2.png)

**Comment by mrosseel** [comment]
Hi, you need to edit the source code before the key combination works, it's mentioned in the docs

**Comment by ligi** [comment]
Thanks for the fast reply - I missed this wiki-page - closing this issue
