### ISSUE TITLE
Mobile app notifications not working properly

### ISSUE THREAD

**Issue by Android-X13** [bisq-network/bisq#6193]
Mobile notifications aren't working for me:

1. Install Android app

2. Open app > click on `Pair` button > `Send token to myself`

3. In desktop Bisq, go to `ACCOUNT` > `NOTIFICATIONS` and enter the pairing token that was received (there is no "I don't have a webcam" button as stated in the [docs](https://docs.bisq.network/bisq-mobile.html#2-pair-it-with-bisq-desktop)). There is also no button in the desktop app to "pair" or something similar, and I don't get a success message once the pairing completes as stated in the above link (but the pairing is done, see below).

4. Enable all three types of notifications

Now after these steps I keep getting notifications on the mobile app from time to time (presumably offer and price alerts) but I don't know what they are about. All I see is this notification:

![mobile_notification](https://user-images.githubusercontent.com/76814540/167320719-c63733ff-1739-41f7-aa61-4d4c1b9acf80.jpg)

And when tapping on it, the Bisq app opens but still shows me the "Pair" screen:

![mobile_bisq_app](https://user-images.githubusercontent.com/76814540/167320761-d473b1ed-1a60-4987-9422-d25619e223f4.jpg)

Which seems to indicate that I have not paired anything (although I have and I do get notifications, but I don't know their contents...!).

**Comment by devinbileck** [comment]
Thanks for the bug report. I will look into this.

**Comment by myselfeuh** [comment]
Hi!

I have exactly the same behaviour between the Bisq client v1.9.1 installed on a win7-x64 desktop and the Bisq notification app v1.1.0 build18 installed on android10 smartphone.

I hope it can be fixed, I would love to use Bisq mobile notifications !
Thanks :)

**Comment by Conza88** [comment]
I don't have this problem...
But I do have the issue of not getting notifications when my offer was TAKEN.

Logs provided to Leo.
Mediation resulted because I was not notified by android app offer was taken. 
I was getting notifications for mediation started (LOL) and other offers, but not that mine was taken.
Linux Bisq 1.9.1 and android app.

**Comment by stonedbear** [comment]
Have the same problem for a good while now. It is annoying as f... Happy to assist with troubleshooting / testing.

**Comment by stonedbear** [comment]
@devinbileck what is the best way to get this prioritized?

**Comment by devinbileck** [comment]
Hi @stonedbear.
I am in the process of preparing a new release right now. Just taking care of a couple last minute items, and hopefully will be able to publish it by end of the week.

**Comment by stonedbear** [comment]
> 

Gentleman and a Scholar, thank you. If I could be of any assistance - just shout.

**Comment by devinbileck** [comment]
v1.2.3 has just been published to the Google Play Store that should hopefully resolve issues with pairing and notifications. @ripcurlx can you close this ticket. Feel free to reopen this or create a new issue if you still have problems.

**Comment by stonedbear** [comment]
So I installed the latest Android app. I am on 1.9.2 bisq on arch Linux.

1. Open the app
2. Pair
3. No webcam
4. Send pairing code: 
![Screenshot_20220628-225740](https://user-images.githubusercontent.com/5209560/176286823-2a4f5841-5e9e-4848-a65d-d4854e7c3e63.jpg)
6. I put the entire string in bisq -> account -> notifications
7. It gets saved but there is no feedback. No submit / save button in desktop app.
8. Nothing happens in the Android app although the wording is it will confirm success upon pairing.
9. Notification arrive but without any content.
![Screenshot_20220628-230418_Chrome](https://user-images.githubusercontent.com/5209560/176287733-eb4c0399-de14-40fe-b1b1-9c4209863940.jpg)
10. When I click that I am back on the app welcome screen.
![Screenshot_20220628-230559](https://user-images.githubusercontent.com/5209560/176287850-d81e6758-02b2-4ac2-b012-add24dafbb74.jpg)

Am I doing something wrong or is this still broken?

**Comment by myselfeuh** [comment]
Hi !

I followed the exact same steps and the result is similar, except that I didn't get the empty notification.
I tried to setup a price alert, but I don't receive any notification at all.
When I open the Android app, it still shows the pairing process although I already entered the key in the desktop app.

I'm using Bisq 1.2.3 on Android 10 and Bisq 1.9.2 on Windows 7.

**Comment by stonedbear** [comment]
Ok, what eventually worked for me:
1. on desktop app under account -> notifications -> clear notifications
2. on android in app settings -> clear data and cache
3. repeat the pairing process from scratch
4. this time i got the successfully paired notification and i can see notifications screen.

**Comment by devinbileck** [comment]
Yeah the UX within the desktop application is not ideal, and doesn't always recognize when a new token is entered. So requires you to press the clear notifications button before entering a new token. That is on my todo list to refactor how that is implemented.

**Comment by ssj4maiko** [comment]
> Ok, what eventually worked for me:
> 
>     1. on desktop app under account -> notifications -> clear notifications
> 
>     2. on android in app settings -> clear data and cache
> 
>     3. repeat the pairing process from scratch
> 
>     4. this time i got the successfully paired notification and i can see notifications screen.

This worked for me the first time, then when I changed phones, I couldn't get it to work as much as I tried.

After days from me giving up, I went to check again, opened the App (did not reinstall it), sent the code to myself via email, then on the Bisq client, I noticed I didn't had it enabled at all (so pretty much clean), selected no webcam, pasted the content, and it worked 1st try.

So if you are having problems, be sure to disable notifications on the client and wait a few hours or a day, I don't know if the application could be facing some "push notification" congestion or whatever, but could help.

**Comment by stonedbear** [comment]
> > Ok, what eventually worked for me:
> > ```
> > 1. on desktop app under account -> notifications -> clear notifications
> > 
> > 2. on android in app settings -> clear data and cache
> > 
> > 3. repeat the pairing process from scratch
> > 
> > 4. this time i got the successfully paired notification and i can see notifications screen.
> > ```
> 
> This worked for me the first time, then when I changed phones, I couldn't get it to work as much as I tried.
> 
> After days from me giving up, I went to check again, opened the App (did not reinstall it), sent the code to myself via email, then on the Bisq client, I noticed I didn't had it enabled at all (so pretty much clean), selected no webcam, pasted the content, and it worked 1st try.
> 
> So if you are having problems, be sure to disable notifications on the client and wait a few hours or a day, I don't know if the application could be facing some "push notification" congestion or whatever, but could help.

Can confirm this works with the latests android app version 1.3.4. Thanks!

**Comment by ssj4maiko** [comment]
> Can confirm this works with the latests android app version 1.3.4. Thanks!

Yes,, I'm on Android 15, App 1.3.4
It's working fine

Also confirmed something here:
Had to factory reset my phone, and set the application again. Because I had the previous notification there, I just cleared it on the application and didn't set anything.
I then restart Bisq and sest it up again, worked first try, so no need to wait, clear the notifications from Bisq, restart it, try again.

You should get the confirmation after a few seconds
