### ISSUE TITLE
Trade's popup details report wrong time of account signing

### ISSUE THREAD

**Issue by Android-X13** [bisq-network/bisq#6196]
1. In `PORTFOLIO` > `OPEN TRADE` or in `PORTFOLIO` > `HISTORY`, click on a trade's ID to show the popup with the trade's details

2. Hover the mouse over the field "BTC buyer payment details" or "BTC seller payment details"

3. The tooltip that is shown reports wrong time since signing at the end: `(...) / Time since signing: X days`

The time reported is the time that this particular account was created, not signed. In my case for my SEPA account, hovering over "BTC buyer payment details" tells me that my account was signed over 60 days ago (which is my account age), but it was only signed yesterday.

**Comment by ghost** [comment]
@Android-X13  thanks for reporting this.

**Comment by Android-X13** [comment]
I should add that this wrong info also appears in the details when clicking on the trade's `DETAIL DATA` button:

```
BuyersAccountAge: Time since signing: X days
SellersAccountAge: Time since signing: X days
```
