### ISSUE TITLE
The state of "Offers matching my account" switches in BUY/SELL categories is not saved

### ISSUE THREAD

**Issue by Android-X13** [bisq-network/bisq#6199]
1. Go to any tab inside the BUY or SELL categories, e.g. `BUY` > `BITCOIN`

2. Toggle `Offers matching my account` ON or OFF

3. Go to any of the other three tabs (BSQ, XMR, OTHER) in the same category; the `Offers matching my account` switch in each tab is unaffected and remains in its previous selection (as expected)

4. Switch to any other top-level tab (PORTFOLIO, FUNDS, etc)

5. Go back to the `BUY` category; the `Offers matching my account` switch in all tabs of this category has been toggled to match the switch of the tab in step 2.

6. In addition all the switches in `SELL` category have also been toggled to match the switch of the tab in step 2.

Expected behavior should be that each tab remembers its own selection (which is what happens until the user decides to view any other top-level tab).

**Comment by ripcurlx** [comment]
@Android-X13 Thanks for the bug report - I'll look into this issue for the next update.

**Comment by ripcurlx** [comment]
@Android-X13 I looked at the previous behavior and found out that this toggle was meant more like a setting across offer books. Meaning if you set once you only want to see offers matching your accounts it will do so on all other offer books as well.

**Comment by Android-X13** [comment]
Hi @ripcurlx

The toggle's behavior wasn't consistent, when the user stays in BUY/SELL categories it remembers its state for each tab, but when you switch to another category it falls back to the last selection for all tabs. But I think the best scenario would be to have the toggle remember its state for each offer book (for example I usually like to keep the toggle enabled in BTC offer book but disabled in the OTHER offer book).

I tried to work on this with my minimal experience since I created this issue... adding 8 new fields (one for each tab, 4 in BUY and 4 in SELL) in the proto file and adjusting the relevant classes would theoretically implement this. It works for me for as long the application is open; toggle of each offer book keeps its state even when switching to other top-level tabs, and the states are correctly saved upon closing. Upon opening the application the states are correctly read, but somewhere after providing the password they are set to arbitrary boolean values and I don't know why. So I couldn't solve it. Maybe you can (if you are interested to implement this behavior, i.e. having the match toggle state for each offer book saved as persistent preferences).

**Comment by ripcurlx** [comment]
> The toggle's behavior wasn't consistent, when the user stays in BUY/SELL categories

Yes, that is what I changed in https://github.com/bisq-network/bisq/pull/6209. Now it is a universal toggle like it was before changing the Buy/Sell navigation. I was also thinking about adding a data structure adding an unlimited amount of tab configs, but just went with the pragmatic solution so far. Kind of weird that the password screen has influence on the preferences states - I guess something else must cause this behavior.
