### ISSUE TITLE
Support for ETH tokens required

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#620]
Not sure if ETH tokens such as PLU need special handling before being added to the exchange. Do we just assume that, since they're sent external to the program, it's not our problem until someone goofs and sends the wrong tokens?

**Comment by haiqu** [comment]
Relevant link: ERC20 token standard. https://github.com/ethereum/EIPs/issues/20

**Comment by ManfredKarrer** [comment]
Transfer is out of system, so users need to know how to do it. Though I prefer to not add tokens which are not clear how to use as it cause much disputes. So if there is not much request for it I prefer to wait with adding them.

**Comment by haiqu** [comment]
I added PLU only because I believe it will be huge within 3 months. Otherwise I can't see any others that warrant being added yet. If any arbitrator needs help figuring out a PLU transaction I already did the legwork for that.

**Comment by ManfredKarrer** [comment]
Ok. Are you in touch with them so they can request? If not and u want to get it added, please add a request with all info.
I still need to catch up reading all in the forum, remember there was some discussion but have not looked closer to it....

**Comment by haiqu** [comment]
I am in touch with them daily. In fact I may become their representative in Australia, it's that far along.

**Comment by konard** [comment]
Please, add StorJ token support.
