### ISSUE TITLE
Add chart to display revenue

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#6203]
We display currently the sum of all burned BSQ and the reimbursemnet requests.
It would be good to see also the difference of sum of all burned BSQ and the reimbursemnet requests as indicator for the total fees (burned BSQ is sum of burned BSQ from fees + burned BSQ from BM from BTC fees + burned BSQ from BM from arbitration cases).
As the timing is not synchronized that chart might be not very accurate in the short term (month) but at least on longer time scale (3 months, 6 months, year) it should produce a realistic picture of total revenue. Maybe adding those additional time scale selectors might be useful as well.

<img width="1352" alt="Screenshot 2022-05-15 at 14 43 45" src="https://user-images.githubusercontent.com/54558767/168473522-ba8c16a9-db49-46ab-9fd6-ab49d6e0103f.png">

**Comment by chimp1984** [comment]
I will work on that.

**Comment by chimp1984** [comment]
The display makes most sense for the Year and 6 months periods.
The reimbursement requests are once a DAO voting period (roughly 1 month) and the proof of burn by the BM is not in sync with those events but can be several weeks delayed. This situation renders the chart for < 6 months rather confusing.
I think it still adds some value to get a view about the long term revenue.

EDIT: This got renamed later to "Diff total burned-reimbursement"

<img width="1618" alt="Screenshot 2022-05-15 at 17 16 19" src="https://user-images.githubusercontent.com/54558767/168480224-a294d2b7-415b-4500-8720-1669be1ae408.png">

<img width="1629" alt="Screenshot 2022-05-15 at 17 16 11" src="https://user-images.githubusercontent.com/54558767/168480223-1448ebe5-0577-44e8-b7dc-9e873b76e668.png">
 


<img width="1619" alt="Screenshot 2022-05-15 at 17 16 04" src="https://user-images.githubusercontent.com/54558767/168480220-00b93735-bcf8-4489-ad0b-076b149d4e9b.png">

**Comment by chimp1984** [comment]
I added other series for the burned BSQ from BTC fees and from arbitration cases. This data is only available since Nov 2021. But that should be a correct value for the total trade fees (revenue).
An alternative view on it is the difference of Total burned BSQ and the reimbursement requests. In early days we did not use reimbursement requests but comp. requests, so in that period its not correct. Also the delay of burning and reimbursements create not very usable chart data but for longer periods is levels out and it can be used as control view to the total trade fees for past months.
<img width="1334" alt="Screenshot 2022-05-15 at 23 31 58" src="https://user-images.githubusercontent.com/54558767/168494960-6784e197-1b97-47f5-8a47-3eea99f33547.png">
<img width="1337" alt="Screenshot 2022-05-15 at 23 32 27" src="https://user-images.githubusercontent.com/54558767/168494963-497579b2-41cb-499b-a657-d9feec8c85f7.png">
<img width="1336" alt="Screenshot 2022-05-15 at 23 33 10" src="https://user-images.githubusercontent.com/54558767/168494964-ceb5ec36-39fc-49e6-9379-772f4c445117.png">
<img width="1346" alt="Screenshot 2022-05-15 at 23 34 52" src="https://user-images.githubusercontent.com/54558767/168494966-6ffeda9b-63c6-4311-9427-4148a9be15a1.png">

**Comment by pazza83** [comment]
Looks like a good idea. 

Will total BTC fees be shown in BTC and BSQ? If so how is this being calculated?

I made a proposal recently to [Show changes in BSQ Supply over time in app](https://github.com/bisq-network/bisq/issues/6100)

I understand @xyzmaker123 is working on this currently.

Also maybe the word request is incorrect. Maybe more suitable would be:

- Compensation issued
- Reimbursements issued

The ones that escape the reports are the sum of the 2 BSQ fees paid each cycle for any request to the DAO and the subsequent vote fees. It is only ever a small amount but would be nice for the figures to be able to add up to total issuance.

**Comment by chimp1984** [comment]
> Will total BTC fees be shown in BTC and BSQ? If so how is this being calculated?
In BSQ. It is the burned BSQ which comes from BTC trade fees using the opReturn tag to distinguish it from the burned BSQ comeing from Arbitration. So its the burned BSQ after the MB has traded the BTC from trade fees for BSQ.

> https://github.com/bisq-network/bisq/issues/6100
This is already implemented (Total BSQ supply).
