### ISSUE TITLE
ERROR: Deposit transaction ID N/A

### ISSUE THREAD

**Issue by dgcfusII** [bisq-network/bisq#6205]
### Description

while exiting my bisq client a buyer took one of my sell offer, this caused an error in the multisig deposit transaction. 
The buyer was able to send me the payment but all my button are grayed out and i cannot release the BTC using my client. Already tried resyncing SPV, restoring a backup and unistalling/reinstalling.
We already went trough mediation, the mediator proposed a solution, but i didn't get it in my client.

#### Version

1.9.1

### Steps to reproduce

Exit bisq when an offer is being accepted.

### Expected behaviour

not sure

### Actual behaviour

bisq thinks i sent btc out of my wallet instead of sending it to a multisig wallet for the trade.

### Screenshots

![1](https://user-images.githubusercontent.com/105599902/168482994-2fedbce5-3f73-46d4-8c28-82c98ff07d68.png)
![2](https://user-images.githubusercontent.com/105599902/168483002-06cc58de-ed46-454b-9591-4f9fa609e168.png)
![3](https://user-images.githubusercontent.com/105599902/168483008-e2a41b3a-7c80-4453-82d7-b8a50e6637ad.png)

#### Additional info

multisig deposit: 59f5f0702d4ddda5239c4c0475abcd0a39a12df51ad7b0af3984fe2cdf74694b
logs may contain sensible data, i can share it on matrix
@dgcfus:matrix.org

**Comment by ghost** [comment]
Thanks for writing this up.  @w0000000t  sent me the logs and it is on my todo list to put a guard against exiting the app while a trade is being started.  (I'll reference this issue when submitting the PR).

---

In regards to your immediate situation, as you did not get the mediation proposal, the mediator will have to perform a "manual payout".  That involves communicating with both buyer and seller using a Bisq tool for both to sign the proposed payout.  Please DM your mediator on Matrix (and if in communication with your peer, DM/trader chat them too) referencing this issue.

**Comment by Drazen-V** [comment]
@dgcfusII @jmacxx @w0000000t Is there any way to remove the trade from Portfolio > Open Trades?
Since this page is blank, as shown in the screenshot above, one cannot press the Trade Completed button. Is there any hack for that?

**Comment by ghost** [comment]
@Drazen-V to remove it, all open trades can be nuked by deleting|renaming a file.  
This is a dangerous operation so first **ensure that you have no other active trades in Portfolio -> Open Trades**.

- Close Bisq.
- Navigate to your [data directory](https://bisq.wiki/Data_directory#Default_locations), sub folder `btc_mainnet/db`.
- Find the file `PendingTrades` and rename it to `PendingTrades.old` or similar, so Bisq will no longer recognize it.
- Start Bisq.
