### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by dchmelik** [bisq-network/bisq#6208]
### Description

* Where:
Build file '/home/d/math/src/network/cryptocurrency/bisq/build.gradle' line: 238

* What went wrong:
A problem occurred evaluating root project 'bisq'.
\> java.lang.UnsupportedClassVersionError: org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

#### Version

20220516-6fa87ae

### Steps to reproduce

./gradlew build

### Expected behaviour

build (with other options in addition to gradlew)

### Actual behaviour

FAILURE: Build failed with an exception.

#### Device or machine

Slackware64 GNU/Linux 15.1-current w/javac 11.0.15

**Comment by ripcurlx** [comment]
The error actually sounds as if you are trying to build the project with Java 8 (version 52.0). Are you sure that you have configured Java 11 correctly in the project repository?

**Comment by dchmelik** [comment]
I'm sure I haven't because I have java 11 configured system-wide.  Something else I built required java 8 and set environment variables without informing me, so I removed that and no longer have the error.
