### ISSUE TITLE
Cannot open wallet because of an exception:

### ISSUE THREAD

**Issue by pietvantzeetje** [bisq-network/bisq#621]
Cannot open wallet because of an exception:
org.bitcoinj.store.BlockStoreException: org.bitcoinj.store.BlockStoreException: Header bytes do not equal SPVB

**Comment by ManfredKarrer** [comment]
Please do a backup and then try to delete the Bitsquare.spvchain file inside the application data directory (Account/Backup/open app data dir button). If it does not fix the issue contact me by email so I can instruct you further.

**Comment by ManfredKarrer** [comment]
If u cannot resolve please re-open.
