### ISSUE TITLE
git-lfs says it's not installed (docs/build.md missing step)

### ISSUE THREAD

**Issue by dchmelik** [bisq-network/bisq#6210]
### Description
```
d@cosmos:~/math/src/network/cryptocurrency/bisq$ ls -l /var/log/packages/git-lfs-3.1.4-x86_64-1_SBo 
-rw-r--r-- 1 root root 3156 May 17 02:14 /var/log/packages/git-lfs-3.1.4-x86_64-1_SBo
d@cosmos:~/math/src/network/cryptocurrency/bisq$ git lfs version
git-lfs/2.13.2 (GitHub; linux amd64; go 1.14.13; git fc664697)
d@cosmos:~/math/src/network/cryptocurrency/bisq$ git lfs pull
Skipping object checkout, Git LFS is not installed.
```
#### Version

20220516-6fa87ae

### Steps to reproduce

git lfs version && git lfs pull

### Expected behaviour

Detect git-lfs-3.1.4-x86_64-1_SBo.

### Actual behaviour

Detects wrong version then doesn't detect any version.

#### Device or machine

Slackware64 15.1-current

**Comment by ripcurlx** [comment]
@dchmelik I think I don't understand exactly what we can/should change with the git lfs installation process.

based on https://github.com/bisq-network/bisq/blob/master/docs/build.md#building-bisq it is a requirement that git lfs is installed properly.

Or do you mean something else?

**Comment by dchmelik** [comment]
> I think I don't understand exactly what we can/should change with the git lfs installation process.

Neither do I, but it's not working (as shown.)  My OS has a newer version but seems it's not being checked for.
```
d@0.cosmos:/var/log/packages$ grep usr/bin/git /var/log/packages/git-lfs-3.1.4-x86_64-1_SBo 
usr/bin/git-lfs
d@cosmos:~$ which git-lfs
/usr/bin/git-lfs
```

**Comment by dchmelik** [comment]
d@0.cosmos:~/math/src/network/cryptocurrency/bisq$ which git-lfs
/usr/local/bin/git-lfs

**Comment by ripcurlx** [comment]
I just gave Google a shot: https://andresa.dev/en/solved-git-lfs-error-skipping-object-checkout-git-lfs-is-not-installed/
Could it be that you missed this step?

**Comment by dchmelik** [comment]
> I just gave Google a shot: https://andresa.dev/en/solved-git-lfs-error-skipping-object-checkout-git-lfs-is-not-installed/
> Could it be that you missed this step?

I showed you my git-lfs package.

**Comment by dchmelik** [comment]
> I just gave Google a shot: https://andresa.dev/en/solved-git-lfs-error-skipping-object-checkout-git-lfs-is-not-installed/ Could it be that you missed this step?

Yes: that should be step three in docs/build.md (and move current step three to step four, etc.; ) if someone's OS already has a package available they won't necessarily know installing git-lfs package doesn't installing its LFS.)

(I had remnant an older version installed but 3.1.4 is installed correctly and 'gradlew build' is running now.)

**Comment by cd2357** [comment]
Git LFS is being removed, see #6360
