### ISSUE TITLE
Wallet Date input field marches across the screen

### ISSUE THREAD

**Issue by imyjimmy** [bisq-network/bisq#6216]
### Description

The width of date input fields for Wallet Date keeps increasing. The calendar icon marches across the app and off the edge.

#### Version

v1.9.1

### Steps to reproduce

Go to Account > Wallet Seed

### Expected behaviour

Width of wallet date inputs should be constant

### Actual behaviour

The Date Input fields keep increasing in width until the it takes up over 100% of the width of the app itself.

### Screenshots

When I first go to the Wallet Seed screen:
<img width="1403" alt="Screen Shot 2022-05-20 at 3 39 22 PM" src="https://user-images.githubusercontent.com/489440/169600719-bbe24a4a-60d4-450a-a07d-0c8a06dcab29.png">

Several seconds later:
<img width="1403" alt="Screen Shot 2022-05-20 at 3 39 24 PM" src="https://user-images.githubusercontent.com/489440/169600721-7212d337-7bbc-43a8-a9b9-27dd7e90bb84.png">

It doesn't stop:
<img width="1403" alt="Screen Shot 2022-05-20 at 3 39 27 PM" src="https://user-images.githubusercontent.com/489440/169600723-3339035f-2e97-4451-a2d7-9ba4c2a4b66b.png">
<img width="1403" alt="Screen Shot 2022-05-20 at 3 39 30 PM" src="https://user-images.githubusercontent.com/489440/169600726-6cbf089c-a94a-434b-afed-618e5ff6a495.png">
<img width="1403" alt="Screen Shot 2022-05-20 at 3 39 39 PM" src="https://user-images.githubusercontent.com/489440/169600728-2fd94522-9773-41fb-9caf-06844e8d682d.png">

#### Device or machine

MacOS 12.3.1

**Comment by fahimahmedx** [comment]
Has this been fixed or is it still an issue? Does not occur on my side in Windows.

**Comment by redpola** [comment]
Reproduced today on a first time install of version 1.9.5 on MacOS 12.5.1 (21G83).

**Comment by redpola** [comment]
The impact of this bug is that those fields become unusable.

This problem persists for the lifetime of the app, so the workaround is to close the app and reopen it and be quick.

**Comment by Android-X13** [comment]
I can't reproduce this.. maybe it's a MacOS only issue.

There's also another date picker in the following view: open Bisq > click on FORGOT PASSWORD? button. Does it also occur in that window?

**Comment by ghost** [comment]
@Android-X13 seems you [identified a fix](https://github.com/sshahine/JFoenix/issues/1245#issuecomment-1236212511) for this issue, will you be making a PR to address the problem in Bisq?

**Comment by Android-X13** [comment]
@jmacxx Unfortunately I don't have a Mac and I can't reproduce the issue. I could submit a PR but it would be a blind fix... I won't be able to test it.

**Comment by ghost** [comment]
@Android-X13 Please submit the fix, there are Mac users | devs who can validate it.

**Comment by redpola** [comment]
Reproduced today on 1.9.9/MacOS.

This is a massive glaring problem and faces the user the first time they open the account page (for me my app opened at this page).

Extremely confusing and worrying for new users, that their new app in an ecosystem that they want to try to trust is acting screwy from the get-go.

**Comment by ghost** [comment]
It would be helpful if someone with a Mac can try out the fix #6602.

**Comment by redpola** [comment]
Is there an easy way for me to grab a build of this? I'm happy to see if that change fixes it.

**Comment by redpola** [comment]
Still a bug on Mac M1/ 1.9.14

**Comment by cmunna0052** [comment]
Downloaded Bisq 1.9.21 for the first time and was immediately greeted by this phenomenon.  Eventually found my way here, so I thought I should confirm that the bug still exists.  M1 Mac with macOS 13.0

**Comment by redpola** [comment]
How was this closed and not subsequently reopened?
