### ISSUE TITLE
ETHC listing in Spreads view

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#622]
Since ETC is now the standard name for Ethereum Classic, I'm surprised to see this listing in v0.4.9.6:

![ethc](https://cloud.githubusercontent.com/assets/13131219/19089584/44a43844-8abe-11e6-943b-07e095e7667f.png)

Either this person has had a listing running for a long time or they're using a very old version of Bitsquare!

**Comment by ManfredKarrer** [comment]
ETHC is already removed, so yes that seems to be an old dangling offer.... the user will discover some day that noboday takes it and to get out his reserved funds remove it (hopefully)...
