### ISSUE TITLE
Error: The system tray is not supported on the current platform. 

### ISSUE THREAD

**Issue by alexorlandi** [bisq-network/bisq#6220]
[bisq.log](https://github.com/bisq-network/bisq/files/8748540/bisq.log)
[bisq.log](https://github.com/bisq-network/bisq/files/8748541/bisq.log)

### Description

Error: The system tray is not supported on the current platform.

#### Version

1.2.7

### Screenshots

![Captura de tela de 2022-05-21 20-34-12](https://user-images.githubusercontent.com/18470609/169672661-7ceff354-b021-4f25-b1c3-a496f39dabc5.png)

#### Device or machine

Linux Ubuntu 22.04 - 64bits

**Comment by ghost** [comment]
Bisq v1.2.7 is over 2 years old and not supported any more.  Please upgrade to the latest version: https://github.com/bisq-network/bisq/releases
