### ISSUE TITLE
Cannot connect bisq to my full node

### ISSUE THREAD

**Issue by BTC1M** [bisq-network/bisq#6223]
Hi folks, 

I'm trying to connect Bisq to my raspiblitz full node over tor, but BISQ no longer connects to Bitcoin Network :

`Connecting to bitcoin network - v1.9.1 / Synchronizing DAO - Bitcoin network peers: 0 / Bisq network peers: 15`

I've already tried to close and reopen Bisq. Sometimes, i get the following error message : 

`Cannot invoke "java.util.List.isEmpty()" because "peers" is null`

Bisq is succesfully connecting to the Bitcoin network when i use provided bitcoin core nodes.

I have the same problem when trying to connect my node with other apps or wallets.
I think the problem comes from Tor but i'm not sure, because it was working fine before the recent Tor auto-update.
The Tor browser is working but my apps can't connect to Tor.

Bisq version : v1.9.1
Operating system : Windows 10

---------------
EDIT :
The problem comes from Tor, i waited 2 hours and now strangely it is working. I don't know why as i didn't do anything to solve the issue. While connected to my node, this window appeared : 
![error](https://user-images.githubusercontent.com/52107488/170062831-9ee7516e-2d74-4d57-b0e3-e62fa07c9afc.png)

**Comment by ghost** [comment]
There have been several other reports of issues connecting to a raspiblitz or other types of 3rd party node products over Tor.  The only solution I've heard of is that restarting the bitcoin node helps (why, I don't know).  The Bisq popup you got about blocking incoming connections is a result of Bisq testing the connection to its own onion address through Tor, and failing.  There have been a couple of reports that this can also happen to be a false alarm - In the next release we'll be waiting for three consecutive failures before popping up that error.  Tor can be flaky.  

Another suggestion could be if your bitcoin node is on your LAN, then connect to it over TCP/IP.

**Comment by bitcoingamer21** [comment]
I know the problem of most self hosted nodes running today, check out this guide:

[https://bisq.wiki/Connecting_to_your_own_Bitcoin_node](https://bisq.wiki/Connecting_to_your_own_Bitcoin_node)

you have to add this to your bitcoin.conf:

peerbloomfilters=1

I have changed it in my self hosted node and its connecting without any lags :). I think the issue can be closed now.

**Comment by ripcurlx** [comment]
Closing based on https://github.com/bisq-network/bisq/issues/6223#issuecomment-1180644310
