### ISSUE TITLE
Do not prompt user to add password if already done

### ISSUE THREAD

**Issue by jonathancross** [bisq-network/bisq#623]
If the user adds a new Altcoin account, they will see a dialog suggesting they use a password to protect their wallet, even if a password is already setup.  This is unnecessary and suggests to the user that the software is not aware of its own state.

Instead, this message should be omitted if not needed.

The message can be found here:
- https://github.com/bitsquare/bitsquare/blob/master/gui/src/main/java/io/bitsquare/gui/main/MainViewModel.java#L621

**Comment by ManfredKarrer** [comment]
Thanks, will fix that for the next release!

**Comment by ManfredKarrer** [comment]
Its in: https://github.com/bitsquare/bitsquare/commit/a7564817c68b5ec992b1d18df2de4e5c648d5c8a

**Comment by jonathancross** [comment]
Cheers!
