### ISSUE TITLE
error during offer acceptance

### ISSUE THREAD

**Issue by ulisses1979** [bisq-network/bisq#6245]
### Description

error during offer acceptance

#### Version

1.9.1

#### Additional info

log attached
[bisq.log](https://github.com/bisq-network/bisq/files/8891882/bisq.log)

**Comment by ghost** [comment]
The other side of the trade rejected your price.  This could be due to a price server being out of sync.  What was the currency being traded?

    Taker's trade price is too far away from our calculated price based on the market price.
    takersPrice=1251798326
    makersPrice=1313273409

**Comment by ulisses1979** [comment]
Hello, you are probably right... the currency pair was BRL x BTC and it took some time between the bisq screens.. so a synchrony problem may have arisen
Anyway, the trade was completed in other transaction and the rates were refunded...
thank you
