### ISSUE TITLE
Offer Placement error: CreateMakerFeeTx

### ISSUE THREAD

**Issue by enzoomb** [bisq-network/bisq#6246]
### Description

An error in selling offer

#### Version

V1.9.1

### Steps to reproduce

[bisq.log](https://github.com/bisq-network/bisq/files/8894613/bisq.log)

**Comment by ghost** [comment]
The error says you do not have enough funds in your wallet.

Please verify the UTXOs in your wallet balance using: Funds -> Send Funds (list of UTXO).  Verify each one using an explorer such as mempool.space to check that your wallet's view of reality matches what is on the blockchain.

It is possible your wallet may need to be resynced: https://bisq.wiki/Troubleshooting_wallet_issues
