### ISSUE TITLE
Bisq does not start

### ISSUE THREAD

**Issue by Android-X13** [bisq-network/bisq#6251]
Since yesterday I've been having issues during startup of Bisq. It's the known "3/4 connection problem" where it gets stuck at the initial screen saying `Synced with Bitcoin Mainnet (via Tor) at block X`.

Initially I followed [this ](https://bisq.wiki/Troubleshooting_network_issues) (deleting all files except `hiddenservice` in `btc_mainnet/tor` folder) which only worked for a couple of times. Afterwards it couldn't load even with that workaround, so my next step was to try and follow [this](https://bisq.wiki/Last_resort_restore), however I can't even get past the first step; after renaming the data directory to Bisq.old and executing Bisq again to make it recreate a new datadir, the application still gets stuck at the same screen.

The weird thing is that Bisq **doesn't start even after a fresh installation at a different computer** (on the same network).

Internet connectivity is fine (I rebooted the connection a couple of times just in case), and Tor connectivity in general seems to be also fine (I can use Tor browser for example).

Windows 10

Attached [bisq.log](https://github.com/bisq-network/bisq/files/8940200/bisq.log) of the brand new Bisq install.

**Comment by ghost** [comment]
From https://status.torproject.org/ : `We are experiencing a network-wide DDoS attempt impacting the performance of the Tor network, which includes both onion services and non-onion services traffic. We are currently investigating potential mitigations.`

The Bisq team is working to upgrade to the latest version of Tor.  Keep an eye on https://github.com/bisq-network/bisq/releases for an update.

**Comment by ripcurlx** [comment]
@Android-X13 Please give https://github.com/bisq-network/bisq/releases/tag/v1.9.2 a shot and let us know if you still experience problems.
