### ISSUE TITLE
Warning We did not receive a filter object from the seed nodes. This is a not expected situation. Please inform the Bisq developers.Warning We did not receive a filter object from the seed nodes. This is a not expected situation. Please inform the Bisq developers.

### ISSUE THREAD

**Issue by hoodulum** [bisq-network/bisq#6255]
how do i fix this issue?

**Comment by hoodulum** [comment]
I downloaded and installed the newest version and still have this issue.

**Comment by ghost** [comment]
From https://status.torproject.org/ : `We are experiencing a network-wide DDoS attempt impacting the performance of the Tor network, which includes both onion services and non-onion services traffic. We are currently investigating potential mitigations.`

The Bisq team is working to upgrade to the latest version of Tor.  Keep an eye on https://github.com/bisq-network/bisq/releases for an update.

**Comment by hoodulum** [comment]
Ok I got the newest new update now. And I'm getting a new error. ![image](https://user-images.githubusercontent.com/78965780/176474710-af885d42-d2b5-43e1-b61a-5e5f4c35e008.jpeg)

**Comment by ghost** [comment]
Tor was upgraded last year from v2 to v3, which requires a completely new onion address. Its possible that you have an old v2 address which will need to be upgraded, see here for instructions: https://bisq.wiki/Changing_your_onion_address

This was the solution for a user with the error "Invalid key type".  https://github.com/bisq-network/bisq/issues/6268

**Comment by chocksmith** [comment]
I have just installed the latest version on a pristine new MacOS and got the same error.

I am running on MacOS Version 13.1 (22C65).
I had to run the following command to run Bisq:
xattr -d com.apple.quarantine /Applications/Bisq.app

<img width="1199" alt="Screenshot 2023-01-02 at 16 21 45" src="https://user-images.githubusercontent.com/999451/210271482-6d55972c-982c-467b-bcd9-020a0295adae.png">

**Comment by MwithM** [comment]
Hi, at settings - Network info, remove Tor files and resync.
