### ISSUE TITLE
Error when confirming received payment - An error occurred at task: SellerSendPayoutTxPublishedMessage Exception message: Not able to find peers witness, unable to sign for trade

### ISSUE THREAD

**Issue by zdick** [bisq-network/bisq#6256]

**Comment by caldwyn** [comment]
Upgraded to v1.9.2 - still same.
I received payment, but I can not confirm it in BISQ.

**Comment by caldwyn** [comment]
Resolved - smart transaction was finished, just BISQ did not recognize it. Buyer has his BTC and I have my security deposit. I moved transaction in BISQ to Failed.
