### ISSUE TITLE
Notifications to iPhone app - error Input length not multiple of 16 bytes

### ISSUE THREAD

**Issue by zdick** [bisq-network/bisq#6257]
### Description
I have successfuly paired iPhone app (confirmed by notification), but I'm not getting any other notifications (trade, offer, price). I'm using Czech laguage version of BISQ, but tried also English version with BISQ restart. Also tried repairing, repairing with app delete and reinstall, pairing with another iPhone.

#### Version
BISQ 1.9.1, 1.9.2

#### Device or machine
Windows 10 64bit Czech localization

#### Log report
čvn-22 17:02:16.568 [JavaFX Application Thread] ERROR b.c.n.a.p.PriceAlert: Vaše upozornění na cenu bylo aktivováno. Aktuální americký dolar cena je 20688.48 BTC/USD 
čvn-22 17:02:16.568 [JavaFX Application Thread] INFO  b.c.n.MobileNotificationService: Send message: 'Vaše upozornění na cenu bylo aktivováno. Aktuální americký dolar cena je 20688.48 BTC/USD' 
čvn-22 17:02:16.569 [JavaFX Application Thread] INFO  b.c.n.MobileNotificationService: sendMessage message=MobileMessage(sentDate=1655910136568, txId=, title=Upozornění na cenu pro americký dolar, message=Vaše upozornění na cenu bylo aktivováno. Aktuální americký dolar cena je 20688.48 BTC/USD, mobileMessageType=PRICE, type=PRICE, actionRequired=, version=1) 
čvn-22 17:02:16.569 [JavaFX Application Thread] INFO  b.c.n.MobileNotificationService: json {"sentDate":1655910136568,"txId":"","title":"Upozornění na cenu pro americký dolar","message":"Vaše upozornění na cenu bylo aktivováno. Aktuální americký dolar cena je 20688.48 BTC/USD","type":"PRICE","actionRequired":"","version":1} 
čvn-22 17:02:16.569 [JavaFX Application Thread] ERROR b.c.n.a.p.PriceAlert: java.lang.Exception: [encrypt] Input length not multiple of 16 bytes

**Comment by devinbileck** [comment]
Thanks for the bug report. I will put this on my todo list.
@ripcurlx please assign this to me.
