### ISSUE TITLE
possibly missing import com.google.code.findbugs

### ISSUE THREAD

**Issue by sgeisler** [bisq-network/bisq#626]
When running tests in a freshly cloned project with fully initialized maven dependencies compilation terminates because `javax.annotation.Nullable` can't be found. Adding `com.google.code.findbugs` to the dependencies fixes the problem.

**Comment by ManfredKarrer** [comment]
In the IntelliJ IDE javax.annotation.Nullable is supported by default so I never got that issue. Thanks for the PR.
