### ISSUE TITLE
error

### ISSUE THREAD

**Issue by oscarolivaresme** [bisq-network/bisq#6261]
### Description
Error
An error occurred at task: SignMediatedPayoutTx
Exception message: myMultiSigPubKey from AddressEntry must match the one from the trade data. trade id =QHFWDS39-31be6cde-cbdd-4acc-b7ab-9ddf689cce12-184

#### Version
v1.8.4

### Expected behaviour
I have trade QHFWDS39. >> I'm the buyer. >> I can't completed the payment (bisq bug). >> I opened a case. >> Support agent: "I have checked the trade and it is fine to make payment." >> I did the payment. >> mediator make a proposal for the trade to be completed. = Seller & Buyer both agree. Problem: Exchange not completed on time (until Jun 22, 2022 12:24:32). Trade is closed and I can't accept mediator proposal. 

### Screenshots
![image](https://user-images.githubusercontent.com/86331475/175342365-7b16c0fb-586f-4b8a-adb1-a1334e145b70.png)

#### Device or machine

PC, Windows

#### Additional info
File error attached

[bisq error.txt](https://github.com/bisq-network/bisq/files/8968853/bisq.error.txt)

**Comment by ghost** [comment]
@oscarolivaresme thanks for the bug report.  I am investigating the technical side and will DM you a request for older logs showing the trade initiation part.  

I think that @pazza83 will be able to do a [manual payout](https://bisq.wiki/Manual_payout) to release the funds.

**Comment by ghost** [comment]
### Technical investigation


Mostly between Jun 27 and July 4, there are multiple errors about **not being able to write database files at shutdown**.  Database files affected include `AddressEntryList`, `PendingTrades`, `MediationDisputeList`, `MailboxMessageList`, `PreferencesPayload`, `BallotList`, `UserPayload`.  The inability to write those files is what caused (a) the initial error (AddressEntry must match the one from the trade data), and (b) the pending trade to be lost on July 3rd.

The earliest such error is April 11, but most of them happened after Jun 19.  I wonder if a lack of disk space could cause it?  The error looks quite random; should certainly not happen at all, and the result being that Bisq will be very unstable.

The user could look into whether adequate free disk space exists and/or closing other running applications (those are just ideas).  On Bisq's side, we could change the app to be more strict when this type of error happens, and display a huge warning to the user that their database has probably been corrupted.  (Since it happens at shutdown, a semaphore would have to be issued for picking up next time the app starts).  @ripcurlx and @chimp1984 thoughts?

<details>
<summary>Log - click to expand</summary>

    jul.-03 21:01:40.943 [JavaFX Application Thread] INFO  b.n.p.n.NetworkNode: Shutdown completed with all connections closed
    jul.-03 21:01:40.963 [JavaFX Application Thread] INFO  b.n.p.n.TorNetworkNode: Tor shutdown completed
    jul.-03 21:01:40.965 [JavaFX Application Thread] INFO  b.c.a.BisqExecutable: P2PService shutdown completed
    jul.-03 21:01:40.966 [JavaFX Application Thread] INFO  b.c.a.BisqExecutable: PersistenceManager flushAllDataToDiskAtShutdown started
    jul.-03 21:01:40.969 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Start flushAllDataToDisk
    jul.-03 21:01:41.242 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Serializing MyVoteList took 258 msec
    jul.-03 21:01:41.409 [Write-FailedTrades_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized FailedTrades completed in 437 msec
    jul.-03 21:01:41.811 [Write-MyVoteList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized MyVoteList completed in 568 msec
    jul.-03 21:01:41.813 [Write-RefundDisputeList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized RefundDisputeList completed in 568 msec
    jul.-03 21:01:41.814 [Write-PreferencesPayload_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized PreferencesPayload completed in 570 msec
    jul.-03 21:01:42.072 [Write-TradeStatistics3Store_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized TradeStatistics3Store completed in 652 msec
    jul.-03 21:01:42.452 [Write-PendingTrades_to-disk] ERROR b.c.p.PersistenceManager: Error at saveToFile, storageFile=PendingTrades java.io.IOException: Failed to rename C:\Users\xxxxxx\AppData\Roaming\Bisq\btc_mainnet\db\temp_PendingTrades480532399461816265.tmp to C:\Users\xxxxxx\AppData\Roaming\Bisq\btc_mainnet\db\PendingTrades
	    at bisq.common.file.FileUtil.renameFile(FileUtil.java:219)
	    at bisq.common.persistence.PersistenceManager.writeToDisk(PersistenceManager.java:483)
	    at bisq.common.persistence.PersistenceManager.lambda$persistNow$9(PersistenceManager.java:432)
	    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	    at java.base/java.lang.Thread.run(Unknown Source)

    jul.-03 21:01:42.453 [Write-PendingTrades_to-disk] WARN  b.c.p.PersistenceManager: Temp file still exists after failed save. We will delete it now. storageFile=PendingTrades
    jul.-03 21:01:42.565 [Write-PendingTrades_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized PendingTrades completed in 1142 msec
    jul.-03 21:01:42.577 [Write-OpenOffers_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized OpenOffers completed in 1242 msec
    jul.-03 21:01:42.577 [Write-MailboxMessageList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized MailboxMessageList completed in 1593 msec
    jul.-03 21:01:42.577 [Write-SequenceNumberMap_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized SequenceNumberMap completed in 1063 msec
    jul.-03 21:01:42.577 [Write-MyBlindVoteList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized MyBlindVoteList completed in 1156 msec
    jul.-03 21:01:42.579 [Write-MyProofOfBurnList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized MyProofOfBurnList completed in 1246 msec
    jul.-03 21:01:42.580 [Write-UserPayload_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized UserPayload completed in 1062 msec
    jul.-03 21:01:42.580 [Write-DisputeList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized DisputeList completed in 1063 msec
    jul.-03 21:01:42.834 [Write-MediationDisputeList_to-disk] ERROR b.c.p.PersistenceManager: Error at saveToFile, storageFile=MediationDisputeList java.io.IOException: Failed to rename C:\Users\xxxxxx\AppData\Roaming\Bisq\btc_mainnet\db\temp_MediationDisputeList11385831694391509707.tmp to C:\Users\xxxxxx\AppData\Roaming\Bisq\btc_mainnet\db\MediationDisputeList
	    at bisq.common.file.FileUtil.renameFile(FileUtil.java:219)
	    at bisq.common.persistence.PersistenceManager.writeToDisk(PersistenceManager.java:483)
	    at bisq.common.persistence.PersistenceManager.lambda$persistNow$9(PersistenceManager.java:432)
	    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	    at java.base/java.lang.Thread.run(Unknown Source)

    jul.-03 21:01:42.835 [Write-MediationDisputeList_to-disk] WARN  b.c.p.PersistenceManager: Temp file still exists after failed save. We will delete it now. storageFile=MediationDisputeList
    jul.-03 21:01:42.836 [Write-MediationDisputeList_to-disk] ERROR b.c.p.PersistenceManager: Cannot delete temp file.
    jul.-03 21:01:42.836 [Write-MediationDisputeList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized MediationDisputeList completed in 1323 msec
    jul.-03 21:01:42.838 [Write-MyReputationList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized MyReputationList completed in 1326 msec
    jul.-03 21:01:42.839 [Write-ClosedTrades_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized ClosedTrades completed in 1321 msec
    jul.-03 21:01:42.839 [Write-BsqSwapTrades_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized BsqSwapTrades completed in 1326 msec
    jul.-03 21:01:42.840 [Write-MyProposalList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized MyProposalList completed in 1430 msec
    jul.-03 21:01:42.841 [Write-UnconfirmedBsqChangeOutputList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized UnconfirmedBsqChangeOutputList completed in 1324 msec
    jul.-03 21:01:42.842 [Write-AddressEntryList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized AddressEntryList completed in 1330 msec
    jul.-03 21:01:42.842 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: flushAllDataToDisk completed
    jul.-03 21:01:42.843 [JavaFX Application Thread] INFO  b.c.a.BisqExecutable: Graceful shutdown completed. Exiting now.




</details>

**Comment by chimp1984** [comment]
There are 2 diff. cases where that IOException is thrown. Would be good to change logs to make debugging easier.
I am not much familiar with Window file system issues (logs is from a Windows user). Do you have other logs, ordo you know which OS the other used? Seems to me a Windows issue...

```
   public static void renameFile(File oldFile, File newFile) throws IOException {
        if (Utilities.isWindows()) {
            // Work around an issue on Windows whereby you can't rename over existing files.
            final File canonical = newFile.getCanonicalFile();
            if (canonical.exists() && !canonical.delete()) {
                throw new IOException("Failed to delete canonical file for replacement with save");
            }
            if (!oldFile.renameTo(canonical)) {
                throw new IOException("Failed to rename " + oldFile + " to " + canonical);
            }
        } else if (!oldFile.renameTo(newFile)) {
            throw new IOException("Failed to rename " + oldFile + " to " + newFile);
        }
    }
```

**Comment by ghost** [comment]
@chimp1984  I have not seen this error reported anywhere else, but a grep of all my log files found it once (Linux BTW).
Seems it can easily go unnoticed.

<details>

<summary>Log file</summary>

    Mar-08 13:24:38.303 [JavaFX Application Thread] INFO  b.n.p.n.NetworkNode: Shutdown completed with all connections closed 
    Mar-08 13:24:38.310 [JavaFX Application Thread] INFO  b.n.p.n.TorNetworkNode: Tor shutdown completed 
    Mar-08 13:24:38.311 [JavaFX Application Thread] INFO  b.c.a.BisqExecutable: P2PService shutdown completed 
    Mar-08 13:24:38.312 [JavaFX Application Thread] INFO  b.c.a.BisqExecutable: PersistenceManager flushAllDataToDiskAtShutdown started 
    Mar-08 13:24:38.312 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Start flushAllDataToDisk 
    Mar-08 13:24:38.492 [Write-MyReputationList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized MyReputationList completed in 137 msec 
    Mar-08 13:24:38.493 [Write-OpenOffers_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized OpenOffers completed in 123 msec 
    Mar-08 13:24:38.493 [Write-MyProposalList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized MyProposalList completed in 129 msec 
    Mar-08 13:24:38.496 [Write-MediationDisputeList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized MediationDisputeList completed in 122 msec 
    Mar-08 13:24:38.496 [Write-MyProofOfBurnList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized MyProofOfBurnList completed in 130 msec 
    Mar-08 13:24:38.496 [Write-MyBlindVoteList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized MyBlindVoteList completed in 130 msec 
    Mar-08 13:24:38.496 [Write-UserPayload_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized UserPayload completed in 126 msec 
    Mar-08 13:24:38.496 [Write-AddressEntryList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized AddressEntryList completed in 151 msec 
    Mar-08 13:24:38.497 [Write-SequenceNumberMap_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized SequenceNumberMap completed in 138 msec 
    Mar-08 13:24:38.497 [Write-PeerList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized PeerList completed in 122 msec 
    Mar-08 13:24:38.498 [Write-MyVoteList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized MyVoteList completed in 155 msec 
    Mar-08 13:24:38.498 [Write-BsqSwapTrades_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized BsqSwapTrades completed in 169 msec 
    Mar-08 13:24:38.510 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Serializing AccountAgeWitnessStore took 107 msec 
    Mar-08 13:24:38.842 [Write-IgnoredMailboxMap_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized IgnoredMailboxMap completed in 259 msec 
    Mar-08 13:24:38.844 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Serializing MailboxMessageList took 130 msec 
    Mar-08 13:24:38.850 [Write-PendingTrades_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized PendingTrades completed in 329 msec 
    Mar-08 13:24:38.850 [Write-UnconfirmedBsqChangeOutputList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized UnconfirmedBsqChangeOutputList completed in 308 msec 
    Mar-08 13:24:38.850 [Write-AccountAgeWitnessStore_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized AccountAgeWitnessStore completed in 340 msec 
    Mar-08 13:24:38.852 [Write-ClosedTrades_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized ClosedTrades completed in 460 msec 
    Mar-08 13:24:38.852 [Write-FailedTrades_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized FailedTrades completed in 307 msec 
    Mar-08 13:24:38.852 [Write-MailboxMessageList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized MailboxMessageList completed in 286 msec 
    Mar-08 13:24:38.852 [Write-PreferencesPayload_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized PreferencesPayload completed in 313 msec 
    Mar-08 13:24:38.852 [Write-DisputeList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized DisputeList completed in 330 msec 
    Mar-08 13:24:38.853 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: flushAllDataToDisk completed 
    Mar-08 13:24:38.853 [JavaFX Application Thread] INFO  b.c.a.BisqExecutable: Graceful shutdown completed. Exiting now. 
    Mar-08 13:24:39.037 [Write-MailboxMessageList_to-disk] ERROR b.c.p.PersistenceManager: Error at saveToFile, storageFile=MailboxMessageList java.io.IOException: Failed to rename /home/yyyyyy/.local/share/Bisq/btc_mainnet/db/temp_MailboxMessageList1764412964800042324.tmp to /home/yyyyyy/.local/share/Bisq/btc_mainnet/db/MailboxMessageList
	    at bisq.common.file.FileUtil.renameFile(FileUtil.java:222)
	    at bisq.common.persistence.PersistenceManager.writeToDisk(PersistenceManager.java:483)
	    at bisq.common.persistence.PersistenceManager.lambda$persistNow$9(PersistenceManager.java:432)
	    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	    at java.base/java.lang.Thread.run(Thread.java:834)

    Mar-08 13:24:39.037 [Write-MailboxMessageList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized MailboxMessageList completed in 185 msec 
    Mar-08 13:36:55.375 [main] INFO  b.c.u.Utilities: System info: os.name=Linux; os.version=4.15.0-66-generic; os.arch=amd64; sun.arch.data.model=64; JRE=11.0.2+9 (Oracle Corporation); JVM=11.0.2+9 (OpenJDK 64-Bit Server VM) 
    Mar-08 13:36:55.503 [main] INFO  b.c.a.AsciiLogo: 



</details>

**Comment by chimp1984** [comment]
Hm... maybe its a concurrency issue?

**Comment by pazza83** [comment]
Will be sending out the info to complete this trade with a manual payout today

**Comment by pazza83** [comment]
Instructions have been sent to buyer and seller for info needed to make a manual payout

**Comment by pazza83** [comment]
The manual payout for the trade has now been successfully broadcast and traders have been informed

**Comment by oscarolivaresme** [comment]
Trade completed. Funds were received successfully.

**Comment by pazza83** [comment]
Glad to hear it. This issue can be closed @ripcurlx

**Comment by pazza83** [comment]
Apologies @oscarolivaresme has their funds but the issue is still to be resolved
