### ISSUE TITLE
Error: "We did not receive a filter object from the seed nodes"

### ISSUE THREAD

**Issue by so7ow** [bisq-network/bisq#6264]
#### Version
1.9.2

### Steps to reproduce
Launch Bisq. 

### Expected behaviour
No error. 

### Actual behaviour
Error. 

### Screenshots
![image](https://user-images.githubusercontent.com/633079/175790878-b53ccd36-2dfd-4901-8d56-51c91e22649a.jpeg)

#### Device or machine
Docker image fflo/bisq-on-docker running on Synology 1815+, DSM 7.1-42661 update 2.

**Comment by kwall2004** [comment]
Same

**Comment by ripcurlx** [comment]
This is unfortunately still related to the choppy Tor connection based on the DDoS attack on the Tor network: https://status.torproject.org/

**Comment by stone212** [comment]
@ripcurlx 

This was not happening for me on the same connection on 1.8.?.  It only started when I upgraded.  So maybe it's not due to the Tor connection?  Or did the problem exist but 1.9.4 introduced the error message?

**Comment by ghost** [comment]
It is strongly correlated with the DDoS.  Many users started reporting the error at the same time, as a result one of our support agents @w0000000t created this workaround to [manually select functioning seednodes.](https://bisq.wiki/Manually_select_seednodes)

**Comment by Menziess** [comment]
I'm having the issue right now.
[v3 Onion Services](https://status.torproject.org/affected/v3-onion-services/): Disrupted

**Comment by so7ow** [comment]
Haven't seen this since the initial report.
