### ISSUE TITLE
Connection to Bitcoin networking failing at startup

### ISSUE THREAD

**Issue by DieserBobby** [bisq-network/bisq#6268]
### Description
After not using bisq for a long time I was asked to update which I did.
While starting **Version 1.9.2** connection to  Bisq network fails saying: **Invalid key type**

#### Version
**Bisq 1.9.2.**

### Expected behaviour
Start bisq normally

### Actual behaviour
Bisq does not connect to bisq network and will not open.

### Screenshots
![Fehler beim Verbinden mit dem Tor Netzwerk](https://user-images.githubusercontent.com/63121369/176161978-b7c52396-f27d-4f05-9b8d-ad89330b3b5f.JPG)

I tried to reinstall using another installer, downloaded from here, same result.
When "repairing" the installation using the repair-button of the installer, I got another error:

![repair fehler](https://user-images.githubusercontent.com/63121369/176162625-6fff2e59-a3fe-4f67-a3db-14a63c144b90.JPG)

#### Device or machine

Win 10 pro 64bit 

#### Additional info
I am also worried about loosing my in-bisq-reputation, I dont know where this is saved exactly.
Could complete uninstalling and aftrwards reinstalling delete my **bisq-identity?**
Hopefully somebody can help.

**Comment by ghost** [comment]
One possibility is that Tor was upgraded last year from v2 to v3, which requires a completely new onion address.  Its possible that you have an old v2 address which will need to be upgraded, see here for instructions:  https://bisq.wiki/Changing_your_onion_address

If upgrading your onion address does not work, please could you grab `bisq.log` from your [data directory](https://bisq.wiki/Data_directory#Windows) and attach it here.  Or you could search for "Invalid key type" in `bisq.log` and paste here the 200 or so lines of logging prior to it.  This would hopefully enable us to get an idea of what was going on when the error happened.

**Comment by DieserBobby** [comment]
Thanks for your response!
I upgraded onion address according to the instruction by removing  the "hiddenservice" folder to another place.
After this, bisq started properly.
As expected all reputations are gone.
Unfortunately my balance sheet is set to zero although I had some little amount of btc in there.
Is there a chance to restore the money into the new setup?
Hmm... the wallet though seems to be the same (made in 2019) - I am not 100% sure how much money was left to be honest.

**Comment by ghost** [comment]
Within Bisq, `Account -> Wallet Info` is one way to check your Bisq wallet balance.  `ctrl-e` (emergency wallet) is another.

You can view from another wallet using watch keys, instructions here: https://bisq.wiki/Watch_keys

**Comment by osequi** [comment]
Experiencing the same error with a fresh install, never used Bisq before

**Comment by ghost** [comment]
@osequi try a new Tor identity:  With Bisq closed, delete the `tor` folder in your [data directory](https://bisq.wiki/Data_directory). Then restart Bisq.

**Comment by osequi** [comment]
Thanks @jmacxx that was it :)
