### ISSUE TITLE
I couldn't make trades with the last update. And now this new update I can't even get to the log In screen.

### ISSUE THREAD

**Issue by hoodulum** [bisq-network/bisq#6273]
### Screenshots

![image](https://user-images.githubusercontent.com/78965780/176475610-5a78ee68-87e5-435b-bfb7-62eeb35fa1ae.jpeg)

#### Device or machine

Windows 8.1

**Comment by ghost** [comment]
Duplicate answered here: https://github.com/bisq-network/bisq/issues/6255#issuecomment-1170260965
