### ISSUE TITLE
Link on wiki points to empty install_java.sh file

### ISSUE THREAD

**Issue by ghubstan** [bisq-network/bisq#6279]
### Description

In the [Downloading_and_installing](https://bisq.wiki/Downloading_and_installing#Build_from_source) wiki page, the [For Linux and macOS](https://github.com/bisq-network/bisq/blob/master/scripts/install_java.sh) link points to an empty install_java.sh script.

#### Version

v1.9.2

### Steps to reproduce

Click the [For Linux and macOS](https://github.com/bisq-network/bisq/blob/master/scripts/install_java.sh) link in the [Downloading_and_installing](https://bisq.wiki/Downloading_and_installing#Build_from_source) wiki page.

### Expected behaviour

Not sure if the install_java.sh script was clobbered while resolving a file conflict, or really is obsolete.  Either the script needs to be fixed, or the link on the wiki needs to be adjusted .

### Actual behaviour

Link points to empty file.

### Screenshots

![for-linux-macos](https://user-images.githubusercontent.com/36207203/177005516-ccd9b3a0-269e-4339-8f44-bcad4d9b5f5b.png)

**Comment by ghost** [comment]
@ripcurlx It seems to be [fixed](https://github.com/bisq-network/bisq/pull/6287)
