### ISSUE TITLE
Could not connect to running Tor: Cannot run program "uname"

### ISSUE THREAD

**Issue by dm1tz** [bisq-network/bisq#6294]
### Description

Connecting to Bisq network results in error: 
```
"ERROR b.n.p2p.network.TorNetworkNode: Could not connect to running Tor: Cannot run program "uname": error=2, No such file or directory
[JavaFX Application Thread] ERROR bisq.core.app.P2PNetworkSetup: onSetupFailed"
```
#### Version

1.9.4

### Steps to reproduce

Run `LD_PRELOAD=/lib/libgcompat.so.0 bisq-desktop`

### Expected behaviour

Bisq starts successfully

### Actual behaviour

App fails to connect to the Bisq network

### Screenshots

![image](https://user-images.githubusercontent.com/82608185/179020798-8f5462f0-5591-4c4b-a0ae-c496e876759e.png)

#### Device or machine

OS: Alpine Linux Edge
Linux kernel:  5.15.54-0-lts
glibc version: musl-1.2.3 with gcompat libs
Java version: openjdk version "11.0.15" 2022-04-19

**Comment by ghost** [comment]
On your Alpine box, try `uname -m`, does it produce any output?  That seems to be the command Bisq Netlayer is attempting to run.

**Comment by dm1tz** [comment]
> On your Alpine box, try `uname -m`, does it produce any output? That seems to be the command Bisq Netlayer is attempting to run.

Yes, it does produce an output:  `x86_64`. I thought that usage of busybox version of uname could be the problem, but even installing gnu version of it didn't help.

**Comment by ghost** [comment]
May I ask what is the preference for running Bisq on Alpine versus a more generic Debian-type platform?

**Comment by dm1tz** [comment]
> May I ask what is the preference for running Bisq on Alpine versus a more generic Debian-type platform?

I don't have any specific use case for it, just happen to use Alpine as my daily driver.

**Comment by Android-X13** [comment]
What about:

`PATH=$PATH LD_PRELOAD=/lib/libgcompat.so.0 bisq-desktop`

**Comment by dm1tz** [comment]
> PATH=$PATH LD_PRELOAD=/lib/libgcompat.so.0 bisq-desktop

Thanks for the tip, but unfortunately still get the same `Cannot run program "uname"` error.
