### ISSUE TITLE
cannot find the x.x BTC transaction failed

### ISSUE THREAD

**Issue by derekellison** [bisq-network/bisq#6295]
### Description

On 3 occasions now I have been unable to take an offer to sell BTC. The process works fine until I click "review and take offer to sell BTC". Then I get a dialog box saying "Cannot find x.x BTC transaction failed". I am then told that no funds were transferred, and that I should shutdown and go back in. I do this and then the transaction sits in open trades with a red exclamation mark. I cannot get it to try again as there is no button to retry. All I am able to do is to move it to failed trades. However this now means that I cannot take this offer - if I try I receive a message as attached saying "You cannot take this offer because you already took it earlier..." and I have now missed the offer, and also the app crashes at that point and I have to use task manager to close it. So frustrating and I am missing good opportunities to take good sell offers. Thinking of going back to regular exchanges sadly, but can't see a way to solve this. If you are too busy to fix it please suggest a workaround thanking you kindly.

Note that I have very high speed reliable internet and a super fast Intel core i9 with 32G high speed memory. Sometimes I see a message saying DAO is lost so perhaps it relates to that, however if that is the case it should not say "wallet successfully funded" and let me get all the way to the end of taking a sell offer before telling me it can't find my BTC. Ideally it should check that the DAO is fine before even showing BUY/SELL offers.

Additionally there is a button in "Failed Trades" that says "move trade to open trades" however that button does not work in my experience and always shows the error "Failed to move this trade to open trades".

#### Version

v1.9,.4 windows

### Expected behaviour

That I can click "Confirm offer to sell BTC" and that the sell order will succeed.

### Actual behaviour

In 3 cases, when I clicked "Comfirm offer to sell BTC" I received a message that the system couldn't find my BTC and that no funds or fees had been deducted, and that I should try to shutdown and restart the application. This failed to return the sell offer to the open trades, and no action that I tried would return this offer to open trades. Attempting to try to take the sell offer ends up with a dialog message saying "You cannot take this offer because you already took it earlier..." and then the Bisq application crashes.

latest trade ID that failed: 60795580-4a65ed8a-fd20-4789-8b0c-049f56933bba-194

### Screenshots

![image](https://user-images.githubusercontent.com/4453793/179346615-d2b4a4e4-82e2-4e8b-a875-e0ee0a4eb54d.png)

#### Device or machine

Windows 10 Intel core i9 with 32G high speed RAM, high speed fibre internet connection

#### Additional info

latest trade ID that failed: 60795580-4a65ed8a-fd20-4789-8b0c-049f56933bba-194

**Comment by ghost** [comment]
When people have reported this in the past a solution which worked was to consolidate UTXOs by doing a send all to a fresh address obtained from the Funds -> Receive Funds tab.  Use a custom `2 sat/vb` miner rate to save on fees.

**Comment by derekellison** [comment]
> When people have reported this in the past a solution which worked was to consolidate UTXOs by doing a send all to a fresh address obtained from the Funds -> Receive Funds tab. Use a custom `2 sat/vb` miner rate to save on fees.

This doesn't solve the failed trade. The problem is that trade is now in limbo and there is no way to attempt that trade again.

A fix is needed so that when such an issue occurs the trade can be reset, or has the ability to be moved to "open trades" again.

![image](https://user-images.githubusercontent.com/4453793/182595936-5e972516-f40d-4dfd-9a11-5828acb13795.png)
