### ISSUE TITLE
Offer is auto disabled after few seconds

### ISSUE THREAD

**Issue by bvanoost** [bisq-network/bisq#6299]
### Description

I made an offer and saw it disappear from the offer list and when i went to portfolio it was there but the enable switch was off, when i turn it back on it goes off again a few seconds later.  I have tried enabling it many times and it will not stay on.  I have checked that my system time is in sync and have restarted Bisq and laptop several times.  Other users have noticed this problem before as well: https://bisq.community/t/offer-keeps-getting-disabled/11629

#### Version

1.9.4

#### Device or machine

Ubuntu 22.04

**Comment by ghost** [comment]
Open your bisq.log (Account -> Backup -> `Open Log File`) and search for `Deactivating open offer`.  Do you find any match for that, can you paste the result here.

What is the DAO state?  (DAO -> Network Monitor, `DAO state`).

**Comment by bvanoost** [comment]
Good catch jmacxx, the log was saying "Deactivating open offer XXXXX due to mempool validation" and when i looked at the DAO state there were some errors so I rebuilt it from scratch and that seems to be problem solved, the offer has been on for 10 minutes straight now.
