### ISSUE TITLE
Address field in "Fund your wallet" should only launch external wallet via left click

### ISSUE THREAD

**Issue by jonathancross** [bisq-network/bisq#630]
Unexpected mouse behavior in this Address field:
Funds -> Deposit funds -> Fund your wallet -> Address
Platform: Linux Mint 17 / Cinnamon

The following actions currently launch the external bitcoin wallet:
- Clicking "Address" field's empty white space (left and right mouse click)
- Selecting text of the bitcoin address
- Right clicking on text of the bitcoin address (to open context menu)

Expected behavior:
- Only a left-click on the address text should launch the external wallet.

---

Additional "Nice to have" (low priority) improvements:
- We might reduce the width of the Address and Amount fields so the "Copy" icon is closer to the address.
- We could then move the QR code to the right or left side to reduce the overall vertical space needed for this panel (important for laptops or smaller monitors).
- ~~Remove the label "QR-Code:"~~ - Addressed in f6b2d77d12ca18988a8e7ae15bc8f62ec5d9c522

**Comment by ManfredKarrer** [comment]
Thanks for the input!

Seems JavaFX does not distinguish between left and right click with standard handlers. I use setOnMouseClicked. With more specific code it should be possible, but have no time yet to fix that now.
- Yes I agree that the copy icon is too far away, but that is used in many places and would require a bit of graphic re-design to get it right.
- QR code has only a few good resolutions. Next smaller size would be like in the create offer view. But might be re-layouted like there.
- I removed the "QR-Code:"

**Comment by ManfredKarrer** [comment]
Fixed here: https://github.com/bitsquare/bitsquare/commit/f51bf75003daf36a9d47a598d75155ecd325f5e5
