### ISSUE TITLE
Pop-up and docs give contradictory advice on trade-id as reason for payment

### ISSUE THREAD

**Issue by bitcoinwakanda** [bisq-network/bisq#6300]
### Description

There are contradictory statements between the trading rules in the docs (https://docs.bisq.network/trading-rules) and the pop-up that appears in the app when making a trade. In the Bisq app it is recommended to NOT give the trade-id as the reason for payment, while in the docs are explicitly asking the users to enter the trade-id as reason for payment. Which one is the right behavior?

#### Version

v1.9.4

### Steps to reproduce

Open a trade with SEPA payment and the notification appears.

### Expected behaviour

The recommended behavior should be the same everywhere.

### Actual behaviour

The recommended behavior is contradictory.

### Screenshots

Bisq:
<img width="559" alt="Screen Shot 2022-07-26 at 2 12 10 PM" src="https://user-images.githubusercontent.com/110035951/181005682-dd888bb6-46ea-4c10-b384-bf33596737da.png">

Docs:
<img width="939" alt="Screen Shot 2022-07-26 at 2 12 49 PM" src="https://user-images.githubusercontent.com/110035951/181005724-3d795a08-0722-43da-96fa-eee75679e984.png">

#### Device or machine

Any

**Comment by ghost** [comment]
Bisq app and Wiki are correct, the docs are outdated.  Someone is going to correct it.  Thankyou for reminding us.

@m52go @pazza83

**Comment by pazza83** [comment]
Hi @bitcoinwakanda thanks for raising this.

I think the whole https://docs.bisq.network/ should be retired.

It ranks well in search engines so maybe a 401 redirect should be used on each page to point to the corresponding wiki page. This way hopefully most of the search rankings will be transferred to the wiki.

**Comment by bitcoinwakanda** [comment]
> Hi @bitcoinwakanda thanks for raising this.
> 
> I think the whole https://docs.bisq.network/ should be retired.
> 
> It ranks well in search engines so maybe a 401 redirect should be used on each page to point to the corresponding wiki page. This way hopefully most of the search rankings will be transferred to the wiki.

Makes sense, I also found it through a search engine.
