### ISSUE TITLE
Annoying feature of Offer Book view

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#632]
In the offer book view I discovered a new feature recently. When I click on a buy or sell offer it immediately takes me to the corresponding Buy or Sell page, and even switches to the right currency. This is GOOD!

But ... if there is only a Buy or a Sell listed but not both, changing the currency dropbox in the offer book windows takes us immediately to the Buy (or Sell) page for that currency. That's BAD because I didn't want to do that necessarily.

**Comment by ManfredKarrer** [comment]
I fear I dont understand the second part...

**Comment by haiqu** [comment]
In that case it may not be intentional. But just in case you didn't follow what I said, I'll try again. Let's say:
1. There is a Sell offer on Eth but no Buy offer.
2. In Offer Book I change the currency to Eth.
3. Immediately I am taken to the Buy page.

That was unexpected, since I was just browsing and did not intend to buy Eth right now.

**Comment by ManfredKarrer** [comment]
So first u are at Market/offer book. 
Then u select ETH and see there is no buy offer. 
The next steps I dont understand: In Offer Book I change the currency to Eth. -> U have already selected ETH otherwise u would not see EHT offers.

**Comment by haiqu** [comment]
Ah. In step 1 the user doesn't yet _know_ that there are no Buy offers. He only changes the currency once, in step 2. But then .... whizz, he's on a different page.

**Comment by haiqu** [comment]
You can relax, the latest build doesn't do that any more.
