### ISSUE TITLE
Build instructions give no info about java

### ISSUE THREAD

**Issue by l0k18** [bisq-network/bisq#6338]
Please, can there be a simple instruction on how to install java version. Even if it is all linux version download zip unpack run as root.

Searched the repo for the term "java" and found nothing that gave information about installing java.

Java is not installed by default anywhere.

`apt get install java` does not work.

**Comment by ghost** [comment]
Found it mentioned in 2 places:

> If you do not have JDK 11 installed, check out [scripts](https://github.com/bisq-network/bisq/blob/master/scripts) in the scripts directory or download it manually from https://jdk.java.net/archive/.

https://github.com/bisq-network/bisq/blob/master/docs/build.md#important-notes





https://github.com/bisq-network/bisq/blob/babdc750ac696f1b222be172b968aed40224b95f/Makefile#L11-L18

**Comment by l0k18** [comment]
AH. Well installing default-jre on ubuntu worked, just to also note.
