### ISSUE TITLE
Deposit transaction ID unrecognized by desktop app

### ISSUE THREAD

**Issue by Drazen-V** [bisq-network/bisq#6339]
### Description

I have made an offer which was taken.
On the desktop app, under Portfolio -> Open Trades, under Trade Information > Deposit transaction ID, the tx id shows, but the app cannot successfully get the proper information to see that the transaction is already included in a block, that is, there is the spinning loading icon, as if the transaction is still part of the Bitcoin mempool. As a result, the trade remaining time clock has not started to tick.
A restart to the app does not help.

Notes:
1. I have a different offer, also initiated by me, that was taken and it shows alright. This offer was taken after the one mentioned above.
2. I received a message from the taker that they mistakenly pressed the "payment started" button. I don't know the timeline, as it was on the taker side, but perhaps they clicked the "payment started" button before the transaction was actually included in a block. This may screw the clock somehow. Highly speculative though. If I get more info from the taker, I will report.

See the screenshots enclosed:
- one from my app, it shows the deposit transaction's status as mentioned above, as well as the "confirm payment receipt", indicating that the taker indeed pressed the payment button.
- from the block explorer, showing that the tx is indeed included in the Bitcoin blockchain.

#### Version

Desktop app v1.9.4

### Expected behaviour

The deposit tx should show as completed (ticked), and the clock should start counting down.

### Actual behaviour

The deposit tx shows as if it is still not included in the chain.

### Screenshots

![1](https://user-images.githubusercontent.com/52383635/186936822-15b4d143-643f-49f7-9229-7333efc65dc0.png)

![2](https://user-images.githubusercontent.com/52383635/186936853-5d9d29f8-7019-43be-a6a8-dcac395da57e.png)

#### Device or machine

Windows 11

#### Additional info

See Notes above

**Comment by pazza83** [comment]
Most of the rime a restart fixes this. As you have tried this and the error persists I would recommend the following:

- Firstly opening mediation for the trade (press the trade and select Ctrl + O. You can then inform the mediator of the issue.
- Backing up your data directory https://bisq.wiki/Backing_up_application_data
- Doing an SPV resync https://bisq.wiki/Resyncing_SPV_file

Following the SPV resync you should find the trade shows as confirmed.

**Comment by Drazen-V** [comment]
Thanks, the SPV resync solved the issue: the deposit tx shows as completed and the clock for the trade remaining time counts down correctly.

If there is interest in debugging and finding the root of the problem, I am happy to help. Otherwise, I guess the issue can be closed.

Thanks again!
