### ISSUE TITLE
Intervals on Trades graph inappropriate

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#634]
The One Minute selection seems to be useless, but a Quarterly would be useful. Take one out, insert the other. Simple task.

**Comment by ManfredKarrer** [comment]
Yes removed the minute. We have 10 min. already so a 15 min. would be too much IMO. But I added Year, so one can see the total volume from the last year (about 600 BTC)

**Comment by haiqu** [comment]
Nice! ;)
