### ISSUE TITLE
Deposit transaction ID N/A

### ISSUE THREAD

**Issue by Drazen-V** [bisq-network/bisq#6347]
### Description

I have made an offer which was taken.
On the desktop app, under Portfolio -> Open Trades, the Trade information box is completely empty (see first screenshot).
Clicking on the Trade ID info button, under Details, the Deposit transaction ID is N/A (see second screenshot).
There, clicking the Detail Data button, at the very end there is no "Raw deposit transaction as hex", like on other trades.
Additionally, under Funds -> Locked Funds, there is no raw for this trade, and under Funds -> Transactions, there is a raw for the funds movement (the deposit), but there is no Trade ID, and Details is "Withdrawn from wallet" (instead of Multisig deposit) -- this also shows the tx ID.

Looking at the log file, I can find the Deposit tx ID (see third screenshot), as well as the corresponding hex.
Moreover, I see the error `ERROR b.d.m.o.w.TradeDetailsWindow: trade.getDepositTxId() and trade.getDepositTx().getTxId().toString() are not the same. trade.getDepositTxId()=null, trade.getDepositTx().getTxId().toString()=null, depositTx=null`, which I suppose is related to this trade.
A restart to the app, as well as resyncing of the SPV file, does not help, as reported by others with a similar issue.

Going over the log file, it seems that the desktop app got restarted (the pc had a crash) after the offer was accepted but before the deposit tx got into a block. The error above only appears after the app restart. However, the tx ID also appear in the log file after the restart (not only before), probably just for the spent tx (the withdraw above).

#### Version

Desktop app v1.9.5

### Expected behaviour

The Trade information box should contain the trade informaiton, and the deposit tx ID should display the tx ID.

### Actual behaviour

The Trade information box is empty , and the deposit tx ID shows N/A.

### Screenshots

![12](https://user-images.githubusercontent.com/52383635/188268663-04de7d0e-b335-43d2-b19e-499330ff5ee5.png)

![11](https://user-images.githubusercontent.com/52383635/188268666-a68f5d6d-0a7d-4000-ba8d-f568d8f9e5d9.png)

![13](https://user-images.githubusercontent.com/52383635/188268668-b745a7cd-a5e7-4a2b-9e48-c0b2cdd760fc.png)

#### Device or machine

Windows 11

#### Additional info

Similar issues, but there are no methods of how to resolve:
- https://github.com/bisq-network/bisq/issues/6205
- https://github.com/bisq-network/bisq/issues/4994
Also
- https://github.com/bisq-network/bisq/issues/3502
- https://github.com/bisq-network/support/issues/591

For potential debugging: https://github.com/bisq-network/bisq/pull/6211

The taker made the payment, but I cannot approve on the app.

**Comment by ghost** [comment]
Sounds like the multisig deposit has been set up but your Bisq does not have it.  There are a multitude of possible reasons a trade can fail.  I investigated a similar case where the app was shut down while a trade was being initialized (#6205).
Please contact your mediator if possible (shown in trade details, either @pazza83 or @leo816) so they can guide you through the process necessary to recover the funds.  https://bisq.wiki/Finding_your_mediator
I am ready to look into this issue further to see what can be done in terms of bug fixing.  The log would be crucial.

**Comment by barakshani** [comment]
I've found the mediator, thanks.

Let me clean my log file -- do you know what you need?
Alternatively, is there a way to send you the log directly? keybase?

**Comment by Drazen-V** [comment]
I've found the mediator, thanks.

Let me clean my log file -- do you know what you need?
Alternatively, is there a way to send you the log directly? keybase?

**Comment by Drazen-V** [comment]
Turns out I cannot open a support ticket without a Deposit ID. @pazza83, what's the best way to reach you?
