### ISSUE TITLE
ripcurlx public key is expired

### ISSUE THREAD

**Issue by regenerous** [bisq-network/bisq#6350]
Keybase.io public key of ripcurlx is expired and when compared with the key downloaded from Bisq website, it does not match. Downloading and trusting the public key provided on the Bisq website defeats the purpose of verifying a download since if the download was compromised, then the downloadable public key on the website can be compromised as well.

Please provide an alternative source to download a non-expired public key to verify the downloads.

**Comment by regenerous** [comment]
Just downloaded the key from keyserver.ubuntu.com and that one is not expired and worked. May want to update the keybase.io key if you're going to reference it in the documentation.

**Comment by ripcurlx** [comment]
@hugoender Thanks for pointing this out! We don't use Keybase anymore so we need to update the documentation to point to another source for verification purpose. For now I updated my public key on Keybase.
