### ISSUE TITLE
SignMediatedPayoutTx

### ISSUE THREAD

**Issue by billypendennis** [bisq-network/bisq#6366]
### Description
An error occurred at task: SignMediatedPayoutTx
Exception message: myMultiSigPubKey from AddressEntry must match the one from the trade data. trade id =97692-14ef623a-6758-4f12-8bba-d37eb4926b82-194

#### Version

v1.8.4
### Expected behaviour

I expected the transaction to complete.

### Actual behaviour

I tried to accept the proposed resolution but it came up with the error message.

#### Device or machine

Machine is Hewlett Packard on Windows 10.

#### Additional info

[bisq log file.txt](https://github.com/bisq-network/bisq/files/9692391/bisq.log.file.txt)

**Comment by billypendennis** [comment]
Your trade peer has accepted the mediator's suggestion for trade 97692
You have accepted the mediator's suggested payout but it seems that your trading peer has not accepted it.

Once the lock time is over on 07 Oct 02:03 (block 757,359), you can open a second-round dispute with an arbitrator who will investigate the case again and do a payout based on their findings.

You can find more details about the arbitration model at:[1]
[https://bisq.wiki/Dispute_resolution#Level_3:_Arbitration]

**Comment by ghost** [comment]
@billypendennis Looks like your mediator is @leo816.  Please could you click on the button in mediator chat to send the trade's log files to him.  I checked the log file you attached here but it does not cover the full timeline of the trade.
