### ISSUE TITLE
Client not starting: java.lang.IllegalStateExcemption:...

### ISSUE THREAD

**Issue by buddhalore** [bisq-network/bisq#6371]
### Description

Bisq doesn't start up correctly: error message: "java.lang.IllegalStateExcemption: Pending or IN_CONFLICT...">
Resetting Tor settings and restarting the client doesn't change anything. Can't even close the "reset Tor settings" window to get into the client (to do a SPV sync).

#### Version

1.9.5

### Steps to reproduce

Just starting up the client, with reset Tor settings I get the same error message

### Expected behaviour

Client would load normally with reset Tor settings

### Actual behaviour

Continuous error on repeat. Am not even getting to the password request. Stalls at around 9 peers

### Screenshots
![bisq problem](https://user-images.githubusercontent.com/85696011/194176677-674392c1-a35c-4a86-a641-154a468e3cb7.png)
![Bisq front](https://user-images.githubusercontent.com/85696011/194177474-44dae326-0d35-43c6-ab9c-45a477fb3492.png)

#### Device or machine

Mas OS 10.13.6

#### Additional info

< ..>

**Comment by Rot127** [comment]
Got the same problem since at least 2 weeks (sorry hadn't time to open an issue).

Here are the logs and the exception in more detail:
```
Oct-05 19:01:23.691 [JavaFX Application Thread] ERROR b.core.btc.setup.WalletsSetup: Service failure from state: STARTING; failure={} java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:591)
	at org.bitcoinj.wallet.Wallet.setTransactionBroadcaster(Wallet.java:5241)
	at org.bitcoinj.core.PeerGroup.addWallet(PeerGroup.java:1218)
	at bisq.core.btc.setup.WalletConfig.startUp(WalletConfig.java:338)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:61)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:117)
	at java.base/java.lang.Thread.run(Unknown Source)

java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:591)
	at org.bitcoinj.wallet.Wallet.setTransactionBroadcaster(Wallet.java:5241)
	at org.bitcoinj.core.PeerGroup.addWallet(PeerGroup.java:1218)
	at bisq.core.btc.setup.WalletConfig.startUp(WalletConfig.java:338)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:61)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:117)
	at java.base/java.lang.Thread.run(Unknown Source)
Oct-05 19:01:23.695 [JavaFX Application Thread] ERROR bisq.core.app.WalletAppSetup: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING. 
```

**Comment by pazza83** [comment]
Hi an SPV resync should fix this issue: https://bisq.wiki/Resyncing_SPV_file

Always be sure to do a backup first: https://bisq.wiki/Backing_up_application_data

**Comment by Rot127** [comment]
Indeed it does.

**Comment by buddhalore** [comment]
I have to do a manual SPV resync. That I can't enter the client means I have to revert to my last back some months ago. Am I correct in assuming the client will never load? It just stalls at 8-9 peers and don't seem to proceed (when I don't reset Tor, pressing "close" and load the client though there's no mainnet connection like the 2cnd screendump)

**Comment by ghost** [comment]
@buddhalore No need to resort to your previous backup.  https://bisq.wiki/Resyncing_SPV_file#From_the_file_system

> Close Bisq, delete the btc_mainnet/wallet/bisq.spvchain from your [data directory](https://bisq.wiki/Data_directory), start Bisq, wait for it to load, and then restart Bisq again.
> Bisq will not prompt you to restart it again—so don't forget to actually do it!
> Depending on the age of your wallet and how many transactions it has, it may take a while to finish syncing. During syncing, it's normal for your machine to reach high CPU usage levels, and Bisq may not be responsive until syncing has finished.

**Comment by buddhalore** [comment]
Im posting in this thread cause its a similar problem, 1.9.9 bisq on mac os x 10.13.6 starting giving problems again. I post here the error messages first, before I decided to try reinstalling the client:
![Screen Shot 2023-03-14 at 11 01 59](https://user-images.githubusercontent.com/85696011/225876990-1336c3b2-734b-40e1-9c00-95082c222b6f.png)
![Screen Shot 2023-03-14 at 11 02 07](https://user-images.githubusercontent.com/85696011/225877000-900f3ba6-2748-465f-9745-2a35dae75b2d.png)
![Screen Shot 2023-03-17 at 10 56 14](https://user-images.githubusercontent.com/85696011/225877016-d1fe0944-a807-47b9-a619-61265024af10.png)

Then I try downloading 1.9.9 again from github, after verifying I get the following error:
![Screen Shot 2023-03-17 at 11 10 17](https://user-images.githubusercontent.com/85696011/225877233-36820f28-455f-4441-bafb-defc3febae78.png)

First I just cancel, then try installing my old Jan download of 1.9.9 but same error message:
![Screen Shot 2023-03-17 at 11 10 17](https://user-images.githubusercontent.com/85696011/225877455-b8b5a085-f86e-470e-a727-f78ea9ed3f7c.png)

I try deleting the bisq.app as said in the system message. But after restarting and reinstalling 1.9.9 from todays download again the same error message. Any suggestions?

**Comment by MwithM** [comment]
You don't need to reinstall Bisq to solve the java.lang... issue. This issue is solved by doing a spv resync: https://bisq.wiki/Resyncing_SPV_file

About being unable to install Bisq, see: https://bisq.community/t/macos-installation-error-bisq-is-damaged-and-cant-be-opened-you-should-move-it-to-trash/11748
Update Bisq if you're not on the last version, but take in mind that reinstalling Bisq is not the solution for except in rare cases.

About "not receiving object filter from seed nodes", I would try restarting Bisq or even delete Tor files at `Settings -> Network Info -> Open Tor Settings -> Delete Outdated Tor Files And Shutdown, then restart Bisq` but sometimes it can be ignored.
