### ISSUE TITLE
QR Code Generator

### ISSUE THREAD

**Issue by flyunity** [bisq-network/bisq#6377]
Hello,

The QR Code Generator on BISQ is using this format to generate a QR Code:

**_"bitcoin:address?amount=0&label=Fund your wallet"_**

However the two different external wallets I use will not accept this format. After talking to their support, they need to see it in this format:

**_"bitcoin:address"_**

Apparently some wallets will take the expanded QR code. However ALL external wallets should take the simplified code that has just the wallet address in it.

Is it possible to change the format that BISQ uses to generate the QR generator to not have the extra parameters?

**Comment by flyunity** [comment]
I just made a discovery. In BISQ, if I input an amount in "Amount in BTC (optional)",  then BISQs QR code works on my other wallets. However if I leave it blank, then it will not work on my external wallets. So the QR generator should say "bitcoin:address"  if the: "amount in BTC (optional)" is blank. However if it is not blank, it should then add that parameter into the QR code.

**Comment by Android-X13** [comment]
Your wallet can handle the `label` and `amount` parameters but only when `amount` is not 0 but this depends on the specific wallet's implementation... I randomly tried some wallets after this and indeed it seems that some cannot decode URIs with any extra parameter, no matter if `amount` is non-zero or not. So the generated QR should either contain a plain `bitcoin:address` URI for such cases or the current extended one (with the `amount` set only if the user has provided an amount in the text field).

It actually makes sense that your wallets do not decode URIs with `amount=0` because using that value is like requesting 0 BTC literally, so there's nothing to fund.

Can you please test if your wallets can decode the following:

`bitcoin:address?label=Fund Bisq wallet`

(only `label` parameter, no `amount`)

**Comment by flyunity** [comment]
> Your wallet can handle the `label` and `amount` parameters but only when `amount` is not 0 but this depends on the specific wallet's implementation... I randomly tried some wallets after this and indeed it seems that some cannot decode URIs with any extra parameter, no matter if `amount` is non-zero or not. So the generated QR should either contain a plain `bitcoin:address` URI for such cases or the current extended one (with the `amount` set only if the user has provided an amount in the text field).
> 
> It actually makes sense that your wallets do not decode URIs with `amount=0` because using that value is like requesting 0 BTC literally, so there's nothing to fund.
> 
> Can you please test if your wallets can decode the following:
> 
> `bitcoin:address?label=Fund Bisq wallet`
> 
> (only `label` parameter, no `amount`)

I tested various wallets. 
All but 1 wallet works with `bitcoin:address?label=Fund Bisq` or` bitcoin:wallet?amount(greater than 0)&label=Fund Bisq wallet`

The one Wallet that did not work with the above is Robinhood (dont hate, trying to move everything out). 
The interesting thing about Robinhood is that it only accepts `address` . Even the `bitcoin:` or any extra parameters throws it out.

My recommendation is have the QR code delete the `label` parameter, AND the `amount` parameter unless the amount is greater than "0".

Not sure if the exchanges save the labels or not, but if so, another reason to delete the `label` parameter.

**Comment by Android-X13** [comment]
Based on your tests and some of my own there's no need to remove the `label` parameter (when using an URI). Wallets that cannot read Bisq's QR will either have issues with the `amount` parameter when its value is 0, or with _any_ parameter, or with the URI format altogether as you have also noticed. Labels are not a bad thing and in fact are used by some privacy-oriented wallets to enforce a feature called "coin control". Ideally your external wallet should be able to parse that parameter (though most will completely ignore it) when reading the QR code and then offer to tag the transaction locally with the specified value.
My only concern here is that labels are used to signify entities (e.g. Bisq), not reasons for payment ("Fund Bisq wallet").
But anyway my point is that you shouldn't be worried about this parameter.

**Comment by flyunity** [comment]
Agreed. So if we can just fix the `amount` parameter to not show a "0" when the field is left blank, then I think we should be good!

**Comment by niyid** [comment]
Hello everyone,

Anybody taking this up? If not assign to me please.

Regards.

**Comment by ghost** [comment]
@niyid the PR above your comment should give you the indication it has been taken up already.

**Comment by niyid** [comment]
> @niyid the PR above your comment should give you the indication it has been taken up already.

Oh. Great. Thank you.
