### ISSUE TITLE
An error occurred at task: CreateMakerFeeTx

### ISSUE THREAD

**Issue by enzoomb** [bisq-network/bisq#6387]
[

### Description
Ocorreu um erro ao colocar a oferta:

An error occurred at task: CreateMakerFeeTx

Ainda nenhuns fundos saíram da sua carteira.
Por favor, reinicie seu programa e verifique sua conexão de rede.
#### Version

v1.9.5

**Comment by ghost** [comment]
Try with more BTC in your Bisq wallet, or consolidate your funds to one UTXO.

**Comment by enzoomb** [comment]
> Try with more BTC in your Bisq wallet, or consolidate your funds to one UTXO.

Okay, thanks
