### ISSUE TITLE
Tor bridge use can't be cleared after error

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#639]
Reported by Shrike on the forum: Tor bridges were set but didn't work. After a long delay he was given the opportunity to enter a new setting. However, at this point there should be an option to clear all bridge settings for the case where it just isn't going to work.

**Comment by ManfredKarrer** [comment]
Prefer to remove bridge support. Was added to get over China GFW but did not help.

**Comment by arruah** [comment]
Doesn't work in Kazakhstan too.

**Comment by haiqu** [comment]
@arruah Can you translate English to Kazakh? We will need that soon.

**Comment by arruah** [comment]
Yes

15 окт. 2016 г. 3:57 пользователь "Rob Judd" notifications@github.com
написал:

**Comment by haiqu** [comment]
Take a look at this file. Everything to the right of the `=` sign on each line needs to be translated.

https://github.com/haiqu/bitsquare/blob/master/gui/src/main/resources/i18n/in_dev/displayStrings_kz.properties

Also refer to the Forum here: https://forum.bitsquare.io/t/any-cunning-linguists-among-us/721/6

**Comment by ManfredKarrer** [comment]
Tor bridges are removed in latest version.
