### ISSUE TITLE
Cannot invoke "java.util.List.isEmpty()" because "peers" is null

### ISSUE THREAD

**Issue by ijanhendrik** [bisq-network/bisq#6390]
First time bug report, not sure how it works. Got this bug:

Cannot invoke "java.util.List.isEmpty()" because "peers" is null

How can I fix that?

**Comment by ghost** [comment]
@ijanhendrik could you provide more information about how to reproduce the issue, what screen you were on, and a stack trace report from bisq.log if possible.  Thanks.

**Comment by sontiger** [comment]
Hi, there I had the same issue and I will attach the log file. Best regars!
[bisq.log](https://github.com/bisq-network/bisq/files/10041201/bisq.log)
