### ISSUE TITLE
Stuch transaction in bisq

### ISSUE THREAD

**Issue by hemzer** [bisq-network/bisq#6392]
### Description
Stuch transaction in bisq. Cant see it on the mempool either

#### Version
v1.9.5

### Steps to reproduce

Withdraw BTC

### Expected behaviour

transaction should enter mempool

### Actual behaviour

Transaction stuck in Bisq. 
Not sent to mempool.
50d32d0b4172fd3194d07d5ed731bbe32ea4efd8a3b0d8927ade518639850ae6

#### Device or machine

Dell / Ubuntu

#### Additional info

![Screenshot](https://user-images.githubusercontent.com/45803492/197664352-f93b93c0-b345-459f-a65b-a3ee7e70057e.png)

**Comment by ghost** [comment]
@hemzer the solution is to resync your wallet state, see https://bisq.wiki/Troubleshooting_wallet_issues

**Comment by hemzer** [comment]
> @hemzer the solution is to resync your wallet state, see https://bisq.wiki/Troubleshooting_wallet_issues

OK did that.. So how am I to get my bitcoins out of Bisq wallet then?

**Comment by pazza83** [comment]
@hemzer now you have done a [resync](https://bisq.wiki/Resyncing_SPV_file) are you able to try resending your Bisq BTC to your wallet.

If that does not work for you I would recommend reaching out to Bisq support channel on Matrix: https://bisq.wiki/Matrix_bisq.chat for some live support

**Comment by hemzer** [comment]
> @hemzer now you have done a [resync](https://bisq.wiki/Resyncing_SPV_file) are you able to try resending your Bisq BTC to your wallet.
> 
> If that does not work for you I would recommend reaching out to Bisq support channel on Matrix: https://bisq.wiki/Matrix_bisq.chat for some live support

Will do Thank you.
I could always sweep the private keys into another wallet, right?

**Comment by pazza83** [comment]
> Will do Thank you. I could always sweep the private keys into another wallet, right?

Yes, this would also work.
