### ISSUE TITLE
An error occurred at task: CreateMakerFeeTx

### ISSUE THREAD

**Issue by enzoomb** [bisq-network/bisq#6394]
#### Version

v.1.9.5

#### Additional info
[log.txt](https://github.com/bisq-network/bisq/files/9893847/log.txt)

**Comment by ghost** [comment]
Related to #6387.

Looks like the Bisq wallet did not like small dust-like UTXOs and an offer size very close to the total balance.

Solution: You consolidated UTXOs and were able to create the offer afterwards.  :+1:
