### ISSUE TITLE
Move related class GrpcClient, GrpcStubs and PasswordCallCredentials into package bisq.cli.request

### ISSUE THREAD

**Issue by Joegardner11** [bisq-network/bisq#6395]
Hi, @chimp1984 

**Issue Description**

Package **_bisq.cli_** groups together miscellaneous classes that might be useful to different packages. The package structure violates the “high cohesion and low coupling” design rules. I found that class **_GrpcClient_**, and **_GrpcStubs_** strongly interact with classes in the other package (**_bisq.cli.request_**) by checking the source code and the snippet of the dependency graph. The project has grown larger, leading to becoming increasingly hard to maintain. During the development process, one groups together classes (that often co-change) with similar responsibilities in one package to facilitate maintenance, which prevents a change that causes other packages to be modified. For example, if one modifies **_package bisq.cli_** (i.e., package rename), resulting in multiple classes of package **_bisq.cli.request_** to be changed.
Location: The source file can be found at path File  cli/src/main/java/bisq/cli/request/ GrpcClient 
cli/src/main/java/bisq/cli/request/GrpcStubs 
cli/src/main/java/bisq/cli/request/PasswordCallCredentials 
Refactoring suggestions

I suggest to move related class **_GrpcClient_**, **_GrpcStubs_** and **_PasswordCallCredentials_** into package **_bisq.cli.request_**.

![dependency graph](https://user-images.githubusercontent.com/29889989/198839781-caf72289-7513-4027-bf97-4dc0b3026484.png)

**Comment by ghubstan** [comment]
I don't have any objection to this re-factoring.  I agree GrpcClient, GrpcStubs and PasswordCallCredentials should be moved into package bisq.cli.request.

I tried it, and all api test suites depending on the modified  bisq.cli.request pkg passed.  CLI terminal based trade-simulation scripts also worked correctly with your proposed change.
