### ISSUE TITLE
Cannot update

### ISSUE THREAD

**Issue by SigmaEnterprise** [bisq-network/bisq#6398]
### Description

Getting dialog box on Windows 10 
The feature you are trying to use is on a network resource that is unavailable 

### Steps to reproduce

Find main.msi in Bisq folder, i do not know it's location

### Expected behaviour

Update to newest version

### Actual behaviour

Update did not progress

#### Device or machine

Windows 10

#### Additional info

The path to my main.msi in Bisq cannot be found

**Comment by w0000000t** [comment]
In my case, on a windows 10 laptop, I got the update popup to 1.9.6, I clicked to download and verify and got an error with verification. Then restarted Bisq, popup was not appearing but I got an update link at center of bottom status bar, clicked that one and it led to a successful download and verification, after which I updated normally.
Do you need a specific help with your instance? The update procedure from inside Bisq will get you several files in your account's download folder, the bisq install exe, the signature, the asc, and several other files, all of which you can safely delete after update.

**Comment by swarna1101** [comment]
The error message "The feature you are trying to use is on a network resource that is unavailable" can occur when you are trying to access a file or resource that is located on a network drive that is not currently available. This can happen if the network drive is disconnected, if there is a problem with the network connection, or if the network resource has been moved or deleted.

To resolve this issue, you will need to ensure that the network resource is available and that you have the correct path to the file. Here are some steps you can try:

1. Check the network connection to make sure that it is stable and that the network drive is properly mapped to your machine.
2. Verify that the file or resource you are trying to access exists and that you have the correct permissions to access it.
3. If you are unsure of the location of the main.msi file, you can try searching for it on your machine using the Windows Search function.
4. If you are unable to locate the main.msi file, you may need to download it again from the Bisq website or from a trusted source.
5. If the issue persists, you may want to consider seeking help from the developers of the application or from a community of users. They may be able to provide more specific guidance on troubleshooting and resolving the issue.

**Comment by sheldonstewart** [comment]
I get the same error. I've tried updating through Bisq app on my windows desktop, and I've tried downloading version 1.9.10 from the site and installing into a new directory. In both cases, I get this error: 
![image](https://github.com/bisq-network/bisq/assets/68789633/f3c73d25-ad02-4d32-a6a6-aa28dfa36908)

I can'tt even uninstall Bisq to do a reinstall. When I try and uninstall I get the same error! Exact same.

**Comment by DarkAnge1** [comment]
For those who are facing this issue, as well as me, the way to resolve this is the following: 
1. Find which version of Bisq you have now. You can do it via Add/Remove programs in Windows.
2. Download that old version of Bisq.
3. Start old version installer. It will unpack MSI file into C:\User\YOUR_USER\AppData\Local\Temp\[SET_OF_NUMBERS].tmp
4. Copy that MSI file somewhere. 
5. Terminate installer of the old version. This will clean those temp files as well, this is why copying MSI is importat.
6. Start new version installer. On prompt for the missing file, poit it to the MSI file you've recently copied. 
7. Process will complete successfully.

Suggestion to Bisq development team is to put uninstaller data somewhere along with the application data. Storing it within Temp folder, which is automatically cleaned by Windows under low space condition is not a very good idea.
