### ISSUE TITLE
macOS: Bisq 1.9.6 has untrusted test code signature & wrong bundle ID

### ISSUE THREAD

**Issue by JayBrown** [bisq-network/bisq#6399]
### Description

Bisq v1.9.6 has a wrong & untrusted code signature; also has the wrong Bundle ID

#### Version

1.9.6

### Steps to reproduce

Open the app e.g. in **Apparency**: https://www.mothersruin.com/software/Apparency/

### Expected behaviour

Should be properly code-signed with an Apple-issued developer code-signing certificate, notarized and trusted by macOS
Bundle ID should be `io.bisq.CAT`

### Actual behaviour

Is not trusted by macOS + wrong bundle ID

### Screenshots

![snap1](https://i.imgur.com/XYrHivi.png)

![snap2](https://i.imgur.com/mskVIwC.png)

![snap3](https://i.imgur.com/2vl2JJ3.png)

#### Device or machine

macOS 12

#### Additional info

n/a

**Comment by ghost** [comment]
ref: https://github.com/bisq-network/bisq/discussions/6341, https://github.com/bisq-network/bisq/pull/6361 and https://bisq.wiki/Downloading_and_installing#macOS :

> Starting with version v1.9.6, we remove notarization from our build pipeline because of of the risk of Apple certification revocation (see https://github.com/bisq-network/bisq/discussions/6341). Unfortunately this will require extra steps when installing Bisq on macOS.

> Please follow the guide at https://support.apple.com/en-us/HT202491 in the section If you want to open an app that hasn’t been notarized or is from an unidentified developer

> If you are running already macOS Ventura (13.0+) you need to do following to be able to start Bisq:

>    enter following command in Apple Terminal sudo xattr -rd com.apple.quarantine /Applications/Bisq.app
>    hit enter and you will be prompted to enter your password to be able to execute the command as super user

> After running this successfully you should be able to start Bisq as always.
