### ISSUE TITLE
Update (1.9.6) error (Mac)

### ISSUE THREAD

**Issue by buddhalore** [bisq-network/bisq#6401]
### Description

Updating from 1.9.5 to 1.9.6 fails (.dmg) from bisq.network manually (not from client)
Upon verifying the asc, having run the .dmg and replaced the old version, then new version fails to load

#### Version

1.9.5

### Steps to reproduce

Downloading the new 1.9.6 (235 MB) - (size seems odd, 1.9.5 was around 335 MB)
Installing and replacing
Error upon loading

### Expected behaviour

New 1.9.6 should load

### Actual behaviour

Error message "file is damaged"

### Screenshots
![Bisq error](https://user-images.githubusercontent.com/85696011/199586730-fd4b20e8-6013-4281-9b0d-9e23be521725.png)

![dwl message](https://user-images.githubusercontent.com/85696011/199586789-b7f09013-8b14-4107-9905-fae695c2f692.png)

#### Device or machine

MAC 10.13.6 High Sierra

#### Additional info

Nov-02 20:15:23.706 [JavaFX Application Thread] INFO  b.c.a.BisqExecutable: P2PService shutdown completed 
Nov-02 20:15:23.706 [JavaFX Application Thread] INFO  b.c.a.BisqExecutable: PersistenceManager flushAllDataToDiskAtShutdown started 
Nov-02 20:15:23.711 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Start flushAllDataToDisk 
Nov-02 20:15:23.836 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Serializing ClosedTrades took 115 msec 
Nov-02 20:15:23.860 [Write-MediationDisputeList_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized MediationDisputeList completed in 141 msec 
Nov-02 20:15:24.001 [Write-ClosedTrades_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized ClosedTrades completed in 165 msec 
Nov-02 20:15:24.002 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: flushAllDataToDisk completed 
Nov-02 20:15:24.002 [JavaFX Application Thread] INFO  b.c.a.BisqExecutable: Graceful shutdown completed. Exiting now.

**Comment by ghost** [comment]
Please see https://bisq.wiki/Downloading_and_installing#macOS :

> Starting with version v1.9.6, we remove notarization from our build pipeline because of of the risk of Apple certification revocation (see https://github.com/bisq-network/bisq/discussions/6341). Unfortunately this will require extra steps when installing Bisq on macOS.

> Please follow the guide at https://support.apple.com/en-us/HT202491 in the section If you want to open an app that hasn’t been notarized or is from an unidentified developer

> If you are running already macOS Ventura (13.0+) you need to do following to be able to start Bisq:

>    enter following command in Apple Terminal sudo xattr -rd com.apple.quarantine /Applications/Bisq.app
>    hit enter and you will be prompted to enter your password to be able to execute the command as super user

> After running this successfully you should be able to start Bisq as always.

**Comment by ghost** [comment]
I have the same issue. I followed Apple's guide, but there is no "Click the Open Anyway button in the General pane to confirm your intent to open or install the app. " that comes up on Security & Privacy that allows me to open Bisq.

macOS Monterey Version 12.6

<details>
<summary>I verified the Bisq signature</summary>

I tried to install the software but was unsuccessful. I first downloaded the binary and the signature file. Then acquired the public key from the [GitHub repo](https://github.com/bisq-network/bisq/blob/master/desktop/package/29CDFD3B.asc). Then verified the signature against the public key.
```bash
$ sudo gpg --import 29CDFD3B.asc
 gpg: key CD5DC1C529CDFD3B: public key "Christoph Atteneder <christoph.atteneder@gmail.com>" imported

$ gpg --verify gpg --verify Bisq-1.9.6.dmg.asc Bisq-1.9.6.dmg
gpg: Signature made Thu Oct 27 11:11:54 2022 EDT
gpg:                using RSA key CB36D7D2EBB2E35D9B75500BCD5DC1C529CDFD3B
gpg:                issuer "christoph.atteneder@gmail.com"
gpg: Good signature from "Christoph Atteneder <christoph.atteneder@gmail.com>" [unknown]
```
</details>

<br><br>


![image](https://user-images.githubusercontent.com/18119820/200132892-03ea622e-0ed1-4e95-a8f6-672d068d4f7f.png)

**Comment by maxim-belkin** [comment]
> > If you are running already macOS Ventura (13.0+) you need to do following to be able to start Bisq:
> 
> > enter following command in Apple Terminal sudo xattr -rd com.apple.quarantine /Applications/Bisq.app
> > hit enter and you will be prompted to enter your password to be able to execute the command as super user

`sudo xattr -rd com.apple.quarantine /Applications/Bisq.app` worked for me

**Comment by ghost** [comment]
> macOS Monterey Version 12.6

**Comment by AleksandrH6** [comment]
I have this same error. Not running Ventura, running MacOS Monterrey 12.6.1 
Not finding any solutions or others with the same problem, anywhere online except for this thread.
Attempted Apple Terminal suggestion for Ventura just to see, didn't work.
Same issue as previous comments, no other Mac security options to bypass this error.

**Comment by ripcurlx** [comment]
Is there someone with the latest Monterey version, who is able to install the current image?

**Comment by aphex3k** [comment]
> Is there someone with the latest Monterey version, who is able to install the current image?

Im using 1.9.6 successfully on Ventura after setting xattrs

**Comment by ripcurlx** [comment]
> I have this same error. Not running Ventura, running MacOS Monterrey 12.6.1 Not finding any solutions or others with the same problem, anywhere online except for this thread. Attempted Apple Terminal suggestion for Ventura just to see, didn't work. Same issue as previous comments, no other Mac security options to bypass this error.

@AleksandrH6 When you ran the Terminal command, what was the output for you?

**Comment by AleksandrH6** [comment]
> > I have this same error. Not running Ventura, running MacOS Monterrey 12.6.1 Not finding any solutions or others with the same problem, anywhere online except for this thread. Attempted Apple Terminal suggestion for Ventura just to see, didn't work. Same issue as previous comments, no other Mac security options to bypass this error.
> 
> @AleksandrH6 When you ran the Terminal command, what was the output for you?

it asked for 
Password:

admin passwords did not work, received 
"Sorry, try again." 
or 
"____(user)_____ is not in the sudoers file.  This incident will be reported."

**Comment by ripcurlx** [comment]
Is this your personal or work laptop? It should be your regular password except you have defined a separate user account you are using because of security reasons.

**Comment by AleksandrH6** [comment]
> sudo xattr -rd com.apple.quarantine /Applications/Bisq.app

Personal iMac, separate user account set up for this. Doesn't seem it needs to be an Admin account because I attempted to load on the admin side as well and it gave me exactly the same message for that user. Thanks

**Comment by HubertusVIE** [comment]
> > > enter following command in Apple Terminal sudo xattr -rd com.apple.quarantine /Applications/Bisq.app
> > > hit enter and you will be prompted to enter your password to be able to execute the command as super user
> `sudo xattr -rd com.apple.quarantine /Applications/Bisq.app` worked for me

This solution worked for me. The developers may want to put this information on the Download Page.
