### ISSUE TITLE
Trojan.Heur! found on Bisq-64bit-1.9.6.exe installer

### ISSUE THREAD

**Issue by ImArghya7** [bisq-network/bisq#6408]
I just downloaded the installer from the Bisq website and ran a Virustotal check, it came up with this result
https://www.virustotal.com/gui/file/1f4b895cfbae4a358a95c686258d231ed07ac06c5daf479755b9a369255c3ba1

Could you kindly explain this?
Is it safe to install?

**Comment by ghost** [comment]
Sometimes antivirus software mistakenly flags Bisq.

There is no trojan in Bisq.  It is safe to install.  You can download it from [here](https://github.com/bisq-network/bisq/releases) on github, or https://bisq.network/downloads/

https://bisq.wiki/Downloading_and_installing contains instructions for verifying the integrity of the downloaded software.

The source code is open so you always have the option to review and [build](https://github.com/bisq-network/bisq/blob/master/docs/build.md) it yourself.

**Comment by ImArghya7** [comment]
Thank you for the clarification.
