### ISSUE TITLE
Java.lang.NullPointerException

### ISSUE THREAD

**Issue by Berensbach** [bisq-network/bisq#6417]
### Description

When starting the app.

#### Version

v1.9.6

### Steps to reproduce

just start the app

### Expected behaviour

no error message

### Actual behaviour

an error message pops up

### Screenshots

![Bisq](https://user-images.githubusercontent.com/36772419/202586857-81a8b6c7-729c-4452-b710-e4f17b14fae5.jpg)

#### Additional info

[bisq.log](https://github.com/bisq-network/bisq/files/10036631/bisq.log)

**Comment by Android-X13** [comment]
If you go to `Settings > PREFERENCES` what value does the `Country` field show you?
Do you remember changing something regarding your region before this error started showing?

**Comment by Berensbach** [comment]
> If you go to `Settings > PREFERENCES` what value does the `Country` field show you? Do you remember changing something regarding your region before this error started showing?

If you go to Settings > PREFERENCES what value does the Country field show you?
-"Latinoamerica"

Do you remember changing something regarding your region before this error started showing?
-No, from the beginning after installation, happened the issue.

-Now I changed my Country field and the issue is solved, thanks.

**Comment by Android-X13** [comment]
There is no "Latinoamerica" option, I suppose there was a specific latin American country shown there and you reported it here in a more generic way? Which is fine, I'm asking just to be clear and understand what the issue was.
