### ISSUE TITLE
Poloniex logo has gone missing

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#643]
In the latest build with all the recent changes it seems the Poloniex logo has slipped through the cracks. It doesn't show up on the screen, at least on my build from the same code as the Dev branch.

**Comment by haiqu** [comment]
False alarm. We never used their logo.

**Comment by ManfredKarrer** [comment]
Yes we use it if a altcoin is selected. maybe the layout change has kicked it out...

**Comment by ManfredKarrer** [comment]
I see it when i select an altcoin....

**Comment by haiqu** [comment]
I see the word `Poloniex` but we didn't use their logo. But I looked in earlier versions, there was never a logo in the graphic.
