### ISSUE TITLE
No seed nodes available

### ISSUE THREAD

**Issue by stone212** [bisq-network/bisq#6448]
### Description

On startup, Bisq app says

```
We did not receive a filter object from the seed nodes.  This is a not expected situation.  Please inform the Bisq developers.
```

#### Version
1.9.4, 1.9.6

### Steps to reproduce

It happens every time I open the Bisq software.

### Expected behaviour

I expect the app to connect to seed nodes, and show me the incoming and outgoing connections.

### Actual behaviour

I see no connections, no offers of any kind.

#### Device or machine

Whonix.  I followed the guidelines for Whonix.

#### Additional info
I used the same whonix with another Bisq instance that has no problems.

This instance worked in the past.

In the time between working and not, I put the seed words into a different instance that works.  

Only one instance is running at one time.

**Comment by ghost** [comment]
- Might be Tor disruption.
- Might be system clock is wrong.
- You could try clearing your tor cache.  Not sure how to do that on Whonix.
- `bisq.log` would probably give us an an idea of what is wrong.  Its in the [data directory](https://bisq.wiki/Data_directory), or you can access it from the Account, Backup screen in Bisq.

**Comment by stone212** [comment]
It's not a Tor disruption, because another Bisq instance works.

System clock verified accurate

Tor cache?  you mean in the app?  That has been cleared.

I looked at bisq.log and didn't see anything strange.  What should I search for?  I don't want to publish the actual log publicly since it has private data like my .onion address

**Comment by ghost** [comment]
Contact Bisq support [via Matrix](https://bisq.wiki/User_support#Via_Matrix_bisq.chat) and send your log to them.
