### ISSUE TITLE
Status bar not updated

### ISSUE THREAD

**Issue by dgyg** [bisq-network/bisq#6475]
### Description

When using the filter in *Porfolio / History* the status bar indicating the number of entries is not updated.

#### Version
v1.9.6

### Steps to reproduce

Switching to *Porfolio / History* and start typing in the field *Filter*.

### Expected behaviour

The number of entries indicated in the status bar is updated and reflects the number of entries shown.

### Actual behaviour

The number is not updated while using the filter.

### Screenshots
![bisq-update-number](https://user-images.githubusercontent.com/7886722/208501514-5dfadaeb-3666-4177-99da-0fab8fc3060e.png)

**Comment by pazza83** [comment]
The number of entries shows the total number of entries across the entire portfolio section.

What sort of use case would you have for showing number of entries by filter? 

For example I would like to see 'Number of entries' with active status when in 'Open Offers' but not sure how this would be achieved.

**Comment by dgyg** [comment]
Without applying any filter the *Number of entries* shows the correct number of each tab *MY OPEN OFFERS*, *OPEN TRADES* etc.

If the *Number of entries* should always show the total of all entries in each tab then there is still a UI bug here that can be reproduced as follows:

1. Select *HISTORY* tab and remember the number. Example 100
2. Apply a *Filter* and count the elements manually. Example 2
3. Change to the *MY OPEN OFFERS* tab
4. Change back to the *HISTORY* tab and check the number again.

In our example the number is 2 and not 100. So the number changed to reflect the applied filter, but it is applied only after changing tabs.
