### ISSUE TITLE
Dev: Error in commit `Use create offer fee from policy`

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#648]
`"The offer fee you " + model.formatter.formatCoinWithCode(FeePolicy.getCreateOfferFee()) + " will be lost if you remove that offer.")`

Should read

`"The offer fee of " + model.formatter.formatCoinWithCode(FeePolicy.getCreateOfferFee()) + " will be lost if you remove that offer.")`

**Comment by ManfredKarrer** [comment]
Ah thanks... Will change
