### ISSUE TITLE
Error Task TrustedListenableFutureTask@nnnnn in v1.9.8

### ISSUE THREAD

**Issue by CygnusGt** [bisq-network/bisq#6484]
### Description

Error message appears:

Task TrustedListenableFutureTask@39d46180[status=PENDING, info=[task=[running=[NOT STARTED YET], bisq.network.p2p.network.NetworkNode$$Lambda$1424/0x000000080082f990@7414378]]] rejected from java.util.concurrent.ThreadPoolExecutor@61f270fb[Running, pool size = 36, active threads = 36, queued tasks = 29, completed tasks = 78078]

#### Version

v1.9.8

### Steps to reproduce

Updated to v.1.9.8 yesterday. Bisq was running over night. I saw this error message the next morning.

### Expected behaviour

Error message should not appear

### Actual behaviour

Message can be dismissed.
After that Bisq runs normal without problems

#### Device or machine

MacBook Pro, 2019
macOS 12.6.1

#### Additional info

I have attached the newest log files

[BisqLog_2022-12-24.zip](https://github.com/bisq-network/bisq/files/10298426/BisqLog_2022-12-24.zip)

**Comment by ghost** [comment]
Thanks @CygnusGt for the helpful log.  This issue is being looked at -- primarily tracked in #6480 but will keep you posted of any solution.

**Comment by CygnusGt** [comment]
Since #6480 was about v1.9.7, I thought it would be better to open a new issue.
Sorry, @jmacxx, if I have caused some confusion with that.
