### ISSUE TITLE
error ver 1.9.8

### ISSUE THREAD

**Issue by wayovermyhead** [bisq-network/bisq#6485]
### Description

Task TrustedListenableFutureTask@2fc0a0be[status=PENDING, info=[task=[running=[NOT STARTED YET], bisq.network.p2p.network.NetworkNode$$Lambda$1353/0x0000000800807a70@72f6077f]]] rejected from java.util.concurrent.ThreadPoolExecutor@8f2655a[Running, pool size = 36, active threads = 36, queued tasks = 30, completed tasks = 114050]
#### Device or machine MacBook Pro Ver 10.15.7

10.15.7

#### Additional info

Task TrustedListenableFutureTask@2fc0a0be[status=PENDING, info=[task=[running=[NOT STARTED YET], bisq.network.p2p.network.NetworkNode$$Lambda$1353/0x0000000800807a70@72f6077f]]] rejected from java.util.concurrent.ThreadPoolExecutor@8f2655a[Running, pool size = 36, active threads = 36, queued tasks = 30, completed tasks = 114050]

**Comment by ghost** [comment]
Thanks @wayovermyhead, this issue is being looked at, primarily tracked in #6480 but will keep you posted of any solution.

**Comment by HenrikJannsen** [comment]
@wayovermyhead Do you get repeated error popups or just one? Does the app behaves normal after closing the error popup?

**Comment by wayovermyhead** [comment]
No repeated popups.  The popup arrived not long after I installed the new version.  After closing the original popup, things seemed to be operating normally.  I was just monitoring prices, offers, etc.  After a day or so, I tried to accept an offer and got the popup again.  I closed the program and reopened.  I was then able to accept the offer and complete the transaction.  Since then the program seems to be operating normally, but I'm just monitoring things.  I haven't tried to accept another offer yet.

Thank you

    On Tuesday, December 27, 2022 at 10:20:53 AM CST, HenrikJannsen ***@***.***> wrote:  
 
 


@wayovermyhead Do you get repeated error popups or just one? Does the app behaves normal after closing the error popup?
