### ISSUE TITLE
Withdrawal TX not accepted by peers. Fee too low.

### ISSUE THREAD

**Issue by systemling32** [bisq-network/bisq#6493]
### Description

I ran into a problem where I tried to withdraw some coins I bought into my hardware wallet. I set the fee rate to 1sat/vbyte as I am not in a rush and want to save on fees. The transaction shows up on the transaction list inside of bisq but in the confirmations column it shows "Seen by 0 peers" forever and the transaction is never mined or viewable on any blockchain explorer. 
However the balance I wanted to withdraw is subtracted from my available balance and is not spendable anymore.
Only way to regain these funds is to Delete SPV file and resync.

#### Version

v1.9.8

### Steps to reproduce

In the 'send funds' dialog select a single native segwit UTXO as input, spend the entire UTXO to another native segwit address, check 'Amount includes mining fee' and set a custom withdrawal transaction fee rate of 1sat/vbyte

### Expected behaviour

- Create a transaction with a fee rate of around 1.02sat/vbyte so that it surpasses the minRelayTxFee of 1000sat/kB
- allow floating point input for fee rate so a user can enter something between 1-2sat/vbyte and create a TX that is not rejected by standard mempool settings
- If a transactions is not accepted by any peers after a defined period of time scrap it and make the inputs spendable again. Also alert the user of the scrapped TX and the possible reason.

### Actual behaviour

Transaction shows up as broadcasted but seen by 0 peers. Funds are marked as spent.
In my testing I calculated that my withdrawal TX hat a fee rate of exactly 1000 sat/kB whereas [this post](https://bitcoin.stackexchange.com/questions/48235/what-is-the-minrelaytxfee#48246) says it needs to be **greater than** 1000 to be valid.

#### Device or machine

amd64 Ubuntu

**Comment by ghost** [comment]
Thanks for the detailed write-up.  Will get that implemented ASAP.
