### ISSUE TITLE
Task TrustedListenableFutureTask@b5b5126[status=PENDING, info=[task=[running=[NOT STARTED YET],

### ISSUE THREAD

**Issue by BLTCCS** [bisq-network/bisq#6499]
I face the error below:
[bisq_error_2023_01_04.txt](https://github.com/bisq-network/bisq/files/10343878/bisq_error_2023_01_04.txt)

[Task TrustedListenableFutureTask@b5b5126[status=PENDING, info=[task=[running=[NOT STARTED YET],](url) bisq.network.p2p.network.NetworkNode$$Lambda$1191/0x000000010079ecb8@4fced3e5]]] rejected from java.util.concurrent.ThreadPoolExecutor@2560c704[Running, pool size = 36, active threads = 36, queued tasks = 30, completed tasks = 2501]

#### Version used is v1.9.8
**Steps to reproduce**
Error appears sometime after application startup

**Expected behaviour**
Error window should not appear

**Actual behaviour**
Error window is shown, once I close it, it does not appear again that day but will show again the next day. Seems to be connected to taking offers/ my offer being accepted

Device or machine
Thinkpad T440p
Windows 8.1 Pro

#### Additional info

Task TrustedListenableFutureTask@b5b5126[status=PENDING, info=[task=[running=[NOT STARTED YET], bisq.network.p2p.network.NetworkNode$$Lambda$1191/0x000000010079ecb8@4fced3e5]]] rejected from java.util.concurrent.ThreadPoolExecutor@2560c704[Running, pool size = 36, active threads = 36, queued tasks = 30, completed tasks = 2501]

I have two failed offers created by myself, accepted by other users but to me the error is displayed:

An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same

ERROR LOGS
[bisq_error_2023_01_04.txt](https://github.com/bisq-network/bisq/files/10343882/bisq_error_2023_01_04.txt)

**Comment by ghost** [comment]
Thanks for reporting.  Two different errors here:

1. **TrustedListenableFutureTask error.**  Tracked in issue [6480](https://github.com/bisq-network/bisq/issues/6480).  Latest [comment.](https://github.com/bisq-network/bisq/issues/6480#issuecomment-1366877455)
2. **DelayedPayoutTx not matching between buyer and seller.**  This is being investigated, perhaps it could be due to one side's DAO state being stale.  It would be helpful if we can get logs from both sides of the trade when this happens.

**Comment by roquefort-sur-soulzon** [comment]
Hi,

Same DelayedPayoutTx issue here on v1.9.8.
I'm available if you need further help from me (logs, troubleshooting).
I'm still in contact with the other side of the trade if you need logs.
I would appreciate a refund for the taker fee.

Regards.
