### ISSUE TITLE
Is jdkfix still required?

### ISSUE THREAD

**Issue by jonathancross** [bisq-network/bisq#650]
From what I can see, [Oracle JDK version 8u102](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html#jdk-8u102-oth-JPR) (1.8.0_102) fixes the [SortedList bug](https://bugs.openjdk.java.net/browse/JDK-8134655).  Can we confirm if `jdkfix-0.4.9.6.jar` is still needed?

I am working on updates to the build instructions for Mac OSx and Bitsquare seems to be working fine without `jdkfix-0.4.9.6.jar`.  However, I am still getting errors in my console and would like to get these resolved to be sure they are not related.

Has anyone else built Bitsquare using the latest JDK and tried this?

Here is the console output (1 unique warning and 1 error on shutdown): [console-log-errors.txt](https://github.com/bitsquare/bitsquare/files/536735/console-log-errors.txt)

**Comment by ManfredKarrer** [comment]
I think with the new version 8_u_112 announced for tomorrow it should be fixed. But had not checked yet if the 1.8.0_102 fixed it already.

" kcr Kevin Rushforth added a comment - 2016-06-03 07:55
Approved to backport to 8u-dev (8u112). "
https://bugs.openjdk.java.net/browse/JDK-8134655

The SortedList bug did not appear consistently, so it was hard to test.

The error in the log is related to the security restriction issue (https://github.com/bitsquare/bitsquare/issues/651).

**Comment by jonathancross** [comment]
Thanks, I missed the `102` vs `112` detail.
Surprising that Bitsquare still worked without the jdkfix jar though...

Feel free to close if you like until we test `112`.

**Comment by ManfredKarrer** [comment]
Yes the SortedList throws only in certain situations, I think mostly at updates of the offer book...

**Comment by ManfredKarrer** [comment]
Hope 112 will be released soon, otherwise I will release without that.

**Comment by jonathancross** [comment]
Per #629

> New jdk is out: http://www.oracle.com/technetwork/java/javase/downloads/index-jsp-138363.html

Cool, got it installed and everything seems to work (no difference from `102` that is).
Do you have a unit test for the SortedList class bug?
Or how would you suggest testing?

**Comment by ManfredKarrer** [comment]
No there is no for the unit test for the SortedList class bug, but I compared the class from our jdkfix module and the new class in the jdk and they are exactly the same.

**Comment by jonathancross** [comment]
Okay, great!
One less manual build step to follow.  :-)

**Comment by phosphorit** [comment]
Oh noes, there is no fixed ARM binary yet, so this breaks the Bitsquare Raspberry Pi install script.  
Heck, I will just include the jdkfix in the install script repo.  
https://forum.bitsquare.io/t/2-btc-bounty-for-improving-performance-of-bitsquare-on-raspberry-pi/295/34?u=phosphor  
https://github.com/phosphorit/bitsquare-on-raspberry-pi

**Comment by phosphorit** [comment]
Turns out it is not so easy to include the jdkfix as it needs to be compiled. @ManfredKarrer would you mind readding the jdkfix or do you have another idea how to get the fix for ARM?

**Comment by ManfredKarrer** [comment]
I made a branch from master for systems which still need the jdkfix (all which are not using the OracleJDK). So if you use that branch it should be like the old version. I will keep it up to data after each release.

https://github.com/bitsquare/bitsquare/tree/MasterWithJdkFix

So please just update the checkout that u use that branch instead of the master.

**Comment by phosphorit** [comment]
:)
