### ISSUE TITLE
Error message of BTC node with unhanlded SendAddrV2Message

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq#6502]
Got that error message in the logs:
```
[BlockingClient network thread for wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid.onion:8333] 
WARN  org.bitcoinj.core.Peer: Peer{[wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid.onion]:8333, 
version=70016, subVer=/Satoshi:0.20.99(@wiz)/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), 
time=2023-01-04 20:06:05, height=770402}: Received unhandled message: 
org.bitcoinj.core.SendAddrV2Message@20509103 
```

**Comment by ghost** [comment]
This is likely a quirk of bitcoind 0.20.99 issuing `SendAddrV2Message` outside of the version handshake envelope.

See https://github.com/bitcoin/bitcoin/pull/20564 which was released in 0.21.0

BitcoinJ  expects it only within the verack envelope:
https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/core/Peer.java#L459-L464

Solution would be to upgrade to a newer version of bitcoin core, especially as **0.20.99** is not an official release.
