### ISSUE TITLE
Trade is in an invalid state - please help, cant continue to accept the payment!

### ISSUE THREAD

**Issue by bbtst** [bisq-network/bisq#6503]
Trade ID: Db6eL-9c61df1a-996f-4b47-a82b-e155dc854d95-198

we were using the integrated chat window while trying to finish the trade and it fell into invalid state

![image](https://user-images.githubusercontent.com/122027302/210786925-946aa6a5-4032-4249-8c14-8d99926f0b45.png)

`Error: An error occurred at task: SellerSendPayoutTxPublishedMessage
Exception message: Not able to find peers witness, unable to sign for trade`

after i close the "Attention" window there is this another error message 
![image](https://user-images.githubusercontent.com/122027302/210787128-745291e7-76b5-4936-8f8b-4e7910cd27e5.png)

Please help us proceed with this trade,
 thank you.

**Comment by ghost** [comment]
That step is after payout has been made, please check your bisq wallet to see the payout transaction.

(Funds -> Transactions).

**Comment by 996f** [comment]
im a taker of this tx and it seems it's "stuck" somewhere

going into funds -> transactions shows that I had received my BTC, but in Receive funds tab, there are no funds available, nor is the depost

**Comment by ghost** [comment]
Glad you received your BTC, have you checked the Send funds tab?

**Comment by 996f** [comment]
yep, seems to be in order, however part of the deposit sits with released funds from the maker and small portion is in some other address...kind of confusing, or maybe should be like that?
