### ISSUE TITLE
Warning when building on Mac OSX

### ISSUE THREAD

**Issue by jonathancross** [bisq-network/bisq#651]
```
Platform: Mac OSX 10.11.6
JDK: Oracle JDK 8 version 8u102 (1.8.0_102)
```

I am trying to build from master on Mac OSX but am getting errors / warnings on startup / shutdown.
I have [tested that strong crypto support is enabled](https://github.com/jonathancross/jc-docs/tree/master/java-strong-crypto-test), checked Bouncy Castle was added in `java.security`, etc.

The app loads and **_appears_** to function properly, but I still get this warning on startup:
- WARN  i.b.c.u.Utilities: Failed to remove cryptography restrictions java.lang.IllegalAccessException: Can not set static final boolean field javax.crypto.JceSecurity.isRestricted to java.lang.Boolean

I get 10 bitcoin peers + 8 Tor peers despite the warning (and errors mentioned below), so maybe these can be ignored?

Related: #650

See complete console output attached to this issue: [console-log-errors.txt](https://github.com/bitsquare/bitsquare/files/536604/console-log-errors.txt)

**Comment by ManfredKarrer** [comment]
Did you follow exactly instructions at the build.md file? Maybe you have different jdks and copied/edited on the wrong jdk? 
The cryptography restrictions need to be changes as we use strong keys. If done like in the instructions in the build file that code path should not be executed. It is just an extra care if people dont follow and then we try via reflection, but I think that does not work reliable on all systems.

**Comment by jonathancross** [comment]
> Did you follow exactly instructions at the build.md file?

I can double check the instructions and try again from scratch,  will report back tomorrow.

> different jdks and copied/edited on the wrong jdk

`JAVA_HOME` does seem to work in a different way on the Mac.  This is why I created this simple test: https://github.com/jonathancross/jc-docs/tree/master/java-strong-crypto-test to be sure that larger keys were supported.

**Comment by ManfredKarrer** [comment]
Hav you checked if java-version reports your jdk and if echo JAVA_HOME points to your right jdk?

**Comment by jonathancross** [comment]
Yes, I checked those:

```
java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

which java
/usr/bin/java

readlink `which java`
/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java

/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home

/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

Also checked the installed jars:

```
ls -o  $JAVA_HOME/jre/lib/security/{US_export_policy.jar,local_policy.jar} $JAVA_HOME/jre/lib/ext/{bcprov-jdk15on-1.53.jar,jdkfix-0.4.9.6.jar}
-rw-rw-r--  1 root  3259402 Oct 18 03:14 /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/ext/bcprov-jdk15on-1.53.jar
-rw-rw-r--  1 root     9774 Oct 18 23:23 /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/ext/jdkfix-0.4.9.6.jar
-rw-rw-r--@ 1 root     3023 Oct 18 02:46 /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/security/US_export_policy.jar
-rw-rw-r--@ 1 root     3035 Oct 18 02:46 /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/security/local_policy.jar
```

**Comment by haiqu** [comment]
Try looking in `$JAVA_HOME/jdk` instead. :) See #653

**Comment by ManfredKarrer** [comment]
Is it still a problem with the latest code?

**Comment by jonathancross** [comment]
No errors anymore after rebuilding everything from source.
Cheers!
