### ISSUE TITLE
Bisq application window appears off screen (Windows 10)

### ISSUE THREAD

**Issue by alexander-nolan** [bisq-network/bisq#6511]
### Description

When trying to open bisq, the application opens, but it is not visible on screen and there is no way to access the application. Alt + Tab allows me to see and select the window, but it doesn't open.

I have uninstalled, deleted the AppData/Local/Bisq Directory, deleted the Bisq reg key under HKEY_CURRENT_USER/SOFTWARE and reinstalled multiple times, and a couple of different versions and I still can't get the application to open.

#### Version

1.9.8

### Steps to reproduce

Install Bisq and open it

### Expected behaviour

Opening the application opens a window and allows me to use the application

### Actual behaviour

Opening the application doesn't allow me to access the application window

#### Device or machine

Dell XPS 9560 | Windows 10.0.19044 Build 19044

**Comment by ghost** [comment]
Run it maximized.
https://github.com/bisq-network/bisq/issues/5648#issuecomment-942695883
https://bisq.wiki/Troubleshooting#Bisq_app_appears_in_taskbar.2C_but_clicking_it_opens_a_blank_window

**Comment by harajuker** [comment]
Just happened to me. None of the suggestions worked, but what did work was hitting twice Windows logo key + D

**Comment by l-ika-l** [comment]
Happened to me, tried running maximized and windows logo + D key, didn't work
