### ISSUE TITLE
Error appearing on my Bisq application , help.

### ISSUE THREAD

**Issue by yusuf1670** [bisq-network/bisq#6512]
### Description
spontaneously appears periodically on my computer, now idea why?

#### Version

the meassage said to attach the log file, here is the copy of it.

### Screenshots

<img width="1024" alt="Screenshot 2023-01-08 at 9 26 22 AM" src="https://user-images.githubusercontent.com/122222850/211208503-a557f90a-9b26-4d0e-88b8-52ae80a5cdb6.png">

**Comment by ghost** [comment]
Please let us know if the problem still happens in the [latest Bisq release](https://github.com/bisq-network/bisq/releases), v1.9.9.

**TrustedListenableFutureTask error.**  Tracked in issue [6480](https://github.com/bisq-network/bisq/issues/6480).  Latest [comment.](https://github.com/bisq-network/bisq/issues/6480#issuecomment-1366877455)
