### ISSUE TITLE
Bisq Error

### ISSUE THREAD

**Issue by pfergi42** [bisq-network/bisq#6516]
I can't run or upgrade Bisq:

![Screenshot 2023-01-10 at 9 49 48 AM](https://user-images.githubusercontent.com/4021240/211625464-86ea9f75-c8bd-4096-99ac-403be08ba58c.png)

**Comment by ghost** [comment]
Duplicate of https://github.com/bisq-network/bisq/discussions/6492 and https://github.com/bisq-network/bisq/issues/6401
