### ISSUE TITLE
Translation UI Spanish - Sell / Other / Price & Amount

### ISSUE THREAD

**Issue by vlc33** [bisq-network/bisq#6524]
### Description

UI Spanish translation

Hello, in Sell / Other / Fix Price & Amount the labels in Spanish translation are buggus:

Cantidad en BTC a recibir    (this seems OK)    [alternatively 'comprar' not 'recibir']
Cantidad en [crypto] a recibir    (I think this sould be ' Cantidad en [crypto] a enviar ' )   [alternatively 'gastar' not 'recibir' nor ('enviar')]

Note:
In Buy / Other / Fix Price & Amount the labels in Spanish translation are:
Cantidad en BTC a gastar    (amount in BTC to spend)
Cantidad en [crypto] a comprar    (amount in [crypto] to buy)

#### Version

1.9.9 B

### Screenshots

![Sell Oher amount_price labels ES](https://user-images.githubusercontent.com/43541146/212734063-04699205-2c3f-48be-9467-b5fcb9a55816.PNG)

**Comment by ghost** [comment]
@MwithM could you check the translations.
A buy from BTC perspective is a sell of Altcoin.

displayStrings.properties: (correct)
`
createOffer.amountPriceBox.buy.volumeDescriptionAltcoin=Amount in {0} to sell
createOffer.amountPriceBox.sell.volumeDescriptionAltcoin=Amount in {0} to buy
`

displayStrings_es.properties: (incorrect)
`
createOffer.amountPriceBox.buy.volumeDescriptionAltcoin=Cantidad en {0} a recibir
createOffer.amountPriceBox.sell.volumeDescriptionAltcoin=Cantidad en {0} a comprar
`

**Comment by MwithM** [comment]
I think it's fine now on transifex.

![image](https://user-images.githubusercontent.com/50149324/212778088-848987e2-7436-4ee7-b061-5409c4f0bb3f.png)

**Comment by ghost** [comment]
@bisq-network/bisq-maintainers   :point_up:

**Comment by vlc33** [comment]
Let me point the different semantic fields we are managing and its correct translation to Spanish es_es

[A]  Send / Receive  -  Enviar / Recibir
[B] Buy / Sell - Comprar / Vender
[C] Spend / Save or Earn  - Gastar / Ingresar

**Comment by ripcurlx** [comment]
> Let me point the different semantic fields we are managing and its correct translation to Spanish es_es
> 
> [A] Send / Receive - Enviar / Recibir [B] Buy / Sell - Comprar / Vender [C] Spend / Save or Earn - Gastar / Ingresar

@MwithM Did you have a look at those as well? Thanks!

**Comment by MwithM** [comment]
I would need specific examples,  I would say that in general they're correct.
The first change suggested on the first post (the one I took a screenshot for transifex) was very necessary though.
