### ISSUE TITLE
Java fails strong crypto test in Windows

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#653]
After seeing Jonathan's issues in #651 I decided to test the strong encryption installed as part of the setup, per https://github.com/jonathancross/jc-docs/blob/master/java-strong-crypto-test/README.md

It failed. :(

I did set this up correctly when I first installed the source, and as a double-check I d/l'ed the files again from Oracle. Same result.

Note that I have no way to test the SHA256 of the file but it's coming straight from Oracle via `wget` so unlikely to be the files.

**Comment by haiqu** [comment]
Found the problem. `Java/jdk` and `Java/jre` both have a `lib/security` subdirectory. You have to copy over these files in BOTH of them.

**Comment by jonathancross** [comment]
Cool, you are the first person to make use of that test class :-)

@haiqu  Feel free to add information about Windows and submit a PR if you like.

**Comment by haiqu** [comment]
Submitted #654 to Manfred but if that page is referenced by something else you could include the data there as well.  See https://github.com/bitsquare/bitsquare/pull/654/commits/62661212f2df71eab6f6cd1e7a9d25361faf2cdc

**Comment by jonathancross** [comment]
Thanks.
Did you install the JRE in addition to the JDK perhaps?

**Comment by haiqu** [comment]
JDK comes with the JRE as a separate directory on Windows.

BTW I just d/l'ed jdk1.8.0_112 today and it seems as if the sortedlist class has been fixed. We can do without jdkfix now!

But you still need to upgrade the security, that won't be available until Java 9.
