### ISSUE TITLE
Trade Init: failures due to buyer's payment info not published

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#6530]
### Description

There is a timing issue whereby the trade init stage is delayed due to Tor and the payment info does not get shared.  Causes a bugged trade, requiring mediator assisted manual payout.

#### Version

v1.9.9 (and earlier)

### Steps to reproduce

- Bob makes a sell BTC offer.
- Alice takes the offer.
- Trade init creates, signs deposit & DPT txs which are sent to Bob and published. (Phase "DEPOSIT_PUBLISHED").
- Bob's reply of `DepositTxAndDelayedPayoutTxMessage` does not yet reach Alice due to Tor -- it is required for Alice to publish the payment acct info.
- Meanwhile the deposit Tx confirms, transitioning the trade to Phase "DEPOSIT_CONFIRMED".
- Alice clicks on the trade in Portfolio/Pending Trades and gets the error `ERROR b.d.m.p.p.s.b.BuyerStep2View: Not supported PaymentMethod: ` [BLANK]
- Alice receives `DepositTxAndDelayedPayoutTxMessage`.  Normally this would have been the trigger to share the payment details but is ignored as the trade is in phase DEPOSIT_CONFIRMED.  Error message `We received a DepositTxAndDelayedPayoutTxMessage but we are are not in the expected phase.`
- Alice or Bob opens mediation.

### Expected behaviour

Perhaps BuyerSendsShareBuyerPaymentAccountMessage can also be triggered from BUYER_SAW_DEPOSIT_TX_IN_NETWORK.

### Actual behaviour

The trade throws an error, payment details are not present, mediation is opened and a manual payout has to be arranged by mediator.

#### Additional info
    Jan-13 19:37:47.056 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: SendOfferAvailabilityRequest 
    Jan-13 19:37:47.056 [JavaFX Application Thread] INFO  b.c.o.a.t.SendOfferAvailabilityRequest: Send OfferAvailabilityRequest with offerId 9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 and uid 71f19e52-5d93-4195-bf73-6017ac68a5e7 to peer bob.onion:9999 
    Jan-13 19:37:47.059 [JavaFX Application Thread] INFO  b.c.o.a.t.SendOfferAvailabilityRequest: OfferAvailabilityRequest arrived at peer: offerId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199; uid=71f19e52-5d93-4195-bf73-6017ac68a5e7 
    Jan-13 19:37:48.380 [JavaFX Application Thread] INFO  b.c.o.a.OfferAvailabilityProtocol: Received handleOfferAvailabilityResponse from bob.onion:9999 with offerId 9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 and uid 7707adc2-99dd-4d68-84dd-eb9ebec838a2 
    Jan-13 19:37:48.380 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: ProcessOfferAvailabilityResponse 
    Jan-13 19:37:48.380 [JavaFX Application Thread] INFO  b.c.o.a.OfferAvailabilityProtocol: Send AckMessage for OfferAvailabilityResponse to peer bob.onion:9999 with offerId 9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 and sourceUid 7707adc2-99dd-4d68-84dd-eb9ebec838a2 
    Jan-13 19:37:48.385 [JavaFX Application Thread] INFO  b.c.n.a.TradeEvents: We got a new trade. id=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 
    Jan-13 19:37:48.390 [JavaFX Application Thread] INFO  b.c.t.p.FluentProtocol$Condition: We received a TAKE_OFFER event at phase INIT and state PREPARATION, tradeId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 
    Jan-13 19:37:48.390 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: CheckIfDaoStateIsInSync 
    Jan-13 19:37:48.390 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: ApplyFilter 
    Jan-13 19:37:48.391 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: TakerVerifyMakerFeePayment 
    Jan-13 19:37:48.391 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: CreateTakerFeeTx 
    Jan-13 19:37:48.454 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: BuyerAsTakerCreatesDepositTxInputs 
    Jan-13 19:37:48.455 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: TakerSendInputsForDepositTxRequest 
    Jan-13 19:37:48.456 [JavaFX Application Thread] INFO  b.c.t.p.b.t.t.TakerSendInputsForDepositTxRequest: Send InputsForDepositTxRequest with offerId 9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 and uid 9091d823-5970-4052-b3d1-7cf8f7c26e4d to peer bob.onion:9999 
    Jan-13 19:37:48.478 [JavaFX Application Thread] INFO  b.c.o.a.OfferAvailabilityProtocol: AckMessage for OfferAvailabilityResponse arrived at makersNodeAddress bob.onion:9999. offerId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199, sourceUid=7707adc2-99dd-4d68-84dd-eb9ebec838a2 
    Jan-13 19:37:48.479 [JavaFX Application Thread] INFO  b.c.t.p.b.t.t.TakerSendInputsForDepositTxRequest: InputsForDepositTxRequest arrived at peer: offerId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199; uid=9091d823-5970-4052-b3d1-7cf8f7c26e4d 
    Jan-13 19:37:48.479 [JavaFX Application Thread] INFO  b.c.t.p.TradeProtocol: TaskRunner successfully completed. Triggered from TAKE_OFFER, tradeId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 
    Jan-13 19:37:48.489 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received AckMessage for OfferAvailabilityRequest with offerId 9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 and uid 71f19e52-5d93-4195-bf73-6017ac68a5e7 
    Jan-13 19:37:49.332 [JavaFX Application Thread] INFO  b.c.t.p.b.BuyerProtocol: Received InputsForDepositTxResponse from bob.onion:9999 with tradeId 9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 and uid 68634d31-fc85-48bf-a5f8-550ae2f1b884 
    Jan-13 19:37:49.334 [JavaFX Application Thread] INFO  b.c.t.p.FluentProtocol$Condition: We received a InputsForDepositTxResponse at phase INIT and state PREPARATION, tradeId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 
    Jan-13 19:37:49.334 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: TakerProcessesInputsForDepositTxResponse 
    Jan-13 19:37:49.335 [JavaFX Application Thread] INFO  b.c.t.p.b.t.t.TakerProcessesInputsForDepositTxResponse: lockTime=774699, delay=-2880 
    Jan-13 19:37:49.335 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: ApplyFilter 
    Jan-13 19:37:49.335 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: TakerVerifyAndSignContract 
    Jan-13 19:37:49.344 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: TakerPublishFeeTx 
    Jan-13 19:37:49.367 [JavaFX Application Thread] INFO  b.c.t.p.b.DisputeProtocol: Received AckMessage for InputsForDepositTxRequest from bob.onion:9999 with tradeId 9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 and uid 9091d823-5970-4052-b3d1-7cf8f7c26e4d 
    Jan-13 19:37:54.368 [JavaFX Application Thread] INFO  b.c.t.m.b.Trade: Set new state at BuyerAsTakerTrade (id=9473938): TAKER_PUBLISHED_TAKER_FEE_TX 
    Jan-13 19:37:54.368 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: BuyerAsTakerSignsDepositTx 
    Jan-13 19:37:54.369 [JavaFX Application Thread] INFO  b.c.b.w.BtcWalletService: Set coinLockedInMultiSig for addressEntry AddressEntry{address=bc1qjdgluvlf72gd5sd6g0l2qa32aag09hmufp37x6, context=MULTI_SIG, offerId='9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199', coinLockedInMultiSig=0, segwit=true} to value 100000 
    Jan-13 19:37:54.371 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: BuyerSetupDepositTxListener 
    Jan-13 19:37:54.383 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: BuyerAsTakerSendsDepositTxMessage 
    Jan-13 19:37:54.384 [JavaFX Application Thread] INFO  b.c.t.p.b.t.b.BuyerAsTakerSendsDepositTxMessage: Send DepositTxMessage to peer bob.onion:9999. tradeId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199, uid=84aa02cf-e280-47a9-96f2-81f2a7ffe8ac 
    Jan-13 19:37:54.386 [JavaFX Application Thread] INFO  b.c.t.p.b.t.b.BuyerAsTakerSendsDepositTxMessage: DepositTxMessage arrived at peer bob.onion:9999. tradeId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199, uid=84aa02cf-e280-47a9-96f2-81f2a7ffe8ac 
    Jan-13 19:37:54.386 [JavaFX Application Thread] INFO  b.c.t.p.TradeProtocol: TaskRunner successfully completed. Triggered from InputsForDepositTxResponse, tradeId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 
    Jan-13 19:37:54.386 [JavaFX Application Thread] INFO  b.c.t.p.TradeProtocol: Send AckMessage for InputsForDepositTxResponse to peer bob.onion:9999. tradeId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199, sourceUid=68634d31-fc85-48bf-a5f8-550ae2f1b884 
    Jan-13 19:37:54.439 [JavaFX Application Thread] INFO  b.c.t.p.TradeProtocol: AckMessage for InputsForDepositTxResponse arrived at peer bob.onion:9999. tradeId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199, sourceUid=68634d31-fc85-48bf-a5f8-550ae2f1b884 
    Jan-13 19:37:57.859 [JavaFX Application Thread] WARN  b.c.b.w.TxBroadcaster: We got an onSuccess callback for a broadcast which already triggered the timeout. txId=7697d4ba86232ee6b1a96f720a097f2462d6b599095c009328293651b6c50966 
    Jan-13 19:37:59.646 [JavaFX Application Thread] INFO  b.c.t.p.b.BuyerProtocol: Received DelayedPayoutTxSignatureRequest from bob.onion:9999 with tradeId 9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 and uid a77d5105-8257-40f1-941c-71c5bb5d7a54 
    Jan-13 19:37:59.647 [JavaFX Application Thread] INFO  b.c.t.p.FluentProtocol$Condition: We received a DelayedPayoutTxSignatureRequest at phase TAKER_FEE_PUBLISHED and state TAKER_PUBLISHED_TAKER_FEE_TX, tradeId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 
    Jan-13 19:37:59.647 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: BuyerProcessDelayedPayoutTxSignatureRequest 
    Jan-13 19:37:59.647 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: BuyerVerifiesPreparedDelayedPayoutTx 
    Jan-13 19:37:59.681 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: BuyerSendsDelayedPayoutTxSignatureResponse 
    Jan-13 19:37:59.682 [JavaFX Application Thread] INFO  b.c.t.p.b.t.b.BuyerSendsDelayedPayoutTxSignatureResponse: Send DelayedPayoutTxSignatureResponse to peer bob.onion:9999. tradeId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199, uid=a1d0ffbf-d512-46c1-9124-fb51f94a901a 
    Jan-13 19:37:59.687 [JavaFX Application Thread] INFO  b.c.t.p.b.DisputeProtocol: Received AckMessage for DepositTxMessage from bob.onion:9999 with tradeId 9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 and uid 84aa02cf-e280-47a9-96f2-81f2a7ffe8ac 
    Jan-13 19:37:59.687 [JavaFX Application Thread] INFO  b.c.t.p.b.t.b.BuyerSendsDelayedPayoutTxSignatureResponse: DelayedPayoutTxSignatureResponse arrived at peer bob.onion:9999. tradeId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199, uid=a1d0ffbf-d512-46c1-9124-fb51f94a901a 
    Jan-13 19:37:59.687 [JavaFX Application Thread] INFO  b.c.t.p.TradeProtocol: TaskRunner successfully completed. Triggered from DelayedPayoutTxSignatureRequest, tradeId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 
    Jan-13 19:37:59.687 [JavaFX Application Thread] INFO  b.c.t.p.TradeProtocol: Send AckMessage for DelayedPayoutTxSignatureRequest to peer bob.onion:9999. tradeId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199, sourceUid=a77d5105-8257-40f1-941c-71c5bb5d7a54 
    Jan-13 19:37:59.740 [JavaFX Application Thread] INFO  b.c.t.p.TradeProtocol: AckMessage for DelayedPayoutTxSignatureRequest arrived at peer bob.onion:9999. tradeId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199, sourceUid=a77d5105-8257-40f1-941c-71c5bb5d7a54 
    Jan-13 19:38:15.220 [JavaFX Application Thread] INFO  b.c.t.m.b.Trade: Set new state at BuyerAsTakerTrade (id=9473938): BUYER_SAW_DEPOSIT_TX_IN_NETWORK 
    Jan-13 19:38:20.465 [JavaFX Application Thread] INFO  b.d.m.p.p.PendingTradesViewModel: UI tradeState=BUYER_SAW_DEPOSIT_TX_IN_NETWORK, id=9473938 
    Jan-13 19:38:31.378 [JavaFX Application Thread] INFO  b.c.t.m.b.Trade: Set new state at BuyerAsTakerTrade (id=9473938): DEPOSIT_CONFIRMED_IN_BLOCK_CHAIN 
    Jan-13 19:38:31.378 [JavaFX Application Thread] INFO  b.d.m.p.p.PendingTradesViewModel: UI tradeState=DEPOSIT_CONFIRMED_IN_BLOCK_CHAIN, id=9473938 
    Jan-13 19:38:31.385 [JavaFX Application Thread] WARN  b.c.locale.Res: Missing resource for key:  
    Jan-13 19:38:31.385 [JavaFX Application Thread] ERROR b.d.m.p.p.s.b.BuyerStep2View: Not supported PaymentMethod:  
    Jan-13 19:38:31.386 [JavaFX Application Thread] ERROR b.d.m.p.p.TradeSubView: Creating viewClass class bisq.desktop.main.portfolio.pendingtrades.steps.buyer.BuyerStep2View caused an error null 
    Jan-13 19:38:31.390 [JavaFX Application Thread] INFO  b.c.d.n.l.LiteNode: New block at height 771820 from bsqWalletService 
    Jan-13 19:39:53.566 [JavaFX Application Thread] INFO  b.c.t.p.b.BuyerProtocol: Received DepositTxAndDelayedPayoutTxMessage from bob.onion:9999 with tradeId 9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 and uid 9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199bob.onion:9999 
    Jan-13 19:39:53.567 [JavaFX Application Thread] WARN  b.c.t.p.TradeProtocol: We received a DepositTxAndDelayedPayoutTxMessage but we are are not in the expected phase.
    This can be an expected case if we get a repeated CounterCurrencyTransferStartedMessage after we have already received one as the peer re-sends that message at each startup.
    Expected phases=[DEPOSIT_PUBLISHED, TAKER_FEE_PUBLISHED],
    Trade phase=DEPOSIT_CONFIRMED,
    Trade state= DEPOSIT_CONFIRMED_IN_BLOCK_CHAIN,
    tradeId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199 
    Jan-13 19:39:53.567 [JavaFX Application Thread] ERROR b.c.t.p.TradeProtocol: Task runner failed with error We received a DepositTxAndDelayedPayoutTxMessage but we are are not in the expected phase.
    This can be an expected case if we get a repeated CounterCurrencyTransferStartedMessage after we have already received one as the peer re-sends that message at each startup.
    Expected phases=[DEPOSIT_PUBLISHED, TAKER_FEE_PUBLISHED],
    Trade phase=DEPOSIT_CONFIRMED,
    Trade state= DEPOSIT_CONFIRMED_IN_BLOCK_CHAIN,
    tradeId=9473938-58f8f647-2c73-4f08-96e1-c3866647efec-199. Triggered from INVALID_PHASE

**Comment by pazza83** [comment]
Hi @jmacxx 

This is still happening for a couple of trades a month.

Is it worth me collecting logs from the buyer and seller for these affected trades?

**Comment by gustavoastorres** [comment]
Hi. I am having a similar problem:
![image](https://github.com/bisq-network/bisq/assets/7401039/2552d2ae-2e90-4ea5-b009-44f590a53b4d)
