### ISSUE TITLE
PGP Verification Not Working

### ISSUE THREAD

**Issue by valiantgenomics** [bisq-network/bisq#6532]
When trying to verify the PGP keys using the official bisq PGP instructions:

`gpg --digest-algo SHA512 --verify Bisq-64bit-1.9.9.deb{.asc*,}`

I get this error:

`gpg: verify signatures failed: Unexpected error`

And yes, I've already imported the public key.

Any help will be highly appreciated!

My system is:
Linux Pop!_OS 22.04 LTS x86_64

**Comment by MwithM** [comment]
What signature have you imported? It recently changed, and it's `E222AA02` as you can see in the release notes.
https://github.com/bisq-network/bisq/releases/tag/v1.9.9

**Comment by valiantgenomics** [comment]
> What signature have you imported? It recently changed, and it's `E222AA02` as you can see in the release notes. https://github.com/bisq-network/bisq/releases/tag/v1.9.9

Thanks for the reply! Yes, this is exactly what I've imported, here's a screenshot of my files:

![image](https://user-images.githubusercontent.com/111633318/213968088-d9b6b26a-a002-4180-9c7b-a3241d87484e.png)

**Comment by MwithM** [comment]
Try `gpg --verify Bisq-64bit-1.9.9.deb.asc`

**Comment by valiantgenomics** [comment]
> gpg --verify Bisq-64bit-1.9.9.deb.asc

Thanks for the reply, I just tried it, didn't work. Same error:

`gpg: verify signatures failed: Unexpected error`

I don't understand why this is happening. Feel like it's an issue with the PGP key itself.

**Comment by valiantgenomics** [comment]
Just bumping this. Is anyone able to PGP verify their Bisq download?

**Comment by ghost** [comment]
Yes, I just followed the instructions at https://github.com/bisq-network/bisq/releases and it worked.


    $ curl https://bisq.network/pubkey/E222AA02.asc | gpg --import
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  3167    0  3167    0     0   3908      0 --:--:-- --:--:-- --:--:--  3905
    gpg: key E222AA02: public key "Alejandro García <alejandro.garcia@disroot.org>" imported
    gpg: Total number processed: 1
    gpg:               imported: 1  (RSA: 1)

    $ gpg --digest-algo SHA256 --verify Bisq-64bit-1.9.9.deb{.asc*,}
    gpg: Signature made Sat 07 Jan 2023 08:30:13 AM CST using RSA key ID E222AA02
    gpg: Good signature from "Alejandro García <alejandro.garcia@disroot.org>"
    gpg: WARNING: This key is not certified with a trusted signature!
    gpg:          There is no indication that the signature belongs to the owner.
    Primary key fingerprint: B493 3191 06CC 3D1F 252E  19CB F806 F422 E222 AA02

**Comment by valiantgenomics** [comment]
@jmacxx Thanks a lot for doing that!

I just tried again, and the issue still persists on my end.

But at least now I know, it seems to be distro-specific. What OS are you running?

I did get some output by just typing:

`gpg Bisq-64bit-1.9.9.deb.asc`

And this is the output I got:

```
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa4096 2022-09-28 [SC] [expires: 2024-09-27]
      B493319106CC3D1F252E19CBF806F422E222AA02
uid           Alejandro García <alejandro.garcia@disroot.org>
sub   rsa4096 2022-09-28 [E] [expires: 2024-09-27]
```

I got the idea from here: https://groups.google.com/g/alt.security.pgp/c/8JHBFearPPM

**Comment by jomz** [comment]
Chiming in here: something about the {asc*,} from the instructions is not working as expected at least on my Ubuntu 22.04;

 jomz@desktop ~/Downloads > gpg --digest-algo SHA256 --verify Bisq-64bit-1.9.9.deb{.asc*,}
gpg: Signature made Sat 07 Jan 2023 15:30:13 CET
gpg:                using RSA key B493319106CC3D1F252E19CBF806F422E222AA02
gpg:                issuer "alejandro.garcia@disroot.org"
gpg: BAD signature from "Alejandro García <alejandro.garcia@disroot.org>" [unknown]

Changing  that to filename.deb.asc filename.deb, I dó get 'Good signature':

 jomz@desktop ~/Downloads  > gpg --digest-algo SHA256 --verify Bisq-64bit-1.9.9.deb.asc Bisq-64bit-1.9.9.deb
gpg: Signature made Sat 07 Jan 2023 15:30:13 CET
gpg:                using RSA key B493319106CC3D1F252E19CBF806F422E222AA02
gpg:                issuer "alejandro.garcia@disroot.org"
gpg: Good signature from "Alejandro García <alejandro.garcia@disroot.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: B493 3191 06CC 3D1F 252E  19CB F806 F422 E222 AA02

**Comment by jomz** [comment]
Adding to this, though it might actually be a separate issue: on my system (Ubuntu 22.04 with currently Bisq 1.9.6), the built-in install files -signature checker was failing as well. I assume this also uses the {.asc*,} under the hood?

Another possible explanation I guess is that the 5BC5ED73 and 29CDFD3B signature files have been replaced by the E222AA02 one, but 1.9.6 still tries to verify with the old signatures...
