### ISSUE TITLE
Scene not available yet, we create a new scene. The bug might be caused by an exception in a constructor or by a circular dependency in guice. 

### ISSUE THREAD

**Issue by Veek** [bisq-network/bisq#655]
```
veek@deathstar:~$ /opt/Bitsquare/Bitsquare 
Oct-19 14:19:10.612 [JavaFX Application Thread] INFO  i.b.a.BitsquareApp: Log files under: /home/veek/.local/share/Bitsquare/bitsquare 
Oct-19 14:19:10.620 [JavaFX Application Thread] INFO  i.b.app.Version: Version{VERSION=0.4.9.6, P2P_NETWORK_VERSION=4, LOCAL_DB_VERSION=4, TRADE_PROTOCOL_VERSION=1, BTC_NETWORK_ID=0, getP2PNetworkId()=0} 
Oct-19 14:19:10.621 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.name: Linux 
Oct-19 14:19:10.622 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.version: 3.16.0-4-amd64 
Oct-19 14:19:10.622 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.arch: amd64 
Oct-19 14:19:10.622 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: sun.arch.data.model: 64 
Oct-19 14:19:10.622 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JRE: 1.8.0_66-b17 (Oracle Corporation) 
Oct-19 14:19:10.623 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JVM: 25.66-b17 (Java HotSpot(TM) 64-Bit Server VM) 
Oct-19 14:19:11.931 [JavaFX Application Thread] WARN  i.b.a.BitsquareApp: Scene not available yet, we create a new scene. The bug might be caused by an exception in a constructor or by a circular dependency in guice. 
```

I get a blank screen: http://pix.toile-libre.org/upload/original/1476867213.png

**Comment by ManfredKarrer** [comment]
Can you send me the full logs? Do u rund from source or the binary? Do u use the latest version?

**Comment by Veek** [comment]
Bitsquare-64bit-0.4.9.6.deb (on debian+olvwm window-manager)

 /opt/Bitsquare/Bitsquare --logLevel ALL >/tmp/dbg

[dbg.txt](https://github.com/bitsquare/bitsquare/files/538696/dbg.txt)

**Comment by ManfredKarrer** [comment]
Do u run form source code? If so did u follow all instructions in the build.md file?
If not I fear thats some strange system related issue. never saw that before.

**Comment by pabpas** [comment]
Getting the same error running Debian Stretch plus a bunch of:

[JavaFX Application Thread] ERROR i.b.c.c.KeyStorage: encoded key spec not recognised

**Comment by ManfredKarrer** [comment]
Do u run form src doe? If so, did u follow exact all the steps in the build.md file? Sounds like BouncyCastle is not copied over.

**Comment by Veek** [comment]
no i haven't used the src - it's a .deb file (from website)

**Comment by ManfredKarrer** [comment]
Have u used the latest binary (0.4.9.7)? Maybe its an issue with the graphic system on your OS? JavaFX has some issues with non standard desktops or graphic systems on linux.

**Comment by Veek** [comment]
I'm using a Core-2 duo GM45 graphics (laptop)- i tried git compile but it asked to download the bitcoinj lib and that failed so i gave up - i know nothing about java..

**Comment by ManfredKarrer** [comment]
If you want to compile form source you need to follow exactly all steps here and use the latest Oracle JDK.
https://github.com/bitsquare/bitsquare/blob/master/doc/build.md

Here are handy install scrips snippets:
https://github.com/bitsquare/bitsquare/blob/master/doc/install_on_unix.sh
https://github.com/bitsquare/bitsquare/blob/master/doc/install_on_unix_fin.sh

**Comment by pabpas** [comment]
I have just tried running from source and I get the same errors. Some things that I noticed when following the instructions:
- Latest java version in Debian testing is openjdk 1.8.0_102 (1.8.0_112 is the minimum according to build.md)
- To build bitcoinj the package openjfx is needed but only libopenjfx-java is mentioned in the requirements.
- Is Oracle JDK mandatory?

**Comment by Veek** [comment]
buggy script:

```
Err http://ppa.launchpad.net jessie/main amd64 Packages                                                  
  404  Not Found
```

Because /etc/apt/sources.list.d/webupd8team-java-jessie.list
deb http://ppa.launchpad.net/webupd8team/java/ubuntu jessie main

there's no 'jessie' in ubuntu.. so.. you get:
cp: cannot create regular file ‘/usr/lib/jvm/java-8-oracle/jre/lib/security/US_export_policy.jar’: No such file or directory

**Comment by Veek** [comment]
I'm running debian stable so..  it's always fairly old - the pkgs

```
deathstar> java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by ManfredKarrer** [comment]
@pabpas The v112 was just released a few days ago. For OpenJDk it takes usually a bit that they support the latest version. There was one bugfix in that latest jdk but it is not s super critical one (offerlist sometimes get screwed up by a bug in SorteList in older versions).
So I recommend to use Oracle jdk or update jdk as sson openJdk is up to date.

**Comment by ManfredKarrer** [comment]
@Veek Could u make a PR for Debian? I have only a Ubuntu VM set up yet, so I cannot test the setup on Debian.

**Comment by pabpas** [comment]
I have tried to run it using OracleJDK only to find out that it is a permission problem. Not sure what but the program runs fine as root.

**Comment by pabpas** [comment]
So I finally got it working by deleting the user config folder.
I don't know what was missing in the beginning but maybe this helps others to fix it. With openjdk btw.

EDIT from Manfred Karrer:
Be careful with that!
".local/share/Bitsquare/" is the data directory with the wallet. If you have already BTC there and no backup your wallet is gone!!!

**Comment by ManfredKarrer** [comment]
Be careful there is the data directory with the wallet. If you have already BTC there and no backup your wallet is gone!! I will edit in your post so other users dont just run that command without knowing what they do....
