### ISSUE TITLE
failed trade please remove

### ISSUE THREAD

**Issue by derekellison** [bisq-network/bisq#6553]
### Description

Failed trade: GKHIldB-f24cd33a-1369-410e-bf2f-e83f8187ae18-199
Please delete trade so that I can try again thanks

#### Version

v1.9.9

### Steps to reproduce

attempted trade when part of my BTC hadn't had enough confirmations

### Expected behaviour

would be warned that trade could not commence because not all the BTC had enough confirmations

### Actual behaviour

trade failed and cannot be removed or re-opened

#### Device or machine

Windows 10 PC

**Comment by MwithM** [comment]
https://bisq.community/t/failed-trades-and-deposit-tx-not-confirmed-troubleshoot-v1-5-4/10223/1

You need to move a failed trade to the failed trade yourself.

**Comment by derekellison** [comment]
It is already in the Portfolio -> Failed section. However the circular arrow to move it back to open trade doesn't work. So I need this trade deleted so that I can attempt to trade again thanks

**Comment by pazza83** [comment]
@derekellison 

Can you explain what about the trade being in failed trades is stopping you from trading again?

Are BTC funds from this trade showing in your reserved or locked funds? If so an SPV resync will fix this: https://bisq.wiki/Resyncing_SPV_file
