### ISSUE TITLE
java.util.ConcurrentModificationException error

### ISSUE THREAD

**Issue by Moty28** [bisq-network/bisq#6555]
An error message called "java.util.ConcurrentModificationException" appeared just after completing a transaction.
The log file is attached.
[bisq_log.txt](https://github.com/bisq-network/bisq/files/10610430/bisq_log.txt)

**Comment by ghost** [comment]
Fixed by #6551

**Comment by ripcurlx** [comment]
Closing as complete by https://github.com/bisq-network/bisq/issues/6555#issue-1571299095.
