### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by supportluckysol** [bisq-network/bisq#6571]
### Description

I attached the Log file and everything I know about it down below

#### Version

v1.9.9

### Expected behaviour

Expected to be able to send a security deposit to open an order.

### Actual behaviour

was about to send security deposit for an order when error window populated

#### Device or machine

Windows current build

#### Additional info

[bisq.log](https://github.com/bisq-network/bisq/files/10702069/bisq.log)

**Comment by ghost** [comment]
Fixed by #6551 - will be in next release.

**Comment by supportluckysol** [comment]
No problem :)
