### ISSUE TITLE
Trade Contract not set on my screen

### ISSUE THREAD

**Issue by Scoop193** [bisq-network/bisq#6573]
![Screenshot (3)](https://user-images.githubusercontent.com/77167690/218149908-bce33b8d-ad4b-4d1a-99eb-0d6531997eaa.png)
![Screenshot (4)](https://user-images.githubusercontent.com/77167690/218149951-f44671ef-716c-4dfd-8df0-db0251047f3f.png)

**Comment by ghost** [comment]
Please complete the ticket you opened in https://github.com/bisq-network/support/issues/1337
