### ISSUE TITLE
Disable `Filter by payment method` for altcoin sales

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#659]
In the Sell and Buy views, if I'm looking at Altcoins there should be no way to use the dropbox for payment methods, since this only relates to fiat currencies. Since we currently only allow purchase of bitcoin with fiat, the box should therefore be blanked or disabled in that situation.

**Comment by ManfredKarrer** [comment]
Agree. Maybe I squeeze it in, but prob. for the next version....

**Comment by haiqu** [comment]
Don't delay v0.4.9.7 for that little issue. I'm just posting this stuff as I find it.

**Comment by haiqu** [comment]
Additional thought: If `Show All` is not selected, it should be selected before disabling the button.

**Comment by Piste** [comment]
Should assign a version/roadmap to this issue? @ManfredKarrer
