### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by richardalg** [bisq-network/bisq#6594]
#### Version

bisq ver 1.9.9
running on Raspberry Pi4 8Gb 

### Steps to reproduce

first time occurrence see line 7047 in attached file

### Expected behaviour

shutdown was initiated

### Actual behaviour

messgage appeared requesting a report to github

### Screenshots

none

#### Device or machine

Raspberry Pi4 8Gb
Bisq built on Debian : Bullseye according to 
https://gist.github.com/tmakerman/ee53a94c3cfc8362192ad9df20709547

#### Additional info
[bisq.log](https://github.com/bisq-network/bisq/files/10851576/bisq.log)

**Comment by ghost** [comment]
Same as https://github.com/bisq-network/bisq/issues/6545

**Comment by ripcurlx** [comment]
Closing based on https://github.com/bisq-network/bisq/issues/6594#issuecomment-1458172737
