### ISSUE TITLE
[Feature Request] Ability to restrict an Amazon eGift Card trade to a specific country

### ISSUE THREAD

**Issue by roquefort-sur-soulzon** [bisq-network/bisq#6595]
Hello,

Considering Amazon's per-country gift card restriction policy, would it be possible to allow traders to specify a country when making an offer ?
Even though you can create gift cards on the different amazon websites, one may want to stay on their region and/or buy cards from physical stores with cash for even better privacy.

Best regards.

**Comment by pazza83** [comment]
Hi @roquefort-sur-soulzon 

Thanks for the issue.

Agreed it is a problem and has lead to a few cancelled trades at mediation.

Can you let me know a little more about Amazon's per-country gift card restriction policy.

When the payment method was first introduced you could buy payment cards in any currency Amazon offered them on by logging in to your Amazon account by changing the top level domain (.com / .co.uk / etc). Is this now not the case?

Also if you were to restrict an Amazon eGift Card to s specific country on the EUR market, where I am guessing this issue comes from, how would you think it should be done?

**Comment by roquefort-sur-soulzon** [comment]
Hi @pazza83 

Thanks for taking this up.

For example on amazon.fr, this is specified [in the very first line of the T&C](https://www.amazon.fr/gp/help/customer/display.html?nodeId=GNG9PXYZUMQT72QK).

It's still possible but it defeats the purpose of this payment method to be fully private/non-KYC'd, as you need an amazon account with a credit card to purchase it.
You are not directly KYC'd but it leaves a trail. A government agency could match your btc transactions with bisq peers to the gift card transactions between amazon accounts after getting data from amazon.
That is why it's better to purchase gift cards from physical stores affiliated to Amazon with cash.

As for how this should be done, I'm not an active developer of the project so I may not have the best advice, but I don't think you need a complex setup. It can just be indicative. When I look at active offers I can see this is already done with other payments methods like SEPA, Cash Deposit, F2F, Bizum, etc.

**Comment by pazza83** [comment]
> That is why it's better to purchase gift cards from physical stores affiliated to Amazon with cash.

Whilst this is better for privacy it presents a fraud risk as both the buyer and seller will have access at some point to the voucher code should they wish. In the case of a dispute it is not possible to ascertain who redeemed the funds buyer or seller.

The Amazon.com eGift Card whilst requiring a credit or debit card purchase (less private) does remove the risk of who redeemed the funds as only the receiver sees the voucher code.

I think the best solution is still for the BTC seller to inform the BTC buyer which country (eg www.amazon.es, www.amazon.de, www.amazon.fr) they would like to receive the gift card in. The BTC buyer can they log into their Amazon account of the associated Amazon country website and purchase the gift card.

**Comment by roquefort-sur-soulzon** [comment]
Thanks for the clarification, that makes sense.
I guess there is still face to face and cash by mail should we need more privacy.

**Comment by pazza83** [comment]
This has now been addressed with https://github.com/bisq-network/bisq/pull/6777
