### ISSUE TITLE
can't open my bisq app problem with TOR

### ISSUE THREAD

**Issue by swidgen** [bisq-network/bisq#6596]
everytime I try to open Bisq on startup it takes me to a page that says it can not connect to tor.  there is a button to delete old tor files then various options to try using bridges and suggests I may be in a country that restricts tor.

I am not in a country that restricts tor so I have no idea why this problem persists.  I've tried deleting the old tor files but this has not helped
I am using the latest version (i think) 1.9.9 and I'm on mac OS.  how can I access my bisq account?

**Comment by swidgen** [comment]
deleted tor file. i think explination is in the wiki

**Comment by pazza83** [comment]
Hi @swidgen, is this now resolved?
