### ISSUE TITLE
Installer doesn't remove jdkfix jar file

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#660]
Just checked my installation after v0.4.9.7 was installed. The jdkfix file was still present and it was in use by Bitsquare (because I tried to delete it and the system wouldn't allow that until I closed the program).

Install script needs to check for jdkfix*.jar and delete the file.

**Comment by ManfredKarrer** [comment]
If u install new jdk and set it as defualt in java home u can delete the old jdk and so the file

**Comment by haiqu** [comment]
This copy was in my Bitsquare install directory. I don't remember putting it there but i might have.

**Comment by ManfredKarrer** [comment]
The windows installer just add files. But the old jdkfix should nto do any harm as it is exact the same class and I removed the flag to use it.
