### ISSUE TITLE
Bad Signature for Ubuntu installation

### ISSUE THREAD

**Issue by nondiremanuell** [bisq-network/bisq#6606]
### Description

I get the following error message trying to verify the installer file:

- gpg --verify Bisq-64bit-1.9.9.deb.asc 
gpg: presupponendo i dati firmati in 'Bisq-64bit-1.9.9.deb'
gpg: Firma effettuata sab 7 gen 2023, 15:30:13 CET
gpg:                utilizzando la chiave RSA B493319106CC3D1F252E19CBF806F422E222AA02
gpg:                autorità emittente "alejandro.garcia@disroot.org"
gpg: Firma BAD da "Alejandro García <alejandro.garcia@disroot.org>" [sconosciuto]

Consider that when I download the .deb and .asc files from your website I get the following files:

-rw-r--r-- 1 nondiremanuel nondiremanuel        0 mar 16 09:36 Bisq-64bit-1.9.9.deb
-rw-rw-r-- 1 nondiremanuel nondiremanuel      874 mar 16 09:36 Bisq-64bit-1.9.9.deb.asc
-rw------- 1 nondiremanuel nondiremanuel 89128330 mar 16 09:37 Bisq-64bit-1.ligg-9MO.9.9.deb.part

and I don't know what the ".part" file is

#### Version

1.9.9

It is very likely that I'm missing some steps or something, so I apologize in advance. Best regards,
Manuel

**Comment by jomz** [comment]
I thínk the .part file means that the .deb download was still busy or for some reason failed to complete.
What I think are file sizes before the dates seem to confirm this.
It would be expected then that verifying the file signature fails...

@nondiremanuel please try downloading the .deb and .deb.asc anew?

**Comment by nondiremanuell** [comment]
> I thínk the .part file means that the .deb download was still busy or for some reason failed to complete. What I think are file sizes before the dates seem to confirm this. It would be expected then that verifying the file signature fails...
> 
> @nondiremanuel please try downloading the .deb and .deb.asc anew?

You are right, that was the issue, probably due to slow connectivity. Sorry for the inconvenience and thanks for your support.
