### ISSUE TITLE
BUG: Create offer dialog stops with Review button disabled

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#661]
Just sold some BTC so I created a new offer. After funding the offer I dismissed the notification popup and found that I could not continue to the Review stage because the button was disabled. I canceled the transaction and did it all again and this time it worked. The only difference is that I waited for the popup to vanish by itself the second time.

No funds were lost.

**Comment by haiqu** [comment]
This is _not_ related to dismissing the popup. I just had it happen again when I waited for the popup to vanish.

**Comment by Piste** [comment]
@haiqu are you able to reproduce this issue in a recent version? Would you say we try to push on or we can close this issue?

**Comment by haiqu** [comment]
Sorry, haven't been trading lately so can't follow up on this.

**Comment by martaGonz** [comment]
This happened to me too, the "Review" button was disabled but was fixed automatically 3 or 4 hours later
