### ISSUE TITLE
JAVA exception

### ISSUE THREAD

**Issue by NoAvailableNameLeft** [bisq-network/bisq#6614]
BISQ wanted me to report this bug, a java exception after downloading, installing and running 1.9.9.
[bisq.log](https://github.com/bisq-network/bisq/files/11051306/bisq.log)

**Comment by ghost** [comment]
Same as https://github.com/bisq-network/bisq/issues/6545

**Comment by r0ck11** [comment]
@jmacxx Just had the same issue as well but it says it's fixed. I guess it's not.

**Comment by ghost** [comment]
We have not had a new release in several months, but the [fix](https://github.com/bisq-network/bisq/pull/6551) is ready for when that release finally arrives!
