### ISSUE TITLE
An error ocurred at task: CreateMakerFeeTx

### ISSUE THREAD

**Issue by onlymarcus** [bisq-network/bisq#6621]
### Description

When trying to publish an offer by copying from history

#### Version

v1.9.9
[bisq.log](https://github.com/bisq-network/bisq/files/11090649/bisq.log)

### Screenshots
![image](https://user-images.githubusercontent.com/36059034/228271169-960d633b-8c95-4b00-9ebe-cf764bd4f972.png)

#### Device or machine

Edição	Windows 10 Home Single Language
Versão	21H2
Instalado em	‎07/‎12/‎2019
Compilação do SO	19044.2728
Experiência	Windows Feature Experience Pack 120.2212.4190.0

**Comment by ghost** [comment]
Duplicate of #6554

Consolidating your UTXOs should fix it.
