### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by pandascrape** [bisq-network/bisq#6625]
### Description

Red error box appeared asking me to report this bug.

#### Version

v1.9.9

### Steps to reproduce

Started Bisq, clicked on the Buy top menu button to see the order book, then left it for a few minutes without doing anything else.
Error box popped up after a few minutes.

### Expected behaviour

No error box.

### Actual behaviour

Error box.

### Screenshots

Unfortunately I closed the error box before capturing the screenshot, but I do have the bisq.log.

#### Device or machine

Debian 11.

#### Additional info

bisq.log attached
[bisq.log](https://github.com/bisq-network/bisq/files/11122743/bisq.log)

**Comment by bitcoinfixesalot** [comment]
[bisq.log](https://github.com/bisq-network/bisq/files/11129940/bisq.log)

It also happened to me when the application was staying open without clicking on anything. When I clicked to report the error I received another error instead of going to this GitHub page.
Os: windows 10

**Comment by HenrikJannsen** [comment]
The issue was already fixed with https://github.com/bisq-network/bisq/pull/6551 for next release
