### ISSUE TITLE
error when trying to accept trade 

### ISSUE THREAD

**Issue by Scoop193** [bisq-network/bisq#6626]
![2023-03-31](https://user-images.githubusercontent.com/77167690/229264439-bdfe5191-668c-490d-8e25-2a2bed37c282.png)

Attention
The trade protocol encountered some problems.

The trade contract is not set.

The trade cannot be completed and you might have lost your trade fee. If so, you can request a reimbursement for lost trade fees here: [1]
[https://github.com/bisq-network/support/issues]

**Comment by Scoop193** [comment]
Attention
The trade protocol encountered a serious problem.

The trade contract is not set.

The trade cannot be completed and you might have lost your trade fee. If so, you can request a reimbursement for lost trade fees here: [1]

Do you want to move the trade to failed trades?

You cannot open mediation or arbitration from the failed trades view, but you can move a failed trade back to the open trades screen any time.
[https://github.com/bisq-network/support/issues]

**Comment by pazza83** [comment]
Hi @Scoop193 

This looks like a failed trade:

https://bisq.wiki/Failed_Trades_-_Reimbursement_of_Trade_Fees_and_Miner_Fees

Are you the maker or taker of the trade?

**Comment by Scoop193** [comment]
I'm the taker buying the btc

**Comment by pazza83** [comment]
Ok check the taker transaction ID. Do you see it confirmed on the blockchain?
