### ISSUE TITLE
Feature request: add "refresh data directory" tool

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/bisq#6627]
A few times in the past weeks I have assisted users who couldn't start their Bisq because of various issues, but as soon as they tried with a new data directory, everything worked.
The last one I remember: initial chain sync stopped at 62% down to 0 bitcoin peers, both with own node and network provided ones.
Starting with new directory, sync completes.

There is a guide on the wiki that is a hack: https://bisq.wiki/Last_resort_restore
I have suggested this guide in the past and it worked.
Why not making it a "refresh/recovery" tool that is done with the press of a button?
Goes like this:
 - user presses button
 - popup is shown explaining the scope of the tool
 - data directory is backed up and only "non user data" files are deleted in the current data directory
 - Bisq is closed after request to restart it after shutdown

**Comment by helixx87** [comment]
I started working on it and opened [draft pull request](https://github.com/bisq-network/bisq/pull/6642). If you'll have any UI suggestions don't hesitate to put them on this issue or on pull request.

**Comment by helixx87** [comment]
I give up with this topic for now - `Bisq/btc_mainnet/db/json` directory is really big and copying it from backup directory took a lot of time. I was also getting input/output error during it (similar to this described [here](https://askubuntu.com/questions/1200227/input-output-error-during-read-on-dev-sda)).

**Comment by suddenwhipvapor** [comment]
This is another feature that would be a pity to abandon, IMO.
Regarding the flow, I believe it would be:
 - make a backup
 - delete everything from data directory that's not really needed to restore the user specific data
 - close bisq with a SHUT DOWN popup asking the user to restart right after, and providing info about restoring backup if it doesn't work

Regarding the issue encountered by @helixx87 I think, from my ignorant perspective, that the first step generates copying the contents of the json folder, it could/should use the same exact routine that is being used in the manually triggered backup function, after which the file deletion occurs.
