### ISSUE TITLE
Java heap space: failed reallocation of scalar replaced objects

### ISSUE THREAD

**Issue by onlymarcus** [bisq-network/bisq#6628]
### Description
Java heap space: failed reallocation of scalar replaced objects

### Screenshots
![image](https://user-images.githubusercontent.com/36059034/229325791-b104bc2a-a10f-47c4-93b6-903cf44bac18.png)

**Comment by HenrikJannsen** [comment]
Could you post the logs before the error occurred? Which OS do you use?
