### ISSUE TITLE
"No Value Present" Error

### ISSUE THREAD

**Issue by calkob** [bisq-network/bisq#663]
on opening bitsquare I was presented with this error message once I cleared it it got another error.  Java.lang.nullpoint exception.  it keeps popping up as you use the app.

**Comment by haiqu** [comment]
What OS?

**Comment by ManfredKarrer** [comment]
Do you have the latest version installed?
Do you run from the binary or from source? if from src u need to follow exactly the build instructions and use the latest jdk version 1.8.112

**Comment by calkob** [comment]
latest version install sorted the problem, thanks for the replies
