### ISSUE TITLE
Failing trade - `... the input ended unexpectedly...`

### ISSUE THREAD

**Issue by Rot127** [bisq-network/bisq#6633]
### Description

Taking an `BTC<->EUR` offer failed with the following error:
`Timeout reached. Protocol did not complete in 120 sec.`

and the exception in the log can be found below.

My connection seemed fine as far as I can tell. So a timeout is a bit unlikely.

I moved the trade to the failed trades, but I can no longer move it back to the open ones.

Offer ID: `YXBZYCR-a6fe75d5-1eda-40c3-a584-e1a773798b9a-199`
Maker's Onion Address: `ue7hvbgxbn2d5ielhjvlkid6ioontxavnvalpcttfoxsdqjtssswb7ad.onion:9999`

#### Version

`v1.9.9`

### Steps to reproduce

Non I am aware of. Except taking the offer listed above.

### Expected behaviour

The offer is successfully taken.

### Actual behaviour

The `Take offer` step times out due to incorrect input.

### Screenshots

Tell me what you need.

#### Device or machine

CPU: `x86`
OS: `Debian-11`

#### Additional info

```
Feb-18 11:01:07.321 [InputHandler-jn5rownceeyplxsslokdwxp7ydejtptys2g75twpovmuoeevodzdn5qd.onion:9999] ERROR b.n.p.n.Connection: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length. 
Feb-18 11:01:07.321 [InputHandler-7nymvxj4rec3wcs4455stuvnkdw3isxblz4qolkub6x4qwvslntjtsad.onion:9999] INFO  b.n.p.n.Connection: SocketException (expected if connection lost). closeConnectionReason=CloseConnectionReason{sendCloseMessage=false, isIntended=false} RESET; connection=Connection{peerAddress=Optional[7nymvxj4rec3wcs4455stuvnkdw3isxblz4qolkub6x4qwvslntjtsad.onion:9999], connectionState=ConnectionState{,
     peerType=PEER,
     numInitialDataRequests=0,
     numInitialDataResponses=0,
     lastInitialDataMsgTimeStamp=0,
     isSeedNode=false,
     expectedInitialDataResponses=5
}, connectionType=OutboundConnection, uid='d1ff1f18-9c4c-4c6c-8129-05b8afc435dc'} 
Feb-18 11:01:07.321 [InputHandler-jn5rownceeyplxsslokdwxp7ydejtptys2g75twpovmuoeevodzdn5qd.onion:9999] WARN  b.n.p.n.Connection: We got reported the ruleViolation INVALID_DATA_TYPE at connection Connection{peerAddress=Optional[jn5rownceeyplxsslokdwxp7ydejtptys2g75twpovmuoeevodzdn5qd.onion:9999], connectionState=ConnectionState{,
     peerType=PEER,
     numInitialDataRequests=0,
     numInitialDataResponses=0,
     lastInitialDataMsgTimeStamp=0,
     isSeedNode=false,
     expectedInitialDataResponses=5
}, connectionType=OutboundConnection, uid='6c67b4f2-7f12-4510-aea6-11c6d6bb7e4e'} 
```

**Comment by pazza83** [comment]
@Rot127 

Thanks for the issue.

Was a deposit transaction created? If so have you checked to see if it present on the blockchain?
