### ISSUE TITLE
Java heap space

### ISSUE THREAD

**Issue by onlymarcus** [bisq-network/bisq#6637]
### Description

[bisq.log](https://github.com/bisq-network/bisq/files/11179490/bisq.log)

**Comment by pazza83** [comment]
Hi @onlymarcus are you looking to share this with someone specific?

It is not recommended to post logs publicly, better to share with someone on the support team in Matrix.

**Comment by onlymarcus** [comment]
Bisq opened a pop up with a message asking me to open a topic here with this error and include the log
