### ISSUE TITLE
Market Depth (order book) graph shows inverted colors

### ISSUE THREAD

**Issue by christian-hawk** [bisq-network/bisq#6639]
### Description
Market Depth shows **GREEN** for sell offers and **RED** for buy offers, the correct is the opposite. 
Market Depth (order book) graph shows inverted colors. This is very confusing for who uses the graph (traders).

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/59786962/230665232-533097d0-5db1-4dbf-bb63-37fcb0b0bca4.png">

#### Version
v1.9.9

### Steps to reproduce
1. Open app
2. Click on Market
3. Check Order Book tab

### Expected behaviour
Should show **RED** for **selling offers** and **GREEN** for **buying offers**. As you can see in any other platform that provides the market depth:

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/59786962/230665016-838236cc-dd8d-4801-83c7-e951b0a233ec.png">

#### Device or machine
Mac OS

**Comment by pazza83** [comment]
This has been discussed previously: 

https://github.com/bisq-network/bisq/issues/2383

I think it is ok the way it is now.

Green = Buy
Red = Sell

**Comment by helixx87** [comment]
I see that [#2383](https://github.com/bisq-network/bisq/issues/2383) discussion wasn't finished but marked as stale by bot. 

> Green = Buy
Red = Sell

It's a bit more complex - when you **buy** you take someone's **sell** offer and vice versa. It seems to be standard in the trading world that **someone's buy** offers are marked **green** on market depth chart. 

Consider Binance trading view:
![binance-market-depth](https://user-images.githubusercontent.com/128257662/230759998-ab522492-9a80-47fe-83de-9520f486db27.png)

I think in addition to what I've done in my PR we could also:
- inverse buttons (green `BUY BTC` will be on the left side above buy offers and vice versa)
- remove headline `Sell BTC to` or rename it to `Buy offers`

**Comment by christian-hawk** [comment]
> This has been discussed previously:
> 
> #2383
> 
> I think it is ok the way it is now.
> 
> Green = Buy Red = Sell

@pazza83 allow me to disagree that it may be ok being wrong. It's an important trading tool, and it should be done right. High volume traders starting in Bisq use this tool a lot :) 

It would be the same as having red candle when prices moves up and green when prices moves down in candlestick price graph. That would also not be ok at all for traders.




> I see that [#2383](https://github.com/bisq-network/bisq/issues/2383) discussion wasn't finished but marked as stale by bot.
> 
> > Green = Buy
> > Red = Sell
> 
> It's a bit more complex - when you **buy** you take someone's **sell** offer and vice versa. It seems to be standard in the trading world that **someone's buy** offers are marked **green** on market depth chart.
> 
> I think in addition to what I've done in my PR we could also:
> 
> * inverse buttons (green `BUY BTC` will be on the left side above buy offers and vice versa)
> * remove headline `Sell BTC to` or rename it to `Buy offers`

Indeed @helixx87 .  Btw thank you for the PR.

Actually is not that complex. 

Rule is:
- 🔴 SALES ORDERS
- 🟢 BUY ORDERS

What we call **OFFER** is a maker order that is similar to a **Limit Order** with some extra features such as % deviation.

When I **take** an order (aka offer) I'm the market **taker**. I also submit an order to accept the open order. (i.e. market order). So, when I submit a **BUY (green) taker order** from a **SELL (red) maker order** I usually do that in a green button. 

If I want to buy at certain price, I will look for the **red prices in order book**, and **red block in market depth graph**.


About adding other changes to the PR:

1. notice that the scope of this issue is regarding the **Market Depth Graph** only. 

2. Fixing the order book sides is another issue (with lower impact, from my perspective, but still important). It may be placed in another independent issue.

3. **EDITED** Buttons may be anywhere, as long as BUY is GREEN and SELL is RED.

---------
### Additional context:

**Order book sides - Green (buy orders) on left, Red (sell orders) on right**
<img width="808" alt="image" src="https://user-images.githubusercontent.com/59786962/231561505-3f45faac-3841-449e-9361-2b563c5f5ae4.png">

**Comment by pazza83** [comment]
Many tanks for the comments @christian-hawk 

Everything you say makes sense.

> About adding other changes to the PR:
> 
> 1. notice that the scope of this issue is regarding the **Market Depth Graph** only.
> 2. Fixing the order book sides is another issue (with lower impact, from my perspective, but still important). It may be placed in another independent issue.
> 3. Buttons may be anywhere, as long as BUY is RED and SELL is RED.

Would it be possible for you to mockup  or sketch out what you think is the best way for the offer book to be presented? I think if changes are to be made they might as well all be made at once.

**Comment by christian-hawk** [comment]
> Many tanks for the comments @christian-hawk
> 
> Everything you say makes sense.
> 
> > About adding other changes to the PR:
> > 
> > 1. notice that the scope of this issue is regarding the **Market Depth Graph** only.
> > 2. Fixing the order book sides is another issue (with lower impact, from my perspective, but still important). It may be placed in another independent issue.
> > 3. Buttons may be anywhere, as long as BUY is RED and SELL is RED.
> 
> Would it be possible for you to mockup or sketch out what you think is the best way for the offer book to be presented? I think if changes are to be made they might as well all be made at once.

I'm really a backend guy, but I can try. Any tools you may suggest for doing it @pazza83 ?

**Comment by pazza83** [comment]
[Gimp](https://www.gimp.org/) comes recommenced but might be more powerful than you need.

It does not have to be fancy, I suppose just something that shows what you think would be best in image form.

**Comment by helixx87** [comment]
Hi @pazza83,
in response to [your request](https://github.com/bisq-network/bisq/pull/6640#issuecomment-1537188329) I'm attaching a recording with a demo of the changes currently included in the pull request:

https://github.com/bisq-network/bisq/assets/128257662/38f97275-e808-4a01-a2f4-0e7ef36b71fb

**Comment by pazza83** [comment]
Hi @helixx87 

Thanks for posting the video.

I'm confused by this.

In the offers shown on the main screen (showing both buy and sell offers), when clicking on sell you see the buy offers, and when clicking on buy you see the sell offers.

Not sure if this is how it would be in practice? Assuming not.

**Comment by helixx87** [comment]
Thanks @pazza83, you're right - I fixed this issue [in the newest commit](https://github.com/bisq-network/bisq/pull/6640/commits/438c7629539525fa196ac37b994ddf5a44414f61). Here is a updated demo:

https://github.com/bisq-network/bisq/assets/128257662/16567f0c-229c-40f0-9795-fe3869fb8238

**Comment by pazza83** [comment]
Thanks, I am still confused:

Your demo:

![Capture2](https://github.com/bisq-network/bisq/assets/66367547/41fb640c-a415-4996-8e8b-572a081b7394)

My Bisq:

![Capture](https://github.com/bisq-network/bisq/assets/66367547/0b4aa389-bc31-46f9-85a1-d876ff8427d2)

I can see the colors are inverted, but surely the offer books should also be inverted?

Something more like this (once red and green have been inverted):

![Capture3](https://github.com/bisq-network/bisq/assets/66367547/5b981964-23a4-404e-bf08-b63c93533b1b)

**Comment by helixx87** [comment]
OK, I prepared diagram that should help us with making final decision how it should works

![areas](https://github.com/bisq-network/bisq/assets/128257662/f1d98f45-1020-44fa-bb21-3592d2c301d0)

I propose for now focus on **BTC/Fiat** market - current implementation on PR works like that:

A) Left side:
- L1 - green histogram representing BTC buy offers (L4), **no click**
- L2 - label with static "Buy offers" text, **no click**
- L3 - green button with static "BUY BTC" text, **click** moves user to `Buy -> Bitcoin` view,
- L4 - list of BTC buy offers, **click** moves user to `Sell -> Bitcoin` view

B) Right side:
- R1  - red histogram representing BTC sell offers (R4), **no click** 
- R2 - label with static "Sell offers" text, **no click**
- R3 - red button with static "SELL BTC" text, **click** moves user to `Sell -> Bitcoin` view 
- R4 - list of BTC sell offers, **click** moves user to `Buy -> Bitcoin` view

I agree this behavior is a bit confusing - I'm looking forward to some proposals how to improve it. I'll also think about it and try to propose something.
