### ISSUE TITLE
It's not possible to create an offer to buy BTC using cash deposit without adding a bank account

### ISSUE THREAD

**Issue by MarcSte** [bisq-network/bisq#664]
As described in [this](https://www.reddit.com/r/Bitcoin/comments/58i7nk/bitsquare_update_v0497/d91ki89/) Reddit comment.

This would be useful for people without access to a bank account.

**Comment by haiqu** [comment]
Well spotted, we'll look into that one poste haste.

This is actually important, a significant number of people in third world countries are unbanked.

**Comment by haiqu** [comment]
I just tested this. As long as you enter a cash deposit account on the accounts page and enter the minumum data (name & email address) trading should be possible. Bank details are optional.

The system just needs to know the currency.

User error, please close.

**Comment by Piste** [comment]
@MarcSte if in agreement, could you close this issue?

**Comment by MarcSte** [comment]
Sure, thx for pointing me to it.
