### ISSUE TITLE
qr transmission 

### ISSUE THREAD

**Issue by Monicaann0o** [bisq-network/bisq#6648]
![2022-12-23 15.32.15.jpg](https://user-images.githubusercontent.com/118498146/231645573-a55296f4-aac5-47fb-ba2b-9a1ad24b1164.jpg)

**Comment by MwithM** [comment]
This qr code has the link https://blockch air.com/bit coin-cash/transaction/c52e52b075edbf6246de9a892f21937937 ac0c4ffc3136a0f230972f078dcfff.pdf

Please remove this issue and ban the user.

**Comment by cd2357** [comment]
https://github.com/bisq-network/bisq/issues/6650#issuecomment-1514364788

https://github.com/bisq-network/bisq/issues/6650#issuecomment-1514375958
