### ISSUE TITLE
help me i can not access

### ISSUE THREAD

**Issue by Monicaann0o** [bisq-network/bisq#6650]
https://photos.app.goo.gl/pzLXThwb2SQy9Lxt5

**Comment by Monicaann0o** [comment]
> https://photos.app.goo.gl/pzLXThwb2SQy9Lxt5

how too open

**Comment by pazza83** [comment]
More spam again

Please can this user be banned

**Comment by cd2357** [comment]
Don't have the right permissions to ban, but I can close this.

**Comment by cd2357** [comment]
@pazza83 perhaps you can ask an admin to add you to @bisq-network/bisq-issues-maintainers . That would give you permissions to close issues, edit labels, etc.

IMO that would make sense, since you're often a "first responder" to new issues.

**Comment by pazza83** [comment]
Thanks, will request permissions from @alejandrogarcia83
