### ISSUE TITLE
CreateMakerFeeTx

### ISSUE THREAD

**Issue by Justus1776** [bisq-network/bisq#6653]
### Description

When creating an offer to sell BTC  getting a notification "Error occurred when placing the offer:"

#### Version

1.9.9

### Steps to reproduce

Create Offer to sell bitcoin

### Expected behaviour

Place offer to sell bitcoin

### Actual behaviour

When placing offer to sell bitcoin getting an error pop up titled "CreateMakerFeeTx

### Screenshots
![image](https://user-images.githubusercontent.com/122484697/232462223-69a5a491-0dff-4342-9239-909929ff7ab9.png)

![image](https://user-images.githubusercontent.com/122484697/232461406-a1b0ffeb-c10a-4eab-ac94-24676abb0810.png)

#### Device or machine

Edition	Windows 10 Home
Version	21H2
Installed on	‎3/‎9/‎2022
OS build	19044.2846
Experience	Windows Feature Experience Pack 120.2212.4190.0

#### Additional info

File Log:  Attached

[bisq file log 0417230549.txt](https://github.com/bisq-network/bisq/files/11249238/bisq.file.log.0417230549.txt)

**Comment by Justus1776** [comment]
Update:  when exchanging for Zelle it works... the issue seems to be when exchanging for Cash in mail

**Comment by Justus1776** [comment]
hello is anybody out there?

**Comment by pazza83** [comment]
Hi this is a similar post to: https://github.com/bisq-network/bisq/issues/6621

I would recommend consolidating your UTXOs.

Send the BTC in you Bisq wallet to a new address also in your Bisq wallet.
