### ISSUE TITLE
Unable to confirm trade id : 2232585-6d37373d-dc0c-49dd-b3d3-0e28afbc3e5c-199

### ISSUE THREAD

**Issue by rbt999** [bisq-network/bisq#6659]
### Description

gettting error when trying to confirm order

#### Version

1.9.9 
Network version: 1; P2P message version: 10; Local DB version: 1; Trade protocol version: 4

### Steps to reproduce

just hittinf , funds received button over and over again populates the same msg 
### Expected behaviour

trade would be confirmed and closed
### Actual behaviour
![ERROR](https://user-images.githubusercontent.com/75705050/232897943-e42065a3-218c-4359-96a7-55ca573642be.JPG)
[bisq.log](https://github.com/bisq-network/bisq/files/11266104/bisq.log)

[bisq.log](https://github.com/bisq-network/bisq/files/11266102/bisq.log)

erro msg

#### Device or machine

windows latest

**Comment by rbt999** [comment]
Tried to resync SPV file, no help

**Comment by MwithM** [comment]
Related to #4065

**Comment by rbt999** [comment]
Thank you, it seems my issue falls into the one where the offer remained open but there are no funds locked anymore.  
Trade partner never reached so it might be the funds are sorted. I checked my locked funds and there r none for this trade. 

I guess I need to follow this below , but could I somehow double check if the funds are not locked anymore ? 

The trade has completed but still shows up in your open trades list.

The following advice involves clearing the data structure which keeps track of open trades. This is only applicable in extreme circumstances when the normal flow of operations did not happen, as is the case here. As always, [make a backup](https://bisq.wiki/Backing_up_application_data) first.

[Prerequisite: you must have no other open trades, as all current open trades will be removed. If you have other open trades, do not continue until they have all completed].

To remove the open trades, close down Bisq then delete the file PendingTrades file from the db folder within the [data directory](https://bisq.wiki/Data_directory).

**Comment by pazza83** [comment]
> I guess I need to follow this below , but could I somehow double check if the funds are not locked anymore ?

Yes, that is the way to fix the issue.

I have seen a few of these trades where one of the traders gets the error message as you detailed but the trade pays out.

Following the steps you posted will remove the trade from your open trades.

Make sure you have double checked the trade did actually pay out and the bitcoin from the trade can be seen in your Funds > Transactions section in Bisq.
