### ISSUE TITLE
Add new account: buttons hidden in 1024 x 768

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#666]
When I select Account->Add New Account this is the result:

![account](https://cloud.githubusercontent.com/assets/13131219/19602736/be72594a-97f1-11e6-824f-3295876ca8b5.png)

Once a country is selected they are barely visible so it's usable, but this does need improvement.

Also note the Bank ID and Account No. text fields are not displayed fully. Removing the `e.g.` would fix that.

**Comment by ManfredKarrer** [comment]
Yeah would require a scroll pane...

**Comment by haiqu** [comment]
Note: Scroll panel not yet added but all inconsistent and verbose text fields have been rectified now.

**Comment by haiqu** [comment]
Manfred: I see you've changed the SEPA form to say simply `IBAN` and `BIC`. Since I had just made that the same as all the other forms, did you want them all reduced to one word? Note that I have no idea of what BIC is but I have heard of SWIFT so if it's going to be so brief I'd suggest at least going back to `BIC/SWIFT`.

Over all anyone from outside Europe will have trouble understanding the form as it now stands.

**Comment by ManfredKarrer** [comment]
For sepa users IBAN, BIC is well known. Swift is not used. I changed it here because it is the stardard and wanted to avoid that people fill in bank cccount nr instead of IBAN.
In other methods it might be more open, or we dont have full info. National bank tx depends on county. So better to leave it more open there.

**Comment by haiqu** [comment]
But IBAN is the account number, isn't it? It stands for "International Bank Account Number".

Or is a shorter version of that number used for national accounts?

SWIFT is "Society for Worldwide Interbank Financial Telecommunication" and they are the organization responsible for issuing BIC, the "Bank (or Business) Identifier Code". Everywhere else except Europe calls them SWIFT codes.

**Comment by ManfredKarrer** [comment]
Yes national account nr. is shorter than IBAN. Yes Swift and BIC are basically the same but banks use BIC in sepa countries so far i know, so people are used to BIC and not Swift.

**Comment by haiqu** [comment]
Oops, didn't mean to close this. Scroll bars still needed.

**Comment by ManfredKarrer** [comment]
Fixed with https://github.com/bitsquare/bitsquare/pull/765
