### ISSUE TITLE
Add available BSQ amount to top menu bar in client

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#6660]
### Description

Bisq has two native wallets, BTC and BSQ.

Users of Bisq see there BTC balances on the top right of the Bisq client (available, reserved and locked), but to see their BSQ balance they need to go to  > DAO > Bisq wallet.

It would improve usability if users could see their available BSQ balance alongside their BTC balances in the top right menu bar on Bisq.

I would propose adding it on the far right. 

#### Version

1.9.9

### Steps to reproduce

To see your BSQ balance you have to go through a couple of screens.

### Expected behaviour

Be able to see your BSQ balance on every screen in the top right alongside BTC balances.

**Comment by pazza83** [comment]
Would still be good to get this implemented.

@helixx87 any updates?

**Comment by pazza83** [comment]
Are any other @bisq-network/bisq-devs able to take this on?

**Comment by helixx87** [comment]
Hi @pazza83, I'm back in business and have plans to take a look into it.

**Comment by pazza83** [comment]
Ok @helixx87 that is good. I am looking forward to BSQ being included in the menu bar.

**Comment by pazza83** [comment]
Hi @helixx87 any updates on this?
