### ISSUE TITLE
Amazon EUR doesn't show country code for gift cards.

### ISSUE THREAD

**Issue by Rassah** [bisq-network/bisq#6661]
### Description

EUR currency allows you to buy Amazon gift card codes from a number of Amazon sites (Amazon .es/de/it/fr/etc). Unfortunately a code for one country does not work in another. When you choose a Sell order for an Amazon card in EUR as a taker, there is nothing indicating what country the gift card is being offered for. I suspect if you create a sale offer as a maker, the takers won't see which card you are asking to sell Bitcoin for either.

#### Version

v1.9.9 

### Steps to reproduce

Take any Amazon EUR SELL offer as a taker

### Expected behaviour

As a taker I should be able to see if the Amazon card being offered is (DE) or (IT) or (ES) or whatever specific country the seller is selling for.

### Actual behaviour

When taking a Sell order for Amazon gift card in EUR currency listing, you just see that the sale is for a general Amazon gift card, not for which specific country it's for.

**Comment by suddenwhipvapor** [comment]
Me and pazza83 just verified the two offers in sell btc tab under EUR egift card, actually show no data about the amazon website country.
I was suggested to tag @jmacxx about this

**Comment by suddenwhipvapor** [comment]
I think this is a noteworthy feature to add, since eur market for egift cards is otherwise heavily impaired because matching peers would be next to impossible, unless they are lucky and realize they should discuss in trader chat which country to buy the egift card for

**Comment by pazza83** [comment]
> I think this is a noteworthy feature to add, since eur market for egift cards is otherwise heavily impaired because matching peers would be next to impossible, unless they are lucky and realize they should discuss in trader chat which country to buy the egift card for

Agreed, I thought this was this how already in place but was mistaken.

@jmacxx 

Are you able to add the letters on the country making the offer on the EU market to the offer book in the same way that that it shows for SEPA trades?

**Comment by ghost** [comment]
@suddenwhipvapor said "unless they are lucky and realize they should discuss in trader chat which country to buy the egift card for"


The country is shown when buyer is prompted to make payment.

![image](https://github.com/bisq-network/bisq/assets/47253594/13c06e6b-2bde-4c11-9a00-c69b61d13c59)

**Comment by suddenwhipvapor** [comment]
Oh. Never used this method myself, but few times saw users complaining. Now I wonder what they were complaining about then...
Angela sure does know what she's doing, I say.

Wait, so this is the result of your PR rather than an existing feature?

**Comment by ghost** [comment]
> Wait, so this is the result of your PR rather than an existing feature?

Existing feature since 2021, look at the date in the screenshot.  And https://github.com/bisq-network/bisq/pull/5117

**Comment by Rassah** [comment]
> @suddenwhipvapor said "unless they are lucky and realize they should discuss in trader chat which country to buy the egift card for"
> 
> The country is shown when buyer is prompted to make payment.
> 

Nope. Go to Sell tab, choose Euro, look for Amazon gift card, hit SELL (you're selling bitcoin in exchange for card). That country information is nowhere to be seen. Next step, it just asks you to transfer funds from wallet, and still no indication of what Amazon country you're buying from. Only after you paid the transaction fee to lock in the funds do you maybe find out.

Confirmed still same issue with v1.9.12

**Comment by ghost** [comment]
I see what you are saying.  Bisq shows your country (which you entered in the Bisq Payment Account setup) to the buyer who needs to go and purchase the gift card.  

Buyer sees:
![image](https://github.com/bisq-network/bisq/assets/47253594/16ca78aa-2bac-4e98-a6b6-ff8e95ee2921)

Seller sees:
![image](https://github.com/bisq-network/bisq/assets/47253594/3bc8d1e0-cac7-4a7c-bcba-62f381ba3e49)

This experience is universal for all payment methods, FWIW.
I am sorry if that is confusing to you as a seller.

**Comment by ghost** [comment]
When @suddenwhipvapor said "unless they are lucky and realize they should discuss in trader chat which country to buy the egift card for" I took it to mean there is a trade in progess (hence the mention of using trader chat to discuss the country).  And I was simply pointing out that the country is shown on the buyer's screen as shown in the above screenshots.

**Prior** to a trade happening, however, the country that the gift card will be purchased from is not currently shown.

@pazza83 has [requested it above](https://github.com/bisq-network/bisq/issues/6661#issuecomment-1642448724) and there is #6777 to implement it.  

That PR will result in the country of the offer creator being shown.  If the offer creator is a BTC buyer then the country shown seems to be irrelevant since the _country of the seller_ is really the one which needs to be used for purchasing an eGift.  :eyes: 


example: 
- I am from the Netherlands and want to buy BTC using Amazon eGift.  I create a buy offer.
- If @pazza83's request is granted, my offer will show up in offer book as `Amazon eGift Card (NL)`
- Angela from Germany takes my offer.  She is prompted to wait for the eGift to show up.  
- I am prompted to go to `amazon.de` and purchase an eGift for Angela.

**Comment by Rassah** [comment]
Yeah, this is more for if you want to get a specific Amazon gift card and want to sell Bitcoin for it. Or if you already have a specific Amazon gift card you want to get rid of for bitcoin. Not if you're buying bitcoin and don't care what Amazon country you use to do it with.
For instance, I have bitcoin and browse the sell section, and see this:
![image](https://github.com/bisq-network/bisq/assets/901536/3a77a1dc-95b2-4e5e-8f63-c1cf277873ca)

If I click on the info, I don't get any extra clues
![image](https://github.com/bisq-network/bisq/assets/901536/4c1190bf-f980-45b6-b69b-b920731a15ac)

Choose SELL to take the offer, still nothing. Just tells me I'll be doing it with my country's Amazon trading account, but no clue what card the Seller has to offer. And NEXT STEP still has no indication of what country.

The seller might have a France Amazon card they need to sell. I need a Spanish or a Netherlands one. We won't know what is being traded until we initiate a trade (transaction fees), discuss it in chat, and maybe find out that we have different needs, so we need to close the trade (more transaction fees). I wouldn't bring it up if it didn't happen to me (twice already)

**Comment by Rassah** [comment]
Gueeeees what?
Need to get an Amazon ES gift card.
Went to "Sell" tab
Selected "Euro" for currency

Oh look, a whole lot of Amazon eGift Cards for sale!
Selected one
Picked my Amazon ES account as recipient.
NO indication of what gift card is for sale.
Paid BTC transaction fee to deposit funds.
Paid BTC transaction fee to take the offer, using my Amazon ES account, still no indication of what gift card this is.

Guy on the other side, "I only have Amazon DE cards to sell."

Can I get my money back? Will this ever be fixed?

**Comment by pazza83** [comment]
Hi @Rassah apologies for this. 

The fix has been applied to the code but will not be in place until the next Bisq release 1.9.13.

I would recommend opening mediation for the trade by selecting the trade and pressing 'Ctrl' + 'O'
