### ISSUE TITLE
errror while trying to trade 

### ISSUE THREAD

**Issue by Scoop193** [bisq-network/bisq#6663]
[bisq419.txt](https://github.com/bisq-network/bisq/files/11276413/bisq419.txt)
![2023-04-19](https://user-images.githubusercontent.com/77167690/233163944-54a9c8a2-8ffc-4526-98d4-772fcd97f1b2.png)

**Comment by pazza83** [comment]
Your wallet might be corrupted. Try doing an [SPV resync](https://bisq.wiki/Resyncing_SPV_file)

**Comment by Scoop193** [comment]
Ok I currently have another trade on going so after that is finished I can
do it

**Comment by pazza83** [comment]
Great let me know if it fixes the issue
