### ISSUE TITLE
Add Auto-confirming trades for ETH/BTC 

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#6664]
### Description

With the recent closure of peer to peer exchanges such as Paxful, Local Bitcoin and Local Cryptos traders from these platforms are looking for new homes.

From feedback received from users of Bisq trading Ethereum one of the pain points of Bisq is Instant Altcoins accounts not always being so instant.

Bisq has for a long time had the option for Monero traders to [auto-confirming trades](https://github.com/bisq-network/proposals/issues/86), if this was reproduced for Ethereum it would have a positive impact to their trading experience and help Bisq grow it's ETH/BTC volumes.

#### Version

V1.9.9

### Steps to reproduce

Traders of ETH / BTC are unable to auto confirm trades

### Expected behaviour

Traders of ETH / BTC to be able to auto confirm trades

- Recommend for it to be the same as XMR / BTC with auto confirm being the default and users able to opt out if wanted or increase the number of default confirmations if required.

**Comment by MwithM** [comment]
Auto confirm was by default after it being in real environment for a long time, so maybe it's better to not make it the default until next 6 months of being deployed or so.

**Comment by pythonicpanda** [comment]
@pazza83 You receive??? My messages not sending more :/

![Captura de tela de 2023-04-21 08-23-53](https://user-images.githubusercontent.com/131182539/233638780-621618d2-0aab-4f70-9ac1-197ac9a9baee.png)

**Comment by pazza83** [comment]
> @pazza83 You receive??? My messages not sending more :/

Yes, I have made the proposal.

**Comment by pythonicpanda** [comment]
> > @pazza83 You receive??? My messages not sending more :/
> 
> Yes, I have made the proposal.

again, please, help me
![Captura de tela de 2023-04-25 23-00-17](https://user-images.githubusercontent.com/131182539/234456404-aaa86d8a-e8b9-46e8-b7e9-528321ede46b.png)

**Comment by pythonicpanda** [comment]
you receive my message?

**Comment by pythonicpanda** [comment]
I have 4 trades. Not visible support field

**Comment by pythonicpanda** [comment]
@pazza83 

again, other trade. same problem. send message support but message not received by arbitration user

![Captura de tela de 2023-04-25 23-06-13](https://user-images.githubusercontent.com/131182539/234458310-4703abb7-a0d3-4676-8f2d-6a2f82bcbe92.png)

**Comment by pythonicpanda** [comment]
@pazza83 

Again, other trade. Please send me proposal. thanks

![Captura de tela de 2023-04-25 23-10-58](https://user-images.githubusercontent.com/131182539/234459379-31f927b1-1fd4-4b58-a4df-97b6ab4d67b4.png)

**Comment by pythonicpanda** [comment]
@pazza83 Other trade 

please, help-me. my message not received?
![Captura de tela de 2023-04-25 23-14-20](https://user-images.githubusercontent.com/131182539/234460466-56e3e318-589f-4532-9598-478a272d568d.png)

**Comment by pythonicpanda** [comment]
@pazza83 

new trade. this trades the buyer not sending fiat money in my account

![Captura de tela de 2023-04-25 23-21-53](https://user-images.githubusercontent.com/131182539/234461437-cb4a81d0-bb12-4fe4-8e65-578e47ae19d5.png)

**Comment by pythonicpanda** [comment]
@pazza83 

This trade... again, same problem? send message for support and not received? please, help-me

![Captura de tela de 2023-04-25 23-32-02](https://user-images.githubusercontent.com/131182539/234463153-06621108-5b9a-40b0-acf0-1072ec638aae.png)

**Comment by pythonicpanda** [comment]
@pazza83 Varios days and not receive proposal. Okay?

![Captura de tela de 2023-04-26 10-51-38](https://user-images.githubusercontent.com/131182539/234615434-051dcf7b-5548-446d-a708-a4e4da218b67.png)

**Comment by pazza83** [comment]
Hi @pythonicpanda just seen your github messages.

Probably not best to discuss your trade on this tread as it derails it and is bad for your privacy.

I am available on [Matrix](https://bisq.wiki/Matrix_bisq.chat)

My username there is: @pazza83:matrix.org

You can send me a private message there about any trades you have in mediation with myself and I will answer them.

**Comment by pazza83** [comment]
Would still be good to add this.

@jmacxx would this be something you would be interested in doing?
