### ISSUE TITLE
Screenshot (Apr 23, 2023 5:07:59 PM)

### ISSUE THREAD

**Issue by Monicaann0o** [bisq-network/bisq#6667]
![Screenshot_20230423-170759.png](https://user-images.githubusercontent.com/118498146/233874205-d59a5908-23d0-473d-b02d-7d45b20fc09f.png)

**Comment by Monicaann0o** [comment]
blockchain

**Comment by pazza83** [comment]
Spam

**Comment by Jmoney509** [comment]
So it's not real
