### ISSUE TITLE
Edit button/pen symbol stops working for altcoin offers requiring restart

### ISSUE THREAD

**Issue by imfiesh** [bisq-network/bisq#6668]
Sometimes the EDIT button stops working for altcoin offers. If I click on it for my own offers when in the SELL/BUY views, I just get switched to the MY OPEN OFFERS tab and if I click the pen symbol in there nothing happens whatsoever. It only seems to happen when I mess around with BSQ offers so it seems BISQ gets confused and starts treating every offer as a BSQ offer when it comes to edit ability. The only remedy is to restart BISQ.
Version: 1.9.9

**Comment by ripcurlx** [comment]
Yes, the handling of edit BSQ is broken, as there is no edit of BSQ. I think the best thing would be to remove the edit button for BSQ offers. Anyone up for this issue?

**Comment by pazza83** [comment]
@ripcurlx 

A while ago I seem to remember edit BSQ swaps agreeing to be implemented as something that deletes the current one and then makes a new offer. Therefore from a UI perspective for the user it would work in the same way as editing any other offer. Would that be possible?

**Comment by imfiesh** [comment]
Seems you got what I meant despite my not very clear explanation, but just for reference: What I mean is that also other altcoin offers, including for example XMR offers, lose the ability to be edited until I restart BISQ. This seems to be triggered by me mistakenly trying to edit an BSQ offer.

**Comment by pazza83** [comment]
Thanks @imfiesh, is one of the @bisq-network/bisq-devs able to replicate this issue and find out what is causing it?

**Comment by alvasw** [comment]
> Thanks @imfiesh, is one of the @bisq-network/bisq-devs able to replicate this issue and find out what is causing it?

@imfiesh is right! I can replicate the bug. If you click on the BSQ offer's "edit button" button and afterward on a not-BSQ offer's edit button the bug happens.
