### ISSUE TITLE
TakerProcessesInputsForDepositTxResponse

### ISSUE THREAD

**Issue by ntheden** [bisq-network/bisq#6671]
### Description

An error occurred when taking the offer.

An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 790589, myLockTime=789203

No funds have left your wallet yet.
Please try to restart your application and check your network connection to see if you can resolve the issue.

Please restart your application and check your network connection to see if you can resolve the issue.

#### Version

version 1.9.9

### Steps to reproduce

- Go to sell tab
- Select a peer to sell
- Go through the dialogs and take the offer.

### Expected behaviour

Trade is entered

### Actual behaviour

Error message as seen above. Does not matter what peer I try to trade with, always the same error. Tried restarting the app several times. The bottom says "Synchronizing DAO", should it say DAO is in synch? It always says synchronizing. Inbound connections: 4, Outbound connections: 7.

#### Device or machine

Linux PureOS (debian-based)

#### Additional info

I have logs but seems like there is some identifying info in there so not posting.

**Comment by ghost** [comment]
Yes, your Bisq is out of sync, by about 10 days according to the message above.  "Synchronizing DAO" in the footer should clear itself shortly after starting Bisq, if it does not you can go to DAO -> BSQ Wallet -> Transactions and look for a progress bar which indicates how many blocks it still needs to catch up.

I would recommend upgrading to [v1.9.10](https://bisq.network/downloads/) as it comes bundled with the latest DAO blocks, so synchronizing should be much faster.

**Comment by ntheden** [comment]
I upgraded to v1.9.10 and went to DAO -> BSQ Wallet -> Transactions but I see no progress bar, only a list of transactions.

In DAO -> Network Monitor, the Chain of DAO state hashes show Conflicts: 1 for every peer. Is that a problem and how do I correct it? It is stuck on Synchronizing DAO for days, I don't think it will resolve by itself.

**Comment by ghost** [comment]
Odd.  One thing to try would be click `Rebuild DAO state from resources` which is a button in Settings -> Preferences.  But something sounds not right, I would need to see logs if there's still a problem.  You could arrange to send them to a [support](https://bisq.wiki/User_support) person on Matrix.

**Comment by ghost** [comment]
How healthy is your bitcoin node connection?  Bottom left footer bar.

**Comment by ntheden** [comment]
Yes, I just noticed today that my bitcoin node has been unstable. I just switched to pre-configured bitcoin nodes over Tor, and it looks better with those.

**Comment by ntheden** [comment]
Closing because it was related to poor bitcoin node connection.
