### ISSUE TITLE
Colors Reversed In Depth Chart

### ISSUE THREAD

**Issue by mjg-foundation** [bisq-network/bisq#6672]
### Description

The colors red and green in the Market page's depth chart are backwards. Buy pressure should be green, and sell pressure should be red.

#### Version

1.9.10

### Steps to reproduce

View the Market page.

### Expected behaviour

The left side of the depth chart should be colored green, and the right side of the depth chart should be colored red.

### Actual behaviour

The left side of the depth chart is red, and the right side of the depth chart is green.

### Screenshots

![depth_chart](https://user-images.githubusercontent.com/114431859/235507092-676302ca-0c10-4b52-b0af-fa10e5151ff4.png)

#### Device or machine

Ubuntu Linux 20.04

**Comment by pazza83** [comment]
Hi @mjg-foundation this is being discussed here: https://github.com/bisq-network/bisq/pull/6640
