### ISSUE TITLE
Bug report on startup

### ISSUE THREAD

**Issue by omusluh** [bisq-network/bisq#6673]
Hi, I logged into Bisq and got this error and instructions were to copy it here for you to see the bug
[bisq error log.txt](https://github.com/bisq-network/bisq/files/11367674/bisq.error.log.txt)

**Comment by Rednator** [comment]
> Hi, I logged into Bisq and got this error and instructions were to copy it here for you to see the bug [bisq error log.txt](https://github.com/bisq-network/bisq/files/11367674/bisq.error.log.txt)

Hi @omusluh visit the official [Bisq](wikibisq.online) page to initiate a chat with the official agent on a live chat to report the error for review and for further assistance via [Bisq Support](wikibisq.online)

**Comment by pazza83** [comment]
> Hi @omusluh visit the official [Bisq] page to initiate a chat with the official agent on a live chat to report the error for review and for further assistance via

@Rednator is trying to Pish for users seed phrases with this dodgy knockoff website.

Is it possible to ban @Rednator and also if possible ban the website from being mentioned that is posted.

**Comment by ghost** [comment]
@omusluh your error is the same as reported in #6545 and has been fixed in the latest release.

So recommend you [upgrade](https://bisq.network/downloads/) to Bisq v1.9.10.

**Comment by gabernard** [comment]
> Is it possible to ban @Rednator and also if possible ban the website from being mentioned that is posted.

I banned him from all Bisq repositories.
