### ISSUE TITLE
Bisq crashes

### ISSUE THREAD

**Issue by Chordbridge** [bisq-network/bisq#6677]
### Description
Bisq crashed when I clicked on Funds.

Pretty simple

#### Version
1.9.10

### Expected behaviour

It would not crash.

#### Device or machine

Lubuntu 20.04

**Comment by Chordbridge** [comment]
[bisq.log](https://github.com/bisq-network/bisq/files/11405496/bisq.log)

**Comment by ghost** [comment]
Looks like this is your error, `Can't load library: /usr/lib/jvm/java-11-openjdk-amd64/lib/libawt_xawt.so`
Seems configuration of your Java runtime environment is wrong.
[Here is a relevant thread about it](https://stackoverflow.com/questions/67720077/java-openjdk-error-cannot-load-library-java-awt).

---



    May-05 13:35:20.155 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
    May-05 13:35:20.155 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= Can't load library: /usr/lib/jvm/java-11-openjdk-amd64/lib/libawt_xawt.so 
    May-05 13:35:20.155 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.UnsatisfiedLinkError 
    May-05 13:35:20.190 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
    java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-amd64/lib/libawt_xawt.so
	    at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2633)
	    at java.base/java.lang.Runtime.load0(Runtime.java:768)
	    at java.base/java.lang.System.load(System.java:1837)
