### ISSUE TITLE
Bisq Application does not load

### ISSUE THREAD

**Issue by AzidanoValkran** [bisq-network/bisq#6681]
### Description

When double-clicking the Bisq icon to start the program, nothing happens

#### Version

1.9.10

### Steps to reproduce

1.) Double click on the Bisq icon.

### Expected behaviour

The application loads up the splash screen, and is viewable on the Task Manager 'Apps' section

### Actual behaviour

The application does not load up but on the Task Manager only shows a Bisq background process running

### Screenshots

![image](https://user-images.githubusercontent.com/78864939/236660202-12440b4f-dd98-4b3b-854b-5fccf98b9a5b.png)

#### Device or machine

Operating System: Windows 10
Device: Alienware laptop
PC

#### Additional info
[bisq.log](https://github.com/bisq-network/bisq/files/11414039/bisq.log)

**Comment by MwithM** [comment]
https://github.com/bisq-network/bisq/issues/6511#issuecomment-1374674668

**Comment by AzidanoValkran** [comment]
> [#6511 (comment)](https://github.com/bisq-network/bisq/issues/6511#issuecomment-1374674668)

Thank you for your quick and prompt response. I am not sure if this is the same issue, as after I double-click on my shortcut, after setting it to run in maximised mode, I do not get the application loading at all. When I press Alt + Tab, I can't even get to the Bisq application as nothing has come up.

Is there any further advice or assistance?

![image](https://user-images.githubusercontent.com/78864939/236666705-12322c03-27c9-4f21-91de-6c727eb3dc55.png)
Task bar does not show Bisq running.

**Comment by ghost** [comment]
Reboot Windows and try again running Bisq maximized.

**Comment by AzidanoValkran** [comment]
OK, on the telegram group I was suggested to follow the instructions for a Last Resort Restore. I renamed my Bisq folder to Bisq.old, reinstalled, and now the application runs, which is good! But now... how do I go from this to get my trades back?

**Comment by AzidanoValkran** [comment]
I think I managed to resolve this issue by following the Last Resort Restore instructions on the wiki.
