### ISSUE TITLE
Canceled transaction - no popup

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#671]
Normally when a transaction is canceled a popup warns that this will incur a fee. About 4 hours ago I canceled a transaction and got no warning. May be related to recent change to code in this area where we added the amount that would be lost to the popup.

Last change needs review. Refer #615

**Comment by haiqu** [comment]
If the last change is OK then it could have been a lost notification due to this slow UI.

**Comment by ManfredKarrer** [comment]
Did you select "Dont show again"?

**Comment by haiqu** [comment]
Don't remember. I'll reset that flag in Settings and keep an eye out.

**Comment by ManfredKarrer** [comment]
Will close, if you can reproduce please re-open it.
