### ISSUE TITLE
Bad SEPA instructions - payment reason field cannot be empty in my bank

### ISSUE THREAD

**Issue by anon88391** [bisq-network/bisq#6711]
Bisq instructions clearly state that the payment reason field MUST be empty when sending a SEPA transfer.
However, my bank does not allow the payment reason field to be blank. It requires at least a single character, but I wouldn't be surprised if other banks required more. 
According to the [Table of Penalties](https://bisq.wiki/Table_of_penalties), not leaving the field empty would most likely constitute "Using unagreed payment reference" and result in a 10% penalty for the buyer.

Please reevaluate and clarify the instructions, perhaps add a statement that when the field can't be empty it should be a dash ("-") character or just the name of the account owner.

**Comment by pazza83** [comment]
Hi @anon88391 

Thanks for posting this.

The rules state:

> If you are required to fill in a reason, use your account name eg "Joe Bloggs" alternatively enter something non-descriptive like a dash

Ref: https://bisq.wiki/Trading_rules#Leave_the_.22reason_for_payment.22_field_empty

Does this cover what you are asking for?

**Comment by anon88391** [comment]
@pazza83 
In that case I think it should also be clarified in the Bisq client, because it does not mention this.
Below is a screenshot of the only instructions that I got in Bisq client. It left me very confused because it was impossible for me to fully comply with them.
![2023-05-29_21-28-15](https://github.com/bisq-network/bisq/assets/35631947/6aa75bea-9573-479e-bc79-ca41fcaa2a70)

**Comment by pazza83** [comment]
Yes that is a good idea.

Are you able to send a full screenshot of the message?

Many thanks

**Comment by anon88391** [comment]
@pazza83 I wasn't able to provide a screenshot as I wasn't using Bisq until today, but the screenshot above contained most of the message. Today I took a screenshot of the message again (identifying information redacted), but it's mostly the same thing.
I want to reiterate that the message sounds like a '-' payment reason would be unacceptable.
![Screenshot](https://github.com/bisq-network/bisq/assets/35631947/b5b52052-3a02-44e7-b615-2e9d25a69008)

**Comment by pazza83** [comment]
Please would one of the devs be able to update the text above to add the following sentence after 'BTC' or Bisq'.

> If you are required to fill in a reason, use your account name eg "Joe Bloggs" alternatively enter something non-descriptive like a dash

**Comment by pazza83** [comment]
This still requires actioning

**Comment by kiocos** [comment]
@pazza83 @anon88391  I opened a PR for this, lmk if you guys think that should be enough:
https://github.com/bisq-network/bisq/pull/6974

**Comment by pazza83** [comment]
@kiocosta many thanks for picking this up
