### ISSUE TITLE
Connection to the Bitcoin network failed because of an error: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.

### ISSUE THREAD

**Issue by pprvggc6um** [bisq-network/bisq#6714]
### Description

Bisq had been working without issue for a while
had to restart system for something

Start Bisq
In less than a minute, get java exception

Warning
Connection to the Bitcoin network failed because of an error: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.

#### Version

1.9.10

### Steps to reproduce

I do not know how to reproduce this issue.

### Expected behaviour

Bisq should start normally

#### Device or machine

HP laptop
Windows 7 Pro
Version 6.1.7601 Service Pack 1 Build 7601

#### Additional info

Bisq had been working without issue for a while
had to restart system for something

Start Bisq
In less than a minute, get java exception

Warning
Connection to the Bitcoin network failed because of an error: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.

![java lang IllegalStateException](https://github.com/bisq-network/bisq/assets/121187130/e1ed277d-f734-4d73-8fbe-0fa57f387295)

click close

After a while with a screen reporting no connection to tor network

![connection-failed](https://github.com/bisq-network/bisq/assets/121187130/2d303766-00a0-401d-b117-d0692b8a16a7)

Get the "Connection problems" screen
![delete-tor-files](https://github.com/bisq-network/bisq/assets/121187130/fccb6da6-b4f6-4cb1-8cd2-d59eb1e65690)

Click "Delete outdated tor files and shutdown"

Tor file deletion completes
![tor-deleted](https://github.com/bisq-network/bisq/assets/121187130/1aa5eb34-aa07-47ef-a846-fd4315a6e6c6)

click shutdown

Start up Bisq again

Back to the java exception error and then the "Connection Problems?" screen suggesting to delete outdated tor files and shutdown.

I moved my data directory aka started up Bisq with a new profile, and this started as expected.

Bisq log file:
[bisq.log](https://github.com/bisq-network/bisq/files/11578189/bisq.log)

**Comment by adrie0** [comment]
> ### Description
> Bisq had been working without issue for a while had to restart system for something
> 
> Start Bisq In less than a minute, get java exception
> 
> Warning Connection to the Bitcoin network failed because of an error: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.
> 
> #### Version
> 1.9.10
> 
> ### Steps to reproduce
> I do not know how to reproduce this issue.
> 
> ### Expected behaviour
> Bisq should start normally
> 
> ### Actual behaviour
> ### Screenshots
> #### Device or machine
> HP laptop Windows 7 Pro Version 6.1.7601 Service Pack 1 Build 7601
> 
> #### Additional info
> Bisq had been working without issue for a while had to restart system for something
> 
> Start Bisq In less than a minute, get java exception
> 
> Warning Connection to the Bitcoin network failed because of an error: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.
> 
> ![java lang IllegalStateException](https://user-images.githubusercontent.com/121187130/241274940-e1ed277d-f734-4d73-8fbe-0fa57f387295.PNG)
> 
> click close
> 
> After a while with a screen reporting no connection to tor network
> 
> ![connection-failed](https://user-images.githubusercontent.com/121187130/241275467-2d303766-00a0-401d-b117-d0692b8a16a7.PNG)
> 
> Get the "Connection problems" screen ![delete-tor-files](https://user-images.githubusercontent.com/121187130/241275554-fccb6da6-b4f6-4cb1-8cd2-d59eb1e65690.PNG)
> 
> Click "Delete outdated tor files and shutdown"
> 
> Tor file deletion completes ![tor-deleted](https://user-images.githubusercontent.com/121187130/241275602-1aa5eb34-aa07-47ef-a846-fd4315a6e6c6.PNG)
> 
> click shutdown
> 
> Start up Bisq again
> 
> Back to the java exception error and then the "Connection Problems?" screen suggesting to delete outdated tor files and shutdown.
> 
> I moved my data directory aka started up Bisq with a new profile, and this started as expected.
> 
> Bisq log file: [bisq.log](https://github.com/bisq-network/bisq/files/11578189/bisq.log)

Hi @pprvggc6um visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Bisq Support](bisqwiki.online)

**Comment by appideias** [comment]
Same here.

**Comment by pazza83** [comment]
An SPV resync should fix this:

https://bisq.wiki/Resyncing_SPV_file
