### ISSUE TITLE
Clicking the payment started button when buying btc results in an error message: "Message of payment sent but not yet received by peer"

### ISSUE THREAD

**Issue by Iyd4raf** [bisq-network/bisq#6715]
Clicking the payment started button when buying btc results in an error message: "Message of payment sent but not yet received by peer"

#### Version

1.9.10

### Steps to reproduce

1. Accept a BTC buy order
2. Click the payment started button once you have sent payment by bank transfer
3. Two different error messages appear. Either this message (paraphrased) is displayed next to the payment started button: "Sending confirmation failed. Please try again". Or the message shown below in the screenshot appears instead: "Message of payment sent but not yet received by peer".
4. The transaction is stuck on this stage because I cannot proceed

### Screenshots

![Capture](https://github.com/bisq-network/bisq/assets/43270055/a6567abe-bb37-4228-a667-111de43028bb)

#### Device or machine

windows 7

**Comment by pazza83** [comment]
Maybe the trade peer is offline or has trouble with their Bisq.

Once the trade window time is up you can open mediation to get support from a mediator.

https://bisq.wiki/Dispute_resolution

**Comment by Iyd4raf** [comment]
Thanks, this has been resolved - it seems that the peer was offline
