### ISSUE TITLE
Deposit Funds listview still messed up

### ISSUE THREAD

**Issue by ElLamparto** [bisq-network/bisq#672]
After opening, everything is ok: 0.0088 BTC belongs to an address "...PATEJ"
![funds_depositfunds01](https://cloud.githubusercontent.com/assets/9163437/19641104/f9678116-99df-11e6-8863-fec30cf0aea3.png)

After scrolling up, 0.0088 BTC suddenly appeares at address "...Ww9Wu" (incorrect):
![funds_depositfunds02](https://cloud.githubusercontent.com/assets/9163437/19641223/2f3163ac-99e0-11e6-9ab0-8783527bdc48.png)

After scrolling down, the address "...PATEJ" holds 0 BTC (incorrect):
![funds_depositfunds03](https://cloud.githubusercontent.com/assets/9163437/19641296/68d0210c-99e0-11e6-836e-33da56ce7c53.png)

bitsquare 0.4.9.7
Debian Jessie 32bit

**Comment by ManfredKarrer** [comment]
I will have a look...

**Comment by ElLamparto** [comment]
Thanks.
Bitsquare runs 4 days with no crash - the null pointer exception seems to be solved. :)

**Comment by ManfredKarrer** [comment]
Thanks for the update. I could nto reproduce the issue, so will close until anyone reproduce it.
