### ISSUE TITLE
SEPA payments should allow "Gibraltar" as bank country

### ISSUE THREAD

**Issue by pandascrape** [bisq-network/bisq#6721]
### Description

I cannot add my EUR bank account because it is Gibraltar based.

#### Version

v1.9.10

### Steps to reproduce

Go to Account > National Currency Accounts > Add New Account
Select "SEPA" as payment method.

### Expected behaviour

'Country of bank' field should accept 'Gibraltar'

### Actual behaviour

'Gibraltar' is not offered, and IBAN code for Gibraltar bank is denied

### Screenshots

n/a

#### Device or machine

Debian 11

#### Additional info

n/a

**Comment by pazza83** [comment]
Hi @pandascrape 

Thanks for creating this issues.

I can see that Gibraltar 'GI' is missing from the list.

I have checked the list of countries / territories with their own IBAN code and Gibraltar is the only one missing.

@jmacxx are you able to add Gibraltar to the SEPA list like in the previous issue: 

https://github.com/bisq-network/growth/issues/209

Apologies for not spotting it last time!

Many thanks

**Comment by pandascrape** [comment]
Thank you. We appreciate you :)
