### ISSUE TITLE
Have a way to distinguish 'proof of burns' between ' burns by burning men' and 'burns for Bisq 2 reputation'

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#6730]
### Description

Similarly to https://github.com/bisq-network/bisq/issues/6729 it would be good if the section 'all proof of burn transactions' could be distinguished between:

- Burns by burning men
- Burns for Bisq 2 reputation
- Other burns

I would propose adding the the following data to the burns:

- Burning Men
- Bisq 2 reputation
- Other

When burning BSQ in 'DAO > Proof of Burn > Proof of Burn' users could be given the option of selecting a reason for the burn between 'Bisq 2 reputation' or 'Other'.

![Capture2](https://github.com/bisq-network/bisq/assets/66367547/d2476477-13e6-48a4-9ef4-07ac98d5d4de)

Burning on 'Proof of Burn > Burning Men' could be automatically tagged as 'Burning Men'

![Capture3](https://github.com/bisq-network/bisq/assets/66367547/12c2fb77-d5b7-4b7c-abdd-4f6c18b07247)

The reason for the burning of BSQ could then be shown in the 'all proof of burn transactions' section:

![Capture](https://github.com/bisq-network/bisq/assets/66367547/5ccdfbc0-3a04-45b5-8d74-525a0074dae1)

This would make for accounting easier as revenue between both Bisq 1 Burning Men and Bisq 2 burning for reputation could be quickly distinguished.  

For example an extra column on the image above to show the 'Reason' for the burning of BSQ.

**Comment by HenrikJannsen** [comment]
Not sure if thats possible with current model. We use just the hash of the preimage with a byte for the version and one for the proofOfWork tx type. We would more another prefix bytes to distinguish the reasons for the burn.
Another hack could be to replace the first 1-2 bytes of the hash with the prefix. But would need to look closer into it if it would have impact on DAO consensus.
For BM we would have the data in BM domain, so I guess there is no need beside for double checking to get that data from the POB.
For Bisq2 I need to look into the details. There that hack to replace some bytes of the hash with a marker could work, of if there is no size limit from DAO consensus side (I guess there is) we could just add those. 
But also there it will go over the Bisq1BridgeNode and there we could get some aggregated data.

**Comment by pazza83** [comment]
Thanks for the explanation.

Another way to distinguish 'proof of burns' between ' burns by burning men' and 'burns for Bisq 2 reputation' would be to include the amount of BSQ burned by burning men per month in the 'Report' function in DAO > Proof of Burn > Burning Men.

This would allow for the total Burnt in BSQ per month to be easily accessed.

And if #6729 was implemented then 'Total BSQ burns' - 'Burns by Burningmen' = BSQ burnt for reputation and other.

**Comment by HenrikJannsen** [comment]
Yes I was thinking also to add that. Maybe @jmacxx has some bandwidth to do that. If not ping me again and I will look at it.
