### ISSUE TITLE
For input string: "301feea14f47b7136043"

### ISSUE THREAD

**Issue by Monero-Mo** [bisq-network/bisq#6731]
### Description
Bisq would not load, just sync with mainnet.

### Steps to reproduce
tried to open it and this happened

#### Device or machine

Device name	DESKTOP-SC9VU9B
Processor	Intel(R) Core(TM) i7 CPU       Q 740  @ 1.73GHz   1.73 GHz
Installed RAM	6.00 GB

System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Home
Version	22H2
Installed on	‎10/‎8/‎2021
OS build	19045.2965
Experience	Windows Feature Experience Pack 1000.19041.1000.0

**Comment by Monero-Mo** [comment]
[bisq.log](https://github.com/bisq-network/bisq/files/11754308/bisq.log)

I think this is how you save a log file

**Comment by ghost** [comment]
Looks like some sort of database corruption.  I suggest you start fresh.  https://bisq.wiki/Switching_to_a_new_data_directory

You can get assistance from support personnel in the matrix support channel: https://bisq.wiki/User_support
