### ISSUE TITLE
technical issue: can only see 1 UTXO line in "send funds" layout

### ISSUE THREAD

**Issue by Renitend** [bisq-network/bisq#6743]

**Comment by Renitend** [comment]
![Bisq](https://github.com/bisq-network/bisq/assets/131745865/2fb5db94-b9c7-467d-a9de-e418f970836d)
It looked like this before I changed the width of the window. By making it less wide I could see 1 Line
![with line](https://github.com/bisq-network/bisq/assets/131745865/d84473e7-32c9-49a6-ac8e-b1cba4ac5e88)
Thats better now but to be able to see more lines would be nice. Can anyone help? thank you

**Comment by Renitend** [comment]
I received your email, clicked on the link an got to Bisqwiki "Getting started". 
Had to open up another account, the third one now and was not able to find the Bisq support Chat.
Why is it made so difficult?
Why cant you just give me a link that gets me to where I have to go?
why cant we just go ahead on this page.
For the commision you charge you could give a better support, it took 4 days to get a not usefull answer.
Thank you so much

**Comment by ghost** [comment]
@Renitend the person you responded to above is a scammer, and their site is fishing to steal user funds in guise of pretending to be support.  Bisq admins delete and block their posts but they always post again.  Please be careful.  Do not interact with their fake support site.

Thanks for sending your bug report and it is being worked on. The issue of screen layout in Send Funds will be addressed in a future release of Bisq.

**Comment by pazza83** [comment]
Hi @Renitend 

I have blocked the spammer.

But in my haste I have hidden your post by accident. 

Please can you repost.

Many thanks
