### ISSUE TITLE
Miner fee not sufficient anymore

### ISSUE THREAD

**Issue by MarcSte** [bisq-network/bisq#676]
With regard to the recent transaction backlog increase, a miner fee of 0.0002 BTC is not sufficient anymore.

https://blockchain.info/unconfirmed-transactions

I found a complaint of a user who had to wait 18h for the first confirmation.

[See here](https://www.reddit.com/r/Bitcoin/comments/59h6b0/why_there_is_huge_amount_of_transactions_with/d98gn9h/)

I consider this to be quite urgent as it worsens UX directly.

**Comment by jonathancross** [comment]
Shot in the dark: Looks like fees were increased dramatically in bitcoinj back in March: https://github.com/bitcoinj/bitcoinj/pull/1232/files
But the Bitsquare fork is much older than that.

If upgrading bitcoinj is not an option, here are some services providing fee predictions as an API:
- ~~https://bitcoinfees.21.co/api~~ (captcha unfortunately)
- ~~https://www.blocktrail.com/api/docs#api_fee_per_kb~~  (captcha unfortunately)
- Bitgo (works in Tor browser): https://www.bitgo.com/api/v1/tx/fee?numBlocks=1 
- Bitcoin Core makes this available via `bitcoin-cli estimatefee 1`.  It might be possible to get that value from blockchain.info via an [API call](https://blockchain.info/api) to their Tor hidden service (blockchainbdgpzk.onion).
- https://api.blockchain.info/fees - Works over Tor with no captcha.  Looking into option using their Tor hidden service now.

There are probably others that could be used.

**Comment by haiqu** [comment]
I agree, seeing similar delays here.

**Comment by ManfredKarrer** [comment]
Most time when users complain about stuck tx is it because one of the traders funded the wallet with a super low fee. If the guy from reddit can post the deposit tx, then we can see more.
We use fixed a fee of 0.0002 for all trade tx (trade fee, MS). That is about 50-90 satoshi which is still a good value.
To make it dynamic makes the trade process more complex (both users need to have the same values). 
Changes in that area would also break backward compatibility, so I want to queue such changes up to a moment when we have a  bigger update (DAO).
But agree we need an API call to get adopted to crazy situations. 
Apis which require an API key are problematic as we are P2P and OS. And as @jonathancross already filtered it must be tor compatible.

Seems there is a new spam attack ongoing to bring the Bitcoin price back down...
https://tradeblock.com/bitcoin/
https://bitcoinfees.github.io/#1d
http://p2sh.info/dashboard/db/fee-estimation

**Comment by MarcSte** [comment]
> Most time when users complain about stuck tx is it because one of the traders funded the wallet with a super low fee. If the guy from reddit can post the deposit tx, then we can see more.
> We use fixed a fee of 0.0002 for all trade tx (trade fee, MS). That is about 50-90 satoshi which is still a good value.

I guess it's not as urgent as I thought. I just had an offer accepted and the deposit tx was confirmed within minutes. Though, I observed with trades for a while that confirmations can take hours from time to time. Your reasoning makes sense to me.

I asked the reddit guy to provide the deposit tx. We'll see if he replies.

Also the backlog is declining quickly now.

**Comment by ulrichard** [comment]
I had three trades in the past week that took almost 24 hours to get included in a block.  One was with Manfred.

The estimatefee can also be queried at the public electrum servers.
`$ (echo '{"id":5,"method":"blockchain.estimatefee","params":[5]}';sleep 2) | ncat --ssl ulrichard.ch 50002`

**Comment by ManfredKarrer** [comment]
Can u send me the tx id?

**Comment by ulrichard** [comment]
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQEMAwAAAAAAAAAAAQf/ctI/io6VUBoShUbaPiQGERFUynKK9vrDvuNcx79TjzUQ
dQKkIn2IZf1NU5l/w0SSkxScisVk19gCpw3y//k9DyvH4AvllN3EeR7A6Z7Ear6T
b9RLXSr/yN5fh/S9OzC6Z2zgn+oKUX3KZv0eNmffNZSdik0XeOq+L2pBxMcOspfI
wvuDx+9u6+4B+shOaq+MTD5IAWF8dp4L0nVkqttSr0+7sd52AsfkHOKWVVT0rA0h
dm8FHkgqRVjK380vhttxQxmZd0M36JKpkLSrs5kBBsuzHUWjxCtVgcrxYCGpAwb2
s5bwqmJ7dfkCybUzEnk+GYVoMB4kdcHyidXgbfQn/NLAMwG3Rm1DSRu/x6pTKvWN
ScjW5OYQsDanesd7S01cMFiPjzkaQP/qQaBnSbJ5K8+Dfn8fsYEGGJDdqKhj09bs
9osxwexPKZ0iNIgBGs7OyjIGGWHG5duSCTrCOg+riRIoZpqK/zW4QLUFEPb+RBnP
0C3DWda9+uZgYjrhuiGeYSIWptW3JgxhPgowG6tyBdbaM66O31+hk0OVFxNODitB
w/Awoywn2dDs0pibQJ2RRr/juqk4W9bcmUUcVcOhb+DyohhzsShB3XfTdpr2AiSx
BDaidRLLxfgsH97YbmvTFPhtWN+6TaBIy8IhlHIycw7g2B4niA==
=iuia
-----END PGP MESSAGE-----

I noticed that blockchain.info didn't show the tx before it was included in a block. The errormessage was that it contained a non standard script. blocktrail.com  displayed it shortly after broadcasting.

**Comment by ulrichard** [comment]
And here is a more recent one.

-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQEMAwAAAAAAAAAAAQf+NgsjKgZk0rLWQGvSqrBjWw710iLPXgKGi5cCRAI7dyAs
clqUK6MHcVib9ltlUb643hYH1YLP3pX1mMxWamQjbqC4wWtozxSzww2grLQgMcr9
baV3rbuHz15fx4cHRiHd34SIZzx13FYn4nBPqsWRZiF8UiCm4KqqhLg1OkjPmrNR
I+kAqadWdBnUM+VmnCy8SoiwkqY0BI3poGgqlWiGnjIiUcHy0wSI72Ee4Smuf7Y2
veQ02tNpKsLG04k5QRJM77iZyoTr9YEqQ4d5oZ2pJlIWerlLWv2MT1dp5qB4QQRq
lbQzLUGDpGLhsEOrtRV7p6uTqsfrvfDrSHU4zvflv9LAmwHNLNgj3prIBZAgDJgd
O4624gwQGp8LfhkCyq+oQXe/AHhmHrTftMwIKMgVh3hZTGkdU2fL4uEY3iFokNYS
uxyJGG+1rcbdNumX6IlAUya6HgIv1T1Lf/uLfe6y1aOXDqOCSBHfFBPX/WXDeC2R
t+KO/B0muToFYLCbULXqslFUaGTZF8Z6zDKayyWGiEXksdOO1UuDGchQeAE9/e+1
qTAdRJ31Hy4HHD9Xfue72ZlNVYzeTVcgu3vdKCvTmQkju38EUoX7tOzrFeN82hlM
7g4KMqB//NLxlFv94iedeob7TxeT7zBVFiAQqnW7FVIbIVH+3UMWqGRBM3pJqxyP
4AqpM+1JFVehqWaSYmM6223+4ff/cY5H07m3ztrpcrBq6l0p0KhG3n9kkbi7GRoN
wklYsHbz2DNvcq5/1SC3biKT4+q7tSEk/N+O27wFvhXihtLjfNtmAVO433Yb
=//Lr
-----END PGP MESSAGE-----

This one was also not displayed by blocktrail.com for about 15 hours after broadcasting. This was an altcoin tx. By the time the tx was in a block, the 24 hours for altcoin trades were up.

**Comment by ManfredKarrer** [comment]
Which PGP key did u use? Can u send me it by email?

**Comment by ManfredKarrer** [comment]
Will close that as there is already code prepared for using fee estimation services and a dynamic tx fee. Will be released with a bigger code change so it might take a bit longer as usual.
