### ISSUE TITLE
US Postal Money Order time too short

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#677]
The US Postal Money Order selection of payment method only gives 4 days for a transaction to complete. Probably should be extended to 7 days.

**Comment by ManfredKarrer** [comment]
Do we have some data/user feedback how long it takes?

**Comment by haiqu** [comment]
I don't think anyone has used it, there are very few US based traders so far. But a standard delivery letter from East coast to West coast would take 3 days on average so 4 days seems to be cutting it fine, especially for remote locations or PO boxes.

**Comment by ManfredKarrer** [comment]
I have seen some trades. 
Ok I will increase it for the next version. But maybe if you like to ask in the forum for some facts from US traders would be good.

**Comment by haiqu** [comment]
Thanks. If US Post is anything like Aus Post then it will be needed. I ordered some Micro SD cards last weekend from Sydney and I'm still waiting for them. That's less than 1000km trip.

BTW we also have Postal Money Orders in Australia. Not sure if anyone uses them now but they're available.

**Comment by ManfredKarrer** [comment]
Set to 8 days in latest version.
