### ISSUE TITLE
Error deposit timeout

### ISSUE THREAD

**Issue by nicarich** [bisq-network/bisq#6775]
### Description

attempt to sell results in an error after accepting offer and confirmation that wallet is funded. failure occurs when performing final confirmation to accept the offer. Never completes, timed out.
error
An error occurred when taking the offer.
Timeout reached. Protocol did not complete in 120 sec.
Please restart your application and check your network connection to see if you can resolve the issue.

This began after accepting/performing the v1.9.12 update. I believe this caused the problem. Attempted 4 trades, with 2 complete computer recycles.
............................................
Attention
the deposit transaction (2 of 2 multisig) is missing
without the deposit transaction the trade cannot be completed
  trade ID's
28819-254e9d8e-4ed6-4d34-bbf1-3abacc992113-1910
KIQVSBXV-ecb2cd9f-d38a-436c-aac8-a3844d25c560-199
QVGRP-f203c51d-64a1-4d0d-8a3b-e5356ba61fe7-199
56oti3xo-9586111f-3281-48af-b0bb-6db1a821eb58-1912

v1.9.12    Version

### Actual behaviour

confirmation timeout. system suggestion to move to failed trades

### Screenshots

attached

#### Device or machine

HP EliteDesk 800 G3 DM 35W  2.80 gigahertz Intel Core i7-6700T .......windows 10 pro

Contract as json:
{
  "offerPayload": {
    "id": "28819-254e9d8e-4ed6-4d34-bbf1-3abacc992113-1910",
    "date": 1689698449490,
    "ownerNodeAddress": {
      "hostName": "yvq3lf427cwhz7zhapj43evxo7oixfcjtmvnim5p6ynvcqbbi6zgyoad.onion",
      "port": 9999
    },
    "direction": "BUY",
    "price": 0,
    "marketPriceMargin": -0.02,
    "useMarketBasedPrice": true,
    "amount": 3000000,
    "minAmount": 3000000,
    "baseCurrencyCode": "BTC",
    "counterCurrencyCode": "USD",
    "arbitratorNodeAddresses": [],
    "mediatorNodeAddresses": [
      {
        "hostName": "6c4cim7h7t3bm4bnchbf727qrhdfrfr6lhod25wjtizm2sifpkktvwad.onion",
        "port": 9999
      },
      {
        "hostName": "7hkpotiyaukuzcfy6faihjaols5r2mkysz7bm3wrhhbpbphzz3zbwyqd.onion",
        "port": 9999
      }
    ],
    "paymentMethodId": "CLEAR_X_CHANGE",
    "makerPaymentAccountId": "7750b629-f38d-4cb7-8d54-8038afc24811",
    "offerFeePaymentTxId": "b86236f5f01d213b79986eff54744312a624116f1fa6479fc9f17a8b9989c55c",
    "versionNr": "1.9.10",
    "blockHeightAtOfferCreation": 799267,
    "txFee": 1750,
    "makerFee": 5000,
    "isCurrencyForMakerFeeBtc": true,
    "buyerSecurityDeposit": 750000,
    "sellerSecurityDeposit": 750000,
    "maxTradeLimit": 10000000,
    "maxTradePeriod": 345600000,
    "useAutoClose": false,
    "useReOpenAfterAutoClose": false,
    "lowerClosePrice": 0,
    "upperClosePrice": 0,
    "isPrivateOffer": false,
    "extraDataMap": {
      "capabilities": "0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17",
      "accountAgeWitnessHash": "b2c964905fde960097c3101b8e5fb60152b98beb"
    },
    "protocolVersion": 4
  },
  "tradeAmount": 3000000,
  "tradePrice": 303328047,
  "takerFeeTxID": "1a8328a9ef2422d9e0393851a75a7e5c63224cb195ad724d704cf6d89b852017",
  "buyerNodeAddress": {
    "hostName": "yvq3lf427cwhz7zhapj43evxo7oixfcjtmvnim5p6ynvcqbbi6zgyoad.onion",
    "port": 9999
  },
  "sellerNodeAddress": {
    "hostName": "dn2qxqtnaapyeoynzuklgridewrefgaqwv33nleskkoxfedqrmtza3qd.onion",
    "port": 9999
  },
  "mediatorNodeAddress": {
    "hostName": "7hkpotiyaukuzcfy6faihjaols5r2mkysz7bm3wrhhbpbphzz3zbwyqd.onion",
    "port": 9999
  },
  "isBuyerMakerAndSellerTaker": true,
  "makerAccountId": "1044922497",
  "takerAccountId": "1046668553",
  "makerPayoutAddressString": "bc1qp8ph838q78pq6pkemkeed8zlwnhmy6hqwpe6gl",
  "takerPayoutAddressString": "bc1qtcw8vungg8xex96ejdmgzehej92n8nmmr0z5fq",
  "lockTime": 802153,
  "refundAgentNodeAddress": {
    "hostName": "3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion",
    "port": 9999
  },
  "hashOfMakersPaymentAccountPayload": [
    86,
    -27,
    21,
    -77,
    -33,
    -62,
    8,
    -18,
    -119,
    -47,
    60,
    3,
    123,
    -40,
    -18,
    59,
    10,
    28,
    -24,
    69
  ],
  "hashOfTakersPaymentAccountPayload": [
    -60,
    -128,
    32,
    53,
    48,
    1,
    -19,
    33,
    -104,
    6,
    75,
    122,
    -63,
    14,
    106,
    24,
    -33,
    34,
    -99,
    42
  ],
  "makerPaymentMethodId": "CLEAR_X_CHANGE",
  "takerPaymentMethodId": "CLEAR_X_CHANGE"
}

Other detail data:

BuyerMultiSigPubKeyHex: 0295c019ea9d44b93d5bfb618cccdf5917ba18b54f1381123fc53fb0557fbbeab3
SellerMultiSigPubKeyHex: 03e7a2b18df3c760d453efba0a2b4d1d68a5c465919f7b4e962f6f9bcad3a1530c

BuyersAccountAge: Payment account age not known.
SellersAccountAge: Payment account age not known.

Selected mediator: leo816
Selected arbitrator (refund agent): refundagent2
[bisq.log](https://github.com/bisq-network/bisq/files/12087921/bisq.log)
![trade1](https://github.com/bisq-network/bisq/assets/139710828/52943ca5-d90d-47b9-812e-529577bea630)
![trade2](https://github.com/bisq-network/bisq/assets/139710828/baac4cd9-6c99-4d2f-908a-208cf5a9630e)
![trade3](https://github.com/bisq-network/bisq/assets/139710828/2530bd90-2c9f-4aeb-8697-d3efe352cafc)
![bisq screenshot1](https://github.com/bisq-network/bisq/assets/139710828/f3c8f9db-ba0d-4912-8e4b-b67365703aa9)

**Comment by ghost** [comment]
You have a failed trade, and the error in the log is `An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same. `

Which means the buyer threw a wobbly during trade setup.  This can mean either their DAO state is corrupted or yours is.  Both of you should navigate to DAO -> Network Monitor and check what it says there.  It might instruct you to resync the DAO state if it detected a problem.  There's also a button in Settings which does the same thing `Rebuild DAO state from resources` and it does not hurt to try it any time you encounter such a problem.

Occasional DAO resyncs and SPV resyncs are just an unfortunate reality in a decentralized system where everything has to be in sync to work properly!

[edit] The same happened for each of your 3 trades, and as they were different peers it points to your DAO needing a resync.

**Comment by nicarich** [comment]
that worked......thanx

**Comment by nicarich** [comment]
that worked... thanx
