### ISSUE TITLE
Discussion: ATM Deposits

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#678]
On 24th Oct I took an offer to sell some BTC for NZD. Method used was supposed to be national bank transfer but instead the buyer used ATM deposit.

This created a problem, and the transaction has now expired and gone to arbitration. The reason I didn't confirm is that there was no identifying information included. See partial snapshot from my account below:

![atm2](https://cloud.githubusercontent.com/assets/13131219/19790730/ed5cc860-9cfd-11e6-9729-625e67e8e9d9.png)

The buyer _might_ have sent from his account, but could also have used a credit card or a cash deposit envelope, so I have to treat this transaction as if it were a cash deposit. That means a copy of the deposit slip, marked "No Refund" and cut in half, sent to my email address.

My thinking on this is that we should modify the Cash Deposit option so it reads:

Cash/ATM Deposit.

That way we completely distinguish this method from national bank transfer. Comments?

**Comment by memetat** [comment]
i had a national bank transfer offer accepted yesterday. (I offered to buy btc) After the bitsquare confirmation, it seemd to continue as a cash deposit, not a national bank transfer. Strange? I dont have a cash deposit set up.

**Comment by haiqu** [comment]
That's a bug, and yes I've seen it. In fact if you're in Australia I may have been the taker.

**Comment by ManfredKarrer** [comment]
I will look into it, might be a bug. 
To resolve the case @memetat should send a photo by PM to @haiqu the receipt with "NO REFUND" written on it and torn in 2 parts. Alternatively u can do it in the dispute chat via the arbitrator (me).

**Comment by haiqu** [comment]
Manfred: See #679 for that bug. Let's return to the ATM Deposit issue ... :)

**Comment by rcarterbrown** [comment]
Hi there, I believe I'm the other end of that trade (962288c6). I'm surprised you didn't receive any identifying information as I used the trade id (962288c6) as the reference on the deposit as instructed. The reason I used an ATM deposit rather than a bank transfer was because of the long weekend and I didn't want to keep us all waiting for two days to complete the trade.
How would you like to proceed?

**Comment by haiqu** [comment]
Hey, nice to see you. I've thrown that one through to the arbitrator with a suggestion to treat it like a Cash Deposit. Essentially that means I'll need a copy of the deposit slip, with "No Refund" written on it and cut in half. You can email it to `judd AT ob-wan DOT com`.

Sorry for the inconvenience but it looks like ATMs don't pass the details on to the account holder.

**Comment by rcarterbrown** [comment]
You too. Done. I wonder if the lack of info being passed on is an isolated incident or a wider issue
?  I have made many ATM deposits to a BTC exchange who also use Wespac who seem to have received the details in the reference field. I actually made a deposit at the same time at the same smart ATM to them as this problematic deposit.

**Comment by haiqu** [comment]
No, it's standard to not forward details with a cash deposit. Same thing happens if you go to the counter and hand it to them. Anyhow, it's all good. You should have your bitcoin soon. :)

**Comment by rcarterbrown** [comment]
Thanks :)
