### ISSUE TITLE
“Connecting to bitcoin network (1/4)"  Fail

### ISSUE THREAD

**Issue by Justus1776** [bisq-network/bisq#6784]
### Description

After installing update 1.9.12 bisq gets stuck at “Connecting to bitcoin network (1/4)"  Fail 

The previous version (1.9.10) was working fine.  It was after the update I had this issue.
![image](https://github.com/bisq-network/bisq/assets/122484697/81827304-ef1f-4176-8760-5fb22fc673ab)

After about 5 or so mins or so the next screen comes up 
![image](https://github.com/bisq-network/bisq/assets/122484697/5f655d5e-6405-4624-b201-89acf82635e6)

#### Version

Current version is 1.9.12

### Steps to reproduce

All I had to do was open the program.  It does not continue to the actual application where trades can be made

### Expected behaviour
to go to the page where I can make trades on bisq

### Actual behaviour
it gets stuck here.  I cant get past these screens

#### Device or machine

Windows 10

LAPTOP-OA37N952
Processor	Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz   1.50 GHz
Installed RAM	16.0 GB 
Device ID	C4570831-81F3-45DB-9F3E-239AFE977E29
System type	64-bit operating system, x64-based processor

#### Additional info

I searched some of this similar issue on the github form... none of what I tried worked.  I also tried to  uninstall reupload the 1.9.10 version but it wouldn't let me.  So i reinstalled the current version.  But to no avail.  Please advise.

**Comment by ghost** [comment]
Someone posted a similar issue & resolution here: https://bisq.community/t/bisq-stuck-connecting-to-tor-at-step-1-4/12176

Also https://bisq.wiki/Last_resort_restore is a solution developed by the support team staff.  It seems to have been successful as a last resort.

**Comment by hugoender** [comment]
I'm having this exact issue and that thread @jmacxx provided did not help. I've been using Bisq for over a year without problem and I think this starting happening after the last update.
