### ISSUE TITLE
Timed out buy...

### ISSUE THREAD

**Issue by MrBass01** [bisq-network/bisq#6786]
### Description

As the tile say, after 120s the order was "timed out". The log file attached: From the chats, I think that it might be possible that my the settings for MTXX might be wrong, but how (if so).

### Screenshots

[bisq.log](https://github.com/bisq-network/bisq/files/12186595/bisq.log)

**Comment by pazza83** [comment]
Often this is a false error.

Was this error message in relation to a trade you made.

If so have you checked the deposit confirmation? Was it confirmed?
