### ISSUE TITLE
Allow mediators to export chat log to send to arbitrator

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#6798]
In the same way that traders can export chat logs for a specific trade to send to a mediator, it would be useful for mediators to be able to export chat logs for a specific trade to send to the arbitrator. 

I would anticipate the buyer and seller chat logs would need to be exported separately.

It would make providing information to the arbitrator easier in situations when the arbitrator requires more info. Currently screen shots are used which is time consuming and less efficient than how traders provide there chat logs to mediators.

**Comment by pazza83** [comment]
Hi this would still be good to have. @jmacxx are you available to implement this?

**Comment by pazza83** [comment]
Hi @jmacxx are you able to look into this? Many thanks

**Comment by ghost** [comment]
As discussed with @pazza83 this was already implemented via a `COPY` button to clipboard.

**Comment by pazza83** [comment]
Hi @jmacxx many thanks for implementing this it works great.
