### ISSUE TITLE
Error message: Validation of Taker Tx returned: [fee address: bc1qj62pl9d06c2f4dzutnqsn7nv0gvy7k7gwhlv3c was not a known BTC fee receiver, Taker tx validation]

### ISSUE THREAD

**Issue by MPatri19** [bisq-network/bisq#6813]
Open Support ticket
There is an issue with a missing or invalid transaction.

Please do NOT send the fiat or altcoin payment.

Open a support ticket to get assistance from a Mediator.

Error message: Validation of Taker Tx returned: [fee address: bc1qj62pl9d06c2f4dzutnqsn7nv0gvy7k7gwhlv3c was not a known BTC fee receiver, Taker tx validation]

Sorry if I'm at the wrong place to ask this.

#### Additional info

[bisq 1.log](https://github.com/bisq-network/bisq/files/12355278/bisq.1.log)

**Comment by ghost** [comment]
Thanks for the report, it was helpful.  

A [software bug](https://github.com/bisq-network/bisq/pull/6814) caused the checking to falsely flag the offer.


Your trade should be able to be completed either by ignoring the message, or getting mediator assistance.

**Comment by MPatri19** [comment]
Thanks for the reply!
