### ISSUE TITLE
Wise: allow to specify account name instead of email

### ISSUE THREAD

**Issue by nikicat** [bisq-network/bisq#6817]
### Description

Wise: specify name instead of email in profile

#### Version

1.9.12

### Steps to reproduce

Start creating a TransferWise account. Bisq requests an email, but incoming Wise payments do not provide a sender email address, only a name, so a receiver cannot verify the account.

### Expected behaviour

Been able to specify a Wise name on the account creation screen and check it on a trade confirmation screen.

### Actual behaviour

Only email is shown, but it's useless now (I guess after a Wise update).

**Comment by nikicat** [comment]
@pazza83 Hi, could you take a look?

**Comment by pazza83** [comment]
Hi @nikicat 

Thanks for the chase up.

Yes this is an issue. A name would help identify the payment.

At the moment it relies on email being suggestive of the name, confirming with the trader in trader chat, or opening mediation for the trade.

Has this been problem with your trades or have you managed to get it resolved?

**Comment by nikicat** [comment]
I always ask for a trader's name and/or transfer number from a counterparty, but this doesn't prevent a "triangle" scam - the scammer can as well ask the actual sender for this data and just forward it to me. The only way to be sure enough is to have counterparty credentials bound to his account and signed.

**Comment by pazza83** [comment]
@nikicat

Ok thanks for the response. 

I agree that adding the name to `account owner full name` field to TransferWise payment method would mitigate for the risks you mention.

@jmacxx are you available to do this? If so please comment below and I will add another few payment methods for where this is the case with.

**Comment by pazza83** [comment]
Hi @jmacxx 

Please can you add the field `Account owner full name` to the following payment methods:

- TransferWise 
- [MoneyBeam (N26)](https://github.com/bisq-network/bisq/issues/4809)  
- Pix

All these payment methods have a similar issue when it comes to the seller verifying the payment.

Many thanks

**Comment by kiocos** [comment]
I'm working on it
