### ISSUE TITLE
Fresh client always prompted DAO out of sync after initial bootstrap.

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#6823]
#### Version

1.9.12

### Steps to reproduce

- Start Bisq as a new user with no data directory.
- Wait for it to finish sync.
- It pops up a message that the DAO is out of sync, prompting you to go to DAO Network Monitor.

![image](https://github.com/bisq-network/bisq/assets/47253594/ac3af1e9-4309-4a4a-995b-f875773716da)

![image](https://github.com/bisq-network/bisq/assets/47253594/cf2df587-a935-4d2a-b9b2-4188704c1bb9)

### Additional info

The same thing happens to a seednode.  Its DAO state does not match consensus.
Workaround in that case is to shut down, delete `DaoStateStore` and `BsqBlocks` then restart.

**Comment by pazza83** [comment]
This is still an issue.

Also happens after:

- SPV resync
- Any period of not using Bisq for a while

Blockchain will sync but the DAO will not until a subsequent restart.
