### ISSUE TITLE
Warning Connection to the Bitcoin network failed because of an error: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was DEAD.

### ISSUE THREAD

**Issue by appideias** [bisq-network/bisq#6844]
### Description

When trying to start the App it shows this error message: 
Warning
Connection to the Bitcoin network failed because of an error: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was DEAD.

#### Version

Version: 1.9.12

### Steps to reproduce

Start
After a while a window pops with the error: Warning
Connection to the Bitcoin network failed because of an error: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was DEAD.

The following screen shows:

<img width="989" alt="Screen Shot 2023-08-29 at 16 35 29" src="https://github.com/bisq-network/bisq/assets/17833655/9519c39e-027d-4b53-84e9-78224dead4fb">

I tried every given option, but nothing fixed the issue.

#### Device or machine

I'm on a macbook running macOS 11.7.9.

#### Additional info

I think the problem started after I tried to use RBF to a transaction that was taking too long to be confirmed.

Any thoughts? I can't access anything on Bisq anymore...

**Comment by sumsibrum** [comment]
i have the exact same issue ,-(

**Comment by appideias** [comment]
Tried to download a reinstall. Same issue.
