### ISSUE TITLE
Crashes ALT-Tab behavior on GNOME Shell (Arch)

### ISSUE THREAD

**Issue by stevenroose** [bisq-network/bisq#685]
When Bitsquare is open, ALT-Tab doesn't work on my Arch Linux laptop using GNOME 3 (GNOME Shell).

I have no idea how this happens, I'm no export on how GNOME does alt-tab or how Bitsquare might influence that.

**Comment by ManfredKarrer** [comment]
Was that with using jdk 7? If so can you try to use the latest jdk and see if that is the same?

**Comment by Piste** [comment]
@stevenroose should we keep this issue open? What were the results of trying Manfred's suggestion?

**Comment by stevenroose** [comment]
I moved from Gnome Shell to Awesome recently, and it still breaks the whole WM. I have this java now:
```
java -version 
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by stevenroose** [comment]
It's up to you do decide, but Bitsquare is very unstable in Linux desktop/window managers in my experience. It somehow breaks some rules that confuses the WMs into not knowing what's going on.
