### ISSUE TITLE
UI doesn't scale on HDPI displays (f.e. 4K)

### ISSUE THREAD

**Issue by stevenroose** [bisq-network/bisq#686]
I have a laptop with a HDPI display. Most native apps do automatic scaling up, however some do not respect the scaling factor (it's in global settings). Bitsquare does not scale, making the buttons and text ridiculously small.

I bet the UI framework Bitsquare uses has an option to enable this.

Here is a screenshot:
![](https://i.imgur.com/MOaWkGs.png)

**Comment by ManfredKarrer** [comment]
JavaFX supports HDPI and as far I know on Mac it works fine. Though there might be some systems where it fails.... Which Laptop/OS/graphic card are u using?
Scaling the layout is on the todo list.

**Comment by stevenroose** [comment]
Laptop: Dell XPS 15 9550
OS: Arch Linux
GPU: Intel Integrated Graphics
Window Manager: Wayland
Display Manager: GDM
Desktop Manager: GNOME 3
Java: OpenJDK 8
Bitsquare: v0.4.9.8

**Comment by ulrichard** [comment]
Same with XPS13 Ubuntu 16.04

**Comment by ManfredKarrer** [comment]
@stevenroose Did you got that issue when using the java 7 jdk? If so I expect it is caused by that. I am surprised that it is working at all with java7. 
@ulrichard Do you get that issue with running from source of with the binary? If running from source, which jdk version are u using? Openjdk or Oracle?

**Comment by stevenroose** [comment]
I'm using OpenJDK 8. And Bitsquare latest release v0.4.9.8.

**Comment by ulrichard** [comment]
I'm using the binary deb package.

**Comment by moodx** [comment]
HP X360 4k laptop with linux mint, resolution 3840 x 2160. Bitsquare is not scaling correctly. I would realy like to use this program but text is too small to work with it. Is there any progress made yet?

Thx!

**Comment by ManfredKarrer** [comment]
@moodx: If u are a developer you could help to figure out why it is not scaling correctly. Let me know then I instruct you how you can help. I cannot really test as I don't have any laptop where scaling is incorrect....

**Comment by ManfredKarrer** [comment]
Got that link posted from a user who had the same issue on Ubuntu:
http://askubuntu.com/questions/526484/fix-scaling-of-java-based-applications-for-a-high-dpi-screen 

I will offer a bounty for the one who provides a fix for it (get in touch to negotiate amount). Need to be java native fix (prog or vm arg or code fix) not an external script of OS setting adjustments.

**Comment by sqrrm** [comment]
I have had a look at this. Not easy to make it scale properly as I can't find a standard way to do it. Tried modifying a majority of the specific pixel setting in the gui to scale for dpi as seen on startup. That works on ubuntu 16.04 for a dell xps 15 which I have. It doesn't work for all window managers for linux however. Making that an optional setting, something like -forceDPI xx, works fine though.

I have no idea how this would look in windows or on mac. It might be that using the dpi from Screen.getPrimary().getDpi() will make it scale first manually in the app and then automatically through the system and make it double the size. If that's the case only providing a -forceDPI option might be better.

Will push something when I've gone through the remaining parts of the gui, as time permits.

**Comment by ManfredKarrer** [comment]
Thanks a lot! The issue is not happening often, so I think those (I assume mostly Linux) who run into the problem can work around it with the -forceDPI option. We could add that to the settings and maybe display what they system reports with Screen.getPrimary().getDpi() so it gives some hints what to use.

**Comment by sqrrm** [comment]
There now is a pull request for this. It would be a good idea to test it on different platforms. I've probably missed some small things that might not scale perfectly but seems to work in general.

No documentation or help added to be able to use scaling.

**Comment by ManfredKarrer** [comment]
Thanks. I responded in the PR....
Can you use that branch for upcoming PRs? https://github.com/bitsquare/bitsquare/tree/UI_scaling_issue_686

**Comment by sqrrm** [comment]
The previous PR was closed in favor of using the JDK9 native scaling. There are some incompatibilities between 8 and 9 but with JDK9 there is a Multi Release feature to allow for jars that can be run under either. If that actually works for this case I think it would be the nicest way to allow for the use of JDK9 for those that are prepared to use the new framework while normal bisq dev stays on 8 until ready to move to 9 (if ever).

**Comment by ManfredKarrer** [comment]
We ship the JDK in the application so the JDK 9 should be ok even if the user has locally a JDK 8 running.

**Comment by ripcurlx** [comment]
Will this issue be closed as soon as we move everything to JDK 9?

**Comment by sqrrm** [comment]
The scaling in JDK 9 is only by integer factors from when I tried it. It's not perfect but should be good enough that we could close this issue by then.

**Comment by cbeams** [comment]
@ripcurlx, from our conversation earlier today about GitHub labels, this issue might be a good one to close as `was:deferred`, as in: "we're closing this for now, deferring it at least until we've moved to JDK (which we think will solve the problem)".

**Comment by ripcurlx** [comment]
As mentioned by @cbeams we'll defer this issue until we're using JDK 9 for Bisq.
