### ISSUE TITLE
Error encountered at app startup: Error begin -1, end -1, length 6

### ISSUE THREAD

**Issue by Jayboi23** [bisq-network/bisq#6875]
### Description
 This error keeps coming up at startup even when i tried starting the bisq app over again and pop up the message after I close it.

#### Version

 v1.9.12

### Screenshots
![Screenshot 2023-09-08 at 11 12 44 AM](https://github.com/bisq-network/bisq/assets/126802382/cc83dd90-29f0-41ee-abc6-0b162b74d1dc)

#### Device or machine

Macbook Air, catalina version 10.15.7

#### Additional info
[bisq.log](https://github.com/bisq-network/bisq/files/12662755/bisq.log)

**Comment by ghost** [comment]
An exception is being thrown by `com.sun.glass.ui.mac.MacAccessible`.  I'd guess the empty make proposal dialog is being shown at startup, and Mac is trying to do something with an empty field.

This may be related: https://bugs.openjdk.org/browse/JDK-8235989
Suggested workaround: Don't use VoiceOver feature on Mac.

Also, per the screenshot, you need BTC to make a DAO proposal transaction.

If this does not help, I'd suggest starting over with a [fresh data directory](https://bisq.wiki/Switching_to_a_new_data_directory).

**Comment by Jayboi23** [comment]
What’s the amount of BTC needed to make DAO proposal transaction?

**Comment by suddenwhipvapor** [comment]
> What’s the amount of BTC needed to make DAO proposal transaction?

In short, you need 100sats per each BSQ requested, + miner fees. Bisq will prepare the tx when you fill in the correct data.
See https://bisq.wiki/Making_a_compensation_request
