### ISSUE TITLE
Possible DoS attack vector

### ISSUE THREAD

**Issue by resignedScientist** [bisq-network/bisq#6878]
### Description

I might have accidentally found an attack vector for denial of service attacks. Somehow Bisq showed me an old account balance, even though I have 0 BTC in my wallet. So I was able to open a trade. It goes that far that someone took the offer and already deposited his BTC. On my side there was no deposit transaction actually happening as my wallet was empty.

I don't know how exactly it was possible that Bisq showed me a wrong balance. But if someone finds that out and has some bad intentions, he could use it to create multiple invalid offers without ever spending a single satoshi.

#### Version

1.9.12

### Steps to reproduce

1. Somehow make Bisq believe it has a balance on the wallet, even though the wallet is empty.
2. Create an offer.
3. Wait for someone to take the offer.
4. The funds of the guy who took the offer are now frozen until a mediator sends them back to him.

### Expected behaviour

It shouldn't be possible to show an invalid wallet balance or even create an invalid offer as a result of that.

### Actual behaviour

I was able to create an offer even though my wallet was empty.

#### Device or machine

MacOS Ventura 13.5.2

**Comment by pazza83** [comment]
Thanks for posting.

Yes this is an issue.

No funds would be locked as a deposit transaction would not be created as no funds would be able to enter the multi-sig from the attacker. This would cause the trade to fail.

The problems it would cause for the other peer are:

- Lost mining fees
- Lost trading fees
- The attacker would get the altcoin / fiat account info of the other user
- Inconvience of likely needing to do an SPV resync

The problems it could cause Bisq is if an attacker did this at scale then they could affect any or all users, resulting in the above.
