### ISSUE TITLE
Timeout when taking an offer

### ISSUE THREAD

**Issue by snakes-r-us** [bisq-network/bisq#691]
When taking the offer  (UNO/BTC trade id 19a53cde) I get:
```
An error occurred when taking the offer.

A timeout occurred.

The trading fee is already paid. In the worst case you have lost that fee. We are sorry about that but keep in mind it is a very small amount.
Please try to restart you application and check your network connection to see if you can resolve the issue.Please try to restart you application and check your network connection to see if you can resolve the issue.


```
From the bitsquare.log:

> nov-04 18:00:08.959 [BlockingClient network thread for /175.140.233.154:8333] ERROR o.b.n.BlockingClient: Error trying to open/read from connection: /175.140.233.154:8333: SOCKS: TTL expired 
> nov-04 18:00:13.902 [BlockingClient network thread for /80.151.181.16:8333] ERROR o.b.n.BlockingClient: Error trying to open/read from connection: /80.151.181.16:8333: SOCKS: TTL expired 
> nov-04 18:00:33.441 [BlockingClient network thread for /91.121.86.38:8333] ERROR o.b.core.Peer: [91.121.86.38]:8333 /Satoshi:0.13.99/: Received Reject: tx b12ad168cd686f670f7e86d8675c77b48ba1ade5bca50089b591c1a947953f35 for reason 'bad-txns-inputs-spent' (18) 
> nov-04 18:00:33.647 [BlockingClient network thread for /148.251.191.101:8333] ERROR o.b.core.Peer: [148.251.191.101]:8333 /Satoshi:0.13.1/: Received Reject: tx bd31394fe5105f6fec97807cc8fd582106d6e1a6a59a683ce20a6b68c9c1e025 for reason 'bad-txns-inputs-spent' (18) 
> nov-04 18:00:33.866 [BlockingClient network thread for /188.122.91.11:8333] ERROR o.b.core.Peer: [188.122.91.11]:8333 /Satoshi:0.13.0/: Received Reject: tx b12ad168cd686f670f7e86d8675c77b48ba1ade5bca50089b591c1a947953f35 for reason 'bad-txns-inputs-spent' (18) 
> nov-04 18:00:34.313 [BlockingClient network thread for /91.121.153.128:8333] ERROR o.b.core.Peer: [91.121.153.128]:8333 /Satoshi:0.13.0/: Received Reject: tx bd31394fe5105f6fec97807cc8fd582106d6e1a6a59a683ce20a6b68c9c1e025 for reason 'bad-txns-inputs-spent' (18) 
> nov-04 18:00:34.310 [BlockingClient network thread for /188.122.91.11:8333] ERROR o.b.core.Peer: [188.122.91.11]:8333 /Satoshi:0.13.0/: Received Reject: tx bd31394fe5105f6fec97807cc8fd582106d6e1a6a59a683ce20a6b68c9c1e025 for reason 'bad-txns-inputs-spent' (18) 
> nov-04 18:00:34.495 [BlockingClient network thread for /85.214.110.57:8333] ERROR o.b.core.Peer: [85.214.110.57]:8333 /Satoshi:0.13.0/: Received Reject: tx bd31394fe5105f6fec97807cc8fd582106d6e1a6a59a683ce20a6b68c9c1e025 for reason 'bad-txns-inputs-spent' (18) 
> nov-04 18:00:34.704 [BlockingClient network thread for /157.193.121.83:8333] ERROR o.b.core.Peer: [157.193.121.83]:8333 /Satoshi:0.13.1/: Received Reject: tx b12ad168cd686f670f7e86d8675c77b48ba1ade5bca50089b591c1a947953f35 for reason 'bad-txns-inputs-spent' (18) 
> nov-04 18:02:32.685 [JavaFX Application Thread] ERROR i.b.t.p.t.TradeProtocol: Timeout reached

I've tried restarting the app and taking this offer several times (trading fees be damned:))  before checking the log eventually.

**Comment by ManfredKarrer** [comment]
Hm, might be that the peer has still an old version. With the recent versions that should only happen in very rare cases.  

The msg in the logs:
Received Reject: tx bd31394fe5105f6fec97807cc8fd582106d6e1a6a59a683ce20a6b68c9c1e025 for reason 'bad-txns-inputs-spent'

sounds like you have some issues in the wallet.

**Comment by ManfredKarrer** [comment]
That bug was prob. caused by an older version where we used a diff. offer id format. Is fixed for the next release.
