### ISSUE TITLE
Failure to Sell BTC

### ISSUE THREAD

**Issue by gustavoastorres** [bisq-network/bisq#6911]
### Description

When taking an offer, Bisq wallet is properly funded, but then an error says there is no money afterwards. But wallet is really properly funded.

#### Version

1.9.14

### Steps to reproduce

Sell BTC, select Bisq wallet to fund the sell.

### Expected behaviour

Transaction acceptance.

### Actual behaviour

Transaction failure.

### Screenshots

![image](https://github.com/bisq-network/bisq/assets/7401039/b0d146ea-3a75-4f1a-b77a-2f65da66e5de)
![image](https://github.com/bisq-network/bisq/assets/7401039/4e8775d4-32e3-4ef7-a407-97ff05281feb)

#### Device or machine

Fedora release 38 (Thirty Eight)

**Comment by ghost** [comment]
Consolidate your balance by doing a send to self which moves funds to a fresh UTXO
See #6554.
