### ISSUE TITLE
Honor Freedesktop XDG base spec

### ISSUE THREAD

**Issue by gerardbosch** [bisq-network/bisq#6933]
### Description

The Freedesktop XDG base spec seems not to be totally honored. I explain myself:

Just after installing and running of Bisq for the first time, I noticed that the `~/.local/share/Bisq/` directory took 568 MB. This is specially important for automated backup systems. In my case I'm doing an automated cloud backup of my homedir on daily basis - based on XDG spec, to only backup user files. So I had to add an exclusion to my backup for this directory after realizing of this, to avoid incurring on extra or unnecessary backup cost.

The `XDG_DATA_HOME` should be for user data, but the initial 568 MB are from the Bitcoin network. In essence, this seems not to be user data, but data that can be recreated.

From https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
> `$XDG_CACHE_HOME` defines the base directory relative to which user-specific non-essential data files should be stored. If `$XDG_CACHE_HOME` is either not set or empty, a default equal to `$HOME/.cache` should be used.
>
> `$XDG_DATA_HOME` defines the base directory relative to which user-specific data files should be stored. If `$XDG_DATA_HOME` is either not set or empty, a default equal to `$HOME/.local/share` should be used.

So I think that the `XDG_CACHE_HOME` dir would be more appropriate for the Bitcoin database, Tor, and/or other non-user data that can be fetched or recreated than the currently used `XDG_DATA_HOME`. 

![image](https://github.com/bisq-network/bisq/assets/30733556/748ec62e-61e1-4dbc-b9f1-af8e4864406c)

#### Version

1.9.14

### Steps to reproduce

Install Bisq from the official DEB and run it for the first time.

### Expected behaviour

The `XDG_DATA_HOME` would contain user-specific data.

### Actual behaviour

The `XDG_DATA_HOME` contains more than 500 MB of that that is not user-specific and can be recreated.

### Screenshots

n/a

#### Device or machine

Linux

#### Additional info

n/a

**Comment by gerardbosch** [comment]
no-stale

**Comment by gerardbosch** [comment]
no-stale

Waiting for triage.

**Comment by gerardbosch** [comment]
no-stale
Waiting for triage.

@alejandrogarcia83, may you or someone review it? Cheers!

**Comment by nikicat** [comment]
I believe it remains relevant. Ideally, $XDG_DATA_HOME should only store data needed to recreate the user-specific application state. This way, it can be backed up frequently without consuming excessive archive space.

**Comment by gerardbosch** [comment]
@ManfredKarrer, @ripcurlx, how to reopen this? Nobody has done the triage and it gets closed every few weeks byt the stale bot. I can't se a 'reopen' button. Thanks.
