### ISSUE TITLE
rename TransferWise to Wise 

### ISSUE THREAD

**Issue by htteot** [bisq-network/bisq#6934]
### Steps to reproduce

Account->National Currency Accounts->Add New Account-> (payment method)

### Expected behaviour

- TransferWise should be renamed to Wise
- Transferwise-USD should be renamed to Wise-USD
- In the info popup dialog when opening Transferwise-USD method: word "formally" should be replaced with "formerly"

**Comment by pazza83** [comment]
@htteot I agree this should be done. Not sure how much dev work it would require though. 

@jmacxx how big a job is this?

**Comment by namloan** [comment]
Also consider updating the list of supported currencies by Wise as it's outdated. You can use the updated list from Bisq2 https://github.com/bisq-network/bisq2/blob/8b9f19ab22f2b460b89c7bb801d032322fcd5dbd/account/src/main/java/bisq/account/payment_method/FiatPaymentRailUtil.java#L93C6-L146
