### ISSUE TITLE
Client can't connect

### ISSUE THREAD

**Issue by MarcSte** [bisq-network/bisq#695]
I'm posting this on behalf of reddit user **Internet151**

**Summary:**

- w10 64-bit
- firewall is disabled
- TOR runs fine in other programs
- bitsquare gets stuck at the connecting to tor/syncing with mainnet page
- latest version, no bridges
- I tried running bitsquare on my laptop running Windows 7 and I get the same problem.
- Comcast is my ISP

**Logfile:** http://pastebin.com/XBABwmdu

https://www.reddit.com/r/bitsquare/comments/4w7jnk/bitsquare_cant_connect_to_tor_but_my_tor_browser/
https://www.reddit.com/r/Bitcoin/comments/5adph2/we_need_more_people_using_bitsquare_ability_to/d9fwhhj/

**Comment by Piste** [comment]
This issue is 9 months old. No one seems to have reported a recurrence, at least on GitHub.
