### ISSUE TITLE
Bisq won't open on Mac M1.

### ISSUE THREAD

**Issue by redpola** [bisq-network/bisq#6954]
### Description

"“Bisq.app” is damaged and can’t be opened. You should move it to the Bin."
#### Version

1.9.14 24th October 2023

#### Reproduce

Go to bisq website
Find download link
Download Mac dmg
Open it
Drag app to /Applications
Open app

A requester appears stating '“Bisq.app” is damaged and can’t be opened. You should move it to the Bin.'

### Screenshots

<img width="263" alt="image" src="https://github.com/bisq-network/bisq/assets/373456/cc50c9f9-4d5f-411f-baa7-a72d80f20bc9">

#### Device or machine

Apple M1 Pro

#### Additional info

There is no option to run this under rosetta. file reports

`% file /Applications/Bisq.app/Contents/MacOS/Bisq

/Applications/Bisq.app/Contents/MacOS/Bisq: Mach-O 64-bit executable x86_64`

**Comment by redpola** [comment]
Found the documentation on this... This really is not a user friendly experience and would put off most non-geeks. Why make this a walled garden for experts only?

**Comment by redpola** [comment]
Leaving more info links [here](https://bisq.wiki/Downloading_and_installing#OS-specific_install_notes) and [here](https://github.com/bisq-network/bisq/discussions/6341).

The discussion explains why this was deemed necessary. Maybe this is something that needs to be revisited should Apple open up their app store to third parties?

**Comment by TaquitoSlayer** [comment]
For those having issues even with the xattr command,
run `command -v xattr` and if it shows `/opt/homebrew/bin/xattr`, make sure you run the command like this `sudo /usr/bin/xattr -rd com.apple.quarantine /Applications/Bisq.app`

Homebrew has their own xattr binary, no clue why. If you run it like the documentation asks, it returns `option -r not recognized`. Perhaps someone updates the documentation for this?
