### ISSUE TITLE
Sepa account not signed

### ISSUE THREAD

**Issue by Beli120805** [bisq-network/bisq#6957]
### Description
I wonder whether this is a bug or I need to understand the rules.
My SEPA account with an age of 122 days still needs to be signed, although I completed a trade on Aug 28, 2023. I was patient and used my TransferWise account, but now I am losing my patience.
Trade-ID: 46535212-af875869-c817-4c67-9883-72f3af15ca2c-1912
#### Version
1.9.14
### Expected behaviour
The account should be signed according to Bisq rules.
### Actual behaviour
It is not signed
### Screenshot
![Bisq SEPA account](https://github.com/bisq-network/bisq/assets/143844999/596ed14a-8972-4992-add2-8520c42ce9a8)

#### Device or machine
iMac, macOS Sonoma 14.1.2

**Comment by suddenwhipvapor** [comment]
Hello there
to make this thread useful for other readers as well, signing for SEPA accounts requires that the user who wants to be signed, should buy at least 0.0025btc from a fully signed seller (one that shows a checkmark inside a multipointed star in the offerbook). Missing either one of these conditions (bought amount less than 0.0025btc, or seller not signed or signed but not with all limits lifted) signing will not occur.

There is an infrequent "bug", where the witness data related to the signing will not be broadcasted on the network, so if your trade satisfied all these requirements but you are still not signed, you will have to recreate your payment account with the same exact details, but a different salt, and act as buyer in another eligible offer.
