### ISSUE TITLE
Falha na liberação do BTC

### ISSUE THREAD

**Issue by edsonsued** [bisq-network/bisq#6958]
### An error occurred at task: CONFIRMAR RECIBO DE PAGAMENTO (liberar BTC PARA O COMPRADOR)

NÃO CONSIGO LIBERA OS BTC PARA O COMPRADOR, QUANDO CLICO EM CONFIRMAR RECIBO DE PAGMENTO o software da bisq não conclui a transação

### Screenshots

<!- 
![image](https://github.com/bisq-network/bisq/assets/51235728/ba0c2ebb-fdc8-437f-9b5e-ee80e4b4e521)

 -->

#### Additional info

Contract as json:
{
  "offerPayload": {
    "id": "950659-2106bdd8-ebd3-477e-aa98-45c9def3e2b7-1914",
    "date": 1701469664973,
    "ownerNodeAddress": {
      "hostName": "rtmu5bfzff6h2prw7rzstro4fzmry7rjbnsl4as4woriituy2ljgwsqd.onion",
      "port": 9999
    },
    "direction": "BUY",
    "price": 0,
    "marketPriceMargin": 5.0E-4,
    "useMarketBasedPrice": true,
    "amount": 250000,
    "minAmount": 250000,
    "baseCurrencyCode": "BTC",
    "counterCurrencyCode": "BRL",
    "arbitratorNodeAddresses": [],
    "mediatorNodeAddresses": [
      {
        "hostName": "saavbszijyrqrj4opgiirusnrpv6ntabttuzvjaqmx7j4r7mlz5eibqd.onion",
        "port": 9999
      },
      {
        "hostName": "d7m3j3u4jo2yuymgvxisklpitd3n5xbsnnpyz2mjh6bl6gmj5rjdxead.onion",
        "port": 9999
      }
    ],
    "paymentMethodId": "PIX",
    "makerPaymentAccountId": "30d6e392-2f94-46a4-9f25-e675bf6f0a5e",
    "offerFeePaymentTxId": "5a3d236dd86a3f8182dba9b74a9df36b26c78e93194a1207851b8a4c927509b6",
    "versionNr": "1.9.14",
    "blockHeightAtOfferCreation": 819345,
    "txFee": 5425,
    "makerFee": 5000,
    "isCurrencyForMakerFeeBtc": true,
    "buyerSecurityDeposit": 100000,
    "sellerSecurityDeposit": 100000,
    "maxTradeLimit": 10000000,
    "maxTradePeriod": 86400000,
    "useAutoClose": false,
    "useReOpenAfterAutoClose": false,
    "lowerClosePrice": 0,
    "upperClosePrice": 0,
    "isPrivateOffer": false,
    "extraDataMap": {
      "capabilities": "0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17",
      "accountAgeWitnessHash": "a5ce2bb010bf7df1957b91bcb14b79d41b6e7965"
    },
    "protocolVersion": 4
  },
  "tradeAmount": 250000,
  "tradePrice": 1956294643,
  "takerFeeTxID": "bae75fd113c0c8e09cae93656a6d4851e4a02ed6395b69a8f11ca06dc55f3e8e",
  "buyerNodeAddress": {
    "hostName": "rtmu5bfzff6h2prw7rzstro4fzmry7rjbnsl4as4woriituy2ljgwsqd.onion",
    "port": 9999
  },
  "sellerNodeAddress": {
    "hostName": "iwqg5obc3tuc3xwwvsehwlob73khhobxa4igxohcqqfoeqd6zq42jnyd.onion",
    "port": 9999
  },
  "mediatorNodeAddress": {
    "hostName": "saavbszijyrqrj4opgiirusnrpv6ntabttuzvjaqmx7j4r7mlz5eibqd.onion",
    "port": 9999
  },
  "isBuyerMakerAndSellerTaker": true,
  "makerAccountId": "2104233109",
  "takerAccountId": "1078023086",
  "makerPaymentAccountPayload": {
    "pixKey": "14898252826",
    "countryCode": "BR",
    "paymentMethodId": "PIX",
    "id": "30d6e392-2f94-46a4-9f25-e675bf6f0a5e",
    "maxTradePeriod": -1
  },
  "takerPaymentAccountPayload": {
    "pixKey": "91987229574",
    "countryCode": "BR",
    "paymentMethodId": "PIX",
    "id": "33350811-5bbd-42af-ba4f-d000b0edea5a",
    "maxTradePeriod": -1
  },
  "makerPayoutAddressString": "bc1qydnz57gzy6un0eykel50y2w92dkr3chpuj4fje",
  "takerPayoutAddressString": "bc1qg6ztgat540sngm7lfyp9whwpvyxprh058sjv4u",
  "lockTime": 822469,
  "refundAgentNodeAddress": {
    "hostName": "3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion",
    "port": 9999
  },
  "hashOfMakersPaymentAccountPayload": [
    -122,
    21,
    9,
    -36,
    91,
    66,
    62,
    84,
    84,
    -30,
    100,
    115,
    -16,
    87,
    48,
    50,
    -12,
    -90,
    10,
    61
  ],
  "hashOfTakersPaymentAccountPayload": [
    41,
    122,
    41,
    26,
    97,
    -86,
    74,
    -127,
    -100,
    43,
    115,
    12,
    14,
    -113,
    61,
    94,
    50,
    83,
    -75,
    -65
  ],
  "makerPaymentMethodId": "PIX",
  "takerPaymentMethodId": "PIX"
}

Other detail data:

BuyerMultiSigPubKeyHex: 03e42feb41ff8443db46b511dc0689b665b03b3da1ec8f1d6541d90cea5abdadb4
SellerMultiSigPubKeyHex: 03d347cfd81da2fab1575feada22f783781dfe9ad56776efdb7735b1ef5685c7f9

BuyersAccountAge: Conta de pagamento criada há 742 dias.
SellersAccountAge: Conta de pagamento criada há 4 dias.

Raw deposit transaction as hex:
01000000000102b60975924c8a1b8507124a19938ec7266bf39d4ab7a9db82813f6ad86d233d5a0100000000ffffffff8e3e5fc56da01cf1a8695b39d62ea0e451486d6a6593ae9ce0c8c013d15fe7ba0100000000ffffffff015515070000000000220020bf9aff7f45ae37d1d47101de777ada4badc75597a9ebafd1b07785bea665f3ab000000000000

Selected mediator: leo816

**Comment by suddenwhipvapor** [comment]
Hi, I get that you clicked the payment received confirmation, but the trade is not getting closed yet.
If restarting bisq doesn't help, I would notify your buyer in trader chat about the issue, and then open mediation, so in mediator chat you will explain the issue to your mediator, asking for a normal payout to be suggested as solution

**Comment by edsonsued** [comment]
I restarted bisq and it didn't solve the problem. I notified the buyer via chat. I opened mediation, but it hasn't been resolved yet.

**Comment by suddenwhipvapor** [comment]
Yeah, mediators have up to 48hrs to respond, but you can DM leo or pazza on matrix at bisq.chat

**Comment by kiocos** [comment]
@edsonsued also, watch out for leaking yours/buyers personal information. The "additional info" you provided could be used to identify you or the buyer, I'd suggest to have this in mind in the future.
