### ISSUE TITLE
BSQ fee validation should check mempool.space in addition to the DAO.

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#6959]
In https://github.com/bisq-network/bisq/pull/6425, we switched validation of BSQ fee payments from mempool.space the DAO database.

> Unconfirmed transactions will not be able to have their BSQ fees checked so early requests for validation will skip the fee check. This is not a problem since maker fee validation is done by takers and **in the majority of cases will be already confirmed**; taker fee validation is done after the first confirm at trade step 2.

---

### Problem scenario:

- Maker has bad SPV wallet state.
- Maker creates an offer but their tx fails to propagate because of their bad SPV state.
- Taker initiates trade.  BSQ fees cannot be checked because DAO does not have the info.  
- Taker tx is published.
- Deposit tx fails due to missing maker input.

**Possible solution is to reintroduce querying mempool.space as part of the BSQ validation prior to trade.**

---

Issue raised by @suddenwhipvapor

**Comment by rofaral** [comment]
I am the taker and want to know if I'hh have the fee values back to my wallet.

**Comment by ghost** [comment]
Yes: [Failed Trades - Reimbursement of Trade Fees and Miner Fees
](https://bisq.wiki/Failed_Trades_-_Reimbursement_of_Trade_Fees_and_Miner_Fees)
@suddenwhipvapor can continue to assist you in Matrix if needed.

**Comment by rofaral** [comment]
I still don't understand, As the taker, Will I have the reimbursement?

**Comment by ghost** [comment]
Please follow the procedure from the wiki: [Failed Trades - Reimbursement of Trade Fees and Miner Fees
](https://bisq.wiki/Failed_Trades_-_Reimbursement_of_Trade_Fees_and_Miner_Fees)

A friendly support staff person can assist you in Matrix if needed.
