### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by stevenroose** [bisq-network/bisq#696]
My system:
```
Arch Linux
Kernel 4.8.6-1-ARCH
64-bit i7 processor
java version "1.7.0_111"
OpenJDK Runtime Environment (IcedTea 2.6.7) (Arch Linux build 7.u111_2.6.7-1-x86_64)
OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)
```

I got a memory leak in Bitsquare (>3 GiB). Is there any information I can provide? I just have it running in the background. I often get notices that an exception has been caught, but if I click report to github or via e-mail, there is no information I can send along.

**Comment by ManfredKarrer** [comment]
Maybe the OpenJDK behaves different memory-wise. I never saw more then 2 GB on my nodes (on a 16GB debian). On OSX I usually never get over 1.2 GB.
Java is greedy and takes what the OS gives. Bitsquare can also run on 200 MB...

**Comment by abelboldu** [comment]
Same issue here with almost same environment:
```
java version "1.7.0_111"
OpenJDK Runtime Environment (IcedTea 2.6.7) (Arch Linux build 7.u111_2.6.7-1-x86_64)
OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)

```

see https://github.com/bitsquare/bitsquare/issues/599

**Comment by abelboldu** [comment]
@stevenroose  Try using java8 with
`sudo archlinux-java set java-8-openjdk
`
It worked for me.

**Comment by ManfredKarrer** [comment]
You need to use latest java version. Java 7 is not supported. I assume that is the main reason of that issue.
