### ISSUE TITLE
Wise: Seller doesn't see the buyer's holder name

### ISSUE THREAD

**Issue by alvasw** [bisq-network/bisq#6983]
PR #6964 was merged into master before it was ready. This issue tracks one of the issues.

### Seller doesn't see the buyer's holder name
1. Create new Wise accounts with an e-mail address and a holder name on Alice's and Bob's Bisq instances.  
2. Start a trade between Alice and Bob  
3. Press the payment started button on the buyer's side  
4. The seller doesn't see the holder name of the buyer 
![seller_holder_missing](https://github.com/bisq-network/bisq/assets/95712046/0a13d97b-ddf9-4013-bbb7-ab3f1a13ab0b)

**Comment by alvasw** [comment]
@yonson2023 Do you have time to fix these issues? Otherwise another dev can fix it.

**Comment by ghost** [comment]
Working on it.

**Comment by ghost** [comment]
Done.
