### ISSUE TITLE
Wise: Holder name is missing on both traders trade details popup

### ISSUE THREAD

**Issue by alvasw** [bisq-network/bisq#6984]
PR https://github.com/bisq-network/bisq/pull/6964 was merged into master before it was ready. This issue tracks one of the issues.

### Holder name is missing on both traders trade details popup
![trade_details_everything_missing](https://github.com/bisq-network/bisq/assets/95712046/0966905b-fc13-461b-8afc-43deae3b2050)

**Comment by alvasw** [comment]
@yonson2023 Do you have time to fix these issues? Otherwise another dev can fix it.

**Comment by ghost** [comment]
Working on it.

**Comment by ghost** [comment]
Done.
