### ISSUE TITLE
Wise: Copy button missing (next to the holder name text field)

### ISSUE THREAD

**Issue by alvasw** [bisq-network/bisq#6985]
PR https://github.com/bisq-network/bisq/pull/6964 was merged into master before it was ready. This issue tracks one of the issues.

### Copy button missing (next to the holder name text field)
![copy_button_missing](https://github.com/bisq-network/bisq/assets/95712046/452a2417-2f37-4f79-a55f-98db47cf236a)

**Comment by alvasw** [comment]
@yonson2023 Do you have time to fix these issues? Otherwise another dev can fix it.

**Comment by ghost** [comment]
Working on it.

**Comment by ghost** [comment]
Done.
