### ISSUE TITLE
Unable to close a mediation ticket

### ISSUE THREAD

**Issue by leo816** [bisq-network/bisq#6999]
### Description

Unable to close a mediation ticket

### Expected behaviour

The ticket should be closed, get greyed out and disappear from open trades

### Actual behaviour

Getting the error message below

### Screenshots

<img width="1012" alt="Screenshot 2024-01-12 at 16 48 18" src="https://github.com/bisq-network/bisq/assets/54798241/2a85f034-203c-4b44-933f-a7b231a06035">

#### Device or machine

Mac OS Big Sur v 11.2.2

**Comment by kiocos** [comment]
Hey @leo816 !
Any chance you still have got the log file for this?
