### ISSUE TITLE
cannot add my sepa fiat account: Error Cannot invoke "javafx.scene.Node.getLayoutBounds()" because "this.textNode" is null

### ISSUE THREAD

**Issue by m0l3Ancap** [bisq-network/bisq#7010]
### Description

fresh installed bisq via yay on arch linux. didnt wait to finish sync and clicked on link a new fiat account. clicked on "SEPA" and boom i am here.

#### Version

1.9.14-1

### Expected behaviour

maybe a submit button of the form is missing. i can fill in my name and thats all.

### Actual behaviour

nothing unexpected happend. app didn't crash or shit.. wait i cannot submit my form. but i dont know how the ui should look like.

### Screenshots

![ksnip_20240125-205828](https://github.com/bisq-network/bisq/assets/157123527/67d7ce5e-bb03-449a-9200-4681ce3a6734)

#### Device or machine

Jan-25 19:30:55.972 [main] INFO  b.c.u.Utilities: System info: os.name=Linux; os.version=6.5.6-arch2-1; os.arch=amd64; sun.arch.data.model=64; JRE=21+35 (N/A); JVM=21+35 (OpenJDK 64-Bit Server VM) 

#### Additional info

love you guys <3

**Comment by ghost** [comment]
Try with Java version family 11, that's what Bisq normally uses.
