### ISSUE TITLE
Remove legacy BSQ trading protocol

### ISSUE THREAD

**Issue by refund-agent2** [bisq-network/bisq#7011]
### Description

BSQ swaps are a quicker and cheaper option to trade BSQ. Leaving the old trading protocol becomes a possible confusion for traders and leaves a door open for bugs.

I suggest that from now on, only swaps should be allowed to trade BSQ.

### Expected behaviour

Traders should not be able to create BSQ accounts, or take multisig BSQ offers.

@jmacxx Could you take a look at this?

**Comment by ghost** [comment]
First implementation of this in #7016 was to automatically delete any BSQ altcoin accounts.  It took care of most of the use-cases that needed fulfilling in a simple and easy to implement way.  Do you think that is the right way to go, or is it too aggressive?  I'm not sure if BSQ altcoin accounts may be seen as a user's property and thus not a good idea to delete.

An alternative might be to hide BSQ altcoin accounts from anywhere in the app they are used, such as create offer, take offer, edit offer, duplicate offer, clone offer etc.

I've moved the PR to draft for now.
