### ISSUE TITLE
Funds/Wallet Withdrawal - Gets rounded up if greater that 4 decimal places of precision

### ISSUE THREAD

**Issue by memetat** [bisq-network/bisq#702]
Hi,
I cant seem to withdraw an exact amount with a higher precision than 4 decimal places as it rounds it up.
(I want to pay someone from the bitsquare wallet for convenience)

If there is an option in the settings, i havnt found it :)

Windows 7/4.9.7/64bit

**Comment by sh4d0v1** [comment]
This is something bugging me too.
Please implement a possibility to set the wanted precision in settings!

**Comment by Nolaan** [comment]
I'd also like to add the fact that the function is not sending the amount requested because it only remove the network fee after. The ideal use case would add the fees after the desired amount, not removing the fees from the amount you're sending.

**Comment by memetat** [comment]
Nolaan, yes thats a bit inconvenient too.  But im glad there is a pop up confirming the amount that will go to the recipient, so you can cancel & readjust.

**Comment by Nolaan** [comment]
Yes it's good unless the other party request a really precise amount over 4 decimals (the reason I'm here, it happened to me on bitwala yesterday :( ). The combined missing points are quite problematic in this case.

**Comment by ManfredKarrer** [comment]
Will try to remove the clipped precision for the next release. To add an option to add the fee and also to adjust the fee directly there would be good as well, though I will not have time to implement that soon. But would be a relatively easy task for any dev who wants to help out here.

**Comment by ManfredKarrer** [comment]
Bitcoin format has not support to all decimal places (up to 1 satoshi).
