### ISSUE TITLE
Failed trade stuck in open trades list

### ISSUE THREAD

**Issue by dutu** [bisq-network/bisq#7024]
### Description

The trade below is failed, as deposit tx is not published.

![image](https://github.com/bisq-network/bisq/assets/6230798/165b20f6-d410-4774-9a0c-5925b1572890)

(Maker fee tx is valid and confirmed).

For some reason timeout has not occurred, as a result bisq is still waiting for the deposit tx to be published. It looks that timeout has been cleared and will never occur.

Retrieving the trade with API shows (I only included fields that could be relevant):

```json
{
  "offer": {
    "id": "sW4P0H-0f45de7c-5b75-42ac-b319-82174d759e91-1914",
    "date": "1706733410755",
    "state": "UNKNOWN",
    "offer_fee_payment_tx_id": "d6d35d21cdd7da0a4f03c8a8783cea5f1228024d9f8ad53c16873afb2d0bf968",
    "is_activated": false,
    "is_my_offer": true,
    "is_my_pending_offer": false,
  },
  "trade_id": "sW4P0H-0f45de7c-5b75-42ac-b319-82174d759e91-1914",
  "date": "1706789716166",
  "taker_fee_tx_id": "",
  "deposit_tx_id": "",
  "payout_tx_id": "",
  "state": "MAKER_SAW_ARRIVED_PUBLISH_DEPOSIT_TX_REQUEST",
  "phase": "TAKER_FEE_PUBLISHED",
  "trade_period_state": "FIRST_HALF",
  "is_deposit_published": false,
  "is_deposit_confirmed": false,
  "is_payment_started_message_sent": false,
  "is_payment_received_message_sent": false,
  "is_payout_published": false,
  "is_completed": false,
  "closing_status": "Pending",
}
```

Restarting bisq application and SPV resync did not resolve the issue (there is no deposit tx published).

Right now the failed trade is stuck in open list trade and there is no option to move the trade to failed trades.

[How to get rid of a trade that is ‘stuck’ in open trades](https://bisq.community/t/how-to-get-rid-of-a-trade-that-is-stuck-in-open-trades/12218) would perhaps be an option.

A possible solution in this case could be for the bisq application to reinitialize the timeout for the deposit tx. Possibly, this could be done at application restart by scanning the open trades (in  TAKER_FEE_PUBLISHED phase?), looking for missing deposit tx id, trade date and missing timeout.

Reinitializing the timeout would fail the trade properly and allow user to move the trade to failed trade list, without the need to apply the solution of deleting the `PendingTrades` file.

(There could be other reasons why a failed trade gets stuck in open trade list, but this case is one of them. Other cases and applicable solutions could be added later on when discovered).

#### Version

v1.9.14

### Expected behaviour

Failed trade should show as failed, and user to be able to move it to failed trades.

### Actual behaviour

Failed tarde is stuck in open trade list and it is not marked as failed.

#### Device or machine

Debian, Bisq v1.9.14

**Comment by pazza83** [comment]
Thanks for opening this issue.

Your trade amount and deposit for this trade: 0.0375 BTC is in address: bc1qzs8577gjsemh22rz980ptxyfwyaav4uq2ehx3v

You should be able to see this in Funds > Send Funds

> Right now the failed trade is stuck in open list trade and there is no option to move the trade to failed trades.

There should be a red arrow on the right side of the trade in the open trades screen to move the trade to failed. Looks like Bisq knows the trade has failed so there should be this option. You might need to scroll to the right to see the red arrow.

If it is not there let me know and I will ask for the logs.

> [How to get rid of a trade that is ‘stuck’ in open trades](https://bisq.community/t/how-to-get-rid-of-a-trade-that-is-stuck-in-open-trades/12218) would perhaps be an option.

Yes this will work but it a bit of a messy solution. Would be good to know what the underlying issue was.

**Comment by dutu** [comment]
Thanks for quick reply.
I don't have the red arrow and the trade looks like a normal open trade waiting for deposit confirmation.
I also don't see the deposit address in my bisq wallet.

I have uploaded the logs as per your instruction

**Comment by pazza83** [comment]
Thanks for letting me know.

I have sent the logs off to be looked into and will get back to you.

> I also don't see the deposit address in my bisq wallet.

Please can you do an [SPV resync](https://bisq.wiki/Resyncing_SPV_file) and see if the address d6d35d21cdd7da0a4f03c8a8783cea5f1228024d9f8ad53c16873afb2d0bf968 shows in your wallet. It should be in Funds > Send Funds

**Comment by dutu** [comment]
I see the address under Reserved Funds.
![image](https://github.com/bisq-network/bisq/assets/6230798/603e3ec4-7358-49cf-b756-e29e17e12ed3)
I guess it cannot be seen under Send Funds because funds cannot be sent, since they are still reserved for the trade.

**Comment by pazza83** [comment]
The trade failed due to the error `Contracts not matching` on the taker side.

**Comment by pazza83** [comment]
> I see the address under Reserved Funds. I guess it cannot be seen under Send Funds because funds cannot be sent, since they are still reserved for the trade.

It might be that the offer is still available for another user to take. Do you see the trade in 'Portfolio > Open Offers'

**Comment by dutu** [comment]
Yes, the offer is available in Open Offers.
So it shows that the first trade has failed (since the offer has been made available again), but in GUI I don't have the option to move it to failed trades and it's stuck in Open Trades list.

**Comment by pazza83** [comment]
> Yes, the offer is available in Open Offers.

Ok, that means someone else can take the offer.

> So it shows that the first trade has failed (since the offer has been made available again), but in GUI I don't have the option to move it to failed trades and it's stuck in Open Trades list.

You should see a red arrow, but as you do not I think waiting for the other trades to complete and then following the instructions here: https://bisq.community/t/how-to-get-rid-of-a-trade-that-is-stuck-in-open-trades/12218 is likely the best option

**Comment by dutu** [comment]
Yes, I don't have a red arrow to move the trade to failed trades. I will follow the instruction you mentioned to get rid of the stuck trade. This was the option from the beginning, but the reason of raising this issue was to find a way to avoid this (at least to find a solution for the future). 
In will wait for other trades to complete (probably it will take a few more days as one peer is not responding at all), them will apply the instruction. In the meantime, if there is more data you want to collect in an attempt to pinpoint the issue or any other workaround you want me to try, let me know and I'll try to assist.

**Comment by pazza83** [comment]
@dutu 

You have lost miner fees and trade fees on this trade.

If you post a bitcoin address in the comment then you can be reimbursed for this loss.

**Comment by dutu** [comment]
I've got another trade in this state, and it's possible I shut down the application before the 120 timout expired. I don't remember the first case.
Anyway, I'm closing this issue and you can reopen it if you consider more work/investigation is required.
