### ISSUE TITLE
Feature request: Chatbox

### ISSUE THREAD

**Issue by sh4d0v1** [bisq-network/bisq#703]
What I am missing at Bitsquare is the "community feeling" given by all the people's voices on a market place (trollbox). People trade and linger, although a chatbox of course would have it's downsides, I am sure the feeling of "something happening" is fundamental for a living, crowded market.

Are there any reasons contra?

**Comment by HostFat** [comment]
I think that the easier way is adding a very simple IRC client, and it should connect to an IRC server that supports Tor connections.

Anyway, I'm sure that the main dev has other priorities now :)

**Comment by sh4d0v1** [comment]
No doubt there are much more important issues atm.

But there is no reason to bring centralized infrastructure in for this task, broadcasting clear text messages to all nodes is an easy task in P2P technologies. Of course some kind of spam brake would be needed.

**Comment by sh4d0v1** [comment]
I see a larger communication system (more than talking to arbitrators) is nothing you find appealing.
I hope a good piece of software like Bitsquare will attract more users some day without this community generating feature.

**Comment by ManfredKarrer** [comment]
A larger communication system which provides quality information would be very appealing but also very challenging and a lot of effort. That would be more in direction of Steem with reputation and a good mechanisms to amplify good content and filter noise. A classical trollbox is the opposite for me, mainly a source of manipulation attempts to push the next pump&dump coin or abused for social engineering tricks. 
The current IRC channel or slack could be uses also if there is demand, but both are pretty quiet. So I also doubt that there is real demand for such.

To flood the P2P network with 1000 messages from a trollbox would be not a good idea as well, the network is already quite loaded and people with high bandwidth costs are already complaining. 

But beside that even if I would be a fan of trollboxes, there is so much hi-prio work to be done first that this would have to wait.

**Comment by Tvax** [comment]
That's a great feature, even if this is not the priority right now we should let the issue open because at some point it will be doable.
