### ISSUE TITLE
[new to this] i cant run bisq on tails 5.22

### ISSUE THREAD

**Issue by anonym59** [bisq-network/bisq#7031]
Might be my fault. Im not too into this kinda stuff. 

When I start Bisq from my Terminal this appears:
fault: An unexpected error occurred. Please file a report at https://bisq.network/issues
java.io.UncheckedIOException: Application data directory '/home/amnesia/.local/share/Bisq' could not be created

When I run it through the application there's no error message and it just doesnt open. 
If you need further Information just ask.

**Comment by robster7674** [comment]
Looks similar to https://github.com/bisq-network/bisq/issues/6470?

**Comment by dutu** [comment]
Check [Run-on-Tails guide for Bisq](https://dutu.github.io/run-on-tails/bisq/bisq.html), it works.
