### ISSUE TITLE
Cannot provide XMR tx id and tx key with RPC method ConfirmPaymentStarted

### ISSUE THREAD

**Issue by dutu** [bisq-network/bisq#7033]
### Description

When using RPC method `ConfirmPaymentStarted` for XMR trades, user is not able to provide transaction id and transaction key.

#### Version

v1.9.14

### Steps to reproduce

RPC method `ConfirmPaymentStarted()` takes only one parameter (the `trade_id`).

### Expected behaviour

`ConfirmPaymentStarted()` should allow two additional (optional) parameters for transaction id and transaction key, `tx_id` (or`tx_hash`) and `tx_key`.
This would be consistent with how GUI works and improve user experience.

### Actual behaviour

API user cannot provide transaction id and transaction key with RPC method `ConfirmPaymentStarted()`

#### Device or machine

Debian, Bisq v1.9.14

**Comment by ghost** [comment]
Adding XMR parameters to `ConfirmPaymentStarted()` API method would

- confuse users buying with non-XMR instruments (e.g. USD, EUR, or ETH)
- break compatibility with existing clients
 
I propose adding a specific method `ConfirmPaymentStartedXmr(tx_id, tx_key)` to avoid the above issues.
