### ISSUE TITLE
Build fails on Linux aarch64

### ISSUE THREAD

**Issue by carlosalbertofilho** [bisq-network/bisq#7034]
## Fedora Linux 38 running on aarch64 machine:
Linux fedora-linux-38 6.7.3-200.fc39.aarch64 #1 SMP PREEMPT_DYNAMIC Thu Feb  1 04:17:25 UTC 2024 aarch64 GNU/Linux

## Java 11
javac --version
javac 11.0.22

### Build doesn't work:
[root@fedora-linux-39 bisq]# ./gradlew build
> Task :build-logic:toolchain-resolver:compileKotlin UP-TO-DATE
> Task :build-logic:toolchain-resolver:compileJava NO-SOURCE
> Task :build-logic:toolchain-resolver:pluginDescriptors UP-TO-DATE
> Task :build-logic:toolchain-resolver:processResources UP-TO-DATE
> Task :build-logic:toolchain-resolver:classes UP-TO-DATE
> Task :build-logic:toolchain-resolver:inspectClassesForKotlinIC UP-TO-DATE
> Task :build-logic:toolchain-resolver:jar UP-TO-DATE
> Task :build-logic:regtest:compileKotlin UP-TO-DATE
> Task :build-logic:regtest:compileJava NO-SOURCE
> Task :build-logic:regtest:pluginDescriptors UP-TO-DATE
> Task :build-logic:regtest:processResources UP-TO-DATE
> Task :build-logic:regtest:classes UP-TO-DATE
> Task :build-logic:regtest:inspectClassesForKotlinIC UP-TO-DATE
> Task :build-logic:regtest:jar UP-TO-DATE
> Task :build-logic:commons:extractPluginRequests UP-TO-DATE
> Task :build-logic:commons:generatePluginAdapters UP-TO-DATE
> Task :build-logic:commons:compileJava UP-TO-DATE
> Task :build-logic:commons:compileGroovy NO-SOURCE
> Task :build-logic:commons:compileGroovyPlugins UP-TO-DATE
> Task :build-logic:commons:pluginDescriptors UP-TO-DATE
> Task :build-logic:commons:processResources UP-TO-DATE
> Task :build-logic:commons:classes UP-TO-DATE
> Task :build-logic:commons:jar UP-TO-DATE
> Task :build-logic:app-start-plugin:compileKotlin UP-TO-DATE
> Task :build-logic:app-start-plugin:compileJava NO-SOURCE
> Task :build-logic:app-start-plugin:pluginDescriptors UP-TO-DATE
> Task :build-logic:app-start-plugin:processResources UP-TO-DATE
> Task :build-logic:app-start-plugin:classes UP-TO-DATE
> Task :build-logic:app-start-plugin:inspectClassesForKotlinIC UP-TO-DATE
> Task :build-logic:app-start-plugin:jar UP-TO-DATE

> Configure project :common
Project :common => no module-info.java found

> Configure project :core
Project :core => no module-info.java found

> Task :build-logic:gradle-tasks:compileKotlin UP-TO-DATE
> Task :build-logic:gradle-tasks:compileJava NO-SOURCE
> Task :build-logic:packaging:compileKotlin UP-TO-DATE
> Task :build-logic:packaging:compileJava NO-SOURCE
> Task :build-logic:packaging:pluginDescriptors UP-TO-DATE
> Task :build-logic:packaging:processResources UP-TO-DATE
> Task :build-logic:packaging:classes UP-TO-DATE
> Task :build-logic:packaging:inspectClassesForKotlinIC UP-TO-DATE
> Task :build-logic:packaging:jar UP-TO-DATE
> Task :build-logic:gradle-tasks:pluginDescriptors UP-TO-DATE
> Task :build-logic:gradle-tasks:processResources NO-SOURCE
> Task :build-logic:gradle-tasks:classes UP-TO-DATE
> Task :build-logic:gradle-tasks:inspectClassesForKotlinIC UP-TO-DATE
> Task :build-logic:gradle-tasks:jar UP-TO-DATE

> Configure project :desktop
Project :desktop => no module-info.java found

> Configure project :p2p
Project :p2p => no module-info.java found

> Task :build-logic:docker-image-builder:compileKotlin UP-TO-DATE
> Task :build-logic:docker-image-builder:compileJava NO-SOURCE
> Task :build-logic:docker-image-builder:pluginDescriptors UP-TO-DATE
> Task :build-logic:docker-image-builder:processResources UP-TO-DATE
> Task :build-logic:docker-image-builder:classes UP-TO-DATE
> Task :build-logic:docker-image-builder:inspectClassesForKotlinIC UP-TO-DATE
> Task :build-logic:docker-image-builder:jar UP-TO-DATE
> Task :proto:extractIncludeProto UP-TO-DATE
> Task :proto:extractProto UP-TO-DATE
> Task :proto:generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':proto:generateProto'.
> Dependency verification failed for configuration ':proto:protobufToolsLocator_protoc':
    - On artifact protoc-3.19.1-linux-aarch_64.exe (com.google.protobuf:protoc:3.19.1) in repository 'MavenRepo': checksum is missing from verification metadata.
  
  If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file by following the instructions at https://docs.gradle.org/7.6.3/userguide/dependency_verification.html#sec:troubleshooting-verification
  
  These files failed verification:
    - GRADLE_USER_HOME/caches/modules-2/files-2.1/com.google.protobuf/protoc/3.19.1/756fa5e2ea67d2153e0f2316eb2e97a90082f44d/protoc-3.19.1-linux-aarch_64.exe
  
  GRADLE_USER_HOME = /root/.gradle
  
  These files failed verification:
    - GRADLE_USER_HOME/caches/modules-2/files-2.1/com.google.protobuf/protoc/3.19.1/756fa5e2ea67d2153e0f2316eb2e97a90082f44d/protoc-3.19.1-linux-aarch_64.exe
  
  GRADLE_USER_HOME = /root/.gradle
  
  Open this report for more details: file:///opt/bisq/build/reports/dependency-verification/at-1707502064517/dependency-verification-report.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by richardalg** [comment]
Hi Carlos, 
I'm going to make a few assumptions: You may be running a Raspberry Pi, and bisq developers do not support aarch64. 
Hence this thread may be of interest: 
https://gist.github.com/tmakerman/ee53a94c3cfc8362192ad9df20709547
And this : 
https://gist.github.com/richardalg/bb9ca80ee851fb792ffd85b9257b189f

I've assumed you are attempting to build bisq-1.9.14 .... 

I've put up some patches in the above links that get a bit further with the build and had success with bisq-1.9.12
I'm just getting back into my attempts - these now stall - a child window appears with the message 
Error
'javafx.beans.binding.BooleanExpression com.sun.javafx.scene.NodeHelper.treeShowingProperty(javafx.sceneNode)'

I've attempted to run $ gradle :apitest:installDaoSetup
in the project directory. This fails with a message that : 
8: only Project build scripts can contain plugins {} blocks. 

Hope this helps.

**Comment by carlosalbertofilho** [comment]
Thanks!! Its work.

`> Task :core:check
> Task :core:build
> Task :daemon:startScripts
> Task :daemon:distTar
> Task :daemon:distZip SKIPPED
> Task :daemon:assemble
> Task :daemon:compileTestJava
> Task :daemon:processTestResources NO-SOURCE
> Task :daemon:testClasses
> Task :daemon:test
> Task :daemon:check
> Task :daemon:installDist
> Task :daemon:build
> Task :desktop:startScripts
> Task :desktop:distTar SKIPPED
> Task :desktop:distZip SKIPPED
> Task :desktop:shadowJar
> Task :desktop:startShadowScripts
> Task :desktop:shadowDistTar SKIPPED
> Task :desktop:shadowDistZip SKIPPED
> Task :desktop:assemble

> Task :desktop:compileTestJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :desktop:processTestResources
> Task :desktop:testClasses

> Task :desktop:test
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

> Task :desktop:check
> Task :desktop:installDist
> Task :desktop:build
> Task :p2p:assemble

> Task :p2p:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :p2p:processTestResources
> Task :p2p:testClasses

> Task :p2p:test
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

> Task :p2p:check
> Task :p2p:build
> Task :proto:assemble
> Task :proto:extractIncludeTestProto
> Task :proto:extractTestProto
> Task :proto:generateTestProto NO-SOURCE
> Task :proto:compileTestJava NO-SOURCE
> Task :proto:processTestResources NO-SOURCE
> Task :proto:testClasses UP-TO-DATE
> Task :proto:test NO-SOURCE
> Task :proto:check UP-TO-DATE
> Task :proto:build
> Task :seednode:startScripts
> Task :seednode:distTar SKIPPED
> Task :seednode:distZip SKIPPED
> Task :seednode:shadowJar
> Task :seednode:startShadowScripts
> Task :seednode:shadowDistTar SKIPPED
> Task :seednode:shadowDistZip SKIPPED
> Task :seednode:assemble
> Task :seednode:compileTestJava
> Task :seednode:processTestResources NO-SOURCE
> Task :seednode:testClasses
> Task :seednode:test
> Task :seednode:check
> Task :seednode:installDist
> Task :seednode:build
> Task :statsnode:compileJava
> Task :statsnode:processResources
> Task :statsnode:classes
> Task :statsnode:jar
> Task :statsnode:startScripts
> Task :statsnode:distTar SKIPPED
> Task :statsnode:distZip SKIPPED
> Task :statsnode:assemble
> Task :statsnode:compileTestJava NO-SOURCE
> Task :statsnode:processTestResources NO-SOURCE
> Task :statsnode:testClasses UP-TO-DATE
> Task :statsnode:test NO-SOURCE
> Task :statsnode:check UP-TO-DATE
> Task :statsnode:installDist
> Task :statsnode:build

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4m 11s
76 actionable tasks: 76 executed
`

**Comment by richardalg** [comment]
"Thanks!! Its work."
Good to hear. I'm still working on my problems. 
It may be of help if you posted details of your OS and the machine running the code. 
TIA.

**Comment by carlosalbertofilho** [comment]
Of course!

I'm running virtualized Fedora on a Mac mini M2 host:

```
uname -a
Darwin agnes.local 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:33:31 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8112 arm64
```

the Fedora is a 4Gb VM with 4 cores:
```
cat /etc/redhat-release 
Fedora release 39 (Thirty Nine)
```
