### ISSUE TITLE
bisq-desktop fails to launch after build arch [new to things]

### ISSUE THREAD

**Issue by JetGreaves** [bisq-network/bisq#7037]
bisq-desktop fails to launch from terminal after build
attempting to launch bisq-desktop with no arguments from terminal window
failure code given:
> /usr/bin/bisq-desktop: line 13: ./gradlew: No such file or directory

running v1.9.14
running on arch linux

**Comment by sinaptik** [comment]
Have a look at comments here for others with this issue: https://aur.archlinux.org/packages/bisq?O=10&PP=10

A fix is to run bisq via `/opt/bisq/bin/desktop`

**Comment by lucawen** [comment]
Happening with me at EndeavourOS. Using the @sinaptik temporary fix resolved, but needs to execute this command all the time.
