### ISSUE TITLE
Java.lang.IllegalStateException: Expected Pending or IN:CONFLICT was building

### ISSUE THREAD

**Issue by buddhalore** [bisq-network/bisq#7044]
### Description

<Upon running the 1.9.14 suddenly I get this old java error. Older macs had it consistently but I can't locate the various older issues and solutions. Upon reinstalling, the error repeats  >

#### Version

<1.9.14>

### Steps to reproduce

<Opening the client, error window pops up (Screenshot), no connection there after (other screeprint)>

### Screenshots

<
![Screen Shot 2024-02-21 at 03 32 54](https://github.com/bisq-network/bisq/assets/85696011/36932fb7-fef7-4af4-a4c8-4303c957df3f)
>
![Screen Shot 2024-02-21 at 03 39 37](https://github.com/bisq-network/bisq/assets/85696011/faa248da-aa17-461d-b3fc-1e2b84d19af9)

#### Device or machine

Mac OS X 10.13.6 high sierra

**Comment by pazza83** [comment]
You need to do an SPV Resync https://bisq.wiki/Resyncing_SPV_file#From_the_file_system

That will fix it

**Comment by uskrusader** [comment]
I'm getting this error every few days. I do SPV resync, then it happens again few days later.  Whats going on?!

**Comment by pazza83** [comment]
I am not sure what the error is, but doing SPV resyncs every few days is not expected.

You might want to consider switching to a new data directory https://bisq.wiki/Switching_to_a_new_data_directory
