### ISSUE TITLE
Rename bonded role 'Keybase admin' to 'Community admin'

### ISSUE THREAD

**Issue by solomon1923** [bisq-network/bisq#7048]
### Description

Keybase was retired a couple of years ago and replaced with Matrix.

There is still a bonded role in the DAO for 'Keybase admin' this should be renamed to 'Community admin'. This makes the bonded role non-platform specific.

Once the role has been renamed a contributor can be found to administer it (Keybase admin is currently vacant). This  it also helps to address who will be an admin for the Bisq Matrix space see: https://github.com/bisq-network/bisq/issues/7026

#### Version

1.9.4

**Comment by HenrikJannsen** [comment]
The Enum value should stay as it is to not risk any issues, but the translation string can be changed.
