### ISSUE TITLE
"Withdraw your bitcoins" for a completed trade remains available after funds are withdrawn via "Funds" tab

### ISSUE THREAD

**Issue by ptmhd** [bisq-network/bisq#705]
minor (trivial?) issue - steps to reproduce

wait until payment is received by seller (check Portfolio, open trades, status should be "Completed")
go to tab Funds, available for withdrawal and withdraw the output corresponding to the transaction of the completed purchase, confirm withdrawal to external address
go back to portfolio, the button "Witdraw to external address" is active, can be clicked and shows an error when clicked.

I would guess that it will deactivate itself after 1st confirmation but nevertheless I'd expect the trade info would not offer withdrawal if the funds are already spend.
also the amount to withdraw was not set to 0.

**Comment by ptmhd** [comment]
can you close it, please? seems like normal behaviour. no matter if withdrawn via portfolio or funds, the buttons remain active and transaction stays there until confirmed?

**Comment by ManfredKarrer** [comment]
Seems like the update of the state if the funds are withdrawn is missing when u go back to the completed screen. I leave it open for future fix.

**Comment by Flugstein** [comment]
same issue here. the trade stays in "open trades" even though the funds are already withdrawn to the external address. if you afterwards click the other button to keep the money in bitsquare the trade gets moved to history.
