### ISSUE TITLE
Error trying to make a Buy order.

### ISSUE THREAD

**Issue by MarkJelic** [bisq-network/bisq#7051]
### Description

Buy order seemed to be going through fine but after the Funding page for the deposit, i received an error that recommened a restart, after recommending I make an Issue in GH

#### Version

Version 1.9.14

### Screenshots
![image](https://github.com/bisq-network/bisq/assets/13119623/c1d62928-d2fe-4280-9191-aaa653225223)

![image](https://github.com/bisq-network/bisq/assets/13119623/9a2ea32f-fb2e-4797-967e-0f9883871f24)

#### Device or machine

Windows 10

**Comment by MarkJelic** [comment]
BTW, I seemed to have lost a considerable amount of BTC out of my BISQ wallet... I selected that as a way to fund the deposit. And now it seems like 0.005 BTC has disappeared. :(

**Comment by MarkJelic** [comment]
[bisq-error.log](https://github.com/bisq-network/bisq/files/14473062/bisq-error.log)

**Comment by ghost** [comment]
Your take offer did not complete successfully as it had issues synchronizing the DAO state.  The only funds that left your wallet was the trade fee of `0.0001725 BTC` (taker tx: `a7bb64e4482d905d98c318d6bc3bb7a9fd73386aa2697b1a27ee9771f951f960`) which is eligible for reimbursement.   See https://bisq.wiki/Failed_Trades_-_Reimbursement_of_Trade_Fees_and_Miner_Fees

@darawhelan can assist if you need further support.

**Comment by MarkJelic** [comment]
I don't know where to ask, and it's a kind of continuance of this issue, so hope you don't mind me asking:
I cannot seem to pick ANY Buy trade. When I select one, the screen changes to where I can enter in the quantity I want to buy, but before I can even tab out of that field, I get this error:
![image](https://github.com/bisq-network/bisq/assets/13119623/d81be897-72d2-4e8a-939d-bbefe9325745)
How do I know if my DOA data is out of sync? And by what method do I sync it?

**Comment by suddenwhipvapor** [comment]
Regarding the first error:
https://bisq.wiki/BuyerVerifiesPreparedDelayedPayoutTx_Exception_error
About your last screenshot, you should go to Settings > Preferences and scroll down to click on the button that says Rebuild DAO from resources
