### ISSUE TITLE
Error on sell transaction

### ISSUE THREAD

**Issue by nerd023** [bisq-network/bisq#7052]
### Description
On sell transaction got below error. See details and screenshot.
ERROR o.b.n.BlockingClient: Error trying to open/read from connection: emzybtc454ewbviqnmgtgx3rgublsgkk23r4onbhidcv36wremue4kqd.onion:8333: SOCKS: Host unreachable 

#### Version
Bisq version 1.9.14

### Steps to reproduce
1. Find a sell offer that is -1.00%
2. Review the offer and accept
3. U will get an error

### Expected behaviour
Offer should proceed to step 2, where chosen buyer should accept it and pay. Instead of that it failed instantly without notifying buyer.

### Actual behaviour
Got above error

### Screenshots
![sell-err](https://github.com/bisq-network/bisq/assets/161706357/23a8a58d-17d1-4f3d-a858-76a3c1473380)
[Uploading bisq.log…]()

#### Device or machine
Win 10 Pro

#### Additional info
Logs attached.

**Comment by ghost** [comment]
Protocol not completing in 120 seconds - that typically is due to interruption of the Tor connection.   See https://bisq.wiki/Failed_Trades_-_Reimbursement_of_Trade_Fees_and_Miner_Fees

@darawhelan can assist if you need support.

**Comment by nerd023** [comment]
Thanks for quick community support @jmacxx
