### ISSUE TITLE
 An error occurred at task: SellerSendPayoutTxPublishedMessage

### ISSUE THREAD

**Issue by Truffle3280** [bisq-network/bisq#7056]
### Description

 Exception message: Not able to find peers witness, unable to sign for trade 

#### Version

1.9.14

### Steps to reproduce

Unable to confirm payment received

### Expected behaviour

No error message

### Actual behaviour

error message

### Screenshots
![Screenshot from 2024-03-16 06-03-39](https://github.com/bisq-network/bisq/assets/122084488/93f478b7-dfd9-4476-abcf-78923f21ae1b)

#### Device or machine

Pop!_OS 22.04 LTS

**Comment by suddenwhipvapor** [comment]
Did this happen with just the one peer, or is it something that occured more than once?
