### ISSUE TITLE
Error exporting Account Age for Bisq2

### ISSUE THREAD

**Issue by DiverterNoKYC** [bisq-network/bisq#7058]
### Description

In the account section in Bisq there is a button to Export Account Age for Bisq2 so that it can be imported. When tapping that button I am met with an error pop-up message.

#### Version

v1.19.4

### Steps to reproduce

- Open Account tab in Bisq
- Select one of the payment accounts
- Scroll to the bottom and tap the button to Export Account Age for Bisq2

### Actual behaviour

Receiving a pop-up error message as shown below:
(Also worth noting my clipboard is empty)

### Screenshots

![image](https://github.com/bisq-network/bisq/assets/74485231/ff425a01-9200-4441-918d-6c0dad969499)
![image](https://github.com/bisq-network/bisq/assets/74485231/ba5c4968-7930-46da-b2cc-720ae4a03601)

#### Device or machine

- Dell Latitude laptop
- Pop!_OS 22.04 LTS 64-bit

**Comment by DiverterNoKYC** [comment]
Resolved

**Comment by MwithM** [comment]
Copied from @suddenwhipvapor

When you click on the export button in bisq1, you need to already have the clipboard populated with data from bisq2, by going to User Options > Reputation, click on signed account age witness, and then click the copy to clipboard button near your user profile id, then bisq1 will automatically update the clipboard contents with the signed data that you paste in bisq2.
