### ISSUE TITLE
Improve export account

### ISSUE THREAD

**Issue by axpoems** [bisq-network/bisq#7066]
### Description

When importing account age in Bisq 2, users need to export their account from Bisq 1.
We should make it more explicit with adding the profile ID field and show the json content which will be copied.
Ref: https://github.com/bisq-network/bisq2/issues/1834#issuecomment-2002847706

**Comment by ghost** [comment]
@alejandrogarcia83 : [improve_export_account.patch.gz](https://github.com/bisq-network/bisq/files/15171095/improve_export_account.patch.gz)
