### ISSUE TITLE
File  bisq-1.9.15.tar.gz.asc missing?

### ISSUE THREAD

**Issue by BtcAutoNode** [bisq-network/bisq#7072]
Hi,

the .asc file is missing for the v1.9.15.tar.gz file on the release page.

best regards

Description
Version
Steps to reproduce
Expected behaviour
Actual behaviour
Screenshots
Device or machine
Additional info

**Comment by FreddieChopin** [comment]
This issue is not completed, the signature is still missing and this file is used by Arch Linux's package to verify the downloaded source...

**Comment by BtcAutoNode** [comment]
This is the message I got to that in the Telegram group. I would also rather have the .asc file for the tar.gz but changed my bash scripts now to verify the source code cloning the git repo: 
![grafik](https://github.com/bisq-network/bisq/assets/149917291/b08aed33-9616-4ce0-8b0f-aedbf59e1311)

**Comment by BtcAutoNode** [comment]
.asc file for the .tar.gz source package is now available. Many thanks for that!
