### ISSUE TITLE
Requested report of issue from bisq application

### ISSUE THREAD

**Issue by dav1dpgit** [bisq-network/bisq#7073]
Requested report of issue from bisq application
[bisq.log](https://github.com/bisq-network/bisq/files/14940664/bisq.log)

**Comment by suddenwhipvapor** [comment]
Can you briefly describe the nature of the issue with your own words? what were you trying to do and what happened that prevented you from doing it?

**Comment by dav1dpgit** [comment]
Sorry it was the auto-log and notfication so didn’t pay too much attention to the details.  Likely it required a full SPV resync on an old account so was excessively slow, failing and freezing multiple times, resulting in deleting a spvresync file and starting from scratch in order to recover.  It is working now but not the smoothest as the SPV often becomes out of sync (again, and old wallet).On May 10, 2024, at 9:19 AM, suddenwhipvapor ***@***.***> wrote:﻿
Can you briefly describe the nature of the issue with your own words? what were you trying to do and what happened that prevented you from doing it?

**Comment by suddenwhipvapor** [comment]
Thank you for the feedback.
Best approaches in this case, only one or even better both:
https://bisq.wiki/Create_a_new_wallet_for_your_data_directory
https://bisq.wiki/Installing_your_own_Bitcoin_node

**Comment by HenrikJannsen** [comment]
Tor is suffering ddos attacks (https://metrics.torproject.org/torperf.html).
The next release will come with some improvements fro initial data loading which should improve a bit the issues.
If you can run locally a full Bitcoin node this greatly improves startup performance. 
See: https://bisq.community/t/psa-consider-running-your-own-bitcoin-node/12005
