### ISSUE TITLE
Error at starting up, this.textNode is null

### ISSUE THREAD

**Issue by bxabi** [bisq-network/bisq#7074]
### Description
Bisq initializing but gives this error

#### Version

1.9.15

### Steps to reproduce

Start Bisq

### Expected behaviour

Starts without an error

### Actual behaviour

Error Window

### Screenshots

![image](https://github.com/bisq-network/bisq/assets/11303766/c011a98b-e9ba-45fd-97a9-46da13d5b3e2)

#### Device or machine

Arch Linux, openJDK 17

#### Additional info

[bisq.log](https://github.com/bisq-network/bisq/files/14968664/bisq.log)

**Comment by bxabi** [comment]
With Java 11 it works.

**Comment by suddenwhipvapor** [comment]
> With Java 11 it works.

so you downgraded from version 17 to version 11 and it worked fine?

**Comment by bxabi** [comment]
yes I have both installed, if I set JAVA_HOME to the 11, it works.

**Comment by suddenwhipvapor** [comment]
Thank you very much for this feedback.
