### ISSUE TITLE
Cloning main yields 1.9.14, and `Cannot invoke javafx.scene.Node.getLayoutBouns() because "this.textNode" is null`

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/bisq#7088]
### Description

I use xpra to remotely access bisq running on a headless debian server with no GUI. Up until 1.9.14 everything went fine, I used to restrictively clone the last version with `git clone --branch release/v1.9.14 https://github.com/bisq-network/bisq`
After I received the update popup I decided to clone main and compile, but when I run it I still see 1.9.14 instead of 1.9.15, and I once again get the popup to update. RIght after that, the error popup for `Cannot invoke javafx.scene.Node.getLayoutBouns() because "this.textNode" is null` appears, and when I close it, every tab I navigate to is empty.
I tried with a fresh data directory, and after the numerous popups that appear after the first start, the same thing happens.

If I manually select branch 1.9.15 when cloning, I can clearly see that version at the bottom after I run the compiled application, and no update popup is shown, but except that, everything else is the same with the aforementioned error.

I currently fell back to 1.9.14 by manually selecting that branch while cloning, so I can at least participate to the DAO.

#### Version

1.9.15

### Steps to reproduce

Run on headless debian bullseye through xpra

### Expected behaviour

Normal operation

### Actual behaviour

The one described above.

#### Device or machine

Debian bullseye, no GUI, launching with xpra

**Comment by dutu** [comment]
Master branch is missing a few commits from v1.9.15 and it won't work properly when compiled (for example version is still shown as `v1.9.14`)

https://github.com/bisq-network/bisq/compare/master...release/v1.9.15

**Comment by suddenwhipvapor** [comment]
> Master branch is missing a few commits from v1.9.15 and it won't work properly when compiled (for example version is still shown as `v1.9.14`)

nothing notable changes if I manually select 1.9.15 while cloning though, I see bisq correctly reporting 1.9.15 in the version number but I still get the error popup from above that makes the application unusable
