### ISSUE TITLE
Input validations for account data

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#709]
We should add complete input validation for all account forms.

For the Fiat accounts we should add (listed by priority):
IBANValidator
BICValidator
InteracETransferValidator
ClearXchangeValidator
ChaseQuickPayValidator
SwishValidator
OKPayValidator
PerfectMoneyValidator

Validation rules have to be researched (code examples can be found by a internet search for most).

For the altcoins we should add altcoin address validation if the address format is clear. That will require a bit of research to all main altcoins. 
We should only add those where we have clear information.
Many altcoins are based on Bitcoin and will prob. inherit Bitcoins address format rules.
We can start with basic validation (lenght, typical start characters,...) and then add the checksum validation if the address format uses that.

To start with lets use the top 10 altcoins from the trade statistics.

package: io.bitsquare.gui.util.validation

**Comment by ManfredKarrer** [comment]
I added a requirement for new altcoins to add a PR for the validation:
https://forum.bitsquare.io/t/how-to-add-your-favorite-altcoin/46/97

The top 10-20 altcoins form trading activity we should implement anyway if we don't get a PR form their community in time.

**Comment by ManfredKarrer** [comment]
I will offer a bounty for that task. If you are interested get in touch and we discuss the amount and work package. The above might be split into smaller packages based on priorities.

**Comment by SimonTuberlin** [comment]
Created a pull request for IBAN and BIC validation. Both have been tested with my limited number of German accounts and variations of the violating the format rules. So far it worked well. Possible known issues are stated in the PR comment.

edit: correlation between BIC/IBAN country code and selection from country dropdown menu should be added

**Comment by ManfredKarrer** [comment]
@SimonTuberlin Great thanks! Please contact me by email (manfred at bitsquare dot io) for arranging a bounty. I will be offline tomorrow but will answer asap.
