### ISSUE TITLE
Invalid offers

### ISSUE THREAD

**Issue by Chordbridge** [bisq-network/bisq#7091]
### Description

I don't think it can take my offers.

#### Version

1.9.15

### Steps to reproduce

unsure

### Expected behaviour

take my offers

### Actual behaviour

No offers taken

### Screenshots

unsure

#### Device or machine

Linux Lubuntu

**Comment by suddenwhipvapor** [comment]
that's not very explicative! :-)
If you mean that you suspect your own offers cannot be taken by other users, you can go to bisq.chat and ask a support agent to try taking your offer to see if it at least reaches the confirmation stage

**Comment by HenrikJannsen** [comment]
I close as the description lacks information. If you manage to describe your problem in more clear terms please open an issue again.
