### ISSUE TITLE
Update process is not clear

### ISSUE THREAD

**Issue by Giszmo** [bisq-network/bisq#7093]
### Description

When following the "please update" prompt, the process stops with "Signatures verified with keys" but no "Finish" button or instructions what to do next.

Apparently there were further popups about mandatory updates under the one below (screenshot).

#### Version

1.9.14

### Expected behaviour

Actionable popups should be above others.

### Actual behaviour

I had to click "Download later" after successfully downloading.

### Screenshots

![image](https://github.com/bisq-network/bisq/assets/96378/6c0500e2-193c-4774-b8f8-e656bde3ce46)

**Comment by suddenwhipvapor** [comment]
After the download and verification steps are done, you are expected to install the deb from the commandline, the download location escapes me honestly, but you can use your file manager to search for the `Bisq-64bit... ` file across all subfolders of your home folder

**Comment by suddenwhipvapor** [comment]
By the way, once you located the file, place yourself in that folder in a terminal, and run `sudo apt install ./Bisq-64....deb`

**Comment by Giszmo** [comment]
I'm old-school, so I do `dpkg -i` but Bisq should inform the user that it's done checking signatures and show a shutdown button and maybe even inform about the folder the files were downloaded to. Having to click "Download later" is awkward.

**Comment by suddenwhipvapor** [comment]
Yes, it would be more streamlined to present UI to close Bisq and then also open a file manager in the destination folder.
Maybe this issue could work as a feature request.
