### ISSUE TITLE
Fix performance bug in confirmation component

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#71]
Confirmation component use too much resources if there are many instantiated. Check for memory leaks and reason why CPU consumption is too high.

**Comment by ManfredKarrer** [comment]
Change the rotation animation to a question mark. Many users did not associate waiting confirmation with the spinner.

**Comment by ManfredKarrer** [comment]
Tested with animation disabled (//spinner.indeterminateTimeline.play();) and cpu usage went down to 1% from 10 - 20%!

**Comment by cbeams** [comment]
> Tested with animation disabled (//spinner.indeterminateTimeline.play();) and cpu usage went down to 1% from 10 - 20%!

nice... :)

**Comment by ManfredKarrer** [comment]
Normally we dont have many displayed, so lets kepp it for the moment.
