### ISSUE TITLE
No reaction after click the Bisq in Application(for Bisq 1.9.15)

### ISSUE THREAD

**Issue by ScottJeromeLouis** [bisq-network/bisq#7107]
/
### Description
Hey Guys new Bisqer here! I just followed the run-on-Tails on Github page step by step and seems everything is fine after install Bisq .
But after I click the Bisq application in the menu icon, it requires a password of tails account and I did it.
And then it said ''starting Bisq........'' and no reaction then.

**Comment by dutu** [comment]
@ScottJeromeLouis this is probably related to Tails setup and not Bisq application itself, hence you could close this issue and I can try to help you here: https://github.com/dutu/run-on-tails/issues/1
