### ISSUE TITLE
Remove link to feedback survey

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq#7116]
The link to the survey does not exist anymore. We should remove that.

![Screenshot 2024-05-26 at 12 39 02](https://github.com/bisq-network/bisq/assets/116298498/6faefa5b-0891-49a9-8902-32a33c713e73)

**Comment by HenrikJannsen** [comment]
Still relevant

**Comment by HenrikJannsen** [comment]
Still relevant

**Comment by yehiahesham2938** [comment]
Hi @HenrikJannsen , this issue seems interesting, I'll start on my implementation, could you please assign it to me.

**Comment by yehiahesham2938** [comment]
Hey @HenrikJannsen, I see that the issue is already solved when forked the repo and started removing the link to feedback survey.
![bisqIMG](https://github.com/user-attachments/assets/ccca4a7f-52f3-4c44-acfe-3429a28fae9f)

**Comment by HenrikJannsen** [comment]
Ah thanks for looking into it. Then we can close it. Feel free to browse other open issues if you have time! Also in Bisq 2 there is lot of open work ;-)
