### ISSUE TITLE
error while placing an order to sell DarkNet

### ISSUE THREAD

**Issue by PIVX-Project** [bisq-network/bisq#712]
An error occurred when placing the offer:

A timeout occurred at publishing the offer.

No funds have left your wallet yet.
Please try to restart you application and check your network connection to see if you can resolve the issue.

**Comment by ManfredKarrer** [comment]
Hm... do u have a stable internet? should not happen.

**Comment by p4tr1kb** [comment]
Same issue here but for an order to buy. On the third attempt I removed the custom peer setting (was pointing to my local node) and then it worked. Restarted the app between all attempts.

**Comment by ManfredKarrer** [comment]
"custom peer setting" -> u mean a local bitcoin core node?

**Comment by p4tr1kb** [comment]
Yes, a local full bitcoin node

**Comment by ManfredKarrer** [comment]
Ok. you need to enable incoming connections in the settings of bitcoin core if u have it running, otherwise bitsquare cannot connect to it. if there is a local btc node it tries to connect to that as that gives u better privacy (flawed bloomfilter).
