### ISSUE TITLE
SPV resync stalls forever

### ISSUE THREAD

**Issue by snex** [bisq-network/bisq#7127]
### Description

I had to do an SPV resync. No matter how many times I try, it eventually stops downloading blocks. There are peers connected, but they never send any data.

#### Version

1.9.15 Ubuntu Linux

### Steps to reproduce

Perform SPV resync.

### Expected behaviour

It should eventually sync and start the app

### Actual behaviour

It eventually gets stuck and refuses to go further. I feel like the peers I am connected to are malicious and doing this on purpose, while also refusing to drop connection so that I can connect to real ones.

#### Additional info

Logs are filled with the following:

May 29 09:01:01 bisq bisq-Bisq.desktop[759418]: #033[0;39m#033[34mMay-29 09:01:01.047 [PeerGroup Thread] INFO o.b.c.PeerGroup$ChainDownloadSpeedCalculator: 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 0.00/0.00 kilobytes per sec, chain/common height 755585/845659, stall disabled (threshold <0.78 KB/sec for 10 seconds)

Occasionally, there will be a log statement about other peers refusing to connect.

**Comment by phbassett** [comment]
I have the same issue.  And am not getting any support.

**Comment by pazza83** [comment]
Have you installed the latest version 1.9.17?

**Comment by snex** [comment]
For me it has been working properly since 0.9.16/17
