### ISSUE TITLE
Failed to launch JVM Error after trying to upgrade Bisq

### ISSUE THREAD

**Issue by Joseph922** [bisq-network/bisq#7132]
### Steps to reproduce
Open Bisq application
->Faild to launch JVM pop up box appears without opening the application.

### Expected behaviour

<The bisq application is able to open and my user and backup data are available -->

### Actual behaviour

[Screen shots May 24'.odt](https://github.com/user-attachments/files/15516946/Screen.shots.May.24.odt)

**Comment by Joseph922** [comment]
Thank you, please let me know if anything else is needed in the issue template to begin review. Thank you for your support.

**Comment by HenrikJannsen** [comment]
Do you run the binary or from source code? Which Operating system do you use?

**Comment by Joseph922** [comment]
Hello Henrik,

I am using windows and using the operating system. I downloaded bisq from the bisq wiki page and it was working great. I was prompted for the update and after started to receive the failed launch JVM error. I tried uninstalling and reinstalling without luck. I also tried clearing the properties folder and in the process of working through it a couple times I believe I deleted it. I have tried to recreate it but not positive the format is correct. Thank you for reaching out and please let me know what I can provide to assist in resolution.

Best regards

**Comment by suddenwhipvapor** [comment]
Are you using Windows 11 by chance? If I remember correctly, I've seen this issue already being reported for that version

**Comment by Joseph922** [comment]
Yes I am using windows 11 home edition, version 23H2 at the moment.

**Comment by suddenwhipvapor** [comment]
As I suspected, this is but one of the issues that I remember being reported for Windows 11.
I am not directly aware of any sure way to work around this issue, but I can suggest to try these steps:
1. Run Bisq in compatibility mode (right click on application icon, then it's probably somewhere under Advanced, select windows 10, or XP, play around) and if it doesn't work...
2. Run bisq with administrative rights, still from under right click - properties menu of the icon, can't remember in which submenu but you are bound to find it, and if not even this works...
3. install a linux image, preferably debian, under VirtualBox, and install and run bisq from there, this is the hardcore way, but I expect it to work 100%, so you can even clone and build from source, and maybe who knows, you get to like linux and get rid of windows for good 😉

**Comment by Joseph922** [comment]
The first option did not work, however I only had windows 8 version to choose from instead of windows 10 or XP. (I can try to download windows 10 and see if it shows as an option). The second option created the same Failed JVM error. I am not familiar with Linux but if I pursue this method what happens to the backups, should I move them to a flash drive during update? Will they be able to be loaded back into bisq or would I be starting with new user and need to upload wallet with seed.

Best regards

**Comment by suddenwhipvapor** [comment]
linux is scary just on paper, believe me, because once you get used to the interface you will learn how much better it is than windows.
The most common interface, afaik, is Gnome, and with that running, the underlying system is less important. Ubuntu is a derivative of Debian, like PopOs, so you could choose whichever one. I personally prefer Debian myself.
In any case, the data directory is 100% portable, you can keep it on windows the whole time, and when you have finally installed bisq on the virtual machine, you can use virtualbox tools to copy the data directory contents from C:\Users\Yourname\AppData\Roaming\Bisq to /home/youruser/.local/share/Bisq, and when you start bisq again you will see the same data you had on windows

**Comment by Joseph922** [comment]
Thank you,

I have downloaded virtual box and downloaded Ubuntu on it. I am still reading through what is needed to download bisq. Just wanted to give you a heads up I am still pursuing the option just trying to get over learning curve.

**Comment by suddenwhipvapor** [comment]
That's great! Installing bisq on linux requires you to `wget` the installer `.deb` file and then run it with `sudo apt install ./....deb`

**Comment by Joseph922** [comment]
Hello,

So not extremely tech savvy but I was able to set up the virtual box and download Ubuntu. I have download the Deb and PGP signature files. At this point the instructions switch over to macOS and I’m on a HP computer running Linux. Can I just down load the PGP public key or do I need to execute functions from terminal command? Also on windows I needed to download Gpg4win then open file in kleopatra in order to verify, I don’t see these steps for Linux. Any additional information would be great, I don’t use command functions normally so definitely a little learning curve here.

**Comment by Joseph922** [comment]
Would it be possible to send me the command functions for download? At the moment I am receiving an error E: unable to locate package bisq-64bit-1.9.15.deb

**Comment by suddenwhipvapor** [comment]
This is the general outline you should follow:
 - from https://bisq.network/downloads/ get the .deb and its PGP signature, and from the end of the list the PGP public key (to get some training with the linux commandline, open a terminal in Debian, immediately run `cd /tmp` and then copy to clipboard the urls of each file, and for all of them do `wget <url>` (you paste in terminal with Ctrl-Shit-V if I'm not wrong, or right click on the background and select paste)
 - do `gpg --import E222AA02.asc` from the terminal (gpg should already be installed, but if it isn't, before then do `sudo apt install gpg`)
 - do `gpg --digest-algo SHA256 --verify Bisq-64bit-1.9.15.deb.asc` (that should be the name of the PGP signature file you downloaded)
 - if it says "Good signature" at the end, you can do `sudo apt install ./Bisq-64bit-1.9.15.deb`

After this you should have bisq installed and ready to be run.
When it's time to update, you can do the same exact thing as above, the new version will install over the old one without issues.

**Comment by Joseph922** [comment]
Do I need to move these files from the downloads folder to somewhere else in order to install? At the moment I am trying to import the E222AA02.asc file and am receiving the below error:

gpg: can’t open ‘E222AA02.asc’ : no such file or directory.

I have the 3 below files sitting in my downloads folder:

E222AA02.asc
Bisq-64bit-1.9.15.deb.asc
Bisq-64bit-1.9.15.deb

There were no updates for gpg install, so I believe that is installed already.

Thank you for your help,

Best regards

**Comment by suddenwhipvapor** [comment]
you have to be located in the same folder where those files reside, in order to run the above commands, so instead of `cd /tmp` you will need to do `cd /path/to/download/` in the example above

**Comment by Joseph922** [comment]
Thank you, that was it! I needed to change the file path, wow I have a lot to learn on the new system. Really appreciate you walking me through.

As the last step which files and how do I need to transfer my old back up file to the new Bisq on Linux virtual box.

Best regards

**Comment by suddenwhipvapor** [comment]
See this link: https://bisq.wiki/Data_directory#Default_locations
Those are the default locations for data directory in the different OSes. So you copy the contents of the data directory in Windows, over the location of the data directory in linux, and then start bisq

**Comment by Joseph922** [comment]
Thank you, I have made a copy of Bisq location on linux and renamed it Bisq Linux. I have copied this file and renamed it Bisq as the original file showed. I believe I can use the SCP function to move the files however can i migrate the entire btc_mainnet folder? Or do I need to move each file individually. Do I need to worry about any other files outside of the btc_main net folder?

**Comment by suddenwhipvapor** [comment]
You can copy all files in one go. Usually with VMs there is also a share feature where you can have the guest OS access a mounted folder from the Host OS so you can pass files both ways.
In any case, yes, do copy the btc_mainnet folder over, or much simpler, just copy the parent folder of the data directory, Bisq, to the place where it should be in the Guest

**Comment by Joseph922** [comment]
Thank you so much for your amazing support and patience with me as I stepped into the command line logic and Linux operating system.

I officially logged back into my account on Bisq. All history, wallet, etc are perfect! I really appreciate all your support.

I did log in and see there is a new version and I am terrified to update again. Is there simple logic I can run in command line to update?

Now I just need to figure out how to increase my virtual machine speed and I’ll possibly be in better shape than at the beginning of the issue.

Can’t thank you enough for your assistance.

Best regards,

**Comment by suddenwhipvapor** [comment]
Great! Thank you for the dedication you showed into wanting to get back onto Bisq :-) As a complete linux newbie as you said you were, it must have took quite some work.

Regarding the update, you do just like you already did with 1..9.15, follow the exact same steps in downloading files, verifying and installing

**Comment by suddenwhipvapor** [comment]
Oh, by the way, regarding the VM speed issue, you can usually increase it by increasing the CPU cores it can use, and the ram. but you will conversely decrease those still available for the host OS.

**Comment by Joseph922** [comment]
Hello,

I have attempted to download the new version of bisq, however I am receiving an error Alejandro Garcia signature is good, but expired.

Would you be able to assist me on how to download the new version of the signature is expired?

**Comment by suddenwhipvapor** [comment]
I think you should delete the old key by Alejandro Garcia and then import it again to get the new one.
See this which maybe helps:
https://stackoverflow.com/questions/73293254/how-to-delete-gpg-keys-no-longer-needed

**Comment by suddenwhipvapor** [comment]
Or maybe this could help
https://security.stackexchange.com/questions/239713/is-gpg-refresh-keys-secure-and-where-is-this-documented

**Comment by Joseph922** [comment]
Thank you for the quick response, that worked!

I appreciate your support,

Best regards,

**Comment by maresol-py** [comment]
Hello,

I had this same "JVM Error" on Windows 11 and after found this tread I decided to move to Linux.
I'm a newbee on Linux OS.

I use an WMware Fusion on macOS ARM64 to virtualize the Debian Linux.

But, when I tried to install Bisq on it, I receive the error below:

```
root@debian:/home/maresol/Downloads# sudo apt install ./Bisq-64bit-1.9.21.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'bisq:amd64' instead of './Bisq-64bit-1.9.21.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bisq:amd64 : Depends: libc6:amd64 but it is not installable
              Depends: zlib1g:amd64 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I don't know why, it selected "amd64" instead to "arm64".

Looking on github I found Bisq is amd64 and arm64 compatilble (https://github.com/bisq-network/bisq-website/issues/136#issuecomment-488770755). Or it's not?

If it is compatible to both, why I couldn't install on arm64?

Can someone help me?

Thanks in advance.

**Comment by suddenwhipvapor** [comment]
> Hello,
> 
> I had this same "JVM Error" on Windows 11 and after found this tread I decided to move to Linux. I'm a newbee on Linux OS.
> 
> I use an WMware Fusion on macOS ARM64 to virtualize the Debian Linux.
> 
> But, when I tried to install Bisq on it, I receive the error below:
> 
> ```
> root@debian:/home/maresol/Downloads# sudo apt install ./Bisq-64bit-1.9.21.deb
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Note, selecting 'bisq:amd64' instead of './Bisq-64bit-1.9.21.deb'
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  bisq:amd64 : Depends: libc6:amd64 but it is not installable
>               Depends: zlib1g:amd64 but it is not installable
> E: Unable to correct problems, you have held broken packages.
> ```
> 
> I don't know why, it selected "amd64" instead to "arm64".
> 
> Looking on github I found Bisq is amd64 and arm64 compatilble ([bisq-network/bisq-website#136 (comment)](https://github.com/bisq-network/bisq-website/issues/136#issuecomment-488770755)). Or it's not?
> 
> If it is compatible to both, why I couldn't install on arm64?
> 
> Can someone help me?
> 
> Thanks in advance.

Bisq is strictly amd64-only, that post you linked does not in fact say that bisq is arm64 compatible, just that he expected it even if it wasn't the case

**Comment by maresol-py** [comment]
@suddenwhipvapor thank you for your reply.

Than, Bisq is amd64 only and don't support arm64, is it? When they posted to "name" as "x64" to represent both, it's not true, yet. But, it will support arm64 in the future? You know?

In this case, I'm running in circle. I have a problem with JVM Error on Windows 11 and can't move to Linux because my hardware is arm64.

Any advice?

**Comment by suddenwhipvapor** [comment]
> [@suddenwhipvapor](https://github.com/suddenwhipvapor) thank you for your reply.
> 
> Than, Bisq is amd64 only and don't support arm64, is it? When they posted to "name" as "x64" to represent both, it's not true, yet. But, it will support arm64 in the future? You know?
> 
> In this case, I'm running in circle. I have a problem with JVM Error on Windows 11 and can't move to Linux because my hardware is arm64.
> 
> Any advice?

I think you can't expect Bisq to ever  support arm64 in the future, it will likely always be an amd64 application.
Regarding your windows error, which I've seen reported for windows 11 already, you can install debian in a virtualbox VM and run Bisq from there

**Comment by maresol-py** [comment]
> > [@suddenwhipvapor](https://github.com/suddenwhipvapor) thank you for your reply.
> > Than, Bisq is amd64 only and don't support arm64, is it? When they posted to "name" as "x64" to represent both, it's not true, yet. But, it will support arm64 in the future? You know?
> > In this case, I'm running in circle. I have a problem with JVM Error on Windows 11 and can't move to Linux because my hardware is arm64.
> > Any advice?
> 
> I think you can't expect Bisq to ever support arm64 in the future, it will likely always be an amd64 application. Regarding your windows error, which I've seen reported for windows 11 already, you can install debian in a virtualbox VM and run Bisq from there

I forgot to mention, my Windows 11 runs on VMware Fusion on the same arm64 hardware.

Interestingly, I only realized now that Bisq, before this JVM error, was running on this Windows for arm64. But sometimes it would crash, probably because of the arm64 vs. amd64 architecture.

**Comment by suddenwhipvapor** [comment]
> > > [@suddenwhipvapor](https://github.com/suddenwhipvapor) thank you for your reply.
> > > Than, Bisq is amd64 only and don't support arm64, is it? When they posted to "name" as "x64" to represent both, it's not true, yet. But, it will support arm64 in the future? You know?
> > > In this case, I'm running in circle. I have a problem with JVM Error on Windows 11 and can't move to Linux because my hardware is arm64.
> > > Any advice?
> > 
> > 
> > I think you can't expect Bisq to ever support arm64 in the future, it will likely always be an amd64 application. Regarding your windows error, which I've seen reported for windows 11 already, you can install debian in a virtualbox VM and run Bisq from there
> 
> I forgot to mention, my Windows 11 runs on VMware Fusion on the same arm64 hardware.
> 
> Interestingly, I only realized now that Bisq, before this JVM error, was running on this Windows for arm64. But sometimes it would crash, probably because of the arm64 vs. amd64 architecture.

not too sure about that but even if you run virtualbox on a arm64 architecture I think bisq is not going to work... worth trying.
