### ISSUE TITLE
BISQ wont start

### ISSUE THREAD

**Issue by Wolfstorm321** [bisq-network/bisq#7141]
BISQ is not starting. The software is stuck on 3/4 and wont advance past it. VPN is turned off, BISQ is using Tor. 
Its been like this for two hours already. I'm on my fifth trial. 

Yesterday it took 40 minutes to start. 
What could possible cause this issue?

**Comment by darawhelan** [comment]
Take a look at this issue and the proposed solution https://github.com/bisq-network/support/issues/1659
