### ISSUE TITLE
blockchain height sync error preventing any new trades although blockheight is sync'ed up correctly

### ISSUE THREAD

**Issue by ialkeilani** [bisq-network/bisq#7145]
### Description

I keep getting this error when i try to create a sell order.  i double checked the block height in network settings, it is synced up correctly up to the last mined blocked (846758 as of this moment).  I even waited for the applicatioon to allow for more than 1 block to be synced...but i keep getting it?  can some1 help?

![image](https://github.com/bisq-network/bisq/assets/6824858/6c169d65-368f-4a0f-a02e-8ceb49e6d6e6)

#### Version

1.9.15

### Steps to reproduce

Launch the application and monitor network settings to ensure bitcoin block height is synced to last mined block
wait for 1 additional block to sync
try to take or create a trade

### Expected behaviour

bisq should allow me to take/create a trade

### Actual behaviour

bisq does not allow me to take/create a trade

### Screenshots

![image](https://github.com/bisq-network/bisq/assets/6824858/ac76f6ad-8712-45f6-b87c-5774bdea7cd5)

#### Device or machine

windows 10 and ubuntu 20.04

**Comment by ljaa45** [comment]
Same thing. Bisq might be dead. Constantly asking me to do SPV resync, DAO is not in sync, disappearing on my pc and making me repair the installing.  I can barely get a trade through.

I don't know wtf is going on in Bisq 2, it's a clown show. Losing access to the data of who you have traded with in the past is no bueno.

**Comment by ialkeilani** [comment]
i already switch to use other services like RoboSats and hodlhodl.com.  bisq is a pain to use.  very difficult to get it to do what you want unless you really really now how to troubleshoot issues that come up everytime i launch the application

**Comment by 73tscho** [comment]
I have the same issue since I updated from 1.9.15 to 1.9.17
I tried to connect to my local node instead of default settings. There was no change and the problem remains.
What can I do?
