### ISSUE TITLE
missin filter object from the seed nodes.

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#7156]
### Description

when i launch the app this message popup after the usual loading of finding peers.
Warning
We did not receive a filter object from the seed nodes. This is a not expected situation. Please inform the Bisq developers.

#### Version
Bisq 1.9.15

### Steps to reproduce
Launch theprogram

### Screenshots
![image](https://github.com/bisq-network/bisq/assets/155928550/4c4861a0-40a1-48ba-829c-1fb155ea7fb5)

#### Device or machine
Pop!_OS 22.04 LTS
64-bit
42.9
X11

**Comment by JesseRacine** [comment]
I'm seeing the same thing. I'm using the Windows build with 1.9.1.5 and Windows 11.

**Comment by canloe** [comment]
Same, Windows 10, v1.9.1.5

EDIT: After trying a few times, I got past it but it says the DAO is resyncing. Trying to take a trade results in a new error: "Warning There are no arbitrators available."
Related?
