### ISSUE TITLE
java.lang.IllegalStateException: Ran out of space to store chain work!

### ISSUE THREAD

**Issue by snex** [bisq-network/bisq#7168]
### Description

Bisq cannot sync SPV. The error in the title is in the logs. This is happening both with network SPV sync as well as local full node.

Possibly a bug in bitcoinj and I have opened an issue over there (https://github.com/bitcoinj/bitcoinj/issues/3410)

#### Version

1.9.16

### Steps to reproduce

Just run the app, it won't sync and logs are spammed with the message

#### Additional info

Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #033[0;39m#033[31mJun-23 08:44:26.728 [NioClientManager] WARN  org.bitcoinj.core.PeerSocketHandler: [127.0.0.1]:8333 -  java.lang.IllegalStateException: Ran out of space to store chain work!
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at com.google.common.base.Preconditions.checkState(Preconditions.java:510)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.StoredBlock.serializeCompact(StoredBlock.java:121)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.store.SPVBlockStore.put(SPVBlockStore.java:201)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.BlockChain.addToBlockStore(BlockChain.java:93)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.AbstractBlockChain.connectBlock(AbstractBlockChain.java:543)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:469)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:361)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.BlockChain.add(BlockChain.java:170)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.Peer.endFilteredBlock(Peer.java:1072)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.Peer.processMessage(Peer.java:454)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:187)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:238)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at com.google.common.util.concurrent.Callables$4.run(Callables.java:117)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by snex** [comment]
Seems to be happening when trying to add block 849,138

**Comment by JulienCharon** [comment]
Same here, sync stays stuck at block 849,137

**Comment by Cognacy** [comment]
Are you able to resolve this, am having similar issue ?

**Comment by snex** [comment]
Let's make sure we put a watch on this as it is only a temporary fix that only buys us a short amount of time while bitcoinj works on a long term fix.

**Comment by cryptofant** [comment]
I have the same issue on  block 849137. How to fix this with the propose of bang-uin?

**Comment by onlymarcus** [comment]
> I have the same issue on block 849137. How to fix this with the propose of bang-uin?

I also have this same problem, and I am unable to respond to support for some trades

**Comment by snex** [comment]
Please download 1.9.17 for the fix.

**Comment by onlymarcus** [comment]
![image](https://github.com/bisq-network/bisq/assets/36059034/c899dfa1-b129-4f06-8ecf-08bf8d37dd7f)

**Comment by cryptofant** [comment]
I downloaded the bisq v 1.9.17. I got the information that the program is damaged and can't be opened. Any body solved this?

**Comment by MwithM** [comment]
That happens on mac, as they don't like you're using your own software.
https://bisq.community/t/macos-installation-error-bisq-is-damaged-and-cant-be-opened-you-should-move-it-to-trash/11748/12

**Comment by onlymarcus** [comment]
> Please download 1.9.17 for the fix.

Thank you. Problem solved.

**Comment by Rav3nPL** [comment]
It is present on bisq-daemon  1.9.16 (there is no 1.9.17 demon/cli build)
```
Jun-30 12:16:53.677 [NioClientManager] WARN  org.bitcoinj.core.PeerSocketHandler: [127.0.0.1]:8333 -  java.lang.IllegalStateException: Ran out of space to store chain work!
        at com.google.common.base.Preconditions.checkState(Preconditions.java:510)
        at org.bitcoinj.core.StoredBlock.serializeCompact(StoredBlock.java:121)
        at org.bitcoinj.store.SPVBlockStore.put(SPVBlockStore.java:201)
        at org.bitcoinj.core.BlockChain.addToBlockStore(BlockChain.java:93)
        at org.bitcoinj.core.AbstractBlockChain.connectBlock(AbstractBlockChain.java:543)
        at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:469)
        at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:361)
        at org.bitcoinj.core.BlockChain.add(BlockChain.java:170)
        at org.bitcoinj.core.Peer.endFilteredBlock(Peer.java:1072)
        at org.bitcoinj.core.Peer.processMessage(Peer.java:454)
        at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:187)
        at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:238)
        at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
        at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:117)
        at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
        at java.base/java.lang.Thread.run(Thread.java:1570)
```
