### ISSUE TITLE
Getting a error message when trying to run BitSquare

### ISSUE THREAD

**Issue by dtsddace** [bisq-network/bisq#718]
I installed BitSquare on a laptop running Windows 10.

I was able to successfully run the program, make a backup of the wallet, along with setting a passphrase.

When I rebooted the laptop, I kept getting the attached error message when trying to run the program again.

![2017-01-03_19-26-08-bitsquare-error-message](https://cloud.githubusercontent.com/assets/24905232/21629809/809bbe08-d1f9-11e6-97df-38ebc576f8d0.png)

**Comment by ManfredKarrer** [comment]
can you copy the Bitsquare.spvchain file from the backup over to the application data directory?
The file is here:
PATH_TO_DATA_DIR/Bitsquare/mainnet/bitcoin/Bitsquare.spvchain 
If that does not help copy also the wallet file over (though do a backup always before replacing).

**Comment by dtsddace** [comment]
Manfred,

I swapped the spvchain file with the one from my backup and it worked.
I'm successfully logged in.

Thanks for your help.

Jelani
