### ISSUE TITLE
Feature request: Privacy & https://market.bitsquare.io showing exact fiat value.

### ISSUE THREAD

**Issue by memetat** [bisq-network/bisq#720]
I guess this is paranoia, but could the amounts in fiat reported on market.bitsquare.io somehow not display true exact amounts, obfuscate by slightly changing exact figure slightly up/down of true value.   Banks could check this data and match transactions to bitsquare usage?

**Comment by ManfredKarrer** [comment]
Yes good point. We will consider it. Maybe just remove the cent amounts...

**Comment by dan-da** [comment]
I think it would be a false sense of security through obscurity.

The information is already public.   All that market.bitsquare.io does is display the data that the bitsquare app provides.   Anyone, including other websites or banks themselves can do this... 

For that matter, banks could just run the app and see trade amounts in there also.

**Comment by cbeams** [comment]
Issue moved to [bisq-network/markets #3](https://github.com/bisq-network/markets/issues/3) via [**ZenHub**](https://www.zenhub.com/)
