### ISSUE TITLE
BISQ wont let me confirm transaction receipt

### ISSUE THREAD

**Issue by Wolfstorm321** [bisq-network/bisq#7205]
BISQ wont let me confirm transaction receipt, it asks for four bitcoin connections. 
However, it is uncommon to have four bitcoin connections in the node. Usually it is only three, sometimes two. 
Can you fix this bug please?

**Comment by scottdax1** [comment]
Hey @Wolfstorm321 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID BTC07638
Please see the link below to our dedicated support line:
[Bitcoin Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by pazza83** [comment]
What version of Bisq are you using?

If you are unable to confirm payment then you can open mediaiton for the trade.

Most of the time not getting 4 connections seems to be a temporary issue and can be fixed with a little waiting or a restart. 

Having less connections would be helpful also.
