### ISSUE TITLE
Clarification on cash/ATM deposits and ClearXchange

### ISSUE THREAD

**Issue by dtsddace** [bisq-network/bisq#721]
In buying bitcoin with USD,, does the option of cash/ATM deposit mean that 
I can load a prepaid ATM debit card and use it to make payment to fulfill a trade?

Also, how does a clearxchange work exactly?

**Comment by ManfredKarrer** [comment]
I think ATM deposit in US does not work. It works in other counties and will be removed in the next release for US.
You need to check with your bank if it part of the ClearXchange network. See the Bitsquare Forum also for more info.

**Comment by jkelly99** [comment]
I wish in the US there was a choice for deposit in person to the seller's bank. There is a network of credit unions where that is possible, called Credit Union Co-Op or something similar.

**Comment by ManfredKarrer** [comment]
@jkelly99 Could you add more info to our Forum. If we have enough detail info we can add it.
