### ISSUE TITLE
Market Data API returns 404 error: not found

### ISSUE THREAD

**Issue by reliant8307** [bisq-network/bisq#7224]
The Market Data API link in the Bisq website is broken:

https://bisq.markets/docs/api/rest

It redirects to:

https://bisq.mempool.emzy.de/docs/api/rest

Is there another URL? Thanks.

**Comment by reliant8307** [comment]
It was fixed. Closing the issue.

**Comment by mmat0s** [comment]
Any alternative for this API?
I am using this API in a project to get BISQ market data, but looks like it not working anymore.
