### ISSUE TITLE
Error: Contracts do not match? Trade could not be completed.

### ISSUE THREAD

**Issue by PeaceLoveLightJoy** [bisq-network/bisq#7226]
### Description

As is the title. After "Take Offer..." is selected (final step) the error in title occurs. Multiple attempts generated same message.

#### Version

Bisq Ver. 1.9.17
[bisq.log](https://github.com/user-attachments/files/16486375/bisq.log)

**Comment by pazza83** [comment]
Go to DAO > Network Monitor

Check to see if your DAO is in consensus if it is not it will give you the option to resync.
