### ISSUE TITLE
DAO error

### ISSUE THREAD

**Issue by kosuodhmwa** [bisq-network/bisq#7229]
### Description

Error message 
![image](https://github.com/user-attachments/assets/badb4c33-7032-47f7-ab45-837e38678370)

#### Version

v1.9.17

### Steps to reproduce

Message seems to occur after some time, no actions needed so it seems

### Expected behaviour

Not showing that message

### Actual behaviour

Error message:
![image](https://github.com/user-attachments/assets/346fd353-9366-4d59-88f9-f546a1f87f1c)

### Screenshots

![image](https://github.com/user-attachments/assets/73e8ce43-f78b-493d-8713-56b58c3c2540)

#### Device or machine

Windows 10 x64 with most current updates

#### Additional info

No.

**Comment by kosuodhmwa** [comment]
ok thx

**Comment by kosuodhmwa** [comment]
Nobody knows that the problem is? Thas occured suddenly after the update i described. Don't know why!?

**Comment by pazza83** [comment]
Hi @kosuodhmwa 

Looks like you DAO is out of sync.

Go to DAO > Network Monitor

Check to see if your DAO is in consensus if it is not it will give you the option to resync.

**Comment by kosuodhmwa** [comment]
i already done that

**Comment by pazza83** [comment]
Is it a specific offer you are trying to take? It might be an issue with the one peer.
