### ISSUE TITLE
All trades failing at TAKER_FEE_PUBLISHED with "Timeout reached. Protocol did not complete in 120 sec."

### ISSUE THREAD

**Issue by citkane** [bisq-network/bisq#7232]
### Description

After upgrading Bisq, all trades are failing at TAKER_FEE_PUBLISHED with "Timeout reached. Protocol did not complete in 120 sec."

#### Version

v1.9.17

### Steps to reproduce

Normal trading when buying fiat or selling bitcoin.

### Expected behaviour

To successfully complete trades 

### Actual behaviour

As described.
The issue persists even after a SPV resync.

### Screenshots
Removed for privacy

#### Device or machine

Linux 64 (Debian 12)

#### Additional info

Logs, contracts
Removed for privacy

**Comment by pazza83** [comment]
Hi @citkane the maker and taker fees are valid. However no deposit transactions took place.

This usually indicates that one of the peers DAO is not in consensus.

Go to DAO > Network Monitor

Check to see if your DAO is in consensus if it is not it will give you the option to resync.

**Comment by citkane** [comment]
![Screenshot from 2024-08-16 18-05-36](https://github.com/user-attachments/assets/9e2ef451-fd9e-44c2-9de2-dee38e0eac19)
![Screenshot from 2024-08-16 18-06-54](https://github.com/user-attachments/assets/579e7253-332c-4201-8c1e-bb6a464a38de)
![Screenshot from 2024-08-16 18-07-09](https://github.com/user-attachments/assets/29f31cc3-4cc9-47ea-84a3-7995cac749f3)
![Screenshot from 2024-08-16 18-07-19](https://github.com/user-attachments/assets/049f9a24-3d72-443c-b869-b93d6c2f7413)

As you have advised, this was the situation on my node and re-sync would appear to have resolved it.

This is not a menu area that I ever need to go to, and I have no idea how things went wrong except that I upgraded to the latest version after a few months of inactivity. I never had a problem before!

The failed trades I uploaded earlier have cost me nominal fees, and reimbursement would be appreciated.

Thanks @pazza83 

UI suggestion: notification in the menu-bar of errors that can affect trades.

**Comment by pazza83** [comment]
There should be a warning that pops up when you get out of consensus and advises you to restart. Maybe you did not receive it. Try the following fix:

Go to Settings > Preferences

Under display options click 'Reset all dont's show again flags'

> The failed trades I uploaded earlier have cost me nominal fees, and reimbursement would be appreciated.

You can claim reimbursement for them see:  https://bisq.wiki/Failed_Trades_-_Reimbursement_of_Trade_Fees_and_Miner_Fees#How_to_make_reimbursement_request_for_lost_miner_and_trade_fees_from_a_failed_trade.3F

**Comment by citkane** [comment]
No, there was no warning.
It has been an aggravating two days...

Thanks for you help.
