### ISSUE TITLE
No daemon or CLI in latest release (v1.9.17)

### ISSUE THREAD

**Issue by orangefren** [bisq-network/bisq#7235]
### Description

Release notes for v1.9.17 have a section about the API. The section contains typos (references v1.9.16, despite being a release note for v1.9.17) and mentions a daemon.jar & cli.jar, both of which are missing from the release.

#### Version

v1.9.17

### Steps to reproduce

Navigate to the release page for v1.9.17 and read the release notes

### Expected behaviour

Provide a pre-built daemon.jar & cli.jar and build instructions to produce them locally.

### Actual behaviour

Pre-built daemon.jar & cli.jar are missing. Build instructions appear nowhere to be found to produce them locally. 

### Screenshots

n/a

#### Device or machine

n/a

#### Additional info

I cannot use the daemon & CLI from the previous release, because they no longer find any offers.

**Comment by Nisaba** [comment]
+1
Please release quickly these files.
Thank you

**Comment by Nisaba** [comment]
Still no news here ??

**Comment by kiocos** [comment]
Hey @orangefren  @Nisaba!
While this is not an ideal solution, I have managed to build `bisq-daemon-1.9.17` and `bisq-cli-1.9.17` locally.
I have not tested the outputted CLI and Daemon, but I believe it should work.

### Pre-requisites
- Git installed
- A terminal emulator (if you are on Windows and don't know which one to use, go for Git Bash)
- OpenJDK 15 (or at least 11): you can check the version by running `java -version` on your terminal. Expected output:
```
openjdk version "15" 2020-09-15
OpenJDK Runtime Environment (build 15+36-1562)
OpenJDK 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)
```
If you don't get the above output, you have to install OpenJDK 15 (or 11) and then add it to your PATH variable. Check tutorials for your OS online if needed. Proceed once you can get the above output from running `java -version`.

### Steps (tested on Linux, but should work fine on any OS):
1. Clone the Bisq repository: `git clone https://github.com/bisq-network/bisq.git`
2. CD into it `cd bisq/`
3. Checkout to the appropriate version: `git checkout release/v1.9.17`
4. Build the project with `./gradlew build`
5. Generate `bisq-daemon-1.9.17` by running `(cd daemon/package && ./create-daemon-dist.sh 1.9.17)`
6. Generate `bisq-cli-1.9.17` by running `(cd cli/package && ./create-cli-dist.sh 1.9.17)`
7. You should now have two zip files generated: one inside `daemon/package/` and another inside `cli/package/` folder
8. Just copy and extract them wherever you like and you will get your .jar file

I have reached out the Bisq maintainers on Matrix, hopefully they will be able to provide a more definitive solution soon.
Let me know if the above works for you guys!

**Comment by Nisaba** [comment]
Hi @kiocosta 
Thank you for your feedback and for this fix, until the definitive solution, hoping soon...

**Comment by Nisaba** [comment]
Hi,

I'm not a java developper and unfortunately I can't build these package.
Waiting feedback from Bisq maintainers quickly

**Comment by kiocos** [comment]
Hi, @Nisaba!
If it's really urgent and you wish to use it, I have uploaded the built files in my Drive. You can get them [here](https://drive.google.com/drive/folders/16xFGgko-kYPFjWVAoWA5Q13bggk3rl3l?usp=sharing).
I have signed them with my GPG key, which you can get at [caiocosta.xyz](https://caiocosta.xyz/).
I recommend that you verify the signature if you intend to use it. Let me know if you need additional help.

ps: I don't intend to break any community rules, just to help. I apologize if sharing files like this is considered bad etiquette.

**Comment by Nisaba** [comment]
Hey !
Thank you very much for your fix.

It works, I get 1.9.17 with getversion command.

Unfortunately (this probably doesn't directly concern you), but getoffers command still displays to me "no SELL USD offers found" like 1.9.16.

So I guess there is an issue also on 1.9.17 daemon that wasn't fixed, that's why it has not been posted in the release...

Hoping Bisq maintainers will have a look at this issue very soon...
