### ISSUE TITLE
Error when trying to make a BSQ transaction (blind vote)

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq#7241]
I got that error when doing the blind vote tx.
![Screenshot 2024-09-12 at 18 24 54](https://github.com/user-attachments/assets/0ce39f35-adc7-4980-9805-fad60c790857)

After resetting master to https://github.com/bisq-network/bisq/commit/5d8641031aa9c3d5ad2c7506972916a7c716ae20 it worked again. So seems the recent wallet related changes have caused it.

@stejbac Could you have a look?

**Comment by stejbac** [comment]
OK, I'll look into it now.
