### ISSUE TITLE
 Allow Account Names to be edited without losing reputation and buyer limits

### ISSUE THREAD

**Issue by daum3ns** [bisq-network/bisq#7260]
Can we please re-open this issue? If you get married and you change your name you will lose the reputation and buy limits.... It's bad because the bisq UI tells the seller to open a dispute when the name does not match, although its impossible to change it in bisq...

_Originally posted by @daum3ns in https://github.com/bisq-network/bisq/issues/2101#issuecomment-2378719999_

**Comment by suddenwhipvapor** [comment]
This is not possible, on principle.
The name tied to the fiat account is what identifies the account signing status. If you could change that, it would open the gates to all sorts of scammers.
So yes, it is unfortunate, but by the trading rules, you will need to sign the account once again.

**Comment by daum3ns** [comment]
yes you are right, however, it is possible to export account age witness and then re-import in the newly created account. 
like this you get the new account with the new name and the trading limits of the old account:
https://bisq.community/t/edit-account-info/6748/5

closing issue
