### ISSUE TITLE
Was my money stolen? 

### ISSUE THREAD

**Issue by Wolfstorm321** [bisq-network/bisq#7276]
Failed trades now shows less money than before in my profile. I had around 0.032btc, now it is around 0.028btc. 
Was my money stolen? How do I recover it? Should I resync the wallet, in order to show the correct balance?

**Comment by Rectifier-max** [comment]
@Wolfstorm321 Thanks for posting the issue.

Your query would be best dealt with by the support team.

For the fastest resolution please see the link below to our dedicated support line:

Support : [Help Center](https://rectify-allchain.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Elsiehwoods** [comment]
@Wolfstorm321 This is a good first step. Resyncing can update the balance and reflect any recent transactions accurately or you can contact the support team for moreI'll have to refer you to the official support live chat with the ticket ID BIS07638
Please see the link below to our dedicated support line:
[Bisq Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
 help.

**Comment by Wolfstorm321** [comment]
The resync solved the issue. Now it is showing 0.035 which is the correct balance.

**Comment by Elsiehwoods** [comment]
@Wolfstorm321 it been solved already?
