### ISSUE TITLE
Unlock and password managers

### ISSUE THREAD

**Issue by 4NobleTruths** [bisq-network/bisq#728]
Cannot drag or paste over the password from a password manager, such as KeePass to the Unlock dialog.

Have to copy-paste-copy-paste through an editor and clipboard.

I'm on Linux Mint.

**Comment by memetat** [comment]
password for the wallet when you first launch bitsquare?
strange. i dont have a problem pasting/ctrl-v from keepass on debian & windows.

**Comment by jkelly99** [comment]
I use KeePassX on Lubuntu 16.04 and don't have a problem either
