### ISSUE TITLE
Support for atomic cross-chain swaps

### ISSUE THREAD

**Issue by mmazi** [bisq-network/bisq#729]
Is any support for [atomic swaps](https://en.bitcoin.it/wiki/Atomic_cross-chain_trading) planned? What is the BitSquare team's stance on this?

**Comment by t4777sd** [comment]
It would definitely help bring more buyers / sellers to the network as it would speed up transaction times between alts.

**Comment by ManfredKarrer** [comment]
Atomic swaps are cool but to implement them in a decentralized manner it takes a lot of engineering effort and resources (full node for each altcoin). So we are not planning to work on that but we will work on automatic altcoin trades, where the lookup in the altcoin blockexplorer is done by the app.

**Comment by jonathancross** [comment]
Side note: The Lightning Network will also [allow atomic cross-chain trading](https://bitcoinmagazine.com/articles/atomic-swaps-how-the-lightning-network-extends-to-altcoins-1484157052/).  Might be good to start thinking about how BitSquare might take advantage of LN.

**Comment by ManfredKarrer** [comment]
I close here. Feel free to continue the discussion on the Forum (I try to keep Guthub dev centric).

**Comment by fresheneesz** [comment]
@manfredkarrer Why did u close this? This is the most important upgrade for bisq. This should be top priority now that the LN has dropped. The pain of having to deal with escrow and mediation fees can all go away (except for when using fiat). Please reopen

**Comment by tomatopeel** [comment]
@fresheneesz See https://github.com/bisq-network/proposals/issues/3 - as far as I can see, the dev's are going to be working with this technology, but it's really not an overnight thing like "oh I read some article that said LN 'dropped' so now LN and atomic swaps everywhere wow".

Presumably there will be some proposals and some discussion on exactly what should be developed, and then code will be written, tested, and so on and so forth. As indicated, this isn't a simple GitHub issue right now, though as linked there is an issue in the proposals repo pertaining to this area of development.

**Comment by fresheneesz** [comment]
@tomatopeel Thanks for the link, but its not proposing atomic swaps.

> it's really not an overnight thing

Of course not. Github issues aren't only for overnight things tho..

**Comment by ManfredKarrer** [comment]
@tomatopeel @fresheneesz I closed because I wanted to keep GH issues focused on stuff we are working on in the foreseeable future. Feel free to write a proposal for atomic swap. As mentioned above I like also the concept but spent already 3 years ago considerable time to find out it is not feasible in the context of Bisq. Would love to see my opinion proven wrong, though!

**Comment by fresheneesz** [comment]
> it is not feasible in the context of Bisq

Do you have a link to the relevant discussion there? I'm curious what barriers were found.
