### ISSUE TITLE
An error occurred when placing the offer:  (but placed anyway)

### ISSUE THREAD

**Issue by ratacat** [bisq-network/bisq#732]
Received this error when placing an offer to sell bitcoins. But the offer apparently got placed anyway.  Running OSX 10.9.5
[bitsquarelog.txt](https://github.com/bitsquare/bitsquare/files/735882/bitsquarelog.txt)

An error occurred when placing the offer:

A timeout occurred at publishing the offer.

No funds have left your wallet yet.
Please try to restart you application and check your network connection to see if you can resolve the issue.

**Comment by ManfredKarrer** [comment]
Thanks for reporting. I answered at #733.
