### ISSUE TITLE
Maybe broken balance check when creating offers / accepting offers

### ISSUE THREAD

**Issue by ratacat** [bisq-network/bisq#733]
I opened a new bitsquare account. Funded it with 1 bitcoin. Created two offers to sell .25 bitcoin a piece.  Funded them from bitsquare account.  Bitsquare reads that I have .52 btc reserved in offers.

Then I go to accept someone else's existing offer for .7 bitcoin, and it goes through it with it just fine.  Even though I should have only like .48 available?  Is that seem right?
![screen shot 2017-01-27 at 10 45 48 am](https://cloud.githubusercontent.com/assets/3517397/22381289/35798224-e47e-11e6-8858-0b65c7573477.png)
You can see photo above of balances.  Including Log.
[bitsquarelog.txt](https://github.com/bitsquare/bitsquare/files/735913/bitsquarelog.txt)

*edit* Okay, something definitely is wonky now. So I went ahead and deleted one of the two .25 offers, because I didn't want someone to take something that maybe was broken. And it shows up as re-deposited in my bitsquare funds, and now my btc reserved in offers shows 0.  But when I look at the offers page, the other offer still shows up.

Also this would be a good time to note, that both of those .25 offers were created in a wonky possibly buggy way that I submitted on #732 

Photo
![screen shot 2017-01-27 at 10 52 47 am](https://cloud.githubusercontent.com/assets/3517397/22381524/310fa7f8-e47f-11e6-83e0-0cab6b45684f.png)

new log
[bitsquare.log.txt](https://github.com/bitsquare/bitsquare/files/735933/bitsquare.log.txt)

**Comment by MarcSte** [comment]
This is probably a UI bug due to the interrupted create offer process.

I just checked the client and cannot see your offer. Your funds are still in your wallet (minus the funds needed for the offer you took sucessfully).

You can use ctrl/cmd+E to access an emergency wallet tool that will correctly display you funds. You can withdraw them as well (better don't right now).

I'd check now as described above, then finish the open trade. Afterwards I'd withdraw the funds to clear the UI. Not sure if that works, though. Maybe you better wait for a dev to reply. You can still check the balance. You can restart the client to find out if this mabe corrects the balance.

**Comment by ManfredKarrer** [comment]
Yes that is related to the bug at the create offer. Seems a race condition with the timeout hit us.
I would recommend u to close all offers and if you have a trade open to wait until it is finished. Then withdraw all with the emergency wallet tool (open with: cmd+e or ctrl+e). In that wallet tool the correct balance should be displayed. After that, remove the data directory and start over again with a new fresh data dir and wallet. Sorry for the inconvenience, I need to make the timeout a bit longer and check why it causes that bug.

**Comment by ratacat** [comment]
Just wanted to say, I really appreciate what y'all are doing. Thankyou

**Comment by ManfredKarrer** [comment]
@ratacat Thanks!!!

**Comment by Piste** [comment]
I tried to look for timeout in the code but there are many such variables. Hence I wasn't able to find out whether the timeout referred to here was indeed increased later on.
If offer timeout was increased, did this remove the race condition?
If offer timeout was not increased, does this case still need to be addressed?

**Comment by ManfredKarrer** [comment]
The bug with the timeout is fixed in the new version. Was not the timeout but bug with the wallet data structure causing failures.
