### ISSUE TITLE
Stuck on take offer screen, Timed out and lost fee

### ISSUE THREAD

**Issue by madtestx** [bisq-network/bisq#745]
Error message:
An error occurred when taking the offer.

A timeout occurred.

The trading fee is already paid. In the worst case you have lost that fee. We are sorry about that but keep in mind it is a very small amount.
Please try to restart you application and check your network connection to see if you can resolve the issue.Please try to restart you application and check your network connection to see if you can resolve the issue.

**Comment by ManfredKarrer** [comment]
Do you remember which offer (id, price, currency) it was?

**Comment by madtestx** [comment]
Haven't got id to hand, currency was GBP buying btc, offer was 0.9btc UK bank transfer

**Comment by k0k0b34n** [comment]
This same error occurred for me. Any way to get my bitcoin back? Transaction details below.
Thanks for all the work you guys are doing on Bitsquare, keep it up!
![image](https://cloud.githubusercontent.com/assets/25877435/23100676/cc6e75f8-f63b-11e6-8336-c4e426b80568.png)

**Comment by MarcSte** [comment]
@k0k0b34n 

You should have only lost the take offer fee (0.0015 BTC)

Please check that in the funds tab. If you're missing the security deposit as well, you can access an emergency wallet tool with cmd+o/ctrl+o. This should display the correct amount an enable you to send them out.

If you wish to get the taker fee back, you can post an address here and I'll reimburse you.

**Comment by k0k0b34n** [comment]
@MarcSte 

I actually only lost the trading fee (0.001 BTC).

I've decided to go ahead and let you guys keep it as a donation if possible.

Thanks for the reply.

**Comment by MarcSte** [comment]
@k0k0b34n 

Thanks!

So you're using an older version. I recommend updating to v0.4.9.9 https://bitsquare.io/downloads/
The latest version is not backwards compatible due to changes in the fee structure. We had to do this to account for rising tx fees. There will be a big new release around the end of march, introducing dynamic tx fees. That should be a permanent solution.

**Comment by k0k0b34n** [comment]
@MarcSte 

I actually do have v0.4.9.9. It took the 0.001 Trading Fee, but not the 0.0005 Mining Fee or 0.03 Security Deposit that were also required for the trade.

**Comment by madtestx** [comment]
Take offer fee 19c1e05a , 3 transactions 0.001btc sent

**Comment by MarcSte** [comment]
Hey @madtestx,

sorry for the late reply. Post an address and I'll reimburse you.
