### ISSUE TITLE
add build dep for ubuntu 16.04

### ISSUE THREAD

**Issue by themighty1** [bisq-network/bisq#749]
> To install OpenJDK use:
> $ sudo apt-get install openjdk-8-jdk maven libopenjfx-java

also must be added openjfx as a dependencied, otherwise bitcoinj compilation fails

**Comment by Piste** [comment]
This seems to be in relation to [build instructions](https://github.com/bitsquare/bitsquare/blob/master/doc/build.md).
The doc indicates "In Debian/Ubuntu systems with OpenJDK you'll need OpenJFX as well, i.e. you'll need the openjfx package besides the openjdk-8-jdk package." hence I think this resolves the problem.
@themighty1 would you be able to close this issue?
