### ISSUE TITLE
building: how do you point bitsquare to bitcoinj

### ISSUE THREAD

**Issue by themighty1** [bisq-network/bisq#750]
Ive built bitcoinj in a separate dir acc.to the build.md instructions
But nowhere in the instructions does it say hot to point bitsquare to the newly built bitcoinj,
hence when building bitsquare, it fails with Failure to find org.bitcoinj:bitcoinj-core:jar:0.13.1.7

**Comment by mrosseel** [comment]
Hi, did you execute the following two lines:
$ cd bitcoinj
$ mvn clean install -DskipTests -Dmaven.javadoc.skip=true

If you did, bitcoinj should have been installed in your local maven repository (~/.m2/repository), and bitsquare should be able to use bitcoinj you built.

**Comment by ManfredKarrer** [comment]
It might be that your branch is using v0.13.1.7 of bitcoinj but the actual bitcoinj uses v0.13.1.8. If that is the case just either checkout the older version of bitcoinj and install that or update your branch with the latest from the Development branch.

**Comment by themighty1** [comment]
I was simply following https://github.com/bitsquare/bitsquare/blob/master/doc/build.md
It says git clone -b FixBloomFilters https://github.com/bitsquare/bitcoinj.git
and so i did just that.

**Comment by ManfredKarrer** [comment]
$ cd ..
$ git clone -b FixBloomFilters https://github.com/bitsquare/bitcoinj.git
$ cd bitcoinj
$ mvn clean install -DskipTests -Dmaven.javadoc.skip=true

**Comment by themighty1** [comment]
Sorry, I wasnt being verbose but that's ---^ exactly what I did.
In other words, I followed the build.md file to a "t" (im on Linux)
branch FixBloomFilters in on top 0.13.1.8, but bitsquare expects 0.13.1.7
you'll have to reconcile those versions in build.md

I just want to get this across - that I wasnt doing my own branches of either bitcoinj or bitsquare, I was simply follwoing build.md and there is a bug in the description which has to be fixed.

**Comment by ManfredKarrer** [comment]
Ah sorry, master and Dev branch sometimes are not in sync with the BitcoinJ head. Will change in master as well to the latest btcj version.
