### ISSUE TITLE
Insufficient money, missing X satoshis

### ISSUE THREAD

**Issue by raitonbolt** [bisq-network/bisq#753]
Hello! I have been trying to sell 0.3 bitcoin which is within the range of the buyer, but for some reason I keep getting an insufficient money error.

**Comment by MarcSte** [comment]
Hello,

posting this in the [Bitsquare forum](https://forum.bitsquare.io/) is a better way to get help.

Please repost it over there with a little more information and close here.

In general, to accept an offer to buy 0.3 BTC you'll need to have 0.3112 BTC in your local Bitsquare wallet. 
0.3 obvious
0.01 security deposit
0.001 taker fee
0.0002 mining fee

**Comment by Piste** [comment]
@raitonbolt were you able to get help on the forums? Can we close this issue?

**Comment by ManfredKarrer** [comment]
That bug is fixed in the new version
