### ISSUE TITLE
Warnings "Seed timed out" and Exceptions "tor host is unreachable"

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#757]
Bitsquare 0.4.9.9 on Debian 8("Jessie") x86_64

"Use Tor for Bitcoin network" is enabled.

No custom Bitcoin node is configured.

The host where Bitsquare is runnin on, has outgoing firewall restrictions.
Only the following is allowed outgoing:

TCP ports 80,443,6667,9001,9030
9050 (Tor socks5-Proxy on another host in LAN, used as proxy in Bitcoin Core)

UDP port 53 (DNS)

ICMP

I do not get no Bitcoin network peer connection. ("Bitcoin network peers: 0"), but the following log message in bitsquare.log. With 0.4.9.8 I got Bitcoin network peer connection. 

```
Feb-12 09:00:57.654 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed seed.bitcoin.sipa.be: timed out 
Feb-12 09:00:57.654 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed dnsseed.bitcoin.dashjr.org: timed out 
Feb-12 09:00:57.654 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed seed.bitcoinstats.com: timed out 
Feb-12 09:00:57.654 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed bitseed.xf2.org: timed out 
Feb-12 09:00:57.654 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed seed.bitcoin.jonasschnelli.ch: timed out 
Feb-12 09:00:57.655 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed seed.bitnodes.io: timed out 
Feb-12 09:01:09.258 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed seed.bitcoin.sipa.be: timed out 
Feb-12 09:01:09.258 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed dnsseed.bitcoin.dashjr.org: timed out 
Feb-12 09:01:09.258 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed seed.bitcoinstats.com: timed out 
Feb-12 09:01:09.258 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed bitseed.xf2.org: timed out 
Feb-12 09:01:09.259 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed seed.bitcoin.jonasschnelli.ch: timed out 
Feb-12 09:01:09.259 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed seed.bitnodes.io: timed out 
Feb-12 09:01:20.852 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed seed.bitcoin.sipa.be: timed out 
Feb-12 09:01:20.852 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed dnsseed.bitcoin.dashjr.org: timed out 
Feb-12 09:01:20.852 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed seed.bitcoinstats.com: timed out 
Feb-12 09:01:20.853 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed bitseed.xf2.org: timed out 
Feb-12 09:01:20.853 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed seed.bitcoin.jonasschnelli.ch: timed out 
Feb-12 09:01:20.853 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed seed.bitnodes.io: timed out
[...]
Feb-12 09:01:28.043 [DNS seed lookups] WARN  i.b.n.DnsLookupTor: Error resolving dnsseed.bitcoin.dashjr.org. Exception:
io.bitsquare.network.DnsLookupException: tor host is unreachable 
Feb-12 09:01:28.852 [DNS seed lookups] WARN  i.b.n.DnsLookupTor: Error resolving seed.bitnodes.io. Exception:
io.bitsquare.network.DnsLookupException: tor host is unreachable 
Feb-12 09:01:28.853 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery: Seed dnsseed.bitcoin.dashjr.org: failed to look
 up: org.bitcoinj.net.discovery.PeerDiscoveryException: io.bitsquare.network.DnsLookupException: io.bitsquare.network.DnsLo
okupException: tor host is unreachable
```

**Comment by ghost** [comment]
When starting Bitsquare with command line parameter

`--socks5DiscoverMode ONION`

the warnings and exceptions mentioned above are gone, startup log is clean.

**Comment by dan-da** [comment]
strange, by default if DNS discovery fails, it should anyway try connecting to ipv4 seeds and .onion seeds.

**Comment by dan-da** [comment]
In general those warnings are safe to ignore.  Except of course if you cannot get connected at all, that is a problem.

The dns discovery mechanism uses a tor extension to socks5 that enables dns lookups over tor.  But it has some pretty big limitations, such as only a single address can be returned at a time, and even that fails if dns server returns more than approx 25 results.

If you have tor installed, it includes a program called tor-resolve that uses the same mechanism.  Generally tor-resolve should give the same results as bitsquare for a given dns lookup.   So you could try for example:

$ tor-resolve seed.bitcoin.sipa.be
188.26.95.240

One difference is that bitsquare (bitcoinj) presently has a 5 second hard-coded timeout for dns requests.  So if the tor roundtrip takes longer than that, you will see the timeout message.

I'm not sure yet that there is a bug here.

**Comment by ghost** [comment]
Thanks for checking. With 0.4.9.8 this problem did not exist.
Tor is running on another Host in LAN, so on Bitsquare/Bitcoin Core  host I do not have tor-resolve.
I added ICMP and TCP 9050 to my OP, these were missing.
