### ISSUE TITLE
"Buy BTC" offers are not sorted correctly after some time

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#762]
Bitsquare 0.4.9.9 on Debian 8("Jessie") x86_64

After some time, the "Buy BTC" offers are not sorted correctly anymore. Maybe there is missing an auto-refresh, because klicking on other tabs like "Settings" and then go back to "Buy BTC" offers list, seems to fix the sorting issue.

![matrica](https://cloud.githubusercontent.com/assets/8447873/23102681/2001def4-f6ae-11e6-9976-bb2c5e3e1e86.png)

**Comment by ManfredKarrer** [comment]
Yes thats a known issue. Hoped some dev take that as low hanging fruit, but did not happen so far and I did not had time...

**Comment by Piste** [comment]
Should we attach a milestone to this bug, to make sure it gets addressed?
