### ISSUE TITLE
UI bug - funds disappear from UI but are accessible with emergency wallet tool

### ISSUE THREAD

**Issue by MarcSte** [bisq-network/bisq#763]
This appears to be happening from time to time.

Here's a reddit thread to show the behaviour with screenshots: https://www.reddit.com/r/Bitcoin/comments/5wrdnq/lost_btc_after_transferring_to_bitsquare/

I've came across these multiple times. Funds have always been recoverable with the emergency wallet tool. No funds were ever lost which makes me believe it's just a UI bug.

**Comment by ManfredKarrer** [comment]
Yes there are some issues when the internal wallet data structure gets out of sync because of some bugs. Will try to fix that for the next version.

**Comment by Piste** [comment]
Was this UI bug addressed?

**Comment by ManfredKarrer** [comment]
Yes that is fixed in the new version.
