### ISSUE TITLE
Packages for Fedora (.rpm) or distro-agnostic builds with Flatpak

### ISSUE THREAD

**Issue by heyakyra** [bisq-network/bisq#767]
This is a request!

**Comment by ManfredKarrer** [comment]
Please provide a build script then I add it.

**Comment by dretec** [comment]
Plus one for this request.... Would provide a build script if I knew how..

**Comment by ghost** [comment]
I'm already able to build RPM with a pure Java based tool without Flatpak, I tested my RPMs on Mageia Linux 5:
http://tuer.sourceforge.net/en/documentation/#jndt

If you're able to provide a single "fat" JAR, it will work. JNDT is based on Ant and can be called in Gradle.

**Comment by ManfredKarrer** [comment]
I would prefer to stick with the official Oracle packager both for practical reasons to not make the build process too complicate and for security reasons. Do you have a script how to build rpm with the default packager. It should basically work, I just did not had time to check it out in details and don't have a Fedora based system set up.

**Comment by hegjon** [comment]
There are more work involved than to install a fat JAR. I have started on including the dependency openjfx into Fedora https://apps.fedoraproject.org/packages/openjfx

**Comment by aiguofer** [comment]
interested in this as well! is there any development? been trying to build from source and keep running into problems too

**Comment by ManfredKarrer** [comment]
If you follow exactly the instructions in /doc/build.md all should work.

**Comment by hegjon** [comment]
The included OpenJDK with openjfx package can be installed by installing java-1.8.0-openjdk-openjfx and java-1.8.0-openjdk-openjfx-devel. The rest is as described in build.md
