### ISSUE TITLE
Mobile builds for Android and iOS

### ISSUE THREAD

**Issue by heyakyra** [bisq-network/bisq#769]
In this day and age, it seems like shooting yourself in the foot to not have native apps for mobile. There is plenty of reading on [mobile first](https://www.google.com/search?q=mobile+first) design, why it's so important strategically, and how to do it well.

**Comment by ManfredKarrer** [comment]
If you can make a pure P2P app mobile, please let me know how to do it. Such discussions are better on the forum. Github is more for development centric things.

**Comment by ghost** [comment]
@thekyriarchy Using an highly polluting search engine relying on a centralized computer system to advise something for a software used to perform decentralized exchange is quite inconsistent.
