### ISSUE TITLE
Ability to see how many trades was done each person

### ISSUE THREAD

**Issue by githubaccq** [bisq-network/bisq#770]
It would be great to see against each offer how many trades were done for a creator of offer. It can prevent from scammers as it is done on localbitcoins.. Here scammers can go to a bank and say their account was 'hacked'. Seller of bitcoins gets frozen account always after this scam and no money often.

**Comment by ManfredKarrer** [comment]
The problem in a decentralized model that we don't have that data. Reputation is not easy in a real P2P system. You can see in your own trades the number of trades u have done with a peer, so it kind of creates a personal reputation system between you and the peer u have been trades. 
Please follow up the discussion on the forum. Github is mainly for development issues. I will close her but feel free to continue at the forum.
