### ISSUE TITLE
Seller managed to take offers at ~25% above what the price should have been

### ISSUE THREAD

**Issue by stiell** [bisq-network/bisq#780]
I currently have an open trade where the seller apparently managed to take my offer at 25% more than the price I had specified. This was one of two NOK trades opened on 2017-03-18 15:06 and 15:07 UTC where the offerer was the buyer and the price was excessively high.

The price was specified to be 5% below market price in NOK. Seller opened the trade with a price of 10212 NOK/BTC when the price at e.g. Bitfinex was no more than 1007 USD/BTC (~8590 NOK) during that period. In other words, the price of the trade is 25% more than what it should have been.

Either the price retrieved from BitcoinAverage was bad at the time or Bitsquare somehow failed to verify the trade price.

I don't know where BitcoinAverage gets its BTC prices in various currencies, but if it's getting them from small, illiquid or otherwise unreliable exchanges then some more reliable way of determining prices should be considered.

Bitsquare version: v0.4.9.9

**Comment by ManfredKarrer** [comment]
There was a bug in the price provider node causing missing updates. It is fixed already and in the next version there will be extra checks on both provider and client side to prevent outdated prices to be used. 
I got reported it from a Norwegian trader, it might be the peer in your trade.
If you suffered losses from that incident please PM me on the forum or send me an email (see my personal email on the contact page at the Bitsquare webpage).
