### ISSUE TITLE
Dockerfile for simple building on every linux (or for running in containers)

### ISSUE THREAD

**Issue by foxcool** [bisq-network/bisq#781]

**Comment by tr37ion** [comment]
Alternatively, you might consider installing it within a systemd-nspawn container. Easier to setup and lightwight eg. https://wiki.archlinux.org/index.php/Firefox/Tweaks#Run_Firefox_inside_an_nspawn_container

**Comment by Piste** [comment]
Have you checked this out: https://hub.docker.com/r/sgeisler/bitsquare-build/ ?
