### ISSUE TITLE
An error occurred at task: SignAndFinalizePayoutTx

### ISSUE THREAD

**Issue by dretec** [bisq-network/bisq#785]
Exception: java.lang.NullPointerException
Running on Windows 7 32 Bit. Bisq version 0.4.9.9.1
Looks like seller has confirmed getting the FIAT as locked funds tab transaction detail, and finally Trade  states: FIAT_RECEIVED,.
When I try to log a support ticket for trade  I get "select deposit transaction for dispute" window, but all three deposits to chose from produce another window with error
"acceptedArbitratorByAddress must be tbe null"

So hoping someone can help, as I am not sure how to get the transaction to complete as to release btc funds to my bisq wallet. Once we can get an RPM of bisq I can ditch my windows VM once and for all.

**Comment by ManfredKarrer** [comment]
Can you restart and try again? Seems you have not received the arbitrator data.
If it still fails I fear I need to debug with your data directory. Ping me by email in that case and I will instruct you further. Email you find on the webpage (manfred...)

**Comment by dretec** [comment]
Hi Manfred, 

Thanks for getting back to me, sure thing let me know how to retrieve
logs for you. 

*UPDATE* the support case has now logged after a graceful restart. 

No response from arbitrator yet. (4 hours since logged)+ ---

On 2017-03-30 08:56, Manfred Karrer wrote:

> Can you restart and try again? Seems you have not received the arbitrator data.
> If it still fails I fear I need to debug with your data directory. Ping me by email in that case and I will instruct you further. Email you find on the webpage (manfred...) 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/bitsquare/bitsquare/issues/785#issuecomment-290206605
[2]

**Comment by ManfredKarrer** [comment]
The log file is in the Data directory:
If you want to open the data directory manually can find it under those locations:
Mac OSX: /Users/username/Library/Application Support/Bitsquare
Linux: /home/username/.local/share/Bitsquare
Windows 7,8: C:\Documents and Settings\username\AppData\Roaming\Bitsquare
Windows XP: C:\Documents and Settings\username\Application Data\Bitsquare

**Comment by dretec** [comment]
Cheers Manfred,

I see lots of this:

Feb-22 05:05:26.437 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
Feb-22 05:05:26.437 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableMessage= Java heap space 
Feb-22 05:05:26.438 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableClass= class java.lang.OutOfMemoryError 
Feb-22 05:05:26.438 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Stack trace:
java.lang.OutOfMemoryError: Java heap space
[bitsquare.log.txt](https://github.com/bitsquare/bitsquare/files/881319/bitsquare.log.txt)


I am running on windows 32bit, which might be the issue with out PAE on. As soon as we can clear this and the transaction completes at my end, I am going to spin up a 64bit Debian/Ununtu VM to run bisq from now on and decommission the windows app/OS.. until some smart fellow gets time to put together an RPM as to run it on Fedora.

**Comment by dretec** [comment]
Did you get a chance to review my bitsquare log? has this Java issue prevented my wallet from accepting my order? The support case closed with no response and at this stage I am out of pocket. :( PS thanks for putting your passion into this, its going to be needed more than ever when the swarm comes.

**Comment by ManfredKarrer** [comment]
I saw OutOfMemoryError exceptions. So that might have caused it. Do u run on a VM? which OS? how much RAM? I OutOfMemoryError exc. only on linux with the seed nodes but never with the GUI app.

Update:
Just saw that you restarted after that. So that should not be the reason.
Before the OutOfMemoryError exc there have been a lot of repeated connection losses and reconnects. That might have been a reason for the OutOfMemoryError.

**Comment by ManfredKarrer** [comment]
"The support case closed with no response" - do you mean a dispute/support ticket? If so can you send me the trade ID?

**Comment by dretec** [comment]
Trade ID sent, Details of VM: windows 7 sp1 32bit - 4GB ram - 3GB usable. have not enabled PAE. No need as It is (was) nothing but a remote desktop client (and bitsquare experiment).  Looking forward to moving bitsquare client to Linux- hopefully bitsquare client backups are cross platform.. :P Chatting with Manfred directly will update this thread once we have a resolution.

**Comment by ManfredKarrer** [comment]
Yes backups work cross platform. just move the whole app data dir. but take care to not mess up with out of syn copies (e.g. making a tx/activity on one and the continue on another with slightly older version)...

**Comment by ManfredKarrer** [comment]
Should be fixed with version 0.5
