### ISSUE TITLE
Relax 50-character wallet password limit

### ISSUE THREAD

**Issue by tr37ion** [bisq-network/bisq#786]
Having longer passwords would be nice. Maybe even 4096 chars, just to be free to enter whatever you want and also set min length to 24 chars eg. Enabling longer wallet passwords prevents users from entering **too short/easy** passwords, too

You might look into *vtpassword* library from http://mvnrepository.com/artifact/edu.vt.middleware/vt-password to verify and show password strength while the user enters a password.
There is a little talk about it at https://stackoverflow.com/questions/3200292/password-strength-checking-library

**Comment by meeDamian** [comment]
I just encountered this, I think related, error after trying to input a 50 char-long password:

<img width="933" alt="macos 2017-05-07 at 22 29 30" src="https://cloud.githubusercontent.com/assets/526657/25782406/d336deae-3374-11e7-9f0e-97e8a7936eee.png">

What is the reason behind such limitation?

**Comment by ManfredKarrer** [comment]
I will have a look. Think there was not hard reason, just that a random pw (using mixed chars) with length of about 30 is sufficiently safe, so to use pw with 100s of chars is pointless IMO.

**Comment by tr37ion** [comment]
Well, I would say limiting password length is not a good idea in general. Password lengths of 160+ chars is currently considered "secure". There are two good articles about that subject.

- https://techbeacon.com/how-developers-can-build-in-better-password-security
- https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet

IMHO leave it up to the users' decision which password length they would like to use.

**Comment by ManfredKarrer** [comment]
If you use mixed chars (alphanumeric + special chars) you should get with a length of > 20 chars a sufficiently high strength (> 128 bit)
https://en.wikipedia.org/wiki/Password_strength
I will release the limit but I think you should be aware that a super long pw does not provide really more security. The weak link will be where you store the pw (I dont assume u dont remember a 160 char pw) and your general operational security (OS,...).

**Comment by tr37ion** [comment]
@ManfredKarrer No worries, I know where you are coming from. Releasing the password length alone is no guarantee for general security as you already mentioned. It just gives users more options using their passwords as they are used to. Some may use password managers, QR Codes or just print them out. 

Anyways, It is great to hear that you will implement it. Big thanks for all your work :1st_place_medal:

**Comment by cbeams** [comment]
Update: we will relax or remove this restriction in the next version.

**Comment by cbeams** [comment]
@ManfredKarrer, I believe this restriction has been lifted for the forthcoming 0.6.0, correct? I just looked briefly, and couldn't find the relevant commit.

**Comment by ManfredKarrer** [comment]
Yes that's lifted for next release 0.6.
