### ISSUE TITLE
Connecting to mainnet (tor) Failed

### ISSUE THREAD

**Issue by RegleroC** [bisq-network/bisq#791]
At the beginning, It won't pass from the first loading screen (I am in Florida, US)

**Comment by ManfredKarrer** [comment]
Can you try to restart? maybe you have internet connection issues or a firewall is blocking Tor?
You can try the Tor browser to see if that works.

**Comment by dfkai** [comment]
the Tor browser is OK and fast, but the bitsquare is still loading...

**Comment by VaughnElric** [comment]
I'm having same issue, Tor browser connects fine.

**Comment by ManfredKarrer** [comment]
On Windows there is a known issue that sometimes a tor file (I think it is the cookie) gets locked. After a OS restart that lock is removed and it works again. 
@freimair Any idea how to check the lock state and if it is locked to unlock it on Windoze?

**Comment by devinbileck** [comment]
Should be able to manually check and unlock it using ProcessExplorer (instructions [here](https://www.howtogeek.com/128680/how-to-delete-move-or-rename-locked-files-in-windows/)).

**Comment by freimair** [comment]
bump
