### ISSUE TITLE
Can't connect to Bitsquare.

### ISSUE THREAD

**Issue by martinschultzkristensen** [bisq-network/bisq#795]
Cannot open wallet because of an exception:
org.bitcoinj.store.BlockStoreException: Corrupted block store: could not find chain head: 0000000000000000019bac0549b9c3382d3953561a161e5a8a6796bdb3e110cf
File path: /Users/Marman/Library/Application Support/Bitsquare/mainnet/bitcoin/Bitsquare.spvchain

Any suggestion?
I have been connected to Bitsquare before, and have a restore code.

Thanks
Best regards
Martin

**Comment by ManfredKarrer** [comment]
Please follow the steps described here:
https://forum.bitsquare.io/t/blockstoreexception-corrupted-spvchain-file/1689
It needs a second restart after it is synced!

**Comment by martinschultzkristensen** [comment]
Thank you.
It's up and running again.
