### ISSUE TITLE
Duplicated outpoint

### ISSUE THREAD

**Issue by tom9000** [bisq-network/bisq#796]
Duplicated outpoint
[bitsquare.log.zip](https://github.com/bitsquare/bitsquare/files/908490/bitsquare.log.zip)

**Comment by ManfredKarrer** [comment]
Seems the wallet is out of sync.
Can u follow what is described here?
https://forum.bitsquare.io/t/blockstoreexception-corrupted-spvchain-file/1689
After a second restart the wallet should be up-to date again.
Maybe better to also to start over with a new data directory if you don't have open trades/offers/disputes. 
See:
https://forum.bitsquare.io/t/switching-to-a-new-data-directory/1697 
Don't forget to make a backup and withdraw the funds first.

**Comment by Piste** [comment]
@tom9000 , did Manfred's suggestions help? Can we close this issue?

**Comment by tom9000** [comment]
Hi, yes thank you, Manfred's method solved the issue.
Please close this.
