### ISSUE TITLE
running bitsquare fails with errors on FreeBSD

### ISSUE THREAD

**Issue by tkoham** [bisq-network/bisq#798]
Everything builds fine, but running the resulting .jar results in this:

https://pastebin.com/UnwkD54a

and an immediate exit

**Comment by mrosseel** [comment]
- javafx used to be not included in openjdk, this might be the problem. Can you install the sun jdk or add openfx ?
- which os?

**Comment by tkoham** [comment]
I've got openjfx8-devel installed. is there any way I can test that it's working?

output of cat $JAVA_HOME/jre/lib/javafx.properties is:

    javafx.runtime.version=8.0.82
    javafx.runtime.build=b00

I built with maven 3.3, could this maven version potentially cause issues?

I'm currently running FreeBSD, trying to make a port/package if possible

**Comment by tkoham** [comment]
![image](https://cloud.githubusercontent.com/assets/13039170/24854747/8df291a8-1dad-11e7-9339-87084fa2db46.png)

this is the accompanying error dialog GUI from openjdk

running under Oracle JDK I get:

https://pastebin.com/s9GzwHgY

and no GUI

**Comment by ManfredKarrer** [comment]
I fear that is a JavaFX incompatibility issue with FreeBSD. maybe you can look at the Java bug tracker or file a bug there?

**Comment by ManfredKarrer** [comment]
We require java version 1.8.0_121 or later. If that is not available for FreeBSD it might also cause issues but probably not the reason for the above.

**Comment by tkoham** [comment]
Java version is 1.8.0_121, so that shouldn't be the issue. That's unfortunate, as maven doesn't like to cooperate with the linux-oracle jdk port from what I can tell. I get a litany of errors and warnings at build time for both bitcoinj and bitsquare. 

I'll look into it on the javaFX end.

**Comment by ManfredKarrer** [comment]
Let us know your findings. We can add it to the build.md file.

**Comment by tkoham** [comment]
OK, sounds good. My guess at this juncture is that one of the libs is pulling something Linux specific
