### ISSUE TITLE
An error occurred when placing the offer: A timeout occurred at publishing the offer.

### ISSUE THREAD

**Issue by mboehler** [bisq-network/bisq#799]
This is the first time I've tried using Bitsquare and I got this error while trying to place an offer to sell Bitcoins:

```
An error occurred when placing the offer:

A timeout occurred at publishing the offer.

No funds have left your wallet yet.
Please try to restart you application and check your network connection to see if you can resolve the issue.

```
Here is the logfile: [bitsquare.zip](https://github.com/bitsquare/bitsquare/files/916399/bitsquare.zip)

**Comment by ManfredKarrer** [comment]
Thanks for reporting.
I see a IncompatibleClassChangeError which is very strange. Do you run from source code or the binary?
If you dont have open offers/trades/disptues maybe its best to withdraw the funds to an external wallet and then backup the data directory and start over with a new data dir.
See: https://forum.bitsquare.io/t/switching-to-a-new-data-directory/1697
for more details.

**Comment by mboehler** [comment]
Hi Manfred,

I run it from the Binary.  I am using Windows 10, 64Bit.  I believe the problem is due to bitsquare not connecting reliably to the bitcoin core node I run on a different pc on my network.  See this thread for related info: https://forum.bitsquare.io/t/bitcoins-never-show-up-in-bitsquare/1840.

After taking my node out of the custom nodes field in bitsquare and allowing it to connect to other bitcoin peers, the problem went away.

Thank you!

**Comment by cbeams** [comment]
Closing as complete. /cc #1167
