### ISSUE TITLE
Seller takes transaction fee and sequrity diposit?

### ISSUE THREAD

**Issue by martinschultzkristensen** [bisq-network/bisq#800]
Hallo there Bitsquare.
When you buy on Bitsquare there is this an offer fee and a multiSig deposit. I understand that you get this deposit back after succeed buy. If that is the case I find that I haven't received mine. I have attached the transaction.csv. I hope you can see enough from there to confirm or de-confirm my thoughts.
Best regards Martin

EDIT: I removed the link for privacy reasons...

**Comment by ManfredKarrer** [comment]
u have a payout of: 0,63
and paid in: -0,0305
so i assume the trade amount was 0.6 btc and 0.03 u got back. so all looks ok to me.
