### ISSUE TITLE
Is there any API in bitsquare ?

### ISSUE THREAD

**Issue by albabosh** [bisq-network/bisq#801]
Is there any API in bitsquare ? I want to trade at bitsquare with my own trading client.

**Comment by mrosseel** [comment]
Hi, not yet but it's being worked in branch issue544-api

**Comment by Piste** [comment]
Linking to 544: https://github.com/bitsquare/bitsquare/issues/544

**Comment by Piste** [comment]
@albabosh , May I suggest adding a +1 to #544 and closing this issue?

**Comment by mrosseel** [comment]
issue closed, duplicate of #544
