### ISSUE TITLE
BITSQUARE MAJOR TROUBLESHOOTING ISSUE 

### ISSUE THREAD

**Issue by tommyredz91** [bisq-network/bisq#802]
Hey guys, I'm writing a new troubleshooting issue over here on github, cause after having downloaded more or less one week ago Bitsquare in its Windows 64 bit version, and having restarted my notebook, in order to make some required programmed updates effective, I haven't anymore been able to connect to Bitsquare network, in order to access my profile and submit new buy/sell orders on the exchange.
I'll attach to this reporting issue the screenshot of the popping-up error I'm facing in the latest days, hoping you could help me out of this asap!!;).=)
I will be very grateful for all the help you'll be so kind to provide me!!=)
![bitsquare troubleshoot 1](https://cloud.githubusercontent.com/assets/10574675/25135642/3c173c24-2453-11e7-9218-c92fd566355c.JPG)

**Comment by ManfredKarrer** [comment]
See https://forum.bitsquare.io/t/blockstoreexception-corrupted-spvchain-file/1689 for instructions how to fix that.

**Comment by Piste** [comment]
@tommyredz91 , is this issue resolved for you now?
