### ISSUE TITLE
Transaction did not deserialize properly

### ISSUE THREAD

**Issue by aubits** [bisq-network/bisq#804]
![image](https://cloud.githubusercontent.com/assets/27845142/25264389/f61275d2-26a9-11e7-8031-c4e8697554b9.png)
Transaction in progress too.

**Comment by ManfredKarrer** [comment]
It might be that the spv file is corrupted. To fix this follow those steps:
https://forum.bitsquare.io/t/blockstoreexception-corrupted-spvchain-file/1689
If that does not help the wallet itself is corrupted. Here are instructions how to recover:
https://forum.bitsquare.io/t/restore-a-corrupted-wallet/1709
Make a backup before doing anything of the above...

**Comment by Piste** [comment]
@aubits , did the problem persist after following Manfred's instructions?

**Comment by aubits** [comment]
No. The problem resolved itself after deleting the spv file.
