### ISSUE TITLE
2 transactions been stuck for 3 days - no support from arbitrator

### ISSUE THREAD

**Issue by Adamlxno1** [bisq-network/bisq#806]
Hi,

Used Bitsquare for the first time, and not really happy about it.
3 days ago i predicted ETH would go up, so wanted to buy ETH with BTC, got the whole account setup and started 2 trades.

They would both take max 24H.
But now stuck for 3 days, no funds back in wallet, only locked in trade.

Opened 2 disputes, arbirator said he has no time now, and saturday he will assist.
Still nothing and my planned profit is also out the door since ETH did indeed go up.

Far from amused! If i'd know this upfront, would have chosen from a straight up crypto exchange.

Also getting this error.
java.lang.NullPointerException
 
ANY help would be appreciated.

      {
        "hostName": "ntjhaj27rylxwvnp.onion",
        "port": 9999
      },
      {
        "hostName": "pkfcmj42c6es6tjt.onion",
        "port": 9999
      }
    ],
    "id": "28855127-fd2d8a6f-fe06-48e3-b0fc-d1aec1580d6b-04991",
    "date": 1492441814451,
    "protocolVersion": 2,
    "useMarketBasedPrice": true,
    "fiatPrice": 0,
    "marketPriceMargin": 0.035,
    "amount": 80000000,
    "minAmount": 80000000,
    "offererNodeAddress": {
      "hostName": "xelfhg54get3oyc3.onion",
      "port": 9999
    },
    "offererPaymentAccountId": "de6949a9-84fc-457c-b20a-c238c5728420",
    "offerFeePaymentTxID": "692d177439774fc675138e7a46cffe8aeff778fb661c344d321669a9c400c8d2"
  },
  "tradeAmount": 80000000,
  "tradePrice": 219140,
  "takeOfferFeeTxID": "9ea45cafcde1ce08022c383411aa8cfb69ff2045f3b4a2c522dfcce21234f2de",
  "arbitratorNodeAddress": {
    "hostName": "pkfcmj42c6es6tjt.onion",
    "port": 9999
  },
  "isBuyerOffererAndSellerTaker": true,
  "offererAccountId": "1928440235",
  "takerAccountId": "239375211",
  "offererPaymentAccountContractData": {
    "address": "0xE9E9EC219BC5d878866639Bf927cB50e7ed29f83",
    "paymentMethodName": "BLOCK_CHAINS",
    "id": "de6949a9-84fc-457c-b20a-c238c5728420",
    "maxTradePeriod": 86400000
  },
  "takerPaymentAccountContractData": {
    "address": "0xCBf2297f7Ed2631DC4BD77995cBD8F62d69f74F0",
    "paymentMethodName": "BLOCK_CHAINS",
    "id": "bf3a9201-068f-4ba8-8458-96cfcd575a0b",
    "maxTradePeriod": 86400000
  },
  "buyerNodeAddress": {
    "hostName": "xelfhg54get3oyc3.onion",
    "port": 9999
  },
  "sellerNodeAddress": {
    "hostName": "7ptznrpxmgtdlvxt.onion",
    "port": 9999
  },
  "offererPayoutAddressString": "13CXbZjgDZKmUFBrxqHGkJXbW4r7AQtv7S",
  "takerPayoutAddressString": "177bKmu35k2sjmiYhntfnt462siGcFbXDK"
}

BuyerMultiSigPubKeyHex: 02c43d6cfe6cb74588135230dee6942951bbe6fef86989e4e05e51f9962df26b97
SellerMultiSigPubKeyHex: 036a54ebc47f6e6101128d1301e684e147edc1627c9c6d127aef2410e663e26c66
==========================================================

2nd trade

"offer": {
    "direction": "BUY",
    "currencyCode": "ETH",
    "paymentMethodName": "BLOCK_CHAINS",
    "arbitratorNodeAddresses": [
      {
        "hostName": "ntjhaj27rylxwvnp.onion",
        "port": 9999
      },
      {
        "hostName": "pkfcmj42c6es6tjt.onion",
        "port": 9999
      }
    ],
    "id": "SdrOt-607cf75c-e85e-4473-9d6d-92bf2820c353-0499",
    "date": 1491827299170,
    "protocolVersion": 2,
    "useMarketBasedPrice": true,
    "fiatPrice": 0,
    "marketPriceMargin": 0.0395,
    "amount": 100000000,
    "minAmount": 10000000,
    "offererNodeAddress": {
      "hostName": "vlyj2d2hi3jtmcf2.onion",
      "port": 9999
    },
    "offererPaymentAccountId": "f48109aa-9d69-4281-9582-2e7f5f67610c",
    "offerFeePaymentTxID": "8190bf5e5d387b253bc87a35fbf464d2faddccf5419c8bd0d89623f0cb9740ee"
  },
  "tradeAmount": 60000000,
  "tradePrice": 213925,
  "takeOfferFeeTxID": "dc0e566df03d4822f0f54f27f7e63e6e75e7e89cbf8b6e0a12d743e200435bd5",
  "arbitratorNodeAddress": {
    "hostName": "pkfcmj42c6es6tjt.onion",
    "port": 9999
  },
  "isBuyerOffererAndSellerTaker": true,
  "offererAccountId": "1121358765",
  "takerAccountId": "239375211",
  "offererPaymentAccountContractData": {
    "address": "0xe54577af61017562639bd4d9b5cb95e19af2e4c7",
    "paymentMethodName": "BLOCK_CHAINS",
    "id": "f48109aa-9d69-4281-9582-2e7f5f67610c",
    "maxTradePeriod": 86400000
  },
  "takerPaymentAccountContractData": {
    "address": "0xCBf2297f7Ed2631DC4BD77995cBD8F62d69f74F0",
    "paymentMethodName": "BLOCK_CHAINS",
    "id": "bf3a9201-068f-4ba8-8458-96cfcd575a0b",
    "maxTradePeriod": 86400000
  },
  "buyerNodeAddress": {
    "hostName": "vlyj2d2hi3jtmcf2.onion",
    "port": 9999
  },
  "sellerNodeAddress": {
    "hostName": "7ptznrpxmgtdlvxt.onion",
    "port": 9999
  },
  "offererPayoutAddressString": "1ApfbXLSE25zuEJoQj66WsjaWMbmM5u3cx",
  "takerPayoutAddressString": "1BsqBtUNVQSgK6beQsHSJ2nsSEgGdUMu3h"
}

BuyerMultiSigPubKeyHex: 0339329c4efd8d4132d5e99f2caadd46b0bd383915ff6fccaf419bd746442d778c
SellerMultiSigPubKeyHex: 02c3104699ba0202e01b94c916e8731cc8902129d506f6e16393098f26ac8f3b8f

**Comment by ManfredKarrer** [comment]
Github is not the right place for customer care issues, that is better to do at the Forum. 
One of the trades has been completed 2 days ago, but seems you did not check your ETH wallet before writing your accusations. I told you that I was traveling and other like normal cannot assist in a timely manner (usually I check 2 times a day the disputes). With the second trade the other peer was not sure what to so so he waited but he has already paid the EHT and the trade is completed as well. 
I am sorry that you had bad luck with your first trades but you should also have more respect to those who work off their asses without earning a cent to provide a trading platform which is censorship resistant and follows the same principles like Bitcoin.
