### ISSUE TITLE
Windows x64 / Doesn't even launch

### ISSUE THREAD

**Issue by Dubardo** [bisq-network/bisq#808]
Doesn't load

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff85cd4fd0c, pid=14860, tid=0x0000000000003aa4
#

From the log file i've attached
[app.zip](https://github.com/bitsquare/bitsquare/files/966774/app.zip)

Fresh Java install also.

**Comment by ManfredKarrer** [comment]
Can u send me the app log file?
You can find the log file in the data directory under those locations:
Mac OSX: /Users/username/Library/Application Support/Bitsquare
Linux: /home/username/.local/share/Bitsquare
Windows 7,8: C:\Documents and Settings\username\AppData\Roaming\Bitsquare
Windows XP: C:\Documents and Settings\username\Application Data\Bitsquare

**Comment by ManfredKarrer** [comment]
Maybe u have some permission issues?

**Comment by Dubardo** [comment]
It's an empty folder
