### ISSUE TITLE
withdrawls have too low fee for current bitcoin network situation

### ISSUE THREAD

**Issue by b3dk7** [bisq-network/bisq#810]
Would be great if the user could set the fee's. Of course a minimum fee could be hard coded to minimize issues with slow confirmation.
This feature would give users the option to withdrawl a lot faster if they are in a hurry.

**Comment by MarcSte** [comment]
The default is too low I guess, but you can increase the fee manually in 'Settings' -> 'Settings'.

That should be what you're requesting.

If you have a stuck tx you can do a [Child pays for parent](https://bitcointalk.org/index.php?topic=1118563.0) tx if your wallet allows it or use the [viabtc tx accelerator](https://www.viabtc.com/tools/txaccelerator/). They force a stupid political statement on you but it works.

**Comment by b3dk7** [comment]
i know viabtc, i had to use it too many time (roll eyes).
ok i can see the option to change the fees now. how did i overlook that... sorry for the redundant issue post
