### ISSUE TITLE
Bitsquare not working in Tails OS

### ISSUE THREAD

**Issue by 1989gironimo** [bisq-network/bisq#811]
I'm trying to run Bitsquare on Tails - I've installed the necessary dependencies and it starts but hangs at startup. I think Bitsquare starts a tor session on its own and doesn't use the preinstalled tor already running. It seems that there's no way to disable the internal tor client and just pass a parameter with proxydetails like "localhost:9150" or something like that.

**Comment by scarar** [comment]
Has this been fixed? Maybe the new version of Tails will offer a fix.

**Comment by ManfredKarrer** [comment]
Yes Bitsquare uses its own Tor binary included in the app. But that should not interfere with any external Tor app and works also if Tor Browsers is running.

**Comment by 1989gironimo** [comment]
well I didn't have the opportunity to test this right now, but I'll report back if I've done so and maybe you have to know that a software which is installed on Tails have to use the built-in tor because of firewall and permissions.

See here for example - an app which is already integrated into Tails:
https://github.com/micahflee/onionshare/blob/master/CHANGELOG.md

Quote: Looks for TOR_CONTROL_PORT environment variable, to help Tails integration

**Comment by sejktmcsdlmfhsc** [comment]
Same here: not working (fails to connect) over here on tails 3.0 , 3.1 or 3.2.
Would be really great if it would be possible to run bisq on tails!

**Comment by sejktmcsdlmfhsc** [comment]
@1989gironimo TOR_CONTROL_PORT might work for an older tails version or current alpha subgraph os, where it has that env vav - in current tails 3.2 the socks server seems to be published under the env var: 'SOCKS5_SERVER': '127.0.0.1:9050' 

dear @ManfredKarrer, first off thanks for the amazing Bisq!! 
(if only I could get it also to run on tails): in #531 you suggested to have tor browser shutdown to see if Bisq is able to connect - this unfortunately did not work on my machine, so I tried to tried to run it with and without torsocks/torify from different locations as shown below:

Tails 3.2 (based on debian 9)
Bisq installed: Bisq-64bit-0.5.3.deb
openjdk-8 java installed via: 
`sudo apt install default-jdk`
`java -version`
yields:
`openjdk version "1.8.0_151"`
`OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-1~deb9u1-b12)`
`OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)`

onion circuits shows Tor status as connected
no torbrowser running

excerpt from os.environ:
`'SOCKS5_SERVER': '127.0.0.1:9050', 'JAVA_HOME': '/usr/lib/jvm/java-8-openjdk-amd64'`

from installed /opt/Bisq and from a copy in ~/Tor Browser/Bisq I ran:
`torify ./Bisq`

resulting in hundreds of denied syscalls:

`WARNING torsocks[21145]: [syscall] Unsupported syscall number 319. Denying the call (in tsocks_syscall() at syscall.c:488)`

without torsocks/torify:
`./Bisq`

```
Successfully removed cryptography restrictions
Nov-14 00:07:59.031 [JavaFX Application Thread] INFO  i.b.g.a.BisqApp: Log files under: /home/amnesia/.local/share/Bisq/bisq 
Nov-14 00:07:59.036 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: System info: os.name=Linux; os.version=4.12.0-2-amd64; os.arch=amd64; sun.arch.data.model=64; JRE=1.8.0_131-b11 (Oracle Corporation); JVM=25.131-b11 (Java HotSpot(TM) 64-Bit Server VM) 
Nov-14 00:08:01.462 [JavaFX Application Thread] INFO  i.b.c.p.HttpClientProvider: FeeProvider with baseUrl http://5bmpx76qllutpcyp.onion/ 
Nov-14 00:08:01.483 [JavaFX Application Thread] INFO  i.b.c.p.HttpClientProvider: PriceProvider with baseUrl http://5bmpx76qllutpcyp.onion/ 
Nov-14 00:08:01.821 [JavaFX Application Thread] INFO  i.b.c.a.Version: Version{VERSION=0.5.3, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=1, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10} 
Nov-14 00:08:05.698 [checkIfLocalHostNodeIsRunningThread] INFO  i.b.g.m.MainViewModel: Localhost peer not detected. 
Nov-14 00:08:05.700 [JavaFX Application Thread] INFO  i.b.g.m.MainViewModel: startBasicServices 
Nov-14 00:08:05.705 [JavaFX Application Thread] INFO  i.b.g.m.MainViewModel: initP2PNetwork 
Nov-14 00:08:05.810 [JavaFX Application Thread] INFO  i.b.g.m.MainViewModel: 
checkCryptoSetupResult=false
loadEntryMapResult=false
walletInitialized=false
p2pNetWorkReady=false 
INFO: uname -m call results in:x86_64
Nov-14 00:08:06.161 [loadEntryMapThread] INFO  i.b.n.p.s.PersistedEntryMap: PersistedEntryMap.fromProto size: 4382 
Nov-14 00:08:07.883 [JavaFX Application Thread] INFO  i.b.g.m.MainViewModel: 
checkCryptoSetupResult=true
loadEntryMapResult=false
walletInitialized=false
p2pNetWorkReady=false 
Nov-14 00:08:10.850 [JavaFX Application Thread] ERROR i.b.n.p.n.TorNetworkNode: TorNode creation failed with exception: Connection refused (Connection refused) 
Nov-14 00:08:24.993 [loadEntryMapThread] INFO  i.b.n.p.s.P2PDataStorage: persistedEntryMap size=4382 
Nov-14 00:08:25.059 [JavaFX Application Thread] INFO  i.b.g.m.MainViewModel: 
checkCryptoSetupResult=true
loadEntryMapResult=true
walletInitialized=false
p2pNetWorkReady=false 

Nov-14 00:12:05.708 [JavaFX Application Thread] WARN  i.b.g.m.MainViewModel: startupTimeout called 
```
resulting in warning:
Warning
The application could not startup after 4 minutes.
You still did not get connected to the Bitcoin network.
If you use Tor for Bitcoin it might be that you got an ustable tor circuit.
You can wait longer or try to restart.
Close Shutdown

Do you have a hint on what else I could try? 
Are there cli argument with which I could hint Bisq to the running Tor connection?

**Comment by 1989gironimo** [comment]
Totally forgot about this :)
sejktmcsdlmfhsc is right, starting/stopping the torbrowser doesn't change anything.
Maybe it's smarter to open a bugreport on the tails bugtracker?
-> https://labs.riseup.net/code/projects/tails/issues

**Comment by ManfredKarrer** [comment]
With the upcoming release v0.6 we support pluggable transports. Not sure if that helps with Tails but maybe worth a try. Beside that there are more features planned for the Netlayer Tor library from @JesusMcCloud. To pass custom torrc entries, enable OS default Tor instance to be used (not 100% if that will be possible) and more network settings options.

**Comment by JesusMcCloud** [comment]
See also JesusMcCloud/netlayer#7, and JesusMcCloud/netlayer#4

**Comment by cashordore** [comment]
Tails is a great platform for Bisq; i'm disappointed it isn't supported, natively.

**Comment by ManfredKarrer** [comment]
@cashordore We lack of developers. If you are familiar with Tor and Java you are welcome to help!
