### ISSUE TITLE
Name missing in UK Faster Payments

### ISSUE THREAD

**Issue by CliffS** [bisq-network/bisq#812]
There are two issues, actually:

1.  Faster Payments and National Bank Transfer are the same thing in the UK.  I needed to add my bank twice to be able to accept both.

2.  When making a Faster Payment, it is necessary to put in the recipient's name.  However this information is not provided, although it *is* provided for SEPA payments.

**Comment by ManfredKarrer** [comment]
So all National Bank Transfer are Faster Payments in the UK? Is the name required for all banks? I assume not as I hear that the first time.

**Comment by ManfredKarrer** [comment]
Can we continue that discussion on the Forum? I prefer to keep Github for technical issues.

**Comment by cbeams** [comment]
Closing as superseded by #1274.
