### ISSUE TITLE
A part of the build instructions won't work with Java >= 1.9

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#813]
The extension mechanism has been removed from Java in its version 1.9:
https://blogs.oracle.com/java-platform-group/planning-safe-removal-of-under-used-endorsed-extension-directories

This part of the build instructions rely on it:
"Copy the BountyCastle provider jar file from the local maven repository to the jre/lib/ext directory"

**Comment by ManfredKarrer** [comment]
Ah thanks. We are still on java 1.8, but do you know how to solve that for java 9?

**Comment by ghost** [comment]
Putting the necessary JAR file(s) into the classpath should work, shouldn't it? I don't understand why it has been advised to put them into jre/lib/ext, it's really a bad idea.

**Comment by cedricwalter** [comment]
Hi
that's the solution i've made in my branch, PR https://github.com/bitsquare/bitsquare/pull/859 so should work now with Bisq 0.5.3, if so please close the issue.

**Comment by ripcurlx** [comment]
Issue is closed because of [Java 10 support](https://github.com/bisq-network/bisq/pull/1660) that was merged yesterday.
