### ISSUE TITLE
Automated Transaction fee too low for withdrawal!

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#814]
I withdrew 0.7 bitcoins 2 days ago exactly, and the transaction has been broadcasted but still 0 confirmations. 
The fee satoshi/byte was 20 by default so i changed it to 40 and then i withdrew - still waiting for my tx to be confirm and im stressing.  Now if i left it 20 by default i assume that was even lower and would never get confirmed. Why isnt the fee automated to give the correct estimation for sending BTC so that users' coins dont get stuck in limbo.?
Could you maybe make an option for the user to choose what type of fee they want? such as Higher fee for faster transaction and Medium fee for Normal send. ?

**Comment by ghost** [comment]
Also - it would be nice if there was another feature to be able to abandon(reverse) transaction such as bitcoinqt has, right click on tx -> abandon transaction.
Im really stressing about the btc now.

**Comment by MarcSte** [comment]
No worries, you won't lose your funds. They should reappear in your wallet after 3 days(?).

You can see which fee is appropriate here: https://bitcoinfees.21.co/

Dynamic tx fees are included in the next release.

Alternatively, you could use this tool and try to accelerate your tx. They include 100 user txs in each block they mine. The service is a little congested as well. Just ignore their forced statement: https://www.viabtc.com/tools/txaccelerator/

For support stuff please use the [Bitsquare forum](https://forum.bitsquare.io/) next time. Github is just for development stuff. Please close here.

**Comment by ghost** [comment]
@MarcSte thank you so much!!!! In the beginning i had an issue posting the tx on viabtc but i read that every hour on the hour you have to try again because they have a limit so it worked. You're a life saver!

Dynamic tx fees would be great! thank you

**Comment by psytek** [comment]
mine was set to 5? It has been 14 days now
