### ISSUE TITLE
Centralized services integration

### ISSUE THREAD

**Issue by eliasbalasis** [bisq-network/bisq#815]
I have built a centralized software platform with support for pluggable electronic trading services.

Are there any considerations/plans to wire bitsquare with a server side to provide centralized functionality?

**Comment by ManfredKarrer** [comment]
We are working on APIs so other people could use Bitsquare as kind of Backend. We are not working on any centralized systems but if those are using us we don't have any issue and provide basic support (APIs).

**Comment by eliasbalasis** [comment]
Thanks,
if it explains better,
I was more thinking about exposing the P2P functionality via a server and transform bitsquare GUI to communicate with that server instead for centralized features

**Comment by ManfredKarrer** [comment]
Ah ok. That is basically planned for a mobile version. So the user hosts his headless version (on a server or at home) and then connects to that as a light client. That model can be used then also for other use cases. Though we don't have the resources atm and to much else to do first.
The APIs will be a mid step. You can run a special version of Bitsquare on a servers as well (headless) and then communicate via API to it. Full trade will not be able soon, but for altcoin trades it is planned and possible. For Fiat it will be not feasible as most banks are not offering APIs to send or confirm Fiat transfers.
Feel free to continue the discussion the Forum. I prefer to keep Github for technical issues.

**Comment by eliasbalasis** [comment]
I understand,
my perspective is closer to a centralized services hub, for many users,
with bitsquare networking components running isolated at the server side background and their functionality exposed via dedicated server side connectivity APIs

Have a look at
https://drive.google.com/file/d/0B3tIYUvecvkAOEo1TDZuaHB0b2s/view?usp=sharing
I hope it helps

A primitive demonstration of the platform end-to-end functionality can be found under
http://nonsecure.floor13.tech/findashboard/
a simple YahooFinance based live quotes service
I could share the credentials separately
