### ISSUE TITLE
Fee + dust output

### ISSUE THREAD

**Issue by HSB65** [bisq-network/bisq#817]
![error](https://cloud.githubusercontent.com/assets/18144690/26188579/4d9d7b66-3ba0-11e7-8422-50a1546ac5e8.png)

I get this error message. Don't understand it.

**Comment by ManfredKarrer** [comment]
Can you send me (forum PM or email) a screenshot of the create offer screen?
It usually comes when the change output would lead to a dust value or if you want to use a too small amount which is less then tx fee+ dust (2730 satoshi).

**Comment by HSB65** [comment]
Removed for privacy reasons.

**Comment by HSB65** [comment]
Basically this error seems to appear every time I try to place sell orders in version Bitsquare-64bit-0.4.9.9.2

**Comment by ManfredKarrer** [comment]
@HSB65 I will investigate. Can you get in touch by email or PM at forum? I don't want that you expose so much data online. I will remove the screenshots.

**Comment by ManfredKarrer** [comment]
Can you try to make a normal transaction to yourself where you put all available funds and send it to your own address. It might be that you have a lot of tiny unspent outputs and that this causes the issue.

**Comment by ManfredKarrer** [comment]
Damn I found the error. Will push a new release soon.

**Comment by ManfredKarrer** [comment]
https://github.com/bitsquare/bitsquare/releases/tag/v0.4.9.9.3
