### ISSUE TITLE
FEATURE REQUEST: Optionally allow LTC Instead of BTC

### ISSUE THREAD

**Issue by ElLamparto** [bisq-network/bisq#818]
BTC is often used as an intermediary for buying/selling altcoins for fiat.
The current BTC transaction backlog is > 200k and it is deteriorating quickly.
It seems that the Core is not in a hurry to implement BIP148 or another solution.

Since the LTC and BTC interfaces are identical, I wonder if it would be realistic to
optionally allow LTC becoming the principal currency in Bitsquare.

**Comment by ManfredKarrer** [comment]
Yes, we are indeed thinking in that direction. We still need to get first the next release out but if tx issue on btc keeps getting worse we need to offer alternatives.
