### ISSUE TITLE
Unconfirmed transaction to an external wallet

### ISSUE THREAD

**Issue by ElLamparto** [bisq-network/bisq#819]
After a successful trade (buy BTC), I send the purchased amount to an external wallet.
After 20 hours the transaction is still unconfirmed.

Size: 191B
Fee: 0.0002
Inputs: 1

bitsquare v0.4.9.9.3

What will happen if the transaction rest unconfirmed and the network "forgets" about it?

**Comment by ManfredKarrer** [comment]
You can make a CPFP tx: http://bitcoinist.com/bitcoin-transactions-confirmed-seconds/
In the worst case if it does not get confirmed I can instruct you how to do a double spend but that is just for emergency and a bit of effort.
Please check the widthdrawal fee in your settings , it should be set to about 100 sat/byte. The calculation in the current version in not very accurate. But when u do a widthdrawal u get a popup where u see the actual fee in sat/byte. That should be whats recommended at https://bitcoinfees.21.co (200-300)

**Comment by ElLamparto** [comment]
I'll check the withdrawal fee (I did not touch it). Does bitsquare rebroadcast a transaction? I am not in a hurry but I do not want to lose BTC.

**Comment by ElLamparto** [comment]
1. Where are the settings (debian)? I do not see the widthdrawal fee in the GUI.
2. How to make CPFP from bitsquare? Just resend the same amount to the same address but with a higher fee?
Thanks!

**Comment by ManfredKarrer** [comment]
In the top menu go to Settings and tab Settings there is a text field for setting the withdrawal fee. Maybe you have to scroll down....
If you have sent to the external wallet BTC you can just do another tx with using the funds you snet out as the input for another tx with a higher fee. Be sure to set the fee much higher as the standard fee to make CPFP attractive for miners.
No worry no money is at risk, worst case to takes longer to get confirmed....

**Comment by ElLamparto** [comment]
Thank you, I found the setting. 20 sat/byte!
I suggest to increase that value on an upgrade or inform users about that necessity...

I'll keep you informed and I'll close this ticket when tx completed.

**Comment by ManfredKarrer** [comment]
Yes that was the old default. unfortunately tx fee went crazy over the last months ;-(
we increased the default already but if u have an old version we dont overwrite your old values.
in the next version we will have dyn. fees and fee estimation anyway so that will not be needed anymore.

**Comment by ElLamparto** [comment]
That's great! Tomorrow I'll try to figure out, how to do CPFP from Bitcoin Core 0.14... (if the tx is still alive until then...)

**Comment by ElLamparto** [comment]
Don't bother. I've found another way and the transaction is now confirmed. :-)
Thank you for your support.
