### ISSUE TITLE
Finalize UI redesign

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#82]
Finished the redesign and get more usability feedback.

**Comment by ManfredKarrer** [comment]
I want to close now this iteration of UI improvements and will create new issues for the remaining which will implement the suggestions from the usability tests. They will have lower priority and could be taken by new developers joining as many are isolated and easy to start.

**Comment by cbeams** [comment]
Sounds good, yeah. Smaller issues are better anyway.
