### ISSUE TITLE
Unfinished trade

### ISSUE THREAD

**Issue by ElLamparto** [bisq-network/bisq#820]
Buy BTC: I received BTC and withdrew it to an external wallet. After 2 days the tx was confirmed (please see a_transactions.png). However the trade is still open (see a_open_trades.png).

Is there anything I can do about it?
Do you need more info?

[a_unfinished_tx.zip](https://github.com/bitsquare/bitsquare/files/1028403/a_unfinished_tx.zip)
bitsquare v0.4.9.9.3.

**Comment by ManfredKarrer** [comment]
When u click on move funds to internal wallet it should get closed.

**Comment by ElLamparto** [comment]
Manfred, your trick worked. Thanks!
It is a bug though, so I leave the ticket open.

**Comment by ManfredKarrer** [comment]
Why do u think its a bug. Maybe its bad usability but it is intended to work like that....

**Comment by ElLamparto** [comment]
Because I have to press "move funds to internal wallet" though the funds were moved to an external wallet long ago. Not logical.
Not consistent either, because all my previous transactions were closed correctly.
