### ISSUE TITLE
Cannot build project -  Failure to find org.bitcoinj:bitcoinj-core:jar:0.13.1.11

### ISSUE THREAD

**Issue by luizfelipetx** [bisq-network/bisq#821]
Failed to execute goal on project common: Could not resolve dependencies for project io.bitsquare:common:jar:0.4.9.9.3: Failure to find org.bitcoinj:bitcoinj-core:jar:0.13.1.11 in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-oss-snapshot has elapsed or updates are forced -> [Help

**Comment by ManfredKarrer** [comment]
You need to build the latest version of the BitcoinJ fork (branch: FixBloomFilters) as instructed in the build.md file.
git clone -b FixBloomFilters https://github.com/bitsquare/bitcoinj.git

**Comment by luizfelipetx** [comment]
i will try.
