### ISSUE TITLE
Bitstamp bug: miscalculates % distance from market price

### ISSUE THREAD

**Issue by fresheneesz** [bisq-network/bisq#823]
I'm trying to do this trade:

![bitstamp distance from market bug](https://cloud.githubusercontent.com/assets/149531/26467139/2a16bef4-4146-11e7-97e8-25b552238a87.jpg)

It says its 99.02% from market price, which seems correct to me. However, when I press next step, it pops up a blocking warning that says "The price you have entered is outside the max. allowed deviation from the market price. The max allowed deviation is 10.00%..."

So.. 99.02% seems like less than 1% off market price - clearly not over 10%. So what's going on here?

**Comment by fresheneesz** [comment]
Ok I figured this out. The error message made things as clear as mud. It would have been nice if it had said the percentage over the market price in that error message. I thought "distance in % from market price" was "percent of market price" - i wanted to list something 99% of market price (1% distance). Better error message or titling is needed here

**Comment by Piste** [comment]
This wording also got me tripped at first. Maybe a display of a quick calc of what the price could be at the time of placing a bid or ask could help. Indicative. 

EDIT: More visually, I'd display an estimated price, in grey, to the right of the percentage sign in the screenshot above.

**Comment by ManfredKarrer** [comment]
Thanks for the input. As soon we have a dedicated UI dev we will re-work that screen.

**Comment by fresheneesz** [comment]
I really question the value of closing stale tickets. Does this bug still exist? Why close this ticket if the bug persists?

**Comment by ripcurlx** [comment]
@fresheneesz That is actually what this auto-stale is all about. Issues with labels like ```a:bug``` will never be closed. Just tickets that didn't have any activity for 90 days. We want to have an issue handling that important stuff is not buried below issues that might be fixed already or are not that important. In this case the UI changed quite a bit already. Next to the percentage value there are now indication/warning symbols explaining if your selling to or against your advantage. If that is not sufficient from your point of view, feel free to re-open this ticket.
