### ISSUE TITLE
Why do I lose my offer fee if I remove my offer? 

### ISSUE THREAD

**Issue by fresheneesz** [bisq-network/bisq#825]
This doesn't make sense to me. The offer fee is for the arbiter. If no one ever accepts my offer, the arbiter doesn't do anything. Why should I lose money if no one accepts my listed offer? This feels very wrong to me. This punishes people for using the system in its current state (not many users, not many open offers). I'm not going to risk listing something on bitsquare if the likely scenario is I have to remove my listing and lose my offer fee. You need to incentivize people to list offers - there should be no risk for listing something.

**Comment by ManfredKarrer** [comment]
The offer fee is required a spam protection for the P2P network.

**Comment by fresheneesz** [comment]
@ManfredKarrer  The fee is far too high for just spam protection. Its almost $4. Spam protection should be something below 1 cent. If there's spam protection it should be fully separable from a refundable arbiter fee. Otherwise no one is going to feel comfortable putting offers on bitsquare. I'm certainly not. I'm a little pissed that the application didn't make it clear this fee is non-refundable. 

On poloniex, they incentivize people to list open offers by giving them a significantly lower fee structure. Unfortunately, I can't get my damn xmr out of poloniex, and I don't trust exchanges anymore than I'm forced to. But no one is on bitsquare, and I suspect part of the reason is this fee.

**Comment by ManfredKarrer** [comment]
The fee includes the TX fee that is why it is so high. The fee the arbitrator receives is 0.0003 BTC. Please continue the discussion on the Forum. I want to keep Github for technical issues.

**Comment by fresheneesz** [comment]
https://forum.bitsquare.io/t/loss-of-fee-on-canceled-open-trade-is-too-expensive/2146
