### ISSUE TITLE
Cannot download app

### ISSUE THREAD

**Issue by hallwaysquirrel** [bisq-network/bisq#826]
trying to dl Bitsquare-64bit-0.4.9.9.3.exe 
i run windows 64bt

but i get error msgs like:

**Comment by hallwaysquirrel** [comment]
'Failed to find library"
"Failed to locate JNI_CreateJavaVM"
"failed to launch JVM"

then quits installation

**Comment by ManfredKarrer** [comment]
Please try to remove the Bitsquare application directory (if you have not used Bitsquare before you can do a uninstall, otherwise do it manually because the application data directory contains the wallet and important data).

**Comment by Piste** [comment]
@hallwaysquirrel did Manfred's suggestion fix your problem? Can we close this issue?
