### ISSUE TITLE
mac, bitsquare version 0.4.9.3, image not recognized

### ISSUE THREAD

**Issue by franknyoung** [bisq-network/bisq#827]
Mac OSX EI Caption version 10.11.6

As below image, can't install bitsquare 0.4.9.3, is there any requirements?

![image](https://cloud.githubusercontent.com/assets/23159763/26762613/c8fdc15a-4977-11e7-94f1-93755f1ed822.png)

**Comment by ManfredKarrer** [comment]
Are you sure the download completed? Seems like a incomplete dmg file...

**Comment by franknyoung** [comment]
Yep, you are right. I recheck the download again and already install it.Thank you

**Comment by ManfredKarrer** [comment]
Ah good! ;-)
