### ISSUE TITLE
Can not connect to tor, both in USA and Singapore

### ISSUE THREAD

**Issue by cooladam201212** [bisq-network/bisq#830]
I opened 2 windows 7 32bit cloud instance.One in Atlanta, another one in Singapore

Successfully connected to Tor network once.But can not connect after that

![wechatimg264](https://user-images.githubusercontent.com/7540590/26985105-a1703ec8-4d74-11e7-89cd-131b6f1cc696.jpeg)

**Comment by ManfredKarrer** [comment]
Do you have any firewall? Usually there are very few issues but if you run it in a cloud service there might be something... Try if Tor browser works

**Comment by cooladam201212** [comment]
Yep, it's the cloud service's problem. I changed to a physical machine and it's OK now.

Thank you very much
