### ISSUE TITLE
help me in solving this

### ISSUE THREAD

**Issue by maharshi001** [bisq-network/bisq#832]
![screenshot from 2017-06-13 19-40-24](https://user-images.githubusercontent.com/29401395/27094688-9a4eb9b4-5088-11e7-90c0-1f692951106d.png)
give me the commands to uninstall this....... plzzzzzzzzzzzzz...........

**Comment by ManfredKarrer** [comment]
youtube-dl???? you might be on the wrong GH issues tracker...

**Comment by maharshi001** [comment]
with the command sudo apt-get remove youtube-dl its shows youtube-dl doesnt existed but when using sudo youtube-dl -u its shows youtube has been updated help me out in uninstallling this as iam a new learner for ubuntu

**Comment by ManfredKarrer** [comment]
As said we have nothing to do with any youtube-dl. Why u are reporting that at Bitsquare?

**Comment by jonathancross** [comment]
Hi @maharshi001, it looks like you are new to GitHub, so you may not realize that this is the wrong place for your question.
It needs to be posted in the correct project here: https://github.com/rg3/youtube-dl/issues/new
