### ISSUE TITLE
Lost 2 tx fees, not sure why. Please help.

### ISSUE THREAD

**Issue by Acedian** [bisq-network/bisq#836]
Trade ID
Y3ScY-d2d3c8bf-6a3e-4816-a68a-124b4c18a449-04993

it says; A timeout occurred.

**Comment by ManfredKarrer** [comment]
Do u remember the currency and price and if it was a buy or sell offer?

**Comment by Acedian** [comment]
I was trying to **buy BTC** with **GBP**. The price of BTC at the time was about 2100GBP. The fee taken was 0.002 for each, totalling 0.004BTC I think.
