### ISSUE TITLE
Fatal Error On Startup Windows x86

### ISSUE THREAD

**Issue by gustebeast** [bisq-network/bisq#838]
Seems like a few people are not able to get the windows x86 version to start up at all. Every time I try and start the application (either via administrator or not) I get this error: https://pastebin.com/a0AFBGQe

**Comment by Piste** [comment]
Are you using the latest version of Bisq (fka Bitsquare)? I am running version 0.5.1 on Windows 10 without a problem.

I saw this in your paste (thanks for this, btw):
`VM Arguments:
jvm_args: -Djava.library.path=C:\Users\gus\AppData\Local\Bitsquare\app;C:\Users\gus\AppData\Local\Bitsquare -Djava.launcher.path=C:\Users\gus\AppData\Local\Bitsquare -Dapp.preferences.id=io/bitsquare/app
java_command: <unknown>
java_class_path (initial): C:\Users\gus\AppData\Local\Bitsquare\app\Bitsquare-0.4.9.9.3.jar`

That Jar version doesn't look good. Actually my Bisq doesn't have any Bitsq* files in that directory. Only Bisq.cfg and Bisq.jar.

I'd recommend starting fresh with a new install and see if the problem persists.

**Comment by gustebeast** [comment]
Downloaded and installed latest version, same issue: https://pastebin.com/yXHpuYEw

**Comment by ManfredKarrer** [comment]
I just tested latest version again on my Win32 VM and it works. Seems to be some local issue. 
Try to delete C:\Users\mk\AppData\Local\Bisq and install new. Do NOT delete C:\Users\mk\AppData\Roaming\bisq as there is the wallet!
Do you have a AV software? There have been reports that they sometimes delete files.

**Comment by gustebeast** [comment]
Deleted and reinstalled, same issue. I'm on win64, perhaps a java issue?

**Comment by freimair** [comment]
@gustebeast that log you provided shows a segfault in the JVM, more exact, the D3D9 part of JFX. So, your Java installation seems to be at fault.

Aside from that, is the issue still there?

Edit: seems to be the same problem as #808

**Comment by gustebeast** [comment]
Probably something on my end, but I am no longer using the tool so im gonna close this out
