### ISSUE TITLE
Time out occurred. Takers fee paid.

### ISSUE THREAD

**Issue by justarandomdude** [bisq-network/bisq#839]
Hi,

My first trade did not go so well. I was trying to buy some BTC but when I pressed to confirm order an error has occurred> Time out occurred. Takers fee paid. I lost 0.0020 BTC. not so much but still not very pleasant. Please refund.
Trade ID 00143478-02cf0534-7cab-4f81-840d-9ebd841dc279-04993
Wallet 1JjKqvjvqG4WK1EAVvwsY1PvDkhN7dJREf

**Comment by ManfredKarrer** [comment]
i found the issue. will be fixed in upcoming release. it is bc the btc network does not reliably confirm a broadcast anymore (was working reliably earlier but seems full nodes behave a bit different with spv nodes since a while).

**Comment by Klar** [comment]
same happened for me, is it possible to get it back? got it like three or four times now :(

**Comment by ManfredKarrer** [comment]
Ping me by PM on the forum...

**Comment by leShnou** [comment]
same thing for me, three times now with trying to buy monero with bitcoin. How can I be refunded? PM on what forum?

**Comment by ManfredKarrer** [comment]
https://forum.bisq.io/

**Comment by cbeams** [comment]
Closing as complete (I assume, via PM with @ManfredKarrer on the forum). /cc #1167.
