### ISSUE TITLE
crash when start on ubuntu16.04 and 16.10

### ISSUE THREAD

**Issue by mouqi123** [bisq-network/bisq#840]
[Thread debugging using libthread_db enabled] Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1". Core was generated by `/opt/Bitsquare/Bitsquare'. Program terminated with signal SIGSEGV, Segmentation fault.
0 0x00007fd11092fff7 in _expand_stack_to(unsigned char*) () from /opt/Bitsquare/runtime/lib/amd64/server/libjvm.so

**Comment by ManfredKarrer** [comment]
It is a issue with latest Ubuntu update. Best to revert the Kernel. 
See: https://forum.bisq.io/t/solved-0-4-9-9-3-amd64-not-starting-on-debian-9-0-stretch/2302/4
