### ISSUE TITLE
LimitedKeyStrengthException

### ISSUE THREAD

**Issue by mouqi123** [bisq-network/bisq#841]
Default crypto policy has not been changed. Only weak keys with length 128 are allowed by the default policy
PS: build from source on ubuntu 16.04.

**Comment by mouqi123** [comment]
This problem is solved. just overwrite the default JCE. http://www.javamex.com/tutorials/cryptography/unrestricted_policy_files.shtml

**Comment by ManfredKarrer** [comment]
If you follow the build instructions there is the info provided as well.
