### ISSUE TITLE
Upgrading to Bisq from Bitsquare

### ISSUE THREAD

**Issue by mmortal03** [bisq-network/bisq#844]
I already had Bitsquare installed on my system, then I installed the newly branded Bisq. I noticed that Bisq doesn't pull any of my settings from my previous Bitsquare install. How can I get it to do so?

**Comment by mrosseel** [comment]
hi @mmortal03 , unfortunately the db structure of Bisq is not compatible with Bitsquare so you have to re-enter your information.

see also this forum post:
https://forum.bisq.io/t/bisq-v-5-0-not-updating-from-old-app-nothing-carried-over-either/2366
