### ISSUE TITLE
Refresh indicator of main market price

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#845]
The market indicator doesnt refresh if the program stays open in one Tab Window constantly, i would have to change between tabs to go back and see that the market price as well as the offer prices has indeed changed.

Can you make this to refresh together with offer prices to change without user intervention automatically?

**Comment by ManfredKarrer** [comment]
Oh thats a bug. Thanks for reporting. I will look into it...

**Comment by ManfredKarrer** [comment]
I could not reproduce the missing update in the price display in the main menu but the missin gprice update in the offer book table. Fix latter with https://github.com/bitsquare/bitsquare/commit/73f21399232eb804e2f6830b25c5203e17d2b877

If you still dont get the updates in the top menu price display, can you try to restart the app and see if you can reproduce it?

**Comment by ManfredKarrer** [comment]
Fix released...

**Comment by Piste** [comment]
@2SI3NX can you confirm this fixed your issue?

**Comment by ManfredKarrer** [comment]
@Piste: Thanks for helping to clean up the GH issue list. I never find time to do it. Don't miss the compensation request deadline for the genesis issuance (see forum).

**Comment by Piste** [comment]
@ManfredKarrer I cannot lie, I've got my eyes on it...
I am researching the best ways for me to find out issues that could be closed. Trying to make a dent, other than being a fanboy on Twitter :p
I can't code Java for the life of me. I thought of linting for the Bisq codebase but didn't seem up my alley. Feel free to point me in the right direction if that's something you're interested in. Any other involvement? Like labelling and all?

**Comment by ghost** [comment]
Sorry for late response. As far as i can see, yes its working now in the latest version.  I dont see any delays in refresh :)  Thanks @ManfredKarrer !

**Comment by ManfredKarrer** [comment]
@Piste Thanks! Cleaning up the issue list is a great help! Great to see people moving from wasting their time on social media (I waste as well too much there) to actually help to get things done! You know: 
Cyperpunks write code and don't post on reddit ;-)

**Comment by Piste** [comment]
Mantra-worthy. Been working on reading more long form and less short term stuff as well. Happy to help this great project.

**Comment by ghost** [comment]
@ManfredKarrer Not sure if i should open a new issue or if i should just post this here.. but since after you sorted this out, The only price that doesnt refresh and you have to switch between buy and sell tabs so that the price updates is the column: EUR (min - max)

The far left column "Price in EUR for 1 BTC" refreshes correctly, its just the "EUR (min - max)" that still needs fixing for real time updates.

**Comment by ManfredKarrer** [comment]
Ah good find! Yes would appreciate if u can fix it! Dont forget to make your compensation request end of the month!

**Comment by ghost** [comment]
@ManfredKarrer apologies but im not a developer. I just like to spot bugs and report... does that make me qualified for the compensation request you mentioned?

Wish i could fix it myself though.

**Comment by r8d8** [comment]
@ManfredKarrer, can I try to fix it?

**Comment by ManfredKarrer** [comment]
@r8d8 Sure, would be great!

**Comment by ghost** [comment]
This problem still persists. Perhaps i should open a new issue on this?
