### ISSUE TITLE
same bank transfer : US - high risk of chargeback

### ISSUE THREAD

**Issue by jbshirk** [bisq-network/bisq#846]
![bitsquare transfer same bank](https://user-images.githubusercontent.com/3949396/27754381-4c01bc7e-5db8-11e7-9df5-b1581cdbe5ca.png)

This isn't true, at least not with BB&T online banking. You simply send the amount to the other account; since you initiate the deposit, you can't just ask for it back. It is a deposit, not a demand draft. This is risk-free unless you are drugged or under physical duress.

https://www.bbt.com/sites/bbtdotcom/online-services/online-banking/payments-and-transfers.page#tab4.

https://www.bbt.com/online-access/online-banking/personal-payments.page

Look here:
https://www.bbt.com/assets/bbtcom/content/pdf/customer-service/personal-services-pricing-guide/bank-services-agreement.pdf

11.FORGED OR UNAUTHORIZED TRANSACTIONS

Duty to Safeguard Account. You have a duty to safeguard access to your account (including any credit accounts), account information, checks, signature stamps, account security codes, passwords, or personal identification numbers (“PIN”) and personal identification. ... You agree to keep any account information, security code, password, PIN or personal identification used to access your deposit or credit account(s) secure and strictly confidential and not to disclose such information to any other person. You must notify the Bank immediately if this information is lost or has become known to, or been used by, an unauthorized person. 

**You acknowledge that the Bank has no method to determine whether a transaction conducted with use of a valid name, account number, and security code or personal identification was proper, and therefore authorize the Bank to complete any transaction involving your account made with the use of such information.** Subject to applicable law, **you agree to be responsible for any transaction initiated with the use of a valid name, account number, security code, or personal identification, and agree that the Bank shall have no liability for any loss, claim, or damage you sustain as a result of the use of your security code or personal information described above whether such transaction was authorized or not.** These rules apply to all checking, savings, or credit accounts in which a check, draft, or other item is used to withdraw or transfer funds. The rules governing electronic fund transfers are contained in Section L of this agreement.
...
Electronic Fund Transfer Agreement & Disclosures

10.UNAUTHORIZED TRANSFERS & YOUR LIABILITY. Tell us AT ONCE if you believe your Access Device has been lost or stolen, or that someone may have electronically transferred money from your account without your permission, or that someone has used information from a check to conduct an unauthorized electronic fund transfer. Telephoning us is the best way of keeping possible losses down. **Except in situations governed by the zero liability policy described in section 9, if you tell us within two (2) business days after you learn of the loss or theft of your Access Device or the unauthorized transaction, you can lose no more than $50 if someone makes electronic transfers without your permission.** If you do NOT tell us within two (2) business days after you learn of the loss or theft of your Access Device or the unauthorized transaction, and we can prove that we could have stopped someone from making electronic transfers without your permission if you had told us, you could lose as much as $500. Also, if your periodic statement shows transfers that you did not make, tell us at once. If you do not tell us within sixty (60) days after the statement was mailed to you, you may not get back any money you lost after sixty (60) days if we can prove that we could have stopped someone from taking the money if you had told us in time. If a good reason kept you from telling us, we will extend the time periods.

**Comment by ManfredKarrer** [comment]
@MarcSte Could you have a look?
