### ISSUE TITLE
keyPair must not be null error when you try to set password

### ISSUE THREAD

**Issue by SMH17** [bisq-network/bisq#847]
I have imported my previously created wallet in the newer Bisq and now when I go to Wallet password to set a password I get this error:

![ikfkjfkfj](https://user-images.githubusercontent.com/8108287/27756819-65c933a6-5dfb-11e7-9c14-01dacf423e3f.JPG)

**Comment by ManfredKarrer** [comment]
You cannot import the old wallet because we use a new wallet format (BIP 44). You need to transfer the funds with a normal BTC transaction. I assume you have not created any offer yet and has no funds there, if that is right just remove the data directory and start over again.

**Comment by SMH17** [comment]
Yes I have used an empty test wallet. However I haven't received any warning about the new format during the import

**Comment by ManfredKarrer** [comment]
Yes there is not check it will prob. even import the keys but just not accessible as BIP 44 uses another key path structure
