### ISSUE TITLE
0.5.0 uninstallable on Qubes OS / Debian Testing VM: "xdg-desktop-menu: No writable system menu directory found"

### ISSUE THREAD

**Issue by clayt0nk** [bisq-network/bisq#848]
Qubes OS is a fully virtualized OS, ie. everything is a virtual machine, so Bisq must install in one of those VMs. In my main Qubes Debian Testing VM, when I

dpkg -i Bisq-64bit-0.5.0.deb

(even after the addition of --force-all) I get this result:

Preparing to unpack Bisq-64bit-0.5.0.deb ...
Removing shortcut
xdg-desktop-menu: No writable system menu directory found.
dpkg: warning: subprocess old pre-removal script returned error exit status 3
dpkg: trying script from the new package instead ...
dpkg: ... it looks like that went OK
Unpacking bisq (0.5.0) over (0.5.0) ...
Setting up bisq (0.5.0) ...
Adding shortcut to the menu
xdg-desktop-menu: No writable system menu directory found.
dpkg: error processing package bisq (--install):
 subprocess installed post-installation script returned error exit status 3
Errors were encountered while processing:
 bisq

This was a bit shorter the first time, the above is a retry but ends with the same result: the package is in (according to the package manager) a not-fully-installed state. It must be removed before any other packages may be installed or upgraded in the future, ergo it must be removed.

--force-all does not get around this, and I don't have a work-around at the moment. Note that the same package installs fine for me on exactly the same revision of hard-metal Debian Testing.

Menu entries are an entirely secondary and unimportant feature, perhaps they should fail with just a warning and not break the whole install process?

**Comment by grazcoin** [comment]
The problem is a known bug in xdg
https://bugs.archlinux.org/task/33316 

The workaround:
sudo mkdir /usr/share/desktop-directories/
sudo dpkg -i Bisq*.deb

and to start the client:
/opt/Bisq/Bisq

**Comment by clayt0nk** [comment]
Yup, mkdir /usr/share/desktop-directories/
works as a fix here to, thanks.

Still think a nit like a menu problem should not cause the install to hard-fail, but neither do I know much about Debian package building and the constraints thereof.

**Comment by clayt0nk** [comment]
This is still broken, and the workaround still works.

**Comment by adrelanos** [comment]
Also happening in Debian based distributions. Please re-open.

**Comment by peterzen** [comment]
This problem is still here after 5 years... can't the desktop file (which is unused as per the README) be removed?  It's causing major pain to install on qubes; it breaks the fundamental file layout concepts of qubes.  The .deb package should be installable in the TemplateVM, not the AppVM.
