### ISSUE TITLE
Bisq 0.5.1 Debian 32bit Packaging problem?

### ISSUE THREAD

**Issue by ElLamparto** [bisq-network/bisq#849]
After successful install, Bisq does not start: **/opt/Bisq/Bisqe/en/libpackager.so not found.**

Indeed there is no /opt/Bisq/Bisqe directory. libpackager.so is located in /opt/Bisq.

**Comment by ManfredKarrer** [comment]
That is strange. Bisqe is nowhere used. I assuem u have downlaoded form github and checked the sig.
maybe just delete /opt/Bisq/ and install new.

**Comment by ElLamparto** [comment]
Yes, I checked your signature.

gpg --verify Bisq-32bit-0.5.1.deb.asc Bisq-32bit-0.5.1.deb
gpg: Signature made Sat 01 Jul 2017 03:32:59 CEST using RSA key ID F379A1C6
gpg: Good signature from "Manfred Karrer <manfred@bitsquare.io>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 1DC3 C8C4 316A 698A C494  039C F5B8 4436 F379 A1C6

**Comment by ManfredKarrer** [comment]
Try to remove /opt/Bisq/ and install new...

**Comment by ElLamparto** [comment]
I did. The same result.
Then I created /opt/Bisq/Bisqe/en/ and copied libpackager.so there. --> Bisq segfaulted at startup.

**Comment by ManfredKarrer** [comment]
Can u try to run from source?
https://github.com/bitsquare/bitsquare/blob/master/doc/build.md

the segfault is prob. bc of the new linux kernel issue.
adding that jre option (-BjvmOptions=-Xss1280k) should avoid it.

**Comment by ghost** [comment]
FYI. I can confirm new Kernel 4.4.0.83 released for Ubuntu 16.04. Works with latest 0.5.1 Bisq.

**Comment by ElLamparto** [comment]
I am still on Debian 8 (Jessie).

java -version
java version "1.7.0_131"
OpenJDK Runtime Environment (IcedTea 2.6.9) (7u131-2.6.9-2~deb8u1)
OpenJDK Server VM (build 24.131-b00, mixed mode)

uname -a
Linux [...] 3.16.0-4-686-pae #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) i686 GNU/Linux

**Comment by EvertonMelo** [comment]
Hi, 

you check The requeriments of install ??? 

> echo "Install Oracle Java 8, git, maven, unzip"

font: https://github.com/bitsquare/bitsquare/blob/master/doc/install_on_unix.sh ( line 9 )

**Comment by ElLamparto** [comment]
I suspected java version to be the cause. IMHO changing java version should be mentioned in the release note.
Next week I will upgrade Jessie to Stretch which probably has java 8 on board. That should fix the problem.
I'll keep you informed via this ticket.

**Comment by ManfredKarrer** [comment]
The java version was always Java 8. Java 7 does not work with Bisq. If you run the installer you don't need to care as the jre is packed in the app. Only if you run from source you need to follow exactly the build.md instructions.

**Comment by ElLamparto** [comment]
I tried 0.5.3, the same result.
[...]:/opt/Bisq$ ./Bisq 
/opt/Bisq/Bisqe/en/libpackager.so not found.

I checked env vars, I found:
PWD=/opt/Bisq

Soon I'll upgrade to Stretch which should be comparable to the current Ubuntu version.... I'll let you know.

**Comment by ElLamparto** [comment]
Ps. I just installed 0.5.3 on another Debian 8 machine --> the same result :(

**Comment by ManfredKarrer** [comment]
So its again that "/opt/Bisq/Bisqe/en/libpackager.so not found."?

**Comment by ManfredKarrer** [comment]
I just checked my ubuntu VM and libpackager is at: /opt/Bisq/libpackager.so
So for some strange reason your OS is installing it to that Bisqe/en/ package. No idea, maybe some OS language issue, which language do u use? I suspect the the e at the end of Bisqe is added for english or espanol? Wehn u move manually the stuff from /opt/Bisq/Bisqe/en/ to /opt/Bisq/ does that help?

**Comment by ElLamparto** [comment]
No, I have /opt/Bisq/libpackager.so (what is correct).
Directory /opt/Bisq/Bisqe/en/ does not exist.
The OS language is English.

Once I created /opt/Bisq/Bisqe/en/ and copied libpackager.so there. --> Bisq segfaulted at startup.

So libpackager.so is in the correct place. For some reason, Bisq searches for it in the non-existing folder /opt/Bisq/Bisqe/en/.

The problem appeared with 0.5.1 (or maybe 0.5.0 which I skipped).

**Comment by ManfredKarrer** [comment]
Very strange. Can u try latest installer 0.5.3. but dont assume its the installer.

**Comment by ElLamparto** [comment]
I upgraded my OS to Debian 9.1 (Stretch). 
The problem still exists. However I noticed the following:

If I start Bisq from my home dir, I get:
![selection_168](https://user-images.githubusercontent.com/9163437/28613969-690e6f7e-71f4-11e7-9cb1-e55975eeceb7.png)

If I start Bisq from /opt/Bisq, I get:
![selection_169](https://user-images.githubusercontent.com/9163437/28614001-88c5f076-71f4-11e7-8b70-3ead05b2d6f6.png)

You see the not printable character after Bisq?

I have an impression, that a variable holding the library path is not initialized or is missing the zero termination... I do not know Java at all, but in those two examples the library path is different and obviously contains some rubbish..

**Comment by ManfredKarrer** [comment]
@cedricwalter Do you have any idea? Never saw that issue before and never got it on my Ubuntus MV...

**Comment by cedricwalter** [comment]
Bug in JDK 8, in the javafx launcher, solved in openjdk 9
https://bugs.openjdk.java.net/browse/JDK-8157913
http://bugs.java.com/view_bug.do?bug_id=8157913

There is a workaround we can implement
Unpack packager-created packages, replace launcher by custom implementation, repackage manually. 

Here is a changeset from another project that did the workaround:
https://github.com/cryptomator/cryptomator/commit/6006d65ce01e8f0852aadae8e5601f0e3dffce96

Another workaround is what you did:  create /opt/Bisq/Bisqe/en/ and copy libpackager.so  there. Cannot understand why you get a segfault as a reward through....

**Comment by ManfredKarrer** [comment]
The segfault might be because of missing -BjvmOptions=-Xss1280k which fixed the issue with recent linux kernel issues. See: https://forum.bisq.io/t/bitsquare-dont-opens-ubuntu-16-04/2312/33

**Comment by ManfredKarrer** [comment]
@cedricwalter Thanks for researching and finding! Any idea why that only seems to be a problem in one case so far? Never got reported it earlier. Should affect all linux users, no?

**Comment by ElLamparto** [comment]
The strange thing is that with previous versions I've done quite a few upgrades without problems.

Manfred, @cedricwalter, could any of you create for me an executable that works? I need Bitsquare and I know next to nothing about Java.

Thank you...

**Comment by ManfredKarrer** [comment]
@ElLamparto As I don't know how to solve that issue I cannot do anything here. But you can run form source code. See https://github.com/bitsquare/bitsquare/blob/master/doc/build.md

**Comment by ElLamparto** [comment]
If you gave me Bisq from your Ubuntu VM, wouldn't it work on my Debian?

**Comment by ManfredKarrer** [comment]
You mean that I give you the extracted app directory. Send me an email if you like I can send you.

**Comment by ElLamparto** [comment]
I installed xubuntu 16.04 (LTS) on a VM and then Bisq.
Bisq segfaulted immediately after start.

Which version of Ubuntu do you use?

**Comment by ManfredKarrer** [comment]
Ubuntu 14.04. Can u try to start with vm arg: -Xss1280k

**Comment by ElLamparto** [comment]
I know nothing about Java.
How to start Bisq with that vm arg? Please give me the syntax.
Thanks.

**Comment by ElLamparto** [comment]
CAN ANYONE HELP??

I tried:
java -Xss1280k -jar /opt/Bisq/app/Bisq-0.5.3.jar

I got:
Cryptography restrictions removal not needed
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.bisq.gui.app.BisqAppMain.doExecute(BisqAppMain.java:80)
	at io.bisq.core.app.BisqExecutable.execute(BisqExecutable.java:70)
	at io.bisq.gui.app.BisqAppMain.main(BisqAppMain.java:75)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more

I also tried export _JAVA_OPTIONS='-Xss1280k' and then run Bisq, but it segfaulted. As far as I remember, it had something to do with extending heap size.

**Comment by ManfredKarrer** [comment]
If you run from source code you need to follow exactly the instructions in /doc/build.md.

**Comment by ElLamparto** [comment]
Ok. I just try to have Bisq operational without compiling...

**Comment by ElLamparto** [comment]
I tried compiling bisq according to install_on_unix.sh. The process seemed to work correctly (incl. protobuf) until:

mvn clean package verify -DskipTests -Dmaven.javadoc.skip=true

which failed with:
[WARNING] The POM for org.libdohj:libdohj-core:jar:0.14.1 is missing, no dependency information available

Attached is the log.
[FailedBuild.zip](https://github.com/bisq-network/bisq-exchange/files/1272782/FailedBuild.zip)

**Comment by mrosseel** [comment]
https://github.com/bisq-network/libdohj
also needs to be checked out and installed in your local maven repository (mvn clean install)

**Comment by ElLamparto** [comment]
Thank you. Sorry, I do not know maven.
1. To what place check it out precisely?
2. And then what is the exact syntax ("mvn clean install")?
3. Finally, should I execute again "mvn clean package verify -DskipTests -Dmaven.javadoc.skip=true"?

**Comment by mrosseel** [comment]
1. Doesn't matter, not inside the bisq directory, somewhere else
2. that should do it, you can add -DskipTests to speed it up
3. Yes, libdohj is just a dependency needed to build bisq

**Comment by ElLamparto** [comment]
@mrosseel, thank you very much. I'll try it in the next weekend.
I hope that in the next version, the workaround described by @cedricwalter will be deployed and the install/upgrade will be flawless like always before v0.5.0.

**Comment by ElLamparto** [comment]
**Yesterday** I compiled libdohj and cloned bisq master.
I got:
[INFO] --- protobuf-maven-plugin:0.5.0:compile (default) @ common ---
[INFO] Compiling 1 proto file(s) to /root/bisq-exchange/common/target/generated-sources/protobuf/java
[ERROR] PROTOC FAILED: /root/bisq-exchange/common/target/dependency/protoc: 1: /root/bisq-exchange/common/target/dependency/protoc: Syntax error: ")" unexpected

[ERROR] /root/bisq-exchange/common/src/main/proto/pb.proto [0:0]: /root/bisq-exchange/common/target/dependency/protoc: 1: /root/bisq-exchange/common/target/dependency/protoc: Syntax error: ")" unexpected

**Comment by rtentser** [comment]
I have the same problem with 0.6.7 on Debian Stretch.

> /opt/Bisq/Bisqen/libpackager.so not found.

But copying libpackager.so to Bisqen don't make any difference. I don't have a segmentation fault, the program just fails to work with the same message.

UPD: Upgrade to openjdk-9-jre didn't help.

**Comment by ElLamparto** [comment]
I am a bit dissapointed, since this problem is not even in the roadmap.
Has anybody an experience in running bisq under wine/playonlinux? Is it possible at all?

**Comment by ManfredKarrer** [comment]
@ElLamparto Can you try to run it from source code?

**Comment by ManfredKarrer** [comment]
The roadmap on the webpage is not much maintained. We are short on dev resources and depend on other people to help out with stuff like that. Seems to be some specific OS issue as there for most people it works.
