### ISSUE TITLE
0.5.1: Reboot needed on fresh start after selecting base currency "Bitcoin"

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#850]
OS: Debian Stretch

When starting 0.5.1 fresh without data directory, one can select the base currency. The selection screen says, the default would be Bitcoin. When clicking on the selection menu button, and selecting "Bitcoin", the program says it had to reboot now, to take the change to affect.

But there was no change of the base currency. So there should not be any need to reboot, I guess?

**Comment by mrosseel** [comment]
Probably because you chose something from the dropdown bisq thinks you changed it. If you just click the button it will continue. Small bug.

**Comment by ManfredKarrer** [comment]
Good catch, will fix that...
