### ISSUE TITLE
"Not enough funds" error although wallet has sufficient available balance

### ISSUE THREAD

**Issue by pmknutsen** [bisq-network/bisq#851]
I get this error when trying to set up a new trade:
![screenshot from 2017-07-04 19-58-42](https://user-images.githubusercontent.com/1565499/27839679-68da7884-60f3-11e7-9d2c-9e405121284c.png)

Yet, the available balance reported should be sufficient to fund this trade:
![screenshot from 2017-07-04 19-58-52](https://user-images.githubusercontent.com/1565499/27839683-6e11ee9a-60f3-11e7-8a9f-c45123e233f9.png)

There are several unconfirmed tx in the wallet. Not sure if this is related to the discrepancy.

**Comment by pmknutsen** [comment]
This from the "Send funds" tab:
![screenshot from 2017-07-04 20-14-41](https://user-images.githubusercontent.com/1565499/27839955-78a1584e-60f5-11e7-943e-07a0b7a27d67.png)

**Comment by ManfredKarrer** [comment]
Are u using the latest version?

**Comment by pmknutsen** [comment]
v0.5.1

**Comment by pmknutsen** [comment]
FYI If I do Ctrl+E the sum available is the sum of "Available balance" and "Reserved in offers".

Also, all inputs have now confirmed but I am still getting the same warning.

**Comment by ManfredKarrer** [comment]
Have you tried to restart. Strange bug, don't have an explanation...

**Comment by pmknutsen** [comment]
Restart did not help. Same problem. I withdrew the entire Available balance to another btc wallet and then sent back the same amount to the bisq wallet. The order was then successfully entered. So, the Available balance reported above was definitely correct.

**Comment by ManfredKarrer** [comment]
Strange... would need an example to reproduce the issue...
