### ISSUE TITLE
New Feature Request:  Alarms/Alerts for Price Hits

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#853]
Would be quite useful and time saving if we could have built in Alarm/Alert feature for desired price hit, so that user is reminded to sell/buy at a specific price he wants.

**Comment by ManfredKarrer** [comment]
Good idea. Maybe some dev can work on that. I am too busy with other stuff atm.

**Comment by cedricwalter** [comment]
Hi @2SI3NX 

Can you elaborate on which kind of feedback you expect in the application? you expect a popup, an email, a sound alarm?

**Comment by ghost** [comment]
This can be a popup at the same time with a tiny sound reminder, and as well as an email field that would email the user. We could fill in an email smtp etc to be able to send out an alert email.  In other words all 3 would be awesome.

**Comment by cedricwalter** [comment]
@2SI3NX i am now fixing first all unit tests to be able to develop that feature using TDD. I expect a few days to achieve that before this feature get implemented by me.

**Comment by ghost** [comment]
Sounds like this could really be a great feature after all! thank you!

**Comment by ghost** [comment]
hi @cedricwalter any updates on this?   This could prove very beneficial at time like these when the price starts becoming very volatile.

Another question.  What do you think of automated offer takes? would this be included into the alarm system or would this be something separate?  Automated offer takes as in, when the price reaches a certain number it should automatically take the cheapest offer automatically.  Maybe this: https://github.com/bisq-network/exchange/issues/1047

**Comment by ManfredKarrer** [comment]
To take an offer automatically by some preferences should not be too hard. Maybe you make a small concept proposal to be clear about all details and potential complications. Might be a case for https://github.com/bisq-network/proposals. Dont need to be something super sophisticated but helps that before starting developing the concept gets right and others can add input. Specially @ripcurlx should be involved regarding UX.

**Comment by ManfredKarrer** [comment]
Close as it is implemented with Bisq mobile notification app
