### ISSUE TITLE
Systray icon disappears after a while in Ubuntu 16.04

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#856]
I thought something went wrong that was not related to bisq when it first happened, but it seems like it happened again.
After hiding the systray icon and doing other stuff in the background, after a while i notice that the tray icon is gone but bisq is still running i can see in the process monitor.

Any way we could find out how this happens or if you could have a look why this is happening?

I also tried to click on bisq again, but it complains that it is already running.
About that, is it possible you can make the startup shortcut detect that its already running if clicked on again, and just unhide the window instead of starting a new process?

**Comment by ghost** [comment]
Right so i have found the root cause of this problem.  The systray icon disappears only when opening Kodi at the same time. Whether Bisq is hidden in the tray icon or not, the systray icon disappears when Kodi runs. Not sure why this is, because i dont see any errors in the logs. But would be nice if this could be investigated and fixed.

**Comment by Piste** [comment]
Would the systray process have some log? Some [googling](https://askubuntu.com/questions/70691/where-can-i-find-unitys-log-files) pointed me to `~/.xsession-errors`. Does this file have any information relevant to Kodi and/or Bisq?
I also found some info about [enabling more icons in the systray](https://askubuntu.com/questions/30742/how-do-i-access-and-enable-more-icons-to-be-in-the-system-tray), this might help as well. 
Let us know.

EDIT: I should indicate that I have no Ubuntu running anywhere, especially not one with a UI.

**Comment by ElLamparto** [comment]
A bit off-topic: I installed Bisq on xubuntu 16.4 (32bit), but it segfaults at start. Have you done anything special before or after installation?

**Comment by ManfredKarrer** [comment]
Can you try to add that VM argument when starting the Bisq binary: -BjvmOptions=-Xss1280k

**Comment by ElLamparto** [comment]
Thanks. It did not work. I hope it will be corrected in the next version...

**Comment by ManfredKarrer** [comment]
That issue is caused by a Linux kernel issue: See:
https://forum.bisq.io/t/solved-0-4-9-9-3-amd64-not-starting-on-debian-9-0-stretch/2302/
https://forum.bisq.io/t/bitsquare-dont-opens-ubuntu-16-04/2312 

The usage of -BjvmOptions=-Xss1280k seemed to worked for most people.

**Comment by KanoczTomas** [comment]
If you mean it disapears from the 'start menu' with systray, then I have the same issue. I do not have Kodi, did not figure out when it happens, but the same used to haplen with bitsquare. A reboot fixes the issue and bisq icon is again visible in the 'start menu'. Running xfce as window manager, ubuntu 16.04.
