### ISSUE TITLE
Ticker API error: "

### ISSUE THREAD

**Issue by DanielFragaBR** [bisq-network/bisq#857]
The following API call started recently to return an error:
https://market.bisq.io/api/ticker/

    {
      "success": 0,
      "error": "An unexpected error occurred."
    }

**Comment by ManfredKarrer** [comment]
@dan-da Could u have a look?

**Comment by dan-da** [comment]
It is fixed with commit dan-da/bitsquare_market@287aa2e2afcbf2de797ef6bbdabb214aa024979f.   

Sorry about that, and thanks for the report!

**Comment by DanielFragaBR** [comment]
Thank you!
