### ISSUE TITLE
Key chain is already encrypted

### ISSUE THREAD

**Issue by isaacbcn** [bisq-network/bisq#866]
if i understand well i need to create a new account and a wallet for this account. 
I cannot find the option for bitcoin option in the altcoin account option. Nor in any other option. And when I try to sign in to a new wallet I get this error message. 
guide me through I know I am not very clever with these issues but I am good example of a common (non technological) user.

**Comment by ManfredKarrer** [comment]
You dont create a bitcoin or BSQ wallet/account. that is created bt default (funds menu and with alt+d it opens the DAO menu).
If you had imported eariler the old wallet it is better to start over again with a new data directory to avoid issues. (assuming u dont have funds/offer/trades...).
