### ISSUE TITLE
Keypair must not be null?

### ISSUE THREAD

**Issue by whisperisko** [bisq-network/bisq#867]
I imported wallet from seed from Bitsquare, then I tried to create a password and this happened:

![untitled-1](https://user-images.githubusercontent.com/29436760/28209546-4296239c-6893-11e7-8d15-a165909bf817.jpg)

**Comment by mrosseel** [comment]
did you get the seed from an old wallet and tried to import it in a new version of Bisq? 
That doesn't work because the wallets are not compatible. Best is to withdraw the bitcoin out of the old wallet to either another address or your new wallet.

**Comment by whisperisko** [comment]
Yes, the thing is I expected it to work. Anyway, I managed to uninstall my AV (Bitdefender) which deleted the Bitsquare 0.4.9 exe file, install the Bitsquare again and withdraw.
