### ISSUE TITLE
Funds locked after crash trying to set wallet password

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#870]
Bisq 0.5.1

Sent funds to bisq account for the first time. Tried to set account password but it resulted in an poup 
window informing of an error. I didn't save a screenshot thinking that the password has not been set after all, but afterwards, when trying to move the funds, bisq asked for wallet password and didn't recognize the one I just used in the action that resulted in the error. App crashed shortly afterwards while I was trying an emergency withdraw.

Checking the log (attached), I think the "java.lang.NullPointerException: keyPair must not be null. If we got the addressEntry created from PB we need to have setDeterministicKey got called before any access with getKeyPair()." line is the culprit as I remember something of the sort in the error popup.
[bisq.log.zip](https://github.com/bitsquare/bitsquare/files/1149586/bisq.log.zip)

Current situation is that coins are locked in Bisq account that doesn't recognize password.

**Comment by ghost** [comment]
Also, when I try to withdraw now, it issues "Error at creating transaction: org.bitcoinj.core.ECKey$KeyIsEncryptedException". It doesn't ask for password at app startup.

**Comment by ManfredKarrer** [comment]
Please do a backup of the app data directory and get in touch with me by email (manfred@bitsquare.io)

**Comment by ManfredKarrer** [comment]
Resolved. Reason was import of old seed words, which is not compatible.
