### ISSUE TITLE
Selecting to trade a coin does not update the Trading account dropdown

### ISSUE THREAD

**Issue by pmknutsen** [bisq-network/bisq#880]
When clicking a button to trade a specific altcoin, e.g. "Create new offer to sell DCR (for BTC)" does not update the Trading Account dropdown box on the Create offer tab. It seems only the last selected altcoin is used as default when re-opening the Create offer tab.

The expected behavior is that the Trading Account dropdown should automatically be updated according to the altcoin quoted on the "Create new offer..." button. Otherwise, it is easy to create an order in the wrong market if not paying attention.

**Comment by ManfredKarrer** [comment]
Thanks for reporting.
