### ISSUE TITLE
Trades in graph/tooltip do not reflect trades in list for same time period.

### ISSUE THREAD

**Issue by dan-da** [bisq-network/bisq#881]
I am working on implementing a summary view across markets for markets.bitsquare.io.   For verification purposes, I am comparing with Bisq app chart under Trades -> Show All.

But the numbers were not matching.   So I compared the trades that Bisq lists for a given day vs what is displayed in the graph tooltip.  They do not match up.

**Example:**
On July 23, 2017 the graph tooltip says Volume 1.9 BTC, Number of Trades: 6.
Yet in the trade list, 8 trades are shown for July 28, totalling 1.771.

Further, the trade list shows that 3 trades occurred today July 24 however the graph does not show any bar (or tooltip) for July 24 (present day).

I am attaching a screenshot.

![bisq-bug](https://user-images.githubusercontent.com/5110592/28542252-6bb80990-7070-11e7-9f45-9c3318575f2a.png)

**Comment by dan-da** [comment]
I haven't looked into this too deeply yet, but my first guess would be that the trade list is using user's local time and the graph is using UTC, or something similar to that.

**Comment by ManfredKarrer** [comment]
Yes the chart has a known bug with the time calculation. The data in the list are the correct ones.

**Comment by dan-da** [comment]
yeah it would be good to get it fixed in the chart so that the chart on markets.bitsquare.io will agree with the app.   else can be confusing to users.  If i find some time I may take a look.

**Comment by ManfredKarrer** [comment]
Yes its basically only in one class (TradesChartsViewModel) where the way how the data items are managed with time tick units is not correctly implemented. Would need a bit of concept redesign, so its not a trivial bugfix but a rewrite of the data management but quite isolated.

**Comment by ManfredKarrer** [comment]
Related to https://github.com/bisq-network/exchange/issues/559
