### ISSUE TITLE
Bisq on The Changelog?!

### ISSUE THREAD

**Issue by jerodsanto** [bisq-network/bisq#886]
Howdy from [The Changelog](https://changelog.com/podcast)!

_(Never heard of The Changelog? We've been interviewing the hackers, leaders, and innovators of open source and software development since '09.)_

We'd love to have you on the show sometime soon. Who would be best person to join us to talk about Bisq and all the cool stuff y'all are up to?

Please email editors@changelog.com to coordinate. 

Looking forward to it! 💚

**Comment by ManfredKarrer** [comment]
@jerodsanto Thanks for the invitation! 
@cbeams can you get in touch?

**Comment by cbeams** [comment]
Hah. Was in the middle of writing my response just now :)

Yeah, @jerodsanto thanks for reaching out! I'm a regular listener to the Changelog anyway, so it'll be cool to do something together.

I'll get in touch with you by mail.

**Comment by cbeams** [comment]
Closing this issue, as we'll continue the conversation and planning via email from here. Thanks again Jerod.

**Comment by cbeams** [comment]
Issue moved to [bisq-network/events #2](https://github.com/bisq-network/events/issues/2) via [**ZenHub**](https://www.zenhub.com/)
