### ISSUE TITLE
Are there any documentation on how to import the project into IntelliJ Idea?

### ISSUE THREAD

**Issue by streetbits** [bisq-network/bisq#889]
I've been trying to build the project in intellij idea but stuck with dependency issues and maven, any guides besides ["Building from source"](https://github.com/bitsquare/bitsquare/blob/master/doc/build.md).
I'm on Windows 7 and IntelliJ Idea 2017.1.1

**Comment by mrosseel** [comment]
if you follow the instructions in that page very carefully it should build. Paste your error here/irc/slack and someone might know the solution.

**Comment by streetbits** [comment]
Solved! I run "mvn clean install" on the project directory and then imported the project to IntelliJ idea and it worked.
Used maven 3.5 to do so.
hope this helps someone.

**Comment by streetbits** [comment]
@mrosseel I created a document detailing building with IntelliJ Idea steps, would you like me to share it here?

**Comment by ManfredKarrer** [comment]
Yes please. we can add it to the doc or wiki

**Comment by ManfredKarrer** [comment]
@streetbits Did you created a doc?

**Comment by eipplusone** [comment]
I had the same issue. It seems like the requirements are:

1) Make sure that you have JDK 8, not 9. The project doesn't build otherwise.
2) Do `mvn clean install` *before* you launch project inside IntelliJ. Invalidating caches/synchronizing doesn't help.

I'm no idea guru, so YMMV.

**Comment by ManfredKarrer** [comment]
You need the Lombok plugin. IntelliJ is used and recommended from the Bisq devs.
