### ISSUE TITLE
Record screencast

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#89]

**Comment by ManfredKarrer** [comment]
@cbeams, @btcll : Lloyd has offered to take that task if that is ok for you Chris.

**Comment by cbeams** [comment]
Yes, that would be great. Perhaps we could discuss the content on this evening's call? Not sure if you two have other specific plans, but I've been thinking it would be good to have the screencast reflect the content in the instructions for alpha testers #91. This doc has yet to be written, and is what I'm hoping to do with you tomorrow, Manfred.

**Comment by ManfredKarrer** [comment]
Yes, lets discuss a bit tonite, and maybe more in details later here. Maybe a few different short videos are good. One for basic overview (just trade), one with more details and setup, one for how to test it/run it (but mabye we should push that more when we have the server seed node)....

**Comment by btcll** [comment]
Sounds good to me, very happy to take direction. Lets discuss what sort
of screencasts will support the project best during the hangout tonight :)

Lloyd

Chris Beams wrote:

**Comment by ManfredKarrer** [comment]
@btcll, @cbeams:
As we discussed in the last hangout, the webpage has higher priority, so we thought it might be better if Chris will make the application screencasts, which will be part of the v0.1 release and docs and later we can add hi-level screencasts which Lloyd can take. But anyway, whoever has first time to take that should just maybe ping the other to prevent that both are working simultaniously on it.....

**Comment by cbeams** [comment]
Thanks for mentioning that, Manfred. I've just updated the title and assignee to reflect. Still think it's a very good idea to have a high-level screencast whenever it makes sense to put that together. These first ones will just be companions for the user guide with the audience being the very early adopters interested in our 0.1.0 alpha.

**Comment by btcll** [comment]
Totally okay for others to take charge of this while I focus my time on the website :)
When the website is ready for feedback and I have time for this I'll touch base with @cbeams to see where it is all up to. If it is still needing to be done we can work it out between ourselves from there.

**Comment by ManfredKarrer** [comment]
See https://github.com/bitsquare/management/issues/88
If you can make voice over with current version I can create a new screencast with 2 app overlapping instead of placed next to each other

**Comment by ManfredKarrer** [comment]
The screencast is basically done (Application demo video) but should be improved.
Request for improvement is handled by https://github.com/bitsquare/management/issues/88
