### ISSUE TITLE
Click the "Price in USD for 1 BTC" column header twice

### ISSUE THREAD

**Issue by dscotese** [bisq-network/bisq#892]
Error: 
.sortType : A bound value cannot be set.
[bisq.zip](https://github.com/bitsquare/bitsquare/files/1185935/bisq.zip) <-- Log file.
Steps to reproduce:
1. Click "Sell BTC"
1. Click the "Price in USD for 1 BTC" column header _twice_.

**Comment by ManfredKarrer** [comment]
Thanks for reporting. The bug is already fixed for the next release.
