### ISSUE TITLE
Add Expanse (EXP)

### ISSUE THREAD

**Issue by ilia2s** [bisq-network/bisq#896]
Please add an expanse coin. 

http://www.expanse.tech/

**Comment by ilia2s** [comment]
?

**Comment by ManfredKarrer** [comment]
See https://forum.bisq.io/t/how-to-add-your-favorite-altcoin/46

**Comment by ilia2s** [comment]
This information is not correct

**Comment by ManfredKarrer** [comment]
What you mean with not correct? That is the link to the requirements to add an altcoin.

**Comment by ilia2s** [comment]
There is no email address at the contact page
