### ISSUE TITLE
Possibly bad key verification for 64-bit Debian GNU/Linux version

### ISSUE THREAD

**Issue by kxcrl** [bisq-network/bisq#900]
Attempting to verify the 64-bit deb package resulted in the following:
```
➜  gpg --import F379A1C6.asc                                                      
gpg: key F379A1C6: public key "Manfred Karrer <manfred@bitsquare.io>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: no ultimately trusted keys found

➜  gpg --digest-algo SHA256 --verify Bisq-64bit-0.5.3.deb.asc Bisq-64bit-0.5.3.deb
gpg: Signature made Mon 17 Jul 2017 04:09:04 AM CDT using RSA key ID F379A1C6
gpg: BAD signature from "Manfred Karrer <manfred@bitsquare.io>"
```

It's probably also worth noting that the provided key URL (https://bisq.io/pubkey/F379A1C6.asc) currently seems to 404

Is there something that I'm missing or an alternative methodology that you were expecting to be used for this?

**Comment by cbeams** [comment]
@kxcrl, with the commit referenced above, the key is now back in place. Thanks for the heads up.

Regarding the verification failure itself, I'll let @ManfredKarrer weigh in.

**Comment by ManfredKarrer** [comment]
@kxcrl Maybe you have the old key which was expired. I uploaded the new key. If you use the one on Github it should be ok.

**Comment by kxcrl** [comment]
Wow, thanks so much for the rapid response @cbeams and @ManfredKarrer 

Just freshly grabbed all three files again (key asc from the previous link, which works now) and it all looks good:

```
➜  gpg --import F379A1C6.asc                                                      
gpg: key F379A1C6: "Manfred Karrer <manfred@bitsquare.io>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

➜  gpg --digest-algo SHA256 --verify Bisq-64bit-0.5.3.deb.asc Bisq-64bit-0.5.3.deb
gpg: Signature made Mon 17 Jul 2017 04:09:04 AM CDT using RSA key ID F379A1C6
gpg: Good signature from "Manfred Karrer <manfred@bitsquare.io>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 1DC3 C8C4 316A 698A C494  039C F5B8 4436 F379 A1C6
```

Thanks again!
