### ISSUE TITLE
Incorrect helping message on own tickets

### ISSUE THREAD

**Issue by ilia2s** [bisq-network/bisq#903]
Hello. For my own tickets in "sell BTC" tab it shows a same "take offer" message like for other tickets. Need to correct alternate message as "cancel your ticket".
![4444](https://user-images.githubusercontent.com/4389641/29147944-0dfdb15a-7d73-11e7-9b1a-a3e6c2aa919f.png)

**Comment by ManfredKarrer** [comment]
I cannot reproduce that in the Development branch.
