### ISSUE TITLE
Unable to compile issue544-api

### ISSUE THREAD

**Issue by ivanreif** [bisq-network/bisq#905]
[INFO] Reactor Summary:
[INFO] 
[INFO] parent ............................................ SUCCESS [0.340s]
[INFO] common ............................................ SUCCESS [31.803s]
[INFO] jsocks ............................................ SUCCESS [1.564s]
[INFO] jtorctl ........................................... SUCCESS [0.780s]
[INFO] jtorproxy ......................................... SUCCESS [5.826s]
[INFO] network ........................................... SUCCESS [6.490s]
[INFO] core .............................................. SUCCESS [14.528s]
[INFO] api ............................................... FAILURE [2.241s]
[INFO] gui ............................................... SKIPPED
[INFO] seednode .......................................... SKIPPED
[INFO] statistics ........................................ SKIPPED
[INFO] provider .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:03.877s
[INFO] Finished at: Tue Aug 15 21:58:43 CEST 2017
[INFO] Final Memory: 54M/797M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project api: Compilation failure: Compilation failure:
[ERROR] /Users//Projects/bitsquare/api/src/main/java/io/bisq/api/BisqProxy.java:[345,44] cannot find symbol
[ERROR] symbol:   method getTradeProtocol()
[ERROR] location: variable trade of type io.bisq.core.trade.Trade
[ERROR] /Users//Projects/bitsquare/api/src/main/java/io/bisq/api/BisqProxy.java:[363,44] cannot find symbol
[ERROR] symbol:   method getTradeProtocol()
[ERROR] location: variable trade of type io.bisq.core.trade.Trade
[ERROR] -> [Help 1]

**Comment by ManfredKarrer** [comment]
@mrosseel Can you have a look once you are back form holiday?

**Comment by ManfredKarrer** [comment]
@ivanreif Did you succeed?  @mrosseel was on holiday. If you still have problems he might be able to help.

**Comment by mrosseel** [comment]
@ivanreif let me know if I can help you any further - the latest version of the api branch compiles and can be found at: https://github.com/mrosseel/bisq-exchange/tree/issue544-api

PS: Due to a policy change branches are now hosted in personal repositories until they're merged to the Development branch using a Pull request.

**Comment by ivanreif** [comment]
@ManfredKarrer The proto error is gone now, but I'm still not able to compile.

Latest trace:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] parent ............................................. SUCCESS [  0.509 s]
[INFO] common ............................................. SUCCESS [03:19 min]
[INFO] jsocks ............................................. SUCCESS [  1.970 s]
[INFO] jtorctl ............................................ SUCCESS [  1.060 s]
[INFO] jtorproxy .......................................... SUCCESS [  5.220 s]
[INFO] network ............................................ SUCCESS [  8.108 s]
[INFO] core ............................................... SUCCESS [ 29.276 s]
[INFO] api ................................................ SUCCESS [ 28.481 s]
[INFO] gui ................................................ FAILURE [02:32 min]
[INFO] seednode ........................................... SKIPPED
[INFO] statistics ......................................... SKIPPED
[INFO] provider ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:08 min
[INFO] Finished at: 2017-09-20T09:17:19+00:00
[INFO] Final Memory: 40M/121M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce) on project gui: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce) on project gui: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
        at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:237)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more


You can also see it in github in your branch list, Travis is failing for API branch.

I will try with @mrosseel repo.

**Comment by mrosseel** [comment]
@ivanreif the mrosseel repo is the only one you should use, the other repo is deprecated.
Let me know if you need more help to compile it and what your plans are :)

**Comment by ivanreif** [comment]
@mrosseel Your repo doesn't work for me as well. Maybe you can help me out.

With your repo I'm stuck at:
[ERROR] /root/bisq-exchange/api/src/main/java/io/bisq/api/BisqProxy.java:[308,42] cannot find symbol
  symbol:   variable OfferUtil
  location: class io.bisq.api.BisqProxy
[ERROR] /root/bisq-exchange/api/src/main/java/io/bisq/api/BisqProxy.java:[309,18] cannot find symbol
  symbol:   variable OfferUtil
  location: class io.bisq.api.BisqProxy
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] parent ............................................. SUCCESS [  0.479 s]
[INFO] common ............................................. SUCCESS [03:23 min]
[INFO] jsocks ............................................. SUCCESS [  1.790 s]
[INFO] jtorctl ............................................ SUCCESS [  0.983 s]
[INFO] jtorproxy .......................................... SUCCESS [  6.573 s]
[INFO] network ............................................ SUCCESS [  7.663 s]
[INFO] core ............................................... SUCCESS [ 29.856 s]
[INFO] api ................................................ FAILURE [  2.756 s]
[INFO] gui ................................................ SKIPPED
[INFO] seednode ........................................... SKIPPED
[INFO] statistics ......................................... SKIPPED
[INFO] provider ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:14 min
[INFO] Finished at: 2017-09-20T09:33:14+00:00
[INFO] Final Memory: 49M/121M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project api: Compilation failure: Compilation failure:
[ERROR] /root/bisq-exchange/api/src/main/java/io/bisq/api/BisqProxy.java:[308,42] cannot find symbol
[ERROR] symbol:   variable OfferUtil
[ERROR] location: class io.bisq.api.BisqProxy
[ERROR] /root/bisq-exchange/api/src/main/java/io/bisq/api/BisqProxy.java:[309,18] cannot find symbol
[ERROR] symbol:   variable OfferUtil
[ERROR] location: class io.bisq.api.BisqProxy



p.s. I did a clean clone and clean install. I'm using linux.

**Comment by mrosseel** [comment]
@ivanreif  that's a mistake from my end, missing file, could you try again now?

**Comment by ivanreif** [comment]
Thanks! It compiles ok now. Next step is to run in in headless mode. Can I do that or shaded.jar in gui is the only option? I would like to have access to api only.

**Comment by mrosseel** [comment]
@ivanreif in theory headless should work but I haven't tested it in a while so not sure it works atm.

Could you tell what you're trying to do? This is beta quality software so please don't risk any real money without thorough testing! 

Just make sure you have an already configured config directory with the relevant fiat and crypto accounts all set up. Headless API can't be used to set those up, this has to be done in GUI. Once that's done, it should be runnable in headless mode, if it doesn't I'll fix it :)

**Comment by ivanreif** [comment]
I'm just trying to use API side of bisq. Let's say, to do some automated trading. Of course, I would run tests first. Could you just tell me how to run it headless and I'll close this issue. Thanks for you support so far.

**Comment by mrosseel** [comment]
@ivanreif automated trading is indeed the goal of the API's :). Don't forget that you can generate a client in the programming language of your choice using the http://localhost:8080/swagger.json definition file.

Just tested headless, it works.

To run headless, this is the main class: io.bisq.api.app.ApiMain
This are the program arguments I use to start it in regtest mode: --enableAPI true --baseCurrencyNetwork=BTC_REGTEST --bitcoinRegtestHost localhost --btcNodes localhost:18444 --nodePort 2003 --seedNodes=localhost:2225 --useLocalhost true --appName Bisq-Regtest-Bob  

PS: if you close this issue, feel free to stay in touch using IRC or slack, thx!

**Comment by ivanreif** [comment]
Thanks, will do.
