### ISSUE TITLE
Privacy enhancement request.

### ISSUE THREAD

**Issue by memetat** [bisq-network/bisq#909]
Hello,
Currently, if you trade fiat-btc and later btc-crypto trade with the same person/onion.address, the btc/crypto trade is not anonymous because of the prior trade, the other person knows who you are.

Work around is you can choose to not to transact with this person or launch another bisq instance, but this is inconvenient, due to the extra hassle & the low volume.

Not sure if this is on the radar to separate somehow to enhance privacy.

I hope i'm not imagining things, i think this was a case, i noticed this some time back, but forgot about it till now.

**Comment by ManfredKarrer** [comment]
It would require a change of the onion address. Such a feature is planned but not in the high-prio task list.

**Comment by ghost** [comment]
Yes this sounds like a great idea to increase privacy!

**Comment by freimair** [comment]
#1056 is again being worked on. stay tuned.
