### ISSUE TITLE
error when taking the offer

### ISSUE THREAD

**Issue by martaGonz** [bisq-network/bisq#913]
I was buying BTC, sent all the fees, and while waiting for the last confirmation I got this error and I don't see the offer of that user anymore:

An error occurred when taking the offer.

A timeout occurred.

The taker fee is already paid. In the worst case you have lost that fee. We are sorry about that but keep in mind it is a very small amount.
Please try to restart you application and check your network connection to see if you can resolve the issue.Please try to restart you application and check your network connection to see if you can resolve the issue.

**Comment by ManfredKarrer** [comment]
That can happen in rare cases (peers goes offline in a short time window or a bug on the makers side).
Do you remember which offer it was (currency, price, offer ID)?

**Comment by martaGonz** [comment]
Yes, maybe because the trade lasted too long while waiting the BTC deposit, 

EUR
BTC price = 3686.7814 EUR
Trade id vtsjj-9aa86ff4-aa52-4779-accc-0b93196fcf63-053

Error message: A timeout occurred

**Comment by martaGonz** [comment]
I tried to buy again  today to that same user and the same error happened, lost the small fee again so I can't repeat the process because I haven't enough funds again

**Comment by ManfredKarrer** [comment]
Oh sorry to hear that. I did not find the offer atm. I assume there is a bug on the peers side causing the issue.

**Comment by martaGonz** [comment]
i finally tried a third time with less amount and the offer was taken.  I made SEPA transfer so the money was in the user's account on the same day.  However he still didn't confirm the transaction.  In the meantime BTC is up 100 euro from the original trade price.  Is this a normal practice? If the price goes up, the seller just waits until the deadline ?  What would happen to the Euros that are already on his account? 
We are 2 people who bought on the same day to that same user.  Both made the SEPA transfer 3 days ago still waiting for confirmation.

**Comment by mrosseel** [comment]
the bitcoin is already in a multisig address, so if the trade times out the arbitrator can give the btc to you if you can prove the SEPA transfer. More probably the guy just hasn't checked his bank account yet.

**Comment by martaGonz** [comment]
thank you!

**Comment by WithoutWorries** [comment]
Just had this happen to me.. quite annoying
