### ISSUE TITLE
problems with maven trying to install bisq

### ISSUE THREAD

**Issue by bbrout** [bisq-network/bisq#915]
Using Ubuntu 16.04 and following instructions in ( https://github.com/bisq-network/bisq-exchange/blob/master/doc/build.md
)
_I have obtained the following:_

```
bruce@bruce-HP-620:~ $java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
bruce@bruce-HP-620:~$ cd bisq
bash: cd: bisq: No such file or directory
bruce@bruce-HP-620:~$ mkdir bisq
bruce@bruce-HP-620:~$ cd bisq
bruce@bruce-HP-620:~/bisq$ mvn clean package verify -DskipTests -Dmaven.javadoc.skip=true
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.225 s
[INFO] Finished at: 2017-09-03T15:03:03-06:00
[INFO] Final Memory: 7M/150M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/bruce/bisq). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
bruce@bruce-HP-620:~/bisq$ mvn -version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-93-generic", arch: "amd64", family: "unix"
```

I have also attempted to use the debian file to install; however it hangs forever with a waiting to install message on the unity icon.

I have also downloaded the source and attempted to build from there; however I run into file verification errors near the end of the build.

I have found this link:

[https://community.ubnt.com/t5/UniFi-Wireless/IMPORTANT-Debian-Ubuntu-users-MUST-READ-Updated-07-06-17/td-p/1968252](url)

which describes a problem with a kernel upgrade; however the suggestions do not seem to help.

Also, in file "install_on_unix.sh" in the source codes, there is a correction which must be made on line 63:

```
echo "Install and resolve dependencies for bisq"
cd ~
git clone -b DAO https://github.com/bitsquare/bitsquare.git
cd bisq

```
which gives the message that directory bisq does not exist.

Suggestions would be appreciated. Thank you.

**Comment by ManfredKarrer** [comment]
Why you check out the DAO branch? If you want to run Bisq from source use Master. The DAO branch is outdated. If you follow exactly the build.md file all should work correctly.

**Comment by bbrout** [comment]
I can see this branch is outdated. I have put in a number of corrections to the install shell. The deb file would not load so I tried a different debian installer and all is now working well. (So far). I used this branch since it was pointed to in the docs. Thanks for your help and comments. I don't know how to use master as opposed to  DAO.

**Comment by ManfredKarrer** [comment]
Where is it pointed to in the docs? To use master omit simply the -b flag at git clone.

**Comment by bbrout** [comment]
I am sorry for taking so long to get back. Thank you for your help. I cannot remember which docs or which link pointed me to the outdated branch. I managed to install the debian with GDebi Installer and it works fine.

**Comment by ManfredKarrer** [comment]
Ah good, then I will close the issue
