### ISSUE TITLE
website: download link for Arch Linux out of date

### ISSUE THREAD

**Issue by radfish** [bisq-network/bisq#917]
Downloads section on the website still links to bitsquare-git package on AUR. It should link to bisq package instead, since the other one is not being updated any longer.

Please change the linked package name, from bitsquare-git to bisq OR bisq-bin OR bisq-git. Actually, it might be good to link to all three packages. Some people prefer to use AUR packages that build from source, some want prebuilt (-bin) and some want bleeding edge (-git); it's standard convention in AUR land.

**Comment by Flugstein** [comment]
@radfish They updated the link to bisq-git, so I think you can close the issue.

**Comment by cbeams** [comment]
Closing as fixed. With the commit above (bisq-network/website@72b0572), the link now points to bisq-git vs bitsquare-git.
