### ISSUE TITLE
Error at creating transaction: org.bitcoinj.core.ECKey$KeyIsEncryptedException

### ISSUE THREAD

**Issue by mongcat** [bisq-network/bisq#918]
Sep-05 20:17:53.453 [JavaFX Application Thread] ERROR i.b.c.b.AddressEntryList: Key from addressEntry not found in that wallet AddressEntry{offerId='null', context=ARBITRATOR, address=null} 
Sep-05 20:17:53.455 [JavaFX Application Thread] ERROR i.b.c.b.AddressEntryList: Key from addressEntry not found in that wallet AddressEntry{offerId='null', context=AVAILABLE, address=null}

**Comment by mongcat** [comment]
Hi, I download the new Bisq app, restored my old Bitsquare account with seed and date, imported some bitcoins from an external wallet, now I can't send any Bitcoins and my password won't work (I got the error above). How can I export the bitcoins to an external wallet so I can restore my old wallet?
Any help gratefully received.

**Comment by ManfredKarrer** [comment]
You must not restore the wallet with the seed from the old wallet. We use a different wallet format in v 0.5 (BIP44). You need to send out the funds with a normal bitcoin transaction. I assume you have not offer/trades/disputes in the new app. If so remove the data directory and start over again with a fresh database and wallet. 

What do you mean with imported BTC from external wallet? Did you send it with a BTC transaction? 

The data directory is under:
Mac OSX: /Users/username/Library/Application Support/Bitsquare
Linux: /home/username/.local/share/Bitsquare
Windows 7,8: C:\Documents and Settings\username\AppData\Roaming\Bitsquare
Windows XP: C:\Documents and Settings\username\Application Data\Bitsquare

**Comment by mrosseel** [comment]
@mongcat if I understand you correctly, you had an old wallet with no bitcoin on it, restored it in the new app and then sent some bitcoin to it? 

In that case, don't delete the data directory ! 

Try to recover the bitcoin to an external wallet and only then delete the data dir and start again with a fresh database as @ManfredKarrer explains above.

**Comment by mongcat** [comment]
@mrosseel That's correct, I transferred some bitcoin to my Bisq wallet to use as deposit. When I tried to transfer a small amount to check the wallet was working I got the above error. My problem is I now have a faulty wallet with bitcoin that I can't transfer out and therefore can't delete data dir. @ManfredKarrer is there a work around?

**Comment by mrosseel** [comment]
can you try with these suggestions: https://forum.bisq.io/t/wallet-problems-what-to-do/1997

**Comment by mongcat** [comment]
@mrosseel I'm not sure that any of those solutions apply to my problem. I think the problem here lies in my restoring my old wallet into the new version of bisq. It allowed me to transfer the bitcoin in but won't allow me to transfer it out. Can you think of anything else

**Comment by mrosseel** [comment]
try the part where it says 'Wallet balance is not as expected'.
There are special commands which allow you to inspect your wallet, including recovery of the private keys used.

**Comment by ManfredKarrer** [comment]
You can open the wallet private key popup with alt+j. If wallet password is disabled you can see the private keys if you enable the checkbox. There you see also the transactions. Check out to whicha address/priv key you sent the funds. Import that private key in any other wallet and you should have accessible your funds. The funds from the old wallet will not be displayed because its a different wallet structure.

**Comment by mongcat** [comment]
@ManfredKarrer Could you give me an example of what I'm looking for. Thanks

**Comment by mrosseel** [comment]
Could you open the wallet with alt+j? If yes, you should search for the public address you sent the bitcoin to. If you can find that, enable the checkbox 'include private keys' and copy the private key belonging to the address you found. Let me know if that works. The step after that is importing the private key somewhere and sending the bitcoin out, but let's first get the private key.

**Comment by mongcat** [comment]
@mrosseel I've found the address, what does the private key look like? Thanks for your help btw

**Comment by mrosseel** [comment]
This is how it looks in my wallet (not a mainnet wallet, don't worry), you are looking for the data after priv HEX= or priv WIF=

    addr:n2s6ADMjPt53WygYH8W13vuChWY1W95fdg  
    hash160:ea2986a2b959ce626dd6c53c46fe29599ab717e8  (M/44H/0H/0H/0/0)
      DeterministicKey{pub 
    HEX=0367c189bcc2526f0aa0c75116faec34c1ce8f43aaa21aafbaec6bedd658f5bca4, priv 
    HEX=629ccfcb9e815423f117bfb4d059cc986d3xxxxxxxx, priv 
    WIF=cQtPfQRT7eRDjZmow3LCXSSzhV9ix5xxxxxxx, isEncrypted=false, 
    isPubKeyOnly=false}

**Comment by mongcat** [comment]
@mrosseel I can't find it in that format, I can only find it like this (I added some x's

>>> UNSPENT:
0.04191201 BTC total value (sends 0.00 BTC and receives 0.04191201 BTC)
  confidence: Appeared in best chain at height xxx523, depth x71. Source: NETWORK
  xxxxxxxxx62d82f776930d33db6f43997a9ddad7617b98ba478b31e45faf474f
  updated: 2017-09-04T19:05:46Z
  version 2
  time locked until block 483495 (estimated to be reached at 2017-09-03T23:07:09Z)
     in   PUSHDATA(71)[xxxxxxx075833e0102e89274c401704e2xxxx05dbadb754337735c23ea05b61e908939460220518d2294288214d277e9f4d8ec9065a46201b73961236390d6a3fcf319fd73d201] PUSHDATA(33)[xxxxxxa043e8ec65b7a7ad9071bd9d1bd94020c78c7a3ebe281dff61b4d1868f3b]

**Comment by mongcat** [comment]
@mrosseel Hi, I've managed to find the address, I was looking for the wrong thing. Problem is the key is encrypted. Any ideas?

**Comment by ManfredKarrer** [comment]
You need to remove the wallet password to see the priv keys.

Never post here any private keys!

**Comment by mrosseel** [comment]
on bitaddress.org in the 'wallet details' tab you can provide your encrypted private key and decrypt it I think (not sure encryption is the same), but Manfred's suggestion of removing the wallet password will be a lot easier.

**Comment by mongcat** [comment]
Thanks @ManfredKarrer and @mrosseel but I think I'm going to admit defeat. It appears that the wallet has created a password as when I try to add one it says 'Key chain already encrypted'. Also, bitaddress.org will give you a public key from a private key but not vice versa

**Comment by ManfredKarrer** [comment]
you need to go to account/wallet password and remove your password there. then alt+j with checked checkbox for displaying priv. keys. you can copy all out to a text editor. then go back to account/password and enable pw again. make a backup as well before - just in case

**Comment by ManfredKarrer** [comment]
Is the issue resolved? If so please close.
