### ISSUE TITLE
BuyerAsTakerSignAndPublishDepositTx

### ISSUE THREAD

**Issue by davibicudo** [bisq-network/bisq#920]
This error happened while I was trying to buy BTC. I lost the (not so negligible) amount of around 9 USD. It's not the most pleasant issue but still acceptable, if the bug is fixed. I hope you'll figure it out, I'm a big fan of bisq and am eager to see it's growth.
The maker's offer has disappeared after the issue. 

Log:
[log.txt](https://github.com/bisq-network/exchange/files/1280870/log.txt)

Message:
An error occurred when taking the offer.

An error occurred at task: BuyerAsTakerSignAndPublishDepositTx
Exception message: Maker's transaction output for the contract hash is not matching takers version.

The taker fee is already paid. In the worst case you have lost that fee. We are sorry about that but keep in mind it is a very small amount.
Please try to restart you application and check your network connection to see if you can resolve the issue.

**Comment by ManfredKarrer** [comment]
Thanks for reporting and your support! That is the first time I see that. The check if the contract hash is the same failed. That might be that the peer is running from source and manipulated the code (not assuming) or a bug on his side (never seen that before).

**Comment by davibicudo** [comment]
I'm the one who should thank you guys for the awesome platform! 
Hope you'll find out what's the problem! The maker has published his email in the contract so you could try to reach him to clear the first option out.

**Comment by ManfredKarrer** [comment]
Can you PM me his email?

**Comment by davibicudo** [comment]
Sure I could... But I don't know how to do this in Github. Could you tell me how or give me your email address?

**Comment by ManfredKarrer** [comment]
Ah sorry, had forum in mind.... just send me per email (manfred at bitsquare dot io)

**Comment by ManfredKarrer** [comment]
Found the issue by comparing the 2 json files. The offer was prob. created with an older version where the email field was added to payment accounts. So one json contains the email the other not. So its due a bug in the software not hanlding the change in 0.5.3 correctly. As it was the first case I assume there are hopefully not many other offers out there anymore.

**Comment by davibicudo** [comment]
Awesome! Great you were able to fix it quickly. Thanks!
