### ISSUE TITLE
spv chain

### ISSUE THREAD

**Issue by mrdock42** [bisq-network/bisq#922]
ive just created my second account and it wont load saying i need to delete a spv shain file thats corrupted

**Comment by mrdock42** [comment]
need any help

**Comment by ManfredKarrer** [comment]
What do you mean with second account? If you install Bisq on another computer the both apps are completely separate.
If you get an error message with a BlockStoreException then you need to delete the spv file and restart 2 times. The app might detect it and guides you through the process. It might take a while if your wallet was older. 
See https://forum.bisq.io/t/blockstoreexception-corrupted-spvchain-file/1689

**Comment by ManfredKarrer** [comment]
Is the issues resolved? If so please close.
