### ISSUE TITLE
Please add American Express Bluebird payment support

### ISSUE THREAD

**Issue by nycnikato** [bisq-network/bisq#925]
There are no chargebacks and no reversals when money is sent, Money can be held by mediator if necessary and sent back to the affected party.  There is an auditable paper trail. American Express can already be used to buy bitcon directly using Abra but this solution may be usable for those who don't want American Express knowing about Bitcoin purchases directly or those who want to have a prepaid option that is better and faster than a bank. This would take minimal effort to implement. money could be sent to an address controlled by mediator with a reference number attached.

**Comment by ManfredKarrer** [comment]
I moved your issue to the Forum:
https://forum.bisq.io/t/collecting-and-investigating-information-about-new-payment-methods/41/19

We try to keep GH issues for technical issues only, so I close here.
