### ISSUE TITLE
Please stop changing bisq github URL name all the time

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#934]
This has been changed a couple of times. Please choose a name and stick with it.

Also, the config folder under Ubuntu, was changed from bisq to Bisq.  ???

I really hope none of these change again.

**Comment by cbeams** [comment]
We do not expect further changes to the current GitHub organization and repository naming scheme.

With regard to the capitalization changes, please see the [0.5.3 release notes](https://github.com/bisq-network/exchange/releases/tag/v0.5.3)

Closing as addressed.
