### ISSUE TITLE
Error when buying BTC

### ISSUE THREAD

**Issue by neilstockbridge** [bisq-network/bisq#937]
I was buying BTC and an error occurred:

EDIT by Manfred Karrer: Removed logs

**Comment by ManfredKarrer** [comment]
Can you email me the full logs? (manfred at bitsquare dot io). I will remove the posted logs above.

**Comment by neilstockbridge** [comment]
Sure.  Is there anything sensitive in the logs, account numbers, etc.?

**Comment by ManfredKarrer** [comment]
No. But a path to Bisq data might be already something you don't want to share publicly... Better to be careful...

**Comment by neilstockbridge** [comment]
E-mailed with PGP.  What do you mean "a path to Bisq data"?  I didn't notice any path in what I posted originally.  Cheers!

**Comment by ManfredKarrer** [comment]
I have not looked so close. Maybe there was nothing. I have a habit to remove posted logs.

**Comment by ManfredKarrer** [comment]
Error happened here: Maker's transaction output for the contract hash is not matching takers version.
Might be that the peer has an older version. Can you send me the json (open trade details by click trade id, there is a button for json contract. Email me the json content. If it goes to a dispute (I assume) post the arbitrator (if not me) a link to that GH issue.  The arbitrator should request the json from the other peer as well so we can compare and see what caused the mismatch.

**Comment by ManfredKarrer** [comment]
@cbeams Ping me when you get that dispute.

**Comment by ManfredKarrer** [comment]
I assume trade ID is UZGPC.

**Comment by neilstockbridge** [comment]
Yes, UZGPC.

**Comment by neilstockbridge** [comment]
Was there any progress with this?  Also, the security deposit has not yet been refunded.  Cheers

**Comment by ManfredKarrer** [comment]
With the new version that bug should be fixed. Can u email me the details? Do you have a trade open or a take-offer attempt which failed (if take-offer no security deposit has left). best if you send me screenshots from tx list, open trades, failed trades.
