### ISSUE TITLE
Enhancement Request: Offers to be taken by multiple payment methods.

### ISSUE THREAD

**Issue by memetat** [bisq-network/bisq#941]
Can i suggest that offers to be able to be taken/fulfilled via multiple payment methods?
An offer with the option to be taken by National Bank Account (or multiple of these, yes there is a different account type for this if needed), OKPay or Money Order for example.

Currently you need to lock up BTC each time you create a separate offer to support each payment method to accept.  I can see this frustrating for sellers with the low volume on bisq currently.

With multiple payment methods attached to an offer, it gives better chance for the offer to be accepted by a peer and so better for bisq network overall.

Also, allowing to add and remove payment methods on the fly to an offer without closing the offer first would be a lot of flexibility to the users, but i assume this is not possible due to the nature of bisq?
What about if the payment methods are all defined/attached to the offer at offer creation time, and then the user can enable or disable the payment methods he wishes?

**Comment by ManfredKarrer** [comment]
I agree that this would be a good improvement but I fear the added complexity on many layers makes that unlikely to get implemented soon. Offer editing is on the road map as well but it is not that simple as well without losing the spam protection mechanism of the offer fee. If you have a concrete idea how to solve the please share.

**Comment by FingerCramp** [comment]
I'll second this request; Hopefully the ability to create an offer to accept more than one payment method is in the eventual timeline.  (I'm no too worried about editing a posted offer, personally).

Thanks, and LONG LIVE BISQ!
