### ISSUE TITLE
implement zeromq for new trades publishing

### ISSUE THREAD

**Issue by KanoczTomas** [bisq-network/bisq#943]
Hi,

this is a feature request to implement zeromq. It would be nice to subscribe to different zeromq events. It is easily implemented on the server side (you already have to update new trades once they come in, so as well might publish an event to zeromq).

The event can be used e.g. for trade notifications. A user would be able to listen to events from 0mq and filter on the amount for example, send an email in case there is an order to take, etc. All that could be left for the user or modules/plugins ecosystem to implement. Increasing the use cases this way. 

It would be a simple and elegant way to expose internal state to outside world, compared to the prepared API it is very lightweight and realtime in nature. I think it would be very beneficial to have it, the costs are almost zero for the server.

Bitcoind has a similar zeromq implementation, it is very lightweight on the server, but offers powerful features for the queue receiver.

**Comment by mrosseel** [comment]
As an addition to the http api, zeromq is certainly something to consider! 
Can I ask what your personal use case would be for this?

**Comment by KanoczTomas** [comment]
I am working with zeromq and bitcoind to make a webfrontend for bitcoin, so it inspired my request, as I heard you guys are working on the API and this is very easy to implement with it. 

A use case comes to my mind ...

A real time notification for trades that interests me (e.g. low volume trades that are rare). Bisq could run headlessly on a raspberry pi system and simply send me a push notification to my android to make me aware of it. Then I could fire up bisq on my pc to do the trade. One could easily do some fancy stats as well, like number of trades per minute and so on ... (not sure if collecting those is possible now). Having the app as a standalone entity is nice, but with this you could open up a whole new world for some plugins and stuff like that.

**Comment by KanoczTomas** [comment]
oh another thing, e.g. creating a website to at least monitor the bisq trade volumes (might be of interest for a lot of people) would be very easy with zeromq + the api. Long polling could be used for realtime updates and the api for the state initialisation.

**Comment by mrosseel** [comment]
Thanks for your input. Zeromq is nicer, but there are already tradestatistics objects which can be dumped to json.
This is used in this site to show trade volumes: https://market.bisq.io/
