### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by kdaye** [bisq-network/bisq#945]
https://www.transifex.com/bitsquare/bitsquare
@ManfredKarrer  please let it be a part of master.I have done it and tested.Thanks!

and Chinese people, please inform If there are something need to modify.

**Comment by ManfredKarrer** [comment]
@kdaye Thanks a lot! 
@riclas Could you make PR to Development branch?

**Comment by kdaye** [comment]
@ManfredKarrer Nice application, I hope it applied to the Chinese language world.that is the motivation for me to translate it. there are not exchange in China since the month . perhaps Bisq will be the market.

**Comment by ManfredKarrer** [comment]
@kdaye Yes definitely. Although there are still work on other areas to be done (Tor pluggable transports)... 
Do you think that most chinese BCT traders understand English good enough that they can communicate in a dispute with the arbitrator in english?

**Comment by kdaye** [comment]
@ManfredKarrer Oh,No! the BCT traders(80%) can't speak English , So they can not communicate in a dispute with the arbitrator in English . if English only,I think they will asking for help with Community(QQ, Wechat etc.) in Chinese.and then someone help them. to write the message to arbitrator... 
that is problem.

**Comment by kdaye** [comment]
When I introduced Bisq in the community( huobi.com's group talk 3000 people), they were in trouble with the English interface. So I think 80% of people do not speak English.

**Comment by ManfredKarrer** [comment]
As soon the full DAO is in place we will also have an open decentrl. arbitration system, then chinese people can become arbitrators. But that will still take a bit...

**Comment by kdaye** [comment]
great,there are also need time to Let people knows Bisq.

**Comment by ManfredKarrer** [comment]
Yes community building and support would be needed as well. if you are interested to be part of that please stay in touch!

**Comment by kdaye** [comment]
sure,I am writing an introduction about Bisq in Chinese. post it to somewhere ,where likes bitcointalk in china.

**Comment by kdaye** [comment]
@ManfredKarrer 
Hi,
When I edit the file 
https://github.com/bisq-network/exchange/blob/11c5c92879d2dce163920d5051622497a8f9ba22/common/src/main/java/io/bisq/common/locale/LanguageUtil.java#L34-L38
like
```
    private static final List<String> userLanguageCodes = Arrays.asList(
            "en", // English
            "de", // German
            "el", // Greek
            "es", // Spanish
            "pt", // Portuguese / Brazil
            "sr", // Serbian
            "zh" // Chinese
```


it is not working with the file named `displayStrings_zh_cn.properties`
and working good when I rename it to `displayStrings_zh.properties`.

file location:
` exchange/common/src/main/resources/i18n/displayStrings_zh_cn.properties `

OR
I add `"zh_cn" // Chinese` ,there are not display `中文`(Chinese) in the screen of settings .
there will display `zh_cn`

**Comment by ManfredKarrer** [comment]
Yes keep the country token away. so "zh in both places should be ok.
