### ISSUE TITLE
Timeout when buying a bitcoin

### ISSUE THREAD

**Issue by eljobe** [bisq-network/bisq#956]
This is a very bad experience for a first-time buyer on Bisq. 👎 

An error occurred when taking the offer.

A timeout occurred.

The taker fee is already paid. In the worst case you have lost that fee. We are sorry about that but keep in mind it is a very small amount.
Please try to restart you application and check your network connection to see if you can resolve the issue.Please try to restart you application and check your network connection to see if you can resolve the issue.
[bisq.log](https://github.com/bisq-network/exchange/files/1362298/bisq.log)

**Comment by cbeams** [comment]
Hey @eljobe, that sucks. Thanks for reporting it. This is rare, but it can happen when a specific timing problem occurs, e.g. the offerer goes offline at just the wrong time while you're trying to take their offer. Do you know the ID of the trade you were trying to take? Or the currency and price?

**Comment by eljobe** [comment]
Offer ID: kVFmGMbB-0b272846-f79d-4b3b-a0df-1b18262133a2-053

I see that someone else had the same problem with the same or very similar offer about 8 hours ago:
https://github.com/bisq-network/exchange/issues/955

**Comment by eljobe** [comment]
Also, I'm betting that the two of us are not the only ones attempting to take that offer right now. It's well-below market value. But, maybe there is something corrupt on the client in more than a rare or one-off way?

**Comment by eljobe** [comment]
Wait, were you looking for the Offer ID (from the UI), or the Trade ID (from the attached bisq.log)?
The later is: GL5HJW-32465189-71c0-4883-b628-ca1caf1662ed-053

**Comment by eljobe** [comment]
Wait, ignore: kVFmGMbB-0b272846-f79d-4b3b-a0df-1b18262133a2-053 entirely. I was in the wrong tab in the Bisq UI. The one from the log is correct: GL5HJW-32465189-71c0-4883-b628-ca1caf1662ed-053 I was looking at the "History" tab where I canceled an offer in the past.

**Comment by cbeams** [comment]
Thanks. I'm unable to dig into this further right now (preparing to give a talk about Bisq right now in Prague!), but @ManfredKarrer may be able to look into it when he gets online. There is a way to blacklist an offer (for reasons exactly like this one) so that no one else bumps into whatever bug this is.

**Comment by eljobe** [comment]
Also, I feel like I should report that when the user perceives that the software has malfunctioned, telling them that the taker fee that they just lost is a "very small amount" when it is about the equivalent of 8 USD, sends the wrong message. It would be a small amount as a percentage of the transaction which was supposed to occur, but it's infinity percent larger than the actual value provided by using the exchange.

All that said, I know that working with a technology that is still under development and really trying to transform how exchanges are run comes with some risk. And I'm not terribly broken up over the loss of 0.0018 BTC. But, still, it looks bad.

**Comment by ManfredKarrer** [comment]
Hi @eljobe, sorry for the late reply....

The text with the "small amount" was from the pre-0.5 version where the trade fee was really super low. Now the trade fee cannot be considered a very small amount, so I will remove that part.

I just added an issue [1] describing the problem. I am not sure if I can work on that soon but will try to look into it before the next release.
If anyone else want to investigate that would be great. Though it might be a difficult task for devs who are not very familiar with the trade protocol and the P2P network.

If anyone has an alternative solution how to mitigate that please let me know. 

[1] https://github.com/bisq-network/exchange/issues/962

**Comment by eljobe** [comment]
I'm happy to close this issue and follow along on #962.
