### ISSUE TITLE
Loss of trade fee in take offer fee process 

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#962]
There are some reports that the take-offer attempt fails after the taker's trade fee has been paid.

There is a conceptually based tiny time window where that can happen. The protocol or taking an offer includes a few messages sent between the peers and before the deposit transaction is created the taker need to pay the trade fee. It is possible that just after that moment the network connection of one of the peers breaks and therefore the deposit tx will not get created, leading to a failed trade where the offer is removed and the takers trade fee paid.  
This should be very rare is the message exchange is fast and the time window very short.

The trade fee payment need to be done before the deposit tx.
Using RBF or a time locked tx does not work because it would render the following deposit tx which uses the output from the trade fee tx invalid and would introduce therefore a security problem. 

It seems that there is some additional reason which can cause such cases because we get more often as expected that problem reported.

It is hard to reproduce but would require some deeper analysis if the protocol steps to see if there is any weak area which can cause that problem.

**Comment by eljobe** [comment]
I noticed, when filing #956, that the offerer of the bitcoin sale did not show up in the network settings "connected peers" list by visual comparison of the onion addresses of the connected peers and the user making the offer. Is it possible that, in this situation, the trade fee transaction is made without hope of the deposit transaction succeeding (because the depositing peer is no longer connected?)

Sorry to be an armchair theorist. I have not looked at the protocol thoroughly enough to know if I'm even making sense.

**Comment by ManfredKarrer** [comment]
When you take and offer by clicking the "take offer" button you start a direct connection to the peer so you have to see the connection in the settings/network list and it must be marked as "direct". 

At take-offer-screen opening you ask the peer if the offer is still available if not you get already a popup with info and preventing you to continue.
Then once you click the final "take offer" button in the confirm screen you ask the peer again if the offer is still available and only then the real take-offer protocol starts.

In that trade protocol [1], [2] at one step you create the take offer fee and then send it to the peer. Only after that the peers exchange the trade data (payment account data). That is done to make data harvesting expensive (only after fee payment is done you get the peers account data). The maker also creates and signs the deposit tx for his part of the inputs. So the error happens in that short period between the trade fee is paid and the half signed deposit tx is sent. It is usually less then 1 second depending on Tor speed (usual Tor RRT is 100-300 ms). The code on the java side should not take any considerable time (a few ms). 

The maker only removes the offer after the deposit tx is visible in the network, so if the deposit tx is not published his offer stays alive. That explains why we don't get reports from makers of lost offers. The taker though removes the offer locally when taking it and he will only see the offer again after the next republishing (after a few minutes).

For the Buyer as maker it might be that one of the tasks listed at the BuyerAsMakerProtocol.handleTakeOfferRequest() method fails. If so the peer will never get a reply and his timeout get triggered. The takers log will not reveal why the makers trade process failed. 
To send an error message to the peer would be an improvement to find out what was going wrong, but of course every message send might fail in itself....

In the past there have been cases with backward compatibility issues which have caused such case, specially when it continued to fail with the same offer. I could contact the maker and found out from their log what was going wrong. 
So if anyone gets that error it would help a lot if I get the offer details (price, currency, ID,...) so I can try it myself and if failed again I can send the peer a direct message to get in touch with me.


Those docs are outdated and not exact with the current implementation but it gives an overview about the trade protocol flow. The protocol is slightly different of maker is buyer or seller.
[1] https://docs.google.com/spreadsheets/d/1U4tJh4MRAMGGs5qieIVZ00b1KyKJKa1ZH85aI-8T7us/edit?usp=drive_web
[2] https://docs.google.com/spreadsheets/d/1hSD4Wixe-xHYT9COXba4fpRbYZhq28tp_F5nxbpljm0/edit#gid=0

The classes implementing the trade protocol are:
BuyerAsMakerProtocol.java
BuyerAsTakerProtocol.java
SellerAsMakerProtocol.java
SellerAsTakerProtocol.java

**Comment by ripcurlx** [comment]
@ManfredKarrer Is this issue still relevant as it was filed such a long time ago?

**Comment by ManfredKarrer** [comment]
I think it can be closed.
