### ISSUE TITLE
Make torrc file editable

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#965]
Some people want to edit the torrc file to add proxies. The file gets replaced at each startup and local path is written to it. The handling of that is questionable and subject for improvement, but it would be better to invest the effort in the new Tor library instead to modify the existing.

An alternative approach would be to let the user append entries to the torrc file via a program argument. 

Easiest way would be to add a list of optional key/value pairs to OnionProxyManager.installAndConfigureFiles(). The list get passed there and is fed by a new prog argument.

See also: 
https://github.com/bisq-network/exchange/issues/829
https://github.com/bisq-network/exchange/issues/483
https://github.com/bisq-network/exchange/issues/413

**Comment by ManfredKarrer** [comment]
@JesusMcCloud has added support for that:
 https://github.com/JesusMcCloud/netlayer/issues/4

**Comment by AcThPaU** [comment]
as for BISQ 1.9.22, the torrc still gets overwritten
