### ISSUE TITLE
I cannot close the window alert

### ISSUE THREAD

**Issue by diegotco** [bisq-network/bisq#969]
![2017-10-13_0838](https://user-images.githubusercontent.com/22822405/31548872-a9d9064c-b02c-11e7-9fe8-e951f716f170.png)

**Comment by ManfredKarrer** [comment]
Could you reproduce that after a restart? Never saw that. I assume another bug (some hidden exception) has caused that.

**Comment by diegotco** [comment]
![2017-10-13_0924](https://user-images.githubusercontent.com/22822405/31550943-47992190-b033-11e7-986e-691fe5aa6069.png)

**Comment by ManfredKarrer** [comment]
Ah ok, thanks. It might be that the combo box which is technically also a popup screwed up the other popup. But the other one should only open when you click a link. Will try if I can reproduce it.
