### ISSUE TITLE
Feature: Coinmarketcap integration under 'Market' tab

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#972]
This would display a list of all coins that the user favorites or "stars".
Most importantly it would show a graph/chart of any coin the user wishes to click on, that will show the timeline of this for eg.
https://coinmarketcap.com/currencies/bitcoin/
1d - 7d - 1m - 3m - 1y - YTD - ALL

What do you think?

**Comment by ManfredKarrer** [comment]
@dan-da ping

**Comment by dan-da** [comment]
I have several reservations.

1. From the description I don't really understand exactly how this feature would work/look or its value to the user.  Perhaps a mockup or two would help, and also one or two use-case descriptions.

2. The markets tab/app is about displaying Bisq market data.  Coinmarketcap is an average across many exchanges.  So this would be mixing data sources, and potentially confusing.

3. markets tab displays data from a decentralized data source.  Displaying coinmarketcap would mean introducing a centralized data source.  That seems to go against ethos of the project.

4. markets tab displays public data, not personalized data.  This request implies adding personalization features, at the very least a cookie or local data store for the favorites.  I'm not keen to start down that road.

**Comment by ghost** [comment]
@dan-da 

1.  Basically it would have a tab under markets tab called "Coinmaketcap", Under that it would have 2 tabs, eg. Altcoins, and Favorites.  Unless you want to make it a separate tab from "Markets" all together.
Under Altcoins/favorites:
- You could see BTC and other altcoins and their prices next to them from Coinmarketcap.
- You could click on BTC for eg. and be able to view the graph exactly like it is on Coinmarketcap so the user can choose to see the timeline of that coin.

Id suggest only those 2 features for now..since i deem them more important

2. Coinmarketcap integration in bisq would be for the user that wants to compare that average across **all** exchanges and to have an easy view of all different cryptocoins and their history, i have many times come across going to coinmarketcap myself just to check some other coins, and then going back to bisq to see if that coin is supported and how popular it is..etc.

3. Just **viewing** centralized data and not interacting with centralized data doesnt really change the ethos of the project. 

4.  If thats the case, then this could prove a bit difficult so i dont know.  But it was just an idea that could make it easier for the user to choose the coins his interested in..instead of seeing centralized coins all the time like XRP.  **Unless**, we could choose all the complete decentralized coins that are in use and traded with on bisq and put those in there only, instead of useless ones.

What do you think?
