### ISSUE TITLE
Tor exited with value 127

### ISSUE THREAD

**Issue by introlinux** [bisq-network/bisq#974]
I'm testing 32bit version, the splash appears, but after some minutes it always complains with the message:

> Warning
> The application could not startup after 4 minutes.
> Yout still did not get connected to the bitcoin network.
> If you use Tor for Bitcoin it might be that you got an unstable Tor circuit.
> You can wait longer o try to restart.
> 

And in the terminal I can see in red text this:

> Oct-16 23:14:56.335 [TorNetworkNode:CreateTorNode-6353] WARN  c.m.t.t.OnionProxyManager: Tor exited with value 127 
> Oct-16 23:14:56.339 [eatInputStream] ERROR c.m.t.t.OnionProxyManager: /home/minino/.local/share/Bisq/btc_mainnet/tor/tor: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory 
> Oct-16 23:14:56.341 [JavaFX Application Thread] ERROR i.b.n.p.n.TorNetworkNode: TorNode creation failed with exception: Could not Start Tor. 
> O
> 

I have libz.so.1 in my system and if I copy it in the folder ~/.local/share/Bisq/btc_mainnet/tor, it complains that it is a 32bit library O_O?
It is curious that if I do ldd tor appear dependencies of 64bit libraries:

> ~/.local/share/Bisq/btc_mainnet/tor$ ldd tor
> 	linux-vdso.so.1 (0x00007ffda6ed2000)
> 	libz.so.1 => not found
> 	libm.so.6 => /lib64/libm.so.6 (0x00007f6eb8467000)
> 	libevent-2.0.so.5 => not found
> 	libssl.so.1.0.0 => not found
> 	libcrypto.so.1.0.0 => not found
> 	librt.so.1 => /lib64/librt.so.1 (0x00007f6eb825e000)
> 	libdl.so.2 => /lib64/libdl.so.2 (0x00007f6eb805a000)
> 	libc.so.6 => /lib64/libc.so.6 (0x00007f6eb7cae000)
> 	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6eb7a91000)
> 	/lib64/ld-linux-x86-64.so.2 (0x0000559db7ece000)

I'm in stable Debian but with Java8 installed.

**Comment by ManfredKarrer** [comment]
Hm. strange... Can you try to run from source with following exactly the instructions in build.md?

**Comment by introlinux** [comment]
False alarm, sorry. I forgot last month I compiled a 64bit kernel in my 32bit system and that's the problem. When I realised, I booted from a 32bit kernel and all is ok now.

Sorry for the inconvenience.

**Comment by cbeams** [comment]
No problem, thanks for following up!
