### ISSUE TITLE
Upgrade to BitcoinJ 0.12

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#98]
BitcoinJ [0.12 will be released soon](https://groups.google.com/d/msg/bitcoinj/OlMq6pg2ucQ/ualBZyJnub4J). Let's update to it when it does.

Note that this will require more than a simple change to dependency metadata. BitcoinJ has been repackaged from `com.google` => `org.bitcoinj`, so we'll have some search and replace work to do at the very least.

**Comment by cbeams** [comment]
Manfred, note that I've updated the title and description to reflect the news that 0.12 will be out soon.

**Comment by cbeams** [comment]
Manfred, #104 is ready to merge. Do you have any issue with me doing that now?

**Comment by ManfredKarrer** [comment]
Yeah lets do the merge. I have to leave soon for an appointment so would be nice if you can do it yourself...

**Comment by cbeams** [comment]
No problem. Just wanted to make sure you're aware of this. Will do shortly.
