### ISSUE TITLE
An error occurred when taking the offer.

### ISSUE THREAD

**Issue by neberg99** [bisq-network/bisq#981]
Got an error popup saying An error occurred when taking the offer.

A timeout occurred. 

A taker fee is already paid. In the worst case you have lost that fee. etc etc

Log files::

Oct-22 17:04:47.432 [JavaFX Application Thread] INFO  i.b.c.t.TaskRunner: Run task: BuyerAsTakerCreatesDepositTxInputs 
Oct-22 17:04:47.433 [JavaFX Application Thread] INFO  i.b.c.b.w.TradeWalletService: print tx before wallet.completeTx:   a7b49ecd619619ccd0834a277311420383aaed65db17d077c649a0120ef0b88e
  INCOMPLETE: No inputs!
 
Oct-22 17:04:47.433 [JavaFX Application Thread] INFO  o.b.w.Wallet: Completing send tx with 1 outputs totalling 0.03024 BTC and a fee of 0.00 BTC/kB 
Oct-22 17:04:47.437 [JavaFX Application Thread] INFO  o.b.w.Wallet:   with a fee of 0.00125654 BTC/kB, 0.00024 BTC for 191 bytes 
Oct-22 17:04:47.437 [JavaFX Application Thread] INFO  o.b.w.Wallet:   completed:   6977b007e6490e6e032507407b85a97c909f6e4216da821220ce36e430aeb8e6
     in   PUSHDATA(71)[304402205fe897b5d30480763fb1a2a81f9aa06ba2824281a801aa805d49a4c5891c30ae02207eb871071c259589ebd2de57b1fc521c8ba3e8aaa644d4a0f777674902df78d901] PUSHDATA(33)[02b0c078b16fd2182d2e0d89080d89b713635b8e86f7ff13f9762c8fc5a4a1b345] 0.03048 BTC (3048000)
          outpoint:922059b93df440a2f5852a65221c24e1694f1b22b153ddae62e7f38fccff187b:1 hash160:978d3ea0bd8326fd49b1e590438eb53575c02bf7
     out  DUP HASH160 PUSHDATA(20)[519d022dd06ed1a9081180ff5b5733625e1c7bd1] EQUALVERIFY CHECKSIG 0.03024 BTC (3024000) ScriptPubKey: 76a914519d022dd06ed1a9081180ff5b5733625e1c7bd188ac Address:18SXpgVYMft91joFPCHWpwAg8N8wsfhxMJ 
     fee  0.00024 BTC for 191 bytes (125 Satoshi/Byte)
     prps USER_PAYMENT
 
Oct-22 17:04:47.438 [JavaFX Application Thread] INFO  i.b.c.t.TaskRunner: Run task: TakerSendPayDepositRequest 
Oct-22 17:06:36.666 [JavaFX Application Thread] ERROR i.b.c.t.p.TradeProtocol: Timeout reached. TradeID=85567791-9ab837cc-db35-4bfb-a2aa-32fdd68c2fd9-053, state=TAKER_PUBLISHED_TAKER_FEE_TX 
Oct-22 17:06:36.697 [JavaFX Application Thread] WARN  i.b.c.t.p.TradeProtocol: cleanupTradableOnFault tradeState=TAKER_PUBLISHED_TAKER_FEE_TX 
Oct-22 17:06:36.699 [JavaFX Application Thread] WARN  i.b.c.t.TradeManager: We found an outdated addressEntry for trade 85567791-9ab837cc-db35-4bfb-a2aa-32fdd68c2fd9-053 
Oct-22 17:06:36.699 [JavaFX Application Thread] INFO  i.b.c.b.w.BtcWalletService: swap addressEntry with address 1N2FZ6D7LB6bHoJHKT3voG7TbnU6vSoMAW and offerId 85567791-9ab837cc-db35-4bfb-a2aa-32fdd68c2fd9-053 from context MULTI_SIG to available 
Oct-22 17:06:36.700 [JavaFX Application Thread] WARN  i.b.c.t.TradeManager: We found an outdated addressEntry for trade 85567791-9ab837cc-db35-4bfb-a2aa-32fdd68c2fd9-053 
Oct-22 17:07:38.972 [JavaFX Application Thread] INFO  i.b.c.b.w.BtcWalletService: swap addressEntry with address 1EpLEpLAmjXmqcdTnbzwaajX5GRGFjYAYj and offerId 85567791-9ab837cc-db35-4bfb-a2aa-32fdd68c2fd9-053 from context RESERVED_FOR_TRADE to available 
Oct-22 17:08:20.554 [JavaFX Application Thread] INFO  i.b.g.a.BisqApp: System load: Memory (MB)): 262 / No. of threads: 50

**Comment by ManfredKarrer** [comment]
Seems at the makers side there was some exception which caused that the maker did not respond anymore. I assume it is related to other bug reports with mismatching contract data.

**Comment by neberg99** [comment]
Ok, thanks. Its happened 6 times now... from a couple of different contracts, usually happens the first time second time the offer goes through but this last one has happened 4 times while I was trying to take an offer. Let me know how it goes, going to stop using it until thats fixed, I keep losing cash. If you want my logs for all the rest, let me know.

**Comment by ManfredKarrer** [comment]
oh sorry to hear that. thats strange. do u have very unstable/slow internet? yes please send me the logs (manfred at bitsquare dot io).
