### ISSUE TITLE
Refine test/dev mode

### ISSUE THREAD

**Issue by Nolaan** [bisq-network/bisq#988]
It would be benefitial to name the --appDataDir or --userDataDir options for the test mode so one doesn't override his/her instance of Bisq.
https://github.com/bisq-network/exchange/wiki/How-to-use-Bitsquare-with-regtest-(advanced)

**Comment by ManfredKarrer** [comment]
Inside the data dir is a BTC network dir (e.g. btc_mainnet), so you would not interfere with your mainnet Bisq data. 
I recommend to use --appName=bisq-Alice and --appName=bisq-Bob as 2 instances to test a trade scenario. The data dir will be named according to the --appName.
